In [1]:
import os
import sys
import io
import logging
import requests
import zipfile
import xml.etree.ElementTree as ET
from typing import Optional, Dict, List
from pathlib import Path
import pandas as pd
import datetime as dt
import pymysql
import FinanceDataReader as fdr

# ---------------------------------------------------------
# 기본 로깅 설정
# ---------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)
logger = logging.getLogger(__name__)


# ---------------------------------------------------------
# 0) 프로젝트 루트 자동 탐색 (DATA 폴더 기준)
# ---------------------------------------------------------
def add_repo_path():
    """프로젝트 루트를 자동 탐색하여 sys.path에 추가"""
    if '__file__' in globals():
        current = Path(__file__).resolve().parent
    else:
        current = Path.cwd()

    for parent in [current] + list(current.parents):
        if (parent / "DATA").exists():
            if str(parent) not in sys.path:
                sys.path.insert(0, str(parent))
            logger.info(f"Project root added: {parent}")
            return str(parent)

    fallback = r"C:\Users\Hoyoung_Park\PyCharmMiscProject\stock_forecast"
    if os.path.isdir(fallback):
        if fallback not in sys.path:
            sys.path.insert(0, fallback)
        logger.warning(f"Using fallback path: {fallback}")
        return fallback

    raise FileNotFoundError("DATA 폴더를 찾을 수 없습니다.")


try:
    project_root = add_repo_path()
    from DATA.stock_invest_function import get_db_host
except ImportError:
    logger.warning("stock_invest_function import 실패 - DB 정보를 직접 설정해야 합니다")


# ---------------------------------------------------------
# 1) corp_code 목록 불러오기 (DART corpCode.xml)
# ---------------------------------------------------------
def load_corp_code(api_key: str) -> pd.DataFrame:
    """
    DART에서 corpCode.zip을 내려받아
    corp_code, corp_name, stock_code 정보를 DataFrame으로 반환.
    """
    url = "https://opendart.fss.or.kr/api/corpCode.xml"
    params = {"crtfc_key": api_key}
    r = requests.get(url, params=params)
    r.raise_for_status()

    content_type = (r.headers.get("Content-Type") or "").lower()
    head_bytes = r.content[:4]  # ZIP 여부 판별용 (b'PK\\x03\\x04')

    # 1) 에러(XML) 응답인지 먼저 체크
    if ("xml" in content_type or "text" in content_type) and not head_bytes.startswith(b"PK"):
        try:
            root = ET.fromstring(r.text)
            status = root.findtext("status")
            message = root.findtext("message")
            if status != "000":
                raise RuntimeError(
                    f"[DART corpCode 오류] status={status}, message={message}"
                )
        except ET.ParseError:
            raise RuntimeError(
                f"[DART corpCode 오류] XML 파싱 실패. "
                f"Content-Type={content_type}, text={r.text[:200]}"
            )

    # 2) 정상: ZIP 파일 처리
    with zipfile.ZipFile(io.BytesIO(r.content)) as z:
        xml_name = None
        for name in z.namelist():
            if name.lower().endswith(".xml"):
                xml_name = name
                break

        if xml_name is None:
            raise RuntimeError(
                f"[DART corpCode 오류] ZIP 안에 XML 파일이 없습니다. files={z.namelist()}"
            )

        with z.open(xml_name) as xml_file:
            tree = ET.parse(xml_file)
            root = tree.getroot()

    # 3) XML → DataFrame 변환
    rows = []
    for child in root.findall("list"):
        corp_code = child.findtext("corp_code")
        corp_name = child.findtext("corp_name")
        stock_code = child.findtext("stock_code")
        rows.append(
            {
                "corp_code": corp_code,
                "corp_name": corp_name,
                "stock_code": stock_code,
            }
        )

    df = pd.DataFrame(rows)
    df = df[df["stock_code"].notnull() & (df["stock_code"] != "")]
    df.reset_index(drop=True, inplace=True)
    return df


# ---------------------------------------------------------
# 2) FinanceDataReader 종목 코드로 corp_code 찾기
# ---------------------------------------------------------
def get_corp_info(corp_df: pd.DataFrame, stock_code: str) -> Optional[Dict]:
    """
    FinanceDataReader 형식의 종목코드(예: '005930')로
    corp_df에서 해당 기업의 corp_code, corp_name, stock_code 를 찾아 dict로 반환.
    """
    row = corp_df.loc[corp_df["stock_code"] == stock_code]
    if row.empty:
        return None

    row = row.iloc[0]
    return {
        "corp_code": row["corp_code"],
        "corp_name": row["corp_name"],
        "stock_code": row["stock_code"],
    }

def test_db_connection(db_info: dict) -> bool:
    """
    MariaDB 연결 테스트 함수.
    연결 성공하면 True, 실패하면 False 반환.
    """
    try:
        conn = pymysql.connect(
            host=db_info["host"],
            port=db_info["port"],
            user=db_info["user"],
            password=db_info["password"],
            database=db_info["database"],
            charset="utf8mb4",
            connect_timeout=5
        )
        conn.close()
        logger.info("DB 연결 성공")
        return True
    except Exception as e:
        logger.error(f"DB 연결 실패: {e}")
        return False



# ---------------------------------------------------------
# 3) 분기별 재무제표 수신 (fnlttSinglAcntAll)
#    - 먼저 CFS 시도, 없으면 OFS로 fallback
# ---------------------------------------------------------
def get_dart_fs_quarterly(api_key: str,
                          corp_code: str,
                          start_year: int,
                          end_year: int) -> pd.DataFrame:
    """
    DART 'fnlttSinglAcntAll' API를 사용하여 분기별 재무제표 수집.
    먼저 CFS(연결) 시도 → 자료 없으면 OFS(개별)로 자동 fallback.
    """

    def fetch_one_year(api_key, corp_code, year, fs_div):
        """특정 연도·fs_div로 조회하는 내부 함수"""
        url = "https://opendart.fss.or.kr/api/fnlttSinglAcntAll.json"
        reprt_map = {
            "11013": ("Q1", "-03-31"),
            "11012": ("H1", "-06-30"),
            "11014": ("Q3", "-09-30"),
            "11011": ("FY", "-12-31"),
        }

        rows: List[Dict] = []

        for reprt_code, (quarter_label, date_suffix) in reprt_map.items():
            params = {
                "crtfc_key": api_key,
                "corp_code": corp_code,
                "bsns_year": str(year),
                "reprt_code": reprt_code,
                "fs_div": fs_div,
            }

            r = requests.get(url, params=params)
            r.raise_for_status()
            data = r.json()

            if data.get("status") != "000":
                continue   # 자료 없음 → 다음 보고서

            for item in data.get("list", []):
                row = {
                    "corp_code": item.get("corp_code"),
                    "bsns_year": int(item.get("bsns_year")),
                    "reprt_code": item.get("reprt_code"),
                    "sj_div": item.get("sj_div"),
                    "sj_nm": item.get("sj_nm"),
                    "account_id": item.get("account_id"),
                    "account_nm": item.get("account_nm"),
                    "thstrm_nm": item.get("thstrm_nm"),
                    "thstrm_amount": item.get("thstrm_amount"),
                    "quarter": quarter_label,
                }
                # 날짜
                try:
                    row["report_date"] = dt.datetime.strptime(
                        f"{year}{date_suffix}", "%Y-%m-%d"
                    ).date()
                except Exception:
                    row["report_date"] = None

                rows.append(row)

        return rows

    # 1) CFS 먼저
    all_rows: List[Dict] = []
    for year in range(start_year, end_year + 1):
        rows = fetch_one_year(api_key, corp_code, year, fs_div="CFS")
        if rows:
            all_rows.extend(rows)

    # 2) CFS 없으면 OFS로 재시도
    if len(all_rows) == 0:
        print("[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.")
        for year in range(start_year, end_year + 1):
            rows = fetch_one_year(api_key, corp_code, year, fs_div="OFS")
            if rows:
                all_rows.extend(rows)

    if not all_rows:
        print("[WARN] CFS/OFS 모두 자료 없음")
        return pd.DataFrame()

    df = pd.DataFrame(all_rows)

    # 금액 숫자 변환
    df["thstrm_amount"] = pd.to_numeric(df["thstrm_amount"], errors="coerce")

    df = df.sort_values(["bsns_year", "reprt_code", "account_nm"]).reset_index(drop=True)
    return df

def run_dart_fs_for_top_n(api_key: str,
                          db_info: dict,
                          start_year: int = 2015,
                          end_year: int = 2025,
                          top_n: int = 50,
                          batch_size: int = 10,
                          use_fdr_filter: bool = True,
                          table_name: str = "korea_fs_data_from_DART"):
    """
    1) DART corp 목록 로드
    2) FDR 시가총액 기준 상위 top_n 종목 선택
    3) 각 종목에 대해 DART 분기 재무 데이터를 수집
    4) 회사 batch_size개 단위로 DB에 저장
    5) 에러 발생 종목은 error_list에 기록

    반환:
        error_list: [(stock_code, corp_name, 에러메시지), ...]
    """

    # DB 연결 테스트
    if not test_db_connection(db_info):
        logger.error("DB 연결 실패로 작업을 중단합니다")
        return []

    logger.info("DB 연결 테스트 완료")

    # 1) DART 기업 목록 로드
    print("=" * 70)
    logger.info("[STEP 1] DART 기업 목록 로드 중...")

    corp_df = load_corp_code(api_key)

    # DART 상장사만 필터링
    corp_df = corp_df[
        corp_df["stock_code"].notna() &
        (corp_df["stock_code"] != "") &
        (corp_df["stock_code"].str.strip() != "")
    ].copy()
    corp_df["stock_code"] = corp_df["stock_code"].astype(str).str.zfill(6)

    logger.info(f"DART 상장사 필터링 완료: {len(corp_df)}개")

    # 2) FDR 기반 현재 상장사 + 시가총액 상위 N개 필터링
    if use_fdr_filter:
        logger.info("[STEP 1-2] FinanceDataReader로 현재 상장 종목 + 시가총액 상위 종목 필터링...")

        try:
            fdr_df = fdr.StockListing("KRX")
            fdr_df["Code"] = fdr_df["Code"].astype(str).str.zfill(6)

            # ETF/ETN/REIT/SPAC 제거
            exclude_types = ["ETF", "ETN", "REIT", "SPAC"]

            if "Type" in fdr_df.columns:
                before = len(fdr_df)
                fdr_df = fdr_df[~fdr_df["Type"].isin(exclude_types)].copy()
                logger.info(f"Type 기반 필터링: {before}개 -> {len(fdr_df)}개")
            else:
                logger.warning("FDR 데이터에 'Type' 컬럼 없음 - Name 기반 필터 사용")
                pattern = r"ETF|ETN|리츠|리트|스팩|SPAC"
                before = len(fdr_df)
                fdr_df = fdr_df[~fdr_df["Name"].str.contains(pattern, case=False, na=False)].copy()
                logger.info(f"Name 기반 필터링: {before}개 -> {len(fdr_df)}개")

            # 시가총액 기준 상위 N개
            if "Marcap" not in fdr_df.columns:
                raise RuntimeError("FDR 데이터에 'Marcap' 컬럼이 없습니다. 버전을 확인하세요.")

            fdr_df = fdr_df.dropna(subset=["Marcap"]).copy()
            fdr_df = fdr_df.sort_values("Marcap", ascending=False)

            fdr_top = fdr_df.head(top_n).copy()
            top_codes = set(fdr_top["Code"].tolist())
            logger.info(f"FDR 시가총액 상위 {top_n}개 코드 추출 완료")

            # DART corp_df와 조인
            before = len(corp_df)
            corp_df = corp_df[corp_df["stock_code"].isin(top_codes)].copy()
            logger.info(f"DART 상장사 중 시가총액 상위 {top_n} 교집합: {before}개 -> {len(corp_df)}개")

        except Exception as e:
            logger.error(f"FDR 필터링 실패: {e}")
            logger.warning("FDR 필터를 건너뛰고 DART 목록만 사용 (시가총액 필터 없음)")

    total_companies = len(corp_df)
    logger.info(f"최종 대상 기업(루프 대상): {total_companies}개")

    print("\n[상장사 샘플]")
    print(corp_df[["corp_name", "stock_code"]].head(10))
    print()

    # -------------------------------------------------
    # 3) 메인 루프: 회사별로 DART 재무제표 수집 + 배치 저장
    # -------------------------------------------------
    error_list = []
    batch_list: List[pd.DataFrame] = []
    batch_codes: List[str] = []

    target_cols = [
        'corp_code', 'bsns_year', 'reprt_code', 'sj_div', 'sj_nm',
        'account_id', 'account_nm', 'thstrm_nm', 'thstrm_amount',
        'quarter', 'report_date'
    ]

    processed_count = 0

    for idx, row in corp_df.iterrows():
        stock_code = row["stock_code"]
        corp_code = row["corp_code"]
        corp_name = row["corp_name"]

        logger.info(f"[{processed_count + 1}/{total_companies}] {corp_name}({stock_code}) 처리 중...")

        try:
            fs_df = get_dart_fs_quarterly(
                api_key=api_key,
                corp_code=corp_code,
                start_year=start_year,
                end_year=end_year,
            )

            if fs_df.empty:
                logger.warning(f"{corp_name}({stock_code}) : 재무데이터 없음 (fs_df empty)")
                processed_count += 1
                continue

            # 필요한 컬럼만 추출
            missing_cols = [c for c in target_cols if c not in fs_df.columns]
            if missing_cols:
                logger.warning(f"{corp_name}({stock_code}) : 필요한 컬럼 누락 - {missing_cols}")
                processed_count += 1
                continue

            fs_df_refined = fs_df[target_cols].copy()
            fs_df_refined["ticker"] = stock_code  # 이 batch 함수에서는 ticker를 미리 넣어둡니다.

            batch_list.append(fs_df_refined)
            batch_codes.append(stock_code)
            processed_count += 1

            # 배치 크기에 도달하면 DB에 저장
            if len(batch_list) >= batch_size:
                logger.info(f"[BATCH SAVE] 회사 {len(batch_list)}개 묶어서 DB 저장 시도...")
                try:
                    save_fs_batch_to_db(batch_list, db_info=db_info, table_name=table_name)
                    logger.info(f"[BATCH SAVE] 저장 완료 (회사 {len(batch_list)}개)")
                except Exception as be:
                    logger.error(f"[BATCH SAVE ERROR] 배치 저장 중 오류 발생: {be}")
                    # 배치에 포함된 종목 모두를 에러 리스트에 추가
                    for sc in batch_codes:
                        error_list.append((sc, "BATCH_ERROR", str(be)))
                finally:
                    # 배치 초기화
                    batch_list = []
                    batch_codes = []

        except Exception as e:
            logger.error(f"{corp_name}({stock_code}) 처리 중 오류 발생: {e}")
            error_list.append((stock_code, corp_name, str(e)))
            processed_count += 1
            continue

    # 마지막으로 남은 배치 처리
    if batch_list:
        logger.info(f"[FINAL BATCH SAVE] 남은 회사 {len(batch_list)}개 DB 저장 시도...")
        try:
            save_fs_batch_to_db(batch_list, db_info=db_info, table_name=table_name)
            logger.info(f"[FINAL BATCH SAVE] 저장 완료 (회사 {len(batch_list)}개)")
        except Exception as be:
            logger.error(f"[FINAL BATCH SAVE ERROR] 배치 저장 중 오류 발생: {be}")
            for sc in batch_codes:
                error_list.append((sc, "BATCH_ERROR", str(be)))

    logger.info(f"작업 완료. 총 기업 수: {total_companies}, 에러 기업 수: {len(error_list)}")

    if error_list:
        print("\n[에러 발생 종목 목록]")
        for sc, name, msg in error_list:
            print(f" - {sc} / {name} / {msg[:100]}")

    return error_list

def run_dart_fs_for_top_range(api_key: str,
                              db_info: dict,
                              start_year: int,
                              end_year: int,
                              top_start: int,
                              top_end: int,
                              batch_size: int = 10,
                              use_fdr_filter: bool = True,
                              table_name: str = "korea_fs_data_from_DART"):

    # 1) DB 연결 테스트
    if not test_db_connection(db_info):
        logger.error("DB 연결 실패로 작업 중단")
        return []

    # 2) DART corp 목록 로드
    corp_df = load_corp_code(api_key)
    corp_df = corp_df[corp_df["stock_code"].notnull()].copy()
    corp_df["stock_code"] = corp_df["stock_code"].astype(str).str.zfill(6)

    # 3) FDR 시총 데이터 로드
    if use_fdr_filter:
        fdr_df = fdr.StockListing("KRX")
        fdr_df["Code"] = fdr_df["Code"].astype(str).str.zfill(6)
        exclude = ["ETF","ETN","REIT","SPAC"]

        if "Type" in fdr_df.columns:
            fdr_df = fdr_df[~fdr_df["Type"].isin(exclude)].copy()

        # 시총 기준 정렬
        fdr_df = fdr_df.dropna(subset=["Marcap"])
        fdr_df = fdr_df.sort_values("Marcap", ascending=False)

        # 4) 범위 선택 (예: 51~100)
        fdr_range = fdr_df.iloc[top_start-1 : top_end]   # 1-indexed → 0-index 변환
        target_codes = set(fdr_range["Code"].tolist())

        print(f"[INFO] 시총 {top_start} ~ {top_end}위 기업 수: {len(target_codes)}")
    else:
        target_codes = set(corp_df["stock_code"].tolist())

    # DART corp_code 조인
    corp_df = corp_df[corp_df["stock_code"].isin(target_codes)].copy()

    # 기존 batch 저장 루틴 재사용
    error_list = run_dart_fs_for_stock_list(
        api_key=api_key,
        db_info=db_info,
        stock_code_list=list(corp_df["stock_code"]),
        start_year=start_year,
        end_year=end_year,
        batch_size=batch_size,
        table_name=table_name,
    )

    return error_list

# ---------------------------------------------------------
# 4) DB 저장 함수
# ---------------------------------------------------------
def save_fs_batch_to_db(batch_list: List[pd.DataFrame],
                        db_info: dict,
                        table_name: str = "korea_fs_data_from_DART"):
    """
    여러 회사의 fs_df_refined(DataFrame)를 한 번에 DB에 저장하는 배치 함수.

    batch_list: 각 원소가 다음 컬럼을 가진 DataFrame
        ['corp_code', 'bsns_year', 'reprt_code', 'sj_div', 'sj_nm',
         'account_id', 'account_nm', 'thstrm_nm', 'thstrm_amount',
         'quarter', 'report_date', 'ticker']
    """

    if not batch_list:
        return

    # 하나로 합치기
    df = pd.concat(batch_list, ignore_index=True)

    # 타입 정리
    df["bsns_year"] = pd.to_numeric(df["bsns_year"], errors="coerce").astype("Int64")
    df["quarter"] = df["quarter"].astype(str)
    df["thstrm_amount"] = pd.to_numeric(df["thstrm_amount"], errors="coerce")
    df["report_date"] = pd.to_datetime(df["report_date"], errors="coerce").dt.date
    df["reprt_code"] = df["reprt_code"].astype(str)

    # PK에 들어가는 account_id 비어있으면 제거
    before = len(df)
    df = df[df["account_id"].notnull() & (df["account_id"] != "")]
    after = len(df)
    if before != after:
        logger.warning(f"[BATCH] account_id 없음으로 제거된 행: {before - after} rows")

    # NaN/NaT/<NA> → None
    df = df.where(pd.notnull(df), None)
    df = df.replace({pd.NA: None})
    df = df.replace({float('nan'): None})
    df = df.astype(object).where(df.notnull(), None)

    conn = pymysql.connect(
        host=db_info["host"],
        port=db_info["port"],
        user=db_info["user"],
        password=db_info["password"],
        database=db_info["database"],
        charset="utf8mb4",
        autocommit=False,
    )

    try:
        with conn.cursor() as cur:
            # 테이블이 없으면 생성
            create_sql = f"""
            CREATE TABLE IF NOT EXISTS {table_name} (
                corp_code      VARCHAR(20)   NOT NULL,
                bsns_year      INT           NOT NULL,
                reprt_code     VARCHAR(10)   NOT NULL,
                quarter        VARCHAR(10)   NOT NULL,
                account_id     VARCHAR(100)  NOT NULL,

                sj_div         VARCHAR(10),
                sj_nm          VARCHAR(100),
                account_nm     VARCHAR(255),
                thstrm_nm      VARCHAR(50),
                thstrm_amount  DOUBLE,
                report_date    DATE,
                ticker         VARCHAR(20)   NOT NULL,

                PRIMARY KEY (corp_code, bsns_year, reprt_code, quarter, account_id)
            ) CHARACTER SET utf8mb4;
            """
            cur.execute(create_sql)

            insert_sql = f"""
            INSERT INTO {table_name} (
                corp_code, bsns_year, reprt_code, sj_div, sj_nm,
                account_id, account_nm, thstrm_nm, thstrm_amount,
                quarter, report_date, ticker
            ) VALUES (
                %(corp_code)s, %(bsns_year)s, %(reprt_code)s, %(sj_div)s, %(sj_nm)s,
                %(account_id)s, %(account_nm)s, %(thstrm_nm)s, %(thstrm_amount)s,
                %(quarter)s, %(report_date)s, %(ticker)s
            )
            ON DUPLICATE KEY UPDATE
                sj_div        = VALUES(sj_div),
                sj_nm         = VALUES(sj_nm),
                account_nm    = VALUES(account_nm),
                thstrm_nm     = VALUES(thstrm_nm),
                thstrm_amount = VALUES(thstrm_amount),
                report_date   = VALUES(report_date),
                ticker        = VALUES(ticker);
            """

            records = df.to_dict(orient="records")
            cur.executemany(insert_sql, records)

        conn.commit()
        logger.info(f"[BATCH] {len(df)} rows saved into {table_name}")

    except Exception as e:
        conn.rollback()
        logger.error(f"[BATCH] DB 저장 중 오류 발생: {e}")
        raise
    finally:
        conn.close()

def run_dart_fs_for_stock_list(api_key: str,
                               db_info: dict,
                               stock_code_list: list,
                               start_year: int = 2015,
                               end_year: int = 2025,
                               batch_size: int = 10,
                               table_name: str = "korea_fs_data_from_DART"):
    """
    지정한 stock_code 리스트(예: ['005930','000660', ...])에 대해서만
    DART 분기 재무제표를 수집하고, batch_size개 회사 단위로 DB에 저장.

    - api_key: DART API 키
    - db_info: MariaDB 접속 정보 딕셔너리
    - stock_code_list: 종목코드 리스트 (길이 N)
    - start_year, end_year: 재무제표 수집 연도 범위
    - batch_size: 몇 개 회사 단위로 DB에 저장할지 (기본 10)
    - table_name: 저장할 테이블 이름

    반환:
        error_list: [(stock_code, corp_name_or_reason, error_message), ...]
    """

    # 0) DB 연결 테스트
    if not test_db_connection(db_info):
        logger.error("DB 연결 실패로 작업을 중단합니다")
        return []

    logger.info("DB 연결 테스트 완료")

    # 1) DART 기업 목록 로드
    logger.info("[STEP 1] DART 기업 목록 로드 중...")
    corp_df = load_corp_code(api_key)

    # 상장사만 필터링 + stock_code 6자리 정규화
    corp_df = corp_df[
        corp_df["stock_code"].notna() &
        (corp_df["stock_code"] != "") &
        (corp_df["stock_code"].str.strip() != "")
    ].copy()
    corp_df["stock_code"] = corp_df["stock_code"].astype(str).str.zfill(6)

    logger.info(f"DART 상장사 필터링 완료: {len(corp_df)}개")

    # 2) 입력받은 stock_code 리스트 정규화 (중복 제거 + 6자리 패딩)
    normalized_codes = sorted(set(str(code).zfill(6) for code in stock_code_list))
    logger.info(f"사용자 지정 종목 수: {len(stock_code_list)}개 -> 정규화 후 {len(normalized_codes)}개")

    # corp_df에서 빠른 lookup을 위해 dict 생성 (stock_code -> (corp_code, corp_name))
    corp_map = {}
    for _, r in corp_df[["corp_code", "corp_name", "stock_code"]].iterrows():
        corp_map[r["stock_code"]] = (r["corp_code"], r["corp_name"])

    # 3) 메인 루프: 회사별 재무제표 수집 + 배치 저장
    error_list = []
    batch_list: List[pd.DataFrame] = []
    batch_codes: List[str] = []

    target_cols = [
        'corp_code', 'bsns_year', 'reprt_code', 'sj_div', 'sj_nm',
        'account_id', 'account_nm', 'thstrm_nm', 'thstrm_amount',
        'quarter', 'report_date'
    ]

    total = len(normalized_codes)
    processed = 0

    for stock_code in normalized_codes:
        processed += 1

        if stock_code not in corp_map:
            msg = "DART corp_code를 찾을 수 없음"
            logger.warning(f"[{processed}/{total}] {stock_code}: {msg}")
            error_list.append((stock_code, "NOT_FOUND_IN_DART", msg))
            continue

        corp_code, corp_name = corp_map[stock_code]
        logger.info(f"[{processed}/{total}] {corp_name}({stock_code}) 처리 중...")

        try:
            # 3-1) 재무데이터 수신
            fs_df = get_dart_fs_quarterly(
                api_key=api_key,
                corp_code=corp_code,
                start_year=start_year,
                end_year=end_year,
            )

            if fs_df.empty:
                msg = "재무데이터 없음 (fs_df empty)"
                logger.warning(f"{corp_name}({stock_code}) : {msg}")
                error_list.append((stock_code, corp_name, msg))
                continue

            # 3-2) 필요한 컬럼 체크
            missing_cols = [c for c in target_cols if c not in fs_df.columns]
            if missing_cols:
                msg = f"필요한 컬럼 누락: {missing_cols}"
                logger.warning(f"{corp_name}({stock_code}) : {msg}")
                error_list.append((stock_code, corp_name, msg))
                continue

            # 3-3) 정제 후 배치 리스트에 추가
            fs_df_refined = fs_df[target_cols].copy()
            fs_df_refined["ticker"] = stock_code  # 여기서 ticker 추가

            batch_list.append(fs_df_refined)
            batch_codes.append(stock_code)

            # 3-4) 배치 크기에 도달하면 DB에 저장
            if len(batch_list) >= batch_size:
                logger.info(f"[BATCH SAVE] 회사 {len(batch_list)}개 묶어서 DB 저장 시도...")
                try:
                    save_fs_batch_to_db(batch_list, db_info=db_info, table_name=table_name)
                    logger.info(f"[BATCH SAVE] 저장 완료 (회사 {len(batch_list)}개)")
                except Exception as be:
                    logger.error(f"[BATCH SAVE ERROR] 배치 저장 중 오류 발생: {be}")
                    for sc in batch_codes:
                        error_list.append((sc, "BATCH_ERROR", str(be)))
                finally:
                    batch_list = []
                    batch_codes = []

        except Exception as e:
            logger.error(f"{corp_name}({stock_code}) 처리 중 오류 발생: {e}")
            error_list.append((stock_code, corp_name, str(e)))
            continue

    # 4) 마지막으로 남은 배치 처리
    if batch_list:
        logger.info(f"[FINAL BATCH SAVE] 남은 회사 {len(batch_list)}개 DB 저장 시도...")
        try:
            save_fs_batch_to_db(batch_list, db_info=db_info, table_name=table_name)
            logger.info(f"[FINAL BATCH SAVE] 저장 완료 (회사 {len(batch_list)}개)")
        except Exception as be:
            logger.error(f"[FINAL BATCH SAVE ERROR] 배치 저장 중 오류 발생: {be}")
            for sc in batch_codes:
                error_list.append((sc, "BATCH_ERROR", str(be)))

    logger.info(f"작업 완료. 지정 종목 수: {total}, 에러 종목 수: {len(error_list)}")

    if error_list:
        print("\n[에러 발생 종목 목록]")
        for sc, name, msg in error_list:
            print(f" - {sc} / {name} / {msg[:100]}")

    return error_list

# =============================================================================
# DART 재무데이터 수집 - Ticker 리스트 입력 실행 스크립트 (수정버전)
# =============================================================================

import os
from typing import List



# DB 연결 함수 import
from DATA.stock_invest_function import get_db_host

def collect_dart_fs_by_tickers(
    ticker_list: List[str],
    api_key: str,
    start_year: int = 2025,
    end_year: int = 2025,
    batch_size: int = 10,
    table_name: str = "korea_fs_data_from_DART"
):
    """
    ticker 리스트를 입력받아 DART 재무데이터를 수집하고 DB에 저장

    Parameters:
    -----------
    ticker_list : List[str]
        종목코드 리스트 (예: ['005930', '000660', '035420'])
    api_key : str
        DART API 키
    start_year : int
        수집 시작 연도 (기본: 2015)
    end_year : int
        수집 종료 연도 (기본: 2025)
    batch_size : int
        한 번에 저장할 회사 수 (기본: 10)
    table_name : str
        저장할 테이블명 (기본: korea_fs_data_from_DART)

    Returns:
    --------
    error_list : list
        에러 발생 종목 리스트 [(ticker, corp_name, error_msg), ...]
    """

    # 1) DB 연결 정보 설정 - get_db_host() 함수 사용
    db_info = {
        'host': get_db_host(),
        'port': 3307,  # 포트 3307로 수정
        'user': 'stox7412',
        'password': 'Apt106503!~',
        'database': 'investar'
    }

    logger.info(f"DB 연결 정보: host={db_info['host']}, port={db_info['port']}, database={db_info['database']}")

    # 2) 입력 확인
    logger.info("=" * 70)
    logger.info("[재무데이터 수집 시작]")
    logger.info(f"대상 종목 수: {len(ticker_list)}개")
    logger.info(f"수집 기간: {start_year}년 ~ {end_year}년")
    logger.info(f"배치 크기: {batch_size}개")
    logger.info(f"저장 테이블: {table_name}")
    logger.info("=" * 70)

    # 샘플 출력
    if len(ticker_list) <= 10:
        logger.info(f"대상 종목: {ticker_list}")
    else:
        logger.info(f"대상 종목 샘플 (처음 10개): {ticker_list[:10]}")

    # 3) 재무데이터 수집 및 저장
    error_list = run_dart_fs_for_stock_list(
        api_key=api_key,
        db_info=db_info,
        stock_code_list=ticker_list,
        start_year=start_year,
        end_year=end_year,
        batch_size=batch_size,
        table_name=table_name
    )

    # 4) 결과 요약
    logger.info("=" * 70)
    logger.info("[작업 완료]")
    logger.info(f"총 대상 종목: {len(ticker_list)}개")
    logger.info(f"성공: {len(ticker_list) - len(error_list)}개")
    logger.info(f"에러 발생: {len(error_list)}개")

    if error_list:
        logger.warning("\n[에러 발생 종목 상세]")
        for ticker, name, msg in error_list:
            logger.warning(f"  - {ticker} ({name}): {msg[:100]}")
    else:
        logger.info("모든 종목 처리 완료!")

    logger.info("=" * 70)

    return error_list

2026-01-06 18:43:42 [INFO] Project root added: C:\Users\82108\OneDrive\바탕 화면\investment\investment_strategy
2026-01-06 18:43:49 [WARNING] From C:\Users\82108\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [2]:
API_KEY = "50424484a46daa88b34fcf875f40ca12b79e1fc1"   # ← 본인 키로 교체하세요
stock_code = "000660"                      # 예: 삼성전자 (FinanceDataReader 코드 형식)

from DATA.stock_invest_function import fetch_table_data, get_db_host

db_info = {
    'host': get_db_host(),
    'port': 3307,
    'user' : 'stox7412',
    'password' : 'Apt106503!~',
    'database': 'investar'
}
#
# ticker_list_sample = [
#     "131290",  # 티에스이
#
# ]
#
# # 실행
# errors = collect_dart_fs_by_tickers(
#     ticker_list=ticker_list_sample,
#     api_key = API_KEY,
#     start_year=2015,
#     end_year=2025,
#     batch_size=5,
#     table_name="korea_fs_data_from_DART"
# )

In [3]:
# test = get_dart_fs_quarterly(API_KEY, "00267881", 2015, 2025)
name = load_corp_code(API_KEY)
name[name['corp_name'].str.contains('티에스이')]
#
test = get_dart_fs_quarterly(API_KEY, "00372226", 2015, 2025)
test

,corp_code,bsns_year,reprt_code,sj_div,sj_nm,account_id,account_nm,thstrm_nm,thstrm_amount,quarter,report_date
0,00372226,2015,11011,CF,현금흐름표,-표준계정코드 미사용-,계속영업,제 21 기,3.362306e+09,FY,2015-12-31
1,00372226,2015,11011,CF,현금흐름표,-표준계정코드 미사용-,계속영업,제 21 기,3.941224e+08,FY,2015-12-31
2,00372226,2015,11011,CF,현금흐름표,-표준계정코드 미사용-,계속영업,제 21 기,8.693712e+09,FY,2015-12-31
3,00372226,2015,11011,IS,손익계산서,ifrs_BasicEarningsLossPerShareFromContinuingOp...,계속영업기본주당이익(손실),제 21 기,1.730000e+02,FY,2015-12-31
4,00372226,2015,11011,IS,손익계산서,-표준계정코드 미사용-,계속영업손익,제 21 기,1.882712e+09,FY,2015-12-31
...,...,...,...,...,...,...,...,...,...,...,...
6107,00372226,2025,11014,CF,현금흐름표,ifrs-full_EffectOfExchangeRateChangesOnCashAnd...,현금및현금성자산에 대한 환율변동효과,제 31 기 3분기,1.084818e+09,Q3,2025-09-30
6108,00372226,2025,11014,CF,현금흐름표,ifrs-full_IncreaseDecreaseInCashAndCashEquival...,현금및현금성자산의순증가(감소),제 31 기 3분기,1.764185e+10,Q3,2025-09-30
6109,00372226,2025,11014,CIS,포괄손익계산서,ifrs-full_OtherComprehensiveIncomeThatWillNotB...,후속적으로 당기손익으로 재분류되지 않는 항목,제 31 기 3분기,1.497172e+09,Q3,2025-09-30
6110,00372226,2025,11014,CIS,포괄손익계산서,ifrs-full_OtherComprehensiveIncomeThatWillBeRe...,후속적으로 당기손익으로 재분류될 수 있는 항목,제 31 기 3분기,-9.344980e+07,Q3,2025-09-30
6111,00372226,2025,11014,IS,손익계산서,ifrs-full_DilutedEarningsLossPerShare,희석주당이익(손실),제 31 기 3분기,1.058000e+03,Q3,2025-09-30

In [4]:
test['account_nm'].unique().tolist()

['계속영업',
 '계속영업기본주당이익(손실)',
 '계속영업손익',
 '계속영업희석주당이익(손실)',
 '관계기업의 자본구성 변동',
 '관계기업투자',
 '금융비용',
 '금융수익',
 '기말의 현금',
 '기말자본',
 '기본주당이익(손실)',
 '기초의 현금',
 '기초자본',
 '기타금융자산',
 '기타금융자산의 감소',
 '기타금융자산의 증가',
 '기타비용',
 '기타비유동자산',
 '기타수익',
 '기타수취채권',
 '기타수취채권의 감소',
 '기타수취채권의 증가',
 '기타유동부채',
 '기타유동자산',
 '기타자본항목',
 '기타지급채무',
 '기타포괄손익누계액',
 '납입자본',
 '단기금융상품',
 '단기금융상품의 순증가',
 '당기법인세부채',
 '당기법인세자산',
 '당기순이익(손실)',
 '매각예정부채',
 '매각예정자산',
 '매도가능금융자산의 증가',
 '매도가능금융자산평가이익',
 '매도가능증권평가손익',
 '매입채무',
 '매출액',
 '매출원가',
 '매출채권',
 '매출총이익',
 '무형자산',
 '무형자산의 취득',
 '배당금수취',
 '법인세납부(환급)',
 '법인세비용',
 '법인세비용차감전순이익(손실)',
 '부채총계',
 '비유동부채',
 '비유동자산',
 '비지배지분',
 '세후 기타포괄손익',
 '세후 총포괄손익',
 '순확정급여부채',
 '순확정급여부채의 재측정요소',
 '연결계속당기순이익',
 '연결범위변동에 따른 현금성자산의 감소',
 '연결중단영업순손실',
 '영업으로부터 창출된 현금흐름',
 '영업이익(손실)',
 '영업활동현금흐름',
 '유동부채',
 '유동자산',
 '유형자산',
 '유형자산의 처분',
 '유형자산의 취득',
 '이연법인세자산',
 '이익잉여금(결손금)',
 '이자수취',
 '이자지급',
 '자기주식의 처분',
 '자기주식의 취득',
 '자본과부채총계',
 '자본총계',
 '자산총계',
 '장기금융상품',
 '장기금융상품의 감소',
 '장기금융상품의 증가',
 '재고자산',
 '재무활동현금흐름',
 '전환우선주의 발행',
 '종속기업 지분 추가 취득',
 '종속기업 지분의 추가 취득',
 '종속기업 투자로 인한 순현금유입',
 '종속기업 투자로 인한 순현금유출',
 '종속기업의 범위변동',
 '종속기업의 유상증자',
 '종속기업의 전환우선주 전환권 행사',
 '종속기업의 취득',
 '주식매수선택권의 행사',
 '주식선택권의 행사',
 '중단영업',
 '중단영업기본주당이익(손실)',
 '중단영업손익',
 '중단영업희석주당이익(손실)',
 '지배기업의 소유주지분',
 '지분법손익',
 '차입금',
 '차입금의 상환',
 '차입금의 증가',
 '충당부채',
 '투자부동산',
 '투자활동현금흐름',
 '판매비와관리비',
 '해외사업환산손익',
 '현금및현금성자산',
 '현금의 증가(감소)',
 '환율변동효과',
 '환율변동효과 반영전 현금및현금성자산의 순증가(감소)',
 '후속적으로 당기손익으로 재분류되지 않는 항목',
 '후속적으로 당기손익으로 재분류될 수 있는 항목',
 '희석주당이익(손실)',
 '관계기업투자자산',
 '단기금융상품의 감소',
 '장기금융상품의 취득',
 '종속기업 취득으로 인한 순현금유출',
 '차입금의 차입',
 '현금및현금성자산에 대한 환율변동효과',
 '단기금융상품의 증가',
 '반기말의 현금',
 '주식보상비용',
 '단기금융상품의 순증감',
 '이연법인세부채',
 '종속기업 및 관계기업 투자',
 '계속영업이익(손실)',
 '관계기업에 대한 투자자산',
 '금융원가',
 '기말현금및현금성자산',
 '기초현금및현금성자산',
 '기타금융자산의 처분',
 '기타금융자산의 취득',
 '기타비유동금융자산',
 '기타비유동채권',
 '기타비유동채무',
 '기타손실',
 '기타수취채권의 처분',
 '기타수취채권의 취득',
 '기타유동채권',
 '기타유동채무',
 '기타이익',
 '기타자본',
 '기타포괄손익',
 '단기금융상품의 처분',
 '당기손익으로 재분류되지 않는항목(세후기타포괄손익)',
 '당기손익으로 재분류될 수 있는 항목(세후기타포괄손익)',
 '매도가능금융자산평가손익(세후기타포괄손익)',
 '무형자산의 처분',
 '배당금수취(영업)',
 '보험수리적손익',
 '비유동충당부채',
 '비지배지분에 귀속되는 당기순이익(손실)',
 '수익(매출액)',
 '이자수취(영업)',
 '이자지급(영업)',
 '자기주식 거래로 인한 증감',
 '자본 증가(감소) 합계',
 '장기차입금',
 '주식기준보상거래',
 '지배기업의 소유주에게 귀속되는 당기순이익(손실)',
 '지배기업의 소유주에게 귀속되는 자본',
 '지배기업의 소유주에게 귀속되는 지분',
 '지배력을 상실하지 않는 종속기업에 대한 소유지분의 변동에 따른 증가(감소)/비지배지분의 변동',
 '총포괄손익',
 '해외사업장환산외환차이(세후기타포괄손익)',
 '현금및현금성자산의순증가(감소)',
 '확정급여제도의 재측정손익(세후기타포괄손익)',
 '확정급여채무',
 '기타자본구성요소',
 '단기금융상품의 취득',
 '영업으로부터창출된현금흐름',
 '총 포괄손익, 비지배지분',
 '총 포괄손익, 지배기업의 소유주에게 귀속되는 지분',
 '퇴직급여부채',
 '기타포괄손익-공정가치금융자산평가손익',
 '단기차입금',
 '소유주와의 거래 소계',
 '장기매입채무 및 기타비유동채무',
 '총포괄손익 소계',
 '해외사업환산손실',
 '매도가능금융자산평가손익',
 '종속기업에 대한 소유지분의 변동으로 인한 지급',
 '단기대여금의 감소',
 '단기대여금의 증가',
 '리스부채의 상환',
 '리스자산',
 '리스자산의 취득',
 '배당금지급',
 '장기대여금의 감소',
 '장기대여금의 증가',
 '관계기업투자의 처분',
 '사업결합으로 인한 현금 증가',
 '자기주식 처분(취득)',
 '종속기업의 자본변동',
 '종속기업투자의 취득',
 '종속기업의 자본변동 등',
 '계약자산',
 '관계기업에 대한 투자자산의 처분',
 '관계기업투자주식',
 '기타금융채무의 증가',
 '기타포괄손익-공정가치 측정 금융자산',
 '당기손익-공정가치 측정 금융부채',
 '당기손익-공정가치 측정 금융자산',
 '당기손익-공정가치 측정 금융자산 감소',
 '당기손익-공정가치 측정 금융자산 증가',
 '당기손익-공정가치측정금융부채 증가',
 '리스부채(비유동)',
 '리스부채(유동)',
 '리스사용권자산',
 '보증금의 감소',
 '보증금의 증가',
 '임대보증금의 증가',
 '자본에 직접 반영된 소유주와의 거래 소계',
 '종속기업의 합병',
 '총 포괄이익 소계',
 '파생상품부채',
 '기타비유동금융부채',
 '단기금융상품의 감소(증가)',
 '리스사용권자산의 취득',
 '기타금융채무',
 '소유주와의 거래',
 '주식기준보상의 감소',
 '파생상품자산의 감소',
 '당기손익인식금융자산의 취득',
 '기타 유동부채',
 '당기손익-공정가치측정금융자산 증가',
 '법인세비용(수익)',
 '법인세환급(납부)',
 '사용권자산',
 '소유주에 대한 배분으로 인식된 배당금',
 '유동 차입금',
 '유동재고자산',
 '유동파생상품부채',
 '임차보증금의 증가',
 '정부보조금의 수령',
 '종속기업투자의 처분',
 '주식기준보상의 행사',
 '주식기준보상거래에 따른 증가(감소), 지분',
 '관계기업 투자의 취득',
 '기타포괄손익-공정가치 측정 지분상품 처분에 따른 이익잉여금 대체',
 '기타포괄손익-공정가치측정금융자산 감소',
 '배당금 지급',
 '비유동파생상품부채',
 '유동 차입금(사채 포함)',
 '장기차입금(사채 포함), 총액',
 '지분법이익(손실)',
 '관계기업에 대한 투자자산의 취득',
 '기타금융자산의 감소(증가)',
 '파생상품의 감소(증가)',
 '파생상품자산']

In [3]:
error_list = run_dart_fs_for_top_range(
    api_key=API_KEY,
    db_info=db_info,
    start_year=2025,
    end_year=2025,
    top_start=0,
    top_end=2900,
    batch_size=10,
    use_fdr_filter=True,
    table_name="korea_fs_data_from_DART",
)

2025-11-28 14:59:01 [INFO] DB 연결 성공
2025-11-28 14:59:15 [INFO] DB 연결 성공
2025-11-28 14:59:15 [INFO] DB 연결 테스트 완료
2025-11-28 14:59:15 [INFO] [STEP 1] DART 기업 목록 로드 중...

[INFO] 시총 2400 ~ 2900위 기업 수: 487

2025-11-28 14:59:17 [INFO] DART 상장사 필터링 완료: 3918개
2025-11-28 14:59:17 [INFO] 사용자 지정 종목 수: 427개 -> 정규화 후 427개
2025-11-28 14:59:17 [INFO] [1/427] 디비금융제14호스팩(0004Y0) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 14:59:23 [INFO] [2/427] 태원물산(001420) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 14:59:31 [INFO] [3/427] SHD(001770) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 14:59:38 [INFO] [4/427] 비비안(002070) 처리 중...
2025-11-28 14:59:43 [INFO] [5/427] 동성제약(002210) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 14:59:51 [INFO] [6/427] 한탑(002680) 처리 중...
2025-11-28 14:59:56 [INFO] [7/427] SUN&L(002820) 처리 중...
2025-11-28 15:00:01 [INFO] [8/427] KB제32호스팩(0037T0) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:00:07 [INFO] [9/427] 교보18호스팩(0041B0) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:00:14 [INFO] [10/427] 엘에스스팩1호(0041J0) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:00:21 [INFO] [BATCH SAVE] 회사 10개 묶어서 DB 저장 시도...
2025-11-28 15:00:23 [INFO] [BATCH] 44192 rows saved into korea_fs_data_from_DART
2025-11-28 15:00:23 [INFO] [BATCH SAVE] 저장 완료 (회사 10개)
2025-11-28 15:00:24 [INFO] [11/427] 하나35호스팩(0041L0) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:00:30 [INFO] [12/427] 남성(004270) 처리 중...
2025-11-28 15:00:35 [INFO] [13/427] 삼성스팩10호(0044K0) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:00:41 [INFO] [14/427] 한창(005110) 처리 중...
2025-11-28 15:00:48 [INFO] [15/427] 한국전자홀딩스(006200) 처리 중...
2025-11-28 15:00:53 [INFO] [16/427] 비엔케이제3호스팩(0068Y0) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:00:59 [WARNING] 비엔케이제3호스팩(0068Y0) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:00:59 [INFO] [17/427] 모헨즈(006920) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:01:04 [INFO] [18/427] 미래아이앤지(007120) 처리 중...
2025-11-28 15:01:08 [INFO] [19/427] 삼성스팩11호(0071M0) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:01:14 [INFO] [20/427] KB제33호스팩(0072Z0) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:01:20 [INFO] [21/427] 한일화학(007770) 처리 중...
2025-11-28 15:01:26 [INFO] [BATCH SAVE] 회사 10개 묶어서 DB 저장 시도...
2025-11-28 15:01:28 [INFO] [BATCH] 41910 rows saved into korea_fs_data_from_DART
2025-11-28 15:01:28 [INFO] [BATCH SAVE] 저장 완료 (회사 10개)
2025-11-28 15:01:28 [INFO] [22/427] 원풍물산(008290) 처리 중...
2025-11-28 15:01:32 [INFO] [23/427] 일정실업(008500) 처리 중...
2025-11-28 15:01:37 [INFO] [24/427] 윌비스(008600) 처리 중...
2025-11-28 15:01:41 [INFO] [25/427] 신영스팩11호(0091W0) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:01:47 [WARNING] 신영스팩11호(0091W0) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:01:47 [INFO] [26/427] 참엔지니어링(009310) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:01:52 [INFO] [27/427] 미래에셋비전스팩8호(0093G0) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:01:58 [WARNING] 미래에셋비전스팩8호(0093G0) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:01:58 [INFO] [28/427] KC그린홀딩스(009440) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:02:06 [INFO] [29/427] 한창제지(009460) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:02:13 [INFO] [30/427] 삼보산업(009620) 처리 중...
2025-11-28 15:02:19 [INFO] [31/427] 우진아이엔에스(010400) 처리 중...
2025-11-28 15:02:24 [INFO] [32/427] 형지I&C(011080) 처리 중...
2025-11-28 15:02:28 [INFO] [33/427] 에넥스(011090) 처리 중...
2025-11-28 15:02:33 [INFO] [BATCH SAVE] 회사 10개 묶어서 DB 저장 시도...
2025-11-28 15:02:37 [INFO] [BATCH] 61210 rows saved into korea_fs_data_from_DART
2025-11-28 15:02:37 [INFO] [BATCH SAVE] 저장 완료 (회사 10개)
2025-11-28 15:02:37 [INFO] [34/427] 아센디오(012170) 처리 중...
2025-11-28 15:02:42 [INFO] [35/427] 뉴인텍(012340) 처리 중...
2025-11-28 15:02:46 [INFO] [36/427] 메디앙스(014100) 처리 중...
2025-11-28 15:02:51 [INFO] [37/427] 성문전자(014910) 처리 중...
2025-11-28 15:02:56 [INFO] [38/427] 이스타코(015020) 처리 중...
2025-11-28 15:02:59 [INFO] [39/427] 에이엔피(015260) 처리 중...
2025-11-28 15:03:04 [INFO] [40/427] 카스(016920) 처리 중...
2025-11-28 15:03:09 [INFO] [41/427] 신원종합개발(017000) 처리 중...
2025-11-28 15:03:13 [INFO] [42/427] 인터엠(017250) 처리 중...
2025-11-28 15:03:20 [INFO] [43/427] 우진비앤지(018620) 처리 중...
2025-11-28 15:03:24 [INFO] [BATCH SAVE] 회사 10개 묶어서 DB 저장 시도...
2025-11-28 15:03:27 [INFO] [BATCH] 53591 rows saved into korea_fs_data_from_DART
2025-11-28 15:03:27 [INFO] [BATCH SAVE] 저장 완료 (회사 10개)
2025-11-28 15:03:27 [INFO] [44/427] 플루토스(019570) 처리 중...
2025-11-28 15:03:32 [INFO] [45/427] 대동금속(020400) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:03:39 [INFO] [46/427] 대호특수강(021040) 처리 중...
2025-11-28 15:03:43 [INFO] [47/427] 플레이위드(023770) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:03:50 [INFO] [48/427] WISCOM(024070) 처리 중...
2025-11-28 15:03:56 [INFO] [49/427] 대원화성(024890) 처리 중...
2025-11-28 15:04:00 [INFO] [50/427] 신라에스지(025870) 처리 중...
2025-11-28 15:04:04 [INFO] [51/427] 한국주강(025890) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:04:29 [ERROR] 한국주강(025890) 처리 중 오류 발생: HTTPSConnectionPool(host='opendart.fss.or.kr', port=443): Max retries exceeded with url: /api/fnlttSinglAcntAll.json?crtfc_key=50424484a46daa88b34fcf875f40ca12b79e1fc1&corp_code=00159564&bsns_year=2015&reprt_code=11012&fs_div=OFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020AF3F23280>: Failed to establish a new connection: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다'))
2025-11-28 15:04:29 [INFO] [52/427] 광진실업(026910) 처리 중...
2025-11-28 15:04:32 [INFO] [53/427] 서울전자통신(027040) 처리 중...
2025-11-28 15:04:36 [INFO] [54/427] 휴맥스홀딩스(028080) 처리 중...
2025-11-28 15:04:41 [INFO] [BATCH SAVE] 회사 10개 묶어서 DB 저장 시도...
2025-11-28 15:04:44 [INFO] [BATCH] 49885 rows saved into korea_fs_data_from_DART
2025-11-28 15:04:44 [INFO] [BATCH SAVE] 저장 완료 (회사 10개)
2025-11-28 15:04:44 [INFO] [55/427] 드래곤플라이(030350) 처리 중...
2025-11-28 15:04:48 [INFO] [56/427] 동원수산(030720) 처리 중...
2025-11-28 15:04:53 [INFO] [57/427] 오스템(031510) 처리 중...
2025-11-28 15:04:58 [INFO] [58/427] 디에이치엑스컴퍼니(031860) 처리 중...
2025-11-28 15:05:04 [INFO] [59/427] 아즈텍WB(032080) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:05:11 [INFO] [60/427] 삼일(032280) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:05:18 [INFO] [61/427] 소프트센(032680) 처리 중...
2025-11-28 15:05:22 [INFO] [62/427] 판타지오(032800) 처리 중...
2025-11-28 15:05:27 [INFO] [63/427] 바이온(032980) 처리 중...
2025-11-28 15:05:33 [INFO] [64/427] 제이엠아이(033050) 처리 중...
2025-11-28 15:05:39 [INFO] [BATCH SAVE] 회사 10개 묶어서 DB 저장 시도...
2025-11-28 15:05:42 [INFO] [BATCH] 58691 rows saved into korea_fs_data_from_DART
2025-11-28 15:05:42 [INFO] [BATCH SAVE] 저장 완료 (회사 10개)
2025-11-28 15:05:42 [INFO] [65/427] 조아제약(034940) 처리 중...
2025-11-28 15:05:47 [INFO] [66/427] 골드앤에스(035290) 처리 중...
2025-11-28 15:05:52 [INFO] [67/427] 기산텔레콤(035460) 처리 중...
2025-11-28 15:05:57 [INFO] [68/427] 바른손이앤에이(035620) 처리 중...
2025-11-28 15:06:02 [INFO] [69/427] 대성미생물(036480) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:06:10 [INFO] [70/427] 우리엔터프라이즈(037400) 처리 중...
2025-11-28 15:06:15 [INFO] [71/427] 루멘스(038060) 처리 중...
2025-11-28 15:06:20 [INFO] [72/427] 케이바이오(038530) 처리 중...
2025-11-28 15:06:24 [INFO] [73/427] 세중(039310) 처리 중...
2025-11-28 15:06:29 [INFO] [74/427] 한국정보공학(039740) 처리 중...
2025-11-28 15:06:34 [INFO] [BATCH SAVE] 회사 10개 묶어서 DB 저장 시도...
2025-11-28 15:06:37 [INFO] [BATCH] 53322 rows saved into korea_fs_data_from_DART
2025-11-28 15:06:37 [INFO] [BATCH SAVE] 저장 완료 (회사 10개)
2025-11-28 15:06:37 [INFO] [75/427] 더테크놀로지(043090) 처리 중...
2025-11-28 15:06:41 [INFO] [76/427] 티에스넥스젠(043220) 처리 중...
2025-11-28 15:06:47 [INFO] [77/427] 디지아이(043360) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:06:54 [INFO] [78/427] 웰킵스하이텍(043590) 처리 중...
2025-11-28 15:07:00 [INFO] [79/427] KD(044180) 처리 중...
2025-11-28 15:07:04 [INFO] [80/427] 주연테크(044380) 처리 중...
2025-11-28 15:07:09 [INFO] [81/427] 빌리언스(044480) 처리 중...
2025-11-28 15:07:14 [INFO] [82/427] 에이치케이(044780) 처리 중...
2025-11-28 15:07:19 [INFO] [83/427] 정원엔시스(045510) 처리 중...
2025-11-28 15:07:24 [INFO] [84/427] 크린앤사이언스(045520) 처리 중...
2025-11-28 15:07:29 [INFO] [BATCH SAVE] 회사 10개 묶어서 DB 저장 시도...
2025-11-28 15:07:33 [INFO] [BATCH] 61190 rows saved into korea_fs_data_from_DART
2025-11-28 15:07:33 [INFO] [BATCH SAVE] 저장 완료 (회사 10개)
2025-11-28 15:07:33 [INFO] [85/427] 한빛소프트(047080) 처리 중...
2025-11-28 15:07:38 [INFO] [86/427] 대동스틸(048470) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:07:45 [INFO] [87/427] 엔피케이(048830) 처리 중...
2025-11-28 15:07:49 [INFO] [88/427] 비케이홀딩스(050090) 처리 중...
2025-11-28 15:07:52 [INFO] [89/427] 에스폴리텍(050760) 처리 중...
2025-11-28 15:07:58 [INFO] [90/427] 피씨디렉트(051380) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:08:05 [INFO] [91/427] 큐로홀딩스(051780) 처리 중...
2025-11-28 15:08:11 [INFO] [92/427] 아이톡시(052770) 처리 중...
2025-11-28 15:08:15 [INFO] [93/427] 태양3C(052960) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:08:21 [WARNING] 태양3C(052960) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:08:21 [INFO] [94/427] 세동(053060) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:08:26 [INFO] [95/427] NE능률(053290) 처리 중...
2025-11-28 15:08:29 [INFO] [BATCH SAVE] 회사 10개 묶어서 DB 저장 시도...
2025-11-28 15:08:32 [INFO] [BATCH] 45926 rows saved into korea_fs_data_from_DART
2025-11-28 15:08:32 [INFO] [BATCH SAVE] 저장 완료 (회사 10개)
2025-11-28 15:08:32 [INFO] [96/427] 삼진엘앤디(054090) 처리 중...
2025-11-28 15:08:37 [INFO] [97/427] 메디콕스(054180) 처리 중...
2025-11-28 15:08:41 [INFO] [98/427] 비츠로시스(054220) 처리 중...
2025-11-28 15:08:45 [INFO] [99/427] 케이피티유(054410) 처리 중...
2025-11-28 15:08:48 [INFO] [100/427] 에이디칩스(054630) 처리 중...
2025-11-28 15:08:52 [INFO] [101/427] 엑사이엔씨(054940) 처리 중...
2025-11-28 15:08:58 [INFO] [102/427] 멕아이씨에스(058110) 처리 중...
2025-11-28 15:09:03 [INFO] [103/427] 한주에이알티(058450) 처리 중...
2025-11-28 15:09:08 [INFO] [104/427] 제이케이시냅스(060230) 처리 중...
2025-11-28 15:09:13 [INFO] [105/427] 스타코링크(060240) 처리 중...
2025-11-28 15:09:18 [INFO] [BATCH SAVE] 회사 10개 묶어서 DB 저장 시도...
2025-11-28 15:09:21 [INFO] [BATCH] 49451 rows saved into korea_fs_data_from_DART
2025-11-28 15:09:21 [INFO] [BATCH SAVE] 저장 완료 (회사 10개)
2025-11-28 15:09:21 [INFO] [106/427] 뉴보텍(060260) 처리 중...
2025-11-28 15:09:25 [INFO] [107/427] 동양에스텍(060380) 처리 중...
2025-11-28 15:09:30 [INFO] [108/427] 국일신동(060480) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:09:36 [INFO] [109/427] 이엘피(063760) 처리 중...
2025-11-28 15:09:41 [INFO] [110/427] 지엔코(065060) 처리 중...
2025-11-28 15:09:47 [INFO] [111/427] 대산F&B(065150) 처리 중...
2025-11-28 15:09:52 [INFO] [112/427] 비엘팜텍(065170) 처리 중...
2025-11-28 15:09:57 [INFO] [113/427] 에스아이리소스(065420) 처리 중...
2025-11-28 15:10:01 [INFO] [114/427] 삼영이엔씨(065570) 처리 중...
2025-11-28 15:10:04 [INFO] [115/427] 하이퍼코퍼레이션(065650) 처리 중...
2025-11-28 15:10:08 [INFO] [BATCH SAVE] 회사 10개 묶어서 DB 저장 시도...
2025-11-28 15:10:11 [INFO] [BATCH] 43666 rows saved into korea_fs_data_from_DART
2025-11-28 15:10:11 [INFO] [BATCH SAVE] 저장 완료 (회사 10개)
2025-11-28 15:10:11 [INFO] [116/427] 파커스(065690) 처리 중...
2025-11-28 15:10:15 [INFO] [117/427] CS(065770) 처리 중...
2025-11-28 15:10:21 [INFO] [118/427] 제노텍(066830) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:10:27 [WARNING] 제노텍(066830) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:10:27 [INFO] [119/427] 이씨에스(067010) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:10:34 [INFO] [120/427] 로지시스(067730) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:10:42 [INFO] [121/427] 세진티에스(067770) 처리 중...
2025-11-28 15:10:48 [INFO] [122/427] 케이웨더(068100) 처리 중...
2025-11-28 15:10:51 [INFO] [123/427] 누리플랜(069140) 처리 중...
2025-11-28 15:10:56 [INFO] [124/427] 유아이디(069330) 처리 중...
2025-11-28 15:11:00 [INFO] [125/427] 한세엠케이(069640) 처리 중...
2025-11-28 15:11:05 [INFO] [126/427] 엑스큐어(070300) 처리 중...
2025-11-28 15:11:08 [INFO] [BATCH SAVE] 회사 10개 묶어서 DB 저장 시도...
2025-11-28 15:11:10 [INFO] [BATCH] 41074 rows saved into korea_fs_data_from_DART
2025-11-28 15:11:10 [INFO] [BATCH SAVE] 저장 완료 (회사 10개)
2025-11-28 15:11:10 [INFO] [127/427] 한솔인티큐브(070590) 처리 중...
2025-11-28 15:11:14 [INFO] [128/427] 듀오백(073190) 처리 중...
2025-11-28 15:11:19 [INFO] [129/427] 에프알텍(073540) 처리 중...
2025-11-28 15:11:24 [INFO] [130/427] 웰크론한텍(076080) 처리 중...
2025-11-28 15:11:29 [INFO] [131/427] 지에이이노더스(076340) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:11:35 [WARNING] 지에이이노더스(076340) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:11:35 [INFO] [132/427] 해성옵틱스(076610) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:11:42 [INFO] [133/427] 케스피온(079190) 처리 중...
2025-11-28 15:11:47 [INFO] [134/427] 서산(079650) 처리 중...
2025-11-28 15:11:51 [INFO] [135/427] 인베니아(079950) 처리 중...
2025-11-28 15:11:56 [INFO] [136/427] 투비소프트(079970) 처리 중...
2025-11-28 15:12:01 [INFO] [137/427] 성창오토텍(080470) 처리 중...
2025-11-28 15:12:06 [INFO] [BATCH SAVE] 회사 10개 묶어서 DB 저장 시도...
2025-11-28 15:12:10 [INFO] [BATCH] 60630 rows saved into korea_fs_data_from_DART
2025-11-28 15:12:10 [INFO] [BATCH SAVE] 저장 완료 (회사 10개)
2025-11-28 15:12:10 [INFO] [138/427] 한국유니온제약(080720) 처리 중...
2025-11-28 15:12:14 [INFO] [139/427] 이엠앤아이(083470) 처리 중...
2025-11-28 15:12:20 [INFO] [140/427] 인콘(083640) 처리 중...
2025-11-28 15:12:25 [INFO] [141/427] 유비온(084440) 처리 중...
2025-11-28 15:12:28 [INFO] [142/427] 티비에이치글로벌(084870) 처리 중...
2025-11-28 15:12:32 [INFO] [143/427] 알티캐스트(085810) 처리 중...
2025-11-28 15:12:37 [INFO] [144/427] 광동헬스바이오(086220) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:12:43 [INFO] [145/427] 진도(088790) 처리 중...
2025-11-28 15:12:48 [INFO] [146/427] THE E&M(089230) 처리 중...
2025-11-28 15:12:53 [INFO] [147/427] 아이윈(090150) 처리 중...
2025-11-28 15:12:58 [INFO] [BATCH SAVE] 회사 10개 묶어서 DB 저장 시도...
2025-11-28 15:13:00 [INFO] [BATCH] 42584 rows saved into korea_fs_data_from_DART
2025-11-28 15:13:00 [INFO] [BATCH SAVE] 저장 완료 (회사 10개)
2025-11-28 15:13:00 [INFO] [148/427] S&K폴리텍(091340) 처리 중...
2025-11-28 15:13:05 [INFO] [149/427] 나노캠텍(091970) 처리 중...
2025-11-28 15:13:10 [INFO] [150/427] 럭스피아(092590) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:13:16 [WARNING] 럭스피아(092590) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:13:16 [INFO] [151/427] 앤씨앤(092600) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:13:21 [INFO] [152/427] 풍강(093380) 처리 중...
2025-11-28 15:13:26 [INFO] [153/427] 엔지브이아이(093510) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:13:32 [WARNING] 엔지브이아이(093510) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:13:32 [INFO] [154/427] 네오리진(094860) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:13:37 [INFO] [155/427] 엘디티(096870) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:13:44 [INFO] [156/427] 에스티오(098660) 처리 중...
2025-11-28 15:13:49 [INFO] [157/427] KS인더스트리(101000) 처리 중...
2025-11-28 15:13:54 [INFO] [158/427] 아이엠(101390) 처리 중...
2025-11-28 15:13:59 [INFO] [159/427] 엔시트론(101400) 처리 중...
2025-11-28 15:14:05 [INFO] [BATCH SAVE] 회사 10개 묶어서 DB 저장 시도...
2025-11-28 15:14:08 [INFO] [BATCH] 56027 rows saved into korea_fs_data_from_DART
2025-11-28 15:14:08 [INFO] [BATCH SAVE] 저장 완료 (회사 10개)
2025-11-28 15:14:08 [INFO] [160/427] 한국정밀기계(101680) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:14:15 [INFO] [161/427] 아하(102950) 처리 중...
2025-11-28 15:14:18 [INFO] [162/427] 에스앤더블류(103230) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:14:25 [INFO] [163/427] 씨앗(103660) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:14:31 [WARNING] 씨앗(103660) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:14:31 [INFO] [164/427] 케이이엠텍(106080) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:14:35 [INFO] [165/427] 파인테크닉스(106240) 처리 중...
2025-11-28 15:14:40 [INFO] [166/427] 노블엠앤비(106520) 처리 중...
2025-11-28 15:14:45 [INFO] [167/427] 전진바이오팜(110020) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:14:51 [INFO] [168/427] KC산업(112190) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:14:57 [WARNING] KC산업(112190) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:14:57 [INFO] [169/427] 디젠스(113810) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:15:02 [INFO] [170/427] 대주이엔티(114920) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:15:08 [WARNING] 대주이엔티(114920) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:15:08 [INFO] [171/427] 씨엔플러스(115530) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:15:13 [INFO] [172/427] 스타플렉스(115570) 처리 중...
2025-11-28 15:15:17 [INFO] [BATCH SAVE] 회사 10개 묶어서 DB 저장 시도...
2025-11-28 15:15:20 [INFO] [BATCH] 53345 rows saved into korea_fs_data_from_DART
2025-11-28 15:15:20 [INFO] [BATCH SAVE] 저장 완료 (회사 10개)
2025-11-28 15:15:20 [INFO] [173/427] 이미지스(115610) 처리 중...
2025-11-28 15:15:23 [INFO] [174/427] 태양기계(116100) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:15:29 [WARNING] 태양기계(116100) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:15:29 [INFO] [175/427] 유니포인트(121060) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:15:35 [WARNING] 유니포인트(121060) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:15:35 [INFO] [176/427] 코이즈(121850) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:15:39 [INFO] [177/427] 에스디시스템(121890) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:15:46 [INFO] [178/427] 알톤(123750) 처리 중...
2025-11-28 15:15:50 [INFO] [179/427] 티피씨글로벌(130740) 처리 중...
2025-11-28 15:15:54 [INFO] [180/427] 딜리(131180) 처리 중...
2025-11-28 15:15:59 [INFO] [181/427] 이퓨쳐(134060) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:16:05 [INFO] [182/427] 큐엠씨(136660) 처리 중...
2025-11-28 15:16:08 [INFO] [183/427] 넥스트아이(137940) 처리 중...
2025-11-28 15:16:13 [INFO] [184/427] BF랩스(139050) 처리 중...
2025-11-28 15:16:17 [INFO] [BATCH SAVE] 회사 10개 묶어서 DB 저장 시도...
2025-11-28 15:16:19 [INFO] [BATCH] 46089 rows saved into korea_fs_data_from_DART
2025-11-28 15:16:19 [INFO] [BATCH SAVE] 저장 완료 (회사 10개)
2025-11-28 15:16:19 [INFO] [185/427] 키네마스터(139670) 처리 중...
2025-11-28 15:16:24 [INFO] [186/427] 카티스(140430) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:16:31 [INFO] [187/427] 위월드(140660) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:16:37 [WARNING] 위월드(140660) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:16:37 [INFO] [188/427] 에이리츠(140910) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:16:44 [INFO] [189/427] 핸즈코퍼레이션(143210) 처리 중...
2025-11-28 15:16:48 [INFO] [190/427] 다이나믹디자인(145210) 처리 중...
2025-11-28 15:16:53 [INFO] [191/427] 율촌(146060) 처리 중...
2025-11-28 15:16:58 [INFO] [192/427] 아이케이세미콘(149010) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:17:04 [WARNING] 아이케이세미콘(149010) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:17:04 [INFO] [193/427] 아퓨어스(149300) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:17:10 [WARNING] 아퓨어스(149300) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:17:10 [INFO] [194/427] 한국ANKOR유전(152550) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:17:17 [WARNING] 한국ANKOR유전(152550) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:17:17 [INFO] [195/427] 아시아종묘(154030) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:17:21 [INFO] [196/427] 다산솔루에타(154040) 처리 중...
2025-11-28 15:17:26 [INFO] [197/427] 에코글로우(159910) 처리 중...
2025-11-28 15:17:31 [INFO] [198/427] 코스텍시스템(169670) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:17:36 [WARNING] 코스텍시스템(169670) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:17:36 [INFO] [199/427] 장원테크(174880) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:17:41 [INFO] [BATCH SAVE] 회사 10개 묶어서 DB 저장 시도...
2025-11-28 15:17:44 [INFO] [BATCH] 44407 rows saved into korea_fs_data_from_DART
2025-11-28 15:17:44 [INFO] [BATCH SAVE] 저장 완료 (회사 10개)
2025-11-28 15:17:44 [INFO] [200/427] 코나솔(176590) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:17:50 [WARNING] 코나솔(176590) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:17:50 [INFO] [201/427] 베셀(177350) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:17:54 [INFO] [202/427] 대동고려삼(178600) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:18:00 [WARNING] 대동고려삼(178600) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:18:00 [INFO] [203/427] 머니무브(179720) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:18:06 [WARNING] 머니무브(179720) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:18:06 [INFO] [204/427] 수프로(185190) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:18:12 [WARNING] 수프로(185190) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:18:12 [INFO] [205/427] 디티앤씨(187220) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:18:17 [INFO] [206/427] 세니젠(188260) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:18:23 [INFO] [207/427] 코셋(189350) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:18:29 [WARNING] 코셋(189350) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:18:29 [INFO] [208/427] 서전기전(189860) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:18:33 [INFO] [209/427] 육일씨엔에쓰(191410) 처리 중...
2025-11-28 15:18:38 [INFO] [210/427] 블루탑(191600) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:18:44 [WARNING] 블루탑(191600) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:18:44 [INFO] [211/427] 윈하이텍(192390) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:18:48 [INFO] [212/427] 링크드(193250) 처리 중...
2025-11-28 15:18:54 [INFO] [213/427] 웹스(196700) 처리 중...
2025-11-28 15:18:58 [INFO] [214/427] 디지캡(197140) 처리 중...
2025-11-28 15:19:02 [INFO] [215/427] 한주라이트메탈(198940) 처리 중...
2025-11-28 15:19:06 [INFO] [BATCH SAVE] 회사 10개 묶어서 DB 저장 시도...
2025-11-28 15:19:09 [INFO] [BATCH] 40556 rows saved into korea_fs_data_from_DART
2025-11-28 15:19:09 [INFO] [BATCH SAVE] 저장 완료 (회사 10개)
2025-11-28 15:19:09 [INFO] [216/427] 데이터스트림즈(199150) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:19:15 [WARNING] 데이터스트림즈(199150) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:19:15 [INFO] [217/427] 바이오프로테크(199290) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:19:21 [WARNING] 바이오프로테크(199290) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:19:21 [INFO] [218/427] 바이오인프라(199730) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:19:27 [INFO] [219/427] 판도라티비(202960) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:19:34 [WARNING] 판도라티비(202960) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:19:34 [INFO] [220/427] 스타에스엠리츠(204210) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:19:37 [INFO] [221/427] 스튜디오산타클로스(204630) 처리 중...
2025-11-28 15:19:42 [INFO] [222/427] 볼빅(206950) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:19:48 [WARNING] 볼빅(206950) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:19:48 [INFO] [223/427] 에이펙스인텍(207490) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:19:54 [WARNING] 에이펙스인텍(207490) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:19:54 [INFO] [224/427] 지란지교시큐리티(208350) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:19:59 [INFO] [225/427] 포톤(208710) 처리 중...
2025-11-28 15:20:04 [INFO] [226/427] 이비테크(208850) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:20:10 [WARNING] 이비테크(208850) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:20:10 [INFO] [227/427] 미래엔에듀파트너(208890) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:20:16 [WARNING] 미래엔에듀파트너(208890) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:20:16 [INFO] [228/427] 캔버스엔(210120) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:20:19 [INFO] [229/427] 오건에코텍(212310) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:20:25 [WARNING] 오건에코텍(212310) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:20:25 [INFO] [230/427] 롤링스톤(214610) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:20:29 [INFO] [231/427] 토박스코리아(215480) 처리 중...
2025-11-28 15:20:33 [INFO] [232/427] 크로넥스(215570) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:20:39 [WARNING] 크로넥스(215570) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:20:39 [INFO] [233/427] 이노인스트루먼트(215790) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:20:44 [INFO] [234/427] 인바이츠바이오코아(216400) 처리 중...
2025-11-28 15:20:47 [INFO] [BATCH SAVE] 회사 10개 묶어서 DB 저장 시도...
2025-11-28 15:20:48 [INFO] [BATCH] 31758 rows saved into korea_fs_data_from_DART
2025-11-28 15:20:48 [INFO] [BATCH SAVE] 저장 완료 (회사 10개)
2025-11-28 15:20:48 [INFO] [235/427] 썬테크(217320) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:20:55 [WARNING] 썬테크(217320) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:20:55 [INFO] [236/427] 선샤인푸드(217620) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:20:59 [INFO] [237/427] 틸론(217880) 처리 중...
2025-11-28 15:21:02 [INFO] [238/427] 에스제이켐(217910) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:21:08 [WARNING] 에스제이켐(217910) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:21:08 [INFO] [239/427] 디와이디(219550) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:21:11 [INFO] [240/427] 플럼라인생명과학(222670) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:21:17 [WARNING] 플럼라인생명과학(222670) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:21:17 [INFO] [241/427] 로지스몬(223220) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:21:23 [WARNING] 로지스몬(223220) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:21:23 [INFO] [242/427] 더코디(224060) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:21:28 [INFO] [243/427] 엔에스컴퍼니(224760) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:21:34 [WARNING] 엔에스컴퍼니(224760) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:21:34 [INFO] [244/427] 엄지하우스(224810) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:21:41 [WARNING] 엄지하우스(224810) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:21:41 [INFO] [245/427] 케이엠제약(225430) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:21:49 [INFO] [246/427] 패션플랫폼(225590) 처리 중...
2025-11-28 15:21:53 [INFO] [247/427] 본느(226340) 처리 중...
2025-11-28 15:21:58 [INFO] [248/427] 퀀텀온(227100) 처리 중...
2025-11-28 15:22:02 [INFO] [249/427] 젠큐릭스(229000) 처리 중...
2025-11-28 15:22:07 [INFO] [250/427] 비유테크놀러지(230980) 처리 중...
2025-11-28 15:22:12 [INFO] [BATCH SAVE] 회사 10개 묶어서 DB 저장 시도...
2025-11-28 15:22:14 [INFO] [BATCH] 37304 rows saved into korea_fs_data_from_DART
2025-11-28 15:22:14 [INFO] [BATCH SAVE] 저장 완료 (회사 10개)
2025-11-28 15:22:14 [INFO] [251/427] 아이티센피엔에스(232830) 처리 중...
2025-11-28 15:22:17 [INFO] [252/427] 메디안디노스틱(233250) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:22:22 [WARNING] 메디안디노스틱(233250) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:22:22 [INFO] [253/427] 질경이(233990) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:22:26 [INFO] [254/427] 에이원알폼(234070) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:22:32 [WARNING] 에이원알폼(234070) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:22:32 [INFO] [255/427] 씨알푸드(236030) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:22:38 [WARNING] 씨알푸드(236030) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:22:38 [INFO] [256/427] 메디젠휴먼케어(236340) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:22:40 [INFO] [257/427] 피앤씨테크(237750) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:22:48 [INFO] [258/427] 엔에스엠(238170) 처리 중...
2025-11-28 15:22:51 [INFO] [259/427] 비피도(238200) 처리 중...
2025-11-28 15:22:55 [INFO] [260/427] 로보쓰리에이아이(238500) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:23:03 [INFO] [261/427] 유진테크놀로지(240600) 처리 중...
2025-11-28 15:23:07 [INFO] [262/427] 피씨엘(241820) 처리 중...
2025-11-28 15:23:10 [INFO] [263/427] 아이티센코어(243870) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:23:16 [WARNING] 아이티센코어(243870) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:23:16 [INFO] [264/427] 올리패스(244460) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:23:21 [INFO] [BATCH SAVE] 회사 10개 묶어서 DB 저장 시도...
2025-11-28 15:23:22 [INFO] [BATCH] 17358 rows saved into korea_fs_data_from_DART
2025-11-28 15:23:22 [INFO] [BATCH SAVE] 저장 완료 (회사 10개)
2025-11-28 15:23:22 [INFO] [265/427] 나눔테크(244880) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:23:28 [WARNING] 나눔테크(244880) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:23:28 [INFO] [266/427] 씨앤에스링크(245450) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:23:34 [WARNING] 씨앤에스링크(245450) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:23:34 [INFO] [267/427] 에스엘에스바이오(246250) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:23:41 [INFO] [268/427] 나노씨엠에스(247660) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:23:48 [INFO] [269/427] 진코스텍(250030) 처리 중...
2025-11-28 15:23:52 [INFO] [270/427] 예선테크(250930) 처리 중...
2025-11-28 15:23:56 [INFO] [271/427] 안지오랩(251280) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:24:02 [WARNING] 안지오랩(251280) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:24:02 [INFO] [272/427] 루트락(253610) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:24:08 [WARNING] 루트락(253610) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:24:08 [INFO] [273/427] 제이엠멀티(254160) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:24:14 [WARNING] 제이엠멀티(254160) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:24:14 [INFO] [274/427] 피엔티엠에스(257370) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:24:18 [INFO] [275/427] 테크트랜스(258050) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:24:24 [WARNING] 테크트랜스(258050) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:24:24 [INFO] [276/427] 세종메디칼(258830) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:24:28 [INFO] [277/427] 뿌리깊은나무들(266170) 처리 중...
2025-11-28 15:24:52 [ERROR] 뿌리깊은나무들(266170) 처리 중 오류 발생: HTTPSConnectionPool(host='opendart.fss.or.kr', port=443): Max retries exceeded with url: /api/fnlttSinglAcntAll.json?crtfc_key=50424484a46daa88b34fcf875f40ca12b79e1fc1&corp_code=00990396&bsns_year=2025&reprt_code=11014&fs_div=CFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020AF3995BE0>: Failed to establish a new connection: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다'))
2025-11-28 15:24:52 [INFO] [278/427] 팡스카이(266350) 처리 중...
2025-11-28 15:24:55 [INFO] [279/427] 바이오인프라생명과학(266470) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:25:01 [WARNING] 바이오인프라생명과학(266470) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:25:01 [INFO] [280/427] 파워풀엑스(266870) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:25:07 [WARNING] 파워풀엑스(266870) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:25:07 [INFO] [281/427] 세븐브로이맥주(267080) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:25:11 [INFO] [282/427] 배럴(267790) 처리 중...
2025-11-28 15:25:15 [INFO] [283/427] 에스에스알(275630) 처리 중...
2025-11-28 15:25:18 [INFO] [BATCH SAVE] 회사 10개 묶어서 DB 저장 시도...
2025-11-28 15:25:19 [INFO] [BATCH] 18433 rows saved into korea_fs_data_from_DART
2025-11-28 15:25:19 [INFO] [BATCH SAVE] 저장 완료 (회사 10개)
2025-11-28 15:25:19 [INFO] [284/427] 스코넥(276040) 처리 중...
2025-11-28 15:25:23 [INFO] [285/427] 엘리비젼(276240) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:25:29 [WARNING] 엘리비젼(276240) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:25:29 [INFO] [286/427] 한울앤제주(276730) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:25:32 [INFO] [287/427] EMB(278990) 처리 중...
2025-11-28 15:25:35 [INFO] [288/427] 이노벡스(279060) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:25:42 [WARNING] 이노벡스(279060) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:25:42 [INFO] [289/427] 진영(285800) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:25:45 [INFO] [290/427] 나라소프트(288490) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:25:51 [WARNING] 나라소프트(288490) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:25:51 [INFO] [291/427] 아이스크림에듀(289010) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:25:54 [INFO] [292/427] 바이오텐(289170) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:26:00 [WARNING] 바이오텐(289170) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:26:00 [INFO] [293/427] 신도기연(290520) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:26:04 [INFO] [294/427] 신시웨이(290560) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:26:10 [INFO] [295/427] 압타머사이언스(291650) 처리 중...
2025-11-28 15:26:13 [INFO] [296/427] 가이아코퍼레이션(296520) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:26:19 [WARNING] 가이아코퍼레이션(296520) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:26:19 [INFO] [297/427] 이노룰스(296640) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:26:23 [INFO] [298/427] 지앤이헬스케어(299480) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:26:29 [WARNING] 지앤이헬스케어(299480) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:26:29 [INFO] [299/427] 더콘텐츠온(302920) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:26:35 [WARNING] 더콘텐츠온(302920) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:26:35 [INFO] [300/427] 지니틱스(303030) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:26:41 [INFO] [BATCH SAVE] 회사 10개 묶어서 DB 저장 시도...
2025-11-28 15:26:42 [INFO] [BATCH] 15061 rows saved into korea_fs_data_from_DART
2025-11-28 15:26:42 [INFO] [BATCH SAVE] 저장 완료 (회사 10개)
2025-11-28 15:26:42 [INFO] [301/427] 테크엔(308700) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:26:48 [WARNING] 테크엔(308700) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:26:48 [INFO] [302/427] 디와이씨(310870) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:26:51 [INFO] [303/427] 엘에이티(311060) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:26:57 [INFO] [304/427] 인터로이드(311960) 처리 중...
2025-11-28 15:27:00 [INFO] [305/427] 에이에프더블류(312610) 처리 중...
2025-11-28 15:27:04 [INFO] [306/427] 캐리(313760) 처리 중...
2025-11-28 15:27:07 [INFO] [307/427] 라닉스(317120) 처리 중...
2025-11-28 15:27:11 [INFO] [308/427] TS트릴리온(317240) 처리 중...
2025-11-28 15:27:15 [INFO] [309/427] 노드메이슨(317860) 처리 중...
2025-11-28 15:27:18 [INFO] [310/427] 팜스빌(318010) 처리 중...
2025-11-28 15:27:22 [INFO] [311/427] 타임기술(318660) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:27:28 [WARNING] 타임기술(318660) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:27:28 [INFO] [312/427] 무진메디(322970) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:27:33 [WARNING] 무진메디(322970) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:27:33 [INFO] [313/427] 펨토바이오메드(327610) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:27:39 [WARNING] 펨토바이오메드(327610) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:27:39 [INFO] [314/427] 솔트웨어(328380) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:27:42 [INFO] [BATCH SAVE] 회사 10개 묶어서 DB 저장 시도...
2025-11-28 15:27:43 [INFO] [BATCH] 14158 rows saved into korea_fs_data_from_DART
2025-11-28 15:27:43 [INFO] [BATCH SAVE] 저장 완료 (회사 10개)
2025-11-28 15:27:43 [INFO] [315/427] 밸로프(331520) 처리 중...
2025-11-28 15:27:47 [INFO] [316/427] 한국미라클피플사(331660) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:27:53 [WARNING] 한국미라클피플사(331660) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:27:53 [INFO] [317/427] 셀레믹스(331920) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:27:56 [INFO] [318/427] 오션스바이오(332190) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:28:02 [WARNING] 오션스바이오(332190) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:28:02 [INFO] [319/427] 윙스풋(335870) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:28:09 [INFO] [320/427] 타스컴(336040) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:28:15 [WARNING] 타스컴(336040) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:28:15 [INFO] [321/427] 퓨쳐메디신(341170) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:28:17 [INFO] [322/427] 이앤에치(341310) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:28:23 [WARNING] 이앤에치(341310) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:28:23 [INFO] [323/427] 이노진(344860) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:28:30 [INFO] [324/427] 타이드(346010) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:28:35 [WARNING] 타이드(346010) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:28:35 [INFO] [325/427] 미쥬(351020) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:28:38 [INFO] [326/427] 셀레스트라(352770) 처리 중...
2025-11-28 15:28:44 [INFO] [327/427] 인바이오(352940) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:28:51 [INFO] [328/427] 휴럼(353190) 처리 중...
2025-11-28 15:28:54 [INFO] [329/427] 에이텀(355690) 처리 중...
2025-11-28 15:28:58 [INFO] [BATCH SAVE] 회사 10개 묶어서 DB 저장 시도...
2025-11-28 15:28:59 [INFO] [BATCH] 15258 rows saved into korea_fs_data_from_DART
2025-11-28 15:28:59 [INFO] [BATCH SAVE] 저장 완료 (회사 10개)
2025-11-28 15:28:59 [INFO] [330/427] 삼영에스앤씨(361670) 처리 중...
2025-11-28 15:29:02 [INFO] [331/427] 드림인사이트(362990) 처리 중...
2025-11-28 15:29:05 [INFO] [332/427] 브이씨(365900) 처리 중...
2025-11-28 15:29:09 [INFO] [333/427] 창대정밀(368030) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:29:14 [WARNING] 창대정밀(368030) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:29:14 [INFO] [334/427] 아이씨에이치(368600) 처리 중...

[WARN] CFS/OFS 모두 자료 없음

2025-11-28 15:29:18 [INFO] [335/427] 오에스피(368970) 처리 중...
2025-11-28 15:29:21 [INFO] [336/427] 아이티아이즈(372800) 처리 중...
2025-11-28 15:29:25 [INFO] [337/427] 엑셀세라퓨틱스(373110) 처리 중...
2025-11-28 15:29:30 [INFO] [338/427] 이지트로닉스(377330) 처리 중...
2025-11-28 15:29:33 [INFO] [339/427] 이성씨엔아이(379390) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:29:40 [WARNING] 이성씨엔아이(379390) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:29:40 [INFO] [340/427] 유디엠텍(389680) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:29:45 [WARNING] 유디엠텍(389680) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:29:45 [INFO] [341/427] 애니메디솔루션(390110) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:29:50 [WARNING] 애니메디솔루션(390110) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:29:50 [INFO] [342/427] 켈스(402420) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:29:55 [WARNING] 켈스(402420) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:29:55 [INFO] [343/427] 라피치(403360) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:30:00 [WARNING] 라피치(403360) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:30:00 [INFO] [344/427] 아이엘커누스(403810) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:30:05 [WARNING] 아이엘커누스(403810) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:30:05 [INFO] [345/427] 플라즈맵(405000) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:30:10 [WARNING] 플라즈맵(405000) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:30:10 [INFO] [346/427] 나라셀라(405920) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:30:14 [WARNING] 나라셀라(405920) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:30:14 [INFO] [347/427] 레이저쎌(412350) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:30:20 [WARNING] 레이저쎌(412350) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:30:20 [INFO] [348/427] 티엘엔지니어링(413300) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:30:24 [WARNING] 티엘엔지니어링(413300) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:30:24 [INFO] [349/427] 스튜디오삼익(415380) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:30:29 [WARNING] 스튜디오삼익(415380) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:30:29 [INFO] [350/427] E8(418620) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:30:34 [WARNING] E8(418620) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:30:34 [INFO] [351/427] 벨로크(424760) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:30:39 [WARNING] 벨로크(424760) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:30:39 [INFO] [352/427] 시지트로닉스(429270) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:30:44 [WARNING] 시지트로닉스(429270) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:30:44 [INFO] [353/427] 엠에프씨(432980) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:30:49 [WARNING] 엠에프씨(432980) : 재무데이터 없음 (fs_df empty)
2025-11-28 15:30:49 [INFO] [354/427] 유안타제11호스팩(444920) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-28 15:30:53 [ERROR] 유안타제11호스팩(444920) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:53 [INFO] [355/427] 유안타제12호스팩(446150) 처리 중...
2025-11-28 15:30:53 [ERROR] 유안타제12호스팩(446150) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:53 [INFO] [356/427] 아이오바이오(447690) 처리 중...
2025-11-28 15:30:53 [ERROR] 아이오바이오(447690) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:53 [INFO] [357/427] IBKS제22호스팩(448760) 처리 중...
2025-11-28 15:30:53 [ERROR] IBKS제22호스팩(448760) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:53 [INFO] [358/427] 마이크로엔엑스(448780) 처리 중...
2025-11-28 15:30:53 [ERROR] 마이크로엔엑스(448780) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:53 [INFO] [359/427] 미래에셋비전스팩3호(448830) 처리 중...
2025-11-28 15:30:53 [ERROR] 미래에셋비전스팩3호(448830) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:53 [INFO] [360/427] 하이제8호스팩(450050) 처리 중...
2025-11-28 15:30:53 [ERROR] 하이제8호스팩(450050) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:53 [INFO] [361/427] 유안타제14호스팩(450940) 처리 중...
2025-11-28 15:30:53 [ERROR] 유안타제14호스팩(450940) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:53 [INFO] [362/427] 엔에이치스팩29호(451700) 처리 중...
2025-11-28 15:30:53 [ERROR] 엔에이치스팩29호(451700) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:53 [INFO] [363/427] 상상인제4호스팩(452670) 처리 중...
2025-11-28 15:30:53 [ERROR] 상상인제4호스팩(452670) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:53 [INFO] [364/427] 하나29호스팩(454640) 처리 중...
2025-11-28 15:30:53 [ERROR] 하나29호스팩(454640) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:53 [INFO] [365/427] KB제25호스팩(455250) 처리 중...
2025-11-28 15:30:53 [ERROR] KB제25호스팩(455250) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:53 [INFO] [366/427] 한화플러스제4호스팩(455310) 처리 중...
2025-11-28 15:30:53 [ERROR] 한화플러스제4호스팩(455310) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:53 [INFO] [367/427] SK증권제9호스팩(455910) 처리 중...
2025-11-28 15:30:53 [ERROR] SK증권제9호스팩(455910) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:53 [INFO] [368/427] 큐라켐(456190) 처리 중...
2025-11-28 15:30:53 [ERROR] 큐라켐(456190) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:53 [INFO] [369/427] 교보14호스팩(456490) 처리 중...
2025-11-28 15:30:53 [ERROR] 교보14호스팩(456490) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:53 [INFO] [370/427] 길교이앤씨(456700) 처리 중...
2025-11-28 15:30:53 [ERROR] 길교이앤씨(456700) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:53 [INFO] [371/427] 대신밸런스제16호스팩(457630) 처리 중...
2025-11-28 15:30:53 [ERROR] 대신밸런스제16호스팩(457630) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:53 [INFO] [372/427] SK증권제10호스팩(457940) 처리 중...
2025-11-28 15:30:53 [ERROR] SK증권제10호스팩(457940) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:53 [INFO] [373/427] 한국제12호스팩(458610) 처리 중...
2025-11-28 15:30:53 [ERROR] 한국제12호스팩(458610) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:53 [INFO] [374/427] 에이치엠씨제6호스팩(462020) 처리 중...
2025-11-28 15:30:53 [ERROR] 에이치엠씨제6호스팩(462020) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:53 [INFO] [375/427] 한국제13호스팩(464440) 처리 중...
2025-11-28 15:30:53 [ERROR] 한국제13호스팩(464440) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:53 [INFO] [376/427] KB제27호스팩(464680) 처리 중...
2025-11-28 15:30:53 [ERROR] KB제27호스팩(464680) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:53 [INFO] [377/427] 교보15호스팩(465320) 처리 중...
2025-11-28 15:30:53 [ERROR] 교보15호스팩(465320) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:53 [INFO] [378/427] 엔에이치스팩30호(466910) 처리 중...
2025-11-28 15:30:53 [ERROR] 엔에이치스팩30호(466910) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:53 [INFO] [379/427] IBKS제23호스팩(467930) 처리 중...
2025-11-28 15:30:53 [ERROR] IBKS제23호스팩(467930) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:53 [INFO] [380/427] 유진스팩10호(468760) 처리 중...
2025-11-28 15:30:53 [ERROR] 유진스팩10호(468760) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:53 [INFO] [381/427] IBKS제24호스팩(469480) 처리 중...
2025-11-28 15:30:54 [ERROR] IBKS제24호스팩(469480) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:54 [INFO] [382/427] 하나30호스팩(469880) 처리 중...
2025-11-28 15:30:54 [ERROR] 하나30호스팩(469880) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:54 [INFO] [383/427] 하나31호스팩(469900) 처리 중...
2025-11-28 15:30:54 [ERROR] 하나31호스팩(469900) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:54 [INFO] [384/427] 대신밸런스제17호스팩(471050) 처리 중...
2025-11-28 15:30:54 [ERROR] 대신밸런스제17호스팩(471050) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:54 [INFO] [385/427] 신영스팩10호(472220) 처리 중...
2025-11-28 15:30:54 [ERROR] 신영스팩10호(472220) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:54 [INFO] [386/427] SK증권제11호스팩(472230) 처리 중...
2025-11-28 15:30:54 [ERROR] SK증권제11호스팩(472230) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:54 [INFO] [387/427] SK증권제12호스팩(473000) 처리 중...
2025-11-28 15:30:54 [ERROR] SK증권제12호스팩(473000) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:54 [INFO] [388/427] 유안타제15호스팩(473050) 처리 중...
2025-11-28 15:30:54 [ERROR] 유안타제15호스팩(473050) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:54 [INFO] [389/427] 비엔케이제2호스팩(473370) 처리 중...
2025-11-28 15:30:54 [ERROR] 비엔케이제2호스팩(473370) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:54 [INFO] [390/427] SK증권제13호스팩(473950) 처리 중...
2025-11-28 15:30:54 [ERROR] SK증권제13호스팩(473950) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:54 [INFO] [391/427] 유안타제16호스팩(474490) 처리 중...
2025-11-28 15:30:54 [ERROR] 유안타제16호스팩(474490) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:54 [INFO] [392/427] 신한제12호스팩(474660) 처리 중...
2025-11-28 15:30:54 [ERROR] 신한제12호스팩(474660) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:54 [INFO] [393/427] 신한제13호스팩(474930) 처리 중...
2025-11-28 15:30:54 [ERROR] 신한제13호스팩(474930) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:54 [INFO] [394/427] 하나32호스팩(475240) 처리 중...
2025-11-28 15:30:54 [ERROR] 하나32호스팩(475240) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:54 [INFO] [395/427] 하나33호스팩(475250) 처리 중...
2025-11-28 15:30:54 [ERROR] 하나33호스팩(475250) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:54 [INFO] [396/427] 타조이엔터테인먼트(476710) 처리 중...
2025-11-28 15:30:54 [ERROR] 타조이엔터테인먼트(476710) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:54 [INFO] [397/427] 에이치엠씨제7호스팩(477340) 처리 중...
2025-11-28 15:30:54 [ERROR] 에이치엠씨제7호스팩(477340) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:54 [INFO] [398/427] 미래에셋비전스팩4호(477380) 처리 중...
2025-11-28 15:30:54 [ERROR] 미래에셋비전스팩4호(477380) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:54 [INFO] [399/427] 미래에셋비전스팩5호(477470) 처리 중...
2025-11-28 15:30:54 [ERROR] 미래에셋비전스팩5호(477470) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:54 [INFO] [400/427] 디비금융스팩12호(477760) 처리 중...
2025-11-28 15:30:54 [ERROR] 디비금융스팩12호(477760) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:54 [INFO] [401/427] 이베스트스팩6호(478110) 처리 중...
2025-11-28 15:30:54 [ERROR] 이베스트스팩6호(478110) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:54 [INFO] [402/427] KB제29호스팩(478390) 처리 중...
2025-11-28 15:30:54 [ERROR] KB제29호스팩(478390) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:54 [INFO] [403/427] 미래에셋비전스팩6호(478440) 처리 중...
2025-11-28 15:30:54 [ERROR] 미래에셋비전스팩6호(478440) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:54 [INFO] [404/427] 대신밸런스제18호스팩(478780) 처리 중...
2025-11-28 15:30:54 [ERROR] 대신밸런스제18호스팩(478780) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:54 [INFO] [405/427] 한국제15호스팩(479880) 처리 중...
2025-11-28 15:30:54 [ERROR] 한국제15호스팩(479880) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:54 [INFO] [406/427] 엔에이치스팩31호(481890) 처리 중...
2025-11-28 15:30:54 [ERROR] 엔에이치스팩31호(481890) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:54 [INFO] [407/427] 교보16호스팩(482520) 처리 중...
2025-11-28 15:30:54 [ERROR] 교보16호스팩(482520) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:54 [INFO] [408/427] 미래에셋비전스팩7호(482680) 처리 중...
2025-11-28 15:30:54 [ERROR] 미래에셋비전스팩7호(482680) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:54 [INFO] [409/427] 대신밸런스제19호스팩(482690) 처리 중...
2025-11-28 15:30:54 [ERROR] 대신밸런스제19호스팩(482690) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:54 [INFO] [410/427] 하나34호스팩(484130) 처리 중...
2025-11-28 15:30:55 [ERROR] 하나34호스팩(484130) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:55 [INFO] [411/427] KB제30호스팩(486630) 처리 중...
2025-11-28 15:30:55 [ERROR] KB제30호스팩(486630) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:55 [INFO] [412/427] 신한제14호스팩(487360) 처리 중...
2025-11-28 15:30:55 [ERROR] 신한제14호스팩(487360) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:55 [INFO] [413/427] 키움제10호스팩(487720) 처리 중...
2025-11-28 15:30:55 [ERROR] 키움제10호스팩(487720) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:55 [INFO] [414/427] 신한제15호스팩(487830) 처리 중...
2025-11-28 15:30:55 [ERROR] 신한제15호스팩(487830) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:55 [INFO] [415/427] 유진스팩11호(488060) 처리 중...
2025-11-28 15:30:55 [ERROR] 유진스팩11호(488060) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:55 [INFO] [416/427] 교보17호스팩(489210) 처리 중...
2025-11-28 15:30:55 [ERROR] 교보17호스팩(489210) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:55 [INFO] [417/427] 키움제11호스팩(489480) 처리 중...
2025-11-28 15:30:55 [ERROR] 키움제11호스팩(489480) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:55 [INFO] [418/427] 디비금융제13호스팩(489730) 처리 중...
2025-11-28 15:30:55 [ERROR] 디비금융제13호스팩(489730) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:55 [INFO] [419/427] KB제31호스팩(492220) 처리 중...
2025-11-28 15:30:55 [ERROR] KB제31호스팩(492220) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:55 [INFO] [420/427] 유안타제17호스팩(493790) 처리 중...
2025-11-28 15:30:55 [ERROR] 유안타제17호스팩(493790) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:55 [INFO] [421/427] 신한제16호스팩(496070) 처리 중...
2025-11-28 15:30:55 [ERROR] 신한제16호스팩(496070) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:55 [INFO] [422/427] 본시스템즈(496320) 처리 중...
2025-11-28 15:30:55 [ERROR] 본시스템즈(496320) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:55 [INFO] [423/427] 한화플러스제5호스팩(498390) 처리 중...
2025-11-28 15:30:55 [ERROR] 한화플러스제5호스팩(498390) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:55 [INFO] [424/427] 글로벌에스엠(900070) 처리 중...
2025-11-28 15:30:55 [ERROR] 글로벌에스엠(900070) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:55 [INFO] [425/427] 애머릿지(900100) 처리 중...
2025-11-28 15:30:55 [ERROR] 애머릿지(900100) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:55 [INFO] [426/427] 이스트아시아홀딩스(900110) 처리 중...
2025-11-28 15:30:55 [ERROR] 이스트아시아홀딩스(900110) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:55 [INFO] [427/427] 씨엑스아이(900120) 처리 중...
2025-11-28 15:30:55 [ERROR] 씨엑스아이(900120) 처리 중 오류 발생: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
2025-11-28 15:30:55 [INFO] [FINAL BATCH SAVE] 남은 회사 8개 DB 저장 시도...
2025-11-28 15:30:56 [INFO] [BATCH] 12424 rows saved into korea_fs_data_from_DART
2025-11-28 15:30:56 [INFO] [FINAL BATCH SAVE] 저장 완료 (회사 8개)
2025-11-28 15:30:56 [INFO] 작업 완료. 지정 종목 수: 427, 에러 종목 수: 159

[에러 발생 종목 목록]
 - 0068Y0 / 비엔케이제3호스팩 / 재무데이터 없음 (fs_df empty)
 - 0091W0 / 신영스팩11호 / 재무데이터 없음 (fs_df empty)
 - 0093G0 / 미래에셋비전스팩8호 / 재무데이터 없음 (fs_df empty)
 - 025890 / 한국주강 / HTTPSConnectionPool(host='opendart.fss.or.kr', port=443): Max retries exceeded with url: /api/fnlttS
 - 052960 / 태양3C / 재무데이터 없음 (fs_df empty)
 - 066830 / 제노텍 / 재무데이터 없음 (fs_df empty)
 - 076340 / 지에이이노더스 / 재무데이터 없음 (fs_df empty)
 - 092590 / 럭스피아 / 재무데이터 없음 (fs_df empty)
 - 093510 / 엔지브이아이 / 재무데이터 없음 (fs_df empty)
 - 103660 / 씨앗 / 재무데이터 없음 (fs_df empty)
 - 112190 / KC산업 / 재무데이터 없음 (fs_df empty)
 - 114920 / 대주이엔티 / 재무데이터 없음 (fs_df empty)
 - 116100 / 태양기계 / 재무데이터 없음 (fs_df empty)
 - 121060 / 유니포인트 / 재무데이터 없음 (fs_df empty)
 - 140660 / 위월드 / 재무데이터 없음 (fs_df empty)
 - 149010 / 아이케이세미콘 / 재무데이터 없음 (fs_df empty)
 - 149300 / 아퓨어스 / 재무데이터 없음 (fs_df empty)
 - 152550 / 한국ANKOR유전 / 재무데이터 없음 (fs_df empty)
 - 169670 / 코스텍시스템 / 재무데이터 없음 (fs_df empty)
 - 176590 / 코나솔 / 재무데이터 없음 (fs_df empty)
 - 178600 / 대동고려삼 / 재무데이터 없음 (fs_df empty)
 - 179720 / 머니무브 / 재무데이터 없음 (fs_df empty)
 - 185190 / 수프로 / 재무데이터 없음 (fs_df empty)
 - 189350 / 코셋 / 재무데이터 없음 (fs_df empty)
 - 191600 / 블루탑 / 재무데이터 없음 (fs_df empty)
 - 199150 / 데이터스트림즈 / 재무데이터 없음 (fs_df empty)
 - 199290 / 바이오프로테크 / 재무데이터 없음 (fs_df empty)
 - 202960 / 판도라티비 / 재무데이터 없음 (fs_df empty)
 - 206950 / 볼빅 / 재무데이터 없음 (fs_df empty)
 - 207490 / 에이펙스인텍 / 재무데이터 없음 (fs_df empty)
 - 208850 / 이비테크 / 재무데이터 없음 (fs_df empty)
 - 208890 / 미래엔에듀파트너 / 재무데이터 없음 (fs_df empty)
 - 212310 / 오건에코텍 / 재무데이터 없음 (fs_df empty)
 - 215570 / 크로넥스 / 재무데이터 없음 (fs_df empty)
 - 217320 / 썬테크 / 재무데이터 없음 (fs_df empty)
 - 217910 / 에스제이켐 / 재무데이터 없음 (fs_df empty)
 - 222670 / 플럼라인생명과학 / 재무데이터 없음 (fs_df empty)
 - 223220 / 로지스몬 / 재무데이터 없음 (fs_df empty)
 - 224760 / 엔에스컴퍼니 / 재무데이터 없음 (fs_df empty)
 - 224810 / 엄지하우스 / 재무데이터 없음 (fs_df empty)
 - 233250 / 메디안디노스틱 / 재무데이터 없음 (fs_df empty)
 - 234070 / 에이원알폼 / 재무데이터 없음 (fs_df empty)
 - 236030 / 씨알푸드 / 재무데이터 없음 (fs_df empty)
 - 243870 / 아이티센코어 / 재무데이터 없음 (fs_df empty)
 - 244880 / 나눔테크 / 재무데이터 없음 (fs_df empty)
 - 245450 / 씨앤에스링크 / 재무데이터 없음 (fs_df empty)
 - 251280 / 안지오랩 / 재무데이터 없음 (fs_df empty)
 - 253610 / 루트락 / 재무데이터 없음 (fs_df empty)
 - 254160 / 제이엠멀티 / 재무데이터 없음 (fs_df empty)
 - 258050 / 테크트랜스 / 재무데이터 없음 (fs_df empty)
 - 266170 / 뿌리깊은나무들 / HTTPSConnectionPool(host='opendart.fss.or.kr', port=443): Max retries exceeded with url: /api/fnlttS
 - 266470 / 바이오인프라생명과학 / 재무데이터 없음 (fs_df empty)
 - 266870 / 파워풀엑스 / 재무데이터 없음 (fs_df empty)
 - 276240 / 엘리비젼 / 재무데이터 없음 (fs_df empty)
 - 279060 / 이노벡스 / 재무데이터 없음 (fs_df empty)
 - 288490 / 나라소프트 / 재무데이터 없음 (fs_df empty)
 - 289170 / 바이오텐 / 재무데이터 없음 (fs_df empty)
 - 296520 / 가이아코퍼레이션 / 재무데이터 없음 (fs_df empty)
 - 299480 / 지앤이헬스케어 / 재무데이터 없음 (fs_df empty)
 - 302920 / 더콘텐츠온 / 재무데이터 없음 (fs_df empty)
 - 308700 / 테크엔 / 재무데이터 없음 (fs_df empty)
 - 318660 / 타임기술 / 재무데이터 없음 (fs_df empty)
 - 322970 / 무진메디 / 재무데이터 없음 (fs_df empty)
 - 327610 / 펨토바이오메드 / 재무데이터 없음 (fs_df empty)
 - 331660 / 한국미라클피플사 / 재무데이터 없음 (fs_df empty)
 - 332190 / 오션스바이오 / 재무데이터 없음 (fs_df empty)
 - 336040 / 타스컴 / 재무데이터 없음 (fs_df empty)
 - 341310 / 이앤에치 / 재무데이터 없음 (fs_df empty)
 - 346010 / 타이드 / 재무데이터 없음 (fs_df empty)
 - 368030 / 창대정밀 / 재무데이터 없음 (fs_df empty)
 - 379390 / 이성씨엔아이 / 재무데이터 없음 (fs_df empty)
 - 389680 / 유디엠텍 / 재무데이터 없음 (fs_df empty)
 - 390110 / 애니메디솔루션 / 재무데이터 없음 (fs_df empty)
 - 402420 / 켈스 / 재무데이터 없음 (fs_df empty)
 - 403360 / 라피치 / 재무데이터 없음 (fs_df empty)
 - 403810 / 아이엘커누스 / 재무데이터 없음 (fs_df empty)
 - 405000 / 플라즈맵 / 재무데이터 없음 (fs_df empty)
 - 405920 / 나라셀라 / 재무데이터 없음 (fs_df empty)
 - 412350 / 레이저쎌 / 재무데이터 없음 (fs_df empty)
 - 413300 / 티엘엔지니어링 / 재무데이터 없음 (fs_df empty)
 - 415380 / 스튜디오삼익 / 재무데이터 없음 (fs_df empty)
 - 418620 / E8 / 재무데이터 없음 (fs_df empty)
 - 424760 / 벨로크 / 재무데이터 없음 (fs_df empty)
 - 429270 / 시지트로닉스 / 재무데이터 없음 (fs_df empty)
 - 432980 / 엠에프씨 / 재무데이터 없음 (fs_df empty)
 - 444920 / 유안타제11호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 446150 / 유안타제12호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 447690 / 아이오바이오 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 448760 / IBKS제22호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 448780 / 마이크로엔엑스 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 448830 / 미래에셋비전스팩3호 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 450050 / 하이제8호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 450940 / 유안타제14호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 451700 / 엔에이치스팩29호 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 452670 / 상상인제4호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 454640 / 하나29호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 455250 / KB제25호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 455310 / 한화플러스제4호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 455910 / SK증권제9호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 456190 / 큐라켐 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 456490 / 교보14호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 456700 / 길교이앤씨 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 457630 / 대신밸런스제16호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 457940 / SK증권제10호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 458610 / 한국제12호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 462020 / 에이치엠씨제6호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 464440 / 한국제13호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 464680 / KB제27호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 465320 / 교보15호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 466910 / 엔에이치스팩30호 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 467930 / IBKS제23호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 468760 / 유진스팩10호 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 469480 / IBKS제24호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 469880 / 하나30호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 469900 / 하나31호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 471050 / 대신밸런스제17호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 472220 / 신영스팩10호 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 472230 / SK증권제11호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 473000 / SK증권제12호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 473050 / 유안타제15호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 473370 / 비엔케이제2호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 473950 / SK증권제13호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 474490 / 유안타제16호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 474660 / 신한제12호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 474930 / 신한제13호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 475240 / 하나32호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 475250 / 하나33호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 476710 / 타조이엔터테인먼트 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 477340 / 에이치엠씨제7호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 477380 / 미래에셋비전스팩4호 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 477470 / 미래에셋비전스팩5호 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 477760 / 디비금융스팩12호 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 478110 / 이베스트스팩6호 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 478390 / KB제29호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 478440 / 미래에셋비전스팩6호 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 478780 / 대신밸런스제18호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 479880 / 한국제15호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 481890 / 엔에이치스팩31호 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 482520 / 교보16호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 482680 / 미래에셋비전스팩7호 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 482690 / 대신밸런스제19호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 484130 / 하나34호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 486630 / KB제30호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 487360 / 신한제14호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 487720 / 키움제10호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 487830 / 신한제15호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 488060 / 유진스팩11호 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 489210 / 교보17호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 489480 / 키움제11호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 489730 / 디비금융제13호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 492220 / KB제31호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 493790 / 유안타제17호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 496070 / 신한제16호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 496320 / 본시스템즈 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 498390 / 한화플러스제5호스팩 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 900070 / 글로벌에스엠 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 900100 / 애머릿지 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 900110 / 이스트아시아홀딩스 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None
 - 900120 / 씨엑스아이 / ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None

In [4]:
# my_codes = ["051910", "035420", "005380", "006400", "035720",
#             "000270", "207940", "068270", "042700", "043150",
#             "131290", "006910", "140860", "095610", "001440",
#             "000500", "004000", "010120", "068270", "058470"]  # 삼성전자, 하이닉스, NAVER, LG화학 등
#
# error_list = run_dart_fs_for_stock_list(
#     api_key=API_KEY,
#     db_info=db_info,
#     stock_code_list=my_codes,
#     start_year=2015,
#     end_year=2025,
#     batch_size=10,   # 10개 모이면 저장 (여기서는 4개라 마지막에 한 번에 저장)
#     table_name="korea_fs_data_from_DART",
# )

2025-11-25 15:04:54 [INFO] DB 연결 성공
2025-11-25 15:04:54 [INFO] DB 연결 테스트 완료
2025-11-25 15:04:54 [INFO] [STEP 1] DART 기업 목록 로드 중...
2025-11-25 15:04:56 [INFO] DART 상장사 필터링 완료: 3916개
2025-11-25 15:04:56 [INFO] 사용자 지정 종목 수: 20개 -> 정규화 후 19개
2025-11-25 15:04:56 [INFO] [1/19] 기아(000270) 처리 중...
2025-11-25 15:05:01 [INFO] [2/19] 가온전선(000500) 처리 중...
2025-11-25 15:05:06 [INFO] [3/19] 대한전선(001440) 처리 중...
2025-11-25 15:05:12 [INFO] [4/19] 롯데정밀화학(004000) 처리 중...
2025-11-25 15:05:17 [INFO] [5/19] 현대자동차(005380) 처리 중...
2025-11-25 15:05:22 [INFO] [6/19] 삼성SDI(006400) 처리 중...
2025-11-25 15:05:27 [INFO] [7/19] 보성파워텍(006910) 처리 중...
2025-11-25 15:05:31 [INFO] [8/19] 엘에스일렉트릭(010120) 처리 중...
2025-11-25 15:05:37 [INFO] [9/19] NAVER(035420) 처리 중...
2025-11-25 15:05:42 [INFO] [10/19] 카카오(035720) 처리 중...
2025-11-25 15:05:45 [INFO] [BATCH SAVE] 회사 10개 묶어서 DB 저장 시도...
2025-11-25 15:06:15 [INFO] [BATCH] 72827 rows saved into korea_fs_data_from_DART
2025-11-25 15:06:15 [INFO] [BATCH SAVE] 저장 완료 (회사 10개)
2025-11-25 15:06:15 [INFO] [11/19] 한미반도체(042700) 처리 중...

[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-25 15:06:20 [WARNING] 한미반도체(042700) : 재무데이터 없음 (fs_df empty)
2025-11-25 15:06:20 [INFO] [12/19] 바텍(043150) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-25 15:06:24 [WARNING] 바텍(043150) : 재무데이터 없음 (fs_df empty)
2025-11-25 15:06:25 [INFO] [13/19] LG화학(051910) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-25 15:06:29 [WARNING] LG화학(051910) : 재무데이터 없음 (fs_df empty)
2025-11-25 15:06:29 [INFO] [14/19] 리노공업(058470) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-25 15:06:34 [WARNING] 리노공업(058470) : 재무데이터 없음 (fs_df empty)
2025-11-25 15:06:34 [INFO] [15/19] 셀트리온(068270) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-25 15:06:38 [WARNING] 셀트리온(068270) : 재무데이터 없음 (fs_df empty)
2025-11-25 15:06:38 [INFO] [16/19] 테스(095610) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-25 15:06:43 [WARNING] 테스(095610) : 재무데이터 없음 (fs_df empty)
2025-11-25 15:06:43 [INFO] [17/19] 티에스이(131290) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-25 15:06:49 [WARNING] 티에스이(131290) : 재무데이터 없음 (fs_df empty)
2025-11-25 15:06:49 [INFO] [18/19] 파크시스템스(140860) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-25 15:06:54 [WARNING] 파크시스템스(140860) : 재무데이터 없음 (fs_df empty)
2025-11-25 15:06:54 [INFO] [19/19] 삼성바이오로직스(207940) 처리 중...

[WARN] CFS/OFS 모두 자료 없음
[INFO] CFS(연결) 자료 없음 → OFS(개별)로 재시도합니다.

2025-11-25 15:06:59 [WARNING] 삼성바이오로직스(207940) : 재무데이터 없음 (fs_df empty)
2025-11-25 15:06:59 [INFO] 작업 완료. 지정 종목 수: 19, 에러 종목 수: 9

[WARN] CFS/OFS 모두 자료 없음

[에러 발생 종목 목록]
 - 042700 / 한미반도체 / 재무데이터 없음 (fs_df empty)
 - 043150 / 바텍 / 재무데이터 없음 (fs_df empty)
 - 051910 / LG화학 / 재무데이터 없음 (fs_df empty)
 - 058470 / 리노공업 / 재무데이터 없음 (fs_df empty)
 - 068270 / 셀트리온 / 재무데이터 없음 (fs_df empty)
 - 095610 / 테스 / 재무데이터 없음 (fs_df empty)
 - 131290 / 티에스이 / 재무데이터 없음 (fs_df empty)
 - 140860 / 파크시스템스 / 재무데이터 없음 (fs_df empty)
 - 207940 / 삼성바이오로직스 / 재무데이터 없음 (fs_df empty)

In [25]:

test_sample_path = r"C:\Users\82108\OneDrive\바탕 화면\investment\investment_strategy\Results\Korea"

# 저장할 전체 파일 경로 만들기
output_path = os.path.join(test_sample_path, "isd_sample_data.xlsx")

# 필터링
test_df = fs_df[fs_df['sj_nm'] == '손익계산서']

# 저장
test_df.to_excel(output_path, index=False)

print(f"[INFO] 저장 완료: {output_path}")

[INFO] 저장 완료: C:\Users\82108\OneDrive\바탕 화면\investment\investment_strategy\Results\Korea\isd_sample_data.xlsx

In [27]:
test_df

,corp_code,bsns_year,reprt_code,sj_div,sj_nm,account_id,account_nm,account_detail,thstrm_nm,thstrm_amount,frmtrm_nm,frmtrm_amount,fs_div,fs_nm,quarter,report_date
101,00126380,2015,11011,IS,손익계산서,ifrs_ProfitLossFromContinuingOperations,계속영업이익(손실),-,제 47 기,1.906014e+13,제 46 기,2.339436e+13,None,None,FY,2015-12-31
102,00126380,2015,11011,IS,손익계산서,ifrs_FinanceCosts,금융비용,-,제 47 기,1.003177e+13,제 46 기,7.294002e+12,None,None,FY,2015-12-31
103,00126380,2015,11011,IS,손익계산서,ifrs_FinanceIncome,금융수익,-,제 47 기,1.051488e+13,제 46 기,8.259829e+12,None,None,FY,2015-12-31
104,00126380,2015,11011,IS,손익계산서,ifrs_BasicEarningsLossPerShare,기본주당이익(손실) (단위:원),-,제 47 기,1.263050e+05,제 46 기,1.531050e+05,None,None,FY,2015-12-31
105,00126380,2015,11011,IS,손익계산서,dart_OtherLosses,기타비용,-,제 47 기,3.723434e+12,제 46 기,2.259737e+12,None,None,FY,2015-12-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6882,00126380,2024,11011,IS,손익계산서,dart_OperatingIncomeLoss,영업이익,-,제 56 기,3.272596e+13,제 55 기,6.566976e+12,None,None,FY,2024-12-31
6883,00126380,2024,11011,IS,손익계산서,ifrs-full_ProfitLossAttributableToOwnersOfParent,지배기업 소유지분,-,제 56 기,3.362136e+13,제 55 기,1.447340e+13,None,None,FY,2024-12-31
6884,00126380,2024,11011,IS,손익계산서,ifrs-full_ShareOfProfitLossOfAssociatesAndJoin...,지분법이익,-,제 56 기,7.510440e+11,제 55 기,8.875500e+11,None,None,FY,2024-12-31
6885,00126380,2024,11011,IS,손익계산서,dart_TotalSellingGeneralAdministrativeExpenses,판매비와관리비,-,제 56 기,8.158267e+13,제 55 기,7.197994e+13,None,None,FY,2024-12-31
6886,00126380,2024,11011,IS,손익계산서,ifrs-full_DilutedEarningsLossPerShare,희석주당이익,-,제 56 기,4.950000e+03,제 55 기,2.131000e+03,None,None,FY,2024-12-31