In [16]:
import requests
import pandas as pd
from datetime import datetime
import logging
from typing import Optional
import json

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

class KOSISRetailSalesCollector:
    """KOSIS 제품 판매채널별 월별 판매액 데이터 수집"""

    def __init__(self, api_key: str):
        self.api_key = api_key
        self.base_url = "https://kosis.kr/openapi/Param/statisticsParameterData.do"

    def get_retail_sales_data(self, months: int = 24) -> Optional[pd.DataFrame]:
        """
        판매채널별 판매액 데이터 수집

        Parameters:
        -----------
        months : int
            최근 몇 개월 데이터 (기본값: 24개월)
        """
        params = {
            'method': 'getList',
            'apiKey': self.api_key,
            'itmId': 'T1',  # 판매액
            'objL1': 'ALL',  # 전체 업태
            'objL2': '',
            'objL3': '',
            'objL4': '',
            'objL5': '',
            'objL6': '',
            'objL7': '',
            'objL8': '',
            'format': 'json',
            'jsonVD': 'Y',
            'prdSe': 'M',  # 월별
            'newEstPrdCnt': str(months),
            'orgId': '101',
            'tblId': 'DT_1K41003'
        }

        try:
            logger.info(f"KOSIS 판매채널별 판매액 데이터 요청 (최근 {months}개월)")
            response = requests.get(self.base_url, params=params, timeout=30)
            response.raise_for_status()

            data = response.json()

            if not data:
                logger.warning("응답 데이터가 비어있습니다")
                return None

            df = pd.DataFrame(data)
            logger.info(f"원본 데이터 수집 완료: {len(df)} rows")
            logger.info(f"컬럼: {df.columns.tolist()}")

            return df

        except requests.exceptions.RequestException as e:
            logger.error(f"API 요청 실패: {e}")
            return None
        except Exception as e:
            logger.error(f"데이터 처리 중 오류: {e}")
            return None

    def process_data(self, df: pd.DataFrame) -> pd.DataFrame:
        """데이터 전처리 및 정제"""
        if df is None or df.empty:
            logger.warning("처리할 데이터가 없습니다")
            return pd.DataFrame()

        logger.info("데이터 전처리 시작")
        processed = df.copy()

        # 1. 날짜 처리
        if 'PRD_DE' in processed.columns:
            processed['date'] = pd.to_datetime(
                processed['PRD_DE'],
                format='%Y%m',
                errors='coerce'
            )
            processed['year'] = processed['date'].dt.year
            processed['month'] = processed['date'].dt.month
            processed['year_month'] = processed['PRD_DE']

        # 2. 판매채널 정보
        channel_cols = ['C1_NM', 'C2_NM', 'C1', 'C2']
        for col in channel_cols:
            if col in processed.columns:
                processed[f'channel_{col.lower()}'] = processed[col]

        # 3. 판매액 (숫자로 변환)
        if 'DT' in processed.columns:
            processed['sales_amount'] = pd.to_numeric(
                processed['DT'].astype(str).str.replace(',', '').str.strip(),
                errors='coerce'
            )

        # 4. 단위 정보
        if 'UNIT_NM' in processed.columns:
            processed['unit'] = processed['UNIT_NM']

        # 5. 항목명
        if 'ITM_NM' in processed.columns:
            processed['item_name'] = processed['ITM_NM']

        # 6. 통계표 정보
        if 'TBL_NM' in processed.columns:
            processed['table_name'] = processed['TBL_NM']

        if 'TBL_ID' in processed.columns:
            processed['table_id'] = processed['TBL_ID']

        if 'ORG_ID' in processed.columns:
            processed['org_id'] = processed['ORG_ID']

        # 7. 데이터 수집 시간
        processed['collected_at'] = datetime.now()

        # 8. 결측치 확인
        logger.info(f"결측치 확인:\n{processed.isnull().sum()}")

        return processed

    def create_summary(self, df: pd.DataFrame) -> pd.DataFrame:
        """판매채널별 요약 통계"""
        if df.empty or 'sales_amount' not in df.columns:
            logger.warning("요약 통계를 생성할 수 없습니다")
            return pd.DataFrame()

        # 채널 컬럼 찾기
        channel_col = None
        for col in ['channel_c1_nm', 'channel_c2_nm', 'C1_NM', 'C2_NM']:
            if col in df.columns:
                channel_col = col
                break

        if channel_col is None:
            logger.warning("채널 정보를 찾을 수 없습니다")
            return pd.DataFrame()

        summary = df.groupby(channel_col).agg({
            'sales_amount': ['count', 'mean', 'sum', 'min', 'max', 'std'],
            'date': ['min', 'max']
        }).round(2)

        summary.columns = ['_'.join(col).strip() for col in summary.columns.values]
        summary = summary.reset_index()
        summary.columns = [
            'channel', 'record_count', 'avg_sales', 'total_sales',
            'min_sales', 'max_sales', 'std_sales', 'first_date', 'last_date'
        ]

        summary = summary.sort_values('total_sales', ascending=False)

        return summary

    def create_pivot_table(self, df: pd.DataFrame) -> pd.DataFrame:
        """날짜 x 판매채널 피벗 테이블 생성"""
        if df.empty:
            return pd.DataFrame()

        # 채널 컬럼 찾기
        channel_col = None
        for col in ['channel_c1_nm', 'channel_c2_nm', 'C1_NM', 'C2_NM']:
            if col in df.columns:
                channel_col = col
                break

        if channel_col is None or 'date' not in df.columns:
            logger.warning("피벗 테이블을 생성할 수 없습니다")
            return pd.DataFrame()

        pivot = df.pivot_table(
            values='sales_amount',
            index='date',
            columns=channel_col,
            aggfunc='sum'
        )

        pivot = pivot.sort_index()

        return pivot

    def get_channel_timeseries(self, df: pd.DataFrame, channel: str = None) -> pd.DataFrame:
        """특정 채널의 시계열 데이터"""
        if df.empty:
            return pd.DataFrame()

        # 채널 컬럼 찾기
        channel_col = None
        for col in ['channel_c1_nm', 'channel_c2_nm', 'C1_NM', 'C2_NM']:
            if col in df.columns:
                channel_col = col
                break

        if channel_col is None:
            return df[['date', 'sales_amount']].sort_values('date')

        if channel:
            filtered = df[df[channel_col] == channel].copy()
            filtered = filtered[['date', channel_col, 'sales_amount', 'unit']].sort_values('date')
            return filtered
        else:
            return df[['date', channel_col, 'sales_amount', 'unit']].sort_values('date')

    def calculate_growth_rate(self, df: pd.DataFrame) -> pd.DataFrame:
        """전년 동월 대비 성장률 계산"""
        if df.empty or 'date' not in df.columns:
            return pd.DataFrame()

        # 채널 컬럼 찾기
        channel_col = None
        for col in ['channel_c1_nm', 'channel_c2_nm', 'C1_NM', 'C2_NM']:
            if col in df.columns:
                channel_col = col
                break

        if channel_col is None:
            return pd.DataFrame()

        df_sorted = df.sort_values(['date', channel_col]).copy()

        # 전년 동월 대비 성장률
        df_sorted['yoy_growth'] = df_sorted.groupby(channel_col)['sales_amount'].pct_change(12) * 100

        # 전월 대비 성장률
        df_sorted['mom_growth'] = df_sorted.groupby(channel_col)['sales_amount'].pct_change(1) * 100

        return df_sorted

    def create_yoy_growth_pivot(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        전년 동월 대비 성장률(YoY Growth) 피벗 테이블 생성
        날짜 x 판매채널, 값은 YoY 성장률(%)

        Parameters:
        -----------
        df : pd.DataFrame
            calculate_growth_rate()로 성장률이 계산된 데이터프레임

        Returns:
        --------
        pd.DataFrame
            날짜를 인덱스로, 채널을 컬럼으로 하는 YoY 성장률 피벗 테이블
        """
        if df.empty:
            logger.warning("데이터가 비어있습니다")
            return pd.DataFrame()

        if 'yoy_growth' not in df.columns:
            logger.warning("yoy_growth 컬럼이 없습니다. calculate_growth_rate()를 먼저 실행하세요")
            return pd.DataFrame()

        # 채널 컬럼 찾기
        channel_col = None
        for col in ['channel_c1_nm', 'channel_c2_nm', 'C1_NM', 'C2_NM']:
            if col in df.columns:
                channel_col = col
                break

        if channel_col is None or 'date' not in df.columns:
            logger.warning("날짜 또는 채널 정보를 찾을 수 없습니다")
            return pd.DataFrame()

        # YoY 성장률 피벗 테이블 생성
        yoy_pivot = df.pivot_table(
            values='yoy_growth',
            index='date',
            columns=channel_col,
            aggfunc='mean'  # 중복이 있을 경우 평균 사용
        )

        yoy_pivot = yoy_pivot.sort_index()

        # 소수점 2자리로 반올림
        yoy_pivot = yoy_pivot.round(2)

        logger.info(f"YoY 성장률 피벗 테이블 생성 완료: {yoy_pivot.shape}")

        return yoy_pivot

    def create_mom_growth_pivot(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        전월 대비 성장률(MoM Growth) 피벗 테이블 생성
        날짜 x 판매채널, 값은 MoM 성장률(%)

        Parameters:
        -----------
        df : pd.DataFrame
            calculate_growth_rate()로 성장률이 계산된 데이터프레임

        Returns:
        --------
        pd.DataFrame
            날짜를 인덱스로, 채널을 컬럼으로 하는 MoM 성장률 피벗 테이블
        """
        if df.empty:
            logger.warning("데이터가 비어있습니다")
            return pd.DataFrame()

        if 'mom_growth' not in df.columns:
            logger.warning("mom_growth 컬럼이 없습니다. calculate_growth_rate()를 먼저 실행하세요")
            return pd.DataFrame()

        # 채널 컬럼 찾기
        channel_col = None
        for col in ['channel_c1_nm', 'channel_c2_nm', 'C1_NM', 'C2_NM']:
            if col in df.columns:
                channel_col = col
                break

        if channel_col is None or 'date' not in df.columns:
            logger.warning("날짜 또는 채널 정보를 찾을 수 없습니다")
            return pd.DataFrame()

        # MoM 성장률 피벗 테이블 생성
        mom_pivot = df.pivot_table(
            values='mom_growth',
            index='date',
            columns=channel_col,
            aggfunc='mean'
        )

        mom_pivot = mom_pivot.sort_index()

        # 소수점 2자리로 반올림
        mom_pivot = mom_pivot.round(2)

        logger.info(f"MoM 성장률 피벗 테이블 생성 완료: {mom_pivot.shape}")

        return mom_pivot

    def export_to_excel(self, df: pd.DataFrame, summary: pd.DataFrame,
                       pivot: pd.DataFrame, yoy_pivot: pd.DataFrame = None,
                       mom_pivot: pd.DataFrame = None,
                       filename: str = 'kosis_retail_sales.xlsx'):
        """여러 시트로 구성된 Excel 파일로 저장"""
        try:
            with pd.ExcelWriter(filename, engine='openpyxl') as writer:
                if not df.empty:
                    df.to_excel(writer, sheet_name='원본데이터', index=False)

                if not summary.empty:
                    summary.to_excel(writer, sheet_name='채널별요약', index=False)

                if not pivot.empty:
                    pivot.to_excel(writer, sheet_name='판매액_피벗')

                # 성장률 데이터
                growth_df = self.calculate_growth_rate(df)
                if not growth_df.empty:
                    growth_df.to_excel(writer, sheet_name='성장률분석', index=False)

                # YoY 성장률 피벗 테이블
                if yoy_pivot is not None and not yoy_pivot.empty:
                    yoy_pivot.to_excel(writer, sheet_name='YoY성장률_피벗')

                # MoM 성장률 피벗 테이블
                if mom_pivot is not None and not mom_pivot.empty:
                    mom_pivot.to_excel(writer, sheet_name='MoM성장률_피벗')

            logger.info(f"Excel 파일 저장 완료: {filename}")

        except Exception as e:
            logger.error(f"Excel 저장 실패: {e}")

    def run_collection(self, months: int = 24, save_excel: bool = True) -> dict:
        """
        전체 수집 프로세스 실행

        Returns:
        --------
        dict: 'raw', 'processed', 'summary', 'pivot', 'yoy_pivot', 'mom_pivot' 키를 가진 딕셔너리
        """
        logger.info("=== KOSIS 판매채널별 판매액 데이터 수집 시작 ===")

        # 1. 데이터 수집
        raw_data = self.get_retail_sales_data(months)
        if raw_data is None or raw_data.empty:
            logger.error("데이터 수집 실패")
            return {
                'raw': pd.DataFrame(),
                'processed': pd.DataFrame(),
                'summary': pd.DataFrame(),
                'pivot': pd.DataFrame(),
                'growth': pd.DataFrame(),
                'yoy_pivot': pd.DataFrame(),
                'mom_pivot': pd.DataFrame()
            }

        # 2. 데이터 처리
        processed_data = self.process_data(raw_data)

        # 3. 요약 통계 생성
        summary = self.create_summary(processed_data)
        if not summary.empty:
            logger.info("\n=== 판매채널별 요약 통계 ===")
            print(summary.to_string(index=False))

        # 4. 판매액 피벗 테이블 생성
        pivot = self.create_pivot_table(processed_data)
        if not pivot.empty:
            logger.info(f"\n=== 판매액 피벗 테이블 (날짜 x 채널) ===")
            print(pivot.head(10))

        # 5. 성장률 계산
        growth_data = self.calculate_growth_rate(processed_data)

        # 6. YoY 성장률 피벗 테이블 생성
        yoy_pivot = self.create_yoy_growth_pivot(growth_data)
        if not yoy_pivot.empty:
            logger.info(f"\n=== YoY 성장률 피벗 테이블 (날짜 x 채널, 단위: %) ===")
            print(yoy_pivot.tail(12))  # 최근 12개월

        # 7. MoM 성장률 피벗 테이블 생성
        mom_pivot = self.create_mom_growth_pivot(growth_data)
        if not mom_pivot.empty:
            logger.info(f"\n=== MoM 성장률 피벗 테이블 (날짜 x 채널, 단위: %) ===")
            print(mom_pivot.tail(12))  # 최근 12개월

        # 8. Excel 저장
        if save_excel:
            self.export_to_excel(processed_data, summary, pivot, yoy_pivot, mom_pivot)

        logger.info("=== 데이터 수집 완료 ===")

        return {
            'raw': raw_data,
            'processed': processed_data,
            'summary': summary,
            'pivot': pivot,
            'growth': growth_data,
            'yoy_pivot': yoy_pivot,
            'mom_pivot': mom_pivot
        }


def main():
    # API 키 설정
    kosis_key = "ZTFhMjg1MzhmNmFiYWJlYmY3ZWUxZDA0ZDI2ZTM0YWU="

    # 수집기 초기화
    collector = KOSISRetailSalesCollector(kosis_key)

    # 데이터 수집 실행 (최근 36개월 - YoY 계산을 위해 충분한 기간 필요)
    results = collector.run_collection(months=36, save_excel=True)

    # 결과 활용 예시
    processed_df = results['processed']
    summary_df = results['summary']
    pivot_df = results['pivot']
    yoy_pivot_df = results['yoy_pivot']
    mom_pivot_df = results['mom_pivot']

    # YoY 성장률 피벗 테이블 상세 분석
    if not yoy_pivot_df.empty:
        print("\n=== YoY 성장률 피벗 테이블 전체 ===")
        print(yoy_pivot_df)

        print("\n=== 최근 6개월 YoY 성장률 ===")
        print(yoy_pivot_df.tail(6))

        print("\n=== 채널별 평균 YoY 성장률 ===")
        print(yoy_pivot_df.mean().sort_values(ascending=False))

        print("\n=== 채널별 최근 YoY 성장률 (가장 최근 월) ===")
        print(yoy_pivot_df.iloc[-1].sort_values(ascending=False))


if __name__ == "__main__":
    main()

2026-02-11 21:26:20,680 - INFO - === KOSIS 판매채널별 판매액 데이터 수집 시작 ===
2026-02-11 21:26:20,681 - INFO - KOSIS 판매채널별 판매액 데이터 요청 (최근 36개월)
2026-02-11 21:26:20,948 - INFO - 원본 데이터 수집 완료: 288 rows
2026-02-11 21:26:20,948 - INFO - 컬럼: ['C1_OBJ_NM', 'DT', 'C1', 'PRD_SE', 'UNIT_NM_ENG', 'ITM_ID', 'TBL_ID', 'ITM_NM', 'TBL_NM', 'PRD_DE', 'LST_CHN_DE', 'C1_NM_ENG', 'C1_NM', 'UNIT_NM', 'ITM_NM_ENG', 'ORG_ID', 'C1_OBJ_NM_ENG']
2026-02-11 21:26:20,950 - INFO - 데이터 전처리 시작
2026-02-11 21:26:20,956 - INFO - 결측치 확인:
C1_OBJ_NM        0
DT               0
C1               0
PRD_SE           0
UNIT_NM_ENG      0
ITM_ID           0
TBL_ID           0
ITM_NM           0
TBL_NM           0
PRD_DE           0
LST_CHN_DE       0
C1_NM_ENG        0
C1_NM            0
UNIT_NM          0
ITM_NM_ENG       0
ORG_ID           0
C1_OBJ_NM_ENG    0
date             0
year             0
month            0
year_month       0
channel_c1_nm    0
channel_c1       0
sales_amount     0
unit             0
item_name        0
table_name       0
table_id         0
org_id           0
collected_at     0
dtype: int64
2026-02-11 21:26:20,961 - INFO -
=== 판매채널별 요약 통계 ===
2026-02-11 21:26:20,968 - INFO -
=== 판매액 피벗 테이블 (날짜 x 채널) ===
2026-02-11 21:26:20,979 - INFO - YoY 성장률 피벗 테이블 생성 완료: (24, 8)
2026-02-11 21:26:20,980 - INFO -
=== YoY 성장률 피벗 테이블 (날짜 x 채널, 단위: %) ===
2026-02-11 21:26:20,989 - INFO - MoM 성장률 피벗 테이블 생성 완료: (35, 8)
2026-02-11 21:26:20,989 - INFO -
=== MoM 성장률 피벗 테이블 (날짜 x 채널, 단위: %) ===

     channel  record_count   avg_sales  total_sales  min_sales  max_sales  std_sales first_date  last_date
       전문소매점            36 15691888.94    564908002   14491139   17026074  677373.14 2023-01-01 2025-12-01
      무점포 소매            36 11436106.17    411699822    9986914   12709635  603605.65 2023-01-01 2025-12-01
승용차 및 연료 소매점            36 10824028.75    389665035    9274173   12266219  684763.12 2023-01-01 2025-12-01
  슈퍼마켓 및 잡화점            36  5626100.86    202539631    4828445    6411664  294360.59 2023-01-01 2025-12-01
         백화점            36  3401036.25    122437305    2967662    3998041  289825.16 2023-01-01 2025-12-01
        대형마트            36  3060581.47    110180933    2473948    3861641  262166.90 2023-01-01 2025-12-01
         편의점            36  2620157.42     94325667    2160538    2866979  185835.31 2023-01-01 2025-12-01
         면세점            36  1128645.25     40631229     797391    1590894  145459.83 2023-01-01 2025-12-01
channel_c1_nm     대형마트      면세점    무점포 소매      백화점  슈퍼마켓 및 잡화점  승용차 및 연료 소매점  \
date
2023-01-01     3485426   797391  10630927  3062624     5840069       9767551
2023-02-01     2473948  1090319   9986914  2988967     4828445      10363664
2023-03-01     2851714  1221714  11016889  3357840     5336950      11500534
2023-04-01     2848227  1174846  10280498  3490298     5463118      10708960
2023-05-01     2929501  1156823  11223025  3743887     5724140      10885475
2023-06-01     2864918  1070833  10688426  3193720     5729623      11350451
2023-07-01     3199158   990857  10748058  3245692     5791070       9899621
2023-08-01     3237279  1136577  10842814  2967662     5891812      10492762
2023-09-01     3528200  1327364  10963703  3327346     6411664      10698097
2023-10-01     2971554  1329247  11528116  3550056     5484337      10855775

channel_c1_nm     전문소매점      편의점
date
2023-01-01     15907278  2315240
2023-02-01     14732634  2160538
2023-03-01     16270167  2527029
2023-04-01     16006925  2536429
2023-05-01     16625151  2682666
2023-06-01     15564048  2693016
2023-07-01     15059682  2741053
2023-08-01     14958845  2788446
2023-09-01     16050076  2777479
2023-10-01     16457090  2728187
channel_c1_nm   대형마트    면세점  무점포 소매   백화점  슈퍼마켓 및 잡화점  승용차 및 연료 소매점  전문소매점  \
date
2025-01-01     18.80 -40.01   -2.06  7.44       10.34          2.14   3.04
2025-02-01    -16.92   9.33    2.05 -4.52      -13.17         13.31  -0.63
2025-03-01     -0.88  -8.60    2.75 -2.70       -0.23          4.86   2.88
2025-04-01     -2.02  -5.25    1.47 -5.07       -0.49          6.31   0.54
2025-05-01     -1.99 -16.08    0.11  0.60       -0.68          4.21   1.53
2025-06-01     -0.09  -9.52    3.04 -1.03       -2.12          6.17   1.25
2025-07-01      0.17 -19.86    6.55  1.10       -0.27          7.49   4.61
2025-08-01    -10.66 -16.13    4.30  3.26       -5.70          5.33   3.77
2025-09-01     -7.31 -10.60   14.84  3.49       -8.15         12.60   0.42
2025-10-01     10.08  -5.66    1.30  8.20        4.30         -3.64   5.79
2025-11-01     -4.91  -1.74    3.87  6.29       -1.09          6.52   3.87
2025-12-01     -5.59 -11.00    4.82  3.14       -2.87          9.06   4.33

channel_c1_nm   편의점
date
2025-01-01     0.36
2025-02-01    -5.78
2025-03-01     0.17
2025-04-01    -1.51
2025-05-01    -1.01
2025-06-01    -1.68
2025-07-01     3.03
2025-08-01     0.22
2025-09-01     0.15
2025-10-01    -0.16
2025-11-01    -0.13
2025-12-01     0.98
channel_c1_nm   대형마트    면세점  무점포 소매    백화점  슈퍼마켓 및 잡화점  승용차 및 연료 소매점  전문소매점  \
date
2025-01-01     23.99 -24.13   -3.30  -9.73       10.17        -13.09  -5.91
2025-02-01    -32.75   4.84   -2.36 -13.48      -19.36          7.50  -5.17
2025-03-01     19.86   8.39    6.38  14.82       11.16         10.11   9.89
2025-04-01    -11.67   9.25   -1.86  -9.06       -2.83         -3.11  -4.07
2025-05-01     10.20 -11.17    1.03  13.09        6.81         -0.45   5.26
2025-06-01     -2.87   3.12   -2.85  -9.88       -3.96         -0.38  -4.58
2025-07-01      2.58 -15.24    5.16  -2.46        2.44         -0.43   3.38
2025-08-01     -0.67  10.82   -5.66  -1.65        0.03         -0.68  -5.02
2025-09-01      4.60   4.70   11.51  11.93        0.52          6.74   7.63
2025-10-01     -0.15  -1.79   -7.37   8.08        2.19        -11.18   4.99
2025-11-01     -8.26  -4.88    6.26   5.30       -6.19         12.73  -3.07
2025-12-01      2.34  12.27   -0.50   1.54       -0.06          4.42   2.67

channel_c1_nm    편의점
date
2025-01-01     -4.38
2025-02-01     -9.34
2025-03-01     17.20
2025-04-01      1.58
2025-05-01      5.35
2025-06-01     -1.27
2025-07-01      5.66
2025-08-01      0.50
2025-09-01     -2.37
2025-10-01     -0.78
2025-11-01     -5.97
2025-12-01     -2.75

2026-02-11 21:26:21,362 - INFO - Excel 파일 저장 완료: kosis_retail_sales.xlsx
2026-02-11 21:26:21,363 - INFO - === 데이터 수집 완료 ===

=== YoY 성장률 피벗 테이블 전체 ===
channel_c1_nm   대형마트    면세점  무점포 소매   백화점  슈퍼마켓 및 잡화점  승용차 및 연료 소매점  전문소매점  \
date
2024-01-01     -6.74  99.51   10.29  6.34       -4.39         -2.03  -6.77
2024-02-01     26.36 -16.06   10.01  6.08       18.49        -10.51  -1.01
2024-03-01     10.13  -2.88    5.37  6.40        3.72         -4.06  -4.87
2024-04-01     -1.48   6.44   12.21 -4.60       -1.29         -1.53  -5.08
2024-05-01      5.53   8.42    5.26 -5.09        0.81         -1.62  -4.73
2024-06-01      2.82  12.02    4.32  1.93       -1.85         -7.76  -2.63
2024-07-01     -5.79  15.86    5.50 -4.24       -2.37          4.02   0.69
2024-08-01      3.69   6.95    0.79  0.86        1.52         -0.53  -2.94
2024-09-01     -4.09 -10.04    0.94  0.46       -3.73         -2.60   0.62
2024-10-01     -4.26 -16.40    0.81 -2.65        1.28         -0.37  -2.21
2024-11-01      0.19 -12.16   -0.41  0.99       -0.44         -7.93   0.30
2024-12-01     -5.17  -3.78    3.78 -0.52        0.25         -4.27  -0.23
2025-01-01     18.80 -40.01   -2.06  7.44       10.34          2.14   3.04
2025-02-01    -16.92   9.33    2.05 -4.52      -13.17         13.31  -0.63
2025-03-01     -0.88  -8.60    2.75 -2.70       -0.23          4.86   2.88
2025-04-01     -2.02  -5.25    1.47 -5.07       -0.49          6.31   0.54
2025-05-01     -1.99 -16.08    0.11  0.60       -0.68          4.21   1.53
2025-06-01     -0.09  -9.52    3.04 -1.03       -2.12          6.17   1.25
2025-07-01      0.17 -19.86    6.55  1.10       -0.27          7.49   4.61
2025-08-01    -10.66 -16.13    4.30  3.26       -5.70          5.33   3.77
2025-09-01     -7.31 -10.60   14.84  3.49       -8.15         12.60   0.42
2025-10-01     10.08  -5.66    1.30  8.20        4.30         -3.64   5.79
2025-11-01     -4.91  -1.74    3.87  6.29       -1.09          6.52   3.87
2025-12-01     -5.59 -11.00    4.82  3.14       -2.87          9.06   4.33

channel_c1_nm   편의점
date
2024-01-01     3.49
2024-02-01     7.10
2024-03-01     0.94
2024-04-01     3.90
2024-05-01     2.97
2024-06-01     1.97
2024-07-01     1.01
2024-08-01     2.59
2024-09-01     0.63
2024-10-01     1.96
2024-11-01     3.45
2024-12-01     0.93
2025-01-01     0.36
2025-02-01    -5.78
2025-03-01     0.17
2025-04-01    -1.51
2025-05-01    -1.01
2025-06-01    -1.68
2025-07-01     3.03
2025-08-01     0.22
2025-09-01     0.15
2025-10-01    -0.16
2025-11-01    -0.13
2025-12-01     0.98

=== 최근 6개월 YoY 성장률 ===
channel_c1_nm   대형마트    면세점  무점포 소매   백화점  슈퍼마켓 및 잡화점  승용차 및 연료 소매점  전문소매점  \
date
2025-07-01      0.17 -19.86    6.55  1.10       -0.27          7.49   4.61
2025-08-01    -10.66 -16.13    4.30  3.26       -5.70          5.33   3.77
2025-09-01     -7.31 -10.60   14.84  3.49       -8.15         12.60   0.42
2025-10-01     10.08  -5.66    1.30  8.20        4.30         -3.64   5.79
2025-11-01     -4.91  -1.74    3.87  6.29       -1.09          6.52   3.87
2025-12-01     -5.59 -11.00    4.82  3.14       -2.87          9.06   4.33

channel_c1_nm   편의점
date
2025-07-01     3.03
2025-08-01     0.22
2025-09-01     0.15
2025-10-01    -0.16
2025-11-01    -0.13
2025-12-01     0.98

=== 채널별 평균 YoY 성장률 ===
channel_c1_nm
무점포 소매          4.246250
승용차 및 연료 소매점    1.465417
백화점             1.090000
편의점             1.065833
전문소매점           0.105833
대형마트           -0.005417
슈퍼마켓 및 잡화점     -0.338750
면세점            -1.968333
dtype: float64

=== 채널별 최근 YoY 성장률 (가장 최근 월) ===
channel_c1_nm
승용차 및 연료 소매점     9.06
무점포 소매           4.82
전문소매점            4.33
백화점              3.14
편의점              0.98
슈퍼마켓 및 잡화점      -2.87
대형마트            -5.59
면세점            -11.00
Name: 2025-12-01 00:00:00, dtype: float64

In [17]:
 # 수집기 초기화
collector = KOSISRetailSalesCollector(kosis_key)
# 데이터 수집 실행 (최근 36개월)
results = collector.run_collection(months=100, save_excel=True)
processed_df = results['processed']
yoy_pivot_df = results['yoy_pivot']
# growth_data = collector.calculate_growth_rate(processed_df)

2026-02-11 21:26:24,956 - INFO - === KOSIS 판매채널별 판매액 데이터 수집 시작 ===
2026-02-11 21:26:24,957 - INFO - KOSIS 판매채널별 판매액 데이터 요청 (최근 100개월)
2026-02-11 21:26:25,294 - INFO - 원본 데이터 수집 완료: 576 rows
2026-02-11 21:26:25,295 - INFO - 컬럼: ['C1_OBJ_NM', 'DT', 'C1', 'PRD_SE', 'UNIT_NM_ENG', 'ITM_ID', 'TBL_ID', 'ITM_NM', 'TBL_NM', 'PRD_DE', 'LST_CHN_DE', 'C1_NM_ENG', 'C1_NM', 'UNIT_NM', 'ITM_NM_ENG', 'ORG_ID', 'C1_OBJ_NM_ENG']
2026-02-11 21:26:25,296 - INFO - 데이터 전처리 시작
2026-02-11 21:26:25,304 - INFO - 결측치 확인:
C1_OBJ_NM        0
DT               0
C1               0
PRD_SE           0
UNIT_NM_ENG      0
ITM_ID           0
TBL_ID           0
ITM_NM           0
TBL_NM           0
PRD_DE           0
LST_CHN_DE       0
C1_NM_ENG        0
C1_NM            0
UNIT_NM          0
ITM_NM_ENG       0
ORG_ID           0
C1_OBJ_NM_ENG    0
date             0
year             0
month            0
year_month       0
channel_c1_nm    0
channel_c1       0
sales_amount     0
unit             0
item_name        0
table_name       0
table_id         0
org_id           0
collected_at     0
dtype: int64
2026-02-11 21:26:25,308 - INFO -
=== 판매채널별 요약 통계 ===
2026-02-11 21:26:25,314 - INFO -
=== 판매액 피벗 테이블 (날짜 x 채널) ===
2026-02-11 21:26:25,325 - INFO - YoY 성장률 피벗 테이블 생성 완료: (60, 8)
2026-02-11 21:26:25,325 - INFO -
=== YoY 성장률 피벗 테이블 (날짜 x 채널, 단위: %) ===
2026-02-11 21:26:25,333 - INFO - MoM 성장률 피벗 테이블 생성 완료: (71, 8)
2026-02-11 21:26:25,334 - INFO -
=== MoM 성장률 피벗 테이블 (날짜 x 채널, 단위: %) ===

     channel  record_count   avg_sales  total_sales  min_sales  max_sales  std_sales first_date  last_date
       전문소매점            72 15244042.07   1097571029   12485052   17026074  938448.23 2020-01-01 2025-12-01
      무점포 소매            72 10546016.35    759313177    7373949   12709635 1187445.25 2020-01-01 2025-12-01
승용차 및 연료 소매점            72 10303943.64    741883942    6967752   12266219 1151976.35 2020-01-01 2025-12-01
  슈퍼마켓 및 잡화점            72  5508419.22    396606184    4476276    6411664  348982.09 2020-01-01 2025-12-01
         백화점            72  3073786.43    221312623    1698069    3998041  511787.57 2020-01-01 2025-12-01
        대형마트            72  2962551.24    213303689    2390074    3861641  277048.14 2020-01-01 2025-12-01
         편의점            72  2506480.01    180466561    1937346    2866979  242678.63 2020-01-01 2025-12-01
         면세점            72  1274818.64     91786942     797391    2024766  246926.00 2020-01-01 2025-12-01
channel_c1_nm     대형마트      면세점   무점포 소매      백화점  슈퍼마켓 및 잡화점  승용차 및 연료 소매점  \
date
2020-01-01     3235517  2024766  7373949  2548874     5623682       7786640
2020-02-01     2465291  1102558  7762883  1803962     5016117       6967752
2020-03-01     2599678  1087340  8695945  1698069     5417439       9050377
2020-04-01     2593974   986741  8221022  2057305     5306617       8733893
2020-05-01     2709738  1017936  8621075  2474372     5822281       8783128
2020-06-01     2598351  1113009  8426702  2312717     5455159       9902822
2020-07-01     2689437  1251560  8466713  2145965     5308835       8778725
2020-08-01     3008962  1444154  8849096  2090506     5622628       8358608
2020-09-01     3472045  1484088  9387547  2416847     6273438       8691469
2020-10-01     2706445  1389363  9191304  2694894     4933817       8856817

channel_c1_nm     전문소매점      편의점
date
2020-01-01     15638352  2060450
2020-02-01     13338998  1937346
2020-03-01     12485052  2015881
2020-04-01     13537724  2037033
2020-05-01     15602573  2292813
2020-06-01     14486300  2315814
2020-07-01     13586414  2385425
2020-08-01     13465955  2411743
2020-09-01     14725893  2333723
2020-10-01     14455041  2361371
channel_c1_nm   대형마트    면세점  무점포 소매   백화점  슈퍼마켓 및 잡화점  승용차 및 연료 소매점  전문소매점  \
date
2025-01-01     18.80 -40.01   -2.06  7.44       10.34          2.14   3.04
2025-02-01    -16.92   9.33    2.05 -4.52      -13.17         13.31  -0.63
2025-03-01     -0.88  -8.60    2.75 -2.70       -0.23          4.86   2.88
2025-04-01     -2.02  -5.25    1.47 -5.07       -0.49          6.31   0.54
2025-05-01     -1.99 -16.08    0.11  0.60       -0.68          4.21   1.53
2025-06-01     -0.09  -9.52    3.04 -1.03       -2.12          6.17   1.25
2025-07-01      0.17 -19.86    6.55  1.10       -0.27          7.49   4.61
2025-08-01    -10.66 -16.13    4.30  3.26       -5.70          5.33   3.77
2025-09-01     -7.31 -10.60   14.84  3.49       -8.15         12.60   0.42
2025-10-01     10.08  -5.66    1.30  8.20        4.30         -3.64   5.79
2025-11-01     -4.91  -1.74    3.87  6.29       -1.09          6.52   3.87
2025-12-01     -5.59 -11.00    4.82  3.14       -2.87          9.06   4.33

channel_c1_nm   편의점
date
2025-01-01     0.36
2025-02-01    -5.78
2025-03-01     0.17
2025-04-01    -1.51
2025-05-01    -1.01
2025-06-01    -1.68
2025-07-01     3.03
2025-08-01     0.22
2025-09-01     0.15
2025-10-01    -0.16
2025-11-01    -0.13
2025-12-01     0.98
channel_c1_nm   대형마트    면세점  무점포 소매    백화점  슈퍼마켓 및 잡화점  승용차 및 연료 소매점  전문소매점  \
date
2025-01-01     23.99 -24.13   -3.30  -9.73       10.17        -13.09  -5.91
2025-02-01    -32.75   4.84   -2.36 -13.48      -19.36          7.50  -5.17
2025-03-01     19.86   8.39    6.38  14.82       11.16         10.11   9.89
2025-04-01    -11.67   9.25   -1.86  -9.06       -2.83         -3.11  -4.07
2025-05-01     10.20 -11.17    1.03  13.09        6.81         -0.45   5.26
2025-06-01     -2.87   3.12   -2.85  -9.88       -3.96         -0.38  -4.58
2025-07-01      2.58 -15.24    5.16  -2.46        2.44         -0.43   3.38
2025-08-01     -0.67  10.82   -5.66  -1.65        0.03         -0.68  -5.02
2025-09-01      4.60   4.70   11.51  11.93        0.52          6.74   7.63
2025-10-01     -0.15  -1.79   -7.37   8.08        2.19        -11.18   4.99
2025-11-01     -8.26  -4.88    6.26   5.30       -6.19         12.73  -3.07
2025-12-01      2.34  12.27   -0.50   1.54       -0.06          4.42   2.67

channel_c1_nm    편의점
date
2025-01-01     -4.38
2025-02-01     -9.34
2025-03-01     17.20
2025-04-01      1.58
2025-05-01      5.35
2025-06-01     -1.27
2025-07-01      5.66
2025-08-01      0.50
2025-09-01     -2.37
2025-10-01     -0.78
2025-11-01     -5.97
2025-12-01     -2.75

2026-02-11 21:26:26,071 - INFO - Excel 파일 저장 완료: kosis_retail_sales.xlsx
2026-02-11 21:26:26,072 - INFO - === 데이터 수집 완료 ===

In [22]:
import requests
import pandas as pd
from datetime import datetime
import logging
from typing import Optional, Dict, List
import json
import os

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

class KOSISRetailCollector:
    """KOSIS 소매판매 데이터 수집 (판매채널별 + 제화별)"""

    def __init__(self, api_key: str, save_dir: str = None):
        self.api_key = api_key
        self.base_url = "https://kosis.kr/openapi/Param/statisticsParameterData.do"

        # 저장 디렉토리 설정
        if save_dir is None:
            self.save_dir = r'C:\Users\82108\OneDrive\바탕 화면\investment\data\analysis_results\KOSIS\retail_sales'
        else:
            self.save_dir = save_dir

        # 디렉토리가 없으면 생성
        os.makedirs(self.save_dir, exist_ok=True)
        logger.info(f"저장 디렉토리: {self.save_dir}")

    def get_data_by_table(self, table_id: str, months: int = 24) -> Optional[pd.DataFrame]:
        """
        KOSIS 통계표별 데이터 수집

        Parameters:
        -----------
        table_id : str
            통계표 ID (예: DT_1K41002, DT_1K41003)
        months : int
            최근 몇 개월 데이터 (기본값: 24개월)
        """
        params = {
            'method': 'getList',
            'apiKey': self.api_key,
            'itmId': 'T1',  # 판매액
            'objL1': 'ALL',  # 전체 업태
            'objL2': '',
            'objL3': '',
            'objL4': '',
            'objL5': '',
            'objL6': '',
            'objL7': '',
            'objL8': '',
            'format': 'json',
            'jsonVD': 'Y',
            'prdSe': 'M',  # 월별
            'newEstPrdCnt': str(months),
            'orgId': '101',
            'tblId': table_id
        }

        try:
            logger.info(f"KOSIS 데이터 요청 (테이블: {table_id}, 최근 {months}개월)")
            response = requests.get(self.base_url, params=params, timeout=30)
            response.raise_for_status()

            data = response.json()

            if not data:
                logger.warning(f"응답 데이터가 비어있습니다 (테이블: {table_id})")
                return None

            df = pd.DataFrame(data)
            logger.info(f"데이터 수집 완료 (테이블: {table_id}): {len(df)} rows")
            logger.info(f"컬럼: {df.columns.tolist()}")

            # 테이블 ID 추가
            df['source_table'] = table_id

            return df

        except requests.exceptions.RequestException as e:
            logger.error(f"API 요청 실패 (테이블: {table_id}): {e}")
            return None
        except Exception as e:
            logger.error(f"데이터 처리 중 오류 (테이블: {table_id}): {e}")
            return None

    def get_channel_sales(self, months: int = 24) -> Optional[pd.DataFrame]:
        """판매채널별 판매액 데이터 수집 (DT_1K41003)"""
        return self.get_data_by_table('DT_1K41003', months)

    def get_product_sales(self, months: int = 24) -> Optional[pd.DataFrame]:
        """제화별 판매액 데이터 수집 (DT_1K41002)"""
        return self.get_data_by_table('DT_1K41002', months)

    def process_data(self, df: pd.DataFrame, data_type: str = 'auto') -> pd.DataFrame:
        """
        데이터 전처리 및 정제

        Parameters:
        -----------
        data_type : str
            'channel' (판매채널별), 'product' (제화별), 'auto' (자동감지)
        """
        if df is None or df.empty:
            logger.warning("처리할 데이터가 없습니다")
            return pd.DataFrame()

        logger.info(f"데이터 전처리 시작 (타입: {data_type})")
        processed = df.copy()

        # 데이터 타입 자동 감지
        if data_type == 'auto':
            if 'source_table' in processed.columns:
                if processed['source_table'].iloc[0] == 'DT_1K41003':
                    data_type = 'channel'
                elif processed['source_table'].iloc[0] == 'DT_1K41002':
                    data_type = 'product'

        processed['data_type'] = data_type

        # 1. 날짜 처리
        if 'PRD_DE' in processed.columns:
            processed['date'] = pd.to_datetime(
                processed['PRD_DE'],
                format='%Y%m',
                errors='coerce'
            )
            processed['year'] = processed['date'].dt.year
            processed['month'] = processed['date'].dt.month
            processed['year_month'] = processed['PRD_DE']

        # 2. 카테고리 정보 (판매채널 또는 제화)
        category_cols = ['C1_NM', 'C2_NM', 'C1', 'C2']
        for col in category_cols:
            if col in processed.columns:
                processed[f'category_{col.lower()}'] = processed[col]

        # 3. 판매액 (숫자로 변환)
        if 'DT' in processed.columns:
            processed['sales_amount'] = pd.to_numeric(
                processed['DT'].astype(str).str.replace(',', '').str.strip(),
                errors='coerce'
            )

        # 4. 단위 정보
        if 'UNIT_NM' in processed.columns:
            processed['unit'] = processed['UNIT_NM']

        # 5. 항목명
        if 'ITM_NM' in processed.columns:
            processed['item_name'] = processed['ITM_NM']

        # 6. 통계표 정보
        if 'TBL_NM' in processed.columns:
            processed['table_name'] = processed['TBL_NM']

        if 'TBL_ID' in processed.columns:
            processed['table_id'] = processed['TBL_ID']

        if 'ORG_ID' in processed.columns:
            processed['org_id'] = processed['ORG_ID']

        # 7. 데이터 수집 시간
        processed['collected_at'] = datetime.now()

        # 8. 결측치 확인
        logger.info(f"결측치 확인:\n{processed.isnull().sum()}")

        return processed

    def create_summary(self, df: pd.DataFrame) -> pd.DataFrame:
        """카테고리별 요약 통계"""
        if df.empty or 'sales_amount' not in df.columns:
            logger.warning("요약 통계를 생성할 수 없습니다")
            return pd.DataFrame()

        # 카테고리 컬럼 찾기
        category_col = None
        for col in ['category_c1_nm', 'category_c2_nm', 'C1_NM', 'C2_NM']:
            if col in df.columns:
                category_col = col
                break

        if category_col is None:
            logger.warning("카테고리 정보를 찾을 수 없습니다")
            return pd.DataFrame()

        summary = df.groupby(category_col).agg({
            'sales_amount': ['count', 'mean', 'sum', 'min', 'max', 'std'],
            'date': ['min', 'max']
        }).round(2)

        summary.columns = ['_'.join(col).strip() for col in summary.columns.values]
        summary = summary.reset_index()
        summary.columns = [
            'category', 'record_count', 'avg_sales', 'total_sales',
            'min_sales', 'max_sales', 'std_sales', 'first_date', 'last_date'
        ]

        summary = summary.sort_values('total_sales', ascending=False)

        return summary

    def create_pivot_table(self, df: pd.DataFrame) -> pd.DataFrame:
        """날짜 x 카테고리 피벗 테이블 생성"""
        if df.empty:
            return pd.DataFrame()

        # 카테고리 컬럼 찾기
        category_col = None
        for col in ['category_c1_nm', 'category_c2_nm', 'C1_NM', 'C2_NM']:
            if col in df.columns:
                category_col = col
                break

        if category_col is None or 'date' not in df.columns:
            logger.warning("피벗 테이블을 생성할 수 없습니다")
            return pd.DataFrame()

        pivot = df.pivot_table(
            values='sales_amount',
            index='date',
            columns=category_col,
            aggfunc='sum'
        )

        pivot = pivot.sort_index()

        return pivot

    def calculate_growth_rate(self, df: pd.DataFrame) -> pd.DataFrame:
        """전년 동월 대비 성장률 계산"""
        if df.empty or 'date' not in df.columns:
            return pd.DataFrame()

        # 카테고리 컬럼 찾기
        category_col = None
        for col in ['category_c1_nm', 'category_c2_nm', 'C1_NM', 'C2_NM']:
            if col in df.columns:
                category_col = col
                break

        if category_col is None:
            return pd.DataFrame()

        df_sorted = df.sort_values(['date', category_col]).copy()

        # 전년 동월 대비 성장률
        df_sorted['yoy_growth'] = df_sorted.groupby(category_col)['sales_amount'].pct_change(12) * 100

        # 전월 대비 성장률
        df_sorted['mom_growth'] = df_sorted.groupby(category_col)['sales_amount'].pct_change(1) * 100

        return df_sorted

    def create_yoy_growth_pivot(self, df: pd.DataFrame) -> pd.DataFrame:
        """전년 동월 대비 성장률(YoY Growth) 피벗 테이블 생성"""
        if df.empty:
            logger.warning("데이터가 비어있습니다")
            return pd.DataFrame()

        if 'yoy_growth' not in df.columns:
            logger.warning("yoy_growth 컬럼이 없습니다. calculate_growth_rate()를 먼저 실행하세요")
            return pd.DataFrame()

        # 카테고리 컬럼 찾기
        category_col = None
        for col in ['category_c1_nm', 'category_c2_nm', 'C1_NM', 'C2_NM']:
            if col in df.columns:
                category_col = col
                break

        if category_col is None or 'date' not in df.columns:
            logger.warning("날짜 또는 카테고리 정보를 찾을 수 없습니다")
            return pd.DataFrame()

        # YoY 성장률 피벗 테이블 생성
        yoy_pivot = df.pivot_table(
            values='yoy_growth',
            index='date',
            columns=category_col,
            aggfunc='mean'
        )

        yoy_pivot = yoy_pivot.sort_index()
        yoy_pivot = yoy_pivot.round(2)

        logger.info(f"YoY 성장률 피벗 테이블 생성 완료: {yoy_pivot.shape}")

        return yoy_pivot

    def create_mom_growth_pivot(self, df: pd.DataFrame) -> pd.DataFrame:
        """전월 대비 성장률(MoM Growth) 피벗 테이블 생성"""
        if df.empty:
            logger.warning("데이터가 비어있습니다")
            return pd.DataFrame()

        if 'mom_growth' not in df.columns:
            logger.warning("mom_growth 컬럼이 없습니다. calculate_growth_rate()를 먼저 실행하세요")
            return pd.DataFrame()

        # 카테고리 컬럼 찾기
        category_col = None
        for col in ['category_c1_nm', 'category_c2_nm', 'C1_NM', 'C2_NM']:
            if col in df.columns:
                category_col = col
                break

        if category_col is None or 'date' not in df.columns:
            logger.warning("날짜 또는 카테고리 정보를 찾을 수 없습니다")
            return pd.DataFrame()

        # MoM 성장률 피벗 테이블 생성
        mom_pivot = df.pivot_table(
            values='mom_growth',
            index='date',
            columns=category_col,
            aggfunc='mean'
        )

        mom_pivot = mom_pivot.sort_index()
        mom_pivot = mom_pivot.round(2)

        logger.info(f"MoM 성장률 피벗 테이블 생성 완료: {mom_pivot.shape}")

        return mom_pivot

    def get_filename_with_date(self, base_name: str = 'kosis_retail_sales') -> str:
        """날짜가 포함된 파일명 생성"""
        today = datetime.now().strftime('%Y%m%d')
        filename = f"{base_name}_{today}.xlsx"
        filepath = os.path.join(self.save_dir, filename)
        return filepath

    def export_to_excel(self, results_dict: Dict[str, Dict[str, pd.DataFrame]],
                       filename: str = None):
        """여러 데이터셋을 하나의 Excel 파일로 저장"""

        # 파일명 생성 (날짜 포함)
        if filename is None:
            filepath = self.get_filename_with_date()
        else:
            filepath = os.path.join(self.save_dir, filename)

        try:
            with pd.ExcelWriter(filepath, engine='openpyxl') as writer:

                # 판매채널별 데이터
                if 'channel' in results_dict:
                    channel = results_dict['channel']

                    if not channel.get('processed', pd.DataFrame()).empty:
                        channel['processed'].to_excel(writer, sheet_name='채널_원본데이터', index=False)

                    if not channel.get('summary', pd.DataFrame()).empty:
                        channel['summary'].to_excel(writer, sheet_name='채널_요약', index=False)

                    if not channel.get('pivot', pd.DataFrame()).empty:
                        channel['pivot'].to_excel(writer, sheet_name='채널_판매액_피벗')

                    if not channel.get('growth', pd.DataFrame()).empty:
                        channel['growth'].to_excel(writer, sheet_name='채널_성장률분석', index=False)

                    if not channel.get('yoy_pivot', pd.DataFrame()).empty:
                        channel['yoy_pivot'].to_excel(writer, sheet_name='채널_YoY_피벗')

                    if not channel.get('mom_pivot', pd.DataFrame()).empty:
                        channel['mom_pivot'].to_excel(writer, sheet_name='채널_MoM_피벗')

                # 제화별 데이터
                if 'product' in results_dict:
                    product = results_dict['product']

                    if not product.get('processed', pd.DataFrame()).empty:
                        product['processed'].to_excel(writer, sheet_name='제화_원본데이터', index=False)

                    if not product.get('summary', pd.DataFrame()).empty:
                        product['summary'].to_excel(writer, sheet_name='제화_요약', index=False)

                    if not product.get('pivot', pd.DataFrame()).empty:
                        product['pivot'].to_excel(writer, sheet_name='제화_판매액_피벗')

                    if not product.get('growth', pd.DataFrame()).empty:
                        product['growth'].to_excel(writer, sheet_name='제화_성장률분석', index=False)

                    if not product.get('yoy_pivot', pd.DataFrame()).empty:
                        product['yoy_pivot'].to_excel(writer, sheet_name='제화_YoY_피벗')

                    if not product.get('mom_pivot', pd.DataFrame()).empty:
                        product['mom_pivot'].to_excel(writer, sheet_name='제화_MoM_피벗')

            logger.info(f"Excel 파일 저장 완료: {filepath}")

        except Exception as e:
            logger.error(f"Excel 저장 실패: {e}")

    def run_single_collection(self, table_id: str, data_type: str, months: int = 24) -> Dict[str, pd.DataFrame]:
        """단일 테이블 수집 프로세스"""
        logger.info(f"=== {data_type} 데이터 수집 시작 (테이블: {table_id}) ===")

        # 1. 데이터 수집
        raw_data = self.get_data_by_table(table_id, months)
        if raw_data is None or raw_data.empty:
            logger.error(f"{data_type} 데이터 수집 실패")
            return {
                'raw': pd.DataFrame(),
                'processed': pd.DataFrame(),
                'summary': pd.DataFrame(),
                'pivot': pd.DataFrame(),
                'growth': pd.DataFrame(),
                'yoy_pivot': pd.DataFrame(),
                'mom_pivot': pd.DataFrame()
            }

        # 2. 데이터 처리
        processed_data = self.process_data(raw_data, data_type)

        # 3. 요약 통계 생성
        summary = self.create_summary(processed_data)
        if not summary.empty:
            logger.info(f"\n=== {data_type} 요약 통계 ===")
            print(summary.to_string(index=False))

        # 4. 판매액 피벗 테이블 생성
        pivot = self.create_pivot_table(processed_data)
        if not pivot.empty:
            logger.info(f"\n=== {data_type} 판매액 피벗 테이블 ===")
            print(pivot.tail(10))

        # 5. 성장률 계산
        growth_data = self.calculate_growth_rate(processed_data)

        # 6. YoY 성장률 피벗 테이블 생성
        yoy_pivot = self.create_yoy_growth_pivot(growth_data)
        if not yoy_pivot.empty:
            logger.info(f"\n=== {data_type} YoY 성장률 피벗 테이블 ===")
            print(yoy_pivot.tail(12))

        # 7. MoM 성장률 피벗 테이블 생성
        mom_pivot = self.create_mom_growth_pivot(growth_data)

        logger.info(f"=== {data_type} 데이터 수집 완료 ===\n")

        return {
            'raw': raw_data,
            'processed': processed_data,
            'summary': summary,
            'pivot': pivot,
            'growth': growth_data,
            'yoy_pivot': yoy_pivot,
            'mom_pivot': mom_pivot
        }

    def run_all_collection(self, months: int = 24, save_excel: bool = True) -> Dict[str, Dict[str, pd.DataFrame]]:
        """
        판매채널별 + 제화별 데이터 모두 수집

        Returns:
        --------
        dict: 'channel'과 'product' 키를 가진 딕셔너리
        """
        logger.info("=== KOSIS 소매판매 전체 데이터 수집 시작 ===\n")

        results = {}

        # 1. 판매채널별 데이터 수집 (DT_1K41003)
        results['channel'] = self.run_single_collection('DT_1K41003', 'channel', months)

        # 2. 제화별 데이터 수집 (DT_1K41002)
        results['product'] = self.run_single_collection('DT_1K41002', 'product', months)

        # 3. Excel 저장
        if save_excel:
            self.export_to_excel(results)

        logger.info("=== KOSIS 소매판매 전체 데이터 수집 완료 ===")

        return results


def main():
    # API 키 설정
    kosis_key = "ZTFhMjg1MzhmNmFiYWJlYmY3ZWUxZDA0ZDI2ZTM0YWU="

    # 저장 경로 설정
    save_directory = r'C:\Users\82108\OneDrive\바탕 화면\investment\data\analysis_results\KOSIS\retail_sales'

    # 수집기 초기화
    collector = KOSISRetailCollector(kosis_key, save_dir=save_directory)

    # 전체 데이터 수집 (판매채널별 + 제화별)
    all_results = collector.run_all_collection(months=36, save_excel=True)

    # 판매채널별 결과
    channel_results = all_results['channel']
    print("\n=== 판매채널별 YoY 성장률 (최근 6개월) ===")
    if not channel_results['yoy_pivot'].empty:
        print(channel_results['yoy_pivot'].tail(6))

    # 제화별 결과
    product_results = all_results['product']
    print("\n=== 제화별 YoY 성장률 (최근 6개월) ===")
    if not product_results['yoy_pivot'].empty:
        print(product_results['yoy_pivot'].tail(6))

    print(f"\n파일 저장 위치: {save_directory}")
    print(f"파일명 형식: kosis_retail_sales_YYYYMMDD.xlsx")


if __name__ == "__main__":
    main()

2026-02-11 21:40:11,423 - INFO - 저장 디렉토리: C:\Users\82108\OneDrive\바탕 화면\investment\data\analysis_results\KOSIS\retail_sales
2026-02-11 21:40:11,424 - INFO - === KOSIS 소매판매 전체 데이터 수집 시작 ===

2026-02-11 21:40:11,424 - INFO - === channel 데이터 수집 시작 (테이블: DT_1K41003) ===
2026-02-11 21:40:11,425 - INFO - KOSIS 데이터 요청 (테이블: DT_1K41003, 최근 36개월)
2026-02-11 21:40:11,696 - INFO - 데이터 수집 완료 (테이블: DT_1K41003): 288 rows
2026-02-11 21:40:11,697 - INFO - 컬럼: ['C1_OBJ_NM', 'DT', 'C1', 'PRD_SE', 'UNIT_NM_ENG', 'ITM_ID', 'TBL_ID', 'ITM_NM', 'TBL_NM', 'PRD_DE', 'LST_CHN_DE', 'C1_NM_ENG', 'C1_NM', 'UNIT_NM', 'ITM_NM_ENG', 'ORG_ID', 'C1_OBJ_NM_ENG']
2026-02-11 21:40:11,699 - INFO - 데이터 전처리 시작 (타입: channel)
2026-02-11 21:40:11,706 - INFO - 결측치 확인:
C1_OBJ_NM         0
DT                0
C1                0
PRD_SE            0
UNIT_NM_ENG       0
ITM_ID            0
TBL_ID            0
ITM_NM            0
TBL_NM            0
PRD_DE            0
LST_CHN_DE        0
C1_NM_ENG         0
C1_NM             0
UNIT_NM           0
ITM_NM_ENG        0
ORG_ID            0
C1_OBJ_NM_ENG     0
source_table      0
data_type         0
date              0
year              0
month             0
year_month        0
category_c1_nm    0
category_c1       0
sales_amount      0
unit              0
item_name         0
table_name        0
table_id          0
org_id            0
collected_at      0
dtype: int64
2026-02-11 21:40:11,712 - INFO -
=== channel 요약 통계 ===
2026-02-11 21:40:11,719 - INFO -
=== channel 판매액 피벗 테이블 ===
2026-02-11 21:40:11,731 - INFO - YoY 성장률 피벗 테이블 생성 완료: (24, 8)
2026-02-11 21:40:11,732 - INFO -
=== channel YoY 성장률 피벗 테이블 ===
2026-02-11 21:40:11,740 - INFO - MoM 성장률 피벗 테이블 생성 완료: (35, 8)
2026-02-11 21:40:11,742 - INFO - === channel 데이터 수집 완료 ===

2026-02-11 21:40:11,742 - INFO - === product 데이터 수집 시작 (테이블: DT_1K41002) ===
2026-02-11 21:40:11,742 - INFO - KOSIS 데이터 요청 (테이블: DT_1K41002, 최근 36개월)

    category  record_count   avg_sales  total_sales  min_sales  max_sales  std_sales first_date  last_date
       전문소매점            36 15691888.94    564908002   14491139   17026074  677373.14 2023-01-01 2025-12-01
      무점포 소매            36 11436106.17    411699822    9986914   12709635  603605.65 2023-01-01 2025-12-01
승용차 및 연료 소매점            36 10824028.75    389665035    9274173   12266219  684763.12 2023-01-01 2025-12-01
  슈퍼마켓 및 잡화점            36  5626100.86    202539631    4828445    6411664  294360.59 2023-01-01 2025-12-01
         백화점            36  3401036.25    122437305    2967662    3998041  289825.16 2023-01-01 2025-12-01
        대형마트            36  3060581.47    110180933    2473948    3861641  262166.90 2023-01-01 2025-12-01
         편의점            36  2620157.42     94325667    2160538    2866979  185835.31 2023-01-01 2025-12-01
         면세점            36  1128645.25     40631229     797391    1590894  145459.83 2023-01-01 2025-12-01
category_c1_nm     대형마트      면세점    무점포 소매      백화점  슈퍼마켓 및 잡화점  승용차 및 연료 소매점  \
date
2025-03-01      3112909  1084509  11926943  3475942     5522466      11570405
2025-04-01      2749521  1184867  11705511  3161028     5366329      11210015
2025-05-01      3029991  1052538  11826145  3574772     5731509      11159593
2025-06-01      2942962  1085420  11489626  3221595     5504482      11116652
2025-07-01      3019032   919954  12082229  3142468     5638700      11068342
2025-08-01      2998664  1019469  11398255  3090567     5640456      10992621
2025-09-01      3136562  1067415  12709635  3459424     5669565      11733293
2025-10-01      3131928  1048264  11773260  3739072     5793559      10421096
2025-11-01      2873322   997143  12509742  3937274     5435158      11747412
2025-12-01      2940431  1119535  12446954  3998041     5431868      12266219

category_c1_nm     전문소매점      편의점
date
2025-03-01      15924676  2555112
2025-04-01      15276897  2595518
2025-05-01      16080477  2734445
2025-06-01      15343837  2699755
2025-07-01      15862662  2852682
2025-08-01      15066187  2866979
2025-09-01      16216400  2799065
2025-10-01      17026074  2777111
2025-11-01      16503476  2611321
2025-12-01      16944846  2539500
category_c1_nm   대형마트    면세점  무점포 소매   백화점  슈퍼마켓 및 잡화점  승용차 및 연료 소매점  전문소매점  \
date
2025-01-01      18.80 -40.01   -2.06  7.44       10.34          2.14   3.04
2025-02-01     -16.92   9.33    2.05 -4.52      -13.17         13.31  -0.63
2025-03-01      -0.88  -8.60    2.75 -2.70       -0.23          4.86   2.88
2025-04-01      -2.02  -5.25    1.47 -5.07       -0.49          6.31   0.54
2025-05-01      -1.99 -16.08    0.11  0.60       -0.68          4.21   1.53
2025-06-01      -0.09  -9.52    3.04 -1.03       -2.12          6.17   1.25
2025-07-01       0.17 -19.86    6.55  1.10       -0.27          7.49   4.61
2025-08-01     -10.66 -16.13    4.30  3.26       -5.70          5.33   3.77
2025-09-01      -7.31 -10.60   14.84  3.49       -8.15         12.60   0.42
2025-10-01      10.08  -5.66    1.30  8.20        4.30         -3.64   5.79
2025-11-01      -4.91  -1.74    3.87  6.29       -1.09          6.52   3.87
2025-12-01      -5.59 -11.00    4.82  3.14       -2.87          9.06   4.33

category_c1_nm   편의점
date
2025-01-01      0.36
2025-02-01     -5.78
2025-03-01      0.17
2025-04-01     -1.51
2025-05-01     -1.01
2025-06-01     -1.68
2025-07-01      3.03
2025-08-01      0.22
2025-09-01      0.15
2025-10-01     -0.16
2025-11-01     -0.13
2025-12-01      0.98

2026-02-11 21:40:12,111 - INFO - 데이터 수집 완료 (테이블: DT_1K41002): 720 rows
2026-02-11 21:40:12,112 - INFO - 컬럼: ['C1_OBJ_NM', 'DT', 'C1', 'PRD_SE', 'UNIT_NM_ENG', 'ITM_ID', 'TBL_ID', 'ITM_NM', 'TBL_NM', 'PRD_DE', 'LST_CHN_DE', 'C1_NM_ENG', 'C1_NM', 'UNIT_NM', 'ITM_NM_ENG', 'ORG_ID', 'C1_OBJ_NM_ENG']
2026-02-11 21:40:12,114 - INFO - 데이터 전처리 시작 (타입: product)
2026-02-11 21:40:12,122 - INFO - 결측치 확인:
C1_OBJ_NM         0
DT                0
C1                0
PRD_SE            0
UNIT_NM_ENG       0
ITM_ID            0
TBL_ID            0
ITM_NM            0
TBL_NM            0
PRD_DE            0
LST_CHN_DE        0
C1_NM_ENG         0
C1_NM             0
UNIT_NM           0
ITM_NM_ENG        0
ORG_ID            0
C1_OBJ_NM_ENG     0
source_table      0
data_type         0
date              0
year              0
month             0
year_month        0
category_c1_nm    0
category_c1       0
sales_amount      0
unit              0
item_name         0
table_name        0
table_id          0
org_id            0
collected_at      0
dtype: int64
2026-02-11 21:40:12,127 - INFO -
=== product 요약 통계 ===
2026-02-11 21:40:12,134 - INFO -
=== product 판매액 피벗 테이블 ===
2026-02-11 21:40:12,148 - INFO - YoY 성장률 피벗 테이블 생성 완료: (24, 20)
2026-02-11 21:40:12,149 - INFO -
=== product YoY 성장률 피벗 테이블 ===
2026-02-11 21:40:12,160 - INFO - MoM 성장률 피벗 테이블 생성 완료: (35, 20)
2026-02-11 21:40:12,160 - INFO - === product 데이터 수집 완료 ===

  category  record_count   avg_sales  total_sales  min_sales  max_sales  std_sales first_date  last_date
        합계            36 53788545.11   1936387624   48625429   57687394 1987300.91 2023-01-01 2025-12-01
합계(승용차 제외)            36 48272009.64   1737792347   43423441   51436615 1708670.14 2023-01-01 2025-12-01
      비내구재            36 29855716.00   1074805776   26341190   32769820 1343425.02 2023-01-01 2025-12-01
      음식료품            36 15034936.03    541257697   12480241   17766442 1110545.40 2023-01-01 2025-12-01
       내구재            36 13425676.11    483324340   11590025   14858028  748771.77 2023-01-01 2025-12-01
      준내구재            36 10507153.00    378257508    8658700   12197737 1124360.67 2023-01-01 2025-12-01
        의복            36  5785716.64    208285799    4371774    7281203  852234.45 2023-01-01 2025-12-01
       승용차            36  5516535.47    198595277    4159036    6642089  614598.55 2023-01-01 2025-12-01
      차량연료            36  4903817.25    176537421    4335672    5369726  241302.24 2023-01-01 2025-12-01
    기타비내구재            36  3649786.39    131392310    3399855    4050780  151294.19 2023-01-01 2025-12-01
       화장품            36  2853579.44    102728860    2588789    3234820  175876.22 2023-01-01 2025-12-01
       의약품            36  2629570.33     94664532    2285066    3011931  182377.76 2023-01-01 2025-12-01
      가전제품            36  2547316.97     91703411    2177247    3144003  262897.80 2023-01-01 2025-12-01
통신기기 및 컴퓨터            36  2404938.56     86577788    2080026    3253751  289638.01 2023-01-01 2025-12-01
     기타내구재            36  2047496.75     73709883    1655120    2581340  189103.69 2023-01-01 2025-12-01
    기타준내구재            36  2022032.47     72793169    1652812    2186972  121747.60 2023-01-01 2025-12-01
오락 취미 경기용품            36  1351935.47     48669677    1057712    1652951  149013.75 2023-01-01 2025-12-01
   신발 및 가방            36  1347468.42     48508863    1180304    1496425   96935.03 2023-01-01 2025-12-01
        가구            36   909388.36     32737981     787377    1038644   56496.70 2023-01-01 2025-12-01
     서적 문구            36   784026.56     28224956     642322     979742   88105.66 2023-01-01 2025-12-01
category_c1_nm      가구     가전제품    기타내구재   기타비내구재   기타준내구재       내구재  \
date
2025-03-01      986460  2306086  2111153  3892854  1910183  13943881
2025-04-01      860271  2255199  2054315  3743599  2015680  13323881
2025-05-01      886293  2547072  2137705  3803542  2057399  13893551
2025-06-01      894921  2619934  2091809  3656558  2050019  13868877
2025-07-01      906506  2999675  2207303  3758851  2121076  14494944
2025-08-01      922954  2444481  2174267  3631435  1974990  13533047
2025-09-01      883333  2292488  2358720  3642346  2023056  14858028
2025-10-01      889334  2215871  2421151  3751827  2016830  13043147
2025-11-01      926352  2426721  2400860  3813202  1959028  14187960
2025-12-01      953363  2286894  2581340  4050780  2022452  14332119

category_c1_nm      비내구재   서적 문구      승용차  신발 및 가방  오락 취미 경기용품      음식료품  \
date
2025-03-01      30503689  965098  6092242  1469120     1324332  14892331
2025-04-01      29408291  737978  6062608  1410062     1372718  14537693
2025-05-01      30304660  685866  5977943  1450397     1421296  15328681
2025-06-01      29304425  642322  6098677  1358508     1251555  14742350
2025-07-01      30223688  779054  5760754  1288601     1281561  15219581
2025-08-01      30365403  756316  5706647  1271192     1241201  15489433
2025-09-01      31917235  754747  6642089  1316772     1322475  16888029
2025-10-01      30551888  678272  5260548  1453775     1508411  15763108
2025-11-01      30366828  743780  6070075  1424243     1395586  14865828
2025-12-01      31700192  943573  6250779  1461353     1356154  15340952

category_c1_nm       의복      의약품      준내구재     차량연료  통신기기 및 컴퓨터        합계  \
date
2025-03-01      6021757  2822651  10725392  4986384     2447940  55172962
2025-04-01      5719054  2778086  10517514  4782798     2091488  53249686
2025-05-01      6062167  2812363  10991259  4876736     2344538  55189470
2025-06-01      5570945  2702919  10231027  4755388     2163536  53404329
2025-07-01      5176199  2804264   9867437  5071863     2620706  54586069
2025-08-01      4687365  2770307   9174748  5052730     2284698  53073198
2025-09-01      5353793  2914761  10016096  4839564     2681398  56791359
2025-10-01      7136313  2893448  12115329  4785570     2256243  55710364
2025-11-01      7281203  2932279  12060060  5173545     2363952  56614848
2025-12-01      6815124  3011931  11655083  5335436     2259743  57687394

category_c1_nm  합계(승용차 제외)      화장품
date
2025-03-01        49080720  2944371
2025-04-01        47187078  2828137
2025-05-01        49211527  2797472
2025-06-01        47305652  2804888
2025-07-01        48825315  2590075
2025-08-01        47366551  2665182
2025-09-01        50149270  2877788
2025-10-01        50449816  2679663
2025-11-01        50544773  2838194
2025-12-01        51436615  3017520
category_c1_nm    가구   가전제품  기타내구재  기타비내구재  기타준내구재    내구재  비내구재  서적 문구    승용차  \
date
2025-01-01     -8.10 -13.47   2.79    3.82  -14.99  -8.80  7.79  -6.92  -0.95
2025-02-01      2.03  -4.81   8.52    4.41   -9.62  14.04 -4.64  -2.17  20.31
2025-03-01     -5.02  -3.77   1.79    4.61   -8.92   3.75  2.90  -1.49   8.93
2025-04-01     -5.28 -10.92   4.23    2.81   -2.62   4.01  1.98  -0.11  14.02
2025-05-01     -6.55  -7.51   1.83   -1.53   -3.99   4.36  0.18  -7.09  11.16
2025-06-01     -5.19  -7.49   5.18    3.49   -2.83   4.73  1.81  -6.67  12.99
2025-07-01     -0.11   3.07   3.63    4.66    1.47   6.34  3.48   2.71  12.42
2025-08-01     -0.18 -10.05  11.90    4.15    0.02   6.26 -1.06   2.44  13.58
2025-09-01      1.55  -1.62  18.35    5.43    3.37  12.17  1.61   5.69  21.74
2025-10-01     -6.97  -5.84  22.73    3.08   -4.56  -2.19  5.04  -6.33  -7.53
2025-11-01     -4.11  -5.79  24.38    5.94   -6.86   5.14  4.00  -1.35   5.44
2025-12-01     -1.82   0.54  17.44    6.66   -6.44   8.49  2.67   1.29  12.33

category_c1_nm  신발 및 가방  오락 취미 경기용품   음식료품    의복    의약품  준내구재  차량연료  \
date
2025-01-01         3.07        0.54  15.50  4.55  10.05 -0.25  3.92
2025-02-01        -4.76       -5.62 -12.88 -3.25  11.09 -5.07  4.59
2025-03-01         3.76       -1.92   2.33 -2.22  12.98 -2.69  0.35
2025-04-01        -1.50       -4.74   2.55 -6.23   9.65 -4.75 -2.15
2025-05-01        -3.08       -6.98   1.83  0.02   9.03 -2.11 -3.50
2025-06-01        -3.99       -6.49   2.59 -1.53   8.00 -2.75 -1.86
2025-07-01         0.69        2.41   4.42  2.84   7.46  2.20  2.69
2025-08-01         0.78        2.87  -1.93  6.02   1.76  3.51 -2.86
2025-09-01        -1.16       -2.32  -0.74  2.47  11.57  1.50  2.23
2025-10-01         0.88       -0.17   7.69  5.06   8.57  2.17  0.74
2025-11-01        -0.69       -3.56   1.64  2.03   9.84 -0.50  6.97
2025-12-01         5.39       -2.06   1.14  1.74   9.03  0.20  5.44

category_c1_nm  통신기기 및 컴퓨터    합계  합계(승용차 제외)    화장품
date
2025-01-01          -23.41  2.33        2.62 -16.95
2025-02-01           28.92 -0.21       -2.19   0.58
2025-03-01            4.72  1.97        1.17   0.73
2025-04-01            0.45  1.06       -0.39  -1.13
2025-05-01            9.86  0.72       -0.41  -5.62
2025-06-01            4.01  1.63        0.33  -1.36
2025-07-01            2.45  3.99        3.08  -5.24
2025-08-01            7.42  1.50        0.21  -3.01
2025-09-01            3.26  4.16        2.20  -0.10
2025-10-01           -4.56  2.64        3.83   0.37
2025-11-01            4.37  3.29        3.04   4.62
2025-12-01            2.61  3.53        2.56  -4.39

2026-02-11 21:40:13,484 - INFO - Excel 파일 저장 완료: C:\Users\82108\OneDrive\바탕 화면\investment\data\analysis_results\KOSIS\retail_sales\kosis_retail_sales_20260211.xlsx
2026-02-11 21:40:13,486 - INFO - === KOSIS 소매판매 전체 데이터 수집 완료 ===

=== 판매채널별 YoY 성장률 (최근 6개월) ===
category_c1_nm   대형마트    면세점  무점포 소매   백화점  슈퍼마켓 및 잡화점  승용차 및 연료 소매점  전문소매점  \
date
2025-07-01       0.17 -19.86    6.55  1.10       -0.27          7.49   4.61
2025-08-01     -10.66 -16.13    4.30  3.26       -5.70          5.33   3.77
2025-09-01      -7.31 -10.60   14.84  3.49       -8.15         12.60   0.42
2025-10-01      10.08  -5.66    1.30  8.20        4.30         -3.64   5.79
2025-11-01      -4.91  -1.74    3.87  6.29       -1.09          6.52   3.87
2025-12-01      -5.59 -11.00    4.82  3.14       -2.87          9.06   4.33

category_c1_nm   편의점
date
2025-07-01      3.03
2025-08-01      0.22
2025-09-01      0.15
2025-10-01     -0.16
2025-11-01     -0.13
2025-12-01      0.98

=== 제화별 YoY 성장률 (최근 6개월) ===
category_c1_nm    가구   가전제품  기타내구재  기타비내구재  기타준내구재    내구재  비내구재  서적 문구    승용차  \
date
2025-07-01     -0.11   3.07   3.63    4.66    1.47   6.34  3.48   2.71  12.42
2025-08-01     -0.18 -10.05  11.90    4.15    0.02   6.26 -1.06   2.44  13.58
2025-09-01      1.55  -1.62  18.35    5.43    3.37  12.17  1.61   5.69  21.74
2025-10-01     -6.97  -5.84  22.73    3.08   -4.56  -2.19  5.04  -6.33  -7.53
2025-11-01     -4.11  -5.79  24.38    5.94   -6.86   5.14  4.00  -1.35   5.44
2025-12-01     -1.82   0.54  17.44    6.66   -6.44   8.49  2.67   1.29  12.33

category_c1_nm  신발 및 가방  오락 취미 경기용품  음식료품    의복    의약품  준내구재  차량연료  \
date
2025-07-01         0.69        2.41  4.42  2.84   7.46  2.20  2.69
2025-08-01         0.78        2.87 -1.93  6.02   1.76  3.51 -2.86
2025-09-01        -1.16       -2.32 -0.74  2.47  11.57  1.50  2.23
2025-10-01         0.88       -0.17  7.69  5.06   8.57  2.17  0.74
2025-11-01        -0.69       -3.56  1.64  2.03   9.84 -0.50  6.97
2025-12-01         5.39       -2.06  1.14  1.74   9.03  0.20  5.44

category_c1_nm  통신기기 및 컴퓨터    합계  합계(승용차 제외)   화장품
date
2025-07-01            2.45  3.99        3.08 -5.24
2025-08-01            7.42  1.50        0.21 -3.01
2025-09-01            3.26  4.16        2.20 -0.10
2025-10-01           -4.56  2.64        3.83  0.37
2025-11-01            4.37  3.29        3.04  4.62
2025-12-01            2.61  3.53        2.56 -4.39

파일 저장 위치: C:\Users\82108\OneDrive\바탕 화면\investment\data\analysis_results\KOSIS\retail_sales
파일명 형식: kosis_retail_sales_YYYYMMDD.xlsx

In [23]:
# API 키 설정
kosis_key = "ZTFhMjg1MzhmNmFiYWJlYmY3ZWUxZDA0ZDI2ZTM0YWU="

# 저장 경로 설정
save_directory = r'C:\Users\82108\OneDrive\바탕 화면\investment\data\analysis_results\KOSIS\retail_sales'

# 수집기 초기화
collector = KOSISRetailCollector(kosis_key, save_dir=save_directory)

# 전체 데이터 수집 (판매채널별 + 제화별)
all_results = collector.run_all_collection(months=36, save_excel=True)

# 판매채널별 결과
channel_results = all_results['channel']
print("\n=== 판매채널별 YoY 성장률 (최근 6개월) ===")
if not channel_results['yoy_pivot'].empty:
    print(channel_results['yoy_pivot'].tail(6))

# 제화별 결과
product_results = all_results['product']
print("\n=== 제화별 YoY 성장률 (최근 6개월) ===")
if not product_results['yoy_pivot'].empty:
    print(product_results['yoy_pivot'].tail(6))

print(f"\n파일 저장 위치: {save_directory}")
print(f"파일명 형식: kosis_retail_sales_YYYYMMDD.xlsx")

2026-02-11 21:42:32,251 - INFO - 저장 디렉토리: C:\Users\82108\OneDrive\바탕 화면\investment\data\analysis_results\KOSIS\retail_sales
2026-02-11 21:42:32,251 - INFO - === KOSIS 소매판매 전체 데이터 수집 시작 ===

2026-02-11 21:42:32,251 - INFO - === channel 데이터 수집 시작 (테이블: DT_1K41003) ===
2026-02-11 21:42:32,252 - INFO - KOSIS 데이터 요청 (테이블: DT_1K41003, 최근 36개월)
2026-02-11 21:42:32,511 - INFO - 데이터 수집 완료 (테이블: DT_1K41003): 288 rows
2026-02-11 21:42:32,512 - INFO - 컬럼: ['C1_OBJ_NM', 'DT', 'C1', 'PRD_SE', 'UNIT_NM_ENG', 'ITM_ID', 'TBL_ID', 'ITM_NM', 'TBL_NM', 'PRD_DE', 'LST_CHN_DE', 'C1_NM_ENG', 'C1_NM', 'UNIT_NM', 'ITM_NM_ENG', 'ORG_ID', 'C1_OBJ_NM_ENG']
2026-02-11 21:42:32,514 - INFO - 데이터 전처리 시작 (타입: channel)
2026-02-11 21:42:32,522 - INFO - 결측치 확인:
C1_OBJ_NM         0
DT                0
C1                0
PRD_SE            0
UNIT_NM_ENG       0
ITM_ID            0
TBL_ID            0
ITM_NM            0
TBL_NM            0
PRD_DE            0
LST_CHN_DE        0
C1_NM_ENG         0
C1_NM             0
UNIT_NM           0
ITM_NM_ENG        0
ORG_ID            0
C1_OBJ_NM_ENG     0
source_table      0
data_type         0
date              0
year              0
month             0
year_month        0
category_c1_nm    0
category_c1       0
sales_amount      0
unit              0
item_name         0
table_name        0
table_id          0
org_id            0
collected_at      0
dtype: int64
2026-02-11 21:42:32,527 - INFO -
=== channel 요약 통계 ===
2026-02-11 21:42:32,533 - INFO -
=== channel 판매액 피벗 테이블 ===
2026-02-11 21:42:32,545 - INFO - YoY 성장률 피벗 테이블 생성 완료: (24, 8)
2026-02-11 21:42:32,546 - INFO -
=== channel YoY 성장률 피벗 테이블 ===
2026-02-11 21:42:32,556 - INFO - MoM 성장률 피벗 테이블 생성 완료: (35, 8)
2026-02-11 21:42:32,557 - INFO - === channel 데이터 수집 완료 ===

2026-02-11 21:42:32,557 - INFO - === product 데이터 수집 시작 (테이블: DT_1K41002) ===
2026-02-11 21:42:32,558 - INFO - KOSIS 데이터 요청 (테이블: DT_1K41002, 최근 36개월)

    category  record_count   avg_sales  total_sales  min_sales  max_sales  std_sales first_date  last_date
       전문소매점            36 15691888.94    564908002   14491139   17026074  677373.14 2023-01-01 2025-12-01
      무점포 소매            36 11436106.17    411699822    9986914   12709635  603605.65 2023-01-01 2025-12-01
승용차 및 연료 소매점            36 10824028.75    389665035    9274173   12266219  684763.12 2023-01-01 2025-12-01
  슈퍼마켓 및 잡화점            36  5626100.86    202539631    4828445    6411664  294360.59 2023-01-01 2025-12-01
         백화점            36  3401036.25    122437305    2967662    3998041  289825.16 2023-01-01 2025-12-01
        대형마트            36  3060581.47    110180933    2473948    3861641  262166.90 2023-01-01 2025-12-01
         편의점            36  2620157.42     94325667    2160538    2866979  185835.31 2023-01-01 2025-12-01
         면세점            36  1128645.25     40631229     797391    1590894  145459.83 2023-01-01 2025-12-01
category_c1_nm     대형마트      면세점    무점포 소매      백화점  슈퍼마켓 및 잡화점  승용차 및 연료 소매점  \
date
2025-03-01      3112909  1084509  11926943  3475942     5522466      11570405
2025-04-01      2749521  1184867  11705511  3161028     5366329      11210015
2025-05-01      3029991  1052538  11826145  3574772     5731509      11159593
2025-06-01      2942962  1085420  11489626  3221595     5504482      11116652
2025-07-01      3019032   919954  12082229  3142468     5638700      11068342
2025-08-01      2998664  1019469  11398255  3090567     5640456      10992621
2025-09-01      3136562  1067415  12709635  3459424     5669565      11733293
2025-10-01      3131928  1048264  11773260  3739072     5793559      10421096
2025-11-01      2873322   997143  12509742  3937274     5435158      11747412
2025-12-01      2940431  1119535  12446954  3998041     5431868      12266219

category_c1_nm     전문소매점      편의점
date
2025-03-01      15924676  2555112
2025-04-01      15276897  2595518
2025-05-01      16080477  2734445
2025-06-01      15343837  2699755
2025-07-01      15862662  2852682
2025-08-01      15066187  2866979
2025-09-01      16216400  2799065
2025-10-01      17026074  2777111
2025-11-01      16503476  2611321
2025-12-01      16944846  2539500
category_c1_nm   대형마트    면세점  무점포 소매   백화점  슈퍼마켓 및 잡화점  승용차 및 연료 소매점  전문소매점  \
date
2025-01-01      18.80 -40.01   -2.06  7.44       10.34          2.14   3.04
2025-02-01     -16.92   9.33    2.05 -4.52      -13.17         13.31  -0.63
2025-03-01      -0.88  -8.60    2.75 -2.70       -0.23          4.86   2.88
2025-04-01      -2.02  -5.25    1.47 -5.07       -0.49          6.31   0.54
2025-05-01      -1.99 -16.08    0.11  0.60       -0.68          4.21   1.53
2025-06-01      -0.09  -9.52    3.04 -1.03       -2.12          6.17   1.25
2025-07-01       0.17 -19.86    6.55  1.10       -0.27          7.49   4.61
2025-08-01     -10.66 -16.13    4.30  3.26       -5.70          5.33   3.77
2025-09-01      -7.31 -10.60   14.84  3.49       -8.15         12.60   0.42
2025-10-01      10.08  -5.66    1.30  8.20        4.30         -3.64   5.79
2025-11-01      -4.91  -1.74    3.87  6.29       -1.09          6.52   3.87
2025-12-01      -5.59 -11.00    4.82  3.14       -2.87          9.06   4.33

category_c1_nm   편의점
date
2025-01-01      0.36
2025-02-01     -5.78
2025-03-01      0.17
2025-04-01     -1.51
2025-05-01     -1.01
2025-06-01     -1.68
2025-07-01      3.03
2025-08-01      0.22
2025-09-01      0.15
2025-10-01     -0.16
2025-11-01     -0.13
2025-12-01      0.98

2026-02-11 21:42:32,839 - INFO - 데이터 수집 완료 (테이블: DT_1K41002): 720 rows
2026-02-11 21:42:32,840 - INFO - 컬럼: ['C1_OBJ_NM', 'DT', 'C1', 'PRD_SE', 'UNIT_NM_ENG', 'ITM_ID', 'TBL_ID', 'ITM_NM', 'TBL_NM', 'PRD_DE', 'LST_CHN_DE', 'C1_NM_ENG', 'C1_NM', 'UNIT_NM', 'ITM_NM_ENG', 'ORG_ID', 'C1_OBJ_NM_ENG']
2026-02-11 21:42:32,841 - INFO - 데이터 전처리 시작 (타입: product)
2026-02-11 21:42:32,849 - INFO - 결측치 확인:
C1_OBJ_NM         0
DT                0
C1                0
PRD_SE            0
UNIT_NM_ENG       0
ITM_ID            0
TBL_ID            0
ITM_NM            0
TBL_NM            0
PRD_DE            0
LST_CHN_DE        0
C1_NM_ENG         0
C1_NM             0
UNIT_NM           0
ITM_NM_ENG        0
ORG_ID            0
C1_OBJ_NM_ENG     0
source_table      0
data_type         0
date              0
year              0
month             0
year_month        0
category_c1_nm    0
category_c1       0
sales_amount      0
unit              0
item_name         0
table_name        0
table_id          0
org_id            0
collected_at      0
dtype: int64
2026-02-11 21:42:32,853 - INFO -
=== product 요약 통계 ===
2026-02-11 21:42:32,859 - INFO -
=== product 판매액 피벗 테이블 ===
2026-02-11 21:42:32,873 - INFO - YoY 성장률 피벗 테이블 생성 완료: (24, 20)
2026-02-11 21:42:32,874 - INFO -
=== product YoY 성장률 피벗 테이블 ===
2026-02-11 21:42:32,885 - INFO - MoM 성장률 피벗 테이블 생성 완료: (35, 20)
2026-02-11 21:42:32,886 - INFO - === product 데이터 수집 완료 ===

  category  record_count   avg_sales  total_sales  min_sales  max_sales  std_sales first_date  last_date
        합계            36 53788545.11   1936387624   48625429   57687394 1987300.91 2023-01-01 2025-12-01
합계(승용차 제외)            36 48272009.64   1737792347   43423441   51436615 1708670.14 2023-01-01 2025-12-01
      비내구재            36 29855716.00   1074805776   26341190   32769820 1343425.02 2023-01-01 2025-12-01
      음식료품            36 15034936.03    541257697   12480241   17766442 1110545.40 2023-01-01 2025-12-01
       내구재            36 13425676.11    483324340   11590025   14858028  748771.77 2023-01-01 2025-12-01
      준내구재            36 10507153.00    378257508    8658700   12197737 1124360.67 2023-01-01 2025-12-01
        의복            36  5785716.64    208285799    4371774    7281203  852234.45 2023-01-01 2025-12-01
       승용차            36  5516535.47    198595277    4159036    6642089  614598.55 2023-01-01 2025-12-01
      차량연료            36  4903817.25    176537421    4335672    5369726  241302.24 2023-01-01 2025-12-01
    기타비내구재            36  3649786.39    131392310    3399855    4050780  151294.19 2023-01-01 2025-12-01
       화장품            36  2853579.44    102728860    2588789    3234820  175876.22 2023-01-01 2025-12-01
       의약품            36  2629570.33     94664532    2285066    3011931  182377.76 2023-01-01 2025-12-01
      가전제품            36  2547316.97     91703411    2177247    3144003  262897.80 2023-01-01 2025-12-01
통신기기 및 컴퓨터            36  2404938.56     86577788    2080026    3253751  289638.01 2023-01-01 2025-12-01
     기타내구재            36  2047496.75     73709883    1655120    2581340  189103.69 2023-01-01 2025-12-01
    기타준내구재            36  2022032.47     72793169    1652812    2186972  121747.60 2023-01-01 2025-12-01
오락 취미 경기용품            36  1351935.47     48669677    1057712    1652951  149013.75 2023-01-01 2025-12-01
   신발 및 가방            36  1347468.42     48508863    1180304    1496425   96935.03 2023-01-01 2025-12-01
        가구            36   909388.36     32737981     787377    1038644   56496.70 2023-01-01 2025-12-01
     서적 문구            36   784026.56     28224956     642322     979742   88105.66 2023-01-01 2025-12-01
category_c1_nm      가구     가전제품    기타내구재   기타비내구재   기타준내구재       내구재  \
date
2025-03-01      986460  2306086  2111153  3892854  1910183  13943881
2025-04-01      860271  2255199  2054315  3743599  2015680  13323881
2025-05-01      886293  2547072  2137705  3803542  2057399  13893551
2025-06-01      894921  2619934  2091809  3656558  2050019  13868877
2025-07-01      906506  2999675  2207303  3758851  2121076  14494944
2025-08-01      922954  2444481  2174267  3631435  1974990  13533047
2025-09-01      883333  2292488  2358720  3642346  2023056  14858028
2025-10-01      889334  2215871  2421151  3751827  2016830  13043147
2025-11-01      926352  2426721  2400860  3813202  1959028  14187960
2025-12-01      953363  2286894  2581340  4050780  2022452  14332119

category_c1_nm      비내구재   서적 문구      승용차  신발 및 가방  오락 취미 경기용품      음식료품  \
date
2025-03-01      30503689  965098  6092242  1469120     1324332  14892331
2025-04-01      29408291  737978  6062608  1410062     1372718  14537693
2025-05-01      30304660  685866  5977943  1450397     1421296  15328681
2025-06-01      29304425  642322  6098677  1358508     1251555  14742350
2025-07-01      30223688  779054  5760754  1288601     1281561  15219581
2025-08-01      30365403  756316  5706647  1271192     1241201  15489433
2025-09-01      31917235  754747  6642089  1316772     1322475  16888029
2025-10-01      30551888  678272  5260548  1453775     1508411  15763108
2025-11-01      30366828  743780  6070075  1424243     1395586  14865828
2025-12-01      31700192  943573  6250779  1461353     1356154  15340952

category_c1_nm       의복      의약품      준내구재     차량연료  통신기기 및 컴퓨터        합계  \
date
2025-03-01      6021757  2822651  10725392  4986384     2447940  55172962
2025-04-01      5719054  2778086  10517514  4782798     2091488  53249686
2025-05-01      6062167  2812363  10991259  4876736     2344538  55189470
2025-06-01      5570945  2702919  10231027  4755388     2163536  53404329
2025-07-01      5176199  2804264   9867437  5071863     2620706  54586069
2025-08-01      4687365  2770307   9174748  5052730     2284698  53073198
2025-09-01      5353793  2914761  10016096  4839564     2681398  56791359
2025-10-01      7136313  2893448  12115329  4785570     2256243  55710364
2025-11-01      7281203  2932279  12060060  5173545     2363952  56614848
2025-12-01      6815124  3011931  11655083  5335436     2259743  57687394

category_c1_nm  합계(승용차 제외)      화장품
date
2025-03-01        49080720  2944371
2025-04-01        47187078  2828137
2025-05-01        49211527  2797472
2025-06-01        47305652  2804888
2025-07-01        48825315  2590075
2025-08-01        47366551  2665182
2025-09-01        50149270  2877788
2025-10-01        50449816  2679663
2025-11-01        50544773  2838194
2025-12-01        51436615  3017520
category_c1_nm    가구   가전제품  기타내구재  기타비내구재  기타준내구재    내구재  비내구재  서적 문구    승용차  \
date
2025-01-01     -8.10 -13.47   2.79    3.82  -14.99  -8.80  7.79  -6.92  -0.95
2025-02-01      2.03  -4.81   8.52    4.41   -9.62  14.04 -4.64  -2.17  20.31
2025-03-01     -5.02  -3.77   1.79    4.61   -8.92   3.75  2.90  -1.49   8.93
2025-04-01     -5.28 -10.92   4.23    2.81   -2.62   4.01  1.98  -0.11  14.02
2025-05-01     -6.55  -7.51   1.83   -1.53   -3.99   4.36  0.18  -7.09  11.16
2025-06-01     -5.19  -7.49   5.18    3.49   -2.83   4.73  1.81  -6.67  12.99
2025-07-01     -0.11   3.07   3.63    4.66    1.47   6.34  3.48   2.71  12.42
2025-08-01     -0.18 -10.05  11.90    4.15    0.02   6.26 -1.06   2.44  13.58
2025-09-01      1.55  -1.62  18.35    5.43    3.37  12.17  1.61   5.69  21.74
2025-10-01     -6.97  -5.84  22.73    3.08   -4.56  -2.19  5.04  -6.33  -7.53
2025-11-01     -4.11  -5.79  24.38    5.94   -6.86   5.14  4.00  -1.35   5.44
2025-12-01     -1.82   0.54  17.44    6.66   -6.44   8.49  2.67   1.29  12.33

category_c1_nm  신발 및 가방  오락 취미 경기용품   음식료품    의복    의약품  준내구재  차량연료  \
date
2025-01-01         3.07        0.54  15.50  4.55  10.05 -0.25  3.92
2025-02-01        -4.76       -5.62 -12.88 -3.25  11.09 -5.07  4.59
2025-03-01         3.76       -1.92   2.33 -2.22  12.98 -2.69  0.35
2025-04-01        -1.50       -4.74   2.55 -6.23   9.65 -4.75 -2.15
2025-05-01        -3.08       -6.98   1.83  0.02   9.03 -2.11 -3.50
2025-06-01        -3.99       -6.49   2.59 -1.53   8.00 -2.75 -1.86
2025-07-01         0.69        2.41   4.42  2.84   7.46  2.20  2.69
2025-08-01         0.78        2.87  -1.93  6.02   1.76  3.51 -2.86
2025-09-01        -1.16       -2.32  -0.74  2.47  11.57  1.50  2.23
2025-10-01         0.88       -0.17   7.69  5.06   8.57  2.17  0.74
2025-11-01        -0.69       -3.56   1.64  2.03   9.84 -0.50  6.97
2025-12-01         5.39       -2.06   1.14  1.74   9.03  0.20  5.44

category_c1_nm  통신기기 및 컴퓨터    합계  합계(승용차 제외)    화장품
date
2025-01-01          -23.41  2.33        2.62 -16.95
2025-02-01           28.92 -0.21       -2.19   0.58
2025-03-01            4.72  1.97        1.17   0.73
2025-04-01            0.45  1.06       -0.39  -1.13
2025-05-01            9.86  0.72       -0.41  -5.62
2025-06-01            4.01  1.63        0.33  -1.36
2025-07-01            2.45  3.99        3.08  -5.24
2025-08-01            7.42  1.50        0.21  -3.01
2025-09-01            3.26  4.16        2.20  -0.10
2025-10-01           -4.56  2.64        3.83   0.37
2025-11-01            4.37  3.29        3.04   4.62
2025-12-01            2.61  3.53        2.56  -4.39

2026-02-11 21:42:34,429 - INFO - Excel 파일 저장 완료: C:\Users\82108\OneDrive\바탕 화면\investment\data\analysis_results\KOSIS\retail_sales\kosis_retail_sales_20260211.xlsx
2026-02-11 21:42:34,430 - INFO - === KOSIS 소매판매 전체 데이터 수집 완료 ===

=== 판매채널별 YoY 성장률 (최근 6개월) ===
category_c1_nm   대형마트    면세점  무점포 소매   백화점  슈퍼마켓 및 잡화점  승용차 및 연료 소매점  전문소매점  \
date
2025-07-01       0.17 -19.86    6.55  1.10       -0.27          7.49   4.61
2025-08-01     -10.66 -16.13    4.30  3.26       -5.70          5.33   3.77
2025-09-01      -7.31 -10.60   14.84  3.49       -8.15         12.60   0.42
2025-10-01      10.08  -5.66    1.30  8.20        4.30         -3.64   5.79
2025-11-01      -4.91  -1.74    3.87  6.29       -1.09          6.52   3.87
2025-12-01      -5.59 -11.00    4.82  3.14       -2.87          9.06   4.33

category_c1_nm   편의점
date
2025-07-01      3.03
2025-08-01      0.22
2025-09-01      0.15
2025-10-01     -0.16
2025-11-01     -0.13
2025-12-01      0.98

=== 제화별 YoY 성장률 (최근 6개월) ===
category_c1_nm    가구   가전제품  기타내구재  기타비내구재  기타준내구재    내구재  비내구재  서적 문구    승용차  \
date
2025-07-01     -0.11   3.07   3.63    4.66    1.47   6.34  3.48   2.71  12.42
2025-08-01     -0.18 -10.05  11.90    4.15    0.02   6.26 -1.06   2.44  13.58
2025-09-01      1.55  -1.62  18.35    5.43    3.37  12.17  1.61   5.69  21.74
2025-10-01     -6.97  -5.84  22.73    3.08   -4.56  -2.19  5.04  -6.33  -7.53
2025-11-01     -4.11  -5.79  24.38    5.94   -6.86   5.14  4.00  -1.35   5.44
2025-12-01     -1.82   0.54  17.44    6.66   -6.44   8.49  2.67   1.29  12.33

category_c1_nm  신발 및 가방  오락 취미 경기용품  음식료품    의복    의약품  준내구재  차량연료  \
date
2025-07-01         0.69        2.41  4.42  2.84   7.46  2.20  2.69
2025-08-01         0.78        2.87 -1.93  6.02   1.76  3.51 -2.86
2025-09-01        -1.16       -2.32 -0.74  2.47  11.57  1.50  2.23
2025-10-01         0.88       -0.17  7.69  5.06   8.57  2.17  0.74
2025-11-01        -0.69       -3.56  1.64  2.03   9.84 -0.50  6.97
2025-12-01         5.39       -2.06  1.14  1.74   9.03  0.20  5.44

category_c1_nm  통신기기 및 컴퓨터    합계  합계(승용차 제외)   화장품
date
2025-07-01            2.45  3.99        3.08 -5.24
2025-08-01            7.42  1.50        0.21 -3.01
2025-09-01            3.26  4.16        2.20 -0.10
2025-10-01           -4.56  2.64        3.83  0.37
2025-11-01            4.37  3.29        3.04  4.62
2025-12-01            2.61  3.53        2.56 -4.39

파일 저장 위치: C:\Users\82108\OneDrive\바탕 화면\investment\data\analysis_results\KOSIS\retail_sales
파일명 형식: kosis_retail_sales_YYYYMMDD.xlsx

In [25]:
channel_results['pivot']

category_c1_nm,대형마트,면세점,무점포 소매,백화점,슈퍼마켓 및 잡화점,승용차 및 연료 소매점,전문소매점,편의점
date,,,,,,,,
2023-01-01,3485426,797391,10630927,3062624,5840069,9767551,15907278,2315240
2023-02-01,2473948,1090319,9986914,2988967,4828445,10363664,14732634,2160538
2023-03-01,2851714,1221714,11016889,3357840,5336950,11500534,16270167,2527029
2023-04-01,2848227,1174846,10280498,3490298,5463118,10708960,16006925,2536429
2023-05-01,2929501,1156823,11223025,3743887,5724140,10885475,16625151,2682666
2023-06-01,2864918,1070833,10688426,3193720,5729623,11350451,15564048,2693016
2023-07-01,3199158,990857,10748058,3245692,5791070,9899621,15059682,2741053
2023-08-01,3237279,1136577,10842814,2967662,5891812,10492762,14958845,2788446
2023-09-01,3528200,1327364,10963703,3327346,6411664,10698097,16050076,2777479
2023-10-01,2971554,1329247,11528116,3550056,5484337,10855775,16457090,2728187
2023-11-01,3015989,1155308,12093697,3667875,5519549,11977905,15842525,2527546
2023-12-01,3284479,1307333,11441141,3896461,5578592,11749350,16279445,2491584
2024-01-01,3250598,1590894,11724335,3256797,5583417,9569600,14830551,2396084
2024-02-01,3126012,915232,10986378,3170646,5721387,9274173,14583289,2314028
2024-03-01,3140594,1186574,11608014,3572575,5535276,11033962,15478517,2550836
2024-04-01,2806119,1250480,11535505,3329812,5392539,10544925,15194568,2635388
2024-05-01,3091592,1254227,11813721,3553294,5770573,10708752,15838303,2762318
2024-06-01,2945683,1199569,11150423,3255239,5623561,10470135,15154883,2745934
2024-07-01,3013906,1147968,11339262,3108132,5653909,10297118,15163446,2768790
2024-08-01,3356573,1215559,10928088,2993084,5981376,10436784,14519336,2860579
2024-09-01,3383965,1194035,11066932,3342618,6172796,10419927,16149159,2794959
2024-10-01,2845103,1111206,11621975,3455846,5554650,10815129,16093998,2781658
2024-11-01,3021773,1014787,12043914,3704262,5495115,11028428,15889276,2614730
2024-12-01,3114580,1257971,11874039,3876229,5592473,11247305,16241232,2514832
2025-01-01,3861641,954397,11482712,3498953,6160992,9774731,15280907,2404668
2025-02-01,2597079,1000604,11212016,3027207,4968106,10508273,14491139,2180162
2025-03-01,3112909,1084509,11926943,3475942,5522466,11570405,15924676,2555112
2025-04-01,2749521,1184867,11705511,3161028,5366329,11210015,15276897,2595518
2025-05-01,3029991,1052538,11826145,3574772,5731509,11159593,16080477,2734445
2025-06-01,2942962,1085420,11489626,3221595,5504482,11116652,15343837,2699755
2025-07-01,3019032,919954,12082229,3142468,5638700,11068342,15862662,2852682
2025-08-01,2998664,1019469,11398255,3090567,5640456,10992621,15066187,2866979
2025-09-01,3136562,1067415,12709635,3459424,5669565,11733293,16216400,2799065
2025-10-01,3131928,1048264,11773260,3739072,5793559,10421096,17026074,2777111
2025-11-01,2873322,997143,12509742,3937274,5435158,11747412,16503476,2611321
2025-12-01,2940431,1119535,12446954,3998041,5431868,12266219,16944846,2539500

In [26]:
channel_results['yoy_pivot']

category_c1_nm,대형마트,면세점,무점포 소매,백화점,슈퍼마켓 및 잡화점,승용차 및 연료 소매점,전문소매점,편의점
date,,,,,,,,
2024-01-01,-6.74,99.51,10.29,6.34,-4.39,-2.03,-6.77,3.49
2024-02-01,26.36,-16.06,10.01,6.08,18.49,-10.51,-1.01,7.10
2024-03-01,10.13,-2.88,5.37,6.40,3.72,-4.06,-4.87,0.94
2024-04-01,-1.48,6.44,12.21,-4.60,-1.29,-1.53,-5.08,3.90
2024-05-01,5.53,8.42,5.26,-5.09,0.81,-1.62,-4.73,2.97
2024-06-01,2.82,12.02,4.32,1.93,-1.85,-7.76,-2.63,1.97
2024-07-01,-5.79,15.86,5.50,-4.24,-2.37,4.02,0.69,1.01
2024-08-01,3.69,6.95,0.79,0.86,1.52,-0.53,-2.94,2.59
2024-09-01,-4.09,-10.04,0.94,0.46,-3.73,-2.60,0.62,0.63
2024-10-01,-4.26,-16.40,0.81,-2.65,1.28,-0.37,-2.21,1.96
2024-11-01,0.19,-12.16,-0.41,0.99,-0.44,-7.93,0.30,3.45
2024-12-01,-5.17,-3.78,3.78,-0.52,0.25,-4.27,-0.23,0.93
2025-01-01,18.80,-40.01,-2.06,7.44,10.34,2.14,3.04,0.36
2025-02-01,-16.92,9.33,2.05,-4.52,-13.17,13.31,-0.63,-5.78
2025-03-01,-0.88,-8.60,2.75,-2.70,-0.23,4.86,2.88,0.17
2025-04-01,-2.02,-5.25,1.47,-5.07,-0.49,6.31,0.54,-1.51
2025-05-01,-1.99,-16.08,0.11,0.60,-0.68,4.21,1.53,-1.01
2025-06-01,-0.09,-9.52,3.04,-1.03,-2.12,6.17,1.25,-1.68
2025-07-01,0.17,-19.86,6.55,1.10,-0.27,7.49,4.61,3.03
2025-08-01,-10.66,-16.13,4.30,3.26,-5.70,5.33,3.77,0.22
2025-09-01,-7.31,-10.60,14.84,3.49,-8.15,12.60,0.42,0.15
2025-10-01,10.08,-5.66,1.30,8.20,4.30,-3.64,5.79,-0.16
2025-11-01,-4.91,-1.74,3.87,6.29,-1.09,6.52,3.87,-0.13
2025-12-01,-5.59,-11.00,4.82,3.14,-2.87,9.06,4.33,0.98

In [29]:
product_results['yoy_pivot']

category_c1_nm,가구,가전제품,기타내구재,기타비내구재,기타준내구재,내구재,비내구재,서적 문구,승용차,신발 및 가방,오락 취미 경기용품,음식료품,의복,의약품,준내구재,차량연료,통신기기 및 컴퓨터,합계,합계(승용차 제외),화장품
date,,,,,,,,,,,,,,,,,,,,
2024-01-01,26.14,2.51,8.41,-1.94,4.82,9.70,-2.84,-0.64,2.83,-0.86,4.26,-7.30,0.62,6.33,1.72,-5.05,24.39,0.76,0.58,18.05
2024-02-01,11.13,-6.53,13.97,0.56,3.86,-8.14,9.65,-0.82,-15.17,1.08,-0.99,22.07,-1.57,8.49,-0.06,-4.78,-15.15,3.01,5.19,-7.19
2024-03-01,16.80,-4.39,8.36,0.58,-0.01,-4.24,2.03,1.25,-9.25,2.42,-8.93,4.62,2.10,3.76,0.25,1.16,-8.74,0.04,1.24,-7.40
2024-04-01,10.47,0.40,0.60,0.42,0.08,-1.97,2.19,-3.29,-4.27,-0.14,-6.07,3.27,-1.41,4.74,-1.61,1.52,-5.82,0.34,0.89,-0.31
2024-05-01,11.88,-7.47,3.99,5.97,0.96,-3.68,2.82,-0.24,-6.09,0.31,-6.56,2.85,-6.42,4.32,-4.25,3.50,-5.25,-0.32,0.35,-2.67
2024-06-01,13.31,-3.74,-0.92,3.00,2.51,-8.60,1.48,-2.57,-17.85,8.62,-6.16,0.20,2.56,3.41,2.11,6.24,-2.62,-1.15,1.21,-2.14
2024-07-01,6.64,-7.43,4.59,4.30,1.04,2.43,2.75,-3.54,0.50,2.36,-8.59,-0.09,-4.18,7.62,-2.88,7.49,17.50,1.58,1.70,5.58
2024-08-01,4.87,-9.20,3.70,0.71,-2.55,-6.65,3.05,-4.44,-1.81,6.86,-8.03,4.16,1.13,10.48,-0.30,1.08,-23.45,-0.05,0.14,-0.95
2024-09-01,8.40,-3.55,7.14,-0.30,-2.94,6.57,-4.15,-6.94,3.96,5.78,-3.77,-4.23,0.44,8.12,-0.17,-9.18,23.49,-1.02,-1.54,-8.33
2024-10-01,6.13,-8.97,2.74,2.59,-1.86,-0.25,-0.86,-1.22,11.27,3.97,-8.59,3.13,-3.04,6.87,-2.79,-11.54,-17.04,-1.14,-2.41,-11.01
2024-11-01,7.61,-8.79,-0.26,-1.13,-2.51,-5.48,-1.04,-4.35,-6.61,9.09,-3.92,2.10,1.34,4.98,0.84,-9.12,-7.74,-1.77,-1.17,-6.00
2024-12-01,5.37,-11.89,-0.93,0.24,-1.16,-5.79,1.35,-3.10,-7.60,-1.92,-0.48,1.61,2.30,7.51,0.79,-0.08,-3.32,-0.55,0.30,0.07
2025-01-01,-8.10,-13.47,2.79,3.82,-14.99,-8.80,7.79,-6.92,-0.95,3.07,0.54,15.50,4.55,10.05,-0.25,3.92,-23.41,2.33,2.62,-16.95
2025-02-01,2.03,-4.81,8.52,4.41,-9.62,14.04,-4.64,-2.17,20.31,-4.76,-5.62,-12.88,-3.25,11.09,-5.07,4.59,28.92,-0.21,-2.19,0.58
2025-03-01,-5.02,-3.77,1.79,4.61,-8.92,3.75,2.90,-1.49,8.93,3.76,-1.92,2.33,-2.22,12.98,-2.69,0.35,4.72,1.97,1.17,0.73
2025-04-01,-5.28,-10.92,4.23,2.81,-2.62,4.01,1.98,-0.11,14.02,-1.50,-4.74,2.55,-6.23,9.65,-4.75,-2.15,0.45,1.06,-0.39,-1.13
2025-05-01,-6.55,-7.51,1.83,-1.53,-3.99,4.36,0.18,-7.09,11.16,-3.08,-6.98,1.83,0.02,9.03,-2.11,-3.50,9.86,0.72,-0.41,-5.62
2025-06-01,-5.19,-7.49,5.18,3.49,-2.83,4.73,1.81,-6.67,12.99,-3.99,-6.49,2.59,-1.53,8.00,-2.75,-1.86,4.01,1.63,0.33,-1.36
2025-07-01,-0.11,3.07,3.63,4.66,1.47,6.34,3.48,2.71,12.42,0.69,2.41,4.42,2.84,7.46,2.20,2.69,2.45,3.99,3.08,-5.24
2025-08-01,-0.18,-10.05,11.90,4.15,0.02,6.26,-1.06,2.44,13.58,0.78,2.87,-1.93,6.02,1.76,3.51,-2.86,7.42,1.50,0.21,-3.01
2025-09-01,1.55,-1.62,18.35,5.43,3.37,12.17,1.61,5.69,21.74,-1.16,-2.32,-0.74,2.47,11.57,1.50,2.23,3.26,4.16,2.20,-0.10
2025-10-01,-6.97,-5.84,22.73,3.08,-4.56,-2.19,5.04,-6.33,-7.53,0.88,-0.17,7.69,5.06,8.57,2.17,0.74,-4.56,2.64,3.83,0.37
2025-11-01,-4.11,-5.79,24.38,5.94,-6.86,5.14,4.00,-1.35,5.44,-0.69,-3.56,1.64,2.03,9.84,-0.50,6.97,4.37,3.29,3.04,4.62
2025-12-01,-1.82,0.54,17.44,6.66,-6.44,8.49,2.67,1.29,12.33,5.39,-2.06,1.14,1.74,9.03,0.20,5.44,2.61,3.53,2.56,-4.39

In [30]:
import requests
import pandas as pd
from datetime import datetime
import logging
from typing import Optional, Dict, List
import json
import os

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

class KOSISRetailCollector:
    """KOSIS 소매판매 데이터 수집 (판매채널별 + 제화별 + 온라인)"""

    def __init__(self, api_key: str, save_dir: str = None):
        self.api_key = api_key
        self.base_url = "https://kosis.kr/openapi/Param/statisticsParameterData.do"

        # 저장 디렉토리 설정
        if save_dir is None:
            self.save_dir = r'C:\Users\82108\OneDrive\바탕 화면\investment\data\analysis_results\KOSIS\retail_sales'
        else:
            self.save_dir = save_dir

        # 디렉토리가 없으면 생성
        os.makedirs(self.save_dir, exist_ok=True)
        logger.info(f"저장 디렉토리: {self.save_dir}")

    def get_data_by_table(self, table_id: str, item_id: str = 'T1',
                         obj_l1: str = 'ALL', obj_l2: str = '',
                         months: int = 24) -> Optional[pd.DataFrame]:
        """
        KOSIS 통계표별 데이터 수집

        Parameters:
        -----------
        table_id : str
            통계표 ID (예: DT_1K41002, DT_1K41003, DT_1KE10041)
        item_id : str
            항목 ID (기본값: 'T1')
        obj_l1 : str
            객체 레벨1 (기본값: 'ALL')
        obj_l2 : str
            객체 레벨2 (기본값: '')
        months : int
            최근 몇 개월 데이터 (기본값: 24개월)
        """
        params = {
            'method': 'getList',
            'apiKey': self.api_key,
            'itmId': item_id,
            'objL1': obj_l1,
            'objL2': obj_l2,
            'objL3': '',
            'objL4': '',
            'objL5': '',
            'objL6': '',
            'objL7': '',
            'objL8': '',
            'format': 'json',
            'jsonVD': 'Y',
            'prdSe': 'M',  # 월별
            'newEstPrdCnt': str(months),
            'orgId': '101',
            'tblId': table_id
        }

        try:
            logger.info(f"KOSIS 데이터 요청 (테이블: {table_id}, 최근 {months}개월)")
            response = requests.get(self.base_url, params=params, timeout=30)
            response.raise_for_status()

            data = response.json()

            if not data:
                logger.warning(f"응답 데이터가 비어있습니다 (테이블: {table_id})")
                return None

            df = pd.DataFrame(data)
            logger.info(f"데이터 수집 완료 (테이블: {table_id}): {len(df)} rows")
            logger.info(f"컬럼: {df.columns.tolist()}")

            # 테이블 ID 추가
            df['source_table'] = table_id

            return df

        except requests.exceptions.RequestException as e:
            logger.error(f"API 요청 실패 (테이블: {table_id}): {e}")
            return None
        except Exception as e:
            logger.error(f"데이터 처리 중 오류 (테이블: {table_id}): {e}")
            return None

    def get_channel_sales(self, months: int = 24) -> Optional[pd.DataFrame]:
        """판매채널별 판매액 데이터 수집 (DT_1K41003)"""
        return self.get_data_by_table('DT_1K41003', item_id='T1', months=months)

    def get_product_sales(self, months: int = 24) -> Optional[pd.DataFrame]:
        """제화별 판매액 데이터 수집 (DT_1K41002)"""
        return self.get_data_by_table('DT_1K41002', item_id='T1', months=months)

    def get_online_sales(self, months: int = 24) -> Optional[pd.DataFrame]:
        """온라인 소매판매액 데이터 수집 (DT_1KE10041)"""
        return self.get_data_by_table('DT_1KE10041', item_id='T20', obj_l1='ALL', obj_l2='ALL', months=months)

    def process_data(self, df: pd.DataFrame, data_type: str = 'auto') -> pd.DataFrame:
        """
        데이터 전처리 및 정제

        Parameters:
        -----------
        data_type : str
            'channel' (판매채널별), 'product' (제화별), 'online' (온라인), 'auto' (자동감지)
        """
        if df is None or df.empty:
            logger.warning("처리할 데이터가 없습니다")
            return pd.DataFrame()

        logger.info(f"데이터 전처리 시작 (타입: {data_type})")
        processed = df.copy()

        # 데이터 타입 자동 감지
        if data_type == 'auto':
            if 'source_table' in processed.columns:
                if processed['source_table'].iloc[0] == 'DT_1K41003':
                    data_type = 'channel'
                elif processed['source_table'].iloc[0] == 'DT_1K41002':
                    data_type = 'product'
                elif processed['source_table'].iloc[0] == 'DT_1KE10041':
                    data_type = 'online'

        processed['data_type'] = data_type

        # 1. 날짜 처리
        if 'PRD_DE' in processed.columns:
            processed['date'] = pd.to_datetime(
                processed['PRD_DE'],
                format='%Y%m',
                errors='coerce'
            )
            processed['year'] = processed['date'].dt.year
            processed['month'] = processed['date'].dt.month
            processed['year_month'] = processed['PRD_DE']

        # 2. 카테고리 정보 (판매채널, 제화, 온라인 상품군)
        category_cols = ['C1_NM', 'C2_NM', 'C1', 'C2']
        for col in category_cols:
            if col in processed.columns:
                processed[f'category_{col.lower()}'] = processed[col]

        # 3. 판매액 (숫자로 변환)
        if 'DT' in processed.columns:
            processed['sales_amount'] = pd.to_numeric(
                processed['DT'].astype(str).str.replace(',', '').str.strip(),
                errors='coerce'
            )

        # 4. 단위 정보
        if 'UNIT_NM' in processed.columns:
            processed['unit'] = processed['UNIT_NM']

        # 5. 항목명
        if 'ITM_NM' in processed.columns:
            processed['item_name'] = processed['ITM_NM']

        # 6. 통계표 정보
        if 'TBL_NM' in processed.columns:
            processed['table_name'] = processed['TBL_NM']

        if 'TBL_ID' in processed.columns:
            processed['table_id'] = processed['TBL_ID']

        if 'ORG_ID' in processed.columns:
            processed['org_id'] = processed['ORG_ID']

        # 7. 데이터 수집 시간
        processed['collected_at'] = datetime.now()

        # 8. 결측치 확인
        logger.info(f"결측치 확인:\n{processed.isnull().sum()}")

        return processed

    def create_summary(self, df: pd.DataFrame) -> pd.DataFrame:
        """카테고리별 요약 통계"""
        if df.empty or 'sales_amount' not in df.columns:
            logger.warning("요약 통계를 생성할 수 없습니다")
            return pd.DataFrame()

        # 카테고리 컬럼 찾기
        category_col = None
        for col in ['category_c1_nm', 'category_c2_nm', 'C1_NM', 'C2_NM']:
            if col in df.columns:
                category_col = col
                break

        if category_col is None:
            logger.warning("카테고리 정보를 찾을 수 없습니다")
            return pd.DataFrame()

        summary = df.groupby(category_col).agg({
            'sales_amount': ['count', 'mean', 'sum', 'min', 'max', 'std'],
            'date': ['min', 'max']
        }).round(2)

        summary.columns = ['_'.join(col).strip() for col in summary.columns.values]
        summary = summary.reset_index()
        summary.columns = [
            'category', 'record_count', 'avg_sales', 'total_sales',
            'min_sales', 'max_sales', 'std_sales', 'first_date', 'last_date'
        ]

        summary = summary.sort_values('total_sales', ascending=False)

        return summary

    def create_pivot_table(self, df: pd.DataFrame) -> pd.DataFrame:
        """날짜 x 카테고리 피벗 테이블 생성"""
        if df.empty:
            return pd.DataFrame()

        # 카테고리 컬럼 찾기
        category_col = None
        for col in ['category_c1_nm', 'category_c2_nm', 'C1_NM', 'C2_NM']:
            if col in df.columns:
                category_col = col
                break

        if category_col is None or 'date' not in df.columns:
            logger.warning("피벗 테이블을 생성할 수 없습니다")
            return pd.DataFrame()

        pivot = df.pivot_table(
            values='sales_amount',
            index='date',
            columns=category_col,
            aggfunc='sum'
        )

        pivot = pivot.sort_index()

        return pivot

    def calculate_growth_rate(self, df: pd.DataFrame) -> pd.DataFrame:
        """전년 동월 대비 성장률 계산"""
        if df.empty or 'date' not in df.columns:
            return pd.DataFrame()

        # 카테고리 컬럼 찾기
        category_col = None
        for col in ['category_c1_nm', 'category_c2_nm', 'C1_NM', 'C2_NM']:
            if col in df.columns:
                category_col = col
                break

        if category_col is None:
            return pd.DataFrame()

        df_sorted = df.sort_values(['date', category_col]).copy()

        # 전년 동월 대비 성장률
        df_sorted['yoy_growth'] = df_sorted.groupby(category_col)['sales_amount'].pct_change(12) * 100

        # 전월 대비 성장률
        df_sorted['mom_growth'] = df_sorted.groupby(category_col)['sales_amount'].pct_change(1) * 100

        return df_sorted

    def create_yoy_growth_pivot(self, df: pd.DataFrame) -> pd.DataFrame:
        """전년 동월 대비 성장률(YoY Growth) 피벗 테이블 생성"""
        if df.empty:
            logger.warning("데이터가 비어있습니다")
            return pd.DataFrame()

        if 'yoy_growth' not in df.columns:
            logger.warning("yoy_growth 컬럼이 없습니다. calculate_growth_rate()를 먼저 실행하세요")
            return pd.DataFrame()

        # 카테고리 컬럼 찾기
        category_col = None
        for col in ['category_c1_nm', 'category_c2_nm', 'C1_NM', 'C2_NM']:
            if col in df.columns:
                category_col = col
                break

        if category_col is None or 'date' not in df.columns:
            logger.warning("날짜 또는 카테고리 정보를 찾을 수 없습니다")
            return pd.DataFrame()

        # YoY 성장률 피벗 테이블 생성
        yoy_pivot = df.pivot_table(
            values='yoy_growth',
            index='date',
            columns=category_col,
            aggfunc='mean'
        )

        yoy_pivot = yoy_pivot.sort_index()
        yoy_pivot = yoy_pivot.round(2)

        logger.info(f"YoY 성장률 피벗 테이블 생성 완료: {yoy_pivot.shape}")

        return yoy_pivot

    def create_mom_growth_pivot(self, df: pd.DataFrame) -> pd.DataFrame:
        """전월 대비 성장률(MoM Growth) 피벗 테이블 생성"""
        if df.empty:
            logger.warning("데이터가 비어있습니다")
            return pd.DataFrame()

        if 'mom_growth' not in df.columns:
            logger.warning("mom_growth 컬럼이 없습니다. calculate_growth_rate()를 먼저 실행하세요")
            return pd.DataFrame()

        # 카테고리 컬럼 찾기
        category_col = None
        for col in ['category_c1_nm', 'category_c2_nm', 'C1_NM', 'C2_NM']:
            if col in df.columns:
                category_col = col
                break

        if category_col is None or 'date' not in df.columns:
            logger.warning("날짜 또는 카테고리 정보를 찾을 수 없습니다")
            return pd.DataFrame()

        # MoM 성장률 피벗 테이블 생성
        mom_pivot = df.pivot_table(
            values='mom_growth',
            index='date',
            columns=category_col,
            aggfunc='mean'
        )

        mom_pivot = mom_pivot.sort_index()
        mom_pivot = mom_pivot.round(2)

        logger.info(f"MoM 성장률 피벗 테이블 생성 완료: {mom_pivot.shape}")

        return mom_pivot

    def get_filename_with_date(self, base_name: str = 'kosis_retail_sales') -> str:
        """날짜가 포함된 파일명 생성"""
        today = datetime.now().strftime('%Y%m%d')
        filename = f"{base_name}_{today}.xlsx"
        filepath = os.path.join(self.save_dir, filename)
        return filepath

    def export_to_excel(self, results_dict: Dict[str, Dict[str, pd.DataFrame]],
                       filename: str = None):
        """여러 데이터셋을 하나의 Excel 파일로 저장"""

        # 파일명 생성 (날짜 포함)
        if filename is None:
            filepath = self.get_filename_with_date()
        else:
            filepath = os.path.join(self.save_dir, filename)

        try:
            with pd.ExcelWriter(filepath, engine='openpyxl') as writer:

                # 판매채널별 데이터
                if 'channel' in results_dict:
                    channel = results_dict['channel']

                    if not channel.get('processed', pd.DataFrame()).empty:
                        channel['processed'].to_excel(writer, sheet_name='채널_원본데이터', index=False)

                    if not channel.get('summary', pd.DataFrame()).empty:
                        channel['summary'].to_excel(writer, sheet_name='채널_요약', index=False)

                    if not channel.get('pivot', pd.DataFrame()).empty:
                        channel['pivot'].to_excel(writer, sheet_name='채널_판매액_피벗')

                    if not channel.get('growth', pd.DataFrame()).empty:
                        channel['growth'].to_excel(writer, sheet_name='채널_성장률분석', index=False)

                    if not channel.get('yoy_pivot', pd.DataFrame()).empty:
                        channel['yoy_pivot'].to_excel(writer, sheet_name='채널_YoY_피벗')

                    if not channel.get('mom_pivot', pd.DataFrame()).empty:
                        channel['mom_pivot'].to_excel(writer, sheet_name='채널_MoM_피벗')

                # 제화별 데이터
                if 'product' in results_dict:
                    product = results_dict['product']

                    if not product.get('processed', pd.DataFrame()).empty:
                        product['processed'].to_excel(writer, sheet_name='제화_원본데이터', index=False)

                    if not product.get('summary', pd.DataFrame()).empty:
                        product['summary'].to_excel(writer, sheet_name='제화_요약', index=False)

                    if not product.get('pivot', pd.DataFrame()).empty:
                        product['pivot'].to_excel(writer, sheet_name='제화_판매액_피벗')

                    if not product.get('growth', pd.DataFrame()).empty:
                        product['growth'].to_excel(writer, sheet_name='제화_성장률분석', index=False)

                    if not product.get('yoy_pivot', pd.DataFrame()).empty:
                        product['yoy_pivot'].to_excel(writer, sheet_name='제화_YoY_피벗')

                    if not product.get('mom_pivot', pd.DataFrame()).empty:
                        product['mom_pivot'].to_excel(writer, sheet_name='제화_MoM_피벗')

                # 온라인 판매 데이터
                if 'online' in results_dict:
                    online = results_dict['online']

                    if not online.get('processed', pd.DataFrame()).empty:
                        online['processed'].to_excel(writer, sheet_name='온라인_원본데이터', index=False)

                    if not online.get('summary', pd.DataFrame()).empty:
                        online['summary'].to_excel(writer, sheet_name='온라인_요약', index=False)

                    if not online.get('pivot', pd.DataFrame()).empty:
                        online['pivot'].to_excel(writer, sheet_name='온라인_판매액_피벗')

                    if not online.get('growth', pd.DataFrame()).empty:
                        online['growth'].to_excel(writer, sheet_name='온라인_성장률분석', index=False)

                    if not online.get('yoy_pivot', pd.DataFrame()).empty:
                        online['yoy_pivot'].to_excel(writer, sheet_name='온라인_YoY_피벗')

                    if not online.get('mom_pivot', pd.DataFrame()).empty:
                        online['mom_pivot'].to_excel(writer, sheet_name='온라인_MoM_피벗')

            logger.info(f"Excel 파일 저장 완료: {filepath}")

        except Exception as e:
            logger.error(f"Excel 저장 실패: {e}")

    def run_single_collection(self, table_id: str, data_type: str,
                             item_id: str = 'T1', obj_l1: str = 'ALL',
                             obj_l2: str = '', months: int = 24) -> Dict[str, pd.DataFrame]:
        """단일 테이블 수집 프로세스"""
        logger.info(f"=== {data_type} 데이터 수집 시작 (테이블: {table_id}) ===")

        # 1. 데이터 수집
        raw_data = self.get_data_by_table(table_id, item_id, obj_l1, obj_l2, months)
        if raw_data is None or raw_data.empty:
            logger.error(f"{data_type} 데이터 수집 실패")
            return {
                'raw': pd.DataFrame(),
                'processed': pd.DataFrame(),
                'summary': pd.DataFrame(),
                'pivot': pd.DataFrame(),
                'growth': pd.DataFrame(),
                'yoy_pivot': pd.DataFrame(),
                'mom_pivot': pd.DataFrame()
            }

        # 2. 데이터 처리
        processed_data = self.process_data(raw_data, data_type)

        # 3. 요약 통계 생성
        summary = self.create_summary(processed_data)
        if not summary.empty:
            logger.info(f"\n=== {data_type} 요약 통계 ===")
            print(summary.to_string(index=False))

        # 4. 판매액 피벗 테이블 생성
        pivot = self.create_pivot_table(processed_data)
        if not pivot.empty:
            logger.info(f"\n=== {data_type} 판매액 피벗 테이블 ===")
            print(pivot.tail(10))

        # 5. 성장률 계산
        growth_data = self.calculate_growth_rate(processed_data)

        # 6. YoY 성장률 피벗 테이블 생성
        yoy_pivot = self.create_yoy_growth_pivot(growth_data)
        if not yoy_pivot.empty:
            logger.info(f"\n=== {data_type} YoY 성장률 피벗 테이블 ===")
            print(yoy_pivot.tail(12))

        # 7. MoM 성장률 피벗 테이블 생성
        mom_pivot = self.create_mom_growth_pivot(growth_data)

        logger.info(f"=== {data_type} 데이터 수집 완료 ===\n")

        return {
            'raw': raw_data,
            'processed': processed_data,
            'summary': summary,
            'pivot': pivot,
            'growth': growth_data,
            'yoy_pivot': yoy_pivot,
            'mom_pivot': mom_pivot
        }

    def run_all_collection(self, months: int = 24, save_excel: bool = True) -> Dict[str, Dict[str, pd.DataFrame]]:
        """
        판매채널별 + 제화별 + 온라인 데이터 모두 수집

        Returns:
        --------
        dict: 'channel', 'product', 'online' 키를 가진 딕셔너리
        """
        logger.info("=== KOSIS 소매판매 전체 데이터 수집 시작 ===\n")

        results = {}

        # 1. 판매채널별 데이터 수집 (DT_1K41003)
        results['channel'] = self.run_single_collection(
            table_id='DT_1K41003',
            data_type='channel',
            item_id='T1',
            obj_l1='ALL',
            obj_l2='',
            months=months
        )

        # 2. 제화별 데이터 수집 (DT_1K41002)
        results['product'] = self.run_single_collection(
            table_id='DT_1K41002',
            data_type='product',
            item_id='T1',
            obj_l1='ALL',
            obj_l2='',
            months=months
        )

        # 3. 온라인 소매판매 데이터 수집 (DT_1KE10041)
        results['online'] = self.run_single_collection(
            table_id='DT_1KE10041',
            data_type='online',
            item_id='T20',
            obj_l1='ALL',
            obj_l2='ALL',
            months=months
        )

        # 4. Excel 저장
        if save_excel:
            self.export_to_excel(results)

        logger.info("=== KOSIS 소매판매 전체 데이터 수집 완료 ===")

        return results


def main():
    # API 키 설정
    kosis_key = "ZTFhMjg1MzhmNmFiYWJlYmY3ZWUxZDA0ZDI2ZTM0YWU="

    # 저장 경로 설정
    save_directory = r'C:\Users\82108\OneDrive\바탕 화면\investment\data\analysis_results\KOSIS\retail_sales'

    # 수집기 초기화
    collector = KOSISRetailCollector(kosis_key, save_dir=save_directory)

    # 전체 데이터 수집 (판매채널별 + 제화별 + 온라인)
    all_results = collector.run_all_collection(months=36, save_excel=True)

    # 판매채널별 결과
    channel_results = all_results['channel']
    print("\n=== 판매채널별 YoY 성장률 (최근 6개월) ===")
    if not channel_results['yoy_pivot'].empty:
        print(channel_results['yoy_pivot'].tail(6))

    # 제화별 결과
    product_results = all_results['product']
    print("\n=== 제화별 YoY 성장률 (최근 6개월) ===")
    if not product_results['yoy_pivot'].empty:
        print(product_results['yoy_pivot'].tail(6))

    # 온라인 판매 결과
    online_results = all_results['online']
    print("\n=== 온라인 판매 YoY 성장률 (최근 6개월) ===")
    if not online_results['yoy_pivot'].empty:
        print(online_results['yoy_pivot'].tail(6))

    print(f"\n파일 저장 위치: {save_directory}")
    print(f"파일명 형식: kosis_retail_sales_YYYYMMDD.xlsx")


if __name__ == "__main__":
    main()

2026-02-11 21:54:02,898 - INFO - 저장 디렉토리: C:\Users\82108\OneDrive\바탕 화면\investment\data\analysis_results\KOSIS\retail_sales
2026-02-11 21:54:02,899 - INFO - === KOSIS 소매판매 전체 데이터 수집 시작 ===

2026-02-11 21:54:02,899 - INFO - === channel 데이터 수집 시작 (테이블: DT_1K41003) ===
2026-02-11 21:54:02,900 - INFO - KOSIS 데이터 요청 (테이블: DT_1K41003, 최근 36개월)
2026-02-11 21:54:03,127 - INFO - 데이터 수집 완료 (테이블: DT_1K41003): 288 rows
2026-02-11 21:54:03,127 - INFO - 컬럼: ['C1_OBJ_NM', 'DT', 'C1', 'PRD_SE', 'UNIT_NM_ENG', 'ITM_ID', 'TBL_ID', 'ITM_NM', 'TBL_NM', 'PRD_DE', 'LST_CHN_DE', 'C1_NM_ENG', 'C1_NM', 'UNIT_NM', 'ITM_NM_ENG', 'ORG_ID', 'C1_OBJ_NM_ENG']
2026-02-11 21:54:03,130 - INFO - 데이터 전처리 시작 (타입: channel)
2026-02-11 21:54:03,137 - INFO - 결측치 확인:
C1_OBJ_NM         0
DT                0
C1                0
PRD_SE            0
UNIT_NM_ENG       0
ITM_ID            0
TBL_ID            0
ITM_NM            0
TBL_NM            0
PRD_DE            0
LST_CHN_DE        0
C1_NM_ENG         0
C1_NM             0
UNIT_NM           0
ITM_NM_ENG        0
ORG_ID            0
C1_OBJ_NM_ENG     0
source_table      0
data_type         0
date              0
year              0
month             0
year_month        0
category_c1_nm    0
category_c1       0
sales_amount      0
unit              0
item_name         0
table_name        0
table_id          0
org_id            0
collected_at      0
dtype: int64
2026-02-11 21:54:03,141 - INFO -
=== channel 요약 통계 ===
2026-02-11 21:54:03,149 - INFO -
=== channel 판매액 피벗 테이블 ===
2026-02-11 21:54:03,161 - INFO - YoY 성장률 피벗 테이블 생성 완료: (24, 8)
2026-02-11 21:54:03,161 - INFO -
=== channel YoY 성장률 피벗 테이블 ===
2026-02-11 21:54:03,169 - INFO - MoM 성장률 피벗 테이블 생성 완료: (35, 8)
2026-02-11 21:54:03,170 - INFO - === channel 데이터 수집 완료 ===

2026-02-11 21:54:03,170 - INFO - === product 데이터 수집 시작 (테이블: DT_1K41002) ===
2026-02-11 21:54:03,171 - INFO - KOSIS 데이터 요청 (테이블: DT_1K41002, 최근 36개월)

    category  record_count   avg_sales  total_sales  min_sales  max_sales  std_sales first_date  last_date
       전문소매점            36 15691888.94    564908002   14491139   17026074  677373.14 2023-01-01 2025-12-01
      무점포 소매            36 11436106.17    411699822    9986914   12709635  603605.65 2023-01-01 2025-12-01
승용차 및 연료 소매점            36 10824028.75    389665035    9274173   12266219  684763.12 2023-01-01 2025-12-01
  슈퍼마켓 및 잡화점            36  5626100.86    202539631    4828445    6411664  294360.59 2023-01-01 2025-12-01
         백화점            36  3401036.25    122437305    2967662    3998041  289825.16 2023-01-01 2025-12-01
        대형마트            36  3060581.47    110180933    2473948    3861641  262166.90 2023-01-01 2025-12-01
         편의점            36  2620157.42     94325667    2160538    2866979  185835.31 2023-01-01 2025-12-01
         면세점            36  1128645.25     40631229     797391    1590894  145459.83 2023-01-01 2025-12-01
category_c1_nm     대형마트      면세점    무점포 소매      백화점  슈퍼마켓 및 잡화점  승용차 및 연료 소매점  \
date
2025-03-01      3112909  1084509  11926943  3475942     5522466      11570405
2025-04-01      2749521  1184867  11705511  3161028     5366329      11210015
2025-05-01      3029991  1052538  11826145  3574772     5731509      11159593
2025-06-01      2942962  1085420  11489626  3221595     5504482      11116652
2025-07-01      3019032   919954  12082229  3142468     5638700      11068342
2025-08-01      2998664  1019469  11398255  3090567     5640456      10992621
2025-09-01      3136562  1067415  12709635  3459424     5669565      11733293
2025-10-01      3131928  1048264  11773260  3739072     5793559      10421096
2025-11-01      2873322   997143  12509742  3937274     5435158      11747412
2025-12-01      2940431  1119535  12446954  3998041     5431868      12266219

category_c1_nm     전문소매점      편의점
date
2025-03-01      15924676  2555112
2025-04-01      15276897  2595518
2025-05-01      16080477  2734445
2025-06-01      15343837  2699755
2025-07-01      15862662  2852682
2025-08-01      15066187  2866979
2025-09-01      16216400  2799065
2025-10-01      17026074  2777111
2025-11-01      16503476  2611321
2025-12-01      16944846  2539500
category_c1_nm   대형마트    면세점  무점포 소매   백화점  슈퍼마켓 및 잡화점  승용차 및 연료 소매점  전문소매점  \
date
2025-01-01      18.80 -40.01   -2.06  7.44       10.34          2.14   3.04
2025-02-01     -16.92   9.33    2.05 -4.52      -13.17         13.31  -0.63
2025-03-01      -0.88  -8.60    2.75 -2.70       -0.23          4.86   2.88
2025-04-01      -2.02  -5.25    1.47 -5.07       -0.49          6.31   0.54
2025-05-01      -1.99 -16.08    0.11  0.60       -0.68          4.21   1.53
2025-06-01      -0.09  -9.52    3.04 -1.03       -2.12          6.17   1.25
2025-07-01       0.17 -19.86    6.55  1.10       -0.27          7.49   4.61
2025-08-01     -10.66 -16.13    4.30  3.26       -5.70          5.33   3.77
2025-09-01      -7.31 -10.60   14.84  3.49       -8.15         12.60   0.42
2025-10-01      10.08  -5.66    1.30  8.20        4.30         -3.64   5.79
2025-11-01      -4.91  -1.74    3.87  6.29       -1.09          6.52   3.87
2025-12-01      -5.59 -11.00    4.82  3.14       -2.87          9.06   4.33

category_c1_nm   편의점
date
2025-01-01      0.36
2025-02-01     -5.78
2025-03-01      0.17
2025-04-01     -1.51
2025-05-01     -1.01
2025-06-01     -1.68
2025-07-01      3.03
2025-08-01      0.22
2025-09-01      0.15
2025-10-01     -0.16
2025-11-01     -0.13
2025-12-01      0.98

2026-02-11 21:54:03,538 - INFO - 데이터 수집 완료 (테이블: DT_1K41002): 720 rows
2026-02-11 21:54:03,538 - INFO - 컬럼: ['C1_OBJ_NM', 'DT', 'C1', 'PRD_SE', 'UNIT_NM_ENG', 'ITM_ID', 'TBL_ID', 'ITM_NM', 'TBL_NM', 'PRD_DE', 'LST_CHN_DE', 'C1_NM_ENG', 'C1_NM', 'UNIT_NM', 'ITM_NM_ENG', 'ORG_ID', 'C1_OBJ_NM_ENG']
2026-02-11 21:54:03,541 - INFO - 데이터 전처리 시작 (타입: product)
2026-02-11 21:54:03,549 - INFO - 결측치 확인:
C1_OBJ_NM         0
DT                0
C1                0
PRD_SE            0
UNIT_NM_ENG       0
ITM_ID            0
TBL_ID            0
ITM_NM            0
TBL_NM            0
PRD_DE            0
LST_CHN_DE        0
C1_NM_ENG         0
C1_NM             0
UNIT_NM           0
ITM_NM_ENG        0
ORG_ID            0
C1_OBJ_NM_ENG     0
source_table      0
data_type         0
date              0
year              0
month             0
year_month        0
category_c1_nm    0
category_c1       0
sales_amount      0
unit              0
item_name         0
table_name        0
table_id          0
org_id            0
collected_at      0
dtype: int64
2026-02-11 21:54:03,555 - INFO -
=== product 요약 통계 ===
2026-02-11 21:54:03,563 - INFO -
=== product 판매액 피벗 테이블 ===
2026-02-11 21:54:03,578 - INFO - YoY 성장률 피벗 테이블 생성 완료: (24, 20)
2026-02-11 21:54:03,578 - INFO -
=== product YoY 성장률 피벗 테이블 ===
2026-02-11 21:54:03,591 - INFO - MoM 성장률 피벗 테이블 생성 완료: (35, 20)
2026-02-11 21:54:03,592 - INFO - === product 데이터 수집 완료 ===

2026-02-11 21:54:03,592 - INFO - === online 데이터 수집 시작 (테이블: DT_1KE10041) ===
2026-02-11 21:54:03,593 - INFO - KOSIS 데이터 요청 (테이블: DT_1KE10041, 최근 36개월)

  category  record_count   avg_sales  total_sales  min_sales  max_sales  std_sales first_date  last_date
        합계            36 53788545.11   1936387624   48625429   57687394 1987300.91 2023-01-01 2025-12-01
합계(승용차 제외)            36 48272009.64   1737792347   43423441   51436615 1708670.14 2023-01-01 2025-12-01
      비내구재            36 29855716.00   1074805776   26341190   32769820 1343425.02 2023-01-01 2025-12-01
      음식료품            36 15034936.03    541257697   12480241   17766442 1110545.40 2023-01-01 2025-12-01
       내구재            36 13425676.11    483324340   11590025   14858028  748771.77 2023-01-01 2025-12-01
      준내구재            36 10507153.00    378257508    8658700   12197737 1124360.67 2023-01-01 2025-12-01
        의복            36  5785716.64    208285799    4371774    7281203  852234.45 2023-01-01 2025-12-01
       승용차            36  5516535.47    198595277    4159036    6642089  614598.55 2023-01-01 2025-12-01
      차량연료            36  4903817.25    176537421    4335672    5369726  241302.24 2023-01-01 2025-12-01
    기타비내구재            36  3649786.39    131392310    3399855    4050780  151294.19 2023-01-01 2025-12-01
       화장품            36  2853579.44    102728860    2588789    3234820  175876.22 2023-01-01 2025-12-01
       의약품            36  2629570.33     94664532    2285066    3011931  182377.76 2023-01-01 2025-12-01
      가전제품            36  2547316.97     91703411    2177247    3144003  262897.80 2023-01-01 2025-12-01
통신기기 및 컴퓨터            36  2404938.56     86577788    2080026    3253751  289638.01 2023-01-01 2025-12-01
     기타내구재            36  2047496.75     73709883    1655120    2581340  189103.69 2023-01-01 2025-12-01
    기타준내구재            36  2022032.47     72793169    1652812    2186972  121747.60 2023-01-01 2025-12-01
오락 취미 경기용품            36  1351935.47     48669677    1057712    1652951  149013.75 2023-01-01 2025-12-01
   신발 및 가방            36  1347468.42     48508863    1180304    1496425   96935.03 2023-01-01 2025-12-01
        가구            36   909388.36     32737981     787377    1038644   56496.70 2023-01-01 2025-12-01
     서적 문구            36   784026.56     28224956     642322     979742   88105.66 2023-01-01 2025-12-01
category_c1_nm      가구     가전제품    기타내구재   기타비내구재   기타준내구재       내구재  \
date
2025-03-01      986460  2306086  2111153  3892854  1910183  13943881
2025-04-01      860271  2255199  2054315  3743599  2015680  13323881
2025-05-01      886293  2547072  2137705  3803542  2057399  13893551
2025-06-01      894921  2619934  2091809  3656558  2050019  13868877
2025-07-01      906506  2999675  2207303  3758851  2121076  14494944
2025-08-01      922954  2444481  2174267  3631435  1974990  13533047
2025-09-01      883333  2292488  2358720  3642346  2023056  14858028
2025-10-01      889334  2215871  2421151  3751827  2016830  13043147
2025-11-01      926352  2426721  2400860  3813202  1959028  14187960
2025-12-01      953363  2286894  2581340  4050780  2022452  14332119

category_c1_nm      비내구재   서적 문구      승용차  신발 및 가방  오락 취미 경기용품      음식료품  \
date
2025-03-01      30503689  965098  6092242  1469120     1324332  14892331
2025-04-01      29408291  737978  6062608  1410062     1372718  14537693
2025-05-01      30304660  685866  5977943  1450397     1421296  15328681
2025-06-01      29304425  642322  6098677  1358508     1251555  14742350
2025-07-01      30223688  779054  5760754  1288601     1281561  15219581
2025-08-01      30365403  756316  5706647  1271192     1241201  15489433
2025-09-01      31917235  754747  6642089  1316772     1322475  16888029
2025-10-01      30551888  678272  5260548  1453775     1508411  15763108
2025-11-01      30366828  743780  6070075  1424243     1395586  14865828
2025-12-01      31700192  943573  6250779  1461353     1356154  15340952

category_c1_nm       의복      의약품      준내구재     차량연료  통신기기 및 컴퓨터        합계  \
date
2025-03-01      6021757  2822651  10725392  4986384     2447940  55172962
2025-04-01      5719054  2778086  10517514  4782798     2091488  53249686
2025-05-01      6062167  2812363  10991259  4876736     2344538  55189470
2025-06-01      5570945  2702919  10231027  4755388     2163536  53404329
2025-07-01      5176199  2804264   9867437  5071863     2620706  54586069
2025-08-01      4687365  2770307   9174748  5052730     2284698  53073198
2025-09-01      5353793  2914761  10016096  4839564     2681398  56791359
2025-10-01      7136313  2893448  12115329  4785570     2256243  55710364
2025-11-01      7281203  2932279  12060060  5173545     2363952  56614848
2025-12-01      6815124  3011931  11655083  5335436     2259743  57687394

category_c1_nm  합계(승용차 제외)      화장품
date
2025-03-01        49080720  2944371
2025-04-01        47187078  2828137
2025-05-01        49211527  2797472
2025-06-01        47305652  2804888
2025-07-01        48825315  2590075
2025-08-01        47366551  2665182
2025-09-01        50149270  2877788
2025-10-01        50449816  2679663
2025-11-01        50544773  2838194
2025-12-01        51436615  3017520
category_c1_nm    가구   가전제품  기타내구재  기타비내구재  기타준내구재    내구재  비내구재  서적 문구    승용차  \
date
2025-01-01     -8.10 -13.47   2.79    3.82  -14.99  -8.80  7.79  -6.92  -0.95
2025-02-01      2.03  -4.81   8.52    4.41   -9.62  14.04 -4.64  -2.17  20.31
2025-03-01     -5.02  -3.77   1.79    4.61   -8.92   3.75  2.90  -1.49   8.93
2025-04-01     -5.28 -10.92   4.23    2.81   -2.62   4.01  1.98  -0.11  14.02
2025-05-01     -6.55  -7.51   1.83   -1.53   -3.99   4.36  0.18  -7.09  11.16
2025-06-01     -5.19  -7.49   5.18    3.49   -2.83   4.73  1.81  -6.67  12.99
2025-07-01     -0.11   3.07   3.63    4.66    1.47   6.34  3.48   2.71  12.42
2025-08-01     -0.18 -10.05  11.90    4.15    0.02   6.26 -1.06   2.44  13.58
2025-09-01      1.55  -1.62  18.35    5.43    3.37  12.17  1.61   5.69  21.74
2025-10-01     -6.97  -5.84  22.73    3.08   -4.56  -2.19  5.04  -6.33  -7.53
2025-11-01     -4.11  -5.79  24.38    5.94   -6.86   5.14  4.00  -1.35   5.44
2025-12-01     -1.82   0.54  17.44    6.66   -6.44   8.49  2.67   1.29  12.33

category_c1_nm  신발 및 가방  오락 취미 경기용품   음식료품    의복    의약품  준내구재  차량연료  \
date
2025-01-01         3.07        0.54  15.50  4.55  10.05 -0.25  3.92
2025-02-01        -4.76       -5.62 -12.88 -3.25  11.09 -5.07  4.59
2025-03-01         3.76       -1.92   2.33 -2.22  12.98 -2.69  0.35
2025-04-01        -1.50       -4.74   2.55 -6.23   9.65 -4.75 -2.15
2025-05-01        -3.08       -6.98   1.83  0.02   9.03 -2.11 -3.50
2025-06-01        -3.99       -6.49   2.59 -1.53   8.00 -2.75 -1.86
2025-07-01         0.69        2.41   4.42  2.84   7.46  2.20  2.69
2025-08-01         0.78        2.87  -1.93  6.02   1.76  3.51 -2.86
2025-09-01        -1.16       -2.32  -0.74  2.47  11.57  1.50  2.23
2025-10-01         0.88       -0.17   7.69  5.06   8.57  2.17  0.74
2025-11-01        -0.69       -3.56   1.64  2.03   9.84 -0.50  6.97
2025-12-01         5.39       -2.06   1.14  1.74   9.03  0.20  5.44

category_c1_nm  통신기기 및 컴퓨터    합계  합계(승용차 제외)    화장품
date
2025-01-01          -23.41  2.33        2.62 -16.95
2025-02-01           28.92 -0.21       -2.19   0.58
2025-03-01            4.72  1.97        1.17   0.73
2025-04-01            0.45  1.06       -0.39  -1.13
2025-05-01            9.86  0.72       -0.41  -5.62
2025-06-01            4.01  1.63        0.33  -1.36
2025-07-01            2.45  3.99        3.08  -5.24
2025-08-01            7.42  1.50        0.21  -3.01
2025-09-01            3.26  4.16        2.20  -0.10
2025-10-01           -4.56  2.64        3.83   0.37
2025-11-01            4.37  3.29        3.04   4.62
2025-12-01            2.61  3.53        2.56  -4.39

2026-02-11 21:54:04,328 - INFO - 데이터 수집 완료 (테이블: DT_1KE10041): 2808 rows
2026-02-11 21:54:04,329 - INFO - 컬럼: ['C1_OBJ_NM', 'C2_NM', 'DT', 'C2', 'C1', 'PRD_SE', 'UNIT_NM_ENG', 'ITM_ID', 'TBL_ID', 'ITM_NM', 'TBL_NM', 'PRD_DE', 'LST_CHN_DE', 'C1_NM_ENG', 'C1_NM', 'UNIT_NM', 'ITM_NM_ENG', 'C2_OBJ_NM_ENG', 'C2_NM_ENG', 'ORG_ID', 'C1_OBJ_NM_ENG', 'C2_OBJ_NM']
2026-02-11 21:54:04,333 - INFO - 데이터 전처리 시작 (타입: online)
2026-02-11 21:54:04,350 - INFO - 결측치 확인:
C1_OBJ_NM         0
C2_NM             0
DT                0
C2                0
C1                0
PRD_SE            0
UNIT_NM_ENG       0
ITM_ID            0
TBL_ID            0
ITM_NM            0
TBL_NM            0
PRD_DE            0
LST_CHN_DE        0
C1_NM_ENG         0
C1_NM             0
UNIT_NM           0
ITM_NM_ENG        0
C2_OBJ_NM_ENG     0
C2_NM_ENG         0
ORG_ID            0
C1_OBJ_NM_ENG     0
C2_OBJ_NM         0
source_table      0
data_type         0
date              0
year              0
month             0
year_month        0
category_c1_nm    0
category_c2_nm    0
category_c1       0
category_c2       0
sales_amount      0
unit              0
item_name         0
table_name        0
table_id          0
org_id            0
collected_at      0
dtype: int64
2026-02-11 21:54:04,355 - INFO -
=== online 요약 통계 ===
2026-02-11 21:54:04,363 - INFO -
=== online 판매액 피벗 테이블 ===
2026-02-11 21:54:04,384 - INFO - YoY 성장률 피벗 테이블 생성 완료: (32, 26)
2026-02-11 21:54:04,385 - INFO -
=== online YoY 성장률 피벗 테이블 ===
2026-02-11 21:54:04,400 - INFO - MoM 성장률 피벗 테이블 생성 완료: (36, 26)
2026-02-11 21:54:04,401 - INFO - === online 데이터 수집 완료 ===

   category  record_count   avg_sales  total_sales  min_sales  max_sales  std_sales first_date  last_date
         합계           108 14327378.65   1547356894    7266313   24290448 5328164.69 2023-01-01 2025-12-01
      음식서비스           108  2052768.11    221698956          0    3828145 1486377.63 2023-01-01 2025-12-01
      음·식료품           108  1899487.70    205144672     308023    3616725 1133701.06 2023-01-01 2025-12-01
 여행 및 교통서비스           108  1774250.13    191619014     122044    3051069 1149493.65 2023-01-01 2025-12-01
 가전·전자·통신기기           108  1240423.46    133965734     154612    2224553  714701.52 2023-01-01 2025-12-01
         의복           108  1221553.69    131927798     484114    2526798  520413.34 2023-01-01 2025-12-01
       생활용품           108  1043274.67    112673664      92001    1754207  675533.33 2023-01-01 2025-12-01
      가전·전자           108   892135.22     96350604      98244    1660920  539578.23 2023-01-01 2025-12-01
        화장품           108   715172.35     77238614     127911    1235649  397159.30 2023-01-01 2025-12-01
      농축수산물           108   708365.13     76503434      94319    1510472  444604.37 2023-01-01 2025-12-01
 컴퓨터 및 주변기기           108   477269.44     51545100     141545     898510  227418.43 2023-01-01 2025-12-01
     이쿠폰서비스           108   456807.65     49335226      26740    1007795  333374.65 2023-01-01 2025-12-01
       통신기기           108   348288.15     37615120      46189     926182  199945.23 2023-01-01 2025-12-01
자동차 및 자동차용품           108   336779.87     36372226     105206     970421  210103.76 2023-01-01 2025-12-01
   스포츠·레저용품           108   313266.87     33832822      23470     580788  201934.82 2023-01-01 2025-12-01
         가구           108   306549.26     33107320      26374     525473  195791.23 2023-01-01 2025-12-01
    아동·유아용품           108   297470.07     32126768      21502     543680  193668.21 2023-01-01 2025-12-01
패션용품 및 액세서리           108   227279.57     24546194      82037     415248  101106.55 2023-01-01 2025-12-01
         신발           108   210872.72     22774254      94709     391615   83269.98 2023-01-01 2025-12-01
 문화 및 레저서비스           108   175280.76     18930322       8418     373641  118461.50 2023-01-01 2025-12-01
         기타           108   171977.35     18573554      42398     337165   83420.21 2023-01-01 2025-12-01
       애완용품           108   154160.43     16649326      19886     260158   95133.67 2023-01-01 2025-12-01
         가방           108   150349.17     16237710      76541     280848   58043.27 2023-01-01 2025-12-01
         서적           108   141236.56     15253548      61486     281183   57464.47 2023-01-01 2025-12-01
      기타서비스           108   139796.33     15098004      51177     388224   78500.03 2023-01-01 2025-12-01
      사무·문구           108   112987.50     12202650      15753     239994   69757.33 2023-01-01 2025-12-01
category_c1_nm       가구      가방    가전·전자  가전·전자·통신기기      기타   기타서비스    농축수산물  \
date
2025-03-01      1013768  446430  2525420     3436116  494960  645262  2313354
2025-04-01       911092  415416  2521252     3423064  481110  531286  2257556
2025-05-01       879328  394848  2895668     3799856  499296  254064  2299690
2025-06-01       899944  380716  2984068     3713748  477912  259580  2213374
2025-07-01       894850  390430  3321840     4398184  454492  258048  2294756
2025-08-01       886484  382186  2638998     3725768  433930  254680  2316756
2025-09-01       903502  398086  2600830     4181200  462466  454974  3020944
2025-10-01       869496  382750  2540240     3810964  475558  290292  2272150
2025-11-01       958150  390018  2961954     4157592  529250  320730  2361638
2025-12-01       931898  409744  2674982     3780880  523706  324020  2512668

category_c1_nm  문화 및 레저서비스   사무·문구     생활용품  ...    음·식료품    음식서비스       의복  \
date                                         ...
2025-03-01          460988  393004  3331412  ...  6162348  6729800  3851918
2025-04-01          543526  362372  3249696  ...  6095676  6387054  3951648
2025-05-01          544186  311258  3328168  ...  6198446  6917614  3685508
2025-06-01          511812  296744  3374188  ...  6036326  6900290  3749616
2025-07-01          654406  321966  3508414  ...  6434688  7153110  3395620
2025-08-01          747282  308562  3346358  ...  6412638  7372746  2669812
2025-09-01          500398  365284  3457396  ...  7233450  6658184  3357848
2025-10-01          602254  332354  3251312  ...  6067240  7152898  4259514
2025-11-01          559456  407278  3406146  ...  6410558  7030952  5053596
2025-12-01          584974  479988  3392858  ...  6478184  7656290  4318182

category_c1_nm   이쿠폰서비스  자동차 및 자동차용품  컴퓨터 및 주변기기     통신기기  패션용품 및 액세서리  \
date
2025-03-01       973410      1045292     1616412   910696       701108
2025-04-01       891804       817664     1330236   901812       672114
2025-05-01      1026376      1381038     1255000   904188       702190
2025-06-01       916458      1519268     1187474   729680       691862
2025-07-01      1025162      1459902     1302962  1076344       739250
2025-08-01       951924      1564236     1288006  1086770       659900
2025-09-01      1046830      1940842     1470294  1580370       749220
2025-10-01      1112314      1111400     1262004  1270724       817222
2025-11-01      1124270      1475930     1614480  1195638       733158
2025-12-01      1293078      1392994     1574388  1105898       830496

category_c1_nm        합계      화장품
date
2025-03-01      44774764  2356752
2025-04-01      43499214  2312510
2025-05-01      44851920  2286870
2025-06-01      43973764  2291160
2025-07-01      46285468  2184490
2025-08-01      44684956  2286652
2025-09-01      47458350  2282848
2025-10-01      45719570  2232832
2025-11-01      48210924  2393890
2025-12-01      48580896  2471298

[10 rows x 26 columns]
category_c1_nm     가구     가방  가전·전자  가전·전자·통신기기     기타  기타서비스  농축수산물  \
date
2025-01-01       6.85  -5.75  -1.08      -20.30 -15.95  20.36  19.50
2025-02-01       2.70   3.74  -2.50       17.94 -11.73  23.86   1.90
2025-03-01       3.66   8.62 -15.56      -14.64  -5.27  -9.61   9.90
2025-04-01      -4.21  -4.31   1.97        0.50  -3.07 -28.62   1.97
2025-05-01      -4.88  -1.93  21.67       14.97  19.98 -49.99 -17.95
2025-06-01     -12.55 -13.08  20.11      -16.64   5.79 -43.87   3.34
2025-07-01     -14.74 -12.88  34.20       37.54  -7.75 -43.03  -1.76
2025-08-01      -5.51  -8.39   3.54       18.97  -7.86 -40.69   1.06
2025-09-01       5.61   0.55  -8.55       23.20  -3.86  73.55  26.02
2025-10-01      -1.54   0.14 -15.37       12.02   3.06  11.96   0.73
2025-11-01       8.47   0.04 -10.57       -6.09  14.31  25.08   2.78
2025-12-01       6.97   7.49  -0.89       -5.52  18.76  24.56   8.58

category_c1_nm  문화 및 레저서비스  사무·문구  생활용품  ...  음·식료품  음식서비스     의복  이쿠폰서비스  \
date                                     ...
2025-01-01            2.16   0.04  0.27  ...   3.28 -27.16   6.18    6.29
2025-02-01            0.40   2.37 -6.49  ...  -5.68 -34.49 -28.30    1.73
2025-03-01           -4.42   5.64  1.39  ...   2.85 -27.02 -21.63  -10.25
2025-04-01           17.97 -15.56 -3.60  ...   2.09 -39.33 -13.21  -26.71
2025-05-01            5.55  -1.13  9.65  ...  -7.31   1.01  16.76   -7.37
2025-06-01            2.39 -16.30  8.38  ...   5.54  11.86  22.80   -4.42
2025-07-01           31.09 -13.47  2.85  ...   2.35   6.29 -11.88    6.23
2025-08-01           26.80 -13.37  1.02  ...   4.24  15.43 -31.97   15.26
2025-09-01           -4.41  17.77  4.65  ...  19.47  -3.75 -10.24   -2.20
2025-10-01            5.02   9.72 -4.04  ...  -0.73   3.66  14.45    8.90
2025-11-01          -14.02  16.02 -0.27  ...   2.36  -1.71  47.82   -3.52
2025-12-01           -7.23  45.43  4.23  ...   2.94   3.85  60.79   20.25

category_c1_nm  자동차 및 자동차용품  컴퓨터 및 주변기기    통신기기  패션용품 및 액세서리    합계    화장품
date
2025-01-01           -26.93       32.13  -39.52         5.13  4.24  11.55
2025-02-01             8.24       52.22   47.90         8.76 -2.63  10.37
2025-03-01            -4.35       15.60  -10.86         1.22 -0.98   6.61
2025-04-01            -0.95       -4.25   -2.43       -20.18 -5.01  -7.41
2025-05-01           143.29      -18.94   -1.09         8.01  2.59   0.48
2025-06-01            57.33      -31.77  -57.62        -2.74  4.43   8.12
2025-07-01            32.33      -18.68   45.84         6.34  3.65 -10.09
2025-08-01            75.68       -4.86   61.61        -1.30  3.18   4.55
2025-09-01            31.07       20.21  115.63         6.51  5.77   0.38
2025-10-01           -19.50        7.10  118.15        15.43  4.06  -7.04
2025-11-01             0.78       20.06    7.78        -1.20  4.16  11.17
2025-12-01            -4.84       24.98   -6.12        25.29  8.63   4.99

[12 rows x 26 columns]

2026-02-11 21:54:09,983 - INFO - Excel 파일 저장 완료: C:\Users\82108\OneDrive\바탕 화면\investment\data\analysis_results\KOSIS\retail_sales\kosis_retail_sales_20260211.xlsx
2026-02-11 21:54:09,984 - INFO - === KOSIS 소매판매 전체 데이터 수집 완료 ===

=== 판매채널별 YoY 성장률 (최근 6개월) ===
category_c1_nm   대형마트    면세점  무점포 소매   백화점  슈퍼마켓 및 잡화점  승용차 및 연료 소매점  전문소매점  \
date
2025-07-01       0.17 -19.86    6.55  1.10       -0.27          7.49   4.61
2025-08-01     -10.66 -16.13    4.30  3.26       -5.70          5.33   3.77
2025-09-01      -7.31 -10.60   14.84  3.49       -8.15         12.60   0.42
2025-10-01      10.08  -5.66    1.30  8.20        4.30         -3.64   5.79
2025-11-01      -4.91  -1.74    3.87  6.29       -1.09          6.52   3.87
2025-12-01      -5.59 -11.00    4.82  3.14       -2.87          9.06   4.33

category_c1_nm   편의점
date
2025-07-01      3.03
2025-08-01      0.22
2025-09-01      0.15
2025-10-01     -0.16
2025-11-01     -0.13
2025-12-01      0.98

=== 제화별 YoY 성장률 (최근 6개월) ===
category_c1_nm    가구   가전제품  기타내구재  기타비내구재  기타준내구재    내구재  비내구재  서적 문구    승용차  \
date
2025-07-01     -0.11   3.07   3.63    4.66    1.47   6.34  3.48   2.71  12.42
2025-08-01     -0.18 -10.05  11.90    4.15    0.02   6.26 -1.06   2.44  13.58
2025-09-01      1.55  -1.62  18.35    5.43    3.37  12.17  1.61   5.69  21.74
2025-10-01     -6.97  -5.84  22.73    3.08   -4.56  -2.19  5.04  -6.33  -7.53
2025-11-01     -4.11  -5.79  24.38    5.94   -6.86   5.14  4.00  -1.35   5.44
2025-12-01     -1.82   0.54  17.44    6.66   -6.44   8.49  2.67   1.29  12.33

category_c1_nm  신발 및 가방  오락 취미 경기용품  음식료품    의복    의약품  준내구재  차량연료  \
date
2025-07-01         0.69        2.41  4.42  2.84   7.46  2.20  2.69
2025-08-01         0.78        2.87 -1.93  6.02   1.76  3.51 -2.86
2025-09-01        -1.16       -2.32 -0.74  2.47  11.57  1.50  2.23
2025-10-01         0.88       -0.17  7.69  5.06   8.57  2.17  0.74
2025-11-01        -0.69       -3.56  1.64  2.03   9.84 -0.50  6.97
2025-12-01         5.39       -2.06  1.14  1.74   9.03  0.20  5.44

category_c1_nm  통신기기 및 컴퓨터    합계  합계(승용차 제외)   화장품
date
2025-07-01            2.45  3.99        3.08 -5.24
2025-08-01            7.42  1.50        0.21 -3.01
2025-09-01            3.26  4.16        2.20 -0.10
2025-10-01           -4.56  2.64        3.83  0.37
2025-11-01            4.37  3.29        3.04  4.62
2025-12-01            2.61  3.53        2.56 -4.39

=== 온라인 판매 YoY 성장률 (최근 6개월) ===
category_c1_nm     가구     가방  가전·전자  가전·전자·통신기기     기타  기타서비스  농축수산물  \
date
2025-07-01     -14.74 -12.88  34.20       37.54  -7.75 -43.03  -1.76
2025-08-01      -5.51  -8.39   3.54       18.97  -7.86 -40.69   1.06
2025-09-01       5.61   0.55  -8.55       23.20  -3.86  73.55  26.02
2025-10-01      -1.54   0.14 -15.37       12.02   3.06  11.96   0.73
2025-11-01       8.47   0.04 -10.57       -6.09  14.31  25.08   2.78
2025-12-01       6.97   7.49  -0.89       -5.52  18.76  24.56   8.58

category_c1_nm  문화 및 레저서비스  사무·문구  생활용품  ...  음·식료품  음식서비스     의복  이쿠폰서비스  \
date                                     ...
2025-07-01           31.09 -13.47  2.85  ...   2.35   6.29 -11.88    6.23
2025-08-01           26.80 -13.37  1.02  ...   4.24  15.43 -31.97   15.26
2025-09-01           -4.41  17.77  4.65  ...  19.47  -3.75 -10.24   -2.20
2025-10-01            5.02   9.72 -4.04  ...  -0.73   3.66  14.45    8.90
2025-11-01          -14.02  16.02 -0.27  ...   2.36  -1.71  47.82   -3.52
2025-12-01           -7.23  45.43  4.23  ...   2.94   3.85  60.79   20.25

category_c1_nm  자동차 및 자동차용품  컴퓨터 및 주변기기    통신기기  패션용품 및 액세서리    합계    화장품
date
2025-07-01            32.33      -18.68   45.84         6.34  3.65 -10.09
2025-08-01            75.68       -4.86   61.61        -1.30  3.18   4.55
2025-09-01            31.07       20.21  115.63         6.51  5.77   0.38
2025-10-01           -19.50        7.10  118.15        15.43  4.06  -7.04
2025-11-01             0.78       20.06    7.78        -1.20  4.16  11.17
2025-12-01            -4.84       24.98   -6.12        25.29  8.63   4.99

[6 rows x 26 columns]

파일 저장 위치: C:\Users\82108\OneDrive\바탕 화면\investment\data\analysis_results\KOSIS\retail_sales
파일명 형식: kosis_retail_sales_YYYYMMDD.xlsx