# US Revenue Forecast v2 — 단계별 테스트 노트북

**소스 테이블** : `US_IS_from_FMP`  
**저장 테이블** : `us_revenue_forecast_data`  
**예측 모델**  : SARIMA · ETS · Prophet · LSTM · Theta + Ensemble (SARIMA+ETS+Theta 평균)

---

| 셀 번호 | 단계 |
|---------|------|
| Cell 1  | 환경 설정 & 경로 자동 감지 |
| Cell 2  | 모듈 Import |
| Cell 3  | 파라미터 설정 |
| Cell 4  | DB 연결 테스트 |
| Cell 5  | 재무 데이터 추출 함수 정의 |
| Cell 6  | 단일 티커 데이터 추출 테스트 |
| Cell 7  | 예측 함수 정의 |
| Cell 8  | 단일 티커 예측 테스트 |
| Cell 9  | Long-format 변환 함수 정의 |
| Cell 10 | Long-format 변환 테스트 |
| Cell 11 | DB 테이블 생성 & 저장 함수 정의 |
| Cell 12 | 단일 티커 저장 테스트 |
| Cell 13 | 배치 실행 (전체 / 특정 티커 / 구간 지정) |
| Cell 14 | 저장 결과 조회 |

---
### ⚡ 메모리 전략
> **티커 1개씩 즉시 저장** 방식을 채택합니다.  
> 배치(20개 누적 후 저장)는 리스트가 메모리에 쌓여 오히려 OOM 위험이 높습니다.  
> 1개 예측 → 즉시 저장 → `clear_memory()` 호출 순서로 메모리를 최소 상태로 유지합니다.

### 🔢 구간 예측 (2000개 티커 단계적 처리)
> Cell 13 의 `TICKER_START` / `TICKER_END` 변수로 처리 구간을 지정하세요.  
> 예: 0~499 → 500~999 → ... 순서로 끊어서 실행하면 메모리 부담 없이 전체 예측 가능합니다.

## Cell 1 · 환경 설정 & 경로 자동 감지

노트북(Hoyoung_Park) / 데스크탑(82108) 어느 환경에서 실행해도  
`DATA` 폴더를 자동으로 찾아 `sys.path`에 추가합니다.

In [1]:
import sys, os, warnings
from pathlib import Path
warnings.filterwarnings("ignore")

# ── 후보 프로젝트 루트 (노트북 / 데스크탑) ───────────────────────
_CANDIDATE_ROOTS = [
    r"C:\Users\Hoyoung_Park\PyCharmMiscProject\stock_forecast",          # 노트북
    r"C:\Users\82108\OneDrive\바탕 화면\investment\investment_strategy",   # 데스크탑
]

def _setup_path() -> str:
    """
    프로젝트 루트(DATA/ 폴더의 부모)를 탐색해 sys.path 에 추가합니다.
    탐색 순서:
      1) __file__ 또는 cwd 기준 상위 경로 중 DATA/ 를 포함하는 첫 번째 경로
      2) _CANDIDATE_ROOTS 에서 실존하는 첫 번째 경로
    """
    try:
        start = Path(__file__).resolve().parent
    except NameError:          # 노트북 환경 — __file__ 없음
        start = Path.cwd()

    # 현재 경로부터 상위로 올라가며 DATA/ 탐색
    for p in [start] + list(start.parents):
        if (p / "DATA").is_dir():
            root = str(p)
            if root not in sys.path:
                sys.path.insert(0, root)
            print(f"[PATH] root 자동 감지 : {root}")
            return root

    # cwd 탐색에서 못 찾으면 후보 경로 시도
    for candidate in _CANDIDATE_ROOTS:
        if os.path.isdir(candidate) and os.path.isdir(os.path.join(candidate, "DATA")):
            if candidate not in sys.path:
                sys.path.insert(0, candidate)
            print(f"[PATH] root 후보 경로 : {candidate}")
            return candidate

    raise EnvironmentError(
        "DATA 폴더를 찾을 수 없습니다.\n"
        "_CANDIDATE_ROOTS 목록을 현재 환경에 맞게 수정하거나 "
        "노트북을 프로젝트 루트 아래에서 실행하세요."
    )

_ROOT = _setup_path()
print(f"[확인] 프로젝트 루트  : {_ROOT}")
print(f"[확인] DATA 경로     : {os.path.join(_ROOT, 'DATA')}")
print(f"[확인] sys.path[0]   : {sys.path[0]}")

[PATH] root 자동 감지 : C:\Users\82108\OneDrive\바탕 화면\investment\investment_strategy
[확인] 프로젝트 루트  : C:\Users\82108\OneDrive\바탕 화면\investment\investment_strategy
[확인] DATA 경로     : C:\Users\82108\OneDrive\바탕 화면\investment\investment_strategy\DATA
[확인] sys.path[0]   : C:\Users\82108\OneDrive\바탕 화면\investment\investment_strategy\US_Market\analysis\미국전기업_매출_예측

## Cell 2 · 모듈 Import

`DATA` 폴더 내 세 모듈과 외부 라이브러리를 불러옵니다.

In [2]:
# ── 내부 모듈 (DATA 폴더) ─────────────────────────────────────
from DATA.config import get_db_info, get_engine
from DATA.us_target_ticker_list_2000 import ticker_list as DEFAULT_TICKER_LIST
from DATA.universal_ts_forecast_function_v2 import (
    forecast_sarima,
    forecast_ets,
    forecast_prophet,
    forecast_lstm,
    forecast_theta,
    infer_freq_alias,
    seasonal_periods_from_freq,
    clear_memory,
)

# ── 외부 라이브러리 ───────────────────────────────────────────
import gc
import traceback
from typing import Optional, List      # Python 3.9 호환 타입 힌트
import numpy as np
import pandas as pd
from datetime import datetime
from sqlalchemy import text
from IPython.display import display

# ── 로그 유틸 (config 에 log 가 없는 경우 자체 정의) ──────────
try:
    from DATA.config import log
except ImportError:
    def log(tag: str, msg: str):
        ts = datetime.now().strftime("%H:%M:%S")
        print(f"[{ts}][{tag}] {msg}")

print(f"[OK] 모든 모듈 Import 완료")
print(f"[OK] DEFAULT_TICKER_LIST 길이: {len(DEFAULT_TICKER_LIST):,}개")

[OK] 모든 모듈 Import 완료
[OK] DEFAULT_TICKER_LIST 길이: 2,000개

## Cell 3 · 파라미터 설정

항목·기간·모델·배치 등 전역 파라미터를 여기서만 수정합니다.

In [3]:
# ════════════════════════════════════════════════════════════
#  ★ 파라미터 — 필요에 따라 이 셀만 수정하세요 ★
# ════════════════════════════════════════════════════════════

# ── 테이블 ────────────────────────────────────────────────
# ── FMP API ──────────────────────────────────────────────
FMP_API_KEY    = "hT0gAk87j9xZx4PlBApvBqfVL5IahvgV"
FMP_BASE_URL   = "https://financialmodelingprep.com/api/v3"
FMP_MAX_RETRY  = 3
FMP_SLEEP_SEC  = 0.35

# ── 데이터 소스 선택 ──────────────────────────────────────
# "db"  : DB(US_IS_from_FMP) 에서 조회  — 빠름, DB 최신화 필요
# "fmp" : FMP API 에서 직접 조회        — 항상 최신, API 호출 비용
DATA_SOURCE    = "fmp"   # "db" 또는 "fmp"

SRC_TABLE  = "US_IS_from_FMP"           # 원본 재무 테이블
DEST_TABLE = "us_revenue_forecast_data" # 예측 결과 저장 테이블

# ── 재무 항목 ─────────────────────────────────────────────
# 예: "sale" (매출) / "opi" (영업이익) / "ni" (순이익) / "ebitda" 등
ITEM       = "sale"

# ── 예측 설정 ─────────────────────────────────────────────
HORIZON    = 8    # 예측 분기 수 (default 8 = 2년)
MIN_OBS    = 28   # 최소 관측 분기 수 (28 = 7년 × 4분기)

# ── 모델 선택 ─────────────────────────────────────────────
ALL_MODELS      = ["SARIMA", "ETS", "Prophet", "LSTM", "Theta"]
ENSEMBLE_MODELS = ["SARIMA", "ETS", "Theta"]   # 앙상블 구성 모델

# ── 예측 실행일 ───────────────────────────────────────────
FORECAST_DATE = datetime.now().strftime("%Y-%m-%d")

# ════════════════════════════════════════════════════════════
print("[파라미터 확인]")
print(f"  DATA_SOURCE  = {DATA_SOURCE}")
print(f"  SRC_TABLE    = {SRC_TABLE}")
print(f"  DEST_TABLE   = {DEST_TABLE}")
print(f"  ITEM         = {ITEM}")
print(f"  HORIZON      = {HORIZON}분기")
print(f"  MIN_OBS      = {MIN_OBS}개")
print(f"  ALL_MODELS   = {ALL_MODELS}")
print(f"  ENSEMBLE     = {ENSEMBLE_MODELS}")
print(f"  FORECAST_DATE= {FORECAST_DATE}")

[파라미터 확인]
  DATA_SOURCE  = fmp
  SRC_TABLE    = US_IS_from_FMP
  DEST_TABLE   = us_revenue_forecast_data
  ITEM         = sale
  HORIZON      = 8분기
  MIN_OBS      = 28개
  ALL_MODELS   = ['SARIMA', 'ETS', 'Prophet', 'LSTM', 'Theta']
  ENSEMBLE     = ['SARIMA', 'ETS', 'Theta']
  FORECAST_DATE= 2026-04-03

## Cell 4 · DB 연결 테스트

In [4]:
db_info = get_db_info()
engine  = get_engine(db_info)

try:
    with engine.connect() as conn:
        conn.execute(text("SELECT 1"))
    print("[OK] DB 연결 성공")
    print(f"     host={db_info.get('host')}  port={db_info.get('port')}  db={db_info.get('database')}")
except Exception as e:
    print(f"[FAIL] DB 연결 실패: {e}")

[OK] DB 연결 성공
     host=192.168.0.230  port=3307  db=investar

## Cell 5 · 재무 데이터 추출 함수 정의

`US_IS_from_FMP` → ticker + item 기준 분기 시계열 추출  

**처리 흐름**
1. ticker / item 기준으로 value, date, period, date_month 추출  
2. 날짜 파싱 및 오름차순 정렬  
3. 월별 중복 제거 (같은 월 → 마지막 행, 단독 행은 보존)  
4. 분기 단위 재집계 (같은 분기 → 마지막 행, 분기말 날짜로 통일)  
5. MIN_OBS 미달 시 ValueError

In [5]:
import time as _time
import requests as _requests


def _fmp_fetch_income(
    ticker: str,
    limit: int = 40,
    period: str = "quarter",
) -> pd.DataFrame:
    """
    FMP API 에서 손익계산서를 직접 조회합니다.
    반환: columns [date, report_date, period, date_month, value]
    """
    url = f"{FMP_BASE_URL}/income-statement/{ticker}"
    params = {"period": period, "limit": limit, "apikey": FMP_API_KEY}

    for k in range(FMP_MAX_RETRY):
        try:
            r = _requests.get(url, params=params, timeout=30)
            if r.status_code == 429:
                _time.sleep(1.5 + k)
                continue
            r.raise_for_status()
            data = r.json()
            if isinstance(data, dict) and "Error Message" in data:
                raise ValueError(data["Error Message"])
            break
        except Exception as e:
            if k == FMP_MAX_RETRY - 1:
                raise RuntimeError(f"FMP 조회 실패 ({ticker}): {e}")
            _time.sleep(FMP_SLEEP_SEC + k * 0.5)

    if not data or not isinstance(data, list):
        return pd.DataFrame()

    df = pd.DataFrame(data)
    if df.empty or "revenue" not in df.columns:
        return pd.DataFrame()

    # FMP 컬럼 → 내부 표준 컬럼으로 변환
    df["date"]        = pd.to_datetime(df["date"],         errors="coerce")
    df["report_date"] = pd.to_datetime(df.get("fillingDate", df.get("acceptedDate", pd.NaT)), errors="coerce")
    df["period"]      = df.get("period", pd.NA)
    # date_month: date 컬럼의 월 첫날 (FMP date = 분기말이므로 그대로 사용)
    df["date_month"]  = df["date"].dt.to_period("M").dt.to_timestamp()
    df["value"]       = pd.to_numeric(df["revenue"], errors="coerce")

    df = (
        df[["date", "report_date", "period", "date_month", "value"]]
        .dropna(subset=["date", "value"])
        .sort_values("date")
        .reset_index(drop=True)
    )
    return df


def _clean_series(df: pd.DataFrame, ticker: str, item: str) -> pd.DataFrame:
    """
    추출된 원시 DataFrame 을 정제합니다.
    - date 기준 중복 제거 (같은 분기말이 여러 번 → 마지막 유지)
    - 분기 연속성 확인 (3개월 간격)
    - 음수 매출 검사
    - 최소 관측치 검사
    """
    df = df.copy()
    df["value"] = pd.to_numeric(df["value"], errors="coerce")
    df = df.dropna(subset=["date", "value"]).sort_values("date").reset_index(drop=True)

    # ── FMP date 는 정확한 분기말이므로 그대로 사용 ──────────
    # 단, 같은 date 가 중복으로 들어온 경우 마지막 행 유지
    df = (
        df.groupby("date", sort=True)
          .last()
          .reset_index()
    )

    return df


def fetch_financial_series(
    engine,
    ticker: str,
    item: str    = "sale",
    min_obs: int = 28,
) -> pd.DataFrame:
    """
    DATA_SOURCE 설정에 따라 DB 또는 FMP API 에서 분기 매출 시계열을 추출합니다.

    DATA_SOURCE = 'fmp' : FMP API 직접 조회 (항상 최신)
    DATA_SOURCE = 'db'  : DB(US_IS_from_FMP) 조회 (빠름)

    반환: columns [date, report_date, period, date_month, value]
    """
    if DATA_SOURCE == "fmp":
        df = _fmp_fetch_income(ticker, limit=max(min_obs + 10, 40))
        if df.empty:
            raise ValueError(f"[{ticker}] FMP에서 '{item}' 데이터 없음")
        _time.sleep(FMP_SLEEP_SEC)  # API 호출 간격
    else:
        # ── DB 조회 (기존 로직) ────────────────────────────
        query = text("""
            SELECT date, report_date, period, date_month, value
            FROM   US_IS_from_FMP
            WHERE  ticker = :ticker
              AND  item   = :item
              AND  value  IS NOT NULL
            ORDER  BY date
        """)
        with engine.connect() as conn:
            df = pd.read_sql(query, conn, params={"ticker": ticker, "item": item})

        if df.empty:
            raise ValueError(f"[{ticker}] DB에서 '{item}' 데이터 없음")

        df["date"]        = pd.to_datetime(df["date"],        errors="coerce")
        df["report_date"] = pd.to_datetime(df["report_date"], errors="coerce")
        df["date_month"]  = pd.to_datetime(df["date_month"],  errors="coerce")
        df["value"]       = pd.to_numeric(df["value"],        errors="coerce")
        df = df.dropna(subset=["date", "value"]).sort_values("date").reset_index(drop=True)

        # DB 중복 제거 (date_month 기준)
        df_no_dm  = df[df["date_month"].isna()].copy()
        df_has_dm = df[df["date_month"].notna()].copy()
        if not df_has_dm.empty:
            df_has_dm["_dm_ym"] = df_has_dm["date_month"].dt.to_period("M")
            df_has_dm = (
                df_has_dm.sort_values("date")
                .groupby("_dm_ym", sort=True).first()
                .reset_index().drop(columns=["_dm_ym"])
            )
        df = (
            pd.concat([df_no_dm, df_has_dm], ignore_index=True)
            .sort_values("date").reset_index(drop=True)
        )

        # DB: report_date 기준 회계분기 재계산
        def _fiscal_qend(row):
            if pd.notna(row["report_date"]):
                return (row["report_date"] - pd.Timedelta(days=45)).to_period("Q").to_timestamp("Q")
            if pd.notna(row["date_month"]):
                return row["date_month"].to_period("Q").to_timestamp("Q")
            return row["date"].to_period("Q").to_timestamp("Q")
        df["date"] = df.apply(_fiscal_qend, axis=1)
        df = df.groupby("date", sort=True).last().reset_index()

    # ── 공통 정제 ─────────────────────────────────────────────
    df = _clean_series(df, ticker, item)

    # ── 음수 매출 검사 ────────────────────────────────────────
    if (df["value"] < 0).any():
        neg_dates = df.loc[df["value"] < 0, "date"].dt.date.tolist()
        raise ValueError(
            f"[{ticker}] '{item}' 음수 매출 존재 → 예측 제외 "
            f"(음수 분기: {neg_dates})"
        )

    # ── 최소 관측치 검사 ──────────────────────────────────────
    if len(df) < min_obs:
        raise ValueError(
            f"[{ticker}] '{item}' 관측치 부족: {len(df)}개 < 최소 {min_obs}개"
        )

    return df


print("[OK] fetch_financial_series 재정의 완료")
print(f"     DATA_SOURCE = '{DATA_SOURCE}'")
if DATA_SOURCE == 'fmp':
    print("     → FMP API 직접 조회 (항상 최신 분기 수신)")
else:
    print("     → DB 조회 (report_date 기준 회계분기 보정 적용)")

[OK] fetch_financial_series 재정의 완료
     DATA_SOURCE = 'fmp'
     → FMP API 직접 조회 (항상 최신 분기 수신)

In [6]:
# ── Cell 6-진단 : DB 원본 데이터 vs 추출 결과 비교 ──────────
# 최신 분기 누락 여부를 확인하는 진단 셀
from sqlalchemy import text as _text

DIAG_TICKER = "NVDA"   # ← 확인할 티커

print(f"[진단] {DIAG_TICKER} — DB 원본 vs fetch 결과 비교")
print("=" * 60)

# DB 원본 (최근 5행)
with engine.connect() as conn:
    raw = pd.read_sql(
        _text("""
            SELECT date, report_date, period, date_month, value
            FROM   US_IS_from_FMP
            WHERE  ticker = :ticker AND item = :item
              AND  value IS NOT NULL
            ORDER  BY date DESC
            LIMIT  6
        """),
        conn,
        params={"ticker": DIAG_TICKER, "item": ITEM}
    )

print("[DB 원본] 최근 6행 (date 내림차순):")
display(raw)

# fetch_financial_series 결과 (최근 5행)
try:
    diag_df = fetch_financial_series(engine, DIAG_TICKER, item=ITEM, min_obs=MIN_OBS)
    print(f"\n[fetch 결과] 최근 5행 (총 {len(diag_df)}분기):")
    display(diag_df.tail(5))
    print(f"\n  → 마지막 분기 date : {diag_df['date'].iloc[-1].date()}")
    print(f"  → 기대값           : 2025-12-31 (NVDA 2025Q4)")
    ok = diag_df['date'].iloc[-1].date().isoformat() == '2026-03-31'
    print(f"  → {'✅ 정상' if ok else '❌ 여전히 누락 — 추가 확인 필요'}")
except Exception as e:
    print(f"[오류] {e}")

[진단] NVDA — DB 원본 vs fetch 결과 비교
============================================================
[DB 원본] 최근 6행 (date 내림차순):

        date report_date period date_month         value
0 2026-01-31  2025-10-26     Q3    2025-10  5.700600e+10
1 2026-01-31  2025-10-26     Q3    2025-10  5.700600e+10
2 2025-12-31  2025-10-26     Q3    2025-10  5.700600e+10
3 2025-12-31  2025-10-26     Q3    2025-10  5.700600e+10
4 2025-11-30  2025-10-26     Q3    2025-10  5.700600e+10
5 2025-11-30  2025-10-26     Q3    2025-10  5.700600e+10

[fetch 결과] 최근 5행 (총 40분기):

         date report_date period date_month        value
35 2025-01-26  2025-02-26     Q4 2025-01-01  39331000000
36 2025-04-27  2025-05-28     Q1 2025-04-01  44062000000
37 2025-07-27  2025-08-27     Q2 2025-07-01  46743000000
38 2025-10-26  2025-11-19     Q3 2025-10-01  57006000000
39 2026-01-25  2026-02-25     Q4 2026-01-01  68127000000

  → 마지막 분기 date : 2026-01-25
  → 기대값           : 2025-12-31 (NVDA 2025Q4)
  → ❌ 여전히 누락 — 추가 확인 필요

## Cell 6 · 단일 티커 데이터 추출 테스트

`TEST_TICKER` 를 원하는 티커로 변경해서 테스트하세요.

In [8]:
TEST_TICKER = "NvDA"   # ← 테스트할 티커

try:
    src_df = fetch_financial_series(
        engine, TEST_TICKER, item=ITEM, min_obs=MIN_OBS
    )
    print(f"[OK] {TEST_TICKER} '{ITEM}' 추출 성공: {len(src_df)}분기")
    print(f"     기간: {src_df['date'].iloc[0].date()} ~ {src_df['date'].iloc[-1].date()}")
    display(src_df.tail(8))
except Exception as e:
    print(f"[FAIL] {e}")

[OK] NvDA 'sale' 추출 성공: 40분기
     기간: 2016-05-01 ~ 2026-01-25

         date report_date period date_month        value
32 2024-04-28  2024-05-29     Q1 2024-04-01  26044000000
33 2024-07-28  2024-08-28     Q2 2024-07-01  30040000000
34 2024-10-27  2024-11-20     Q3 2024-10-01  35082000000
35 2025-01-26  2025-02-26     Q4 2025-01-01  39331000000
36 2025-04-27  2025-05-28     Q1 2025-04-01  44062000000
37 2025-07-27  2025-08-27     Q2 2025-07-01  46743000000
38 2025-10-26  2025-11-19     Q3 2025-10-01  57006000000
39 2026-01-25  2026-02-25     Q4 2026-01-01  68127000000

## Cell 7 · 예측 함수 정의

- `make_forecast_index` : 마지막 실제값 다음 분기부터 HORIZON 개 날짜 생성  
- `forecast_one_ticker` : 5개 모델 순차 실행, 메모리 추적 포함

In [9]:
def make_forecast_index(
    last_date: pd.Timestamp,
    horizon: int,
    freq: str = "QE",
) -> pd.DatetimeIndex:
    """
    last_date 다음 분기부터 horizon 개의 날짜 인덱스를 생성합니다.
    freq : infer_freq_alias() 가 반환하는 값 (Q, QE, QS 등)
    """
    _freq = freq if freq else "QE"
    try:
        idx = pd.date_range(
            start   = last_date + pd.tseries.frequencies.to_offset(_freq),
            periods = horizon,
            freq    = _freq,
        )
    except Exception:
        # fallback: 3개월 간격으로 직접 생성
        idx = pd.date_range(
            start   = last_date + pd.DateOffset(months=3),
            periods = horizon,
            freq    = "QE",
        )
    return idx


def forecast_one_ticker(
    y: pd.Series,
    ticker: str,
    horizon: int,
    models: list,
) -> dict:
    """
    단일 티커의 시계열 y 에 대해 지정 모델들로 예측을 수행합니다.

    실제 함수 시그니처 (universal_ts_forecast_function_v2.py 기준):
      forecast_sarima  : (y, forecast_horizon, seasonal_period=int)
      forecast_ets     : (y, forecast_horizon, m=int)
      forecast_prophet : (y, forecast_horizon, m=int)
      forecast_lstm    : (y, forecast_horizon)           ← m 파라미터 없음
      forecast_theta   : (y, forecast_horizon, m=int)

    Parameters
    ----------
    y       : DatetimeIndex 를 가진 분기 시계열 (Series)
    ticker  : 종목 코드 (로그 출력용)
    horizon : 예측 분기 수
    models  : 사용할 모델 목록  ["SARIMA", "ETS", "Prophet", "LSTM", "Theta"]

    Returns
    -------
    dict  {model_name: {"forecast": array, "spec": dict} or {"error": str}}
    """
    import psutil, os
    proc = psutil.Process(os.getpid())

    def _mem_mb():
        return proc.memory_info().rss / 1024 / 1024

    freq    = infer_freq_alias(y.index)
    sp      = seasonal_periods_from_freq(freq)   # 분기=4, 월=12
    results = {}

    # ── 각 함수의 실제 파라미터명에 맞춰 호출 ─────────────────────
    def _call(model_name):
        if model_name == "SARIMA":
            # forecast_sarima(y, forecast_horizon, seasonal_period=)
            return forecast_sarima(y, horizon, seasonal_period=sp)
        elif model_name == "ETS":
            # forecast_ets(y, forecast_horizon, m=)
            return forecast_ets(y, horizon, m=sp)
        elif model_name == "Prophet":
            # forecast_prophet(y, forecast_horizon, m=)
            return forecast_prophet(y, horizon, m=sp)
        elif model_name == "LSTM":
            # forecast_lstm(y, forecast_horizon)  ← m 파라미터 없음
            return forecast_lstm(y, horizon)
        elif model_name == "Theta":
            # forecast_theta(y, forecast_horizon, m=)
            return forecast_theta(y, horizon, m=sp)
        else:
            raise ValueError(f"알 수 없는 모델: {model_name}")

    for model_name in models:
        log(ticker, f"  [{model_name}] 시작  (메모리: {_mem_mb():.1f} MB)")
        try:
            res = _call(model_name)
            results[model_name] = res
            fc_arr = np.asarray(res.get("forecast", []))
            if len(fc_arr) > 0:
                log(ticker, f"  [{model_name}] 완료  첫값={fc_arr[0]:.2e} (메모리: {_mem_mb():.1f} MB)")
            else:
                log(ticker, f"  [{model_name}] 오류응답: {res}")
        except Exception as e:
            log(ticker, f"  [{model_name}] 오류: {e}")
            results[model_name] = {"error": str(e)}
        finally:
            gc.collect()

    return results

print("[OK] make_forecast_index / forecast_one_ticker 함수 정의 완료")
print("  SARIMA  : forecast_sarima(y, forecast_horizon, seasonal_period=sp)")
print("  ETS     : forecast_ets(y, forecast_horizon, m=sp)")
print("  Prophet : forecast_prophet(y, forecast_horizon, m=sp)")
print("  LSTM    : forecast_lstm(y, forecast_horizon)")
print("  Theta   : forecast_theta(y, forecast_horizon, m=sp)")

[OK] make_forecast_index / forecast_one_ticker 함수 정의 완료
  SARIMA  : forecast_sarima(y, forecast_horizon, seasonal_period=sp)
  ETS     : forecast_ets(y, forecast_horizon, m=sp)
  Prophet : forecast_prophet(y, forecast_horizon, m=sp)
  LSTM    : forecast_lstm(y, forecast_horizon)
  Theta   : forecast_theta(y, forecast_horizon, m=sp)

## Cell 8 · 단일 티커 예측 테스트

Cell 6 에서 추출한 `src_df` 를 사용합니다.  
모델별 예측값과 SARIMA 파라미터를 확인하세요.

In [10]:
# Cell 6 에서 src_df 가 정상 추출된 경우에만 실행
y = src_df.set_index("date")["value"].copy()
y.index = pd.DatetimeIndex(y.index)
y.name  = ITEM

print(f"예측 입력 시계열: {len(y)}분기  ({y.index[0].date()} ~ {y.index[-1].date()})")

# 테스트용 모델 — 빠른 확인이 필요하면 ['SARIMA', 'ETS', 'Theta'] 로 축소 가능
TEST_MODELS = ALL_MODELS

forecast_results = forecast_one_ticker(y, TEST_TICKER, HORIZON, TEST_MODELS)
freq             = infer_freq_alias(y.index)
forecast_index   = make_forecast_index(y.index[-1], HORIZON, freq)

print("\n[예측 결과 요약]")
for model_name, res in forecast_results.items():
    if "error" in res:
        print(f"  {model_name:<10}: 오류 → {res['error']}")
    else:
        fc  = np.asarray(res["forecast"])
        msg = f"  {model_name:<10}: {fc.round(0).tolist()}"
        if model_name == "SARIMA" and "spec" in res:
            spec = res["spec"]
            aic  = spec.get("ic_value", "")
            aic_str = f"  AIC={aic:.2f}" if isinstance(aic, float) else ""
            msg += f"  | order={spec.get('order')} seasonal={spec.get('seasonal_order')}{aic_str}"
        print(msg)

예측 입력 시계열: 40분기  (2016-05-01 ~ 2026-01-25)
[NvDA]   [SARIMA] 시작  (메모리: 434.9 MB)
[메모리] forecast_sarima 실행 전: 434.90 MB
[메모리] find_best_sarima_params 실행 전: 434.92 MB
[메모리] find_best_sarima_params 실행 후: 439.50 MB (변화: +4.58 MB)
[메모리] forecast_sarima 실행 후: 439.60 MB (변화: +4.70 MB)
[NvDA]   [SARIMA] 완료  첫값=7.70e+10 (메모리: 439.6 MB)
[NvDA]   [ETS] 시작  (메모리: 439.7 MB)
[메모리] forecast_ets 실행 전: 439.67 MB
[메모리] forecast_ets 실행 후: 439.88 MB (변화: +0.21 MB)
[NvDA]   [ETS] 완료  첫값=7.31e+10 (메모리: 439.9 MB)
[NvDA]   [Prophet] 시작  (메모리: 439.9 MB)
[메모리] forecast_prophet 실행 전: 439.88 MB

23:16:37 - cmdstanpy - INFO - Chain [1] start processing
23:16:37 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 442.05 MB (변화: +2.18 MB)
[NvDA]   [Prophet] 완료  첫값=3.55e+10 (메모리: 442.1 MB)
[NvDA]   [LSTM] 시작  (메모리: 442.1 MB)
[메모리] forecast_lstm 실행 전: 442.05 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1444.05 MB (변화: +1002.00 MB)
[경고] 메모리 사용량이 크게 증가했습니다. 메모리 정리를 권장합니다.
[NvDA]   [LSTM] 완료  첫값=1.02e+11 (메모리: 1444.0 MB)
[NvDA]   [Theta] 시작  (메모리: 1444.0 MB)
[메모리] forecast_theta 실행 전: 1444.05 MB
[메모리] forecast_theta 실행 후: 1444.20 MB (변화: +0.16 MB)
[NvDA]   [Theta] 완료  첫값=6.93e+10 (메모리: 1444.2 MB)

[예측 결과 요약]
  SARIMA    : [77009581499.0, 86489752720.0, 97189212251.0, 109271288604.0, 122922037308.0, 138353518625.0, 155807564246.0, 175560108316.0]  | order=(1, 0, 1) seasonal=(0, 0, 0, 4)  AIC=-34.23
  ETS       : [73111737442.0, 83601980656.0, 97071432606.0, 101894892870.0, 109350370170.0, 125040217228.0, 145185950434.0, 152400211561.0]
  Prophet   : [35502090084.0, 35856982357.0, 36249898801.0, 36630140521.0, 37023056966.0, 37403298686.0, 37796215130.0, 38189131575.0]
  LSTM      : [102177193984.0, 142308802560.0, 202571857920.0, 307686113280.0, 527764422656.0, 1053215424512.0, 2335740788736.0, 5244441329664.0]
  Theta     : [69341559945.0, 76382794054.0, 83989946306.0, 81799816419.0, 83242897674.0, 91729929200.0, 100901715379.0, 98218894477.0]

## Cell 9 · Long-format 변환 함수 정의

actual + forecast(각 모델) + Ensemble → 하나의 long-format DataFrame

**저장 컬럼**

| 컬럼 | 설명 |
|------|------|
| ticker | 종목 코드 |
| item | 재무 항목 |
| date | 기준일(분기말) |
| period | 회계 분기(Q1~Q4/FY) — actual 행만 |
| date_month | 해당 분기 기간 — actual 행만 |
| data_type | `actual` / `forecast` |
| model | actual / SARIMA / ETS / Prophet / LSTM / Theta / Ensemble |
| value | 수치값 |
| forecast_date | 예측 실행일 |
| sarima_order | SARIMA (p,d,q) — SARIMA 행만 |
| sarima_seasonal_order | SARIMA (P,D,Q,m) — SARIMA 행만 |
| sarima_ic_value | SARIMA 최적 AIC — SARIMA 행만 |
| created_at | 레코드 생성 시각 |

In [11]:
def build_long_df(
    ticker: str,
    item: str,
    src_df: pd.DataFrame,
    forecast_results: dict,
    forecast_index: pd.DatetimeIndex,
    forecast_date: str,
    ensemble_models: list = None,
) -> pd.DataFrame:
    """
    실제값(actual) + 예측값(각 모델) + 앙상블 → long-format DataFrame.

    Parameters
    ----------
    ticker           : 종목 코드
    item             : 재무 항목
    src_df           : fetch_financial_series() 반환 DataFrame
    forecast_results : forecast_one_ticker() 반환 dict
    forecast_index   : 예측 날짜 DatetimeIndex
    forecast_date    : 예측 실행일 (str)
    ensemble_models  : 앙상블 구성 모델 목록 (None → ENSEMBLE_MODELS 전역 변수 사용)
    """
    if ensemble_models is None:
        ensemble_models = ENSEMBLE_MODELS

    now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    rows    = []

    # ── actual 행 ────────────────────────────────────────────
    for _, row in src_df.iterrows():
        rows.append({
            "ticker"                : ticker,
            "item"                  : item,
            "date"                  : row["date"].strftime("%Y-%m-%d"),
            "period"                : row.get("period"),
            "date_month"            : (
                row["date_month"].strftime("%Y-%m-%d")
                if pd.notna(row.get("date_month")) else None
            ),
            "data_type"             : "actual",
            "model"                 : "actual",
            "value"                 : round(float(row["value"]), 6),
            "forecast_date"         : forecast_date,
            "sarima_order"          : None,
            "sarima_seasonal_order" : None,
            "sarima_ic_value"       : None,
            "created_at"            : now_str,
        })

    # ── forecast 행 ──────────────────────────────────────────
    ensemble_bucket = {}   # { date_str : [val, ...] }

    for model_name, res in forecast_results.items():
        if "error" in res or "forecast" not in res:
            continue

        fc_arr = np.asarray(res["forecast"])
        spec   = res.get("spec", {})

        sarima_order    = None
        sarima_seasonal = None
        sarima_ic       = None
        if model_name == "SARIMA":
            sarima_order    = str(spec.get("order",          ""))
            sarima_seasonal = str(spec.get("seasonal_order", ""))
            raw_ic = spec.get("ic_value")
            if raw_ic is not None:
                try:
                    v = float(raw_ic)
                    sarima_ic = round(v, 4) if np.isfinite(v) else None
                except (TypeError, ValueError):
                    pass

        for i, dt in enumerate(forecast_index):
            if i >= len(fc_arr):
                break
            val    = float(fc_arr[i])
            dt_str = dt.strftime("%Y-%m-%d")

            rows.append({
                "ticker"                : ticker,
                "item"                  : item,
                "date"                  : dt_str,
                "period"                : None,
                "date_month"            : None,
                "data_type"             : "forecast",
                "model"                 : model_name,
                "value"                 : round(val, 6),
                "forecast_date"         : forecast_date,
                "sarima_order"          : sarima_order,
                "sarima_seasonal_order" : sarima_seasonal,
                "sarima_ic_value"       : sarima_ic,
                "created_at"            : now_str,
            })

            if model_name in ensemble_models:
                ensemble_bucket.setdefault(dt_str, []).append(val)

    # ── Ensemble 행 (SARIMA + ETS + Theta 평균) ─────────────
    for dt_str, vals in ensemble_bucket.items():
        rows.append({
            "ticker"                : ticker,
            "item"                  : item,
            "date"                  : dt_str,
            "period"                : None,
            "date_month"            : None,
            "data_type"             : "forecast",
            "model"                 : "Ensemble",
            "value"                 : round(float(np.mean(vals)), 6),
            "forecast_date"         : forecast_date,
            "sarima_order"          : None,
            "sarima_seasonal_order" : None,
            "sarima_ic_value"       : None,
            "created_at"            : now_str,
        })

    return pd.DataFrame(rows)

print("[OK] build_long_df 함수 정의 완료")

[OK] build_long_df 함수 정의 완료

## Cell 10 · Long-format 변환 테스트

In [12]:
long_df = build_long_df(
    ticker           = TEST_TICKER,
    item             = ITEM,
    src_df           = src_df,
    forecast_results = forecast_results,
    forecast_index   = forecast_index,
    forecast_date    = FORECAST_DATE,
)

print(f"[OK] long_df 생성: {len(long_df)}행")
print("\n모델별 행 수:")
display(long_df.groupby(["data_type", "model"]).size().reset_index(name="rows"))
print("\n샘플 (forecast 상위 5행):")
display(long_df[long_df["data_type"] == "forecast"].head())

[OK] long_df 생성: 88행

모델별 행 수:

  data_type     model  rows
0    actual    actual    40
1  forecast       ETS     8
2  forecast  Ensemble     8
3  forecast      LSTM     8
4  forecast   Prophet     8
5  forecast    SARIMA     8
6  forecast     Theta     8

샘플 (forecast 상위 5행):

,ticker,item,date,period,date_month,data_type,model,value,forecast_date,sarima_order,sarima_seasonal_order,sarima_ic_value,created_at
40,NvDA,sale,2026-03-31,None,None,forecast,SARIMA,7.700958e+10,2026-04-03,"(1, 0, 1)","(0, 0, 0, 4)",-34.2293,2026-04-03 23:16:45
41,NvDA,sale,2026-06-30,None,None,forecast,SARIMA,8.648975e+10,2026-04-03,"(1, 0, 1)","(0, 0, 0, 4)",-34.2293,2026-04-03 23:16:45
42,NvDA,sale,2026-09-30,None,None,forecast,SARIMA,9.718921e+10,2026-04-03,"(1, 0, 1)","(0, 0, 0, 4)",-34.2293,2026-04-03 23:16:45
43,NvDA,sale,2026-12-31,None,None,forecast,SARIMA,1.092713e+11,2026-04-03,"(1, 0, 1)","(0, 0, 0, 4)",-34.2293,2026-04-03 23:16:45
44,NvDA,sale,2027-03-31,None,None,forecast,SARIMA,1.229220e+11,2026-04-03,"(1, 0, 1)","(0, 0, 0, 4)",-34.2293,2026-04-03 23:16:45

## Cell 11 · DB 테이블 생성 & 저장 함수 정의

**중복 판정 기준** : `(ticker, item, date, model, forecast_date)`  
→ 이미 존재하는 행은 건드리지 않고, 신규 행만 INSERT

In [13]:
# ── 테이블 CREATE (최초 1회) ──────────────────────────────────
CREATE_TABLE_SQL = f"""
CREATE TABLE IF NOT EXISTS `{DEST_TABLE}` (
    id                    BIGINT       NOT NULL AUTO_INCREMENT,
    ticker                VARCHAR(20)  NOT NULL,
    item                  VARCHAR(30)  NOT NULL,
    date                  DATE         NOT NULL,
    period                VARCHAR(10)  DEFAULT NULL,
    date_month            DATE         DEFAULT NULL,
    data_type             VARCHAR(10)  NOT NULL COMMENT 'actual / forecast',
    model                 VARCHAR(20)  NOT NULL,
    value                 DOUBLE       DEFAULT NULL,
    forecast_date         DATE         NOT NULL,
    sarima_order          VARCHAR(30)  DEFAULT NULL,
    sarima_seasonal_order VARCHAR(30)  DEFAULT NULL,
    sarima_ic_value       DOUBLE       DEFAULT NULL,
    created_at            DATETIME     DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_main (ticker, item, date, model, forecast_date),
    INDEX idx_ticker      (ticker),
    INDEX idx_forecast_dt (forecast_date),
    INDEX idx_model       (model)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
"""

def ensure_table(engine):
    """저장 테이블이 없으면 생성합니다."""
    with engine.begin() as conn:
        conn.execute(text(CREATE_TABLE_SQL))
    print(f"[OK] 테이블 '{DEST_TABLE}' 준비 완료")


def save_to_db(engine, long_df: pd.DataFrame, dest_table: str = DEST_TABLE) -> int:
    """
    long_df 를 DB 에 저장합니다.
    - 중복 기준: (ticker, item, date, model, forecast_date)
    - 기존 행 유지 + 신규 행만 INSERT

    Returns
    -------
    int  : 실제 삽입된 신규 행 수
    """
    if long_df is None or long_df.empty:
        return 0

    # ── 1. 기존 키 조회 ────────────────────────────────────
    ticker      = long_df["ticker"].iloc[0]
    item        = long_df["item"].iloc[0]
    fc_date_val = long_df["forecast_date"].iloc[0]

    check_sql = text(f"""
        SELECT CONCAT(ticker,'|',item,'|',date,'|',model,'|',forecast_date) AS uq_key
        FROM   `{dest_table}`
        WHERE  ticker        = :ticker
          AND  item          = :item
          AND  forecast_date = :fc_date
    """)

    with engine.connect() as conn:
        existing = pd.read_sql(
            check_sql, conn,
            params={"ticker": ticker, "item": item, "fc_date": fc_date_val}
        )
    existing_keys = set(existing["uq_key"].tolist()) if not existing.empty else set()

    # ── 2. 신규 행 필터링 ──────────────────────────────────
    new_df = long_df[
        ~long_df.apply(
            lambda r: f"{r['ticker']}|{r['item']}|{r['date']}|{r['model']}|{r['forecast_date']}"
            in existing_keys,
            axis=1,
        )
    ].copy()

    if new_df.empty:
        log(ticker, f"  [DB] 신규 행 없음 — 스킵")
        return 0

    # ── 3. INSERT ─────────────────────────────────────────
    new_df.to_sql(
        name       = dest_table,
        con        = engine,
        if_exists  = "append",
        index      = False,
        chunksize  = 500,
        method     = "multi",
    )
    log(ticker, f"  [DB] {len(new_df)}행 저장 완료")
    return len(new_df)

print("[OK] ensure_table / save_to_db 함수 정의 완료")

[OK] ensure_table / save_to_db 함수 정의 완료

## Cell 12 · 단일 티커 저장 테스트

In [14]:
# 테이블 생성 (최초 1회)
ensure_table(engine)

# Cell 10 의 long_df 저장
inserted = save_to_db(engine, long_df)
print(f"[OK] {TEST_TICKER} 저장 완료 — 삽입: {inserted}행")

# 저장 확인
with engine.connect() as conn:
    chk = pd.read_sql(
        text(f"""
            SELECT model, data_type, COUNT(*) AS cnt
            FROM   `{DEST_TABLE}`
            WHERE  ticker = :tk AND forecast_date = :fd
            GROUP  BY model, data_type
            ORDER  BY model
        """),
        conn,
        params={"tk": TEST_TICKER, "fd": FORECAST_DATE},
    )
display(chk)

[OK] 테이블 'us_revenue_forecast_data' 준비 완료
[NvDA]   [DB] 신규 행 없음 — 스킵
[OK] NvDA 저장 완료 — 삽입: 0행

      model data_type  cnt
0    actual    actual   40
1  Ensemble  forecast    8
2       ETS  forecast    8
3      LSTM  forecast    8
4   Prophet  forecast    8
5    SARIMA  forecast    8
6     Theta  forecast    8

## Cell 13 · 배치 실행 (전체 / 특정 티커 / 구간 지정)

### 실행 모드 선택

| 변수 | 설명 |
|------|------|
| `RUN_TICKERS` | `None` → DEFAULT_TICKER_LIST 전체 / `["AAPL", ...]` → 특정 티커만 |
| `TICKER_START` | 리스트 슬라이싱 시작 인덱스 (0부터, `None` = 처음) |
| `TICKER_END`   | 리스트 슬라이싱 끝 인덱스 (None = 끝까지) |
| `RUN_MODELS`   | 사용할 모델 목록 |

### 구간 예시
```python
TICKER_START, TICKER_END = 0,   500   # 1~500번째 티커
TICKER_START, TICKER_END = 500, 1000  # 501~1000번째 티커
TICKER_START, TICKER_END = None, None # 전체
```

### 메모리 전략
> 티커 1개 예측 → 즉시 DB 저장 → `clear_memory()` 호출  
> 이 방식이 배치(20개 누적) 방식보다 피크 메모리가 낮고 중단 시 손실도 최소화됩니다.

In [16]:
# ════════════════════════════════════════════════════════════
#  배치 설정 — 여기를 수정하세요
# ════════════════════════════════════════════════════════════

# ── 특정 티커 지정 (None 이면 아래 구간/전체 사용) ────────────
# Optional[list] = Python 3.9 호환 (3.10+ 의 list | None 대신 사용)
RUN_TICKERS = None          # type: Optional[list]
# RUN_TICKERS = ["AAPL", "MSFT", "NVDA"]   # 특정 티커만

# ── 전체 리스트 구간 지정 (RUN_TICKERS=None 일 때 적용) ──────
TICKER_START = 1000           # type: Optional[int]  # 시작 인덱스 (0부터)
TICKER_END   = 1500          # type: Optional[int]  # 끝 인덱스 (exclusive, None=끝까지)
# 예: 0~499   → START=0,   END=500
# 예: 500~999 → START=500, END=1000
# 예: 전체    → START=None, END=None

# ── 모델 / 항목 / 예측 기간 ───────────────────────────────────
RUN_MODELS  = ALL_MODELS   # 또는 ["SARIMA", "ETS", "Theta"]  (빠른 실행)
RUN_ITEM    = ITEM
RUN_HORIZON = HORIZON
RUN_MIN_OBS = MIN_OBS

# ════════════════════════════════════════════════════════════
#  실행 대상 티커 목록 결정
# ════════════════════════════════════════════════════════════
if RUN_TICKERS is not None:
    tickers = RUN_TICKERS
    print(f"[모드] 특정 티커 지정: {tickers}")
else:
    tickers = DEFAULT_TICKER_LIST[TICKER_START:TICKER_END]
    _s = TICKER_START if TICKER_START is not None else 0
    _e = TICKER_END   if TICKER_END   is not None else len(DEFAULT_TICKER_LIST)
    print(f"[모드] 구간 실행: index {_s} ~ {_e-1}  ({len(tickers)}개)")

total = len(tickers)

# ════════════════════════════════════════════════════════════
#  배치 실행
# ════════════════════════════════════════════════════════════
ensure_table(engine)

success, skipped, errored, neg_skipped = 0, 0, 0, 0
skip_list, error_list, neg_skip_list   = [], [], []

log("BATCH", "=" * 70)
log("BATCH", f"시작  | 티커 {total}개 | 항목: {RUN_ITEM} | 예측기간: {RUN_HORIZON}분기")
log("BATCH", f"모델  : {RUN_MODELS}")
log("BATCH", f"예측일: {FORECAST_DATE} | min_obs: {RUN_MIN_OBS}")
log("BATCH", "=" * 70)

for i, ticker in enumerate(tickers, 1):
    pct = i / total * 100
    log("PROGRESS", f"[{i:>4}/{total}] ({pct:5.1f}%)  >>  {ticker}")

    # ── STEP 1 : 데이터 추출 ──────────────────────────────
    try:
        _src_df = fetch_financial_series(
            engine, ticker, RUN_ITEM, RUN_MIN_OBS
        )
    except ValueError as e:
        err_msg = str(e)
        if "음수 매출" in err_msg:
            # 음수 매출 → 예측 제외 (별도 카운트)
            log(ticker, f"[NEG-SKIP] {err_msg}")
            neg_skipped += 1
            neg_skip_list.append(ticker)
        else:
            log(ticker, f"[SKIP] {err_msg}")
            skipped += 1
            skip_list.append(ticker)
        continue
    except Exception as e:
        log(ticker, f"[SKIP] {e}")
        skipped += 1
        skip_list.append(ticker)
        continue

    _y = _src_df.set_index("date")["value"].copy()
    _y.index = pd.DatetimeIndex(_y.index)
    _y.name  = RUN_ITEM
    log(ticker, f"  {len(_y)}분기 | {_y.index[0].date()} ~ {_y.index[-1].date()}")

    # ── STEP 2 : 예측 ─────────────────────────────────────
    try:
        _fc_results = forecast_one_ticker(_y, ticker, RUN_HORIZON, RUN_MODELS)
    except Exception as e:
        log(ticker, f"[ERROR] 예측: {e}")
        traceback.print_exc()
        errored += 1
        error_list.append(ticker)
        del _src_df, _y
        clear_memory()
        continue

    # ── STEP 3 : 예측 인덱스 생성 ────────────────────────
    _freq     = infer_freq_alias(_y.index)
    _fc_index = make_forecast_index(_y.index[-1], RUN_HORIZON, _freq)

    # ── STEP 4 : Long-format 변환 ─────────────────────────
    try:
        _ldf = build_long_df(
            ticker           = ticker,
            item             = RUN_ITEM,
            src_df           = _src_df,
            forecast_results = _fc_results,
            forecast_index   = _fc_index,
            forecast_date    = FORECAST_DATE,
        )
    except Exception as e:
        log(ticker, f"[ERROR] Long-format 변환: {e}")
        errored += 1
        error_list.append(ticker)
        del _src_df, _y, _fc_results
        clear_memory()
        continue

    # ── STEP 5 : DB 저장 (1개씩 즉시 저장 — 메모리 최소화) ─
    try:
        save_to_db(engine, _ldf)
        success += 1
    except Exception as e:
        log(ticker, f"[ERROR] DB 저장: {e}")
        errored += 1
        error_list.append(ticker)

    # ── STEP 6 : 메모리 해제 ─────────────────────────────
    del _src_df, _y, _fc_results, _ldf
    clear_memory()

# ── 요약 ──────────────────────────────────────────────────
log("BATCH", "=" * 70)
log("BATCH", f"완료 | 성공: {success}  데이터스킵: {skipped}  음수제외: {neg_skipped}  오류: {errored}  합계: {total}")
if skip_list:     log("BATCH", f"데이터스킵  : {skip_list}")
if neg_skip_list: log("BATCH", f"음수매출제외 : {neg_skip_list}")
if error_list:    log("BATCH", f"오류 티커   : {error_list}")
log("BATCH", "=" * 70)

[메모리] forecast_lstm 실행 후: 1640.53 MB (변화: +0.97 MB)
[MUX]   [LSTM] 완료  첫값=5.12e+07 (메모리: 1640.5 MB)
[MUX]   [Theta] 시작  (메모리: 1640.5 MB)
[메모리] forecast_theta 실행 전: 1640.53 MB
[메모리] forecast_theta 실행 후: 1640.53 MB (변화: +0.00 MB)
[MUX]   [Theta] 완료  첫값=5.96e+07 (메모리: 1640.5 MB)
[MUX]   [DB] 88행 저장 완료
[PROGRESS] [ 389/500] ( 77.8%)  >>  GOGL
[GOGL]   40분기 | 2015-06-30 ~ 2025-03-31
[GOGL]   [SARIMA] 시작  (메모리: 1640.5 MB)
[메모리] forecast_sarima 실행 전: 1640.53 MB
[메모리] find_best_sarima_params 실행 전: 1640.53 MB
[메모리] find_best_sarima_params 실행 후: 1640.53 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1640.53 MB (변화: +0.00 MB)
[GOGL]   [SARIMA] 완료  첫값=1.51e+08 (메모리: 1640.5 MB)
[GOGL]   [ETS] 시작  (메모리: 1640.5 MB)
[메모리] forecast_ets 실행 전: 1640.53 MB
[메모리] forecast_ets 실행 후: 1640.53 MB (변화: +0.00 MB)
[GOGL]   [ETS] 완료  첫값=1.56e+08 (메모리: 1640.5 MB)
[GOGL]   [Prophet] 시작  (메모리: 1640.5 MB)

01:05:22 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1640.53 MB

01:05:22 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1640.55 MB (변화: +0.02 MB)
[GOGL]   [Prophet] 완료  첫값=2.93e+08 (메모리: 1640.5 MB)
[GOGL]   [LSTM] 시작  (메모리: 1640.5 MB)
[메모리] forecast_lstm 실행 전: 1640.55 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1640.52 MB (변화: -0.03 MB)
[GOGL]   [LSTM] 완료  첫값=2.25e+08 (메모리: 1640.5 MB)
[GOGL]   [Theta] 시작  (메모리: 1640.5 MB)
[메모리] forecast_theta 실행 전: 1640.52 MB
[메모리] forecast_theta 실행 후: 1640.52 MB (변화: +0.00 MB)
[GOGL]   [Theta] 완료  첫값=1.53e+08 (메모리: 1640.5 MB)
[GOGL]   [DB] 88행 저장 완료
[PROGRESS] [ 390/500] ( 78.0%)  >>  BLBD
[BLBD]   40분기 | 2016-04-02 ~ 2025-12-27
[BLBD]   [SARIMA] 시작  (메모리: 1640.5 MB)
[메모리] forecast_sarima 실행 전: 1640.52 MB
[메모리] find_best_sarima_params 실행 전: 1640.52 MB
[메모리] find_best_sarima_params 실행 후: 1640.52 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1640.52 MB (변화: +0.00 MB)
[BLBD]   [SARIMA] 완료  첫값=4.19e+08 (메모리: 1640.5 MB)
[BLBD]   [ETS] 시작  (메모리: 1640.5 MB)
[메모리] forecast_ets 실행 전: 1640.52 MB
[메모리] forecast_ets 실행 후: 1640.52 MB (변화: +0.00 MB)
[BLBD]   [ETS] 완료  첫값=4.00e+08 (메모리: 1640.5 MB)
[BLBD]   [Prophet] 시작  (메모리: 1640.5 MB)

01:05:38 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1640.52 MB

01:05:38 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1640.55 MB (변화: +0.03 MB)
[BLBD]   [Prophet] 완료  첫값=3.18e+08 (메모리: 1640.6 MB)
[BLBD]   [LSTM] 시작  (메모리: 1640.6 MB)
[메모리] forecast_lstm 실행 전: 1640.55 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1640.52 MB (변화: -0.03 MB)
[BLBD]   [LSTM] 완료  첫값=3.57e+08 (메모리: 1640.5 MB)
[BLBD]   [Theta] 시작  (메모리: 1640.5 MB)
[메모리] forecast_theta 실행 전: 1640.52 MB
[메모리] forecast_theta 실행 후: 1640.52 MB (변화: +0.00 MB)
[BLBD]   [Theta] 완료  첫값=3.96e+08 (메모리: 1640.5 MB)
[BLBD]   [DB] 88행 저장 완료
[PROGRESS] [ 391/500] ( 78.2%)  >>  LZB
[LZB]   40분기 | 2016-04-30 ~ 2026-01-24
[LZB]   [SARIMA] 시작  (메모리: 1640.5 MB)
[메모리] forecast_sarima 실행 전: 1640.52 MB
[메모리] find_best_sarima_params 실행 전: 1640.52 MB
[메모리] find_best_sarima_params 실행 후: 1640.52 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1640.52 MB (변화: +0.00 MB)
[LZB]   [SARIMA] 완료  첫값=5.44e+08 (메모리: 1640.5 MB)
[LZB]   [ETS] 시작  (메모리: 1640.5 MB)
[메모리] forecast_ets 실행 전: 1640.52 MB
[메모리] forecast_ets 실행 후: 1640.53 MB (변화: +0.00 MB)
[LZB]   [ETS] 완료  첫값=5.56e+08 (메모리: 1640.5 MB)
[LZB]   [Prophet] 시작  (메모리: 1640.5 MB)
[메모리] forecast_prophet 실행 전: 1640.53 MB

01:05:54 - cmdstanpy - INFO - Chain [1] start processing
01:05:54 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1640.53 MB (변화: +0.00 MB)
[LZB]   [Prophet] 완료  첫값=5.77e+08 (메모리: 1640.5 MB)
[LZB]   [LSTM] 시작  (메모리: 1640.5 MB)
[메모리] forecast_lstm 실행 전: 1640.53 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1640.49 MB (변화: -0.04 MB)
[LZB]   [LSTM] 완료  첫값=5.74e+08 (메모리: 1640.5 MB)
[LZB]   [Theta] 시작  (메모리: 1640.5 MB)
[메모리] forecast_theta 실행 전: 1640.49 MB
[메모리] forecast_theta 실행 후: 1640.49 MB (변화: +0.00 MB)
[LZB]   [Theta] 완료  첫값=5.53e+08 (메모리: 1640.5 MB)
[LZB]   [DB] 88행 저장 완료
[PROGRESS] [ 392/500] ( 78.4%)  >>  ALGT
[ALGT]   40분기 | 2016-03-31 ~ 2025-12-31
[ALGT]   [SARIMA] 시작  (메모리: 1640.5 MB)
[메모리] forecast_sarima 실행 전: 1640.49 MB
[메모리] find_best_sarima_params 실행 전: 1640.49 MB
[메모리] find_best_sarima_params 실행 후: 1640.49 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1640.49 MB (변화: +0.00 MB)
[ALGT]   [SARIMA] 완료  첫값=6.56e+08 (메모리: 1640.5 MB)
[ALGT]   [ETS] 시작  (메모리: 1640.5 MB)
[메모리] forecast_ets 실행 전: 1640.49 MB
[메모리] forecast_ets 실행 후: 1640.49 MB (변화: +0.00 MB)
[ALGT]   [ETS] 완료  첫값=6.94e+08 (메모리: 1640.5 MB)
[ALGT]   [Prophet] 시작  (메모리: 1640.5 MB)

01:06:09 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1640.49 MB

01:06:09 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1640.51 MB (변화: +0.02 MB)
[ALGT]   [Prophet] 완료  첫값=6.63e+08 (메모리: 1640.5 MB)
[ALGT]   [LSTM] 시작  (메모리: 1640.5 MB)
[메모리] forecast_lstm 실행 전: 1640.51 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1640.50 MB (변화: -0.01 MB)
[ALGT]   [LSTM] 완료  첫값=6.29e+08 (메모리: 1640.5 MB)
[ALGT]   [Theta] 시작  (메모리: 1640.5 MB)
[메모리] forecast_theta 실행 전: 1640.50 MB
[메모리] forecast_theta 실행 후: 1640.50 MB (변화: +0.00 MB)
[ALGT]   [Theta] 완료  첫값=6.51e+08 (메모리: 1640.5 MB)
[ALGT]   [DB] 88행 저장 완료
[PROGRESS] [ 393/500] ( 78.6%)  >>  GBX
[GBX]   40분기 | 2016-02-29 ~ 2025-11-30
[GBX]   [SARIMA] 시작  (메모리: 1640.5 MB)
[메모리] forecast_sarima 실행 전: 1640.50 MB
[메모리] find_best_sarima_params 실행 전: 1640.50 MB
[메모리] find_best_sarima_params 실행 후: 1640.50 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1640.50 MB (변화: +0.00 MB)
[GBX]   [SARIMA] 완료  첫값=7.06e+08 (메모리: 1640.5 MB)
[GBX]   [ETS] 시작  (메모리: 1640.5 MB)
[메모리] forecast_ets 실행 전: 1640.50 MB
[메모리] forecast_ets 실행 후: 1640.51 MB (변화: +0.00 MB)
[GBX]   [ETS] 완료  첫값=7.23e+08 (메모리: 1640.5 MB)
[GBX]   [Prophet] 시작  (메모리: 1640.5 MB)

01:06:25 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1640.51 MB

01:06:25 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1640.51 MB (변화: +0.00 MB)
[GBX]   [Prophet] 완료  첫값=8.82e+08 (메모리: 1640.5 MB)
[GBX]   [LSTM] 시작  (메모리: 1640.5 MB)
[메모리] forecast_lstm 실행 전: 1640.51 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1640.49 MB (변화: -0.02 MB)
[GBX]   [LSTM] 완료  첫값=8.47e+08 (메모리: 1640.5 MB)
[GBX]   [Theta] 시작  (메모리: 1640.5 MB)
[메모리] forecast_theta 실행 전: 1640.49 MB
[메모리] forecast_theta 실행 후: 1640.49 MB (변화: +0.00 MB)
[GBX]   [Theta] 완료  첫값=7.18e+08 (메모리: 1640.5 MB)
[GBX]   [DB] 88행 저장 완료
[PROGRESS] [ 394/500] ( 78.8%)  >>  INFN
[INFN]   40분기 | 2015-03-28 ~ 2024-12-28
[INFN]   [SARIMA] 시작  (메모리: 1640.5 MB)
[메모리] forecast_sarima 실행 전: 1640.49 MB
[메모리] find_best_sarima_params 실행 전: 1640.49 MB
[메모리] find_best_sarima_params 실행 후: 1640.49 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1640.49 MB (변화: +0.00 MB)
[INFN]   [SARIMA] 완료  첫값=3.31e+08 (메모리: 1640.5 MB)
[INFN]   [ETS] 시작  (메모리: 1640.5 MB)
[메모리] forecast_ets 실행 전: 1640.49 MB
[메모리] forecast_ets 실행 후: 1640.49 MB (변화: +0.00 MB)
[INFN]   [ETS] 완료  첫값=3.64e+08 (메모리: 1640.5 MB)
[INFN]   [Prophet] 시작  (메모리: 1640.5 MB)

01:06:43 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1640.49 MB

01:06:43 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1640.68 MB (변화: +0.19 MB)
[INFN]   [Prophet] 완료  첫값=4.22e+08 (메모리: 1640.7 MB)
[INFN]   [LSTM] 시작  (메모리: 1640.7 MB)
[메모리] forecast_lstm 실행 전: 1640.68 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1640.82 MB (변화: +0.14 MB)
[INFN]   [LSTM] 완료  첫값=3.84e+08 (메모리: 1640.8 MB)
[INFN]   [Theta] 시작  (메모리: 1640.8 MB)
[메모리] forecast_theta 실행 전: 1640.82 MB
[메모리] forecast_theta 실행 후: 1640.82 MB (변화: +0.00 MB)
[INFN]   [Theta] 완료  첫값=3.62e+08 (메모리: 1640.8 MB)
[INFN]   [DB] 88행 저장 완료
[PROGRESS] [ 395/500] ( 79.0%)  >>  NVAX
[NVAX] [NEG-SKIP] [NVAX] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2021, 12, 31), datetime.date(2023, 3, 31)])
[PROGRESS] [ 396/500] ( 79.2%)  >>  TR
[TR]   40분기 | 2016-03-31 ~ 2025-12-31
[TR]   [SARIMA] 시작  (메모리: 1640.8 MB)
[메모리] forecast_sarima 실행 전: 1640.82 MB
[메모리] find_best_sarima_params 실행 전: 1640.82 MB
[메모리] find_best_sarima_params 실행 후: 1640.82 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1640.82 MB (변화: +0.00 MB)
[TR]   [SARIMA] 완료  첫값=1.65e+08 (메모리: 1640.8 MB)
[TR]   [ETS] 시작  (메모리: 1640.8 MB)
[메모리] forecast_ets 실행 전: 1640.82 MB
[메모리] forecast_ets 실행 후: 1640.82 MB (변화: +0.00 MB)
[TR]   [ETS] 완료  첫값=1.55e+08 (메모리: 1640.8 MB)
[TR]   [Prophet] 시작  (메모리: 1640.8 MB)

01:07:02 - cmdstanpy - INFO - Chain [1] start processing
01:07:02 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1640.82 MB
[메모리] forecast_prophet 실행 후: 1640.85 MB (변화: +0.02 MB)
[TR]   [Prophet] 완료  첫값=1.94e+08 (메모리: 1640.8 MB)
[TR]   [LSTM] 시작  (메모리: 1640.8 MB)
[메모리] forecast_lstm 실행 전: 1640.85 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1640.82 MB (변화: -0.03 MB)
[TR]   [LSTM] 완료  첫값=1.82e+08 (메모리: 1640.8 MB)
[TR]   [Theta] 시작  (메모리: 1640.8 MB)
[메모리] forecast_theta 실행 전: 1640.82 MB
[메모리] forecast_theta 실행 후: 1640.82 MB (변화: +0.00 MB)
[TR]   [Theta] 완료  첫값=1.54e+08 (메모리: 1640.8 MB)
[TR]   [DB] 88행 저장 완료
[PROGRESS] [ 397/500] ( 79.4%)  >>  SPB
[SPB]   40분기 | 2016-03-31 ~ 2025-12-28
[SPB]   [SARIMA] 시작  (메모리: 1640.8 MB)
[메모리] forecast_sarima 실행 전: 1640.82 MB
[메모리] find_best_sarima_params 실행 전: 1640.82 MB
[메모리] find_best_sarima_params 실행 후: 1640.82 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1640.82 MB (변화: +0.00 MB)
[SPB]   [SARIMA] 완료  첫값=6.93e+08 (메모리: 1640.8 MB)
[SPB]   [ETS] 시작  (메모리: 1640.8 MB)
[메모리] forecast_ets 실행 전: 1640.82 MB
[메모리] forecast_ets 실행 후: 1640.82 MB (변화: +0.00 MB)
[SPB]   [ETS] 완료  첫값=6.41e+08 (메모리: 1640.8 MB)
[SPB]   [Prophet] 시작  (메모리: 1640.8 MB)

01:07:17 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1640.82 MB

01:07:17 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1640.84 MB (변화: +0.02 MB)
[SPB]   [Prophet] 완료  첫값=6.47e+08 (메모리: 1640.8 MB)
[SPB]   [LSTM] 시작  (메모리: 1640.8 MB)
[메모리] forecast_lstm 실행 전: 1640.84 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1640.75 MB (변화: -0.09 MB)
[SPB]   [LSTM] 완료  첫값=6.98e+08 (메모리: 1640.8 MB)
[SPB]   [Theta] 시작  (메모리: 1640.8 MB)
[메모리] forecast_theta 실행 전: 1640.75 MB
[메모리] forecast_theta 실행 후: 1640.75 MB (변화: +0.00 MB)
[SPB]   [Theta] 완료  첫값=6.77e+08 (메모리: 1640.8 MB)
[SPB]   [DB] 88행 저장 완료
[PROGRESS] [ 398/500] ( 79.6%)  >>  QURE
[QURE]   40분기 | 2016-03-31 ~ 2025-12-31
[QURE]   [SARIMA] 시작  (메모리: 1640.8 MB)
[메모리] forecast_sarima 실행 전: 1640.75 MB
[메모리] find_best_sarima_params 실행 전: 1640.75 MB
[메모리] find_best_sarima_params 실행 후: 1640.75 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1640.75 MB (변화: +0.00 MB)
[QURE]   [SARIMA] 완료  첫값=1.70e+06 (메모리: 1640.8 MB)
[QURE]   [ETS] 시작  (메모리: 1640.8 MB)
[메모리] forecast_ets 실행 전: 1640.75 MB
[메모리] forecast_ets 실행 후: 1640.76 MB (변화: +0.00 MB)
[QURE]   [ETS] 완료  첫값=2.11e+06 (메모리: 1640.8 MB)
[QURE]   [Prophet] 시작  (메모리: 1640.8 MB)
[메모리] forecast_prophet 실행 전: 1640.76 MB

01:07:36 - cmdstanpy - INFO - Chain [1] start processing
01:07:36 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1641.37 MB (변화: +0.61 MB)
[QURE]   [Prophet] 완료  첫값=2.58e+07 (메모리: 1641.4 MB)
[QURE]   [LSTM] 시작  (메모리: 1641.4 MB)
[메모리] forecast_lstm 실행 전: 1641.37 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1642.32 MB (변화: +0.95 MB)
[QURE]   [LSTM] 완료  첫값=3.30e+07 (메모리: 1642.3 MB)
[QURE]   [Theta] 시작  (메모리: 1642.3 MB)
[메모리] forecast_theta 실행 전: 1642.32 MB
[메모리] forecast_theta 실행 후: 1642.32 MB (변화: +0.00 MB)
[QURE]   [Theta] 완료  첫값=5.52e+06 (메모리: 1642.3 MB)
[QURE]   [DB] 88행 저장 완료
[PROGRESS] [ 399/500] ( 79.8%)  >>  TTI
[TTI]   40분기 | 2016-03-31 ~ 2025-12-31
[TTI]   [SARIMA] 시작  (메모리: 1642.3 MB)
[메모리] forecast_sarima 실행 전: 1642.32 MB
[메모리] find_best_sarima_params 실행 전: 1642.32 MB
[메모리] find_best_sarima_params 실행 후: 1642.32 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1642.32 MB (변화: +0.00 MB)
[TTI]   [SARIMA] 완료  첫값=1.35e+08 (메모리: 1642.3 MB)
[TTI]   [ETS] 시작  (메모리: 1642.3 MB)
[메모리] forecast_ets 실행 전: 1642.32 MB
[메모리] forecast_ets 실행 후: 1642.32 MB (변화: +0.00 MB)
[TTI]   [ETS] 완료  첫값=1.38e+08 (메모리: 1642.3 MB)
[TTI]   [Prophet] 시작  (메모리: 1642.3 MB)
[메모리] forecast_prophet 실행 전: 1642.32 MB

01:07:55 - cmdstanpy - INFO - Chain [1] start processing
01:07:55 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1642.35 MB (변화: +0.02 MB)
[TTI]   [Prophet] 완료  첫값=1.30e+08 (메모리: 1642.3 MB)
[TTI]   [LSTM] 시작  (메모리: 1642.3 MB)
[메모리] forecast_lstm 실행 전: 1642.35 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1642.33 MB (변화: -0.02 MB)
[TTI]   [LSTM] 완료  첫값=1.59e+08 (메모리: 1642.3 MB)
[TTI]   [Theta] 시작  (메모리: 1642.3 MB)
[메모리] forecast_theta 실행 전: 1642.33 MB
[메모리] forecast_theta 실행 후: 1642.33 MB (변화: +0.00 MB)
[TTI]   [Theta] 완료  첫값=1.46e+08 (메모리: 1642.3 MB)
[TTI]   [DB] 88행 저장 완료
[PROGRESS] [ 400/500] ( 80.0%)  >>  CNL
[CNL]   40분기 | 2016-03-31 ~ 2025-12-31
[CNL]   [SARIMA] 시작  (메모리: 1642.3 MB)
[메모리] forecast_sarima 실행 전: 1642.33 MB
[메모리] find_best_sarima_params 실행 전: 1642.33 MB
[메모리] find_best_sarima_params 실행 후: 1642.33 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1642.33 MB (변화: +0.00 MB)
[CNL]   [SARIMA] 완료  첫값=6.84e+06 (메모리: 1642.3 MB)
[CNL]   [ETS] 시작  (메모리: 1642.3 MB)
[메모리] forecast_ets 실행 전: 1642.33 MB
[메모리] forecast_ets 실행 후: 1642.33 MB (변화: +0.00 MB)
[CNL]   [ETS] 완료  첫값=-2.94e+06 (메모리: 1642.3 MB)
[CNL]   [Prophet] 시작  (메모리: 1642.3 MB)

01:08:12 - cmdstanpy - INFO - Chain [1] start processing
01:08:12 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1642.33 MB
[메모리] forecast_prophet 실행 후: 1642.48 MB (변화: +0.15 MB)
[CNL]   [Prophet] 완료  첫값=-9.37e+07 (메모리: 1642.5 MB)
[CNL]   [LSTM] 시작  (메모리: 1642.5 MB)
[메모리] forecast_lstm 실행 전: 1642.48 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1642.43 MB (변화: -0.05 MB)
[CNL]   [LSTM] 완료  첫값=1.88e+07 (메모리: 1642.4 MB)
[CNL]   [Theta] 시작  (메모리: 1642.4 MB)
[메모리] forecast_theta 실행 전: 1642.43 MB
[메모리] forecast_theta 실행 후: 1642.43 MB (변화: +0.00 MB)
[CNL]   [Theta] 완료  첫값=-7.28e+05 (메모리: 1642.4 MB)
[CNL]   [DB] 88행 저장 완료
[PROGRESS] [ 401/500] ( 80.2%)  >>  TRIP
[TRIP]   40분기 | 2016-03-31 ~ 2025-12-31
[TRIP]   [SARIMA] 시작  (메모리: 1642.4 MB)
[메모리] forecast_sarima 실행 전: 1642.43 MB
[메모리] find_best_sarima_params 실행 전: 1642.43 MB
[메모리] find_best_sarima_params 실행 후: 1642.43 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1642.43 MB (변화: +0.00 MB)
[TRIP]   [SARIMA] 완료  첫값=4.47e+08 (메모리: 1642.4 MB)
[TRIP]   [ETS] 시작  (메모리: 1642.4 MB)
[메모리] forecast_ets 실행 전: 1642.43 MB
[메모리] forecast_ets 실행 후: 1642.43 MB (변화: +0.00 MB)
[TRIP]   [ETS] 완료  첫값=4.34e+08 (메모리: 1642.4 MB)
[TRIP]   [Prophet] 시작  (메모리: 1642.4 MB)

01:08:32 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1642.43 MB

01:08:32 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1642.46 MB (변화: +0.02 MB)
[TRIP]   [Prophet] 완료  첫값=4.19e+08 (메모리: 1642.5 MB)
[TRIP]   [LSTM] 시작  (메모리: 1642.5 MB)
[메모리] forecast_lstm 실행 전: 1642.46 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1641.60 MB (변화: -0.86 MB)
[TRIP]   [LSTM] 완료  첫값=4.29e+08 (메모리: 1641.6 MB)
[TRIP]   [Theta] 시작  (메모리: 1641.6 MB)
[메모리] forecast_theta 실행 전: 1641.60 MB
[메모리] forecast_theta 실행 후: 1641.60 MB (변화: +0.00 MB)
[TRIP]   [Theta] 완료  첫값=4.49e+08 (메모리: 1641.6 MB)
[TRIP]   [DB] 88행 저장 완료
[PROGRESS] [ 402/500] ( 80.4%)  >>  WRE
[WRE] [NEG-SKIP] [WRE] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2022, 12, 31)])
[PROGRESS] [ 403/500] ( 80.6%)  >>  WEN
[WEN]   40분기 | 2016-04-03 ~ 2025-12-28
[WEN]   [SARIMA] 시작  (메모리: 1641.6 MB)
[메모리] forecast_sarima 실행 전: 1641.60 MB
[메모리] find_best_sarima_params 실행 전: 1641.60 MB
[메모리] find_best_sarima_params 실행 후: 1641.60 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1641.60 MB (변화: +0.00 MB)
[WEN]   [SARIMA] 완료  첫값=5.48e+08 (메모리: 1641.6 MB)
[WEN]   [ETS] 시작  (메모리: 1641.6 MB)
[메모리] forecast_ets 실행 전: 1641.60 MB
[메모리] forecast_ets 실행 후: 1641.60 MB (변화: +0.00 MB)
[WEN]   [ETS] 완료  첫값=5.42e+08 (메모리: 1641.6 MB)
[WEN]   [Prophet] 시작  (메모리: 1641.6 MB)

01:08:55 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1641.60 MB

01:08:55 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1641.62 MB (변화: +0.03 MB)
[WEN]   [Prophet] 완료  첫값=5.91e+08 (메모리: 1641.6 MB)
[WEN]   [LSTM] 시작  (메모리: 1641.6 MB)
[메모리] forecast_lstm 실행 전: 1641.62 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1642.59 MB (변화: +0.97 MB)
[WEN]   [LSTM] 완료  첫값=5.49e+08 (메모리: 1642.6 MB)
[WEN]   [Theta] 시작  (메모리: 1642.6 MB)
[메모리] forecast_theta 실행 전: 1642.59 MB
[메모리] forecast_theta 실행 후: 1642.59 MB (변화: +0.00 MB)
[WEN]   [Theta] 완료  첫값=5.40e+08 (메모리: 1642.6 MB)
[WEN]   [DB] 88행 저장 완료
[PROGRESS] [ 404/500] ( 80.8%)  >>  GLP
[GLP]   40분기 | 2016-03-31 ~ 2025-12-31
[GLP]   [SARIMA] 시작  (메모리: 1642.6 MB)
[메모리] forecast_sarima 실행 전: 1642.59 MB
[메모리] find_best_sarima_params 실행 전: 1642.59 MB
[메모리] find_best_sarima_params 실행 후: 1642.59 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1642.59 MB (변화: +0.00 MB)
[GLP]   [SARIMA] 완료  첫값=4.76e+09 (메모리: 1642.6 MB)
[GLP]   [ETS] 시작  (메모리: 1642.6 MB)
[메모리] forecast_ets 실행 전: 1642.59 MB
[메모리] forecast_ets 실행 후: 1642.60 MB (변화: +0.00 MB)
[GLP]   [ETS] 완료  첫값=4.63e+09 (메모리: 1642.6 MB)
[GLP]   [Prophet] 시작  (메모리: 1642.6 MB)

01:09:11 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1642.60 MB

01:09:11 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1642.62 MB (변화: +0.02 MB)
[GLP]   [Prophet] 완료  첫값=4.89e+09 (메모리: 1642.6 MB)
[GLP]   [LSTM] 시작  (메모리: 1642.6 MB)
[메모리] forecast_lstm 실행 전: 1642.62 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1642.59 MB (변화: -0.03 MB)
[GLP]   [LSTM] 완료  첫값=4.24e+09 (메모리: 1642.6 MB)
[GLP]   [Theta] 시작  (메모리: 1642.6 MB)
[메모리] forecast_theta 실행 전: 1642.59 MB
[메모리] forecast_theta 실행 후: 1642.59 MB (변화: +0.00 MB)
[GLP]   [Theta] 완료  첫값=4.70e+09 (메모리: 1642.6 MB)
[GLP]   [DB] 88행 저장 완료
[PROGRESS] [ 405/500] ( 81.0%)  >>  LILA
[LILA]   40분기 | 2016-03-31 ~ 2025-12-31
[LILA]   [SARIMA] 시작  (메모리: 1642.6 MB)
[메모리] forecast_sarima 실행 전: 1642.59 MB
[메모리] find_best_sarima_params 실행 전: 1642.59 MB
[메모리] find_best_sarima_params 실행 후: 1642.59 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1642.59 MB (변화: +0.00 MB)
[LILA]   [SARIMA] 완료  첫값=1.16e+09 (메모리: 1642.6 MB)
[LILA]   [ETS] 시작  (메모리: 1642.6 MB)
[메모리] forecast_ets 실행 전: 1642.59 MB
[메모리] forecast_ets 실행 후: 1642.59 MB (변화: +0.00 MB)
[LILA]   [ETS] 완료  첫값=1.14e+09 (메모리: 1642.6 MB)
[LILA]   [Prophet] 시작  (메모리: 1642.6 MB)

01:09:29 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1642.59 MB

01:09:29 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1642.60 MB (변화: +0.01 MB)
[LILA]   [Prophet] 완료  첫값=1.25e+09 (메모리: 1642.6 MB)
[LILA]   [LSTM] 시작  (메모리: 1642.6 MB)
[메모리] forecast_lstm 실행 전: 1642.60 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1641.55 MB (변화: -1.05 MB)
[LILA]   [LSTM] 완료  첫값=1.09e+09 (메모리: 1641.5 MB)
[LILA]   [Theta] 시작  (메모리: 1641.5 MB)
[메모리] forecast_theta 실행 전: 1641.55 MB
[메모리] forecast_theta 실행 후: 1641.55 MB (변화: +0.00 MB)
[LILA]   [Theta] 완료  첫값=1.17e+09 (메모리: 1641.5 MB)
[LILA]   [DB] 88행 저장 완료
[PROGRESS] [ 406/500] ( 81.2%)  >>  UTI
[UTI]   40분기 | 2016-03-31 ~ 2025-12-31
[UTI]   [SARIMA] 시작  (메모리: 1641.5 MB)
[메모리] forecast_sarima 실행 전: 1641.55 MB
[메모리] find_best_sarima_params 실행 전: 1641.55 MB
[메모리] find_best_sarima_params 실행 후: 1641.55 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1641.55 MB (변화: +0.00 MB)
[UTI]   [SARIMA] 완료  첫값=2.26e+08 (메모리: 1641.5 MB)
[UTI]   [ETS] 시작  (메모리: 1641.5 MB)
[메모리] forecast_ets 실행 전: 1641.55 MB
[메모리] forecast_ets 실행 후: 1641.55 MB (변화: +0.00 MB)
[UTI]   [ETS] 완료  첫값=2.29e+08 (메모리: 1641.6 MB)
[UTI]   [Prophet] 시작  (메모리: 1641.6 MB)
[메모리] forecast_prophet 실행 전: 1641.55 MB

01:09:46 - cmdstanpy - INFO - Chain [1] start processing
01:09:46 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1641.57 MB (변화: +0.02 MB)
[UTI]   [Prophet] 완료  첫값=2.35e+08 (메모리: 1641.6 MB)
[UTI]   [LSTM] 시작  (메모리: 1641.6 MB)
[메모리] forecast_lstm 실행 전: 1641.57 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1641.54 MB (변화: -0.04 MB)
[UTI]   [LSTM] 완료  첫값=2.58e+08 (메모리: 1641.5 MB)
[UTI]   [Theta] 시작  (메모리: 1641.5 MB)
[메모리] forecast_theta 실행 전: 1641.54 MB
[메모리] forecast_theta 실행 후: 1641.54 MB (변화: +0.00 MB)
[UTI]   [Theta] 완료  첫값=2.26e+08 (메모리: 1641.5 MB)
[UTI]   [DB] 88행 저장 완료
[PROGRESS] [ 407/500] ( 81.4%)  >>  SBH
[SBH]   40분기 | 2016-03-31 ~ 2025-12-31
[SBH]   [SARIMA] 시작  (메모리: 1641.5 MB)
[메모리] forecast_sarima 실행 전: 1641.54 MB
[메모리] find_best_sarima_params 실행 전: 1641.54 MB
[메모리] find_best_sarima_params 실행 후: 1641.54 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1641.54 MB (변화: +0.00 MB)
[SBH]   [SARIMA] 완료  첫값=9.15e+08 (메모리: 1641.5 MB)
[SBH]   [ETS] 시작  (메모리: 1641.5 MB)
[메모리] forecast_ets 실행 전: 1641.54 MB
[메모리] forecast_ets 실행 후: 1641.54 MB (변화: +0.00 MB)
[SBH]   [ETS] 완료  첫값=8.92e+08 (메모리: 1641.5 MB)
[SBH]   [Prophet] 시작  (메모리: 1641.5 MB)
[메모리] forecast_prophet 실행 전: 1641.54 MB

01:10:08 - cmdstanpy - INFO - Chain [1] start processing
01:10:08 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1642.21 MB (변화: +0.67 MB)
[SBH]   [Prophet] 완료  첫값=9.17e+08 (메모리: 1642.2 MB)
[SBH]   [LSTM] 시작  (메모리: 1642.2 MB)
[메모리] forecast_lstm 실행 전: 1642.21 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1643.19 MB (변화: +0.98 MB)
[SBH]   [LSTM] 완료  첫값=9.00e+08 (메모리: 1643.2 MB)
[SBH]   [Theta] 시작  (메모리: 1643.2 MB)
[메모리] forecast_theta 실행 전: 1643.19 MB
[메모리] forecast_theta 실행 후: 1643.19 MB (변화: +0.00 MB)
[SBH]   [Theta] 완료  첫값=9.28e+08 (메모리: 1643.2 MB)
[SBH]   [DB] 88행 저장 완료
[PROGRESS] [ 408/500] ( 81.6%)  >>  DNOW
[DNOW]   40분기 | 2016-03-31 ~ 2025-12-31
[DNOW]   [SARIMA] 시작  (메모리: 1643.2 MB)
[메모리] forecast_sarima 실행 전: 1643.19 MB
[메모리] find_best_sarima_params 실행 전: 1643.19 MB
[메모리] find_best_sarima_params 실행 후: 1643.19 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1643.19 MB (변화: +0.00 MB)
[DNOW]   [SARIMA] 완료  첫값=1.09e+09 (메모리: 1643.2 MB)
[DNOW]   [ETS] 시작  (메모리: 1643.2 MB)
[메모리] forecast_ets 실행 전: 1643.19 MB
[메모리] forecast_ets 실행 후: 1643.19 MB (변화: +0.00 MB)
[DNOW]   [ETS] 완료  첫값=1.46e+09 (메모리: 1643.2 MB)
[DNOW]   [Prophet] 시작  (메모리: 1643.2 MB)

01:10:24 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1643.19 MB

01:10:25 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1643.21 MB (변화: +0.02 MB)
[DNOW]   [Prophet] 완료  첫값=5.79e+08 (메모리: 1643.2 MB)
[DNOW]   [LSTM] 시작  (메모리: 1643.2 MB)
[메모리] forecast_lstm 실행 전: 1643.21 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1642.07 MB (변화: -1.14 MB)
[DNOW]   [LSTM] 완료  첫값=5.93e+08 (메모리: 1642.1 MB)
[DNOW]   [Theta] 시작  (메모리: 1642.1 MB)
[메모리] forecast_theta 실행 전: 1642.07 MB
[메모리] forecast_theta 실행 후: 1642.07 MB (변화: +0.00 MB)
[DNOW]   [Theta] 완료  첫값=9.58e+08 (메모리: 1642.1 MB)
[DNOW]   [DB] 88행 저장 완료
[PROGRESS] [ 409/500] ( 81.8%)  >>  NVEE
[NVEE]   40분기 | 2015-09-30 ~ 2025-06-28
[NVEE]   [SARIMA] 시작  (메모리: 1642.1 MB)
[메모리] forecast_sarima 실행 전: 1642.07 MB
[메모리] find_best_sarima_params 실행 전: 1642.07 MB
[메모리] find_best_sarima_params 실행 후: 1642.07 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1642.07 MB (변화: +0.00 MB)
[NVEE]   [SARIMA] 완료  첫값=2.50e+08 (메모리: 1642.1 MB)
[NVEE]   [ETS] 시작  (메모리: 1642.1 MB)
[메모리] forecast_ets 실행 전: 1642.07 MB
[메모리] forecast_ets 실행 후: 1642.07 MB (변화: +0.00 MB)
[NVEE]   [ETS] 완료  첫값=2.65e+08 (메모리: 1642.1 MB)
[NVEE]   [Prophet] 시작  (메모리: 1642.1 MB)

01:10:41 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1642.07 MB

01:10:42 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1642.10 MB (변화: +0.02 MB)
[NVEE]   [Prophet] 완료  첫값=2.62e+08 (메모리: 1642.1 MB)
[NVEE]   [LSTM] 시작  (메모리: 1642.1 MB)
[메모리] forecast_lstm 실행 전: 1642.10 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1643.11 MB (변화: +1.01 MB)
[NVEE]   [LSTM] 완료  첫값=2.60e+08 (메모리: 1643.1 MB)
[NVEE]   [Theta] 시작  (메모리: 1643.1 MB)
[메모리] forecast_theta 실행 전: 1643.11 MB
[메모리] forecast_theta 실행 후: 1643.11 MB (변화: +0.00 MB)
[NVEE]   [Theta] 완료  첫값=2.59e+08 (메모리: 1643.1 MB)
[NVEE]   [DB] 88행 저장 완료
[PROGRESS] [ 410/500] ( 82.0%)  >>  ROCK
[ROCK]   40분기 | 2016-03-31 ~ 2025-12-31
[ROCK]   [SARIMA] 시작  (메모리: 1643.1 MB)
[메모리] forecast_sarima 실행 전: 1643.11 MB
[메모리] find_best_sarima_params 실행 전: 1643.11 MB
[메모리] find_best_sarima_params 실행 후: 1643.11 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1643.11 MB (변화: +0.00 MB)
[ROCK]   [SARIMA] 완료  첫값=2.57e+08 (메모리: 1643.1 MB)
[ROCK]   [ETS] 시작  (메모리: 1643.1 MB)
[메모리] forecast_ets 실행 전: 1643.11 MB
[메모리] forecast_ets 실행 후: 1643.11 MB (변화: +0.00 MB)
[ROCK]   [ETS] 완료  첫값=2.44e+08 (메모리: 1643.1 MB)
[ROCK]   [Prophet] 시작  (메모리: 1643.1 MB)
[메모리] forecast_prophet 실행 전: 1643.11 MB

01:10:58 - cmdstanpy - INFO - Chain [1] start processing
01:10:59 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1643.13 MB (변화: +0.02 MB)
[ROCK]   [Prophet] 완료  첫값=3.32e+08 (메모리: 1643.1 MB)
[ROCK]   [LSTM] 시작  (메모리: 1643.1 MB)
[메모리] forecast_lstm 실행 전: 1643.13 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1643.13 MB (변화: +0.00 MB)
[ROCK]   [LSTM] 완료  첫값=3.10e+08 (메모리: 1643.1 MB)
[ROCK]   [Theta] 시작  (메모리: 1643.1 MB)
[메모리] forecast_theta 실행 전: 1643.13 MB
[메모리] forecast_theta 실행 후: 1643.13 MB (변화: +0.00 MB)
[ROCK]   [Theta] 완료  첫값=2.40e+08 (메모리: 1643.1 MB)
[ROCK]   [DB] 88행 저장 완료
[PROGRESS] [ 411/500] ( 82.2%)  >>  FIVN
[FIVN]   40분기 | 2016-03-31 ~ 2025-12-31
[FIVN]   [SARIMA] 시작  (메모리: 1643.1 MB)
[메모리] forecast_sarima 실행 전: 1643.13 MB
[메모리] find_best_sarima_params 실행 전: 1643.13 MB
[메모리] find_best_sarima_params 실행 후: 1643.13 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1643.13 MB (변화: +0.00 MB)
[FIVN]   [SARIMA] 완료  첫값=3.03e+08 (메모리: 1643.1 MB)
[FIVN]   [ETS] 시작  (메모리: 1643.1 MB)
[메모리] forecast_ets 실행 전: 1643.13 MB
[메모리] forecast_ets 실행 후: 1643.13 MB (변화: +0.00 MB)
[FIVN]   [ETS] 완료  첫값=3.03e+08 (메모리: 1643.1 MB)
[FIVN]   [Prophet] 시작  (메모리: 1643.1 MB)

01:11:18 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1643.13 MB

01:11:18 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1643.14 MB (변화: +0.01 MB)
[FIVN]   [Prophet] 완료  첫값=3.08e+08 (메모리: 1643.1 MB)
[FIVN]   [LSTM] 시작  (메모리: 1643.1 MB)
[메모리] forecast_lstm 실행 전: 1643.14 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1643.12 MB (변화: -0.02 MB)
[FIVN]   [LSTM] 완료  첫값=2.77e+08 (메모리: 1643.1 MB)
[FIVN]   [Theta] 시작  (메모리: 1643.1 MB)
[메모리] forecast_theta 실행 전: 1643.12 MB
[메모리] forecast_theta 실행 후: 1643.12 MB (변화: +0.00 MB)
[FIVN]   [Theta] 완료  첫값=3.06e+08 (메모리: 1643.1 MB)
[FIVN]   [DB] 88행 저장 완료
[PROGRESS] [ 412/500] ( 82.4%)  >>  ALEX
[ALEX] [NEG-SKIP] [ALEX] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2022, 12, 31)])
[PROGRESS] [ 413/500] ( 82.6%)  >>  INT
[INT]   40분기 | 2016-03-31 ~ 2025-12-31
[INT]   [SARIMA] 시작  (메모리: 1643.1 MB)
[메모리] forecast_sarima 실행 전: 1643.12 MB
[메모리] find_best_sarima_params 실행 전: 1643.12 MB
[메모리] find_best_sarima_params 실행 후: 1643.12 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1643.12 MB (변화: +0.00 MB)
[INT]   [SARIMA] 완료  첫값=9.03e+09 (메모리: 1643.1 MB)
[INT]   [ETS] 시작  (메모리: 1643.1 MB)
[메모리] forecast_ets 실행 전: 1643.12 MB
[메모리] forecast_ets 실행 후: 1643.12 MB (변화: +0.00 MB)
[INT]   [ETS] 완료  첫값=9.40e+09 (메모리: 1643.1 MB)
[INT]   [Prophet] 시작  (메모리: 1643.1 MB)

01:11:35 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1643.12 MB

01:11:35 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1643.12 MB (변화: +0.00 MB)
[INT]   [Prophet] 완료  첫값=1.12e+10 (메모리: 1643.1 MB)
[INT]   [LSTM] 시작  (메모리: 1643.1 MB)
[메모리] forecast_lstm 실행 전: 1643.12 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1643.11 MB (변화: -0.01 MB)
[INT]   [LSTM] 완료  첫값=9.03e+09 (메모리: 1643.1 MB)
[INT]   [Theta] 시작  (메모리: 1643.1 MB)
[메모리] forecast_theta 실행 전: 1643.11 MB
[메모리] forecast_theta 실행 후: 1643.11 MB (변화: +0.00 MB)
[INT]   [Theta] 완료  첫값=9.08e+09 (메모리: 1643.1 MB)
[INT]   [DB] 88행 저장 완료
[PROGRESS] [ 414/500] ( 82.8%)  >>  ABR
[ABR] [NEG-SKIP] [ABR] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2020, 3, 31)])
[PROGRESS] [ 415/500] ( 83.0%)  >>  NVRI
[NVRI]   40분기 | 2016-03-31 ~ 2025-12-31
[NVRI]   [SARIMA] 시작  (메모리: 1643.1 MB)
[메모리] forecast_sarima 실행 전: 1643.11 MB
[메모리] find_best_sarima_params 실행 전: 1643.11 MB
[메모리] find_best_sarima_params 실행 후: 1643.11 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1643.11 MB (변화: +0.00 MB)
[NVRI]   [SARIMA] 완료  첫값=5.93e+08 (메모리: 1643.1 MB)
[NVRI]   [ETS] 시작  (메모리: 1643.1 MB)
[메모리] forecast_ets 실행 전: 1643.11 MB
[메모리] forecast_ets 실행 후: 1643.12 MB (변화: +0.00 MB)
[NVRI]   [ETS] 완료  첫값=5.99e+08 (메모리: 1643.1 MB)
[NVRI]   [Prophet] 시작  (메모리: 1643.1 MB)
[메모리] forecast_prophet 실행 전: 1643.12 MB

01:11:56 - cmdstanpy - INFO - Chain [1] start processing
01:11:56 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1643.13 MB (변화: +0.02 MB)
[NVRI]   [Prophet] 완료  첫값=5.91e+08 (메모리: 1643.1 MB)
[NVRI]   [LSTM] 시작  (메모리: 1643.1 MB)
[메모리] forecast_lstm 실행 전: 1643.13 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1643.11 MB (변화: -0.02 MB)
[NVRI]   [LSTM] 완료  첫값=5.87e+08 (메모리: 1643.1 MB)
[NVRI]   [Theta] 시작  (메모리: 1643.1 MB)
[메모리] forecast_theta 실행 전: 1643.11 MB
[메모리] forecast_theta 실행 후: 1643.11 MB (변화: +0.00 MB)
[NVRI]   [Theta] 완료  첫값=5.74e+08 (메모리: 1643.1 MB)
[NVRI]   [DB] 88행 저장 완료
[PROGRESS] [ 416/500] ( 83.2%)  >>  NRP
[NRP]   40분기 | 2016-03-31 ~ 2025-12-31
[NRP]   [SARIMA] 시작  (메모리: 1643.1 MB)
[메모리] forecast_sarima 실행 전: 1643.11 MB
[메모리] find_best_sarima_params 실행 전: 1643.11 MB
[메모리] find_best_sarima_params 실행 후: 1643.11 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1643.11 MB (변화: +0.00 MB)
[NRP]   [SARIMA] 완료  첫값=4.84e+07 (메모리: 1643.1 MB)
[NRP]   [ETS] 시작  (메모리: 1643.1 MB)
[메모리] forecast_ets 실행 전: 1643.11 MB
[메모리] forecast_ets 실행 후: 1643.11 MB (변화: +0.00 MB)
[NRP]   [ETS] 완료  첫값=4.28e+07 (메모리: 1643.1 MB)
[NRP]   [Prophet] 시작  (메모리: 1643.1 MB)

01:12:13 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1643.11 MB

01:12:13 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1643.44 MB (변화: +0.33 MB)
[NRP]   [Prophet] 완료  첫값=5.27e+07 (메모리: 1643.4 MB)
[NRP]   [LSTM] 시작  (메모리: 1643.4 MB)
[메모리] forecast_lstm 실행 전: 1643.44 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1643.48 MB (변화: +0.04 MB)
[NRP]   [LSTM] 완료  첫값=4.74e+07 (메모리: 1643.5 MB)
[NRP]   [Theta] 시작  (메모리: 1643.5 MB)
[메모리] forecast_theta 실행 전: 1643.48 MB
[메모리] forecast_theta 실행 후: 1643.48 MB (변화: +0.00 MB)
[NRP]   [Theta] 완료  첫값=4.83e+07 (메모리: 1643.5 MB)
[NRP]   [DB] 88행 저장 완료
[PROGRESS] [ 417/500] ( 83.4%)  >>  CSIQ
[CSIQ]   40분기 | 2016-03-31 ~ 2025-12-31
[CSIQ]   [SARIMA] 시작  (메모리: 1643.5 MB)
[메모리] forecast_sarima 실행 전: 1643.48 MB
[메모리] find_best_sarima_params 실행 전: 1643.48 MB
[메모리] find_best_sarima_params 실행 후: 1643.48 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1643.48 MB (변화: +0.00 MB)
[CSIQ]   [SARIMA] 완료  첫값=9.79e+08 (메모리: 1643.5 MB)
[CSIQ]   [ETS] 시작  (메모리: 1643.5 MB)
[메모리] forecast_ets 실행 전: 1643.48 MB
[메모리] forecast_ets 실행 후: 1643.49 MB (변화: +0.00 MB)
[CSIQ]   [ETS] 완료  첫값=1.25e+09 (메모리: 1643.5 MB)
[CSIQ]   [Prophet] 시작  (메모리: 1643.5 MB)

01:12:32 - cmdstanpy - INFO - Chain [1] start processing
01:12:32 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1643.49 MB
[메모리] forecast_prophet 실행 후: 1643.50 MB (변화: +0.02 MB)
[CSIQ]   [Prophet] 완료  첫값=1.81e+09 (메모리: 1643.5 MB)
[CSIQ]   [LSTM] 시작  (메모리: 1643.5 MB)
[메모리] forecast_lstm 실행 전: 1643.50 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1643.52 MB (변화: +0.02 MB)
[CSIQ]   [LSTM] 완료  첫값=1.78e+09 (메모리: 1643.5 MB)
[CSIQ]   [Theta] 시작  (메모리: 1643.5 MB)
[메모리] forecast_theta 실행 전: 1643.52 MB
[메모리] forecast_theta 실행 후: 1643.52 MB (변화: +0.00 MB)
[CSIQ]   [Theta] 완료  첫값=1.21e+09 (메모리: 1643.5 MB)
[CSIQ]   [DB] 88행 저장 완료
[PROGRESS] [ 418/500] ( 83.6%)  >>  VIVO
[VIVO] [SKIP] [VIVO] FMP에서 'sale' 데이터 없음
[PROGRESS] [ 419/500] ( 83.8%)  >>  NVCR
[NVCR]   40분기 | 2016-03-31 ~ 2025-12-31
[NVCR]   [SARIMA] 시작  (메모리: 1643.5 MB)
[메모리] forecast_sarima 실행 전: 1643.52 MB
[메모리] find_best_sarima_params 실행 전: 1643.52 MB
[메모리] find_best_sarima_params 실행 후: 1643.52 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1643.52 MB (변화: +0.00 MB)
[NVCR]   [SARIMA] 완료  첫값=1.73e+08 (메모리: 1643.5 MB)
[NVCR]   [ETS] 시작  (메모리: 1643.5 MB)
[메모리] forecast_ets 실행 전: 1643.52 MB
[메모리] forecast_ets 실행 후: 1643.52 MB (변화: +0.00 MB)
[NVCR]   [ETS] 완료  첫값=1.71e+08 (메모리: 1643.5 MB)
[NVCR]   [Prophet] 시작  (메모리: 1643.5 MB)

01:12:51 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1643.52 MB

01:12:51 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1643.55 MB (변화: +0.02 MB)
[NVCR]   [Prophet] 완료  첫값=1.66e+08 (메모리: 1643.5 MB)
[NVCR]   [LSTM] 시작  (메모리: 1643.5 MB)
[메모리] forecast_lstm 실행 전: 1643.55 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1643.55 MB (변화: +0.00 MB)
[NVCR]   [LSTM] 완료  첫값=1.61e+08 (메모리: 1643.5 MB)
[NVCR]   [Theta] 시작  (메모리: 1643.5 MB)
[메모리] forecast_theta 실행 전: 1643.55 MB
[메모리] forecast_theta 실행 후: 1643.55 MB (변화: +0.00 MB)
[NVCR]   [Theta] 완료  첫값=1.70e+08 (메모리: 1643.5 MB)
[NVCR]   [DB] 88행 저장 완료
[PROGRESS] [ 420/500] ( 84.0%)  >>  ATSG
[ATSG]   40분기 | 2015-03-31 ~ 2024-12-31
[ATSG]   [SARIMA] 시작  (메모리: 1643.5 MB)
[메모리] forecast_sarima 실행 전: 1643.55 MB
[메모리] find_best_sarima_params 실행 전: 1643.55 MB
[메모리] find_best_sarima_params 실행 후: 1643.55 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1643.55 MB (변화: +0.00 MB)
[ATSG]   [SARIMA] 완료  첫값=5.34e+08 (메모리: 1643.5 MB)
[ATSG]   [ETS] 시작  (메모리: 1643.5 MB)
[메모리] forecast_ets 실행 전: 1643.55 MB
[메모리] forecast_ets 실행 후: 1643.55 MB (변화: +0.00 MB)
[ATSG]   [ETS] 완료  첫값=4.94e+08 (메모리: 1643.6 MB)
[ATSG]   [Prophet] 시작  (메모리: 1643.6 MB)

01:13:08 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1643.55 MB

01:13:08 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1643.55 MB (변화: +0.00 MB)
[ATSG]   [Prophet] 완료  첫값=5.77e+08 (메모리: 1643.6 MB)
[ATSG]   [LSTM] 시작  (메모리: 1643.6 MB)
[메모리] forecast_lstm 실행 전: 1643.55 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1643.51 MB (변화: -0.04 MB)
[ATSG]   [LSTM] 완료  첫값=5.78e+08 (메모리: 1643.5 MB)
[ATSG]   [Theta] 시작  (메모리: 1643.5 MB)
[메모리] forecast_theta 실행 전: 1643.51 MB
[메모리] forecast_theta 실행 후: 1643.51 MB (변화: +0.00 MB)
[ATSG]   [Theta] 완료  첫값=4.85e+08 (메모리: 1643.5 MB)
[ATSG]   [DB] 88행 저장 완료
[PROGRESS] [ 421/500] ( 84.2%)  >>  QUBT
[QUBT]   39분기 | 2010-09-30 ~ 2025-12-31
[QUBT]   [SARIMA] 시작  (메모리: 1643.5 MB)
[메모리] forecast_sarima 실행 전: 1643.51 MB
[메모리] find_best_sarima_params 실행 전: 1643.51 MB
[메모리] find_best_sarima_params 실행 후: 1643.51 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1643.51 MB (변화: +0.00 MB)
[QUBT]   [SARIMA] 완료  첫값=5.43e+04 (메모리: 1643.5 MB)
[QUBT]   [ETS] 시작  (메모리: 1643.5 MB)
[메모리] forecast_ets 실행 전: 1643.51 MB
[메모리] forecast_ets 실행 후: 1643.52 MB (변화: +0.00 MB)
[QUBT]   [ETS] 완료  첫값=1.93e+05 (메모리: 1643.5 MB)
[QUBT]   [Prophet] 시작  (메모리: 1643.5 MB)

01:13:23 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1643.52 MB

01:13:23 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1643.53 MB (변화: +0.01 MB)
[QUBT]   [Prophet] 완료  첫값=-1.35e+05 (메모리: 1643.5 MB)
[QUBT]   [LSTM] 시작  (메모리: 1643.5 MB)
[메모리] forecast_lstm 실행 전: 1643.53 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1643.52 MB (변화: -0.00 MB)
[QUBT]   [LSTM] 완료  첫값=1.90e+05 (메모리: 1643.5 MB)
[QUBT]   [Theta] 시작  (메모리: 1643.5 MB)
[메모리] forecast_theta 실행 전: 1643.52 MB
[메모리] forecast_theta 실행 후: 1643.52 MB (변화: +0.00 MB)
[QUBT]   [Theta] 완료  첫값=2.01e+05 (메모리: 1643.5 MB)
[QUBT]   [DB] 87행 저장 완료
[PROGRESS] [ 422/500] ( 84.4%)  >>  CTS
[CTS]   40분기 | 2016-03-31 ~ 2025-12-31
[CTS]   [SARIMA] 시작  (메모리: 1643.5 MB)
[메모리] forecast_sarima 실행 전: 1643.52 MB
[메모리] find_best_sarima_params 실행 전: 1643.52 MB
[메모리] find_best_sarima_params 실행 후: 1643.52 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1643.52 MB (변화: +0.00 MB)
[CTS]   [SARIMA] 완료  첫값=1.38e+08 (메모리: 1643.5 MB)
[CTS]   [ETS] 시작  (메모리: 1643.5 MB)
[메모리] forecast_ets 실행 전: 1643.52 MB
[메모리] forecast_ets 실행 후: 1643.53 MB (변화: +0.00 MB)
[CTS]   [ETS] 완료  첫값=1.38e+08 (메모리: 1643.5 MB)
[CTS]   [Prophet] 시작  (메모리: 1643.5 MB)

01:13:44 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1643.53 MB

01:13:45 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1643.55 MB (변화: +0.02 MB)
[CTS]   [Prophet] 완료  첫값=1.44e+08 (메모리: 1643.6 MB)
[CTS]   [LSTM] 시작  (메모리: 1643.6 MB)
[메모리] forecast_lstm 실행 전: 1643.55 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1643.54 MB (변화: -0.01 MB)
[CTS]   [LSTM] 완료  첫값=1.35e+08 (메모리: 1643.5 MB)
[CTS]   [Theta] 시작  (메모리: 1643.5 MB)
[메모리] forecast_theta 실행 전: 1643.54 MB
[메모리] forecast_theta 실행 후: 1643.54 MB (변화: +0.00 MB)
[CTS]   [Theta] 완료  첫값=1.38e+08 (메모리: 1643.5 MB)
[CTS]   [DB] 88행 저장 완료
[PROGRESS] [ 423/500] ( 84.6%)  >>  IMOS
[IMOS]   40분기 | 2016-03-31 ~ 2025-12-31
[IMOS]   [SARIMA] 시작  (메모리: 1643.5 MB)
[메모리] forecast_sarima 실행 전: 1643.54 MB
[메모리] find_best_sarima_params 실행 전: 1643.54 MB
[메모리] find_best_sarima_params 실행 후: 1643.54 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1643.54 MB (변화: +0.00 MB)
[IMOS]   [SARIMA] 완료  첫값=5.19e+09 (메모리: 1643.5 MB)
[IMOS]   [ETS] 시작  (메모리: 1643.5 MB)
[메모리] forecast_ets 실행 전: 1643.54 MB
[메모리] forecast_ets 실행 후: 1643.54 MB (변화: +0.00 MB)
[IMOS]   [ETS] 완료  첫값=4.96e+09 (메모리: 1643.5 MB)
[IMOS]   [Prophet] 시작  (메모리: 1643.5 MB)

01:14:01 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1643.54 MB

01:14:01 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1643.55 MB (변화: +0.01 MB)
[IMOS]   [Prophet] 완료  첫값=5.85e+09 (메모리: 1643.6 MB)
[IMOS]   [LSTM] 시작  (메모리: 1643.6 MB)
[메모리] forecast_lstm 실행 전: 1643.55 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1643.54 MB (변화: -0.01 MB)
[IMOS]   [LSTM] 완료  첫값=4.94e+09 (메모리: 1643.5 MB)
[IMOS]   [Theta] 시작  (메모리: 1643.5 MB)
[메모리] forecast_theta 실행 전: 1643.54 MB
[메모리] forecast_theta 실행 후: 1643.54 MB (변화: +0.00 MB)
[IMOS]   [Theta] 완료  첫값=4.62e+09 (메모리: 1643.5 MB)
[IMOS]   [DB] 88행 저장 완료
[PROGRESS] [ 424/500] ( 84.8%)  >>  BAK
[BAK]   40분기 | 2016-03-31 ~ 2025-12-31
[BAK]   [SARIMA] 시작  (메모리: 1643.5 MB)
[메모리] forecast_sarima 실행 전: 1643.54 MB
[메모리] find_best_sarima_params 실행 전: 1643.54 MB
[메모리] find_best_sarima_params 실행 후: 1643.54 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1643.54 MB (변화: +0.00 MB)
[BAK]   [SARIMA] 완료  첫값=1.64e+10 (메모리: 1643.5 MB)
[BAK]   [ETS] 시작  (메모리: 1643.5 MB)
[메모리] forecast_ets 실행 전: 1643.54 MB
[메모리] forecast_ets 실행 후: 1643.55 MB (변화: +0.01 MB)
[BAK]   [ETS] 완료  첫값=1.41e+10 (메모리: 1643.5 MB)
[BAK]   [Prophet] 시작  (메모리: 1643.5 MB)
[메모리] forecast_prophet 실행 전: 1643.55 MB

01:14:17 - cmdstanpy - INFO - Chain [1] start processing
01:14:17 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1643.56 MB (변화: +0.01 MB)
[BAK]   [Prophet] 완료  첫값=2.11e+10 (메모리: 1643.6 MB)
[BAK]   [LSTM] 시작  (메모리: 1643.6 MB)
[메모리] forecast_lstm 실행 전: 1643.56 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1643.56 MB (변화: +0.00 MB)
[BAK]   [LSTM] 완료  첫값=1.65e+10 (메모리: 1643.6 MB)
[BAK]   [Theta] 시작  (메모리: 1643.6 MB)
[메모리] forecast_theta 실행 전: 1643.56 MB
[메모리] forecast_theta 실행 후: 1643.56 MB (변화: +0.00 MB)
[BAK]   [Theta] 완료  첫값=1.67e+10 (메모리: 1643.6 MB)
[BAK]   [DB] 88행 저장 완료
[PROGRESS] [ 425/500] ( 85.0%)  >>  RCII
[RCII]   40분기 | 2015-09-30 ~ 2025-12-31
[RCII]   [SARIMA] 시작  (메모리: 1643.6 MB)
[메모리] forecast_sarima 실행 전: 1643.56 MB
[메모리] find_best_sarima_params 실행 전: 1643.56 MB
[메모리] find_best_sarima_params 실행 후: 1643.56 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1643.56 MB (변화: +0.00 MB)
[RCII]   [SARIMA] 완료  첫값=1.21e+09 (메모리: 1643.6 MB)
[RCII]   [ETS] 시작  (메모리: 1643.6 MB)
[메모리] forecast_ets 실행 전: 1643.56 MB
[메모리] forecast_ets 실행 후: 1643.56 MB (변화: +0.00 MB)
[RCII]   [ETS] 완료  첫값=1.16e+09 (메모리: 1643.6 MB)
[RCII]   [Prophet] 시작  (메모리: 1643.6 MB)

01:14:33 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1643.56 MB

01:14:33 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1643.57 MB (변화: +0.01 MB)
[RCII]   [Prophet] 완료  첫값=1.19e+09 (메모리: 1643.6 MB)
[RCII]   [LSTM] 시작  (메모리: 1643.6 MB)
[메모리] forecast_lstm 실행 전: 1643.57 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1643.55 MB (변화: -0.02 MB)
[RCII]   [LSTM] 완료  첫값=1.12e+09 (메모리: 1643.5 MB)
[RCII]   [Theta] 시작  (메모리: 1643.5 MB)
[메모리] forecast_theta 실행 전: 1643.55 MB
[메모리] forecast_theta 실행 후: 1643.55 MB (변화: +0.00 MB)
[RCII]   [Theta] 완료  첫값=1.15e+09 (메모리: 1643.5 MB)
[RCII]   [DB] 88행 저장 완료
[PROGRESS] [ 426/500] ( 85.2%)  >>  ASM
[ASM]   40분기 | 2016-03-31 ~ 2025-12-31
[ASM]   [SARIMA] 시작  (메모리: 1643.5 MB)
[메모리] forecast_sarima 실행 전: 1643.55 MB
[메모리] find_best_sarima_params 실행 전: 1643.55 MB
[메모리] find_best_sarima_params 실행 후: 1643.55 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1643.55 MB (변화: +0.00 MB)
[ASM]   [SARIMA] 완료  첫값=2.35e+07 (메모리: 1643.5 MB)
[ASM]   [ETS] 시작  (메모리: 1643.5 MB)
[메모리] forecast_ets 실행 전: 1643.55 MB
[메모리] forecast_ets 실행 후: 1643.55 MB (변화: +0.00 MB)
[ASM]   [ETS] 완료  첫값=2.25e+07 (메모리: 1643.6 MB)
[ASM]   [Prophet] 시작  (메모리: 1643.6 MB)

01:14:47 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1643.55 MB

01:14:47 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1643.57 MB (변화: +0.02 MB)
[ASM]   [Prophet] 완료  첫값=1.65e+07 (메모리: 1643.6 MB)
[ASM]   [LSTM] 시작  (메모리: 1643.6 MB)
[메모리] forecast_lstm 실행 전: 1643.57 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1643.57 MB (변화: -0.00 MB)
[ASM]   [LSTM] 완료  첫값=1.69e+07 (메모리: 1643.6 MB)
[ASM]   [Theta] 시작  (메모리: 1642.5 MB)
[메모리] forecast_theta 실행 전: 1642.46 MB
[메모리] forecast_theta 실행 후: 1642.46 MB (변화: +0.00 MB)
[ASM]   [Theta] 완료  첫값=2.42e+07 (메모리: 1642.5 MB)
[ASM]   [DB] 88행 저장 완료
[PROGRESS] [ 427/500] ( 85.4%)  >>  PGRE
[PGRE]   40분기 | 2015-12-31 ~ 2025-09-30
[PGRE]   [SARIMA] 시작  (메모리: 1642.5 MB)
[메모리] forecast_sarima 실행 전: 1642.46 MB
[메모리] find_best_sarima_params 실행 전: 1642.46 MB
[메모리] find_best_sarima_params 실행 후: 1642.46 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1642.46 MB (변화: +0.00 MB)
[PGRE]   [SARIMA] 완료  첫값=1.78e+08 (메모리: 1642.5 MB)
[PGRE]   [ETS] 시작  (메모리: 1642.5 MB)
[메모리] forecast_ets 실행 전: 1642.46 MB
[메모리] forecast_ets 실행 후: 1642.46 MB (변화: +0.00 MB)
[PGRE]   [ETS] 완료  첫값=1.80e+08 (메모리: 1642.5 MB)
[PGRE]   [Prophet] 시작  (메모리: 1642.5 MB)

01:15:05 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1642.46 MB

01:15:05 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1642.47 MB (변화: +0.01 MB)
[PGRE]   [Prophet] 완료  첫값=1.83e+08 (메모리: 1642.5 MB)
[PGRE]   [LSTM] 시작  (메모리: 1642.5 MB)
[메모리] forecast_lstm 실행 전: 1642.47 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1643.43 MB (변화: +0.96 MB)
[PGRE]   [LSTM] 완료  첫값=1.80e+08 (메모리: 1643.4 MB)
[PGRE]   [Theta] 시작  (메모리: 1643.4 MB)
[메모리] forecast_theta 실행 전: 1643.43 MB
[메모리] forecast_theta 실행 후: 1643.43 MB (변화: +0.00 MB)
[PGRE]   [Theta] 완료  첫값=1.79e+08 (메모리: 1643.4 MB)
[PGRE]   [DB] 88행 저장 완료
[PROGRESS] [ 428/500] ( 85.6%)  >>  VYX
[VYX] [NEG-SKIP] [VYX] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2023, 12, 31)])
[PROGRESS] [ 429/500] ( 85.8%)  >>  VET
[VET]   40분기 | 2016-03-31 ~ 2025-12-31
[VET]   [SARIMA] 시작  (메모리: 1643.4 MB)
[메모리] forecast_sarima 실행 전: 1643.43 MB
[메모리] find_best_sarima_params 실행 전: 1643.43 MB
[메모리] find_best_sarima_params 실행 후: 1643.43 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1643.43 MB (변화: +0.00 MB)
[VET]   [SARIMA] 완료  첫값=4.30e+08 (메모리: 1643.4 MB)
[VET]   [ETS] 시작  (메모리: 1643.4 MB)
[메모리] forecast_ets 실행 전: 1643.43 MB
[메모리] forecast_ets 실행 후: 1643.44 MB (변화: +0.00 MB)
[VET]   [ETS] 완료  첫값=4.19e+08 (메모리: 1643.4 MB)
[VET]   [Prophet] 시작  (메모리: 1643.4 MB)
[메모리] forecast_prophet 실행 전: 1643.44 MB

01:15:22 - cmdstanpy - INFO - Chain [1] start processing
01:15:22 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1643.46 MB (변화: +0.02 MB)
[VET]   [Prophet] 완료  첫값=6.06e+08 (메모리: 1643.5 MB)
[VET]   [LSTM] 시작  (메모리: 1643.5 MB)
[메모리] forecast_lstm 실행 전: 1643.46 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1643.47 MB (변화: +0.01 MB)
[VET]   [LSTM] 완료  첫값=4.71e+08 (메모리: 1643.5 MB)
[VET]   [Theta] 시작  (메모리: 1643.5 MB)
[메모리] forecast_theta 실행 전: 1643.47 MB
[메모리] forecast_theta 실행 후: 1643.47 MB (변화: +0.00 MB)
[VET]   [Theta] 완료  첫값=4.34e+08 (메모리: 1643.5 MB)
[VET]   [DB] 88행 저장 완료
[PROGRESS] [ 430/500] ( 86.0%)  >>  COLL
[COLL]   40분기 | 2016-03-31 ~ 2025-12-31
[COLL]   [SARIMA] 시작  (메모리: 1643.5 MB)
[메모리] forecast_sarima 실행 전: 1643.47 MB
[메모리] find_best_sarima_params 실행 전: 1643.47 MB
[메모리] find_best_sarima_params 실행 후: 1643.47 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1643.47 MB (변화: +0.00 MB)
[COLL]   [SARIMA] 완료  첫값=2.09e+08 (메모리: 1643.5 MB)
[COLL]   [ETS] 시작  (메모리: 1643.5 MB)
[메모리] forecast_ets 실행 전: 1643.47 MB
[메모리] forecast_ets 실행 후: 1643.47 MB (변화: +0.00 MB)
[COLL]   [ETS] 완료  첫값=2.22e+08 (메모리: 1643.5 MB)
[COLL]   [Prophet] 시작  (메모리: 1643.5 MB)

01:15:40 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1643.47 MB

01:15:40 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1643.49 MB (변화: +0.02 MB)
[COLL]   [Prophet] 완료  첫값=1.92e+08 (메모리: 1643.5 MB)
[COLL]   [LSTM] 시작  (메모리: 1643.5 MB)
[메모리] forecast_lstm 실행 전: 1643.49 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1643.43 MB (변화: -0.07 MB)
[COLL]   [LSTM] 완료  첫값=1.78e+08 (메모리: 1643.4 MB)
[COLL]   [Theta] 시작  (메모리: 1643.4 MB)
[메모리] forecast_theta 실행 전: 1643.43 MB
[메모리] forecast_theta 실행 후: 1643.43 MB (변화: +0.00 MB)
[COLL]   [Theta] 완료  첫값=2.17e+08 (메모리: 1643.4 MB)
[COLL]   [DB] 88행 저장 완료
[PROGRESS] [ 431/500] ( 86.2%)  >>  CNXN
[CNXN]   40분기 | 2016-03-31 ~ 2025-12-31
[CNXN]   [SARIMA] 시작  (메모리: 1643.4 MB)
[메모리] forecast_sarima 실행 전: 1643.43 MB
[메모리] find_best_sarima_params 실행 전: 1643.43 MB
[메모리] find_best_sarima_params 실행 후: 1643.43 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1643.43 MB (변화: +0.00 MB)
[CNXN]   [SARIMA] 완료  첫값=7.14e+08 (메모리: 1643.4 MB)
[CNXN]   [ETS] 시작  (메모리: 1643.4 MB)
[메모리] forecast_ets 실행 전: 1643.43 MB
[메모리] forecast_ets 실행 후: 1643.43 MB (변화: +0.01 MB)
[CNXN]   [ETS] 완료  첫값=6.67e+08 (메모리: 1643.4 MB)
[CNXN]   [Prophet] 시작  (메모리: 1643.4 MB)

01:16:00 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1643.43 MB

01:16:00 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1643.46 MB (변화: +0.03 MB)
[CNXN]   [Prophet] 완료  첫값=7.31e+08 (메모리: 1643.5 MB)
[CNXN]   [LSTM] 시작  (메모리: 1643.5 MB)
[메모리] forecast_lstm 실행 전: 1643.46 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1643.40 MB (변화: -0.06 MB)
[CNXN]   [LSTM] 완료  첫값=7.00e+08 (메모리: 1643.4 MB)
[CNXN]   [Theta] 시작  (메모리: 1643.4 MB)
[메모리] forecast_theta 실행 전: 1643.40 MB
[메모리] forecast_theta 실행 후: 1643.40 MB (변화: +0.00 MB)
[CNXN]   [Theta] 완료  첫값=7.11e+08 (메모리: 1643.4 MB)
[CNXN]   [DB] 88행 저장 완료
[PROGRESS] [ 432/500] ( 86.4%)  >>  WKC
[WKC]   40분기 | 2016-03-31 ~ 2025-12-31
[WKC]   [SARIMA] 시작  (메모리: 1643.4 MB)
[메모리] forecast_sarima 실행 전: 1643.40 MB
[메모리] find_best_sarima_params 실행 전: 1643.40 MB
[메모리] find_best_sarima_params 실행 후: 1643.40 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1643.40 MB (변화: +0.00 MB)
[WKC]   [SARIMA] 완료  첫값=9.03e+09 (메모리: 1643.4 MB)
[WKC]   [ETS] 시작  (메모리: 1643.4 MB)
[메모리] forecast_ets 실행 전: 1643.40 MB
[메모리] forecast_ets 실행 후: 1643.41 MB (변화: +0.00 MB)
[WKC]   [ETS] 완료  첫값=9.12e+09 (메모리: 1643.4 MB)
[WKC]   [Prophet] 시작  (메모리: 1643.4 MB)

01:16:16 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1643.41 MB

01:16:16 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1643.79 MB (변화: +0.38 MB)
[WKC]   [Prophet] 완료  첫값=1.15e+10 (메모리: 1643.8 MB)
[WKC]   [LSTM] 시작  (메모리: 1643.8 MB)
[메모리] forecast_lstm 실행 전: 1643.79 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1644.96 MB (변화: +1.17 MB)
[WKC]   [LSTM] 완료  첫값=9.37e+09 (메모리: 1645.0 MB)
[WKC]   [Theta] 시작  (메모리: 1645.0 MB)
[메모리] forecast_theta 실행 전: 1644.96 MB
[메모리] forecast_theta 실행 후: 1644.96 MB (변화: +0.00 MB)
[WKC]   [Theta] 완료  첫값=9.08e+09 (메모리: 1645.0 MB)
[WKC]   [DB] 88행 저장 완료
[PROGRESS] [ 433/500] ( 86.6%)  >>  BCRX
[BCRX]   40분기 | 2016-03-31 ~ 2025-12-31
[BCRX]   [SARIMA] 시작  (메모리: 1645.0 MB)
[메모리] forecast_sarima 실행 전: 1644.96 MB
[메모리] find_best_sarima_params 실행 전: 1644.96 MB
[메모리] find_best_sarima_params 실행 후: 1644.96 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1644.96 MB (변화: +0.00 MB)
[BCRX]   [SARIMA] 완료  첫값=3.99e+08 (메모리: 1645.0 MB)
[BCRX]   [ETS] 시작  (메모리: 1645.0 MB)
[메모리] forecast_ets 실행 전: 1644.96 MB
[메모리] forecast_ets 실행 후: 1644.96 MB (변화: +0.00 MB)
[BCRX]   [ETS] 완료  첫값=2.89e+08 (메모리: 1645.0 MB)
[BCRX]   [Prophet] 시작  (메모리: 1645.0 MB)

01:16:35 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1644.96 MB

01:16:35 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1645.17 MB (변화: +0.21 MB)
[BCRX]   [Prophet] 완료  첫값=1.58e+08 (메모리: 1645.2 MB)
[BCRX]   [LSTM] 시작  (메모리: 1645.2 MB)
[메모리] forecast_lstm 실행 전: 1645.17 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1646.30 MB (변화: +1.13 MB)
[BCRX]   [LSTM] 완료  첫값=2.99e+08 (메모리: 1646.3 MB)
[BCRX]   [Theta] 시작  (메모리: 1646.3 MB)
[메모리] forecast_theta 실행 전: 1646.30 MB
[메모리] forecast_theta 실행 후: 1646.30 MB (변화: +0.00 MB)
[BCRX]   [Theta] 완료  첫값=2.91e+08 (메모리: 1646.3 MB)
[BCRX]   [DB] 88행 저장 완료
[PROGRESS] [ 434/500] ( 86.8%)  >>  HIMX
[HIMX]   40분기 | 2016-03-31 ~ 2025-12-31
[HIMX]   [SARIMA] 시작  (메모리: 1646.3 MB)
[메모리] forecast_sarima 실행 전: 1646.30 MB
[메모리] find_best_sarima_params 실행 전: 1646.30 MB
[메모리] find_best_sarima_params 실행 후: 1646.30 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1646.30 MB (변화: +0.00 MB)
[HIMX]   [SARIMA] 완료  첫값=2.03e+08 (메모리: 1646.3 MB)
[HIMX]   [ETS] 시작  (메모리: 1646.3 MB)
[메모리] forecast_ets 실행 전: 1646.30 MB
[메모리] forecast_ets 실행 후: 1646.30 MB (변화: +0.00 MB)
[HIMX]   [ETS] 완료  첫값=1.87e+08 (메모리: 1646.3 MB)
[HIMX]   [Prophet] 시작  (메모리: 1646.3 MB)
[메모리] forecast_prophet 실행 전: 1646.30 MB

01:16:53 - cmdstanpy - INFO - Chain [1] start processing
01:16:53 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1646.33 MB (변화: +0.02 MB)
[HIMX]   [Prophet] 완료  첫값=2.70e+08 (메모리: 1646.3 MB)
[HIMX]   [LSTM] 시작  (메모리: 1646.3 MB)
[메모리] forecast_lstm 실행 전: 1646.33 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1645.41 MB (변화: -0.91 MB)
[HIMX]   [LSTM] 완료  첫값=2.35e+08 (메모리: 1645.4 MB)
[HIMX]   [Theta] 시작  (메모리: 1645.4 MB)
[메모리] forecast_theta 실행 전: 1645.41 MB
[메모리] forecast_theta 실행 후: 1645.41 MB (변화: +0.00 MB)
[HIMX]   [Theta] 완료  첫값=1.88e+08 (메모리: 1645.4 MB)
[HIMX]   [DB] 88행 저장 완료
[PROGRESS] [ 435/500] ( 87.0%)  >>  ENR
[ENR]   40분기 | 2016-03-31 ~ 2025-12-31
[ENR]   [SARIMA] 시작  (메모리: 1645.4 MB)
[메모리] forecast_sarima 실행 전: 1645.41 MB
[메모리] find_best_sarima_params 실행 전: 1645.41 MB
[메모리] find_best_sarima_params 실행 후: 1645.41 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1645.41 MB (변화: +0.00 MB)
[ENR]   [SARIMA] 완료  첫값=7.35e+08 (메모리: 1645.4 MB)
[ENR]   [ETS] 시작  (메모리: 1645.4 MB)
[메모리] forecast_ets 실행 전: 1645.41 MB
[메모리] forecast_ets 실행 후: 1645.42 MB (변화: +0.00 MB)
[ENR]   [ETS] 완료  첫값=7.32e+08 (메모리: 1645.4 MB)
[ENR]   [Prophet] 시작  (메모리: 1645.4 MB)

01:17:15 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1645.42 MB

01:17:15 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1645.44 MB (변화: +0.02 MB)
[ENR]   [Prophet] 완료  첫값=8.52e+08 (메모리: 1645.4 MB)
[ENR]   [LSTM] 시작  (메모리: 1645.4 MB)
[메모리] forecast_lstm 실행 전: 1645.44 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1646.40 MB (변화: +0.96 MB)
[ENR]   [LSTM] 완료  첫값=7.47e+08 (메모리: 1646.4 MB)
[ENR]   [Theta] 시작  (메모리: 1646.4 MB)
[메모리] forecast_theta 실행 전: 1646.40 MB
[메모리] forecast_theta 실행 후: 1646.40 MB (변화: +0.00 MB)
[ENR]   [Theta] 완료  첫값=6.42e+08 (메모리: 1646.4 MB)
[ENR]   [DB] 88행 저장 완료
[PROGRESS] [ 436/500] ( 87.2%)  >>  XHR
[XHR]   40분기 | 2016-03-31 ~ 2025-12-31
[XHR]   [SARIMA] 시작  (메모리: 1646.4 MB)
[메모리] forecast_sarima 실행 전: 1646.40 MB
[메모리] find_best_sarima_params 실행 전: 1646.40 MB
[메모리] find_best_sarima_params 실행 후: 1646.40 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1646.40 MB (변화: +0.00 MB)
[XHR]   [SARIMA] 완료  첫값=2.54e+08 (메모리: 1646.4 MB)
[XHR]   [ETS] 시작  (메모리: 1646.4 MB)
[메모리] forecast_ets 실행 전: 1646.40 MB
[메모리] forecast_ets 실행 후: 1646.40 MB (변화: +0.00 MB)
[XHR]   [ETS] 완료  첫값=2.73e+08 (메모리: 1646.4 MB)
[XHR]   [Prophet] 시작  (메모리: 1646.4 MB)

01:17:33 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1646.40 MB

01:17:33 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1646.41 MB (변화: +0.01 MB)
[XHR]   [Prophet] 완료  첫값=2.41e+08 (메모리: 1646.4 MB)
[XHR]   [LSTM] 시작  (메모리: 1646.4 MB)
[메모리] forecast_lstm 실행 전: 1646.41 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1645.55 MB (변화: -0.87 MB)
[XHR]   [LSTM] 완료  첫값=2.44e+08 (메모리: 1645.5 MB)
[XHR]   [Theta] 시작  (메모리: 1645.5 MB)
[메모리] forecast_theta 실행 전: 1645.55 MB
[메모리] forecast_theta 실행 후: 1645.55 MB (변화: +0.00 MB)
[XHR]   [Theta] 완료  첫값=2.61e+08 (메모리: 1645.5 MB)
[XHR]   [DB] 88행 저장 완료
[PROGRESS] [ 437/500] ( 87.4%)  >>  WWW
[WWW]   40분기 | 2016-03-26 ~ 2026-01-03
[WWW]   [SARIMA] 시작  (메모리: 1645.5 MB)
[메모리] forecast_sarima 실행 전: 1645.55 MB
[메모리] find_best_sarima_params 실행 전: 1645.55 MB
[메모리] find_best_sarima_params 실행 후: 1645.55 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1645.55 MB (변화: +0.00 MB)
[WWW]   [SARIMA] 완료  첫값=5.16e+08 (메모리: 1645.5 MB)
[WWW]   [ETS] 시작  (메모리: 1645.5 MB)
[메모리] forecast_ets 실행 전: 1645.55 MB
[메모리] forecast_ets 실행 후: 1645.55 MB (변화: +0.00 MB)
[WWW]   [ETS] 완료  첫값=4.47e+08 (메모리: 1645.6 MB)
[WWW]   [Prophet] 시작  (메모리: 1645.6 MB)

01:17:49 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1645.55 MB

01:17:49 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1645.94 MB (변화: +0.39 MB)
[WWW]   [Prophet] 완료  첫값=4.98e+08 (메모리: 1645.9 MB)
[WWW]   [LSTM] 시작  (메모리: 1645.9 MB)
[메모리] forecast_lstm 실행 전: 1645.94 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1646.25 MB (변화: +0.32 MB)
[WWW]   [LSTM] 완료  첫값=5.04e+08 (메모리: 1646.3 MB)
[WWW]   [Theta] 시작  (메모리: 1646.3 MB)
[메모리] forecast_theta 실행 전: 1646.25 MB
[메모리] forecast_theta 실행 후: 1646.25 MB (변화: +0.00 MB)
[WWW]   [Theta] 완료  첫값=5.03e+08 (메모리: 1646.3 MB)
[WWW]   [DB] 88행 저장 완료
[PROGRESS] [ 438/500] ( 87.6%)  >>  PGEN
[PGEN]   40분기 | 2016-03-31 ~ 2025-12-31
[PGEN]   [SARIMA] 시작  (메모리: 1646.3 MB)
[메모리] forecast_sarima 실행 전: 1646.25 MB
[메모리] find_best_sarima_params 실행 전: 1646.25 MB
[메모리] find_best_sarima_params 실행 후: 1646.25 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1646.25 MB (변화: +0.00 MB)
[PGEN]   [SARIMA] 완료  첫값=2.31e+06 (메모리: 1646.3 MB)
[PGEN]   [ETS] 시작  (메모리: 1646.3 MB)
[메모리] forecast_ets 실행 전: 1646.25 MB
[메모리] forecast_ets 실행 후: 1646.26 MB (변화: +0.00 MB)
[PGEN]   [ETS] 완료  첫값=2.24e+06 (메모리: 1646.3 MB)
[PGEN]   [Prophet] 시작  (메모리: 1646.3 MB)

01:18:02 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1646.26 MB

01:18:02 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1645.82 MB (변화: -0.44 MB)
[PGEN]   [Prophet] 완료  첫값=-1.20e+07 (메모리: 1645.8 MB)
[PGEN]   [LSTM] 시작  (메모리: 1645.8 MB)
[메모리] forecast_lstm 실행 전: 1645.82 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1646.79 MB (변화: +0.97 MB)
[PGEN]   [LSTM] 완료  첫값=1.01e+06 (메모리: 1646.8 MB)
[PGEN]   [Theta] 시작  (메모리: 1646.8 MB)
[메모리] forecast_theta 실행 전: 1646.79 MB
[메모리] forecast_theta 실행 후: 1646.79 MB (변화: +0.00 MB)
[PGEN]   [Theta] 완료  첫값=2.84e+06 (메모리: 1646.8 MB)
[PGEN]   [DB] 88행 저장 완료
[PROGRESS] [ 439/500] ( 87.8%)  >>  AMSC
[AMSC]   40분기 | 2016-03-31 ~ 2025-12-31
[AMSC]   [SARIMA] 시작  (메모리: 1646.8 MB)
[메모리] forecast_sarima 실행 전: 1646.79 MB
[메모리] find_best_sarima_params 실행 전: 1646.79 MB
[메모리] find_best_sarima_params 실행 후: 1646.79 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1646.79 MB (변화: +0.00 MB)
[AMSC]   [SARIMA] 완료  첫값=7.46e+07 (메모리: 1646.8 MB)
[AMSC]   [ETS] 시작  (메모리: 1646.8 MB)
[메모리] forecast_ets 실행 전: 1646.79 MB
[메모리] forecast_ets 실행 후: 1646.79 MB (변화: +0.00 MB)
[AMSC]   [ETS] 완료  첫값=8.03e+07 (메모리: 1646.8 MB)
[AMSC]   [Prophet] 시작  (메모리: 1646.8 MB)

01:18:20 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1646.79 MB

01:18:20 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1646.08 MB (변화: -0.71 MB)
[AMSC]   [Prophet] 완료  첫값=5.46e+07 (메모리: 1646.1 MB)
[AMSC]   [LSTM] 시작  (메모리: 1646.1 MB)
[메모리] forecast_lstm 실행 전: 1646.08 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1647.05 MB (변화: +0.97 MB)
[AMSC]   [LSTM] 완료  첫값=1.01e+08 (메모리: 1647.1 MB)
[AMSC]   [Theta] 시작  (메모리: 1647.1 MB)
[메모리] forecast_theta 실행 전: 1647.05 MB
[메모리] forecast_theta 실행 후: 1647.05 MB (변화: +0.00 MB)
[AMSC]   [Theta] 완료  첫값=7.12e+07 (메모리: 1647.1 MB)
[AMSC]   [DB] 88행 저장 완료
[PROGRESS] [ 440/500] ( 88.0%)  >>  SCZM
[SCZM]   32분기 | 2017-09-30 ~ 2025-09-30
[SCZM]   [SARIMA] 시작  (메모리: 1647.1 MB)
[메모리] forecast_sarima 실행 전: 1647.05 MB
[메모리] find_best_sarima_params 실행 전: 1647.05 MB
[메모리] find_best_sarima_params 실행 후: 1647.05 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1647.05 MB (변화: +0.00 MB)
[SCZM]   [SARIMA] 완료  첫값=8.41e+07 (메모리: 1647.1 MB)
[SCZM]   [ETS] 시작  (메모리: 1647.1 MB)
[메모리] forecast_ets 실행 전: 1647.05 MB
[메모리] forecast_ets 실행 후: 1647.06 MB (변화: +0.00 MB)
[SCZM]   [ETS] 완료  첫값=8.30e+07 (메모리: 1647.1 MB)
[SCZM]   [Prophet] 시작  (메모리: 1647.1 MB)

01:18:38 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1647.06 MB

01:18:39 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1647.08 MB (변화: +0.02 MB)
[SCZM]   [Prophet] 완료  첫값=8.27e+07 (메모리: 1647.1 MB)
[SCZM]   [LSTM] 시작  (메모리: 1647.1 MB)
[메모리] forecast_lstm 실행 전: 1647.08 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1646.21 MB (변화: -0.86 MB)
[SCZM]   [LSTM] 완료  첫값=7.70e+07 (메모리: 1646.2 MB)
[SCZM]   [Theta] 시작  (메모리: 1646.2 MB)
[메모리] forecast_theta 실행 전: 1646.21 MB
[메모리] forecast_theta 실행 후: 1646.21 MB (변화: +0.00 MB)
[SCZM]   [Theta] 완료  첫값=7.61e+07 (메모리: 1646.2 MB)
[SCZM]   [DB] 80행 저장 완료
[PROGRESS] [ 441/500] ( 88.2%)  >>  THR
[THR]   40분기 | 2016-03-31 ~ 2025-12-31
[THR]   [SARIMA] 시작  (메모리: 1646.2 MB)
[메모리] forecast_sarima 실행 전: 1646.21 MB
[메모리] find_best_sarima_params 실행 전: 1646.21 MB
[메모리] find_best_sarima_params 실행 후: 1646.21 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1646.21 MB (변화: +0.00 MB)
[THR]   [SARIMA] 완료  첫값=1.51e+08 (메모리: 1646.2 MB)
[THR]   [ETS] 시작  (메모리: 1646.2 MB)
[메모리] forecast_ets 실행 전: 1646.21 MB
[메모리] forecast_ets 실행 후: 1646.22 MB (변화: +0.00 MB)
[THR]   [ETS] 완료  첫값=1.45e+08 (메모리: 1646.2 MB)
[THR]   [Prophet] 시작  (메모리: 1646.2 MB)
[메모리] forecast_prophet 실행 전: 1646.22 MB

01:18:56 - cmdstanpy - INFO - Chain [1] start processing
01:18:56 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1646.96 MB (변화: +0.74 MB)
[THR]   [Prophet] 완료  첫값=1.31e+08 (메모리: 1647.0 MB)
[THR]   [LSTM] 시작  (메모리: 1647.0 MB)
[메모리] forecast_lstm 실행 전: 1646.96 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1646.23 MB (변화: -0.73 MB)
[THR]   [LSTM] 완료  첫값=1.20e+08 (메모리: 1646.2 MB)
[THR]   [Theta] 시작  (메모리: 1646.2 MB)
[메모리] forecast_theta 실행 전: 1646.23 MB
[메모리] forecast_theta 실행 후: 1646.23 MB (변화: +0.00 MB)
[THR]   [Theta] 완료  첫값=1.44e+08 (메모리: 1646.2 MB)
[THR]   [DB] 88행 저장 완료
[PROGRESS] [ 442/500] ( 88.4%)  >>  LADR
[LADR]   40분기 | 2016-03-31 ~ 2025-12-31
[LADR]   [SARIMA] 시작  (메모리: 1646.2 MB)
[메모리] forecast_sarima 실행 전: 1646.23 MB
[메모리] find_best_sarima_params 실행 전: 1646.23 MB
[메모리] find_best_sarima_params 실행 후: 1646.23 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1646.23 MB (변화: +0.00 MB)
[LADR]   [SARIMA] 완료  첫값=8.79e+07 (메모리: 1646.2 MB)
[LADR]   [ETS] 시작  (메모리: 1646.2 MB)
[메모리] forecast_ets 실행 전: 1646.23 MB
[메모리] forecast_ets 실행 후: 1646.23 MB (변화: +0.00 MB)
[LADR]   [ETS] 완료  첫값=8.43e+07 (메모리: 1646.2 MB)
[LADR]   [Prophet] 시작  (메모리: 1646.2 MB)

01:19:13 - cmdstanpy - INFO - Chain [1] start processing
01:19:13 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1646.23 MB
[메모리] forecast_prophet 실행 후: 1646.96 MB (변화: +0.73 MB)
[LADR]   [Prophet] 완료  첫값=1.20e+08 (메모리: 1647.0 MB)
[LADR]   [LSTM] 시작  (메모리: 1647.0 MB)
[메모리] forecast_lstm 실행 전: 1646.96 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1646.23 MB (변화: -0.73 MB)
[LADR]   [LSTM] 완료  첫값=1.09e+08 (메모리: 1646.2 MB)
[LADR]   [Theta] 시작  (메모리: 1646.2 MB)
[메모리] forecast_theta 실행 전: 1646.23 MB
[메모리] forecast_theta 실행 후: 1646.23 MB (변화: +0.00 MB)
[LADR]   [Theta] 완료  첫값=9.67e+07 (메모리: 1646.2 MB)
[LADR]   [DB] 88행 저장 완료
[PROGRESS] [ 443/500] ( 88.6%)  >>  PEB
[PEB]   40분기 | 2016-03-31 ~ 2025-12-31
[PEB]   [SARIMA] 시작  (메모리: 1646.2 MB)
[메모리] forecast_sarima 실행 전: 1646.23 MB
[메모리] find_best_sarima_params 실행 전: 1646.23 MB
[메모리] find_best_sarima_params 실행 후: 1646.23 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1646.23 MB (변화: +0.00 MB)
[PEB]   [SARIMA] 완료  첫값=3.73e+08 (메모리: 1646.2 MB)
[PEB]   [ETS] 시작  (메모리: 1646.2 MB)
[메모리] forecast_ets 실행 전: 1646.23 MB
[메모리] forecast_ets 실행 후: 1646.23 MB (변화: +0.00 MB)
[PEB]   [ETS] 완료  첫값=3.55e+08 (메모리: 1646.2 MB)
[PEB]   [Prophet] 시작  (메모리: 1646.2 MB)

01:19:31 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1646.23 MB

01:19:31 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1646.61 MB (변화: +0.37 MB)
[PEB]   [Prophet] 완료  첫값=3.77e+08 (메모리: 1646.6 MB)
[PEB]   [LSTM] 시작  (메모리: 1646.6 MB)
[메모리] forecast_lstm 실행 전: 1646.61 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1646.23 MB (변화: -0.37 MB)
[PEB]   [LSTM] 완료  첫값=3.50e+08 (메모리: 1646.2 MB)
[PEB]   [Theta] 시작  (메모리: 1646.2 MB)
[메모리] forecast_theta 실행 전: 1646.23 MB
[메모리] forecast_theta 실행 후: 1646.23 MB (변화: +0.00 MB)
[PEB]   [Theta] 완료  첫값=3.62e+08 (메모리: 1646.2 MB)
[PEB]   [DB] 88행 저장 완료
[PROGRESS] [ 444/500] ( 88.8%)  >>  TNC
[TNC]   40분기 | 2016-03-31 ~ 2025-12-31
[TNC]   [SARIMA] 시작  (메모리: 1646.2 MB)
[메모리] forecast_sarima 실행 전: 1646.23 MB
[메모리] find_best_sarima_params 실행 전: 1646.23 MB
[메모리] find_best_sarima_params 실행 후: 1646.23 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1646.23 MB (변화: +0.00 MB)
[TNC]   [SARIMA] 완료  첫값=2.98e+08 (메모리: 1646.2 MB)
[TNC]   [ETS] 시작  (메모리: 1646.2 MB)
[메모리] forecast_ets 실행 전: 1646.23 MB
[메모리] forecast_ets 실행 후: 1646.24 MB (변화: +0.00 MB)
[TNC]   [ETS] 완료  첫값=2.81e+08 (메모리: 1646.2 MB)
[TNC]   [Prophet] 시작  (메모리: 1646.2 MB)

01:19:48 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1646.24 MB

01:19:48 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1646.24 MB (변화: +0.00 MB)
[TNC]   [Prophet] 완료  첫값=3.23e+08 (메모리: 1646.2 MB)
[TNC]   [LSTM] 시작  (메모리: 1646.2 MB)
[메모리] forecast_lstm 실행 전: 1646.24 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1647.21 MB (변화: +0.97 MB)
[TNC]   [LSTM] 완료  첫값=3.12e+08 (메모리: 1647.2 MB)
[TNC]   [Theta] 시작  (메모리: 1647.2 MB)
[메모리] forecast_theta 실행 전: 1647.21 MB
[메모리] forecast_theta 실행 후: 1647.21 MB (변화: +0.00 MB)
[TNC]   [Theta] 완료  첫값=2.99e+08 (메모리: 1647.2 MB)
[TNC]   [DB] 88행 저장 완료
[PROGRESS] [ 445/500] ( 89.0%)  >>  MAN
[MAN]   40분기 | 2016-03-31 ~ 2025-12-31
[MAN]   [SARIMA] 시작  (메모리: 1647.2 MB)
[메모리] forecast_sarima 실행 전: 1647.21 MB
[메모리] find_best_sarima_params 실행 전: 1647.21 MB
[메모리] find_best_sarima_params 실행 후: 1647.21 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1647.21 MB (변화: +0.00 MB)
[MAN]   [SARIMA] 완료  첫값=4.71e+09 (메모리: 1647.2 MB)
[MAN]   [ETS] 시작  (메모리: 1647.2 MB)
[메모리] forecast_ets 실행 전: 1647.21 MB
[메모리] forecast_ets 실행 후: 1647.21 MB (변화: +0.00 MB)
[MAN]   [ETS] 완료  첫값=4.48e+09 (메모리: 1647.2 MB)
[MAN]   [Prophet] 시작  (메모리: 1647.2 MB)

01:20:04 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1647.21 MB

01:20:04 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1647.23 MB (변화: +0.02 MB)
[MAN]   [Prophet] 완료  첫값=4.52e+09 (메모리: 1647.2 MB)
[MAN]   [LSTM] 시작  (메모리: 1647.2 MB)
[메모리] forecast_lstm 실행 전: 1647.23 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1647.21 MB (변화: -0.02 MB)
[MAN]   [LSTM] 완료  첫값=4.47e+09 (메모리: 1647.2 MB)
[MAN]   [Theta] 시작  (메모리: 1647.2 MB)
[메모리] forecast_theta 실행 전: 1647.21 MB
[메모리] forecast_theta 실행 후: 1647.21 MB (변화: +0.00 MB)
[MAN]   [Theta] 완료  첫값=4.69e+09 (메모리: 1647.2 MB)
[MAN]   [DB] 88행 저장 완료
[PROGRESS] [ 446/500] ( 89.2%)  >>  TRS
[TRS]   40분기 | 2016-03-31 ~ 2025-12-31
[TRS]   [SARIMA] 시작  (메모리: 1647.2 MB)
[메모리] forecast_sarima 실행 전: 1647.21 MB
[메모리] find_best_sarima_params 실행 전: 1647.21 MB
[메모리] find_best_sarima_params 실행 후: 1647.21 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1647.21 MB (변화: +0.00 MB)
[TRS]   [SARIMA] 완료  첫값=1.92e+08 (메모리: 1647.2 MB)
[TRS]   [ETS] 시작  (메모리: 1647.2 MB)
[메모리] forecast_ets 실행 전: 1647.21 MB
[메모리] forecast_ets 실행 후: 1647.22 MB (변화: +0.00 MB)
[TRS]   [ETS] 완료  첫값=1.67e+08 (메모리: 1647.2 MB)
[TRS]   [Prophet] 시작  (메모리: 1647.2 MB)

01:20:21 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1647.22 MB

01:20:21 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1647.24 MB (변화: +0.02 MB)
[TRS]   [Prophet] 완료  첫값=2.33e+08 (메모리: 1647.2 MB)
[TRS]   [LSTM] 시작  (메모리: 1647.2 MB)
[메모리] forecast_lstm 실행 전: 1647.24 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1648.25 MB (변화: +1.02 MB)
[TRS]   [LSTM] 완료  첫값=2.46e+08 (메모리: 1648.3 MB)
[TRS]   [Theta] 시작  (메모리: 1648.3 MB)
[메모리] forecast_theta 실행 전: 1648.25 MB
[메모리] forecast_theta 실행 후: 1648.25 MB (변화: +0.00 MB)
[TRS]   [Theta] 완료  첫값=1.78e+08 (메모리: 1648.3 MB)
[TRS]   [DB] 88행 저장 완료
[PROGRESS] [ 447/500] ( 89.4%)  >>  RES
[RES]   40분기 | 2016-03-31 ~ 2025-12-31
[RES]   [SARIMA] 시작  (메모리: 1648.3 MB)
[메모리] forecast_sarima 실행 전: 1648.25 MB
[메모리] find_best_sarima_params 실행 전: 1648.25 MB
[메모리] find_best_sarima_params 실행 후: 1648.25 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1648.25 MB (변화: +0.00 MB)
[RES]   [SARIMA] 완료  첫값=4.26e+08 (메모리: 1648.3 MB)
[RES]   [ETS] 시작  (메모리: 1648.3 MB)
[메모리] forecast_ets 실행 전: 1648.25 MB
[메모리] forecast_ets 실행 후: 1648.26 MB (변화: +0.00 MB)
[RES]   [ETS] 완료  첫값=4.47e+08 (메모리: 1648.3 MB)
[RES]   [Prophet] 시작  (메모리: 1648.3 MB)
[메모리] forecast_prophet 실행 전: 1648.26 MB

01:20:35 - cmdstanpy - INFO - Chain [1] start processing
01:20:35 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1648.27 MB (변화: +0.01 MB)
[RES]   [Prophet] 완료  첫값=3.85e+08 (메모리: 1648.3 MB)
[RES]   [LSTM] 시작  (메모리: 1648.3 MB)
[메모리] forecast_lstm 실행 전: 1648.27 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1648.32 MB (변화: +0.05 MB)
[RES]   [LSTM] 완료  첫값=3.19e+08 (메모리: 1648.3 MB)
[RES]   [Theta] 시작  (메모리: 1648.3 MB)
[메모리] forecast_theta 실행 전: 1648.32 MB
[메모리] forecast_theta 실행 후: 1648.32 MB (변화: +0.00 MB)
[RES]   [Theta] 완료  첫값=4.28e+08 (메모리: 1648.3 MB)
[RES]   [DB] 88행 저장 완료
[PROGRESS] [ 448/500] ( 89.6%)  >>  SBET
[SBET] [NEG-SKIP] [SBET] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2019, 6, 30), datetime.date(2020, 12, 31)])
[PROGRESS] [ 449/500] ( 89.8%)  >>  NGL
[NGL]   40분기 | 2016-03-31 ~ 2025-12-31
[NGL]   [SARIMA] 시작  (메모리: 1648.3 MB)
[메모리] forecast_sarima 실행 전: 1648.32 MB
[메모리] find_best_sarima_params 실행 전: 1648.32 MB
[메모리] find_best_sarima_params 실행 후: 1648.32 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1648.32 MB (변화: +0.00 MB)
[NGL]   [SARIMA] 완료  첫값=9.10e+08 (메모리: 1648.3 MB)
[NGL]   [ETS] 시작  (메모리: 1648.3 MB)
[메모리] forecast_ets 실행 전: 1648.32 MB
[메모리] forecast_ets 실행 후: 1648.32 MB (변화: +0.00 MB)
[NGL]   [ETS] 완료  첫값=8.82e+08 (메모리: 1648.3 MB)
[NGL]   [Prophet] 시작  (메모리: 1648.3 MB)

01:20:55 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1648.32 MB

01:20:55 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1648.34 MB (변화: +0.02 MB)
[NGL]   [Prophet] 완료  첫값=6.37e+08 (메모리: 1648.3 MB)
[NGL]   [LSTM] 시작  (메모리: 1648.3 MB)
[메모리] forecast_lstm 실행 전: 1648.34 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1648.34 MB (변화: +0.00 MB)
[NGL]   [LSTM] 완료  첫값=1.38e+09 (메모리: 1648.3 MB)
[NGL]   [Theta] 시작  (메모리: 1648.3 MB)
[메모리] forecast_theta 실행 전: 1648.34 MB
[메모리] forecast_theta 실행 후: 1648.34 MB (변화: +0.00 MB)
[NGL]   [Theta] 완료  첫값=8.99e+08 (메모리: 1648.3 MB)
[NGL]   [DB] 88행 저장 완료
[PROGRESS] [ 450/500] ( 90.0%)  >>  TWO
[TWO] [NEG-SKIP] [TWO] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2016, 3, 31), datetime.date(2020, 3, 31), datetime.date(2020, 6, 30), datetime.date(2021, 3, 31), datetime.date(2022, 3, 31), datetime.date(2022, 12, 31)])
[PROGRESS] [ 451/500] ( 90.2%)  >>  ARI
[ARI]   40분기 | 2016-03-31 ~ 2025-12-31
[ARI]   [SARIMA] 시작  (메모리: 1648.3 MB)
[메모리] forecast_sarima 실행 전: 1648.34 MB
[메모리] find_best_sarima_params 실행 전: 1648.34 MB
[메모리] find_best_sarima_params 실행 후: 1648.34 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1648.34 MB (변화: +0.00 MB)
[ARI]   [SARIMA] 완료  첫값=2.01e+08 (메모리: 1648.3 MB)
[ARI]   [ETS] 시작  (메모리: 1648.3 MB)
[메모리] forecast_ets 실행 전: 1648.34 MB
[메모리] forecast_ets 실행 후: 1648.34 MB (변화: +0.00 MB)
[ARI]   [ETS] 완료  첫값=1.99e+08 (메모리: 1648.3 MB)
[ARI]   [Prophet] 시작  (메모리: 1648.3 MB)

01:21:10 - cmdstanpy - INFO - Chain [1] start processing
01:21:10 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1648.34 MB
[메모리] forecast_prophet 실행 후: 1648.36 MB (변화: +0.01 MB)
[ARI]   [Prophet] 완료  첫값=2.00e+08 (메모리: 1648.4 MB)
[ARI]   [LSTM] 시작  (메모리: 1648.4 MB)
[메모리] forecast_lstm 실행 전: 1648.36 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1648.33 MB (변화: -0.03 MB)
[ARI]   [LSTM] 완료  첫값=2.29e+08 (메모리: 1648.3 MB)
[ARI]   [Theta] 시작  (메모리: 1648.3 MB)
[메모리] forecast_theta 실행 전: 1648.33 MB
[메모리] forecast_theta 실행 후: 1648.33 MB (변화: +0.00 MB)
[ARI]   [Theta] 완료  첫값=1.96e+08 (메모리: 1648.3 MB)
[ARI]   [DB] 88행 저장 완료
[PROGRESS] [ 452/500] ( 90.4%)  >>  NEXT
[NEXT]   40분기 | 2016-03-31 ~ 2025-12-31
[NEXT]   [SARIMA] 시작  (메모리: 1648.3 MB)
[메모리] forecast_sarima 실행 전: 1648.33 MB
[메모리] find_best_sarima_params 실행 전: 1648.33 MB
[메모리] find_best_sarima_params 실행 후: 1648.33 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1648.33 MB (변화: +0.00 MB)
[NEXT]   [SARIMA] 완료  첫값=0.00e+00 (메모리: 1648.3 MB)
[NEXT]   [ETS] 시작  (메모리: 1648.3 MB)
[메모리] forecast_ets 실행 전: 1648.33 MB
[메모리] forecast_ets 실행 후: 1648.33 MB (변화: +0.00 MB)
[NEXT]   [ETS] 완료  첫값=-4.88e+04 (메모리: 1648.3 MB)
[NEXT]   [Prophet] 시작  (메모리: 1648.3 MB)

01:21:22 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1648.33 MB

01:21:22 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1648.35 MB (변화: +0.02 MB)
[NEXT]   [Prophet] 완료  첫값=-2.68e+04 (메모리: 1648.3 MB)
[NEXT]   [LSTM] 시작  (메모리: 1648.3 MB)
[메모리] forecast_lstm 실행 전: 1648.35 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1648.34 MB (변화: -0.01 MB)
[NEXT]   [LSTM] 완료  첫값=1.10e+02 (메모리: 1648.3 MB)
[NEXT]   [Theta] 시작  (메모리: 1648.3 MB)
[메모리] forecast_theta 실행 전: 1648.34 MB
[메모리] forecast_theta 실행 후: 1648.34 MB (변화: +0.00 MB)
[NEXT]   [Theta] 완료  첫값=-5.62e+04 (메모리: 1648.3 MB)
[NEXT]   [DB] 88행 저장 완료
[PROGRESS] [ 453/500] ( 90.6%)  >>  VRE
[VRE]   40분기 | 2016-03-31 ~ 2025-12-31
[VRE]   [SARIMA] 시작  (메모리: 1648.3 MB)
[메모리] forecast_sarima 실행 전: 1648.34 MB
[메모리] find_best_sarima_params 실행 전: 1648.34 MB
[메모리] find_best_sarima_params 실행 후: 1648.34 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1648.34 MB (변화: +0.00 MB)
[VRE]   [SARIMA] 완료  첫값=6.99e+07 (메모리: 1648.3 MB)
[VRE]   [ETS] 시작  (메모리: 1648.3 MB)
[메모리] forecast_ets 실행 전: 1648.34 MB
[메모리] forecast_ets 실행 후: 1648.34 MB (변화: +0.01 MB)
[VRE]   [ETS] 완료  첫값=6.26e+07 (메모리: 1648.3 MB)
[VRE]   [Prophet] 시작  (메모리: 1648.3 MB)
[메모리] forecast_prophet 실행 전: 1648.34 MB

01:21:40 - cmdstanpy - INFO - Chain [1] start processing
01:21:40 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1648.35 MB (변화: +0.00 MB)
[VRE]   [Prophet] 완료  첫값=4.13e+07 (메모리: 1648.3 MB)
[VRE]   [LSTM] 시작  (메모리: 1648.3 MB)
[메모리] forecast_lstm 실행 전: 1648.35 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1648.34 MB (변화: -0.01 MB)
[VRE]   [LSTM] 완료  첫값=6.47e+07 (메모리: 1648.3 MB)
[VRE]   [Theta] 시작  (메모리: 1648.3 MB)
[메모리] forecast_theta 실행 전: 1648.34 MB
[메모리] forecast_theta 실행 후: 1648.34 MB (변화: +0.00 MB)
[VRE]   [Theta] 완료  첫값=6.29e+07 (메모리: 1648.3 MB)
[VRE]   [DB] 88행 저장 완료
[PROGRESS] [ 454/500] ( 90.8%)  >>  NSSC
[NSSC]   40분기 | 2016-03-31 ~ 2025-12-31
[NSSC]   [SARIMA] 시작  (메모리: 1648.3 MB)
[메모리] forecast_sarima 실행 전: 1648.34 MB
[메모리] find_best_sarima_params 실행 전: 1648.34 MB
[메모리] find_best_sarima_params 실행 후: 1648.34 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1648.34 MB (변화: +0.00 MB)
[NSSC]   [SARIMA] 완료  첫값=4.95e+07 (메모리: 1648.3 MB)
[NSSC]   [ETS] 시작  (메모리: 1648.3 MB)
[메모리] forecast_ets 실행 전: 1648.34 MB
[메모리] forecast_ets 실행 후: 1648.34 MB (변화: +0.00 MB)
[NSSC]   [ETS] 완료  첫값=4.96e+07 (메모리: 1648.3 MB)
[NSSC]   [Prophet] 시작  (메모리: 1648.3 MB)

01:21:56 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1648.34 MB

01:21:57 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1648.36 MB (변화: +0.01 MB)
[NSSC]   [Prophet] 완료  첫값=5.07e+07 (메모리: 1648.4 MB)
[NSSC]   [LSTM] 시작  (메모리: 1648.4 MB)
[메모리] forecast_lstm 실행 전: 1648.36 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1648.35 MB (변화: -0.01 MB)
[NSSC]   [LSTM] 완료  첫값=5.10e+07 (메모리: 1648.3 MB)
[NSSC]   [Theta] 시작  (메모리: 1648.3 MB)
[메모리] forecast_theta 실행 전: 1648.35 MB
[메모리] forecast_theta 실행 후: 1648.35 MB (변화: +0.00 MB)
[NSSC]   [Theta] 완료  첫값=4.88e+07 (메모리: 1648.3 MB)
[NSSC]   [DB] 88행 저장 완료
[PROGRESS] [ 455/500] ( 91.0%)  >>  HCSG
[HCSG]   40분기 | 2016-03-31 ~ 2025-12-31
[HCSG]   [SARIMA] 시작  (메모리: 1648.3 MB)
[메모리] forecast_sarima 실행 전: 1648.35 MB
[메모리] find_best_sarima_params 실행 전: 1648.35 MB
[메모리] find_best_sarima_params 실행 후: 1648.35 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1648.35 MB (변화: +0.00 MB)
[HCSG]   [SARIMA] 완료  첫값=4.67e+08 (메모리: 1648.3 MB)
[HCSG]   [ETS] 시작  (메모리: 1648.3 MB)
[메모리] forecast_ets 실행 전: 1648.35 MB
[메모리] forecast_ets 실행 후: 1648.35 MB (변화: +0.00 MB)
[HCSG]   [ETS] 완료  첫값=4.69e+08 (메모리: 1648.4 MB)
[HCSG]   [Prophet] 시작  (메모리: 1648.4 MB)
[메모리] forecast_prophet 실행 전: 1648.35 MB

01:22:16 - cmdstanpy - INFO - Chain [1] start processing
01:22:16 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1648.37 MB (변화: +0.02 MB)
[HCSG]   [Prophet] 완료  첫값=4.34e+08 (메모리: 1648.4 MB)
[HCSG]   [LSTM] 시작  (메모리: 1648.4 MB)
[메모리] forecast_lstm 실행 전: 1648.37 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1648.38 MB (변화: +0.01 MB)
[HCSG]   [LSTM] 완료  첫값=4.37e+08 (메모리: 1648.4 MB)
[HCSG]   [Theta] 시작  (메모리: 1648.4 MB)
[메모리] forecast_theta 실행 전: 1648.38 MB
[메모리] forecast_theta 실행 후: 1648.38 MB (변화: +0.00 MB)
[HCSG]   [Theta] 완료  첫값=4.67e+08 (메모리: 1648.4 MB)
[HCSG]   [DB] 88행 저장 완료
[PROGRESS] [ 456/500] ( 91.2%)  >>  ACHC
[ACHC]   40분기 | 2016-03-31 ~ 2025-12-31
[ACHC]   [SARIMA] 시작  (메모리: 1648.4 MB)
[메모리] forecast_sarima 실행 전: 1648.38 MB
[메모리] find_best_sarima_params 실행 전: 1648.38 MB
[메모리] find_best_sarima_params 실행 후: 1648.38 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1648.38 MB (변화: +0.00 MB)
[ACHC]   [SARIMA] 완료  첫값=8.21e+08 (메모리: 1648.4 MB)
[ACHC]   [ETS] 시작  (메모리: 1648.4 MB)
[메모리] forecast_ets 실행 전: 1648.38 MB
[메모리] forecast_ets 실행 후: 1648.38 MB (변화: +0.00 MB)
[ACHC]   [ETS] 완료  첫값=7.96e+08 (메모리: 1648.4 MB)
[ACHC]   [Prophet] 시작  (메모리: 1648.4 MB)

01:22:37 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1648.38 MB

01:22:37 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1648.40 MB (변화: +0.02 MB)
[ACHC]   [Prophet] 완료  첫값=7.46e+08 (메모리: 1648.4 MB)
[ACHC]   [LSTM] 시작  (메모리: 1648.4 MB)
[메모리] forecast_lstm 실행 전: 1648.40 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1648.41 MB (변화: +0.01 MB)
[ACHC]   [LSTM] 완료  첫값=7.36e+08 (메모리: 1648.4 MB)
[ACHC]   [Theta] 시작  (메모리: 1648.4 MB)
[메모리] forecast_theta 실행 전: 1648.41 MB
[메모리] forecast_theta 실행 후: 1648.41 MB (변화: +0.00 MB)
[ACHC]   [Theta] 완료  첫값=8.23e+08 (메모리: 1648.4 MB)
[ACHC]   [DB] 88행 저장 완료
[PROGRESS] [ 457/500] ( 91.4%)  >>  UVV
[UVV]   40분기 | 2016-03-31 ~ 2025-12-31
[UVV]   [SARIMA] 시작  (메모리: 1648.4 MB)
[메모리] forecast_sarima 실행 전: 1648.41 MB
[메모리] find_best_sarima_params 실행 전: 1648.41 MB
[메모리] find_best_sarima_params 실행 후: 1648.41 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1648.41 MB (변화: +0.00 MB)
[UVV]   [SARIMA] 완료  첫값=8.93e+08 (메모리: 1648.4 MB)
[UVV]   [ETS] 시작  (메모리: 1648.4 MB)
[메모리] forecast_ets 실행 전: 1648.41 MB
[메모리] forecast_ets 실행 후: 1648.42 MB (변화: +0.00 MB)
[UVV]   [ETS] 완료  첫값=7.55e+08 (메모리: 1648.4 MB)
[UVV]   [Prophet] 시작  (메모리: 1648.4 MB)

01:22:57 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1648.42 MB

01:22:57 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1648.42 MB (변화: +0.00 MB)
[UVV]   [Prophet] 완료  첫값=7.27e+08 (메모리: 1648.4 MB)
[UVV]   [LSTM] 시작  (메모리: 1648.4 MB)
[메모리] forecast_lstm 실행 전: 1648.42 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1648.41 MB (변화: -0.01 MB)
[UVV]   [LSTM] 완료  첫값=7.22e+08 (메모리: 1648.4 MB)
[UVV]   [Theta] 시작  (메모리: 1648.4 MB)
[메모리] forecast_theta 실행 전: 1648.41 MB
[메모리] forecast_theta 실행 후: 1648.41 MB (변화: +0.00 MB)
[UVV]   [Theta] 완료  첫값=8.75e+08 (메모리: 1648.4 MB)
[UVV]   [DB] 88행 저장 완료
[PROGRESS] [ 458/500] ( 91.6%)  >>  TNDM
[TNDM]   40분기 | 2016-03-31 ~ 2025-12-31
[TNDM]   [SARIMA] 시작  (메모리: 1648.4 MB)
[메모리] forecast_sarima 실행 전: 1648.41 MB
[메모리] find_best_sarima_params 실행 전: 1648.41 MB
[메모리] find_best_sarima_params 실행 후: 1647.38 MB (변화: -1.03 MB)
[메모리] forecast_sarima 실행 후: 1647.38 MB (변화: -1.03 MB)
[TNDM]   [SARIMA] 완료  첫값=2.76e+08 (메모리: 1647.4 MB)
[TNDM]   [ETS] 시작  (메모리: 1647.4 MB)
[메모리] forecast_ets 실행 전: 1647.38 MB
[메모리] forecast_ets 실행 후: 1647.38 MB (변화: +0.00 MB)
[TNDM]   [ETS] 완료  첫값=2.62e+08 (메모리: 1647.4 MB)
[TNDM]   [Prophet] 시작  (메모리: 1647.4 MB)

01:23:13 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1647.38 MB

01:23:13 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1647.38 MB (변화: +0.00 MB)
[TNDM]   [Prophet] 완료  첫값=2.91e+08 (메모리: 1647.4 MB)
[TNDM]   [LSTM] 시작  (메모리: 1647.4 MB)
[메모리] forecast_lstm 실행 전: 1647.38 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1647.35 MB (변화: -0.03 MB)
[TNDM]   [LSTM] 완료  첫값=2.48e+08 (메모리: 1647.4 MB)
[TNDM]   [Theta] 시작  (메모리: 1647.4 MB)
[메모리] forecast_theta 실행 전: 1647.35 MB
[메모리] forecast_theta 실행 후: 1647.35 MB (변화: +0.00 MB)
[TNDM]   [Theta] 완료  첫값=2.26e+08 (메모리: 1647.4 MB)
[TNDM]   [DB] 88행 저장 완료
[PROGRESS] [ 459/500] ( 91.8%)  >>  GRC
[GRC]   40분기 | 2016-03-31 ~ 2025-12-31
[GRC]   [SARIMA] 시작  (메모리: 1647.4 MB)
[메모리] forecast_sarima 실행 전: 1647.35 MB
[메모리] find_best_sarima_params 실행 전: 1647.35 MB
[메모리] find_best_sarima_params 실행 후: 1647.35 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1647.35 MB (변화: +0.00 MB)
[GRC]   [SARIMA] 완료  첫값=1.69e+08 (메모리: 1647.4 MB)
[GRC]   [ETS] 시작  (메모리: 1647.4 MB)
[메모리] forecast_ets 실행 전: 1647.35 MB
[메모리] forecast_ets 실행 후: 1647.36 MB (변화: +0.00 MB)
[GRC]   [ETS] 완료  첫값=1.70e+08 (메모리: 1647.4 MB)
[GRC]   [Prophet] 시작  (메모리: 1647.4 MB)

01:23:30 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1647.36 MB

01:23:30 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1647.37 MB (변화: +0.02 MB)
[GRC]   [Prophet] 완료  첫값=1.69e+08 (메모리: 1647.4 MB)
[GRC]   [LSTM] 시작  (메모리: 1647.4 MB)
[메모리] forecast_lstm 실행 전: 1647.37 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1647.35 MB (변화: -0.02 MB)
[GRC]   [LSTM] 완료  첫값=1.69e+08 (메모리: 1647.4 MB)
[GRC]   [Theta] 시작  (메모리: 1647.4 MB)
[메모리] forecast_theta 실행 전: 1647.35 MB
[메모리] forecast_theta 실행 후: 1647.35 MB (변화: +0.00 MB)
[GRC]   [Theta] 완료  첫값=1.68e+08 (메모리: 1647.4 MB)
[GRC]   [DB] 88행 저장 완료
[PROGRESS] [ 460/500] ( 92.0%)  >>  ASTH
[ASTH] [SKIP] [ASTH] 'sale' 관측치 부족: 19개 < 최소 28개
[PROGRESS] [ 461/500] ( 92.2%)  >>  NNE
[NNE] [SKIP] [NNE] 'sale' 관측치 부족: 14개 < 최소 28개
[PROGRESS] [ 462/500] ( 92.4%)  >>  DHC
[DHC]   40분기 | 2016-03-31 ~ 2025-12-31
[DHC]   [SARIMA] 시작  (메모리: 1647.4 MB)
[메모리] forecast_sarima 실행 전: 1647.35 MB
[메모리] find_best_sarima_params 실행 전: 1647.35 MB
[메모리] find_best_sarima_params 실행 후: 1647.35 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1647.35 MB (변화: +0.00 MB)
[DHC]   [SARIMA] 완료  첫값=3.83e+08 (메모리: 1647.4 MB)
[DHC]   [ETS] 시작  (메모리: 1647.4 MB)
[메모리] forecast_ets 실행 전: 1647.35 MB
[메모리] forecast_ets 실행 후: 1647.36 MB (변화: +0.00 MB)
[DHC]   [ETS] 완료  첫값=3.97e+08 (메모리: 1647.4 MB)
[DHC]   [Prophet] 시작  (메모리: 1647.4 MB)

01:23:52 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1647.36 MB

01:23:53 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1647.72 MB (변화: +0.37 MB)
[DHC]   [Prophet] 완료  첫값=3.96e+08 (메모리: 1647.7 MB)
[DHC]   [LSTM] 시작  (메모리: 1647.7 MB)
[메모리] forecast_lstm 실행 전: 1647.72 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1647.72 MB (변화: +0.00 MB)
[DHC]   [LSTM] 완료  첫값=3.65e+08 (메모리: 1647.7 MB)
[DHC]   [Theta] 시작  (메모리: 1647.7 MB)
[메모리] forecast_theta 실행 전: 1647.72 MB
[메모리] forecast_theta 실행 후: 1647.72 MB (변화: +0.00 MB)
[DHC]   [Theta] 완료  첫값=3.83e+08 (메모리: 1647.7 MB)
[DHC]   [DB] 88행 저장 완료
[PROGRESS] [ 463/500] ( 92.6%)  >>  CRAI
[CRAI]   40분기 | 2016-04-02 ~ 2026-01-03
[CRAI]   [SARIMA] 시작  (메모리: 1647.7 MB)
[메모리] forecast_sarima 실행 전: 1647.72 MB
[메모리] find_best_sarima_params 실행 전: 1647.72 MB
[메모리] find_best_sarima_params 실행 후: 1647.72 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1647.72 MB (변화: +0.00 MB)
[CRAI]   [SARIMA] 완료  첫값=1.99e+08 (메모리: 1647.7 MB)
[CRAI]   [ETS] 시작  (메모리: 1647.7 MB)
[메모리] forecast_ets 실행 전: 1647.72 MB
[메모리] forecast_ets 실행 후: 1647.73 MB (변화: +0.00 MB)
[CRAI]   [ETS] 완료  첫값=2.04e+08 (메모리: 1647.7 MB)
[CRAI]   [Prophet] 시작  (메모리: 1647.7 MB)
[메모리] forecast_prophet 실행 전: 1647.73 MB

01:24:10 - cmdstanpy - INFO - Chain [1] start processing
01:24:10 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1647.74 MB (변화: +0.02 MB)
[CRAI]   [Prophet] 완료  첫값=1.89e+08 (메모리: 1647.7 MB)
[CRAI]   [LSTM] 시작  (메모리: 1647.7 MB)
[메모리] forecast_lstm 실행 전: 1647.74 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1647.71 MB (변화: -0.03 MB)
[CRAI]   [LSTM] 완료  첫값=1.89e+08 (메모리: 1647.7 MB)
[CRAI]   [Theta] 시작  (메모리: 1647.7 MB)
[메모리] forecast_theta 실행 전: 1647.71 MB
[메모리] forecast_theta 실행 후: 1647.71 MB (변화: +0.00 MB)
[CRAI]   [Theta] 완료  첫값=2.05e+08 (메모리: 1647.7 MB)
[CRAI]   [DB] 88행 저장 완료
[PROGRESS] [ 464/500] ( 92.8%)  >>  UMH
[UMH]   40분기 | 2016-03-31 ~ 2025-12-31
[UMH]   [SARIMA] 시작  (메모리: 1647.7 MB)
[메모리] forecast_sarima 실행 전: 1647.71 MB
[메모리] find_best_sarima_params 실행 전: 1647.71 MB
[메모리] find_best_sarima_params 실행 후: 1647.71 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1647.71 MB (변화: +0.00 MB)
[UMH]   [SARIMA] 완료  첫값=6.78e+07 (메모리: 1647.7 MB)
[UMH]   [ETS] 시작  (메모리: 1647.7 MB)
[메모리] forecast_ets 실행 전: 1647.71 MB
[메모리] forecast_ets 실행 후: 1647.71 MB (변화: +0.00 MB)
[UMH]   [ETS] 완료  첫값=6.82e+07 (메모리: 1647.7 MB)
[UMH]   [Prophet] 시작  (메모리: 1647.7 MB)

01:24:29 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1647.71 MB

01:24:29 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1647.73 MB (변화: +0.02 MB)
[UMH]   [Prophet] 완료  첫값=6.83e+07 (메모리: 1647.7 MB)
[UMH]   [LSTM] 시작  (메모리: 1647.7 MB)
[메모리] forecast_lstm 실행 전: 1647.73 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1647.74 MB (변화: +0.00 MB)
[UMH]   [LSTM] 완료  첫값=6.67e+07 (메모리: 1647.7 MB)
[UMH]   [Theta] 시작  (메모리: 1647.7 MB)
[메모리] forecast_theta 실행 전: 1647.74 MB
[메모리] forecast_theta 실행 후: 1647.74 MB (변화: +0.00 MB)
[UMH]   [Theta] 완료  첫값=6.73e+07 (메모리: 1647.7 MB)
[UMH]   [DB] 88행 저장 완료
[PROGRESS] [ 465/500] ( 93.0%)  >>  IRS
[IRS] [NEG-SKIP] [IRS] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2018, 6, 30), datetime.date(2021, 6, 30)])
[PROGRESS] [ 466/500] ( 93.2%)  >>  KW
[KW]   40분기 | 2016-03-31 ~ 2025-12-31
[KW]   [SARIMA] 시작  (메모리: 1647.7 MB)
[메모리] forecast_sarima 실행 전: 1647.74 MB
[메모리] find_best_sarima_params 실행 전: 1647.74 MB
[메모리] find_best_sarima_params 실행 후: 1647.74 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1647.74 MB (변화: +0.00 MB)
[KW]   [SARIMA] 완료  첫값=1.18e+08 (메모리: 1647.7 MB)
[KW]   [ETS] 시작  (메모리: 1647.7 MB)
[메모리] forecast_ets 실행 전: 1647.74 MB
[메모리] forecast_ets 실행 후: 1647.74 MB (변화: +0.00 MB)
[KW]   [ETS] 완료  첫값=1.12e+08 (메모리: 1647.7 MB)
[KW]   [Prophet] 시작  (메모리: 1647.7 MB)
[메모리] forecast_prophet 실행 전: 1647.74 MB

01:24:47 - cmdstanpy - INFO - Chain [1] start processing
01:24:47 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1648.01 MB (변화: +0.27 MB)
[KW]   [Prophet] 완료  첫값=1.10e+08 (메모리: 1648.0 MB)
[KW]   [LSTM] 시작  (메모리: 1648.0 MB)
[메모리] forecast_lstm 실행 전: 1648.01 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1647.99 MB (변화: -0.02 MB)
[KW]   [LSTM] 완료  첫값=1.27e+08 (메모리: 1648.0 MB)
[KW]   [Theta] 시작  (메모리: 1648.0 MB)
[메모리] forecast_theta 실행 전: 1647.99 MB
[메모리] forecast_theta 실행 후: 1647.99 MB (변화: +0.00 MB)
[KW]   [Theta] 완료  첫값=1.12e+08 (메모리: 1648.0 MB)
[KW]   [DB] 88행 저장 완료
[PROGRESS] [ 467/500] ( 93.4%)  >>  COHU
[COHU]   40분기 | 2016-03-26 ~ 2025-12-27
[COHU]   [SARIMA] 시작  (메모리: 1648.0 MB)
[메모리] forecast_sarima 실행 전: 1647.99 MB
[메모리] find_best_sarima_params 실행 전: 1647.99 MB
[메모리] find_best_sarima_params 실행 후: 1647.99 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1647.99 MB (변화: +0.00 MB)
[COHU]   [SARIMA] 완료  첫값=1.22e+08 (메모리: 1648.0 MB)
[COHU]   [ETS] 시작  (메모리: 1648.0 MB)
[메모리] forecast_ets 실행 전: 1647.99 MB
[메모리] forecast_ets 실행 후: 1647.99 MB (변화: +0.00 MB)
[COHU]   [ETS] 완료  첫값=1.22e+08 (메모리: 1648.0 MB)
[COHU]   [Prophet] 시작  (메모리: 1648.0 MB)

01:25:07 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1647.99 MB

01:25:07 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1648.01 MB (변화: +0.02 MB)
[COHU]   [Prophet] 완료  첫값=1.65e+08 (메모리: 1648.0 MB)
[COHU]   [LSTM] 시작  (메모리: 1648.0 MB)
[메모리] forecast_lstm 실행 전: 1648.01 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1648.09 MB (변화: +0.08 MB)
[COHU]   [LSTM] 완료  첫값=1.38e+08 (메모리: 1648.1 MB)
[COHU]   [Theta] 시작  (메모리: 1648.1 MB)
[메모리] forecast_theta 실행 전: 1648.09 MB
[메모리] forecast_theta 실행 후: 1648.09 MB (변화: +0.00 MB)
[COHU]   [Theta] 완료  첫값=1.21e+08 (메모리: 1648.1 MB)
[COHU]   [DB] 88행 저장 완료
[PROGRESS] [ 468/500] ( 93.6%)  >>  MLKN
[MLKN]   40분기 | 2016-05-31 ~ 2026-02-28
[MLKN]   [SARIMA] 시작  (메모리: 1648.1 MB)
[메모리] forecast_sarima 실행 전: 1648.09 MB
[메모리] find_best_sarima_params 실행 전: 1648.09 MB
[메모리] find_best_sarima_params 실행 후: 1648.09 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1648.09 MB (변화: +0.00 MB)
[MLKN]   [SARIMA] 완료  첫값=9.38e+08 (메모리: 1648.1 MB)
[MLKN]   [ETS] 시작  (메모리: 1648.1 MB)
[메모리] forecast_ets 실행 전: 1648.09 MB
[메모리] forecast_ets 실행 후: 1648.09 MB (변화: +0.00 MB)
[MLKN]   [ETS] 완료  첫값=9.36e+08 (메모리: 1648.1 MB)
[MLKN]   [Prophet] 시작  (메모리: 1648.1 MB)

01:25:28 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1648.09 MB

01:25:28 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1648.09 MB (변화: +0.00 MB)
[MLKN]   [Prophet] 완료  첫값=1.03e+09 (메모리: 1648.1 MB)
[MLKN]   [LSTM] 시작  (메모리: 1648.1 MB)
[메모리] forecast_lstm 실행 전: 1648.09 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1648.20 MB (변화: +0.11 MB)
[MLKN]   [LSTM] 완료  첫값=9.33e+08 (메모리: 1648.2 MB)
[MLKN]   [Theta] 시작  (메모리: 1648.2 MB)
[메모리] forecast_theta 실행 전: 1648.20 MB
[메모리] forecast_theta 실행 후: 1648.20 MB (변화: +0.00 MB)
[MLKN]   [Theta] 완료  첫값=9.30e+08 (메모리: 1648.2 MB)
[MLKN]   [DB] 88행 저장 완료
[PROGRESS] [ 469/500] ( 93.8%)  >>  DSGR
[DSGR]   40분기 | 2016-03-31 ~ 2025-12-31
[DSGR]   [SARIMA] 시작  (메모리: 1648.2 MB)
[메모리] forecast_sarima 실행 전: 1648.20 MB
[메모리] find_best_sarima_params 실행 전: 1648.20 MB
[메모리] find_best_sarima_params 실행 후: 1648.20 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1648.20 MB (변화: +0.00 MB)
[DSGR]   [SARIMA] 완료  첫값=5.07e+08 (메모리: 1648.2 MB)
[DSGR]   [ETS] 시작  (메모리: 1648.2 MB)
[메모리] forecast_ets 실행 전: 1648.20 MB
[메모리] forecast_ets 실행 후: 1648.20 MB (변화: +0.00 MB)
[DSGR]   [ETS] 완료  첫값=5.10e+08 (메모리: 1648.2 MB)
[DSGR]   [Prophet] 시작  (메모리: 1648.2 MB)
[메모리] forecast_prophet 실행 전: 1648.20 MB

01:25:48 - cmdstanpy - INFO - Chain [1] start processing
01:25:48 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1648.61 MB (변화: +0.41 MB)
[DSGR]   [Prophet] 완료  첫값=4.79e+08 (메모리: 1648.6 MB)
[DSGR]   [LSTM] 시작  (메모리: 1648.6 MB)
[메모리] forecast_lstm 실행 전: 1648.61 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1647.88 MB (변화: -0.73 MB)
[DSGR]   [LSTM] 완료  첫값=5.79e+08 (메모리: 1647.9 MB)
[DSGR]   [Theta] 시작  (메모리: 1647.9 MB)
[메모리] forecast_theta 실행 전: 1647.88 MB
[메모리] forecast_theta 실행 후: 1647.88 MB (변화: +0.00 MB)
[DSGR]   [Theta] 완료  첫값=4.98e+08 (메모리: 1647.9 MB)
[DSGR]   [DB] 88행 저장 완료
[PROGRESS] [ 470/500] ( 94.0%)  >>  PDFS
[PDFS]   40분기 | 2016-03-31 ~ 2025-12-31
[PDFS]   [SARIMA] 시작  (메모리: 1647.9 MB)
[메모리] forecast_sarima 실행 전: 1647.88 MB
[메모리] find_best_sarima_params 실행 전: 1647.88 MB
[메모리] find_best_sarima_params 실행 후: 1647.88 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1647.88 MB (변화: +0.00 MB)
[PDFS]   [SARIMA] 완료  첫값=6.40e+07 (메모리: 1647.9 MB)
[PDFS]   [ETS] 시작  (메모리: 1647.9 MB)
[메모리] forecast_ets 실행 전: 1647.88 MB
[메모리] forecast_ets 실행 후: 1647.88 MB (변화: +0.00 MB)
[PDFS]   [ETS] 완료  첫값=6.35e+07 (메모리: 1647.9 MB)
[PDFS]   [Prophet] 시작  (메모리: 1647.9 MB)
[메모리] forecast_prophet 실행 전: 1647.88 MB

01:26:10 - cmdstanpy - INFO - Chain [1] start processing
01:26:10 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1647.89 MB (변화: +0.01 MB)
[PDFS]   [Prophet] 완료  첫값=5.71e+07 (메모리: 1647.9 MB)
[PDFS]   [LSTM] 시작  (메모리: 1647.9 MB)
[메모리] forecast_lstm 실행 전: 1647.89 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1648.85 MB (변화: +0.96 MB)
[PDFS]   [LSTM] 완료  첫값=6.20e+07 (메모리: 1648.8 MB)
[PDFS]   [Theta] 시작  (메모리: 1648.8 MB)
[메모리] forecast_theta 실행 전: 1648.85 MB
[메모리] forecast_theta 실행 후: 1648.85 MB (변화: +0.00 MB)
[PDFS]   [Theta] 완료  첫값=6.11e+07 (메모리: 1648.8 MB)
[PDFS]   [DB] 88행 저장 완료
[PROGRESS] [ 471/500] ( 94.2%)  >>  MGIC
[MGIC]   40분기 | 2015-12-31 ~ 2025-09-30
[MGIC]   [SARIMA] 시작  (메모리: 1648.8 MB)
[메모리] forecast_sarima 실행 전: 1648.85 MB
[메모리] find_best_sarima_params 실행 전: 1648.85 MB
[메모리] find_best_sarima_params 실행 후: 1648.85 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1648.85 MB (변화: +0.00 MB)
[MGIC]   [SARIMA] 완료  첫값=1.69e+08 (메모리: 1648.8 MB)
[MGIC]   [ETS] 시작  (메모리: 1648.8 MB)
[메모리] forecast_ets 실행 전: 1648.85 MB
[메모리] forecast_ets 실행 후: 1648.85 MB (변화: +0.00 MB)
[MGIC]   [ETS] 완료  첫값=1.66e+08 (메모리: 1648.9 MB)
[MGIC]   [Prophet] 시작  (메모리: 1648.9 MB)

01:26:32 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1648.85 MB

01:26:32 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1648.85 MB (변화: +0.00 MB)
[MGIC]   [Prophet] 완료  첫값=1.64e+08 (메모리: 1648.9 MB)
[MGIC]   [LSTM] 시작  (메모리: 1648.9 MB)
[메모리] forecast_lstm 실행 전: 1648.85 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1648.85 MB (변화: +0.00 MB)
[MGIC]   [LSTM] 완료  첫값=1.43e+08 (메모리: 1648.9 MB)
[MGIC]   [Theta] 시작  (메모리: 1648.9 MB)
[메모리] forecast_theta 실행 전: 1648.85 MB
[메모리] forecast_theta 실행 후: 1648.85 MB (변화: +0.00 MB)
[MGIC]   [Theta] 완료  첫값=1.64e+08 (메모리: 1648.9 MB)
[MGIC]   [DB] 88행 저장 완료
[PROGRESS] [ 472/500] ( 94.4%)  >>  LAC
[LAC] [NEG-SKIP] [LAC] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2019, 12, 31)])
[PROGRESS] [ 473/500] ( 94.6%)  >>  SYX
[SYX] [NEG-SKIP] [SYX] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2015, 12, 31)])
[PROGRESS] [ 474/500] ( 94.8%)  >>  NAK
[NAK]   40분기 | 2016-03-31 ~ 2025-12-31
[NAK]   [SARIMA] 시작  (메모리: 1648.9 MB)
[메모리] forecast_sarima 실행 전: 1648.85 MB
[메모리] find_best_sarima_params 실행 전: 1648.85 MB
[메모리] find_best_sarima_params 실행 후: 1648.85 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1648.85 MB (변화: +0.00 MB)
[NAK]   [SARIMA] 완료  첫값=0.00e+00 (메모리: 1648.9 MB)
[NAK]   [ETS] 시작  (메모리: 1648.9 MB)
[메모리] forecast_ets 실행 전: 1648.85 MB
[메모리] forecast_ets 실행 후: 1648.86 MB (변화: +0.00 MB)
[NAK]   [ETS] 완료  첫값=0.00e+00 (메모리: 1648.9 MB)
[NAK]   [Prophet] 시작  (메모리: 1648.9 MB)
[메모리] forecast_prophet 실행 전: 1648.86 MB
[메모리] forecast_prophet 실행 후: 1648.86 MB (변화: +0.01 MB)
[NAK]   [Prophet] 완료  첫값=0.00e+00 (메모리: 1648.9 MB)
[NAK]   [LSTM] 시작  (메모리: 1648.9 MB)
[메모리] forecast_lstm 실행 전: 1648.86 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1648.85 MB (변화: -0.02 MB)
[NAK]   [LSTM] 완료  첫값=0.00e+00 (메모리: 1648.8 MB)
[NAK]   [Theta] 시작  (메모리: 1648.8 MB)
[메모리] forecast_theta 실행 전: 1648.85 MB
[메모리] forecast_theta 실행 후: 1648.85 MB (변화: +0.00 MB)
[NAK]   [Theta] 완료  첫값=0.00e+00 (메모리: 1648.8 MB)
[NAK]   [DB] 88행 저장 완료
[PROGRESS] [ 475/500] ( 95.0%)  >>  RLGY
[RLGY]   40분기 | 2014-03-31 ~ 2025-09-30
[RLGY]   [SARIMA] 시작  (메모리: 1648.8 MB)
[메모리] forecast_sarima 실행 전: 1648.85 MB
[메모리] find_best_sarima_params 실행 전: 1648.85 MB
[메모리] find_best_sarima_params 실행 후: 1648.85 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1648.85 MB (변화: +0.00 MB)
[RLGY]   [SARIMA] 완료  첫값=1.52e+09 (메모리: 1648.8 MB)
[RLGY]   [ETS] 시작  (메모리: 1648.8 MB)
[메모리] forecast_ets 실행 전: 1648.85 MB
[메모리] forecast_ets 실행 후: 1648.85 MB (변화: +0.00 MB)
[RLGY]   [ETS] 완료  첫값=1.28e+09 (메모리: 1648.8 MB)
[RLGY]   [Prophet] 시작  (메모리: 1648.8 MB)

01:27:08 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1648.85 MB

01:27:09 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1648.87 MB (변화: +0.02 MB)
[RLGY]   [Prophet] 완료  첫값=1.73e+09 (메모리: 1648.9 MB)
[RLGY]   [LSTM] 시작  (메모리: 1648.9 MB)
[메모리] forecast_lstm 실행 전: 1648.87 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1648.84 MB (변화: -0.03 MB)
[RLGY]   [LSTM] 완료  첫값=1.87e+09 (메모리: 1648.8 MB)
[RLGY]   [Theta] 시작  (메모리: 1648.8 MB)
[메모리] forecast_theta 실행 전: 1648.84 MB
[메모리] forecast_theta 실행 후: 1648.84 MB (변화: +0.00 MB)
[RLGY]   [Theta] 완료  첫값=1.30e+09 (메모리: 1648.8 MB)
[RLGY]   [DB] 88행 저장 완료
[PROGRESS] [ 476/500] ( 95.2%)  >>  PRG
[PRG]   40분기 | 2016-03-31 ~ 2025-12-31
[PRG]   [SARIMA] 시작  (메모리: 1648.8 MB)
[메모리] forecast_sarima 실행 전: 1648.84 MB
[메모리] find_best_sarima_params 실행 전: 1648.84 MB
[메모리] find_best_sarima_params 실행 후: 1648.84 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1648.84 MB (변화: +0.00 MB)
[PRG]   [SARIMA] 완료  첫값=5.69e+08 (메모리: 1648.8 MB)
[PRG]   [ETS] 시작  (메모리: 1648.8 MB)
[메모리] forecast_ets 실행 전: 1648.84 MB
[메모리] forecast_ets 실행 후: 1648.84 MB (변화: +0.00 MB)
[PRG]   [ETS] 완료  첫값=5.93e+08 (메모리: 1648.8 MB)
[PRG]   [Prophet] 시작  (메모리: 1648.8 MB)

01:27:25 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1648.84 MB

01:27:25 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1648.85 MB (변화: +0.01 MB)
[PRG]   [Prophet] 완료  첫값=5.49e+08 (메모리: 1648.9 MB)
[PRG]   [LSTM] 시작  (메모리: 1648.9 MB)
[메모리] forecast_lstm 실행 전: 1648.85 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1648.89 MB (변화: +0.04 MB)
[PRG]   [LSTM] 완료  첫값=6.15e+08 (메모리: 1648.9 MB)
[PRG]   [Theta] 시작  (메모리: 1648.9 MB)
[메모리] forecast_theta 실행 전: 1648.89 MB
[메모리] forecast_theta 실행 후: 1648.89 MB (변화: +0.00 MB)
[PRG]   [Theta] 완료  첫값=5.94e+08 (메모리: 1648.9 MB)
[PRG]   [DB] 88행 저장 완료
[PROGRESS] [ 477/500] ( 95.4%)  >>  LNN
[LNN]   40분기 | 2016-05-31 ~ 2026-02-28
[LNN]   [SARIMA] 시작  (메모리: 1648.9 MB)
[메모리] forecast_sarima 실행 전: 1648.89 MB
[메모리] find_best_sarima_params 실행 전: 1648.89 MB
[메모리] find_best_sarima_params 실행 후: 1648.89 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1648.89 MB (변화: +0.00 MB)
[LNN]   [SARIMA] 완료  첫값=1.57e+08 (메모리: 1648.9 MB)
[LNN]   [ETS] 시작  (메모리: 1648.9 MB)
[메모리] forecast_ets 실행 전: 1648.89 MB
[메모리] forecast_ets 실행 후: 1648.90 MB (변화: +0.00 MB)
[LNN]   [ETS] 완료  첫값=1.59e+08 (메모리: 1648.9 MB)
[LNN]   [Prophet] 시작  (메모리: 1648.9 MB)

01:27:45 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1648.90 MB

01:27:46 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1648.91 MB (변화: +0.02 MB)
[LNN]   [Prophet] 완료  첫값=1.74e+08 (메모리: 1648.9 MB)
[LNN]   [LSTM] 시작  (메모리: 1648.9 MB)
[메모리] forecast_lstm 실행 전: 1648.91 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1648.90 MB (변화: -0.01 MB)
[LNN]   [LSTM] 완료  첫값=1.58e+08 (메모리: 1648.9 MB)
[LNN]   [Theta] 시작  (메모리: 1648.9 MB)
[메모리] forecast_theta 실행 전: 1648.90 MB
[메모리] forecast_theta 실행 후: 1648.90 MB (변화: +0.00 MB)
[LNN]   [Theta] 완료  첫값=1.71e+08 (메모리: 1648.9 MB)
[LNN]   [DB] 88행 저장 완료
[PROGRESS] [ 478/500] ( 95.6%)  >>  EFC
[EFC] [NEG-SKIP] [EFC] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2016, 3, 31), datetime.date(2020, 3, 31), datetime.date(2022, 6, 30)])
[PROGRESS] [ 479/500] ( 95.8%)  >>  WGO
[WGO]   40분기 | 2016-05-28 ~ 2026-02-28
[WGO]   [SARIMA] 시작  (메모리: 1648.9 MB)
[메모리] forecast_sarima 실행 전: 1648.90 MB
[메모리] find_best_sarima_params 실행 전: 1648.90 MB
[메모리] find_best_sarima_params 실행 후: 1648.90 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1648.90 MB (변화: +0.00 MB)
[WGO]   [SARIMA] 완료  첫값=6.95e+08 (메모리: 1648.9 MB)
[WGO]   [ETS] 시작  (메모리: 1648.9 MB)
[메모리] forecast_ets 실행 전: 1648.90 MB
[메모리] forecast_ets 실행 후: 1648.91 MB (변화: +0.00 MB)
[WGO]   [ETS] 완료  첫값=7.43e+08 (메모리: 1648.9 MB)
[WGO]   [Prophet] 시작  (메모리: 1648.9 MB)

01:28:02 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1648.91 MB

01:28:03 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1648.91 MB (변화: +0.00 MB)
[WGO]   [Prophet] 완료  첫값=9.55e+08 (메모리: 1648.9 MB)
[WGO]   [LSTM] 시작  (메모리: 1648.9 MB)
[메모리] forecast_lstm 실행 전: 1648.91 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1648.90 MB (변화: -0.01 MB)
[WGO]   [LSTM] 완료  첫값=7.93e+08 (메모리: 1648.9 MB)
[WGO]   [Theta] 시작  (메모리: 1648.9 MB)
[메모리] forecast_theta 실행 전: 1648.90 MB
[메모리] forecast_theta 실행 후: 1648.90 MB (변화: +0.00 MB)
[WGO]   [Theta] 완료  첫값=7.23e+08 (메모리: 1648.9 MB)
[WGO]   [DB] 88행 저장 완료
[PROGRESS] [ 480/500] ( 96.0%)  >>  HSKA
[HSKA]   40분기 | 2013-06-30 ~ 2023-03-31
[HSKA]   [SARIMA] 시작  (메모리: 1648.9 MB)
[메모리] forecast_sarima 실행 전: 1648.90 MB
[메모리] find_best_sarima_params 실행 전: 1648.90 MB
[메모리] find_best_sarima_params 실행 후: 1648.90 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1648.90 MB (변화: +0.00 MB)
[HSKA]   [SARIMA] 완료  첫값=6.70e+07 (메모리: 1648.9 MB)
[HSKA]   [ETS] 시작  (메모리: 1648.9 MB)
[메모리] forecast_ets 실행 전: 1648.90 MB
[메모리] forecast_ets 실행 후: 1648.90 MB (변화: +0.00 MB)
[HSKA]   [ETS] 완료  첫값=6.73e+07 (메모리: 1648.9 MB)
[HSKA]   [Prophet] 시작  (메모리: 1648.9 MB)

01:28:24 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1648.90 MB

01:28:24 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1648.90 MB (변화: +0.00 MB)
[HSKA]   [Prophet] 완료  첫값=6.40e+07 (메모리: 1648.9 MB)
[HSKA]   [LSTM] 시작  (메모리: 1648.9 MB)
[메모리] forecast_lstm 실행 전: 1648.90 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1648.86 MB (변화: -0.04 MB)
[HSKA]   [LSTM] 완료  첫값=8.20e+07 (메모리: 1648.9 MB)
[HSKA]   [Theta] 시작  (메모리: 1648.9 MB)
[메모리] forecast_theta 실행 전: 1648.86 MB
[메모리] forecast_theta 실행 후: 1648.86 MB (변화: +0.00 MB)
[HSKA]   [Theta] 완료  첫값=6.63e+07 (메모리: 1648.9 MB)
[HSKA]   [DB] 88행 저장 완료
[PROGRESS] [ 481/500] ( 96.2%)  >>  GSL
[GSL]   40분기 | 2016-03-31 ~ 2025-12-31
[GSL]   [SARIMA] 시작  (메모리: 1648.9 MB)
[메모리] forecast_sarima 실행 전: 1648.86 MB
[메모리] find_best_sarima_params 실행 전: 1648.86 MB
[메모리] find_best_sarima_params 실행 후: 1648.86 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1648.86 MB (변화: +0.00 MB)
[GSL]   [SARIMA] 완료  첫값=1.94e+08 (메모리: 1648.9 MB)
[GSL]   [ETS] 시작  (메모리: 1648.9 MB)
[메모리] forecast_ets 실행 전: 1648.86 MB
[메모리] forecast_ets 실행 후: 1648.87 MB (변화: +0.00 MB)
[GSL]   [ETS] 완료  첫값=1.98e+08 (메모리: 1648.9 MB)
[GSL]   [Prophet] 시작  (메모리: 1648.9 MB)
[메모리] forecast_prophet 실행 전: 1648.87 MB

01:28:40 - cmdstanpy - INFO - Chain [1] start processing
01:28:40 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1648.89 MB (변화: +0.03 MB)
[GSL]   [Prophet] 완료  첫값=2.04e+08 (메모리: 1648.9 MB)
[GSL]   [LSTM] 시작  (메모리: 1648.9 MB)
[메모리] forecast_lstm 실행 전: 1648.89 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1648.88 MB (변화: -0.02 MB)
[GSL]   [LSTM] 완료  첫값=1.88e+08 (메모리: 1648.9 MB)
[GSL]   [Theta] 시작  (메모리: 1648.9 MB)
[메모리] forecast_theta 실행 전: 1648.88 MB
[메모리] forecast_theta 실행 후: 1648.88 MB (변화: +0.00 MB)
[GSL]   [Theta] 완료  첫값=1.95e+08 (메모리: 1648.9 MB)
[GSL]   [DB] 88행 저장 완료
[PROGRESS] [ 482/500] ( 96.4%)  >>  USPH
[USPH]   40분기 | 2016-03-31 ~ 2025-12-31
[USPH]   [SARIMA] 시작  (메모리: 1648.9 MB)
[메모리] forecast_sarima 실행 전: 1648.88 MB
[메모리] find_best_sarima_params 실행 전: 1648.88 MB
[메모리] find_best_sarima_params 실행 후: 1648.88 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1648.88 MB (변화: +0.00 MB)
[USPH]   [SARIMA] 완료  첫값=1.89e+08 (메모리: 1648.9 MB)
[USPH]   [ETS] 시작  (메모리: 1648.9 MB)
[메모리] forecast_ets 실행 전: 1648.88 MB
[메모리] forecast_ets 실행 후: 1648.88 MB (변화: +0.00 MB)
[USPH]   [ETS] 완료  첫값=1.84e+08 (메모리: 1648.9 MB)
[USPH]   [Prophet] 시작  (메모리: 1648.9 MB)

01:28:57 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1648.88 MB

01:28:57 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1648.89 MB (변화: +0.01 MB)
[USPH]   [Prophet] 완료  첫값=1.78e+08 (메모리: 1648.9 MB)
[USPH]   [LSTM] 시작  (메모리: 1648.9 MB)
[메모리] forecast_lstm 실행 전: 1648.89 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1648.90 MB (변화: +0.01 MB)
[USPH]   [LSTM] 완료  첫값=1.92e+08 (메모리: 1648.9 MB)
[USPH]   [Theta] 시작  (메모리: 1648.9 MB)
[메모리] forecast_theta 실행 전: 1648.90 MB
[메모리] forecast_theta 실행 후: 1648.90 MB (변화: +0.00 MB)
[USPH]   [Theta] 완료  첫값=1.88e+08 (메모리: 1648.9 MB)
[USPH]   [DB] 88행 저장 완료
[PROGRESS] [ 483/500] ( 96.6%)  >>  KAMN
[KAMN]   40분기 | 2014-03-28 ~ 2023-12-31
[KAMN]   [SARIMA] 시작  (메모리: 1648.9 MB)
[메모리] forecast_sarima 실행 전: 1648.90 MB
[메모리] find_best_sarima_params 실행 전: 1648.90 MB
[메모리] find_best_sarima_params 실행 후: 1648.90 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1648.90 MB (변화: +0.00 MB)
[KAMN]   [SARIMA] 완료  첫값=2.03e+08 (메모리: 1648.9 MB)
[KAMN]   [ETS] 시작  (메모리: 1648.9 MB)
[메모리] forecast_ets 실행 전: 1648.90 MB
[메모리] forecast_ets 실행 후: 1648.91 MB (변화: +0.00 MB)
[KAMN]   [ETS] 완료  첫값=1.92e+08 (메모리: 1648.9 MB)
[KAMN]   [Prophet] 시작  (메모리: 1648.9 MB)

01:29:17 - cmdstanpy - INFO - Chain [1] start processing
01:29:17 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1648.91 MB
[메모리] forecast_prophet 실행 후: 1648.92 MB (변화: +0.02 MB)
[KAMN]   [Prophet] 완료  첫값=1.31e+08 (메모리: 1648.9 MB)
[KAMN]   [LSTM] 시작  (메모리: 1648.9 MB)
[메모리] forecast_lstm 실행 전: 1648.92 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1648.92 MB (변화: -0.00 MB)
[KAMN]   [LSTM] 완료  첫값=1.74e+08 (메모리: 1648.9 MB)
[KAMN]   [Theta] 시작  (메모리: 1648.9 MB)
[메모리] forecast_theta 실행 전: 1648.92 MB
[메모리] forecast_theta 실행 후: 1648.92 MB (변화: +0.00 MB)
[KAMN]   [Theta] 완료  첫값=1.93e+08 (메모리: 1648.9 MB)
[KAMN]   [DB] 88행 저장 완료
[PROGRESS] [ 484/500] ( 96.8%)  >>  ENOV
[ENOV]   40분기 | 2016-04-01 ~ 2025-12-31
[ENOV]   [SARIMA] 시작  (메모리: 1648.9 MB)
[메모리] forecast_sarima 실행 전: 1648.92 MB
[메모리] find_best_sarima_params 실행 전: 1648.92 MB
[메모리] find_best_sarima_params 실행 후: 1648.92 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1648.92 MB (변화: +0.00 MB)
[ENOV]   [SARIMA] 완료  첫값=5.67e+08 (메모리: 1648.9 MB)
[ENOV]   [ETS] 시작  (메모리: 1648.9 MB)
[메모리] forecast_ets 실행 전: 1648.92 MB
[메모리] forecast_ets 실행 후: 1648.92 MB (변화: +0.00 MB)
[ENOV]   [ETS] 완료  첫값=5.30e+08 (메모리: 1648.9 MB)
[ENOV]   [Prophet] 시작  (메모리: 1648.9 MB)

01:29:35 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1648.92 MB

01:29:35 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1648.94 MB (변화: +0.02 MB)
[ENOV]   [Prophet] 완료  첫값=4.06e+08 (메모리: 1648.9 MB)
[ENOV]   [LSTM] 시작  (메모리: 1648.9 MB)
[메모리] forecast_lstm 실행 전: 1648.94 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1648.93 MB (변화: -0.01 MB)
[ENOV]   [LSTM] 완료  첫값=5.39e+08 (메모리: 1648.9 MB)
[ENOV]   [Theta] 시작  (메모리: 1648.9 MB)
[메모리] forecast_theta 실행 전: 1648.93 MB
[메모리] forecast_theta 실행 후: 1648.93 MB (변화: +0.00 MB)
[ENOV]   [Theta] 완료  첫값=5.42e+08 (메모리: 1648.9 MB)
[ENOV]   [DB] 88행 저장 완료
[PROGRESS] [ 485/500] ( 97.0%)  >>  TA
[TA]   40분기 | 2013-06-30 ~ 2023-03-31
[TA]   [SARIMA] 시작  (메모리: 1648.9 MB)
[메모리] forecast_sarima 실행 전: 1648.93 MB
[메모리] find_best_sarima_params 실행 전: 1648.93 MB
[메모리] find_best_sarima_params 실행 후: 1648.93 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1648.93 MB (변화: +0.00 MB)
[TA]   [SARIMA] 완료  첫값=2.24e+09 (메모리: 1648.9 MB)
[TA]   [ETS] 시작  (메모리: 1648.9 MB)
[메모리] forecast_ets 실행 전: 1648.93 MB
[메모리] forecast_ets 실행 후: 1648.94 MB (변화: +0.00 MB)
[TA]   [ETS] 완료  첫값=2.48e+09 (메모리: 1648.9 MB)
[TA]   [Prophet] 시작  (메모리: 1648.9 MB)
[메모리] forecast_prophet 실행 전: 1648.94 MB

01:29:56 - cmdstanpy - INFO - Chain [1] start processing
01:29:56 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1648.96 MB (변화: +0.02 MB)
[TA]   [Prophet] 완료  첫값=1.95e+09 (메모리: 1649.0 MB)
[TA]   [LSTM] 시작  (메모리: 1649.0 MB)
[메모리] forecast_lstm 실행 전: 1648.96 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1649.01 MB (변화: +0.05 MB)
[TA]   [LSTM] 완료  첫값=1.97e+09 (메모리: 1649.0 MB)
[TA]   [Theta] 시작  (메모리: 1649.0 MB)
[메모리] forecast_theta 실행 전: 1649.01 MB
[메모리] forecast_theta 실행 후: 1649.01 MB (변화: +0.00 MB)
[TA]   [Theta] 완료  첫값=2.24e+09 (메모리: 1649.0 MB)
[TA]   [DB] 88행 저장 완료
[PROGRESS] [ 486/500] ( 97.2%)  >>  BTCM
[BTCM] [NEG-SKIP] [BTCM] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2023, 12, 31)])
[PROGRESS] [ 487/500] ( 97.4%)  >>  LAR
[LAR] [NEG-SKIP] [LAR] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2019, 12, 31)])
[PROGRESS] [ 488/500] ( 97.6%)  >>  EVO
[EVO]   40분기 | 2015-12-31 ~ 2025-09-30
[EVO]   [SARIMA] 시작  (메모리: 1649.0 MB)
[메모리] forecast_sarima 실행 전: 1649.01 MB
[메모리] find_best_sarima_params 실행 전: 1649.01 MB
[메모리] find_best_sarima_params 실행 후: 1649.01 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1649.01 MB (변화: +0.00 MB)
[EVO]   [SARIMA] 완료  첫값=2.02e+08 (메모리: 1649.0 MB)
[EVO]   [ETS] 시작  (메모리: 1649.0 MB)
[메모리] forecast_ets 실행 전: 1649.01 MB
[메모리] forecast_ets 실행 후: 1649.01 MB (변화: +0.00 MB)
[EVO]   [ETS] 완료  첫값=1.84e+08 (메모리: 1649.0 MB)
[EVO]   [Prophet] 시작  (메모리: 1649.0 MB)

01:30:15 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1649.01 MB

01:30:15 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1649.02 MB (변화: +0.01 MB)
[EVO]   [Prophet] 완료  첫값=2.28e+08 (메모리: 1649.0 MB)
[EVO]   [LSTM] 시작  (메모리: 1649.0 MB)
[메모리] forecast_lstm 실행 전: 1649.02 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1648.97 MB (변화: -0.05 MB)
[EVO]   [LSTM] 완료  첫값=1.95e+08 (메모리: 1649.0 MB)
[EVO]   [Theta] 시작  (메모리: 1649.0 MB)
[메모리] forecast_theta 실행 전: 1648.97 MB
[메모리] forecast_theta 실행 후: 1648.97 MB (변화: +0.00 MB)
[EVO]   [Theta] 완료  첫값=1.83e+08 (메모리: 1649.0 MB)
[EVO]   [DB] 88행 저장 완료
[PROGRESS] [ 489/500] ( 97.8%)  >>  SWM
[SWM]   40분기 | 2013-09-30 ~ 2025-12-31
[SWM]   [SARIMA] 시작  (메모리: 1649.0 MB)
[메모리] forecast_sarima 실행 전: 1648.97 MB
[메모리] find_best_sarima_params 실행 전: 1648.97 MB
[메모리] find_best_sarima_params 실행 후: 1648.97 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1648.97 MB (변화: +0.00 MB)
[SWM]   [SARIMA] 완료  첫값=5.11e+08 (메모리: 1649.0 MB)
[SWM]   [ETS] 시작  (메모리: 1649.0 MB)
[메모리] forecast_ets 실행 전: 1648.97 MB
[메모리] forecast_ets 실행 후: 1648.98 MB (변화: +0.00 MB)
[SWM]   [ETS] 완료  첫값=4.87e+08 (메모리: 1649.0 MB)
[SWM]   [Prophet] 시작  (메모리: 1649.0 MB)

01:30:31 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1648.98 MB

01:30:31 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1649.00 MB (변화: +0.02 MB)
[SWM]   [Prophet] 완료  첫값=5.29e+08 (메모리: 1649.0 MB)
[SWM]   [LSTM] 시작  (메모리: 1649.0 MB)
[메모리] forecast_lstm 실행 전: 1649.00 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1648.96 MB (변화: -0.04 MB)
[SWM]   [LSTM] 완료  첫값=6.42e+08 (메모리: 1649.0 MB)
[SWM]   [Theta] 시작  (메모리: 1649.0 MB)
[메모리] forecast_theta 실행 전: 1648.96 MB
[메모리] forecast_theta 실행 후: 1648.96 MB (변화: +0.00 MB)
[SWM]   [Theta] 완료  첫값=4.65e+08 (메모리: 1649.0 MB)
[SWM]   [DB] 88행 저장 완료
[PROGRESS] [ 490/500] ( 98.0%)  >>  CRI
[CRI]   40분기 | 2016-04-02 ~ 2026-01-03
[CRI]   [SARIMA] 시작  (메모리: 1649.0 MB)
[메모리] forecast_sarima 실행 전: 1648.96 MB
[메모리] find_best_sarima_params 실행 전: 1648.96 MB
[메모리] find_best_sarima_params 실행 후: 1648.96 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1648.96 MB (변화: +0.00 MB)
[CRI]   [SARIMA] 완료  첫값=6.61e+08 (메모리: 1649.0 MB)
[CRI]   [ETS] 시작  (메모리: 1649.0 MB)
[메모리] forecast_ets 실행 전: 1648.96 MB
[메모리] forecast_ets 실행 후: 1648.96 MB (변화: +0.00 MB)
[CRI]   [ETS] 완료  첫값=6.58e+08 (메모리: 1649.0 MB)
[CRI]   [Prophet] 시작  (메모리: 1649.0 MB)

01:30:53 - cmdstanpy - INFO - Chain [1] start processing
01:30:53 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1648.96 MB
[메모리] forecast_prophet 실행 후: 1647.98 MB (변화: -0.98 MB)
[CRI]   [Prophet] 완료  첫값=7.48e+08 (메모리: 1648.0 MB)
[CRI]   [LSTM] 시작  (메모리: 1648.0 MB)
[메모리] forecast_lstm 실행 전: 1647.98 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1648.96 MB (변화: +0.98 MB)
[CRI]   [LSTM] 완료  첫값=7.48e+08 (메모리: 1649.0 MB)
[CRI]   [Theta] 시작  (메모리: 1649.0 MB)
[메모리] forecast_theta 실행 전: 1648.96 MB
[메모리] forecast_theta 실행 후: 1648.96 MB (변화: +0.00 MB)
[CRI]   [Theta] 완료  첫값=6.60e+08 (메모리: 1649.0 MB)
[CRI]   [DB] 88행 저장 완료
[PROGRESS] [ 491/500] ( 98.2%)  >>  PAR
[PAR]   40분기 | 2016-03-31 ~ 2025-12-31
[PAR]   [SARIMA] 시작  (메모리: 1649.0 MB)
[메모리] forecast_sarima 실행 전: 1648.96 MB
[메모리] find_best_sarima_params 실행 전: 1648.96 MB
[메모리] find_best_sarima_params 실행 후: 1648.96 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1648.96 MB (변화: +0.00 MB)
[PAR]   [SARIMA] 완료  첫값=1.17e+08 (메모리: 1649.0 MB)
[PAR]   [ETS] 시작  (메모리: 1649.0 MB)
[메모리] forecast_ets 실행 전: 1648.96 MB
[메모리] forecast_ets 실행 후: 1648.96 MB (변화: +0.00 MB)
[PAR]   [ETS] 완료  첫값=1.18e+08 (메모리: 1649.0 MB)
[PAR]   [Prophet] 시작  (메모리: 1649.0 MB)
[메모리] forecast_prophet 실행 전: 1648.96 MB

01:31:08 - cmdstanpy - INFO - Chain [1] start processing
01:31:08 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1648.97 MB (변화: +0.00 MB)
[PAR]   [Prophet] 완료  첫값=1.04e+08 (메모리: 1649.0 MB)
[PAR]   [LSTM] 시작  (메모리: 1649.0 MB)
[메모리] forecast_lstm 실행 전: 1648.97 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1648.96 MB (변화: -0.01 MB)
[PAR]   [LSTM] 완료  첫값=1.17e+08 (메모리: 1649.0 MB)
[PAR]   [Theta] 시작  (메모리: 1649.0 MB)
[메모리] forecast_theta 실행 전: 1648.96 MB
[메모리] forecast_theta 실행 후: 1648.96 MB (변화: +0.00 MB)
[PAR]   [Theta] 완료  첫값=1.16e+08 (메모리: 1649.0 MB)
[PAR]   [DB] 88행 저장 완료
[PROGRESS] [ 492/500] ( 98.4%)  >>  EYPT
[EYPT]   40분기 | 2016-03-31 ~ 2025-12-31
[EYPT]   [SARIMA] 시작  (메모리: 1649.0 MB)
[메모리] forecast_sarima 실행 전: 1648.96 MB
[메모리] find_best_sarima_params 실행 전: 1648.96 MB
[메모리] find_best_sarima_params 실행 후: 1648.96 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1648.96 MB (변화: +0.00 MB)
[EYPT]   [SARIMA] 완료  첫값=5.13e+05 (메모리: 1649.0 MB)
[EYPT]   [ETS] 시작  (메모리: 1649.0 MB)
[메모리] forecast_ets 실행 전: 1648.96 MB
[메모리] forecast_ets 실행 후: 1648.96 MB (변화: +0.00 MB)
[EYPT]   [ETS] 완료  첫값=8.68e+05 (메모리: 1649.0 MB)
[EYPT]   [Prophet] 시작  (메모리: 1649.0 MB)

01:31:26 - cmdstanpy - INFO - Chain [1] start processing
01:31:26 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1648.96 MB
[메모리] forecast_prophet 실행 후: 1647.98 MB (변화: -0.98 MB)
[EYPT]   [Prophet] 완료  첫값=1.27e+07 (메모리: 1648.0 MB)
[EYPT]   [LSTM] 시작  (메모리: 1648.0 MB)
[메모리] forecast_lstm 실행 전: 1647.98 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1648.95 MB (변화: +0.96 MB)
[EYPT]   [LSTM] 완료  첫값=1.01e+07 (메모리: 1648.9 MB)
[EYPT]   [Theta] 시작  (메모리: 1648.9 MB)
[메모리] forecast_theta 실행 전: 1648.95 MB
[메모리] forecast_theta 실행 후: 1648.95 MB (변화: +0.00 MB)
[EYPT]   [Theta] 완료  첫값=8.49e+05 (메모리: 1648.9 MB)
[EYPT]   [DB] 88행 저장 완료
[PROGRESS] [ 493/500] ( 98.6%)  >>  VTOL
[VTOL]   40분기 | 2016-03-31 ~ 2025-12-31
[VTOL]   [SARIMA] 시작  (메모리: 1648.9 MB)
[메모리] forecast_sarima 실행 전: 1648.95 MB
[메모리] find_best_sarima_params 실행 전: 1648.95 MB
[메모리] find_best_sarima_params 실행 후: 1648.95 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1648.95 MB (변화: +0.00 MB)
[VTOL]   [SARIMA] 완료  첫값=3.77e+08 (메모리: 1648.9 MB)
[VTOL]   [ETS] 시작  (메모리: 1648.9 MB)
[메모리] forecast_ets 실행 전: 1648.95 MB
[메모리] forecast_ets 실행 후: 1648.95 MB (변화: +0.00 MB)
[VTOL]   [ETS] 완료  첫값=3.63e+08 (메모리: 1648.9 MB)
[VTOL]   [Prophet] 시작  (메모리: 1648.9 MB)

01:31:45 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1648.95 MB

01:31:45 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1648.96 MB (변화: +0.02 MB)
[VTOL]   [Prophet] 완료  첫값=3.86e+08 (메모리: 1649.0 MB)
[VTOL]   [LSTM] 시작  (메모리: 1649.0 MB)
[메모리] forecast_lstm 실행 전: 1648.96 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1648.94 MB (변화: -0.03 MB)
[VTOL]   [LSTM] 완료  첫값=3.49e+08 (메모리: 1648.9 MB)
[VTOL]   [Theta] 시작  (메모리: 1648.9 MB)
[메모리] forecast_theta 실행 전: 1648.94 MB
[메모리] forecast_theta 실행 후: 1648.94 MB (변화: +0.00 MB)
[VTOL]   [Theta] 완료  첫값=3.58e+08 (메모리: 1648.9 MB)
[VTOL]   [DB] 88행 저장 완료
[PROGRESS] [ 494/500] ( 98.8%)  >>  RCAT
[RCAT]   40분기 | 2016-03-31 ~ 2025-12-31
[RCAT]   [SARIMA] 시작  (메모리: 1648.9 MB)
[메모리] forecast_sarima 실행 전: 1648.94 MB
[메모리] find_best_sarima_params 실행 전: 1648.94 MB
[메모리] find_best_sarima_params 실행 후: 1648.94 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1648.94 MB (변화: +0.00 MB)
[RCAT]   [SARIMA] 완료  첫값=3.91e+07 (메모리: 1648.9 MB)
[RCAT]   [ETS] 시작  (메모리: 1648.9 MB)
[메모리] forecast_ets 실행 전: 1648.94 MB
[메모리] forecast_ets 실행 후: 1648.94 MB (변화: +0.00 MB)
[RCAT]   [ETS] 완료  첫값=4.27e+07 (메모리: 1648.9 MB)
[RCAT]   [Prophet] 시작  (메모리: 1648.9 MB)

01:32:04 - cmdstanpy - INFO - Chain [1] start processing
01:32:04 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1648.94 MB
[메모리] forecast_prophet 실행 후: 1648.09 MB (변화: -0.85 MB)
[RCAT]   [Prophet] 완료  첫값=6.02e+06 (메모리: 1648.1 MB)
[RCAT]   [LSTM] 시작  (메모리: 1648.1 MB)
[메모리] forecast_lstm 실행 전: 1648.09 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1647.96 MB (변화: -0.14 MB)
[RCAT]   [LSTM] 완료  첫값=1.91e+07 (메모리: 1648.0 MB)
[RCAT]   [Theta] 시작  (메모리: 1648.0 MB)
[메모리] forecast_theta 실행 전: 1647.96 MB
[메모리] forecast_theta 실행 후: 1647.96 MB (변화: +0.00 MB)
[RCAT]   [Theta] 완료  첫값=2.63e+07 (메모리: 1648.0 MB)
[RCAT]   [DB] 88행 저장 완료
[PROGRESS] [ 495/500] ( 99.0%)  >>  ATEN
[ATEN]   40분기 | 2016-03-31 ~ 2025-12-31
[ATEN]   [SARIMA] 시작  (메모리: 1648.0 MB)
[메모리] forecast_sarima 실행 전: 1647.96 MB
[메모리] find_best_sarima_params 실행 전: 1647.96 MB
[메모리] find_best_sarima_params 실행 후: 1647.96 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1647.96 MB (변화: +0.00 MB)
[ATEN]   [SARIMA] 완료  첫값=6.92e+07 (메모리: 1648.0 MB)
[ATEN]   [ETS] 시작  (메모리: 1648.0 MB)
[메모리] forecast_ets 실행 전: 1647.96 MB
[메모리] forecast_ets 실행 후: 1647.96 MB (변화: +0.00 MB)
[ATEN]   [ETS] 완료  첫값=6.88e+07 (메모리: 1648.0 MB)
[ATEN]   [Prophet] 시작  (메모리: 1648.0 MB)

01:32:25 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1647.96 MB

01:32:25 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1649.44 MB (변화: +1.48 MB)
[ATEN]   [Prophet] 완료  첫값=7.05e+07 (메모리: 1649.4 MB)
[ATEN]   [LSTM] 시작  (메모리: 1649.4 MB)
[메모리] forecast_lstm 실행 전: 1649.44 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1648.71 MB (변화: -0.73 MB)
[ATEN]   [LSTM] 완료  첫값=6.63e+07 (메모리: 1648.7 MB)
[ATEN]   [Theta] 시작  (메모리: 1648.7 MB)
[메모리] forecast_theta 실행 전: 1648.71 MB
[메모리] forecast_theta 실행 후: 1648.71 MB (변화: +0.00 MB)
[ATEN]   [Theta] 완료  첫값=6.84e+07 (메모리: 1648.7 MB)
[ATEN]   [DB] 88행 저장 완료
[PROGRESS] [ 496/500] ( 99.2%)  >>  IRMD
[IRMD]   40분기 | 2016-03-31 ~ 2025-12-31
[IRMD]   [SARIMA] 시작  (메모리: 1648.7 MB)
[메모리] forecast_sarima 실행 전: 1648.71 MB
[메모리] find_best_sarima_params 실행 전: 1648.71 MB
[메모리] find_best_sarima_params 실행 후: 1648.71 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1648.71 MB (변화: +0.00 MB)
[IRMD]   [SARIMA] 완료  첫값=2.40e+07 (메모리: 1648.7 MB)
[IRMD]   [ETS] 시작  (메모리: 1648.7 MB)
[메모리] forecast_ets 실행 전: 1648.71 MB
[메모리] forecast_ets 실행 후: 1648.71 MB (변화: +0.00 MB)
[IRMD]   [ETS] 완료  첫값=2.23e+07 (메모리: 1648.7 MB)
[IRMD]   [Prophet] 시작  (메모리: 1648.7 MB)

01:32:43 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1648.71 MB

01:32:43 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1648.73 MB (변화: +0.01 MB)
[IRMD]   [Prophet] 완료  첫값=2.23e+07 (메모리: 1648.7 MB)
[IRMD]   [LSTM] 시작  (메모리: 1648.7 MB)
[메모리] forecast_lstm 실행 전: 1648.73 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1648.00 MB (변화: -0.73 MB)
[IRMD]   [LSTM] 완료  첫값=2.14e+07 (메모리: 1648.0 MB)
[IRMD]   [Theta] 시작  (메모리: 1648.0 MB)
[메모리] forecast_theta 실행 전: 1648.00 MB
[메모리] forecast_theta 실행 후: 1648.00 MB (변화: +0.00 MB)
[IRMD]   [Theta] 완료  첫값=2.21e+07 (메모리: 1648.0 MB)
[IRMD]   [DB] 88행 저장 완료
[PROGRESS] [ 497/500] ( 99.4%)  >>  CNMD
[CNMD]   40분기 | 2016-03-31 ~ 2025-12-31
[CNMD]   [SARIMA] 시작  (메모리: 1648.0 MB)
[메모리] forecast_sarima 실행 전: 1648.00 MB
[메모리] find_best_sarima_params 실행 전: 1648.00 MB
[메모리] find_best_sarima_params 실행 후: 1648.00 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1648.00 MB (변화: +0.00 MB)
[CNMD]   [SARIMA] 완료  첫값=3.54e+08 (메모리: 1648.0 MB)
[CNMD]   [ETS] 시작  (메모리: 1648.0 MB)
[메모리] forecast_ets 실행 전: 1648.00 MB
[메모리] forecast_ets 실행 후: 1648.00 MB (변화: +0.00 MB)
[CNMD]   [ETS] 완료  첫값=3.41e+08 (메모리: 1648.0 MB)
[CNMD]   [Prophet] 시작  (메모리: 1648.0 MB)

01:33:01 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1648.00 MB

01:33:01 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1648.74 MB (변화: +0.73 MB)
[CNMD]   [Prophet] 완료  첫값=3.52e+08 (메모리: 1648.7 MB)
[CNMD]   [LSTM] 시작  (메모리: 1648.7 MB)
[메모리] forecast_lstm 실행 전: 1648.74 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1647.99 MB (변화: -0.75 MB)
[CNMD]   [LSTM] 완료  첫값=3.45e+08 (메모리: 1648.0 MB)
[CNMD]   [Theta] 시작  (메모리: 1648.0 MB)
[메모리] forecast_theta 실행 전: 1647.99 MB
[메모리] forecast_theta 실행 후: 1647.99 MB (변화: +0.00 MB)
[CNMD]   [Theta] 완료  첫값=3.40e+08 (메모리: 1648.0 MB)
[CNMD]   [DB] 88행 저장 완료
[PROGRESS] [ 498/500] ( 99.6%)  >>  SCL
[SCL]   40분기 | 2016-03-31 ~ 2025-12-31
[SCL]   [SARIMA] 시작  (메모리: 1648.0 MB)
[메모리] forecast_sarima 실행 전: 1647.99 MB
[메모리] find_best_sarima_params 실행 전: 1647.99 MB
[메모리] find_best_sarima_params 실행 후: 1647.99 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1647.99 MB (변화: +0.00 MB)
[SCL]   [SARIMA] 완료  첫값=5.57e+08 (메모리: 1648.0 MB)
[SCL]   [ETS] 시작  (메모리: 1648.0 MB)
[메모리] forecast_ets 실행 전: 1647.99 MB
[메모리] forecast_ets 실행 후: 1648.00 MB (변화: +0.00 MB)
[SCL]   [ETS] 완료  첫값=5.88e+08 (메모리: 1648.0 MB)
[SCL]   [Prophet] 시작  (메모리: 1648.0 MB)
[메모리] forecast_prophet 실행 전: 1648.00 MB

01:33:18 - cmdstanpy - INFO - Chain [1] start processing
01:33:18 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1648.37 MB (변화: +0.38 MB)
[SCL]   [Prophet] 완료  첫값=6.23e+08 (메모리: 1648.4 MB)
[SCL]   [LSTM] 시작  (메모리: 1648.4 MB)
[메모리] forecast_lstm 실행 전: 1648.37 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1647.99 MB (변화: -0.38 MB)
[SCL]   [LSTM] 완료  첫값=5.59e+08 (메모리: 1648.0 MB)
[SCL]   [Theta] 시작  (메모리: 1648.0 MB)
[메모리] forecast_theta 실행 전: 1647.99 MB
[메모리] forecast_theta 실행 후: 1647.99 MB (변화: +0.00 MB)
[SCL]   [Theta] 완료  첫값=5.90e+08 (메모리: 1648.0 MB)
[SCL]   [DB] 88행 저장 완료
[PROGRESS] [ 499/500] ( 99.8%)  >>  ELE
[ELE]   33분기 | 2017-09-30 ~ 2025-12-31
[ELE]   [SARIMA] 시작  (메모리: 1648.0 MB)
[메모리] forecast_sarima 실행 전: 1647.99 MB
[메모리] find_best_sarima_params 실행 전: 1647.99 MB
[메모리] find_best_sarima_params 실행 후: 1647.99 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1647.99 MB (변화: +0.00 MB)
[ELE]   [SARIMA] 완료  첫값=1.86e+07 (메모리: 1648.0 MB)
[ELE]   [ETS] 시작  (메모리: 1648.0 MB)
[메모리] forecast_ets 실행 전: 1647.99 MB
[메모리] forecast_ets 실행 후: 1647.99 MB (변화: +0.00 MB)
[ELE]   [ETS] 완료  첫값=1.71e+07 (메모리: 1648.0 MB)
[ELE]   [Prophet] 시작  (메모리: 1648.0 MB)

01:33:33 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1647.99 MB

01:33:33 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1648.62 MB (변화: +0.63 MB)
[ELE]   [Prophet] 완료  첫값=7.37e+06 (메모리: 1648.6 MB)
[ELE]   [LSTM] 시작  (메모리: 1648.6 MB)
[메모리] forecast_lstm 실행 전: 1648.62 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1648.33 MB (변화: -0.29 MB)
[ELE]   [LSTM] 완료  첫값=6.95e+06 (메모리: 1648.3 MB)
[ELE]   [Theta] 시작  (메모리: 1648.3 MB)
[메모리] forecast_theta 실행 전: 1648.33 MB
[메모리] forecast_theta 실행 후: 1648.33 MB (변화: +0.00 MB)
[ELE]   [Theta] 완료  첫값=1.32e+07 (메모리: 1648.3 MB)
[ELE]   [DB] 81행 저장 완료
[PROGRESS] [ 500/500] (100.0%)  >>  INVA
[INVA]   40분기 | 2016-03-31 ~ 2025-12-31
[INVA]   [SARIMA] 시작  (메모리: 1648.3 MB)
[메모리] forecast_sarima 실행 전: 1648.33 MB
[메모리] find_best_sarima_params 실행 전: 1648.33 MB
[메모리] find_best_sarima_params 실행 후: 1648.33 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1648.33 MB (변화: +0.00 MB)
[INVA]   [SARIMA] 완료  첫값=1.11e+08 (메모리: 1648.3 MB)
[INVA]   [ETS] 시작  (메모리: 1648.3 MB)
[메모리] forecast_ets 실행 전: 1648.33 MB
[메모리] forecast_ets 실행 후: 1648.33 MB (변화: +0.00 MB)
[INVA]   [ETS] 완료  첫값=1.07e+08 (메모리: 1648.3 MB)
[INVA]   [Prophet] 시작  (메모리: 1648.3 MB)
[메모리] forecast_prophet 실행 전: 1648.33 MB

01:33:48 - cmdstanpy - INFO - Chain [1] start processing
01:33:48 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1647.98 MB (변화: -0.36 MB)
[INVA]   [Prophet] 완료  첫값=1.07e+08 (메모리: 1648.0 MB)
[INVA]   [LSTM] 시작  (메모리: 1648.0 MB)
[메모리] forecast_lstm 실행 전: 1647.98 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1649.22 MB (변화: +1.24 MB)
[INVA]   [LSTM] 완료  첫값=9.02e+07 (메모리: 1649.2 MB)
[INVA]   [Theta] 시작  (메모리: 1649.2 MB)
[메모리] forecast_theta 실행 전: 1649.22 MB
[메모리] forecast_theta 실행 후: 1649.22 MB (변화: +0.00 MB)
[INVA]   [Theta] 완료  첫값=1.04e+08 (메모리: 1649.2 MB)
[INVA]   [DB] 88행 저장 완료
[BATCH] ======================================================================
[BATCH] 완료 | 성공: 459  데이터스킵: 11  음수제외: 30  오류: 0  합계: 500
[BATCH] 데이터스킵  : ['DJT', 'VRN', 'CXT', 'CON', 'CMBT', 'EACQ', 'BWLP', 'TVPT', 'VIVO', 'ASTH', 'NNE']
[BATCH] 음수매출제외 : ['COMM', 'WSC', 'DNN', 'SLG', 'MPW', 'COTY', 'BTE', 'WVE', 'PLUG', 'VGR', 'GLPG', 'NOG', 'DX', 'ARR', 'SEM', 'CLI', 'STGW', 'NVAX', 'WRE', 'ALEX', 'ABR', 'VYX', 'SBET', 'TWO', 'IRS', 'LAC', 'SYX', 'EFC', 'BTCM', 'LAR']
[BATCH] ======================================================================

## Cell 14 · 저장 결과 조회

배치 완료 후 DB 에 저장된 결과를 확인합니다.

In [15]:
# ── 오늘 예측된 티커 × 모델별 요약 ──────────────────────────
with engine.connect() as conn:
    summary_df = pd.read_sql(
        text(f"""
            SELECT
                ticker,
                item,
                model,
                MIN(date)  AS date_from,
                MAX(date)  AS date_to,
                COUNT(*)   AS row_count,
                forecast_date
            FROM   `{DEST_TABLE}`
            WHERE  forecast_date = :fd
            GROUP  BY ticker, item, model, forecast_date
            ORDER  BY ticker, model
        """),
        conn,
        params={"fd": FORECAST_DATE},
    )

print(f"[오늘({FORECAST_DATE}) 예측 저장 결과: {len(summary_df)}건]")
display(summary_df)

[오늘(2026-04-03) 예측 저장 결과: 6732건]

     ticker  item     model   date_from     date_to  row_count forecast_date
0         A  sale    actual  2016-04-30  2026-01-31         40    2026-04-03
1         A  sale  Ensemble  2026-03-31  2027-12-31          8    2026-04-03
2         A  sale       ETS  2026-03-31  2027-12-31          8    2026-04-03
3         A  sale      LSTM  2026-03-31  2027-12-31          8    2026-04-03
4         A  sale   Prophet  2026-03-31  2027-12-31          8    2026-04-03
...     ...   ...       ...         ...         ...        ...           ...
6727    ZWS  sale       ETS  2026-03-31  2027-12-31          8    2026-04-03
6728    ZWS  sale      LSTM  2026-03-31  2027-12-31          8    2026-04-03
6729    ZWS  sale   Prophet  2026-03-31  2027-12-31          8    2026-04-03
6730    ZWS  sale    SARIMA  2026-03-31  2027-12-31          8    2026-04-03
6731    ZWS  sale     Theta  2026-03-31  2027-12-31          8    2026-04-03

[6732 rows x 7 columns]

In [16]:
# ── 전체 DB 저장 통계 ─────────────────────────────────────
with engine.connect() as conn:
    total_stat = pd.read_sql(
        text(f"""
            SELECT
                forecast_date,
                COUNT(DISTINCT ticker) AS ticker_cnt,
                COUNT(DISTINCT model)  AS model_cnt,
                COUNT(*)               AS total_rows
            FROM   `{DEST_TABLE}`
            GROUP  BY forecast_date
            ORDER  BY forecast_date DESC
            LIMIT  10
        """),
        conn,
    )

print("[전체 DB 저장 현황 (최근 10개 예측일)]")
display(total_stat)

[전체 DB 저장 현황 (최근 10개 예측일)]

  forecast_date  ticker_cnt  model_cnt  total_rows
0    2026-04-03         962          7       84616
1    2026-03-31         731          7       65721
2    2026-03-30         964          7       87241

## Cell 15 · 오염 데이터 삭제 & 재예측

### 왜 필요한가?
기존 예측은 **FMP 중복 데이터(같은 실적이 다른 분기 날짜에 저장된 행)**를  
그대로 포함한 시계열로 예측했습니다.  
예) `date_month=2025-12`인 실적이 `2025-12-31`과 `2026-03-31` 두 날짜에 저장  
→ 시계열 마지막에 **가짜 분기가 추가**되어 예측 기준점이 한 분기 뒤로 밀림

### 처리 순서
1. **Cell 15-A** : 삭제 대상 확인 (실제 삭제 전 확인용)
2. **Cell 15-B** : `us_revenue_forecast_data` 에서 기존 예측 데이터 삭제
3. **Cell 13** : 수정된 `fetch_financial_series` 로 재예측 실행

> ⚠️ 특정 ticker 만 재예측하려면 `RUN_TICKERS = ["AAPL", ...]` 로 지정하세요.

In [23]:
# # ══════════════════════════════════════════════════════
# #  Cell 15-A : 삭제 대상 확인 (읽기 전용 — 실제 삭제 안 함)
# # ══════════════════════════════════════════════════════
#
# # 삭제할 forecast_date 지정
# # None → DEST_TABLE 전체 삭제 / 문자열 → 특정 날짜만
# DELETE_FORECAST_DATE = None    # 예: "2026-03-25"  또는 None (전체)
# DELETE_TICKERS       = None    # 예: ["AAPL", "MSFT"]  또는 None (전체)
#
# # ── 삭제 대상 row 수 확인 ─────────────────────────────
# with engine.connect() as conn:
#     cond_parts = []
#     cond_params = {}
#     if DELETE_FORECAST_DATE:
#         cond_parts.append("forecast_date = :fd")
#         cond_params["fd"] = DELETE_FORECAST_DATE
#     if DELETE_TICKERS:
#         in_clause = ", ".join([f":t{i}" for i in range(len(DELETE_TICKERS))])
#         cond_parts.append(f"ticker IN ({in_clause})")
#         for i, t in enumerate(DELETE_TICKERS):
#             cond_params[f"t{i}"] = t
#
#     where_sql = ("WHERE " + " AND ".join(cond_parts)) if cond_parts else ""
#     check_sql = text(f"SELECT COUNT(*) AS cnt FROM `{DEST_TABLE}` {where_sql}")
#     row = conn.execute(check_sql, cond_params).fetchone()
#     cnt = row[0] if row else 0
#
# print(f"[확인] 삭제 대상 조건:")
# print(f"       forecast_date = {DELETE_FORECAST_DATE or '전체'}")
# print(f"       tickers       = {DELETE_TICKERS or '전체'}")
# print(f"       삭제 예정 행 수: {cnt:,}행")
# print()
# print("실제 삭제하려면 Cell 15-B 를 실행하세요.")

In [17]:
# # ══════════════════════════════════════════════════════
# #  Cell 15-B : 실제 삭제 실행
# #  ⚠️  되돌릴 수 없습니다. Cell 15-A 확인 후 실행하세요.
# # ══════════════════════════════════════════════════════
#
# # Cell 15-A 와 동일한 조건 사용
# with engine.begin() as conn:
#     del_parts = []
#     del_params = {}
#     if DELETE_FORECAST_DATE:
#         del_parts.append("forecast_date = :fd")
#         del_params["fd"] = DELETE_FORECAST_DATE
#     if DELETE_TICKERS:
#         in_clause = ", ".join([f":t{i}" for i in range(len(DELETE_TICKERS))])
#         del_parts.append(f"ticker IN ({in_clause})")
#         for i, t in enumerate(DELETE_TICKERS):
#             del_params[f"t{i}"] = t
#
#     where_sql = ("WHERE " + " AND ".join(del_parts)) if del_parts else ""
#     delete_sql = text(f"DELETE FROM `{DEST_TABLE}` {where_sql}")
#     result = conn.execute(delete_sql, del_params)
#
# print(f"[완료] 삭제된 행 수: {result.rowcount:,}행")
# print()
# print("다음 단계: Cell 13 을 실행해 재예측을 진행하세요.")
# print("  → fetch_financial_series 가 수정됐으므로 정확한 시계열로 재예측됩니다.")