In [2]:
import sys
import pandas as pd

# 프로젝트 루트 (당신 환경에 맞게 이미 확인된 경로)
sys.path.append(
    r"C:\Users\82108\OneDrive\바탕 화면\investment\investment_strategy\US_Market\collect"
)

print("Python path added")

Python path added

In [3]:
from sec_data_pipeline.collectors.sec_utils import fetch_company_facts
from sec_data_pipeline.parsers.company_facts_parser import CompanyFactsParser
from sec_data_pipeline.parsers.financial_normalizer import FinancialNormalizer

print("Imports successful")
print("CompanyFactsParser path:")
import sec_data_pipeline.parsers.company_facts_parser as cfp
print(cfp.__file__)

Imports successful
CompanyFactsParser path:
C:\Users\82108\OneDrive\바탕 화면\investment\investment_strategy\US_Market\collect\sec_data_pipeline\parsers\company_facts_parser.py

In [4]:
ticker = "A"  # Agilent

# ⚠ SEC API는 User-Agent 필수 (이메일 포함 권장)
headers = {
    "User-Agent": "Hoyoung Park (hoyoung@example.com)"  # 이메일은 본인 것으로 교체
}

facts = fetch_company_facts(ticker, headers=headers)

print("Company facts downloaded")
print("Top-level keys:", facts.keys())

Company facts downloaded
Top-level keys: dict_keys(['cik', 'entityName', 'facts'])

In [5]:
parser = CompanyFactsParser(facts)

print("Entity name:", parser.entity_name)
print("CIK:", parser.cik)

# Revenue tag 자동 탐색
rev_tag = parser.detect_best_revenue_tag()
print("Detected revenue tag:", rev_tag)

Entity name: AGILENT TECHNOLOGIES, INC.
CIK: 1090872
Detected revenue tag: RevenueFromContractWithCustomerExcludingAssessedTax

In [6]:
normalizer = FinancialNormalizer(parser)

df_q = normalizer.create_normalized_dataframe(period_type="quarterly")

print("Quarterly normalized dataframe created")
print("Shape:", df_q.shape)
print("Date range:", df_q.index.min(), "~", df_q.index.max())

Quarterly normalized dataframe created
Shape: (71, 31)
Date range: 2006-10-31 00:00:00 ~ 2025-07-31 00:00:00

In [7]:
max_end = pd.to_datetime(df_q.index).max()
print("MAX period_end:", max_end)

print("\nLast 8 rows:")
df_q.tail(8)

MAX period_end: 2025-07-31 00:00:00

Last 8 rows:

,revenue,net_income,operating_income,total_assets,current_assets,total_liabilities,current_liabilities,stockholders_equity,cash,long_term_debt,...,other_noncurrent_assets,short_term_debt,accounts_payable,accounts_receivable,inventory,deferred_revenue,accrued_liabilities,non_interest_current_liabilities,depreciation_amortization,capital_expenditures
date,,,,,,,,,,,,,,,,,,,,,
2023-10-31,1.672000e+09,111000000.0,133000000.0,1.076300e+10,4.186000e+09,4.918000e+09,1.603000e+09,5.845000e+09,1.590000e+09,2.735000e+09,...,708000000.0,0.0,418000000.0,1.291000e+09,1.031000e+09,505000000.0,371000000.0,309000000.0,67000000.0,76000000.0
2024-01-31,1.658000e+09,348000000.0,384000000.0,1.094800e+10,4.338000e+09,4.760000e+09,1.617000e+09,6.188000e+09,1.748000e+09,2.555000e+09,...,716000000.0,0.0,488000000.0,1.295000e+09,1.033000e+09,522000000.0,272000000.0,309000000.0,62000000.0,90000000.0
2024-04-30,1.573000e+09,308000000.0,363000000.0,1.085600e+10,4.203000e+09,4.642000e+09,1.958000e+09,6.214000e+09,1.671000e+09,2.136000e+09,...,725000000.0,420000000.0,461000000.0,1.249000e+09,1.000000e+09,533000000.0,326000000.0,309000000.0,62000000.0,90000000.0
2024-07-31,1.578000e+09,282000000.0,333000000.0,1.099600e+10,4.256000e+09,5.093000e+09,2.389000e+09,5.903000e+09,1.779000e+09,2.137000e+09,...,751000000.0,795000000.0,497000000.0,1.227000e+09,9.780000e+08,524000000.0,309000000.0,309000000.0,62000000.0,90000000.0
2024-10-31,1.578000e+09,282000000.0,333000000.0,1.184600e+10,3.959000e+09,5.948000e+09,1.895000e+09,5.898000e+09,1.329000e+09,3.345000e+09,...,910000000.0,45000000.0,540000000.0,1.324000e+09,9.720000e+08,544000000.0,368000000.0,398000000.0,62000000.0,90000000.0
2025-01-31,1.681000e+09,318000000.0,376000000.0,1.191400e+10,4.107000e+09,5.887000e+09,1.869000e+09,6.027000e+09,1.467000e+09,3.347000e+09,...,875000000.0,16000000.0,547000000.0,1.328000e+09,9.970000e+08,612000000.0,258000000.0,398000000.0,72000000.0,97000000.0
2025-04-30,1.668000e+09,215000000.0,300000000.0,1.215800e+10,4.208000e+09,6.022000e+09,2.012000e+09,6.136000e+09,1.486000e+09,3.349000e+09,...,934000000.0,146000000.0,517000000.0,1.366000e+09,9.910000e+08,628000000.0,347000000.0,398000000.0,72000000.0,97000000.0
2025-07-31,1.738000e+09,336000000.0,360000000.0,1.222600e+10,4.253000e+09,5.856000e+09,1.892000e+09,6.370000e+09,1.535000e+09,3.350000e+09,...,930000000.0,59000000.0,530000000.0,1.382000e+09,1.014000e+09,620000000.0,346000000.0,398000000.0,72000000.0,97000000.0

In [8]:
# revenue 관련 컬럼 자동 탐색
for col in df_q.columns:
    if "rev" in col.lower() or "sale" in col.lower():
        print(f"\nLast 12 values of column: {col}")
        display(df_q[col].tail(12))

Last 12 values of column: revenue

date
2022-10-31    1.718000e+09
2023-01-31    1.756000e+09
2023-04-30    1.717000e+09
2023-07-31    1.672000e+09
2023-10-31    1.672000e+09
2024-01-31    1.658000e+09
2024-04-30    1.573000e+09
2024-07-31    1.578000e+09
2024-10-31    1.578000e+09
2025-01-31    1.681000e+09
2025-04-30    1.668000e+09
2025-07-31    1.738000e+09
Name: revenue, dtype: float64

Last 12 values of column: cost_of_revenue

date
2022-10-31    542000000.0
2023-01-31    542000000.0
2023-04-30    542000000.0
2023-07-31    542000000.0
2023-10-31    542000000.0
2024-01-31    542000000.0
2024-04-30    542000000.0
2024-07-31    542000000.0
2024-10-31    542000000.0
2025-01-31    542000000.0
2025-04-30    542000000.0
2025-07-31    542000000.0
Name: cost_of_revenue, dtype: float64

Last 12 values of column: deferred_revenue

date
2022-10-31    461000000.0
2023-01-31    521000000.0
2023-04-30    519000000.0
2023-07-31    512000000.0
2023-10-31    505000000.0
2024-01-31    522000000.0
2024-04-30    533000000.0
2024-07-31    524000000.0
2024-10-31    544000000.0
2025-01-31    612000000.0
2025-04-30    628000000.0
2025-07-31    620000000.0
Name: deferred_revenue, dtype: float64

In [10]:
raw = parser.extract_tag_data(rev_tag)

raw_sorted = raw[["end","fp","form","filed","val"]].sort_values(
    ["end","filed"], ascending=[True, True]
)

raw_sorted.tail(20)

           end    fp  form      filed         val
81  2023-10-31  None   8-K 2024-09-03  6833000000
82  2023-10-31    FY  10-K 2024-12-20  6833000000
83  2023-10-31  None   8-K 2025-03-03  6833000000
84  2024-01-31    Q1  10-Q 2024-03-05  1658000000
85  2024-01-31    Q1  10-Q 2025-03-03  1658000000
88  2024-04-30    Q2  10-Q 2024-06-03  1573000000
86  2024-04-30    Q2  10-Q 2024-06-03  3231000000
89  2024-04-30    Q2  10-Q 2025-06-02  1573000000
87  2024-04-30    Q2  10-Q 2025-06-02  3231000000
90  2024-07-31    Q3  10-Q 2024-08-30  4809000000
92  2024-07-31    Q3  10-Q 2024-08-30  1578000000
91  2024-07-31    Q3  10-Q 2025-08-29  4809000000
93  2024-07-31    Q3  10-Q 2025-08-29  1578000000
94  2024-10-31    FY  10-K 2024-12-20  6510000000
95  2024-10-31  None   8-K 2025-03-03  6510000000
96  2025-01-31    Q1  10-Q 2025-03-03  1681000000
97  2025-04-30    Q2  10-Q 2025-06-02  3349000000
98  2025-04-30    Q2  10-Q 2025-06-02  1668000000
99  2025-07-31    Q3  10-Q 2025-08-29  5087000000
100 2025-07-31    Q3  10-Q 2025-08-29  1738000000

In [9]:
# wide → long 변환 예시
df_long = (
    df_q
    .reset_index()
    .melt(id_vars="period_end", var_name="item_name", value_name="value")
)

# long → pivot
pivot = df_long.pivot_table(
    index="period_end",
    columns="item_name",
    values="value",
    aggfunc="last"
).sort_index()

pivot.tail(8)

KeyError: "The following id_vars or value_vars are not present in the DataFrame: ['period_end']"