# 1. 단일 기업 재무제표 받기

In [19]:
from collectors import SECAPIClient, RateLimiter
from parsers import CompanyFactsParser, FinancialNormalizer

user_agent = "PersonalResearch stox1224@email.com"
client = SECAPIClient(user_agent, RateLimiter(10, 1.0))

# 데이터 수집
company_facts = client.get_company_facts_by_ticker('AAPL')
parser = CompanyFactsParser(company_facts)

# 분기 데이터 확인
quarterly_revenue = parser.get_quarterly_data('Revenues')
print("\n분기별 Revenue (최근 12분기):")
print(quarterly_revenue[['end', 'val', 'fy', 'fp', 'form']].tail(12))

# 연간 데이터 확인
annual_revenue = parser.get_annual_data('Revenues')
print("\n연간 Revenue (최근 5년):")
print(annual_revenue[['end', 'val', 'fy', 'fp', 'form']].tail(5))

# Normalizer로 DataFrame 생성
normalizer = FinancialNormalizer(parser)

# 분기 데이터
df_quarterly = normalizer.create_normalized_dataframe(period_type='quarterly')
print("\n분기별 DataFrame:")
print(df_quarterly[['revenue', 'net_income']].tail(12))

# 연간 데이터
df_annual = normalizer.create_normalized_dataframe(period_type='annual')
print("\n연간 DataFrame:")
print(df_annual[['revenue', 'net_income']].tail(5))

  Found CIK for AAPL: 320193

분기별 Revenue (최근 12분기):

TypeError: 'NoneType' object is not subscriptable

In [17]:
quarterly_revenue

### 분기별 vs 연간 데이터분기별

In [13]:
# 분기별 데이터
df_quarterly = normalizer.create_normalized_dataframe(period_type='quarterly')

# 연간 데이터
df_annual = normalizer.create_normalized_dataframe(period_type='annual')

In [14]:
df_quarterly

,revenue,net_income,operating_income,gross_profit,total_assets,current_assets,total_liabilities,current_liabilities,stockholders_equity,cash,long_term_debt,cost_of_revenue,operating_expenses,research_development
date,,,,,,,,,,,,,,
2008-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10339000000,NaN,NaN,NaN,NaN
2008-09-30,1.506100e+10,4.373000e+09,5.999000e+09,NaN,NaN,NaN,NaN,NaN,3.359400e+10,9004000000,NaN,2.848000e+09,NaN,2.283000e+09
2008-12-31,3.169000e+10,4.174000e+09,1.193800e+10,NaN,NaN,NaN,NaN,NaN,3.447800e+10,8346000000,NaN,6.755000e+09,NaN,4.573000e+09
2009-03-31,4.533800e+10,1.152400e+10,1.637600e+10,NaN,NaN,NaN,NaN,NaN,3.694300e+10,7285000000,NaN,9.569000e+09,NaN,6.785000e+09
2009-06-30,NaN,NaN,NaN,NaN,7.788800e+10,4.928000e+10,NaN,2.703400e+10,3.955800e+10,6076000000,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-09-30,NaN,2.466700e+10,3.055200e+10,4.548600e+10,5.230130e+11,1.499260e+11,2.352900e+11,1.152000e+11,2.877230e+11,20840000000,4.511700e+10,NaN,1.493400e+10,7.544000e+09
2024-12-31,NaN,4.877500e+10,6.220500e+10,9.331900e+10,5.338980e+11,1.470800e+11,2.312030e+11,1.088820e+11,3.026950e+11,17482000000,4.497000e+10,NaN,NaN,1.546100e+10
2025-03-31,NaN,7.459900e+10,9.420500e+10,1.414660e+11,5.626240e+11,1.566440e+11,2.407330e+11,1.142060e+11,3.218910e+11,28828000000,4.288100e+10,NaN,NaN,2.365900e+10
2025-06-30,NaN,NaN,NaN,NaN,6.190030e+11,1.911310e+11,2.755240e+11,1.412180e+11,3.434790e+11,30242000000,4.315100e+10,NaN,NaN,NaN
2025-09-30,NaN,2.774700e+10,3.796100e+10,5.363000e+10,6.363510e+11,1.890660e+11,2.732750e+11,1.349960e+11,3.630760e+11,28849000000,4.320800e+10,NaN,1.566900e+10,8.146000e+09

In [15]:
df_annual

,revenue,net_income,operating_income,gross_profit,total_assets,current_assets,total_liabilities,current_liabilities,stockholders_equity,cash,long_term_debt,cost_of_revenue,operating_expenses,research_development
date,,,,,,,,,,,,,,
2008-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10339000000,NaN,NaN,NaN,NaN
2008-09-30,1.506100e+10,4.373000e+09,5.999000e+09,NaN,NaN,NaN,NaN,NaN,3.359400e+10,9004000000,NaN,2.848000e+09,NaN,2.283000e+09
2008-12-31,3.169000e+10,4.174000e+09,1.193800e+10,NaN,NaN,NaN,NaN,NaN,3.447800e+10,8346000000,NaN,6.755000e+09,NaN,4.573000e+09
2009-03-31,4.533800e+10,1.152400e+10,1.637600e+10,NaN,NaN,NaN,NaN,NaN,3.694300e+10,7285000000,NaN,9.569000e+09,NaN,6.785000e+09
2009-06-30,NaN,NaN,NaN,NaN,7.788800e+10,4.928000e+10,NaN,2.703400e+10,3.955800e+10,6076000000,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-09-30,NaN,2.466700e+10,3.055200e+10,4.548600e+10,5.230130e+11,1.499260e+11,2.352900e+11,1.152000e+11,2.877230e+11,20840000000,4.511700e+10,NaN,1.493400e+10,7.544000e+09
2024-12-31,NaN,4.877500e+10,6.220500e+10,9.331900e+10,5.338980e+11,1.470800e+11,2.312030e+11,1.088820e+11,3.026950e+11,17482000000,4.497000e+10,NaN,NaN,1.546100e+10
2025-03-31,NaN,7.459900e+10,9.420500e+10,1.414660e+11,5.626240e+11,1.566440e+11,2.407330e+11,1.142060e+11,3.218910e+11,28828000000,4.288100e+10,NaN,NaN,2.365900e+10
2025-06-30,NaN,NaN,NaN,NaN,6.190030e+11,1.911310e+11,2.755240e+11,1.412180e+11,3.434790e+11,30242000000,4.315100e+10,NaN,NaN,NaN
2025-09-30,NaN,2.774700e+10,3.796100e+10,5.363000e+10,6.363510e+11,1.890660e+11,2.732750e+11,1.349960e+11,3.630760e+11,28849000000,4.320800e+10,NaN,1.566900e+10,8.146000e+09

### Billions 단위로 변환

In [ ]:
df_billions = normalizer.convert_to_billions(df)
print(df_billions[['revenue', 'net_income']].tail(8))

### TTM (Trailing Twelve Months) 계산

In [ ]:
df_ttm = normalizer.calculate_ttm(df_billions, columns=['revenue', 'net_income'])
print(df_ttm[['revenue', 'revenue_ttm']].tail(8))

# 2. 다수 기업 재무제표 받기

In [ ]:
from collectors import SECAPIClient, RateLimiter, BulkDownloader
from parsers import CompanyFactsParser, FinancialNormalizer
import pandas as pd

# 1. 클라이언트 및 다운로더 설정
user_agent = "PersonalResearch stox1224@email.com"
client = SECAPIClient(user_agent, RateLimiter(10, 1.0))
downloader = BulkDownloader(client, output_dir="./sec_data", max_workers=3)

# 2. 다운로드할 기업 리스트
tickers = ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'TSLA', 'NVDA', 'META']

# 3. 배치 다운로드 (자동으로 JSON 파일 저장)
results = downloader.download_company_facts_batch(tickers)

# 4. 각 기업별 데이터 처리
all_financials = {}

for ticker, company_facts in results.items():
    parser = CompanyFactsParser(company_facts)
    normalizer = FinancialNormalizer(parser)

    # 재무데이터 정규화
    df = normalizer.create_normalized_dataframe(period_type='quarterly')
    df_billions = normalizer.convert_to_billions(df)

    all_financials[ticker] = df_billions

    # 개별 CSV 저장
    normalizer.export_to_csv(df_billions, f'{ticker}_financials.csv')

print(f"총 {len(all_financials)}개 기업 데이터 수집 완료")

# 3. 특정 재무항목만 추출

In [ ]:
revenue_comparison = {}

for ticker, company_facts in results.items():
    parser = CompanyFactsParser(company_facts)
    normalizer = FinancialNormalizer(parser)

    # Revenue만 추출
    revenue_series = normalizer.normalize_single_item('revenue', period_type='quarterly')

    if revenue_series is not None:
        revenue_comparison[ticker] = revenue_series / 1_000_000_000  # Billions

# DataFrame으로 변환
revenue_df = pd.DataFrame(revenue_comparison)
print("\n최근 8분기 매출 비교 (Billions):")
print(revenue_df.tail(8))

# YoY 성장률
growth_df = revenue_df.pct_change(periods=4) * 100
print("\nYoY 매출 성장률 (%):")
print(growth_df.tail(4))

# 4. 사용 가능한 재무 항목

In [ ]:
# 추출 가능한 표준 재무 항목들
available_items = [
    'revenue',              # 매출
    'net_income',           # 순이익
    'operating_income',     # 영업이익
    'gross_profit',         # 매출총이익
    'total_assets',         # 총자산
    'current_assets',       # 유동자산
    'total_liabilities',    # 총부채
    'current_liabilities',  # 유동부채
    'stockholders_equity',  # 자본
    'cash',                 # 현금
    'long_term_debt',       # 장기부채
    'cost_of_revenue',      # 매출원가
    'operating_expenses',   # 영업비용
    'research_development', # 연구개발비
    'earnings_per_share',   # 주당순이익
]

# 특정 항목만 추출
for item in ['revenue', 'net_income', 'total_assets']:
    series = normalizer.normalize_single_item(item, period_type='quarterly')
    print(f"\n{item}:")
    print(series.tail(4))

# 5. 재무비율 계산

In [ ]:
# 데이터 준비
df = normalizer.create_normalized_dataframe(period_type='quarterly')

# 재무비율 자동 계산
df_ratios = normalizer.calculate_financial_ratios(df)

# 계산되는 비율들:
# - profit_margin: 순이익률
# - operating_margin: 영업이익률
# - current_ratio: 유동비율
# - debt_to_equity: 부채비율
# - roe: 자기자본이익률
# - roa: 총자산이익률

print(df_ratios[['revenue', 'net_income', 'profit_margin']].tail(8))

# 6. 성장률 분석

In [ ]:
df_billions = normalizer.convert_to_billions(df)

# YoY 성장률 계산
df_growth = normalizer.calculate_growth_rates(
    df_billions,
    columns=['revenue', 'net_income'],
    periods=4  # 4분기 = YoY
)

print(df_growth[['revenue', 'revenue_yoy_growth']].tail(8))

# 7. 진행상황 모니터링

In [ ]:
# 콜백 함수 정의
def on_download_complete(ticker, data, index, total):
    if data:
        entity_name = data.get('entityName', 'Unknown')
        print(f"[{index}/{total}] {ticker}: {entity_name} - 완료")
    else:
        print(f"[{index}/{total}] {ticker}: 실패")

# 콜백과 함께 다운로드
results = downloader.download_company_facts_batch(
    tickers=['AAPL', 'MSFT', 'GOOGL'],
    callback=on_download_complete
)

# 8. 중단된 다운로드 재개

In [ ]:
# 이미 다운로드된 파일은 건너뛰기
remaining_results = downloader.resume_download(tickers)

# 9. 다운로드 리포트 생성

In [ ]:
# 다운로드 후 리포트 생성
downloader.create_download_report(results, "download_report.json")

# 10. 실전 예제: S&P 500 상위 기업 분석

In [ ]:
# Tech Giants
tech_giants = ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'META', 'NVDA', 'TSLA']

# 다운로드
downloader = BulkDownloader(client, output_dir="./tech_giants", max_workers=5)
results = downloader.download_company_facts_batch(tech_giants)

# Revenue 비교 분석
revenue_data = {}
for ticker, facts in results.items():
    parser = CompanyFactsParser(facts)
    normalizer = FinancialNormalizer(parser)
    revenue = normalizer.normalize_single_item('revenue', period_type='quarterly')
    if revenue is not None:
        revenue_data[ticker] = revenue / 1e9  # Billions

# 비교 DataFrame
comparison = pd.DataFrame(revenue_data)
print("\nTech Giants 최근 매출 비교 (Billions):")
print(comparison.tail(8))

# 시각화 (선택사항)
import matplotlib.pyplot as plt
comparison.tail(12).plot(figsize=(12, 6))
plt.title('Tech Giants Revenue Comparison (Last 12 Quarters)')
plt.ylabel('Revenue (Billions USD)')
plt.legend(loc='best')
plt.grid(True)
plt.savefig('tech_giants_revenue.png')