# US Revenue Forecast v2 — 단계별 테스트 노트북

**소스 테이블** : `US_IS_from_FMP`  
**저장 테이블** : `us_revenue_forecast_data`  
**예측 모델**  : SARIMA · ETS · Prophet · LSTM · Theta + Ensemble (SARIMA+ETS+Theta 평균)

---

| 셀 번호 | 단계 |
|---------|------|
| Cell 1  | 환경 설정 & 경로 자동 감지 |
| Cell 2  | 모듈 Import |
| Cell 3  | 파라미터 설정 |
| Cell 4  | DB 연결 테스트 |
| Cell 5  | 재무 데이터 추출 함수 정의 |
| Cell 6  | 단일 티커 데이터 추출 테스트 |
| Cell 7  | 예측 함수 정의 |
| Cell 8  | 단일 티커 예측 테스트 |
| Cell 9  | Long-format 변환 함수 정의 |
| Cell 10 | Long-format 변환 테스트 |
| Cell 11 | DB 테이블 생성 & 저장 함수 정의 |
| Cell 12 | 단일 티커 저장 테스트 |
| Cell 13 | 배치 실행 (전체 / 특정 티커 / 구간 지정) |
| Cell 14 | 저장 결과 조회 |

---
### ⚡ 메모리 전략
> **티커 1개씩 즉시 저장** 방식을 채택합니다.  
> 배치(20개 누적 후 저장)는 리스트가 메모리에 쌓여 오히려 OOM 위험이 높습니다.  
> 1개 예측 → 즉시 저장 → `clear_memory()` 호출 순서로 메모리를 최소 상태로 유지합니다.

### 🔢 구간 예측 (2000개 티커 단계적 처리)
> Cell 13 의 `TICKER_START` / `TICKER_END` 변수로 처리 구간을 지정하세요.  
> 예: 0~499 → 500~999 → ... 순서로 끊어서 실행하면 메모리 부담 없이 전체 예측 가능합니다.

## Cell 1 · 환경 설정 & 경로 자동 감지

노트북(Hoyoung_Park) / 데스크탑(82108) 어느 환경에서 실행해도  
`DATA` 폴더를 자동으로 찾아 `sys.path`에 추가합니다.

In [1]:
import sys, os, warnings
from pathlib import Path
warnings.filterwarnings("ignore")

# ── 후보 프로젝트 루트 (노트북 / 데스크탑) ───────────────────────
_CANDIDATE_ROOTS = [
    r"C:\Users\Hoyoung_Park\PyCharmMiscProject\stock_forecast",          # 노트북
    r"C:\Users\82108\OneDrive\바탕 화면\investment\investment_strategy",   # 데스크탑
]

def _setup_path() -> str:
    """
    프로젝트 루트(DATA/ 폴더의 부모)를 탐색해 sys.path 에 추가합니다.
    탐색 순서:
      1) __file__ 또는 cwd 기준 상위 경로 중 DATA/ 를 포함하는 첫 번째 경로
      2) _CANDIDATE_ROOTS 에서 실존하는 첫 번째 경로
    """
    try:
        start = Path(__file__).resolve().parent
    except NameError:          # 노트북 환경 — __file__ 없음
        start = Path.cwd()

    # 현재 경로부터 상위로 올라가며 DATA/ 탐색
    for p in [start] + list(start.parents):
        if (p / "DATA").is_dir():
            root = str(p)
            if root not in sys.path:
                sys.path.insert(0, root)
            print(f"[PATH] root 자동 감지 : {root}")
            return root

    # cwd 탐색에서 못 찾으면 후보 경로 시도
    for candidate in _CANDIDATE_ROOTS:
        if os.path.isdir(candidate) and os.path.isdir(os.path.join(candidate, "DATA")):
            if candidate not in sys.path:
                sys.path.insert(0, candidate)
            print(f"[PATH] root 후보 경로 : {candidate}")
            return candidate

    raise EnvironmentError(
        "DATA 폴더를 찾을 수 없습니다.\n"
        "_CANDIDATE_ROOTS 목록을 현재 환경에 맞게 수정하거나 "
        "노트북을 프로젝트 루트 아래에서 실행하세요."
    )

_ROOT = _setup_path()
print(f"[확인] 프로젝트 루트  : {_ROOT}")
print(f"[확인] DATA 경로     : {os.path.join(_ROOT, 'DATA')}")
print(f"[확인] sys.path[0]   : {sys.path[0]}")

[PATH] root 자동 감지 : C:\Users\82108\OneDrive\바탕 화면\investment\investment_strategy
[확인] 프로젝트 루트  : C:\Users\82108\OneDrive\바탕 화면\investment\investment_strategy
[확인] DATA 경로     : C:\Users\82108\OneDrive\바탕 화면\investment\investment_strategy\DATA
[확인] sys.path[0]   : C:\Users\82108\OneDrive\바탕 화면\investment\investment_strategy\US_Market\analysis\미국전기업_매출_예측

## Cell 2 · 모듈 Import

`DATA` 폴더 내 세 모듈과 외부 라이브러리를 불러옵니다.

In [2]:
# ── 내부 모듈 (DATA 폴더) ─────────────────────────────────────
from DATA.config import get_db_info, get_engine
from DATA.us_target_ticker_list_2000 import ticker_list as DEFAULT_TICKER_LIST
from DATA.universal_ts_forecast_function_v2 import (
    forecast_sarima,
    forecast_ets,
    forecast_prophet,
    forecast_lstm,
    forecast_theta,
    infer_freq_alias,
    seasonal_periods_from_freq,
    clear_memory,
)

# ── 외부 라이브러리 ───────────────────────────────────────────
import gc
import traceback
from typing import Optional, List      # Python 3.9 호환 타입 힌트
import numpy as np
import pandas as pd
from datetime import datetime
from sqlalchemy import text
from IPython.display import display

# ── 로그 유틸 (config 에 log 가 없는 경우 자체 정의) ──────────
try:
    from DATA.config import log
except ImportError:
    def log(tag: str, msg: str):
        ts = datetime.now().strftime("%H:%M:%S")
        print(f"[{ts}][{tag}] {msg}")

print(f"[OK] 모든 모듈 Import 완료")
print(f"[OK] DEFAULT_TICKER_LIST 길이: {len(DEFAULT_TICKER_LIST):,}개")

[OK] 모든 모듈 Import 완료
[OK] DEFAULT_TICKER_LIST 길이: 2,000개

## Cell 3 · 파라미터 설정

항목·기간·모델·배치 등 전역 파라미터를 여기서만 수정합니다.

In [3]:
# ════════════════════════════════════════════════════════════
#  ★ 파라미터 — 필요에 따라 이 셀만 수정하세요 ★
# ════════════════════════════════════════════════════════════

# ── 테이블 ────────────────────────────────────────────────
SRC_TABLE  = "US_IS_from_FMP"           # 원본 재무 테이블
DEST_TABLE = "us_revenue_forecast_data" # 예측 결과 저장 테이블

# ── 재무 항목 ─────────────────────────────────────────────
# 예: "sale" (매출) / "opi" (영업이익) / "ni" (순이익) / "ebitda" 등
ITEM       = "sale"

# ── 예측 설정 ─────────────────────────────────────────────
HORIZON    = 8    # 예측 분기 수 (default 8 = 2년)
MIN_OBS    = 28   # 최소 관측 분기 수 (28 = 7년 × 4분기)

# ── 모델 선택 ─────────────────────────────────────────────
ALL_MODELS      = ["SARIMA", "ETS", "Prophet", "LSTM", "Theta"]
ENSEMBLE_MODELS = ["SARIMA", "ETS", "Theta"]   # 앙상블 구성 모델

# ── 예측 실행일 ───────────────────────────────────────────
FORECAST_DATE = datetime.now().strftime("%Y-%m-%d")

# ════════════════════════════════════════════════════════════
print("[파라미터 확인]")
print(f"  SRC_TABLE    = {SRC_TABLE}")
print(f"  DEST_TABLE   = {DEST_TABLE}")
print(f"  ITEM         = {ITEM}")
print(f"  HORIZON      = {HORIZON}분기")
print(f"  MIN_OBS      = {MIN_OBS}개")
print(f"  ALL_MODELS   = {ALL_MODELS}")
print(f"  ENSEMBLE     = {ENSEMBLE_MODELS}")
print(f"  FORECAST_DATE= {FORECAST_DATE}")

[파라미터 확인]
  SRC_TABLE    = US_IS_from_FMP
  DEST_TABLE   = us_revenue_forecast_data
  ITEM         = sale
  HORIZON      = 8분기
  MIN_OBS      = 28개
  ALL_MODELS   = ['SARIMA', 'ETS', 'Prophet', 'LSTM', 'Theta']
  ENSEMBLE     = ['SARIMA', 'ETS', 'Theta']
  FORECAST_DATE= 2026-03-27

## Cell 4 · DB 연결 테스트

In [4]:
db_info = get_db_info()
engine  = get_engine(db_info)

try:
    with engine.connect() as conn:
        conn.execute(text("SELECT 1"))
    print("[OK] DB 연결 성공")
    print(f"     host={db_info.get('host')}  port={db_info.get('port')}  db={db_info.get('database')}")
except Exception as e:
    print(f"[FAIL] DB 연결 실패: {e}")

[OK] DB 연결 성공
     host=192.168.0.230  port=3307  db=investar

## Cell 5 · 재무 데이터 추출 함수 정의

`US_IS_from_FMP` → ticker + item 기준 분기 시계열 추출  

**처리 흐름**
1. ticker / item 기준으로 value, date, period, date_month 추출  
2. 날짜 파싱 및 오름차순 정렬  
3. 월별 중복 제거 (같은 월 → 마지막 행, 단독 행은 보존)  
4. 분기 단위 재집계 (같은 분기 → 마지막 행, 분기말 날짜로 통일)  
5. MIN_OBS 미달 시 ValueError

In [5]:
def fetch_financial_series(
    engine,
    ticker: str,
    item: str   = "sale",
    min_obs: int = 28,
) -> pd.DataFrame:
    """
    US_IS_from_FMP 테이블에서 ticker + item 기준으로 분기 시계열을 추출합니다.

    Parameters
    ----------
    engine  : SQLAlchemy engine
    ticker  : 종목 코드  (예: 'AAPL')
    item    : 재무 항목  (예: 'sale' / 'opi' / 'ni')
    min_obs : 최소 분기 수 — 미달 시 ValueError

    Returns
    -------
    DataFrame  columns: date, report_date, period, date_month, value
    """
    query = text("""
        SELECT
            date,
            report_date,
            period,
            date_month,
            value
        FROM   US_IS_from_FMP
        WHERE  ticker = :ticker
          AND  item   = :item
          AND  value  IS NOT NULL
        ORDER  BY date
    """)

    with engine.connect() as conn:
        df = pd.read_sql(query, conn, params={"ticker": ticker, "item": item})

    if df.empty:
        raise ValueError(f"[{ticker}] '{item}' 데이터가 DB에 없습니다.")

    # 1. 날짜 변환
    df["date"]        = pd.to_datetime(df["date"],        errors="coerce")
    df["report_date"] = pd.to_datetime(df["report_date"], errors="coerce")
    df["date_month"]  = pd.to_datetime(df["date_month"],  errors="coerce")
    df = df.dropna(subset=["date"]).sort_values("date").reset_index(drop=True)
    df["value"] = pd.to_numeric(df["value"], errors="coerce")
    df = df.dropna(subset=["value"])

    # 2. 월별 중복 제거
    #    같은 월에 여러 행 → 마지막 행 유지
    #    처음/끝처럼 해당 월에 1건만 있는 행은 그대로 보존
    df["_ym"]  = df["date"].dt.to_period("M")
    dup_mask   = df["_ym"].duplicated(keep=False)

    if dup_mask.any():
        df_single = df[~dup_mask].copy()
        df_dup    = (
            df[dup_mask]
            .groupby("_ym", sort=True)
            .last()
            .reset_index()
        )
        df = (
            pd.concat([df_single, df_dup], ignore_index=True)
            .sort_values("date")
            .reset_index(drop=True)
        )
    df = df.drop(columns=["_ym"])

    # 3. 분기 단위 재집계 → 분기말 날짜로 통일
    df["_q"] = df["date"].dt.to_period("Q")
    df = (
        df.groupby("_q", sort=True)
          .last()
          .reset_index()
    )
    df["date"] = df["_q"].dt.to_timestamp("Q")   # 예: 2023Q4 → 2023-12-31
    df = (
        df.drop(columns=["_q"])
          .sort_values("date")
          .reset_index(drop=True)
    )

    # 4. 최소 관측치 검사
    if len(df) < min_obs:
        raise ValueError(
            f"[{ticker}] '{item}' 관측치 부족: {len(df)}개 < 최소 {min_obs}개"
        )

    return df   # columns: date, report_date, period, date_month, value

print("[OK] fetch_financial_series 함수 정의 완료")

[OK] fetch_financial_series 함수 정의 완료

## Cell 6 · 단일 티커 데이터 추출 테스트

`TEST_TICKER` 를 원하는 티커로 변경해서 테스트하세요.

In [6]:
TEST_TICKER = "AAPL"   # ← 테스트할 티커

try:
    src_df = fetch_financial_series(
        engine, TEST_TICKER, item=ITEM, min_obs=MIN_OBS
    )
    print(f"[OK] {TEST_TICKER} '{ITEM}' 추출 성공: {len(src_df)}분기")
    print(f"     기간: {src_df['date'].iloc[0].date()} ~ {src_df['date'].iloc[-1].date()}")
    display(src_df.tail(8))
except Exception as e:
    print(f"[FAIL] {e}")

[OK] AAPL 'sale' 추출 성공: 45분기
     기간: 2015-03-31 ~ 2026-03-31

         date report_date period date_month         value
37 2024-06-30  2024-06-29     Q3 2024-06-01  8.577700e+10
38 2024-09-30  2024-09-28     Q4 2024-09-01  9.493000e+10
39 2024-12-31  2024-12-28     Q1 2024-12-01  1.243000e+11
40 2025-03-31  2025-03-29     Q2 2025-03-01  9.535900e+10
41 2025-06-30  2025-06-28     Q3 2025-06-01  9.403600e+10
42 2025-09-30  2025-09-27     Q4 2025-09-01  1.024660e+11
43 2025-12-31  2025-12-27     Q1 2025-12-01  1.437560e+11
44 2026-03-31  2025-12-27     Q1 2025-12-01  1.437560e+11

## Cell 7 · 예측 함수 정의

- `make_forecast_index` : 마지막 실제값 다음 분기부터 HORIZON 개 날짜 생성  
- `forecast_one_ticker` : 5개 모델 순차 실행, 메모리 추적 포함

In [7]:
def make_forecast_index(
    last_date: pd.Timestamp,
    horizon: int,
    freq: str = "QE",
) -> pd.DatetimeIndex:
    """
    last_date 다음 분기부터 horizon 개의 날짜 인덱스를 생성합니다.
    freq : infer_freq_alias() 가 반환하는 값 (Q, QE, QS 등)
    """
    _freq = freq if freq else "QE"
    try:
        idx = pd.date_range(
            start   = last_date + pd.tseries.frequencies.to_offset(_freq),
            periods = horizon,
            freq    = _freq,
        )
    except Exception:
        # fallback: 3개월 간격으로 직접 생성
        idx = pd.date_range(
            start   = last_date + pd.DateOffset(months=3),
            periods = horizon,
            freq    = "QE",
        )
    return idx


def forecast_one_ticker(
    y: pd.Series,
    ticker: str,
    horizon: int,
    models: list,
) -> dict:
    """
    단일 티커의 시계열 y 에 대해 지정 모델들로 예측을 수행합니다.

    실제 함수 시그니처 (universal_ts_forecast_function_v2.py 기준):
      forecast_sarima  : (y, forecast_horizon, seasonal_period=int)
      forecast_ets     : (y, forecast_horizon, m=int)
      forecast_prophet : (y, forecast_horizon, m=int)
      forecast_lstm    : (y, forecast_horizon)           ← m 파라미터 없음
      forecast_theta   : (y, forecast_horizon, m=int)

    Parameters
    ----------
    y       : DatetimeIndex 를 가진 분기 시계열 (Series)
    ticker  : 종목 코드 (로그 출력용)
    horizon : 예측 분기 수
    models  : 사용할 모델 목록  ["SARIMA", "ETS", "Prophet", "LSTM", "Theta"]

    Returns
    -------
    dict  {model_name: {"forecast": array, "spec": dict} or {"error": str}}
    """
    import psutil, os
    proc = psutil.Process(os.getpid())

    def _mem_mb():
        return proc.memory_info().rss / 1024 / 1024

    freq    = infer_freq_alias(y.index)
    sp      = seasonal_periods_from_freq(freq)   # 분기=4, 월=12
    results = {}

    # ── 각 함수의 실제 파라미터명에 맞춰 호출 ─────────────────────
    def _call(model_name):
        if model_name == "SARIMA":
            # forecast_sarima(y, forecast_horizon, seasonal_period=)
            return forecast_sarima(y, horizon, seasonal_period=sp)
        elif model_name == "ETS":
            # forecast_ets(y, forecast_horizon, m=)
            return forecast_ets(y, horizon, m=sp)
        elif model_name == "Prophet":
            # forecast_prophet(y, forecast_horizon, m=)
            return forecast_prophet(y, horizon, m=sp)
        elif model_name == "LSTM":
            # forecast_lstm(y, forecast_horizon)  ← m 파라미터 없음
            return forecast_lstm(y, horizon)
        elif model_name == "Theta":
            # forecast_theta(y, forecast_horizon, m=)
            return forecast_theta(y, horizon, m=sp)
        else:
            raise ValueError(f"알 수 없는 모델: {model_name}")

    for model_name in models:
        log(ticker, f"  [{model_name}] 시작  (메모리: {_mem_mb():.1f} MB)")
        try:
            res = _call(model_name)
            results[model_name] = res
            fc_arr = np.asarray(res.get("forecast", []))
            if len(fc_arr) > 0:
                log(ticker, f"  [{model_name}] 완료  첫값={fc_arr[0]:.2e} (메모리: {_mem_mb():.1f} MB)")
            else:
                log(ticker, f"  [{model_name}] 오류응답: {res}")
        except Exception as e:
            log(ticker, f"  [{model_name}] 오류: {e}")
            results[model_name] = {"error": str(e)}
        finally:
            gc.collect()

    return results

print("[OK] make_forecast_index / forecast_one_ticker 함수 정의 완료")
print("  SARIMA  : forecast_sarima(y, forecast_horizon, seasonal_period=sp)")
print("  ETS     : forecast_ets(y, forecast_horizon, m=sp)")
print("  Prophet : forecast_prophet(y, forecast_horizon, m=sp)")
print("  LSTM    : forecast_lstm(y, forecast_horizon)")
print("  Theta   : forecast_theta(y, forecast_horizon, m=sp)")

[OK] make_forecast_index / forecast_one_ticker 함수 정의 완료
  SARIMA  : forecast_sarima(y, forecast_horizon, seasonal_period=sp)
  ETS     : forecast_ets(y, forecast_horizon, m=sp)
  Prophet : forecast_prophet(y, forecast_horizon, m=sp)
  LSTM    : forecast_lstm(y, forecast_horizon)
  Theta   : forecast_theta(y, forecast_horizon, m=sp)

## Cell 8 · 단일 티커 예측 테스트

Cell 6 에서 추출한 `src_df` 를 사용합니다.  
모델별 예측값과 SARIMA 파라미터를 확인하세요.

In [8]:
# Cell 6 에서 src_df 가 정상 추출된 경우에만 실행
y = src_df.set_index("date")["value"].copy()
y.index = pd.DatetimeIndex(y.index)
y.name  = ITEM

print(f"예측 입력 시계열: {len(y)}분기  ({y.index[0].date()} ~ {y.index[-1].date()})")

# 테스트용 모델 — 빠른 확인이 필요하면 ['SARIMA', 'ETS', 'Theta'] 로 축소 가능
TEST_MODELS = ALL_MODELS

forecast_results = forecast_one_ticker(y, TEST_TICKER, HORIZON, TEST_MODELS)
freq             = infer_freq_alias(y.index)
forecast_index   = make_forecast_index(y.index[-1], HORIZON, freq)

print("\n[예측 결과 요약]")
for model_name, res in forecast_results.items():
    if "error" in res:
        print(f"  {model_name:<10}: 오류 → {res['error']}")
    else:
        fc  = np.asarray(res["forecast"])
        msg = f"  {model_name:<10}: {fc.round(0).tolist()}"
        if model_name == "SARIMA" and "spec" in res:
            spec = res["spec"]
            aic  = spec.get("ic_value", "")
            aic_str = f"  AIC={aic:.2f}" if isinstance(aic, float) else ""
            msg += f"  | order={spec.get('order')} seasonal={spec.get('seasonal_order')}{aic_str}"
        print(msg)

예측 입력 시계열: 45분기  (2015-03-31 ~ 2026-03-31)
[AAPL]   [SARIMA] 시작  (메모리: 431.6 MB)
[메모리] forecast_sarima 실행 전: 431.62 MB
[메모리] find_best_sarima_params 실행 전: 431.65 MB
[메모리] find_best_sarima_params 실행 후: 436.88 MB (변화: +5.23 MB)
[메모리] forecast_sarima 실행 후: 436.99 MB (변화: +5.37 MB)
[AAPL]   [SARIMA] 완료  첫값=1.35e+11 (메모리: 437.0 MB)
[AAPL]   [ETS] 시작  (메모리: 437.1 MB)
[메모리] forecast_ets 실행 전: 437.06 MB
[메모리] forecast_ets 실행 후: 437.26 MB (변화: +0.20 MB)
[AAPL]   [ETS] 완료  첫값=1.12e+11 (메모리: 437.3 MB)
[AAPL]   [Prophet] 시작  (메모리: 437.3 MB)

00:24:24 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 437.26 MB

00:24:24 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 440.32 MB (변화: +3.06 MB)
[AAPL]   [Prophet] 완료  첫값=1.19e+11 (메모리: 440.3 MB)
[AAPL]   [LSTM] 시작  (메모리: 440.3 MB)
[메모리] forecast_lstm 실행 전: 440.32 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1448.62 MB (변화: +1008.30 MB)
[경고] 메모리 사용량이 크게 증가했습니다. 메모리 정리를 권장합니다.
[AAPL]   [LSTM] 완료  첫값=1.03e+11 (메모리: 1448.6 MB)
[AAPL]   [Theta] 시작  (메모리: 1448.6 MB)
[메모리] forecast_theta 실행 전: 1448.62 MB
[메모리] forecast_theta 실행 후: 1448.78 MB (변화: +0.16 MB)
[AAPL]   [Theta] 완료  첫값=1.15e+11 (메모리: 1448.8 MB)

[예측 결과 요약]
  SARIMA    : [135238172626.0, 145630469496.0, 190965969156.0, 168115103284.0, 159595361653.0, 171899902806.0, 222578777791.0, 198600825393.0]  | order=(1, 0, 0) seasonal=(1, 0, 1, 4)  AIC=-49.16
  ETS       : [111600659045.0, 119882190949.0, 175206371709.0, 138591237537.0, 120227487135.0, 129149188664.0, 188749976755.0, 149304460839.0]
  Prophet   : [118785779479.0, 120376186029.0, 121966592578.0, 123522425072.0, 125095544593.0, 126685951143.0, 128276357692.0, 129849477213.0]
  LSTM      : [103296303104.0, 105070764032.0, 106696286208.0, 106669875200.0, 107837636608.0, 109027778560.0, 109605085184.0, 108743417856.0]
  Theta     : [115136490467.0, 122886617885.0, 181007559375.0, 137558352815.0, 119548528460.0, 127606139091.0, 188064054845.0, 142861140981.0]

## Cell 9 · Long-format 변환 함수 정의

actual + forecast(각 모델) + Ensemble → 하나의 long-format DataFrame

**저장 컬럼**

| 컬럼 | 설명 |
|------|------|
| ticker | 종목 코드 |
| item | 재무 항목 |
| date | 기준일(분기말) |
| period | 회계 분기(Q1~Q4/FY) — actual 행만 |
| date_month | 해당 분기 기간 — actual 행만 |
| data_type | `actual` / `forecast` |
| model | actual / SARIMA / ETS / Prophet / LSTM / Theta / Ensemble |
| value | 수치값 |
| forecast_date | 예측 실행일 |
| sarima_order | SARIMA (p,d,q) — SARIMA 행만 |
| sarima_seasonal_order | SARIMA (P,D,Q,m) — SARIMA 행만 |
| sarima_ic_value | SARIMA 최적 AIC — SARIMA 행만 |
| created_at | 레코드 생성 시각 |

In [9]:
def build_long_df(
    ticker: str,
    item: str,
    src_df: pd.DataFrame,
    forecast_results: dict,
    forecast_index: pd.DatetimeIndex,
    forecast_date: str,
    ensemble_models: list = None,
) -> pd.DataFrame:
    """
    실제값(actual) + 예측값(각 모델) + 앙상블 → long-format DataFrame.

    Parameters
    ----------
    ticker           : 종목 코드
    item             : 재무 항목
    src_df           : fetch_financial_series() 반환 DataFrame
    forecast_results : forecast_one_ticker() 반환 dict
    forecast_index   : 예측 날짜 DatetimeIndex
    forecast_date    : 예측 실행일 (str)
    ensemble_models  : 앙상블 구성 모델 목록 (None → ENSEMBLE_MODELS 전역 변수 사용)
    """
    if ensemble_models is None:
        ensemble_models = ENSEMBLE_MODELS

    now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    rows    = []

    # ── actual 행 ────────────────────────────────────────────
    for _, row in src_df.iterrows():
        rows.append({
            "ticker"                : ticker,
            "item"                  : item,
            "date"                  : row["date"].strftime("%Y-%m-%d"),
            "period"                : row.get("period"),
            "date_month"            : (
                row["date_month"].strftime("%Y-%m-%d")
                if pd.notna(row.get("date_month")) else None
            ),
            "data_type"             : "actual",
            "model"                 : "actual",
            "value"                 : round(float(row["value"]), 6),
            "forecast_date"         : forecast_date,
            "sarima_order"          : None,
            "sarima_seasonal_order" : None,
            "sarima_ic_value"       : None,
            "created_at"            : now_str,
        })

    # ── forecast 행 ──────────────────────────────────────────
    ensemble_bucket = {}   # { date_str : [val, ...] }

    for model_name, res in forecast_results.items():
        if "error" in res or "forecast" not in res:
            continue

        fc_arr = np.asarray(res["forecast"])
        spec   = res.get("spec", {})

        sarima_order    = None
        sarima_seasonal = None
        sarima_ic       = None
        if model_name == "SARIMA":
            sarima_order    = str(spec.get("order",          ""))
            sarima_seasonal = str(spec.get("seasonal_order", ""))
            raw_ic = spec.get("ic_value")
            if raw_ic is not None:
                try:
                    v = float(raw_ic)
                    sarima_ic = round(v, 4) if np.isfinite(v) else None
                except (TypeError, ValueError):
                    pass

        for i, dt in enumerate(forecast_index):
            if i >= len(fc_arr):
                break
            val    = float(fc_arr[i])
            dt_str = dt.strftime("%Y-%m-%d")

            rows.append({
                "ticker"                : ticker,
                "item"                  : item,
                "date"                  : dt_str,
                "period"                : None,
                "date_month"            : None,
                "data_type"             : "forecast",
                "model"                 : model_name,
                "value"                 : round(val, 6),
                "forecast_date"         : forecast_date,
                "sarima_order"          : sarima_order,
                "sarima_seasonal_order" : sarima_seasonal,
                "sarima_ic_value"       : sarima_ic,
                "created_at"            : now_str,
            })

            if model_name in ensemble_models:
                ensemble_bucket.setdefault(dt_str, []).append(val)

    # ── Ensemble 행 (SARIMA + ETS + Theta 평균) ─────────────
    for dt_str, vals in ensemble_bucket.items():
        rows.append({
            "ticker"                : ticker,
            "item"                  : item,
            "date"                  : dt_str,
            "period"                : None,
            "date_month"            : None,
            "data_type"             : "forecast",
            "model"                 : "Ensemble",
            "value"                 : round(float(np.mean(vals)), 6),
            "forecast_date"         : forecast_date,
            "sarima_order"          : None,
            "sarima_seasonal_order" : None,
            "sarima_ic_value"       : None,
            "created_at"            : now_str,
        })

    return pd.DataFrame(rows)

print("[OK] build_long_df 함수 정의 완료")

[OK] build_long_df 함수 정의 완료

## Cell 10 · Long-format 변환 테스트

In [10]:
long_df = build_long_df(
    ticker           = TEST_TICKER,
    item             = ITEM,
    src_df           = src_df,
    forecast_results = forecast_results,
    forecast_index   = forecast_index,
    forecast_date    = FORECAST_DATE,
)

print(f"[OK] long_df 생성: {len(long_df)}행")
print("\n모델별 행 수:")
display(long_df.groupby(["data_type", "model"]).size().reset_index(name="rows"))
print("\n샘플 (forecast 상위 5행):")
display(long_df[long_df["data_type"] == "forecast"].head())

[OK] long_df 생성: 93행

모델별 행 수:

  data_type     model  rows
0    actual    actual    45
1  forecast       ETS     8
2  forecast  Ensemble     8
3  forecast      LSTM     8
4  forecast   Prophet     8
5  forecast    SARIMA     8
6  forecast     Theta     8

샘플 (forecast 상위 5행):

,ticker,item,date,period,date_month,data_type,model,value,forecast_date,sarima_order,sarima_seasonal_order,sarima_ic_value,created_at
45,AAPL,sale,2026-06-30,None,None,forecast,SARIMA,1.352382e+11,2026-03-27,"(1, 0, 0)","(1, 0, 1, 4)",-49.1557,2026-03-27 00:24:33
46,AAPL,sale,2026-09-30,None,None,forecast,SARIMA,1.456305e+11,2026-03-27,"(1, 0, 0)","(1, 0, 1, 4)",-49.1557,2026-03-27 00:24:33
47,AAPL,sale,2026-12-31,None,None,forecast,SARIMA,1.909660e+11,2026-03-27,"(1, 0, 0)","(1, 0, 1, 4)",-49.1557,2026-03-27 00:24:33
48,AAPL,sale,2027-03-31,None,None,forecast,SARIMA,1.681151e+11,2026-03-27,"(1, 0, 0)","(1, 0, 1, 4)",-49.1557,2026-03-27 00:24:33
49,AAPL,sale,2027-06-30,None,None,forecast,SARIMA,1.595954e+11,2026-03-27,"(1, 0, 0)","(1, 0, 1, 4)",-49.1557,2026-03-27 00:24:33

## Cell 11 · DB 테이블 생성 & 저장 함수 정의

**중복 판정 기준** : `(ticker, item, date, model, forecast_date)`  
→ 이미 존재하는 행은 건드리지 않고, 신규 행만 INSERT

In [11]:
# ── 테이블 CREATE (최초 1회) ──────────────────────────────────
CREATE_TABLE_SQL = f"""
CREATE TABLE IF NOT EXISTS `{DEST_TABLE}` (
    id                    BIGINT       NOT NULL AUTO_INCREMENT,
    ticker                VARCHAR(20)  NOT NULL,
    item                  VARCHAR(30)  NOT NULL,
    date                  DATE         NOT NULL,
    period                VARCHAR(10)  DEFAULT NULL,
    date_month            DATE         DEFAULT NULL,
    data_type             VARCHAR(10)  NOT NULL COMMENT 'actual / forecast',
    model                 VARCHAR(20)  NOT NULL,
    value                 DOUBLE       DEFAULT NULL,
    forecast_date         DATE         NOT NULL,
    sarima_order          VARCHAR(30)  DEFAULT NULL,
    sarima_seasonal_order VARCHAR(30)  DEFAULT NULL,
    sarima_ic_value       DOUBLE       DEFAULT NULL,
    created_at            DATETIME     DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_main (ticker, item, date, model, forecast_date),
    INDEX idx_ticker      (ticker),
    INDEX idx_forecast_dt (forecast_date),
    INDEX idx_model       (model)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
"""

def ensure_table(engine):
    """저장 테이블이 없으면 생성합니다."""
    with engine.begin() as conn:
        conn.execute(text(CREATE_TABLE_SQL))
    print(f"[OK] 테이블 '{DEST_TABLE}' 준비 완료")


def save_to_db(engine, long_df: pd.DataFrame, dest_table: str = DEST_TABLE) -> int:
    """
    long_df 를 DB 에 저장합니다.
    - 중복 기준: (ticker, item, date, model, forecast_date)
    - 기존 행 유지 + 신규 행만 INSERT

    Returns
    -------
    int  : 실제 삽입된 신규 행 수
    """
    if long_df is None or long_df.empty:
        return 0

    # ── 1. 기존 키 조회 ────────────────────────────────────
    ticker      = long_df["ticker"].iloc[0]
    item        = long_df["item"].iloc[0]
    fc_date_val = long_df["forecast_date"].iloc[0]

    check_sql = text(f"""
        SELECT CONCAT(ticker,'|',item,'|',date,'|',model,'|',forecast_date) AS uq_key
        FROM   `{dest_table}`
        WHERE  ticker        = :ticker
          AND  item          = :item
          AND  forecast_date = :fc_date
    """)

    with engine.connect() as conn:
        existing = pd.read_sql(
            check_sql, conn,
            params={"ticker": ticker, "item": item, "fc_date": fc_date_val}
        )
    existing_keys = set(existing["uq_key"].tolist()) if not existing.empty else set()

    # ── 2. 신규 행 필터링 ──────────────────────────────────
    new_df = long_df[
        ~long_df.apply(
            lambda r: f"{r['ticker']}|{r['item']}|{r['date']}|{r['model']}|{r['forecast_date']}"
            in existing_keys,
            axis=1,
        )
    ].copy()

    if new_df.empty:
        log(ticker, f"  [DB] 신규 행 없음 — 스킵")
        return 0

    # ── 3. INSERT ─────────────────────────────────────────
    new_df.to_sql(
        name       = dest_table,
        con        = engine,
        if_exists  = "append",
        index      = False,
        chunksize  = 500,
        method     = "multi",
    )
    log(ticker, f"  [DB] {len(new_df)}행 저장 완료")
    return len(new_df)

print("[OK] ensure_table / save_to_db 함수 정의 완료")

[OK] ensure_table / save_to_db 함수 정의 완료

## Cell 12 · 단일 티커 저장 테스트

In [12]:
# 테이블 생성 (최초 1회)
ensure_table(engine)

# Cell 10 의 long_df 저장
inserted = save_to_db(engine, long_df)
print(f"[OK] {TEST_TICKER} 저장 완료 — 삽입: {inserted}행")

# 저장 확인
with engine.connect() as conn:
    chk = pd.read_sql(
        text(f"""
            SELECT model, data_type, COUNT(*) AS cnt
            FROM   `{DEST_TABLE}`
            WHERE  ticker = :tk AND forecast_date = :fd
            GROUP  BY model, data_type
            ORDER  BY model
        """),
        conn,
        params={"tk": TEST_TICKER, "fd": FORECAST_DATE},
    )
display(chk)

[OK] 테이블 'us_revenue_forecast_data' 준비 완료
[AAPL]   [DB] 93행 저장 완료
[OK] AAPL 저장 완료 — 삽입: 93행

      model data_type  cnt
0    actual    actual   45
1  Ensemble  forecast    8
2       ETS  forecast    8
3      LSTM  forecast    8
4   Prophet  forecast    8
5    SARIMA  forecast    8
6     Theta  forecast    8

## Cell 13 · 배치 실행 (전체 / 특정 티커 / 구간 지정)

### 실행 모드 선택

| 변수 | 설명 |
|------|------|
| `RUN_TICKERS` | `None` → DEFAULT_TICKER_LIST 전체 / `["AAPL", ...]` → 특정 티커만 |
| `TICKER_START` | 리스트 슬라이싱 시작 인덱스 (0부터, `None` = 처음) |
| `TICKER_END`   | 리스트 슬라이싱 끝 인덱스 (None = 끝까지) |
| `RUN_MODELS`   | 사용할 모델 목록 |

### 구간 예시
```python
TICKER_START, TICKER_END = 0,   500   # 1~500번째 티커
TICKER_START, TICKER_END = 500, 1000  # 501~1000번째 티커
TICKER_START, TICKER_END = None, None # 전체
```

### 메모리 전략
> 티커 1개 예측 → 즉시 DB 저장 → `clear_memory()` 호출  
> 이 방식이 배치(20개 누적) 방식보다 피크 메모리가 낮고 중단 시 손실도 최소화됩니다.

In [13]:
`1          # ════════════════════════════════════════════════════════════
#  배치 설정 — 여기를 수정하세요
# ════════════════════════════════════════════════════════════

# ── 특정 티커 지정 (None 이면 아래 구간/전체 사용) ────────────
# Optional[list] = Python 3.9 호환 (3.10+ 의 list | None 대신 사용)
RUN_TICKERS = None          # type: Optional[list]
# RUN_TICKERS = ["AAPL", "MSFT", "NVDA"]   # 특정 티커만

# ── 전체 리스트 구간 지정 (RUN_TICKERS=None 일 때 적용) ──────
TICKER_START = 1500            # type: Optional[int]  # 시작 인덱스 (0부터)
TICKER_END   = 2000          # type: Optional[int]  # 끝 인덱스 (exclusive, None=끝까지)
# 예: 0~499   → START=0,   END=500
# 예: 500~999 → START=500, END=1000
# 예: 전체    → START=None, END=None

# ── 모델 / 항목 / 예측 기간 ───────────────────────────────────
RUN_MODELS  = ALL_MODELS   # 또는 ["SARIMA", "ETS", "Theta"]  (빠른 실행)
RUN_ITEM    = ITEM
RUN_HORIZON = HORIZON
RUN_MIN_OBS = MIN_OBS

# ════════════════════════════════════════════════════════════
#  실행 대상 티커 목록 결정
# ════════════════════════════════════════════════════════════
if RUN_TICKERS is not None:
    tickers = RUN_TICKERS
    print(f"[모드] 특정 티커 지정: {tickers}")
else:
    tickers = DEFAULT_TICKER_LIST[TICKER_START:TICKER_END]
    _s = TICKER_START if TICKER_START is not None else 0
    _e = TICKER_END   if TICKER_END   is not None else len(DEFAULT_TICKER_LIST)
    print(f"[모드] 구간 실행: index {_s} ~ {_e-1}  ({len(tickers)}개)")

total = len(tickers)

# ════════════════════════════════════════════════════════════
#  배치 실행
# ════════════════════════════════════════════════════════════
ensure_table(engine)

success, skipped, errored = 0, 0, 0
skip_list, error_list     = [], []

log("BATCH", "=" * 70)
log("BATCH", f"시작  | 티커 {total}개 | 항목: {RUN_ITEM} | 예측기간: {RUN_HORIZON}분기")
log("BATCH", f"모델  : {RUN_MODELS}")
log("BATCH", f"예측일: {FORECAST_DATE} | min_obs: {RUN_MIN_OBS}")
log("BATCH", "=" * 70)

for i, ticker in enumerate(tickers, 1):
    pct = i / total * 100
    log("PROGRESS", f"[{i:>4}/{total}] ({pct:5.1f}%)  >>  {ticker}")

    # ── STEP 1 : 데이터 추출 ──────────────────────────────
    try:
        _src_df = fetch_financial_series(
            engine, ticker, RUN_ITEM, RUN_MIN_OBS
        )
    except Exception as e:
        log(ticker, f"[SKIP] {e}")
        skipped += 1
        skip_list.append(ticker)
        continue

    _y = _src_df.set_index("date")["value"].copy()
    _y.index = pd.DatetimeIndex(_y.index)
    _y.name  = RUN_ITEM
    log(ticker, f"  {len(_y)}분기 | {_y.index[0].date()} ~ {_y.index[-1].date()}")

    # ── STEP 2 : 예측 ─────────────────────────────────────
    try:
        _fc_results = forecast_one_ticker(_y, ticker, RUN_HORIZON, RUN_MODELS)
    except Exception as e:
        log(ticker, f"[ERROR] 예측: {e}")
        traceback.print_exc()
        errored += 1
        error_list.append(ticker)
        del _src_df, _y
        clear_memory()
        continue

    # ── STEP 3 : 예측 인덱스 생성 ────────────────────────
    _freq     = infer_freq_alias(_y.index)
    _fc_index = make_forecast_index(_y.index[-1], RUN_HORIZON, _freq)

    # ── STEP 4 : Long-format 변환 ─────────────────────────
    try:
        _ldf = build_long_df(
            ticker           = ticker,
            item             = RUN_ITEM,
            src_df           = _src_df,
            forecast_results = _fc_results,
            forecast_index   = _fc_index,
            forecast_date    = FORECAST_DATE,
        )
    except Exception as e:
        log(ticker, f"[ERROR] Long-format 변환: {e}")
        errored += 1
        error_list.append(ticker)
        del _src_df, _y, _fc_results
        clear_memory()
        continue

    # ── STEP 5 : DB 저장 (1개씩 즉시 저장 — 메모리 최소화) ─
    try:
        save_to_db(engine, _ldf)
        success += 1
    except Exception as e:
        log(ticker, f"[ERROR] DB 저장: {e}")
        errored += 1
        error_list.append(ticker)

    # ── STEP 6 : 메모리 해제 ─────────────────────────────
    del _src_df, _y, _fc_results, _ldf
    clear_memory()

# ── 요약 ──────────────────────────────────────────────────
log("BATCH", "=" * 70)
log("BATCH", f"완료 | 성공: {success}  스킵: {skipped}  오류: {errored}  합계: {total}")
if skip_list:  log("BATCH", f"스킵 티커  : {skip_list}")
if error_list: log("BATCH", f"오류 티커  : {error_list}")
log("BATCH", "=" * 70)

[메모리] find_best_sarima_params 실행 후: 1541.41 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1541.41 MB (변화: +0.00 MB)
[AAT]   [SARIMA] 완료  첫값=1.11e+08 (메모리: 1541.4 MB)
[AAT]   [ETS] 시작  (메모리: 1541.4 MB)
[메모리] forecast_ets 실행 전: 1541.41 MB
[메모리] forecast_ets 실행 후: 1541.41 MB (변화: +0.01 MB)
[AAT]   [ETS] 완료  첫값=1.11e+08 (메모리: 1541.4 MB)
[AAT]   [Prophet] 시작  (메모리: 1541.4 MB)
[메모리] forecast_prophet 실행 전: 1541.41 MB

00:43:11 - cmdstanpy - INFO - Chain [1] start processing
00:43:11 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1541.46 MB (변화: +0.05 MB)
[AAT]   [Prophet] 완료  첫값=1.19e+08 (메모리: 1541.5 MB)
[AAT]   [LSTM] 시작  (메모리: 1541.5 MB)
[메모리] forecast_lstm 실행 전: 1541.46 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1541.68 MB (변화: +0.21 MB)
[AAT]   [LSTM] 완료  첫값=1.19e+08 (메모리: 1541.7 MB)
[AAT]   [Theta] 시작  (메모리: 1541.7 MB)
[메모리] forecast_theta 실행 전: 1541.68 MB
[메모리] forecast_theta 실행 후: 1541.68 MB (변화: +0.00 MB)
[AAT]   [Theta] 완료  첫값=1.10e+08 (메모리: 1541.7 MB)
[AAT]   [DB] 93행 저장 완료
[PROGRESS] [  56/500] ( 11.2%)  >>  CRTO
[CRTO]   45분기 | 2015-03-31 ~ 2026-03-31
[CRTO]   [SARIMA] 시작  (메모리: 1541.7 MB)
[메모리] forecast_sarima 실행 전: 1541.68 MB
[메모리] find_best_sarima_params 실행 전: 1541.68 MB
[메모리] find_best_sarima_params 실행 후: 1541.68 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1541.68 MB (변화: +0.00 MB)
[CRTO]   [SARIMA] 완료  첫값=5.54e+08 (메모리: 1541.7 MB)
[CRTO]   [ETS] 시작  (메모리: 1541.7 MB)
[메모리] forecast_ets 실행 전: 1541.68 MB
[메모리] forecast_ets 실행 후: 1541.68 MB (변화: +0.00 MB)
[CRTO]   [ETS] 완료  첫값=5.15e+08 (메모리: 1541.7 MB)
[CRTO]   [Prophet] 시작  (메모리: 1541.7 MB)

00:43:33 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1541.68 MB

00:43:33 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1541.77 MB (변화: +0.09 MB)
[CRTO]   [Prophet] 완료  첫값=5.38e+08 (메모리: 1541.8 MB)
[CRTO]   [LSTM] 시작  (메모리: 1541.8 MB)
[메모리] forecast_lstm 실행 전: 1541.77 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1542.16 MB (변화: +0.40 MB)
[CRTO]   [LSTM] 완료  첫값=4.74e+08 (메모리: 1542.2 MB)
[CRTO]   [Theta] 시작  (메모리: 1542.2 MB)
[메모리] forecast_theta 실행 전: 1542.16 MB
[메모리] forecast_theta 실행 후: 1542.16 MB (변화: +0.00 MB)
[CRTO]   [Theta] 완료  첫값=5.24e+08 (메모리: 1542.2 MB)
[CRTO]   [DB] 93행 저장 완료
[PROGRESS] [  57/500] ( 11.4%)  >>  VLRS
[VLRS]   45분기 | 2015-03-31 ~ 2026-03-31
[VLRS]   [SARIMA] 시작  (메모리: 1542.2 MB)
[메모리] forecast_sarima 실행 전: 1542.16 MB
[메모리] find_best_sarima_params 실행 전: 1542.16 MB
[메모리] find_best_sarima_params 실행 후: 1542.16 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1542.16 MB (변화: +0.00 MB)
[VLRS]   [SARIMA] 완료  첫값=8.69e+08 (메모리: 1542.2 MB)
[VLRS]   [ETS] 시작  (메모리: 1542.2 MB)
[메모리] forecast_ets 실행 전: 1542.16 MB
[메모리] forecast_ets 실행 후: 1542.17 MB (변화: +0.00 MB)
[VLRS]   [ETS] 완료  첫값=7.06e+08 (메모리: 1542.2 MB)
[VLRS]   [Prophet] 시작  (메모리: 1542.2 MB)

00:43:50 - cmdstanpy - INFO - Chain [1] start processing
00:43:50 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1542.17 MB
[메모리] forecast_prophet 실행 후: 1542.22 MB (변화: +0.05 MB)
[VLRS]   [Prophet] 완료  첫값=8.53e+08 (메모리: 1542.2 MB)
[VLRS]   [LSTM] 시작  (메모리: 1542.2 MB)
[메모리] forecast_lstm 실행 전: 1542.22 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1543.23 MB (변화: +1.01 MB)
[VLRS]   [LSTM] 완료  첫값=7.83e+08 (메모리: 1543.2 MB)
[VLRS]   [Theta] 시작  (메모리: 1543.2 MB)
[메모리] forecast_theta 실행 전: 1543.23 MB
[메모리] forecast_theta 실행 후: 1543.23 MB (변화: +0.00 MB)
[VLRS]   [Theta] 완료  첫값=6.81e+08 (메모리: 1543.2 MB)
[VLRS]   [DB] 93행 저장 완료
[PROGRESS] [  58/500] ( 11.6%)  >>  SIFY
[SIFY]   45분기 | 2015-03-31 ~ 2026-03-31
[SIFY]   [SARIMA] 시작  (메모리: 1543.2 MB)
[메모리] forecast_sarima 실행 전: 1543.23 MB
[메모리] find_best_sarima_params 실행 전: 1543.23 MB
[메모리] find_best_sarima_params 실행 후: 1543.23 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1543.23 MB (변화: +0.00 MB)
[SIFY]   [SARIMA] 완료  첫값=1.20e+10 (메모리: 1543.2 MB)
[SIFY]   [ETS] 시작  (메모리: 1543.2 MB)
[메모리] forecast_ets 실행 전: 1543.23 MB
[메모리] forecast_ets 실행 후: 1543.23 MB (변화: +0.00 MB)
[SIFY]   [ETS] 완료  첫값=1.15e+10 (메모리: 1543.2 MB)
[SIFY]   [Prophet] 시작  (메모리: 1543.2 MB)

00:44:09 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1543.23 MB

00:44:09 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1543.35 MB (변화: +0.11 MB)
[SIFY]   [Prophet] 완료  첫값=1.14e+10 (메모리: 1543.3 MB)
[SIFY]   [LSTM] 시작  (메모리: 1543.3 MB)
[메모리] forecast_lstm 실행 전: 1543.35 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1542.93 MB (변화: -0.41 MB)
[SIFY]   [LSTM] 완료  첫값=1.22e+10 (메모리: 1542.9 MB)
[SIFY]   [Theta] 시작  (메모리: 1542.9 MB)
[메모리] forecast_theta 실행 전: 1542.93 MB
[메모리] forecast_theta 실행 후: 1542.93 MB (변화: +0.00 MB)
[SIFY]   [Theta] 완료  첫값=1.12e+10 (메모리: 1542.9 MB)
[SIFY]   [DB] 93행 저장 완료
[PROGRESS] [  59/500] ( 11.8%)  >>  CAPR
[CAPR]   45분기 | 2015-03-31 ~ 2026-03-31
[CAPR]   [SARIMA] 시작  (메모리: 1542.9 MB)
[메모리] forecast_sarima 실행 전: 1542.94 MB
[메모리] find_best_sarima_params 실행 전: 1542.94 MB
[메모리] find_best_sarima_params 실행 후: 1542.94 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1542.94 MB (변화: +0.00 MB)
[CAPR]   [SARIMA] 완료  첫값=-1.38e+07 (메모리: 1542.9 MB)
[CAPR]   [ETS] 시작  (메모리: 1542.9 MB)
[메모리] forecast_ets 실행 전: 1542.94 MB
[메모리] forecast_ets 실행 후: 1542.95 MB (변화: +0.01 MB)
[CAPR]   [ETS] 완료  첫값=-5.37e+05 (메모리: 1542.9 MB)
[CAPR]   [Prophet] 시작  (메모리: 1542.9 MB)
[메모리] forecast_prophet 실행 전: 1542.95 MB

00:44:32 - cmdstanpy - INFO - Chain [1] start processing
00:44:32 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1543.38 MB (변화: +0.43 MB)
[CAPR]   [Prophet] 완료  첫값=2.91e+06 (메모리: 1543.4 MB)
[CAPR]   [LSTM] 시작  (메모리: 1543.4 MB)
[메모리] forecast_lstm 실행 전: 1543.38 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1543.02 MB (변화: -0.36 MB)
[CAPR]   [LSTM] 완료  첫값=2.36e+06 (메모리: 1543.0 MB)
[CAPR]   [Theta] 시작  (메모리: 1543.0 MB)
[메모리] forecast_theta 실행 전: 1543.02 MB
[메모리] forecast_theta 실행 후: 1543.02 MB (변화: +0.00 MB)
[CAPR]   [Theta] 완료  첫값=-1.13e+05 (메모리: 1543.0 MB)
[CAPR]   [DB] 93행 저장 완료
[PROGRESS] [  60/500] ( 12.0%)  >>  UAN
[UAN]   45분기 | 2015-03-31 ~ 2026-03-31
[UAN]   [SARIMA] 시작  (메모리: 1543.0 MB)
[메모리] forecast_sarima 실행 전: 1543.02 MB
[메모리] find_best_sarima_params 실행 전: 1543.02 MB
[메모리] find_best_sarima_params 실행 후: 1543.02 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1543.02 MB (변화: +0.00 MB)
[UAN]   [SARIMA] 완료  첫값=1.79e+08 (메모리: 1543.0 MB)
[UAN]   [ETS] 시작  (메모리: 1543.0 MB)
[메모리] forecast_ets 실행 전: 1543.02 MB
[메모리] forecast_ets 실행 후: 1543.02 MB (변화: +0.01 MB)
[UAN]   [ETS] 완료  첫값=2.01e+08 (메모리: 1543.0 MB)
[UAN]   [Prophet] 시작  (메모리: 1543.0 MB)

00:44:49 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1543.02 MB

00:44:49 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1543.07 MB (변화: +0.04 MB)
[UAN]   [Prophet] 완료  첫값=1.79e+08 (메모리: 1543.1 MB)
[UAN]   [LSTM] 시작  (메모리: 1543.1 MB)
[메모리] forecast_lstm 실행 전: 1543.07 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1544.36 MB (변화: +1.29 MB)
[UAN]   [LSTM] 완료  첫값=1.28e+08 (메모리: 1544.4 MB)
[UAN]   [Theta] 시작  (메모리: 1544.4 MB)
[메모리] forecast_theta 실행 전: 1544.36 MB
[메모리] forecast_theta 실행 후: 1544.36 MB (변화: +0.00 MB)
[UAN]   [Theta] 완료  첫값=2.07e+08 (메모리: 1544.4 MB)
[UAN]   [DB] 93행 저장 완료
[PROGRESS] [  61/500] ( 12.2%)  >>  ALNT
[ALNT]   45분기 | 2015-03-31 ~ 2026-03-31
[ALNT]   [SARIMA] 시작  (메모리: 1544.4 MB)
[메모리] forecast_sarima 실행 전: 1544.36 MB
[메모리] find_best_sarima_params 실행 전: 1544.36 MB
[메모리] find_best_sarima_params 실행 후: 1544.36 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1544.36 MB (변화: +0.00 MB)
[ALNT]   [SARIMA] 완료  첫값=1.41e+08 (메모리: 1544.4 MB)
[ALNT]   [ETS] 시작  (메모리: 1544.4 MB)
[메모리] forecast_ets 실행 전: 1544.36 MB
[메모리] forecast_ets 실행 후: 1544.36 MB (변화: +0.00 MB)
[ALNT]   [ETS] 완료  첫값=1.42e+08 (메모리: 1544.4 MB)
[ALNT]   [Prophet] 시작  (메모리: 1544.4 MB)

00:45:09 - cmdstanpy - INFO - Chain [1] start processing
00:45:10 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1544.36 MB
[메모리] forecast_prophet 실행 후: 1544.40 MB (변화: +0.04 MB)
[ALNT]   [Prophet] 완료  첫값=1.52e+08 (메모리: 1544.4 MB)
[ALNT]   [LSTM] 시작  (메모리: 1544.4 MB)
[메모리] forecast_lstm 실행 전: 1544.40 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1545.72 MB (변화: +1.32 MB)
[ALNT]   [LSTM] 완료  첫값=1.50e+08 (메모리: 1545.7 MB)
[ALNT]   [Theta] 시작  (메모리: 1545.7 MB)
[메모리] forecast_theta 실행 전: 1545.72 MB
[메모리] forecast_theta 실행 후: 1545.72 MB (변화: +0.00 MB)
[ALNT]   [Theta] 완료  첫값=1.38e+08 (메모리: 1545.7 MB)
[ALNT]   [DB] 93행 저장 완료
[PROGRESS] [  62/500] ( 12.4%)  >>  CDNA
[CDNA]   45분기 | 2015-03-31 ~ 2026-03-31
[CDNA]   [SARIMA] 시작  (메모리: 1545.7 MB)
[메모리] forecast_sarima 실행 전: 1545.72 MB
[메모리] find_best_sarima_params 실행 전: 1545.72 MB
[메모리] find_best_sarima_params 실행 후: 1545.72 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1545.72 MB (변화: +0.00 MB)
[CDNA]   [SARIMA] 완료  첫값=9.82e+07 (메모리: 1545.7 MB)
[CDNA]   [ETS] 시작  (메모리: 1545.7 MB)
[메모리] forecast_ets 실행 전: 1545.72 MB
[메모리] forecast_ets 실행 후: 1545.73 MB (변화: +0.01 MB)
[CDNA]   [ETS] 완료  첫값=1.13e+08 (메모리: 1545.7 MB)
[CDNA]   [Prophet] 시작  (메모리: 1545.7 MB)

00:45:31 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1545.73 MB

00:45:31 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1546.47 MB (변화: +0.75 MB)
[CDNA]   [Prophet] 완료  첫값=1.05e+08 (메모리: 1546.5 MB)
[CDNA]   [LSTM] 시작  (메모리: 1546.5 MB)
[메모리] forecast_lstm 실행 전: 1546.47 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1546.11 MB (변화: -0.36 MB)
[CDNA]   [LSTM] 완료  첫값=9.74e+07 (메모리: 1546.1 MB)
[CDNA]   [Theta] 시작  (메모리: 1546.1 MB)
[메모리] forecast_theta 실행 전: 1546.11 MB
[메모리] forecast_theta 실행 후: 1546.11 MB (변화: +0.00 MB)
[CDNA]   [Theta] 완료  첫값=1.11e+08 (메모리: 1546.1 MB)
[CDNA]   [DB] 93행 저장 완료
[PROGRESS] [  63/500] ( 12.6%)  >>  SP
[SP]   45분기 | 2015-03-31 ~ 2026-03-31
[SP]   [SARIMA] 시작  (메모리: 1546.1 MB)
[메모리] forecast_sarima 실행 전: 1546.11 MB
[메모리] find_best_sarima_params 실행 전: 1546.11 MB
[메모리] find_best_sarima_params 실행 후: 1546.11 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1546.11 MB (변화: +0.00 MB)
[SP]   [SARIMA] 완료  첫값=4.52e+08 (메모리: 1546.1 MB)
[SP]   [ETS] 시작  (메모리: 1546.1 MB)
[메모리] forecast_ets 실행 전: 1546.11 MB
[메모리] forecast_ets 실행 후: 1546.12 MB (변화: +0.01 MB)
[SP]   [ETS] 완료  첫값=4.33e+08 (메모리: 1546.1 MB)
[SP]   [Prophet] 시작  (메모리: 1546.1 MB)

00:45:52 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1546.12 MB

00:45:52 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1546.16 MB (변화: +0.04 MB)
[SP]   [Prophet] 완료  첫값=4.19e+08 (메모리: 1546.2 MB)
[SP]   [LSTM] 시작  (메모리: 1546.2 MB)
[메모리] forecast_lstm 실행 전: 1546.16 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1545.92 MB (변화: -0.24 MB)
[SP]   [LSTM] 완료  첫값=4.17e+08 (메모리: 1545.9 MB)
[SP]   [Theta] 시작  (메모리: 1545.9 MB)
[메모리] forecast_theta 실행 전: 1545.92 MB
[메모리] forecast_theta 실행 후: 1545.92 MB (변화: +0.00 MB)
[SP]   [Theta] 완료  첫값=4.52e+08 (메모리: 1545.9 MB)
[SP]   [DB] 93행 저장 완료
[PROGRESS] [  64/500] ( 12.8%)  >>  DEA
[DEA]   45분기 | 2015-03-31 ~ 2026-03-31
[DEA]   [SARIMA] 시작  (메모리: 1545.9 MB)
[메모리] forecast_sarima 실행 전: 1545.92 MB
[메모리] find_best_sarima_params 실행 전: 1545.92 MB
[메모리] find_best_sarima_params 실행 후: 1545.92 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1545.92 MB (변화: +0.00 MB)
[DEA]   [SARIMA] 완료  첫값=8.70e+07 (메모리: 1545.9 MB)
[DEA]   [ETS] 시작  (메모리: 1545.9 MB)
[메모리] forecast_ets 실행 전: 1545.92 MB
[메모리] forecast_ets 실행 후: 1545.93 MB (변화: +0.00 MB)
[DEA]   [ETS] 완료  첫값=9.11e+07 (메모리: 1545.9 MB)
[DEA]   [Prophet] 시작  (메모리: 1545.9 MB)

00:46:13 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1545.93 MB

00:46:13 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1545.97 MB (변화: +0.04 MB)
[DEA]   [Prophet] 완료  첫값=8.58e+07 (메모리: 1546.0 MB)
[DEA]   [LSTM] 시작  (메모리: 1546.0 MB)
[메모리] forecast_lstm 실행 전: 1545.97 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1546.90 MB (변화: +0.93 MB)
[DEA]   [LSTM] 완료  첫값=8.51e+07 (메모리: 1546.9 MB)
[DEA]   [Theta] 시작  (메모리: 1546.9 MB)
[메모리] forecast_theta 실행 전: 1546.90 MB
[메모리] forecast_theta 실행 후: 1546.90 MB (변화: +0.00 MB)
[DEA]   [Theta] 완료  첫값=8.77e+07 (메모리: 1546.9 MB)
[DEA]   [DB] 93행 저장 완료
[PROGRESS] [  65/500] ( 13.0%)  >>  CSR
[CSR]   45분기 | 2015-03-31 ~ 2026-03-31
[CSR]   [SARIMA] 시작  (메모리: 1546.9 MB)
[메모리] forecast_sarima 실행 전: 1546.90 MB
[메모리] find_best_sarima_params 실행 전: 1546.90 MB
[메모리] find_best_sarima_params 실행 후: 1546.90 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1546.90 MB (변화: +0.00 MB)
[CSR]   [SARIMA] 완료  첫값=7.14e+07 (메모리: 1546.9 MB)
[CSR]   [ETS] 시작  (메모리: 1546.9 MB)
[메모리] forecast_ets 실행 전: 1546.90 MB
[메모리] forecast_ets 실행 후: 1546.90 MB (변화: +0.00 MB)
[CSR]   [ETS] 완료  첫값=7.11e+07 (메모리: 1546.9 MB)
[CSR]   [Prophet] 시작  (메모리: 1546.9 MB)

00:46:37 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1546.90 MB

00:46:37 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1546.96 MB (변화: +0.05 MB)
[CSR]   [Prophet] 완료  첫값=6.60e+07 (메모리: 1547.0 MB)
[CSR]   [LSTM] 시작  (메모리: 1547.0 MB)
[메모리] forecast_lstm 실행 전: 1546.96 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1546.89 MB (변화: -0.07 MB)
[CSR]   [LSTM] 완료  첫값=6.57e+07 (메모리: 1546.9 MB)
[CSR]   [Theta] 시작  (메모리: 1546.9 MB)
[메모리] forecast_theta 실행 전: 1546.89 MB
[메모리] forecast_theta 실행 후: 1546.89 MB (변화: +0.00 MB)
[CSR]   [Theta] 완료  첫값=7.10e+07 (메모리: 1546.9 MB)
[CSR]   [DB] 93행 저장 완료
[PROGRESS] [  66/500] ( 13.2%)  >>  CIM
[CIM]   45분기 | 2015-03-31 ~ 2026-03-31
[CIM]   [SARIMA] 시작  (메모리: 1546.9 MB)
[메모리] forecast_sarima 실행 전: 1546.89 MB
[메모리] find_best_sarima_params 실행 전: 1546.89 MB
[메모리] find_best_sarima_params 실행 후: 1546.90 MB (변화: +0.01 MB)
[메모리] forecast_sarima 실행 후: 1546.90 MB (변화: +0.01 MB)
[CIM]   [SARIMA] 완료  첫값=9.46e+07 (메모리: 1546.9 MB)
[CIM]   [ETS] 시작  (메모리: 1546.9 MB)
[메모리] forecast_ets 실행 전: 1546.90 MB
[메모리] forecast_ets 실행 후: 1546.91 MB (변화: +0.01 MB)
[CIM]   [ETS] 완료  첫값=3.75e+07 (메모리: 1546.9 MB)
[CIM]   [Prophet] 시작  (메모리: 1546.9 MB)

00:46:56 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1546.91 MB

00:46:56 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1546.93 MB (변화: +0.02 MB)
[CIM]   [Prophet] 완료  첫값=3.07e+07 (메모리: 1546.9 MB)
[CIM]   [LSTM] 시작  (메모리: 1546.9 MB)
[메모리] forecast_lstm 실행 전: 1546.93 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1547.26 MB (변화: +0.33 MB)
[CIM]   [LSTM] 완료  첫값=6.10e+07 (메모리: 1547.3 MB)
[CIM]   [Theta] 시작  (메모리: 1547.3 MB)
[메모리] forecast_theta 실행 전: 1547.26 MB
[메모리] forecast_theta 실행 후: 1547.26 MB (변화: +0.00 MB)
[CIM]   [Theta] 완료  첫값=4.38e+07 (메모리: 1547.3 MB)
[CIM]   [DB] 93행 저장 완료
[PROGRESS] [  67/500] ( 13.4%)  >>  SBGI
[SBGI]   45분기 | 2015-03-31 ~ 2026-03-31
[SBGI]   [SARIMA] 시작  (메모리: 1547.3 MB)
[메모리] forecast_sarima 실행 전: 1547.26 MB
[메모리] find_best_sarima_params 실행 전: 1547.26 MB
[메모리] find_best_sarima_params 실행 후: 1547.26 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1547.26 MB (변화: +0.00 MB)
[SBGI]   [SARIMA] 완료  첫값=7.73e+08 (메모리: 1547.3 MB)
[SBGI]   [ETS] 시작  (메모리: 1547.3 MB)
[메모리] forecast_ets 실행 전: 1547.26 MB
[메모리] forecast_ets 실행 후: 1547.27 MB (변화: +0.00 MB)
[SBGI]   [ETS] 완료  첫값=7.65e+08 (메모리: 1547.3 MB)
[SBGI]   [Prophet] 시작  (메모리: 1547.3 MB)

00:47:15 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1547.27 MB

00:47:15 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1547.30 MB (변화: +0.04 MB)
[SBGI]   [Prophet] 완료  첫값=1.07e+09 (메모리: 1547.3 MB)
[SBGI]   [LSTM] 시작  (메모리: 1547.3 MB)
[메모리] forecast_lstm 실행 전: 1547.30 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1548.25 MB (변화: +0.95 MB)
[SBGI]   [LSTM] 완료  첫값=9.06e+08 (메모리: 1548.3 MB)
[SBGI]   [Theta] 시작  (메모리: 1548.3 MB)
[메모리] forecast_theta 실행 전: 1548.25 MB
[메모리] forecast_theta 실행 후: 1548.25 MB (변화: +0.00 MB)
[SBGI]   [Theta] 완료  첫값=7.56e+08 (메모리: 1548.3 MB)
[SBGI]   [DB] 93행 저장 완료
[PROGRESS] [  68/500] ( 13.6%)  >>  GILT
[GILT]   45분기 | 2015-03-31 ~ 2026-03-31
[GILT]   [SARIMA] 시작  (메모리: 1548.3 MB)
[메모리] forecast_sarima 실행 전: 1548.25 MB
[메모리] find_best_sarima_params 실행 전: 1548.25 MB
[메모리] find_best_sarima_params 실행 후: 1548.25 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1548.25 MB (변화: +0.00 MB)
[GILT]   [SARIMA] 완료  첫값=1.36e+08 (메모리: 1548.3 MB)
[GILT]   [ETS] 시작  (메모리: 1548.3 MB)
[메모리] forecast_ets 실행 전: 1548.25 MB
[메모리] forecast_ets 실행 후: 1548.26 MB (변화: +0.01 MB)
[GILT]   [ETS] 완료  첫값=1.44e+08 (메모리: 1548.3 MB)
[GILT]   [Prophet] 시작  (메모리: 1548.3 MB)

00:47:38 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1548.26 MB

00:47:38 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1548.30 MB (변화: +0.04 MB)
[GILT]   [Prophet] 완료  첫값=8.86e+07 (메모리: 1548.3 MB)
[GILT]   [LSTM] 시작  (메모리: 1548.3 MB)
[메모리] forecast_lstm 실행 전: 1548.30 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1548.59 MB (변화: +0.30 MB)
[GILT]   [LSTM] 완료  첫값=1.07e+08 (메모리: 1548.6 MB)
[GILT]   [Theta] 시작  (메모리: 1548.6 MB)
[메모리] forecast_theta 실행 전: 1548.59 MB
[메모리] forecast_theta 실행 후: 1548.59 MB (변화: +0.00 MB)
[GILT]   [Theta] 완료  첫값=1.37e+08 (메모리: 1548.6 MB)
[GILT]   [DB] 93행 저장 완료
[PROGRESS] [  69/500] ( 13.8%)  >>  DAKT
[DAKT]   45분기 | 2015-03-31 ~ 2026-03-31
[DAKT]   [SARIMA] 시작  (메모리: 1548.6 MB)
[메모리] forecast_sarima 실행 전: 1548.60 MB
[메모리] find_best_sarima_params 실행 전: 1548.60 MB
[메모리] find_best_sarima_params 실행 후: 1548.61 MB (변화: +0.01 MB)
[메모리] forecast_sarima 실행 후: 1548.61 MB (변화: +0.01 MB)
[DAKT]   [SARIMA] 완료  첫값=2.49e+08 (메모리: 1548.6 MB)
[DAKT]   [ETS] 시작  (메모리: 1548.6 MB)
[메모리] forecast_ets 실행 전: 1548.61 MB
[메모리] forecast_ets 실행 후: 1548.61 MB (변화: +0.00 MB)
[DAKT]   [ETS] 완료  첫값=2.66e+08 (메모리: 1548.6 MB)
[DAKT]   [Prophet] 시작  (메모리: 1548.6 MB)

00:48:02 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1548.61 MB

00:48:02 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1548.67 MB (변화: +0.06 MB)
[DAKT]   [Prophet] 완료  첫값=2.01e+08 (메모리: 1548.7 MB)
[DAKT]   [LSTM] 시작  (메모리: 1548.7 MB)
[메모리] forecast_lstm 실행 전: 1548.67 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1548.49 MB (변화: -0.18 MB)
[DAKT]   [LSTM] 완료  첫값=2.49e+08 (메모리: 1548.5 MB)
[DAKT]   [Theta] 시작  (메모리: 1548.5 MB)
[메모리] forecast_theta 실행 전: 1548.49 MB
[메모리] forecast_theta 실행 후: 1548.49 MB (변화: +0.00 MB)
[DAKT]   [Theta] 완료  첫값=2.61e+08 (메모리: 1548.5 MB)
[DAKT]   [DB] 93행 저장 완료
[PROGRESS] [  70/500] ( 14.0%)  >>  CMP
[CMP]   45분기 | 2015-03-31 ~ 2026-03-31
[CMP]   [SARIMA] 시작  (메모리: 1548.5 MB)
[메모리] forecast_sarima 실행 전: 1548.49 MB
[메모리] find_best_sarima_params 실행 전: 1548.49 MB
[메모리] find_best_sarima_params 실행 후: 1548.49 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1548.49 MB (변화: +0.00 MB)
[CMP]   [SARIMA] 완료  첫값=1.97e+08 (메모리: 1548.5 MB)
[CMP]   [ETS] 시작  (메모리: 1548.5 MB)
[메모리] forecast_ets 실행 전: 1548.49 MB
[메모리] forecast_ets 실행 후: 1548.49 MB (변화: +0.00 MB)
[CMP]   [ETS] 완료  첫값=2.10e+08 (메모리: 1548.5 MB)
[CMP]   [Prophet] 시작  (메모리: 1548.5 MB)

00:48:20 - cmdstanpy - INFO - Chain [1] start processing
00:48:20 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1548.49 MB
[메모리] forecast_prophet 실행 후: 1548.80 MB (변화: +0.31 MB)
[CMP]   [Prophet] 완료  첫값=3.21e+08 (메모리: 1548.8 MB)
[CMP]   [LSTM] 시작  (메모리: 1548.8 MB)
[메모리] forecast_lstm 실행 전: 1548.80 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1548.64 MB (변화: -0.15 MB)
[CMP]   [LSTM] 완료  첫값=3.01e+08 (메모리: 1548.6 MB)
[CMP]   [Theta] 시작  (메모리: 1548.6 MB)
[메모리] forecast_theta 실행 전: 1548.64 MB
[메모리] forecast_theta 실행 후: 1548.64 MB (변화: +0.00 MB)
[CMP]   [Theta] 완료  첫값=2.11e+08 (메모리: 1548.6 MB)
[CMP]   [DB] 93행 저장 완료
[PROGRESS] [  71/500] ( 14.2%)  >>  HIBB
[HIBB]   45분기 | 2015-03-31 ~ 2026-03-31
[HIBB]   [SARIMA] 시작  (메모리: 1548.6 MB)
[메모리] forecast_sarima 실행 전: 1548.64 MB
[메모리] find_best_sarima_params 실행 전: 1548.64 MB
[메모리] find_best_sarima_params 실행 후: 1548.64 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1548.64 MB (변화: +0.00 MB)
[HIBB]   [SARIMA] 완료  첫값=4.71e+08 (메모리: 1548.6 MB)
[HIBB]   [ETS] 시작  (메모리: 1548.6 MB)
[메모리] forecast_ets 실행 전: 1548.64 MB
[메모리] forecast_ets 실행 후: 1548.65 MB (변화: +0.01 MB)
[HIBB]   [ETS] 완료  첫값=4.91e+08 (메모리: 1548.7 MB)
[HIBB]   [Prophet] 시작  (메모리: 1548.7 MB)

00:48:39 - cmdstanpy - INFO - Chain [1] start processing
00:48:39 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1548.65 MB
[메모리] forecast_prophet 실행 후: 1548.32 MB (변화: -0.34 MB)
[HIBB]   [Prophet] 완료  첫값=4.92e+08 (메모리: 1548.3 MB)
[HIBB]   [LSTM] 시작  (메모리: 1548.3 MB)
[메모리] forecast_lstm 실행 전: 1548.32 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1550.80 MB (변화: +2.49 MB)
[HIBB]   [LSTM] 완료  첫값=4.53e+08 (메모리: 1550.8 MB)
[HIBB]   [Theta] 시작  (메모리: 1550.8 MB)
[메모리] forecast_theta 실행 전: 1550.80 MB
[메모리] forecast_theta 실행 후: 1550.80 MB (변화: +0.00 MB)
[HIBB]   [Theta] 완료  첫값=4.95e+08 (메모리: 1550.8 MB)
[HIBB]   [DB] 93행 저장 완료
[PROGRESS] [  72/500] ( 14.4%)  >>  MMI
[MMI]   45분기 | 2015-03-31 ~ 2026-03-31
[MMI]   [SARIMA] 시작  (메모리: 1550.8 MB)
[메모리] forecast_sarima 실행 전: 1550.81 MB
[메모리] find_best_sarima_params 실행 전: 1550.81 MB
[메모리] find_best_sarima_params 실행 후: 1550.81 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1550.81 MB (변화: +0.00 MB)
[MMI]   [SARIMA] 완료  첫값=2.65e+08 (메모리: 1550.8 MB)
[MMI]   [ETS] 시작  (메모리: 1550.8 MB)
[메모리] forecast_ets 실행 전: 1550.81 MB
[메모리] forecast_ets 실행 후: 1550.82 MB (변화: +0.01 MB)
[MMI]   [ETS] 완료  첫값=2.78e+08 (메모리: 1550.8 MB)
[MMI]   [Prophet] 시작  (메모리: 1550.8 MB)

00:49:00 - cmdstanpy - INFO - Chain [1] start processing
00:49:00 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1550.82 MB
[메모리] forecast_prophet 실행 후: 1550.87 MB (변화: +0.05 MB)
[MMI]   [Prophet] 완료  첫값=2.33e+08 (메모리: 1550.9 MB)
[MMI]   [LSTM] 시작  (메모리: 1550.9 MB)
[메모리] forecast_lstm 실행 전: 1550.87 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1550.32 MB (변화: -0.54 MB)
[MMI]   [LSTM] 완료  첫값=1.94e+08 (메모리: 1550.3 MB)
[MMI]   [Theta] 시작  (메모리: 1550.3 MB)
[메모리] forecast_theta 실행 전: 1550.32 MB
[메모리] forecast_theta 실행 후: 1550.32 MB (변화: +0.00 MB)
[MMI]   [Theta] 완료  첫값=2.39e+08 (메모리: 1550.3 MB)
[MMI]   [DB] 93행 저장 완료
[PROGRESS] [  73/500] ( 14.6%)  >>  NEGG
[NEGG]   42분기 | 2015-12-31 ~ 2026-03-31
[NEGG]   [SARIMA] 시작  (메모리: 1550.3 MB)
[메모리] forecast_sarima 실행 전: 1550.32 MB
[메모리] find_best_sarima_params 실행 전: 1550.32 MB
[메모리] find_best_sarima_params 실행 후: 1550.33 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1550.33 MB (변화: +0.00 MB)
[NEGG]   [SARIMA] 완료  첫값=3.03e+08 (메모리: 1550.3 MB)
[NEGG]   [ETS] 시작  (메모리: 1550.3 MB)
[메모리] forecast_ets 실행 전: 1550.33 MB
[메모리] forecast_ets 실행 후: 1550.34 MB (변화: +0.01 MB)
[NEGG]   [ETS] 완료  첫값=2.48e+08 (메모리: 1550.3 MB)
[NEGG]   [Prophet] 시작  (메모리: 1550.3 MB)

00:49:17 - cmdstanpy - INFO - Chain [1] start processing
00:49:17 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1550.34 MB
[메모리] forecast_prophet 실행 후: 1550.37 MB (변화: +0.04 MB)
[NEGG]   [Prophet] 완료  첫값=3.01e+08 (메모리: 1550.4 MB)
[NEGG]   [LSTM] 시작  (메모리: 1550.4 MB)
[메모리] forecast_lstm 실행 전: 1550.37 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1550.14 MB (변화: -0.23 MB)
[NEGG]   [LSTM] 완료  첫값=3.87e+08 (메모리: 1550.1 MB)
[NEGG]   [Theta] 시작  (메모리: 1550.1 MB)
[메모리] forecast_theta 실행 전: 1550.14 MB
[메모리] forecast_theta 실행 후: 1550.14 MB (변화: +0.00 MB)
[NEGG]   [Theta] 완료  첫값=3.65e+08 (메모리: 1550.1 MB)
[NEGG]   [DB] 90행 저장 완료
[PROGRESS] [  74/500] ( 14.8%)  >>  TROX
[TROX]   45분기 | 2015-03-31 ~ 2026-03-31
[TROX]   [SARIMA] 시작  (메모리: 1550.1 MB)
[메모리] forecast_sarima 실행 전: 1550.14 MB
[메모리] find_best_sarima_params 실행 전: 1550.14 MB
[메모리] find_best_sarima_params 실행 후: 1550.14 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1550.14 MB (변화: +0.00 MB)
[TROX]   [SARIMA] 완료  첫값=6.99e+08 (메모리: 1550.1 MB)
[TROX]   [ETS] 시작  (메모리: 1550.1 MB)
[메모리] forecast_ets 실행 전: 1550.14 MB
[메모리] forecast_ets 실행 후: 1550.15 MB (변화: +0.01 MB)
[TROX]   [ETS] 완료  첫값=8.01e+08 (메모리: 1550.2 MB)
[TROX]   [Prophet] 시작  (메모리: 1550.2 MB)
[메모리] forecast_prophet 실행 전: 1550.15 MB

00:49:39 - cmdstanpy - INFO - Chain [1] start processing
00:49:39 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1550.21 MB (변화: +0.06 MB)
[TROX]   [Prophet] 완료  첫값=8.40e+08 (메모리: 1550.2 MB)
[TROX]   [LSTM] 시작  (메모리: 1550.2 MB)
[메모리] forecast_lstm 실행 전: 1550.21 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1548.57 MB (변화: -1.65 MB)
[TROX]   [LSTM] 완료  첫값=6.98e+08 (메모리: 1548.6 MB)
[TROX]   [Theta] 시작  (메모리: 1548.6 MB)
[메모리] forecast_theta 실행 전: 1548.57 MB
[메모리] forecast_theta 실행 후: 1548.57 MB (변화: +0.00 MB)
[TROX]   [Theta] 완료  첫값=7.76e+08 (메모리: 1548.6 MB)
[TROX]   [DB] 93행 저장 완료
[PROGRESS] [  75/500] ( 15.0%)  >>  PDM
[PDM]   45분기 | 2015-03-31 ~ 2026-03-31
[PDM]   [SARIMA] 시작  (메모리: 1548.6 MB)
[메모리] forecast_sarima 실행 전: 1548.57 MB
[메모리] find_best_sarima_params 실행 전: 1548.57 MB
[메모리] find_best_sarima_params 실행 후: 1548.58 MB (변화: +0.01 MB)
[메모리] forecast_sarima 실행 후: 1548.58 MB (변화: +0.01 MB)
[PDM]   [SARIMA] 완료  첫값=-7.06e+07 (메모리: 1548.6 MB)
[PDM]   [ETS] 시작  (메모리: 1548.6 MB)
[메모리] forecast_ets 실행 전: 1548.58 MB
[메모리] forecast_ets 실행 후: 1548.59 MB (변화: +0.01 MB)
[PDM]   [ETS] 완료  첫값=-9.71e+05 (메모리: 1548.6 MB)
[PDM]   [Prophet] 시작  (메모리: 1548.6 MB)

00:49:57 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1548.59 MB

00:49:57 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1549.43 MB (변화: +0.84 MB)
[PDM]   [Prophet] 완료  첫값=1.15e+08 (메모리: 1549.4 MB)
[PDM]   [LSTM] 시작  (메모리: 1549.4 MB)
[메모리] forecast_lstm 실행 전: 1549.43 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1549.31 MB (변화: -0.12 MB)
[PDM]   [LSTM] 완료  첫값=1.25e+08 (메모리: 1549.3 MB)
[PDM]   [Theta] 시작  (메모리: 1549.3 MB)
[메모리] forecast_theta 실행 전: 1549.31 MB
[메모리] forecast_theta 실행 후: 1549.31 MB (변화: +0.00 MB)
[PDM]   [Theta] 완료  첫값=-3.87e+05 (메모리: 1549.3 MB)
[PDM]   [DB] 93행 저장 완료
[PROGRESS] [  76/500] ( 15.2%)  >>  PVLA
[PVLA] [SKIP] [PVLA] 'sale' 관측치 부족: 13개 < 최소 28개
[PROGRESS] [  77/500] ( 15.4%)  >>  PDS
[PDS]   45분기 | 2015-03-31 ~ 2026-03-31
[PDS]   [SARIMA] 시작  (메모리: 1549.3 MB)
[메모리] forecast_sarima 실행 전: 1549.31 MB
[메모리] find_best_sarima_params 실행 전: 1549.31 MB
[메모리] find_best_sarima_params 실행 후: 1549.31 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1549.31 MB (변화: +0.00 MB)
[PDS]   [SARIMA] 완료  첫값=4.18e+08 (메모리: 1549.3 MB)
[PDS]   [ETS] 시작  (메모리: 1549.3 MB)
[메모리] forecast_ets 실행 전: 1549.31 MB
[메모리] forecast_ets 실행 후: 1549.32 MB (변화: +0.01 MB)
[PDS]   [ETS] 완료  첫값=3.57e+08 (메모리: 1549.3 MB)
[PDS]   [Prophet] 시작  (메모리: 1549.3 MB)

00:50:22 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1549.32 MB

00:50:22 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1549.34 MB (변화: +0.02 MB)
[PDS]   [Prophet] 완료  첫값=4.29e+08 (메모리: 1549.3 MB)
[PDS]   [LSTM] 시작  (메모리: 1549.3 MB)
[메모리] forecast_lstm 실행 전: 1549.34 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1550.29 MB (변화: +0.95 MB)
[PDS]   [LSTM] 완료  첫값=4.20e+08 (메모리: 1550.3 MB)
[PDS]   [Theta] 시작  (메모리: 1550.3 MB)
[메모리] forecast_theta 실행 전: 1550.29 MB
[메모리] forecast_theta 실행 후: 1550.29 MB (변화: +0.00 MB)
[PDS]   [Theta] 완료  첫값=3.59e+08 (메모리: 1550.3 MB)
[PDS]   [DB] 93행 저장 완료
[PROGRESS] [  78/500] ( 15.6%)  >>  MRTN
[MRTN]   45분기 | 2015-03-31 ~ 2026-03-31
[MRTN]   [SARIMA] 시작  (메모리: 1550.3 MB)
[메모리] forecast_sarima 실행 전: 1550.30 MB
[메모리] find_best_sarima_params 실행 전: 1550.30 MB
[메모리] find_best_sarima_params 실행 후: 1550.30 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1550.30 MB (변화: +0.00 MB)
[MRTN]   [SARIMA] 완료  첫값=2.10e+08 (메모리: 1550.3 MB)
[MRTN]   [ETS] 시작  (메모리: 1550.3 MB)
[메모리] forecast_ets 실행 전: 1550.30 MB
[메모리] forecast_ets 실행 후: 1550.30 MB (변화: +0.01 MB)
[MRTN]   [ETS] 완료  첫값=2.12e+08 (메모리: 1550.3 MB)
[MRTN]   [Prophet] 시작  (메모리: 1550.3 MB)

00:50:42 - cmdstanpy - INFO - Chain [1] start processing
00:50:42 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1550.30 MB
[메모리] forecast_prophet 실행 후: 1550.34 MB (변화: +0.04 MB)
[MRTN]   [Prophet] 완료  첫값=2.77e+08 (메모리: 1550.3 MB)
[MRTN]   [LSTM] 시작  (메모리: 1550.3 MB)
[메모리] forecast_lstm 실행 전: 1550.34 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1549.25 MB (변화: -1.09 MB)
[MRTN]   [LSTM] 완료  첫값=2.38e+08 (메모리: 1549.3 MB)
[MRTN]   [Theta] 시작  (메모리: 1549.3 MB)
[메모리] forecast_theta 실행 전: 1549.25 MB
[메모리] forecast_theta 실행 후: 1549.25 MB (변화: +0.00 MB)
[MRTN]   [Theta] 완료  첫값=2.15e+08 (메모리: 1549.3 MB)
[MRTN]   [DB] 93행 저장 완료
[PROGRESS] [  79/500] ( 15.8%)  >>  VEC
[VEC]   45분기 | 2015-03-31 ~ 2026-03-31
[VEC]   [SARIMA] 시작  (메모리: 1549.3 MB)
[메모리] forecast_sarima 실행 전: 1549.25 MB
[메모리] find_best_sarima_params 실행 전: 1549.25 MB
[메모리] find_best_sarima_params 실행 후: 1549.25 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1549.25 MB (변화: +0.00 MB)
[VEC]   [SARIMA] 완료  첫값=1.23e+09 (메모리: 1549.3 MB)
[VEC]   [ETS] 시작  (메모리: 1549.3 MB)
[메모리] forecast_ets 실행 전: 1549.25 MB
[메모리] forecast_ets 실행 후: 1549.26 MB (변화: +0.01 MB)
[VEC]   [ETS] 완료  첫값=1.19e+09 (메모리: 1549.3 MB)
[VEC]   [Prophet] 시작  (메모리: 1549.3 MB)

00:51:02 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1549.26 MB

00:51:02 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1550.10 MB (변화: +0.84 MB)
[VEC]   [Prophet] 완료  첫값=9.59e+08 (메모리: 1550.1 MB)
[VEC]   [LSTM] 시작  (메모리: 1550.1 MB)
[메모리] forecast_lstm 실행 전: 1550.10 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1551.88 MB (변화: +1.78 MB)
[VEC]   [LSTM] 완료  첫값=1.85e+09 (메모리: 1551.9 MB)
[VEC]   [Theta] 시작  (메모리: 1551.9 MB)
[메모리] forecast_theta 실행 전: 1551.88 MB
[메모리] forecast_theta 실행 후: 1551.88 MB (변화: +0.00 MB)
[VEC]   [Theta] 완료  첫값=1.14e+09 (메모리: 1551.9 MB)
[VEC]   [DB] 93행 저장 완료
[PROGRESS] [  80/500] ( 16.0%)  >>  GLYC
[GLYC]   45분기 | 2015-03-31 ~ 2026-03-31
[GLYC]   [SARIMA] 시작  (메모리: 1551.9 MB)
[메모리] forecast_sarima 실행 전: 1551.88 MB
[메모리] find_best_sarima_params 실행 전: 1551.88 MB
[메모리] find_best_sarima_params 실행 후: 1551.88 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1551.88 MB (변화: +0.00 MB)
[GLYC]   [SARIMA] 완료  첫값=-8.09e+04 (메모리: 1551.9 MB)
[GLYC]   [ETS] 시작  (메모리: 1551.9 MB)
[메모리] forecast_ets 실행 전: 1551.88 MB
[메모리] forecast_ets 실행 후: 1551.89 MB (변화: +0.00 MB)
[GLYC]   [ETS] 완료  첫값=4.02e+05 (메모리: 1551.9 MB)
[GLYC]   [Prophet] 시작  (메모리: 1551.9 MB)

00:51:22 - cmdstanpy - INFO - Chain [1] start processing
00:51:22 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1551.89 MB
[메모리] forecast_prophet 실행 후: 1551.92 MB (변화: +0.04 MB)
[GLYC]   [Prophet] 완료  첫값=-6.36e+05 (메모리: 1551.9 MB)
[GLYC]   [LSTM] 시작  (메모리: 1551.9 MB)
[메모리] forecast_lstm 실행 전: 1551.92 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1552.03 MB (변화: +0.11 MB)
[GLYC]   [LSTM] 완료  첫값=2.60e+05 (메모리: 1552.0 MB)
[GLYC]   [Theta] 시작  (메모리: 1552.0 MB)
[메모리] forecast_theta 실행 전: 1552.03 MB
[메모리] forecast_theta 실행 후: 1552.03 MB (변화: +0.00 MB)
[GLYC]   [Theta] 완료  첫값=-8.09e+05 (메모리: 1552.0 MB)
[GLYC]   [DB] 93행 저장 완료
[PROGRESS] [  81/500] ( 16.2%)  >>  GLDD
[GLDD]   45분기 | 2015-03-31 ~ 2026-03-31
[GLDD]   [SARIMA] 시작  (메모리: 1552.0 MB)
[메모리] forecast_sarima 실행 전: 1552.03 MB
[메모리] find_best_sarima_params 실행 전: 1552.03 MB
[메모리] find_best_sarima_params 실행 후: 1552.03 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1552.03 MB (변화: +0.00 MB)
[GLDD]   [SARIMA] 완료  첫값=1.81e+08 (메모리: 1552.0 MB)
[GLDD]   [ETS] 시작  (메모리: 1552.0 MB)
[메모리] forecast_ets 실행 전: 1552.03 MB
[메모리] forecast_ets 실행 후: 1552.03 MB (변화: +0.00 MB)
[GLDD]   [ETS] 완료  첫값=1.70e+08 (메모리: 1552.0 MB)
[GLDD]   [Prophet] 시작  (메모리: 1552.0 MB)

00:51:39 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1552.03 MB

00:51:39 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1552.12 MB (변화: +0.09 MB)
[GLDD]   [Prophet] 완료  첫값=1.77e+08 (메모리: 1552.1 MB)
[GLDD]   [LSTM] 시작  (메모리: 1552.1 MB)
[메모리] forecast_lstm 실행 전: 1552.12 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1551.77 MB (변화: -0.35 MB)
[GLDD]   [LSTM] 완료  첫값=1.84e+08 (메모리: 1551.8 MB)
[GLDD]   [Theta] 시작  (메모리: 1551.8 MB)
[메모리] forecast_theta 실행 전: 1551.77 MB
[메모리] forecast_theta 실행 후: 1551.77 MB (변화: +0.00 MB)
[GLDD]   [Theta] 완료  첫값=1.96e+08 (메모리: 1551.8 MB)
[GLDD]   [DB] 93행 저장 완료
[PROGRESS] [  82/500] ( 16.4%)  >>  MFA
[MFA]   45분기 | 2015-03-31 ~ 2026-03-31
[MFA]   [SARIMA] 시작  (메모리: 1551.8 MB)
[메모리] forecast_sarima 실행 전: 1551.77 MB
[메모리] find_best_sarima_params 실행 전: 1551.77 MB
[메모리] find_best_sarima_params 실행 후: 1551.77 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1551.77 MB (변화: +0.00 MB)
[MFA]   [SARIMA] 완료  첫값=1.25e+08 (메모리: 1551.8 MB)
[MFA]   [ETS] 시작  (메모리: 1551.8 MB)
[메모리] forecast_ets 실행 전: 1551.77 MB
[메모리] forecast_ets 실행 후: 1551.78 MB (변화: +0.00 MB)
[MFA]   [ETS] 완료  첫값=7.11e+07 (메모리: 1551.8 MB)
[MFA]   [Prophet] 시작  (메모리: 1551.8 MB)

00:51:59 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1551.78 MB

00:52:00 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1552.20 MB (변화: +0.42 MB)
[MFA]   [Prophet] 완료  첫값=4.24e+07 (메모리: 1552.2 MB)
[MFA]   [LSTM] 시작  (메모리: 1552.2 MB)
[메모리] forecast_lstm 실행 전: 1552.20 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1554.14 MB (변화: +1.94 MB)
[MFA]   [LSTM] 완료  첫값=1.15e+08 (메모리: 1554.1 MB)
[MFA]   [Theta] 시작  (메모리: 1554.1 MB)
[메모리] forecast_theta 실행 전: 1554.14 MB
[메모리] forecast_theta 실행 후: 1554.14 MB (변화: +0.00 MB)
[MFA]   [Theta] 완료  첫값=5.62e+07 (메모리: 1554.1 MB)
[MFA]   [DB] 93행 저장 완료
[PROGRESS] [  83/500] ( 16.6%)  >>  SAFE
[SAFE]   45분기 | 2015-03-31 ~ 2026-03-31
[SAFE]   [SARIMA] 시작  (메모리: 1554.1 MB)
[메모리] forecast_sarima 실행 전: 1554.14 MB
[메모리] find_best_sarima_params 실행 전: 1554.14 MB
[메모리] find_best_sarima_params 실행 후: 1554.14 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1554.14 MB (변화: +0.00 MB)
[SAFE]   [SARIMA] 완료  첫값=9.79e+07 (메모리: 1554.1 MB)
[SAFE]   [ETS] 시작  (메모리: 1554.1 MB)
[메모리] forecast_ets 실행 전: 1554.14 MB
[메모리] forecast_ets 실행 후: 1554.15 MB (변화: +0.01 MB)
[SAFE]   [ETS] 완료  첫값=9.23e+07 (메모리: 1554.1 MB)
[SAFE]   [Prophet] 시작  (메모리: 1554.1 MB)

00:52:19 - cmdstanpy - INFO - Chain [1] start processing
00:52:20 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1554.15 MB
[메모리] forecast_prophet 실행 후: 1553.88 MB (변화: -0.27 MB)
[SAFE]   [Prophet] 완료  첫값=8.66e+07 (메모리: 1553.9 MB)
[SAFE]   [LSTM] 시작  (메모리: 1553.9 MB)
[메모리] forecast_lstm 실행 전: 1553.88 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1553.62 MB (변화: -0.25 MB)
[SAFE]   [LSTM] 완료  첫값=1.05e+08 (메모리: 1553.6 MB)
[SAFE]   [Theta] 시작  (메모리: 1553.6 MB)
[메모리] forecast_theta 실행 전: 1553.62 MB
[메모리] forecast_theta 실행 후: 1553.62 MB (변화: +0.00 MB)
[SAFE]   [Theta] 완료  첫값=9.49e+07 (메모리: 1553.6 MB)
[SAFE]   [DB] 93행 저장 완료
[PROGRESS] [  84/500] ( 16.8%)  >>  BVH
[BVH]   45분기 | 2015-03-31 ~ 2026-03-31
[BVH]   [SARIMA] 시작  (메모리: 1553.6 MB)
[메모리] forecast_sarima 실행 전: 1553.62 MB
[메모리] find_best_sarima_params 실행 전: 1553.62 MB
[메모리] find_best_sarima_params 실행 후: 1553.62 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1553.62 MB (변화: +0.00 MB)
[BVH]   [SARIMA] 완료  첫값=2.35e+08 (메모리: 1553.6 MB)
[BVH]   [ETS] 시작  (메모리: 1553.6 MB)
[메모리] forecast_ets 실행 전: 1553.62 MB
[메모리] forecast_ets 실행 후: 1553.62 MB (변화: +0.00 MB)
[BVH]   [ETS] 완료  첫값=2.44e+08 (메모리: 1553.6 MB)
[BVH]   [Prophet] 시작  (메모리: 1553.6 MB)

00:52:44 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1553.62 MB

00:52:44 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1553.66 MB (변화: +0.04 MB)
[BVH]   [Prophet] 완료  첫값=2.33e+08 (메모리: 1553.7 MB)
[BVH]   [LSTM] 시작  (메모리: 1553.7 MB)
[메모리] forecast_lstm 실행 전: 1553.66 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1553.50 MB (변화: -0.16 MB)
[BVH]   [LSTM] 완료  첫값=2.18e+08 (메모리: 1553.5 MB)
[BVH]   [Theta] 시작  (메모리: 1553.5 MB)
[메모리] forecast_theta 실행 전: 1553.50 MB
[메모리] forecast_theta 실행 후: 1553.50 MB (변화: +0.00 MB)
[BVH]   [Theta] 완료  첫값=2.36e+08 (메모리: 1553.5 MB)
[BVH]   [DB] 93행 저장 완료
[PROGRESS] [  85/500] ( 17.0%)  >>  TBPH
[TBPH]   45분기 | 2015-03-31 ~ 2026-03-31
[TBPH]   [SARIMA] 시작  (메모리: 1553.5 MB)
[메모리] forecast_sarima 실행 전: 1553.50 MB
[메모리] find_best_sarima_params 실행 전: 1553.50 MB
[메모리] find_best_sarima_params 실행 후: 1553.50 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1553.50 MB (변화: +0.00 MB)
[TBPH]   [SARIMA] 완료  첫값=2.40e+07 (메모리: 1553.5 MB)
[TBPH]   [ETS] 시작  (메모리: 1553.5 MB)
[메모리] forecast_ets 실행 전: 1553.50 MB
[메모리] forecast_ets 실행 후: 1553.50 MB (변화: +0.00 MB)
[TBPH]   [ETS] 완료  첫값=2.07e+07 (메모리: 1553.5 MB)
[TBPH]   [Prophet] 시작  (메모리: 1553.5 MB)

00:53:02 - cmdstanpy - INFO - Chain [1] start processing
00:53:02 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1553.50 MB
[메모리] forecast_prophet 실행 후: 1553.54 MB (변화: +0.05 MB)
[TBPH]   [Prophet] 완료  첫값=1.90e+07 (메모리: 1553.5 MB)
[TBPH]   [LSTM] 시작  (메모리: 1553.5 MB)
[메모리] forecast_lstm 실행 전: 1553.54 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1554.59 MB (변화: +1.05 MB)
[TBPH]   [LSTM] 완료  첫값=1.86e+07 (메모리: 1554.6 MB)
[TBPH]   [Theta] 시작  (메모리: 1554.6 MB)
[메모리] forecast_theta 실행 전: 1554.59 MB
[메모리] forecast_theta 실행 후: 1554.59 MB (변화: +0.00 MB)
[TBPH]   [Theta] 완료  첫값=2.05e+07 (메모리: 1554.6 MB)
[TBPH]   [DB] 93행 저장 완료
[PROGRESS] [  86/500] ( 17.2%)  >>  OPK
[OPK]   45분기 | 2015-03-31 ~ 2026-03-31
[OPK]   [SARIMA] 시작  (메모리: 1554.6 MB)
[메모리] forecast_sarima 실행 전: 1554.59 MB
[메모리] find_best_sarima_params 실행 전: 1554.59 MB
[메모리] find_best_sarima_params 실행 후: 1554.60 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1554.60 MB (변화: +0.00 MB)
[OPK]   [SARIMA] 완료  첫값=1.53e+08 (메모리: 1554.6 MB)
[OPK]   [ETS] 시작  (메모리: 1554.6 MB)
[메모리] forecast_ets 실행 전: 1554.60 MB
[메모리] forecast_ets 실행 후: 1554.61 MB (변화: +0.01 MB)
[OPK]   [ETS] 완료  첫값=1.65e+08 (메모리: 1554.6 MB)
[OPK]   [Prophet] 시작  (메모리: 1554.6 MB)

00:53:20 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1554.61 MB

00:53:20 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1554.23 MB (변화: -0.37 MB)
[OPK]   [Prophet] 완료  첫값=2.29e+08 (메모리: 1554.2 MB)
[OPK]   [LSTM] 시작  (메모리: 1554.2 MB)
[메모리] forecast_lstm 실행 전: 1554.23 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1555.25 MB (변화: +1.01 MB)
[OPK]   [LSTM] 완료  첫값=2.19e+08 (메모리: 1555.2 MB)
[OPK]   [Theta] 시작  (메모리: 1555.2 MB)
[메모리] forecast_theta 실행 전: 1555.25 MB
[메모리] forecast_theta 실행 후: 1555.25 MB (변화: +0.00 MB)
[OPK]   [Theta] 완료  첫값=1.52e+08 (메모리: 1555.2 MB)
[OPK]   [DB] 93행 저장 완료
[PROGRESS] [  87/500] ( 17.4%)  >>  SOL
[SOL]   45분기 | 2015-03-31 ~ 2026-03-31
[SOL]   [SARIMA] 시작  (메모리: 1555.2 MB)
[메모리] forecast_sarima 실행 전: 1555.25 MB
[메모리] find_best_sarima_params 실행 전: 1555.25 MB
[메모리] find_best_sarima_params 실행 후: 1555.25 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1555.25 MB (변화: +0.00 MB)
[SOL]   [SARIMA] 완료  첫값=2.10e+07 (메모리: 1555.2 MB)
[SOL]   [ETS] 시작  (메모리: 1555.2 MB)
[메모리] forecast_ets 실행 전: 1555.25 MB
[메모리] forecast_ets 실행 후: 1555.25 MB (변화: +0.00 MB)
[SOL]   [ETS] 완료  첫값=1.49e+07 (메모리: 1555.2 MB)
[SOL]   [Prophet] 시작  (메모리: 1555.2 MB)

00:53:36 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1555.25 MB

00:53:36 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1554.29 MB (변화: -0.96 MB)
[SOL]   [Prophet] 완료  첫값=-5.77e+07 (메모리: 1554.3 MB)
[SOL]   [LSTM] 시작  (메모리: 1554.3 MB)
[메모리] forecast_lstm 실행 전: 1554.29 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1555.38 MB (변화: +1.09 MB)
[SOL]   [LSTM] 완료  첫값=1.93e+07 (메모리: 1555.4 MB)
[SOL]   [Theta] 시작  (메모리: 1555.4 MB)
[메모리] forecast_theta 실행 전: 1555.38 MB
[메모리] forecast_theta 실행 후: 1555.38 MB (변화: +0.00 MB)
[SOL]   [Theta] 완료  첫값=1.73e+07 (메모리: 1555.4 MB)
[SOL]   [DB] 93행 저장 완료
[PROGRESS] [  88/500] ( 17.6%)  >>  PRSU
[PRSU]   45분기 | 2015-03-31 ~ 2026-03-31
[PRSU]   [SARIMA] 시작  (메모리: 1555.4 MB)
[메모리] forecast_sarima 실행 전: 1555.38 MB
[메모리] find_best_sarima_params 실행 전: 1555.38 MB
[메모리] find_best_sarima_params 실행 후: 1555.38 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1555.38 MB (변화: +0.00 MB)
[PRSU]   [SARIMA] 완료  첫값=3.90e+08 (메모리: 1555.4 MB)
[PRSU]   [ETS] 시작  (메모리: 1555.4 MB)
[메모리] forecast_ets 실행 전: 1555.38 MB
[메모리] forecast_ets 실행 후: 1555.38 MB (변화: +0.00 MB)
[PRSU]   [ETS] 완료  첫값=2.53e+08 (메모리: 1555.4 MB)
[PRSU]   [Prophet] 시작  (메모리: 1555.4 MB)

00:53:54 - cmdstanpy - INFO - Chain [1] start processing
00:53:55 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1555.38 MB
[메모리] forecast_prophet 실행 후: 1554.40 MB (변화: -0.98 MB)
[PRSU]   [Prophet] 완료  첫값=1.32e+08 (메모리: 1554.4 MB)
[PRSU]   [LSTM] 시작  (메모리: 1554.4 MB)
[메모리] forecast_lstm 실행 전: 1554.40 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1555.30 MB (변화: +0.91 MB)
[PRSU]   [LSTM] 완료  첫값=1.53e+08 (메모리: 1555.3 MB)
[PRSU]   [Theta] 시작  (메모리: 1555.3 MB)
[메모리] forecast_theta 실행 전: 1555.30 MB
[메모리] forecast_theta 실행 후: 1555.30 MB (변화: +0.00 MB)
[PRSU]   [Theta] 완료  첫값=1.56e+08 (메모리: 1555.3 MB)
[PRSU]   [DB] 93행 저장 완료
[PROGRESS] [  89/500] ( 17.8%)  >>  CCO
[CCO]   45분기 | 2015-03-31 ~ 2026-03-31
[CCO]   [SARIMA] 시작  (메모리: 1555.3 MB)
[메모리] forecast_sarima 실행 전: 1555.30 MB
[메모리] find_best_sarima_params 실행 전: 1555.30 MB
[메모리] find_best_sarima_params 실행 후: 1555.30 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1555.30 MB (변화: +0.00 MB)
[CCO]   [SARIMA] 완료  첫값=4.07e+08 (메모리: 1555.3 MB)
[CCO]   [ETS] 시작  (메모리: 1555.3 MB)
[메모리] forecast_ets 실행 전: 1555.30 MB
[메모리] forecast_ets 실행 후: 1555.31 MB (변화: +0.01 MB)
[CCO]   [ETS] 완료  첫값=4.02e+08 (메모리: 1555.3 MB)
[CCO]   [Prophet] 시작  (메모리: 1555.3 MB)

00:54:13 - cmdstanpy - INFO - Chain [1] start processing
00:54:14 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1555.31 MB
[메모리] forecast_prophet 실행 후: 1556.11 MB (변화: +0.80 MB)
[CCO]   [Prophet] 완료  첫값=4.10e+08 (메모리: 1556.1 MB)
[CCO]   [LSTM] 시작  (메모리: 1556.1 MB)
[메모리] forecast_lstm 실행 전: 1556.11 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1556.93 MB (변화: +0.82 MB)
[CCO]   [LSTM] 완료  첫값=4.42e+08 (메모리: 1556.9 MB)
[CCO]   [Theta] 시작  (메모리: 1556.9 MB)
[메모리] forecast_theta 실행 전: 1556.93 MB
[메모리] forecast_theta 실행 후: 1556.93 MB (변화: +0.00 MB)
[CCO]   [Theta] 완료  첫값=4.07e+08 (메모리: 1556.9 MB)
[CCO]   [DB] 93행 저장 완료
[PROGRESS] [  90/500] ( 18.0%)  >>  CPLP
[CPLP]   45분기 | 2015-03-31 ~ 2026-03-31
[CPLP]   [SARIMA] 시작  (메모리: 1556.9 MB)
[메모리] forecast_sarima 실행 전: 1556.93 MB
[메모리] find_best_sarima_params 실행 전: 1556.93 MB
[메모리] find_best_sarima_params 실행 후: 1556.93 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1556.93 MB (변화: +0.00 MB)
[CPLP]   [SARIMA] 완료  첫값=9.77e+07 (메모리: 1556.9 MB)
[CPLP]   [ETS] 시작  (메모리: 1556.9 MB)
[메모리] forecast_ets 실행 전: 1556.93 MB
[메모리] forecast_ets 실행 후: 1556.93 MB (변화: +0.00 MB)
[CPLP]   [ETS] 완료  첫값=9.29e+07 (메모리: 1556.9 MB)
[CPLP]   [Prophet] 시작  (메모리: 1556.9 MB)

00:54:31 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1556.93 MB

00:54:31 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1556.59 MB (변화: -0.34 MB)
[CPLP]   [Prophet] 완료  첫값=9.20e+07 (메모리: 1556.6 MB)
[CPLP]   [LSTM] 시작  (메모리: 1556.6 MB)
[메모리] forecast_lstm 실행 전: 1556.59 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1557.55 MB (변화: +0.96 MB)
[CPLP]   [LSTM] 완료  첫값=8.76e+07 (메모리: 1557.6 MB)
[CPLP]   [Theta] 시작  (메모리: 1557.6 MB)
[메모리] forecast_theta 실행 전: 1557.55 MB
[메모리] forecast_theta 실행 후: 1557.55 MB (변화: +0.00 MB)
[CPLP]   [Theta] 완료  첫값=9.07e+07 (메모리: 1557.6 MB)
[CPLP]   [DB] 93행 저장 완료
[PROGRESS] [  91/500] ( 18.2%)  >>  LQDT
[LQDT]   45분기 | 2015-03-31 ~ 2026-03-31
[LQDT]   [SARIMA] 시작  (메모리: 1557.6 MB)
[메모리] forecast_sarima 실행 전: 1557.55 MB
[메모리] find_best_sarima_params 실행 전: 1557.55 MB
[메모리] find_best_sarima_params 실행 후: 1557.55 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1557.55 MB (변화: +0.00 MB)
[LQDT]   [SARIMA] 완료  첫값=1.22e+08 (메모리: 1557.6 MB)
[LQDT]   [ETS] 시작  (메모리: 1557.6 MB)
[메모리] forecast_ets 실행 전: 1557.55 MB
[메모리] forecast_ets 실행 후: 1557.56 MB (변화: +0.01 MB)
[LQDT]   [ETS] 완료  첫값=1.21e+08 (메모리: 1557.6 MB)
[LQDT]   [Prophet] 시작  (메모리: 1557.6 MB)

00:54:57 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1557.56 MB

00:54:57 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1556.74 MB (변화: -0.82 MB)
[LQDT]   [Prophet] 완료  첫값=9.66e+07 (메모리: 1556.7 MB)
[LQDT]   [LSTM] 시작  (메모리: 1556.7 MB)
[메모리] forecast_lstm 실행 전: 1556.74 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1557.67 MB (변화: +0.93 MB)
[LQDT]   [LSTM] 완료  첫값=1.48e+08 (메모리: 1557.7 MB)
[LQDT]   [Theta] 시작  (메모리: 1557.7 MB)
[메모리] forecast_theta 실행 전: 1557.67 MB
[메모리] forecast_theta 실행 후: 1557.67 MB (변화: +0.00 MB)
[LQDT]   [Theta] 완료  첫값=1.18e+08 (메모리: 1557.7 MB)
[LQDT]   [DB] 93행 저장 완료
[PROGRESS] [  92/500] ( 18.4%)  >>  BBSI
[BBSI]   45분기 | 2015-03-31 ~ 2026-03-31
[BBSI]   [SARIMA] 시작  (메모리: 1557.7 MB)
[메모리] forecast_sarima 실행 전: 1557.67 MB
[메모리] find_best_sarima_params 실행 전: 1557.67 MB
[메모리] find_best_sarima_params 실행 후: 1557.67 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1557.67 MB (변화: +0.00 MB)
[BBSI]   [SARIMA] 완료  첫값=3.29e+08 (메모리: 1557.7 MB)
[BBSI]   [ETS] 시작  (메모리: 1557.7 MB)
[메모리] forecast_ets 실행 전: 1557.67 MB
[메모리] forecast_ets 실행 후: 1557.68 MB (변화: +0.01 MB)
[BBSI]   [ETS] 완료  첫값=3.34e+08 (메모리: 1557.7 MB)
[BBSI]   [Prophet] 시작  (메모리: 1557.7 MB)
[메모리] forecast_prophet 실행 전: 1557.68 MB

00:55:22 - cmdstanpy - INFO - Chain [1] start processing
00:55:22 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1557.71 MB (변화: +0.04 MB)
[BBSI]   [Prophet] 완료  첫값=3.12e+08 (메모리: 1557.7 MB)
[BBSI]   [LSTM] 시작  (메모리: 1557.7 MB)
[메모리] forecast_lstm 실행 전: 1557.71 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1558.35 MB (변화: +0.64 MB)
[BBSI]   [LSTM] 완료  첫값=2.99e+08 (메모리: 1558.4 MB)
[BBSI]   [Theta] 시작  (메모리: 1558.4 MB)
[메모리] forecast_theta 실행 전: 1558.35 MB
[메모리] forecast_theta 실행 후: 1558.35 MB (변화: +0.00 MB)
[BBSI]   [Theta] 완료  첫값=3.30e+08 (메모리: 1558.4 MB)
[BBSI]   [DB] 93행 저장 완료
[PROGRESS] [  93/500] ( 18.6%)  >>  NBR
[NBR]   45분기 | 2015-03-31 ~ 2026-03-31
[NBR]   [SARIMA] 시작  (메모리: 1558.4 MB)
[메모리] forecast_sarima 실행 전: 1558.35 MB
[메모리] find_best_sarima_params 실행 전: 1558.35 MB
[메모리] find_best_sarima_params 실행 후: 1558.35 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1558.35 MB (변화: +0.00 MB)
[NBR]   [SARIMA] 완료  첫값=8.04e+08 (메모리: 1558.4 MB)
[NBR]   [ETS] 시작  (메모리: 1558.4 MB)
[메모리] forecast_ets 실행 전: 1558.35 MB
[메모리] forecast_ets 실행 후: 1558.35 MB (변화: +0.00 MB)
[NBR]   [ETS] 완료  첫값=7.73e+08 (메모리: 1558.4 MB)
[NBR]   [Prophet] 시작  (메모리: 1558.4 MB)

00:55:41 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1558.35 MB

00:55:41 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1558.03 MB (변화: -0.32 MB)
[NBR]   [Prophet] 완료  첫값=6.92e+08 (메모리: 1558.0 MB)
[NBR]   [LSTM] 시작  (메모리: 1558.0 MB)
[메모리] forecast_lstm 실행 전: 1558.03 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1559.10 MB (변화: +1.07 MB)
[NBR]   [LSTM] 완료  첫값=6.85e+08 (메모리: 1559.1 MB)
[NBR]   [Theta] 시작  (메모리: 1559.1 MB)
[메모리] forecast_theta 실행 전: 1559.10 MB
[메모리] forecast_theta 실행 후: 1559.10 MB (변화: +0.00 MB)
[NBR]   [Theta] 완료  첫값=8.05e+08 (메모리: 1559.1 MB)
[NBR]   [DB] 93행 저장 완료
[PROGRESS] [  94/500] ( 18.8%)  >>  IOVA
[IOVA]   45분기 | 2015-03-31 ~ 2026-03-31
[IOVA]   [SARIMA] 시작  (메모리: 1559.1 MB)
[메모리] forecast_sarima 실행 전: 1559.10 MB
[메모리] find_best_sarima_params 실행 전: 1559.10 MB
[메모리] find_best_sarima_params 실행 후: 1559.10 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1559.10 MB (변화: +0.00 MB)
[IOVA]   [SARIMA] 완료  첫값=5.66e+07 (메모리: 1559.1 MB)
[IOVA]   [ETS] 시작  (메모리: 1559.1 MB)
[메모리] forecast_ets 실행 전: 1559.10 MB
[메모리] forecast_ets 실행 후: 1559.10 MB (변화: +0.00 MB)
[IOVA]   [ETS] 완료  첫값=6.97e+07 (메모리: 1559.1 MB)
[IOVA]   [Prophet] 시작  (메모리: 1559.1 MB)

00:56:05 - cmdstanpy - INFO - Chain [1] start processing
00:56:05 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1559.10 MB
[메모리] forecast_prophet 실행 후: 1559.35 MB (변화: +0.25 MB)
[IOVA]   [Prophet] 완료  첫값=3.77e+07 (메모리: 1559.3 MB)
[IOVA]   [LSTM] 시작  (메모리: 1559.3 MB)
[메모리] forecast_lstm 실행 전: 1559.35 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1559.03 MB (변화: -0.32 MB)
[IOVA]   [LSTM] 완료  첫값=1.12e+08 (메모리: 1559.0 MB)
[IOVA]   [Theta] 시작  (메모리: 1559.0 MB)
[메모리] forecast_theta 실행 전: 1559.03 MB
[메모리] forecast_theta 실행 후: 1559.03 MB (변화: +0.00 MB)
[IOVA]   [Theta] 완료  첫값=7.05e+07 (메모리: 1559.0 MB)
[IOVA]   [DB] 93행 저장 완료
[PROGRESS] [  95/500] ( 19.0%)  >>  WBI
[WBI] [SKIP] [WBI] 'sale' 관측치 부족: 5개 < 최소 28개
[PROGRESS] [  96/500] ( 19.2%)  >>  LMB
[LMB]   45분기 | 2015-03-31 ~ 2026-03-31
[LMB]   [SARIMA] 시작  (메모리: 1559.0 MB)
[메모리] forecast_sarima 실행 전: 1559.04 MB
[메모리] find_best_sarima_params 실행 전: 1559.04 MB
[메모리] find_best_sarima_params 실행 후: 1559.04 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1559.04 MB (변화: +0.00 MB)
[LMB]   [SARIMA] 완료  첫값=1.89e+08 (메모리: 1559.0 MB)
[LMB]   [ETS] 시작  (메모리: 1559.0 MB)
[메모리] forecast_ets 실행 전: 1559.04 MB
[메모리] forecast_ets 실행 후: 1559.04 MB (변화: +0.00 MB)
[LMB]   [ETS] 완료  첫값=1.79e+08 (메모리: 1559.0 MB)
[LMB]   [Prophet] 시작  (메모리: 1559.0 MB)

00:56:31 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1559.04 MB

00:56:31 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1559.07 MB (변화: +0.03 MB)
[LMB]   [Prophet] 완료  첫값=1.55e+08 (메모리: 1559.1 MB)
[LMB]   [LSTM] 시작  (메모리: 1559.1 MB)
[메모리] forecast_lstm 실행 전: 1559.07 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1559.20 MB (변화: +0.13 MB)
[LMB]   [LSTM] 완료  첫값=1.47e+08 (메모리: 1559.2 MB)
[LMB]   [Theta] 시작  (메모리: 1559.2 MB)
[메모리] forecast_theta 실행 전: 1559.20 MB
[메모리] forecast_theta 실행 후: 1559.20 MB (변화: +0.00 MB)
[LMB]   [Theta] 완료  첫값=1.82e+08 (메모리: 1559.2 MB)
[LMB]   [DB] 93행 저장 완료
[PROGRESS] [  97/500] ( 19.4%)  >>  AXL
[AXL]   45분기 | 2015-03-31 ~ 2026-03-31
[AXL]   [SARIMA] 시작  (메모리: 1559.2 MB)
[메모리] forecast_sarima 실행 전: 1559.20 MB
[메모리] find_best_sarima_params 실행 전: 1559.20 MB
[메모리] find_best_sarima_params 실행 후: 1559.20 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1559.20 MB (변화: +0.00 MB)
[AXL]   [SARIMA] 완료  첫값=1.41e+09 (메모리: 1559.2 MB)
[AXL]   [ETS] 시작  (메모리: 1559.2 MB)
[메모리] forecast_ets 실행 전: 1559.20 MB
[메모리] forecast_ets 실행 후: 1559.20 MB (변화: +0.00 MB)
[AXL]   [ETS] 완료  첫값=1.40e+09 (메모리: 1559.2 MB)
[AXL]   [Prophet] 시작  (메모리: 1559.2 MB)

00:56:51 - cmdstanpy - INFO - Chain [1] start processing
00:56:51 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1559.20 MB
[메모리] forecast_prophet 실행 후: 1558.75 MB (변화: -0.44 MB)
[AXL]   [Prophet] 완료  첫값=1.56e+09 (메모리: 1558.8 MB)
[AXL]   [LSTM] 시작  (메모리: 1558.8 MB)
[메모리] forecast_lstm 실행 전: 1558.75 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1559.77 MB (변화: +1.02 MB)
[AXL]   [LSTM] 완료  첫값=1.51e+09 (메모리: 1559.8 MB)
[AXL]   [Theta] 시작  (메모리: 1559.8 MB)
[메모리] forecast_theta 실행 전: 1559.77 MB
[메모리] forecast_theta 실행 후: 1559.77 MB (변화: +0.00 MB)
[AXL]   [Theta] 완료  첫값=1.42e+09 (메모리: 1559.8 MB)
[AXL]   [DB] 93행 저장 완료
[PROGRESS] [  98/500] ( 19.6%)  >>  CPAC
[CPAC]   45분기 | 2015-03-31 ~ 2026-03-31
[CPAC]   [SARIMA] 시작  (메모리: 1559.8 MB)
[메모리] forecast_sarima 실행 전: 1559.77 MB
[메모리] find_best_sarima_params 실행 전: 1559.77 MB
[메모리] find_best_sarima_params 실행 후: 1559.77 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1559.77 MB (변화: +0.00 MB)
[CPAC]   [SARIMA] 완료  첫값=5.04e+08 (메모리: 1559.8 MB)
[CPAC]   [ETS] 시작  (메모리: 1559.8 MB)
[메모리] forecast_ets 실행 전: 1559.77 MB
[메모리] forecast_ets 실행 후: 1559.77 MB (변화: +0.00 MB)
[CPAC]   [ETS] 완료  첫값=4.87e+08 (메모리: 1559.8 MB)
[CPAC]   [Prophet] 시작  (메모리: 1559.8 MB)

00:57:13 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1559.77 MB

00:57:13 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1559.79 MB (변화: +0.02 MB)
[CPAC]   [Prophet] 완료  첫값=5.67e+08 (메모리: 1559.8 MB)
[CPAC]   [LSTM] 시작  (메모리: 1559.8 MB)
[메모리] forecast_lstm 실행 전: 1559.79 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1559.77 MB (변화: -0.03 MB)
[CPAC]   [LSTM] 완료  첫값=5.04e+08 (메모리: 1559.8 MB)
[CPAC]   [Theta] 시작  (메모리: 1559.8 MB)
[메모리] forecast_theta 실행 전: 1559.77 MB
[메모리] forecast_theta 실행 후: 1559.77 MB (변화: +0.00 MB)
[CPAC]   [Theta] 완료  첫값=4.78e+08 (메모리: 1559.8 MB)
[CPAC]   [DB] 93행 저장 완료
[PROGRESS] [  99/500] ( 19.8%)  >>  STAA
[STAA]   45분기 | 2015-03-31 ~ 2026-03-31
[STAA]   [SARIMA] 시작  (메모리: 1559.8 MB)
[메모리] forecast_sarima 실행 전: 1559.77 MB
[메모리] find_best_sarima_params 실행 전: 1559.77 MB
[메모리] find_best_sarima_params 실행 후: 1559.77 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1559.77 MB (변화: +0.00 MB)
[STAA]   [SARIMA] 완료  첫값=9.86e+07 (메모리: 1559.8 MB)
[STAA]   [ETS] 시작  (메모리: 1559.8 MB)
[메모리] forecast_ets 실행 전: 1559.77 MB
[메모리] forecast_ets 실행 후: 1559.77 MB (변화: +0.01 MB)
[STAA]   [ETS] 완료  첫값=1.05e+08 (메모리: 1559.8 MB)
[STAA]   [Prophet] 시작  (메모리: 1559.8 MB)

00:57:32 - cmdstanpy - INFO - Chain [1] start processing
00:57:32 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1559.77 MB
[메모리] forecast_prophet 실행 후: 1559.80 MB (변화: +0.03 MB)
[STAA]   [Prophet] 완료  첫값=8.78e+07 (메모리: 1559.8 MB)
[STAA]   [LSTM] 시작  (메모리: 1559.8 MB)
[메모리] forecast_lstm 실행 전: 1559.80 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1560.49 MB (변화: +0.68 MB)
[STAA]   [LSTM] 완료  첫값=8.37e+07 (메모리: 1560.5 MB)
[STAA]   [Theta] 시작  (메모리: 1560.5 MB)
[메모리] forecast_theta 실행 전: 1560.49 MB
[메모리] forecast_theta 실행 후: 1560.49 MB (변화: +0.00 MB)
[STAA]   [Theta] 완료  첫값=1.03e+08 (메모리: 1560.5 MB)
[STAA]   [DB] 93행 저장 완료
[PROGRESS] [ 100/500] ( 20.0%)  >>  LOT
[LOT] [SKIP] [LOT] 'sale' 관측치 부족: 19개 < 최소 28개
[PROGRESS] [ 101/500] ( 20.2%)  >>  CHS
[CHS]   45분기 | 2015-03-31 ~ 2026-03-31
[CHS]   [SARIMA] 시작  (메모리: 1560.5 MB)
[메모리] forecast_sarima 실행 전: 1560.49 MB
[메모리] find_best_sarima_params 실행 전: 1560.49 MB
[메모리] find_best_sarima_params 실행 후: 1560.49 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1560.49 MB (변화: +0.00 MB)
[CHS]   [SARIMA] 완료  첫값=5.02e+08 (메모리: 1560.5 MB)
[CHS]   [ETS] 시작  (메모리: 1560.5 MB)
[메모리] forecast_ets 실행 전: 1560.49 MB
[메모리] forecast_ets 실행 후: 1560.49 MB (변화: +0.00 MB)
[CHS]   [ETS] 완료  첫값=4.83e+08 (메모리: 1560.5 MB)
[CHS]   [Prophet] 시작  (메모리: 1560.5 MB)

00:57:54 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1560.49 MB

00:57:54 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1560.07 MB (변화: -0.42 MB)
[CHS]   [Prophet] 완료  첫값=5.09e+08 (메모리: 1560.1 MB)
[CHS]   [LSTM] 시작  (메모리: 1560.1 MB)
[메모리] forecast_lstm 실행 전: 1560.07 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1559.96 MB (변화: -0.11 MB)
[CHS]   [LSTM] 완료  첫값=4.64e+08 (메모리: 1560.0 MB)
[CHS]   [Theta] 시작  (메모리: 1560.0 MB)
[메모리] forecast_theta 실행 전: 1559.96 MB
[메모리] forecast_theta 실행 후: 1559.96 MB (변화: +0.00 MB)
[CHS]   [Theta] 완료  첫값=4.80e+08 (메모리: 1560.0 MB)
[CHS]   [DB] 93행 저장 완료
[PROGRESS] [ 102/500] ( 20.4%)  >>  HA
[HA]   45분기 | 2015-03-31 ~ 2026-03-31
[HA]   [SARIMA] 시작  (메모리: 1560.0 MB)
[메모리] forecast_sarima 실행 전: 1559.96 MB
[메모리] find_best_sarima_params 실행 전: 1559.96 MB
[메모리] find_best_sarima_params 실행 후: 1559.96 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1559.96 MB (변화: +0.00 MB)
[HA]   [SARIMA] 완료  첫값=7.11e+08 (메모리: 1560.0 MB)
[HA]   [ETS] 시작  (메모리: 1560.0 MB)
[메모리] forecast_ets 실행 전: 1559.96 MB
[메모리] forecast_ets 실행 후: 1559.96 MB (변화: +0.00 MB)
[HA]   [ETS] 완료  첫값=7.06e+08 (메모리: 1560.0 MB)
[HA]   [Prophet] 시작  (메모리: 1560.0 MB)

00:58:15 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1559.96 MB

00:58:15 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1560.28 MB (변화: +0.31 MB)
[HA]   [Prophet] 완료  첫값=6.58e+08 (메모리: 1560.3 MB)
[HA]   [LSTM] 시작  (메모리: 1560.3 MB)
[메모리] forecast_lstm 실행 전: 1560.28 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1559.89 MB (변화: -0.38 MB)
[HA]   [LSTM] 완료  첫값=6.63e+08 (메모리: 1559.9 MB)
[HA]   [Theta] 시작  (메모리: 1559.9 MB)
[메모리] forecast_theta 실행 전: 1559.89 MB
[메모리] forecast_theta 실행 후: 1559.89 MB (변화: +0.00 MB)
[HA]   [Theta] 완료  첫값=7.33e+08 (메모리: 1559.9 MB)
[HA]   [DB] 93행 저장 완료
[PROGRESS] [ 103/500] ( 20.6%)  >>  SSYS
[SSYS]   45분기 | 2015-03-31 ~ 2026-03-31
[SSYS]   [SARIMA] 시작  (메모리: 1559.9 MB)
[메모리] forecast_sarima 실행 전: 1559.89 MB
[메모리] find_best_sarima_params 실행 전: 1559.89 MB
[메모리] find_best_sarima_params 실행 후: 1559.89 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1559.89 MB (변화: +0.00 MB)
[SSYS]   [SARIMA] 완료  첫값=1.38e+08 (메모리: 1559.9 MB)
[SSYS]   [ETS] 시작  (메모리: 1559.9 MB)
[메모리] forecast_ets 실행 전: 1559.89 MB
[메모리] forecast_ets 실행 후: 1559.90 MB (변화: +0.00 MB)
[SSYS]   [ETS] 완료  첫값=1.39e+08 (메모리: 1559.9 MB)
[SSYS]   [Prophet] 시작  (메모리: 1559.9 MB)

00:58:37 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1559.90 MB

00:58:37 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1559.92 MB (변화: +0.02 MB)
[SSYS]   [Prophet] 완료  첫값=1.39e+08 (메모리: 1559.9 MB)
[SSYS]   [LSTM] 시작  (메모리: 1559.9 MB)
[메모리] forecast_lstm 실행 전: 1559.92 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1561.11 MB (변화: +1.18 MB)
[SSYS]   [LSTM] 완료  첫값=1.47e+08 (메모리: 1561.1 MB)
[SSYS]   [Theta] 시작  (메모리: 1561.1 MB)
[메모리] forecast_theta 실행 전: 1561.11 MB
[메모리] forecast_theta 실행 후: 1561.11 MB (변화: +0.00 MB)
[SSYS]   [Theta] 완료  첫값=1.39e+08 (메모리: 1561.1 MB)
[SSYS]   [DB] 93행 저장 완료
[PROGRESS] [ 104/500] ( 20.8%)  >>  HDL
[HDL] [SKIP] [HDL] 'sale' 관측치 부족: 21개 < 최소 28개
[PROGRESS] [ 105/500] ( 21.0%)  >>  BJRI
[BJRI]   45분기 | 2015-03-31 ~ 2026-03-31
[BJRI]   [SARIMA] 시작  (메모리: 1561.1 MB)
[메모리] forecast_sarima 실행 전: 1561.11 MB
[메모리] find_best_sarima_params 실행 전: 1561.11 MB
[메모리] find_best_sarima_params 실행 후: 1561.11 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1561.11 MB (변화: +0.00 MB)
[BJRI]   [SARIMA] 완료  첫값=3.30e+08 (메모리: 1561.1 MB)
[BJRI]   [ETS] 시작  (메모리: 1561.1 MB)
[메모리] forecast_ets 실행 전: 1561.11 MB
[메모리] forecast_ets 실행 후: 1561.11 MB (변화: +0.00 MB)
[BJRI]   [ETS] 완료  첫값=3.27e+08 (메모리: 1561.1 MB)
[BJRI]   [Prophet] 시작  (메모리: 1561.1 MB)

00:58:58 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1561.11 MB

00:58:58 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1561.60 MB (변화: +0.49 MB)
[BJRI]   [Prophet] 완료  첫값=3.46e+08 (메모리: 1561.6 MB)
[BJRI]   [LSTM] 시작  (메모리: 1561.6 MB)
[메모리] forecast_lstm 실행 전: 1561.60 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1560.76 MB (변화: -0.84 MB)
[BJRI]   [LSTM] 완료  첫값=3.28e+08 (메모리: 1560.8 MB)
[BJRI]   [Theta] 시작  (메모리: 1560.8 MB)
[메모리] forecast_theta 실행 전: 1560.76 MB
[메모리] forecast_theta 실행 후: 1560.76 MB (변화: +0.00 MB)
[BJRI]   [Theta] 완료  첫값=3.33e+08 (메모리: 1560.8 MB)
[BJRI]   [DB] 93행 저장 완료
[PROGRESS] [ 106/500] ( 21.2%)  >>  XNCR
[XNCR]   45분기 | 2015-03-31 ~ 2026-03-31
[XNCR]   [SARIMA] 시작  (메모리: 1560.8 MB)
[메모리] forecast_sarima 실행 전: 1560.76 MB
[메모리] find_best_sarima_params 실행 전: 1560.76 MB
[메모리] find_best_sarima_params 실행 후: 1560.76 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1560.76 MB (변화: +0.00 MB)
[XNCR]   [SARIMA] 완료  첫값=2.91e+07 (메모리: 1560.8 MB)
[XNCR]   [ETS] 시작  (메모리: 1560.8 MB)
[메모리] forecast_ets 실행 전: 1560.76 MB
[메모리] forecast_ets 실행 후: 1560.77 MB (변화: +0.01 MB)
[XNCR]   [ETS] 완료  첫값=2.84e+07 (메모리: 1560.8 MB)
[XNCR]   [Prophet] 시작  (메모리: 1560.8 MB)

00:59:14 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1560.77 MB

00:59:14 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1560.80 MB (변화: +0.03 MB)
[XNCR]   [Prophet] 완료  첫값=4.61e+07 (메모리: 1560.8 MB)
[XNCR]   [LSTM] 시작  (메모리: 1560.8 MB)
[메모리] forecast_lstm 실행 전: 1560.80 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1560.51 MB (변화: -0.29 MB)
[XNCR]   [LSTM] 완료  첫값=3.54e+07 (메모리: 1560.5 MB)
[XNCR]   [Theta] 시작  (메모리: 1560.5 MB)
[메모리] forecast_theta 실행 전: 1560.51 MB
[메모리] forecast_theta 실행 후: 1560.51 MB (변화: +0.00 MB)
[XNCR]   [Theta] 완료  첫값=3.38e+07 (메모리: 1560.5 MB)
[XNCR]   [DB] 93행 저장 완료
[PROGRESS] [ 107/500] ( 21.4%)  >>  GSM
[GSM]   45분기 | 2015-03-31 ~ 2026-03-31
[GSM]   [SARIMA] 시작  (메모리: 1560.5 MB)
[메모리] forecast_sarima 실행 전: 1560.51 MB
[메모리] find_best_sarima_params 실행 전: 1560.51 MB
[메모리] find_best_sarima_params 실행 후: 1560.51 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1560.51 MB (변화: +0.00 MB)
[GSM]   [SARIMA] 완료  첫값=3.12e+08 (메모리: 1560.5 MB)
[GSM]   [ETS] 시작  (메모리: 1560.5 MB)
[메모리] forecast_ets 실행 전: 1560.51 MB
[메모리] forecast_ets 실행 후: 1560.51 MB (변화: +0.00 MB)
[GSM]   [ETS] 완료  첫값=3.16e+08 (메모리: 1560.5 MB)
[GSM]   [Prophet] 시작  (메모리: 1560.5 MB)

00:59:34 - cmdstanpy - INFO - Chain [1] start processing
00:59:35 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1560.51 MB
[메모리] forecast_prophet 실행 후: 1561.34 MB (변화: +0.83 MB)
[GSM]   [Prophet] 완료  첫값=4.13e+08 (메모리: 1561.3 MB)
[GSM]   [LSTM] 시작  (메모리: 1561.3 MB)
[메모리] forecast_lstm 실행 전: 1561.34 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1561.96 MB (변화: +0.62 MB)
[GSM]   [LSTM] 완료  첫값=4.13e+08 (메모리: 1562.0 MB)
[GSM]   [Theta] 시작  (메모리: 1562.0 MB)
[메모리] forecast_theta 실행 전: 1561.96 MB
[메모리] forecast_theta 실행 후: 1561.96 MB (변화: +0.00 MB)
[GSM]   [Theta] 완료  첫값=3.12e+08 (메모리: 1562.0 MB)
[GSM]   [DB] 93행 저장 완료
[PROGRESS] [ 108/500] ( 21.6%)  >>  ALBO
[ALBO]   45분기 | 2015-03-31 ~ 2026-03-31
[ALBO]   [SARIMA] 시작  (메모리: 1562.0 MB)
[메모리] forecast_sarima 실행 전: 1561.96 MB
[메모리] find_best_sarima_params 실행 전: 1561.96 MB
[메모리] find_best_sarima_params 실행 후: 1561.96 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1561.96 MB (변화: +0.00 MB)
[ALBO]   [SARIMA] 완료  첫값=1.04e+07 (메모리: 1562.0 MB)
[ALBO]   [ETS] 시작  (메모리: 1562.0 MB)
[메모리] forecast_ets 실행 전: 1561.96 MB
[메모리] forecast_ets 실행 후: 1561.96 MB (변화: +0.01 MB)
[ALBO]   [ETS] 완료  첫값=9.99e+06 (메모리: 1562.0 MB)
[ALBO]   [Prophet] 시작  (메모리: 1562.0 MB)

00:59:53 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1561.96 MB

00:59:53 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1561.53 MB (변화: -0.44 MB)
[ALBO]   [Prophet] 완료  첫값=1.23e+07 (메모리: 1561.5 MB)
[ALBO]   [LSTM] 시작  (메모리: 1561.5 MB)
[메모리] forecast_lstm 실행 전: 1561.53 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1563.33 MB (변화: +1.80 MB)
[ALBO]   [LSTM] 완료  첫값=8.68e+06 (메모리: 1563.3 MB)
[ALBO]   [Theta] 시작  (메모리: 1563.3 MB)
[메모리] forecast_theta 실행 전: 1563.33 MB
[메모리] forecast_theta 실행 후: 1563.33 MB (변화: +0.00 MB)
[ALBO]   [Theta] 완료  첫값=9.18e+06 (메모리: 1563.3 MB)
[ALBO]   [DB] 93행 저장 완료
[PROGRESS] [ 109/500] ( 21.8%)  >>  SPTN
[SPTN]   44분기 | 2015-06-30 ~ 2026-03-31
[SPTN]   [SARIMA] 시작  (메모리: 1563.3 MB)
[메모리] forecast_sarima 실행 전: 1563.33 MB
[메모리] find_best_sarima_params 실행 전: 1563.33 MB
[메모리] find_best_sarima_params 실행 후: 1563.33 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1563.33 MB (변화: +0.00 MB)
[SPTN]   [SARIMA] 완료  첫값=2.94e+09 (메모리: 1563.3 MB)
[SPTN]   [ETS] 시작  (메모리: 1563.3 MB)
[메모리] forecast_ets 실행 전: 1563.33 MB
[메모리] forecast_ets 실행 후: 1563.34 MB (변화: +0.01 MB)
[SPTN]   [ETS] 완료  첫값=2.89e+09 (메모리: 1563.3 MB)
[SPTN]   [Prophet] 시작  (메모리: 1563.3 MB)

01:00:13 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1563.34 MB

01:00:13 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1563.40 MB (변화: +0.06 MB)
[SPTN]   [Prophet] 완료  첫값=2.54e+09 (메모리: 1563.4 MB)
[SPTN]   [LSTM] 시작  (메모리: 1563.4 MB)
[메모리] forecast_lstm 실행 전: 1563.40 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1562.99 MB (변화: -0.41 MB)
[SPTN]   [LSTM] 완료  첫값=2.52e+09 (메모리: 1563.0 MB)
[SPTN]   [Theta] 시작  (메모리: 1563.0 MB)
[메모리] forecast_theta 실행 전: 1562.99 MB
[메모리] forecast_theta 실행 후: 1562.99 MB (변화: +0.00 MB)
[SPTN]   [Theta] 완료  첫값=2.85e+09 (메모리: 1563.0 MB)
[SPTN]   [DB] 92행 저장 완료
[PROGRESS] [ 110/500] ( 22.0%)  >>  SCHN
[SCHN]   45분기 | 2015-03-31 ~ 2026-03-31
[SCHN]   [SARIMA] 시작  (메모리: 1563.0 MB)
[메모리] forecast_sarima 실행 전: 1562.99 MB
[메모리] find_best_sarima_params 실행 전: 1562.99 MB
[메모리] find_best_sarima_params 실행 후: 1562.99 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1562.99 MB (변화: +0.00 MB)
[SCHN]   [SARIMA] 완료  첫값=7.88e+08 (메모리: 1563.0 MB)
[SCHN]   [ETS] 시작  (메모리: 1563.0 MB)
[메모리] forecast_ets 실행 전: 1562.99 MB
[메모리] forecast_ets 실행 후: 1562.99 MB (변화: +0.00 MB)
[SCHN]   [ETS] 완료  첫값=8.36e+08 (메모리: 1563.0 MB)
[SCHN]   [Prophet] 시작  (메모리: 1563.0 MB)

01:00:29 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1562.99 MB

01:00:29 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1563.82 MB (변화: +0.83 MB)
[SCHN]   [Prophet] 완료  첫값=8.10e+08 (메모리: 1563.8 MB)
[SCHN]   [LSTM] 시작  (메모리: 1563.8 MB)
[메모리] forecast_lstm 실행 전: 1563.82 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1563.00 MB (변화: -0.82 MB)
[SCHN]   [LSTM] 완료  첫값=6.70e+08 (메모리: 1563.0 MB)
[SCHN]   [Theta] 시작  (메모리: 1563.0 MB)
[메모리] forecast_theta 실행 전: 1563.00 MB
[메모리] forecast_theta 실행 후: 1563.00 MB (변화: +0.00 MB)
[SCHN]   [Theta] 완료  첫값=8.38e+08 (메모리: 1563.0 MB)
[SCHN]   [DB] 93행 저장 완료
[PROGRESS] [ 111/500] ( 22.2%)  >>  CTMX
[CTMX]   45분기 | 2015-03-31 ~ 2026-03-31
[CTMX]   [SARIMA] 시작  (메모리: 1563.0 MB)
[메모리] forecast_sarima 실행 전: 1563.00 MB
[메모리] find_best_sarima_params 실행 전: 1563.00 MB
[메모리] find_best_sarima_params 실행 후: 1563.00 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1563.00 MB (변화: +0.00 MB)
[CTMX]   [SARIMA] 완료  첫값=5.98e+06 (메모리: 1563.0 MB)
[CTMX]   [ETS] 시작  (메모리: 1563.0 MB)
[메모리] forecast_ets 실행 전: 1563.00 MB
[메모리] forecast_ets 실행 후: 1563.01 MB (변화: +0.00 MB)
[CTMX]   [ETS] 완료  첫값=5.12e+06 (메모리: 1563.0 MB)
[CTMX]   [Prophet] 시작  (메모리: 1563.0 MB)

01:00:46 - cmdstanpy - INFO - Chain [1] start processing
01:00:46 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1563.01 MB
[메모리] forecast_prophet 실행 후: 1563.44 MB (변화: +0.43 MB)
[CTMX]   [Prophet] 완료  첫값=2.74e+07 (메모리: 1563.4 MB)
[CTMX]   [LSTM] 시작  (메모리: 1563.4 MB)
[메모리] forecast_lstm 실행 전: 1563.44 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1563.01 MB (변화: -0.43 MB)
[CTMX]   [LSTM] 완료  첫값=2.49e+07 (메모리: 1563.0 MB)
[CTMX]   [Theta] 시작  (메모리: 1563.0 MB)
[메모리] forecast_theta 실행 전: 1563.01 MB
[메모리] forecast_theta 실행 후: 1563.01 MB (변화: +0.00 MB)
[CTMX]   [Theta] 완료  첫값=6.32e+06 (메모리: 1563.0 MB)
[CTMX]   [DB] 93행 저장 완료
[PROGRESS] [ 112/500] ( 22.4%)  >>  RYI
[RYI]   45분기 | 2015-03-31 ~ 2026-03-31
[RYI]   [SARIMA] 시작  (메모리: 1563.0 MB)
[메모리] forecast_sarima 실행 전: 1563.01 MB
[메모리] find_best_sarima_params 실행 전: 1563.01 MB
[메모리] find_best_sarima_params 실행 후: 1563.01 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1563.01 MB (변화: +0.00 MB)
[RYI]   [SARIMA] 완료  첫값=1.12e+09 (메모리: 1563.0 MB)
[RYI]   [ETS] 시작  (메모리: 1563.0 MB)
[메모리] forecast_ets 실행 전: 1563.01 MB
[메모리] forecast_ets 실행 후: 1563.01 MB (변화: +0.00 MB)
[RYI]   [ETS] 완료  첫값=1.17e+09 (메모리: 1563.0 MB)
[RYI]   [Prophet] 시작  (메모리: 1563.0 MB)

01:01:08 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1563.01 MB

01:01:08 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1563.04 MB (변화: +0.02 MB)
[RYI]   [Prophet] 완료  첫값=1.39e+09 (메모리: 1563.0 MB)
[RYI]   [LSTM] 시작  (메모리: 1563.0 MB)
[메모리] forecast_lstm 실행 전: 1563.04 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1563.93 MB (변화: +0.89 MB)
[RYI]   [LSTM] 완료  첫값=1.22e+09 (메모리: 1563.9 MB)
[RYI]   [Theta] 시작  (메모리: 1563.9 MB)
[메모리] forecast_theta 실행 전: 1563.93 MB
[메모리] forecast_theta 실행 후: 1563.93 MB (변화: +0.00 MB)
[RYI]   [Theta] 완료  첫값=1.17e+09 (메모리: 1563.9 MB)
[RYI]   [DB] 93행 저장 완료
[PROGRESS] [ 113/500] ( 22.6%)  >>  SCSC
[SCSC]   45분기 | 2015-03-31 ~ 2026-03-31
[SCSC]   [SARIMA] 시작  (메모리: 1563.9 MB)
[메모리] forecast_sarima 실행 전: 1563.93 MB
[메모리] find_best_sarima_params 실행 전: 1563.93 MB
[메모리] find_best_sarima_params 실행 후: 1563.93 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1563.93 MB (변화: +0.00 MB)
[SCSC]   [SARIMA] 완료  첫값=7.68e+08 (메모리: 1563.9 MB)
[SCSC]   [ETS] 시작  (메모리: 1563.9 MB)
[메모리] forecast_ets 실행 전: 1563.93 MB
[메모리] forecast_ets 실행 후: 1563.93 MB (변화: +0.00 MB)
[SCSC]   [ETS] 완료  첫값=8.05e+08 (메모리: 1563.9 MB)
[SCSC]   [Prophet] 시작  (메모리: 1563.9 MB)

01:01:31 - cmdstanpy - INFO - Chain [1] start processing
01:01:31 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1563.93 MB
[메모리] forecast_prophet 실행 후: 1563.96 MB (변화: +0.03 MB)
[SCSC]   [Prophet] 완료  첫값=7.95e+08 (메모리: 1564.0 MB)
[SCSC]   [LSTM] 시작  (메모리: 1564.0 MB)
[메모리] forecast_lstm 실행 전: 1563.96 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1563.89 MB (변화: -0.07 MB)
[SCSC]   [LSTM] 완료  첫값=7.79e+08 (메모리: 1563.9 MB)
[SCSC]   [Theta] 시작  (메모리: 1563.9 MB)
[메모리] forecast_theta 실행 전: 1563.89 MB
[메모리] forecast_theta 실행 후: 1563.89 MB (변화: +0.00 MB)
[SCSC]   [Theta] 완료  첫값=7.63e+08 (메모리: 1563.9 MB)
[SCSC]   [DB] 93행 저장 완료
[PROGRESS] [ 114/500] ( 22.8%)  >>  CLB
[CLB]   45분기 | 2015-03-31 ~ 2026-03-31
[CLB]   [SARIMA] 시작  (메모리: 1563.9 MB)
[메모리] forecast_sarima 실행 전: 1563.89 MB
[메모리] find_best_sarima_params 실행 전: 1563.89 MB
[메모리] find_best_sarima_params 실행 후: 1563.89 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1563.89 MB (변화: +0.00 MB)
[CLB]   [SARIMA] 완료  첫값=1.37e+08 (메모리: 1563.9 MB)
[CLB]   [ETS] 시작  (메모리: 1563.9 MB)
[메모리] forecast_ets 실행 전: 1563.89 MB
[메모리] forecast_ets 실행 후: 1563.89 MB (변화: +0.00 MB)
[CLB]   [ETS] 완료  첫값=1.37e+08 (메모리: 1563.9 MB)
[CLB]   [Prophet] 시작  (메모리: 1563.9 MB)

01:01:49 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1563.89 MB

01:01:49 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1563.91 MB (변화: +0.02 MB)
[CLB]   [Prophet] 완료  첫값=1.13e+08 (메모리: 1563.9 MB)
[CLB]   [LSTM] 시작  (메모리: 1563.9 MB)
[메모리] forecast_lstm 실행 전: 1563.91 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1562.75 MB (변화: -1.16 MB)
[CLB]   [LSTM] 완료  첫값=1.27e+08 (메모리: 1562.7 MB)
[CLB]   [Theta] 시작  (메모리: 1562.7 MB)
[메모리] forecast_theta 실행 전: 1562.75 MB
[메모리] forecast_theta 실행 후: 1562.75 MB (변화: +0.00 MB)
[CLB]   [Theta] 완료  첫값=1.38e+08 (메모리: 1562.7 MB)
[CLB]   [DB] 93행 저장 완료
[PROGRESS] [ 115/500] ( 23.0%)  >>  EPC
[EPC]   45분기 | 2015-03-31 ~ 2026-03-31
[EPC]   [SARIMA] 시작  (메모리: 1562.7 MB)
[메모리] forecast_sarima 실행 전: 1562.75 MB
[메모리] find_best_sarima_params 실행 전: 1562.75 MB
[메모리] find_best_sarima_params 실행 후: 1562.75 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1562.75 MB (변화: +0.00 MB)
[EPC]   [SARIMA] 완료  첫값=4.86e+08 (메모리: 1562.7 MB)
[EPC]   [ETS] 시작  (메모리: 1562.7 MB)
[메모리] forecast_ets 실행 전: 1562.75 MB
[메모리] forecast_ets 실행 후: 1562.81 MB (변화: +0.07 MB)
[EPC]   [ETS] 완료  첫값=4.54e+08 (메모리: 1562.8 MB)
[EPC]   [Prophet] 시작  (메모리: 1562.8 MB)

01:02:09 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1562.81 MB

01:02:09 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1563.27 MB (변화: +0.46 MB)
[EPC]   [Prophet] 완료  첫값=4.82e+08 (메모리: 1563.3 MB)
[EPC]   [LSTM] 시작  (메모리: 1563.3 MB)
[메모리] forecast_lstm 실행 전: 1563.27 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1563.23 MB (변화: -0.04 MB)
[EPC]   [LSTM] 완료  첫값=5.48e+08 (메모리: 1563.2 MB)
[EPC]   [Theta] 시작  (메모리: 1563.2 MB)
[메모리] forecast_theta 실행 전: 1563.23 MB
[메모리] forecast_theta 실행 후: 1563.23 MB (변화: +0.00 MB)
[EPC]   [Theta] 완료  첫값=4.51e+08 (메모리: 1563.2 MB)
[EPC]   [DB] 93행 저장 완료
[PROGRESS] [ 116/500] ( 23.2%)  >>  IART
[IART]   45분기 | 2015-03-31 ~ 2026-03-31
[IART]   [SARIMA] 시작  (메모리: 1563.2 MB)
[메모리] forecast_sarima 실행 전: 1563.23 MB
[메모리] find_best_sarima_params 실행 전: 1563.23 MB
[메모리] find_best_sarima_params 실행 후: 1563.23 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1563.23 MB (변화: +0.00 MB)
[IART]   [SARIMA] 완료  첫값=4.13e+08 (메모리: 1563.2 MB)
[IART]   [ETS] 시작  (메모리: 1563.2 MB)
[메모리] forecast_ets 실행 전: 1563.23 MB
[메모리] forecast_ets 실행 후: 1563.23 MB (변화: +0.00 MB)
[IART]   [ETS] 완료  첫값=4.09e+08 (메모리: 1563.2 MB)
[IART]   [Prophet] 시작  (메모리: 1563.2 MB)

01:02:27 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1563.23 MB

01:02:27 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1563.53 MB (변화: +0.30 MB)
[IART]   [Prophet] 완료  첫값=4.23e+08 (메모리: 1563.5 MB)
[IART]   [LSTM] 시작  (메모리: 1563.5 MB)
[메모리] forecast_lstm 실행 전: 1563.53 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1564.57 MB (변화: +1.04 MB)
[IART]   [LSTM] 완료  첫값=3.95e+08 (메모리: 1564.6 MB)
[IART]   [Theta] 시작  (메모리: 1564.6 MB)
[메모리] forecast_theta 실행 전: 1564.57 MB
[메모리] forecast_theta 실행 후: 1564.57 MB (변화: +0.00 MB)
[IART]   [Theta] 완료  첫값=4.03e+08 (메모리: 1564.6 MB)
[IART]   [DB] 93행 저장 완료
[PROGRESS] [ 117/500] ( 23.4%)  >>  TMST
[TMST]   45분기 | 2015-03-31 ~ 2026-03-31
[TMST]   [SARIMA] 시작  (메모리: 1564.6 MB)
[메모리] forecast_sarima 실행 전: 1564.57 MB
[메모리] find_best_sarima_params 실행 전: 1564.57 MB
[메모리] find_best_sarima_params 실행 후: 1564.57 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1564.57 MB (변화: +0.00 MB)
[TMST]   [SARIMA] 완료  첫값=3.06e+08 (메모리: 1564.6 MB)
[TMST]   [ETS] 시작  (메모리: 1564.6 MB)
[메모리] forecast_ets 실행 전: 1564.57 MB
[메모리] forecast_ets 실행 후: 1564.58 MB (변화: +0.00 MB)
[TMST]   [ETS] 완료  첫값=2.97e+08 (메모리: 1564.6 MB)
[TMST]   [Prophet] 시작  (메모리: 1564.6 MB)

01:02:50 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1564.58 MB

01:02:50 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1564.61 MB (변화: +0.04 MB)
[TMST]   [Prophet] 완료  첫값=3.10e+08 (메모리: 1564.6 MB)
[TMST]   [LSTM] 시작  (메모리: 1564.6 MB)
[메모리] forecast_lstm 실행 전: 1564.61 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1564.30 MB (변화: -0.31 MB)
[TMST]   [LSTM] 완료  첫값=2.77e+08 (메모리: 1564.3 MB)
[TMST]   [Theta] 시작  (메모리: 1564.3 MB)
[메모리] forecast_theta 실행 전: 1564.30 MB
[메모리] forecast_theta 실행 후: 1564.30 MB (변화: +0.00 MB)
[TMST]   [Theta] 완료  첫값=3.06e+08 (메모리: 1564.3 MB)
[TMST]   [DB] 93행 저장 완료
[PROGRESS] [ 118/500] ( 23.6%)  >>  TELL
[TELL]   45분기 | 2015-03-31 ~ 2026-03-31
[TELL]   [SARIMA] 시작  (메모리: 1564.3 MB)
[메모리] forecast_sarima 실행 전: 1564.30 MB
[메모리] find_best_sarima_params 실행 전: 1564.30 MB
[메모리] find_best_sarima_params 실행 후: 1564.30 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1564.30 MB (변화: +0.00 MB)
[TELL]   [SARIMA] 완료  첫값=-9.12e+06 (메모리: 1564.3 MB)
[TELL]   [ETS] 시작  (메모리: 1564.3 MB)
[메모리] forecast_ets 실행 전: 1564.30 MB
[메모리] forecast_ets 실행 후: 1564.30 MB (변화: +0.00 MB)
[TELL]   [ETS] 완료  첫값=-1.01e+06 (메모리: 1564.3 MB)
[TELL]   [Prophet] 시작  (메모리: 1564.3 MB)

01:03:06 - cmdstanpy - INFO - Chain [1] start processing
01:03:06 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1564.30 MB
[메모리] forecast_prophet 실행 후: 1563.82 MB (변화: -0.48 MB)
[TELL]   [Prophet] 완료  첫값=3.10e+07 (메모리: 1563.8 MB)
[TELL]   [LSTM] 시작  (메모리: 1563.8 MB)
[메모리] forecast_lstm 실행 전: 1563.82 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1563.71 MB (변화: -0.11 MB)
[TELL]   [LSTM] 완료  첫값=7.54e+06 (메모리: 1563.7 MB)
[TELL]   [Theta] 시작  (메모리: 1563.7 MB)
[메모리] forecast_theta 실행 전: 1563.71 MB
[메모리] forecast_theta 실행 후: 1563.71 MB (변화: +0.00 MB)
[TELL]   [Theta] 완료  첫값=6.63e+05 (메모리: 1563.7 MB)
[TELL]   [DB] 93행 저장 완료
[PROGRESS] [ 119/500] ( 23.8%)  >>  LIND
[LIND]   45분기 | 2015-03-31 ~ 2026-03-31
[LIND]   [SARIMA] 시작  (메모리: 1563.7 MB)
[메모리] forecast_sarima 실행 전: 1563.71 MB
[메모리] find_best_sarima_params 실행 전: 1563.71 MB
[메모리] find_best_sarima_params 실행 후: 1563.71 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1563.71 MB (변화: +0.00 MB)
[LIND]   [SARIMA] 완료  첫값=2.48e+08 (메모리: 1563.7 MB)
[LIND]   [ETS] 시작  (메모리: 1563.7 MB)
[메모리] forecast_ets 실행 전: 1563.71 MB
[메모리] forecast_ets 실행 후: 1563.71 MB (변화: +0.00 MB)
[LIND]   [ETS] 완료  첫값=2.28e+08 (메모리: 1563.7 MB)
[LIND]   [Prophet] 시작  (메모리: 1563.7 MB)

01:03:28 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1563.71 MB

01:03:29 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1563.75 MB (변화: +0.04 MB)
[LIND]   [Prophet] 완료  첫값=1.74e+08 (메모리: 1563.8 MB)
[LIND]   [LSTM] 시작  (메모리: 1563.8 MB)
[메모리] forecast_lstm 실행 전: 1563.75 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1564.99 MB (변화: +1.24 MB)
[LIND]   [LSTM] 완료  첫값=2.46e+08 (메모리: 1565.0 MB)
[LIND]   [Theta] 시작  (메모리: 1565.0 MB)
[메모리] forecast_theta 실행 전: 1564.99 MB
[메모리] forecast_theta 실행 후: 1564.99 MB (변화: +0.00 MB)
[LIND]   [Theta] 완료  첫값=2.24e+08 (메모리: 1565.0 MB)
[LIND]   [DB] 93행 저장 완료
[PROGRESS] [ 120/500] ( 24.0%)  >>  DJCO
[DJCO]   45분기 | 2015-03-31 ~ 2026-03-31
[DJCO]   [SARIMA] 시작  (메모리: 1565.0 MB)
[메모리] forecast_sarima 실행 전: 1564.99 MB
[메모리] find_best_sarima_params 실행 전: 1564.99 MB
[메모리] find_best_sarima_params 실행 후: 1564.99 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1564.99 MB (변화: +0.00 MB)
[DJCO]   [SARIMA] 완료  첫값=2.83e+07 (메모리: 1565.0 MB)
[DJCO]   [ETS] 시작  (메모리: 1565.0 MB)
[메모리] forecast_ets 실행 전: 1564.99 MB
[메모리] forecast_ets 실행 후: 1564.99 MB (변화: +0.00 MB)
[DJCO]   [ETS] 완료  첫값=3.12e+07 (메모리: 1565.0 MB)
[DJCO]   [Prophet] 시작  (메모리: 1565.0 MB)

01:03:53 - cmdstanpy - INFO - Chain [1] start processing
01:03:53 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1564.99 MB
[메모리] forecast_prophet 실행 후: 1564.53 MB (변화: -0.46 MB)
[DJCO]   [Prophet] 완료  첫값=2.15e+07 (메모리: 1564.5 MB)
[DJCO]   [LSTM] 시작  (메모리: 1564.5 MB)
[메모리] forecast_lstm 실행 전: 1564.53 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1565.52 MB (변화: +0.99 MB)
[DJCO]   [LSTM] 완료  첫값=3.18e+07 (메모리: 1565.5 MB)
[DJCO]   [Theta] 시작  (메모리: 1565.5 MB)
[메모리] forecast_theta 실행 전: 1565.52 MB
[메모리] forecast_theta 실행 후: 1565.52 MB (변화: +0.00 MB)
[DJCO]   [Theta] 완료  첫값=3.06e+07 (메모리: 1565.5 MB)
[DJCO]   [DB] 93행 저장 완료
[PROGRESS] [ 121/500] ( 24.2%)  >>  PCRX
[PCRX]   45분기 | 2015-03-31 ~ 2026-03-31
[PCRX]   [SARIMA] 시작  (메모리: 1565.5 MB)
[메모리] forecast_sarima 실행 전: 1565.52 MB
[메모리] find_best_sarima_params 실행 전: 1565.52 MB
[메모리] find_best_sarima_params 실행 후: 1565.53 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1565.53 MB (변화: +0.00 MB)
[PCRX]   [SARIMA] 완료  첫값=1.91e+08 (메모리: 1565.5 MB)
[PCRX]   [ETS] 시작  (메모리: 1565.5 MB)
[메모리] forecast_ets 실행 전: 1565.53 MB
[메모리] forecast_ets 실행 후: 1565.53 MB (변화: +0.00 MB)
[PCRX]   [ETS] 완료  첫값=1.86e+08 (메모리: 1565.5 MB)
[PCRX]   [Prophet] 시작  (메모리: 1565.5 MB)

01:04:15 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1565.53 MB

01:04:15 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1565.55 MB (변화: +0.02 MB)
[PCRX]   [Prophet] 완료  첫값=1.99e+08 (메모리: 1565.5 MB)
[PCRX]   [LSTM] 시작  (메모리: 1565.5 MB)
[메모리] forecast_lstm 실행 전: 1565.55 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1565.62 MB (변화: +0.07 MB)
[PCRX]   [LSTM] 완료  첫값=1.93e+08 (메모리: 1565.6 MB)
[PCRX]   [Theta] 시작  (메모리: 1565.6 MB)
[메모리] forecast_theta 실행 전: 1565.62 MB
[메모리] forecast_theta 실행 후: 1565.62 MB (변화: +0.00 MB)
[PCRX]   [Theta] 완료  첫값=1.82e+08 (메모리: 1565.6 MB)
[PCRX]   [DB] 93행 저장 완료
[PROGRESS] [ 122/500] ( 24.4%)  >>  GCI
[GCI]   45분기 | 2015-03-31 ~ 2026-03-31
[GCI]   [SARIMA] 시작  (메모리: 1565.6 MB)
[메모리] forecast_sarima 실행 전: 1565.62 MB
[메모리] find_best_sarima_params 실행 전: 1565.62 MB
[메모리] find_best_sarima_params 실행 후: 1565.62 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1565.62 MB (변화: +0.00 MB)
[GCI]   [SARIMA] 완료  첫값=5.61e+08 (메모리: 1565.6 MB)
[GCI]   [ETS] 시작  (메모리: 1565.6 MB)
[메모리] forecast_ets 실행 전: 1565.62 MB
[메모리] forecast_ets 실행 후: 1565.62 MB (변화: +0.00 MB)
[GCI]   [ETS] 완료  첫값=5.62e+08 (메모리: 1565.6 MB)
[GCI]   [Prophet] 시작  (메모리: 1565.6 MB)

01:04:36 - cmdstanpy - INFO - Chain [1] start processing
01:04:36 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1565.62 MB
[메모리] forecast_prophet 실행 후: 1565.62 MB (변화: +0.01 MB)
[GCI]   [Prophet] 완료  첫값=7.78e+08 (메모리: 1565.6 MB)
[GCI]   [LSTM] 시작  (메모리: 1565.6 MB)
[메모리] forecast_lstm 실행 전: 1565.62 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1565.70 MB (변화: +0.08 MB)
[GCI]   [LSTM] 완료  첫값=6.10e+08 (메모리: 1565.7 MB)
[GCI]   [Theta] 시작  (메모리: 1565.7 MB)
[메모리] forecast_theta 실행 전: 1565.70 MB
[메모리] forecast_theta 실행 후: 1565.70 MB (변화: +0.00 MB)
[GCI]   [Theta] 완료  첫값=5.51e+08 (메모리: 1565.7 MB)
[GCI]   [DB] 93행 저장 완료
[PROGRESS] [ 123/500] ( 24.6%)  >>  ITRN
[ITRN]   45분기 | 2015-03-31 ~ 2026-03-31
[ITRN]   [SARIMA] 시작  (메모리: 1565.7 MB)
[메모리] forecast_sarima 실행 전: 1565.70 MB
[메모리] find_best_sarima_params 실행 전: 1565.70 MB
[메모리] find_best_sarima_params 실행 후: 1565.70 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1565.70 MB (변화: +0.00 MB)
[ITRN]   [SARIMA] 완료  첫값=9.46e+07 (메모리: 1565.7 MB)
[ITRN]   [ETS] 시작  (메모리: 1565.7 MB)
[메모리] forecast_ets 실행 전: 1565.70 MB
[메모리] forecast_ets 실행 후: 1565.71 MB (변화: +0.00 MB)
[ITRN]   [ETS] 완료  첫값=9.22e+07 (메모리: 1565.7 MB)
[ITRN]   [Prophet] 시작  (메모리: 1565.7 MB)

01:04:55 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1565.71 MB

01:04:55 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1566.99 MB (변화: +1.28 MB)
[ITRN]   [Prophet] 완료  첫값=9.13e+07 (메모리: 1567.0 MB)
[ITRN]   [LSTM] 시작  (메모리: 1567.0 MB)
[메모리] forecast_lstm 실행 전: 1566.99 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1567.10 MB (변화: +0.11 MB)
[ITRN]   [LSTM] 완료  첫값=1.08e+08 (메모리: 1567.1 MB)
[ITRN]   [Theta] 시작  (메모리: 1567.1 MB)
[메모리] forecast_theta 실행 전: 1567.10 MB
[메모리] forecast_theta 실행 후: 1567.10 MB (변화: +0.00 MB)
[ITRN]   [Theta] 완료  첫값=8.99e+07 (메모리: 1567.1 MB)
[ITRN]   [DB] 93행 저장 완료
[PROGRESS] [ 124/500] ( 24.8%)  >>  VERB
[VERB]   45분기 | 2015-03-31 ~ 2026-03-31
[VERB]   [SARIMA] 시작  (메모리: 1567.1 MB)
[메모리] forecast_sarima 실행 전: 1567.10 MB
[메모리] find_best_sarima_params 실행 전: 1567.10 MB
[메모리] find_best_sarima_params 실행 후: 1567.10 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1567.10 MB (변화: +0.00 MB)
[VERB]   [SARIMA] 완료  첫값=3.25e+06 (메모리: 1567.1 MB)
[VERB]   [ETS] 시작  (메모리: 1567.1 MB)
[메모리] forecast_ets 실행 전: 1567.10 MB
[메모리] forecast_ets 실행 후: 1567.10 MB (변화: +0.00 MB)
[VERB]   [ETS] 완료  첫값=3.78e+06 (메모리: 1567.1 MB)
[VERB]   [Prophet] 시작  (메모리: 1567.1 MB)

01:05:10 - cmdstanpy - INFO - Chain [1] start processing
01:05:11 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1567.10 MB
[메모리] forecast_prophet 실행 후: 1566.77 MB (변화: -0.33 MB)
[VERB]   [Prophet] 완료  첫값=2.44e+06 (메모리: 1566.8 MB)
[VERB]   [LSTM] 시작  (메모리: 1566.8 MB)
[메모리] forecast_lstm 실행 전: 1566.77 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1567.72 MB (변화: +0.95 MB)
[VERB]   [LSTM] 완료  첫값=1.71e+06 (메모리: 1567.7 MB)
[VERB]   [Theta] 시작  (메모리: 1567.7 MB)
[메모리] forecast_theta 실행 전: 1567.72 MB
[메모리] forecast_theta 실행 후: 1567.72 MB (변화: +0.00 MB)
[VERB]   [Theta] 완료  첫값=3.64e+06 (메모리: 1567.7 MB)
[VERB]   [DB] 93행 저장 완료
[PROGRESS] [ 125/500] ( 25.0%)  >>  GES
[GES]   45분기 | 2015-03-31 ~ 2026-03-31
[GES]   [SARIMA] 시작  (메모리: 1567.7 MB)
[메모리] forecast_sarima 실행 전: 1567.72 MB
[메모리] find_best_sarima_params 실행 전: 1567.72 MB
[메모리] find_best_sarima_params 실행 후: 1567.73 MB (변화: +0.01 MB)
[메모리] forecast_sarima 실행 후: 1567.73 MB (변화: +0.01 MB)
[GES]   [SARIMA] 완료  첫값=5.54e+08 (메모리: 1567.7 MB)
[GES]   [ETS] 시작  (메모리: 1567.7 MB)
[메모리] forecast_ets 실행 전: 1567.73 MB
[메모리] forecast_ets 실행 후: 1567.73 MB (변화: +0.00 MB)
[GES]   [ETS] 완료  첫값=5.75e+08 (메모리: 1567.7 MB)
[GES]   [Prophet] 시작  (메모리: 1567.7 MB)

01:05:33 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1567.73 MB

01:05:33 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1568.12 MB (변화: +0.39 MB)
[GES]   [Prophet] 완료  첫값=7.50e+08 (메모리: 1568.1 MB)
[GES]   [LSTM] 시작  (메모리: 1568.1 MB)
[메모리] forecast_lstm 실행 전: 1568.12 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1567.30 MB (변화: -0.82 MB)
[GES]   [LSTM] 완료  첫값=8.75e+08 (메모리: 1567.3 MB)
[GES]   [Theta] 시작  (메모리: 1567.3 MB)
[메모리] forecast_theta 실행 전: 1567.30 MB
[메모리] forecast_theta 실행 후: 1567.30 MB (변화: +0.00 MB)
[GES]   [Theta] 완료  첫값=5.62e+08 (메모리: 1567.3 MB)
[GES]   [DB] 93행 저장 완료
[PROGRESS] [ 126/500] ( 25.2%)  >>  GNK
[GNK]   45분기 | 2015-03-31 ~ 2026-03-31
[GNK]   [SARIMA] 시작  (메모리: 1567.3 MB)
[메모리] forecast_sarima 실행 전: 1567.30 MB
[메모리] find_best_sarima_params 실행 전: 1567.30 MB
[메모리] find_best_sarima_params 실행 후: 1567.30 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1567.30 MB (변화: +0.00 MB)
[GNK]   [SARIMA] 완료  첫값=8.68e+07 (메모리: 1567.3 MB)
[GNK]   [ETS] 시작  (메모리: 1567.3 MB)
[메모리] forecast_ets 실행 전: 1567.30 MB
[메모리] forecast_ets 실행 후: 1567.30 MB (변화: +0.00 MB)
[GNK]   [ETS] 완료  첫값=8.47e+07 (메모리: 1567.3 MB)
[GNK]   [Prophet] 시작  (메모리: 1567.3 MB)

01:05:51 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1567.30 MB

01:05:51 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1567.72 MB (변화: +0.43 MB)
[GNK]   [Prophet] 완료  첫값=1.23e+08 (메모리: 1567.7 MB)
[GNK]   [LSTM] 시작  (메모리: 1567.7 MB)
[메모리] forecast_lstm 실행 전: 1567.72 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1568.54 MB (변화: +0.82 MB)
[GNK]   [LSTM] 완료  첫값=9.67e+07 (메모리: 1568.5 MB)
[GNK]   [Theta] 시작  (메모리: 1568.5 MB)
[메모리] forecast_theta 실행 전: 1568.54 MB
[메모리] forecast_theta 실행 후: 1568.54 MB (변화: +0.00 MB)
[GNK]   [Theta] 완료  첫값=8.51e+07 (메모리: 1568.5 MB)
[GNK]   [DB] 93행 저장 완료
[PROGRESS] [ 127/500] ( 25.4%)  >>  GERN
[GERN]   45분기 | 2015-03-31 ~ 2026-03-31
[GERN]   [SARIMA] 시작  (메모리: 1568.5 MB)
[메모리] forecast_sarima 실행 전: 1568.54 MB
[메모리] find_best_sarima_params 실행 전: 1568.54 MB
[메모리] find_best_sarima_params 실행 후: 1568.54 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1568.54 MB (변화: +0.00 MB)
[GERN]   [SARIMA] 완료  첫값=4.40e+07 (메모리: 1568.5 MB)
[GERN]   [ETS] 시작  (메모리: 1568.5 MB)
[메모리] forecast_ets 실행 전: 1568.54 MB
[메모리] forecast_ets 실행 후: 1568.54 MB (변화: +0.00 MB)
[GERN]   [ETS] 완료  첫값=3.59e+07 (메모리: 1568.5 MB)
[GERN]   [Prophet] 시작  (메모리: 1568.5 MB)

01:06:10 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1568.54 MB

01:06:10 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1568.10 MB (변화: -0.45 MB)
[GERN]   [Prophet] 완료  첫값=2.33e+07 (메모리: 1568.1 MB)
[GERN]   [LSTM] 시작  (메모리: 1568.1 MB)
[메모리] forecast_lstm 실행 전: 1568.10 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1570.18 MB (변화: +2.08 MB)
[GERN]   [LSTM] 완료  첫값=7.57e+07 (메모리: 1570.2 MB)
[GERN]   [Theta] 시작  (메모리: 1570.2 MB)
[메모리] forecast_theta 실행 전: 1570.18 MB
[메모리] forecast_theta 실행 후: 1570.18 MB (변화: +0.00 MB)
[GERN]   [Theta] 완료  첫값=3.14e+07 (메모리: 1570.2 MB)
[GERN]   [DB] 93행 저장 완료
[PROGRESS] [ 128/500] ( 25.6%)  >>  HNRG
[HNRG]   45분기 | 2015-03-31 ~ 2026-03-31
[HNRG]   [SARIMA] 시작  (메모리: 1570.2 MB)
[메모리] forecast_sarima 실행 전: 1570.18 MB
[메모리] find_best_sarima_params 실행 전: 1570.18 MB
[메모리] find_best_sarima_params 실행 후: 1570.18 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1570.18 MB (변화: +0.00 MB)
[HNRG]   [SARIMA] 완료  첫값=1.47e+08 (메모리: 1570.2 MB)
[HNRG]   [ETS] 시작  (메모리: 1570.2 MB)
[메모리] forecast_ets 실행 전: 1570.18 MB
[메모리] forecast_ets 실행 후: 1570.18 MB (변화: +0.00 MB)
[HNRG]   [ETS] 완료  첫값=1.36e+08 (메모리: 1570.2 MB)
[HNRG]   [Prophet] 시작  (메모리: 1570.2 MB)

01:06:33 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1570.18 MB

01:06:34 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1569.74 MB (변화: -0.44 MB)
[HNRG]   [Prophet] 완료  첫값=1.25e+08 (메모리: 1569.7 MB)
[HNRG]   [LSTM] 시작  (메모리: 1569.7 MB)
[메모리] forecast_lstm 실행 전: 1569.74 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1570.75 MB (변화: +1.01 MB)
[HNRG]   [LSTM] 완료  첫값=1.16e+08 (메모리: 1570.8 MB)
[HNRG]   [Theta] 시작  (메모리: 1570.8 MB)
[메모리] forecast_theta 실행 전: 1570.75 MB
[메모리] forecast_theta 실행 후: 1570.75 MB (변화: +0.00 MB)
[HNRG]   [Theta] 완료  첫값=1.48e+08 (메모리: 1570.8 MB)
[HNRG]   [DB] 93행 저장 완료
[PROGRESS] [ 129/500] ( 25.8%)  >>  PLOW
[PLOW]   45분기 | 2015-03-31 ~ 2026-03-31
[PLOW]   [SARIMA] 시작  (메모리: 1570.8 MB)
[메모리] forecast_sarima 실행 전: 1570.75 MB
[메모리] find_best_sarima_params 실행 전: 1570.75 MB
[메모리] find_best_sarima_params 실행 후: 1570.75 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1570.75 MB (변화: +0.00 MB)
[PLOW]   [SARIMA] 완료  첫값=2.38e+08 (메모리: 1570.8 MB)
[PLOW]   [ETS] 시작  (메모리: 1570.8 MB)
[메모리] forecast_ets 실행 전: 1570.75 MB
[메모리] forecast_ets 실행 후: 1570.76 MB (변화: +0.01 MB)
[PLOW]   [ETS] 완료  첫값=2.14e+08 (메모리: 1570.8 MB)
[PLOW]   [Prophet] 시작  (메모리: 1570.8 MB)

01:06:52 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1570.76 MB

01:06:52 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1570.80 MB (변화: +0.04 MB)
[PLOW]   [Prophet] 완료  첫값=1.64e+08 (메모리: 1570.8 MB)
[PLOW]   [LSTM] 시작  (메모리: 1570.8 MB)
[메모리] forecast_lstm 실행 전: 1570.80 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1570.03 MB (변화: -0.77 MB)
[PLOW]   [LSTM] 완료  첫값=1.72e+08 (메모리: 1570.0 MB)
[PLOW]   [Theta] 시작  (메모리: 1570.0 MB)
[메모리] forecast_theta 실행 전: 1570.03 MB
[메모리] forecast_theta 실행 후: 1570.03 MB (변화: +0.00 MB)
[PLOW]   [Theta] 완료  첫값=2.32e+08 (메모리: 1570.0 MB)
[PLOW]   [DB] 93행 저장 완료
[PROGRESS] [ 130/500] ( 26.0%)  >>  NPK
[NPK]   44분기 | 2015-06-30 ~ 2026-03-31
[NPK]   [SARIMA] 시작  (메모리: 1570.0 MB)
[메모리] forecast_sarima 실행 전: 1570.03 MB
[메모리] find_best_sarima_params 실행 전: 1570.03 MB
[메모리] find_best_sarima_params 실행 후: 1570.03 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1570.03 MB (변화: +0.00 MB)
[NPK]   [SARIMA] 완료  첫값=8.93e+07 (메모리: 1570.0 MB)
[NPK]   [ETS] 시작  (메모리: 1570.0 MB)
[메모리] forecast_ets 실행 전: 1570.03 MB
[메모리] forecast_ets 실행 후: 1570.03 MB (변화: +0.00 MB)
[NPK]   [ETS] 완료  첫값=9.97e+07 (메모리: 1570.0 MB)
[NPK]   [Prophet] 시작  (메모리: 1570.0 MB)

01:07:10 - cmdstanpy - INFO - Chain [1] start processing
01:07:10 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1570.03 MB
[메모리] forecast_prophet 실행 후: 1570.86 MB (변화: +0.82 MB)
[NPK]   [Prophet] 완료  첫값=1.00e+08 (메모리: 1570.9 MB)
[NPK]   [LSTM] 시작  (메모리: 1570.9 MB)
[메모리] forecast_lstm 실행 전: 1570.86 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1570.89 MB (변화: +0.03 MB)
[NPK]   [LSTM] 완료  첫값=9.85e+07 (메모리: 1570.9 MB)
[NPK]   [Theta] 시작  (메모리: 1570.9 MB)
[메모리] forecast_theta 실행 전: 1570.89 MB
[메모리] forecast_theta 실행 후: 1570.89 MB (변화: +0.00 MB)
[NPK]   [Theta] 완료  첫값=1.12e+08 (메모리: 1570.9 MB)
[NPK]   [DB] 92행 저장 완료
[PROGRESS] [ 131/500] ( 26.2%)  >>  JBSS
[JBSS]   45분기 | 2015-03-31 ~ 2026-03-31
[JBSS]   [SARIMA] 시작  (메모리: 1570.9 MB)
[메모리] forecast_sarima 실행 전: 1570.89 MB
[메모리] find_best_sarima_params 실행 전: 1570.89 MB
[메모리] find_best_sarima_params 실행 후: 1570.89 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1570.89 MB (변화: +0.00 MB)
[JBSS]   [SARIMA] 완료  첫값=3.30e+08 (메모리: 1570.9 MB)
[JBSS]   [ETS] 시작  (메모리: 1570.9 MB)
[메모리] forecast_ets 실행 전: 1570.89 MB
[메모리] forecast_ets 실행 후: 1570.89 MB (변화: +0.00 MB)
[JBSS]   [ETS] 완료  첫값=3.09e+08 (메모리: 1570.9 MB)
[JBSS]   [Prophet] 시작  (메모리: 1570.9 MB)

01:07:28 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1570.89 MB

01:07:28 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1570.91 MB (변화: +0.02 MB)
[JBSS]   [Prophet] 완료  첫값=2.90e+08 (메모리: 1570.9 MB)
[JBSS]   [LSTM] 시작  (메모리: 1570.9 MB)
[메모리] forecast_lstm 실행 전: 1570.91 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1570.03 MB (변화: -0.88 MB)
[JBSS]   [LSTM] 완료  첫값=2.81e+08 (메모리: 1570.0 MB)
[JBSS]   [Theta] 시작  (메모리: 1570.0 MB)
[메모리] forecast_theta 실행 전: 1570.03 MB
[메모리] forecast_theta 실행 후: 1570.03 MB (변화: +0.00 MB)
[JBSS]   [Theta] 완료  첫값=3.08e+08 (메모리: 1570.0 MB)
[JBSS]   [DB] 93행 저장 완료
[PROGRESS] [ 132/500] ( 26.4%)  >>  CAPL
[CAPL]   45분기 | 2015-03-31 ~ 2026-03-31
[CAPL]   [SARIMA] 시작  (메모리: 1570.0 MB)
[메모리] forecast_sarima 실행 전: 1570.03 MB
[메모리] find_best_sarima_params 실행 전: 1570.03 MB
[메모리] find_best_sarima_params 실행 후: 1570.03 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1570.03 MB (변화: +0.00 MB)
[CAPL]   [SARIMA] 완료  첫값=1.07e+09 (메모리: 1570.0 MB)
[CAPL]   [ETS] 시작  (메모리: 1570.0 MB)
[메모리] forecast_ets 실행 전: 1570.03 MB
[메모리] forecast_ets 실행 후: 1570.03 MB (변화: +0.00 MB)
[CAPL]   [ETS] 완료  첫값=1.19e+09 (메모리: 1570.0 MB)
[CAPL]   [Prophet] 시작  (메모리: 1570.0 MB)

01:07:47 - cmdstanpy - INFO - Chain [1] start processing
01:07:47 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1570.03 MB
[메모리] forecast_prophet 실행 후: 1570.47 MB (변화: +0.44 MB)
[CAPL]   [Prophet] 완료  첫값=1.15e+09 (메모리: 1570.5 MB)
[CAPL]   [LSTM] 시작  (메모리: 1570.5 MB)
[메모리] forecast_lstm 실행 전: 1570.47 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1570.08 MB (변화: -0.39 MB)
[CAPL]   [LSTM] 완료  첫값=9.37e+08 (메모리: 1570.1 MB)
[CAPL]   [Theta] 시작  (메모리: 1570.1 MB)
[메모리] forecast_theta 실행 전: 1570.08 MB
[메모리] forecast_theta 실행 후: 1570.08 MB (변화: +0.00 MB)
[CAPL]   [Theta] 완료  첫값=1.17e+09 (메모리: 1570.1 MB)
[CAPL]   [DB] 93행 저장 완료
[PROGRESS] [ 133/500] ( 26.6%)  >>  SMP
[SMP]   45분기 | 2015-03-31 ~ 2026-03-31
[SMP]   [SARIMA] 시작  (메모리: 1570.1 MB)
[메모리] forecast_sarima 실행 전: 1570.08 MB
[메모리] find_best_sarima_params 실행 전: 1570.08 MB
[메모리] find_best_sarima_params 실행 후: 1570.08 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1570.08 MB (변화: +0.00 MB)
[SMP]   [SARIMA] 완료  첫값=5.62e+08 (메모리: 1570.1 MB)
[SMP]   [ETS] 시작  (메모리: 1570.1 MB)
[메모리] forecast_ets 실행 전: 1570.08 MB
[메모리] forecast_ets 실행 후: 1570.09 MB (변화: +0.01 MB)
[SMP]   [ETS] 완료  첫값=5.67e+08 (메모리: 1570.1 MB)
[SMP]   [Prophet] 시작  (메모리: 1570.1 MB)

01:08:06 - cmdstanpy - INFO - Chain [1] start processing
01:08:06 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1570.09 MB
[메모리] forecast_prophet 실행 후: 1570.24 MB (변화: +0.16 MB)
[SMP]   [Prophet] 완료  첫값=4.26e+08 (메모리: 1570.2 MB)
[SMP]   [LSTM] 시작  (메모리: 1570.2 MB)
[메모리] forecast_lstm 실행 전: 1570.24 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1569.80 MB (변화: -0.44 MB)
[SMP]   [LSTM] 완료  첫값=4.14e+08 (메모리: 1569.8 MB)
[SMP]   [Theta] 시작  (메모리: 1569.8 MB)
[메모리] forecast_theta 실행 전: 1569.80 MB
[메모리] forecast_theta 실행 후: 1569.80 MB (변화: +0.00 MB)
[SMP]   [Theta] 완료  첫값=5.61e+08 (메모리: 1569.8 MB)
[SMP]   [DB] 93행 저장 완료
[PROGRESS] [ 134/500] ( 26.8%)  >>  AMWD
[AMWD]   45분기 | 2015-03-31 ~ 2026-03-31
[AMWD]   [SARIMA] 시작  (메모리: 1569.8 MB)
[메모리] forecast_sarima 실행 전: 1569.80 MB
[메모리] find_best_sarima_params 실행 전: 1569.80 MB
[메모리] find_best_sarima_params 실행 후: 1569.80 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1569.80 MB (변화: +0.00 MB)
[AMWD]   [SARIMA] 완료  첫값=4.00e+08 (메모리: 1569.8 MB)
[AMWD]   [ETS] 시작  (메모리: 1569.8 MB)
[메모리] forecast_ets 실행 전: 1569.80 MB
[메모리] forecast_ets 실행 후: 1569.80 MB (변화: +0.00 MB)
[AMWD]   [ETS] 완료  첫값=4.27e+08 (메모리: 1569.8 MB)
[AMWD]   [Prophet] 시작  (메모리: 1569.8 MB)

01:08:26 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1569.80 MB

01:08:26 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1570.23 MB (변화: +0.43 MB)
[AMWD]   [Prophet] 완료  첫값=4.22e+08 (메모리: 1570.2 MB)
[AMWD]   [LSTM] 시작  (메모리: 1570.2 MB)
[메모리] forecast_lstm 실행 전: 1570.23 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1570.83 MB (변화: +0.60 MB)
[AMWD]   [LSTM] 완료  첫값=4.34e+08 (메모리: 1570.8 MB)
[AMWD]   [Theta] 시작  (메모리: 1570.8 MB)
[메모리] forecast_theta 실행 전: 1570.83 MB
[메모리] forecast_theta 실행 후: 1570.83 MB (변화: +0.00 MB)
[AMWD]   [Theta] 완료  첫값=4.25e+08 (메모리: 1570.8 MB)
[AMWD]   [DB] 93행 저장 완료
[PROGRESS] [ 135/500] ( 27.0%)  >>  NAT
[NAT]   45분기 | 2015-03-31 ~ 2026-03-31
[NAT]   [SARIMA] 시작  (메모리: 1570.8 MB)
[메모리] forecast_sarima 실행 전: 1570.83 MB
[메모리] find_best_sarima_params 실행 전: 1570.83 MB
[메모리] find_best_sarima_params 실행 후: 1570.83 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1570.83 MB (변화: +0.00 MB)
[NAT]   [SARIMA] 완료  첫값=6.89e+07 (메모리: 1570.8 MB)
[NAT]   [ETS] 시작  (메모리: 1570.8 MB)
[메모리] forecast_ets 실행 전: 1570.83 MB
[메모리] forecast_ets 실행 후: 1570.83 MB (변화: +0.00 MB)
[NAT]   [ETS] 완료  첫값=6.84e+07 (메모리: 1570.8 MB)
[NAT]   [Prophet] 시작  (메모리: 1570.8 MB)

01:08:48 - cmdstanpy - INFO - Chain [1] start processing
01:08:49 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1570.83 MB
[메모리] forecast_prophet 실행 후: 1570.89 MB (변화: +0.05 MB)
[NAT]   [Prophet] 완료  첫값=7.23e+07 (메모리: 1570.9 MB)
[NAT]   [LSTM] 시작  (메모리: 1570.9 MB)
[메모리] forecast_lstm 실행 전: 1570.89 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1571.11 MB (변화: +0.22 MB)
[NAT]   [LSTM] 완료  첫값=6.86e+07 (메모리: 1571.1 MB)
[NAT]   [Theta] 시작  (메모리: 1571.1 MB)
[메모리] forecast_theta 실행 전: 1571.11 MB
[메모리] forecast_theta 실행 후: 1571.11 MB (변화: +0.00 MB)
[NAT]   [Theta] 완료  첫값=7.47e+07 (메모리: 1571.1 MB)
[NAT]   [DB] 93행 저장 완료
[PROGRESS] [ 136/500] ( 27.2%)  >>  NX
[NX]   45분기 | 2015-03-31 ~ 2026-03-31
[NX]   [SARIMA] 시작  (메모리: 1571.1 MB)
[메모리] forecast_sarima 실행 전: 1571.11 MB
[메모리] find_best_sarima_params 실행 전: 1571.11 MB
[메모리] find_best_sarima_params 실행 후: 1571.11 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1571.11 MB (변화: +0.00 MB)
[NX]   [SARIMA] 완료  첫값=5.34e+08 (메모리: 1571.1 MB)
[NX]   [ETS] 시작  (메모리: 1571.1 MB)
[메모리] forecast_ets 실행 전: 1571.11 MB
[메모리] forecast_ets 실행 후: 1571.11 MB (변화: +0.00 MB)
[NX]   [ETS] 완료  첫값=5.40e+08 (메모리: 1571.1 MB)
[NX]   [Prophet] 시작  (메모리: 1571.1 MB)

01:09:08 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1571.11 MB

01:09:08 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1570.66 MB (변화: -0.44 MB)
[NX]   [Prophet] 완료  첫값=3.97e+08 (메모리: 1570.7 MB)
[NX]   [LSTM] 시작  (메모리: 1570.7 MB)
[메모리] forecast_lstm 실행 전: 1570.66 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1572.02 MB (변화: +1.35 MB)
[NX]   [LSTM] 완료  첫값=4.26e+08 (메모리: 1572.0 MB)
[NX]   [Theta] 시작  (메모리: 1572.0 MB)
[메모리] forecast_theta 실행 전: 1572.02 MB
[메모리] forecast_theta 실행 후: 1572.02 MB (변화: +0.00 MB)
[NX]   [Theta] 완료  첫값=5.35e+08 (메모리: 1572.0 MB)
[NX]   [DB] 93행 저장 완료
[PROGRESS] [ 137/500] ( 27.4%)  >>  POET
[POET]   45분기 | 2015-03-31 ~ 2026-03-31
[POET]   [SARIMA] 시작  (메모리: 1572.0 MB)
[메모리] forecast_sarima 실행 전: 1572.02 MB
[메모리] find_best_sarima_params 실행 전: 1572.02 MB
[메모리] find_best_sarima_params 실행 후: 1572.02 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1572.02 MB (변화: +0.00 MB)
[POET]   [SARIMA] 완료  첫값=2.30e+05 (메모리: 1572.0 MB)
[POET]   [ETS] 시작  (메모리: 1572.0 MB)
[메모리] forecast_ets 실행 전: 1572.02 MB
[메모리] forecast_ets 실행 후: 1572.02 MB (변화: +0.00 MB)
[POET]   [ETS] 완료  첫값=3.23e+05 (메모리: 1572.0 MB)
[POET]   [Prophet] 시작  (메모리: 1572.0 MB)

01:09:27 - cmdstanpy - INFO - Chain [1] start processing
01:09:27 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1572.02 MB
[메모리] forecast_prophet 실행 후: 1571.43 MB (변화: -0.59 MB)
[POET]   [Prophet] 완료  첫값=7.05e+04 (메모리: 1571.4 MB)
[POET]   [LSTM] 시작  (메모리: 1571.4 MB)
[메모리] forecast_lstm 실행 전: 1571.43 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1572.66 MB (변화: +1.22 MB)
[POET]   [LSTM] 완료  첫값=2.65e+05 (메모리: 1572.7 MB)
[POET]   [Theta] 시작  (메모리: 1572.7 MB)
[메모리] forecast_theta 실행 전: 1572.66 MB
[메모리] forecast_theta 실행 후: 1572.66 MB (변화: +0.00 MB)
[POET]   [Theta] 완료  첫값=2.87e+05 (메모리: 1572.7 MB)
[POET]   [DB] 93행 저장 완료
[PROGRESS] [ 138/500] ( 27.6%)  >>  SCHL
[SCHL]   45분기 | 2015-03-31 ~ 2026-03-31
[SCHL]   [SARIMA] 시작  (메모리: 1572.7 MB)
[메모리] forecast_sarima 실행 전: 1572.66 MB
[메모리] find_best_sarima_params 실행 전: 1572.66 MB
[메모리] find_best_sarima_params 실행 후: 1572.66 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1572.66 MB (변화: +0.00 MB)
[SCHL]   [SARIMA] 완료  첫값=4.65e+08 (메모리: 1572.7 MB)
[SCHL]   [ETS] 시작  (메모리: 1572.7 MB)
[메모리] forecast_ets 실행 전: 1572.66 MB
[메모리] forecast_ets 실행 후: 1572.66 MB (변화: +0.00 MB)
[SCHL]   [ETS] 완료  첫값=4.70e+08 (메모리: 1572.7 MB)
[SCHL]   [Prophet] 시작  (메모리: 1572.7 MB)

01:09:52 - cmdstanpy - INFO - Chain [1] start processing
01:09:52 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1572.66 MB
[메모리] forecast_prophet 실행 후: 1572.09 MB (변화: -0.57 MB)
[SCHL]   [Prophet] 완료  첫값=4.09e+08 (메모리: 1572.1 MB)
[SCHL]   [LSTM] 시작  (메모리: 1572.1 MB)
[메모리] forecast_lstm 실행 전: 1572.09 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1573.08 MB (변화: +0.99 MB)
[SCHL]   [LSTM] 완료  첫값=4.42e+08 (메모리: 1573.1 MB)
[SCHL]   [Theta] 시작  (메모리: 1573.1 MB)
[메모리] forecast_theta 실행 전: 1573.08 MB
[메모리] forecast_theta 실행 후: 1573.08 MB (변화: +0.00 MB)
[SCHL]   [Theta] 완료  첫값=5.15e+08 (메모리: 1573.1 MB)
[SCHL]   [DB] 93행 저장 완료
[PROGRESS] [ 139/500] ( 27.8%)  >>  FARO
[FARO]   45분기 | 2015-03-31 ~ 2026-03-31
[FARO]   [SARIMA] 시작  (메모리: 1573.1 MB)
[메모리] forecast_sarima 실행 전: 1573.08 MB
[메모리] find_best_sarima_params 실행 전: 1573.08 MB
[메모리] find_best_sarima_params 실행 후: 1573.09 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1573.09 MB (변화: +0.00 MB)
[FARO]   [SARIMA] 완료  첫값=8.09e+07 (메모리: 1573.1 MB)
[FARO]   [ETS] 시작  (메모리: 1573.1 MB)
[메모리] forecast_ets 실행 전: 1573.09 MB
[메모리] forecast_ets 실행 후: 1573.09 MB (변화: +0.00 MB)
[FARO]   [ETS] 완료  첫값=8.04e+07 (메모리: 1573.1 MB)
[FARO]   [Prophet] 시작  (메모리: 1573.1 MB)

01:10:11 - cmdstanpy - INFO - Chain [1] start processing
01:10:11 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1573.09 MB
[메모리] forecast_prophet 실행 후: 1573.11 MB (변화: +0.02 MB)
[FARO]   [Prophet] 완료  첫값=8.67e+07 (메모리: 1573.1 MB)
[FARO]   [LSTM] 시작  (메모리: 1573.1 MB)
[메모리] forecast_lstm 실행 전: 1573.11 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1573.11 MB (변화: -0.00 MB)
[FARO]   [LSTM] 완료  첫값=8.31e+07 (메모리: 1573.1 MB)
[FARO]   [Theta] 시작  (메모리: 1573.1 MB)
[메모리] forecast_theta 실행 전: 1573.11 MB
[메모리] forecast_theta 실행 후: 1573.11 MB (변화: +0.00 MB)
[FARO]   [Theta] 완료  첫값=7.91e+07 (메모리: 1573.1 MB)
[FARO]   [DB] 93행 저장 완료
[PROGRESS] [ 140/500] ( 28.0%)  >>  RPD
[RPD]   45분기 | 2015-03-31 ~ 2026-03-31
[RPD]   [SARIMA] 시작  (메모리: 1573.1 MB)
[메모리] forecast_sarima 실행 전: 1573.11 MB
[메모리] find_best_sarima_params 실행 전: 1573.11 MB
[메모리] find_best_sarima_params 실행 후: 1573.11 MB (변화: +0.00 MB)
[메모리] find_best_sarima_params 실행 전: 1573.11 MB
[메모리] find_best_sarima_params 실행 후: 1573.12 MB (변화: +0.01 MB)
[메모리] forecast_sarima 실행 후: 1573.12 MB (변화: +0.02 MB)
[RPD]   [SARIMA] 오류응답: {'error': 'SARIMA 적합 실패 (발산 포함)'}
[RPD]   [ETS] 시작  (메모리: 1573.1 MB)
[메모리] forecast_ets 실행 전: 1573.12 MB
[메모리] forecast_ets 실행 후: 1573.12 MB (변화: +0.00 MB)
[RPD]   [ETS] 완료  첫값=2.30e+11 (메모리: 1573.1 MB)
[RPD]   [Prophet] 시작  (메모리: 1573.1 MB)

01:10:41 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1573.12 MB

01:10:42 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1573.13 MB (변화: +0.01 MB)
[RPD]   [Prophet] 완료  첫값=3.81e+10 (메모리: 1573.1 MB)
[RPD]   [LSTM] 시작  (메모리: 1573.1 MB)
[메모리] forecast_lstm 실행 전: 1573.13 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1572.02 MB (변화: -1.11 MB)
[RPD]   [LSTM] 완료  첫값=2.19e+10 (메모리: 1572.0 MB)
[RPD]   [Theta] 시작  (메모리: 1572.0 MB)
[메모리] forecast_theta 실행 전: 1572.02 MB
[메모리] forecast_theta 실행 후: 1572.02 MB (변화: +0.00 MB)
[RPD]   [Theta] 완료  첫값=2.28e+11 (메모리: 1572.0 MB)
[RPD]   [DB] 85행 저장 완료
[PROGRESS] [ 141/500] ( 28.2%)  >>  FWRD
[FWRD]   45분기 | 2015-03-31 ~ 2026-03-31
[FWRD]   [SARIMA] 시작  (메모리: 1572.0 MB)
[메모리] forecast_sarima 실행 전: 1572.02 MB
[메모리] find_best_sarima_params 실행 전: 1572.02 MB
[메모리] find_best_sarima_params 실행 후: 1572.02 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1572.02 MB (변화: +0.00 MB)
[FWRD]   [SARIMA] 완료  첫값=6.11e+08 (메모리: 1572.0 MB)
[FWRD]   [ETS] 시작  (메모리: 1572.0 MB)
[메모리] forecast_ets 실행 전: 1572.02 MB
[메모리] forecast_ets 실행 후: 1572.03 MB (변화: +0.00 MB)
[FWRD]   [ETS] 완료  첫값=6.12e+08 (메모리: 1572.0 MB)
[FWRD]   [Prophet] 시작  (메모리: 1572.0 MB)

01:10:58 - cmdstanpy - INFO - Chain [1] start processing
01:10:58 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1572.03 MB
[메모리] forecast_prophet 실행 후: 1572.05 MB (변화: +0.02 MB)
[FWRD]   [Prophet] 완료  첫값=5.92e+08 (메모리: 1572.1 MB)
[FWRD]   [LSTM] 시작  (메모리: 1572.1 MB)
[메모리] forecast_lstm 실행 전: 1572.05 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1572.96 MB (변화: +0.91 MB)
[FWRD]   [LSTM] 완료  첫값=6.37e+08 (메모리: 1573.0 MB)
[FWRD]   [Theta] 시작  (메모리: 1573.0 MB)
[메모리] forecast_theta 실행 전: 1572.96 MB
[메모리] forecast_theta 실행 후: 1572.96 MB (변화: +0.00 MB)
[FWRD]   [Theta] 완료  첫값=6.43e+08 (메모리: 1573.0 MB)
[FWRD]   [DB] 93행 저장 완료
[PROGRESS] [ 142/500] ( 28.4%)  >>  CSII
[CSII]   45분기 | 2015-03-31 ~ 2026-03-31
[CSII]   [SARIMA] 시작  (메모리: 1573.0 MB)
[메모리] forecast_sarima 실행 전: 1572.96 MB
[메모리] find_best_sarima_params 실행 전: 1572.96 MB
[메모리] find_best_sarima_params 실행 후: 1572.96 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1572.96 MB (변화: +0.00 MB)
[CSII]   [SARIMA] 완료  첫값=6.15e+07 (메모리: 1573.0 MB)
[CSII]   [ETS] 시작  (메모리: 1573.0 MB)
[메모리] forecast_ets 실행 전: 1572.96 MB
[메모리] forecast_ets 실행 후: 1572.97 MB (변화: +0.01 MB)
[CSII]   [ETS] 완료  첫값=6.31e+07 (메모리: 1573.0 MB)
[CSII]   [Prophet] 시작  (메모리: 1573.0 MB)

01:11:18 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1572.97 MB

01:11:18 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1572.99 MB (변화: +0.02 MB)
[CSII]   [Prophet] 완료  첫값=6.34e+07 (메모리: 1573.0 MB)
[CSII]   [LSTM] 시작  (메모리: 1573.0 MB)
[메모리] forecast_lstm 실행 전: 1572.99 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1572.96 MB (변화: -0.02 MB)
[CSII]   [LSTM] 완료  첫값=6.15e+07 (메모리: 1573.0 MB)
[CSII]   [Theta] 시작  (메모리: 1573.0 MB)
[메모리] forecast_theta 실행 전: 1572.96 MB
[메모리] forecast_theta 실행 후: 1572.96 MB (변화: +0.00 MB)
[CSII]   [Theta] 완료  첫값=6.19e+07 (메모리: 1573.0 MB)
[CSII]   [DB] 93행 저장 완료
[PROGRESS] [ 143/500] ( 28.6%)  >>  ODP
[ODP]   45분기 | 2015-03-31 ~ 2026-03-31
[ODP]   [SARIMA] 시작  (메모리: 1573.0 MB)
[메모리] forecast_sarima 실행 전: 1572.96 MB
[메모리] find_best_sarima_params 실행 전: 1572.96 MB
[메모리] find_best_sarima_params 실행 후: 1572.96 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1572.96 MB (변화: +0.00 MB)
[ODP]   [SARIMA] 완료  첫값=1.59e+09 (메모리: 1573.0 MB)
[ODP]   [ETS] 시작  (메모리: 1573.0 MB)
[메모리] forecast_ets 실행 전: 1572.96 MB
[메모리] forecast_ets 실행 후: 1572.96 MB (변화: +0.00 MB)
[ODP]   [ETS] 완료  첫값=1.50e+09 (메모리: 1573.0 MB)
[ODP]   [Prophet] 시작  (메모리: 1573.0 MB)

01:11:44 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1572.96 MB

01:11:44 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1572.98 MB (변화: +0.01 MB)
[ODP]   [Prophet] 완료  첫값=1.49e+09 (메모리: 1573.0 MB)
[ODP]   [LSTM] 시작  (메모리: 1573.0 MB)
[메모리] forecast_lstm 실행 전: 1572.98 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1572.97 MB (변화: -0.01 MB)
[ODP]   [LSTM] 완료  첫값=1.63e+09 (메모리: 1573.0 MB)
[ODP]   [Theta] 시작  (메모리: 1573.0 MB)
[메모리] forecast_theta 실행 전: 1572.97 MB
[메모리] forecast_theta 실행 후: 1572.97 MB (변화: +0.00 MB)
[ODP]   [Theta] 완료  첫값=1.53e+09 (메모리: 1573.0 MB)
[ODP]   [DB] 93행 저장 완료
[PROGRESS] [ 144/500] ( 28.8%)  >>  IRWD
[IRWD]   45분기 | 2015-03-31 ~ 2026-03-31
[IRWD]   [SARIMA] 시작  (메모리: 1573.0 MB)
[메모리] forecast_sarima 실행 전: 1572.97 MB
[메모리] find_best_sarima_params 실행 전: 1572.97 MB
[메모리] find_best_sarima_params 실행 후: 1572.97 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1572.97 MB (변화: +0.00 MB)
[IRWD]   [SARIMA] 완료  첫값=1.07e+08 (메모리: 1573.0 MB)
[IRWD]   [ETS] 시작  (메모리: 1573.0 MB)
[메모리] forecast_ets 실행 전: 1572.97 MB
[메모리] forecast_ets 실행 후: 1572.97 MB (변화: +0.00 MB)
[IRWD]   [ETS] 완료  첫값=1.25e+08 (메모리: 1573.0 MB)
[IRWD]   [Prophet] 시작  (메모리: 1573.0 MB)

01:12:07 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1572.97 MB

01:12:07 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1572.98 MB (변화: +0.01 MB)
[IRWD]   [Prophet] 완료  첫값=1.17e+08 (메모리: 1573.0 MB)
[IRWD]   [LSTM] 시작  (메모리: 1573.0 MB)
[메모리] forecast_lstm 실행 전: 1572.98 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1571.76 MB (변화: -1.22 MB)
[IRWD]   [LSTM] 완료  첫값=9.75e+07 (메모리: 1571.8 MB)
[IRWD]   [Theta] 시작  (메모리: 1571.8 MB)
[메모리] forecast_theta 실행 전: 1571.76 MB
[메모리] forecast_theta 실행 후: 1571.76 MB (변화: +0.00 MB)
[IRWD]   [Theta] 완료  첫값=1.27e+08 (메모리: 1571.8 MB)
[IRWD]   [DB] 93행 저장 완료
[PROGRESS] [ 145/500] ( 29.0%)  >>  RDUS
[RDUS]   45분기 | 2015-03-31 ~ 2026-03-31
[RDUS]   [SARIMA] 시작  (메모리: 1571.8 MB)
[메모리] forecast_sarima 실행 전: 1571.76 MB
[메모리] find_best_sarima_params 실행 전: 1571.76 MB
[메모리] find_best_sarima_params 실행 후: 1571.76 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1571.76 MB (변화: +0.00 MB)
[RDUS]   [SARIMA] 완료  첫값=7.40e+08 (메모리: 1571.8 MB)
[RDUS]   [ETS] 시작  (메모리: 1571.8 MB)
[메모리] forecast_ets 실행 전: 1571.76 MB
[메모리] forecast_ets 실행 후: 1571.77 MB (변화: +0.00 MB)
[RDUS]   [ETS] 완료  첫값=7.35e+08 (메모리: 1571.8 MB)
[RDUS]   [Prophet] 시작  (메모리: 1571.8 MB)

01:12:24 - cmdstanpy - INFO - Chain [1] start processing
01:12:24 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1571.77 MB
[메모리] forecast_prophet 실행 후: 1572.17 MB (변화: +0.41 MB)
[RDUS]   [Prophet] 완료  첫값=7.40e+08 (메모리: 1572.2 MB)
[RDUS]   [LSTM] 시작  (메모리: 1572.2 MB)
[메모리] forecast_lstm 실행 전: 1572.17 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1572.63 MB (변화: +0.46 MB)
[RDUS]   [LSTM] 완료  첫값=7.35e+08 (메모리: 1572.6 MB)
[RDUS]   [Theta] 시작  (메모리: 1572.6 MB)
[메모리] forecast_theta 실행 전: 1572.63 MB
[메모리] forecast_theta 실행 후: 1572.63 MB (변화: +0.00 MB)
[RDUS]   [Theta] 완료  첫값=7.39e+08 (메모리: 1572.6 MB)
[RDUS]   [DB] 93행 저장 완료
[PROGRESS] [ 146/500] ( 29.2%)  >>  AIV
[AIV]   45분기 | 2015-03-31 ~ 2026-03-31
[AIV]   [SARIMA] 시작  (메모리: 1572.6 MB)
[메모리] forecast_sarima 실행 전: 1572.63 MB
[메모리] find_best_sarima_params 실행 전: 1572.63 MB
[메모리] find_best_sarima_params 실행 후: 1572.63 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1572.63 MB (변화: +0.00 MB)
[AIV]   [SARIMA] 완료  첫값=3.51e+07 (메모리: 1572.6 MB)
[AIV]   [ETS] 시작  (메모리: 1572.6 MB)
[메모리] forecast_ets 실행 전: 1572.63 MB
[메모리] forecast_ets 실행 후: 1572.64 MB (변화: +0.00 MB)
[AIV]   [ETS] 완료  첫값=3.61e+07 (메모리: 1572.6 MB)
[AIV]   [Prophet] 시작  (메모리: 1572.6 MB)

01:12:46 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1572.64 MB

01:12:46 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1572.40 MB (변화: -0.23 MB)
[AIV]   [Prophet] 완료  첫값=-1.95e+07 (메모리: 1572.4 MB)
[AIV]   [LSTM] 시작  (메모리: 1572.4 MB)
[메모리] forecast_lstm 실행 전: 1572.40 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1573.57 MB (변화: +1.17 MB)
[AIV]   [LSTM] 완료  첫값=4.41e+07 (메모리: 1573.6 MB)
[AIV]   [Theta] 시작  (메모리: 1573.6 MB)
[메모리] forecast_theta 실행 전: 1573.57 MB
[메모리] forecast_theta 실행 후: 1573.57 MB (변화: +0.00 MB)
[AIV]   [Theta] 완료  첫값=3.67e+07 (메모리: 1573.6 MB)
[AIV]   [DB] 93행 저장 완료
[PROGRESS] [ 147/500] ( 29.4%)  >>  APOG
[APOG]   45분기 | 2015-03-31 ~ 2026-03-31
[APOG]   [SARIMA] 시작  (메모리: 1573.6 MB)
[메모리] forecast_sarima 실행 전: 1573.57 MB
[메모리] find_best_sarima_params 실행 전: 1573.57 MB
[메모리] find_best_sarima_params 실행 후: 1573.57 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1573.57 MB (변화: +0.00 MB)
[APOG]   [SARIMA] 완료  첫값=3.49e+08 (메모리: 1573.6 MB)
[APOG]   [ETS] 시작  (메모리: 1573.6 MB)
[메모리] forecast_ets 실행 전: 1573.57 MB
[메모리] forecast_ets 실행 후: 1573.58 MB (변화: +0.00 MB)
[APOG]   [ETS] 완료  첫값=3.42e+08 (메모리: 1573.6 MB)
[APOG]   [Prophet] 시작  (메모리: 1573.6 MB)

01:13:06 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1573.58 MB

01:13:07 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1572.66 MB (변화: -0.92 MB)
[APOG]   [Prophet] 완료  첫값=3.61e+08 (메모리: 1572.7 MB)
[APOG]   [LSTM] 시작  (메모리: 1572.7 MB)
[메모리] forecast_lstm 실행 전: 1572.66 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1573.62 MB (변화: +0.96 MB)
[APOG]   [LSTM] 완료  첫값=3.38e+08 (메모리: 1573.6 MB)
[APOG]   [Theta] 시작  (메모리: 1573.6 MB)
[메모리] forecast_theta 실행 전: 1573.62 MB
[메모리] forecast_theta 실행 후: 1573.62 MB (변화: +0.00 MB)
[APOG]   [Theta] 완료  첫값=3.38e+08 (메모리: 1573.6 MB)
[APOG]   [DB] 93행 저장 완료
[PROGRESS] [ 148/500] ( 29.6%)  >>  GHM
[GHM]   45분기 | 2015-03-31 ~ 2026-03-31
[GHM]   [SARIMA] 시작  (메모리: 1573.6 MB)
[메모리] forecast_sarima 실행 전: 1573.62 MB
[메모리] find_best_sarima_params 실행 전: 1573.62 MB
[메모리] find_best_sarima_params 실행 후: 1573.62 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1573.62 MB (변화: +0.00 MB)
[GHM]   [SARIMA] 완료  첫값=6.10e+07 (메모리: 1573.6 MB)
[GHM]   [ETS] 시작  (메모리: 1573.6 MB)
[메모리] forecast_ets 실행 전: 1573.62 MB
[메모리] forecast_ets 실행 후: 1573.62 MB (변화: +0.00 MB)
[GHM]   [ETS] 완료  첫값=6.12e+07 (메모리: 1573.6 MB)
[GHM]   [Prophet] 시작  (메모리: 1573.6 MB)

01:13:31 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1573.62 MB

01:13:31 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1573.64 MB (변화: +0.02 MB)
[GHM]   [Prophet] 완료  첫값=6.08e+07 (메모리: 1573.6 MB)
[GHM]   [LSTM] 시작  (메모리: 1573.6 MB)
[메모리] forecast_lstm 실행 전: 1573.64 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1573.62 MB (변화: -0.02 MB)
[GHM]   [LSTM] 완료  첫값=6.61e+07 (메모리: 1573.6 MB)
[GHM]   [Theta] 시작  (메모리: 1573.6 MB)
[메모리] forecast_theta 실행 전: 1573.62 MB
[메모리] forecast_theta 실행 후: 1573.62 MB (변화: +0.00 MB)
[GHM]   [Theta] 완료  첫값=5.51e+07 (메모리: 1573.6 MB)
[GHM]   [DB] 93행 저장 완료
[PROGRESS] [ 149/500] ( 29.8%)  >>  MOBL
[MOBL]   45분기 | 2015-03-31 ~ 2026-03-31
[MOBL]   [SARIMA] 시작  (메모리: 1573.6 MB)
[메모리] forecast_sarima 실행 전: 1573.62 MB
[메모리] find_best_sarima_params 실행 전: 1573.62 MB
[메모리] find_best_sarima_params 실행 후: 1573.62 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1573.62 MB (변화: +0.00 MB)
[MOBL]   [SARIMA] 완료  첫값=5.00e+07 (메모리: 1573.6 MB)
[MOBL]   [ETS] 시작  (메모리: 1573.6 MB)
[메모리] forecast_ets 실행 전: 1573.62 MB
[메모리] forecast_ets 실행 후: 1573.63 MB (변화: +0.00 MB)
[MOBL]   [ETS] 완료  첫값=5.00e+07 (메모리: 1573.6 MB)
[MOBL]   [Prophet] 시작  (메모리: 1573.6 MB)

01:13:55 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1573.63 MB

01:13:55 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1573.65 MB (변화: +0.02 MB)
[MOBL]   [Prophet] 완료  첫값=4.97e+07 (메모리: 1573.6 MB)
[MOBL]   [LSTM] 시작  (메모리: 1573.6 MB)
[메모리] forecast_lstm 실행 전: 1573.65 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1573.64 MB (변화: -0.01 MB)
[MOBL]   [LSTM] 완료  첫값=5.58e+07 (메모리: 1573.6 MB)
[MOBL]   [Theta] 시작  (메모리: 1573.6 MB)
[메모리] forecast_theta 실행 전: 1573.64 MB
[메모리] forecast_theta 실행 후: 1573.64 MB (변화: +0.00 MB)
[MOBL]   [Theta] 완료  첫값=5.07e+07 (메모리: 1573.6 MB)
[MOBL]   [DB] 93행 저장 완료
[PROGRESS] [ 150/500] ( 30.0%)  >>  MLCO
[MLCO]   45분기 | 2015-03-31 ~ 2026-03-31
[MLCO]   [SARIMA] 시작  (메모리: 1573.6 MB)
[메모리] forecast_sarima 실행 전: 1573.64 MB
[메모리] find_best_sarima_params 실행 전: 1573.64 MB
[메모리] find_best_sarima_params 실행 후: 1573.64 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1573.64 MB (변화: +0.00 MB)
[MLCO]   [SARIMA] 완료  첫값=1.31e+09 (메모리: 1573.6 MB)
[MLCO]   [ETS] 시작  (메모리: 1573.6 MB)
[메모리] forecast_ets 실행 전: 1573.64 MB
[메모리] forecast_ets 실행 후: 1573.64 MB (변화: +0.00 MB)
[MLCO]   [ETS] 완료  첫값=1.12e+09 (메모리: 1573.6 MB)
[MLCO]   [Prophet] 시작  (메모리: 1573.6 MB)

01:14:11 - cmdstanpy - INFO - Chain [1] start processing
01:14:11 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1573.64 MB
[메모리] forecast_prophet 실행 후: 1573.66 MB (변화: +0.02 MB)
[MLCO]   [Prophet] 완료  첫값=9.00e+08 (메모리: 1573.7 MB)
[MLCO]   [LSTM] 시작  (메모리: 1573.7 MB)
[메모리] forecast_lstm 실행 전: 1573.66 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1573.95 MB (변화: +0.29 MB)
[MLCO]   [LSTM] 완료  첫값=9.24e+08 (메모리: 1573.9 MB)
[MLCO]   [Theta] 시작  (메모리: 1573.9 MB)
[메모리] forecast_theta 실행 전: 1573.95 MB
[메모리] forecast_theta 실행 후: 1573.95 MB (변화: +0.00 MB)
[MLCO]   [Theta] 완료  첫값=1.31e+09 (메모리: 1573.9 MB)
[MLCO]   [DB] 93행 저장 완료
[PROGRESS] [ 151/500] ( 30.2%)  >>  UBP
[UBP]   45분기 | 2015-03-31 ~ 2026-03-31
[UBP]   [SARIMA] 시작  (메모리: 1573.9 MB)
[메모리] forecast_sarima 실행 전: 1573.95 MB
[메모리] find_best_sarima_params 실행 전: 1573.95 MB
[메모리] find_best_sarima_params 실행 후: 1573.95 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1573.95 MB (변화: +0.00 MB)
[UBP]   [SARIMA] 완료  첫값=3.51e+07 (메모리: 1573.9 MB)
[UBP]   [ETS] 시작  (메모리: 1573.9 MB)
[메모리] forecast_ets 실행 전: 1573.95 MB
[메모리] forecast_ets 실행 후: 1573.95 MB (변화: +0.00 MB)
[UBP]   [ETS] 완료  첫값=3.55e+07 (메모리: 1573.9 MB)
[UBP]   [Prophet] 시작  (메모리: 1573.9 MB)

01:14:33 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1573.95 MB

01:14:33 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1572.99 MB (변화: -0.96 MB)
[UBP]   [Prophet] 완료  첫값=3.63e+07 (메모리: 1573.0 MB)
[UBP]   [LSTM] 시작  (메모리: 1573.0 MB)
[메모리] forecast_lstm 실행 전: 1572.99 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1573.96 MB (변화: +0.97 MB)
[UBP]   [LSTM] 완료  첫값=3.49e+07 (메모리: 1574.0 MB)
[UBP]   [Theta] 시작  (메모리: 1574.0 MB)
[메모리] forecast_theta 실행 전: 1573.96 MB
[메모리] forecast_theta 실행 후: 1573.96 MB (변화: +0.00 MB)
[UBP]   [Theta] 완료  첫값=3.52e+07 (메모리: 1574.0 MB)
[UBP]   [DB] 93행 저장 완료
[PROGRESS] [ 152/500] ( 30.4%)  >>  UBA
[UBA]   45분기 | 2015-03-31 ~ 2026-03-31
[UBA]   [SARIMA] 시작  (메모리: 1574.0 MB)
[메모리] forecast_sarima 실행 전: 1573.96 MB
[메모리] find_best_sarima_params 실행 전: 1573.96 MB
[메모리] find_best_sarima_params 실행 후: 1573.96 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1573.96 MB (변화: +0.00 MB)
[UBA]   [SARIMA] 완료  첫값=3.51e+07 (메모리: 1574.0 MB)
[UBA]   [ETS] 시작  (메모리: 1574.0 MB)
[메모리] forecast_ets 실행 전: 1573.96 MB
[메모리] forecast_ets 실행 후: 1573.96 MB (변화: +0.00 MB)
[UBA]   [ETS] 완료  첫값=3.55e+07 (메모리: 1574.0 MB)
[UBA]   [Prophet] 시작  (메모리: 1574.0 MB)

01:14:53 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1573.96 MB

01:14:53 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1573.44 MB (변화: -0.52 MB)
[UBA]   [Prophet] 완료  첫값=3.63e+07 (메모리: 1573.4 MB)
[UBA]   [LSTM] 시작  (메모리: 1573.4 MB)
[메모리] forecast_lstm 실행 전: 1573.44 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1574.46 MB (변화: +1.02 MB)
[UBA]   [LSTM] 완료  첫값=3.46e+07 (메모리: 1574.5 MB)
[UBA]   [Theta] 시작  (메모리: 1574.5 MB)
[메모리] forecast_theta 실행 전: 1574.46 MB
[메모리] forecast_theta 실행 후: 1574.46 MB (변화: +0.00 MB)
[UBA]   [Theta] 완료  첫값=3.52e+07 (메모리: 1574.5 MB)
[UBA]   [DB] 93행 저장 완료
[PROGRESS] [ 153/500] ( 30.6%)  >>  LINC
[LINC]   45분기 | 2015-03-31 ~ 2026-03-31
[LINC]   [SARIMA] 시작  (메모리: 1574.5 MB)
[메모리] forecast_sarima 실행 전: 1574.46 MB
[메모리] find_best_sarima_params 실행 전: 1574.46 MB
[메모리] find_best_sarima_params 실행 후: 1574.46 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1574.46 MB (변화: +0.00 MB)
[LINC]   [SARIMA] 완료  첫값=1.42e+08 (메모리: 1574.5 MB)
[LINC]   [ETS] 시작  (메모리: 1574.5 MB)
[메모리] forecast_ets 실행 전: 1574.46 MB
[메모리] forecast_ets 실행 후: 1574.46 MB (변화: +0.00 MB)
[LINC]   [ETS] 완료  첫값=1.38e+08 (메모리: 1574.5 MB)
[LINC]   [Prophet] 시작  (메모리: 1574.5 MB)

01:15:14 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1574.46 MB

01:15:14 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1573.53 MB (변화: -0.93 MB)
[LINC]   [Prophet] 완료  첫값=1.26e+08 (메모리: 1573.5 MB)
[LINC]   [LSTM] 시작  (메모리: 1573.5 MB)
[메모리] forecast_lstm 실행 전: 1573.53 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1575.93 MB (변화: +2.39 MB)
[LINC]   [LSTM] 완료  첫값=1.62e+08 (메모리: 1575.9 MB)
[LINC]   [Theta] 시작  (메모리: 1575.9 MB)
[메모리] forecast_theta 실행 전: 1575.93 MB
[메모리] forecast_theta 실행 후: 1575.93 MB (변화: +0.00 MB)
[LINC]   [Theta] 완료  첫값=1.37e+08 (메모리: 1575.9 MB)
[LINC]   [DB] 93행 저장 완료
[PROGRESS] [ 154/500] ( 30.8%)  >>  MATW
[MATW]   45분기 | 2015-03-31 ~ 2026-03-31
[MATW]   [SARIMA] 시작  (메모리: 1575.9 MB)
[메모리] forecast_sarima 실행 전: 1575.93 MB
[메모리] find_best_sarima_params 실행 전: 1575.93 MB
[메모리] find_best_sarima_params 실행 후: 1575.93 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1575.93 MB (변화: +0.00 MB)
[MATW]   [SARIMA] 완료  첫값=2.63e+08 (메모리: 1575.9 MB)
[MATW]   [ETS] 시작  (메모리: 1575.9 MB)
[메모리] forecast_ets 실행 전: 1575.93 MB
[메모리] forecast_ets 실행 후: 1575.93 MB (변화: +0.00 MB)
[MATW]   [ETS] 완료  첫값=2.30e+08 (메모리: 1575.9 MB)
[MATW]   [Prophet] 시작  (메모리: 1575.9 MB)

01:15:40 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1575.93 MB

01:15:40 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1575.49 MB (변화: -0.43 MB)
[MATW]   [Prophet] 완료  첫값=4.17e+08 (메모리: 1575.5 MB)
[MATW]   [LSTM] 시작  (메모리: 1575.5 MB)
[메모리] forecast_lstm 실행 전: 1575.49 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1576.48 MB (변화: +0.99 MB)
[MATW]   [LSTM] 완료  첫값=4.37e+08 (메모리: 1576.5 MB)
[MATW]   [Theta] 시작  (메모리: 1576.5 MB)
[메모리] forecast_theta 실행 전: 1576.48 MB
[메모리] forecast_theta 실행 후: 1576.48 MB (변화: +0.00 MB)
[MATW]   [Theta] 완료  첫값=2.86e+08 (메모리: 1576.5 MB)
[MATW]   [DB] 93행 저장 완료
[PROGRESS] [ 155/500] ( 31.0%)  >>  TK
[TK]   45분기 | 2015-03-31 ~ 2026-03-31
[TK]   [SARIMA] 시작  (메모리: 1576.5 MB)
[메모리] forecast_sarima 실행 전: 1576.48 MB
[메모리] find_best_sarima_params 실행 전: 1576.48 MB
[메모리] find_best_sarima_params 실행 후: 1576.48 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1576.48 MB (변화: +0.00 MB)
[TK]   [SARIMA] 완료  첫값=2.32e+08 (메모리: 1576.5 MB)
[TK]   [ETS] 시작  (메모리: 1576.5 MB)
[메모리] forecast_ets 실행 전: 1576.48 MB
[메모리] forecast_ets 실행 후: 1576.49 MB (변화: +0.01 MB)
[TK]   [ETS] 완료  첫값=2.25e+08 (메모리: 1576.5 MB)
[TK]   [Prophet] 시작  (메모리: 1576.5 MB)

01:15:58 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1576.49 MB

01:15:58 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1576.52 MB (변화: +0.04 MB)
[TK]   [Prophet] 완료  첫값=1.95e+08 (메모리: 1576.5 MB)
[TK]   [LSTM] 시작  (메모리: 1576.5 MB)
[메모리] forecast_lstm 실행 전: 1576.52 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1575.27 MB (변화: -1.26 MB)
[TK]   [LSTM] 완료  첫값=3.12e+08 (메모리: 1575.3 MB)
[TK]   [Theta] 시작  (메모리: 1575.3 MB)
[메모리] forecast_theta 실행 전: 1575.27 MB
[메모리] forecast_theta 실행 후: 1575.27 MB (변화: +0.00 MB)
[TK]   [Theta] 완료  첫값=2.29e+08 (메모리: 1575.3 MB)
[TK]   [DB] 93행 저장 완료
[PROGRESS] [ 156/500] ( 31.2%)  >>  AEHR
[AEHR]   45분기 | 2015-03-31 ~ 2026-03-31
[AEHR]   [SARIMA] 시작  (메모리: 1575.3 MB)
[메모리] forecast_sarima 실행 전: 1575.27 MB
[메모리] find_best_sarima_params 실행 전: 1575.27 MB
[메모리] find_best_sarima_params 실행 후: 1575.27 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1575.27 MB (변화: +0.00 MB)
[AEHR]   [SARIMA] 완료  첫값=1.00e+07 (메모리: 1575.3 MB)
[AEHR]   [ETS] 시작  (메모리: 1575.3 MB)
[메모리] forecast_ets 실행 전: 1575.27 MB
[메모리] forecast_ets 실행 후: 1575.27 MB (변화: +0.00 MB)
[AEHR]   [ETS] 완료  첫값=1.30e+07 (메모리: 1575.3 MB)
[AEHR]   [Prophet] 시작  (메모리: 1575.3 MB)

01:16:14 - cmdstanpy - INFO - Chain [1] start processing
01:16:14 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1575.27 MB
[메모리] forecast_prophet 실행 후: 1575.71 MB (변화: +0.45 MB)
[AEHR]   [Prophet] 완료  첫값=1.61e+07 (메모리: 1575.7 MB)
[AEHR]   [LSTM] 시작  (메모리: 1575.7 MB)
[메모리] forecast_lstm 실행 전: 1575.71 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1575.38 MB (변화: -0.34 MB)
[AEHR]   [LSTM] 완료  첫값=1.27e+07 (메모리: 1575.4 MB)
[AEHR]   [Theta] 시작  (메모리: 1575.4 MB)
[메모리] forecast_theta 실행 전: 1575.38 MB
[메모리] forecast_theta 실행 후: 1575.38 MB (변화: +0.00 MB)
[AEHR]   [Theta] 완료  첫값=1.28e+07 (메모리: 1575.4 MB)
[AEHR]   [DB] 93행 저장 완료
[PROGRESS] [ 157/500] ( 31.4%)  >>  OMER
[OMER]   45분기 | 2015-03-31 ~ 2026-03-31
[OMER]   [SARIMA] 시작  (메모리: 1575.4 MB)
[메모리] forecast_sarima 실행 전: 1575.38 MB
[메모리] find_best_sarima_params 실행 전: 1575.38 MB
[메모리] find_best_sarima_params 실행 후: 1575.38 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1575.38 MB (변화: +0.00 MB)
[OMER]   [SARIMA] 완료  첫값=-7.00e+06 (메모리: 1575.4 MB)
[OMER]   [ETS] 시작  (메모리: 1575.4 MB)
[메모리] forecast_ets 실행 전: 1575.38 MB
[메모리] forecast_ets 실행 후: 1575.38 MB (변화: +0.00 MB)
[OMER]   [ETS] 완료  첫값=2.57e+06 (메모리: 1575.4 MB)
[OMER]   [Prophet] 시작  (메모리: 1575.4 MB)

01:16:31 - cmdstanpy - INFO - Chain [1] start processing
01:16:31 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1575.38 MB
[메모리] forecast_prophet 실행 후: 1575.41 MB (변화: +0.03 MB)
[OMER]   [Prophet] 완료  첫값=-3.13e+06 (메모리: 1575.4 MB)
[OMER]   [LSTM] 시작  (메모리: 1575.4 MB)
[메모리] forecast_lstm 실행 전: 1575.41 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1575.34 MB (변화: -0.07 MB)
[OMER]   [LSTM] 완료  첫값=-4.84e+05 (메모리: 1575.3 MB)
[OMER]   [Theta] 시작  (메모리: 1575.3 MB)
[메모리] forecast_theta 실행 전: 1575.34 MB
[메모리] forecast_theta 실행 후: 1575.34 MB (변화: +0.00 MB)
[OMER]   [Theta] 완료  첫값=-5.06e+05 (메모리: 1575.3 MB)
[OMER]   [DB] 93행 저장 완료
[PROGRESS] [ 158/500] ( 31.6%)  >>  MTUS
[MTUS]   45분기 | 2015-03-31 ~ 2026-03-31
[MTUS]   [SARIMA] 시작  (메모리: 1575.3 MB)
[메모리] forecast_sarima 실행 전: 1575.34 MB
[메모리] find_best_sarima_params 실행 전: 1575.34 MB
[메모리] find_best_sarima_params 실행 후: 1575.34 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1575.34 MB (변화: +0.00 MB)
[MTUS]   [SARIMA] 완료  첫값=3.06e+08 (메모리: 1575.3 MB)
[MTUS]   [ETS] 시작  (메모리: 1575.3 MB)
[메모리] forecast_ets 실행 전: 1575.34 MB
[메모리] forecast_ets 실행 후: 1575.35 MB (변화: +0.01 MB)
[MTUS]   [ETS] 완료  첫값=2.97e+08 (메모리: 1575.3 MB)
[MTUS]   [Prophet] 시작  (메모리: 1575.3 MB)

01:16:52 - cmdstanpy - INFO - Chain [1] start processing
01:16:52 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1575.35 MB
[메모리] forecast_prophet 실행 후: 1575.76 MB (변화: +0.41 MB)
[MTUS]   [Prophet] 완료  첫값=3.10e+08 (메모리: 1575.8 MB)
[MTUS]   [LSTM] 시작  (메모리: 1575.8 MB)
[메모리] forecast_lstm 실행 전: 1575.76 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1576.14 MB (변화: +0.38 MB)
[MTUS]   [LSTM] 완료  첫값=2.99e+08 (메모리: 1576.1 MB)
[MTUS]   [Theta] 시작  (메모리: 1576.1 MB)
[메모리] forecast_theta 실행 전: 1576.14 MB
[메모리] forecast_theta 실행 후: 1576.14 MB (변화: +0.00 MB)
[MTUS]   [Theta] 완료  첫값=3.06e+08 (메모리: 1576.1 MB)
[MTUS]   [DB] 93행 저장 완료
[PROGRESS] [ 159/500] ( 31.8%)  >>  ATRI
[ATRI]   45분기 | 2015-03-31 ~ 2026-03-31
[ATRI]   [SARIMA] 시작  (메모리: 1576.1 MB)
[메모리] forecast_sarima 실행 전: 1576.14 MB
[메모리] find_best_sarima_params 실행 전: 1576.14 MB
[메모리] find_best_sarima_params 실행 후: 1576.14 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1576.14 MB (변화: +0.00 MB)
[ATRI]   [SARIMA] 완료  첫값=4.96e+07 (메모리: 1576.1 MB)
[ATRI]   [ETS] 시작  (메모리: 1576.1 MB)
[메모리] forecast_ets 실행 전: 1576.14 MB
[메모리] forecast_ets 실행 후: 1576.15 MB (변화: +0.00 MB)
[ATRI]   [ETS] 완료  첫값=5.13e+07 (메모리: 1576.1 MB)
[ATRI]   [Prophet] 시작  (메모리: 1576.1 MB)

01:17:18 - cmdstanpy - INFO - Chain [1] start processing
01:17:18 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1576.15 MB
[메모리] forecast_prophet 실행 후: 1576.11 MB (변화: -0.04 MB)
[ATRI]   [Prophet] 완료  첫값=4.85e+07 (메모리: 1576.1 MB)
[ATRI]   [LSTM] 시작  (메모리: 1576.1 MB)
[메모리] forecast_lstm 실행 전: 1576.11 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1575.98 MB (변화: -0.12 MB)
[ATRI]   [LSTM] 완료  첫값=5.26e+07 (메모리: 1576.0 MB)
[ATRI]   [Theta] 시작  (메모리: 1576.0 MB)
[메모리] forecast_theta 실행 전: 1575.98 MB
[메모리] forecast_theta 실행 후: 1575.98 MB (변화: +0.00 MB)
[ATRI]   [Theta] 완료  첫값=5.01e+07 (메모리: 1576.0 MB)
[ATRI]   [DB] 93행 저장 완료
[PROGRESS] [ 160/500] ( 32.0%)  >>  ODC
[ODC]   45분기 | 2015-03-31 ~ 2026-03-31
[ODC]   [SARIMA] 시작  (메모리: 1576.0 MB)
[메모리] forecast_sarima 실행 전: 1575.98 MB
[메모리] find_best_sarima_params 실행 전: 1575.98 MB
[메모리] find_best_sarima_params 실행 후: 1575.98 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1575.98 MB (변화: +0.00 MB)
[ODC]   [SARIMA] 완료  첫값=1.24e+08 (메모리: 1576.0 MB)
[ODC]   [ETS] 시작  (메모리: 1576.0 MB)
[메모리] forecast_ets 실행 전: 1575.98 MB
[메모리] forecast_ets 실행 후: 1575.98 MB (변화: +0.00 MB)
[ODC]   [ETS] 완료  첫값=1.22e+08 (메모리: 1576.0 MB)
[ODC]   [Prophet] 시작  (메모리: 1576.0 MB)

01:17:41 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1575.98 MB

01:17:41 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1575.98 MB (변화: +0.00 MB)
[ODC]   [Prophet] 완료  첫값=1.29e+08 (메모리: 1576.0 MB)
[ODC]   [LSTM] 시작  (메모리: 1576.0 MB)
[메모리] forecast_lstm 실행 전: 1575.98 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1576.94 MB (변화: +0.95 MB)
[ODC]   [LSTM] 완료  첫값=1.23e+08 (메모리: 1576.9 MB)
[ODC]   [Theta] 시작  (메모리: 1576.9 MB)
[메모리] forecast_theta 실행 전: 1576.94 MB
[메모리] forecast_theta 실행 후: 1576.94 MB (변화: +0.00 MB)
[ODC]   [Theta] 완료  첫값=1.20e+08 (메모리: 1576.9 MB)
[ODC]   [DB] 93행 저장 완료
[PROGRESS] [ 161/500] ( 32.2%)  >>  TCRZ
[TCRZ] [SKIP] [TCRZ] 'sale' 데이터가 DB에 없습니다.
[PROGRESS] [ 162/500] ( 32.4%)  >>  QNST
[QNST]   45분기 | 2015-03-31 ~ 2026-03-31
[QNST]   [SARIMA] 시작  (메모리: 1576.9 MB)
[메모리] forecast_sarima 실행 전: 1576.94 MB
[메모리] find_best_sarima_params 실행 전: 1576.94 MB
[메모리] find_best_sarima_params 실행 후: 1576.94 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1576.94 MB (변화: +0.00 MB)
[QNST]   [SARIMA] 완료  첫값=2.79e+08 (메모리: 1576.9 MB)
[QNST]   [ETS] 시작  (메모리: 1576.9 MB)
[메모리] forecast_ets 실행 전: 1576.94 MB
[메모리] forecast_ets 실행 후: 1576.94 MB (변화: +0.00 MB)
[QNST]   [ETS] 완료  첫값=2.79e+08 (메모리: 1576.9 MB)
[QNST]   [Prophet] 시작  (메모리: 1576.9 MB)

01:18:07 - cmdstanpy - INFO - Chain [1] start processing
01:18:07 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1576.94 MB
[메모리] forecast_prophet 실행 후: 1576.98 MB (변화: +0.05 MB)
[QNST]   [Prophet] 완료  첫값=2.46e+08 (메모리: 1577.0 MB)
[QNST]   [LSTM] 시작  (메모리: 1577.0 MB)
[메모리] forecast_lstm 실행 전: 1576.98 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1576.95 MB (변화: -0.04 MB)
[QNST]   [LSTM] 완료  첫값=3.76e+08 (메모리: 1576.9 MB)
[QNST]   [Theta] 시작  (메모리: 1576.9 MB)
[메모리] forecast_theta 실행 전: 1576.95 MB
[메모리] forecast_theta 실행 후: 1576.95 MB (변화: +0.00 MB)
[QNST]   [Theta] 완료  첫값=2.73e+08 (메모리: 1576.9 MB)
[QNST]   [DB] 93행 저장 완료
[PROGRESS] [ 163/500] ( 32.6%)  >>  GAU
[GAU]   45분기 | 2015-03-31 ~ 2026-03-31
[GAU]   [SARIMA] 시작  (메모리: 1576.9 MB)
[메모리] forecast_sarima 실행 전: 1576.95 MB
[메모리] find_best_sarima_params 실행 전: 1576.95 MB
[메모리] find_best_sarima_params 실행 후: 1576.95 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1576.95 MB (변화: +0.00 MB)
[GAU]   [SARIMA] 완료  첫값=1.05e+08 (메모리: 1576.9 MB)
[GAU]   [ETS] 시작  (메모리: 1576.9 MB)
[메모리] forecast_ets 실행 전: 1576.95 MB
[메모리] forecast_ets 실행 후: 1576.95 MB (변화: +0.01 MB)
[GAU]   [ETS] 완료  첫값=1.36e+08 (메모리: 1577.0 MB)
[GAU]   [Prophet] 시작  (메모리: 1577.0 MB)

01:18:29 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1576.95 MB

01:18:29 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1576.97 MB (변화: +0.02 MB)
[GAU]   [Prophet] 완료  첫값=4.87e+07 (메모리: 1577.0 MB)
[GAU]   [LSTM] 시작  (메모리: 1577.0 MB)
[메모리] forecast_lstm 실행 전: 1576.97 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1577.05 MB (변화: +0.08 MB)
[GAU]   [LSTM] 완료  첫값=6.26e+07 (메모리: 1577.1 MB)
[GAU]   [Theta] 시작  (메모리: 1577.1 MB)
[메모리] forecast_theta 실행 전: 1577.05 MB
[메모리] forecast_theta 실행 후: 1577.05 MB (변화: +0.00 MB)
[GAU]   [Theta] 완료  첫값=1.13e+08 (메모리: 1577.1 MB)
[GAU]   [DB] 93행 저장 완료
[PROGRESS] [ 164/500] ( 32.8%)  >>  GPRE
[GPRE]   45분기 | 2015-03-31 ~ 2026-03-31
[GPRE]   [SARIMA] 시작  (메모리: 1577.1 MB)
[메모리] forecast_sarima 실행 전: 1577.05 MB
[메모리] find_best_sarima_params 실행 전: 1577.05 MB
[메모리] find_best_sarima_params 실행 후: 1577.05 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1577.05 MB (변화: +0.00 MB)
[GPRE]   [SARIMA] 완료  첫값=4.24e+08 (메모리: 1577.1 MB)
[GPRE]   [ETS] 시작  (메모리: 1577.1 MB)
[메모리] forecast_ets 실행 전: 1577.05 MB
[메모리] forecast_ets 실행 후: 1577.05 MB (변화: +0.00 MB)
[GPRE]   [ETS] 완료  첫값=4.49e+08 (메모리: 1577.1 MB)
[GPRE]   [Prophet] 시작  (메모리: 1577.1 MB)

01:18:52 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1577.05 MB

01:18:52 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1577.07 MB (변화: +0.02 MB)
[GPRE]   [Prophet] 완료  첫값=6.04e+08 (메모리: 1577.1 MB)
[GPRE]   [LSTM] 시작  (메모리: 1577.1 MB)
[메모리] forecast_lstm 실행 전: 1577.07 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1575.93 MB (변화: -1.14 MB)
[GPRE]   [LSTM] 완료  첫값=6.06e+08 (메모리: 1575.9 MB)
[GPRE]   [Theta] 시작  (메모리: 1575.9 MB)
[메모리] forecast_theta 실행 전: 1575.93 MB
[메모리] forecast_theta 실행 후: 1575.93 MB (변화: +0.00 MB)
[GPRE]   [Theta] 완료  첫값=4.27e+08 (메모리: 1575.9 MB)
[GPRE]   [DB] 93행 저장 완료
[PROGRESS] [ 165/500] ( 33.0%)  >>  HTLD
[HTLD]   45분기 | 2015-03-31 ~ 2026-03-31
[HTLD]   [SARIMA] 시작  (메모리: 1575.9 MB)
[메모리] forecast_sarima 실행 전: 1575.93 MB
[메모리] find_best_sarima_params 실행 전: 1575.93 MB
[메모리] find_best_sarima_params 실행 후: 1575.93 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1575.93 MB (변화: +0.00 MB)
[HTLD]   [SARIMA] 완료  첫값=1.79e+08 (메모리: 1575.9 MB)
[HTLD]   [ETS] 시작  (메모리: 1575.9 MB)
[메모리] forecast_ets 실행 전: 1575.93 MB
[메모리] forecast_ets 실행 후: 1575.94 MB (변화: +0.01 MB)
[HTLD]   [ETS] 완료  첫값=1.81e+08 (메모리: 1575.9 MB)
[HTLD]   [Prophet] 시작  (메모리: 1575.9 MB)

01:19:11 - cmdstanpy - INFO - Chain [1] start processing
01:19:11 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1575.94 MB
[메모리] forecast_prophet 실행 후: 1576.76 MB (변화: +0.82 MB)
[HTLD]   [Prophet] 완료  첫값=2.47e+08 (메모리: 1576.8 MB)
[HTLD]   [LSTM] 시작  (메모리: 1576.8 MB)
[메모리] forecast_lstm 실행 전: 1576.76 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1575.93 MB (변화: -0.83 MB)
[HTLD]   [LSTM] 완료  첫값=2.11e+08 (메모리: 1575.9 MB)
[HTLD]   [Theta] 시작  (메모리: 1575.9 MB)
[메모리] forecast_theta 실행 전: 1575.93 MB
[메모리] forecast_theta 실행 후: 1575.93 MB (변화: +0.00 MB)
[HTLD]   [Theta] 완료  첫값=1.82e+08 (메모리: 1575.9 MB)
[HTLD]   [DB] 93행 저장 완료
[PROGRESS] [ 166/500] ( 33.2%)  >>  CMRX
[CMRX]   45분기 | 2015-03-31 ~ 2026-03-31
[CMRX]   [SARIMA] 시작  (메모리: 1575.9 MB)
[메모리] forecast_sarima 실행 전: 1575.93 MB
[메모리] find_best_sarima_params 실행 전: 1575.93 MB
[메모리] find_best_sarima_params 실행 후: 1575.93 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1575.93 MB (변화: +0.00 MB)
[CMRX]   [SARIMA] 완료  첫값=8.19e+05 (메모리: 1575.9 MB)
[CMRX]   [ETS] 시작  (메모리: 1575.9 MB)
[메모리] forecast_ets 실행 전: 1575.93 MB
[메모리] forecast_ets 실행 후: 1575.94 MB (변화: +0.00 MB)
[CMRX]   [ETS] 완료  첫값=-5.42e+04 (메모리: 1575.9 MB)
[CMRX]   [Prophet] 시작  (메모리: 1575.9 MB)

01:19:32 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1575.94 MB

01:19:32 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1575.68 MB (변화: -0.26 MB)
[CMRX]   [Prophet] 완료  첫값=1.27e+06 (메모리: 1575.7 MB)
[CMRX]   [LSTM] 시작  (메모리: 1575.7 MB)
[메모리] forecast_lstm 실행 전: 1575.68 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1577.10 MB (변화: +1.42 MB)
[CMRX]   [LSTM] 완료  첫값=2.54e+06 (메모리: 1577.1 MB)
[CMRX]   [Theta] 시작  (메모리: 1577.1 MB)
[메모리] forecast_theta 실행 전: 1577.10 MB
[메모리] forecast_theta 실행 후: 1577.10 MB (변화: +0.00 MB)
[CMRX]   [Theta] 완료  첫값=6.89e+05 (메모리: 1577.1 MB)
[CMRX]   [DB] 93행 저장 완료
[PROGRESS] [ 167/500] ( 33.4%)  >>  FOXF
[FOXF]   45분기 | 2015-03-31 ~ 2026-03-31
[FOXF]   [SARIMA] 시작  (메모리: 1577.1 MB)
[메모리] forecast_sarima 실행 전: 1577.10 MB
[메모리] find_best_sarima_params 실행 전: 1577.10 MB
[메모리] find_best_sarima_params 실행 후: 1577.10 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1577.10 MB (변화: +0.00 MB)
[FOXF]   [SARIMA] 완료  첫값=3.76e+08 (메모리: 1577.1 MB)
[FOXF]   [ETS] 시작  (메모리: 1577.1 MB)
[메모리] forecast_ets 실행 전: 1577.10 MB
[메모리] forecast_ets 실행 후: 1577.10 MB (변화: +0.00 MB)
[FOXF]   [ETS] 완료  첫값=4.08e+08 (메모리: 1577.1 MB)
[FOXF]   [Prophet] 시작  (메모리: 1577.1 MB)

01:19:53 - cmdstanpy - INFO - Chain [1] start processing
01:19:53 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1577.10 MB
[메모리] forecast_prophet 실행 후: 1577.18 MB (변화: +0.08 MB)
[FOXF]   [Prophet] 완료  첫값=4.31e+08 (메모리: 1577.2 MB)
[FOXF]   [LSTM] 시작  (메모리: 1577.2 MB)
[메모리] forecast_lstm 실행 전: 1577.18 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1578.29 MB (변화: +1.11 MB)
[FOXF]   [LSTM] 완료  첫값=3.67e+08 (메모리: 1578.3 MB)
[FOXF]   [Theta] 시작  (메모리: 1578.3 MB)
[메모리] forecast_theta 실행 전: 1578.29 MB
[메모리] forecast_theta 실행 후: 1578.29 MB (변화: +0.00 MB)
[FOXF]   [Theta] 완료  첫값=3.92e+08 (메모리: 1578.3 MB)
[FOXF]   [DB] 93행 저장 완료
[PROGRESS] [ 168/500] ( 33.6%)  >>  CDMO
[CDMO]   45분기 | 2015-03-31 ~ 2026-03-31
[CDMO]   [SARIMA] 시작  (메모리: 1578.3 MB)
[메모리] forecast_sarima 실행 전: 1578.29 MB
[메모리] find_best_sarima_params 실행 전: 1578.29 MB
[메모리] find_best_sarima_params 실행 후: 1578.29 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1578.29 MB (변화: +0.00 MB)
[CDMO]   [SARIMA] 완료  첫값=3.42e+07 (메모리: 1578.3 MB)
[CDMO]   [ETS] 시작  (메모리: 1578.3 MB)
[메모리] forecast_ets 실행 전: 1578.29 MB
[메모리] forecast_ets 실행 후: 1578.29 MB (변화: +0.00 MB)
[CDMO]   [ETS] 완료  첫값=4.43e+07 (메모리: 1578.3 MB)
[CDMO]   [Prophet] 시작  (메모리: 1578.3 MB)

01:20:11 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1578.29 MB

01:20:11 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1578.31 MB (변화: +0.02 MB)
[CDMO]   [Prophet] 완료  첫값=3.99e+07 (메모리: 1578.3 MB)
[CDMO]   [LSTM] 시작  (메모리: 1578.3 MB)
[메모리] forecast_lstm 실행 전: 1578.31 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1577.18 MB (변화: -1.13 MB)
[CDMO]   [LSTM] 완료  첫값=4.18e+07 (메모리: 1577.2 MB)
[CDMO]   [Theta] 시작  (메모리: 1577.2 MB)
[메모리] forecast_theta 실행 전: 1577.18 MB
[메모리] forecast_theta 실행 후: 1577.18 MB (변화: +0.00 MB)
[CDMO]   [Theta] 완료  첫값=3.90e+07 (메모리: 1577.2 MB)
[CDMO]   [DB] 93행 저장 완료
[PROGRESS] [ 169/500] ( 33.8%)  >>  BBW
[BBW]   44분기 | 2015-06-30 ~ 2026-03-31
[BBW]   [SARIMA] 시작  (메모리: 1577.2 MB)
[메모리] forecast_sarima 실행 전: 1577.18 MB
[메모리] find_best_sarima_params 실행 전: 1577.18 MB
[메모리] find_best_sarima_params 실행 후: 1577.18 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1577.18 MB (변화: +0.00 MB)
[BBW]   [SARIMA] 완료  첫값=1.18e+08 (메모리: 1577.2 MB)
[BBW]   [ETS] 시작  (메모리: 1577.2 MB)
[메모리] forecast_ets 실행 전: 1577.18 MB
[메모리] forecast_ets 실행 후: 1577.18 MB (변화: +0.00 MB)
[BBW]   [ETS] 완료  첫값=1.08e+08 (메모리: 1577.2 MB)
[BBW]   [Prophet] 시작  (메모리: 1577.2 MB)

01:20:29 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1577.18 MB

01:20:30 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1577.62 MB (변화: +0.44 MB)
[BBW]   [Prophet] 완료  첫값=1.22e+08 (메모리: 1577.6 MB)
[BBW]   [LSTM] 시작  (메모리: 1577.6 MB)
[메모리] forecast_lstm 실행 전: 1577.62 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1577.41 MB (변화: -0.21 MB)
[BBW]   [LSTM] 완료  첫값=1.33e+08 (메모리: 1577.4 MB)
[BBW]   [Theta] 시작  (메모리: 1577.4 MB)
[메모리] forecast_theta 실행 전: 1577.41 MB
[메모리] forecast_theta 실행 후: 1577.41 MB (변화: +0.00 MB)
[BBW]   [Theta] 완료  첫값=1.07e+08 (메모리: 1577.4 MB)
[BBW]   [DB] 92행 저장 완료
[PROGRESS] [ 170/500] ( 34.0%)  >>  AXTI
[AXTI]   45분기 | 2015-03-31 ~ 2026-03-31
[AXTI]   [SARIMA] 시작  (메모리: 1577.4 MB)
[메모리] forecast_sarima 실행 전: 1577.41 MB
[메모리] find_best_sarima_params 실행 전: 1577.41 MB
[메모리] find_best_sarima_params 실행 후: 1577.41 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1577.41 MB (변화: +0.00 MB)
[AXTI]   [SARIMA] 완료  첫값=2.80e+07 (메모리: 1577.4 MB)
[AXTI]   [ETS] 시작  (메모리: 1577.4 MB)
[메모리] forecast_ets 실행 전: 1577.41 MB
[메모리] forecast_ets 실행 후: 1577.41 MB (변화: +0.00 MB)
[AXTI]   [ETS] 완료  첫값=3.01e+07 (메모리: 1577.4 MB)
[AXTI]   [Prophet] 시작  (메모리: 1577.4 MB)

01:20:46 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1577.41 MB

01:20:46 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1578.23 MB (변화: +0.82 MB)
[AXTI]   [Prophet] 완료  첫값=2.76e+07 (메모리: 1578.2 MB)
[AXTI]   [LSTM] 시작  (메모리: 1578.2 MB)
[메모리] forecast_lstm 실행 전: 1578.23 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1577.99 MB (변화: -0.24 MB)
[AXTI]   [LSTM] 완료  첫값=2.31e+07 (메모리: 1578.0 MB)
[AXTI]   [Theta] 시작  (메모리: 1578.0 MB)
[메모리] forecast_theta 실행 전: 1577.99 MB
[메모리] forecast_theta 실행 후: 1577.99 MB (변화: +0.00 MB)
[AXTI]   [Theta] 완료  첫값=2.80e+07 (메모리: 1578.0 MB)
[AXTI]   [DB] 93행 저장 완료
[PROGRESS] [ 171/500] ( 34.2%)  >>  ICPT
[ICPT]   45분기 | 2015-03-31 ~ 2026-03-31
[ICPT]   [SARIMA] 시작  (메모리: 1578.0 MB)
[메모리] forecast_sarima 실행 전: 1577.99 MB
[메모리] find_best_sarima_params 실행 전: 1577.99 MB
[메모리] find_best_sarima_params 실행 후: 1577.99 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1577.99 MB (변화: +0.00 MB)
[ICPT]   [SARIMA] 완료  첫값=8.77e+07 (메모리: 1578.0 MB)
[ICPT]   [ETS] 시작  (메모리: 1578.0 MB)
[메모리] forecast_ets 실행 전: 1577.99 MB
[메모리] forecast_ets 실행 후: 1577.99 MB (변화: +0.00 MB)
[ICPT]   [ETS] 완료  첫값=1.10e+08 (메모리: 1578.0 MB)
[ICPT]   [Prophet] 시작  (메모리: 1578.0 MB)

01:21:06 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1577.99 MB

01:21:06 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1577.85 MB (변화: -0.14 MB)
[ICPT]   [Prophet] 완료  첫값=1.12e+08 (메모리: 1577.9 MB)
[ICPT]   [LSTM] 시작  (메모리: 1577.9 MB)
[메모리] forecast_lstm 실행 전: 1577.85 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1578.81 MB (변화: +0.96 MB)
[ICPT]   [LSTM] 완료  첫값=9.41e+07 (메모리: 1578.8 MB)
[ICPT]   [Theta] 시작  (메모리: 1578.8 MB)
[메모리] forecast_theta 실행 전: 1578.81 MB
[메모리] forecast_theta 실행 후: 1578.81 MB (변화: +0.00 MB)
[ICPT]   [Theta] 완료  첫값=1.23e+08 (메모리: 1578.8 MB)
[ICPT]   [DB] 93행 저장 완료
[PROGRESS] [ 172/500] ( 34.4%)  >>  TEN
[TEN]   45분기 | 2015-03-31 ~ 2026-03-31
[TEN]   [SARIMA] 시작  (메모리: 1578.8 MB)
[메모리] forecast_sarima 실행 전: 1578.81 MB
[메모리] find_best_sarima_params 실행 전: 1578.81 MB
[메모리] find_best_sarima_params 실행 후: 1578.81 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1578.81 MB (변화: +0.00 MB)
[TEN]   [SARIMA] 완료  첫값=1.87e+08 (메모리: 1578.8 MB)
[TEN]   [ETS] 시작  (메모리: 1578.8 MB)
[메모리] forecast_ets 실행 전: 1578.81 MB
[메모리] forecast_ets 실행 후: 1578.81 MB (변화: +0.00 MB)
[TEN]   [ETS] 완료  첫값=1.85e+08 (메모리: 1578.8 MB)
[TEN]   [Prophet] 시작  (메모리: 1578.8 MB)

01:21:27 - cmdstanpy - INFO - Chain [1] start processing
01:21:27 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1578.81 MB
[메모리] forecast_prophet 실행 후: 1577.98 MB (변화: -0.83 MB)
[TEN]   [Prophet] 완료  첫값=2.41e+08 (메모리: 1578.0 MB)
[TEN]   [LSTM] 시작  (메모리: 1578.0 MB)
[메모리] forecast_lstm 실행 전: 1577.98 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1579.30 MB (변화: +1.32 MB)
[TEN]   [LSTM] 완료  첫값=1.71e+08 (메모리: 1579.3 MB)
[TEN]   [Theta] 시작  (메모리: 1579.3 MB)
[메모리] forecast_theta 실행 전: 1579.30 MB
[메모리] forecast_theta 실행 후: 1579.30 MB (변화: +0.00 MB)
[TEN]   [Theta] 완료  첫값=1.88e+08 (메모리: 1579.3 MB)
[TEN]   [DB] 93행 저장 완료
[PROGRESS] [ 173/500] ( 34.6%)  >>  POLY
[POLY]   45분기 | 2015-03-31 ~ 2026-03-31
[POLY]   [SARIMA] 시작  (메모리: 1579.3 MB)
[메모리] forecast_sarima 실행 전: 1579.30 MB
[메모리] find_best_sarima_params 실행 전: 1579.30 MB
[메모리] find_best_sarima_params 실행 후: 1579.30 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1579.30 MB (변화: +0.00 MB)
[POLY]   [SARIMA] 완료  첫값=4.22e+08 (메모리: 1579.3 MB)
[POLY]   [ETS] 시작  (메모리: 1579.3 MB)
[메모리] forecast_ets 실행 전: 1579.30 MB
[메모리] forecast_ets 실행 후: 1579.30 MB (변화: +0.00 MB)
[POLY]   [ETS] 완료  첫값=4.05e+08 (메모리: 1579.3 MB)
[POLY]   [Prophet] 시작  (메모리: 1579.3 MB)

01:21:52 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1579.30 MB

01:21:52 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1579.12 MB (변화: -0.17 MB)
[POLY]   [Prophet] 완료  첫값=4.90e+08 (메모리: 1579.1 MB)
[POLY]   [LSTM] 시작  (메모리: 1579.1 MB)
[메모리] forecast_lstm 실행 전: 1579.12 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1580.32 MB (변화: +1.20 MB)
[POLY]   [LSTM] 완료  첫값=4.17e+08 (메모리: 1580.3 MB)
[POLY]   [Theta] 시작  (메모리: 1580.3 MB)
[메모리] forecast_theta 실행 전: 1580.32 MB
[메모리] forecast_theta 실행 후: 1580.32 MB (변화: +0.00 MB)
[POLY]   [Theta] 완료  첫값=4.00e+08 (메모리: 1580.3 MB)
[POLY]   [DB] 93행 저장 완료
[PROGRESS] [ 174/500] ( 34.8%)  >>  NEWP
[NEWP]   45분기 | 2015-03-31 ~ 2026-03-31
[NEWP]   [SARIMA] 시작  (메모리: 1580.3 MB)
[메모리] forecast_sarima 실행 전: 1580.32 MB
[메모리] find_best_sarima_params 실행 전: 1580.32 MB
[메모리] find_best_sarima_params 실행 후: 1580.32 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1580.32 MB (변화: +0.00 MB)
[NEWP]   [SARIMA] 완료  첫값=-8.62e+04 (메모리: 1580.3 MB)
[NEWP]   [ETS] 시작  (메모리: 1580.3 MB)
[메모리] forecast_ets 실행 전: 1580.32 MB
[메모리] forecast_ets 실행 후: 1580.32 MB (변화: +0.00 MB)
[NEWP]   [ETS] 완료  첫값=-2.48e+05 (메모리: 1580.3 MB)
[NEWP]   [Prophet] 시작  (메모리: 1580.3 MB)

01:22:10 - cmdstanpy - INFO - Chain [1] start processing
01:22:10 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1580.32 MB
[메모리] forecast_prophet 실행 후: 1579.64 MB (변화: -0.68 MB)
[NEWP]   [Prophet] 완료  첫값=-1.42e+05 (메모리: 1579.6 MB)
[NEWP]   [LSTM] 시작  (메모리: 1579.6 MB)
[메모리] forecast_lstm 실행 전: 1579.64 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1581.15 MB (변화: +1.50 MB)
[NEWP]   [LSTM] 완료  첫값=1.95e+05 (메모리: 1581.1 MB)
[NEWP]   [Theta] 시작  (메모리: 1581.1 MB)
[메모리] forecast_theta 실행 전: 1581.15 MB
[메모리] forecast_theta 실행 후: 1581.15 MB (변화: +0.00 MB)
[NEWP]   [Theta] 완료  첫값=-2.08e+05 (메모리: 1581.1 MB)
[NEWP]   [DB] 93행 저장 완료
[PROGRESS] [ 175/500] ( 35.0%)  >>  CTLP
[CTLP]   45분기 | 2015-03-31 ~ 2026-03-31
[CTLP]   [SARIMA] 시작  (메모리: 1581.1 MB)
[메모리] forecast_sarima 실행 전: 1581.15 MB
[메모리] find_best_sarima_params 실행 전: 1581.15 MB
[메모리] find_best_sarima_params 실행 후: 1581.15 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1581.15 MB (변화: +0.00 MB)
[CTLP]   [SARIMA] 완료  첫값=8.45e+07 (메모리: 1581.1 MB)
[CTLP]   [ETS] 시작  (메모리: 1581.1 MB)
[메모리] forecast_ets 실행 전: 1581.15 MB
[메모리] forecast_ets 실행 후: 1581.15 MB (변화: +0.00 MB)
[CTLP]   [ETS] 완료  첫값=8.77e+07 (메모리: 1581.2 MB)
[CTLP]   [Prophet] 시작  (메모리: 1581.2 MB)

01:22:35 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1581.15 MB

01:22:35 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1580.57 MB (변화: -0.59 MB)
[CTLP]   [Prophet] 완료  첫값=8.36e+07 (메모리: 1580.6 MB)
[CTLP]   [LSTM] 시작  (메모리: 1580.6 MB)
[메모리] forecast_lstm 실행 전: 1580.57 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1581.54 MB (변화: +0.97 MB)
[CTLP]   [LSTM] 완료  첫값=8.25e+07 (메모리: 1581.5 MB)
[CTLP]   [Theta] 시작  (메모리: 1581.5 MB)
[메모리] forecast_theta 실행 전: 1581.54 MB
[메모리] forecast_theta 실행 후: 1581.54 MB (변화: +0.00 MB)
[CTLP]   [Theta] 완료  첫값=8.27e+07 (메모리: 1581.5 MB)
[CTLP]   [DB] 93행 저장 완료
[PROGRESS] [ 176/500] ( 35.2%)  >>  ABUS
[ABUS]   45분기 | 2015-03-31 ~ 2026-03-31
[ABUS]   [SARIMA] 시작  (메모리: 1581.5 MB)
[메모리] forecast_sarima 실행 전: 1581.54 MB
[메모리] find_best_sarima_params 실행 전: 1581.54 MB
[메모리] find_best_sarima_params 실행 후: 1581.54 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1581.54 MB (변화: +0.00 MB)
[ABUS]   [SARIMA] 완료  첫값=2.90e+06 (메모리: 1581.5 MB)
[ABUS]   [ETS] 시작  (메모리: 1581.5 MB)
[메모리] forecast_ets 실행 전: 1581.54 MB
[메모리] forecast_ets 실행 후: 1581.54 MB (변화: +0.00 MB)
[ABUS]   [ETS] 완료  첫값=3.14e+06 (메모리: 1581.5 MB)
[ABUS]   [Prophet] 시작  (메모리: 1581.5 MB)

01:22:53 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1581.54 MB

01:22:53 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1581.57 MB (변화: +0.02 MB)
[ABUS]   [Prophet] 완료  첫값=3.70e+06 (메모리: 1581.6 MB)
[ABUS]   [LSTM] 시작  (메모리: 1581.6 MB)
[메모리] forecast_lstm 실행 전: 1581.57 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1581.58 MB (변화: +0.01 MB)
[ABUS]   [LSTM] 완료  첫값=3.00e+06 (메모리: 1581.6 MB)
[ABUS]   [Theta] 시작  (메모리: 1581.6 MB)
[메모리] forecast_theta 실행 전: 1581.58 MB
[메모리] forecast_theta 실행 후: 1581.58 MB (변화: +0.00 MB)
[ABUS]   [Theta] 완료  첫값=1.73e+06 (메모리: 1581.6 MB)
[ABUS]   [DB] 93행 저장 완료
[PROGRESS] [ 177/500] ( 35.4%)  >>  AMN
[AMN]   45분기 | 2015-03-31 ~ 2026-03-31
[AMN]   [SARIMA] 시작  (메모리: 1581.6 MB)
[메모리] forecast_sarima 실행 전: 1581.58 MB
[메모리] find_best_sarima_params 실행 전: 1581.58 MB
[메모리] find_best_sarima_params 실행 후: 1581.58 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1581.58 MB (변화: +0.00 MB)
[AMN]   [SARIMA] 완료  첫값=6.35e+08 (메모리: 1581.6 MB)
[AMN]   [ETS] 시작  (메모리: 1581.6 MB)
[메모리] forecast_ets 실행 전: 1581.58 MB
[메모리] forecast_ets 실행 후: 1581.58 MB (변화: +0.00 MB)
[AMN]   [ETS] 완료  첫값=5.88e+08 (메모리: 1581.6 MB)
[AMN]   [Prophet] 시작  (메모리: 1581.6 MB)

01:23:14 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1581.58 MB

01:23:14 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1581.62 MB (변화: +0.04 MB)
[AMN]   [Prophet] 완료  첫값=9.75e+08 (메모리: 1581.6 MB)
[AMN]   [LSTM] 시작  (메모리: 1581.6 MB)
[메모리] forecast_lstm 실행 전: 1581.62 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1580.54 MB (변화: -1.07 MB)
[AMN]   [LSTM] 완료  첫값=7.44e+08 (메모리: 1580.5 MB)
[AMN]   [Theta] 시작  (메모리: 1580.5 MB)
[메모리] forecast_theta 실행 전: 1580.54 MB
[메모리] forecast_theta 실행 후: 1580.54 MB (변화: +0.00 MB)
[AMN]   [Theta] 완료  첫값=6.14e+08 (메모리: 1580.5 MB)
[AMN]   [DB] 93행 저장 완료
[PROGRESS] [ 178/500] ( 35.6%)  >>  BTX
[BTX] [SKIP] [BTX] 'sale' 데이터가 DB에 없습니다.
[PROGRESS] [ 179/500] ( 35.8%)  >>  WRN
[WRN]   45분기 | 2015-03-31 ~ 2026-03-31
[WRN]   [SARIMA] 시작  (메모리: 1580.5 MB)
[메모리] forecast_sarima 실행 전: 1580.54 MB
[메모리] find_best_sarima_params 실행 전: 1580.54 MB
[메모리] find_best_sarima_params 실행 후: 1580.55 MB (변화: +0.01 MB)
[메모리] forecast_sarima 실행 후: 1580.55 MB (변화: +0.01 MB)
[WRN]   [SARIMA] 완료  첫값=0.00e+00 (메모리: 1580.6 MB)
[WRN]   [ETS] 시작  (메모리: 1580.6 MB)
[메모리] forecast_ets 실행 전: 1580.55 MB
[메모리] forecast_ets 실행 후: 1580.55 MB (변화: +0.00 MB)
[WRN]   [ETS] 완료  첫값=0.00e+00 (메모리: 1580.6 MB)
[WRN]   [Prophet] 시작  (메모리: 1580.6 MB)
[메모리] forecast_prophet 실행 전: 1580.55 MB
[메모리] forecast_prophet 실행 후: 1580.57 MB (변화: +0.02 MB)
[WRN]   [Prophet] 완료  첫값=0.00e+00 (메모리: 1580.6 MB)
[WRN]   [LSTM] 시작  (메모리: 1580.6 MB)
[메모리] forecast_lstm 실행 전: 1580.57 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1580.46 MB (변화: -0.11 MB)
[WRN]   [LSTM] 완료  첫값=0.00e+00 (메모리: 1580.5 MB)
[WRN]   [Theta] 시작  (메모리: 1580.5 MB)
[메모리] forecast_theta 실행 전: 1580.46 MB
[메모리] forecast_theta 실행 후: 1580.46 MB (변화: +0.00 MB)
[WRN]   [Theta] 완료  첫값=0.00e+00 (메모리: 1580.5 MB)
[WRN]   [DB] 93행 저장 완료
[PROGRESS] [ 180/500] ( 36.0%)  >>  HAYN
[HAYN]   45분기 | 2015-03-31 ~ 2026-03-31
[HAYN]   [SARIMA] 시작  (메모리: 1580.5 MB)
[메모리] forecast_sarima 실행 전: 1580.46 MB
[메모리] find_best_sarima_params 실행 전: 1580.46 MB
[메모리] find_best_sarima_params 실행 후: 1580.46 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1580.46 MB (변화: +0.00 MB)
[HAYN]   [SARIMA] 완료  첫값=1.49e+08 (메모리: 1580.5 MB)
[HAYN]   [ETS] 시작  (메모리: 1580.5 MB)
[메모리] forecast_ets 실행 전: 1580.46 MB
[메모리] forecast_ets 실행 후: 1580.46 MB (변화: +0.00 MB)
[HAYN]   [ETS] 완료  첫값=1.49e+08 (메모리: 1580.5 MB)
[HAYN]   [Prophet] 시작  (메모리: 1580.5 MB)

01:23:59 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1580.46 MB

01:23:59 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1581.51 MB (변화: +1.05 MB)
[HAYN]   [Prophet] 완료  첫값=1.49e+08 (메모리: 1581.5 MB)
[HAYN]   [LSTM] 시작  (메모리: 1581.5 MB)
[메모리] forecast_lstm 실행 전: 1581.51 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1581.59 MB (변화: +0.08 MB)
[HAYN]   [LSTM] 완료  첫값=1.53e+08 (메모리: 1581.6 MB)
[HAYN]   [Theta] 시작  (메모리: 1581.6 MB)
[메모리] forecast_theta 실행 전: 1581.59 MB
[메모리] forecast_theta 실행 후: 1581.59 MB (변화: +0.00 MB)
[HAYN]   [Theta] 완료  첫값=1.49e+08 (메모리: 1581.6 MB)
[HAYN]   [DB] 93행 저장 완료
[PROGRESS] [ 181/500] ( 36.2%)  >>  ADTN
[ADTN]   45분기 | 2015-03-31 ~ 2026-03-31
[ADTN]   [SARIMA] 시작  (메모리: 1581.6 MB)
[메모리] forecast_sarima 실행 전: 1581.59 MB
[메모리] find_best_sarima_params 실행 전: 1581.59 MB
[메모리] find_best_sarima_params 실행 후: 1581.59 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1581.59 MB (변화: +0.00 MB)
[ADTN]   [SARIMA] 완료  첫값=2.79e+08 (메모리: 1581.6 MB)
[ADTN]   [ETS] 시작  (메모리: 1581.6 MB)
[메모리] forecast_ets 실행 전: 1581.59 MB
[메모리] forecast_ets 실행 후: 1581.59 MB (변화: +0.01 MB)
[ADTN]   [ETS] 완료  첫값=3.03e+08 (메모리: 1581.6 MB)
[ADTN]   [Prophet] 시작  (메모리: 1581.6 MB)

01:24:17 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1581.59 MB

01:24:17 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1580.62 MB (변화: -0.97 MB)
[ADTN]   [Prophet] 완료  첫값=2.68e+08 (메모리: 1580.6 MB)
[ADTN]   [LSTM] 시작  (메모리: 1580.6 MB)
[메모리] forecast_lstm 실행 전: 1580.62 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1581.86 MB (변화: +1.23 MB)
[ADTN]   [LSTM] 완료  첫값=2.23e+08 (메모리: 1581.9 MB)
[ADTN]   [Theta] 시작  (메모리: 1581.9 MB)
[메모리] forecast_theta 실행 전: 1581.86 MB
[메모리] forecast_theta 실행 후: 1581.86 MB (변화: +0.00 MB)
[ADTN]   [Theta] 완료  첫값=3.00e+08 (메모리: 1581.9 MB)
[ADTN]   [DB] 93행 저장 완료
[PROGRESS] [ 182/500] ( 36.4%)  >>  MDXG
[MDXG]   45분기 | 2015-03-31 ~ 2026-03-31
[MDXG]   [SARIMA] 시작  (메모리: 1581.9 MB)
[메모리] forecast_sarima 실행 전: 1581.86 MB
[메모리] find_best_sarima_params 실행 전: 1581.86 MB
[메모리] find_best_sarima_params 실행 후: 1581.86 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1581.86 MB (변화: +0.00 MB)
[MDXG]   [SARIMA] 완료  첫값=1.16e+08 (메모리: 1581.9 MB)
[MDXG]   [ETS] 시작  (메모리: 1581.9 MB)
[메모리] forecast_ets 실행 전: 1581.86 MB
[메모리] forecast_ets 실행 후: 1581.86 MB (변화: +0.00 MB)
[MDXG]   [ETS] 완료  첫값=1.23e+08 (메모리: 1581.9 MB)
[MDXG]   [Prophet] 시작  (메모리: 1581.9 MB)

01:24:37 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1581.86 MB

01:24:37 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1582.35 MB (변화: +0.49 MB)
[MDXG]   [Prophet] 완료  첫값=9.46e+07 (메모리: 1582.3 MB)
[MDXG]   [LSTM] 시작  (메모리: 1582.3 MB)
[메모리] forecast_lstm 실행 전: 1582.35 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1581.47 MB (변화: -0.88 MB)
[MDXG]   [LSTM] 완료  첫값=8.83e+07 (메모리: 1581.5 MB)
[MDXG]   [Theta] 시작  (메모리: 1581.5 MB)
[메모리] forecast_theta 실행 전: 1581.47 MB
[메모리] forecast_theta 실행 후: 1581.47 MB (변화: +0.00 MB)
[MDXG]   [Theta] 완료  첫값=1.19e+08 (메모리: 1581.5 MB)
[MDXG]   [DB] 93행 저장 완료
[PROGRESS] [ 183/500] ( 36.6%)  >>  MTA
[MTA]   45분기 | 2015-03-31 ~ 2026-03-31
[MTA]   [SARIMA] 시작  (메모리: 1581.5 MB)
[메모리] forecast_sarima 실행 전: 1581.47 MB
[메모리] find_best_sarima_params 실행 전: 1581.47 MB
[메모리] find_best_sarima_params 실행 후: 1581.47 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1581.47 MB (변화: +0.00 MB)
[MTA]   [SARIMA] 완료  첫값=3.79e+06 (메모리: 1581.5 MB)
[MTA]   [ETS] 시작  (메모리: 1581.5 MB)
[메모리] forecast_ets 실행 전: 1581.47 MB
[메모리] forecast_ets 실행 후: 1581.48 MB (변화: +0.00 MB)
[MTA]   [ETS] 완료  첫값=3.82e+06 (메모리: 1581.5 MB)
[MTA]   [Prophet] 시작  (메모리: 1581.5 MB)

01:24:53 - cmdstanpy - INFO - Chain [1] start processing
01:24:53 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1581.48 MB
[메모리] forecast_prophet 실행 후: 1581.50 MB (변화: +0.02 MB)
[MTA]   [Prophet] 완료  첫값=2.28e+06 (메모리: 1581.5 MB)
[MTA]   [LSTM] 시작  (메모리: 1581.5 MB)
[메모리] forecast_lstm 실행 전: 1581.50 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1582.43 MB (변화: +0.93 MB)
[MTA]   [LSTM] 완료  첫값=2.02e+06 (메모리: 1582.4 MB)
[MTA]   [Theta] 시작  (메모리: 1582.4 MB)
[메모리] forecast_theta 실행 전: 1582.43 MB
[메모리] forecast_theta 실행 후: 1582.43 MB (변화: +0.00 MB)
[MTA]   [Theta] 완료  첫값=3.97e+06 (메모리: 1582.4 MB)
[MTA]   [DB] 93행 저장 완료
[PROGRESS] [ 184/500] ( 36.8%)  >>  BLDP
[BLDP]   45분기 | 2015-03-31 ~ 2026-03-31
[BLDP]   [SARIMA] 시작  (메모리: 1582.4 MB)
[메모리] forecast_sarima 실행 전: 1582.43 MB
[메모리] find_best_sarima_params 실행 전: 1582.43 MB
[메모리] find_best_sarima_params 실행 후: 1582.43 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1582.43 MB (변화: +0.00 MB)
[BLDP]   [SARIMA] 완료  첫값=2.41e+07 (메모리: 1582.4 MB)
[BLDP]   [ETS] 시작  (메모리: 1582.4 MB)
[메모리] forecast_ets 실행 전: 1582.43 MB
[메모리] forecast_ets 실행 후: 1582.43 MB (변화: +0.00 MB)
[BLDP]   [ETS] 완료  첫값=3.50e+07 (메모리: 1582.4 MB)
[BLDP]   [Prophet] 시작  (메모리: 1582.4 MB)

01:25:13 - cmdstanpy - INFO - Chain [1] start processing
01:25:13 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1582.43 MB
[메모리] forecast_prophet 실행 후: 1583.08 MB (변화: +0.65 MB)
[BLDP]   [Prophet] 완료  첫값=2.58e+07 (메모리: 1583.1 MB)
[BLDP]   [LSTM] 시작  (메모리: 1583.1 MB)
[메모리] forecast_lstm 실행 전: 1583.08 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1583.25 MB (변화: +0.17 MB)
[BLDP]   [LSTM] 완료  첫값=2.21e+07 (메모리: 1583.2 MB)
[BLDP]   [Theta] 시작  (메모리: 1583.2 MB)
[메모리] forecast_theta 실행 전: 1583.25 MB
[메모리] forecast_theta 실행 후: 1583.25 MB (변화: +0.00 MB)
[BLDP]   [Theta] 완료  첫값=3.47e+07 (메모리: 1583.2 MB)
[BLDP]   [DB] 93행 저장 완료
[PROGRESS] [ 185/500] ( 37.0%)  >>  OSTK
[OSTK]   45분기 | 2015-03-31 ~ 2026-03-31
[OSTK]   [SARIMA] 시작  (메모리: 1583.2 MB)
[메모리] forecast_sarima 실행 전: 1583.25 MB
[메모리] find_best_sarima_params 실행 전: 1583.25 MB
[메모리] find_best_sarima_params 실행 후: 1583.25 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1583.25 MB (변화: +0.00 MB)
[OSTK]   [SARIMA] 완료  첫값=2.77e+08 (메모리: 1583.2 MB)
[OSTK]   [ETS] 시작  (메모리: 1583.2 MB)
[메모리] forecast_ets 실행 전: 1583.25 MB
[메모리] forecast_ets 실행 후: 1583.25 MB (변화: +0.00 MB)
[OSTK]   [ETS] 완료  첫값=2.92e+08 (메모리: 1583.2 MB)
[OSTK]   [Prophet] 시작  (메모리: 1583.2 MB)

01:25:32 - cmdstanpy - INFO - Chain [1] start processing
01:25:32 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1583.25 MB
[메모리] forecast_prophet 실행 후: 1583.25 MB (변화: +0.00 MB)
[OSTK]   [Prophet] 완료  첫값=3.86e+08 (메모리: 1583.3 MB)
[OSTK]   [LSTM] 시작  (메모리: 1583.3 MB)
[메모리] forecast_lstm 실행 전: 1583.25 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1583.82 MB (변화: +0.57 MB)
[OSTK]   [LSTM] 완료  첫값=3.31e+08 (메모리: 1583.8 MB)
[OSTK]   [Theta] 시작  (메모리: 1583.8 MB)
[메모리] forecast_theta 실행 전: 1583.82 MB
[메모리] forecast_theta 실행 후: 1583.82 MB (변화: +0.00 MB)
[OSTK]   [Theta] 완료  첫값=2.98e+08 (메모리: 1583.8 MB)
[OSTK]   [DB] 93행 저장 완료
[PROGRESS] [ 186/500] ( 37.2%)  >>  NXRT
[NXRT]   45분기 | 2015-03-31 ~ 2026-03-31
[NXRT]   [SARIMA] 시작  (메모리: 1583.8 MB)
[메모리] forecast_sarima 실행 전: 1583.82 MB
[메모리] find_best_sarima_params 실행 전: 1583.82 MB
[메모리] find_best_sarima_params 실행 후: 1583.82 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1583.82 MB (변화: +0.00 MB)
[NXRT]   [SARIMA] 완료  첫값=6.36e+07 (메모리: 1583.8 MB)
[NXRT]   [ETS] 시작  (메모리: 1583.8 MB)
[메모리] forecast_ets 실행 전: 1583.82 MB
[메모리] forecast_ets 실행 후: 1583.82 MB (변화: +0.00 MB)
[NXRT]   [ETS] 완료  첫값=6.33e+07 (메모리: 1583.8 MB)
[NXRT]   [Prophet] 시작  (메모리: 1583.8 MB)

01:25:55 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1583.82 MB

01:25:55 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1584.60 MB (변화: +0.77 MB)
[NXRT]   [Prophet] 완료  첫값=6.61e+07 (메모리: 1584.6 MB)
[NXRT]   [LSTM] 시작  (메모리: 1584.6 MB)
[메모리] forecast_lstm 실행 전: 1584.60 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1585.56 MB (변화: +0.96 MB)
[NXRT]   [LSTM] 완료  첫값=7.04e+07 (메모리: 1585.6 MB)
[NXRT]   [Theta] 시작  (메모리: 1585.6 MB)
[메모리] forecast_theta 실행 전: 1585.56 MB
[메모리] forecast_theta 실행 후: 1585.56 MB (변화: +0.00 MB)
[NXRT]   [Theta] 완료  첫값=6.22e+07 (메모리: 1585.6 MB)
[NXRT]   [DB] 93행 저장 완료
[PROGRESS] [ 187/500] ( 37.4%)  >>  MYE
[MYE]   45분기 | 2015-03-31 ~ 2026-03-31
[MYE]   [SARIMA] 시작  (메모리: 1585.6 MB)
[메모리] forecast_sarima 실행 전: 1585.56 MB
[메모리] find_best_sarima_params 실행 전: 1585.56 MB
[메모리] find_best_sarima_params 실행 후: 1585.56 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1585.56 MB (변화: +0.00 MB)
[MYE]   [SARIMA] 완료  첫값=2.06e+08 (메모리: 1585.6 MB)
[MYE]   [ETS] 시작  (메모리: 1585.6 MB)
[메모리] forecast_ets 실행 전: 1585.56 MB
[메모리] forecast_ets 실행 후: 1585.56 MB (변화: +0.00 MB)
[MYE]   [ETS] 완료  첫값=2.05e+08 (메모리: 1585.6 MB)
[MYE]   [Prophet] 시작  (메모리: 1585.6 MB)

01:26:15 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1585.56 MB

01:26:16 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1585.57 MB (변화: +0.02 MB)
[MYE]   [Prophet] 완료  첫값=2.19e+08 (메모리: 1585.6 MB)
[MYE]   [LSTM] 시작  (메모리: 1585.6 MB)
[메모리] forecast_lstm 실행 전: 1585.57 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1585.54 MB (변화: -0.03 MB)
[MYE]   [LSTM] 완료  첫값=1.96e+08 (메모리: 1585.5 MB)
[MYE]   [Theta] 시작  (메모리: 1585.5 MB)
[메모리] forecast_theta 실행 전: 1585.54 MB
[메모리] forecast_theta 실행 후: 1585.54 MB (변화: +0.00 MB)
[MYE]   [Theta] 완료  첫값=2.04e+08 (메모리: 1585.5 MB)
[MYE]   [DB] 93행 저장 완료
[PROGRESS] [ 188/500] ( 37.6%)  >>  AMC
[AMC]   45분기 | 2015-03-31 ~ 2026-03-31
[AMC]   [SARIMA] 시작  (메모리: 1585.5 MB)
[메모리] forecast_sarima 실행 전: 1585.54 MB
[메모리] find_best_sarima_params 실행 전: 1585.54 MB
[메모리] find_best_sarima_params 실행 후: 1585.54 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1585.54 MB (변화: +0.00 MB)
[AMC]   [SARIMA] 완료  첫값=9.80e+08 (메모리: 1585.5 MB)
[AMC]   [ETS] 시작  (메모리: 1585.5 MB)
[메모리] forecast_ets 실행 전: 1585.54 MB
[메모리] forecast_ets 실행 후: 1585.55 MB (변화: +0.01 MB)
[AMC]   [ETS] 완료  첫값=1.14e+09 (메모리: 1585.6 MB)
[AMC]   [Prophet] 시작  (메모리: 1585.6 MB)

01:26:32 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1585.55 MB

01:26:32 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1585.61 MB (변화: +0.06 MB)
[AMC]   [Prophet] 완료  첫값=1.15e+09 (메모리: 1585.6 MB)
[AMC]   [LSTM] 시작  (메모리: 1585.6 MB)
[메모리] forecast_lstm 실행 전: 1585.61 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1585.61 MB (변화: +0.00 MB)
[AMC]   [LSTM] 완료  첫값=1.00e+09 (메모리: 1585.6 MB)
[AMC]   [Theta] 시작  (메모리: 1585.6 MB)
[메모리] forecast_theta 실행 전: 1585.61 MB
[메모리] forecast_theta 실행 후: 1585.61 MB (변화: +0.00 MB)
[AMC]   [Theta] 완료  첫값=1.29e+09 (메모리: 1585.6 MB)
[AMC]   [DB] 93행 저장 완료
[PROGRESS] [ 189/500] ( 37.8%)  >>  APEI
[APEI]   45분기 | 2015-03-31 ~ 2026-03-31
[APEI]   [SARIMA] 시작  (메모리: 1585.6 MB)
[메모리] forecast_sarima 실행 전: 1585.61 MB
[메모리] find_best_sarima_params 실행 전: 1585.61 MB
[메모리] find_best_sarima_params 실행 후: 1585.61 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1585.61 MB (변화: +0.00 MB)
[APEI]   [SARIMA] 완료  첫값=1.66e+08 (메모리: 1585.6 MB)
[APEI]   [ETS] 시작  (메모리: 1585.6 MB)
[메모리] forecast_ets 실행 전: 1585.61 MB
[메모리] forecast_ets 실행 후: 1585.61 MB (변화: +0.00 MB)
[APEI]   [ETS] 완료  첫값=1.58e+08 (메모리: 1585.6 MB)
[APEI]   [Prophet] 시작  (메모리: 1585.6 MB)

01:26:52 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1585.61 MB

01:26:52 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1585.63 MB (변화: +0.02 MB)
[APEI]   [Prophet] 완료  첫값=1.68e+08 (메모리: 1585.6 MB)
[APEI]   [LSTM] 시작  (메모리: 1585.6 MB)
[메모리] forecast_lstm 실행 전: 1585.63 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1583.58 MB (변화: -2.05 MB)
[APEI]   [LSTM] 완료  첫값=1.56e+08 (메모리: 1583.6 MB)
[APEI]   [Theta] 시작  (메모리: 1583.6 MB)
[메모리] forecast_theta 실행 전: 1583.58 MB
[메모리] forecast_theta 실행 후: 1583.58 MB (변화: +0.00 MB)
[APEI]   [Theta] 완료  첫값=1.57e+08 (메모리: 1583.6 MB)
[APEI]   [DB] 93행 저장 완료
[PROGRESS] [ 190/500] ( 38.0%)  >>  BFS
[BFS]   45분기 | 2015-03-31 ~ 2026-03-31
[BFS]   [SARIMA] 시작  (메모리: 1583.6 MB)
[메모리] forecast_sarima 실행 전: 1583.58 MB
[메모리] find_best_sarima_params 실행 전: 1583.58 MB
[메모리] find_best_sarima_params 실행 후: 1583.58 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1583.58 MB (변화: +0.00 MB)
[BFS]   [SARIMA] 완료  첫값=7.29e+07 (메모리: 1583.6 MB)
[BFS]   [ETS] 시작  (메모리: 1583.6 MB)
[메모리] forecast_ets 실행 전: 1583.58 MB
[메모리] forecast_ets 실행 후: 1583.58 MB (변화: +0.00 MB)
[BFS]   [ETS] 완료  첫값=7.12e+07 (메모리: 1583.6 MB)
[BFS]   [Prophet] 시작  (메모리: 1583.6 MB)

01:27:14 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1583.58 MB

01:27:14 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1583.60 MB (변화: +0.02 MB)
[BFS]   [Prophet] 완료  첫값=7.32e+07 (메모리: 1583.6 MB)
[BFS]   [LSTM] 시작  (메모리: 1583.6 MB)
[메모리] forecast_lstm 실행 전: 1583.60 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1583.64 MB (변화: +0.04 MB)
[BFS]   [LSTM] 완료  첫값=7.80e+07 (메모리: 1583.6 MB)
[BFS]   [Theta] 시작  (메모리: 1583.6 MB)
[메모리] forecast_theta 실행 전: 1583.64 MB
[메모리] forecast_theta 실행 후: 1583.64 MB (변화: +0.00 MB)
[BFS]   [Theta] 완료  첫값=7.03e+07 (메모리: 1583.6 MB)
[BFS]   [DB] 93행 저장 완료
[PROGRESS] [ 191/500] ( 38.2%)  >>  PACB
[PACB]   45분기 | 2015-03-31 ~ 2026-03-31
[PACB]   [SARIMA] 시작  (메모리: 1583.6 MB)
[메모리] forecast_sarima 실행 전: 1583.64 MB
[메모리] find_best_sarima_params 실행 전: 1583.64 MB
[메모리] find_best_sarima_params 실행 후: 1583.64 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1583.64 MB (변화: +0.00 MB)
[PACB]   [SARIMA] 완료  첫값=4.43e+07 (메모리: 1583.6 MB)
[PACB]   [ETS] 시작  (메모리: 1583.6 MB)
[메모리] forecast_ets 실행 전: 1583.64 MB
[메모리] forecast_ets 실행 후: 1583.64 MB (변화: +0.00 MB)
[PACB]   [ETS] 완료  첫값=4.48e+07 (메모리: 1583.6 MB)
[PACB]   [Prophet] 시작  (메모리: 1583.6 MB)

01:27:34 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1583.64 MB

01:27:35 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1583.66 MB (변화: +0.02 MB)
[PACB]   [Prophet] 완료  첫값=4.39e+07 (메모리: 1583.7 MB)
[PACB]   [LSTM] 시작  (메모리: 1583.7 MB)
[메모리] forecast_lstm 실행 전: 1583.66 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1583.66 MB (변화: +0.00 MB)
[PACB]   [LSTM] 완료  첫값=4.26e+07 (메모리: 1583.7 MB)
[PACB]   [Theta] 시작  (메모리: 1583.7 MB)
[메모리] forecast_theta 실행 전: 1583.66 MB
[메모리] forecast_theta 실행 후: 1583.66 MB (변화: +0.00 MB)
[PACB]   [Theta] 완료  첫값=4.37e+07 (메모리: 1583.7 MB)
[PACB]   [DB] 93행 저장 완료
[PROGRESS] [ 192/500] ( 38.4%)  >>  ERII
[ERII]   45분기 | 2015-03-31 ~ 2026-03-31
[ERII]   [SARIMA] 시작  (메모리: 1583.7 MB)
[메모리] forecast_sarima 실행 전: 1583.66 MB
[메모리] find_best_sarima_params 실행 전: 1583.66 MB
[메모리] find_best_sarima_params 실행 후: 1583.66 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1583.66 MB (변화: +0.00 MB)
[ERII]   [SARIMA] 완료  첫값=2.51e+07 (메모리: 1583.7 MB)
[ERII]   [ETS] 시작  (메모리: 1583.7 MB)
[메모리] forecast_ets 실행 전: 1583.66 MB
[메모리] forecast_ets 실행 후: 1583.66 MB (변화: +0.00 MB)
[ERII]   [ETS] 완료  첫값=3.28e+07 (메모리: 1583.7 MB)
[ERII]   [Prophet] 시작  (메모리: 1583.7 MB)

01:27:57 - cmdstanpy - INFO - Chain [1] start processing
01:27:57 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1583.66 MB
[메모리] forecast_prophet 실행 후: 1583.68 MB (변화: +0.02 MB)
[ERII]   [Prophet] 완료  첫값=3.63e+07 (메모리: 1583.7 MB)
[ERII]   [LSTM] 시작  (메모리: 1583.7 MB)
[메모리] forecast_lstm 실행 전: 1583.68 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1583.69 MB (변화: +0.01 MB)
[ERII]   [LSTM] 완료  첫값=3.74e+07 (메모리: 1583.7 MB)
[ERII]   [Theta] 시작  (메모리: 1583.7 MB)
[메모리] forecast_theta 실행 전: 1583.69 MB
[메모리] forecast_theta 실행 후: 1583.69 MB (변화: +0.00 MB)
[ERII]   [Theta] 완료  첫값=2.85e+07 (메모리: 1583.7 MB)
[ERII]   [DB] 93행 저장 완료
[PROGRESS] [ 193/500] ( 38.6%)  >>  NKTR
[NKTR]   45분기 | 2015-03-31 ~ 2026-03-31
[NKTR]   [SARIMA] 시작  (메모리: 1583.7 MB)
[메모리] forecast_sarima 실행 전: 1583.69 MB
[메모리] find_best_sarima_params 실행 전: 1583.69 MB
[메모리] find_best_sarima_params 실행 후: 1583.69 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1583.69 MB (변화: +0.00 MB)
[NKTR]   [SARIMA] 완료  첫값=1.90e+07 (메모리: 1583.7 MB)
[NKTR]   [ETS] 시작  (메모리: 1583.7 MB)
[메모리] forecast_ets 실행 전: 1583.69 MB
[메모리] forecast_ets 실행 후: 1583.69 MB (변화: +0.00 MB)
[NKTR]   [ETS] 완료  첫값=1.55e+07 (메모리: 1583.7 MB)
[NKTR]   [Prophet] 시작  (메모리: 1583.7 MB)

01:28:13 - cmdstanpy - INFO - Chain [1] start processing
01:28:13 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1583.69 MB
[메모리] forecast_prophet 실행 후: 1583.70 MB (변화: +0.01 MB)
[NKTR]   [Prophet] 완료  첫값=3.20e+06 (메모리: 1583.7 MB)
[NKTR]   [LSTM] 시작  (메모리: 1583.7 MB)
[메모리] forecast_lstm 실행 전: 1583.70 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1583.71 MB (변화: +0.01 MB)
[NKTR]   [LSTM] 완료  첫값=4.76e+07 (메모리: 1583.7 MB)
[NKTR]   [Theta] 시작  (메모리: 1583.7 MB)
[메모리] forecast_theta 실행 전: 1583.71 MB
[메모리] forecast_theta 실행 후: 1583.71 MB (변화: +0.00 MB)
[NKTR]   [Theta] 완료  첫값=1.26e+07 (메모리: 1583.7 MB)
[NKTR]   [DB] 93행 저장 완료
[PROGRESS] [ 194/500] ( 38.8%)  >>  KALV
[KALV]   45분기 | 2015-03-31 ~ 2026-03-31
[KALV]   [SARIMA] 시작  (메모리: 1583.7 MB)
[메모리] forecast_sarima 실행 전: 1583.71 MB
[메모리] find_best_sarima_params 실행 전: 1583.71 MB
[메모리] find_best_sarima_params 실행 후: 1583.71 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1583.71 MB (변화: +0.00 MB)
[KALV]   [SARIMA] 완료  첫값=1.90e+07 (메모리: 1583.7 MB)
[KALV]   [ETS] 시작  (메모리: 1583.7 MB)
[메모리] forecast_ets 실행 전: 1583.71 MB
[메모리] forecast_ets 실행 후: 1583.71 MB (변화: +0.00 MB)
[KALV]   [ETS] 완료  첫값=1.39e+07 (메모리: 1583.7 MB)
[KALV]   [Prophet] 시작  (메모리: 1583.7 MB)

01:28:29 - cmdstanpy - INFO - Chain [1] start processing
01:28:29 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1583.71 MB
[메모리] forecast_prophet 실행 후: 1583.73 MB (변화: +0.02 MB)
[KALV]   [Prophet] 완료  첫값=3.69e+06 (메모리: 1583.7 MB)
[KALV]   [LSTM] 시작  (메모리: 1583.7 MB)
[메모리] forecast_lstm 실행 전: 1583.73 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1583.79 MB (변화: +0.06 MB)
[KALV]   [LSTM] 완료  첫값=4.76e+06 (메모리: 1583.8 MB)
[KALV]   [Theta] 시작  (메모리: 1583.8 MB)
[메모리] forecast_theta 실행 전: 1583.79 MB
[메모리] forecast_theta 실행 후: 1583.79 MB (변화: +0.00 MB)
[KALV]   [Theta] 완료  첫값=1.37e+07 (메모리: 1583.8 MB)
[KALV]   [DB] 93행 저장 완료
[PROGRESS] [ 195/500] ( 39.0%)  >>  RWT
[RWT]   45분기 | 2015-03-31 ~ 2026-03-31
[RWT]   [SARIMA] 시작  (메모리: 1583.8 MB)
[메모리] forecast_sarima 실행 전: 1583.79 MB
[메모리] find_best_sarima_params 실행 전: 1583.79 MB
[메모리] find_best_sarima_params 실행 후: 1583.79 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1583.79 MB (변화: +0.00 MB)
[RWT]   [SARIMA] 완료  첫값=9.86e+07 (메모리: 1583.8 MB)
[RWT]   [ETS] 시작  (메모리: 1583.8 MB)
[메모리] forecast_ets 실행 전: 1583.79 MB
[메모리] forecast_ets 실행 후: 1583.79 MB (변화: +0.00 MB)
[RWT]   [ETS] 완료  첫값=2.36e+07 (메모리: 1583.8 MB)
[RWT]   [Prophet] 시작  (메모리: 1583.8 MB)

01:28:54 - cmdstanpy - INFO - Chain [1] start processing
01:28:54 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1583.79 MB
[메모리] forecast_prophet 실행 후: 1583.80 MB (변화: +0.00 MB)
[RWT]   [Prophet] 완료  첫값=4.76e+07 (메모리: 1583.8 MB)
[RWT]   [LSTM] 시작  (메모리: 1583.8 MB)
[메모리] forecast_lstm 실행 전: 1583.80 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1583.77 MB (변화: -0.03 MB)
[RWT]   [LSTM] 완료  첫값=8.94e+07 (메모리: 1583.8 MB)
[RWT]   [Theta] 시작  (메모리: 1583.8 MB)
[메모리] forecast_theta 실행 전: 1583.77 MB
[메모리] forecast_theta 실행 후: 1583.77 MB (변화: +0.00 MB)
[RWT]   [Theta] 완료  첫값=5.27e+07 (메모리: 1583.8 MB)
[RWT]   [DB] 93행 저장 완료
[PROGRESS] [ 196/500] ( 39.2%)  >>  KURA
[KURA]   45분기 | 2015-03-31 ~ 2026-03-31
[KURA]   [SARIMA] 시작  (메모리: 1583.8 MB)
[메모리] forecast_sarima 실행 전: 1583.77 MB
[메모리] find_best_sarima_params 실행 전: 1583.77 MB
[메모리] find_best_sarima_params 실행 후: 1583.77 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1583.77 MB (변화: +0.00 MB)
[KURA]   [SARIMA] 완료  첫값=1.77e+07 (메모리: 1583.8 MB)
[KURA]   [ETS] 시작  (메모리: 1583.8 MB)
[메모리] forecast_ets 실행 전: 1583.77 MB
[메모리] forecast_ets 실행 후: 1583.77 MB (변화: +0.00 MB)
[KURA]   [ETS] 완료  첫값=2.29e+07 (메모리: 1583.8 MB)
[KURA]   [Prophet] 시작  (메모리: 1583.8 MB)

01:29:11 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1583.77 MB

01:29:11 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1583.79 MB (변화: +0.01 MB)
[KURA]   [Prophet] 완료  첫값=1.17e+07 (메모리: 1583.8 MB)
[KURA]   [LSTM] 시작  (메모리: 1583.8 MB)
[메모리] forecast_lstm 실행 전: 1583.79 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1583.75 MB (변화: -0.04 MB)
[KURA]   [LSTM] 완료  첫값=3.66e+07 (메모리: 1583.7 MB)
[KURA]   [Theta] 시작  (메모리: 1583.7 MB)
[메모리] forecast_theta 실행 전: 1583.75 MB
[메모리] forecast_theta 실행 후: 1583.75 MB (변화: +0.00 MB)
[KURA]   [Theta] 완료  첫값=1.98e+07 (메모리: 1583.7 MB)
[KURA]   [DB] 93행 저장 완료
[PROGRESS] [ 197/500] ( 39.4%)  >>  WLKP
[WLKP]   45분기 | 2015-03-31 ~ 2026-03-31
[WLKP]   [SARIMA] 시작  (메모리: 1583.7 MB)
[메모리] forecast_sarima 실행 전: 1583.75 MB
[메모리] find_best_sarima_params 실행 전: 1583.75 MB
[메모리] find_best_sarima_params 실행 후: 1583.75 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1583.75 MB (변화: +0.00 MB)
[WLKP]   [SARIMA] 완료  첫값=3.10e+08 (메모리: 1583.7 MB)
[WLKP]   [ETS] 시작  (메모리: 1583.7 MB)
[메모리] forecast_ets 실행 전: 1583.75 MB
[메모리] forecast_ets 실행 후: 1583.75 MB (변화: +0.00 MB)
[WLKP]   [ETS] 완료  첫값=3.15e+08 (메모리: 1583.8 MB)
[WLKP]   [Prophet] 시작  (메모리: 1583.8 MB)

01:29:34 - cmdstanpy - INFO - Chain [1] start processing
01:29:34 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1583.75 MB
[메모리] forecast_prophet 실행 후: 1583.77 MB (변화: +0.02 MB)
[WLKP]   [Prophet] 완료  첫값=3.19e+08 (메모리: 1583.8 MB)
[WLKP]   [LSTM] 시작  (메모리: 1583.8 MB)
[메모리] forecast_lstm 실행 전: 1583.77 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1583.73 MB (변화: -0.04 MB)
[WLKP]   [LSTM] 완료  첫값=2.80e+08 (메모리: 1583.7 MB)
[WLKP]   [Theta] 시작  (메모리: 1583.7 MB)
[메모리] forecast_theta 실행 전: 1583.73 MB
[메모리] forecast_theta 실행 후: 1583.73 MB (변화: +0.00 MB)
[WLKP]   [Theta] 완료  첫값=3.10e+08 (메모리: 1583.7 MB)
[WLKP]   [DB] 93행 저장 완료
[PROGRESS] [ 198/500] ( 39.6%)  >>  MMX
[MMX]   45분기 | 2015-03-31 ~ 2026-03-31
[MMX]   [SARIMA] 시작  (메모리: 1583.7 MB)
[메모리] forecast_sarima 실행 전: 1583.73 MB
[메모리] find_best_sarima_params 실행 전: 1583.73 MB
[메모리] find_best_sarima_params 실행 후: 1583.73 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1583.73 MB (변화: +0.00 MB)
[MMX]   [SARIMA] 완료  첫값=1.64e+07 (메모리: 1583.7 MB)
[MMX]   [ETS] 시작  (메모리: 1583.7 MB)
[메모리] forecast_ets 실행 전: 1583.73 MB
[메모리] forecast_ets 실행 후: 1583.73 MB (변화: +0.00 MB)
[MMX]   [ETS] 완료  첫값=1.65e+07 (메모리: 1583.7 MB)
[MMX]   [Prophet] 시작  (메모리: 1583.7 MB)

01:29:57 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1583.73 MB

01:29:57 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1583.74 MB (변화: +0.01 MB)
[MMX]   [Prophet] 완료  첫값=2.07e+07 (메모리: 1583.7 MB)
[MMX]   [LSTM] 시작  (메모리: 1583.7 MB)
[메모리] forecast_lstm 실행 전: 1583.74 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1583.70 MB (변화: -0.04 MB)
[MMX]   [LSTM] 완료  첫값=1.59e+07 (메모리: 1583.7 MB)
[MMX]   [Theta] 시작  (메모리: 1583.7 MB)
[메모리] forecast_theta 실행 전: 1583.70 MB
[메모리] forecast_theta 실행 후: 1583.70 MB (변화: +0.00 MB)
[MMX]   [Theta] 완료  첫값=1.66e+07 (메모리: 1583.7 MB)
[MMX]   [DB] 93행 저장 완료
[PROGRESS] [ 199/500] ( 39.8%)  >>  RZLV
[RZLV] [SKIP] [RZLV] 'sale' 관측치 부족: 16개 < 최소 28개
[PROGRESS] [ 200/500] ( 40.0%)  >>  HSC
[HSC]   45분기 | 2015-03-31 ~ 2026-03-31
[HSC]   [SARIMA] 시작  (메모리: 1583.7 MB)
[메모리] forecast_sarima 실행 전: 1583.70 MB
[메모리] find_best_sarima_params 실행 전: 1583.70 MB
[메모리] find_best_sarima_params 실행 후: 1583.70 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1583.70 MB (변화: +0.00 MB)
[HSC]   [SARIMA] 완료  첫값=5.75e+08 (메모리: 1583.7 MB)
[HSC]   [ETS] 시작  (메모리: 1583.7 MB)
[메모리] forecast_ets 실행 전: 1583.70 MB
[메모리] forecast_ets 실행 후: 1583.70 MB (변화: +0.00 MB)
[HSC]   [ETS] 완료  첫값=5.89e+08 (메모리: 1583.7 MB)
[HSC]   [Prophet] 시작  (메모리: 1583.7 MB)

01:30:20 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1583.70 MB

01:30:20 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1584.11 MB (변화: +0.41 MB)
[HSC]   [Prophet] 완료  첫값=5.93e+08 (메모리: 1584.1 MB)
[HSC]   [LSTM] 시작  (메모리: 1584.1 MB)
[메모리] forecast_lstm 실행 전: 1584.11 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1584.07 MB (변화: -0.04 MB)
[HSC]   [LSTM] 완료  첫값=5.59e+08 (메모리: 1584.1 MB)
[HSC]   [Theta] 시작  (메모리: 1584.1 MB)
[메모리] forecast_theta 실행 전: 1584.07 MB
[메모리] forecast_theta 실행 후: 1584.07 MB (변화: +0.00 MB)
[HSC]   [Theta] 완료  첫값=5.88e+08 (메모리: 1584.1 MB)
[HSC]   [DB] 93행 저장 완료
[PROGRESS] [ 201/500] ( 40.2%)  >>  KE
[KE]   45분기 | 2015-03-31 ~ 2026-03-31
[KE]   [SARIMA] 시작  (메모리: 1584.1 MB)
[메모리] forecast_sarima 실행 전: 1584.07 MB
[메모리] find_best_sarima_params 실행 전: 1584.07 MB
[메모리] find_best_sarima_params 실행 후: 1584.07 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1584.07 MB (변화: +0.00 MB)
[KE]   [SARIMA] 완료  첫값=3.45e+08 (메모리: 1584.1 MB)
[KE]   [ETS] 시작  (메모리: 1584.1 MB)
[메모리] forecast_ets 실행 전: 1584.07 MB
[메모리] forecast_ets 실행 후: 1584.08 MB (변화: +0.00 MB)
[KE]   [ETS] 완료  첫값=3.45e+08 (메모리: 1584.1 MB)
[KE]   [Prophet] 시작  (메모리: 1584.1 MB)
[메모리] forecast_prophet 실행 전: 1584.08 MB

01:30:39 - cmdstanpy - INFO - Chain [1] start processing
01:30:40 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1584.89 MB (변화: +0.81 MB)
[KE]   [Prophet] 완료  첫값=4.35e+08 (메모리: 1584.9 MB)
[KE]   [LSTM] 시작  (메모리: 1584.9 MB)
[메모리] forecast_lstm 실행 전: 1584.89 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1584.93 MB (변화: +0.04 MB)
[KE]   [LSTM] 완료  첫값=4.38e+08 (메모리: 1584.9 MB)
[KE]   [Theta] 시작  (메모리: 1584.9 MB)
[메모리] forecast_theta 실행 전: 1584.93 MB
[메모리] forecast_theta 실행 후: 1584.93 MB (변화: +0.00 MB)
[KE]   [Theta] 완료  첫값=3.45e+08 (메모리: 1584.9 MB)
[KE]   [DB] 93행 저장 완료
[PROGRESS] [ 202/500] ( 40.4%)  >>  BGM
[BGM] [SKIP] [BGM] 'sale' 관측치 부족: 9개 < 최소 28개
[PROGRESS] [ 203/500] ( 40.6%)  >>  CRY
[CRY]   45분기 | 2015-03-31 ~ 2026-03-31
[CRY]   [SARIMA] 시작  (메모리: 1584.9 MB)
[메모리] forecast_sarima 실행 전: 1584.93 MB
[메모리] find_best_sarima_params 실행 전: 1584.93 MB
[메모리] find_best_sarima_params 실행 후: 1584.93 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1584.93 MB (변화: +0.00 MB)
[CRY]   [SARIMA] 완료  첫값=1.22e+08 (메모리: 1584.9 MB)
[CRY]   [ETS] 시작  (메모리: 1584.9 MB)
[메모리] forecast_ets 실행 전: 1584.93 MB
[메모리] forecast_ets 실행 후: 1584.93 MB (변화: +0.00 MB)
[CRY]   [ETS] 완료  첫값=1.21e+08 (메모리: 1584.9 MB)
[CRY]   [Prophet] 시작  (메모리: 1584.9 MB)

01:31:01 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1584.93 MB

01:31:02 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1585.20 MB (변화: +0.27 MB)
[CRY]   [Prophet] 완료  첫값=1.09e+08 (메모리: 1585.2 MB)
[CRY]   [LSTM] 시작  (메모리: 1585.2 MB)
[메모리] forecast_lstm 실행 전: 1585.20 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1585.17 MB (변화: -0.03 MB)
[CRY]   [LSTM] 완료  첫값=1.24e+08 (메모리: 1585.2 MB)
[CRY]   [Theta] 시작  (메모리: 1585.2 MB)
[메모리] forecast_theta 실행 전: 1585.17 MB
[메모리] forecast_theta 실행 후: 1585.17 MB (변화: +0.00 MB)
[CRY]   [Theta] 완료  첫값=1.17e+08 (메모리: 1585.2 MB)
[CRY]   [DB] 93행 저장 완료
[PROGRESS] [ 204/500] ( 40.8%)  >>  WSR
[WSR]   45분기 | 2015-03-31 ~ 2026-03-31
[WSR]   [SARIMA] 시작  (메모리: 1585.2 MB)
[메모리] forecast_sarima 실행 전: 1585.17 MB
[메모리] find_best_sarima_params 실행 전: 1585.17 MB
[메모리] find_best_sarima_params 실행 후: 1585.17 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1585.17 MB (변화: +0.00 MB)
[WSR]   [SARIMA] 완료  첫값=4.17e+07 (메모리: 1585.2 MB)
[WSR]   [ETS] 시작  (메모리: 1585.2 MB)
[메모리] forecast_ets 실행 전: 1585.17 MB
[메모리] forecast_ets 실행 후: 1585.18 MB (변화: +0.00 MB)
[WSR]   [ETS] 완료  첫값=4.11e+07 (메모리: 1585.2 MB)
[WSR]   [Prophet] 시작  (메모리: 1585.2 MB)

01:31:22 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1585.18 MB

01:31:22 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1585.20 MB (변화: +0.02 MB)
[WSR]   [Prophet] 완료  첫값=4.06e+07 (메모리: 1585.2 MB)
[WSR]   [LSTM] 시작  (메모리: 1585.2 MB)
[메모리] forecast_lstm 실행 전: 1585.20 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1585.18 MB (변화: -0.02 MB)
[WSR]   [LSTM] 완료  첫값=4.18e+07 (메모리: 1585.2 MB)
[WSR]   [Theta] 시작  (메모리: 1585.2 MB)
[메모리] forecast_theta 실행 전: 1585.18 MB
[메모리] forecast_theta 실행 후: 1585.18 MB (변화: +0.00 MB)
[WSR]   [Theta] 완료  첫값=4.07e+07 (메모리: 1585.2 MB)
[WSR]   [DB] 93행 저장 완료
[PROGRESS] [ 205/500] ( 41.0%)  >>  GDEN
[GDEN]   45분기 | 2015-03-31 ~ 2026-03-31
[GDEN]   [SARIMA] 시작  (메모리: 1585.2 MB)
[메모리] forecast_sarima 실행 전: 1585.18 MB
[메모리] find_best_sarima_params 실행 전: 1585.18 MB
[메모리] find_best_sarima_params 실행 후: 1585.18 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1585.18 MB (변화: +0.00 MB)
[GDEN]   [SARIMA] 완료  첫값=1.65e+08 (메모리: 1585.2 MB)
[GDEN]   [ETS] 시작  (메모리: 1585.2 MB)
[메모리] forecast_ets 실행 전: 1585.18 MB
[메모리] forecast_ets 실행 후: 1585.18 MB (변화: +0.00 MB)
[GDEN]   [ETS] 완료  첫값=1.36e+08 (메모리: 1585.2 MB)
[GDEN]   [Prophet] 시작  (메모리: 1585.2 MB)
[메모리] forecast_prophet 실행 전: 1585.18 MB

01:31:42 - cmdstanpy - INFO - Chain [1] start processing
01:31:42 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1585.20 MB (변화: +0.02 MB)
[GDEN]   [Prophet] 완료  첫값=2.52e+08 (메모리: 1585.2 MB)
[GDEN]   [LSTM] 시작  (메모리: 1585.2 MB)
[메모리] forecast_lstm 실행 전: 1585.20 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1585.16 MB (변화: -0.04 MB)
[GDEN]   [LSTM] 완료  첫값=2.02e+08 (메모리: 1585.2 MB)
[GDEN]   [Theta] 시작  (메모리: 1585.2 MB)
[메모리] forecast_theta 실행 전: 1585.16 MB
[메모리] forecast_theta 실행 후: 1585.16 MB (변화: +0.00 MB)
[GDEN]   [Theta] 완료  첫값=1.57e+08 (메모리: 1585.2 MB)
[GDEN]   [DB] 93행 저장 완료
[PROGRESS] [ 206/500] ( 41.2%)  >>  AIOT
[AIOT]   45분기 | 2015-03-31 ~ 2026-03-31
[AIOT]   [SARIMA] 시작  (메모리: 1585.2 MB)
[메모리] forecast_sarima 실행 전: 1585.16 MB
[메모리] find_best_sarima_params 실행 전: 1585.16 MB
[메모리] find_best_sarima_params 실행 후: 1585.16 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1585.16 MB (변화: +0.00 MB)
[AIOT]   [SARIMA] 완료  첫값=1.17e+08 (메모리: 1585.2 MB)
[AIOT]   [ETS] 시작  (메모리: 1585.2 MB)
[메모리] forecast_ets 실행 전: 1585.16 MB
[메모리] forecast_ets 실행 후: 1585.17 MB (변화: +0.00 MB)
[AIOT]   [ETS] 완료  첫값=1.37e+08 (메모리: 1585.2 MB)
[AIOT]   [Prophet] 시작  (메모리: 1585.2 MB)

01:32:02 - cmdstanpy - INFO - Chain [1] start processing
01:32:02 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1585.17 MB
[메모리] forecast_prophet 실행 후: 1585.19 MB (변화: +0.02 MB)
[AIOT]   [Prophet] 완료  첫값=8.63e+07 (메모리: 1585.2 MB)
[AIOT]   [LSTM] 시작  (메모리: 1585.2 MB)
[메모리] forecast_lstm 실행 전: 1585.19 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1585.27 MB (변화: +0.08 MB)
[AIOT]   [LSTM] 완료  첫값=1.46e+08 (메모리: 1585.3 MB)
[AIOT]   [Theta] 시작  (메모리: 1585.3 MB)
[메모리] forecast_theta 실행 전: 1585.27 MB
[메모리] forecast_theta 실행 후: 1585.27 MB (변화: +0.00 MB)
[AIOT]   [Theta] 완료  첫값=1.36e+08 (메모리: 1585.3 MB)
[AIOT]   [DB] 93행 저장 완료
[PROGRESS] [ 207/500] ( 41.4%)  >>  ATXS
[ATXS]   45분기 | 2015-03-31 ~ 2026-03-31
[ATXS]   [SARIMA] 시작  (메모리: 1585.3 MB)
[메모리] forecast_sarima 실행 전: 1585.27 MB
[메모리] find_best_sarima_params 실행 전: 1585.27 MB
[메모리] find_best_sarima_params 실행 후: 1585.27 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1585.27 MB (변화: +0.00 MB)
[ATXS]   [SARIMA] 완료  첫값=7.06e+05 (메모리: 1585.3 MB)
[ATXS]   [ETS] 시작  (메모리: 1585.3 MB)
[메모리] forecast_ets 실행 전: 1585.27 MB
[메모리] forecast_ets 실행 후: 1585.27 MB (변화: +0.00 MB)
[ATXS]   [ETS] 완료  첫값=7.21e+05 (메모리: 1585.3 MB)
[ATXS]   [Prophet] 시작  (메모리: 1585.3 MB)

01:32:21 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1585.27 MB

01:32:21 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1585.35 MB (변화: +0.07 MB)
[ATXS]   [Prophet] 완료  첫값=1.75e+05 (메모리: 1585.3 MB)
[ATXS]   [LSTM] 시작  (메모리: 1585.3 MB)
[메모리] forecast_lstm 실행 전: 1585.35 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1585.36 MB (변화: +0.02 MB)
[ATXS]   [LSTM] 완료  첫값=1.21e+05 (메모리: 1585.4 MB)
[ATXS]   [Theta] 시작  (메모리: 1585.4 MB)
[메모리] forecast_theta 실행 전: 1585.36 MB
[메모리] forecast_theta 실행 후: 1585.36 MB (변화: +0.00 MB)
[ATXS]   [Theta] 완료  첫값=7.09e+05 (메모리: 1585.4 MB)
[ATXS]   [DB] 93행 저장 완료
[PROGRESS] [ 208/500] ( 41.6%)  >>  GYRE
[GYRE]   45분기 | 2015-03-31 ~ 2026-03-31
[GYRE]   [SARIMA] 시작  (메모리: 1585.4 MB)
[메모리] forecast_sarima 실행 전: 1585.36 MB
[메모리] find_best_sarima_params 실행 전: 1585.36 MB
[메모리] find_best_sarima_params 실행 후: 1585.36 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1585.36 MB (변화: +0.00 MB)
[GYRE]   [SARIMA] 완료  첫값=3.07e+07 (메모리: 1585.4 MB)
[GYRE]   [ETS] 시작  (메모리: 1585.4 MB)
[메모리] forecast_ets 실행 전: 1585.36 MB
[메모리] forecast_ets 실행 후: 1585.37 MB (변화: +0.00 MB)
[GYRE]   [ETS] 완료  첫값=3.02e+07 (메모리: 1585.4 MB)
[GYRE]   [Prophet] 시작  (메모리: 1585.4 MB)

01:32:37 - cmdstanpy - INFO - Chain [1] start processing
01:32:37 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1585.37 MB
[메모리] forecast_prophet 실행 후: 1585.38 MB (변화: +0.02 MB)
[GYRE]   [Prophet] 완료  첫값=2.88e+07 (메모리: 1585.4 MB)
[GYRE]   [LSTM] 시작  (메모리: 1585.4 MB)
[메모리] forecast_lstm 실행 전: 1585.38 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1585.44 MB (변화: +0.05 MB)
[GYRE]   [LSTM] 완료  첫값=3.45e+07 (메모리: 1585.4 MB)
[GYRE]   [Theta] 시작  (메모리: 1585.4 MB)
[메모리] forecast_theta 실행 전: 1585.44 MB
[메모리] forecast_theta 실행 후: 1585.44 MB (변화: +0.00 MB)
[GYRE]   [Theta] 완료  첫값=2.93e+07 (메모리: 1585.4 MB)
[GYRE]   [DB] 93행 저장 완료
[PROGRESS] [ 209/500] ( 41.8%)  >>  BZH
[BZH]   45분기 | 2015-03-31 ~ 2026-03-31
[BZH]   [SARIMA] 시작  (메모리: 1585.4 MB)
[메모리] forecast_sarima 실행 전: 1585.44 MB
[메모리] find_best_sarima_params 실행 전: 1585.44 MB
[메모리] find_best_sarima_params 실행 후: 1585.44 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1585.44 MB (변화: +0.00 MB)
[BZH]   [SARIMA] 완료  첫값=4.94e+08 (메모리: 1585.4 MB)
[BZH]   [ETS] 시작  (메모리: 1585.4 MB)
[메모리] forecast_ets 실행 전: 1585.44 MB
[메모리] forecast_ets 실행 후: 1585.44 MB (변화: +0.00 MB)
[BZH]   [ETS] 완료  첫값=5.34e+08 (메모리: 1585.4 MB)
[BZH]   [Prophet] 시작  (메모리: 1585.4 MB)

01:32:58 - cmdstanpy - INFO - Chain [1] start processing
01:32:58 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1585.44 MB
[메모리] forecast_prophet 실행 후: 1585.47 MB (변화: +0.03 MB)
[BZH]   [Prophet] 완료  첫값=5.86e+08 (메모리: 1585.5 MB)
[BZH]   [LSTM] 시작  (메모리: 1585.5 MB)
[메모리] forecast_lstm 실행 전: 1585.47 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1585.46 MB (변화: -0.00 MB)
[BZH]   [LSTM] 완료  첫값=5.90e+08 (메모리: 1585.5 MB)
[BZH]   [Theta] 시작  (메모리: 1585.5 MB)
[메모리] forecast_theta 실행 전: 1585.46 MB
[메모리] forecast_theta 실행 후: 1585.46 MB (변화: +0.00 MB)
[BZH]   [Theta] 완료  첫값=4.20e+08 (메모리: 1585.5 MB)
[BZH]   [DB] 93행 저장 완료
[PROGRESS] [ 210/500] ( 42.0%)  >>  RGNX
[RGNX]   45분기 | 2015-03-31 ~ 2026-03-31
[RGNX]   [SARIMA] 시작  (메모리: 1585.5 MB)
[메모리] forecast_sarima 실행 전: 1585.46 MB
[메모리] find_best_sarima_params 실행 전: 1585.46 MB
[메모리] find_best_sarima_params 실행 후: 1585.46 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1585.46 MB (변화: +0.00 MB)
[RGNX]   [SARIMA] 완료  첫값=3.29e+07 (메모리: 1585.5 MB)
[RGNX]   [ETS] 시작  (메모리: 1585.5 MB)
[메모리] forecast_ets 실행 전: 1585.46 MB
[메모리] forecast_ets 실행 후: 1585.47 MB (변화: +0.00 MB)
[RGNX]   [ETS] 완료  첫값=5.16e+07 (메모리: 1585.5 MB)
[RGNX]   [Prophet] 시작  (메모리: 1585.5 MB)

01:33:16 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1585.47 MB

01:33:16 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1585.48 MB (변화: +0.01 MB)
[RGNX]   [Prophet] 완료  첫값=5.11e+07 (메모리: 1585.5 MB)
[RGNX]   [LSTM] 시작  (메모리: 1585.5 MB)
[메모리] forecast_lstm 실행 전: 1585.48 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1585.43 MB (변화: -0.05 MB)
[RGNX]   [LSTM] 완료  첫값=3.97e+07 (메모리: 1585.4 MB)
[RGNX]   [Theta] 시작  (메모리: 1585.4 MB)
[메모리] forecast_theta 실행 전: 1585.43 MB
[메모리] forecast_theta 실행 후: 1585.43 MB (변화: +0.00 MB)
[RGNX]   [Theta] 완료  첫값=4.51e+07 (메모리: 1585.4 MB)
[RGNX]   [DB] 93행 저장 완료
[PROGRESS] [ 211/500] ( 42.2%)  >>  FFHL
[FFHL]   45분기 | 2015-03-31 ~ 2026-03-31
[FFHL]   [SARIMA] 시작  (메모리: 1585.4 MB)
[메모리] forecast_sarima 실행 전: 1585.43 MB
[메모리] find_best_sarima_params 실행 전: 1585.43 MB
[메모리] find_best_sarima_params 실행 후: 1585.43 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1585.43 MB (변화: +0.00 MB)
[FFHL]   [SARIMA] 완료  첫값=8.87e+07 (메모리: 1585.4 MB)
[FFHL]   [ETS] 시작  (메모리: 1585.4 MB)
[메모리] forecast_ets 실행 전: 1585.43 MB
[메모리] forecast_ets 실행 후: 1585.43 MB (변화: +0.00 MB)
[FFHL]   [ETS] 완료  첫값=9.00e+07 (메모리: 1585.4 MB)
[FFHL]   [Prophet] 시작  (메모리: 1585.4 MB)

01:33:35 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1585.43 MB

01:33:35 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1585.47 MB (변화: +0.04 MB)
[FFHL]   [Prophet] 완료  첫값=8.85e+07 (메모리: 1585.5 MB)
[FFHL]   [LSTM] 시작  (메모리: 1585.5 MB)
[메모리] forecast_lstm 실행 전: 1585.47 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1584.46 MB (변화: -1.02 MB)
[FFHL]   [LSTM] 완료  첫값=1.03e+08 (메모리: 1584.5 MB)
[FFHL]   [Theta] 시작  (메모리: 1584.5 MB)
[메모리] forecast_theta 실행 전: 1584.46 MB
[메모리] forecast_theta 실행 후: 1584.46 MB (변화: +0.00 MB)
[FFHL]   [Theta] 완료  첫값=8.78e+07 (메모리: 1584.5 MB)
[FFHL]   [DB] 93행 저장 완료
[PROGRESS] [ 212/500] ( 42.4%)  >>  CXP
[CXP]   45분기 | 2015-03-31 ~ 2026-03-31
[CXP]   [SARIMA] 시작  (메모리: 1584.5 MB)
[메모리] forecast_sarima 실행 전: 1584.46 MB
[메모리] find_best_sarima_params 실행 전: 1584.46 MB
[메모리] find_best_sarima_params 실행 후: 1584.46 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1584.46 MB (변화: +0.00 MB)
[CXP]   [SARIMA] 완료  첫값=6.20e+07 (메모리: 1584.5 MB)
[CXP]   [ETS] 시작  (메모리: 1584.5 MB)
[메모리] forecast_ets 실행 전: 1584.46 MB
[메모리] forecast_ets 실행 후: 1584.46 MB (변화: +0.00 MB)
[CXP]   [ETS] 완료  첫값=6.29e+07 (메모리: 1584.5 MB)
[CXP]   [Prophet] 시작  (메모리: 1584.5 MB)

01:33:54 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1584.46 MB

01:33:54 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1584.48 MB (변화: +0.02 MB)
[CXP]   [Prophet] 완료  첫값=4.50e+07 (메모리: 1584.5 MB)
[CXP]   [LSTM] 시작  (메모리: 1584.5 MB)
[메모리] forecast_lstm 실행 전: 1584.48 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1584.49 MB (변화: +0.01 MB)
[CXP]   [LSTM] 완료  첫값=6.54e+07 (메모리: 1584.5 MB)
[CXP]   [Theta] 시작  (메모리: 1584.5 MB)
[메모리] forecast_theta 실행 전: 1584.49 MB
[메모리] forecast_theta 실행 후: 1584.49 MB (변화: +0.00 MB)
[CXP]   [Theta] 완료  첫값=6.35e+07 (메모리: 1584.5 MB)
[CXP]   [DB] 93행 저장 완료
[PROGRESS] [ 213/500] ( 42.6%)  >>  LXU
[LXU]   45분기 | 2015-03-31 ~ 2026-03-31
[LXU]   [SARIMA] 시작  (메모리: 1584.5 MB)
[메모리] forecast_sarima 실행 전: 1584.49 MB
[메모리] find_best_sarima_params 실행 전: 1584.49 MB
[메모리] find_best_sarima_params 실행 후: 1584.49 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1584.49 MB (변화: +0.00 MB)
[LXU]   [SARIMA] 완료  첫값=1.60e+08 (메모리: 1584.5 MB)
[LXU]   [ETS] 시작  (메모리: 1584.5 MB)
[메모리] forecast_ets 실행 전: 1584.49 MB
[메모리] forecast_ets 실행 후: 1584.49 MB (변화: +0.00 MB)
[LXU]   [ETS] 완료  첫값=1.66e+08 (메모리: 1584.5 MB)
[LXU]   [Prophet] 시작  (메모리: 1584.5 MB)

01:34:13 - cmdstanpy - INFO - Chain [1] start processing
01:34:13 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1584.49 MB
[메모리] forecast_prophet 실행 후: 1584.51 MB (변화: +0.02 MB)
[LXU]   [Prophet] 완료  첫값=1.53e+08 (메모리: 1584.5 MB)
[LXU]   [LSTM] 시작  (메모리: 1584.5 MB)
[메모리] forecast_lstm 실행 전: 1584.51 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1584.46 MB (변화: -0.05 MB)
[LXU]   [LSTM] 완료  첫값=1.30e+08 (메모리: 1584.5 MB)
[LXU]   [Theta] 시작  (메모리: 1584.5 MB)
[메모리] forecast_theta 실행 전: 1584.46 MB
[메모리] forecast_theta 실행 후: 1584.46 MB (변화: +0.00 MB)
[LXU]   [Theta] 완료  첫값=1.69e+08 (메모리: 1584.5 MB)
[LXU]   [DB] 93행 저장 완료
[PROGRESS] [ 214/500] ( 42.8%)  >>  VOLT
[VOLT]   45분기 | 2015-03-31 ~ 2026-03-31
[VOLT]   [SARIMA] 시작  (메모리: 1584.5 MB)
[메모리] forecast_sarima 실행 전: 1584.46 MB
[메모리] find_best_sarima_params 실행 전: 1584.46 MB
[메모리] find_best_sarima_params 실행 후: 1584.46 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1584.46 MB (변화: +0.00 MB)
[VOLT]   [SARIMA] 완료  첫값=2.24e+08 (메모리: 1584.5 MB)
[VOLT]   [ETS] 시작  (메모리: 1584.5 MB)
[메모리] forecast_ets 실행 전: 1584.46 MB
[메모리] forecast_ets 실행 후: 1584.46 MB (변화: +0.00 MB)
[VOLT]   [ETS] 완료  첫값=2.26e+08 (메모리: 1584.5 MB)
[VOLT]   [Prophet] 시작  (메모리: 1584.5 MB)

01:34:36 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1584.46 MB

01:34:37 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1584.50 MB (변화: +0.04 MB)
[VOLT]   [Prophet] 완료  첫값=2.31e+08 (메모리: 1584.5 MB)
[VOLT]   [LSTM] 시작  (메모리: 1584.5 MB)
[메모리] forecast_lstm 실행 전: 1584.50 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1584.48 MB (변화: -0.02 MB)
[VOLT]   [LSTM] 완료  첫값=2.26e+08 (메모리: 1584.5 MB)
[VOLT]   [Theta] 시작  (메모리: 1584.5 MB)
[메모리] forecast_theta 실행 전: 1584.48 MB
[메모리] forecast_theta 실행 후: 1584.48 MB (변화: +0.00 MB)
[VOLT]   [Theta] 완료  첫값=2.28e+08 (메모리: 1584.5 MB)
[VOLT]   [DB] 93행 저장 완료
[PROGRESS] [ 215/500] ( 43.0%)  >>  MATV
[MATV]   45분기 | 2015-03-31 ~ 2026-03-31
[MATV]   [SARIMA] 시작  (메모리: 1584.5 MB)
[메모리] forecast_sarima 실행 전: 1584.48 MB
[메모리] find_best_sarima_params 실행 전: 1584.48 MB
[메모리] find_best_sarima_params 실행 후: 1584.48 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1584.48 MB (변화: +0.00 MB)
[MATV]   [SARIMA] 완료  첫값=5.26e+08 (메모리: 1584.5 MB)
[MATV]   [ETS] 시작  (메모리: 1584.5 MB)
[메모리] forecast_ets 실행 전: 1584.48 MB
[메모리] forecast_ets 실행 후: 1584.48 MB (변화: +0.00 MB)
[MATV]   [ETS] 완료  첫값=5.39e+08 (메모리: 1584.5 MB)
[MATV]   [Prophet] 시작  (메모리: 1584.5 MB)

01:34:56 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1584.48 MB

01:34:57 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1584.89 MB (변화: +0.41 MB)
[MATV]   [Prophet] 완료  첫값=5.62e+08 (메모리: 1584.9 MB)
[MATV]   [LSTM] 시작  (메모리: 1584.9 MB)
[메모리] forecast_lstm 실행 전: 1584.89 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1584.86 MB (변화: -0.03 MB)
[MATV]   [LSTM] 완료  첫값=5.11e+08 (메모리: 1584.9 MB)
[MATV]   [Theta] 시작  (메모리: 1584.9 MB)
[메모리] forecast_theta 실행 전: 1584.86 MB
[메모리] forecast_theta 실행 후: 1584.86 MB (변화: +0.00 MB)
[MATV]   [Theta] 완료  첫값=5.38e+08 (메모리: 1584.9 MB)
[MATV]   [DB] 93행 저장 완료
[PROGRESS] [ 216/500] ( 43.2%)  >>  VTLE
[VTLE]   45분기 | 2015-03-31 ~ 2026-03-31
[VTLE]   [SARIMA] 시작  (메모리: 1584.9 MB)
[메모리] forecast_sarima 실행 전: 1584.86 MB
[메모리] find_best_sarima_params 실행 전: 1584.86 MB
[메모리] find_best_sarima_params 실행 후: 1584.86 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1584.86 MB (변화: +0.00 MB)
[VTLE]   [SARIMA] 완료  첫값=4.21e+08 (메모리: 1584.9 MB)
[VTLE]   [ETS] 시작  (메모리: 1584.9 MB)
[메모리] forecast_ets 실행 전: 1584.86 MB
[메모리] forecast_ets 실행 후: 1584.86 MB (변화: +0.00 MB)
[VTLE]   [ETS] 완료  첫값=4.31e+08 (메모리: 1584.9 MB)
[VTLE]   [Prophet] 시작  (메모리: 1584.9 MB)

01:35:20 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1584.86 MB

01:35:20 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1584.87 MB (변화: +0.01 MB)
[VTLE]   [Prophet] 완료  첫값=5.03e+08 (메모리: 1584.9 MB)
[VTLE]   [LSTM] 시작  (메모리: 1584.9 MB)
[메모리] forecast_lstm 실행 전: 1584.87 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1584.88 MB (변화: +0.01 MB)
[VTLE]   [LSTM] 완료  첫값=4.33e+08 (메모리: 1584.9 MB)
[VTLE]   [Theta] 시작  (메모리: 1584.9 MB)
[메모리] forecast_theta 실행 전: 1584.88 MB
[메모리] forecast_theta 실행 후: 1584.88 MB (변화: +0.00 MB)
[VTLE]   [Theta] 완료  첫값=4.18e+08 (메모리: 1584.9 MB)
[VTLE]   [DB] 93행 저장 완료
[PROGRESS] [ 217/500] ( 43.4%)  >>  RUTH
[RUTH]   45분기 | 2015-03-31 ~ 2026-03-31
[RUTH]   [SARIMA] 시작  (메모리: 1584.9 MB)
[메모리] forecast_sarima 실행 전: 1584.88 MB
[메모리] find_best_sarima_params 실행 전: 1584.88 MB
[메모리] find_best_sarima_params 실행 후: 1584.88 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1584.88 MB (변화: +0.00 MB)
[RUTH]   [SARIMA] 완료  첫값=1.36e+08 (메모리: 1584.9 MB)
[RUTH]   [ETS] 시작  (메모리: 1584.9 MB)
[메모리] forecast_ets 실행 전: 1584.88 MB
[메모리] forecast_ets 실행 후: 1584.89 MB (변화: +0.00 MB)
[RUTH]   [ETS] 완료  첫값=1.23e+08 (메모리: 1584.9 MB)
[RUTH]   [Prophet] 시작  (메모리: 1584.9 MB)

01:35:38 - cmdstanpy - INFO - Chain [1] start processing
01:35:38 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1584.89 MB
[메모리] forecast_prophet 실행 후: 1584.89 MB (변화: +0.00 MB)
[RUTH]   [Prophet] 완료  첫값=1.39e+08 (메모리: 1584.9 MB)
[RUTH]   [LSTM] 시작  (메모리: 1584.9 MB)
[메모리] forecast_lstm 실행 전: 1584.89 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1584.92 MB (변화: +0.03 MB)
[RUTH]   [LSTM] 완료  첫값=1.48e+08 (메모리: 1584.9 MB)
[RUTH]   [Theta] 시작  (메모리: 1584.9 MB)
[메모리] forecast_theta 실행 전: 1584.92 MB
[메모리] forecast_theta 실행 후: 1584.92 MB (변화: +0.00 MB)
[RUTH]   [Theta] 완료  첫값=1.38e+08 (메모리: 1584.9 MB)
[RUTH]   [DB] 93행 저장 완료
[PROGRESS] [ 218/500] ( 43.6%)  >>  LYTS
[LYTS]   45분기 | 2015-03-31 ~ 2026-03-31
[LYTS]   [SARIMA] 시작  (메모리: 1584.9 MB)
[메모리] forecast_sarima 실행 전: 1584.92 MB
[메모리] find_best_sarima_params 실행 전: 1584.92 MB
[메모리] find_best_sarima_params 실행 후: 1584.92 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1584.92 MB (변화: +0.00 MB)
[LYTS]   [SARIMA] 완료  첫값=1.58e+08 (메모리: 1584.9 MB)
[LYTS]   [ETS] 시작  (메모리: 1584.9 MB)
[메모리] forecast_ets 실행 전: 1584.92 MB
[메모리] forecast_ets 실행 후: 1584.92 MB (변화: +0.00 MB)
[LYTS]   [ETS] 완료  첫값=1.64e+08 (메모리: 1584.9 MB)
[LYTS]   [Prophet] 시작  (메모리: 1584.9 MB)

01:36:00 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1584.92 MB

01:36:00 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1584.93 MB (변화: +0.02 MB)
[LYTS]   [Prophet] 완료  첫값=1.51e+08 (메모리: 1584.9 MB)
[LYTS]   [LSTM] 시작  (메모리: 1584.9 MB)
[메모리] forecast_lstm 실행 전: 1584.93 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1585.01 MB (변화: +0.07 MB)
[LYTS]   [LSTM] 완료  첫값=1.41e+08 (메모리: 1585.0 MB)
[LYTS]   [Theta] 시작  (메모리: 1585.0 MB)
[메모리] forecast_theta 실행 전: 1585.01 MB
[메모리] forecast_theta 실행 후: 1585.01 MB (변화: +0.00 MB)
[LYTS]   [Theta] 완료  첫값=1.63e+08 (메모리: 1585.0 MB)
[LYTS]   [DB] 93행 저장 완료
[PROGRESS] [ 219/500] ( 43.8%)  >>  SSTK
[SSTK]   45분기 | 2015-03-31 ~ 2026-03-31
[SSTK]   [SARIMA] 시작  (메모리: 1585.0 MB)
[메모리] forecast_sarima 실행 전: 1585.01 MB
[메모리] find_best_sarima_params 실행 전: 1585.01 MB
[메모리] find_best_sarima_params 실행 후: 1585.01 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1585.01 MB (변화: +0.00 MB)
[SSTK]   [SARIMA] 완료  첫값=2.69e+08 (메모리: 1585.0 MB)
[SSTK]   [ETS] 시작  (메모리: 1585.0 MB)
[메모리] forecast_ets 실행 전: 1585.01 MB
[메모리] forecast_ets 실행 후: 1585.01 MB (변화: +0.00 MB)
[SSTK]   [ETS] 완료  첫값=2.69e+08 (메모리: 1585.0 MB)
[SSTK]   [Prophet] 시작  (메모리: 1585.0 MB)

01:36:23 - cmdstanpy - INFO - Chain [1] start processing
01:36:23 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1585.01 MB
[메모리] forecast_prophet 실행 후: 1585.01 MB (변화: +0.00 MB)
[SSTK]   [Prophet] 완료  첫값=2.65e+08 (메모리: 1585.0 MB)
[SSTK]   [LSTM] 시작  (메모리: 1585.0 MB)
[메모리] forecast_lstm 실행 전: 1585.01 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1584.98 MB (변화: -0.03 MB)
[SSTK]   [LSTM] 완료  첫값=2.73e+08 (메모리: 1585.0 MB)
[SSTK]   [Theta] 시작  (메모리: 1585.0 MB)
[메모리] forecast_theta 실행 전: 1584.98 MB
[메모리] forecast_theta 실행 후: 1584.98 MB (변화: +0.00 MB)
[SSTK]   [Theta] 완료  첫값=2.64e+08 (메모리: 1585.0 MB)
[SSTK]   [DB] 93행 저장 완료
[PROGRESS] [ 220/500] ( 44.0%)  >>  ATHM
[ATHM]   45분기 | 2015-03-31 ~ 2026-03-31
[ATHM]   [SARIMA] 시작  (메모리: 1585.0 MB)
[메모리] forecast_sarima 실행 전: 1584.98 MB
[메모리] find_best_sarima_params 실행 전: 1584.98 MB
[메모리] find_best_sarima_params 실행 후: 1584.98 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1584.98 MB (변화: +0.00 MB)
[ATHM]   [SARIMA] 완료  첫값=2.05e+09 (메모리: 1585.0 MB)
[ATHM]   [ETS] 시작  (메모리: 1585.0 MB)
[메모리] forecast_ets 실행 전: 1584.98 MB
[메모리] forecast_ets 실행 후: 1584.98 MB (변화: +0.00 MB)
[ATHM]   [ETS] 완료  첫값=2.07e+09 (메모리: 1585.0 MB)
[ATHM]   [Prophet] 시작  (메모리: 1585.0 MB)

01:36:46 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1584.98 MB

01:36:46 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1585.80 MB (변화: +0.81 MB)
[ATHM]   [Prophet] 완료  첫값=2.00e+09 (메모리: 1585.8 MB)
[ATHM]   [LSTM] 시작  (메모리: 1585.8 MB)
[메모리] forecast_lstm 실행 전: 1585.80 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1585.76 MB (변화: -0.04 MB)
[ATHM]   [LSTM] 완료  첫값=1.74e+09 (메모리: 1585.8 MB)
[ATHM]   [Theta] 시작  (메모리: 1585.8 MB)
[메모리] forecast_theta 실행 전: 1585.76 MB
[메모리] forecast_theta 실행 후: 1585.76 MB (변화: +0.00 MB)
[ATHM]   [Theta] 완료  첫값=2.17e+09 (메모리: 1585.8 MB)
[ATHM]   [DB] 93행 저장 완료
[PROGRESS] [ 221/500] ( 44.2%)  >>  TATT
[TATT]   45분기 | 2015-03-31 ~ 2026-03-31
[TATT]   [SARIMA] 시작  (메모리: 1585.8 MB)
[메모리] forecast_sarima 실행 전: 1585.76 MB
[메모리] find_best_sarima_params 실행 전: 1585.76 MB
[메모리] find_best_sarima_params 실행 후: 1585.76 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1585.76 MB (변화: +0.00 MB)
[TATT]   [SARIMA] 완료  첫값=4.71e+07 (메모리: 1585.8 MB)
[TATT]   [ETS] 시작  (메모리: 1585.8 MB)
[메모리] forecast_ets 실행 전: 1585.76 MB
[메모리] forecast_ets 실행 후: 1585.76 MB (변화: +0.00 MB)
[TATT]   [ETS] 완료  첫값=4.69e+07 (메모리: 1585.8 MB)
[TATT]   [Prophet] 시작  (메모리: 1585.8 MB)

01:37:05 - cmdstanpy - INFO - Chain [1] start processing
01:37:05 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1585.76 MB
[메모리] forecast_prophet 실행 후: 1585.05 MB (변화: -0.71 MB)
[TATT]   [Prophet] 완료  첫값=3.64e+07 (메모리: 1585.1 MB)
[TATT]   [LSTM] 시작  (메모리: 1585.1 MB)
[메모리] forecast_lstm 실행 전: 1585.05 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.03 MB (변화: +0.98 MB)
[TATT]   [LSTM] 완료  첫값=4.96e+07 (메모리: 1586.0 MB)
[TATT]   [Theta] 시작  (메모리: 1586.0 MB)
[메모리] forecast_theta 실행 전: 1586.03 MB
[메모리] forecast_theta 실행 후: 1586.03 MB (변화: +0.00 MB)
[TATT]   [Theta] 완료  첫값=4.62e+07 (메모리: 1586.0 MB)
[TATT]   [DB] 93행 저장 완료
[PROGRESS] [ 222/500] ( 44.4%)  >>  CSV
[CSV]   45분기 | 2015-03-31 ~ 2026-03-31
[CSV]   [SARIMA] 시작  (메모리: 1586.0 MB)
[메모리] forecast_sarima 실행 전: 1586.03 MB
[메모리] find_best_sarima_params 실행 전: 1586.03 MB
[메모리] find_best_sarima_params 실행 후: 1586.03 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.03 MB (변화: +0.00 MB)
[CSV]   [SARIMA] 완료  첫값=1.01e+08 (메모리: 1586.0 MB)
[CSV]   [ETS] 시작  (메모리: 1586.0 MB)
[메모리] forecast_ets 실행 전: 1586.03 MB
[메모리] forecast_ets 실행 후: 1586.03 MB (변화: +0.00 MB)
[CSV]   [ETS] 완료  첫값=9.93e+07 (메모리: 1586.0 MB)
[CSV]   [Prophet] 시작  (메모리: 1586.0 MB)

01:37:32 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1586.03 MB

01:37:32 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1586.69 MB (변화: +0.66 MB)
[CSV]   [Prophet] 완료  첫값=1.09e+08 (메모리: 1586.7 MB)
[CSV]   [LSTM] 시작  (메모리: 1586.7 MB)
[메모리] forecast_lstm 실행 전: 1586.69 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.82 MB (변화: +0.13 MB)
[CSV]   [LSTM] 완료  첫값=1.05e+08 (메모리: 1586.8 MB)
[CSV]   [Theta] 시작  (메모리: 1586.8 MB)
[메모리] forecast_theta 실행 전: 1586.82 MB
[메모리] forecast_theta 실행 후: 1586.82 MB (변화: +0.00 MB)
[CSV]   [Theta] 완료  첫값=9.80e+07 (메모리: 1586.8 MB)
[CSV]   [DB] 93행 저장 완료
[PROGRESS] [ 223/500] ( 44.6%)  >>  URG
[URG]   45분기 | 2015-03-31 ~ 2026-03-31
[URG]   [SARIMA] 시작  (메모리: 1586.8 MB)
[메모리] forecast_sarima 실행 전: 1586.82 MB
[메모리] find_best_sarima_params 실행 전: 1586.82 MB
[메모리] find_best_sarima_params 실행 후: 1586.82 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.82 MB (변화: +0.00 MB)
[URG]   [SARIMA] 완료  첫값=7.51e+06 (메모리: 1586.8 MB)
[URG]   [ETS] 시작  (메모리: 1586.8 MB)
[메모리] forecast_ets 실행 전: 1586.82 MB
[메모리] forecast_ets 실행 후: 1586.82 MB (변화: +0.00 MB)
[URG]   [ETS] 완료  첫값=8.33e+06 (메모리: 1586.8 MB)
[URG]   [Prophet] 시작  (메모리: 1586.8 MB)

01:37:50 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1586.82 MB

01:37:50 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1586.83 MB (변화: +0.02 MB)
[URG]   [Prophet] 완료  첫값=3.09e+06 (메모리: 1586.8 MB)
[URG]   [LSTM] 시작  (메모리: 1586.8 MB)
[메모리] forecast_lstm 실행 전: 1586.83 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.86 MB (변화: +0.03 MB)
[URG]   [LSTM] 완료  첫값=4.89e+06 (메모리: 1586.9 MB)
[URG]   [Theta] 시작  (메모리: 1586.9 MB)
[메모리] forecast_theta 실행 전: 1586.86 MB
[메모리] forecast_theta 실행 후: 1586.86 MB (변화: +0.00 MB)
[URG]   [Theta] 완료  첫값=6.23e+06 (메모리: 1586.9 MB)
[URG]   [DB] 93행 저장 완료
[PROGRESS] [ 224/500] ( 44.8%)  >>  RIGL
[RIGL]   45분기 | 2015-03-31 ~ 2026-03-31
[RIGL]   [SARIMA] 시작  (메모리: 1586.9 MB)
[메모리] forecast_sarima 실행 전: 1586.86 MB
[메모리] find_best_sarima_params 실행 전: 1586.86 MB
[메모리] find_best_sarima_params 실행 후: 1586.86 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.86 MB (변화: +0.00 MB)
[RIGL]   [SARIMA] 완료  첫값=7.37e+07 (메모리: 1586.9 MB)
[RIGL]   [ETS] 시작  (메모리: 1586.9 MB)
[메모리] forecast_ets 실행 전: 1586.86 MB
[메모리] forecast_ets 실행 후: 1586.86 MB (변화: +0.00 MB)
[RIGL]   [ETS] 완료  첫값=7.32e+07 (메모리: 1586.9 MB)
[RIGL]   [Prophet] 시작  (메모리: 1586.9 MB)

01:38:07 - cmdstanpy - INFO - Chain [1] start processing
01:38:07 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1586.86 MB
[메모리] forecast_prophet 실행 후: 1586.88 MB (변화: +0.02 MB)
[RIGL]   [Prophet] 완료  첫값=6.04e+07 (메모리: 1586.9 MB)
[RIGL]   [LSTM] 시작  (메모리: 1586.9 MB)
[메모리] forecast_lstm 실행 전: 1586.88 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.88 MB (변화: -0.00 MB)
[RIGL]   [LSTM] 완료  첫값=6.81e+07 (메모리: 1586.9 MB)
[RIGL]   [Theta] 시작  (메모리: 1586.9 MB)
[메모리] forecast_theta 실행 전: 1586.88 MB
[메모리] forecast_theta 실행 후: 1586.88 MB (변화: +0.00 MB)
[RIGL]   [Theta] 완료  첫값=6.93e+07 (메모리: 1586.9 MB)
[RIGL]   [DB] 93행 저장 완료
[PROGRESS] [ 225/500] ( 45.0%)  >>  SXC
[SXC]   45분기 | 2015-03-31 ~ 2026-03-31
[SXC]   [SARIMA] 시작  (메모리: 1586.9 MB)
[메모리] forecast_sarima 실행 전: 1586.88 MB
[메모리] find_best_sarima_params 실행 전: 1586.88 MB
[메모리] find_best_sarima_params 실행 후: 1586.88 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.88 MB (변화: +0.00 MB)
[SXC]   [SARIMA] 완료  첫값=4.92e+08 (메모리: 1586.9 MB)
[SXC]   [ETS] 시작  (메모리: 1586.9 MB)
[메모리] forecast_ets 실행 전: 1586.88 MB
[메모리] forecast_ets 실행 후: 1586.89 MB (변화: +0.01 MB)
[SXC]   [ETS] 완료  첫값=4.97e+08 (메모리: 1586.9 MB)
[SXC]   [Prophet] 시작  (메모리: 1586.9 MB)

01:38:32 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1586.89 MB

01:38:33 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1586.91 MB (변화: +0.02 MB)
[SXC]   [Prophet] 완료  첫값=5.09e+08 (메모리: 1586.9 MB)
[SXC]   [LSTM] 시작  (메모리: 1586.9 MB)
[메모리] forecast_lstm 실행 전: 1586.91 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.89 MB (변화: -0.02 MB)
[SXC]   [LSTM] 완료  첫값=4.63e+08 (메모리: 1586.9 MB)
[SXC]   [Theta] 시작  (메모리: 1586.9 MB)
[메모리] forecast_theta 실행 전: 1586.89 MB
[메모리] forecast_theta 실행 후: 1586.89 MB (변화: +0.00 MB)
[SXC]   [Theta] 완료  첫값=4.92e+08 (메모리: 1586.9 MB)
[SXC]   [DB] 93행 저장 완료
[PROGRESS] [ 226/500] ( 45.2%)  >>  STAR
[STAR]   45분기 | 2015-03-31 ~ 2026-03-31
[STAR]   [SARIMA] 시작  (메모리: 1586.9 MB)
[메모리] forecast_sarima 실행 전: 1586.89 MB
[메모리] find_best_sarima_params 실행 전: 1586.89 MB
[메모리] find_best_sarima_params 실행 후: 1586.89 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.89 MB (변화: +0.00 MB)
[STAR]   [SARIMA] 완료  첫값=1.03e+08 (메모리: 1586.9 MB)
[STAR]   [ETS] 시작  (메모리: 1586.9 MB)
[메모리] forecast_ets 실행 전: 1586.89 MB
[메모리] forecast_ets 실행 후: 1586.89 MB (변화: +0.00 MB)
[STAR]   [ETS] 완료  첫값=1.28e+08 (메모리: 1586.9 MB)
[STAR]   [Prophet] 시작  (메모리: 1586.9 MB)

01:38:54 - cmdstanpy - INFO - Chain [1] start processing
01:38:54 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1586.89 MB
[메모리] forecast_prophet 실행 후: 1586.92 MB (변화: +0.02 MB)
[STAR]   [Prophet] 완료  첫값=6.84e+07 (메모리: 1586.9 MB)
[STAR]   [LSTM] 시작  (메모리: 1586.9 MB)
[메모리] forecast_lstm 실행 전: 1586.92 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.91 MB (변화: -0.01 MB)
[STAR]   [LSTM] 완료  첫값=6.62e+07 (메모리: 1586.9 MB)
[STAR]   [Theta] 시작  (메모리: 1586.9 MB)
[메모리] forecast_theta 실행 전: 1586.91 MB
[메모리] forecast_theta 실행 후: 1586.91 MB (변화: +0.00 MB)
[STAR]   [Theta] 완료  첫값=8.79e+07 (메모리: 1586.9 MB)
[STAR]   [DB] 93행 저장 완료
[PROGRESS] [ 227/500] ( 45.4%)  >>  ESPR
[ESPR]   45분기 | 2015-03-31 ~ 2026-03-31
[ESPR]   [SARIMA] 시작  (메모리: 1586.9 MB)
[메모리] forecast_sarima 실행 전: 1586.91 MB
[메모리] find_best_sarima_params 실행 전: 1586.91 MB
[메모리] find_best_sarima_params 실행 후: 1586.91 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.91 MB (변화: +0.00 MB)
[ESPR]   [SARIMA] 완료  첫값=6.86e+07 (메모리: 1586.9 MB)
[ESPR]   [ETS] 시작  (메모리: 1586.9 MB)
[메모리] forecast_ets 실행 전: 1586.91 MB
[메모리] forecast_ets 실행 후: 1586.91 MB (변화: +0.00 MB)
[ESPR]   [ETS] 완료  첫값=6.71e+07 (메모리: 1586.9 MB)
[ESPR]   [Prophet] 시작  (메모리: 1586.9 MB)

01:39:10 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1586.91 MB

01:39:10 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1586.92 MB (변화: +0.02 MB)
[ESPR]   [Prophet] 완료  첫값=7.46e+07 (메모리: 1586.9 MB)
[ESPR]   [LSTM] 시작  (메모리: 1586.9 MB)
[메모리] forecast_lstm 실행 전: 1586.92 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.91 MB (변화: -0.01 MB)
[ESPR]   [LSTM] 완료  첫값=5.30e+07 (메모리: 1586.9 MB)
[ESPR]   [Theta] 시작  (메모리: 1586.9 MB)
[메모리] forecast_theta 실행 전: 1586.91 MB
[메모리] forecast_theta 실행 후: 1586.91 MB (변화: +0.00 MB)
[ESPR]   [Theta] 완료  첫값=7.64e+07 (메모리: 1586.9 MB)
[ESPR]   [DB] 93행 저장 완료
[PROGRESS] [ 228/500] ( 45.6%)  >>  AOSL
[AOSL]   45분기 | 2015-03-31 ~ 2026-03-31
[AOSL]   [SARIMA] 시작  (메모리: 1586.9 MB)
[메모리] forecast_sarima 실행 전: 1586.91 MB
[메모리] find_best_sarima_params 실행 전: 1586.91 MB
[메모리] find_best_sarima_params 실행 후: 1586.91 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.91 MB (변화: +0.00 MB)
[AOSL]   [SARIMA] 완료  첫값=1.65e+08 (메모리: 1586.9 MB)
[AOSL]   [ETS] 시작  (메모리: 1586.9 MB)
[메모리] forecast_ets 실행 전: 1586.91 MB
[메모리] forecast_ets 실행 후: 1586.91 MB (변화: +0.00 MB)
[AOSL]   [ETS] 완료  첫값=1.74e+08 (메모리: 1586.9 MB)
[AOSL]   [Prophet] 시작  (메모리: 1586.9 MB)

01:39:30 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1586.91 MB

01:39:30 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1586.93 MB (변화: +0.02 MB)
[AOSL]   [Prophet] 완료  첫값=1.98e+08 (메모리: 1586.9 MB)
[AOSL]   [LSTM] 시작  (메모리: 1586.9 MB)
[메모리] forecast_lstm 실행 전: 1586.93 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.97 MB (변화: +0.04 MB)
[AOSL]   [LSTM] 완료  첫값=1.69e+08 (메모리: 1587.0 MB)
[AOSL]   [Theta] 시작  (메모리: 1587.0 MB)
[메모리] forecast_theta 실행 전: 1586.97 MB
[메모리] forecast_theta 실행 후: 1586.97 MB (변화: +0.00 MB)
[AOSL]   [Theta] 완료  첫값=1.73e+08 (메모리: 1587.0 MB)
[AOSL]   [DB] 93행 저장 완료
[PROGRESS] [ 229/500] ( 45.8%)  >>  PLAY
[PLAY]   45분기 | 2015-03-31 ~ 2026-03-31
[PLAY]   [SARIMA] 시작  (메모리: 1587.0 MB)
[메모리] forecast_sarima 실행 전: 1586.97 MB
[메모리] find_best_sarima_params 실행 전: 1586.97 MB
[메모리] find_best_sarima_params 실행 후: 1586.97 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.97 MB (변화: +0.00 MB)
[PLAY]   [SARIMA] 완료  첫값=4.48e+08 (메모리: 1587.0 MB)
[PLAY]   [ETS] 시작  (메모리: 1587.0 MB)
[메모리] forecast_ets 실행 전: 1586.97 MB
[메모리] forecast_ets 실행 후: 1586.98 MB (변화: +0.01 MB)
[PLAY]   [ETS] 완료  첫값=4.86e+08 (메모리: 1587.0 MB)
[PLAY]   [Prophet] 시작  (메모리: 1587.0 MB)
[메모리] forecast_prophet 실행 전: 1586.98 MB

01:39:51 - cmdstanpy - INFO - Chain [1] start processing
01:39:51 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1587.00 MB (변화: +0.02 MB)
[PLAY]   [Prophet] 완료  첫값=5.43e+08 (메모리: 1587.0 MB)
[PLAY]   [LSTM] 시작  (메모리: 1587.0 MB)
[메모리] forecast_lstm 실행 전: 1587.00 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.96 MB (변화: -0.03 MB)
[PLAY]   [LSTM] 완료  첫값=4.80e+08 (메모리: 1587.0 MB)
[PLAY]   [Theta] 시작  (메모리: 1587.0 MB)
[메모리] forecast_theta 실행 전: 1586.96 MB
[메모리] forecast_theta 실행 후: 1586.96 MB (변화: +0.00 MB)
[PLAY]   [Theta] 완료  첫값=4.53e+08 (메모리: 1587.0 MB)
[PLAY]   [DB] 93행 저장 완료
[PROGRESS] [ 230/500] ( 46.0%)  >>  GRPN
[GRPN]   45분기 | 2015-03-31 ~ 2026-03-31
[GRPN]   [SARIMA] 시작  (메모리: 1587.0 MB)
[메모리] forecast_sarima 실행 전: 1586.96 MB
[메모리] find_best_sarima_params 실행 전: 1586.96 MB
[메모리] find_best_sarima_params 실행 후: 1586.96 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.96 MB (변화: +0.00 MB)
[GRPN]   [SARIMA] 완료  첫값=1.30e+08 (메모리: 1587.0 MB)
[GRPN]   [ETS] 시작  (메모리: 1587.0 MB)
[메모리] forecast_ets 실행 전: 1586.96 MB
[메모리] forecast_ets 실행 후: 1586.96 MB (변화: +0.00 MB)
[GRPN]   [ETS] 완료  첫값=1.25e+08 (메모리: 1587.0 MB)
[GRPN]   [Prophet] 시작  (메모리: 1587.0 MB)

01:40:16 - cmdstanpy - INFO - Chain [1] start processing
01:40:16 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1586.96 MB
[메모리] forecast_prophet 실행 후: 1586.99 MB (변화: +0.02 MB)
[GRPN]   [Prophet] 완료  첫값=-4.01e+07 (메모리: 1587.0 MB)
[GRPN]   [LSTM] 시작  (메모리: 1587.0 MB)
[메모리] forecast_lstm 실행 전: 1586.99 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.99 MB (변화: +0.00 MB)
[GRPN]   [LSTM] 완료  첫값=1.32e+08 (메모리: 1587.0 MB)
[GRPN]   [Theta] 시작  (메모리: 1587.0 MB)
[메모리] forecast_theta 실행 전: 1586.99 MB
[메모리] forecast_theta 실행 후: 1586.99 MB (변화: +0.00 MB)
[GRPN]   [Theta] 완료  첫값=1.26e+08 (메모리: 1587.0 MB)
[GRPN]   [DB] 93행 저장 완료
[PROGRESS] [ 231/500] ( 46.2%)  >>  CVLG
[CVLG]   45분기 | 2015-03-31 ~ 2026-03-31
[CVLG]   [SARIMA] 시작  (메모리: 1587.0 MB)
[메모리] forecast_sarima 실행 전: 1586.99 MB
[메모리] find_best_sarima_params 실행 전: 1586.99 MB
[메모리] find_best_sarima_params 실행 후: 1586.99 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.99 MB (변화: +0.00 MB)
[CVLG]   [SARIMA] 완료  첫값=3.07e+08 (메모리: 1587.0 MB)
[CVLG]   [ETS] 시작  (메모리: 1587.0 MB)
[메모리] forecast_ets 실행 전: 1586.99 MB
[메모리] forecast_ets 실행 후: 1587.00 MB (변화: +0.01 MB)
[CVLG]   [ETS] 완료  첫값=3.13e+08 (메모리: 1587.0 MB)
[CVLG]   [Prophet] 시작  (메모리: 1587.0 MB)

01:40:39 - cmdstanpy - INFO - Chain [1] start processing
01:40:39 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1587.00 MB
[메모리] forecast_prophet 실행 후: 1587.01 MB (변화: +0.01 MB)
[CVLG]   [Prophet] 완료  첫값=3.16e+08 (메모리: 1587.0 MB)
[CVLG]   [LSTM] 시작  (메모리: 1587.0 MB)
[메모리] forecast_lstm 실행 전: 1587.01 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1587.01 MB (변화: +0.00 MB)
[CVLG]   [LSTM] 완료  첫값=2.93e+08 (메모리: 1587.0 MB)
[CVLG]   [Theta] 시작  (메모리: 1587.0 MB)
[메모리] forecast_theta 실행 전: 1587.01 MB
[메모리] forecast_theta 실행 후: 1587.01 MB (변화: +0.00 MB)
[CVLG]   [Theta] 완료  첫값=3.06e+08 (메모리: 1587.0 MB)
[CVLG]   [DB] 93행 저장 완료
[PROGRESS] [ 232/500] ( 46.4%)  >>  CBRL
[CBRL]   45분기 | 2015-03-31 ~ 2026-03-31
[CBRL]   [SARIMA] 시작  (메모리: 1587.0 MB)
[메모리] forecast_sarima 실행 전: 1587.01 MB
[메모리] find_best_sarima_params 실행 전: 1587.01 MB
[메모리] find_best_sarima_params 실행 후: 1587.01 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1587.01 MB (변화: +0.00 MB)
[CBRL]   [SARIMA] 완료  첫값=7.24e+08 (메모리: 1587.0 MB)
[CBRL]   [ETS] 시작  (메모리: 1587.0 MB)
[메모리] forecast_ets 실행 전: 1587.01 MB
[메모리] forecast_ets 실행 후: 1587.02 MB (변화: +0.00 MB)
[CBRL]   [ETS] 완료  첫값=7.06e+08 (메모리: 1587.0 MB)
[CBRL]   [Prophet] 시작  (메모리: 1587.0 MB)

01:40:59 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1587.02 MB

01:41:00 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1587.02 MB (변화: +0.00 MB)
[CBRL]   [Prophet] 완료  첫값=8.56e+08 (메모리: 1587.0 MB)
[CBRL]   [LSTM] 시작  (메모리: 1587.0 MB)
[메모리] forecast_lstm 실행 전: 1587.02 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.98 MB (변화: -0.04 MB)
[CBRL]   [LSTM] 완료  첫값=8.37e+08 (메모리: 1587.0 MB)
[CBRL]   [Theta] 시작  (메모리: 1587.0 MB)
[메모리] forecast_theta 실행 전: 1586.98 MB
[메모리] forecast_theta 실행 후: 1586.98 MB (변화: +0.00 MB)
[CBRL]   [Theta] 완료  첫값=8.19e+08 (메모리: 1587.0 MB)
[CBRL]   [DB] 93행 저장 완료
[PROGRESS] [ 233/500] ( 46.6%)  >>  HSTM
[HSTM]   45분기 | 2015-03-31 ~ 2026-03-31
[HSTM]   [SARIMA] 시작  (메모리: 1587.0 MB)
[메모리] forecast_sarima 실행 전: 1586.98 MB
[메모리] find_best_sarima_params 실행 전: 1586.98 MB
[메모리] find_best_sarima_params 실행 후: 1586.98 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.98 MB (변화: +0.00 MB)
[HSTM]   [SARIMA] 완료  첫값=7.69e+07 (메모리: 1587.0 MB)
[HSTM]   [ETS] 시작  (메모리: 1587.0 MB)
[메모리] forecast_ets 실행 전: 1586.98 MB
[메모리] forecast_ets 실행 후: 1586.98 MB (변화: +0.00 MB)
[HSTM]   [ETS] 완료  첫값=7.76e+07 (메모리: 1587.0 MB)
[HSTM]   [Prophet] 시작  (메모리: 1587.0 MB)

01:41:20 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1586.98 MB

01:41:21 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1586.99 MB (변화: +0.01 MB)
[HSTM]   [Prophet] 완료  첫값=7.68e+07 (메모리: 1587.0 MB)
[HSTM]   [LSTM] 시작  (메모리: 1587.0 MB)
[메모리] forecast_lstm 실행 전: 1586.99 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1587.04 MB (변화: +0.05 MB)
[HSTM]   [LSTM] 완료  첫값=8.29e+07 (메모리: 1587.0 MB)
[HSTM]   [Theta] 시작  (메모리: 1587.0 MB)
[메모리] forecast_theta 실행 전: 1587.04 MB
[메모리] forecast_theta 실행 후: 1587.04 MB (변화: +0.00 MB)
[HSTM]   [Theta] 완료  첫값=7.66e+07 (메모리: 1587.0 MB)
[HSTM]   [DB] 93행 저장 완료
[PROGRESS] [ 234/500] ( 46.8%)  >>  CHUY
[CHUY]   45분기 | 2015-03-31 ~ 2026-03-31
[CHUY]   [SARIMA] 시작  (메모리: 1587.0 MB)
[메모리] forecast_sarima 실행 전: 1587.04 MB
[메모리] find_best_sarima_params 실행 전: 1587.04 MB
[메모리] find_best_sarima_params 실행 후: 1587.04 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1587.04 MB (변화: +0.00 MB)
[CHUY]   [SARIMA] 완료  첫값=1.21e+08 (메모리: 1587.0 MB)
[CHUY]   [ETS] 시작  (메모리: 1587.0 MB)
[메모리] forecast_ets 실행 전: 1587.04 MB
[메모리] forecast_ets 실행 후: 1587.04 MB (변화: +0.00 MB)
[CHUY]   [ETS] 완료  첫값=1.26e+08 (메모리: 1587.0 MB)
[CHUY]   [Prophet] 시작  (메모리: 1587.0 MB)

01:41:39 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1587.04 MB

01:41:39 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1587.05 MB (변화: +0.01 MB)
[CHUY]   [Prophet] 완료  첫값=1.23e+08 (메모리: 1587.1 MB)
[CHUY]   [LSTM] 시작  (메모리: 1587.1 MB)
[메모리] forecast_lstm 실행 전: 1587.05 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1587.04 MB (변화: -0.02 MB)
[CHUY]   [LSTM] 완료  첫값=1.37e+08 (메모리: 1587.0 MB)
[CHUY]   [Theta] 시작  (메모리: 1587.0 MB)
[메모리] forecast_theta 실행 전: 1587.04 MB
[메모리] forecast_theta 실행 후: 1587.04 MB (변화: +0.00 MB)
[CHUY]   [Theta] 완료  첫값=1.24e+08 (메모리: 1587.0 MB)
[CHUY]   [DB] 93행 저장 완료
[PROGRESS] [ 235/500] ( 47.0%)  >>  NWPX
[NWPX]   45분기 | 2015-03-31 ~ 2026-03-31
[NWPX]   [SARIMA] 시작  (메모리: 1587.0 MB)
[메모리] forecast_sarima 실행 전: 1587.04 MB
[메모리] find_best_sarima_params 실행 전: 1587.04 MB
[메모리] find_best_sarima_params 실행 후: 1587.04 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1587.04 MB (변화: +0.00 MB)
[NWPX]   [SARIMA] 완료  첫값=1.60e+08 (메모리: 1587.0 MB)
[NWPX]   [ETS] 시작  (메모리: 1587.0 MB)
[메모리] forecast_ets 실행 전: 1587.04 MB
[메모리] forecast_ets 실행 후: 1587.04 MB (변화: +0.00 MB)
[NWPX]   [ETS] 완료  첫값=1.60e+08 (메모리: 1587.0 MB)
[NWPX]   [Prophet] 시작  (메모리: 1587.0 MB)

01:41:58 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1587.04 MB

01:41:58 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1587.04 MB (변화: +0.01 MB)
[NWPX]   [Prophet] 완료  첫값=1.42e+08 (메모리: 1587.0 MB)
[NWPX]   [LSTM] 시작  (메모리: 1587.0 MB)
[메모리] forecast_lstm 실행 전: 1587.04 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1587.02 MB (변화: -0.02 MB)
[NWPX]   [LSTM] 완료  첫값=1.29e+08 (메모리: 1587.0 MB)
[NWPX]   [Theta] 시작  (메모리: 1587.0 MB)
[메모리] forecast_theta 실행 전: 1587.02 MB
[메모리] forecast_theta 실행 후: 1587.02 MB (변화: +0.00 MB)
[NWPX]   [Theta] 완료  첫값=1.60e+08 (메모리: 1587.0 MB)
[NWPX]   [DB] 93행 저장 완료
[PROGRESS] [ 236/500] ( 47.2%)  >>  IDR
[IDR]   45분기 | 2015-03-31 ~ 2026-03-31
[IDR]   [SARIMA] 시작  (메모리: 1587.0 MB)
[메모리] forecast_sarima 실행 전: 1587.02 MB
[메모리] find_best_sarima_params 실행 전: 1587.02 MB
[메모리] find_best_sarima_params 실행 후: 1587.02 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1587.02 MB (변화: +0.00 MB)
[IDR]   [SARIMA] 완료  첫값=1.20e+07 (메모리: 1587.0 MB)
[IDR]   [ETS] 시작  (메모리: 1587.0 MB)
[메모리] forecast_ets 실행 전: 1587.02 MB
[메모리] forecast_ets 실행 후: 1587.02 MB (변화: +0.00 MB)
[IDR]   [ETS] 완료  첫값=1.29e+07 (메모리: 1587.0 MB)
[IDR]   [Prophet] 시작  (메모리: 1587.0 MB)

01:42:15 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1587.02 MB

01:42:15 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1586.45 MB (변화: -0.58 MB)
[IDR]   [Prophet] 완료  첫값=7.44e+06 (메모리: 1586.4 MB)
[IDR]   [LSTM] 시작  (메모리: 1586.4 MB)
[메모리] forecast_lstm 실행 전: 1586.45 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.31 MB (변화: -0.14 MB)
[IDR]   [LSTM] 완료  첫값=1.46e+07 (메모리: 1586.3 MB)
[IDR]   [Theta] 시작  (메모리: 1586.3 MB)
[메모리] forecast_theta 실행 전: 1586.31 MB
[메모리] forecast_theta 실행 후: 1586.31 MB (변화: +0.00 MB)
[IDR]   [Theta] 완료  첫값=1.13e+07 (메모리: 1586.3 MB)
[IDR]   [DB] 93행 저장 완료
[PROGRESS] [ 237/500] ( 47.4%)  >>  NYMT
[NYMT]   45분기 | 2015-03-31 ~ 2026-03-31
[NYMT]   [SARIMA] 시작  (메모리: 1586.3 MB)
[메모리] forecast_sarima 실행 전: 1586.31 MB
[메모리] find_best_sarima_params 실행 전: 1586.31 MB
[메모리] find_best_sarima_params 실행 후: 1586.31 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.31 MB (변화: +0.00 MB)
[NYMT]   [SARIMA] 완료  첫값=9.24e+07 (메모리: 1586.3 MB)
[NYMT]   [ETS] 시작  (메모리: 1586.3 MB)
[메모리] forecast_ets 실행 전: 1586.31 MB
[메모리] forecast_ets 실행 후: 1586.31 MB (변화: +0.00 MB)
[NYMT]   [ETS] 완료  첫값=4.46e+07 (메모리: 1586.3 MB)
[NYMT]   [Prophet] 시작  (메모리: 1586.3 MB)

01:42:37 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1586.31 MB

01:42:37 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1587.95 MB (변화: +1.64 MB)
[NYMT]   [Prophet] 완료  첫값=5.81e+07 (메모리: 1587.9 MB)
[NYMT]   [LSTM] 시작  (메모리: 1587.9 MB)
[메모리] forecast_lstm 실행 전: 1587.95 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1587.14 MB (변화: -0.81 MB)
[NYMT]   [LSTM] 완료  첫값=2.33e+07 (메모리: 1587.1 MB)
[NYMT]   [Theta] 시작  (메모리: 1587.1 MB)
[메모리] forecast_theta 실행 전: 1587.14 MB
[메모리] forecast_theta 실행 후: 1587.14 MB (변화: +0.00 MB)
[NYMT]   [Theta] 완료  첫값=5.64e+07 (메모리: 1587.1 MB)
[NYMT]   [DB] 93행 저장 완료
[PROGRESS] [ 238/500] ( 47.6%)  >>  IIIN
[IIIN]   45분기 | 2015-03-31 ~ 2026-03-31
[IIIN]   [SARIMA] 시작  (메모리: 1587.1 MB)
[메모리] forecast_sarima 실행 전: 1587.14 MB
[메모리] find_best_sarima_params 실행 전: 1587.14 MB
[메모리] find_best_sarima_params 실행 후: 1587.14 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1587.14 MB (변화: +0.00 MB)
[IIIN]   [SARIMA] 완료  첫값=1.69e+08 (메모리: 1587.1 MB)
[IIIN]   [ETS] 시작  (메모리: 1587.1 MB)
[메모리] forecast_ets 실행 전: 1587.14 MB
[메모리] forecast_ets 실행 후: 1587.14 MB (변화: +0.00 MB)
[IIIN]   [ETS] 완료  첫값=1.79e+08 (메모리: 1587.1 MB)
[IIIN]   [Prophet] 시작  (메모리: 1587.1 MB)

01:42:57 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1587.14 MB

01:42:57 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1587.84 MB (변화: +0.70 MB)
[IIIN]   [Prophet] 완료  첫값=1.73e+08 (메모리: 1587.8 MB)
[IIIN]   [LSTM] 시작  (메모리: 1587.8 MB)
[메모리] forecast_lstm 실행 전: 1587.84 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1587.02 MB (변화: -0.82 MB)
[IIIN]   [LSTM] 완료  첫값=1.59e+08 (메모리: 1587.0 MB)
[IIIN]   [Theta] 시작  (메모리: 1587.0 MB)
[메모리] forecast_theta 실행 전: 1587.02 MB
[메모리] forecast_theta 실행 후: 1587.02 MB (변화: +0.00 MB)
[IIIN]   [Theta] 완료  첫값=1.78e+08 (메모리: 1587.0 MB)
[IIIN]   [DB] 93행 저장 완료
[PROGRESS] [ 239/500] ( 47.8%)  >>  EBS
[EBS]   45분기 | 2015-03-31 ~ 2026-03-31
[EBS]   [SARIMA] 시작  (메모리: 1587.0 MB)
[메모리] forecast_sarima 실행 전: 1587.02 MB
[메모리] find_best_sarima_params 실행 전: 1587.02 MB
[메모리] find_best_sarima_params 실행 후: 1587.02 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1587.02 MB (변화: +0.00 MB)
[EBS]   [SARIMA] 완료  첫값=2.30e+08 (메모리: 1587.0 MB)
[EBS]   [ETS] 시작  (메모리: 1587.0 MB)
[메모리] forecast_ets 실행 전: 1587.02 MB
[메모리] forecast_ets 실행 후: 1587.02 MB (변화: +0.00 MB)
[EBS]   [ETS] 완료  첫값=2.27e+08 (메모리: 1587.0 MB)
[EBS]   [Prophet] 시작  (메모리: 1587.0 MB)

01:43:21 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1587.02 MB

01:43:21 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1588.24 MB (변화: +1.22 MB)
[EBS]   [Prophet] 완료  첫값=3.32e+08 (메모리: 1588.2 MB)
[EBS]   [LSTM] 시작  (메모리: 1588.2 MB)
[메모리] forecast_lstm 실행 전: 1588.24 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1587.40 MB (변화: -0.84 MB)
[EBS]   [LSTM] 완료  첫값=2.58e+08 (메모리: 1587.4 MB)
[EBS]   [Theta] 시작  (메모리: 1587.4 MB)
[메모리] forecast_theta 실행 전: 1587.40 MB
[메모리] forecast_theta 실행 후: 1587.40 MB (변화: +0.00 MB)
[EBS]   [Theta] 완료  첫값=2.23e+08 (메모리: 1587.4 MB)
[EBS]   [DB] 93행 저장 완료
[PROGRESS] [ 240/500] ( 48.0%)  >>  KODK
[KODK]   45분기 | 2015-03-31 ~ 2026-03-31
[KODK]   [SARIMA] 시작  (메모리: 1587.4 MB)
[메모리] forecast_sarima 실행 전: 1587.40 MB
[메모리] find_best_sarima_params 실행 전: 1587.40 MB
[메모리] find_best_sarima_params 실행 후: 1587.40 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1587.40 MB (변화: +0.00 MB)
[KODK]   [SARIMA] 완료  첫값=2.60e+08 (메모리: 1587.4 MB)
[KODK]   [ETS] 시작  (메모리: 1587.4 MB)
[메모리] forecast_ets 실행 전: 1587.40 MB
[메모리] forecast_ets 실행 후: 1587.40 MB (변화: +0.00 MB)
[KODK]   [ETS] 완료  첫값=2.66e+08 (메모리: 1587.4 MB)
[KODK]   [Prophet] 시작  (메모리: 1587.4 MB)

01:43:40 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1587.40 MB

01:43:40 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1586.87 MB (변화: -0.53 MB)
[KODK]   [Prophet] 완료  첫값=2.50e+08 (메모리: 1586.9 MB)
[KODK]   [LSTM] 시작  (메모리: 1586.9 MB)
[메모리] forecast_lstm 실행 전: 1586.87 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1587.85 MB (변화: +0.98 MB)
[KODK]   [LSTM] 완료  첫값=2.62e+08 (메모리: 1587.8 MB)
[KODK]   [Theta] 시작  (메모리: 1587.8 MB)
[메모리] forecast_theta 실행 전: 1587.85 MB
[메모리] forecast_theta 실행 후: 1587.85 MB (변화: +0.00 MB)
[KODK]   [Theta] 완료  첫값=2.72e+08 (메모리: 1587.8 MB)
[KODK]   [DB] 93행 저장 완료
[PROGRESS] [ 241/500] ( 48.2%)  >>  KRO
[KRO]   45분기 | 2015-03-31 ~ 2026-03-31
[KRO]   [SARIMA] 시작  (메모리: 1587.8 MB)
[메모리] forecast_sarima 실행 전: 1587.85 MB
[메모리] find_best_sarima_params 실행 전: 1587.85 MB
[메모리] find_best_sarima_params 실행 후: 1587.85 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1587.85 MB (변화: +0.00 MB)
[KRO]   [SARIMA] 완료  첫값=4.67e+08 (메모리: 1587.8 MB)
[KRO]   [ETS] 시작  (메모리: 1587.8 MB)
[메모리] forecast_ets 실행 전: 1587.85 MB
[메모리] forecast_ets 실행 후: 1587.85 MB (변화: +0.00 MB)
[KRO]   [ETS] 완료  첫값=4.79e+08 (메모리: 1587.9 MB)
[KRO]   [Prophet] 시작  (메모리: 1587.9 MB)

01:43:59 - cmdstanpy - INFO - Chain [1] start processing
01:43:59 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1587.85 MB
[메모리] forecast_prophet 실행 후: 1587.14 MB (변화: -0.71 MB)
[KRO]   [Prophet] 완료  첫값=4.93e+08 (메모리: 1587.1 MB)
[KRO]   [LSTM] 시작  (메모리: 1587.1 MB)
[메모리] forecast_lstm 실행 전: 1587.14 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1588.11 MB (변화: +0.97 MB)
[KRO]   [LSTM] 완료  첫값=4.74e+08 (메모리: 1588.1 MB)
[KRO]   [Theta] 시작  (메모리: 1588.1 MB)
[메모리] forecast_theta 실행 전: 1588.11 MB
[메모리] forecast_theta 실행 후: 1588.11 MB (변화: +0.00 MB)
[KRO]   [Theta] 완료  첫값=4.59e+08 (메모리: 1588.1 MB)
[KRO]   [DB] 93행 저장 완료
[PROGRESS] [ 242/500] ( 48.4%)  >>  MBUU
[MBUU]   45분기 | 2015-03-31 ~ 2026-03-31
[MBUU]   [SARIMA] 시작  (메모리: 1588.1 MB)
[메모리] forecast_sarima 실행 전: 1588.11 MB
[메모리] find_best_sarima_params 실행 전: 1588.11 MB
[메모리] find_best_sarima_params 실행 후: 1588.11 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1588.11 MB (변화: +0.00 MB)
[MBUU]   [SARIMA] 완료  첫값=1.93e+08 (메모리: 1588.1 MB)
[MBUU]   [ETS] 시작  (메모리: 1588.1 MB)
[메모리] forecast_ets 실행 전: 1588.11 MB
[메모리] forecast_ets 실행 후: 1588.11 MB (변화: +0.00 MB)
[MBUU]   [ETS] 완료  첫값=1.74e+08 (메모리: 1588.1 MB)
[MBUU]   [Prophet] 시작  (메모리: 1588.1 MB)

01:44:18 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1588.11 MB

01:44:18 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1588.76 MB (변화: +0.65 MB)
[MBUU]   [Prophet] 완료  첫값=2.93e+08 (메모리: 1588.8 MB)
[MBUU]   [LSTM] 시작  (메모리: 1588.8 MB)
[메모리] forecast_lstm 실행 전: 1588.76 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1588.94 MB (변화: +0.18 MB)
[MBUU]   [LSTM] 완료  첫값=2.29e+08 (메모리: 1588.9 MB)
[MBUU]   [Theta] 시작  (메모리: 1588.9 MB)
[메모리] forecast_theta 실행 전: 1588.94 MB
[메모리] forecast_theta 실행 후: 1588.94 MB (변화: +0.00 MB)
[MBUU]   [Theta] 완료  첫값=1.71e+08 (메모리: 1588.9 MB)
[MBUU]   [DB] 93행 저장 완료
[PROGRESS] [ 243/500] ( 48.6%)  >>  AIC
[AIC] [SKIP] [AIC] 'sale' 관측치 부족: 25개 < 최소 28개
[PROGRESS] [ 244/500] ( 48.8%)  >>  SGOC
[SGOC]   36분기 | 2017-06-30 ~ 2026-03-31
[SGOC]   [SARIMA] 시작  (메모리: 1588.9 MB)
[메모리] forecast_sarima 실행 전: 1588.94 MB
[메모리] find_best_sarima_params 실행 전: 1588.94 MB
[메모리] find_best_sarima_params 실행 후: 1588.94 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1588.94 MB (변화: +0.00 MB)
[SGOC]   [SARIMA] 완료  첫값=2.53e+06 (메모리: 1588.9 MB)
[SGOC]   [ETS] 시작  (메모리: 1588.9 MB)
[메모리] forecast_ets 실행 전: 1588.94 MB
[메모리] forecast_ets 실행 후: 1588.95 MB (변화: +0.00 MB)
[SGOC]   [ETS] 완료  첫값=2.57e+06 (메모리: 1588.9 MB)
[SGOC]   [Prophet] 시작  (메모리: 1588.9 MB)

01:44:42 - cmdstanpy - INFO - Chain [1] start processing
01:44:42 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1588.95 MB
[메모리] forecast_prophet 실행 후: 1588.96 MB (변화: +0.02 MB)
[SGOC]   [Prophet] 완료  첫값=3.22e+06 (메모리: 1589.0 MB)
[SGOC]   [LSTM] 시작  (메모리: 1589.0 MB)
[메모리] forecast_lstm 실행 전: 1588.96 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1589.04 MB (변화: +0.07 MB)
[SGOC]   [LSTM] 완료  첫값=2.54e+06 (메모리: 1589.0 MB)
[SGOC]   [Theta] 시작  (메모리: 1589.0 MB)
[메모리] forecast_theta 실행 전: 1589.04 MB
[메모리] forecast_theta 실행 후: 1589.04 MB (변화: +0.00 MB)
[SGOC]   [Theta] 완료  첫값=2.66e+06 (메모리: 1589.0 MB)
[SGOC]   [DB] 84행 저장 완료
[PROGRESS] [ 245/500] ( 49.0%)  >>  ETD
[ETD]   45분기 | 2015-03-31 ~ 2026-03-31
[ETD]   [SARIMA] 시작  (메모리: 1589.0 MB)
[메모리] forecast_sarima 실행 전: 1589.04 MB
[메모리] find_best_sarima_params 실행 전: 1589.04 MB
[메모리] find_best_sarima_params 실행 후: 1589.04 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1589.04 MB (변화: +0.00 MB)
[ETD]   [SARIMA] 완료  첫값=1.50e+08 (메모리: 1589.0 MB)
[ETD]   [ETS] 시작  (메모리: 1589.0 MB)
[메모리] forecast_ets 실행 전: 1589.04 MB
[메모리] forecast_ets 실행 후: 1589.05 MB (변화: +0.01 MB)
[ETD]   [ETS] 완료  첫값=1.51e+08 (메모리: 1589.0 MB)
[ETD]   [Prophet] 시작  (메모리: 1589.0 MB)

01:45:03 - cmdstanpy - INFO - Chain [1] start processing
01:45:03 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1589.05 MB
[메모리] forecast_prophet 실행 후: 1589.05 MB (변화: +0.00 MB)
[ETD]   [Prophet] 완료  첫값=1.60e+08 (메모리: 1589.1 MB)
[ETD]   [LSTM] 시작  (메모리: 1589.1 MB)
[메모리] forecast_lstm 실행 전: 1589.05 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1588.03 MB (변화: -1.02 MB)
[ETD]   [LSTM] 완료  첫값=1.75e+08 (메모리: 1588.0 MB)
[ETD]   [Theta] 시작  (메모리: 1588.0 MB)
[메모리] forecast_theta 실행 전: 1588.03 MB
[메모리] forecast_theta 실행 후: 1588.03 MB (변화: +0.00 MB)
[ETD]   [Theta] 완료  첫값=1.49e+08 (메모리: 1588.0 MB)
[ETD]   [DB] 93행 저장 완료
[PROGRESS] [ 246/500] ( 49.2%)  >>  NR
[NR]   45분기 | 2015-03-31 ~ 2026-03-31
[NR]   [SARIMA] 시작  (메모리: 1588.0 MB)
[메모리] forecast_sarima 실행 전: 1588.03 MB
[메모리] find_best_sarima_params 실행 전: 1588.03 MB
[메모리] find_best_sarima_params 실행 후: 1588.03 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1588.03 MB (변화: +0.00 MB)
[NR]   [SARIMA] 완료  첫값=2.48e+07 (메모리: 1588.0 MB)
[NR]   [ETS] 시작  (메모리: 1588.0 MB)
[메모리] forecast_ets 실행 전: 1588.03 MB
[메모리] forecast_ets 실행 후: 1588.03 MB (변화: +0.00 MB)
[NR]   [ETS] 완료  첫값=6.79e+07 (메모리: 1588.0 MB)
[NR]   [Prophet] 시작  (메모리: 1588.0 MB)

01:45:18 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1588.03 MB

01:45:18 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1588.45 MB (변화: +0.42 MB)
[NR]   [Prophet] 완료  첫값=1.03e+08 (메모리: 1588.4 MB)
[NR]   [LSTM] 시작  (메모리: 1588.4 MB)
[메모리] forecast_lstm 실행 전: 1588.45 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1588.45 MB (변화: +0.00 MB)
[NR]   [LSTM] 완료  첫값=4.73e+07 (메모리: 1588.5 MB)
[NR]   [Theta] 시작  (메모리: 1588.5 MB)
[메모리] forecast_theta 실행 전: 1588.45 MB
[메모리] forecast_theta 실행 후: 1588.45 MB (변화: +0.00 MB)
[NR]   [Theta] 완료  첫값=6.72e+07 (메모리: 1588.5 MB)
[NR]   [DB] 93행 저장 완료
[PROGRESS] [ 247/500] ( 49.4%)  >>  NTGR
[NTGR]   45분기 | 2015-03-31 ~ 2026-03-31
[NTGR]   [SARIMA] 시작  (메모리: 1588.5 MB)
[메모리] forecast_sarima 실행 전: 1588.45 MB
[메모리] find_best_sarima_params 실행 전: 1588.45 MB
[메모리] find_best_sarima_params 실행 후: 1588.45 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1588.45 MB (변화: +0.00 MB)
[NTGR]   [SARIMA] 완료  첫값=1.79e+08 (메모리: 1588.5 MB)
[NTGR]   [ETS] 시작  (메모리: 1588.5 MB)
[메모리] forecast_ets 실행 전: 1588.45 MB
[메모리] forecast_ets 실행 후: 1588.46 MB (변화: +0.00 MB)
[NTGR]   [ETS] 완료  첫값=1.61e+08 (메모리: 1588.5 MB)
[NTGR]   [Prophet] 시작  (메모리: 1588.5 MB)

01:45:37 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1588.46 MB

01:45:37 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1588.46 MB (변화: +0.00 MB)
[NTGR]   [Prophet] 완료  첫값=1.63e+08 (메모리: 1588.5 MB)
[NTGR]   [LSTM] 시작  (메모리: 1588.5 MB)
[메모리] forecast_lstm 실행 전: 1588.46 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1588.45 MB (변화: -0.00 MB)
[NTGR]   [LSTM] 완료  첫값=1.69e+08 (메모리: 1588.5 MB)
[NTGR]   [Theta] 시작  (메모리: 1588.5 MB)
[메모리] forecast_theta 실행 전: 1588.45 MB
[메모리] forecast_theta 실행 후: 1588.45 MB (변화: +0.00 MB)
[NTGR]   [Theta] 완료  첫값=1.62e+08 (메모리: 1588.5 MB)
[NTGR]   [DB] 93행 저장 완료
[PROGRESS] [ 248/500] ( 49.6%)  >>  IVR
[IVR]   45분기 | 2015-03-31 ~ 2026-03-31
[IVR]   [SARIMA] 시작  (메모리: 1588.5 MB)
[메모리] forecast_sarima 실행 전: 1588.45 MB
[메모리] find_best_sarima_params 실행 전: 1588.45 MB
[메모리] find_best_sarima_params 실행 후: 1588.45 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1588.45 MB (변화: +0.00 MB)
[IVR]   [SARIMA] 완료  첫값=-2.61e+07 (메모리: 1588.5 MB)
[IVR]   [ETS] 시작  (메모리: 1588.5 MB)
[메모리] forecast_ets 실행 전: 1588.45 MB
[메모리] forecast_ets 실행 후: 1588.46 MB (변화: +0.00 MB)
[IVR]   [ETS] 완료  첫값=7.37e+07 (메모리: 1588.5 MB)
[IVR]   [Prophet] 시작  (메모리: 1588.5 MB)

01:45:58 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1588.46 MB

01:45:58 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1588.46 MB (변화: +0.00 MB)
[IVR]   [Prophet] 완료  첫값=-2.69e+07 (메모리: 1588.5 MB)
[IVR]   [LSTM] 시작  (메모리: 1588.5 MB)
[메모리] forecast_lstm 실행 전: 1588.46 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1588.50 MB (변화: +0.05 MB)
[IVR]   [LSTM] 완료  첫값=2.39e+07 (메모리: 1588.5 MB)
[IVR]   [Theta] 시작  (메모리: 1588.5 MB)
[메모리] forecast_theta 실행 전: 1588.50 MB
[메모리] forecast_theta 실행 후: 1588.50 MB (변화: +0.00 MB)
[IVR]   [Theta] 완료  첫값=-2.00e+07 (메모리: 1588.5 MB)
[IVR]   [DB] 93행 저장 완료
[PROGRESS] [ 249/500] ( 49.8%)  >>  KFRC
[KFRC]   45분기 | 2015-03-31 ~ 2026-03-31
[KFRC]   [SARIMA] 시작  (메모리: 1588.5 MB)
[메모리] forecast_sarima 실행 전: 1588.50 MB
[메모리] find_best_sarima_params 실행 전: 1588.50 MB
[메모리] find_best_sarima_params 실행 후: 1588.50 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1588.50 MB (변화: +0.00 MB)
[KFRC]   [SARIMA] 완료  첫값=3.32e+08 (메모리: 1588.5 MB)
[KFRC]   [ETS] 시작  (메모리: 1588.5 MB)
[메모리] forecast_ets 실행 전: 1588.50 MB
[메모리] forecast_ets 실행 후: 1588.50 MB (변화: +0.00 MB)
[KFRC]   [ETS] 완료  첫값=3.45e+08 (메모리: 1588.5 MB)
[KFRC]   [Prophet] 시작  (메모리: 1588.5 MB)

01:46:22 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1588.50 MB

01:46:22 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1588.51 MB (변화: +0.01 MB)
[KFRC]   [Prophet] 완료  첫값=3.26e+08 (메모리: 1588.5 MB)
[KFRC]   [LSTM] 시작  (메모리: 1588.5 MB)
[메모리] forecast_lstm 실행 전: 1588.51 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1588.54 MB (변화: +0.03 MB)
[KFRC]   [LSTM] 완료  첫값=3.59e+08 (메모리: 1588.5 MB)
[KFRC]   [Theta] 시작  (메모리: 1588.5 MB)
[메모리] forecast_theta 실행 전: 1588.54 MB
[메모리] forecast_theta 실행 후: 1588.54 MB (변화: +0.00 MB)
[KFRC]   [Theta] 완료  첫값=3.42e+08 (메모리: 1588.5 MB)
[KFRC]   [DB] 93행 저장 완료
[PROGRESS] [ 250/500] ( 50.0%)  >>  SRDX
[SRDX]   45분기 | 2015-03-31 ~ 2026-03-31
[SRDX]   [SARIMA] 시작  (메모리: 1588.5 MB)
[메모리] forecast_sarima 실행 전: 1588.54 MB
[메모리] find_best_sarima_params 실행 전: 1588.54 MB
[메모리] find_best_sarima_params 실행 후: 1588.54 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1588.54 MB (변화: +0.00 MB)
[SRDX]   [SARIMA] 완료  첫값=3.44e+07 (메모리: 1588.5 MB)
[SRDX]   [ETS] 시작  (메모리: 1588.5 MB)
[메모리] forecast_ets 실행 전: 1588.54 MB
[메모리] forecast_ets 실행 후: 1588.54 MB (변화: +0.00 MB)
[SRDX]   [ETS] 완료  첫값=3.69e+07 (메모리: 1588.5 MB)
[SRDX]   [Prophet] 시작  (메모리: 1588.5 MB)

01:46:40 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1588.54 MB

01:46:41 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1588.55 MB (변화: +0.00 MB)
[SRDX]   [Prophet] 완료  첫값=3.35e+07 (메모리: 1588.5 MB)
[SRDX]   [LSTM] 시작  (메모리: 1588.5 MB)
[메모리] forecast_lstm 실행 전: 1588.55 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1588.50 MB (변화: -0.05 MB)
[SRDX]   [LSTM] 완료  첫값=3.47e+07 (메모리: 1588.5 MB)
[SRDX]   [Theta] 시작  (메모리: 1588.5 MB)
[메모리] forecast_theta 실행 전: 1588.50 MB
[메모리] forecast_theta 실행 후: 1588.50 MB (변화: +0.00 MB)
[SRDX]   [Theta] 완료  첫값=3.26e+07 (메모리: 1588.5 MB)
[SRDX]   [DB] 93행 저장 완료
[PROGRESS] [ 251/500] ( 50.2%)  >>  SHEN
[SHEN]   45분기 | 2015-03-31 ~ 2026-03-31
[SHEN]   [SARIMA] 시작  (메모리: 1588.5 MB)
[메모리] forecast_sarima 실행 전: 1588.50 MB
[메모리] find_best_sarima_params 실행 전: 1588.50 MB
[메모리] find_best_sarima_params 실행 후: 1588.50 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1588.50 MB (변화: +0.00 MB)
[SHEN]   [SARIMA] 완료  첫값=8.98e+07 (메모리: 1588.5 MB)
[SHEN]   [ETS] 시작  (메모리: 1588.5 MB)
[메모리] forecast_ets 실행 전: 1588.50 MB
[메모리] forecast_ets 실행 후: 1588.50 MB (변화: +0.00 MB)
[SHEN]   [ETS] 완료  첫값=9.47e+07 (메모리: 1588.5 MB)
[SHEN]   [Prophet] 시작  (메모리: 1588.5 MB)

01:46:57 - cmdstanpy - INFO - Chain [1] start processing
01:46:57 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1588.50 MB
[메모리] forecast_prophet 실행 후: 1588.52 MB (변화: +0.01 MB)
[SHEN]   [Prophet] 완료  첫값=6.42e+07 (메모리: 1588.5 MB)
[SHEN]   [LSTM] 시작  (메모리: 1588.5 MB)
[메모리] forecast_lstm 실행 전: 1588.52 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1588.55 MB (변화: +0.03 MB)
[SHEN]   [LSTM] 완료  첫값=7.51e+07 (메모리: 1588.5 MB)
[SHEN]   [Theta] 시작  (메모리: 1588.5 MB)
[메모리] forecast_theta 실행 전: 1588.55 MB
[메모리] forecast_theta 실행 후: 1588.55 MB (변화: +0.00 MB)
[SHEN]   [Theta] 완료  첫값=9.43e+07 (메모리: 1588.5 MB)
[SHEN]   [DB] 93행 저장 완료
[PROGRESS] [ 252/500] ( 50.4%)  >>  CGC
[CGC]   45분기 | 2015-03-31 ~ 2026-03-31
[CGC]   [SARIMA] 시작  (메모리: 1588.5 MB)
[메모리] forecast_sarima 실행 전: 1588.55 MB
[메모리] find_best_sarima_params 실행 전: 1588.55 MB
[메모리] find_best_sarima_params 실행 후: 1588.55 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1588.55 MB (변화: +0.00 MB)
[CGC]   [SARIMA] 완료  첫값=9.49e+07 (메모리: 1588.5 MB)
[CGC]   [ETS] 시작  (메모리: 1588.5 MB)
[메모리] forecast_ets 실행 전: 1588.55 MB
[메모리] forecast_ets 실행 후: 1588.55 MB (변화: +0.00 MB)
[CGC]   [ETS] 완료  첫값=9.31e+07 (메모리: 1588.5 MB)
[CGC]   [Prophet] 시작  (메모리: 1588.5 MB)

01:47:16 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1588.55 MB

01:47:16 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1588.55 MB (변화: +0.00 MB)
[CGC]   [Prophet] 완료  첫값=1.16e+08 (메모리: 1588.6 MB)
[CGC]   [LSTM] 시작  (메모리: 1588.6 MB)
[메모리] forecast_lstm 실행 전: 1588.55 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1587.48 MB (변화: -1.07 MB)
[CGC]   [LSTM] 완료  첫값=7.76e+07 (메모리: 1587.5 MB)
[CGC]   [Theta] 시작  (메모리: 1587.5 MB)
[메모리] forecast_theta 실행 전: 1587.48 MB
[메모리] forecast_theta 실행 후: 1587.48 MB (변화: +0.00 MB)
[CGC]   [Theta] 완료  첫값=9.01e+07 (메모리: 1587.5 MB)
[CGC]   [DB] 93행 저장 완료
[PROGRESS] [ 253/500] ( 50.6%)  >>  CDXC
[CDXC]   45분기 | 2015-03-31 ~ 2026-03-31
[CDXC]   [SARIMA] 시작  (메모리: 1587.5 MB)
[메모리] forecast_sarima 실행 전: 1587.48 MB
[메모리] find_best_sarima_params 실행 전: 1587.48 MB
[메모리] find_best_sarima_params 실행 후: 1587.48 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1587.48 MB (변화: +0.00 MB)
[CDXC]   [SARIMA] 완료  첫값=5.63e+05 (메모리: 1587.5 MB)
[CDXC]   [ETS] 시작  (메모리: 1587.5 MB)
[메모리] forecast_ets 실행 전: 1587.48 MB
[메모리] forecast_ets 실행 후: 1587.49 MB (변화: +0.00 MB)
[CDXC]   [ETS] 완료  첫값=-6.43e+06 (메모리: 1587.5 MB)
[CDXC]   [Prophet] 시작  (메모리: 1587.5 MB)

01:47:37 - cmdstanpy - INFO - Chain [1] start processing
01:47:37 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1587.49 MB
[메모리] forecast_prophet 실행 후: 1587.50 MB (변화: +0.01 MB)
[CDXC]   [Prophet] 완료  첫값=1.91e+07 (메모리: 1587.5 MB)
[CDXC]   [LSTM] 시작  (메모리: 1587.5 MB)
[메모리] forecast_lstm 실행 전: 1587.50 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1587.48 MB (변화: -0.01 MB)
[CDXC]   [LSTM] 완료  첫값=1.61e+07 (메모리: 1587.5 MB)
[CDXC]   [Theta] 시작  (메모리: 1587.5 MB)
[메모리] forecast_theta 실행 전: 1587.48 MB
[메모리] forecast_theta 실행 후: 1587.48 MB (변화: +0.00 MB)
[CDXC]   [Theta] 완료  첫값=1.51e+05 (메모리: 1587.5 MB)
[CDXC]   [DB] 93행 저장 완료
[PROGRESS] [ 254/500] ( 50.8%)  >>  HZO
[HZO]   45분기 | 2015-03-31 ~ 2026-03-31
[HZO]   [SARIMA] 시작  (메모리: 1587.5 MB)
[메모리] forecast_sarima 실행 전: 1587.48 MB
[메모리] find_best_sarima_params 실행 전: 1587.48 MB
[메모리] find_best_sarima_params 실행 후: 1587.48 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1587.48 MB (변화: +0.00 MB)
[HZO]   [SARIMA] 완료  첫값=6.38e+08 (메모리: 1587.5 MB)
[HZO]   [ETS] 시작  (메모리: 1587.5 MB)
[메모리] forecast_ets 실행 전: 1587.48 MB
[메모리] forecast_ets 실행 후: 1587.49 MB (변화: +0.01 MB)
[HZO]   [ETS] 완료  첫값=6.74e+08 (메모리: 1587.5 MB)
[HZO]   [Prophet] 시작  (메모리: 1587.5 MB)

01:47:58 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1587.49 MB

01:47:58 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1587.90 MB (변화: +0.41 MB)
[HZO]   [Prophet] 완료  첫값=6.75e+08 (메모리: 1587.9 MB)
[HZO]   [LSTM] 시작  (메모리: 1587.9 MB)
[메모리] forecast_lstm 실행 전: 1587.90 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1587.86 MB (변화: -0.05 MB)
[HZO]   [LSTM] 완료  첫값=6.20e+08 (메모리: 1587.9 MB)
[HZO]   [Theta] 시작  (메모리: 1587.9 MB)
[메모리] forecast_theta 실행 전: 1587.86 MB
[메모리] forecast_theta 실행 후: 1587.86 MB (변화: +0.00 MB)
[HZO]   [Theta] 완료  첫값=6.87e+08 (메모리: 1587.9 MB)
[HZO]   [DB] 93행 저장 완료
[PROGRESS] [ 255/500] ( 51.0%)  >>  CRMD
[CRMD]   45분기 | 2015-03-31 ~ 2026-03-31
[CRMD]   [SARIMA] 시작  (메모리: 1587.9 MB)
[메모리] forecast_sarima 실행 전: 1587.86 MB
[메모리] find_best_sarima_params 실행 전: 1587.86 MB
[메모리] find_best_sarima_params 실행 후: 1587.86 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1587.86 MB (변화: +0.00 MB)
[CRMD]   [SARIMA] 완료  첫값=1.35e+08 (메모리: 1587.9 MB)
[CRMD]   [ETS] 시작  (메모리: 1587.9 MB)
[메모리] forecast_ets 실행 전: 1587.86 MB
[메모리] forecast_ets 실행 후: 1587.86 MB (변화: +0.00 MB)
[CRMD]   [ETS] 완료  첫값=1.22e+08 (메모리: 1587.9 MB)
[CRMD]   [Prophet] 시작  (메모리: 1587.9 MB)

01:48:18 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1587.86 MB

01:48:18 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1588.28 MB (변화: +0.42 MB)
[CRMD]   [Prophet] 완료  첫값=3.63e+07 (메모리: 1588.3 MB)
[CRMD]   [LSTM] 시작  (메모리: 1588.3 MB)
[메모리] forecast_lstm 실행 전: 1588.28 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1588.28 MB (변화: +0.00 MB)
[CRMD]   [LSTM] 완료  첫값=1.59e+08 (메모리: 1588.3 MB)
[CRMD]   [Theta] 시작  (메모리: 1588.3 MB)
[메모리] forecast_theta 실행 전: 1588.28 MB
[메모리] forecast_theta 실행 후: 1588.28 MB (변화: +0.00 MB)
[CRMD]   [Theta] 완료  첫값=1.05e+08 (메모리: 1588.3 MB)
[CRMD]   [DB] 93행 저장 완료
[PROGRESS] [ 256/500] ( 51.2%)  >>  AVNS
[AVNS]   45분기 | 2015-03-31 ~ 2026-03-31
[AVNS]   [SARIMA] 시작  (메모리: 1588.3 MB)
[메모리] forecast_sarima 실행 전: 1588.28 MB
[메모리] find_best_sarima_params 실행 전: 1588.28 MB
[메모리] find_best_sarima_params 실행 후: 1588.28 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1588.28 MB (변화: +0.00 MB)
[AVNS]   [SARIMA] 완료  첫값=1.73e+08 (메모리: 1588.3 MB)
[AVNS]   [ETS] 시작  (메모리: 1588.3 MB)
[메모리] forecast_ets 실행 전: 1588.28 MB
[메모리] forecast_ets 실행 후: 1588.28 MB (변화: +0.00 MB)
[AVNS]   [ETS] 완료  첫값=1.63e+08 (메모리: 1588.3 MB)
[AVNS]   [Prophet] 시작  (메모리: 1588.3 MB)

01:48:44 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1588.28 MB

01:48:44 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1588.29 MB (변화: +0.01 MB)
[AVNS]   [Prophet] 완료  첫값=1.13e+08 (메모리: 1588.3 MB)
[AVNS]   [LSTM] 시작  (메모리: 1588.3 MB)
[메모리] forecast_lstm 실행 전: 1588.29 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1588.29 MB (변화: +0.00 MB)
[AVNS]   [LSTM] 완료  첫값=1.78e+08 (메모리: 1588.3 MB)
[AVNS]   [Theta] 시작  (메모리: 1588.3 MB)
[메모리] forecast_theta 실행 전: 1588.29 MB
[메모리] forecast_theta 실행 후: 1588.29 MB (변화: +0.00 MB)
[AVNS]   [Theta] 완료  첫값=1.64e+08 (메모리: 1588.3 MB)
[AVNS]   [DB] 93행 저장 완료
[PROGRESS] [ 257/500] ( 51.4%)  >>  ABST
[ABST]   45분기 | 2015-03-31 ~ 2026-03-31
[ABST]   [SARIMA] 시작  (메모리: 1588.3 MB)
[메모리] forecast_sarima 실행 전: 1588.29 MB
[메모리] find_best_sarima_params 실행 전: 1588.29 MB
[메모리] find_best_sarima_params 실행 후: 1588.29 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1588.29 MB (변화: +0.00 MB)
[ABST]   [SARIMA] 완료  첫값=6.00e+07 (메모리: 1588.3 MB)
[ABST]   [ETS] 시작  (메모리: 1588.3 MB)
[메모리] forecast_ets 실행 전: 1588.29 MB
[메모리] forecast_ets 실행 후: 1588.29 MB (변화: +0.00 MB)
[ABST]   [ETS] 완료  첫값=5.84e+07 (메모리: 1588.3 MB)
[ABST]   [Prophet] 시작  (메모리: 1588.3 MB)

01:49:08 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1588.29 MB

01:49:08 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1588.70 MB (변화: +0.41 MB)
[ABST]   [Prophet] 완료  첫값=6.44e+07 (메모리: 1588.7 MB)
[ABST]   [LSTM] 시작  (메모리: 1588.7 MB)
[메모리] forecast_lstm 실행 전: 1588.70 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1588.90 MB (변화: +0.20 MB)
[ABST]   [LSTM] 완료  첫값=5.98e+07 (메모리: 1588.9 MB)
[ABST]   [Theta] 시작  (메모리: 1588.9 MB)
[메모리] forecast_theta 실행 전: 1588.90 MB
[메모리] forecast_theta 실행 후: 1588.90 MB (변화: +0.00 MB)
[ABST]   [Theta] 완료  첫값=5.92e+07 (메모리: 1588.9 MB)
[ABST]   [DB] 93행 저장 완료
[PROGRESS] [ 258/500] ( 51.6%)  >>  GOGO
[GOGO]   45분기 | 2015-03-31 ~ 2026-03-31
[GOGO]   [SARIMA] 시작  (메모리: 1588.9 MB)
[메모리] forecast_sarima 실행 전: 1588.90 MB
[메모리] find_best_sarima_params 실행 전: 1588.90 MB
[메모리] find_best_sarima_params 실행 후: 1588.90 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1588.90 MB (변화: +0.00 MB)
[GOGO]   [SARIMA] 완료  첫값=2.24e+08 (메모리: 1588.9 MB)
[GOGO]   [ETS] 시작  (메모리: 1588.9 MB)
[메모리] forecast_ets 실행 전: 1588.90 MB
[메모리] forecast_ets 실행 후: 1588.90 MB (변화: +0.00 MB)
[GOGO]   [ETS] 완료  첫값=2.25e+08 (메모리: 1588.9 MB)
[GOGO]   [Prophet] 시작  (메모리: 1588.9 MB)

01:49:32 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1588.90 MB

01:49:32 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1590.05 MB (변화: +1.15 MB)
[GOGO]   [Prophet] 완료  첫값=1.38e+08 (메모리: 1590.1 MB)
[GOGO]   [LSTM] 시작  (메모리: 1590.1 MB)
[메모리] forecast_lstm 실행 전: 1590.05 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1589.25 MB (변화: -0.80 MB)
[GOGO]   [LSTM] 완료  첫값=1.33e+08 (메모리: 1589.2 MB)
[GOGO]   [Theta] 시작  (메모리: 1589.2 MB)
[메모리] forecast_theta 실행 전: 1589.25 MB
[메모리] forecast_theta 실행 후: 1589.25 MB (변화: +0.00 MB)
[GOGO]   [Theta] 완료  첫값=2.23e+08 (메모리: 1589.2 MB)
[GOGO]   [DB] 93행 저장 완료
[PROGRESS] [ 259/500] ( 51.8%)  >>  CMCL
[CMCL]   45분기 | 2015-03-31 ~ 2026-03-31
[CMCL]   [SARIMA] 시작  (메모리: 1589.2 MB)
[메모리] forecast_sarima 실행 전: 1589.25 MB
[메모리] find_best_sarima_params 실행 전: 1589.25 MB
[메모리] find_best_sarima_params 실행 후: 1589.25 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1589.25 MB (변화: +0.00 MB)
[CMCL]   [SARIMA] 완료  첫값=7.45e+07 (메모리: 1589.2 MB)
[CMCL]   [ETS] 시작  (메모리: 1589.2 MB)
[메모리] forecast_ets 실행 전: 1589.25 MB
[메모리] forecast_ets 실행 후: 1589.25 MB (변화: +0.00 MB)
[CMCL]   [ETS] 완료  첫값=7.76e+07 (메모리: 1589.2 MB)
[CMCL]   [Prophet] 시작  (메모리: 1589.2 MB)

01:49:51 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1589.25 MB

01:49:51 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1589.93 MB (변화: +0.69 MB)
[CMCL]   [Prophet] 완료  첫값=6.95e+07 (메모리: 1589.9 MB)
[CMCL]   [LSTM] 시작  (메모리: 1589.9 MB)
[메모리] forecast_lstm 실행 전: 1589.93 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1589.10 MB (변화: -0.84 MB)
[CMCL]   [LSTM] 완료  첫값=8.30e+07 (메모리: 1589.1 MB)
[CMCL]   [Theta] 시작  (메모리: 1589.1 MB)
[메모리] forecast_theta 실행 전: 1589.10 MB
[메모리] forecast_theta 실행 후: 1589.10 MB (변화: +0.00 MB)
[CMCL]   [Theta] 완료  첫값=7.66e+07 (메모리: 1589.1 MB)
[CMCL]   [DB] 93행 저장 완료
[PROGRESS] [ 260/500] ( 52.0%)  >>  KOS
[KOS]   45분기 | 2015-03-31 ~ 2026-03-31
[KOS]   [SARIMA] 시작  (메모리: 1589.1 MB)
[메모리] forecast_sarima 실행 전: 1589.10 MB
[메모리] find_best_sarima_params 실행 전: 1589.10 MB
[메모리] find_best_sarima_params 실행 후: 1589.10 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1589.10 MB (변화: +0.00 MB)
[KOS]   [SARIMA] 완료  첫값=3.18e+08 (메모리: 1589.1 MB)
[KOS]   [ETS] 시작  (메모리: 1589.1 MB)
[메모리] forecast_ets 실행 전: 1589.10 MB
[메모리] forecast_ets 실행 후: 1589.10 MB (변화: +0.00 MB)
[KOS]   [ETS] 완료  첫값=3.28e+08 (메모리: 1589.1 MB)
[KOS]   [Prophet] 시작  (메모리: 1589.1 MB)

01:50:12 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1589.10 MB

01:50:12 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1589.92 MB (변화: +0.82 MB)
[KOS]   [Prophet] 완료  첫값=4.87e+08 (메모리: 1589.9 MB)
[KOS]   [LSTM] 시작  (메모리: 1589.9 MB)
[메모리] forecast_lstm 실행 전: 1589.92 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1588.03 MB (변화: -1.89 MB)
[KOS]   [LSTM] 완료  첫값=3.62e+08 (메모리: 1588.0 MB)
[KOS]   [Theta] 시작  (메모리: 1588.0 MB)
[메모리] forecast_theta 실행 전: 1588.03 MB
[메모리] forecast_theta 실행 후: 1588.03 MB (변화: +0.00 MB)
[KOS]   [Theta] 완료  첫값=3.25e+08 (메모리: 1588.0 MB)
[KOS]   [DB] 93행 저장 완료
[PROGRESS] [ 261/500] ( 52.2%)  >>  MNRO
[MNRO]   45분기 | 2015-03-31 ~ 2026-03-31
[MNRO]   [SARIMA] 시작  (메모리: 1588.0 MB)
[메모리] forecast_sarima 실행 전: 1588.03 MB
[메모리] find_best_sarima_params 실행 전: 1588.03 MB
[메모리] find_best_sarima_params 실행 후: 1588.03 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1588.03 MB (변화: +0.00 MB)
[MNRO]   [SARIMA] 완료  첫값=2.95e+08 (메모리: 1588.0 MB)
[MNRO]   [ETS] 시작  (메모리: 1588.0 MB)
[메모리] forecast_ets 실행 전: 1588.03 MB
[메모리] forecast_ets 실행 후: 1588.04 MB (변화: +0.00 MB)
[MNRO]   [ETS] 완료  첫값=3.01e+08 (메모리: 1588.0 MB)
[MNRO]   [Prophet] 시작  (메모리: 1588.0 MB)

01:50:32 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1588.04 MB

01:50:33 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1589.27 MB (변화: +1.24 MB)
[MNRO]   [Prophet] 완료  첫값=3.01e+08 (메모리: 1589.3 MB)
[MNRO]   [LSTM] 시작  (메모리: 1589.3 MB)
[메모리] forecast_lstm 실행 전: 1589.27 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1590.24 MB (변화: +0.97 MB)
[MNRO]   [LSTM] 완료  첫값=3.11e+08 (메모리: 1590.2 MB)
[MNRO]   [Theta] 시작  (메모리: 1590.2 MB)
[메모리] forecast_theta 실행 전: 1590.24 MB
[메모리] forecast_theta 실행 후: 1590.24 MB (변화: +0.00 MB)
[MNRO]   [Theta] 완료  첫값=2.99e+08 (메모리: 1590.2 MB)
[MNRO]   [DB] 93행 저장 완료
[PROGRESS] [ 262/500] ( 52.4%)  >>  APPS
[APPS]   45분기 | 2015-03-31 ~ 2026-03-31
[APPS]   [SARIMA] 시작  (메모리: 1590.2 MB)
[메모리] forecast_sarima 실행 전: 1590.24 MB
[메모리] find_best_sarima_params 실행 전: 1590.24 MB
[메모리] find_best_sarima_params 실행 후: 1590.24 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1590.24 MB (변화: +0.00 MB)
[APPS]   [SARIMA] 완료  첫값=1.61e+08 (메모리: 1590.2 MB)
[APPS]   [ETS] 시작  (메모리: 1590.2 MB)
[메모리] forecast_ets 실행 전: 1590.24 MB
[메모리] forecast_ets 실행 후: 1590.25 MB (변화: +0.00 MB)
[APPS]   [ETS] 완료  첫값=1.80e+08 (메모리: 1590.2 MB)
[APPS]   [Prophet] 시작  (메모리: 1590.2 MB)

01:50:58 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1590.25 MB

01:50:58 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1589.75 MB (변화: -0.49 MB)
[APPS]   [Prophet] 완료  첫값=1.75e+08 (메모리: 1589.8 MB)
[APPS]   [LSTM] 시작  (메모리: 1589.8 MB)
[메모리] forecast_lstm 실행 전: 1589.75 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1591.32 MB (변화: +1.56 MB)
[APPS]   [LSTM] 완료  첫값=1.26e+08 (메모리: 1591.3 MB)
[APPS]   [Theta] 시작  (메모리: 1591.3 MB)
[메모리] forecast_theta 실행 전: 1591.32 MB
[메모리] forecast_theta 실행 후: 1591.32 MB (변화: +0.00 MB)
[APPS]   [Theta] 완료  첫값=1.71e+08 (메모리: 1591.3 MB)
[APPS]   [DB] 93행 저장 완료
[PROGRESS] [ 263/500] ( 52.6%)  >>  RGR
[RGR]   45분기 | 2015-03-31 ~ 2026-03-31
[RGR]   [SARIMA] 시작  (메모리: 1591.3 MB)
[메모리] forecast_sarima 실행 전: 1591.32 MB
[메모리] find_best_sarima_params 실행 전: 1591.32 MB
[메모리] find_best_sarima_params 실행 후: 1591.32 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1591.32 MB (변화: +0.00 MB)
[RGR]   [SARIMA] 완료  첫값=1.26e+08 (메모리: 1591.3 MB)
[RGR]   [ETS] 시작  (메모리: 1591.3 MB)
[메모리] forecast_ets 실행 전: 1591.32 MB
[메모리] forecast_ets 실행 후: 1591.32 MB (변화: +0.00 MB)
[RGR]   [ETS] 완료  첫값=1.27e+08 (메모리: 1591.3 MB)
[RGR]   [Prophet] 시작  (메모리: 1591.3 MB)

01:51:19 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1591.32 MB

01:51:19 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1591.08 MB (변화: -0.24 MB)
[RGR]   [Prophet] 완료  첫값=1.38e+08 (메모리: 1591.1 MB)
[RGR]   [LSTM] 시작  (메모리: 1591.1 MB)
[메모리] forecast_lstm 실행 전: 1591.08 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1591.21 MB (변화: +0.13 MB)
[RGR]   [LSTM] 완료  첫값=1.36e+08 (메모리: 1591.2 MB)
[RGR]   [Theta] 시작  (메모리: 1591.2 MB)
[메모리] forecast_theta 실행 전: 1591.21 MB
[메모리] forecast_theta 실행 후: 1591.21 MB (변화: +0.00 MB)
[RGR]   [Theta] 완료  첫값=1.27e+08 (메모리: 1591.2 MB)
[RGR]   [DB] 93행 저장 완료
[PROGRESS] [ 264/500] ( 52.8%)  >>  NGVC
[NGVC]   45분기 | 2015-03-31 ~ 2026-03-31
[NGVC]   [SARIMA] 시작  (메모리: 1591.2 MB)
[메모리] forecast_sarima 실행 전: 1591.21 MB
[메모리] find_best_sarima_params 실행 전: 1591.21 MB
[메모리] find_best_sarima_params 실행 후: 1591.21 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1591.21 MB (변화: +0.00 MB)
[NGVC]   [SARIMA] 완료  첫값=3.41e+08 (메모리: 1591.2 MB)
[NGVC]   [ETS] 시작  (메모리: 1591.2 MB)
[메모리] forecast_ets 실행 전: 1591.21 MB
[메모리] forecast_ets 실행 후: 1591.21 MB (변화: +0.00 MB)
[NGVC]   [ETS] 완료  첫값=3.32e+08 (메모리: 1591.2 MB)
[NGVC]   [Prophet] 시작  (메모리: 1591.2 MB)
[메모리] forecast_prophet 실행 전: 1591.21 MB

01:51:46 - cmdstanpy - INFO - Chain [1] start processing
01:51:46 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1591.38 MB (변화: +0.17 MB)
[NGVC]   [Prophet] 완료  첫값=3.44e+08 (메모리: 1591.4 MB)
[NGVC]   [LSTM] 시작  (메모리: 1591.4 MB)
[메모리] forecast_lstm 실행 전: 1591.38 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1592.19 MB (변화: +0.80 MB)
[NGVC]   [LSTM] 완료  첫값=3.27e+08 (메모리: 1592.2 MB)
[NGVC]   [Theta] 시작  (메모리: 1592.2 MB)
[메모리] forecast_theta 실행 전: 1592.19 MB
[메모리] forecast_theta 실행 후: 1592.19 MB (변화: +0.00 MB)
[NGVC]   [Theta] 완료  첫값=3.29e+08 (메모리: 1592.2 MB)
[NGVC]   [DB] 93행 저장 완료
[PROGRESS] [ 265/500] ( 53.0%)  >>  REPX
[REPX]   45분기 | 2015-03-31 ~ 2026-03-31
[REPX]   [SARIMA] 시작  (메모리: 1592.2 MB)
[메모리] forecast_sarima 실행 전: 1592.19 MB
[메모리] find_best_sarima_params 실행 전: 1592.19 MB
[메모리] find_best_sarima_params 실행 후: 1592.19 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1592.19 MB (변화: +0.00 MB)
[REPX]   [SARIMA] 완료  첫값=1.46e+08 (메모리: 1592.2 MB)
[REPX]   [ETS] 시작  (메모리: 1592.2 MB)
[메모리] forecast_ets 실행 전: 1592.19 MB
[메모리] forecast_ets 실행 후: 1592.19 MB (변화: +0.00 MB)
[REPX]   [ETS] 완료  첫값=1.09e+08 (메모리: 1592.2 MB)
[REPX]   [Prophet] 시작  (메모리: 1592.2 MB)

01:52:03 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1592.19 MB

01:52:03 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.60 MB (변화: +1.41 MB)
[REPX]   [Prophet] 완료  첫값=1.13e+08 (메모리: 1593.6 MB)
[REPX]   [LSTM] 시작  (메모리: 1593.6 MB)
[메모리] forecast_lstm 실행 전: 1593.60 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1592.32 MB (변화: -1.28 MB)
[REPX]   [LSTM] 완료  첫값=1.23e+08 (메모리: 1592.3 MB)
[REPX]   [Theta] 시작  (메모리: 1592.3 MB)
[메모리] forecast_theta 실행 전: 1592.32 MB
[메모리] forecast_theta 실행 후: 1592.32 MB (변화: +0.00 MB)
[REPX]   [Theta] 완료  첫값=1.27e+08 (메모리: 1592.3 MB)
[REPX]   [DB] 93행 저장 완료
[PROGRESS] [ 266/500] ( 53.2%)  >>  KRNT
[KRNT]   45분기 | 2015-03-31 ~ 2026-03-31
[KRNT]   [SARIMA] 시작  (메모리: 1592.3 MB)
[메모리] forecast_sarima 실행 전: 1592.32 MB
[메모리] find_best_sarima_params 실행 전: 1592.32 MB
[메모리] find_best_sarima_params 실행 후: 1592.32 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1592.32 MB (변화: +0.00 MB)
[KRNT]   [SARIMA] 완료  첫값=6.30e+07 (메모리: 1592.3 MB)
[KRNT]   [ETS] 시작  (메모리: 1592.3 MB)
[메모리] forecast_ets 실행 전: 1592.32 MB
[메모리] forecast_ets 실행 후: 1592.32 MB (변화: +0.01 MB)
[KRNT]   [ETS] 완료  첫값=6.47e+07 (메모리: 1592.3 MB)
[KRNT]   [Prophet] 시작  (메모리: 1592.3 MB)

01:52:26 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1592.32 MB

01:52:26 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.73 MB (변화: +1.40 MB)
[KRNT]   [Prophet] 완료  첫값=6.90e+07 (메모리: 1593.7 MB)
[KRNT]   [LSTM] 시작  (메모리: 1593.7 MB)
[메모리] forecast_lstm 실행 전: 1593.73 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1592.93 MB (변화: -0.80 MB)
[KRNT]   [LSTM] 완료  첫값=5.42e+07 (메모리: 1592.9 MB)
[KRNT]   [Theta] 시작  (메모리: 1592.9 MB)
[메모리] forecast_theta 실행 전: 1592.93 MB
[메모리] forecast_theta 실행 후: 1592.93 MB (변화: +0.00 MB)
[KRNT]   [Theta] 완료  첫값=6.40e+07 (메모리: 1592.9 MB)
[KRNT]   [DB] 93행 저장 완료
[PROGRESS] [ 267/500] ( 53.4%)  >>  EU
[EU]   45분기 | 2015-03-31 ~ 2026-03-31
[EU]   [SARIMA] 시작  (메모리: 1592.9 MB)
[메모리] forecast_sarima 실행 전: 1592.93 MB
[메모리] find_best_sarima_params 실행 전: 1592.93 MB
[메모리] find_best_sarima_params 실행 후: 1592.93 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1592.93 MB (변화: +0.00 MB)
[EU]   [SARIMA] 완료  첫값=6.48e+06 (메모리: 1592.9 MB)
[EU]   [ETS] 시작  (메모리: 1592.9 MB)
[메모리] forecast_ets 실행 전: 1592.93 MB
[메모리] forecast_ets 실행 후: 1592.93 MB (변화: +0.00 MB)
[EU]   [ETS] 완료  첫값=4.52e+06 (메모리: 1592.9 MB)
[EU]   [Prophet] 시작  (메모리: 1592.9 MB)

01:52:46 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1592.93 MB

01:52:46 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1592.53 MB (변화: -0.40 MB)
[EU]   [Prophet] 완료  첫값=8.26e+06 (메모리: 1592.5 MB)
[EU]   [LSTM] 시작  (메모리: 1592.5 MB)
[메모리] forecast_lstm 실행 전: 1592.53 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1592.40 MB (변화: -0.13 MB)
[EU]   [LSTM] 완료  첫값=1.02e+07 (메모리: 1592.4 MB)
[EU]   [Theta] 시작  (메모리: 1592.4 MB)
[메모리] forecast_theta 실행 전: 1592.40 MB
[메모리] forecast_theta 실행 후: 1592.40 MB (변화: +0.00 MB)
[EU]   [Theta] 완료  첫값=7.49e+06 (메모리: 1592.4 MB)
[EU]   [DB] 93행 저장 완료
[PROGRESS] [ 268/500] ( 53.6%)  >>  SNDA
[SNDA]   45분기 | 2015-03-31 ~ 2026-03-31
[SNDA]   [SARIMA] 시작  (메모리: 1592.4 MB)
[메모리] forecast_sarima 실행 전: 1592.40 MB
[메모리] find_best_sarima_params 실행 전: 1592.40 MB
[메모리] find_best_sarima_params 실행 후: 1592.40 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1592.40 MB (변화: +0.00 MB)
[SNDA]   [SARIMA] 완료  첫값=9.80e+07 (메모리: 1592.4 MB)
[SNDA]   [ETS] 시작  (메모리: 1592.4 MB)
[메모리] forecast_ets 실행 전: 1592.40 MB
[메모리] forecast_ets 실행 후: 1592.40 MB (변화: +0.00 MB)
[SNDA]   [ETS] 완료  첫값=1.02e+08 (메모리: 1592.4 MB)
[SNDA]   [Prophet] 시작  (메모리: 1592.4 MB)

01:53:08 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1592.40 MB

01:53:08 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1592.83 MB (변화: +0.43 MB)
[SNDA]   [Prophet] 완료  첫값=6.45e+07 (메모리: 1592.8 MB)
[SNDA]   [LSTM] 시작  (메모리: 1592.8 MB)
[메모리] forecast_lstm 실행 전: 1592.83 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1592.44 MB (변화: -0.39 MB)
[SNDA]   [LSTM] 완료  첫값=9.84e+07 (메모리: 1592.4 MB)
[SNDA]   [Theta] 시작  (메모리: 1592.4 MB)
[메모리] forecast_theta 실행 전: 1592.44 MB
[메모리] forecast_theta 실행 후: 1592.44 MB (변화: +0.00 MB)
[SNDA]   [Theta] 완료  첫값=9.82e+07 (메모리: 1592.4 MB)
[SNDA]   [DB] 93행 저장 완료
[PROGRESS] [ 269/500] ( 53.8%)  >>  CEVA
[CEVA]   45분기 | 2015-03-31 ~ 2026-03-31
[CEVA]   [SARIMA] 시작  (메모리: 1592.4 MB)
[메모리] forecast_sarima 실행 전: 1592.44 MB
[메모리] find_best_sarima_params 실행 전: 1592.44 MB
[메모리] find_best_sarima_params 실행 후: 1592.44 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1592.44 MB (변화: +0.00 MB)
[CEVA]   [SARIMA] 완료  첫값=2.88e+07 (메모리: 1592.4 MB)
[CEVA]   [ETS] 시작  (메모리: 1592.4 MB)
[메모리] forecast_ets 실행 전: 1592.44 MB
[메모리] forecast_ets 실행 후: 1592.44 MB (변화: +0.00 MB)
[CEVA]   [ETS] 완료  첫값=2.93e+07 (메모리: 1592.4 MB)
[CEVA]   [Prophet] 시작  (메모리: 1592.4 MB)

01:53:34 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1592.44 MB

01:53:35 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1592.45 MB (변화: +0.01 MB)
[CEVA]   [Prophet] 완료  첫값=3.11e+07 (메모리: 1592.4 MB)
[CEVA]   [LSTM] 시작  (메모리: 1592.4 MB)
[메모리] forecast_lstm 실행 전: 1592.45 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1592.28 MB (변화: -0.17 MB)
[CEVA]   [LSTM] 완료  첫값=2.74e+07 (메모리: 1592.3 MB)
[CEVA]   [Theta] 시작  (메모리: 1592.3 MB)
[메모리] forecast_theta 실행 전: 1592.28 MB
[메모리] forecast_theta 실행 후: 1592.28 MB (변화: +0.00 MB)
[CEVA]   [Theta] 완료  첫값=2.92e+07 (메모리: 1592.3 MB)
[CEVA]   [DB] 93행 저장 완료
[PROGRESS] [ 270/500] ( 54.0%)  >>  HOV
[HOV]   45분기 | 2015-03-31 ~ 2026-03-31
[HOV]   [SARIMA] 시작  (메모리: 1592.3 MB)
[메모리] forecast_sarima 실행 전: 1592.28 MB
[메모리] find_best_sarima_params 실행 전: 1592.28 MB
[메모리] find_best_sarima_params 실행 후: 1592.28 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1592.28 MB (변화: +0.00 MB)
[HOV]   [SARIMA] 완료  첫값=6.82e+08 (메모리: 1592.3 MB)
[HOV]   [ETS] 시작  (메모리: 1592.3 MB)
[메모리] forecast_ets 실행 전: 1592.28 MB
[메모리] forecast_ets 실행 후: 1592.28 MB (변화: +0.00 MB)
[HOV]   [ETS] 완료  첫값=8.42e+08 (메모리: 1592.3 MB)
[HOV]   [Prophet] 시작  (메모리: 1592.3 MB)

01:53:57 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1592.28 MB

01:53:57 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1592.30 MB (변화: +0.02 MB)
[HOV]   [Prophet] 완료  첫값=7.75e+08 (메모리: 1592.3 MB)
[HOV]   [LSTM] 시작  (메모리: 1592.3 MB)
[메모리] forecast_lstm 실행 전: 1592.30 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.29 MB (변화: +0.99 MB)
[HOV]   [LSTM] 완료  첫값=7.10e+08 (메모리: 1593.3 MB)
[HOV]   [Theta] 시작  (메모리: 1593.3 MB)
[메모리] forecast_theta 실행 전: 1593.29 MB
[메모리] forecast_theta 실행 후: 1593.29 MB (변화: +0.00 MB)
[HOV]   [Theta] 완료  첫값=8.47e+08 (메모리: 1593.3 MB)
[HOV]   [DB] 93행 저장 완료
[PROGRESS] [ 271/500] ( 54.2%)  >>  CMCO
[CMCO]   45분기 | 2015-03-31 ~ 2026-03-31
[CMCO]   [SARIMA] 시작  (메모리: 1593.3 MB)
[메모리] forecast_sarima 실행 전: 1593.29 MB
[메모리] find_best_sarima_params 실행 전: 1593.29 MB
[메모리] find_best_sarima_params 실행 후: 1593.29 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.29 MB (변화: +0.00 MB)
[CMCO]   [SARIMA] 완료  첫값=2.62e+08 (메모리: 1593.3 MB)
[CMCO]   [ETS] 시작  (메모리: 1593.3 MB)
[메모리] forecast_ets 실행 전: 1593.29 MB
[메모리] forecast_ets 실행 후: 1593.29 MB (변화: +0.00 MB)
[CMCO]   [ETS] 완료  첫값=2.46e+08 (메모리: 1593.3 MB)
[CMCO]   [Prophet] 시작  (메모리: 1593.3 MB)
[메모리] forecast_prophet 실행 전: 1593.29 MB

01:54:16 - cmdstanpy - INFO - Chain [1] start processing
01:54:16 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.30 MB (변화: +0.00 MB)
[CMCO]   [Prophet] 완료  첫값=2.63e+08 (메모리: 1593.3 MB)
[CMCO]   [LSTM] 시작  (메모리: 1593.3 MB)
[메모리] forecast_lstm 실행 전: 1593.30 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.32 MB (변화: +0.02 MB)
[CMCO]   [LSTM] 완료  첫값=2.45e+08 (메모리: 1593.3 MB)
[CMCO]   [Theta] 시작  (메모리: 1593.3 MB)
[메모리] forecast_theta 실행 전: 1593.32 MB
[메모리] forecast_theta 실행 후: 1593.32 MB (변화: +0.00 MB)
[CMCO]   [Theta] 완료  첫값=2.46e+08 (메모리: 1593.3 MB)
[CMCO]   [DB] 93행 저장 완료
[PROGRESS] [ 272/500] ( 54.4%)  >>  LAB
[LAB]   45분기 | 2015-03-31 ~ 2026-03-31
[LAB]   [SARIMA] 시작  (메모리: 1593.3 MB)
[메모리] forecast_sarima 실행 전: 1593.32 MB
[메모리] find_best_sarima_params 실행 전: 1593.32 MB
[메모리] find_best_sarima_params 실행 후: 1593.32 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.32 MB (변화: +0.00 MB)
[LAB]   [SARIMA] 완료  첫값=2.43e+07 (메모리: 1593.3 MB)
[LAB]   [ETS] 시작  (메모리: 1593.3 MB)
[메모리] forecast_ets 실행 전: 1593.32 MB
[메모리] forecast_ets 실행 후: 1593.32 MB (변화: +0.00 MB)
[LAB]   [ETS] 완료  첫값=1.69e+07 (메모리: 1593.3 MB)
[LAB]   [Prophet] 시작  (메모리: 1593.3 MB)

01:54:41 - cmdstanpy - INFO - Chain [1] start processing
01:54:41 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1593.32 MB
[메모리] forecast_prophet 실행 후: 1593.32 MB (변화: +0.00 MB)
[LAB]   [Prophet] 완료  첫값=3.04e+07 (메모리: 1593.3 MB)
[LAB]   [LSTM] 시작  (메모리: 1593.3 MB)
[메모리] forecast_lstm 실행 전: 1593.32 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.29 MB (변화: -0.03 MB)
[LAB]   [LSTM] 완료  첫값=2.96e+07 (메모리: 1593.3 MB)
[LAB]   [Theta] 시작  (메모리: 1592.2 MB)
[메모리] forecast_theta 실행 전: 1592.18 MB
[메모리] forecast_theta 실행 후: 1592.18 MB (변화: +0.00 MB)
[LAB]   [Theta] 완료  첫값=2.80e+07 (메모리: 1592.2 MB)
[LAB]   [DB] 93행 저장 완료
[PROGRESS] [ 273/500] ( 54.6%)  >>  TBN
[TBN] [SKIP] [TBN] 'sale' 관측치 부족: 27개 < 최소 28개
[PROGRESS] [ 274/500] ( 54.8%)  >>  APEN
[APEN]   45분기 | 2015-03-31 ~ 2026-03-31
[APEN]   [SARIMA] 시작  (메모리: 1592.2 MB)
[메모리] forecast_sarima 실행 전: 1592.18 MB
[메모리] find_best_sarima_params 실행 전: 1592.18 MB
[메모리] find_best_sarima_params 실행 후: 1592.18 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1592.18 MB (변화: +0.00 MB)
[APEN]   [SARIMA] 완료  첫값=2.13e+07 (메모리: 1592.2 MB)
[APEN]   [ETS] 시작  (메모리: 1592.2 MB)
[메모리] forecast_ets 실행 전: 1592.18 MB
[메모리] forecast_ets 실행 후: 1592.18 MB (변화: +0.00 MB)
[APEN]   [ETS] 완료  첫값=2.10e+07 (메모리: 1592.2 MB)
[APEN]   [Prophet] 시작  (메모리: 1592.2 MB)

01:55:03 - cmdstanpy - INFO - Chain [1] start processing
01:55:03 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1592.18 MB
[메모리] forecast_prophet 실행 후: 1592.60 MB (변화: +0.42 MB)
[APEN]   [Prophet] 완료  첫값=2.37e+07 (메모리: 1592.6 MB)
[APEN]   [LSTM] 시작  (메모리: 1592.6 MB)
[메모리] forecast_lstm 실행 전: 1592.60 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1592.17 MB (변화: -0.43 MB)
[APEN]   [LSTM] 완료  첫값=1.85e+07 (메모리: 1592.2 MB)
[APEN]   [Theta] 시작  (메모리: 1592.2 MB)
[메모리] forecast_theta 실행 전: 1592.17 MB
[메모리] forecast_theta 실행 후: 1592.17 MB (변화: +0.00 MB)
[APEN]   [Theta] 완료  첫값=2.25e+07 (메모리: 1592.2 MB)
[APEN]   [DB] 93행 저장 완료
[PROGRESS] [ 275/500] ( 55.0%)  >>  CASS
[CASS]   45분기 | 2015-03-31 ~ 2026-03-31
[CASS]   [SARIMA] 시작  (메모리: 1592.2 MB)
[메모리] forecast_sarima 실행 전: 1592.17 MB
[메모리] find_best_sarima_params 실행 전: 1592.17 MB
[메모리] find_best_sarima_params 실행 후: 1592.17 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1592.17 MB (변화: +0.00 MB)
[CASS]   [SARIMA] 완료  첫값=5.01e+07 (메모리: 1592.2 MB)
[CASS]   [ETS] 시작  (메모리: 1592.2 MB)
[메모리] forecast_ets 실행 전: 1592.17 MB
[메모리] forecast_ets 실행 후: 1592.18 MB (변화: +0.01 MB)
[CASS]   [ETS] 완료  첫값=4.94e+07 (메모리: 1592.2 MB)
[CASS]   [Prophet] 시작  (메모리: 1592.2 MB)

01:55:23 - cmdstanpy - INFO - Chain [1] start processing
01:55:23 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1592.18 MB
[메모리] forecast_prophet 실행 후: 1592.19 MB (변화: +0.02 MB)
[CASS]   [Prophet] 완료  첫값=5.45e+07 (메모리: 1592.2 MB)
[CASS]   [LSTM] 시작  (메모리: 1592.2 MB)
[메모리] forecast_lstm 실행 전: 1592.19 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.16 MB (변화: +0.97 MB)
[CASS]   [LSTM] 완료  첫값=5.23e+07 (메모리: 1593.2 MB)
[CASS]   [Theta] 시작  (메모리: 1593.2 MB)
[메모리] forecast_theta 실행 전: 1593.16 MB
[메모리] forecast_theta 실행 후: 1593.16 MB (변화: +0.00 MB)
[CASS]   [Theta] 완료  첫값=4.90e+07 (메모리: 1593.2 MB)
[CASS]   [DB] 93행 저장 완료
[PROGRESS] [ 276/500] ( 55.2%)  >>  BDSI
[BDSI]   45분기 | 2015-03-31 ~ 2026-03-31
[BDSI]   [SARIMA] 시작  (메모리: 1593.2 MB)
[메모리] forecast_sarima 실행 전: 1593.16 MB
[메모리] find_best_sarima_params 실행 전: 1593.16 MB
[메모리] find_best_sarima_params 실행 후: 1593.16 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.16 MB (변화: +0.00 MB)
[BDSI]   [SARIMA] 완료  첫값=4.35e+07 (메모리: 1593.2 MB)
[BDSI]   [ETS] 시작  (메모리: 1593.2 MB)
[메모리] forecast_ets 실행 전: 1593.16 MB
[메모리] forecast_ets 실행 후: 1593.17 MB (변화: +0.00 MB)
[BDSI]   [ETS] 완료  첫값=3.62e+07 (메모리: 1593.2 MB)
[BDSI]   [Prophet] 시작  (메모리: 1593.2 MB)

01:55:41 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1593.17 MB

01:55:42 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.18 MB (변화: +0.01 MB)
[BDSI]   [Prophet] 완료  첫값=5.37e+07 (메모리: 1593.2 MB)
[BDSI]   [LSTM] 시작  (메모리: 1593.2 MB)
[메모리] forecast_lstm 실행 전: 1593.18 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.20 MB (변화: +0.02 MB)
[BDSI]   [LSTM] 완료  첫값=4.47e+07 (메모리: 1593.2 MB)
[BDSI]   [Theta] 시작  (메모리: 1593.2 MB)
[메모리] forecast_theta 실행 전: 1593.20 MB
[메모리] forecast_theta 실행 후: 1593.20 MB (변화: +0.00 MB)
[BDSI]   [Theta] 완료  첫값=4.40e+07 (메모리: 1593.2 MB)
[BDSI]   [DB] 93행 저장 완료
[PROGRESS] [ 277/500] ( 55.4%)  >>  CTO
[CTO]   45분기 | 2015-03-31 ~ 2026-03-31
[CTO]   [SARIMA] 시작  (메모리: 1593.2 MB)
[메모리] forecast_sarima 실행 전: 1593.20 MB
[메모리] find_best_sarima_params 실행 전: 1593.20 MB
[메모리] find_best_sarima_params 실행 후: 1593.20 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.20 MB (변화: +0.00 MB)
[CTO]   [SARIMA] 완료  첫값=4.04e+07 (메모리: 1593.2 MB)
[CTO]   [ETS] 시작  (메모리: 1593.2 MB)
[메모리] forecast_ets 실행 전: 1593.20 MB
[메모리] forecast_ets 실행 후: 1593.21 MB (변화: +0.00 MB)
[CTO]   [ETS] 완료  첫값=3.56e+07 (메모리: 1593.2 MB)
[CTO]   [Prophet] 시작  (메모리: 1593.2 MB)

01:56:06 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1593.21 MB

01:56:06 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.21 MB (변화: +0.01 MB)
[CTO]   [Prophet] 완료  첫값=3.27e+07 (메모리: 1593.2 MB)
[CTO]   [LSTM] 시작  (메모리: 1593.2 MB)
[메모리] forecast_lstm 실행 전: 1593.21 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.21 MB (변화: -0.00 MB)
[CTO]   [LSTM] 완료  첫값=3.71e+07 (메모리: 1593.2 MB)
[CTO]   [Theta] 시작  (메모리: 1593.2 MB)
[메모리] forecast_theta 실행 전: 1593.21 MB
[메모리] forecast_theta 실행 후: 1593.21 MB (변화: +0.00 MB)
[CTO]   [Theta] 완료  첫값=3.35e+07 (메모리: 1593.2 MB)
[CTO]   [DB] 93행 저장 완료
[PROGRESS] [ 278/500] ( 55.6%)  >>  LE
[LE]   45분기 | 2015-03-31 ~ 2026-03-31
[LE]   [SARIMA] 시작  (메모리: 1593.2 MB)
[메모리] forecast_sarima 실행 전: 1593.21 MB
[메모리] find_best_sarima_params 실행 전: 1593.21 MB
[메모리] find_best_sarima_params 실행 후: 1593.21 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.21 MB (변화: +0.00 MB)
[LE]   [SARIMA] 완료  첫값=2.32e+08 (메모리: 1593.2 MB)
[LE]   [ETS] 시작  (메모리: 1593.2 MB)
[메모리] forecast_ets 실행 전: 1593.21 MB
[메모리] forecast_ets 실행 후: 1593.21 MB (변화: +0.00 MB)
[LE]   [ETS] 완료  첫값=2.16e+08 (메모리: 1593.2 MB)
[LE]   [Prophet] 시작  (메모리: 1593.2 MB)

01:56:28 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1593.21 MB

01:56:28 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.22 MB (변화: +0.01 MB)
[LE]   [Prophet] 완료  첫값=3.56e+08 (메모리: 1593.2 MB)
[LE]   [LSTM] 시작  (메모리: 1593.2 MB)
[메모리] forecast_lstm 실행 전: 1593.22 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.20 MB (변화: -0.02 MB)
[LE]   [LSTM] 완료  첫값=3.41e+08 (메모리: 1593.2 MB)
[LE]   [Theta] 시작  (메모리: 1593.2 MB)
[메모리] forecast_theta 실행 전: 1593.20 MB
[메모리] forecast_theta 실행 후: 1593.20 MB (변화: +0.00 MB)
[LE]   [Theta] 완료  첫값=2.17e+08 (메모리: 1593.2 MB)
[LE]   [DB] 93행 저장 완료
[PROGRESS] [ 279/500] ( 55.8%)  >>  KOP
[KOP]   45분기 | 2015-03-31 ~ 2026-03-31
[KOP]   [SARIMA] 시작  (메모리: 1593.2 MB)
[메모리] forecast_sarima 실행 전: 1593.20 MB
[메모리] find_best_sarima_params 실행 전: 1593.20 MB
[메모리] find_best_sarima_params 실행 후: 1593.20 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.20 MB (변화: +0.00 MB)
[KOP]   [SARIMA] 완료  첫값=5.25e+08 (메모리: 1593.2 MB)
[KOP]   [ETS] 시작  (메모리: 1593.2 MB)
[메모리] forecast_ets 실행 전: 1593.20 MB
[메모리] forecast_ets 실행 후: 1593.21 MB (변화: +0.00 MB)
[KOP]   [ETS] 완료  첫값=5.33e+08 (메모리: 1593.2 MB)
[KOP]   [Prophet] 시작  (메모리: 1593.2 MB)

01:56:49 - cmdstanpy - INFO - Chain [1] start processing
01:56:49 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1593.21 MB
[메모리] forecast_prophet 실행 후: 1593.22 MB (변화: +0.02 MB)
[KOP]   [Prophet] 완료  첫값=5.28e+08 (메모리: 1593.2 MB)
[KOP]   [LSTM] 시작  (메모리: 1593.2 MB)
[메모리] forecast_lstm 실행 전: 1593.22 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.18 MB (변화: -0.04 MB)
[KOP]   [LSTM] 완료  첫값=4.90e+08 (메모리: 1593.2 MB)
[KOP]   [Theta] 시작  (메모리: 1593.2 MB)
[메모리] forecast_theta 실행 전: 1593.18 MB
[메모리] forecast_theta 실행 후: 1593.18 MB (변화: +0.00 MB)
[KOP]   [Theta] 완료  첫값=5.33e+08 (메모리: 1593.2 MB)
[KOP]   [DB] 93행 저장 완료
[PROGRESS] [ 280/500] ( 56.0%)  >>  TRNS
[TRNS]   45분기 | 2015-03-31 ~ 2026-03-31
[TRNS]   [SARIMA] 시작  (메모리: 1593.2 MB)
[메모리] forecast_sarima 실행 전: 1593.18 MB
[메모리] find_best_sarima_params 실행 전: 1593.18 MB
[메모리] find_best_sarima_params 실행 후: 1593.18 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.18 MB (변화: +0.00 MB)
[TRNS]   [SARIMA] 완료  첫값=7.23e+07 (메모리: 1593.2 MB)
[TRNS]   [ETS] 시작  (메모리: 1593.2 MB)
[메모리] forecast_ets 실행 전: 1593.18 MB
[메모리] forecast_ets 실행 후: 1593.18 MB (변화: +0.00 MB)
[TRNS]   [ETS] 완료  첫값=6.93e+07 (메모리: 1593.2 MB)
[TRNS]   [Prophet] 시작  (메모리: 1593.2 MB)
[메모리] forecast_prophet 실행 전: 1593.18 MB

01:57:09 - cmdstanpy - INFO - Chain [1] start processing
01:57:09 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.19 MB (변화: +0.01 MB)
[TRNS]   [Prophet] 완료  첫값=7.96e+07 (메모리: 1593.2 MB)
[TRNS]   [LSTM] 시작  (메모리: 1593.2 MB)
[메모리] forecast_lstm 실행 전: 1593.19 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.22 MB (변화: +0.03 MB)
[TRNS]   [LSTM] 완료  첫값=9.34e+07 (메모리: 1593.2 MB)
[TRNS]   [Theta] 시작  (메모리: 1593.2 MB)
[메모리] forecast_theta 실행 전: 1593.22 MB
[메모리] forecast_theta 실행 후: 1593.22 MB (변화: +0.00 MB)
[TRNS]   [Theta] 완료  첫값=6.85e+07 (메모리: 1593.2 MB)
[TRNS]   [DB] 93행 저장 완료
[PROGRESS] [ 281/500] ( 56.2%)  >>  ANGI
[ANGI]   45분기 | 2015-03-31 ~ 2026-03-31
[ANGI]   [SARIMA] 시작  (메모리: 1593.2 MB)
[메모리] forecast_sarima 실행 전: 1593.22 MB
[메모리] find_best_sarima_params 실행 전: 1593.22 MB
[메모리] find_best_sarima_params 실행 후: 1593.22 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.22 MB (변화: +0.00 MB)
[ANGI]   [SARIMA] 완료  첫값=2.59e+08 (메모리: 1593.2 MB)
[ANGI]   [ETS] 시작  (메모리: 1593.2 MB)
[메모리] forecast_ets 실행 전: 1593.22 MB
[메모리] forecast_ets 실행 후: 1593.22 MB (변화: +0.00 MB)
[ANGI]   [ETS] 완료  첫값=2.58e+08 (메모리: 1593.2 MB)
[ANGI]   [Prophet] 시작  (메모리: 1593.2 MB)

01:57:26 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1593.22 MB

01:57:27 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.24 MB (변화: +0.02 MB)
[ANGI]   [Prophet] 완료  첫값=4.07e+08 (메모리: 1593.2 MB)
[ANGI]   [LSTM] 시작  (메모리: 1593.2 MB)
[메모리] forecast_lstm 실행 전: 1593.24 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1591.09 MB (변화: -2.14 MB)
[ANGI]   [LSTM] 완료  첫값=2.86e+08 (메모리: 1591.1 MB)
[ANGI]   [Theta] 시작  (메모리: 1591.1 MB)
[메모리] forecast_theta 실행 전: 1591.09 MB
[메모리] forecast_theta 실행 후: 1591.09 MB (변화: +0.00 MB)
[ANGI]   [Theta] 완료  첫값=2.56e+08 (메모리: 1591.1 MB)
[ANGI]   [DB] 93행 저장 완료
[PROGRESS] [ 282/500] ( 56.4%)  >>  LXRX
[LXRX]   45분기 | 2015-03-31 ~ 2026-03-31
[LXRX]   [SARIMA] 시작  (메모리: 1591.1 MB)
[메모리] forecast_sarima 실행 전: 1591.09 MB
[메모리] find_best_sarima_params 실행 전: 1591.09 MB
[메모리] find_best_sarima_params 실행 후: 1591.09 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1591.09 MB (변화: +0.00 MB)
[LXRX]   [SARIMA] 완료  첫값=2.55e+07 (메모리: 1591.1 MB)
[LXRX]   [ETS] 시작  (메모리: 1591.1 MB)
[메모리] forecast_ets 실행 전: 1591.09 MB
[메모리] forecast_ets 실행 후: 1591.09 MB (변화: +0.00 MB)
[LXRX]   [ETS] 완료  첫값=2.06e+07 (메모리: 1591.1 MB)
[LXRX]   [Prophet] 시작  (메모리: 1591.1 MB)

01:57:43 - cmdstanpy - INFO - Chain [1] start processing
01:57:43 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1591.09 MB
[메모리] forecast_prophet 실행 후: 1591.10 MB (변화: +0.01 MB)
[LXRX]   [Prophet] 완료  첫값=3.42e+06 (메모리: 1591.1 MB)
[LXRX]   [LSTM] 시작  (메모리: 1591.1 MB)
[메모리] forecast_lstm 실행 전: 1591.10 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1592.11 MB (변화: +1.01 MB)
[LXRX]   [LSTM] 완료  첫값=1.31e+07 (메모리: 1592.1 MB)
[LXRX]   [Theta] 시작  (메모리: 1592.1 MB)
[메모리] forecast_theta 실행 전: 1592.11 MB
[메모리] forecast_theta 실행 후: 1592.11 MB (변화: +0.00 MB)
[LXRX]   [Theta] 완료  첫값=2.85e+07 (메모리: 1592.1 MB)
[LXRX]   [DB] 93행 저장 완료
[PROGRESS] [ 283/500] ( 56.6%)  >>  VPG
[VPG]   45분기 | 2015-03-31 ~ 2026-03-31
[VPG]   [SARIMA] 시작  (메모리: 1592.1 MB)
[메모리] forecast_sarima 실행 전: 1592.11 MB
[메모리] find_best_sarima_params 실행 전: 1592.11 MB
[메모리] find_best_sarima_params 실행 후: 1592.11 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1592.11 MB (변화: +0.00 MB)
[VPG]   [SARIMA] 완료  첫값=8.12e+07 (메모리: 1592.1 MB)
[VPG]   [ETS] 시작  (메모리: 1592.1 MB)
[메모리] forecast_ets 실행 전: 1592.11 MB
[메모리] forecast_ets 실행 후: 1592.12 MB (변화: +0.01 MB)
[VPG]   [ETS] 완료  첫값=7.85e+07 (메모리: 1592.1 MB)
[VPG]   [Prophet] 시작  (메모리: 1592.1 MB)

01:58:02 - cmdstanpy - INFO - Chain [1] start processing
01:58:02 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1592.12 MB
[메모리] forecast_prophet 실행 후: 1592.12 MB (변화: +0.00 MB)
[VPG]   [Prophet] 완료  첫값=8.80e+07 (메모리: 1592.1 MB)
[VPG]   [LSTM] 시작  (메모리: 1592.1 MB)
[메모리] forecast_lstm 실행 전: 1592.12 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1592.16 MB (변화: +0.04 MB)
[VPG]   [LSTM] 완료  첫값=7.90e+07 (메모리: 1592.2 MB)
[VPG]   [Theta] 시작  (메모리: 1592.2 MB)
[메모리] forecast_theta 실행 전: 1592.16 MB
[메모리] forecast_theta 실행 후: 1592.16 MB (변화: +0.00 MB)
[VPG]   [Theta] 완료  첫값=7.76e+07 (메모리: 1592.2 MB)
[VPG]   [DB] 93행 저장 완료
[PROGRESS] [ 284/500] ( 56.8%)  >>  BYON
[BYON]   45분기 | 2015-03-31 ~ 2026-03-31
[BYON]   [SARIMA] 시작  (메모리: 1592.2 MB)
[메모리] forecast_sarima 실행 전: 1592.16 MB
[메모리] find_best_sarima_params 실행 전: 1592.16 MB
[메모리] find_best_sarima_params 실행 후: 1592.16 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1592.16 MB (변화: +0.00 MB)
[BYON]   [SARIMA] 완료  첫값=2.77e+08 (메모리: 1592.2 MB)
[BYON]   [ETS] 시작  (메모리: 1592.2 MB)
[메모리] forecast_ets 실행 전: 1592.16 MB
[메모리] forecast_ets 실행 후: 1592.16 MB (변화: +0.00 MB)
[BYON]   [ETS] 완료  첫값=2.92e+08 (메모리: 1592.2 MB)
[BYON]   [Prophet] 시작  (메모리: 1592.2 MB)

01:58:23 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1592.16 MB

01:58:23 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1592.17 MB (변화: +0.01 MB)
[BYON]   [Prophet] 완료  첫값=3.85e+08 (메모리: 1592.2 MB)
[BYON]   [LSTM] 시작  (메모리: 1592.2 MB)
[메모리] forecast_lstm 실행 전: 1592.17 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1592.17 MB (변화: +0.00 MB)
[BYON]   [LSTM] 완료  첫값=3.88e+08 (메모리: 1592.2 MB)
[BYON]   [Theta] 시작  (메모리: 1592.2 MB)
[메모리] forecast_theta 실행 전: 1592.17 MB
[메모리] forecast_theta 실행 후: 1592.17 MB (변화: +0.00 MB)
[BYON]   [Theta] 완료  첫값=2.98e+08 (메모리: 1592.2 MB)
[BYON]   [DB] 93행 저장 완료
[PROGRESS] [ 285/500] ( 57.0%)  >>  RYAM
[RYAM]   45분기 | 2015-03-31 ~ 2026-03-31
[RYAM]   [SARIMA] 시작  (메모리: 1592.2 MB)
[메모리] forecast_sarima 실행 전: 1592.17 MB
[메모리] find_best_sarima_params 실행 전: 1592.17 MB
[메모리] find_best_sarima_params 실행 후: 1592.17 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1592.17 MB (변화: +0.00 MB)
[RYAM]   [SARIMA] 완료  첫값=3.53e+08 (메모리: 1592.2 MB)
[RYAM]   [ETS] 시작  (메모리: 1592.2 MB)
[메모리] forecast_ets 실행 전: 1592.17 MB
[메모리] forecast_ets 실행 후: 1592.17 MB (변화: +0.00 MB)
[RYAM]   [ETS] 완료  첫값=3.51e+08 (메모리: 1592.2 MB)
[RYAM]   [Prophet] 시작  (메모리: 1592.2 MB)

01:58:42 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1592.17 MB

01:58:42 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1592.18 MB (변화: +0.00 MB)
[RYAM]   [Prophet] 완료  첫값=4.48e+08 (메모리: 1592.2 MB)
[RYAM]   [LSTM] 시작  (메모리: 1592.2 MB)
[메모리] forecast_lstm 실행 전: 1592.18 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1592.12 MB (변화: -0.05 MB)
[RYAM]   [LSTM] 완료  첫값=3.81e+08 (메모리: 1592.1 MB)
[RYAM]   [Theta] 시작  (메모리: 1592.1 MB)
[메모리] forecast_theta 실행 전: 1592.12 MB
[메모리] forecast_theta 실행 후: 1592.12 MB (변화: +0.00 MB)
[RYAM]   [Theta] 완료  첫값=3.50e+08 (메모리: 1592.1 MB)
[RYAM]   [DB] 93행 저장 완료
[PROGRESS] [ 286/500] ( 57.2%)  >>  HY
[HY]   45분기 | 2015-03-31 ~ 2026-03-31
[HY]   [SARIMA] 시작  (메모리: 1592.1 MB)
[메모리] forecast_sarima 실행 전: 1592.12 MB
[메모리] find_best_sarima_params 실행 전: 1592.12 MB
[메모리] find_best_sarima_params 실행 후: 1592.12 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1592.12 MB (변화: +0.00 MB)
[HY]   [SARIMA] 완료  첫값=1.03e+09 (메모리: 1592.1 MB)
[HY]   [ETS] 시작  (메모리: 1592.1 MB)
[메모리] forecast_ets 실행 전: 1592.12 MB
[메모리] forecast_ets 실행 후: 1592.13 MB (변화: +0.00 MB)
[HY]   [ETS] 완료  첫값=1.00e+09 (메모리: 1592.1 MB)
[HY]   [Prophet] 시작  (메모리: 1592.1 MB)
[메모리] forecast_prophet 실행 전: 1592.13 MB

01:59:08 - cmdstanpy - INFO - Chain [1] start processing
01:59:08 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1592.13 MB (변화: +0.00 MB)
[HY]   [Prophet] 완료  첫값=1.05e+09 (메모리: 1592.1 MB)
[HY]   [LSTM] 시작  (메모리: 1592.1 MB)
[메모리] forecast_lstm 실행 전: 1592.13 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1592.15 MB (변화: +0.02 MB)
[HY]   [LSTM] 완료  첫값=1.03e+09 (메모리: 1592.2 MB)
[HY]   [Theta] 시작  (메모리: 1592.2 MB)
[메모리] forecast_theta 실행 전: 1592.15 MB
[메모리] forecast_theta 실행 후: 1592.15 MB (변화: +0.00 MB)
[HY]   [Theta] 완료  첫값=9.94e+08 (메모리: 1592.2 MB)
[HY]   [DB] 93행 저장 완료
[PROGRESS] [ 287/500] ( 57.4%)  >>  RGLS
[RGLS]   45분기 | 2015-03-31 ~ 2026-03-31
[RGLS]   [SARIMA] 시작  (메모리: 1592.2 MB)
[메모리] forecast_sarima 실행 전: 1592.15 MB
[메모리] find_best_sarima_params 실행 전: 1592.15 MB
[메모리] find_best_sarima_params 실행 후: 1592.15 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1592.15 MB (변화: +0.00 MB)
[RGLS]   [SARIMA] 완료  첫값=-6.27e+05 (메모리: 1592.2 MB)
[RGLS]   [ETS] 시작  (메모리: 1592.2 MB)
[메모리] forecast_ets 실행 전: 1592.15 MB
[메모리] forecast_ets 실행 후: 1592.16 MB (변화: +0.01 MB)
[RGLS]   [ETS] 완료  첫값=-9.48e+05 (메모리: 1592.2 MB)
[RGLS]   [Prophet] 시작  (메모리: 1592.2 MB)

01:59:24 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1592.16 MB

01:59:24 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1592.98 MB (변화: +0.82 MB)
[RGLS]   [Prophet] 완료  첫값=-5.14e+05 (메모리: 1593.0 MB)
[RGLS]   [LSTM] 시작  (메모리: 1593.0 MB)
[메모리] forecast_lstm 실행 전: 1592.98 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1592.96 MB (변화: -0.01 MB)
[RGLS]   [LSTM] 완료  첫값=5.24e+05 (메모리: 1593.0 MB)
[RGLS]   [Theta] 시작  (메모리: 1593.0 MB)
[메모리] forecast_theta 실행 전: 1592.96 MB
[메모리] forecast_theta 실행 후: 1592.96 MB (변화: +0.00 MB)
[RGLS]   [Theta] 완료  첫값=-9.27e+04 (메모리: 1593.0 MB)
[RGLS]   [DB] 93행 저장 완료
[PROGRESS] [ 288/500] ( 57.6%)  >>  ODV
[ODV] [SKIP] [ODV] 'sale' 관측치 부족: 27개 < 최소 28개
[PROGRESS] [ 289/500] ( 57.8%)  >>  BLMN
[BLMN]   45분기 | 2015-03-31 ~ 2026-03-31
[BLMN]   [SARIMA] 시작  (메모리: 1593.0 MB)
[메모리] forecast_sarima 실행 전: 1592.96 MB
[메모리] find_best_sarima_params 실행 전: 1592.96 MB
[메모리] find_best_sarima_params 실행 후: 1592.96 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1592.96 MB (변화: +0.00 MB)
[BLMN]   [SARIMA] 완료  첫값=9.82e+08 (메모리: 1593.0 MB)
[BLMN]   [ETS] 시작  (메모리: 1593.0 MB)
[메모리] forecast_ets 실행 전: 1592.96 MB
[메모리] forecast_ets 실행 후: 1592.96 MB (변화: +0.00 MB)
[BLMN]   [ETS] 완료  첫값=9.09e+08 (메모리: 1593.0 MB)
[BLMN]   [Prophet] 시작  (메모리: 1593.0 MB)

01:59:45 - cmdstanpy - INFO - Chain [1] start processing
01:59:45 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1592.96 MB
[메모리] forecast_prophet 실행 후: 1592.98 MB (변화: +0.01 MB)
[BLMN]   [Prophet] 완료  첫값=9.87e+08 (메모리: 1593.0 MB)
[BLMN]   [LSTM] 시작  (메모리: 1593.0 MB)
[메모리] forecast_lstm 실행 전: 1592.98 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1592.98 MB (변화: +0.01 MB)
[BLMN]   [LSTM] 완료  첫값=9.57e+08 (메모리: 1593.0 MB)
[BLMN]   [Theta] 시작  (메모리: 1593.0 MB)
[메모리] forecast_theta 실행 전: 1592.98 MB
[메모리] forecast_theta 실행 후: 1592.98 MB (변화: +0.00 MB)
[BLMN]   [Theta] 완료  첫값=9.33e+08 (메모리: 1593.0 MB)
[BLMN]   [DB] 93행 저장 완료
[PROGRESS] [ 290/500] ( 58.0%)  >>  OXM
[OXM]   45분기 | 2015-03-31 ~ 2026-03-31
[OXM]   [SARIMA] 시작  (메모리: 1593.0 MB)
[메모리] forecast_sarima 실행 전: 1592.98 MB
[메모리] find_best_sarima_params 실행 전: 1592.98 MB
[메모리] find_best_sarima_params 실행 후: 1592.98 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1592.98 MB (변화: +0.00 MB)
[OXM]   [SARIMA] 완료  첫값=2.99e+08 (메모리: 1593.0 MB)
[OXM]   [ETS] 시작  (메모리: 1593.0 MB)
[메모리] forecast_ets 실행 전: 1592.98 MB
[메모리] forecast_ets 실행 후: 1592.98 MB (변화: +0.00 MB)
[OXM]   [ETS] 완료  첫값=3.03e+08 (메모리: 1593.0 MB)
[OXM]   [Prophet] 시작  (메모리: 1593.0 MB)

02:00:04 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1592.98 MB

02:00:04 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.02 MB (변화: +0.04 MB)
[OXM]   [Prophet] 완료  첫값=3.75e+08 (메모리: 1593.0 MB)
[OXM]   [LSTM] 시작  (메모리: 1593.0 MB)
[메모리] forecast_lstm 실행 전: 1593.02 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1592.98 MB (변화: -0.04 MB)
[OXM]   [LSTM] 완료  첫값=3.82e+08 (메모리: 1593.0 MB)
[OXM]   [Theta] 시작  (메모리: 1593.0 MB)
[메모리] forecast_theta 실행 전: 1592.98 MB
[메모리] forecast_theta 실행 후: 1592.98 MB (변화: +0.00 MB)
[OXM]   [Theta] 완료  첫값=3.02e+08 (메모리: 1593.0 MB)
[OXM]   [DB] 93행 저장 완료
[PROGRESS] [ 291/500] ( 58.2%)  >>  TWI
[TWI]   45분기 | 2015-03-31 ~ 2026-03-31
[TWI]   [SARIMA] 시작  (메모리: 1593.0 MB)
[메모리] forecast_sarima 실행 전: 1592.98 MB
[메모리] find_best_sarima_params 실행 전: 1592.98 MB
[메모리] find_best_sarima_params 실행 후: 1592.98 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1592.98 MB (변화: +0.00 MB)
[TWI]   [SARIMA] 완료  첫값=4.79e+08 (메모리: 1593.0 MB)
[TWI]   [ETS] 시작  (메모리: 1593.0 MB)
[메모리] forecast_ets 실행 전: 1592.98 MB
[메모리] forecast_ets 실행 후: 1592.98 MB (변화: +0.00 MB)
[TWI]   [ETS] 완료  첫값=4.57e+08 (메모리: 1593.0 MB)
[TWI]   [Prophet] 시작  (메모리: 1593.0 MB)

02:00:23 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1592.98 MB

02:00:23 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.00 MB (변화: +0.02 MB)
[TWI]   [Prophet] 완료  첫값=4.99e+08 (메모리: 1593.0 MB)
[TWI]   [LSTM] 시작  (메모리: 1593.0 MB)
[메모리] forecast_lstm 실행 전: 1593.00 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.04 MB (변화: +0.04 MB)
[TWI]   [LSTM] 완료  첫값=4.27e+08 (메모리: 1593.0 MB)
[TWI]   [Theta] 시작  (메모리: 1593.0 MB)
[메모리] forecast_theta 실행 전: 1593.04 MB
[메모리] forecast_theta 실행 후: 1593.04 MB (변화: +0.00 MB)
[TWI]   [Theta] 완료  첫값=4.57e+08 (메모리: 1593.0 MB)
[TWI]   [DB] 93행 저장 완료
[PROGRESS] [ 292/500] ( 58.4%)  >>  BXC
[BXC]   44분기 | 2015-06-30 ~ 2026-03-31
[BXC]   [SARIMA] 시작  (메모리: 1593.0 MB)
[메모리] forecast_sarima 실행 전: 1593.04 MB
[메모리] find_best_sarima_params 실행 전: 1593.04 MB
[메모리] find_best_sarima_params 실행 후: 1593.04 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.04 MB (변화: +0.00 MB)
[BXC]   [SARIMA] 완료  첫값=8.18e+08 (메모리: 1593.0 MB)
[BXC]   [ETS] 시작  (메모리: 1593.0 MB)
[메모리] forecast_ets 실행 전: 1593.04 MB
[메모리] forecast_ets 실행 후: 1593.04 MB (변화: +0.00 MB)
[BXC]   [ETS] 완료  첫값=8.72e+08 (메모리: 1593.0 MB)
[BXC]   [Prophet] 시작  (메모리: 1593.0 MB)

02:00:42 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1593.04 MB

02:00:42 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.06 MB (변화: +0.02 MB)
[BXC]   [Prophet] 완료  첫값=9.51e+08 (메모리: 1593.1 MB)
[BXC]   [LSTM] 시작  (메모리: 1593.1 MB)
[메모리] forecast_lstm 실행 전: 1593.06 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.08 MB (변화: +0.02 MB)
[BXC]   [LSTM] 완료  첫값=8.22e+08 (메모리: 1593.1 MB)
[BXC]   [Theta] 시작  (메모리: 1593.1 MB)
[메모리] forecast_theta 실행 전: 1593.08 MB
[메모리] forecast_theta 실행 후: 1593.08 MB (변화: +0.00 MB)
[BXC]   [Theta] 완료  첫값=8.71e+08 (메모리: 1593.1 MB)
[BXC]   [DB] 92행 저장 완료
[PROGRESS] [ 293/500] ( 58.6%)  >>  STKL
[STKL]   44분기 | 2015-06-30 ~ 2026-03-31
[STKL]   [SARIMA] 시작  (메모리: 1593.1 MB)
[메모리] forecast_sarima 실행 전: 1593.08 MB
[메모리] find_best_sarima_params 실행 전: 1593.08 MB
[메모리] find_best_sarima_params 실행 후: 1593.08 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.08 MB (변화: +0.00 MB)
[STKL]   [SARIMA] 완료  첫값=2.20e+08 (메모리: 1593.1 MB)
[STKL]   [ETS] 시작  (메모리: 1593.1 MB)
[메모리] forecast_ets 실행 전: 1593.08 MB
[메모리] forecast_ets 실행 후: 1593.09 MB (변화: +0.00 MB)
[STKL]   [ETS] 완료  첫값=2.20e+08 (메모리: 1593.1 MB)
[STKL]   [Prophet] 시작  (메모리: 1593.1 MB)

02:00:59 - cmdstanpy - INFO - Chain [1] start processing
02:00:59 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1593.09 MB
[메모리] forecast_prophet 실행 후: 1593.10 MB (변화: +0.02 MB)
[STKL]   [Prophet] 완료  첫값=1.38e+08 (메모리: 1593.1 MB)
[STKL]   [LSTM] 시작  (메모리: 1593.1 MB)
[메모리] forecast_lstm 실행 전: 1593.10 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.10 MB (변화: +0.00 MB)
[STKL]   [LSTM] 완료  첫값=1.28e+08 (메모리: 1593.1 MB)
[STKL]   [Theta] 시작  (메모리: 1593.1 MB)
[메모리] forecast_theta 실행 전: 1593.10 MB
[메모리] forecast_theta 실행 후: 1593.10 MB (변화: +0.00 MB)
[STKL]   [Theta] 완료  첫값=2.03e+08 (메모리: 1593.1 MB)
[STKL]   [DB] 92행 저장 완료
[PROGRESS] [ 294/500] ( 58.8%)  >>  CPS
[CPS]   45분기 | 2015-03-31 ~ 2026-03-31
[CPS]   [SARIMA] 시작  (메모리: 1593.1 MB)
[메모리] forecast_sarima 실행 전: 1593.10 MB
[메모리] find_best_sarima_params 실행 전: 1593.10 MB
[메모리] find_best_sarima_params 실행 후: 1593.10 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.10 MB (변화: +0.00 MB)
[CPS]   [SARIMA] 완료  첫값=6.69e+08 (메모리: 1593.1 MB)
[CPS]   [ETS] 시작  (메모리: 1593.1 MB)
[메모리] forecast_ets 실행 전: 1593.10 MB
[메모리] forecast_ets 실행 후: 1593.10 MB (변화: +0.00 MB)
[CPS]   [ETS] 완료  첫값=6.32e+08 (메모리: 1593.1 MB)
[CPS]   [Prophet] 시작  (메모리: 1593.1 MB)

02:01:16 - cmdstanpy - INFO - Chain [1] start processing
02:01:16 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1593.10 MB
[메모리] forecast_prophet 실행 후: 1593.11 MB (변화: +0.00 MB)
[CPS]   [Prophet] 완료  첫값=5.99e+08 (메모리: 1593.1 MB)
[CPS]   [LSTM] 시작  (메모리: 1593.1 MB)
[메모리] forecast_lstm 실행 전: 1593.11 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.06 MB (변화: -0.05 MB)
[CPS]   [LSTM] 완료  첫값=6.05e+08 (메모리: 1593.1 MB)
[CPS]   [Theta] 시작  (메모리: 1593.1 MB)
[메모리] forecast_theta 실행 전: 1593.06 MB
[메모리] forecast_theta 실행 후: 1593.06 MB (변화: +0.00 MB)
[CPS]   [Theta] 완료  첫값=6.25e+08 (메모리: 1593.1 MB)
[CPS]   [DB] 93행 저장 완료
[PROGRESS] [ 295/500] ( 59.0%)  >>  AMOT
[AMOT]   45분기 | 2015-03-31 ~ 2026-03-31
[AMOT]   [SARIMA] 시작  (메모리: 1593.1 MB)
[메모리] forecast_sarima 실행 전: 1593.06 MB
[메모리] find_best_sarima_params 실행 전: 1593.06 MB
[메모리] find_best_sarima_params 실행 후: 1593.06 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.06 MB (변화: +0.00 MB)
[AMOT]   [SARIMA] 완료  첫값=1.39e+08 (메모리: 1593.1 MB)
[AMOT]   [ETS] 시작  (메모리: 1593.1 MB)
[메모리] forecast_ets 실행 전: 1593.06 MB
[메모리] forecast_ets 실행 후: 1593.06 MB (변화: +0.00 MB)
[AMOT]   [ETS] 완료  첫값=1.41e+08 (메모리: 1593.1 MB)
[AMOT]   [Prophet] 시작  (메모리: 1593.1 MB)

02:01:35 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1593.06 MB

02:01:35 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.08 MB (변화: +0.02 MB)
[AMOT]   [Prophet] 완료  첫값=1.50e+08 (메모리: 1593.1 MB)
[AMOT]   [LSTM] 시작  (메모리: 1593.1 MB)
[메모리] forecast_lstm 실행 전: 1593.08 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.04 MB (변화: -0.04 MB)
[AMOT]   [LSTM] 완료  첫값=1.34e+08 (메모리: 1593.0 MB)
[AMOT]   [Theta] 시작  (메모리: 1593.0 MB)
[메모리] forecast_theta 실행 전: 1593.04 MB
[메모리] forecast_theta 실행 후: 1593.04 MB (변화: +0.00 MB)
[AMOT]   [Theta] 완료  첫값=1.38e+08 (메모리: 1593.0 MB)
[AMOT]   [DB] 93행 저장 완료
[PROGRESS] [ 296/500] ( 59.2%)  >>  AHH
[AHH]   45분기 | 2015-03-31 ~ 2026-03-31
[AHH]   [SARIMA] 시작  (메모리: 1593.0 MB)
[메모리] forecast_sarima 실행 전: 1593.04 MB
[메모리] find_best_sarima_params 실행 전: 1593.04 MB
[메모리] find_best_sarima_params 실행 후: 1593.04 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.04 MB (변화: +0.00 MB)
[AHH]   [SARIMA] 완료  첫값=9.61e+07 (메모리: 1593.0 MB)
[AHH]   [ETS] 시작  (메모리: 1593.0 MB)
[메모리] forecast_ets 실행 전: 1593.04 MB
[메모리] forecast_ets 실행 후: 1593.04 MB (변화: +0.00 MB)
[AHH]   [ETS] 완료  첫값=9.99e+07 (메모리: 1593.0 MB)
[AHH]   [Prophet] 시작  (메모리: 1593.0 MB)

02:01:54 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1593.04 MB

02:01:54 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.05 MB (변화: +0.02 MB)
[AHH]   [Prophet] 완료  첫값=1.47e+08 (메모리: 1593.1 MB)
[AHH]   [LSTM] 시작  (메모리: 1593.1 MB)
[메모리] forecast_lstm 실행 전: 1593.05 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.05 MB (변화: -0.00 MB)
[AHH]   [LSTM] 완료  첫값=1.40e+08 (메모리: 1593.1 MB)
[AHH]   [Theta] 시작  (메모리: 1593.1 MB)
[메모리] forecast_theta 실행 전: 1593.05 MB
[메모리] forecast_theta 실행 후: 1593.05 MB (변화: +0.00 MB)
[AHH]   [Theta] 완료  첫값=9.71e+07 (메모리: 1593.1 MB)
[AHH]   [DB] 93행 저장 완료
[PROGRESS] [ 297/500] ( 59.4%)  >>  CNSL
[CNSL]   45분기 | 2015-03-31 ~ 2026-03-31
[CNSL]   [SARIMA] 시작  (메모리: 1593.1 MB)
[메모리] forecast_sarima 실행 전: 1593.05 MB
[메모리] find_best_sarima_params 실행 전: 1593.05 MB
[메모리] find_best_sarima_params 실행 후: 1593.05 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.05 MB (변화: +0.00 MB)
[CNSL]   [SARIMA] 완료  첫값=2.69e+08 (메모리: 1593.1 MB)
[CNSL]   [ETS] 시작  (메모리: 1593.1 MB)
[메모리] forecast_ets 실행 전: 1593.05 MB
[메모리] forecast_ets 실행 후: 1593.06 MB (변화: +0.01 MB)
[CNSL]   [ETS] 완료  첫값=2.70e+08 (메모리: 1593.1 MB)
[CNSL]   [Prophet] 시작  (메모리: 1593.1 MB)

02:02:14 - cmdstanpy - INFO - Chain [1] start processing
02:02:14 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1593.06 MB
[메모리] forecast_prophet 실행 후: 1593.07 MB (변화: +0.01 MB)
[CNSL]   [Prophet] 완료  첫값=3.13e+08 (메모리: 1593.1 MB)
[CNSL]   [LSTM] 시작  (메모리: 1593.1 MB)
[메모리] forecast_lstm 실행 전: 1593.07 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.14 MB (변화: +0.08 MB)
[CNSL]   [LSTM] 완료  첫값=2.73e+08 (메모리: 1593.1 MB)
[CNSL]   [Theta] 시작  (메모리: 1593.1 MB)
[메모리] forecast_theta 실행 전: 1593.14 MB
[메모리] forecast_theta 실행 후: 1593.14 MB (변화: +0.00 MB)
[CNSL]   [Theta] 완료  첫값=2.67e+08 (메모리: 1593.1 MB)
[CNSL]   [DB] 93행 저장 완료
[PROGRESS] [ 298/500] ( 59.6%)  >>  GOOD
[GOOD]   45분기 | 2015-03-31 ~ 2026-03-31
[GOOD]   [SARIMA] 시작  (메모리: 1593.1 MB)
[메모리] forecast_sarima 실행 전: 1593.14 MB
[메모리] find_best_sarima_params 실행 전: 1593.14 MB
[메모리] find_best_sarima_params 실행 후: 1593.14 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.14 MB (변화: +0.00 MB)
[GOOD]   [SARIMA] 완료  첫값=4.15e+07 (메모리: 1593.1 MB)
[GOOD]   [ETS] 시작  (메모리: 1593.1 MB)
[메모리] forecast_ets 실행 전: 1593.14 MB
[메모리] forecast_ets 실행 후: 1593.14 MB (변화: +0.00 MB)
[GOOD]   [ETS] 완료  첫값=4.17e+07 (메모리: 1593.1 MB)
[GOOD]   [Prophet] 시작  (메모리: 1593.1 MB)

02:02:39 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1593.14 MB

02:02:39 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.15 MB (변화: +0.00 MB)
[GOOD]   [Prophet] 완료  첫값=4.08e+07 (메모리: 1593.1 MB)
[GOOD]   [LSTM] 시작  (메모리: 1593.1 MB)
[메모리] forecast_lstm 실행 전: 1593.15 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.14 MB (변화: -0.01 MB)
[GOOD]   [LSTM] 완료  첫값=3.99e+07 (메모리: 1593.1 MB)
[GOOD]   [Theta] 시작  (메모리: 1593.1 MB)
[메모리] forecast_theta 실행 전: 1593.14 MB
[메모리] forecast_theta 실행 후: 1593.14 MB (변화: +0.00 MB)
[GOOD]   [Theta] 완료  첫값=4.11e+07 (메모리: 1593.1 MB)
[GOOD]   [DB] 93행 저장 완료
[PROGRESS] [ 299/500] ( 59.8%)  >>  DBVT
[DBVT]   45분기 | 2015-03-31 ~ 2026-03-31
[DBVT]   [SARIMA] 시작  (메모리: 1593.1 MB)
[메모리] forecast_sarima 실행 전: 1593.14 MB
[메모리] find_best_sarima_params 실행 전: 1593.14 MB
[메모리] find_best_sarima_params 실행 후: 1593.14 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.14 MB (변화: +0.00 MB)
[DBVT]   [SARIMA] 완료  첫값=3.29e+05 (메모리: 1593.1 MB)
[DBVT]   [ETS] 시작  (메모리: 1593.1 MB)
[메모리] forecast_ets 실행 전: 1593.14 MB
[메모리] forecast_ets 실행 후: 1593.14 MB (변화: +0.00 MB)
[DBVT]   [ETS] 완료  첫값=5.27e+05 (메모리: 1593.1 MB)
[DBVT]   [Prophet] 시작  (메모리: 1593.1 MB)

02:02:57 - cmdstanpy - INFO - Chain [1] start processing
02:02:57 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1593.14 MB
[메모리] forecast_prophet 실행 후: 1593.15 MB (변화: +0.01 MB)
[DBVT]   [Prophet] 완료  첫값=6.82e+05 (메모리: 1593.1 MB)
[DBVT]   [LSTM] 시작  (메모리: 1593.1 MB)
[메모리] forecast_lstm 실행 전: 1593.15 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.15 MB (변화: +0.00 MB)
[DBVT]   [LSTM] 완료  첫값=1.66e+06 (메모리: 1593.1 MB)
[DBVT]   [Theta] 시작  (메모리: 1593.1 MB)
[메모리] forecast_theta 실행 전: 1593.15 MB
[메모리] forecast_theta 실행 후: 1593.15 MB (변화: +0.00 MB)
[DBVT]   [Theta] 완료  첫값=3.63e+05 (메모리: 1593.1 MB)
[DBVT]   [DB] 93행 저장 완료
[PROGRESS] [ 300/500] ( 60.0%)  >>  LLNW
[LLNW]   45분기 | 2015-03-31 ~ 2026-03-31
[LLNW]   [SARIMA] 시작  (메모리: 1593.1 MB)
[메모리] forecast_sarima 실행 전: 1593.15 MB
[메모리] find_best_sarima_params 실행 전: 1593.15 MB
[메모리] find_best_sarima_params 실행 후: 1593.15 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.15 MB (변화: +0.00 MB)
[LLNW]   [SARIMA] 완료  첫값=7.53e+07 (메모리: 1593.1 MB)
[LLNW]   [ETS] 시작  (메모리: 1593.1 MB)
[메모리] forecast_ets 실행 전: 1593.15 MB
[메모리] forecast_ets 실행 후: 1593.15 MB (변화: +0.00 MB)
[LLNW]   [ETS] 완료  첫값=7.66e+07 (메모리: 1593.2 MB)
[LLNW]   [Prophet] 시작  (메모리: 1593.2 MB)

02:03:18 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1593.15 MB

02:03:18 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.15 MB (변화: +0.00 MB)
[LLNW]   [Prophet] 완료  첫값=7.97e+07 (메모리: 1593.2 MB)
[LLNW]   [LSTM] 시작  (메모리: 1593.2 MB)
[메모리] forecast_lstm 실행 전: 1593.15 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.14 MB (변화: -0.01 MB)
[LLNW]   [LSTM] 완료  첫값=7.52e+07 (메모리: 1593.1 MB)
[LLNW]   [Theta] 시작  (메모리: 1593.1 MB)
[메모리] forecast_theta 실행 전: 1593.14 MB
[메모리] forecast_theta 실행 후: 1593.14 MB (변화: +0.00 MB)
[LLNW]   [Theta] 완료  첫값=7.62e+07 (메모리: 1593.1 MB)
[LLNW]   [DB] 93행 저장 완료
[PROGRESS] [ 301/500] ( 60.2%)  >>  SAGE
[SAGE]   45분기 | 2015-03-31 ~ 2026-03-31
[SAGE]   [SARIMA] 시작  (메모리: 1593.1 MB)
[메모리] forecast_sarima 실행 전: 1593.14 MB
[메모리] find_best_sarima_params 실행 전: 1593.14 MB
[메모리] find_best_sarima_params 실행 후: 1593.14 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.14 MB (변화: +0.00 MB)
[SAGE]   [SARIMA] 완료  첫값=1.56e+07 (메모리: 1593.1 MB)
[SAGE]   [ETS] 시작  (메모리: 1593.1 MB)
[메모리] forecast_ets 실행 전: 1593.14 MB
[메모리] forecast_ets 실행 후: 1593.14 MB (변화: +0.00 MB)
[SAGE]   [ETS] 완료  첫값=4.71e+07 (메모리: 1593.1 MB)
[SAGE]   [Prophet] 시작  (메모리: 1593.1 MB)

02:03:33 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1593.14 MB

02:03:33 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.15 MB (변화: +0.01 MB)
[SAGE]   [Prophet] 완료  첫값=4.83e+07 (메모리: 1593.2 MB)
[SAGE]   [LSTM] 시작  (메모리: 1593.2 MB)
[메모리] forecast_lstm 실행 전: 1593.15 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.13 MB (변화: -0.02 MB)
[SAGE]   [LSTM] 완료  첫값=4.02e+07 (메모리: 1593.1 MB)
[SAGE]   [Theta] 시작  (메모리: 1593.1 MB)
[메모리] forecast_theta 실행 전: 1593.13 MB
[메모리] forecast_theta 실행 후: 1593.13 MB (변화: +0.00 MB)
[SAGE]   [Theta] 완료  첫값=2.77e+07 (메모리: 1593.1 MB)
[SAGE]   [DB] 93행 저장 완료
[PROGRESS] [ 302/500] ( 60.4%)  >>  SB
[SB]   45분기 | 2015-03-31 ~ 2026-03-31
[SB]   [SARIMA] 시작  (메모리: 1593.1 MB)
[메모리] forecast_sarima 실행 전: 1593.13 MB
[메모리] find_best_sarima_params 실행 전: 1593.13 MB
[메모리] find_best_sarima_params 실행 후: 1593.13 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.13 MB (변화: +0.00 MB)
[SB]   [SARIMA] 완료  첫값=7.44e+07 (메모리: 1593.1 MB)
[SB]   [ETS] 시작  (메모리: 1593.1 MB)
[메모리] forecast_ets 실행 전: 1593.13 MB
[메모리] forecast_ets 실행 후: 1593.13 MB (변화: +0.00 MB)
[SB]   [ETS] 완료  첫값=7.75e+07 (메모리: 1593.1 MB)
[SB]   [Prophet] 시작  (메모리: 1593.1 MB)

02:03:52 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1593.13 MB

02:03:52 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.14 MB (변화: +0.01 MB)
[SB]   [Prophet] 완료  첫값=8.81e+07 (메모리: 1593.1 MB)
[SB]   [LSTM] 시작  (메모리: 1593.1 MB)
[메모리] forecast_lstm 실행 전: 1593.14 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.11 MB (변화: -0.03 MB)
[SB]   [LSTM] 완료  첫값=7.06e+07 (메모리: 1593.1 MB)
[SB]   [Theta] 시작  (메모리: 1593.1 MB)
[메모리] forecast_theta 실행 전: 1593.11 MB
[메모리] forecast_theta 실행 후: 1593.11 MB (변화: +0.00 MB)
[SB]   [Theta] 완료  첫값=7.74e+07 (메모리: 1593.1 MB)
[SB]   [DB] 93행 저장 완료
[PROGRESS] [ 303/500] ( 60.6%)  >>  CLMB
[CLMB]   45분기 | 2015-03-31 ~ 2026-03-31
[CLMB]   [SARIMA] 시작  (메모리: 1593.1 MB)
[메모리] forecast_sarima 실행 전: 1593.11 MB
[메모리] find_best_sarima_params 실행 전: 1593.11 MB
[메모리] find_best_sarima_params 실행 후: 1593.11 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.11 MB (변화: +0.00 MB)
[CLMB]   [SARIMA] 완료  첫값=1.74e+08 (메모리: 1593.1 MB)
[CLMB]   [ETS] 시작  (메모리: 1593.1 MB)
[메모리] forecast_ets 실행 전: 1593.11 MB
[메모리] forecast_ets 실행 후: 1593.11 MB (변화: +0.00 MB)
[CLMB]   [ETS] 완료  첫값=1.63e+08 (메모리: 1593.1 MB)
[CLMB]   [Prophet] 시작  (메모리: 1593.1 MB)

02:04:10 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1593.11 MB

02:04:10 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.12 MB (변화: +0.02 MB)
[CLMB]   [Prophet] 완료  첫값=1.14e+08 (메모리: 1593.1 MB)
[CLMB]   [LSTM] 시작  (메모리: 1593.1 MB)
[메모리] forecast_lstm 실행 전: 1593.12 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.16 MB (변화: +0.04 MB)
[CLMB]   [LSTM] 완료  첫값=1.19e+08 (메모리: 1593.2 MB)
[CLMB]   [Theta] 시작  (메모리: 1593.2 MB)
[메모리] forecast_theta 실행 전: 1593.16 MB
[메모리] forecast_theta 실행 후: 1593.16 MB (변화: +0.00 MB)
[CLMB]   [Theta] 완료  첫값=1.62e+08 (메모리: 1593.2 MB)
[CLMB]   [DB] 93행 저장 완료
[PROGRESS] [ 304/500] ( 60.8%)  >>  MYGN
[MYGN]   45분기 | 2015-03-31 ~ 2026-03-31
[MYGN]   [SARIMA] 시작  (메모리: 1593.2 MB)
[메모리] forecast_sarima 실행 전: 1593.16 MB
[메모리] find_best_sarima_params 실행 전: 1593.16 MB
[메모리] find_best_sarima_params 실행 후: 1593.16 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.16 MB (변화: +0.00 MB)
[MYGN]   [SARIMA] 완료  첫값=2.18e+08 (메모리: 1593.2 MB)
[MYGN]   [ETS] 시작  (메모리: 1593.2 MB)
[메모리] forecast_ets 실행 전: 1593.16 MB
[메모리] forecast_ets 실행 후: 1593.16 MB (변화: +0.00 MB)
[MYGN]   [ETS] 완료  첫값=2.10e+08 (메모리: 1593.2 MB)
[MYGN]   [Prophet] 시작  (메모리: 1593.2 MB)

02:04:27 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1593.16 MB

02:04:28 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.17 MB (변화: +0.01 MB)
[MYGN]   [Prophet] 완료  첫값=1.88e+08 (메모리: 1593.2 MB)
[MYGN]   [LSTM] 시작  (메모리: 1593.2 MB)
[메모리] forecast_lstm 실행 전: 1593.17 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.20 MB (변화: +0.02 MB)
[MYGN]   [LSTM] 완료  첫값=1.89e+08 (메모리: 1593.2 MB)
[MYGN]   [Theta] 시작  (메모리: 1593.2 MB)
[메모리] forecast_theta 실행 전: 1593.20 MB
[메모리] forecast_theta 실행 후: 1593.20 MB (변화: +0.00 MB)
[MYGN]   [Theta] 완료  첫값=2.06e+08 (메모리: 1593.2 MB)
[MYGN]   [DB] 93행 저장 완료
[PROGRESS] [ 305/500] ( 61.0%)  >>  TNP
[TNP]   45분기 | 2015-03-31 ~ 2026-03-31
[TNP]   [SARIMA] 시작  (메모리: 1593.2 MB)
[메모리] forecast_sarima 실행 전: 1593.20 MB
[메모리] find_best_sarima_params 실행 전: 1593.20 MB
[메모리] find_best_sarima_params 실행 후: 1593.20 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.20 MB (변화: +0.00 MB)
[TNP]   [SARIMA] 완료  첫값=1.94e+08 (메모리: 1593.2 MB)
[TNP]   [ETS] 시작  (메모리: 1593.2 MB)
[메모리] forecast_ets 실행 전: 1593.20 MB
[메모리] forecast_ets 실행 후: 1593.20 MB (변화: +0.01 MB)
[TNP]   [ETS] 완료  첫값=1.97e+08 (메모리: 1593.2 MB)
[TNP]   [Prophet] 시작  (메모리: 1593.2 MB)

02:04:48 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1593.20 MB

02:04:48 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.21 MB (변화: +0.00 MB)
[TNP]   [Prophet] 완료  첫값=2.15e+08 (메모리: 1593.2 MB)
[TNP]   [LSTM] 시작  (메모리: 1593.2 MB)
[메모리] forecast_lstm 실행 전: 1593.21 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.18 MB (변화: -0.02 MB)
[TNP]   [LSTM] 완료  첫값=1.91e+08 (메모리: 1593.2 MB)
[TNP]   [Theta] 시작  (메모리: 1593.2 MB)
[메모리] forecast_theta 실행 전: 1593.18 MB
[메모리] forecast_theta 실행 후: 1593.18 MB (변화: +0.00 MB)
[TNP]   [Theta] 완료  첫값=1.97e+08 (메모리: 1593.2 MB)
[TNP]   [DB] 93행 저장 완료
[PROGRESS] [ 306/500] ( 61.2%)  >>  UHT
[UHT]   45분기 | 2015-03-31 ~ 2026-03-31
[UHT]   [SARIMA] 시작  (메모리: 1593.2 MB)
[메모리] forecast_sarima 실행 전: 1593.18 MB
[메모리] find_best_sarima_params 실행 전: 1593.18 MB
[메모리] find_best_sarima_params 실행 후: 1593.18 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.18 MB (변화: +0.00 MB)
[UHT]   [SARIMA] 완료  첫값=2.58e+07 (메모리: 1593.2 MB)
[UHT]   [ETS] 시작  (메모리: 1593.2 MB)
[메모리] forecast_ets 실행 전: 1593.18 MB
[메모리] forecast_ets 실행 후: 1593.19 MB (변화: +0.00 MB)
[UHT]   [ETS] 완료  첫값=2.59e+07 (메모리: 1593.2 MB)
[UHT]   [Prophet] 시작  (메모리: 1593.2 MB)

02:05:09 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1593.19 MB

02:05:09 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.22 MB (변화: +0.03 MB)
[UHT]   [Prophet] 완료  첫값=2.60e+07 (메모리: 1593.2 MB)
[UHT]   [LSTM] 시작  (메모리: 1593.2 MB)
[메모리] forecast_lstm 실행 전: 1593.22 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.18 MB (변화: -0.04 MB)
[UHT]   [LSTM] 완료  첫값=2.95e+07 (메모리: 1593.2 MB)
[UHT]   [Theta] 시작  (메모리: 1593.2 MB)
[메모리] forecast_theta 실행 전: 1593.18 MB
[메모리] forecast_theta 실행 후: 1593.18 MB (변화: +0.00 MB)
[UHT]   [Theta] 완료  첫값=2.56e+07 (메모리: 1593.2 MB)
[UHT]   [DB] 93행 저장 완료
[PROGRESS] [ 307/500] ( 61.4%)  >>  NUS
[NUS]   45분기 | 2015-03-31 ~ 2026-03-31
[NUS]   [SARIMA] 시작  (메모리: 1593.2 MB)
[메모리] forecast_sarima 실행 전: 1593.18 MB
[메모리] find_best_sarima_params 실행 전: 1593.18 MB
[메모리] find_best_sarima_params 실행 후: 1593.18 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.18 MB (변화: +0.00 MB)
[NUS]   [SARIMA] 완료  첫값=3.86e+08 (메모리: 1593.2 MB)
[NUS]   [ETS] 시작  (메모리: 1593.2 MB)
[메모리] forecast_ets 실행 전: 1593.18 MB
[메모리] forecast_ets 실행 후: 1593.18 MB (변화: +0.00 MB)
[NUS]   [ETS] 완료  첫값=3.98e+08 (메모리: 1593.2 MB)
[NUS]   [Prophet] 시작  (메모리: 1593.2 MB)

02:05:29 - cmdstanpy - INFO - Chain [1] start processing
02:05:29 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1593.18 MB
[메모리] forecast_prophet 실행 후: 1593.20 MB (변화: +0.01 MB)
[NUS]   [Prophet] 완료  첫값=3.53e+08 (메모리: 1593.2 MB)
[NUS]   [LSTM] 시작  (메모리: 1593.2 MB)
[메모리] forecast_lstm 실행 전: 1593.20 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.18 MB (변화: -0.01 MB)
[NUS]   [LSTM] 완료  첫값=3.87e+08 (메모리: 1593.2 MB)
[NUS]   [Theta] 시작  (메모리: 1593.2 MB)
[메모리] forecast_theta 실행 전: 1593.18 MB
[메모리] forecast_theta 실행 후: 1593.18 MB (변화: +0.00 MB)
[NUS]   [Theta] 완료  첫값=4.01e+08 (메모리: 1593.2 MB)
[NUS]   [DB] 93행 저장 완료
[PROGRESS] [ 308/500] ( 61.6%)  >>  ZEUS
[ZEUS]   45분기 | 2015-03-31 ~ 2026-03-31
[ZEUS]   [SARIMA] 시작  (메모리: 1593.2 MB)
[메모리] forecast_sarima 실행 전: 1593.18 MB
[메모리] find_best_sarima_params 실행 전: 1593.18 MB
[메모리] find_best_sarima_params 실행 후: 1593.18 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.18 MB (변화: +0.00 MB)
[ZEUS]   [SARIMA] 완료  첫값=5.16e+08 (메모리: 1593.2 MB)
[ZEUS]   [ETS] 시작  (메모리: 1593.2 MB)
[메모리] forecast_ets 실행 전: 1593.18 MB
[메모리] forecast_ets 실행 후: 1593.19 MB (변화: +0.01 MB)
[ZEUS]   [ETS] 완료  첫값=4.92e+08 (메모리: 1593.2 MB)
[ZEUS]   [Prophet] 시작  (메모리: 1593.2 MB)
[메모리] forecast_prophet 실행 전: 1593.19 MB

02:05:53 - cmdstanpy - INFO - Chain [1] start processing
02:05:53 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.20 MB (변화: +0.00 MB)
[ZEUS]   [Prophet] 완료  첫값=5.84e+08 (메모리: 1593.2 MB)
[ZEUS]   [LSTM] 시작  (메모리: 1593.2 MB)
[메모리] forecast_lstm 실행 전: 1593.20 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.19 MB (변화: -0.01 MB)
[ZEUS]   [LSTM] 완료  첫값=4.77e+08 (메모리: 1593.2 MB)
[ZEUS]   [Theta] 시작  (메모리: 1593.2 MB)
[메모리] forecast_theta 실행 전: 1593.19 MB
[메모리] forecast_theta 실행 후: 1593.19 MB (변화: +0.00 MB)
[ZEUS]   [Theta] 완료  첫값=4.92e+08 (메모리: 1593.2 MB)
[ZEUS]   [DB] 93행 저장 완료
[PROGRESS] [ 309/500] ( 61.8%)  >>  PRTA
[PRTA]   45분기 | 2015-03-31 ~ 2026-03-31
[PRTA]   [SARIMA] 시작  (메모리: 1593.2 MB)
[메모리] forecast_sarima 실행 전: 1593.19 MB
[메모리] find_best_sarima_params 실행 전: 1593.19 MB
[메모리] find_best_sarima_params 실행 후: 1593.19 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.19 MB (변화: +0.00 MB)
[PRTA]   [SARIMA] 완료  첫값=6.97e+06 (메모리: 1593.2 MB)
[PRTA]   [ETS] 시작  (메모리: 1593.2 MB)
[메모리] forecast_ets 실행 전: 1593.19 MB
[메모리] forecast_ets 실행 후: 1593.19 MB (변화: +0.00 MB)
[PRTA]   [ETS] 완료  첫값=1.22e+07 (메모리: 1593.2 MB)
[PRTA]   [Prophet] 시작  (메모리: 1593.2 MB)

02:06:13 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1593.19 MB

02:06:13 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.20 MB (변화: +0.01 MB)
[PRTA]   [Prophet] 완료  첫값=2.45e+07 (메모리: 1593.2 MB)
[PRTA]   [LSTM] 시작  (메모리: 1593.2 MB)
[메모리] forecast_lstm 실행 전: 1593.20 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.14 MB (변화: -0.05 MB)
[PRTA]   [LSTM] 완료  첫값=1.43e+07 (메모리: 1593.1 MB)
[PRTA]   [Theta] 시작  (메모리: 1593.1 MB)
[메모리] forecast_theta 실행 전: 1593.14 MB
[메모리] forecast_theta 실행 후: 1593.14 MB (변화: +0.00 MB)
[PRTA]   [Theta] 완료  첫값=3.25e+06 (메모리: 1593.1 MB)
[PRTA]   [DB] 93행 저장 완료
[PROGRESS] [ 310/500] ( 62.0%)  >>  MGPI
[MGPI]   45분기 | 2015-03-31 ~ 2026-03-31
[MGPI]   [SARIMA] 시작  (메모리: 1593.1 MB)
[메모리] forecast_sarima 실행 전: 1593.14 MB
[메모리] find_best_sarima_params 실행 전: 1593.14 MB
[메모리] find_best_sarima_params 실행 후: 1593.14 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.14 MB (변화: +0.00 MB)
[MGPI]   [SARIMA] 완료  첫값=1.31e+08 (메모리: 1593.1 MB)
[MGPI]   [ETS] 시작  (메모리: 1593.1 MB)
[메모리] forecast_ets 실행 전: 1593.14 MB
[메모리] forecast_ets 실행 후: 1593.14 MB (변화: +0.00 MB)
[MGPI]   [ETS] 완료  첫값=1.40e+08 (메모리: 1593.1 MB)
[MGPI]   [Prophet] 시작  (메모리: 1593.1 MB)

02:06:32 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1593.14 MB

02:06:32 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.18 MB (변화: +0.03 MB)
[MGPI]   [Prophet] 완료  첫값=1.90e+08 (메모리: 1593.2 MB)
[MGPI]   [LSTM] 시작  (메모리: 1593.2 MB)
[메모리] forecast_lstm 실행 전: 1593.18 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.16 MB (변화: -0.02 MB)
[MGPI]   [LSTM] 완료  첫값=1.44e+08 (메모리: 1593.2 MB)
[MGPI]   [Theta] 시작  (메모리: 1593.2 MB)
[메모리] forecast_theta 실행 전: 1593.16 MB
[메모리] forecast_theta 실행 후: 1593.16 MB (변화: +0.00 MB)
[MGPI]   [Theta] 완료  첫값=1.40e+08 (메모리: 1593.2 MB)
[MGPI]   [DB] 93행 저장 완료
[PROGRESS] [ 311/500] ( 62.2%)  >>  DRQ
[DRQ]   45분기 | 2015-03-31 ~ 2026-03-31
[DRQ]   [SARIMA] 시작  (메모리: 1593.2 MB)
[메모리] forecast_sarima 실행 전: 1593.16 MB
[메모리] find_best_sarima_params 실행 전: 1593.16 MB
[메모리] find_best_sarima_params 실행 후: 1593.16 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.16 MB (변화: +0.00 MB)
[DRQ]   [SARIMA] 완료  첫값=2.40e+08 (메모리: 1593.2 MB)
[DRQ]   [ETS] 시작  (메모리: 1593.2 MB)
[메모리] forecast_ets 실행 전: 1593.16 MB
[메모리] forecast_ets 실행 후: 1593.16 MB (변화: +0.00 MB)
[DRQ]   [ETS] 완료  첫값=2.51e+08 (메모리: 1593.2 MB)
[DRQ]   [Prophet] 시작  (메모리: 1593.2 MB)

02:06:51 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1593.16 MB

02:06:51 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.18 MB (변화: +0.02 MB)
[DRQ]   [Prophet] 완료  첫값=1.51e+08 (메모리: 1593.2 MB)
[DRQ]   [LSTM] 시작  (메모리: 1593.2 MB)
[메모리] forecast_lstm 실행 전: 1593.18 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.17 MB (변화: -0.01 MB)
[DRQ]   [LSTM] 완료  첫값=2.28e+08 (메모리: 1593.2 MB)
[DRQ]   [Theta] 시작  (메모리: 1593.2 MB)
[메모리] forecast_theta 실행 전: 1593.17 MB
[메모리] forecast_theta 실행 후: 1593.17 MB (변화: +0.00 MB)
[DRQ]   [Theta] 완료  첫값=2.40e+08 (메모리: 1593.2 MB)
[DRQ]   [DB] 93행 저장 완료
[PROGRESS] [ 312/500] ( 62.4%)  >>  HCKT
[HCKT]   44분기 | 2015-06-30 ~ 2026-03-31
[HCKT]   [SARIMA] 시작  (메모리: 1593.2 MB)
[메모리] forecast_sarima 실행 전: 1593.17 MB
[메모리] find_best_sarima_params 실행 전: 1593.17 MB
[메모리] find_best_sarima_params 실행 후: 1593.17 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.17 MB (변화: +0.00 MB)
[HCKT]   [SARIMA] 완료  첫값=7.24e+07 (메모리: 1593.2 MB)
[HCKT]   [ETS] 시작  (메모리: 1593.2 MB)
[메모리] forecast_ets 실행 전: 1593.17 MB
[메모리] forecast_ets 실행 후: 1593.17 MB (변화: +0.00 MB)
[HCKT]   [ETS] 완료  첫값=7.34e+07 (메모리: 1593.2 MB)
[HCKT]   [Prophet] 시작  (메모리: 1593.2 MB)
[메모리] forecast_prophet 실행 전: 1593.17 MB

02:07:16 - cmdstanpy - INFO - Chain [1] start processing
02:07:17 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.19 MB (변화: +0.02 MB)
[HCKT]   [Prophet] 완료  첫값=7.50e+07 (메모리: 1593.2 MB)
[HCKT]   [LSTM] 시작  (메모리: 1593.2 MB)
[메모리] forecast_lstm 실행 전: 1593.19 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.22 MB (변화: +0.03 MB)
[HCKT]   [LSTM] 완료  첫값=7.40e+07 (메모리: 1593.2 MB)
[HCKT]   [Theta] 시작  (메모리: 1593.2 MB)
[메모리] forecast_theta 실행 전: 1593.22 MB
[메모리] forecast_theta 실행 후: 1593.22 MB (변화: +0.00 MB)
[HCKT]   [Theta] 완료  첫값=7.23e+07 (메모리: 1593.2 MB)
[HCKT]   [DB] 92행 저장 완료
[PROGRESS] [ 313/500] ( 62.6%)  >>  SCVL
[SCVL]   45분기 | 2015-03-31 ~ 2026-03-31
[SCVL]   [SARIMA] 시작  (메모리: 1593.2 MB)
[메모리] forecast_sarima 실행 전: 1593.22 MB
[메모리] find_best_sarima_params 실행 전: 1593.22 MB
[메모리] find_best_sarima_params 실행 후: 1593.22 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.22 MB (변화: +0.00 MB)
[SCVL]   [SARIMA] 완료  첫값=3.06e+08 (메모리: 1593.2 MB)
[SCVL]   [ETS] 시작  (메모리: 1593.2 MB)
[메모리] forecast_ets 실행 전: 1593.22 MB
[메모리] forecast_ets 실행 후: 1593.22 MB (변화: +0.00 MB)
[SCVL]   [ETS] 완료  첫값=2.90e+08 (메모리: 1593.2 MB)
[SCVL]   [Prophet] 시작  (메모리: 1593.2 MB)

02:07:33 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1593.22 MB

02:07:33 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.22 MB (변화: +0.00 MB)
[SCVL]   [Prophet] 완료  첫값=3.16e+08 (메모리: 1593.2 MB)
[SCVL]   [LSTM] 시작  (메모리: 1593.2 MB)
[메모리] forecast_lstm 실행 전: 1593.22 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.16 MB (변화: -0.06 MB)
[SCVL]   [LSTM] 완료  첫값=2.89e+08 (메모리: 1593.2 MB)
[SCVL]   [Theta] 시작  (메모리: 1593.2 MB)
[메모리] forecast_theta 실행 전: 1593.16 MB
[메모리] forecast_theta 실행 후: 1593.16 MB (변화: +0.00 MB)
[SCVL]   [Theta] 완료  첫값=2.86e+08 (메모리: 1593.2 MB)
[SCVL]   [DB] 93행 저장 완료
[PROGRESS] [ 314/500] ( 62.8%)  >>  SABR
[SABR]   45분기 | 2015-03-31 ~ 2026-03-31
[SABR]   [SARIMA] 시작  (메모리: 1593.2 MB)
[메모리] forecast_sarima 실행 전: 1593.16 MB
[메모리] find_best_sarima_params 실행 전: 1593.16 MB
[메모리] find_best_sarima_params 실행 후: 1593.16 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.16 MB (변화: +0.00 MB)
[SABR]   [SARIMA] 완료  첫값=7.15e+08 (메모리: 1593.2 MB)
[SABR]   [ETS] 시작  (메모리: 1593.2 MB)
[메모리] forecast_ets 실행 전: 1593.16 MB
[메모리] forecast_ets 실행 후: 1593.16 MB (변화: +0.00 MB)
[SABR]   [ETS] 완료  첫값=6.05e+08 (메모리: 1593.2 MB)
[SABR]   [Prophet] 시작  (메모리: 1593.2 MB)

02:07:56 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1593.16 MB

02:07:56 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.18 MB (변화: +0.02 MB)
[SABR]   [Prophet] 완료  첫값=6.18e+08 (메모리: 1593.2 MB)
[SABR]   [LSTM] 시작  (메모리: 1593.2 MB)
[메모리] forecast_lstm 실행 전: 1593.18 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.13 MB (변화: -0.05 MB)
[SABR]   [LSTM] 완료  첫값=7.24e+08 (메모리: 1593.1 MB)
[SABR]   [Theta] 시작  (메모리: 1593.1 MB)
[메모리] forecast_theta 실행 전: 1593.13 MB
[메모리] forecast_theta 실행 후: 1593.13 MB (변화: +0.00 MB)
[SABR]   [Theta] 완료  첫값=7.12e+08 (메모리: 1593.1 MB)
[SABR]   [DB] 93행 저장 완료
[PROGRESS] [ 315/500] ( 63.0%)  >>  OFIX
[OFIX]   45분기 | 2015-03-31 ~ 2026-03-31
[OFIX]   [SARIMA] 시작  (메모리: 1593.1 MB)
[메모리] forecast_sarima 실행 전: 1593.13 MB
[메모리] find_best_sarima_params 실행 전: 1593.13 MB
[메모리] find_best_sarima_params 실행 후: 1593.13 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.13 MB (변화: +0.00 MB)
[OFIX]   [SARIMA] 완료  첫값=2.11e+08 (메모리: 1593.1 MB)
[OFIX]   [ETS] 시작  (메모리: 1593.1 MB)
[메모리] forecast_ets 실행 전: 1593.13 MB
[메모리] forecast_ets 실행 후: 1593.13 MB (변화: +0.00 MB)
[OFIX]   [ETS] 완료  첫값=2.11e+08 (메모리: 1593.1 MB)
[OFIX]   [Prophet] 시작  (메모리: 1593.1 MB)

02:08:21 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1593.13 MB

02:08:21 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.53 MB (변화: +0.40 MB)
[OFIX]   [Prophet] 완료  첫값=2.17e+08 (메모리: 1593.5 MB)
[OFIX]   [LSTM] 시작  (메모리: 1593.5 MB)
[메모리] forecast_lstm 실행 전: 1593.53 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.52 MB (변화: -0.01 MB)
[OFIX]   [LSTM] 완료  첫값=2.05e+08 (메모리: 1593.5 MB)
[OFIX]   [Theta] 시작  (메모리: 1593.5 MB)
[메모리] forecast_theta 실행 전: 1593.52 MB
[메모리] forecast_theta 실행 후: 1593.52 MB (변화: +0.00 MB)
[OFIX]   [Theta] 완료  첫값=2.06e+08 (메모리: 1593.5 MB)
[OFIX]   [DB] 93행 저장 완료
[PROGRESS] [ 316/500] ( 63.2%)  >>  OCGN
[OCGN]   45분기 | 2015-03-31 ~ 2026-03-31
[OCGN]   [SARIMA] 시작  (메모리: 1593.5 MB)
[메모리] forecast_sarima 실행 전: 1593.52 MB
[메모리] find_best_sarima_params 실행 전: 1593.52 MB
[메모리] find_best_sarima_params 실행 후: 1593.52 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.52 MB (변화: +0.00 MB)
[OCGN]   [SARIMA] 완료  첫값=1.54e+06 (메모리: 1593.5 MB)
[OCGN]   [ETS] 시작  (메모리: 1593.5 MB)
[메모리] forecast_ets 실행 전: 1593.52 MB
[메모리] forecast_ets 실행 후: 1593.53 MB (변화: +0.01 MB)
[OCGN]   [ETS] 완료  첫값=1.71e+06 (메모리: 1593.5 MB)
[OCGN]   [Prophet] 시작  (메모리: 1593.5 MB)

02:08:38 - cmdstanpy - INFO - Chain [1] start processing
02:08:38 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1593.53 MB
[메모리] forecast_prophet 실행 후: 1593.55 MB (변화: +0.02 MB)
[OCGN]   [Prophet] 완료  첫값=1.59e+06 (메모리: 1593.6 MB)
[OCGN]   [LSTM] 시작  (메모리: 1593.6 MB)
[메모리] forecast_lstm 실행 전: 1593.55 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.56 MB (변화: +0.01 MB)
[OCGN]   [LSTM] 완료  첫값=1.96e+06 (메모리: 1593.6 MB)
[OCGN]   [Theta] 시작  (메모리: 1593.6 MB)
[메모리] forecast_theta 실행 전: 1593.56 MB
[메모리] forecast_theta 실행 후: 1593.56 MB (변화: +0.00 MB)
[OCGN]   [Theta] 완료  첫값=1.76e+06 (메모리: 1593.6 MB)
[OCGN]   [DB] 93행 저장 완료
[PROGRESS] [ 317/500] ( 63.4%)  >>  FTK
[FTK]   45분기 | 2015-03-31 ~ 2026-03-31
[FTK]   [SARIMA] 시작  (메모리: 1593.6 MB)
[메모리] forecast_sarima 실행 전: 1593.56 MB
[메모리] find_best_sarima_params 실행 전: 1593.56 MB
[메모리] find_best_sarima_params 실행 후: 1593.57 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.57 MB (변화: +0.00 MB)
[FTK]   [SARIMA] 완료  첫값=5.60e+07 (메모리: 1593.6 MB)
[FTK]   [ETS] 시작  (메모리: 1593.6 MB)
[메모리] forecast_ets 실행 전: 1593.57 MB
[메모리] forecast_ets 실행 후: 1593.57 MB (변화: +0.00 MB)
[FTK]   [ETS] 완료  첫값=5.55e+07 (메모리: 1593.6 MB)
[FTK]   [Prophet] 시작  (메모리: 1593.6 MB)

02:08:58 - cmdstanpy - INFO - Chain [1] start processing
02:08:58 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1593.57 MB
[메모리] forecast_prophet 실행 후: 1593.58 MB (변화: +0.01 MB)
[FTK]   [Prophet] 완료  첫값=2.95e+07 (메모리: 1593.6 MB)
[FTK]   [LSTM] 시작  (메모리: 1593.6 MB)
[메모리] forecast_lstm 실행 전: 1593.58 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.58 MB (변화: +0.00 MB)
[FTK]   [LSTM] 완료  첫값=4.40e+07 (메모리: 1593.6 MB)
[FTK]   [Theta] 시작  (메모리: 1593.6 MB)
[메모리] forecast_theta 실행 전: 1593.58 MB
[메모리] forecast_theta 실행 후: 1593.58 MB (변화: +0.00 MB)
[FTK]   [Theta] 완료  첫값=5.51e+07 (메모리: 1593.6 MB)
[FTK]   [DB] 93행 저장 완료
[PROGRESS] [ 318/500] ( 63.6%)  >>  PBPB
[PBPB]   45분기 | 2015-03-31 ~ 2026-03-31
[PBPB]   [SARIMA] 시작  (메모리: 1593.6 MB)
[메모리] forecast_sarima 실행 전: 1593.58 MB
[메모리] find_best_sarima_params 실행 전: 1593.58 MB
[메모리] find_best_sarima_params 실행 후: 1593.58 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.58 MB (변화: +0.00 MB)
[PBPB]   [SARIMA] 완료  첫값=1.24e+08 (메모리: 1593.6 MB)
[PBPB]   [ETS] 시작  (메모리: 1593.6 MB)
[메모리] forecast_ets 실행 전: 1593.58 MB
[메모리] forecast_ets 실행 후: 1593.58 MB (변화: +0.00 MB)
[PBPB]   [ETS] 완료  첫값=1.28e+08 (메모리: 1593.6 MB)
[PBPB]   [Prophet] 시작  (메모리: 1593.6 MB)

02:09:18 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1593.58 MB

02:09:18 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.58 MB (변화: +0.00 MB)
[PBPB]   [Prophet] 완료  첫값=1.19e+08 (메모리: 1593.6 MB)
[PBPB]   [LSTM] 시작  (메모리: 1593.6 MB)
[메모리] forecast_lstm 실행 전: 1593.58 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.56 MB (변화: -0.02 MB)
[PBPB]   [LSTM] 완료  첫값=1.29e+08 (메모리: 1593.6 MB)
[PBPB]   [Theta] 시작  (메모리: 1593.6 MB)
[메모리] forecast_theta 실행 전: 1593.56 MB
[메모리] forecast_theta 실행 후: 1593.56 MB (변화: +0.00 MB)
[PBPB]   [Theta] 완료  첫값=1.24e+08 (메모리: 1593.6 MB)
[PBPB]   [DB] 93행 저장 완료
[PROGRESS] [ 319/500] ( 63.8%)  >>  FET
[FET]   45분기 | 2015-03-31 ~ 2026-03-31
[FET]   [SARIMA] 시작  (메모리: 1593.6 MB)
[메모리] forecast_sarima 실행 전: 1593.56 MB
[메모리] find_best_sarima_params 실행 전: 1593.56 MB
[메모리] find_best_sarima_params 실행 후: 1593.56 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.56 MB (변화: +0.00 MB)
[FET]   [SARIMA] 완료  첫값=1.96e+08 (메모리: 1593.6 MB)
[FET]   [ETS] 시작  (메모리: 1593.6 MB)
[메모리] forecast_ets 실행 전: 1593.56 MB
[메모리] forecast_ets 실행 후: 1593.57 MB (변화: +0.01 MB)
[FET]   [ETS] 완료  첫값=1.91e+08 (메모리: 1593.6 MB)
[FET]   [Prophet] 시작  (메모리: 1593.6 MB)
[메모리] forecast_prophet 실행 전: 1593.57 MB

02:09:35 - cmdstanpy - INFO - Chain [1] start processing
02:09:35 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.58 MB (변화: +0.01 MB)
[FET]   [Prophet] 완료  첫값=1.71e+08 (메모리: 1593.6 MB)
[FET]   [LSTM] 시작  (메모리: 1593.6 MB)
[메모리] forecast_lstm 실행 전: 1593.58 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.57 MB (변화: -0.02 MB)
[FET]   [LSTM] 완료  첫값=2.04e+08 (메모리: 1593.6 MB)
[FET]   [Theta] 시작  (메모리: 1593.6 MB)
[메모리] forecast_theta 실행 전: 1593.57 MB
[메모리] forecast_theta 실행 후: 1593.57 MB (변화: +0.00 MB)
[FET]   [Theta] 완료  첫값=1.96e+08 (메모리: 1593.6 MB)
[FET]   [DB] 93행 저장 완료
[PROGRESS] [ 320/500] ( 64.0%)  >>  THM
[THM]   45분기 | 2015-03-31 ~ 2026-03-31
[THM]   [SARIMA] 시작  (메모리: 1593.6 MB)
[메모리] forecast_sarima 실행 전: 1593.57 MB
[메모리] find_best_sarima_params 실행 전: 1593.57 MB
[메모리] find_best_sarima_params 실행 후: 1593.57 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.57 MB (변화: +0.00 MB)
[THM]   [SARIMA] 완료  첫값=2.43e+02 (메모리: 1593.6 MB)
[THM]   [ETS] 시작  (메모리: 1593.6 MB)
[메모리] forecast_ets 실행 전: 1593.57 MB
[메모리] forecast_ets 실행 후: 1593.57 MB (변화: +0.00 MB)
[THM]   [ETS] 완료  첫값=-2.08e+02 (메모리: 1593.6 MB)
[THM]   [Prophet] 시작  (메모리: 1593.6 MB)

02:09:51 - cmdstanpy - INFO - Chain [1] start processing
02:09:51 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1593.57 MB
[메모리] forecast_prophet 실행 후: 1593.58 MB (변화: +0.01 MB)
[THM]   [Prophet] 완료  첫값=-3.20e+02 (메모리: 1593.6 MB)
[THM]   [LSTM] 시작  (메모리: 1593.6 MB)
[메모리] forecast_lstm 실행 전: 1593.58 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.69 MB (변화: +0.11 MB)
[THM]   [LSTM] 완료  첫값=5.56e+02 (메모리: 1593.7 MB)
[THM]   [Theta] 시작  (메모리: 1593.7 MB)
[메모리] forecast_theta 실행 전: 1593.69 MB
[메모리] forecast_theta 실행 후: 1593.69 MB (변화: +0.00 MB)
[THM]   [Theta] 완료  첫값=-6.05e+02 (메모리: 1593.7 MB)
[THM]   [DB] 93행 저장 완료
[PROGRESS] [ 321/500] ( 64.2%)  >>  PANL
[PANL]   45분기 | 2015-03-31 ~ 2026-03-31
[PANL]   [SARIMA] 시작  (메모리: 1593.7 MB)
[메모리] forecast_sarima 실행 전: 1593.69 MB
[메모리] find_best_sarima_params 실행 전: 1593.69 MB
[메모리] find_best_sarima_params 실행 후: 1593.69 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.69 MB (변화: +0.00 MB)
[PANL]   [SARIMA] 완료  첫값=1.84e+08 (메모리: 1593.7 MB)
[PANL]   [ETS] 시작  (메모리: 1593.7 MB)
[메모리] forecast_ets 실행 전: 1593.69 MB
[메모리] forecast_ets 실행 후: 1593.69 MB (변화: +0.00 MB)
[PANL]   [ETS] 완료  첫값=1.78e+08 (메모리: 1593.7 MB)
[PANL]   [Prophet] 시작  (메모리: 1593.7 MB)

02:10:12 - cmdstanpy - INFO - Chain [1] start processing
02:10:12 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1593.69 MB
[메모리] forecast_prophet 실행 후: 1593.70 MB (변화: +0.00 MB)
[PANL]   [Prophet] 완료  첫값=1.73e+08 (메모리: 1593.7 MB)
[PANL]   [LSTM] 시작  (메모리: 1593.7 MB)
[메모리] forecast_lstm 실행 전: 1593.70 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.66 MB (변화: -0.04 MB)
[PANL]   [LSTM] 완료  첫값=1.48e+08 (메모리: 1593.7 MB)
[PANL]   [Theta] 시작  (메모리: 1593.7 MB)
[메모리] forecast_theta 실행 전: 1593.66 MB
[메모리] forecast_theta 실행 후: 1593.66 MB (변화: +0.00 MB)
[PANL]   [Theta] 완료  첫값=1.84e+08 (메모리: 1593.7 MB)
[PANL]   [DB] 93행 저장 완료
[PROGRESS] [ 322/500] ( 64.4%)  >>  INN
[INN]   45분기 | 2015-03-31 ~ 2026-03-31
[INN]   [SARIMA] 시작  (메모리: 1593.7 MB)
[메모리] forecast_sarima 실행 전: 1593.66 MB
[메모리] find_best_sarima_params 실행 전: 1593.66 MB
[메모리] find_best_sarima_params 실행 후: 1593.66 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.66 MB (변화: +0.00 MB)
[INN]   [SARIMA] 완료  첫값=1.77e+08 (메모리: 1593.7 MB)
[INN]   [ETS] 시작  (메모리: 1593.7 MB)
[메모리] forecast_ets 실행 전: 1593.66 MB
[메모리] forecast_ets 실행 후: 1593.66 MB (변화: +0.00 MB)
[INN]   [ETS] 완료  첫값=1.75e+08 (메모리: 1593.7 MB)
[INN]   [Prophet] 시작  (메모리: 1593.7 MB)

02:10:31 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1593.66 MB

02:10:31 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.67 MB (변화: +0.01 MB)
[INN]   [Prophet] 완료  첫값=1.78e+08 (메모리: 1593.7 MB)
[INN]   [LSTM] 시작  (메모리: 1593.7 MB)
[메모리] forecast_lstm 실행 전: 1593.67 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.68 MB (변화: +0.02 MB)
[INN]   [LSTM] 완료  첫값=1.62e+08 (메모리: 1593.7 MB)
[INN]   [Theta] 시작  (메모리: 1593.7 MB)
[메모리] forecast_theta 실행 전: 1593.68 MB
[메모리] forecast_theta 실행 후: 1593.68 MB (변화: +0.00 MB)
[INN]   [Theta] 완료  첫값=1.78e+08 (메모리: 1593.7 MB)
[INN]   [DB] 93행 저장 완료
[PROGRESS] [ 323/500] ( 64.6%)  >>  FEIM
[FEIM]   45분기 | 2015-03-31 ~ 2026-03-31
[FEIM]   [SARIMA] 시작  (메모리: 1593.7 MB)
[메모리] forecast_sarima 실행 전: 1593.68 MB
[메모리] find_best_sarima_params 실행 전: 1593.68 MB
[메모리] find_best_sarima_params 실행 후: 1593.68 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.68 MB (변화: +0.00 MB)
[FEIM]   [SARIMA] 완료  첫값=1.71e+07 (메모리: 1593.7 MB)
[FEIM]   [ETS] 시작  (메모리: 1593.7 MB)
[메모리] forecast_ets 실행 전: 1593.68 MB
[메모리] forecast_ets 실행 후: 1593.68 MB (변화: +0.00 MB)
[FEIM]   [ETS] 완료  첫값=1.75e+07 (메모리: 1593.7 MB)
[FEIM]   [Prophet] 시작  (메모리: 1593.7 MB)

02:10:49 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1593.68 MB

02:10:49 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.70 MB (변화: +0.01 MB)
[FEIM]   [Prophet] 완료  첫값=1.39e+07 (메모리: 1593.7 MB)
[FEIM]   [LSTM] 시작  (메모리: 1593.7 MB)
[메모리] forecast_lstm 실행 전: 1593.70 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.64 MB (변화: -0.05 MB)
[FEIM]   [LSTM] 완료  첫값=1.45e+07 (메모리: 1593.6 MB)
[FEIM]   [Theta] 시작  (메모리: 1593.6 MB)
[메모리] forecast_theta 실행 전: 1593.64 MB
[메모리] forecast_theta 실행 후: 1593.64 MB (변화: +0.00 MB)
[FEIM]   [Theta] 완료  첫값=1.70e+07 (메모리: 1593.6 MB)
[FEIM]   [DB] 93행 저장 완료
[PROGRESS] [ 324/500] ( 64.8%)  >>  ZVRA
[ZVRA]   45분기 | 2015-03-31 ~ 2026-03-31
[ZVRA]   [SARIMA] 시작  (메모리: 1593.6 MB)
[메모리] forecast_sarima 실행 전: 1593.64 MB
[메모리] find_best_sarima_params 실행 전: 1593.64 MB
[메모리] find_best_sarima_params 실행 후: 1593.64 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.64 MB (변화: +0.00 MB)
[ZVRA]   [SARIMA] 완료  첫값=1.95e+07 (메모리: 1593.6 MB)
[ZVRA]   [ETS] 시작  (메모리: 1593.6 MB)
[메모리] forecast_ets 실행 전: 1593.64 MB
[메모리] forecast_ets 실행 후: 1593.64 MB (변화: +0.00 MB)
[ZVRA]   [ETS] 완료  첫값=2.66e+07 (메모리: 1593.6 MB)
[ZVRA]   [Prophet] 시작  (메모리: 1593.6 MB)

02:11:05 - cmdstanpy - INFO - Chain [1] start processing
02:11:05 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1593.64 MB
[메모리] forecast_prophet 실행 후: 1593.66 MB (변화: +0.02 MB)
[ZVRA]   [Prophet] 완료  첫값=1.54e+07 (메모리: 1593.7 MB)
[ZVRA]   [LSTM] 시작  (메모리: 1593.7 MB)
[메모리] forecast_lstm 실행 전: 1593.66 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.73 MB (변화: +0.07 MB)
[ZVRA]   [LSTM] 완료  첫값=3.01e+07 (메모리: 1593.7 MB)
[ZVRA]   [Theta] 시작  (메모리: 1593.7 MB)
[메모리] forecast_theta 실행 전: 1593.73 MB
[메모리] forecast_theta 실행 후: 1593.73 MB (변화: +0.00 MB)
[ZVRA]   [Theta] 완료  첫값=2.63e+07 (메모리: 1593.7 MB)
[ZVRA]   [DB] 93행 저장 완료
[PROGRESS] [ 325/500] ( 65.0%)  >>  CYRX
[CYRX]   45분기 | 2015-03-31 ~ 2026-03-31
[CYRX]   [SARIMA] 시작  (메모리: 1593.7 MB)
[메모리] forecast_sarima 실행 전: 1593.73 MB
[메모리] find_best_sarima_params 실행 전: 1593.73 MB
[메모리] find_best_sarima_params 실행 후: 1592.57 MB (변화: -1.17 MB)
[메모리] forecast_sarima 실행 후: 1592.57 MB (변화: -1.17 MB)
[CYRX]   [SARIMA] 완료  첫값=4.80e+07 (메모리: 1592.6 MB)
[CYRX]   [ETS] 시작  (메모리: 1592.6 MB)
[메모리] forecast_ets 실행 전: 1592.57 MB
[메모리] forecast_ets 실행 후: 1592.57 MB (변화: +0.00 MB)
[CYRX]   [ETS] 완료  첫값=4.90e+07 (메모리: 1592.6 MB)
[CYRX]   [Prophet] 시작  (메모리: 1592.6 MB)
[메모리] forecast_prophet 실행 전: 1592.57 MB

02:11:29 - cmdstanpy - INFO - Chain [1] start processing
02:11:29 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1592.98 MB (변화: +0.42 MB)
[CYRX]   [Prophet] 완료  첫값=6.44e+07 (메모리: 1593.0 MB)
[CYRX]   [LSTM] 시작  (메모리: 1593.0 MB)
[메모리] forecast_lstm 실행 전: 1592.98 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.00 MB (변화: +0.01 MB)
[CYRX]   [LSTM] 완료  첫값=5.13e+07 (메모리: 1593.0 MB)
[CYRX]   [Theta] 시작  (메모리: 1593.0 MB)
[메모리] forecast_theta 실행 전: 1593.00 MB
[메모리] forecast_theta 실행 후: 1593.00 MB (변화: +0.00 MB)
[CYRX]   [Theta] 완료  첫값=4.70e+07 (메모리: 1593.0 MB)
[CYRX]   [DB] 93행 저장 완료
[PROGRESS] [ 326/500] ( 65.2%)  >>  SOHU
[SOHU]   45분기 | 2015-03-31 ~ 2026-03-31
[SOHU]   [SARIMA] 시작  (메모리: 1593.0 MB)
[메모리] forecast_sarima 실행 전: 1593.00 MB
[메모리] find_best_sarima_params 실행 전: 1593.00 MB
[메모리] find_best_sarima_params 실행 후: 1593.00 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.00 MB (변화: +0.00 MB)
[SOHU]   [SARIMA] 완료  첫값=1.39e+08 (메모리: 1593.0 MB)
[SOHU]   [ETS] 시작  (메모리: 1593.0 MB)
[메모리] forecast_ets 실행 전: 1593.00 MB
[메모리] forecast_ets 실행 후: 1593.00 MB (변화: +0.00 MB)
[SOHU]   [ETS] 완료  첫값=1.46e+08 (메모리: 1593.0 MB)
[SOHU]   [Prophet] 시작  (메모리: 1593.0 MB)

02:11:54 - cmdstanpy - INFO - Chain [1] start processing
02:11:54 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1593.00 MB
[메모리] forecast_prophet 실행 후: 1593.02 MB (변화: +0.02 MB)
[SOHU]   [Prophet] 완료  첫값=7.12e+07 (메모리: 1593.0 MB)
[SOHU]   [LSTM] 시작  (메모리: 1593.0 MB)
[메모리] forecast_lstm 실행 전: 1593.02 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1592.98 MB (변화: -0.04 MB)
[SOHU]   [LSTM] 완료  첫값=1.52e+08 (메모리: 1593.0 MB)
[SOHU]   [Theta] 시작  (메모리: 1593.0 MB)
[메모리] forecast_theta 실행 전: 1592.98 MB
[메모리] forecast_theta 실행 후: 1592.98 MB (변화: +0.00 MB)
[SOHU]   [Theta] 완료  첫값=1.48e+08 (메모리: 1593.0 MB)
[SOHU]   [DB] 93행 저장 완료
[PROGRESS] [ 327/500] ( 65.4%)  >>  LGTY
[LGTY]   45분기 | 2015-03-31 ~ 2026-03-31
[LGTY]   [SARIMA] 시작  (메모리: 1593.0 MB)
[메모리] forecast_sarima 실행 전: 1592.98 MB
[메모리] find_best_sarima_params 실행 전: 1592.98 MB
[메모리] find_best_sarima_params 실행 후: 1592.98 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1592.98 MB (변화: +0.00 MB)
[LGTY]   [SARIMA] 완료  첫값=2.53e+07 (메모리: 1593.0 MB)
[LGTY]   [ETS] 시작  (메모리: 1593.0 MB)
[메모리] forecast_ets 실행 전: 1592.98 MB
[메모리] forecast_ets 실행 후: 1592.99 MB (변화: +0.00 MB)
[LGTY]   [ETS] 완료  첫값=2.56e+07 (메모리: 1593.0 MB)
[LGTY]   [Prophet] 시작  (메모리: 1593.0 MB)
[메모리] forecast_prophet 실행 전: 1592.99 MB

02:12:15 - cmdstanpy - INFO - Chain [1] start processing
02:12:15 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.00 MB (변화: +0.01 MB)
[LGTY]   [Prophet] 완료  첫값=2.52e+07 (메모리: 1593.0 MB)
[LGTY]   [LSTM] 시작  (메모리: 1593.0 MB)
[메모리] forecast_lstm 실행 전: 1593.00 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.01 MB (변화: +0.01 MB)
[LGTY]   [LSTM] 완료  첫값=2.69e+07 (메모리: 1593.0 MB)
[LGTY]   [Theta] 시작  (메모리: 1593.0 MB)
[메모리] forecast_theta 실행 전: 1593.01 MB
[메모리] forecast_theta 실행 후: 1593.01 MB (변화: +0.00 MB)
[LGTY]   [Theta] 완료  첫값=2.53e+07 (메모리: 1593.0 MB)
[LGTY]   [DB] 93행 저장 완료
[PROGRESS] [ 328/500] ( 65.6%)  >>  BDN
[BDN]   45분기 | 2015-03-31 ~ 2026-03-31
[BDN]   [SARIMA] 시작  (메모리: 1593.0 MB)
[메모리] forecast_sarima 실행 전: 1593.01 MB
[메모리] find_best_sarima_params 실행 전: 1593.01 MB
[메모리] find_best_sarima_params 실행 후: 1593.01 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.01 MB (변화: +0.00 MB)
[BDN]   [SARIMA] 완료  첫값=1.20e+08 (메모리: 1593.0 MB)
[BDN]   [ETS] 시작  (메모리: 1593.0 MB)
[메모리] forecast_ets 실행 전: 1593.01 MB
[메모리] forecast_ets 실행 후: 1593.01 MB (변화: +0.00 MB)
[BDN]   [ETS] 완료  첫값=1.18e+08 (메모리: 1593.0 MB)
[BDN]   [Prophet] 시작  (메모리: 1593.0 MB)

02:12:39 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1593.01 MB

02:12:39 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.02 MB (변화: +0.02 MB)
[BDN]   [Prophet] 완료  첫값=1.21e+08 (메모리: 1593.0 MB)
[BDN]   [LSTM] 시작  (메모리: 1593.0 MB)
[메모리] forecast_lstm 실행 전: 1593.02 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.02 MB (변화: +0.00 MB)
[BDN]   [LSTM] 완료  첫값=1.26e+08 (메모리: 1593.0 MB)
[BDN]   [Theta] 시작  (메모리: 1593.0 MB)
[메모리] forecast_theta 실행 전: 1593.02 MB
[메모리] forecast_theta 실행 후: 1593.02 MB (변화: +0.00 MB)
[BDN]   [Theta] 완료  첫값=1.21e+08 (메모리: 1593.0 MB)
[BDN]   [DB] 93행 저장 완료
[PROGRESS] [ 329/500] ( 65.8%)  >>  OIS
[OIS]   45분기 | 2015-03-31 ~ 2026-03-31
[OIS]   [SARIMA] 시작  (메모리: 1593.0 MB)
[메모리] forecast_sarima 실행 전: 1593.02 MB
[메모리] find_best_sarima_params 실행 전: 1593.02 MB
[메모리] find_best_sarima_params 실행 후: 1593.02 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.02 MB (변화: +0.00 MB)
[OIS]   [SARIMA] 완료  첫값=1.65e+08 (메모리: 1593.0 MB)
[OIS]   [ETS] 시작  (메모리: 1593.0 MB)
[메모리] forecast_ets 실행 전: 1593.02 MB
[메모리] forecast_ets 실행 후: 1593.03 MB (변화: +0.00 MB)
[OIS]   [ETS] 완료  첫값=1.66e+08 (메모리: 1593.0 MB)
[OIS]   [Prophet] 시작  (메모리: 1593.0 MB)

02:13:00 - cmdstanpy - INFO - Chain [1] start processing
02:13:00 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1593.03 MB
[메모리] forecast_prophet 실행 후: 1593.04 MB (변화: +0.01 MB)
[OIS]   [Prophet] 완료  첫값=1.57e+08 (메모리: 1593.0 MB)
[OIS]   [LSTM] 시작  (메모리: 1593.0 MB)
[메모리] forecast_lstm 실행 전: 1593.04 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.03 MB (변화: -0.00 MB)
[OIS]   [LSTM] 완료  첫값=1.75e+08 (메모리: 1593.0 MB)
[OIS]   [Theta] 시작  (메모리: 1593.0 MB)
[메모리] forecast_theta 실행 전: 1593.03 MB
[메모리] forecast_theta 실행 후: 1593.03 MB (변화: +0.00 MB)
[OIS]   [Theta] 완료  첫값=1.65e+08 (메모리: 1593.0 MB)
[OIS]   [DB] 93행 저장 완료
[PROGRESS] [ 330/500] ( 66.0%)  >>  TAST
[TAST]   45분기 | 2015-03-31 ~ 2026-03-31
[TAST]   [SARIMA] 시작  (메모리: 1593.0 MB)
[메모리] forecast_sarima 실행 전: 1593.03 MB
[메모리] find_best_sarima_params 실행 전: 1593.03 MB
[메모리] find_best_sarima_params 실행 후: 1593.03 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.03 MB (변화: +0.00 MB)
[TAST]   [SARIMA] 완료  첫값=4.61e+08 (메모리: 1593.0 MB)
[TAST]   [ETS] 시작  (메모리: 1593.0 MB)
[메모리] forecast_ets 실행 전: 1593.03 MB
[메모리] forecast_ets 실행 후: 1593.03 MB (변화: +0.00 MB)
[TAST]   [ETS] 완료  첫값=4.54e+08 (메모리: 1593.0 MB)
[TAST]   [Prophet] 시작  (메모리: 1593.0 MB)
[메모리] forecast_prophet 실행 전: 1593.03 MB

02:13:21 - cmdstanpy - INFO - Chain [1] start processing
02:13:21 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.04 MB (변화: +0.01 MB)
[TAST]   [Prophet] 완료  첫값=4.79e+08 (메모리: 1593.0 MB)
[TAST]   [LSTM] 시작  (메모리: 1593.0 MB)
[메모리] forecast_lstm 실행 전: 1593.04 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.01 MB (변화: -0.03 MB)
[TAST]   [LSTM] 완료  첫값=4.74e+08 (메모리: 1593.0 MB)
[TAST]   [Theta] 시작  (메모리: 1593.0 MB)
[메모리] forecast_theta 실행 전: 1593.01 MB
[메모리] forecast_theta 실행 후: 1593.01 MB (변화: +0.00 MB)
[TAST]   [Theta] 완료  첫값=4.52e+08 (메모리: 1593.0 MB)
[TAST]   [DB] 93행 저장 완료
[PROGRESS] [ 331/500] ( 66.2%)  >>  DVS
[DVS]   45분기 | 2015-03-31 ~ 2026-03-31
[DVS]   [SARIMA] 시작  (메모리: 1593.0 MB)
[메모리] forecast_sarima 실행 전: 1593.01 MB
[메모리] find_best_sarima_params 실행 전: 1593.01 MB
[메모리] find_best_sarima_params 실행 후: 1593.01 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.01 MB (변화: +0.00 MB)
[DVS]   [SARIMA] 완료  첫값=0.00e+00 (메모리: 1593.0 MB)
[DVS]   [ETS] 시작  (메모리: 1593.0 MB)
[메모리] forecast_ets 실행 전: 1593.01 MB
[메모리] forecast_ets 실행 후: 1593.01 MB (변화: +0.00 MB)
[DVS]   [ETS] 완료  첫값=0.00e+00 (메모리: 1593.0 MB)
[DVS]   [Prophet] 시작  (메모리: 1593.0 MB)
[메모리] forecast_prophet 실행 전: 1593.01 MB
[메모리] forecast_prophet 실행 후: 1593.02 MB (변화: +0.01 MB)
[DVS]   [Prophet] 완료  첫값=0.00e+00 (메모리: 1593.0 MB)
[DVS]   [LSTM] 시작  (메모리: 1593.0 MB)
[메모리] forecast_lstm 실행 전: 1593.02 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.00 MB (변화: -0.02 MB)
[DVS]   [LSTM] 완료  첫값=0.00e+00 (메모리: 1593.0 MB)
[DVS]   [Theta] 시작  (메모리: 1593.0 MB)
[메모리] forecast_theta 실행 전: 1593.00 MB
[메모리] forecast_theta 실행 후: 1593.00 MB (변화: +0.00 MB)
[DVS]   [Theta] 완료  첫값=0.00e+00 (메모리: 1593.0 MB)
[DVS]   [DB] 93행 저장 완료
[PROGRESS] [ 332/500] ( 66.4%)  >>  RBBN
[RBBN]   45분기 | 2015-03-31 ~ 2026-03-31
[RBBN]   [SARIMA] 시작  (메모리: 1593.0 MB)
[메모리] forecast_sarima 실행 전: 1593.00 MB
[메모리] find_best_sarima_params 실행 전: 1593.00 MB
[메모리] find_best_sarima_params 실행 후: 1593.00 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.00 MB (변화: +0.00 MB)
[RBBN]   [SARIMA] 완료  첫값=2.80e+08 (메모리: 1593.0 MB)
[RBBN]   [ETS] 시작  (메모리: 1593.0 MB)
[메모리] forecast_ets 실행 전: 1593.00 MB
[메모리] forecast_ets 실행 후: 1593.00 MB (변화: +0.00 MB)
[RBBN]   [ETS] 완료  첫값=2.59e+08 (메모리: 1593.0 MB)
[RBBN]   [Prophet] 시작  (메모리: 1593.0 MB)

02:14:04 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1593.00 MB

02:14:04 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.01 MB (변화: +0.00 MB)
[RBBN]   [Prophet] 완료  첫값=2.59e+08 (메모리: 1593.0 MB)
[RBBN]   [LSTM] 시작  (메모리: 1593.0 MB)
[메모리] forecast_lstm 실행 전: 1593.01 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1592.98 MB (변화: -0.03 MB)
[RBBN]   [LSTM] 완료  첫값=2.17e+08 (메모리: 1593.0 MB)
[RBBN]   [Theta] 시작  (메모리: 1593.0 MB)
[메모리] forecast_theta 실행 전: 1592.98 MB
[메모리] forecast_theta 실행 후: 1592.98 MB (변화: +0.00 MB)
[RBBN]   [Theta] 완료  첫값=2.57e+08 (메모리: 1593.0 MB)
[RBBN]   [DB] 93행 저장 완료
[PROGRESS] [ 333/500] ( 66.6%)  >>  SWBI
[SWBI]   45분기 | 2015-03-31 ~ 2026-03-31
[SWBI]   [SARIMA] 시작  (메모리: 1593.0 MB)
[메모리] forecast_sarima 실행 전: 1592.98 MB
[메모리] find_best_sarima_params 실행 전: 1592.98 MB
[메모리] find_best_sarima_params 실행 후: 1592.98 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1592.98 MB (변화: +0.00 MB)
[SWBI]   [SARIMA] 완료  첫값=1.41e+08 (메모리: 1593.0 MB)
[SWBI]   [ETS] 시작  (메모리: 1593.0 MB)
[메모리] forecast_ets 실행 전: 1592.98 MB
[메모리] forecast_ets 실행 후: 1592.98 MB (변화: +0.00 MB)
[SWBI]   [ETS] 완료  첫값=1.44e+08 (메모리: 1593.0 MB)
[SWBI]   [Prophet] 시작  (메모리: 1593.0 MB)

02:14:25 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1592.98 MB

02:14:25 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.00 MB (변화: +0.02 MB)
[SWBI]   [Prophet] 완료  첫값=1.36e+08 (메모리: 1593.0 MB)
[SWBI]   [LSTM] 시작  (메모리: 1593.0 MB)
[메모리] forecast_lstm 실행 전: 1593.00 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1592.95 MB (변화: -0.05 MB)
[SWBI]   [LSTM] 완료  첫값=1.44e+08 (메모리: 1592.9 MB)
[SWBI]   [Theta] 시작  (메모리: 1592.9 MB)
[메모리] forecast_theta 실행 전: 1592.95 MB
[메모리] forecast_theta 실행 후: 1592.95 MB (변화: +0.00 MB)
[SWBI]   [Theta] 완료  첫값=1.42e+08 (메모리: 1592.9 MB)
[SWBI]   [DB] 93행 저장 완료
[PROGRESS] [ 334/500] ( 66.8%)  >>  LWLG
[LWLG]   45분기 | 2015-03-31 ~ 2026-03-31
[LWLG]   [SARIMA] 시작  (메모리: 1592.9 MB)
[메모리] forecast_sarima 실행 전: 1592.95 MB
[메모리] find_best_sarima_params 실행 전: 1592.95 MB
[메모리] find_best_sarima_params 실행 후: 1592.95 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1592.95 MB (변화: +0.00 MB)
[LWLG]   [SARIMA] 완료  첫값=3.10e+04 (메모리: 1592.9 MB)
[LWLG]   [ETS] 시작  (메모리: 1592.9 MB)
[메모리] forecast_ets 실행 전: 1592.95 MB
[메모리] forecast_ets 실행 후: 1592.95 MB (변화: +0.00 MB)
[LWLG]   [ETS] 완료  첫값=2.84e+04 (메모리: 1593.0 MB)
[LWLG]   [Prophet] 시작  (메모리: 1593.0 MB)

02:14:44 - cmdstanpy - INFO - Chain [1] start processing
02:14:44 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1592.95 MB
[메모리] forecast_prophet 실행 후: 1592.97 MB (변화: +0.02 MB)
[LWLG]   [Prophet] 완료  첫값=1.56e+04 (메모리: 1593.0 MB)
[LWLG]   [LSTM] 시작  (메모리: 1593.0 MB)
[메모리] forecast_lstm 실행 전: 1592.97 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.01 MB (변화: +0.04 MB)
[LWLG]   [LSTM] 완료  첫값=3.31e+04 (메모리: 1593.0 MB)
[LWLG]   [Theta] 시작  (메모리: 1593.0 MB)
[메모리] forecast_theta 실행 전: 1593.01 MB
[메모리] forecast_theta 실행 후: 1593.01 MB (변화: +0.00 MB)
[LWLG]   [Theta] 완료  첫값=2.17e+04 (메모리: 1593.0 MB)
[LWLG]   [DB] 93행 저장 완료
[PROGRESS] [ 335/500] ( 67.0%)  >>  NAGE
[NAGE]   45분기 | 2015-03-31 ~ 2026-03-31
[NAGE]   [SARIMA] 시작  (메모리: 1593.0 MB)
[메모리] forecast_sarima 실행 전: 1593.01 MB
[메모리] find_best_sarima_params 실행 전: 1593.01 MB
[메모리] find_best_sarima_params 실행 후: 1593.01 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.01 MB (변화: +0.00 MB)
[NAGE]   [SARIMA] 완료  첫값=3.43e+07 (메모리: 1593.0 MB)
[NAGE]   [ETS] 시작  (메모리: 1593.0 MB)
[메모리] forecast_ets 실행 전: 1593.01 MB
[메모리] forecast_ets 실행 후: 1593.01 MB (변화: +0.00 MB)
[NAGE]   [ETS] 완료  첫값=3.79e+07 (메모리: 1593.0 MB)
[NAGE]   [Prophet] 시작  (메모리: 1593.0 MB)

02:15:10 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1593.01 MB

02:15:10 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.02 MB (변화: +0.01 MB)
[NAGE]   [Prophet] 완료  첫값=3.27e+07 (메모리: 1593.0 MB)
[NAGE]   [LSTM] 시작  (메모리: 1593.0 MB)
[메모리] forecast_lstm 실행 전: 1593.02 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.06 MB (변화: +0.04 MB)
[NAGE]   [LSTM] 완료  첫값=3.89e+07 (메모리: 1593.1 MB)
[NAGE]   [Theta] 시작  (메모리: 1593.1 MB)
[메모리] forecast_theta 실행 전: 1593.06 MB
[메모리] forecast_theta 실행 후: 1593.06 MB (변화: +0.00 MB)
[NAGE]   [Theta] 완료  첫값=3.64e+07 (메모리: 1593.1 MB)
[NAGE]   [DB] 93행 저장 완료
[PROGRESS] [ 336/500] ( 67.2%)  >>  DIN
[DIN]   45분기 | 2015-03-31 ~ 2026-03-31
[DIN]   [SARIMA] 시작  (메모리: 1593.1 MB)
[메모리] forecast_sarima 실행 전: 1593.06 MB
[메모리] find_best_sarima_params 실행 전: 1593.06 MB
[메모리] find_best_sarima_params 실행 후: 1593.06 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.06 MB (변화: +0.00 MB)
[DIN]   [SARIMA] 완료  첫값=2.25e+08 (메모리: 1593.1 MB)
[DIN]   [ETS] 시작  (메모리: 1593.1 MB)
[메모리] forecast_ets 실행 전: 1593.06 MB
[메모리] forecast_ets 실행 후: 1593.06 MB (변화: +0.00 MB)
[DIN]   [ETS] 완료  첫값=2.26e+08 (메모리: 1593.1 MB)
[DIN]   [Prophet] 시작  (메모리: 1593.1 MB)

02:15:33 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1593.06 MB

02:15:33 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.07 MB (변화: +0.01 MB)
[DIN]   [Prophet] 완료  첫값=2.28e+08 (메모리: 1593.1 MB)
[DIN]   [LSTM] 시작  (메모리: 1593.1 MB)
[메모리] forecast_lstm 실행 전: 1593.07 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.09 MB (변화: +0.02 MB)
[DIN]   [LSTM] 완료  첫값=2.11e+08 (메모리: 1593.1 MB)
[DIN]   [Theta] 시작  (메모리: 1593.1 MB)
[메모리] forecast_theta 실행 전: 1593.09 MB
[메모리] forecast_theta 실행 후: 1593.09 MB (변화: +0.00 MB)
[DIN]   [Theta] 완료  첫값=2.18e+08 (메모리: 1593.1 MB)
[DIN]   [DB] 93행 저장 완료
[PROGRESS] [ 337/500] ( 67.4%)  >>  KMDA
[KMDA]   45분기 | 2015-03-31 ~ 2026-03-31
[KMDA]   [SARIMA] 시작  (메모리: 1593.1 MB)
[메모리] forecast_sarima 실행 전: 1593.09 MB
[메모리] find_best_sarima_params 실행 전: 1593.09 MB
[메모리] find_best_sarima_params 실행 후: 1593.09 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.09 MB (변화: +0.00 MB)
[KMDA]   [SARIMA] 완료  첫값=4.96e+07 (메모리: 1593.1 MB)
[KMDA]   [ETS] 시작  (메모리: 1593.1 MB)
[메모리] forecast_ets 실행 전: 1593.09 MB
[메모리] forecast_ets 실행 후: 1593.09 MB (변화: +0.00 MB)
[KMDA]   [ETS] 완료  첫값=4.93e+07 (메모리: 1593.1 MB)
[KMDA]   [Prophet] 시작  (메모리: 1593.1 MB)

02:15:57 - cmdstanpy - INFO - Chain [1] start processing
02:15:57 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1593.09 MB
[메모리] forecast_prophet 실행 후: 1593.10 MB (변화: +0.00 MB)
[KMDA]   [Prophet] 완료  첫값=4.49e+07 (메모리: 1593.1 MB)
[KMDA]   [LSTM] 시작  (메모리: 1593.1 MB)
[메모리] forecast_lstm 실행 전: 1593.10 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1594.14 MB (변화: +1.04 MB)
[KMDA]   [LSTM] 완료  첫값=4.30e+07 (메모리: 1594.1 MB)
[KMDA]   [Theta] 시작  (메모리: 1594.1 MB)
[메모리] forecast_theta 실행 전: 1594.14 MB
[메모리] forecast_theta 실행 후: 1594.14 MB (변화: +0.00 MB)
[KMDA]   [Theta] 완료  첫값=5.17e+07 (메모리: 1594.1 MB)
[KMDA]   [DB] 93행 저장 완료
[PROGRESS] [ 338/500] ( 67.6%)  >>  EGY
[EGY]   45분기 | 2015-03-31 ~ 2026-03-31
[EGY]   [SARIMA] 시작  (메모리: 1594.1 MB)
[메모리] forecast_sarima 실행 전: 1594.14 MB
[메모리] find_best_sarima_params 실행 전: 1594.14 MB
[메모리] find_best_sarima_params 실행 후: 1594.14 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1594.14 MB (변화: +0.00 MB)
[EGY]   [SARIMA] 완료  첫값=6.39e+07 (메모리: 1594.1 MB)
[EGY]   [ETS] 시작  (메모리: 1594.1 MB)
[메모리] forecast_ets 실행 전: 1594.14 MB
[메모리] forecast_ets 실행 후: 1594.14 MB (변화: +0.00 MB)
[EGY]   [ETS] 완료  첫값=7.85e+07 (메모리: 1594.1 MB)
[EGY]   [Prophet] 시작  (메모리: 1594.1 MB)

02:16:17 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1594.14 MB

02:16:17 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1594.15 MB (변화: +0.01 MB)
[EGY]   [Prophet] 완료  첫값=1.19e+08 (메모리: 1594.2 MB)
[EGY]   [LSTM] 시작  (메모리: 1594.2 MB)
[메모리] forecast_lstm 실행 전: 1594.15 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1594.13 MB (변화: -0.02 MB)
[EGY]   [LSTM] 완료  첫값=1.02e+08 (메모리: 1594.1 MB)
[EGY]   [Theta] 시작  (메모리: 1594.1 MB)
[메모리] forecast_theta 실행 전: 1594.13 MB
[메모리] forecast_theta 실행 후: 1594.13 MB (변화: +0.00 MB)
[EGY]   [Theta] 완료  첫값=7.65e+07 (메모리: 1594.1 MB)
[EGY]   [DB] 93행 저장 완료
[PROGRESS] [ 339/500] ( 67.8%)  >>  EBF
[EBF]   45분기 | 2015-03-31 ~ 2026-03-31
[EBF]   [SARIMA] 시작  (메모리: 1594.1 MB)
[메모리] forecast_sarima 실행 전: 1594.13 MB
[메모리] find_best_sarima_params 실행 전: 1594.13 MB
[메모리] find_best_sarima_params 실행 후: 1594.13 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1594.13 MB (변화: +0.00 MB)
[EBF]   [SARIMA] 완료  첫값=1.00e+08 (메모리: 1594.1 MB)
[EBF]   [ETS] 시작  (메모리: 1594.1 MB)
[메모리] forecast_ets 실행 전: 1594.13 MB
[메모리] forecast_ets 실행 후: 1594.13 MB (변화: +0.00 MB)
[EBF]   [ETS] 완료  첫값=1.01e+08 (메모리: 1594.1 MB)
[EBF]   [Prophet] 시작  (메모리: 1594.1 MB)

02:16:39 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1594.13 MB

02:16:39 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1594.14 MB (변화: +0.01 MB)
[EBF]   [Prophet] 완료  첫값=9.48e+07 (메모리: 1594.1 MB)
[EBF]   [LSTM] 시작  (메모리: 1594.1 MB)
[메모리] forecast_lstm 실행 전: 1594.14 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1594.13 MB (변화: -0.00 MB)
[EBF]   [LSTM] 완료  첫값=9.87e+07 (메모리: 1594.1 MB)
[EBF]   [Theta] 시작  (메모리: 1594.1 MB)
[메모리] forecast_theta 실행 전: 1594.13 MB
[메모리] forecast_theta 실행 후: 1594.13 MB (변화: +0.00 MB)
[EBF]   [Theta] 완료  첫값=1.00e+08 (메모리: 1594.1 MB)
[EBF]   [DB] 93행 저장 완료
[PROGRESS] [ 340/500] ( 68.0%)  >>  FPI
[FPI]   45분기 | 2015-03-31 ~ 2026-03-31
[FPI]   [SARIMA] 시작  (메모리: 1594.1 MB)
[메모리] forecast_sarima 실행 전: 1594.13 MB
[메모리] find_best_sarima_params 실행 전: 1594.13 MB
[메모리] find_best_sarima_params 실행 후: 1594.13 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1594.13 MB (변화: +0.00 MB)
[FPI]   [SARIMA] 완료  첫값=1.06e+07 (메모리: 1594.1 MB)
[FPI]   [ETS] 시작  (메모리: 1594.1 MB)
[메모리] forecast_ets 실행 전: 1594.13 MB
[메모리] forecast_ets 실행 후: 1594.14 MB (변화: +0.01 MB)
[FPI]   [ETS] 완료  첫값=8.70e+06 (메모리: 1594.1 MB)
[FPI]   [Prophet] 시작  (메모리: 1594.1 MB)

02:17:01 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1594.14 MB

02:17:01 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1594.15 MB (변화: +0.01 MB)
[FPI]   [Prophet] 완료  첫값=1.58e+07 (메모리: 1594.1 MB)
[FPI]   [LSTM] 시작  (메모리: 1594.1 MB)
[메모리] forecast_lstm 실행 전: 1594.15 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1594.12 MB (변화: -0.02 MB)
[FPI]   [LSTM] 완료  첫값=1.58e+07 (메모리: 1594.1 MB)
[FPI]   [Theta] 시작  (메모리: 1594.1 MB)
[메모리] forecast_theta 실행 전: 1594.12 MB
[메모리] forecast_theta 실행 후: 1594.12 MB (변화: +0.00 MB)
[FPI]   [Theta] 완료  첫값=1.04e+07 (메모리: 1594.1 MB)
[FPI]   [DB] 93행 저장 완료
[PROGRESS] [ 341/500] ( 68.2%)  >>  PWFL
[PWFL]   45분기 | 2015-03-31 ~ 2026-03-31
[PWFL]   [SARIMA] 시작  (메모리: 1594.1 MB)
[메모리] forecast_sarima 실행 전: 1594.12 MB
[메모리] find_best_sarima_params 실행 전: 1594.12 MB
[메모리] find_best_sarima_params 실행 후: 1594.12 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1594.12 MB (변화: +0.00 MB)
[PWFL]   [SARIMA] 완료  첫값=1.20e+08 (메모리: 1594.1 MB)
[PWFL]   [ETS] 시작  (메모리: 1594.1 MB)
[메모리] forecast_ets 실행 전: 1594.12 MB
[메모리] forecast_ets 실행 후: 1594.12 MB (변화: +0.00 MB)
[PWFL]   [ETS] 완료  첫값=1.25e+08 (메모리: 1594.1 MB)
[PWFL]   [Prophet] 시작  (메모리: 1594.1 MB)

02:17:18 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1594.12 MB

02:17:19 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1594.41 MB (변화: +0.28 MB)
[PWFL]   [Prophet] 완료  첫값=8.34e+07 (메모리: 1594.4 MB)
[PWFL]   [LSTM] 시작  (메모리: 1594.4 MB)
[메모리] forecast_lstm 실행 전: 1594.41 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1594.43 MB (변화: +0.02 MB)
[PWFL]   [LSTM] 완료  첫값=1.59e+08 (메모리: 1594.4 MB)
[PWFL]   [Theta] 시작  (메모리: 1594.4 MB)
[메모리] forecast_theta 실행 전: 1594.43 MB
[메모리] forecast_theta 실행 후: 1594.43 MB (변화: +0.00 MB)
[PWFL]   [Theta] 완료  첫값=1.25e+08 (메모리: 1594.4 MB)
[PWFL]   [DB] 93행 저장 완료
[PROGRESS] [ 342/500] ( 68.4%)  >>  MAGN
[MAGN]   45분기 | 2015-03-31 ~ 2026-03-31
[MAGN]   [SARIMA] 시작  (메모리: 1594.4 MB)
[메모리] forecast_sarima 실행 전: 1594.43 MB
[메모리] find_best_sarima_params 실행 전: 1594.43 MB
[메모리] find_best_sarima_params 실행 후: 1594.43 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1594.43 MB (변화: +0.00 MB)
[MAGN]   [SARIMA] 완료  첫값=7.02e+08 (메모리: 1594.4 MB)
[MAGN]   [ETS] 시작  (메모리: 1594.4 MB)
[메모리] forecast_ets 실행 전: 1594.43 MB
[메모리] forecast_ets 실행 후: 1594.43 MB (변화: +0.00 MB)
[MAGN]   [ETS] 완료  첫값=7.05e+08 (메모리: 1594.4 MB)
[MAGN]   [Prophet] 시작  (메모리: 1594.4 MB)

02:17:40 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1594.43 MB

02:17:40 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1594.43 MB (변화: +0.01 MB)
[MAGN]   [Prophet] 완료  첫값=5.13e+08 (메모리: 1594.4 MB)
[MAGN]   [LSTM] 시작  (메모리: 1594.4 MB)
[메모리] forecast_lstm 실행 전: 1594.43 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1594.41 MB (변화: -0.03 MB)
[MAGN]   [LSTM] 완료  첫값=6.19e+08 (메모리: 1594.4 MB)
[MAGN]   [Theta] 시작  (메모리: 1594.4 MB)
[메모리] forecast_theta 실행 전: 1594.41 MB
[메모리] forecast_theta 실행 후: 1594.41 MB (변화: +0.00 MB)
[MAGN]   [Theta] 완료  첫값=6.96e+08 (메모리: 1594.4 MB)
[MAGN]   [DB] 93행 저장 완료
[PROGRESS] [ 343/500] ( 68.6%)  >>  RMR
[RMR]   45분기 | 2015-03-31 ~ 2026-03-31
[RMR]   [SARIMA] 시작  (메모리: 1594.4 MB)
[메모리] forecast_sarima 실행 전: 1594.41 MB
[메모리] find_best_sarima_params 실행 전: 1594.41 MB
[메모리] find_best_sarima_params 실행 후: 1594.41 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1594.41 MB (변화: +0.00 MB)
[RMR]   [SARIMA] 완료  첫값=2.03e+08 (메모리: 1594.4 MB)
[RMR]   [ETS] 시작  (메모리: 1594.4 MB)
[메모리] forecast_ets 실행 전: 1594.41 MB
[메모리] forecast_ets 실행 후: 1594.41 MB (변화: +0.00 MB)
[RMR]   [ETS] 완료  첫값=1.96e+08 (메모리: 1594.4 MB)
[RMR]   [Prophet] 시작  (메모리: 1594.4 MB)

02:18:00 - cmdstanpy - INFO - Chain [1] start processing
02:18:00 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1594.41 MB
[메모리] forecast_prophet 실행 후: 1594.81 MB (변화: +0.41 MB)
[RMR]   [Prophet] 완료  첫값=1.82e+08 (메모리: 1594.8 MB)
[RMR]   [LSTM] 시작  (메모리: 1594.8 MB)
[메모리] forecast_lstm 실행 전: 1594.81 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1594.78 MB (변화: -0.04 MB)
[RMR]   [LSTM] 완료  첫값=1.95e+08 (메모리: 1594.8 MB)
[RMR]   [Theta] 시작  (메모리: 1594.8 MB)
[메모리] forecast_theta 실행 전: 1594.78 MB
[메모리] forecast_theta 실행 후: 1594.78 MB (변화: +0.00 MB)
[RMR]   [Theta] 완료  첫값=1.82e+08 (메모리: 1594.8 MB)
[RMR]   [DB] 93행 저장 완료
[PROGRESS] [ 344/500] ( 68.8%)  >>  HPP
[HPP]   45분기 | 2015-03-31 ~ 2026-03-31
[HPP]   [SARIMA] 시작  (메모리: 1594.8 MB)
[메모리] forecast_sarima 실행 전: 1594.78 MB
[메모리] find_best_sarima_params 실행 전: 1594.78 MB
[메모리] find_best_sarima_params 실행 후: 1594.78 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1594.78 MB (변화: +0.00 MB)
[HPP]   [SARIMA] 완료  첫값=1.87e+08 (메모리: 1594.8 MB)
[HPP]   [ETS] 시작  (메모리: 1594.8 MB)
[메모리] forecast_ets 실행 전: 1594.78 MB
[메모리] forecast_ets 실행 후: 1594.78 MB (변화: +0.00 MB)
[HPP]   [ETS] 완료  첫값=1.94e+08 (메모리: 1594.8 MB)
[HPP]   [Prophet] 시작  (메모리: 1594.8 MB)

02:18:22 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1594.78 MB

02:18:23 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1594.80 MB (변화: +0.02 MB)
[HPP]   [Prophet] 완료  첫값=1.98e+08 (메모리: 1594.8 MB)
[HPP]   [LSTM] 시작  (메모리: 1594.8 MB)
[메모리] forecast_lstm 실행 전: 1594.80 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1594.91 MB (변화: +0.11 MB)
[HPP]   [LSTM] 완료  첫값=2.01e+08 (메모리: 1594.9 MB)
[HPP]   [Theta] 시작  (메모리: 1594.9 MB)
[메모리] forecast_theta 실행 전: 1594.91 MB
[메모리] forecast_theta 실행 후: 1594.91 MB (변화: +0.00 MB)
[HPP]   [Theta] 완료  첫값=1.87e+08 (메모리: 1594.9 MB)
[HPP]   [DB] 93행 저장 완료
[PROGRESS] [ 345/500] ( 69.0%)  >>  GEVO
[GEVO]   45분기 | 2015-03-31 ~ 2026-03-31
[GEVO]   [SARIMA] 시작  (메모리: 1594.9 MB)
[메모리] forecast_sarima 실행 전: 1594.91 MB
[메모리] find_best_sarima_params 실행 전: 1594.91 MB
[메모리] find_best_sarima_params 실행 후: 1594.91 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1594.91 MB (변화: +0.00 MB)
[GEVO]   [SARIMA] 완료  첫값=4.03e+07 (메모리: 1594.9 MB)
[GEVO]   [ETS] 시작  (메모리: 1594.9 MB)
[메모리] forecast_ets 실행 전: 1594.91 MB
[메모리] forecast_ets 실행 후: 1594.91 MB (변화: +0.00 MB)
[GEVO]   [ETS] 완료  첫값=4.54e+07 (메모리: 1594.9 MB)
[GEVO]   [Prophet] 시작  (메모리: 1594.9 MB)

02:18:41 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1594.91 MB

02:18:41 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1594.91 MB (변화: +0.00 MB)
[GEVO]   [Prophet] 완료  첫값=1.68e+07 (메모리: 1594.9 MB)
[GEVO]   [LSTM] 시작  (메모리: 1594.9 MB)
[메모리] forecast_lstm 실행 전: 1594.91 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1594.98 MB (변화: +0.07 MB)
[GEVO]   [LSTM] 완료  첫값=6.04e+07 (메모리: 1595.0 MB)
[GEVO]   [Theta] 시작  (메모리: 1595.0 MB)
[메모리] forecast_theta 실행 전: 1594.98 MB
[메모리] forecast_theta 실행 후: 1594.98 MB (변화: +0.00 MB)
[GEVO]   [Theta] 완료  첫값=4.18e+07 (메모리: 1595.0 MB)
[GEVO]   [DB] 93행 저장 완료
[PROGRESS] [ 346/500] ( 69.2%)  >>  SIGA
[SIGA]   45분기 | 2015-03-31 ~ 2026-03-31
[SIGA]   [SARIMA] 시작  (메모리: 1595.0 MB)
[메모리] forecast_sarima 실행 전: 1594.98 MB
[메모리] find_best_sarima_params 실행 전: 1594.98 MB
[메모리] find_best_sarima_params 실행 후: 1594.98 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1594.98 MB (변화: +0.00 MB)
[SIGA]   [SARIMA] 완료  첫값=1.42e+07 (메모리: 1595.0 MB)
[SIGA]   [ETS] 시작  (메모리: 1595.0 MB)
[메모리] forecast_ets 실행 전: 1594.98 MB
[메모리] forecast_ets 실행 후: 1594.99 MB (변화: +0.01 MB)
[SIGA]   [ETS] 완료  첫값=2.56e+07 (메모리: 1595.0 MB)
[SIGA]   [Prophet] 시작  (메모리: 1595.0 MB)

02:19:04 - cmdstanpy - INFO - Chain [1] start processing
02:19:04 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1594.99 MB
[메모리] forecast_prophet 실행 후: 1595.01 MB (변화: +0.02 MB)
[SIGA]   [Prophet] 완료  첫값=3.73e+07 (메모리: 1595.0 MB)
[SIGA]   [LSTM] 시작  (메모리: 1595.0 MB)
[메모리] forecast_lstm 실행 전: 1595.01 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1594.99 MB (변화: -0.02 MB)
[SIGA]   [LSTM] 완료  첫값=3.04e+07 (메모리: 1595.0 MB)
[SIGA]   [Theta] 시작  (메모리: 1595.0 MB)
[메모리] forecast_theta 실행 전: 1594.99 MB
[메모리] forecast_theta 실행 후: 1594.99 MB (변화: +0.00 MB)
[SIGA]   [Theta] 완료  첫값=9.59e+06 (메모리: 1595.0 MB)
[SIGA]   [DB] 93행 저장 완료
[PROGRESS] [ 347/500] ( 69.4%)  >>  CHCT
[CHCT]   44분기 | 2015-06-30 ~ 2026-03-31
[CHCT]   [SARIMA] 시작  (메모리: 1595.0 MB)
[메모리] forecast_sarima 실행 전: 1594.99 MB
[메모리] find_best_sarima_params 실행 전: 1594.99 MB
[메모리] find_best_sarima_params 실행 후: 1594.99 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1594.99 MB (변화: +0.00 MB)
[CHCT]   [SARIMA] 완료  첫값=3.08e+07 (메모리: 1595.0 MB)
[CHCT]   [ETS] 시작  (메모리: 1595.0 MB)
[메모리] forecast_ets 실행 전: 1594.99 MB
[메모리] forecast_ets 실행 후: 1594.99 MB (변화: +0.00 MB)
[CHCT]   [ETS] 완료  첫값=3.14e+07 (메모리: 1595.0 MB)
[CHCT]   [Prophet] 시작  (메모리: 1595.0 MB)

02:19:26 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1594.99 MB

02:19:27 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1595.04 MB (변화: +0.04 MB)
[CHCT]   [Prophet] 완료  첫값=3.15e+07 (메모리: 1595.0 MB)
[CHCT]   [LSTM] 시작  (메모리: 1595.0 MB)
[메모리] forecast_lstm 실행 전: 1595.04 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1595.05 MB (변화: +0.02 MB)
[CHCT]   [LSTM] 완료  첫값=3.09e+07 (메모리: 1595.1 MB)
[CHCT]   [Theta] 시작  (메모리: 1595.1 MB)
[메모리] forecast_theta 실행 전: 1595.05 MB
[메모리] forecast_theta 실행 후: 1595.05 MB (변화: +0.00 MB)
[CHCT]   [Theta] 완료  첫값=3.14e+07 (메모리: 1595.1 MB)
[CHCT]   [DB] 92행 저장 완료
[PROGRESS] [ 348/500] ( 69.6%)  >>  HT
[HT]   45분기 | 2015-03-31 ~ 2026-03-31
[HT]   [SARIMA] 시작  (메모리: 1595.1 MB)
[메모리] forecast_sarima 실행 전: 1595.05 MB
[메모리] find_best_sarima_params 실행 전: 1595.05 MB
[메모리] find_best_sarima_params 실행 후: 1595.05 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1595.05 MB (변화: +0.00 MB)
[HT]   [SARIMA] 완료  첫값=9.20e+07 (메모리: 1595.1 MB)
[HT]   [ETS] 시작  (메모리: 1595.1 MB)
[메모리] forecast_ets 실행 전: 1595.05 MB
[메모리] forecast_ets 실행 후: 1595.05 MB (변화: +0.00 MB)
[HT]   [ETS] 완료  첫값=9.65e+07 (메모리: 1595.1 MB)
[HT]   [Prophet] 시작  (메모리: 1595.1 MB)

02:19:42 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1595.05 MB

02:19:42 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1595.05 MB (변화: +0.00 MB)
[HT]   [Prophet] 완료  첫값=7.93e+07 (메모리: 1595.1 MB)
[HT]   [LSTM] 시작  (메모리: 1595.1 MB)
[메모리] forecast_lstm 실행 전: 1595.05 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1595.04 MB (변화: -0.02 MB)
[HT]   [LSTM] 완료  첫값=8.88e+07 (메모리: 1595.0 MB)
[HT]   [Theta] 시작  (메모리: 1595.0 MB)
[메모리] forecast_theta 실행 전: 1595.04 MB
[메모리] forecast_theta 실행 후: 1595.04 MB (변화: +0.00 MB)
[HT]   [Theta] 완료  첫값=9.15e+07 (메모리: 1595.0 MB)
[HT]   [DB] 93행 저장 완료
[PROGRESS] [ 349/500] ( 69.8%)  >>  CLNE
[CLNE]   45분기 | 2015-03-31 ~ 2026-03-31
[CLNE]   [SARIMA] 시작  (메모리: 1595.0 MB)
[메모리] forecast_sarima 실행 전: 1595.04 MB
[메모리] find_best_sarima_params 실행 전: 1595.04 MB
[메모리] find_best_sarima_params 실행 후: 1595.04 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1595.04 MB (변화: +0.00 MB)
[CLNE]   [SARIMA] 완료  첫값=5.11e+07 (메모리: 1595.0 MB)
[CLNE]   [ETS] 시작  (메모리: 1595.0 MB)
[메모리] forecast_ets 실행 전: 1595.04 MB
[메모리] forecast_ets 실행 후: 1595.04 MB (변화: +0.00 MB)
[CLNE]   [ETS] 완료  첫값=5.47e+07 (메모리: 1595.0 MB)
[CLNE]   [Prophet] 시작  (메모리: 1595.0 MB)

02:20:00 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1595.04 MB

02:20:00 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1595.06 MB (변화: +0.02 MB)
[CLNE]   [Prophet] 완료  첫값=1.00e+08 (메모리: 1595.1 MB)
[CLNE]   [LSTM] 시작  (메모리: 1595.1 MB)
[메모리] forecast_lstm 실행 전: 1595.06 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1595.04 MB (변화: -0.02 MB)
[CLNE]   [LSTM] 완료  첫값=1.04e+08 (메모리: 1595.0 MB)
[CLNE]   [Theta] 시작  (메모리: 1595.0 MB)
[메모리] forecast_theta 실행 전: 1595.04 MB
[메모리] forecast_theta 실행 후: 1595.04 MB (변화: +0.00 MB)
[CLNE]   [Theta] 완료  첫값=8.99e+07 (메모리: 1595.0 MB)
[CLNE]   [DB] 93행 저장 완료
[PROGRESS] [ 350/500] ( 70.0%)  >>  MITK
[MITK]   45분기 | 2015-03-31 ~ 2026-03-31
[MITK]   [SARIMA] 시작  (메모리: 1595.0 MB)
[메모리] forecast_sarima 실행 전: 1595.04 MB
[메모리] find_best_sarima_params 실행 전: 1595.04 MB
[메모리] find_best_sarima_params 실행 후: 1595.04 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1595.04 MB (변화: +0.00 MB)
[MITK]   [SARIMA] 완료  첫값=4.36e+07 (메모리: 1595.0 MB)
[MITK]   [ETS] 시작  (메모리: 1595.0 MB)
[메모리] forecast_ets 실행 전: 1595.04 MB
[메모리] forecast_ets 실행 후: 1595.04 MB (변화: +0.00 MB)
[MITK]   [ETS] 완료  첫값=4.65e+07 (메모리: 1595.0 MB)
[MITK]   [Prophet] 시작  (메모리: 1595.0 MB)

02:20:22 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1595.04 MB

02:20:22 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1595.05 MB (변화: +0.01 MB)
[MITK]   [Prophet] 완료  첫값=5.15e+07 (메모리: 1595.1 MB)
[MITK]   [LSTM] 시작  (메모리: 1595.1 MB)
[메모리] forecast_lstm 실행 전: 1595.05 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1595.05 MB (변화: -0.01 MB)
[MITK]   [LSTM] 완료  첫값=5.00e+07 (메모리: 1595.0 MB)
[MITK]   [Theta] 시작  (메모리: 1595.0 MB)
[메모리] forecast_theta 실행 전: 1595.05 MB
[메모리] forecast_theta 실행 후: 1595.05 MB (변화: +0.00 MB)
[MITK]   [Theta] 완료  첫값=4.51e+07 (메모리: 1595.0 MB)
[MITK]   [DB] 93행 저장 완료
[PROGRESS] [ 351/500] ( 70.2%)  >>  ORN
[ORN]   45분기 | 2015-03-31 ~ 2026-03-31
[ORN]   [SARIMA] 시작  (메모리: 1595.0 MB)
[메모리] forecast_sarima 실행 전: 1595.05 MB
[메모리] find_best_sarima_params 실행 전: 1595.05 MB
[메모리] find_best_sarima_params 실행 후: 1595.05 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1595.05 MB (변화: +0.00 MB)
[ORN]   [SARIMA] 완료  첫값=2.17e+08 (메모리: 1595.0 MB)
[ORN]   [ETS] 시작  (메모리: 1595.0 MB)
[메모리] forecast_ets 실행 전: 1595.05 MB
[메모리] forecast_ets 실행 후: 1595.05 MB (변화: +0.00 MB)
[ORN]   [ETS] 완료  첫값=2.18e+08 (메모리: 1595.0 MB)
[ORN]   [Prophet] 시작  (메모리: 1595.0 MB)

02:20:42 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1595.05 MB

02:20:42 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1595.05 MB (변화: +0.00 MB)
[ORN]   [Prophet] 완료  첫값=2.14e+08 (메모리: 1595.1 MB)
[ORN]   [LSTM] 시작  (메모리: 1595.1 MB)
[메모리] forecast_lstm 실행 전: 1595.05 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1595.00 MB (변화: -0.05 MB)
[ORN]   [LSTM] 완료  첫값=1.99e+08 (메모리: 1595.0 MB)
[ORN]   [Theta] 시작  (메모리: 1595.0 MB)
[메모리] forecast_theta 실행 전: 1595.00 MB
[메모리] forecast_theta 실행 후: 1595.00 MB (변화: +0.00 MB)
[ORN]   [Theta] 완료  첫값=2.27e+08 (메모리: 1595.0 MB)
[ORN]   [DB] 93행 저장 완료
[PROGRESS] [ 352/500] ( 70.4%)  >>  ASC
[ASC]   45분기 | 2015-03-31 ~ 2026-03-31
[ASC]   [SARIMA] 시작  (메모리: 1595.0 MB)
[메모리] forecast_sarima 실행 전: 1595.00 MB
[메모리] find_best_sarima_params 실행 전: 1595.00 MB
[메모리] find_best_sarima_params 실행 후: 1595.00 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1595.00 MB (변화: +0.00 MB)
[ASC]   [SARIMA] 완료  첫값=8.29e+07 (메모리: 1595.0 MB)
[ASC]   [ETS] 시작  (메모리: 1595.0 MB)
[메모리] forecast_ets 실행 전: 1595.00 MB
[메모리] forecast_ets 실행 후: 1595.00 MB (변화: +0.01 MB)
[ASC]   [ETS] 완료  첫값=8.73e+07 (메모리: 1595.0 MB)
[ASC]   [Prophet] 시작  (메모리: 1595.0 MB)

02:21:01 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1595.00 MB

02:21:01 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1595.01 MB (변화: +0.01 MB)
[ASC]   [Prophet] 완료  첫값=1.02e+08 (메모리: 1595.0 MB)
[ASC]   [LSTM] 시작  (메모리: 1595.0 MB)
[메모리] forecast_lstm 실행 전: 1595.01 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1595.03 MB (변화: +0.02 MB)
[ASC]   [LSTM] 완료  첫값=8.54e+07 (메모리: 1595.0 MB)
[ASC]   [Theta] 시작  (메모리: 1595.0 MB)
[메모리] forecast_theta 실행 전: 1595.03 MB
[메모리] forecast_theta 실행 후: 1595.03 MB (변화: +0.00 MB)
[ASC]   [Theta] 완료  첫값=8.49e+07 (메모리: 1595.0 MB)
[ASC]   [DB] 93행 저장 완료
[PROGRESS] [ 353/500] ( 70.6%)  >>  PKE
[PKE]   45분기 | 2015-03-31 ~ 2026-03-31
[PKE]   [SARIMA] 시작  (메모리: 1595.0 MB)
[메모리] forecast_sarima 실행 전: 1595.03 MB
[메모리] find_best_sarima_params 실행 전: 1595.03 MB
[메모리] find_best_sarima_params 실행 후: 1595.03 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1595.03 MB (변화: +0.00 MB)
[PKE]   [SARIMA] 완료  첫값=1.65e+07 (메모리: 1595.0 MB)
[PKE]   [ETS] 시작  (메모리: 1595.0 MB)
[메모리] forecast_ets 실행 전: 1595.03 MB
[메모리] forecast_ets 실행 후: 1595.03 MB (변화: +0.00 MB)
[PKE]   [ETS] 완료  첫값=1.69e+07 (메모리: 1595.0 MB)
[PKE]   [Prophet] 시작  (메모리: 1595.0 MB)

02:21:19 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1595.03 MB

02:21:19 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1595.04 MB (변화: +0.01 MB)
[PKE]   [Prophet] 완료  첫값=8.44e+06 (메모리: 1595.0 MB)
[PKE]   [LSTM] 시작  (메모리: 1595.0 MB)
[메모리] forecast_lstm 실행 전: 1595.04 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1595.04 MB (변화: +0.00 MB)
[PKE]   [LSTM] 완료  첫값=1.36e+07 (메모리: 1595.0 MB)
[PKE]   [Theta] 시작  (메모리: 1595.0 MB)
[메모리] forecast_theta 실행 전: 1595.04 MB
[메모리] forecast_theta 실행 후: 1595.04 MB (변화: +0.00 MB)
[PKE]   [Theta] 완료  첫값=1.70e+07 (메모리: 1595.0 MB)
[PKE]   [DB] 93행 저장 완료
[PROGRESS] [ 354/500] ( 70.8%)  >>  JOUT
[JOUT]   45분기 | 2015-03-31 ~ 2026-03-31
[JOUT]   [SARIMA] 시작  (메모리: 1595.0 MB)
[메모리] forecast_sarima 실행 전: 1595.04 MB
[메모리] find_best_sarima_params 실행 전: 1595.04 MB
[메모리] find_best_sarima_params 실행 후: 1595.04 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1595.04 MB (변화: +0.00 MB)
[JOUT]   [SARIMA] 완료  첫값=1.66e+08 (메모리: 1595.0 MB)
[JOUT]   [ETS] 시작  (메모리: 1595.0 MB)
[메모리] forecast_ets 실행 전: 1595.04 MB
[메모리] forecast_ets 실행 후: 1595.04 MB (변화: +0.00 MB)
[JOUT]   [ETS] 완료  첫값=1.74e+08 (메모리: 1595.0 MB)
[JOUT]   [Prophet] 시작  (메모리: 1595.0 MB)

02:21:38 - cmdstanpy - INFO - Chain [1] start processing
02:21:38 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1595.04 MB
[메모리] forecast_prophet 실행 후: 1595.04 MB (변화: +0.01 MB)
[JOUT]   [Prophet] 완료  첫값=1.77e+08 (메모리: 1595.0 MB)
[JOUT]   [LSTM] 시작  (메모리: 1595.0 MB)
[메모리] forecast_lstm 실행 전: 1595.04 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1595.02 MB (변화: -0.02 MB)
[JOUT]   [LSTM] 완료  첫값=1.46e+08 (메모리: 1595.0 MB)
[JOUT]   [Theta] 시작  (메모리: 1595.0 MB)
[메모리] forecast_theta 실행 전: 1595.02 MB
[메모리] forecast_theta 실행 후: 1595.02 MB (변화: +0.00 MB)
[JOUT]   [Theta] 완료  첫값=1.76e+08 (메모리: 1595.0 MB)
[JOUT]   [DB] 93행 저장 완료
[PROGRESS] [ 355/500] ( 71.0%)  >>  MCS
[MCS]   45분기 | 2015-03-31 ~ 2026-03-31
[MCS]   [SARIMA] 시작  (메모리: 1595.0 MB)
[메모리] forecast_sarima 실행 전: 1595.02 MB
[메모리] find_best_sarima_params 실행 전: 1595.02 MB
[메모리] find_best_sarima_params 실행 후: 1595.02 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1595.02 MB (변화: +0.00 MB)
[MCS]   [SARIMA] 완료  첫값=1.62e+08 (메모리: 1595.0 MB)
[MCS]   [ETS] 시작  (메모리: 1595.0 MB)
[메모리] forecast_ets 실행 전: 1595.02 MB
[메모리] forecast_ets 실행 후: 1595.02 MB (변화: +0.00 MB)
[MCS]   [ETS] 완료  첫값=1.88e+08 (메모리: 1595.0 MB)
[MCS]   [Prophet] 시작  (메모리: 1595.0 MB)

02:21:55 - cmdstanpy - INFO - Chain [1] start processing
02:21:55 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1595.02 MB
[메모리] forecast_prophet 실행 후: 1595.03 MB (변화: +0.00 MB)
[MCS]   [Prophet] 완료  첫값=1.82e+08 (메모리: 1595.0 MB)
[MCS]   [LSTM] 시작  (메모리: 1595.0 MB)
[메모리] forecast_lstm 실행 전: 1595.03 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1595.01 MB (변화: -0.02 MB)
[MCS]   [LSTM] 완료  첫값=1.74e+08 (메모리: 1595.0 MB)
[MCS]   [Theta] 시작  (메모리: 1595.0 MB)
[메모리] forecast_theta 실행 전: 1595.01 MB
[메모리] forecast_theta 실행 후: 1595.01 MB (변화: +0.00 MB)
[MCS]   [Theta] 완료  첫값=2.11e+08 (메모리: 1595.0 MB)
[MCS]   [DB] 93행 저장 완료
[PROGRESS] [ 356/500] ( 71.2%)  >>  CODI
[CODI]   45분기 | 2015-03-31 ~ 2026-03-31
[CODI]   [SARIMA] 시작  (메모리: 1595.0 MB)
[메모리] forecast_sarima 실행 전: 1595.01 MB
[메모리] find_best_sarima_params 실행 전: 1595.01 MB
[메모리] find_best_sarima_params 실행 후: 1595.01 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1595.01 MB (변화: +0.00 MB)
[CODI]   [SARIMA] 완료  첫값=4.85e+08 (메모리: 1595.0 MB)
[CODI]   [ETS] 시작  (메모리: 1595.0 MB)
[메모리] forecast_ets 실행 전: 1595.01 MB
[메모리] forecast_ets 실행 후: 1595.01 MB (변화: +0.00 MB)
[CODI]   [ETS] 완료  첫값=4.80e+08 (메모리: 1595.0 MB)
[CODI]   [Prophet] 시작  (메모리: 1595.0 MB)

02:22:14 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1595.01 MB

02:22:14 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1595.02 MB (변화: +0.01 MB)
[CODI]   [Prophet] 완료  첫값=5.62e+08 (메모리: 1595.0 MB)
[CODI]   [LSTM] 시작  (메모리: 1595.0 MB)
[메모리] forecast_lstm 실행 전: 1595.02 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1595.13 MB (변화: +0.12 MB)
[CODI]   [LSTM] 완료  첫값=4.78e+08 (메모리: 1595.1 MB)
[CODI]   [Theta] 시작  (메모리: 1595.1 MB)
[메모리] forecast_theta 실행 전: 1595.13 MB
[메모리] forecast_theta 실행 후: 1595.13 MB (변화: +0.00 MB)
[CODI]   [Theta] 완료  첫값=4.72e+08 (메모리: 1595.1 MB)
[CODI]   [DB] 93행 저장 완료
[PROGRESS] [ 357/500] ( 71.4%)  >>  CERS
[CERS]   45분기 | 2015-03-31 ~ 2026-03-31
[CERS]   [SARIMA] 시작  (메모리: 1595.1 MB)
[메모리] forecast_sarima 실행 전: 1595.13 MB
[메모리] find_best_sarima_params 실행 전: 1595.13 MB
[메모리] find_best_sarima_params 실행 후: 1595.13 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1595.13 MB (변화: +0.00 MB)
[CERS]   [SARIMA] 완료  첫값=5.94e+07 (메모리: 1595.1 MB)
[CERS]   [ETS] 시작  (메모리: 1595.1 MB)
[메모리] forecast_ets 실행 전: 1595.13 MB
[메모리] forecast_ets 실행 후: 1595.14 MB (변화: +0.00 MB)
[CERS]   [ETS] 완료  첫값=6.16e+07 (메모리: 1595.1 MB)
[CERS]   [Prophet] 시작  (메모리: 1595.1 MB)
[메모리] forecast_prophet 실행 전: 1595.14 MB

02:22:36 - cmdstanpy - INFO - Chain [1] start processing
02:22:37 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1595.14 MB (변화: +0.00 MB)
[CERS]   [Prophet] 완료  첫값=5.37e+07 (메모리: 1595.1 MB)
[CERS]   [LSTM] 시작  (메모리: 1595.1 MB)
[메모리] forecast_lstm 실행 전: 1595.14 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1595.16 MB (변화: +0.02 MB)
[CERS]   [LSTM] 완료  첫값=5.81e+07 (메모리: 1595.2 MB)
[CERS]   [Theta] 시작  (메모리: 1595.2 MB)
[메모리] forecast_theta 실행 전: 1595.16 MB
[메모리] forecast_theta 실행 후: 1595.16 MB (변화: +0.00 MB)
[CERS]   [Theta] 완료  첫값=6.22e+07 (메모리: 1595.2 MB)
[CERS]   [DB] 93행 저장 완료
[PROGRESS] [ 358/500] ( 71.6%)  >>  NRC
[NRC]   45분기 | 2015-03-31 ~ 2026-03-31
[NRC]   [SARIMA] 시작  (메모리: 1595.2 MB)
[메모리] forecast_sarima 실행 전: 1595.16 MB
[메모리] find_best_sarima_params 실행 전: 1595.16 MB
[메모리] find_best_sarima_params 실행 후: 1595.16 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1595.16 MB (변화: +0.00 MB)
[NRC]   [SARIMA] 완료  첫값=3.52e+07 (메모리: 1595.2 MB)
[NRC]   [ETS] 시작  (메모리: 1595.2 MB)
[메모리] forecast_ets 실행 전: 1595.16 MB
[메모리] forecast_ets 실행 후: 1595.16 MB (변화: +0.00 MB)
[NRC]   [ETS] 완료  첫값=3.51e+07 (메모리: 1595.2 MB)
[NRC]   [Prophet] 시작  (메모리: 1595.2 MB)

02:23:02 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1595.16 MB

02:23:02 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1595.16 MB (변화: +0.00 MB)
[NRC]   [Prophet] 완료  첫값=3.48e+07 (메모리: 1595.2 MB)
[NRC]   [LSTM] 시작  (메모리: 1595.2 MB)
[메모리] forecast_lstm 실행 전: 1595.16 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1595.15 MB (변화: -0.01 MB)
[NRC]   [LSTM] 완료  첫값=3.50e+07 (메모리: 1595.2 MB)
[NRC]   [Theta] 시작  (메모리: 1595.2 MB)
[메모리] forecast_theta 실행 전: 1595.15 MB
[메모리] forecast_theta 실행 후: 1595.15 MB (변화: +0.00 MB)
[NRC]   [Theta] 완료  첫값=3.40e+07 (메모리: 1595.2 MB)
[NRC]   [DB] 93행 저장 완료
[PROGRESS] [ 359/500] ( 71.8%)  >>  BBBY
[BBBY]   45분기 | 2015-03-31 ~ 2026-03-31
[BBBY]   [SARIMA] 시작  (메모리: 1595.2 MB)
[메모리] forecast_sarima 실행 전: 1595.15 MB
[메모리] find_best_sarima_params 실행 전: 1595.15 MB
[메모리] find_best_sarima_params 실행 후: 1595.15 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1595.15 MB (변화: +0.00 MB)
[BBBY]   [SARIMA] 완료  첫값=2.61e+08 (메모리: 1595.2 MB)
[BBBY]   [ETS] 시작  (메모리: 1595.2 MB)
[메모리] forecast_ets 실행 전: 1595.15 MB
[메모리] forecast_ets 실행 후: 1595.16 MB (변화: +0.00 MB)
[BBBY]   [ETS] 완료  첫값=2.37e+08 (메모리: 1595.2 MB)
[BBBY]   [Prophet] 시작  (메모리: 1595.2 MB)

02:23:19 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1595.16 MB

02:23:20 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1595.16 MB (변화: +0.00 MB)
[BBBY]   [Prophet] 완료  첫값=-4.44e+08 (메모리: 1595.2 MB)
[BBBY]   [LSTM] 시작  (메모리: 1595.2 MB)
[메모리] forecast_lstm 실행 전: 1595.16 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1595.14 MB (변화: -0.01 MB)
[BBBY]   [LSTM] 완료  첫값=4.51e+08 (메모리: 1595.1 MB)
[BBBY]   [Theta] 시작  (메모리: 1595.1 MB)
[메모리] forecast_theta 실행 전: 1595.14 MB
[메모리] forecast_theta 실행 후: 1595.14 MB (변화: +0.00 MB)
[BBBY]   [Theta] 완료  첫값=2.49e+08 (메모리: 1595.1 MB)
[BBBY]   [DB] 93행 저장 완료
[PROGRESS] [ 360/500] ( 72.0%)  >>  IMMP
[IMMP]   44분기 | 2015-06-30 ~ 2026-03-31
[IMMP]   [SARIMA] 시작  (메모리: 1595.1 MB)
[메모리] forecast_sarima 실행 전: 1595.14 MB
[메모리] find_best_sarima_params 실행 전: 1595.14 MB
[메모리] find_best_sarima_params 실행 후: 1595.14 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1595.14 MB (변화: +0.00 MB)
[IMMP]   [SARIMA] 완료  첫값=1.67e+06 (메모리: 1595.1 MB)
[IMMP]   [ETS] 시작  (메모리: 1595.1 MB)
[메모리] forecast_ets 실행 전: 1595.14 MB
[메모리] forecast_ets 실행 후: 1595.15 MB (변화: +0.01 MB)
[IMMP]   [ETS] 완료  첫값=3.00e+05 (메모리: 1595.2 MB)
[IMMP]   [Prophet] 시작  (메모리: 1595.2 MB)

02:23:37 - cmdstanpy - INFO - Chain [1] start processing
02:23:37 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1595.15 MB
[메모리] forecast_prophet 실행 후: 1595.19 MB (변화: +0.04 MB)
[IMMP]   [Prophet] 완료  첫값=2.31e+06 (메모리: 1595.2 MB)
[IMMP]   [LSTM] 시작  (메모리: 1595.2 MB)
[메모리] forecast_lstm 실행 전: 1595.19 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1595.20 MB (변화: +0.02 MB)
[IMMP]   [LSTM] 완료  첫값=2.09e+06 (메모리: 1595.2 MB)
[IMMP]   [Theta] 시작  (메모리: 1595.2 MB)
[메모리] forecast_theta 실행 전: 1595.20 MB
[메모리] forecast_theta 실행 후: 1595.20 MB (변화: +0.00 MB)
[IMMP]   [Theta] 완료  첫값=2.10e+06 (메모리: 1595.2 MB)
[IMMP]   [DB] 92행 저장 완료
[PROGRESS] [ 361/500] ( 72.2%)  >>  MTW
[MTW]   45분기 | 2015-03-31 ~ 2026-03-31
[MTW]   [SARIMA] 시작  (메모리: 1595.2 MB)
[메모리] forecast_sarima 실행 전: 1595.20 MB
[메모리] find_best_sarima_params 실행 전: 1595.20 MB
[메모리] find_best_sarima_params 실행 후: 1595.20 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1595.20 MB (변화: +0.00 MB)
[MTW]   [SARIMA] 완료  첫값=7.95e+08 (메모리: 1595.2 MB)
[MTW]   [ETS] 시작  (메모리: 1595.2 MB)
[메모리] forecast_ets 실행 전: 1595.20 MB
[메모리] forecast_ets 실행 후: 1595.20 MB (변화: +0.00 MB)
[MTW]   [ETS] 완료  첫값=8.24e+08 (메모리: 1595.2 MB)
[MTW]   [Prophet] 시작  (메모리: 1595.2 MB)

02:23:57 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1595.20 MB

02:23:57 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1595.20 MB (변화: +0.00 MB)
[MTW]   [Prophet] 완료  첫값=5.06e+08 (메모리: 1595.2 MB)
[MTW]   [LSTM] 시작  (메모리: 1595.2 MB)
[메모리] forecast_lstm 실행 전: 1595.20 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1595.18 MB (변화: -0.02 MB)
[MTW]   [LSTM] 완료  첫값=5.38e+08 (메모리: 1595.2 MB)
[MTW]   [Theta] 시작  (메모리: 1595.2 MB)
[메모리] forecast_theta 실행 전: 1595.18 MB
[메모리] forecast_theta 실행 후: 1595.18 MB (변화: +0.00 MB)
[MTW]   [Theta] 완료  첫값=6.62e+08 (메모리: 1595.2 MB)
[MTW]   [DB] 93행 저장 완료
[PROGRESS] [ 362/500] ( 72.4%)  >>  KOPN
[KOPN]   45분기 | 2015-03-31 ~ 2026-03-31
[KOPN]   [SARIMA] 시작  (메모리: 1595.2 MB)
[메모리] forecast_sarima 실행 전: 1595.18 MB
[메모리] find_best_sarima_params 실행 전: 1595.18 MB
[메모리] find_best_sarima_params 실행 후: 1595.18 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1595.18 MB (변화: +0.00 MB)
[KOPN]   [SARIMA] 완료  첫값=1.08e+07 (메모리: 1595.2 MB)
[KOPN]   [ETS] 시작  (메모리: 1595.2 MB)
[메모리] forecast_ets 실행 전: 1595.18 MB
[메모리] forecast_ets 실행 후: 1595.19 MB (변화: +0.00 MB)
[KOPN]   [ETS] 완료  첫값=1.12e+07 (메모리: 1595.2 MB)
[KOPN]   [Prophet] 시작  (메모리: 1595.2 MB)

02:24:17 - cmdstanpy - INFO - Chain [1] start processing
02:24:17 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1595.19 MB
[메모리] forecast_prophet 실행 후: 1595.19 MB (변화: +0.00 MB)
[KOPN]   [Prophet] 완료  첫값=1.28e+07 (메모리: 1595.2 MB)
[KOPN]   [LSTM] 시작  (메모리: 1595.2 MB)
[메모리] forecast_lstm 실행 전: 1595.19 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1595.17 MB (변화: -0.02 MB)
[KOPN]   [LSTM] 완료  첫값=1.09e+07 (메모리: 1595.2 MB)
[KOPN]   [Theta] 시작  (메모리: 1595.2 MB)
[메모리] forecast_theta 실행 전: 1595.17 MB
[메모리] forecast_theta 실행 후: 1595.17 MB (변화: +0.00 MB)
[KOPN]   [Theta] 완료  첫값=1.09e+07 (메모리: 1595.2 MB)
[KOPN]   [DB] 93행 저장 완료
[PROGRESS] [ 363/500] ( 72.6%)  >>  SVA
[SVA]   45분기 | 2015-03-31 ~ 2026-03-31
[SVA]   [SARIMA] 시작  (메모리: 1595.2 MB)
[메모리] forecast_sarima 실행 전: 1595.17 MB
[메모리] find_best_sarima_params 실행 전: 1595.17 MB
[메모리] find_best_sarima_params 실행 후: 1595.17 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1595.17 MB (변화: +0.00 MB)
[SVA]   [SARIMA] 완료  첫값=3.05e+08 (메모리: 1595.2 MB)
[SVA]   [ETS] 시작  (메모리: 1595.2 MB)
[메모리] forecast_ets 실행 전: 1595.17 MB
[메모리] forecast_ets 실행 후: 1595.18 MB (변화: +0.00 MB)
[SVA]   [ETS] 완료  첫값=3.71e+08 (메모리: 1595.2 MB)
[SVA]   [Prophet] 시작  (메모리: 1595.2 MB)

02:24:34 - cmdstanpy - INFO - Chain [1] start processing
02:24:34 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1595.18 MB
[메모리] forecast_prophet 실행 후: 1595.19 MB (변화: +0.01 MB)
[SVA]   [Prophet] 완료  첫값=1.77e+09 (메모리: 1595.2 MB)
[SVA]   [LSTM] 시작  (메모리: 1595.2 MB)
[메모리] forecast_lstm 실행 전: 1595.19 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1595.15 MB (변화: -0.04 MB)
[SVA]   [LSTM] 완료  첫값=1.55e+09 (메모리: 1595.2 MB)
[SVA]   [Theta] 시작  (메모리: 1595.2 MB)
[메모리] forecast_theta 실행 전: 1595.15 MB
[메모리] forecast_theta 실행 후: 1595.15 MB (변화: +0.00 MB)
[SVA]   [Theta] 완료  첫값=3.33e+08 (메모리: 1595.2 MB)
[SVA]   [DB] 93행 저장 완료
[PROGRESS] [ 364/500] ( 72.8%)  >>  MLR
[MLR]   45분기 | 2015-03-31 ~ 2026-03-31
[MLR]   [SARIMA] 시작  (메모리: 1595.2 MB)
[메모리] forecast_sarima 실행 전: 1595.15 MB
[메모리] find_best_sarima_params 실행 전: 1595.15 MB
[메모리] find_best_sarima_params 실행 후: 1595.15 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1595.15 MB (변화: +0.00 MB)
[MLR]   [SARIMA] 완료  첫값=1.82e+08 (메모리: 1595.2 MB)
[MLR]   [ETS] 시작  (메모리: 1595.2 MB)
[메모리] forecast_ets 실행 전: 1595.15 MB
[메모리] forecast_ets 실행 후: 1595.16 MB (변화: +0.00 MB)
[MLR]   [ETS] 완료  첫값=1.82e+08 (메모리: 1595.2 MB)
[MLR]   [Prophet] 시작  (메모리: 1595.2 MB)

02:24:54 - cmdstanpy - INFO - Chain [1] start processing
02:24:54 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1595.16 MB
[메모리] forecast_prophet 실행 후: 1595.16 MB (변화: +0.00 MB)
[MLR]   [Prophet] 완료  첫값=2.65e+08 (메모리: 1595.2 MB)
[MLR]   [LSTM] 시작  (메모리: 1595.2 MB)
[메모리] forecast_lstm 실행 전: 1595.16 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1594.08 MB (변화: -1.08 MB)
[MLR]   [LSTM] 완료  첫값=2.32e+08 (메모리: 1594.1 MB)
[MLR]   [Theta] 시작  (메모리: 1594.1 MB)
[메모리] forecast_theta 실행 전: 1594.08 MB
[메모리] forecast_theta 실행 후: 1594.08 MB (변화: +0.00 MB)
[MLR]   [Theta] 완료  첫값=1.79e+08 (메모리: 1594.1 MB)
[MLR]   [DB] 93행 저장 완료
[PROGRESS] [ 365/500] ( 73.0%)  >>  OSPN
[OSPN]   45분기 | 2015-03-31 ~ 2026-03-31
[OSPN]   [SARIMA] 시작  (메모리: 1594.1 MB)
[메모리] forecast_sarima 실행 전: 1594.08 MB
[메모리] find_best_sarima_params 실행 전: 1594.08 MB
[메모리] find_best_sarima_params 실행 후: 1594.08 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1594.08 MB (변화: +0.00 MB)
[OSPN]   [SARIMA] 완료  첫값=5.90e+07 (메모리: 1594.1 MB)
[OSPN]   [ETS] 시작  (메모리: 1594.1 MB)
[메모리] forecast_ets 실행 전: 1594.08 MB
[메모리] forecast_ets 실행 후: 1594.08 MB (변화: +0.00 MB)
[OSPN]   [ETS] 완료  첫값=5.75e+07 (메모리: 1594.1 MB)
[OSPN]   [Prophet] 시작  (메모리: 1594.1 MB)

02:25:15 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1594.08 MB

02:25:15 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1594.49 MB (변화: +0.41 MB)
[OSPN]   [Prophet] 완료  첫값=5.96e+07 (메모리: 1594.5 MB)
[OSPN]   [LSTM] 시작  (메모리: 1594.5 MB)
[메모리] forecast_lstm 실행 전: 1594.49 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1594.56 MB (변화: +0.07 MB)
[OSPN]   [LSTM] 완료  첫값=5.83e+07 (메모리: 1594.6 MB)
[OSPN]   [Theta] 시작  (메모리: 1594.6 MB)
[메모리] forecast_theta 실행 전: 1594.56 MB
[메모리] forecast_theta 실행 후: 1594.56 MB (변화: +0.00 MB)
[OSPN]   [Theta] 완료  첫값=5.75e+07 (메모리: 1594.6 MB)
[OSPN]   [DB] 93행 저장 완료
[PROGRESS] [ 366/500] ( 73.2%)  >>  VNDA
[VNDA]   45분기 | 2015-03-31 ~ 2026-03-31
[VNDA]   [SARIMA] 시작  (메모리: 1594.6 MB)
[메모리] forecast_sarima 실행 전: 1594.56 MB
[메모리] find_best_sarima_params 실행 전: 1594.56 MB
[메모리] find_best_sarima_params 실행 후: 1594.56 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1594.56 MB (변화: +0.00 MB)
[VNDA]   [SARIMA] 완료  첫값=5.72e+07 (메모리: 1594.6 MB)
[VNDA]   [ETS] 시작  (메모리: 1594.6 MB)
[메모리] forecast_ets 실행 전: 1594.56 MB
[메모리] forecast_ets 실행 후: 1594.57 MB (변화: +0.00 MB)
[VNDA]   [ETS] 완료  첫값=6.05e+07 (메모리: 1594.6 MB)
[VNDA]   [Prophet] 시작  (메모리: 1594.6 MB)

02:25:39 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1594.57 MB

02:25:39 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1594.57 MB (변화: +0.01 MB)
[VNDA]   [Prophet] 완료  첫값=6.33e+07 (메모리: 1594.6 MB)
[VNDA]   [LSTM] 시작  (메모리: 1594.6 MB)
[메모리] forecast_lstm 실행 전: 1594.57 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1594.58 MB (변화: +0.00 MB)
[VNDA]   [LSTM] 완료  첫값=5.32e+07 (메모리: 1594.6 MB)
[VNDA]   [Theta] 시작  (메모리: 1594.6 MB)
[메모리] forecast_theta 실행 전: 1594.58 MB
[메모리] forecast_theta 실행 후: 1594.58 MB (변화: +0.00 MB)
[VNDA]   [Theta] 완료  첫값=5.97e+07 (메모리: 1594.6 MB)
[VNDA]   [DB] 93행 저장 완료
[PROGRESS] [ 367/500] ( 73.4%)  >>  CD
[CD]   44분기 | 2015-06-30 ~ 2026-03-31
[CD]   [SARIMA] 시작  (메모리: 1594.6 MB)
[메모리] forecast_sarima 실행 전: 1594.58 MB
[메모리] find_best_sarima_params 실행 전: 1594.58 MB
[메모리] find_best_sarima_params 실행 후: 1594.58 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1594.58 MB (변화: +0.00 MB)
[CD]   [SARIMA] 완료  첫값=3.73e+06 (메모리: 1594.6 MB)
[CD]   [ETS] 시작  (메모리: 1594.6 MB)
[메모리] forecast_ets 실행 전: 1594.58 MB
[메모리] forecast_ets 실행 후: 1594.58 MB (변화: +0.00 MB)
[CD]   [ETS] 완료  첫값=2.02e+06 (메모리: 1594.6 MB)
[CD]   [Prophet] 시작  (메모리: 1594.6 MB)

02:26:02 - cmdstanpy - INFO - Chain [1] start processing
02:26:02 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1594.58 MB
[메모리] forecast_prophet 실행 후: 1594.60 MB (변화: +0.02 MB)
[CD]   [Prophet] 완료  첫값=-4.88e+06 (메모리: 1594.6 MB)
[CD]   [LSTM] 시작  (메모리: 1594.6 MB)
[메모리] forecast_lstm 실행 전: 1594.60 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1594.61 MB (변화: +0.01 MB)
[CD]   [LSTM] 완료  첫값=6.37e+05 (메모리: 1594.6 MB)
[CD]   [Theta] 시작  (메모리: 1594.6 MB)
[메모리] forecast_theta 실행 전: 1594.61 MB
[메모리] forecast_theta 실행 후: 1594.61 MB (변화: +0.00 MB)
[CD]   [Theta] 완료  첫값=4.86e+06 (메모리: 1594.6 MB)
[CD]   [DB] 92행 저장 완료
[PROGRESS] [ 368/500] ( 73.6%)  >>  TCI
[TCI]   45분기 | 2015-03-31 ~ 2026-03-31
[TCI]   [SARIMA] 시작  (메모리: 1594.6 MB)
[메모리] forecast_sarima 실행 전: 1594.61 MB
[메모리] find_best_sarima_params 실행 전: 1594.61 MB
[메모리] find_best_sarima_params 실행 후: 1594.61 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1594.61 MB (변화: +0.00 MB)
[TCI]   [SARIMA] 완료  첫값=1.19e+07 (메모리: 1594.6 MB)
[TCI]   [ETS] 시작  (메모리: 1594.6 MB)
[메모리] forecast_ets 실행 전: 1594.61 MB
[메모리] forecast_ets 실행 후: 1594.61 MB (변화: +0.00 MB)
[TCI]   [ETS] 완료  첫값=1.19e+07 (메모리: 1594.6 MB)
[TCI]   [Prophet] 시작  (메모리: 1594.6 MB)

02:26:18 - cmdstanpy - INFO - Chain [1] start processing
02:26:18 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1594.61 MB
[메모리] forecast_prophet 실행 후: 1594.61 MB (변화: +0.00 MB)
[TCI]   [Prophet] 완료  첫값=5.36e+06 (메모리: 1594.6 MB)
[TCI]   [LSTM] 시작  (메모리: 1594.6 MB)
[메모리] forecast_lstm 실행 전: 1594.61 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1594.61 MB (변화: +0.00 MB)
[TCI]   [LSTM] 완료  첫값=1.14e+07 (메모리: 1594.6 MB)
[TCI]   [Theta] 시작  (메모리: 1594.6 MB)
[메모리] forecast_theta 실행 전: 1594.61 MB
[메모리] forecast_theta 실행 후: 1594.61 MB (변화: +0.00 MB)
[TCI]   [Theta] 완료  첫값=1.19e+07 (메모리: 1594.6 MB)
[TCI]   [DB] 93행 저장 완료
[PROGRESS] [ 369/500] ( 73.8%)  >>  EMX
[EMX]   45분기 | 2015-03-31 ~ 2026-03-31
[EMX]   [SARIMA] 시작  (메모리: 1594.6 MB)
[메모리] forecast_sarima 실행 전: 1594.61 MB
[메모리] find_best_sarima_params 실행 전: 1594.61 MB
[메모리] find_best_sarima_params 실행 후: 1594.61 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1594.61 MB (변화: +0.00 MB)
[EMX]   [SARIMA] 완료  첫값=6.47e+06 (메모리: 1594.6 MB)
[EMX]   [ETS] 시작  (메모리: 1594.6 MB)
[메모리] forecast_ets 실행 전: 1594.61 MB
[메모리] forecast_ets 실행 후: 1594.61 MB (변화: +0.00 MB)
[EMX]   [ETS] 완료  첫값=5.47e+06 (메모리: 1594.6 MB)
[EMX]   [Prophet] 시작  (메모리: 1594.6 MB)

02:26:34 - cmdstanpy - INFO - Chain [1] start processing
02:26:35 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1594.61 MB
[메모리] forecast_prophet 실행 후: 1594.62 MB (변화: +0.02 MB)
[EMX]   [Prophet] 완료  첫값=6.19e+06 (메모리: 1594.6 MB)
[EMX]   [LSTM] 시작  (메모리: 1594.6 MB)
[메모리] forecast_lstm 실행 전: 1594.62 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1594.61 MB (변화: -0.02 MB)
[EMX]   [LSTM] 완료  첫값=7.34e+06 (메모리: 1594.6 MB)
[EMX]   [Theta] 시작  (메모리: 1594.6 MB)
[메모리] forecast_theta 실행 전: 1594.61 MB
[메모리] forecast_theta 실행 후: 1594.61 MB (변화: +0.00 MB)
[EMX]   [Theta] 완료  첫값=4.95e+06 (메모리: 1594.6 MB)
[EMX]   [DB] 93행 저장 완료
[PROGRESS] [ 370/500] ( 74.0%)  >>  OLP
[OLP]   45분기 | 2015-03-31 ~ 2026-03-31
[OLP]   [SARIMA] 시작  (메모리: 1594.6 MB)
[메모리] forecast_sarima 실행 전: 1594.61 MB
[메모리] find_best_sarima_params 실행 전: 1594.61 MB
[메모리] find_best_sarima_params 실행 후: 1594.61 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1594.61 MB (변화: +0.00 MB)
[OLP]   [SARIMA] 완료  첫값=2.52e+07 (메모리: 1594.6 MB)
[OLP]   [ETS] 시작  (메모리: 1594.6 MB)
[메모리] forecast_ets 실행 전: 1594.61 MB
[메모리] forecast_ets 실행 후: 1594.61 MB (변화: +0.00 MB)
[OLP]   [ETS] 완료  첫값=2.48e+07 (메모리: 1594.6 MB)
[OLP]   [Prophet] 시작  (메모리: 1594.6 MB)

02:26:54 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1594.61 MB

02:26:54 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1594.61 MB (변화: +0.01 MB)
[OLP]   [Prophet] 완료  첫값=2.49e+07 (메모리: 1594.6 MB)
[OLP]   [LSTM] 시작  (메모리: 1594.6 MB)
[메모리] forecast_lstm 실행 전: 1594.61 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1594.60 MB (변화: -0.01 MB)
[OLP]   [LSTM] 완료  첫값=2.31e+07 (메모리: 1594.6 MB)
[OLP]   [Theta] 시작  (메모리: 1594.6 MB)
[메모리] forecast_theta 실행 전: 1594.60 MB
[메모리] forecast_theta 실행 후: 1594.60 MB (변화: +0.00 MB)
[OLP]   [Theta] 완료  첫값=2.45e+07 (메모리: 1594.6 MB)
[OLP]   [DB] 93행 저장 완료
[PROGRESS] [ 371/500] ( 74.2%)  >>  OBE
[OBE]   45분기 | 2015-03-31 ~ 2026-03-31
[OBE]   [SARIMA] 시작  (메모리: 1594.6 MB)
[메모리] forecast_sarima 실행 전: 1594.60 MB
[메모리] find_best_sarima_params 실행 전: 1594.60 MB
[메모리] find_best_sarima_params 실행 후: 1594.60 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1594.60 MB (변화: +0.00 MB)
[OBE]   [SARIMA] 완료  첫값=1.61e+08 (메모리: 1594.6 MB)
[OBE]   [ETS] 시작  (메모리: 1594.6 MB)
[메모리] forecast_ets 실행 전: 1594.60 MB
[메모리] forecast_ets 실행 후: 1594.60 MB (변화: +0.00 MB)
[OBE]   [ETS] 완료  첫값=1.26e+08 (메모리: 1594.6 MB)
[OBE]   [Prophet] 시작  (메모리: 1594.6 MB)

02:27:13 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1594.60 MB

02:27:13 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1594.60 MB (변화: +0.00 MB)
[OBE]   [Prophet] 완료  첫값=1.48e+08 (메모리: 1594.6 MB)
[OBE]   [LSTM] 시작  (메모리: 1594.6 MB)
[메모리] forecast_lstm 실행 전: 1594.60 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1594.59 MB (변화: -0.02 MB)
[OBE]   [LSTM] 완료  첫값=1.72e+08 (메모리: 1594.6 MB)
[OBE]   [Theta] 시작  (메모리: 1594.6 MB)
[메모리] forecast_theta 실행 전: 1594.59 MB
[메모리] forecast_theta 실행 후: 1594.59 MB (변화: +0.00 MB)
[OBE]   [Theta] 완료  첫값=1.31e+08 (메모리: 1594.6 MB)
[OBE]   [DB] 93행 저장 완료
[PROGRESS] [ 372/500] ( 74.4%)  >>  SLS
[SLS]   45분기 | 2015-03-31 ~ 2026-03-31
[SLS]   [SARIMA] 시작  (메모리: 1594.6 MB)
[메모리] forecast_sarima 실행 전: 1594.59 MB
[메모리] find_best_sarima_params 실행 전: 1594.59 MB
[메모리] find_best_sarima_params 실행 후: 1594.59 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1594.59 MB (변화: +0.00 MB)
[SLS]   [SARIMA] 완료  첫값=-2.73e+05 (메모리: 1594.6 MB)
[SLS]   [ETS] 시작  (메모리: 1594.6 MB)
[메모리] forecast_ets 실행 전: 1594.59 MB
[메모리] forecast_ets 실행 후: 1594.59 MB (변화: +0.00 MB)
[SLS]   [ETS] 완료  첫값=2.79e+05 (메모리: 1594.6 MB)
[SLS]   [Prophet] 시작  (메모리: 1594.6 MB)

02:27:27 - cmdstanpy - INFO - Chain [1] start processing
02:27:27 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1594.59 MB
[메모리] forecast_prophet 실행 후: 1594.59 MB (변화: +0.00 MB)
[SLS]   [Prophet] 완료  첫값=2.84e+05 (메모리: 1594.6 MB)
[SLS]   [LSTM] 시작  (메모리: 1594.6 MB)
[메모리] forecast_lstm 실행 전: 1594.59 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1594.54 MB (변화: -0.05 MB)
[SLS]   [LSTM] 완료  첫값=-3.04e+05 (메모리: 1594.5 MB)
[SLS]   [Theta] 시작  (메모리: 1594.5 MB)
[메모리] forecast_theta 실행 전: 1594.54 MB
[메모리] forecast_theta 실행 후: 1594.54 MB (변화: +0.00 MB)
[SLS]   [Theta] 완료  첫값=1.62e+03 (메모리: 1594.5 MB)
[SLS]   [DB] 93행 저장 완료
[PROGRESS] [ 373/500] ( 74.6%)  >>  GSS
[GSS]   45분기 | 2015-03-31 ~ 2026-03-31
[GSS]   [SARIMA] 시작  (메모리: 1594.5 MB)
[메모리] forecast_sarima 실행 전: 1594.54 MB
[메모리] find_best_sarima_params 실행 전: 1594.54 MB
[메모리] find_best_sarima_params 실행 후: 1594.54 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1594.54 MB (변화: +0.00 MB)
[GSS]   [SARIMA] 완료  첫값=6.47e+07 (메모리: 1594.5 MB)
[GSS]   [ETS] 시작  (메모리: 1594.5 MB)
[메모리] forecast_ets 실행 전: 1594.54 MB
[메모리] forecast_ets 실행 후: 1594.54 MB (변화: +0.00 MB)
[GSS]   [ETS] 완료  첫값=6.47e+07 (메모리: 1594.5 MB)
[GSS]   [Prophet] 시작  (메모리: 1594.5 MB)

02:27:47 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1594.54 MB

02:27:47 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1595.35 MB (변화: +0.81 MB)
[GSS]   [Prophet] 완료  첫값=6.52e+07 (메모리: 1595.3 MB)
[GSS]   [LSTM] 시작  (메모리: 1595.3 MB)
[메모리] forecast_lstm 실행 전: 1595.35 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1595.32 MB (변화: -0.03 MB)
[GSS]   [LSTM] 완료  첫값=6.33e+07 (메모리: 1595.3 MB)
[GSS]   [Theta] 시작  (메모리: 1595.3 MB)
[메모리] forecast_theta 실행 전: 1595.32 MB
[메모리] forecast_theta 실행 후: 1595.32 MB (변화: +0.00 MB)
[GSS]   [Theta] 완료  첫값=6.43e+07 (메모리: 1595.3 MB)
[GSS]   [DB] 93행 저장 완료
[PROGRESS] [ 374/500] ( 74.8%)  >>  MLAB
[MLAB]   45분기 | 2015-03-31 ~ 2026-03-31
[MLAB]   [SARIMA] 시작  (메모리: 1595.3 MB)
[메모리] forecast_sarima 실행 전: 1595.32 MB
[메모리] find_best_sarima_params 실행 전: 1595.32 MB
[메모리] find_best_sarima_params 실행 후: 1595.32 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1595.32 MB (변화: +0.00 MB)
[MLAB]   [SARIMA] 완료  첫값=6.81e+07 (메모리: 1595.3 MB)
[MLAB]   [ETS] 시작  (메모리: 1595.3 MB)
[메모리] forecast_ets 실행 전: 1595.32 MB
[메모리] forecast_ets 실행 후: 1595.32 MB (변화: +0.00 MB)
[MLAB]   [ETS] 완료  첫값=6.18e+07 (메모리: 1595.3 MB)
[MLAB]   [Prophet] 시작  (메모리: 1595.3 MB)

02:28:06 - cmdstanpy - INFO - Chain [1] start processing
02:28:06 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1595.32 MB
[메모리] forecast_prophet 실행 후: 1595.34 MB (변화: +0.02 MB)
[MLAB]   [Prophet] 완료  첫값=6.61e+07 (메모리: 1595.3 MB)
[MLAB]   [LSTM] 시작  (메모리: 1595.3 MB)
[메모리] forecast_lstm 실행 전: 1595.34 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1595.36 MB (변화: +0.02 MB)
[MLAB]   [LSTM] 완료  첫값=6.57e+07 (메모리: 1595.4 MB)
[MLAB]   [Theta] 시작  (메모리: 1595.4 MB)
[메모리] forecast_theta 실행 전: 1595.36 MB
[메모리] forecast_theta 실행 후: 1595.36 MB (변화: +0.00 MB)
[MLAB]   [Theta] 완료  첫값=5.96e+07 (메모리: 1595.4 MB)
[MLAB]   [DB] 93행 저장 완료
[PROGRESS] [ 375/500] ( 75.0%)  >>  WOLF
[WOLF]   45분기 | 2015-03-31 ~ 2026-03-31
[WOLF]   [SARIMA] 시작  (메모리: 1595.4 MB)
[메모리] forecast_sarima 실행 전: 1595.37 MB
[메모리] find_best_sarima_params 실행 전: 1595.37 MB
[메모리] find_best_sarima_params 실행 후: 1595.37 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1595.37 MB (변화: +0.00 MB)
[WOLF]   [SARIMA] 완료  첫값=1.65e+08 (메모리: 1595.4 MB)
[WOLF]   [ETS] 시작  (메모리: 1595.4 MB)
[메모리] forecast_ets 실행 전: 1595.37 MB
[메모리] forecast_ets 실행 후: 1595.37 MB (변화: +0.00 MB)
[WOLF]   [ETS] 완료  첫값=1.75e+08 (메모리: 1595.4 MB)
[WOLF]   [Prophet] 시작  (메모리: 1595.4 MB)

02:28:29 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1595.37 MB

02:28:29 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1595.39 MB (변화: +0.02 MB)
[WOLF]   [Prophet] 완료  첫값=1.14e+08 (메모리: 1595.4 MB)
[WOLF]   [LSTM] 시작  (메모리: 1595.4 MB)
[메모리] forecast_lstm 실행 전: 1595.39 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1595.41 MB (변화: +0.01 MB)
[WOLF]   [LSTM] 완료  첫값=1.83e+08 (메모리: 1595.4 MB)
[WOLF]   [Theta] 시작  (메모리: 1595.4 MB)
[메모리] forecast_theta 실행 전: 1595.41 MB
[메모리] forecast_theta 실행 후: 1595.41 MB (변화: +0.00 MB)
[WOLF]   [Theta] 완료  첫값=1.78e+08 (메모리: 1595.4 MB)
[WOLF]   [DB] 93행 저장 완료
[PROGRESS] [ 376/500] ( 75.2%)  >>  MG
[MG]   45분기 | 2015-03-31 ~ 2026-03-31
[MG]   [SARIMA] 시작  (메모리: 1595.4 MB)
[메모리] forecast_sarima 실행 전: 1595.41 MB
[메모리] find_best_sarima_params 실행 전: 1595.41 MB
[메모리] find_best_sarima_params 실행 후: 1595.41 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1595.41 MB (변화: +0.00 MB)
[MG]   [SARIMA] 완료  첫값=1.88e+08 (메모리: 1595.4 MB)
[MG]   [ETS] 시작  (메모리: 1595.4 MB)
[메모리] forecast_ets 실행 전: 1595.41 MB
[메모리] forecast_ets 실행 후: 1595.41 MB (변화: +0.01 MB)
[MG]   [ETS] 완료  첫값=2.05e+08 (메모리: 1595.4 MB)
[MG]   [Prophet] 시작  (메모리: 1595.4 MB)

02:28:49 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1595.41 MB

02:28:49 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1595.41 MB (변화: +0.00 MB)
[MG]   [Prophet] 완료  첫값=1.80e+08 (메모리: 1595.4 MB)
[MG]   [LSTM] 시작  (메모리: 1595.4 MB)
[메모리] forecast_lstm 실행 전: 1595.41 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1595.42 MB (변화: +0.01 MB)
[MG]   [LSTM] 완료  첫값=1.78e+08 (메모리: 1595.4 MB)
[MG]   [Theta] 시작  (메모리: 1595.4 MB)
[메모리] forecast_theta 실행 전: 1595.42 MB
[메모리] forecast_theta 실행 후: 1595.42 MB (변화: +0.00 MB)
[MG]   [Theta] 완료  첫값=1.95e+08 (메모리: 1595.4 MB)
[MG]   [DB] 93행 저장 완료
[PROGRESS] [ 377/500] ( 75.4%)  >>  GLDG
[GLDG]   45분기 | 2015-03-31 ~ 2026-03-31
[GLDG]   [SARIMA] 시작  (메모리: 1595.4 MB)
[메모리] forecast_sarima 실행 전: 1595.42 MB
[메모리] find_best_sarima_params 실행 전: 1595.42 MB
[메모리] find_best_sarima_params 실행 후: 1595.42 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1595.42 MB (변화: +0.00 MB)
[GLDG]   [SARIMA] 완료  첫값=0.00e+00 (메모리: 1595.4 MB)
[GLDG]   [ETS] 시작  (메모리: 1595.4 MB)
[메모리] forecast_ets 실행 전: 1595.42 MB
[메모리] forecast_ets 실행 후: 1595.43 MB (변화: +0.00 MB)
[GLDG]   [ETS] 완료  첫값=0.00e+00 (메모리: 1595.4 MB)
[GLDG]   [Prophet] 시작  (메모리: 1595.4 MB)
[메모리] forecast_prophet 실행 전: 1595.43 MB
[메모리] forecast_prophet 실행 후: 1595.43 MB (변화: +0.01 MB)
[GLDG]   [Prophet] 완료  첫값=0.00e+00 (메모리: 1595.4 MB)
[GLDG]   [LSTM] 시작  (메모리: 1595.4 MB)
[메모리] forecast_lstm 실행 전: 1595.43 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1595.42 MB (변화: -0.01 MB)
[GLDG]   [LSTM] 완료  첫값=0.00e+00 (메모리: 1595.4 MB)
[GLDG]   [Theta] 시작  (메모리: 1595.4 MB)
[메모리] forecast_theta 실행 전: 1595.42 MB
[메모리] forecast_theta 실행 후: 1595.42 MB (변화: +0.00 MB)
[GLDG]   [Theta] 완료  첫값=0.00e+00 (메모리: 1595.4 MB)
[GLDG]   [DB] 93행 저장 완료
[PROGRESS] [ 378/500] ( 75.6%)  >>  AVXL
[AVXL]   45분기 | 2015-03-31 ~ 2026-03-31
[AVXL]   [SARIMA] 시작  (메모리: 1595.4 MB)
[메모리] forecast_sarima 실행 전: 1595.42 MB
[메모리] find_best_sarima_params 실행 전: 1595.42 MB
[메모리] find_best_sarima_params 실행 후: 1595.42 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1595.42 MB (변화: +0.00 MB)
[AVXL]   [SARIMA] 완료  첫값=0.00e+00 (메모리: 1595.4 MB)
[AVXL]   [ETS] 시작  (메모리: 1595.4 MB)
[메모리] forecast_ets 실행 전: 1595.42 MB
[메모리] forecast_ets 실행 후: 1595.43 MB (변화: +0.00 MB)
[AVXL]   [ETS] 완료  첫값=0.00e+00 (메모리: 1595.4 MB)
[AVXL]   [Prophet] 시작  (메모리: 1595.4 MB)
[메모리] forecast_prophet 실행 전: 1595.43 MB
[메모리] forecast_prophet 실행 후: 1595.43 MB (변화: +0.01 MB)
[AVXL]   [Prophet] 완료  첫값=0.00e+00 (메모리: 1595.4 MB)
[AVXL]   [LSTM] 시작  (메모리: 1595.4 MB)
[메모리] forecast_lstm 실행 전: 1595.43 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1595.43 MB (변화: -0.00 MB)
[AVXL]   [LSTM] 완료  첫값=0.00e+00 (메모리: 1595.4 MB)
[AVXL]   [Theta] 시작  (메모리: 1595.4 MB)
[메모리] forecast_theta 실행 전: 1595.43 MB
[메모리] forecast_theta 실행 후: 1595.43 MB (변화: +0.00 MB)
[AVXL]   [Theta] 완료  첫값=0.00e+00 (메모리: 1595.4 MB)
[AVXL]   [DB] 93행 저장 완료
[PROGRESS] [ 379/500] ( 75.8%)  >>  CVGW
[CVGW]   45분기 | 2015-03-31 ~ 2026-03-31
[CVGW]   [SARIMA] 시작  (메모리: 1595.4 MB)
[메모리] forecast_sarima 실행 전: 1595.43 MB
[메모리] find_best_sarima_params 실행 전: 1595.43 MB
[메모리] find_best_sarima_params 실행 후: 1595.43 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1595.43 MB (변화: +0.00 MB)
[CVGW]   [SARIMA] 완료  첫값=1.56e+08 (메모리: 1595.4 MB)
[CVGW]   [ETS] 시작  (메모리: 1595.4 MB)
[메모리] forecast_ets 실행 전: 1595.43 MB
[메모리] forecast_ets 실행 후: 1595.43 MB (변화: +0.00 MB)
[CVGW]   [ETS] 완료  첫값=1.43e+08 (메모리: 1595.4 MB)
[CVGW]   [Prophet] 시작  (메모리: 1595.4 MB)

02:29:49 - cmdstanpy - INFO - Chain [1] start processing
02:29:49 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1595.43 MB
[메모리] forecast_prophet 실행 후: 1595.44 MB (변화: +0.01 MB)
[CVGW]   [Prophet] 완료  첫값=1.90e+08 (메모리: 1595.4 MB)
[CVGW]   [LSTM] 시작  (메모리: 1595.4 MB)
[메모리] forecast_lstm 실행 전: 1595.44 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1595.48 MB (변화: +0.04 MB)
[CVGW]   [LSTM] 완료  첫값=1.79e+08 (메모리: 1595.5 MB)
[CVGW]   [Theta] 시작  (메모리: 1595.5 MB)
[메모리] forecast_theta 실행 전: 1595.48 MB
[메모리] forecast_theta 실행 후: 1595.48 MB (변화: +0.00 MB)
[CVGW]   [Theta] 완료  첫값=1.43e+08 (메모리: 1595.5 MB)
[CVGW]   [DB] 93행 저장 완료
[PROGRESS] [ 380/500] ( 76.0%)  >>  GRVY
[GRVY]   45분기 | 2015-03-31 ~ 2026-03-31
[GRVY]   [SARIMA] 시작  (메모리: 1595.5 MB)
[메모리] forecast_sarima 실행 전: 1595.48 MB
[메모리] find_best_sarima_params 실행 전: 1595.48 MB
[메모리] find_best_sarima_params 실행 후: 1595.48 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1595.48 MB (변화: +0.00 MB)
[GRVY]   [SARIMA] 완료  첫값=1.26e+11 (메모리: 1595.5 MB)
[GRVY]   [ETS] 시작  (메모리: 1595.5 MB)
[메모리] forecast_ets 실행 전: 1595.48 MB
[메모리] forecast_ets 실행 후: 1595.48 MB (변화: +0.00 MB)
[GRVY]   [ETS] 완료  첫값=1.04e+11 (메모리: 1595.5 MB)
[GRVY]   [Prophet] 시작  (메모리: 1595.5 MB)

02:30:06 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1595.48 MB

02:30:06 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1595.49 MB (변화: +0.00 MB)
[GRVY]   [Prophet] 완료  첫값=1.37e+11 (메모리: 1595.5 MB)
[GRVY]   [LSTM] 시작  (메모리: 1595.5 MB)
[메모리] forecast_lstm 실행 전: 1595.49 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1595.48 MB (변화: -0.01 MB)
[GRVY]   [LSTM] 완료  첫값=1.11e+11 (메모리: 1595.5 MB)
[GRVY]   [Theta] 시작  (메모리: 1595.5 MB)
[메모리] forecast_theta 실행 전: 1595.48 MB
[메모리] forecast_theta 실행 후: 1595.48 MB (변화: +0.00 MB)
[GRVY]   [Theta] 완료  첫값=1.00e+11 (메모리: 1595.5 MB)
[GRVY]   [DB] 93행 저장 완료
[PROGRESS] [ 381/500] ( 76.2%)  >>  FRPH
[FRPH]   45분기 | 2015-03-31 ~ 2026-03-31
[FRPH]   [SARIMA] 시작  (메모리: 1595.5 MB)
[메모리] forecast_sarima 실행 전: 1595.48 MB
[메모리] find_best_sarima_params 실행 전: 1595.48 MB
[메모리] find_best_sarima_params 실행 후: 1595.48 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1595.48 MB (변화: +0.00 MB)
[FRPH]   [SARIMA] 완료  첫값=1.08e+07 (메모리: 1595.5 MB)
[FRPH]   [ETS] 시작  (메모리: 1595.5 MB)
[메모리] forecast_ets 실행 전: 1595.48 MB
[메모리] forecast_ets 실행 후: 1595.48 MB (변화: +0.01 MB)
[FRPH]   [ETS] 완료  첫값=1.06e+07 (메모리: 1595.5 MB)
[FRPH]   [Prophet] 시작  (메모리: 1595.5 MB)

02:30:24 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1595.48 MB

02:30:25 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1595.49 MB (변화: +0.01 MB)
[FRPH]   [Prophet] 완료  첫값=9.86e+06 (메모리: 1595.5 MB)
[FRPH]   [LSTM] 시작  (메모리: 1595.5 MB)
[메모리] forecast_lstm 실행 전: 1595.49 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1595.46 MB (변화: -0.04 MB)
[FRPH]   [LSTM] 완료  첫값=1.02e+07 (메모리: 1595.5 MB)
[FRPH]   [Theta] 시작  (메모리: 1595.5 MB)
[메모리] forecast_theta 실행 전: 1595.46 MB
[메모리] forecast_theta 실행 후: 1595.46 MB (변화: +0.00 MB)
[FRPH]   [Theta] 완료  첫값=1.06e+07 (메모리: 1595.5 MB)
[FRPH]   [DB] 93행 저장 완료
[PROGRESS] [ 382/500] ( 76.4%)  >>  IPI
[IPI]   45분기 | 2015-03-31 ~ 2026-03-31
[IPI]   [SARIMA] 시작  (메모리: 1595.5 MB)
[메모리] forecast_sarima 실행 전: 1595.46 MB
[메모리] find_best_sarima_params 실행 전: 1595.46 MB
[메모리] find_best_sarima_params 실행 후: 1595.46 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1595.46 MB (변화: +0.00 MB)
[IPI]   [SARIMA] 완료  첫값=4.93e+07 (메모리: 1595.5 MB)
[IPI]   [ETS] 시작  (메모리: 1595.5 MB)
[메모리] forecast_ets 실행 전: 1595.46 MB
[메모리] forecast_ets 실행 후: 1595.46 MB (변화: +0.00 MB)
[IPI]   [ETS] 완료  첫값=4.72e+07 (메모리: 1595.5 MB)
[IPI]   [Prophet] 시작  (메모리: 1595.5 MB)

02:30:43 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1595.46 MB

02:30:43 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1595.47 MB (변화: +0.02 MB)
[IPI]   [Prophet] 완료  첫값=6.87e+07 (메모리: 1595.5 MB)
[IPI]   [LSTM] 시작  (메모리: 1595.5 MB)
[메모리] forecast_lstm 실행 전: 1595.47 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1595.44 MB (변화: -0.03 MB)
[IPI]   [LSTM] 완료  첫값=6.32e+07 (메모리: 1595.4 MB)
[IPI]   [Theta] 시작  (메모리: 1595.4 MB)
[메모리] forecast_theta 실행 전: 1595.44 MB
[메모리] forecast_theta 실행 후: 1595.44 MB (변화: +0.00 MB)
[IPI]   [Theta] 완료  첫값=4.86e+07 (메모리: 1595.4 MB)
[IPI]   [DB] 93행 저장 완료
[PROGRESS] [ 383/500] ( 76.6%)  >>  CABO
[CABO]   45분기 | 2015-03-31 ~ 2026-03-31
[CABO]   [SARIMA] 시작  (메모리: 1595.4 MB)
[메모리] forecast_sarima 실행 전: 1595.44 MB
[메모리] find_best_sarima_params 실행 전: 1595.44 MB
[메모리] find_best_sarima_params 실행 후: 1595.44 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1595.44 MB (변화: +0.00 MB)
[CABO]   [SARIMA] 완료  첫값=3.81e+08 (메모리: 1595.4 MB)
[CABO]   [ETS] 시작  (메모리: 1595.4 MB)
[메모리] forecast_ets 실행 전: 1595.44 MB
[메모리] forecast_ets 실행 후: 1595.44 MB (변화: +0.00 MB)
[CABO]   [ETS] 완료  첫값=3.82e+08 (메모리: 1595.4 MB)
[CABO]   [Prophet] 시작  (메모리: 1595.4 MB)
[메모리] forecast_prophet 실행 전: 1595.44 MB

02:31:03 - cmdstanpy - INFO - Chain [1] start processing
02:31:04 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1595.46 MB (변화: +0.02 MB)
[CABO]   [Prophet] 완료  첫값=3.90e+08 (메모리: 1595.5 MB)
[CABO]   [LSTM] 시작  (메모리: 1595.5 MB)
[메모리] forecast_lstm 실행 전: 1595.46 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1595.41 MB (변화: -0.05 MB)
[CABO]   [LSTM] 완료  첫값=4.06e+08 (메모리: 1595.4 MB)
[CABO]   [Theta] 시작  (메모리: 1595.4 MB)
[메모리] forecast_theta 실행 전: 1595.41 MB
[메모리] forecast_theta 실행 후: 1595.41 MB (변화: +0.00 MB)
[CABO]   [Theta] 완료  첫값=3.88e+08 (메모리: 1595.4 MB)
[CABO]   [DB] 93행 저장 완료
[PROGRESS] [ 384/500] ( 76.8%)  >>  DMAC
[DMAC]   45분기 | 2015-03-31 ~ 2026-03-31
[DMAC]   [SARIMA] 시작  (메모리: 1595.4 MB)
[메모리] forecast_sarima 실행 전: 1595.41 MB
[메모리] find_best_sarima_params 실행 전: 1595.41 MB
[메모리] find_best_sarima_params 실행 후: 1595.41 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1595.41 MB (변화: +0.00 MB)
[DMAC]   [SARIMA] 완료  첫값=5.61e+03 (메모리: 1595.4 MB)
[DMAC]   [ETS] 시작  (메모리: 1595.4 MB)
[메모리] forecast_ets 실행 전: 1595.41 MB
[메모리] forecast_ets 실행 후: 1595.41 MB (변화: +0.00 MB)
[DMAC]   [ETS] 완료  첫값=-8.97e+03 (메모리: 1595.4 MB)
[DMAC]   [Prophet] 시작  (메모리: 1595.4 MB)

02:31:21 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1595.41 MB

02:31:21 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1595.82 MB (변화: +0.41 MB)
[DMAC]   [Prophet] 완료  첫값=-1.56e+03 (메모리: 1595.8 MB)
[DMAC]   [LSTM] 시작  (메모리: 1595.8 MB)
[메모리] forecast_lstm 실행 전: 1595.82 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1595.79 MB (변화: -0.03 MB)
[DMAC]   [LSTM] 완료  첫값=2.38e+04 (메모리: 1595.8 MB)
[DMAC]   [Theta] 시작  (메모리: 1595.8 MB)
[메모리] forecast_theta 실행 전: 1595.79 MB
[메모리] forecast_theta 실행 후: 1595.79 MB (변화: +0.00 MB)
[DMAC]   [Theta] 완료  첫값=-1.15e+04 (메모리: 1595.8 MB)
[DMAC]   [DB] 93행 저장 완료
[PROGRESS] [ 385/500] ( 77.0%)  >>  LAAC
[LAAC]   45분기 | 2015-03-31 ~ 2026-03-31
[LAAC]   [SARIMA] 시작  (메모리: 1595.8 MB)
[메모리] forecast_sarima 실행 전: 1595.79 MB
[메모리] find_best_sarima_params 실행 전: 1595.79 MB
[메모리] find_best_sarima_params 실행 후: 1595.79 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1595.79 MB (변화: +0.00 MB)
[LAAC]   [SARIMA] 완료  첫값=2.46e+04 (메모리: 1595.8 MB)
[LAAC]   [ETS] 시작  (메모리: 1595.8 MB)
[메모리] forecast_ets 실행 전: 1595.79 MB
[메모리] forecast_ets 실행 후: 1595.79 MB (변화: +0.00 MB)
[LAAC]   [ETS] 완료  첫값=2.27e+05 (메모리: 1595.8 MB)
[LAAC]   [Prophet] 시작  (메모리: 1595.8 MB)

02:31:42 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1595.79 MB

02:31:42 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1595.80 MB (변화: +0.01 MB)
[LAAC]   [Prophet] 완료  첫값=-1.37e+05 (메모리: 1595.8 MB)
[LAAC]   [LSTM] 시작  (메모리: 1595.8 MB)
[메모리] forecast_lstm 실행 전: 1595.80 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1595.82 MB (변화: +0.02 MB)
[LAAC]   [LSTM] 완료  첫값=-3.10e+05 (메모리: 1595.8 MB)
[LAAC]   [Theta] 시작  (메모리: 1595.8 MB)
[메모리] forecast_theta 실행 전: 1595.82 MB
[메모리] forecast_theta 실행 후: 1595.82 MB (변화: +0.00 MB)
[LAAC]   [Theta] 완료  첫값=-4.25e+04 (메모리: 1595.8 MB)
[LAAC]   [DB] 93행 저장 완료
[PROGRESS] [ 386/500] ( 77.2%)  >>  CYH
[CYH]   45분기 | 2015-03-31 ~ 2026-03-31
[CYH]   [SARIMA] 시작  (메모리: 1595.8 MB)
[메모리] forecast_sarima 실행 전: 1595.82 MB
[메모리] find_best_sarima_params 실행 전: 1595.82 MB
[메모리] find_best_sarima_params 실행 후: 1595.82 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1595.82 MB (변화: +0.00 MB)
[CYH]   [SARIMA] 완료  첫값=3.05e+09 (메모리: 1595.8 MB)
[CYH]   [ETS] 시작  (메모리: 1595.8 MB)
[메모리] forecast_ets 실행 전: 1595.82 MB
[메모리] forecast_ets 실행 후: 1595.82 MB (변화: +0.00 MB)
[CYH]   [ETS] 완료  첫값=2.95e+09 (메모리: 1595.8 MB)
[CYH]   [Prophet] 시작  (메모리: 1595.8 MB)

02:32:00 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1595.82 MB

02:32:00 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1595.83 MB (변화: +0.01 MB)
[CYH]   [Prophet] 완료  첫값=3.11e+09 (메모리: 1595.8 MB)
[CYH]   [LSTM] 시작  (메모리: 1595.8 MB)
[메모리] forecast_lstm 실행 전: 1595.83 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1595.84 MB (변화: +0.00 MB)
[CYH]   [LSTM] 완료  첫값=3.04e+09 (메모리: 1595.8 MB)
[CYH]   [Theta] 시작  (메모리: 1595.8 MB)
[메모리] forecast_theta 실행 전: 1595.84 MB
[메모리] forecast_theta 실행 후: 1595.84 MB (변화: +0.00 MB)
[CYH]   [Theta] 완료  첫값=2.97e+09 (메모리: 1595.8 MB)
[CYH]   [DB] 93행 저장 완료
[PROGRESS] [ 387/500] ( 77.4%)  >>  ATEX
[ATEX]   45분기 | 2015-03-31 ~ 2026-03-31
[ATEX]   [SARIMA] 시작  (메모리: 1595.8 MB)
[메모리] forecast_sarima 실행 전: 1595.84 MB
[메모리] find_best_sarima_params 실행 전: 1595.84 MB
[메모리] find_best_sarima_params 실행 후: 1595.84 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1595.84 MB (변화: +0.00 MB)
[ATEX]   [SARIMA] 완료  첫값=-1.02e+06 (메모리: 1595.8 MB)
[ATEX]   [ETS] 시작  (메모리: 1595.8 MB)
[메모리] forecast_ets 실행 전: 1595.84 MB
[메모리] forecast_ets 실행 후: 1595.84 MB (변화: +0.00 MB)
[ATEX]   [ETS] 완료  첫값=-6.14e+05 (메모리: 1595.8 MB)
[ATEX]   [Prophet] 시작  (메모리: 1595.8 MB)

02:32:17 - cmdstanpy - INFO - Chain [1] start processing
02:32:17 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1595.84 MB
[메모리] forecast_prophet 실행 후: 1595.85 MB (변화: +0.01 MB)
[ATEX]   [Prophet] 완료  첫값=7.36e+05 (메모리: 1595.8 MB)
[ATEX]   [LSTM] 시작  (메모리: 1595.8 MB)
[메모리] forecast_lstm 실행 전: 1595.85 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1595.88 MB (변화: +0.03 MB)
[ATEX]   [LSTM] 완료  첫값=5.34e+05 (메모리: 1595.9 MB)
[ATEX]   [Theta] 시작  (메모리: 1595.9 MB)
[메모리] forecast_theta 실행 전: 1595.88 MB
[메모리] forecast_theta 실행 후: 1595.88 MB (변화: +0.00 MB)
[ATEX]   [Theta] 완료  첫값=-2.43e+04 (메모리: 1595.9 MB)
[ATEX]   [DB] 93행 저장 완료
[PROGRESS] [ 388/500] ( 77.6%)  >>  SHYF
[SHYF]   45분기 | 2015-03-31 ~ 2026-03-31
[SHYF]   [SARIMA] 시작  (메모리: 1595.9 MB)
[메모리] forecast_sarima 실행 전: 1595.88 MB
[메모리] find_best_sarima_params 실행 전: 1595.88 MB
[메모리] find_best_sarima_params 실행 후: 1595.88 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1595.88 MB (변화: +0.00 MB)
[SHYF]   [SARIMA] 완료  첫값=2.05e+08 (메모리: 1595.9 MB)
[SHYF]   [ETS] 시작  (메모리: 1595.9 MB)
[메모리] forecast_ets 실행 전: 1595.88 MB
[메모리] forecast_ets 실행 후: 1595.88 MB (변화: +0.00 MB)
[SHYF]   [ETS] 완료  첫값=2.08e+08 (메모리: 1595.9 MB)
[SHYF]   [Prophet] 시작  (메모리: 1595.9 MB)

02:32:43 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1595.88 MB

02:32:43 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1595.88 MB (변화: +0.00 MB)
[SHYF]   [Prophet] 완료  첫값=2.38e+08 (메모리: 1595.9 MB)
[SHYF]   [LSTM] 시작  (메모리: 1595.9 MB)
[메모리] forecast_lstm 실행 전: 1595.88 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1595.84 MB (변화: -0.04 MB)
[SHYF]   [LSTM] 완료  첫값=2.06e+08 (메모리: 1595.8 MB)
[SHYF]   [Theta] 시작  (메모리: 1595.8 MB)
[메모리] forecast_theta 실행 전: 1595.84 MB
[메모리] forecast_theta 실행 후: 1595.84 MB (변화: +0.00 MB)
[SHYF]   [Theta] 완료  첫값=2.06e+08 (메모리: 1595.8 MB)
[SHYF]   [DB] 93행 저장 완료
[PROGRESS] [ 389/500] ( 77.8%)  >>  NETI
[NETI]   45분기 | 2015-03-31 ~ 2026-03-31
[NETI]   [SARIMA] 시작  (메모리: 1595.8 MB)
[메모리] forecast_sarima 실행 전: 1595.84 MB
[메모리] find_best_sarima_params 실행 전: 1595.84 MB
[메모리] find_best_sarima_params 실행 후: 1595.84 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1595.84 MB (변화: +0.00 MB)
[NETI]   [SARIMA] 완료  첫값=4.97e+07 (메모리: 1595.8 MB)
[NETI]   [ETS] 시작  (메모리: 1595.8 MB)
[메모리] forecast_ets 실행 전: 1595.84 MB
[메모리] forecast_ets 실행 후: 1595.84 MB (변화: +0.00 MB)
[NETI]   [ETS] 완료  첫값=5.90e+07 (메모리: 1595.8 MB)
[NETI]   [Prophet] 시작  (메모리: 1595.8 MB)

02:33:06 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1595.84 MB

02:33:06 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1596.23 MB (변화: +0.39 MB)
[NETI]   [Prophet] 완료  첫값=5.75e+07 (메모리: 1596.2 MB)
[NETI]   [LSTM] 시작  (메모리: 1596.2 MB)
[메모리] forecast_lstm 실행 전: 1596.23 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1596.23 MB (변화: +0.00 MB)
[NETI]   [LSTM] 완료  첫값=4.72e+07 (메모리: 1596.2 MB)
[NETI]   [Theta] 시작  (메모리: 1596.2 MB)
[메모리] forecast_theta 실행 전: 1596.23 MB
[메모리] forecast_theta 실행 후: 1596.23 MB (변화: +0.00 MB)
[NETI]   [Theta] 완료  첫값=5.89e+07 (메모리: 1596.2 MB)
[NETI]   [DB] 93행 저장 완료
[PROGRESS] [ 390/500] ( 78.0%)  >>  NOA
[NOA]   45분기 | 2015-03-31 ~ 2026-03-31
[NOA]   [SARIMA] 시작  (메모리: 1596.2 MB)
[메모리] forecast_sarima 실행 전: 1596.23 MB
[메모리] find_best_sarima_params 실행 전: 1596.23 MB
[메모리] find_best_sarima_params 실행 후: 1596.23 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1596.23 MB (변화: +0.00 MB)
[NOA]   [SARIMA] 완료  첫값=2.99e+08 (메모리: 1596.2 MB)
[NOA]   [ETS] 시작  (메모리: 1596.2 MB)
[메모리] forecast_ets 실행 전: 1596.23 MB
[메모리] forecast_ets 실행 후: 1596.23 MB (변화: +0.00 MB)
[NOA]   [ETS] 완료  첫값=2.33e+08 (메모리: 1596.2 MB)
[NOA]   [Prophet] 시작  (메모리: 1596.2 MB)

02:33:25 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1596.23 MB

02:33:25 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1596.24 MB (변화: +0.01 MB)
[NOA]   [Prophet] 완료  첫값=3.19e+08 (메모리: 1596.2 MB)
[NOA]   [LSTM] 시작  (메모리: 1596.2 MB)
[메모리] forecast_lstm 실행 전: 1596.24 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1596.22 MB (변화: -0.02 MB)
[NOA]   [LSTM] 완료  첫값=3.39e+08 (메모리: 1596.2 MB)
[NOA]   [Theta] 시작  (메모리: 1596.2 MB)
[메모리] forecast_theta 실행 전: 1596.22 MB
[메모리] forecast_theta 실행 후: 1596.22 MB (변화: +0.00 MB)
[NOA]   [Theta] 완료  첫값=2.18e+08 (메모리: 1596.2 MB)
[NOA]   [DB] 93행 저장 완료
[PROGRESS] [ 391/500] ( 78.2%)  >>  NGS
[NGS]   45분기 | 2015-03-31 ~ 2026-03-31
[NGS]   [SARIMA] 시작  (메모리: 1596.2 MB)
[메모리] forecast_sarima 실행 전: 1596.22 MB
[메모리] find_best_sarima_params 실행 전: 1596.22 MB
[메모리] find_best_sarima_params 실행 후: 1596.22 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1596.22 MB (변화: +0.00 MB)
[NGS]   [SARIMA] 완료  첫값=4.34e+07 (메모리: 1596.2 MB)
[NGS]   [ETS] 시작  (메모리: 1596.2 MB)
[메모리] forecast_ets 실행 전: 1596.22 MB
[메모리] forecast_ets 실행 후: 1596.23 MB (변화: +0.01 MB)
[NGS]   [ETS] 완료  첫값=4.42e+07 (메모리: 1596.2 MB)
[NGS]   [Prophet] 시작  (메모리: 1596.2 MB)

02:33:46 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1596.23 MB

02:33:46 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1596.23 MB (변화: +0.00 MB)
[NGS]   [Prophet] 완료  첫값=3.67e+07 (메모리: 1596.2 MB)
[NGS]   [LSTM] 시작  (메모리: 1596.2 MB)
[메모리] forecast_lstm 실행 전: 1596.23 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1596.25 MB (변화: +0.02 MB)
[NGS]   [LSTM] 완료  첫값=4.75e+07 (메모리: 1596.3 MB)
[NGS]   [Theta] 시작  (메모리: 1596.3 MB)
[메모리] forecast_theta 실행 전: 1596.25 MB
[메모리] forecast_theta 실행 후: 1596.25 MB (변화: +0.00 MB)
[NGS]   [Theta] 완료  첫값=4.27e+07 (메모리: 1596.3 MB)
[NGS]   [DB] 93행 저장 완료
[PROGRESS] [ 392/500] ( 78.4%)  >>  TRC
[TRC]   45분기 | 2015-03-31 ~ 2026-03-31
[TRC]   [SARIMA] 시작  (메모리: 1596.3 MB)
[메모리] forecast_sarima 실행 전: 1596.25 MB
[메모리] find_best_sarima_params 실행 전: 1596.25 MB
[메모리] find_best_sarima_params 실행 후: 1596.25 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1596.25 MB (변화: +0.00 MB)
[TRC]   [SARIMA] 완료  첫값=7.26e+06 (메모리: 1596.3 MB)
[TRC]   [ETS] 시작  (메모리: 1596.3 MB)
[메모리] forecast_ets 실행 전: 1596.25 MB
[메모리] forecast_ets 실행 후: 1596.26 MB (변화: +0.00 MB)
[TRC]   [ETS] 완료  첫값=7.42e+06 (메모리: 1596.3 MB)
[TRC]   [Prophet] 시작  (메모리: 1596.3 MB)

02:34:11 - cmdstanpy - INFO - Chain [1] start processing
02:34:11 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1596.26 MB
[메모리] forecast_prophet 실행 후: 1596.26 MB (변화: +0.00 MB)
[TRC]   [Prophet] 완료  첫값=1.26e+07 (메모리: 1596.3 MB)
[TRC]   [LSTM] 시작  (메모리: 1596.3 MB)
[메모리] forecast_lstm 실행 전: 1596.26 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1596.28 MB (변화: +0.02 MB)
[TRC]   [LSTM] 완료  첫값=1.19e+07 (메모리: 1596.3 MB)
[TRC]   [Theta] 시작  (메모리: 1596.3 MB)
[메모리] forecast_theta 실행 전: 1596.28 MB
[메모리] forecast_theta 실행 후: 1596.28 MB (변화: +0.00 MB)
[TRC]   [Theta] 완료  첫값=7.12e+06 (메모리: 1596.3 MB)
[TRC]   [DB] 93행 저장 완료
[PROGRESS] [ 393/500] ( 78.6%)  >>  FCEL
[FCEL]   45분기 | 2015-03-31 ~ 2026-03-31
[FCEL]   [SARIMA] 시작  (메모리: 1596.3 MB)
[메모리] forecast_sarima 실행 전: 1596.28 MB
[메모리] find_best_sarima_params 실행 전: 1596.28 MB
[메모리] find_best_sarima_params 실행 후: 1596.28 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1596.28 MB (변화: +0.00 MB)
[FCEL]   [SARIMA] 완료  첫값=4.45e+07 (메모리: 1596.3 MB)
[FCEL]   [ETS] 시작  (메모리: 1596.3 MB)
[메모리] forecast_ets 실행 전: 1596.28 MB
[메모리] forecast_ets 실행 후: 1596.29 MB (변화: +0.00 MB)
[FCEL]   [ETS] 완료  첫값=4.25e+07 (메모리: 1596.3 MB)
[FCEL]   [Prophet] 시작  (메모리: 1596.3 MB)

02:34:27 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1596.29 MB

02:34:27 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1596.30 MB (변화: +0.02 MB)
[FCEL]   [Prophet] 완료  첫값=3.18e+07 (메모리: 1596.3 MB)
[FCEL]   [LSTM] 시작  (메모리: 1596.3 MB)
[메모리] forecast_lstm 실행 전: 1596.30 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1596.28 MB (변화: -0.02 MB)
[FCEL]   [LSTM] 완료  첫값=3.11e+07 (메모리: 1596.3 MB)
[FCEL]   [Theta] 시작  (메모리: 1596.3 MB)
[메모리] forecast_theta 실행 전: 1596.28 MB
[메모리] forecast_theta 실행 후: 1596.28 MB (변화: +0.00 MB)
[FCEL]   [Theta] 완료  첫값=4.64e+07 (메모리: 1596.3 MB)
[FCEL]   [DB] 93행 저장 완료
[PROGRESS] [ 394/500] ( 78.8%)  >>  ALLT
[ALLT]   45분기 | 2015-03-31 ~ 2026-03-31
[ALLT]   [SARIMA] 시작  (메모리: 1596.3 MB)
[메모리] forecast_sarima 실행 전: 1596.28 MB
[메모리] find_best_sarima_params 실행 전: 1596.28 MB
[메모리] find_best_sarima_params 실행 후: 1596.28 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1596.28 MB (변화: +0.00 MB)
[ALLT]   [SARIMA] 완료  첫값=2.52e+07 (메모리: 1596.3 MB)
[ALLT]   [ETS] 시작  (메모리: 1596.3 MB)
[메모리] forecast_ets 실행 전: 1596.28 MB
[메모리] forecast_ets 실행 후: 1596.29 MB (변화: +0.01 MB)
[ALLT]   [ETS] 완료  첫값=2.72e+07 (메모리: 1596.3 MB)
[ALLT]   [Prophet] 시작  (메모리: 1596.3 MB)

02:34:46 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1596.29 MB

02:34:46 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1596.29 MB (변화: +0.00 MB)
[ALLT]   [Prophet] 완료  첫값=2.83e+07 (메모리: 1596.3 MB)
[ALLT]   [LSTM] 시작  (메모리: 1596.3 MB)
[메모리] forecast_lstm 실행 전: 1596.29 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1596.27 MB (변화: -0.02 MB)
[ALLT]   [LSTM] 완료  첫값=2.95e+07 (메모리: 1596.3 MB)
[ALLT]   [Theta] 시작  (메모리: 1596.3 MB)
[메모리] forecast_theta 실행 전: 1596.27 MB
[메모리] forecast_theta 실행 후: 1596.27 MB (변화: +0.00 MB)
[ALLT]   [Theta] 완료  첫값=2.72e+07 (메모리: 1596.3 MB)
[ALLT]   [DB] 93행 저장 완료
[PROGRESS] [ 395/500] ( 79.0%)  >>  CLFD
[CLFD]   45분기 | 2015-03-31 ~ 2026-03-31
[CLFD]   [SARIMA] 시작  (메모리: 1596.3 MB)
[메모리] forecast_sarima 실행 전: 1596.27 MB
[메모리] find_best_sarima_params 실행 전: 1596.27 MB
[메모리] find_best_sarima_params 실행 후: 1596.27 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1596.27 MB (변화: +0.00 MB)
[CLFD]   [SARIMA] 완료  첫값=2.59e+07 (메모리: 1596.3 MB)
[CLFD]   [ETS] 시작  (메모리: 1596.3 MB)
[메모리] forecast_ets 실행 전: 1596.27 MB
[메모리] forecast_ets 실행 후: 1596.27 MB (변화: +0.00 MB)
[CLFD]   [ETS] 완료  첫값=4.06e+07 (메모리: 1596.3 MB)
[CLFD]   [Prophet] 시작  (메모리: 1596.3 MB)

02:35:10 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1596.27 MB

02:35:10 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1596.27 MB (변화: +0.00 MB)
[CLFD]   [Prophet] 완료  첫값=5.51e+07 (메모리: 1596.3 MB)
[CLFD]   [LSTM] 시작  (메모리: 1596.3 MB)
[메모리] forecast_lstm 실행 전: 1596.27 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1596.27 MB (변화: +0.00 MB)
[CLFD]   [LSTM] 완료  첫값=3.98e+07 (메모리: 1596.3 MB)
[CLFD]   [Theta] 시작  (메모리: 1596.3 MB)
[메모리] forecast_theta 실행 전: 1596.27 MB
[메모리] forecast_theta 실행 후: 1596.27 MB (변화: +0.00 MB)
[CLFD]   [Theta] 완료  첫값=4.03e+07 (메모리: 1596.3 MB)
[CLFD]   [DB] 93행 저장 완료
[PROGRESS] [ 396/500] ( 79.2%)  >>  EVH
[EVH]   45분기 | 2015-03-31 ~ 2026-03-31
[EVH]   [SARIMA] 시작  (메모리: 1596.3 MB)
[메모리] forecast_sarima 실행 전: 1596.27 MB
[메모리] find_best_sarima_params 실행 전: 1596.27 MB
[메모리] find_best_sarima_params 실행 후: 1596.27 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1596.27 MB (변화: +0.00 MB)
[EVH]   [SARIMA] 완료  첫값=4.91e+08 (메모리: 1596.3 MB)
[EVH]   [ETS] 시작  (메모리: 1596.3 MB)
[메모리] forecast_ets 실행 전: 1596.27 MB
[메모리] forecast_ets 실행 후: 1596.27 MB (변화: +0.00 MB)
[EVH]   [ETS] 완료  첫값=3.69e+08 (메모리: 1596.3 MB)
[EVH]   [Prophet] 시작  (메모리: 1596.3 MB)

02:35:31 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1596.27 MB

02:35:31 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1596.28 MB (변화: +0.00 MB)
[EVH]   [Prophet] 완료  첫값=5.83e+08 (메모리: 1596.3 MB)
[EVH]   [LSTM] 시작  (메모리: 1596.3 MB)
[메모리] forecast_lstm 실행 전: 1596.28 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1596.26 MB (변화: -0.02 MB)
[EVH]   [LSTM] 완료  첫값=5.07e+08 (메모리: 1596.3 MB)
[EVH]   [Theta] 시작  (메모리: 1596.3 MB)
[메모리] forecast_theta 실행 전: 1596.26 MB
[메모리] forecast_theta 실행 후: 1596.26 MB (변화: +0.00 MB)
[EVH]   [Theta] 완료  첫값=4.79e+08 (메모리: 1596.3 MB)
[EVH]   [DB] 93행 저장 완료
[PROGRESS] [ 397/500] ( 79.4%)  >>  CAL
[CAL]   45분기 | 2015-03-31 ~ 2026-03-31
[CAL]   [SARIMA] 시작  (메모리: 1596.3 MB)
[메모리] forecast_sarima 실행 전: 1596.26 MB
[메모리] find_best_sarima_params 실행 전: 1596.26 MB
[메모리] find_best_sarima_params 실행 후: 1596.26 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1596.26 MB (변화: +0.00 MB)
[CAL]   [SARIMA] 완료  첫값=7.29e+08 (메모리: 1596.3 MB)
[CAL]   [ETS] 시작  (메모리: 1596.3 MB)
[메모리] forecast_ets 실행 전: 1596.26 MB
[메모리] forecast_ets 실행 후: 1596.26 MB (변화: +0.00 MB)
[CAL]   [ETS] 완료  첫값=7.16e+08 (메모리: 1596.3 MB)
[CAL]   [Prophet] 시작  (메모리: 1596.3 MB)

02:35:50 - cmdstanpy - INFO - Chain [1] start processing
02:35:50 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1596.26 MB
[메모리] forecast_prophet 실행 후: 1596.29 MB (변화: +0.02 MB)
[CAL]   [Prophet] 완료  첫값=7.15e+08 (메모리: 1596.3 MB)
[CAL]   [LSTM] 시작  (메모리: 1596.3 MB)
[메모리] forecast_lstm 실행 전: 1596.29 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1596.31 MB (변화: +0.03 MB)
[CAL]   [LSTM] 완료  첫값=6.30e+08 (메모리: 1596.3 MB)
[CAL]   [Theta] 시작  (메모리: 1596.3 MB)
[메모리] forecast_theta 실행 전: 1596.31 MB
[메모리] forecast_theta 실행 후: 1596.31 MB (변화: +0.00 MB)
[CAL]   [Theta] 완료  첫값=7.34e+08 (메모리: 1596.3 MB)
[CAL]   [DB] 93행 저장 완료
[PROGRESS] [ 398/500] ( 79.6%)  >>  PTSI
[PTSI]   45분기 | 2015-03-31 ~ 2026-03-31
[PTSI]   [SARIMA] 시작  (메모리: 1596.3 MB)
[메모리] forecast_sarima 실행 전: 1596.31 MB
[메모리] find_best_sarima_params 실행 전: 1596.31 MB
[메모리] find_best_sarima_params 실행 후: 1596.31 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1596.31 MB (변화: +0.00 MB)
[PTSI]   [SARIMA] 완료  첫값=1.48e+08 (메모리: 1596.3 MB)
[PTSI]   [ETS] 시작  (메모리: 1596.3 MB)
[메모리] forecast_ets 실행 전: 1596.31 MB
[메모리] forecast_ets 실행 후: 1596.31 MB (변화: +0.00 MB)
[PTSI]   [ETS] 완료  첫값=1.50e+08 (메모리: 1596.3 MB)
[PTSI]   [Prophet] 시작  (메모리: 1596.3 MB)

02:36:11 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1596.31 MB

02:36:11 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1596.70 MB (변화: +0.38 MB)
[PTSI]   [Prophet] 완료  첫값=1.49e+08 (메모리: 1596.7 MB)
[PTSI]   [LSTM] 시작  (메모리: 1596.7 MB)
[메모리] forecast_lstm 실행 전: 1596.70 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1596.69 MB (변화: -0.01 MB)
[PTSI]   [LSTM] 완료  첫값=4.13e+07 (메모리: 1596.7 MB)
[PTSI]   [Theta] 시작  (메모리: 1596.7 MB)
[메모리] forecast_theta 실행 전: 1596.69 MB
[메모리] forecast_theta 실행 후: 1596.69 MB (변화: +0.00 MB)
[PTSI]   [Theta] 완료  첫값=1.37e+08 (메모리: 1596.7 MB)
[PTSI]   [DB] 93행 저장 완료
[PROGRESS] [ 399/500] ( 79.8%)  >>  NATR
[NATR]   45분기 | 2015-03-31 ~ 2026-03-31
[NATR]   [SARIMA] 시작  (메모리: 1596.7 MB)
[메모리] forecast_sarima 실행 전: 1596.69 MB
[메모리] find_best_sarima_params 실행 전: 1596.69 MB
[메모리] find_best_sarima_params 실행 후: 1596.69 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1596.69 MB (변화: +0.00 MB)
[NATR]   [SARIMA] 완료  첫값=1.30e+08 (메모리: 1596.7 MB)
[NATR]   [ETS] 시작  (메모리: 1596.7 MB)
[메모리] forecast_ets 실행 전: 1596.69 MB
[메모리] forecast_ets 실행 후: 1596.69 MB (변화: +0.00 MB)
[NATR]   [ETS] 완료  첫값=1.29e+08 (메모리: 1596.7 MB)
[NATR]   [Prophet] 시작  (메모리: 1596.7 MB)

02:36:30 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1596.69 MB

02:36:31 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1596.83 MB (변화: +0.14 MB)
[NATR]   [Prophet] 완료  첫값=1.24e+08 (메모리: 1596.8 MB)
[NATR]   [LSTM] 시작  (메모리: 1596.8 MB)
[메모리] forecast_lstm 실행 전: 1596.83 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1596.81 MB (변화: -0.02 MB)
[NATR]   [LSTM] 완료  첫값=1.21e+08 (메모리: 1596.8 MB)
[NATR]   [Theta] 시작  (메모리: 1596.8 MB)
[메모리] forecast_theta 실행 전: 1596.81 MB
[메모리] forecast_theta 실행 후: 1596.81 MB (변화: +0.00 MB)
[NATR]   [Theta] 완료  첫값=1.28e+08 (메모리: 1596.8 MB)
[NATR]   [DB] 93행 저장 완료
[PROGRESS] [ 400/500] ( 80.0%)  >>  LPTH
[LPTH]   45분기 | 2015-03-31 ~ 2026-03-31
[LPTH]   [SARIMA] 시작  (메모리: 1596.8 MB)
[메모리] forecast_sarima 실행 전: 1596.81 MB
[메모리] find_best_sarima_params 실행 전: 1596.81 MB
[메모리] find_best_sarima_params 실행 후: 1596.81 MB (변화: +0.00 MB)
[메모리] find_best_sarima_params 실행 전: 1596.81 MB
[메모리] find_best_sarima_params 실행 후: 1596.81 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1596.81 MB (변화: +0.00 MB)
[LPTH]   [SARIMA] 오류응답: {'error': 'SARIMA 적합 실패 (발산 포함)'}
[LPTH]   [ETS] 시작  (메모리: 1596.8 MB)
[메모리] forecast_ets 실행 전: 1596.81 MB
[메모리] forecast_ets 실행 후: 1596.81 MB (변화: +0.00 MB)
[LPTH]   [ETS] 완료  첫값=2.22e+10 (메모리: 1596.8 MB)
[LPTH]   [Prophet] 시작  (메모리: 1596.8 MB)

02:36:59 - cmdstanpy - INFO - Chain [1] start processing
02:36:59 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1596.81 MB
[메모리] forecast_prophet 실행 후: 1597.09 MB (변화: +0.29 MB)
[LPTH]   [Prophet] 완료  첫값=2.86e+09 (메모리: 1597.1 MB)
[LPTH]   [LSTM] 시작  (메모리: 1597.1 MB)
[메모리] forecast_lstm 실행 전: 1597.09 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1597.15 MB (변화: +0.05 MB)
[LPTH]   [LSTM] 완료  첫값=3.83e+09 (메모리: 1597.1 MB)
[LPTH]   [Theta] 시작  (메모리: 1597.1 MB)
[메모리] forecast_theta 실행 전: 1597.15 MB
[메모리] forecast_theta 실행 후: 1597.15 MB (변화: +0.00 MB)
[LPTH]   [Theta] 완료  첫값=1.68e+10 (메모리: 1597.1 MB)
[LPTH]   [DB] 85행 저장 완료
[PROGRESS] [ 401/500] ( 80.2%)  >>  ULH
[ULH]   45분기 | 2015-03-31 ~ 2026-03-31
[ULH]   [SARIMA] 시작  (메모리: 1597.1 MB)
[메모리] forecast_sarima 실행 전: 1597.15 MB
[메모리] find_best_sarima_params 실행 전: 1597.15 MB
[메모리] find_best_sarima_params 실행 후: 1597.15 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1597.15 MB (변화: +0.00 MB)
[ULH]   [SARIMA] 완료  첫값=3.97e+08 (메모리: 1597.1 MB)
[ULH]   [ETS] 시작  (메모리: 1597.1 MB)
[메모리] forecast_ets 실행 전: 1597.15 MB
[메모리] forecast_ets 실행 후: 1597.15 MB (변화: +0.00 MB)
[ULH]   [ETS] 완료  첫값=4.11e+08 (메모리: 1597.1 MB)
[ULH]   [Prophet] 시작  (메모리: 1597.1 MB)

02:37:24 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1597.15 MB

02:37:24 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1596.48 MB (변화: -0.67 MB)
[ULH]   [Prophet] 완료  첫값=4.76e+08 (메모리: 1596.5 MB)
[ULH]   [LSTM] 시작  (메모리: 1596.5 MB)
[메모리] forecast_lstm 실행 전: 1596.48 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1596.48 MB (변화: +0.00 MB)
[ULH]   [LSTM] 완료  첫값=4.33e+08 (메모리: 1596.5 MB)
[ULH]   [Theta] 시작  (메모리: 1596.5 MB)
[메모리] forecast_theta 실행 전: 1596.48 MB
[메모리] forecast_theta 실행 후: 1596.48 MB (변화: +0.00 MB)
[ULH]   [Theta] 완료  첫값=4.06e+08 (메모리: 1596.5 MB)
[ULH]   [DB] 93행 저장 완료
[PROGRESS] [ 402/500] ( 80.4%)  >>  HVT
[HVT]   45분기 | 2015-03-31 ~ 2026-03-31
[HVT]   [SARIMA] 시작  (메모리: 1596.5 MB)
[메모리] forecast_sarima 실행 전: 1596.48 MB
[메모리] find_best_sarima_params 실행 전: 1596.48 MB
[메모리] find_best_sarima_params 실행 후: 1596.48 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1596.48 MB (변화: +0.00 MB)
[HVT]   [SARIMA] 완료  첫값=1.94e+08 (메모리: 1596.5 MB)
[HVT]   [ETS] 시작  (메모리: 1596.5 MB)
[메모리] forecast_ets 실행 전: 1596.48 MB
[메모리] forecast_ets 실행 후: 1596.48 MB (변화: +0.00 MB)
[HVT]   [ETS] 완료  첫값=1.80e+08 (메모리: 1596.5 MB)
[HVT]   [Prophet] 시작  (메모리: 1596.5 MB)

02:37:47 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1596.48 MB

02:37:47 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1597.30 MB (변화: +0.82 MB)
[HVT]   [Prophet] 완료  첫값=2.11e+08 (메모리: 1597.3 MB)
[HVT]   [LSTM] 시작  (메모리: 1597.3 MB)
[메모리] forecast_lstm 실행 전: 1597.30 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1597.28 MB (변화: -0.02 MB)
[HVT]   [LSTM] 완료  첫값=1.88e+08 (메모리: 1597.3 MB)
[HVT]   [Theta] 시작  (메모리: 1597.3 MB)
[메모리] forecast_theta 실행 전: 1597.28 MB
[메모리] forecast_theta 실행 후: 1597.28 MB (변화: +0.00 MB)
[HVT]   [Theta] 완료  첫값=1.93e+08 (메모리: 1597.3 MB)
[HVT]   [DB] 93행 저장 완료
[PROGRESS] [ 403/500] ( 80.6%)  >>  ANGO
[ANGO]   45분기 | 2015-03-31 ~ 2026-03-31
[ANGO]   [SARIMA] 시작  (메모리: 1597.3 MB)
[메모리] forecast_sarima 실행 전: 1597.28 MB
[메모리] find_best_sarima_params 실행 전: 1597.28 MB
[메모리] find_best_sarima_params 실행 후: 1597.28 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1597.28 MB (변화: +0.00 MB)
[ANGO]   [SARIMA] 완료  첫값=7.94e+07 (메모리: 1597.3 MB)
[ANGO]   [ETS] 시작  (메모리: 1597.3 MB)
[메모리] forecast_ets 실행 전: 1597.28 MB
[메모리] forecast_ets 실행 후: 1597.28 MB (변화: +0.00 MB)
[ANGO]   [ETS] 완료  첫값=8.22e+07 (메모리: 1597.3 MB)
[ANGO]   [Prophet] 시작  (메모리: 1597.3 MB)

02:38:10 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1597.28 MB

02:38:10 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1597.00 MB (변화: -0.28 MB)
[ANGO]   [Prophet] 완료  첫값=7.32e+07 (메모리: 1597.0 MB)
[ANGO]   [LSTM] 시작  (메모리: 1597.0 MB)
[메모리] forecast_lstm 실행 전: 1597.00 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1597.67 MB (변화: +0.67 MB)
[ANGO]   [LSTM] 완료  첫값=7.37e+07 (메모리: 1597.7 MB)
[ANGO]   [Theta] 시작  (메모리: 1597.7 MB)
[메모리] forecast_theta 실행 전: 1597.67 MB
[메모리] forecast_theta 실행 후: 1597.67 MB (변화: +0.00 MB)
[ANGO]   [Theta] 완료  첫값=7.86e+07 (메모리: 1597.7 MB)
[ANGO]   [DB] 93행 저장 완료
[PROGRESS] [ 404/500] ( 80.8%)  >>  ZUMZ
[ZUMZ]   45분기 | 2015-03-31 ~ 2026-03-31
[ZUMZ]   [SARIMA] 시작  (메모리: 1597.7 MB)
[메모리] forecast_sarima 실행 전: 1597.67 MB
[메모리] find_best_sarima_params 실행 전: 1597.67 MB
[메모리] find_best_sarima_params 실행 후: 1597.67 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1597.67 MB (변화: +0.00 MB)
[ZUMZ]   [SARIMA] 완료  첫값=1.74e+08 (메모리: 1597.7 MB)
[ZUMZ]   [ETS] 시작  (메모리: 1597.7 MB)
[메모리] forecast_ets 실행 전: 1597.67 MB
[메모리] forecast_ets 실행 후: 1597.67 MB (변화: +0.00 MB)
[ZUMZ]   [ETS] 완료  첫값=1.74e+08 (메모리: 1597.7 MB)
[ZUMZ]   [Prophet] 시작  (메모리: 1597.7 MB)

02:38:28 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1597.67 MB

02:38:28 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1597.33 MB (변화: -0.34 MB)
[ZUMZ]   [Prophet] 완료  첫값=2.46e+08 (메모리: 1597.3 MB)
[ZUMZ]   [LSTM] 시작  (메모리: 1597.3 MB)
[메모리] forecast_lstm 실행 전: 1597.33 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.36 MB (변화: +1.02 MB)
[ZUMZ]   [LSTM] 완료  첫값=2.18e+08 (메모리: 1598.4 MB)
[ZUMZ]   [Theta] 시작  (메모리: 1598.4 MB)
[메모리] forecast_theta 실행 전: 1598.36 MB
[메모리] forecast_theta 실행 후: 1598.36 MB (변화: +0.00 MB)
[ZUMZ]   [Theta] 완료  첫값=1.73e+08 (메모리: 1598.4 MB)
[ZUMZ]   [DB] 93행 저장 완료
[PROGRESS] [ 405/500] ( 81.0%)  >>  PTN
[PTN]   45분기 | 2015-03-31 ~ 2026-03-31
[PTN]   [SARIMA] 시작  (메모리: 1598.4 MB)
[메모리] forecast_sarima 실행 전: 1598.36 MB
[메모리] find_best_sarima_params 실행 전: 1598.36 MB
[메모리] find_best_sarima_params 실행 후: 1598.36 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.36 MB (변화: +0.00 MB)
[PTN]   [SARIMA] 완료  첫값=9.53e+06 (메모리: 1598.4 MB)
[PTN]   [ETS] 시작  (메모리: 1598.4 MB)
[메모리] forecast_ets 실행 전: 1598.36 MB
[메모리] forecast_ets 실행 후: 1598.36 MB (변화: +0.00 MB)
[PTN]   [ETS] 완료  첫값=1.20e+07 (메모리: 1598.4 MB)
[PTN]   [Prophet] 시작  (메모리: 1598.4 MB)

02:38:47 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1598.36 MB

02:38:47 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1597.38 MB (변화: -0.98 MB)
[PTN]   [Prophet] 완료  첫값=2.05e+06 (메모리: 1597.4 MB)
[PTN]   [LSTM] 시작  (메모리: 1597.4 MB)
[메모리] forecast_lstm 실행 전: 1597.38 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.39 MB (변화: +1.02 MB)
[PTN]   [LSTM] 완료  첫값=6.93e+06 (메모리: 1598.4 MB)
[PTN]   [Theta] 시작  (메모리: 1598.4 MB)
[메모리] forecast_theta 실행 전: 1598.39 MB
[메모리] forecast_theta 실행 후: 1598.39 MB (변화: +0.00 MB)
[PTN]   [Theta] 완료  첫값=2.43e+06 (메모리: 1598.4 MB)
[PTN]   [DB] 93행 저장 완료
[PROGRESS] [ 406/500] ( 81.2%)  >>  USAP
[USAP]   45분기 | 2015-03-31 ~ 2026-03-31
[USAP]   [SARIMA] 시작  (메모리: 1598.4 MB)
[메모리] forecast_sarima 실행 전: 1598.39 MB
[메모리] find_best_sarima_params 실행 전: 1598.39 MB
[메모리] find_best_sarima_params 실행 후: 1598.39 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.39 MB (변화: +0.00 MB)
[USAP]   [SARIMA] 완료  첫값=8.83e+07 (메모리: 1598.4 MB)
[USAP]   [ETS] 시작  (메모리: 1598.4 MB)
[메모리] forecast_ets 실행 전: 1598.39 MB
[메모리] forecast_ets 실행 후: 1598.39 MB (변화: +0.00 MB)
[USAP]   [ETS] 완료  첫값=9.31e+07 (메모리: 1598.4 MB)
[USAP]   [Prophet] 시작  (메모리: 1598.4 MB)

02:39:04 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1598.39 MB

02:39:05 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1597.41 MB (변화: -0.98 MB)
[USAP]   [Prophet] 완료  첫값=7.99e+07 (메모리: 1597.4 MB)
[USAP]   [LSTM] 시작  (메모리: 1597.4 MB)
[메모리] forecast_lstm 실행 전: 1597.41 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1597.09 MB (변화: -0.32 MB)
[USAP]   [LSTM] 완료  첫값=7.30e+07 (메모리: 1597.1 MB)
[USAP]   [Theta] 시작  (메모리: 1597.1 MB)
[메모리] forecast_theta 실행 전: 1597.09 MB
[메모리] forecast_theta 실행 후: 1597.09 MB (변화: +0.00 MB)
[USAP]   [Theta] 완료  첫값=9.00e+07 (메모리: 1597.1 MB)
[USAP]   [DB] 93행 저장 완료
[PROGRESS] [ 407/500] ( 81.4%)  >>  CLPT
[CLPT]   45분기 | 2015-03-31 ~ 2026-03-31
[CLPT]   [SARIMA] 시작  (메모리: 1597.1 MB)
[메모리] forecast_sarima 실행 전: 1597.09 MB
[메모리] find_best_sarima_params 실행 전: 1597.09 MB
[메모리] find_best_sarima_params 실행 후: 1597.09 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1597.09 MB (변화: +0.00 MB)
[CLPT]   [SARIMA] 완료  첫값=1.06e+07 (메모리: 1597.1 MB)
[CLPT]   [ETS] 시작  (메모리: 1597.1 MB)
[메모리] forecast_ets 실행 전: 1597.09 MB
[메모리] forecast_ets 실행 후: 1597.09 MB (변화: +0.00 MB)
[CLPT]   [ETS] 완료  첫값=1.03e+07 (메모리: 1597.1 MB)
[CLPT]   [Prophet] 시작  (메모리: 1597.1 MB)

02:39:31 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1597.09 MB

02:39:31 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1597.51 MB (변화: +0.42 MB)
[CLPT]   [Prophet] 완료  첫값=9.58e+06 (메모리: 1597.5 MB)
[CLPT]   [LSTM] 시작  (메모리: 1597.5 MB)
[메모리] forecast_lstm 실행 전: 1597.51 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1597.19 MB (변화: -0.32 MB)
[CLPT]   [LSTM] 완료  첫값=1.07e+07 (메모리: 1597.2 MB)
[CLPT]   [Theta] 시작  (메모리: 1597.2 MB)
[메모리] forecast_theta 실행 전: 1597.19 MB
[메모리] forecast_theta 실행 후: 1597.19 MB (변화: +0.00 MB)
[CLPT]   [Theta] 완료  첫값=8.34e+06 (메모리: 1597.2 MB)
[CLPT]   [DB] 93행 저장 완료
[PROGRESS] [ 408/500] ( 81.6%)  >>  TSAT
[TSAT]   45분기 | 2015-03-31 ~ 2026-03-31
[TSAT]   [SARIMA] 시작  (메모리: 1597.2 MB)
[메모리] forecast_sarima 실행 전: 1597.19 MB
[메모리] find_best_sarima_params 실행 전: 1597.19 MB
[메모리] find_best_sarima_params 실행 후: 1597.19 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1597.19 MB (변화: +0.00 MB)
[TSAT]   [SARIMA] 완료  첫값=9.93e+07 (메모리: 1597.2 MB)
[TSAT]   [ETS] 시작  (메모리: 1597.2 MB)
[메모리] forecast_ets 실행 전: 1597.19 MB
[메모리] forecast_ets 실행 후: 1597.19 MB (변화: +0.00 MB)
[TSAT]   [ETS] 완료  첫값=9.43e+07 (메모리: 1597.2 MB)
[TSAT]   [Prophet] 시작  (메모리: 1597.2 MB)

02:39:58 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1597.19 MB

02:39:58 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1598.01 MB (변화: +0.82 MB)
[TSAT]   [Prophet] 완료  첫값=9.58e+07 (메모리: 1598.0 MB)
[TSAT]   [LSTM] 시작  (메모리: 1598.0 MB)
[메모리] forecast_lstm 실행 전: 1598.01 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1597.20 MB (변화: -0.81 MB)
[TSAT]   [LSTM] 완료  첫값=9.96e+07 (메모리: 1597.2 MB)
[TSAT]   [Theta] 시작  (메모리: 1597.2 MB)
[메모리] forecast_theta 실행 전: 1597.20 MB
[메모리] forecast_theta 실행 후: 1597.20 MB (변화: +0.00 MB)
[TSAT]   [Theta] 완료  첫값=1.00e+08 (메모리: 1597.2 MB)
[TSAT]   [DB] 93행 저장 완료
[PROGRESS] [ 409/500] ( 81.8%)  >>  SGU
[SGU]   45분기 | 2015-03-31 ~ 2026-03-31
[SGU]   [SARIMA] 시작  (메모리: 1597.2 MB)
[메모리] forecast_sarima 실행 전: 1597.20 MB
[메모리] find_best_sarima_params 실행 전: 1597.20 MB
[메모리] find_best_sarima_params 실행 후: 1597.20 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1597.20 MB (변화: +0.00 MB)
[SGU]   [SARIMA] 완료  첫값=2.62e+08 (메모리: 1597.2 MB)
[SGU]   [ETS] 시작  (메모리: 1597.2 MB)
[메모리] forecast_ets 실행 전: 1597.20 MB
[메모리] forecast_ets 실행 후: 1597.20 MB (변화: +0.00 MB)
[SGU]   [ETS] 완료  첫값=2.37e+08 (메모리: 1597.2 MB)
[SGU]   [Prophet] 시작  (메모리: 1597.2 MB)

02:40:23 - cmdstanpy - INFO - Chain [1] start processing
02:40:23 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1597.20 MB
[메모리] forecast_prophet 실행 후: 1598.02 MB (변화: +0.82 MB)
[SGU]   [Prophet] 완료  첫값=4.83e+08 (메모리: 1598.0 MB)
[SGU]   [LSTM] 시작  (메모리: 1598.0 MB)
[메모리] forecast_lstm 실행 전: 1598.02 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1597.19 MB (변화: -0.83 MB)
[SGU]   [LSTM] 완료  첫값=4.80e+08 (메모리: 1597.2 MB)
[SGU]   [Theta] 시작  (메모리: 1597.2 MB)
[메모리] forecast_theta 실행 전: 1597.19 MB
[메모리] forecast_theta 실행 후: 1597.19 MB (변화: +0.00 MB)
[SGU]   [Theta] 완료  첫값=2.44e+08 (메모리: 1597.2 MB)
[SGU]   [DB] 93행 저장 완료
[PROGRESS] [ 410/500] ( 82.0%)  >>  VHI
[VHI]   45분기 | 2015-03-31 ~ 2026-03-31
[VHI]   [SARIMA] 시작  (메모리: 1597.2 MB)
[메모리] forecast_sarima 실행 전: 1597.19 MB
[메모리] find_best_sarima_params 실행 전: 1597.19 MB
[메모리] find_best_sarima_params 실행 후: 1597.19 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1597.19 MB (변화: +0.00 MB)
[VHI]   [SARIMA] 완료  첫값=5.06e+08 (메모리: 1597.2 MB)
[VHI]   [ETS] 시작  (메모리: 1597.2 MB)
[메모리] forecast_ets 실행 전: 1597.19 MB
[메모리] forecast_ets 실행 후: 1597.20 MB (변화: +0.00 MB)
[VHI]   [ETS] 완료  첫값=5.25e+08 (메모리: 1597.2 MB)
[VHI]   [Prophet] 시작  (메모리: 1597.2 MB)

02:40:41 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1597.20 MB

02:40:41 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1597.21 MB (변화: +0.02 MB)
[VHI]   [Prophet] 완료  첫값=5.57e+08 (메모리: 1597.2 MB)
[VHI]   [LSTM] 시작  (메모리: 1597.2 MB)
[메모리] forecast_lstm 실행 전: 1597.21 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.19 MB (변화: +0.98 MB)
[VHI]   [LSTM] 완료  첫값=5.15e+08 (메모리: 1598.2 MB)
[VHI]   [Theta] 시작  (메모리: 1598.2 MB)
[메모리] forecast_theta 실행 전: 1598.19 MB
[메모리] forecast_theta 실행 후: 1598.19 MB (변화: +0.00 MB)
[VHI]   [Theta] 완료  첫값=5.06e+08 (메모리: 1598.2 MB)
[VHI]   [DB] 93행 저장 완료
[PROGRESS] [ 411/500] ( 82.2%)  >>  PLG
[PLG]   45분기 | 2015-03-31 ~ 2026-03-31
[PLG]   [SARIMA] 시작  (메모리: 1598.2 MB)
[메모리] forecast_sarima 실행 전: 1598.19 MB
[메모리] find_best_sarima_params 실행 전: 1598.19 MB
[메모리] find_best_sarima_params 실행 후: 1598.19 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.19 MB (변화: +0.00 MB)
[PLG]   [SARIMA] 완료  첫값=0.00e+00 (메모리: 1598.2 MB)
[PLG]   [ETS] 시작  (메모리: 1598.2 MB)
[메모리] forecast_ets 실행 전: 1598.19 MB
[메모리] forecast_ets 실행 후: 1598.19 MB (변화: +0.00 MB)
[PLG]   [ETS] 완료  첫값=0.00e+00 (메모리: 1598.2 MB)
[PLG]   [Prophet] 시작  (메모리: 1598.2 MB)
[메모리] forecast_prophet 실행 전: 1598.19 MB
[메모리] forecast_prophet 실행 후: 1598.21 MB (변화: +0.02 MB)
[PLG]   [Prophet] 완료  첫값=0.00e+00 (메모리: 1598.2 MB)
[PLG]   [LSTM] 시작  (메모리: 1598.2 MB)
[메모리] forecast_lstm 실행 전: 1598.21 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.21 MB (변화: +0.00 MB)
[PLG]   [LSTM] 완료  첫값=0.00e+00 (메모리: 1598.2 MB)
[PLG]   [Theta] 시작  (메모리: 1598.2 MB)
[메모리] forecast_theta 실행 전: 1598.21 MB
[메모리] forecast_theta 실행 후: 1598.21 MB (변화: +0.00 MB)
[PLG]   [Theta] 완료  첫값=0.00e+00 (메모리: 1598.2 MB)
[PLG]   [DB] 93행 저장 완료
[PROGRESS] [ 412/500] ( 82.4%)  >>  KOR
[KOR] [SKIP] [KOR] 'sale' 데이터가 DB에 없습니다.
[PROGRESS] [ 413/500] ( 82.6%)  >>  GPRK
[GPRK]   45분기 | 2015-03-31 ~ 2026-03-31
[GPRK]   [SARIMA] 시작  (메모리: 1598.2 MB)
[메모리] forecast_sarima 실행 전: 1598.21 MB
[메모리] find_best_sarima_params 실행 전: 1598.21 MB
[메모리] find_best_sarima_params 실행 후: 1598.21 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.21 MB (변화: +0.00 MB)
[GPRK]   [SARIMA] 완료  첫값=1.57e+08 (메모리: 1598.2 MB)
[GPRK]   [ETS] 시작  (메모리: 1598.2 MB)
[메모리] forecast_ets 실행 전: 1598.21 MB
[메모리] forecast_ets 실행 후: 1598.21 MB (변화: +0.00 MB)
[GPRK]   [ETS] 완료  첫값=1.43e+08 (메모리: 1598.2 MB)
[GPRK]   [Prophet] 시작  (메모리: 1598.2 MB)

02:41:25 - cmdstanpy - INFO - Chain [1] start processing
02:41:25 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1598.21 MB
[메모리] forecast_prophet 실행 후: 1598.23 MB (변화: +0.01 MB)
[GPRK]   [Prophet] 완료  첫값=1.93e+08 (메모리: 1598.2 MB)
[GPRK]   [LSTM] 시작  (메모리: 1598.2 MB)
[메모리] forecast_lstm 실행 전: 1598.23 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.22 MB (변화: -0.01 MB)
[GPRK]   [LSTM] 완료  첫값=1.40e+08 (메모리: 1598.2 MB)
[GPRK]   [Theta] 시작  (메모리: 1598.2 MB)
[메모리] forecast_theta 실행 전: 1598.22 MB
[메모리] forecast_theta 실행 후: 1598.22 MB (변화: +0.00 MB)
[GPRK]   [Theta] 완료  첫값=1.45e+08 (메모리: 1598.2 MB)
[GPRK]   [DB] 93행 저장 완료
[PROGRESS] [ 414/500] ( 82.8%)  >>  NATH
[NATH]   45분기 | 2015-03-31 ~ 2026-03-31
[NATH]   [SARIMA] 시작  (메모리: 1598.2 MB)
[메모리] forecast_sarima 실행 전: 1598.22 MB
[메모리] find_best_sarima_params 실행 전: 1598.22 MB
[메모리] find_best_sarima_params 실행 후: 1598.22 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.22 MB (변화: +0.00 MB)
[NATH]   [SARIMA] 완료  첫값=4.66e+07 (메모리: 1598.2 MB)
[NATH]   [ETS] 시작  (메모리: 1598.2 MB)
[메모리] forecast_ets 실행 전: 1598.22 MB
[메모리] forecast_ets 실행 후: 1598.22 MB (변화: +0.00 MB)
[NATH]   [ETS] 완료  첫값=4.98e+07 (메모리: 1598.2 MB)
[NATH]   [Prophet] 시작  (메모리: 1598.2 MB)

02:41:48 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1598.22 MB

02:41:48 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1598.22 MB (변화: +0.00 MB)
[NATH]   [Prophet] 완료  첫값=3.71e+07 (메모리: 1598.2 MB)
[NATH]   [LSTM] 시작  (메모리: 1598.2 MB)
[메모리] forecast_lstm 실행 전: 1598.22 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.23 MB (변화: +0.01 MB)
[NATH]   [LSTM] 완료  첫값=3.97e+07 (메모리: 1598.2 MB)
[NATH]   [Theta] 시작  (메모리: 1598.2 MB)
[메모리] forecast_theta 실행 전: 1598.23 MB
[메모리] forecast_theta 실행 후: 1598.23 MB (변화: +0.00 MB)
[NATH]   [Theta] 완료  첫값=4.97e+07 (메모리: 1598.2 MB)
[NATH]   [DB] 93행 저장 완료
[PROGRESS] [ 415/500] ( 83.0%)  >>  PERI
[PERI]   45분기 | 2015-03-31 ~ 2026-03-31
[PERI]   [SARIMA] 시작  (메모리: 1598.2 MB)
[메모리] forecast_sarima 실행 전: 1598.23 MB
[메모리] find_best_sarima_params 실행 전: 1598.23 MB
[메모리] find_best_sarima_params 실행 후: 1598.23 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.23 MB (변화: +0.00 MB)
[PERI]   [SARIMA] 완료  첫값=1.14e+08 (메모리: 1598.2 MB)
[PERI]   [ETS] 시작  (메모리: 1598.2 MB)
[메모리] forecast_ets 실행 전: 1598.23 MB
[메모리] forecast_ets 실행 후: 1598.23 MB (변화: +0.00 MB)
[PERI]   [ETS] 완료  첫값=1.16e+08 (메모리: 1598.2 MB)
[PERI]   [Prophet] 시작  (메모리: 1598.2 MB)

02:42:06 - cmdstanpy - INFO - Chain [1] start processing
02:42:06 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1598.23 MB
[메모리] forecast_prophet 실행 후: 1598.26 MB (변화: +0.02 MB)
[PERI]   [Prophet] 완료  첫값=1.53e+08 (메모리: 1598.3 MB)
[PERI]   [LSTM] 시작  (메모리: 1598.3 MB)
[메모리] forecast_lstm 실행 전: 1598.26 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.25 MB (변화: -0.01 MB)
[PERI]   [LSTM] 완료  첫값=1.42e+08 (메모리: 1598.2 MB)
[PERI]   [Theta] 시작  (메모리: 1598.2 MB)
[메모리] forecast_theta 실행 전: 1598.25 MB
[메모리] forecast_theta 실행 후: 1598.25 MB (변화: +0.00 MB)
[PERI]   [Theta] 완료  첫값=1.17e+08 (메모리: 1598.2 MB)
[PERI]   [DB] 93행 저장 완료
[PROGRESS] [ 416/500] ( 83.2%)  >>  LTBR
[LTBR]   45분기 | 2015-03-31 ~ 2026-03-31
[LTBR]   [SARIMA] 시작  (메모리: 1598.2 MB)
[메모리] forecast_sarima 실행 전: 1598.25 MB
[메모리] find_best_sarima_params 실행 전: 1598.25 MB
[메모리] find_best_sarima_params 실행 후: 1598.25 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.25 MB (변화: +0.00 MB)
[LTBR]   [SARIMA] 완료  첫값=2.95e+02 (메모리: 1598.2 MB)
[LTBR]   [ETS] 시작  (메모리: 1598.2 MB)
[메모리] forecast_ets 실행 전: 1598.25 MB
[메모리] forecast_ets 실행 후: 1598.25 MB (변화: +0.00 MB)
[LTBR]   [ETS] 완료  첫값=-7.01e+03 (메모리: 1598.2 MB)
[LTBR]   [Prophet] 시작  (메모리: 1598.2 MB)

02:42:23 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1598.25 MB

02:42:24 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1598.25 MB (변화: +0.00 MB)
[LTBR]   [Prophet] 완료  첫값=-5.94e+04 (메모리: 1598.2 MB)
[LTBR]   [LSTM] 시작  (메모리: 1598.2 MB)
[메모리] forecast_lstm 실행 전: 1598.25 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.27 MB (변화: +0.02 MB)
[LTBR]   [LSTM] 완료  첫값=6.21e-01 (메모리: 1598.3 MB)
[LTBR]   [Theta] 시작  (메모리: 1598.3 MB)
[메모리] forecast_theta 실행 전: 1598.27 MB
[메모리] forecast_theta 실행 후: 1598.27 MB (변화: +0.00 MB)
[LTBR]   [Theta] 완료  첫값=-2.08e+04 (메모리: 1598.3 MB)
[LTBR]   [DB] 93행 저장 완료
[PROGRESS] [ 417/500] ( 83.4%)  >>  ACRS
[ACRS]   45분기 | 2015-03-31 ~ 2026-03-31
[ACRS]   [SARIMA] 시작  (메모리: 1598.3 MB)
[메모리] forecast_sarima 실행 전: 1598.27 MB
[메모리] find_best_sarima_params 실행 전: 1598.27 MB
[메모리] find_best_sarima_params 실행 후: 1598.27 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.27 MB (변화: +0.00 MB)
[ACRS]   [SARIMA] 완료  첫값=1.31e+06 (메모리: 1598.3 MB)
[ACRS]   [ETS] 시작  (메모리: 1598.3 MB)
[메모리] forecast_ets 실행 전: 1598.27 MB
[메모리] forecast_ets 실행 후: 1598.27 MB (변화: +0.00 MB)
[ACRS]   [ETS] 완료  첫값=3.91e+06 (메모리: 1598.3 MB)
[ACRS]   [Prophet] 시작  (메모리: 1598.3 MB)

02:42:46 - cmdstanpy - INFO - Chain [1] start processing
02:42:46 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1598.27 MB
[메모리] forecast_prophet 실행 후: 1598.27 MB (변화: +0.00 MB)
[ACRS]   [Prophet] 완료  첫값=6.08e+06 (메모리: 1598.3 MB)
[ACRS]   [LSTM] 시작  (메모리: 1598.3 MB)
[메모리] forecast_lstm 실행 전: 1598.27 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1597.14 MB (변화: -1.13 MB)
[ACRS]   [LSTM] 완료  첫값=3.72e+06 (메모리: 1597.1 MB)
[ACRS]   [Theta] 시작  (메모리: 1597.1 MB)
[메모리] forecast_theta 실행 전: 1597.14 MB
[메모리] forecast_theta 실행 후: 1597.14 MB (변화: +0.00 MB)
[ACRS]   [Theta] 완료  첫값=3.47e+06 (메모리: 1597.1 MB)
[ACRS]   [DB] 93행 저장 완료
[PROGRESS] [ 418/500] ( 83.6%)  >>  LND
[LND]   45분기 | 2015-03-31 ~ 2026-03-31
[LND]   [SARIMA] 시작  (메모리: 1597.1 MB)
[메모리] forecast_sarima 실행 전: 1597.14 MB
[메모리] find_best_sarima_params 실행 전: 1597.14 MB
[메모리] find_best_sarima_params 실행 후: 1597.14 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1597.14 MB (변화: +0.00 MB)
[LND]   [SARIMA] 완료  첫값=3.54e+08 (메모리: 1597.1 MB)
[LND]   [ETS] 시작  (메모리: 1597.1 MB)
[메모리] forecast_ets 실행 전: 1597.14 MB
[메모리] forecast_ets 실행 후: 1597.14 MB (변화: +0.00 MB)
[LND]   [ETS] 완료  첫값=5.24e+08 (메모리: 1597.1 MB)
[LND]   [Prophet] 시작  (메모리: 1597.1 MB)

02:43:03 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1597.14 MB

02:43:03 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1597.14 MB (변화: +0.00 MB)
[LND]   [Prophet] 완료  첫값=3.52e+08 (메모리: 1597.1 MB)
[LND]   [LSTM] 시작  (메모리: 1597.1 MB)
[메모리] forecast_lstm 실행 전: 1597.14 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1595.66 MB (변화: -1.48 MB)
[LND]   [LSTM] 완료  첫값=3.90e+08 (메모리: 1595.7 MB)
[LND]   [Theta] 시작  (메모리: 1595.7 MB)
[메모리] forecast_theta 실행 전: 1595.66 MB
[메모리] forecast_theta 실행 후: 1595.66 MB (변화: +0.00 MB)
[LND]   [Theta] 완료  첫값=4.87e+08 (메모리: 1595.7 MB)
[LND]   [DB] 93행 저장 완료
[PROGRESS] [ 419/500] ( 83.8%)  >>  HELE
[HELE]   45분기 | 2015-03-31 ~ 2026-03-31
[HELE]   [SARIMA] 시작  (메모리: 1595.7 MB)
[메모리] forecast_sarima 실행 전: 1595.66 MB
[메모리] find_best_sarima_params 실행 전: 1595.66 MB
[메모리] find_best_sarima_params 실행 후: 1595.66 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1595.66 MB (변화: +0.00 MB)
[HELE]   [SARIMA] 완료  첫값=4.21e+08 (메모리: 1595.7 MB)
[HELE]   [ETS] 시작  (메모리: 1595.7 MB)
[메모리] forecast_ets 실행 전: 1595.66 MB
[메모리] forecast_ets 실행 후: 1595.66 MB (변화: +0.00 MB)
[HELE]   [ETS] 완료  첫값=4.47e+08 (메모리: 1595.7 MB)
[HELE]   [Prophet] 시작  (메모리: 1595.7 MB)

02:43:21 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1595.66 MB

02:43:22 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1595.66 MB (변화: +0.00 MB)
[HELE]   [Prophet] 완료  첫값=5.37e+08 (메모리: 1595.7 MB)
[HELE]   [LSTM] 시작  (메모리: 1595.7 MB)
[메모리] forecast_lstm 실행 전: 1595.66 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1596.67 MB (변화: +1.00 MB)
[HELE]   [LSTM] 완료  첫값=4.80e+08 (메모리: 1596.7 MB)
[HELE]   [Theta] 시작  (메모리: 1596.7 MB)
[메모리] forecast_theta 실행 전: 1596.67 MB
[메모리] forecast_theta 실행 후: 1596.67 MB (변화: +0.00 MB)
[HELE]   [Theta] 완료  첫값=4.50e+08 (메모리: 1596.7 MB)
[HELE]   [DB] 93행 저장 완료
[PROGRESS] [ 420/500] ( 84.0%)  >>  CLLS
[CLLS]   45분기 | 2015-03-31 ~ 2026-03-31
[CLLS]   [SARIMA] 시작  (메모리: 1596.7 MB)
[메모리] forecast_sarima 실행 전: 1596.67 MB
[메모리] find_best_sarima_params 실행 전: 1596.67 MB
[메모리] find_best_sarima_params 실행 후: 1596.67 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1596.67 MB (변화: +0.00 MB)
[CLLS]   [SARIMA] 완료  첫값=1.15e+07 (메모리: 1596.7 MB)
[CLLS]   [ETS] 시작  (메모리: 1596.7 MB)
[메모리] forecast_ets 실행 전: 1596.67 MB
[메모리] forecast_ets 실행 후: 1596.67 MB (변화: +0.00 MB)
[CLLS]   [ETS] 완료  첫값=2.72e+07 (메모리: 1596.7 MB)
[CLLS]   [Prophet] 시작  (메모리: 1596.7 MB)

02:43:42 - cmdstanpy - INFO - Chain [1] start processing
02:43:42 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1596.67 MB
[메모리] forecast_prophet 실행 후: 1596.70 MB (변화: +0.03 MB)
[CLLS]   [Prophet] 완료  첫값=1.46e+07 (메모리: 1596.7 MB)
[CLLS]   [LSTM] 시작  (메모리: 1596.7 MB)
[메모리] forecast_lstm 실행 전: 1596.70 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1596.70 MB (변화: +0.00 MB)
[CLLS]   [LSTM] 완료  첫값=1.43e+07 (메모리: 1596.7 MB)
[CLLS]   [Theta] 시작  (메모리: 1596.7 MB)
[메모리] forecast_theta 실행 전: 1596.70 MB
[메모리] forecast_theta 실행 후: 1596.70 MB (변화: +0.00 MB)
[CLLS]   [Theta] 완료  첫값=3.27e+07 (메모리: 1596.7 MB)
[CLLS]   [DB] 93행 저장 완료
[PROGRESS] [ 421/500] ( 84.2%)  >>  PLM
[PLM]   45분기 | 2015-03-31 ~ 2026-03-31
[PLM]   [SARIMA] 시작  (메모리: 1596.7 MB)
[메모리] forecast_sarima 실행 전: 1596.70 MB
[메모리] find_best_sarima_params 실행 전: 1596.70 MB
[메모리] find_best_sarima_params 실행 후: 1596.70 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1596.70 MB (변화: +0.00 MB)
[PLM]   [SARIMA] 완료  첫값=0.00e+00 (메모리: 1596.7 MB)
[PLM]   [ETS] 시작  (메모리: 1596.7 MB)
[메모리] forecast_ets 실행 전: 1596.70 MB
[메모리] forecast_ets 실행 후: 1596.70 MB (변화: +0.00 MB)
[PLM]   [ETS] 완료  첫값=0.00e+00 (메모리: 1596.7 MB)
[PLM]   [Prophet] 시작  (메모리: 1596.7 MB)
[메모리] forecast_prophet 실행 전: 1596.70 MB
[메모리] forecast_prophet 실행 후: 1596.71 MB (변화: +0.01 MB)
[PLM]   [Prophet] 완료  첫값=0.00e+00 (메모리: 1596.7 MB)
[PLM]   [LSTM] 시작  (메모리: 1596.7 MB)
[메모리] forecast_lstm 실행 전: 1596.71 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1596.77 MB (변화: +0.06 MB)
[PLM]   [LSTM] 완료  첫값=0.00e+00 (메모리: 1596.8 MB)
[PLM]   [Theta] 시작  (메모리: 1596.8 MB)
[메모리] forecast_theta 실행 전: 1596.77 MB
[메모리] forecast_theta 실행 후: 1596.77 MB (변화: +0.00 MB)
[PLM]   [Theta] 완료  첫값=0.00e+00 (메모리: 1596.8 MB)
[PLM]   [DB] 93행 저장 완료
[PROGRESS] [ 422/500] ( 84.4%)  >>  WNC
[WNC]   45분기 | 2015-03-31 ~ 2026-03-31
[WNC]   [SARIMA] 시작  (메모리: 1596.8 MB)
[메모리] forecast_sarima 실행 전: 1596.77 MB
[메모리] find_best_sarima_params 실행 전: 1596.77 MB
[메모리] find_best_sarima_params 실행 후: 1596.77 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1596.77 MB (변화: +0.00 MB)
[WNC]   [SARIMA] 완료  첫값=4.23e+08 (메모리: 1596.8 MB)
[WNC]   [ETS] 시작  (메모리: 1596.8 MB)
[메모리] forecast_ets 실행 전: 1596.77 MB
[메모리] forecast_ets 실행 후: 1596.77 MB (변화: +0.00 MB)
[WNC]   [ETS] 완료  첫값=3.62e+08 (메모리: 1596.8 MB)
[WNC]   [Prophet] 시작  (메모리: 1596.8 MB)

02:44:26 - cmdstanpy - INFO - Chain [1] start processing
02:44:26 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1596.77 MB
[메모리] forecast_prophet 실행 후: 1596.77 MB (변화: +0.00 MB)
[WNC]   [Prophet] 완료  첫값=4.90e+08 (메모리: 1596.8 MB)
[WNC]   [LSTM] 시작  (메모리: 1596.8 MB)
[메모리] forecast_lstm 실행 전: 1596.77 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1596.77 MB (변화: +0.00 MB)
[WNC]   [LSTM] 완료  첫값=4.65e+08 (메모리: 1596.8 MB)
[WNC]   [Theta] 시작  (메모리: 1596.8 MB)
[메모리] forecast_theta 실행 전: 1596.77 MB
[메모리] forecast_theta 실행 후: 1596.77 MB (변화: +0.00 MB)
[WNC]   [Theta] 완료  첫값=3.22e+08 (메모리: 1596.8 MB)
[WNC]   [DB] 93행 저장 완료
[PROGRESS] [ 423/500] ( 84.6%)  >>  USNA
[USNA]   44분기 | 2015-06-30 ~ 2026-03-31
[USNA]   [SARIMA] 시작  (메모리: 1596.8 MB)
[메모리] forecast_sarima 실행 전: 1596.77 MB
[메모리] find_best_sarima_params 실행 전: 1596.77 MB
[메모리] find_best_sarima_params 실행 후: 1596.77 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1596.77 MB (변화: +0.00 MB)
[USNA]   [SARIMA] 완료  첫값=2.14e+08 (메모리: 1596.8 MB)
[USNA]   [ETS] 시작  (메모리: 1596.8 MB)
[메모리] forecast_ets 실행 전: 1596.77 MB
[메모리] forecast_ets 실행 후: 1596.77 MB (변화: +0.00 MB)
[USNA]   [ETS] 완료  첫값=2.07e+08 (메모리: 1596.8 MB)
[USNA]   [Prophet] 시작  (메모리: 1596.8 MB)

02:44:51 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1596.77 MB

02:44:51 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1596.80 MB (변화: +0.02 MB)
[USNA]   [Prophet] 완료  첫값=2.08e+08 (메모리: 1596.8 MB)
[USNA]   [LSTM] 시작  (메모리: 1596.8 MB)
[메모리] forecast_lstm 실행 전: 1596.80 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1596.82 MB (변화: +0.02 MB)
[USNA]   [LSTM] 완료  첫값=2.35e+08 (메모리: 1596.8 MB)
[USNA]   [Theta] 시작  (메모리: 1596.8 MB)
[메모리] forecast_theta 실행 전: 1596.82 MB
[메모리] forecast_theta 실행 후: 1596.82 MB (변화: +0.00 MB)
[USNA]   [Theta] 완료  첫값=2.13e+08 (메모리: 1596.8 MB)
[USNA]   [DB] 92행 저장 완료
[PROGRESS] [ 424/500] ( 84.8%)  >>  JACK
[JACK]   45분기 | 2015-03-31 ~ 2026-03-31
[JACK]   [SARIMA] 시작  (메모리: 1596.8 MB)
[메모리] forecast_sarima 실행 전: 1596.82 MB
[메모리] find_best_sarima_params 실행 전: 1596.82 MB
[메모리] find_best_sarima_params 실행 후: 1596.82 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1596.82 MB (변화: +0.00 MB)
[JACK]   [SARIMA] 완료  첫값=2.58e+08 (메모리: 1596.8 MB)
[JACK]   [ETS] 시작  (메모리: 1596.8 MB)
[메모리] forecast_ets 실행 전: 1596.82 MB
[메모리] forecast_ets 실행 후: 1596.82 MB (변화: +0.00 MB)
[JACK]   [ETS] 완료  첫값=3.19e+08 (메모리: 1596.8 MB)
[JACK]   [Prophet] 시작  (메모리: 1596.8 MB)

02:45:05 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1596.82 MB

02:45:06 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1596.82 MB (변화: +0.00 MB)
[JACK]   [Prophet] 완료  첫값=3.73e+08 (메모리: 1596.8 MB)
[JACK]   [LSTM] 시작  (메모리: 1596.8 MB)
[메모리] forecast_lstm 실행 전: 1596.82 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1596.77 MB (변화: -0.05 MB)
[JACK]   [LSTM] 완료  첫값=3.45e+08 (메모리: 1596.8 MB)
[JACK]   [Theta] 시작  (메모리: 1596.8 MB)
[메모리] forecast_theta 실행 전: 1596.77 MB
[메모리] forecast_theta 실행 후: 1596.77 MB (변화: +0.00 MB)
[JACK]   [Theta] 완료  첫값=3.09e+08 (메모리: 1596.8 MB)
[JACK]   [DB] 93행 저장 완료
[PROGRESS] [ 425/500] ( 85.0%)  >>  ELVA
[ELVA]   45분기 | 2015-03-31 ~ 2026-03-31
[ELVA]   [SARIMA] 시작  (메모리: 1596.8 MB)
[메모리] forecast_sarima 실행 전: 1596.77 MB
[메모리] find_best_sarima_params 실행 전: 1596.77 MB
[메모리] find_best_sarima_params 실행 후: 1596.77 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1596.77 MB (변화: +0.00 MB)
[ELVA]   [SARIMA] 완료  첫값=2.96e+07 (메모리: 1596.8 MB)
[ELVA]   [ETS] 시작  (메모리: 1596.8 MB)
[메모리] forecast_ets 실행 전: 1596.77 MB
[메모리] forecast_ets 실행 후: 1596.77 MB (변화: +0.00 MB)
[ELVA]   [ETS] 완료  첫값=2.30e+07 (메모리: 1596.8 MB)
[ELVA]   [Prophet] 시작  (메모리: 1596.8 MB)

02:45:22 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1596.77 MB

02:45:22 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1596.79 MB (변화: +0.02 MB)
[ELVA]   [Prophet] 완료  첫값=1.39e+07 (메모리: 1596.8 MB)
[ELVA]   [LSTM] 시작  (메모리: 1596.8 MB)
[메모리] forecast_lstm 실행 전: 1596.79 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1596.77 MB (변화: -0.02 MB)
[ELVA]   [LSTM] 완료  첫값=2.27e+07 (메모리: 1596.8 MB)
[ELVA]   [Theta] 시작  (메모리: 1596.8 MB)
[메모리] forecast_theta 실행 전: 1596.77 MB
[메모리] forecast_theta 실행 후: 1596.77 MB (변화: +0.00 MB)
[ELVA]   [Theta] 완료  첫값=1.85e+07 (메모리: 1596.8 MB)
[ELVA]   [DB] 93행 저장 완료
[PROGRESS] [ 426/500] ( 85.2%)  >>  SMLP
[SMLP]   45분기 | 2015-03-31 ~ 2026-03-31
[SMLP]   [SARIMA] 시작  (메모리: 1596.8 MB)
[메모리] forecast_sarima 실행 전: 1596.77 MB
[메모리] find_best_sarima_params 실행 전: 1596.77 MB
[메모리] find_best_sarima_params 실행 후: 1596.77 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1596.77 MB (변화: +0.00 MB)
[SMLP]   [SARIMA] 완료  첫값=1.19e+08 (메모리: 1596.8 MB)
[SMLP]   [ETS] 시작  (메모리: 1596.8 MB)
[메모리] forecast_ets 실행 전: 1596.77 MB
[메모리] forecast_ets 실행 후: 1596.77 MB (변화: +0.00 MB)
[SMLP]   [ETS] 완료  첫값=1.12e+08 (메모리: 1596.8 MB)
[SMLP]   [Prophet] 시작  (메모리: 1596.8 MB)

02:45:43 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1596.77 MB

02:45:43 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1596.77 MB (변화: +0.00 MB)
[SMLP]   [Prophet] 완료  첫값=1.15e+08 (메모리: 1596.8 MB)
[SMLP]   [LSTM] 시작  (메모리: 1596.8 MB)
[메모리] forecast_lstm 실행 전: 1596.77 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1596.79 MB (변화: +0.01 MB)
[SMLP]   [LSTM] 완료  첫값=1.11e+08 (메모리: 1596.8 MB)
[SMLP]   [Theta] 시작  (메모리: 1596.8 MB)
[메모리] forecast_theta 실행 전: 1596.79 MB
[메모리] forecast_theta 실행 후: 1596.79 MB (변화: +0.00 MB)
[SMLP]   [Theta] 완료  첫값=1.19e+08 (메모리: 1596.8 MB)
[SMLP]   [DB] 93행 저장 완료
[PROGRESS] [ 427/500] ( 85.4%)  >>  SLP
[SLP]   45분기 | 2015-03-31 ~ 2026-03-31
[SLP]   [SARIMA] 시작  (메모리: 1596.8 MB)
[메모리] forecast_sarima 실행 전: 1596.79 MB
[메모리] find_best_sarima_params 실행 전: 1596.79 MB
[메모리] find_best_sarima_params 실행 후: 1596.79 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1596.79 MB (변화: +0.00 MB)
[SLP]   [SARIMA] 완료  첫값=1.72e+07 (메모리: 1596.8 MB)
[SLP]   [ETS] 시작  (메모리: 1596.8 MB)
[메모리] forecast_ets 실행 전: 1596.79 MB
[메모리] forecast_ets 실행 후: 1596.79 MB (변화: +0.00 MB)
[SLP]   [ETS] 완료  첫값=2.09e+07 (메모리: 1596.8 MB)
[SLP]   [Prophet] 시작  (메모리: 1596.8 MB)

02:46:03 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1596.79 MB

02:46:03 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1596.79 MB (변화: +0.00 MB)
[SLP]   [Prophet] 완료  첫값=2.00e+07 (메모리: 1596.8 MB)
[SLP]   [LSTM] 시작  (메모리: 1596.8 MB)
[메모리] forecast_lstm 실행 전: 1596.79 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1596.80 MB (변화: +0.00 MB)
[SLP]   [LSTM] 완료  첫값=2.22e+07 (메모리: 1596.8 MB)
[SLP]   [Theta] 시작  (메모리: 1596.8 MB)
[메모리] forecast_theta 실행 전: 1596.80 MB
[메모리] forecast_theta 실행 후: 1596.80 MB (변화: +0.00 MB)
[SLP]   [Theta] 완료  첫값=2.04e+07 (메모리: 1596.8 MB)
[SLP]   [DB] 93행 저장 완료
[PROGRESS] [ 428/500] ( 85.6%)  >>  LXFR
[LXFR]   45분기 | 2015-03-31 ~ 2026-03-31
[LXFR]   [SARIMA] 시작  (메모리: 1596.8 MB)
[메모리] forecast_sarima 실행 전: 1596.80 MB
[메모리] find_best_sarima_params 실행 전: 1596.80 MB
[메모리] find_best_sarima_params 실행 후: 1596.80 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1596.80 MB (변화: +0.00 MB)
[LXFR]   [SARIMA] 완료  첫값=9.29e+07 (메모리: 1596.8 MB)
[LXFR]   [ETS] 시작  (메모리: 1596.8 MB)
[메모리] forecast_ets 실행 전: 1596.80 MB
[메모리] forecast_ets 실행 후: 1596.80 MB (변화: +0.00 MB)
[LXFR]   [ETS] 완료  첫값=9.71e+07 (메모리: 1596.8 MB)
[LXFR]   [Prophet] 시작  (메모리: 1596.8 MB)

02:46:25 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1596.80 MB

02:46:25 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1596.80 MB (변화: +0.00 MB)
[LXFR]   [Prophet] 완료  첫값=9.32e+07 (메모리: 1596.8 MB)
[LXFR]   [LSTM] 시작  (메모리: 1596.8 MB)
[메모리] forecast_lstm 실행 전: 1596.80 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1596.78 MB (변화: -0.03 MB)
[LXFR]   [LSTM] 완료  첫값=9.54e+07 (메모리: 1596.8 MB)
[LXFR]   [Theta] 시작  (메모리: 1596.8 MB)
[메모리] forecast_theta 실행 전: 1596.78 MB
[메모리] forecast_theta 실행 후: 1596.78 MB (변화: +0.00 MB)
[LXFR]   [Theta] 완료  첫값=9.31e+07 (메모리: 1596.8 MB)
[LXFR]   [DB] 93행 저장 완료
[PROGRESS] [ 429/500] ( 85.8%)  >>  TROO
[TROO]   44분기 | 2015-06-30 ~ 2026-03-31
[TROO]   [SARIMA] 시작  (메모리: 1596.8 MB)
[메모리] forecast_sarima 실행 전: 1596.78 MB
[메모리] find_best_sarima_params 실행 전: 1596.78 MB
[메모리] find_best_sarima_params 실행 후: 1596.78 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1596.78 MB (변화: +0.00 MB)
[TROO]   [SARIMA] 완료  첫값=9.29e+06 (메모리: 1596.8 MB)
[TROO]   [ETS] 시작  (메모리: 1596.8 MB)
[메모리] forecast_ets 실행 전: 1596.78 MB
[메모리] forecast_ets 실행 후: 1596.78 MB (변화: +0.00 MB)
[TROO]   [ETS] 완료  첫값=8.26e+06 (메모리: 1596.8 MB)
[TROO]   [Prophet] 시작  (메모리: 1596.8 MB)

02:46:46 - cmdstanpy - INFO - Chain [1] start processing
02:46:46 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1596.78 MB
[메모리] forecast_prophet 실행 후: 1597.18 MB (변화: +0.40 MB)
[TROO]   [Prophet] 완료  첫값=4.66e+06 (메모리: 1597.2 MB)
[TROO]   [LSTM] 시작  (메모리: 1597.2 MB)
[메모리] forecast_lstm 실행 전: 1597.18 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1597.19 MB (변화: +0.01 MB)
[TROO]   [LSTM] 완료  첫값=1.08e+07 (메모리: 1597.2 MB)
[TROO]   [Theta] 시작  (메모리: 1597.2 MB)
[메모리] forecast_theta 실행 전: 1597.19 MB
[메모리] forecast_theta 실행 후: 1597.19 MB (변화: +0.00 MB)
[TROO]   [Theta] 완료  첫값=7.90e+06 (메모리: 1597.2 MB)
[TROO]   [DB] 92행 저장 완료
[PROGRESS] [ 430/500] ( 86.0%)  >>  CINR
[CINR]   45분기 | 2015-03-31 ~ 2026-03-31
[CINR]   [SARIMA] 시작  (메모리: 1597.2 MB)
[메모리] forecast_sarima 실행 전: 1597.19 MB
[메모리] find_best_sarima_params 실행 전: 1597.19 MB
[메모리] find_best_sarima_params 실행 후: 1597.19 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1597.19 MB (변화: +0.00 MB)
[CINR]   [SARIMA] 완료  첫값=1.57e+08 (메모리: 1597.2 MB)
[CINR]   [ETS] 시작  (메모리: 1597.2 MB)
[메모리] forecast_ets 실행 전: 1597.19 MB
[메모리] forecast_ets 실행 후: 1597.19 MB (변화: +0.00 MB)
[CINR]   [ETS] 완료  첫값=1.48e+08 (메모리: 1597.2 MB)
[CINR]   [Prophet] 시작  (메모리: 1597.2 MB)

02:47:07 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1597.19 MB

02:47:07 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1597.20 MB (변화: +0.01 MB)
[CINR]   [Prophet] 완료  첫값=1.60e+08 (메모리: 1597.2 MB)
[CINR]   [LSTM] 시작  (메모리: 1597.2 MB)
[메모리] forecast_lstm 실행 전: 1597.20 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1597.41 MB (변화: +0.21 MB)
[CINR]   [LSTM] 완료  첫값=1.52e+08 (메모리: 1597.4 MB)
[CINR]   [Theta] 시작  (메모리: 1597.4 MB)
[메모리] forecast_theta 실행 전: 1597.41 MB
[메모리] forecast_theta 실행 후: 1597.41 MB (변화: +0.00 MB)
[CINR]   [Theta] 완료  첫값=1.46e+08 (메모리: 1597.4 MB)
[CINR]   [DB] 93행 저장 완료
[PROGRESS] [ 431/500] ( 86.2%)  >>  GTN
[GTN]   45분기 | 2015-03-31 ~ 2026-03-31
[GTN]   [SARIMA] 시작  (메모리: 1597.4 MB)
[메모리] forecast_sarima 실행 전: 1597.41 MB
[메모리] find_best_sarima_params 실행 전: 1597.41 MB
[메모리] find_best_sarima_params 실행 후: 1597.41 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1597.41 MB (변화: +0.00 MB)
[GTN]   [SARIMA] 완료  첫값=7.79e+08 (메모리: 1597.4 MB)
[GTN]   [ETS] 시작  (메모리: 1597.4 MB)
[메모리] forecast_ets 실행 전: 1597.41 MB
[메모리] forecast_ets 실행 후: 1597.41 MB (변화: +0.00 MB)
[GTN]   [ETS] 완료  첫값=7.68e+08 (메모리: 1597.4 MB)
[GTN]   [Prophet] 시작  (메모리: 1597.4 MB)

02:47:25 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1597.41 MB

02:47:25 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1596.76 MB (변화: -0.65 MB)
[GTN]   [Prophet] 완료  첫값=1.01e+09 (메모리: 1596.8 MB)
[GTN]   [LSTM] 시작  (메모리: 1596.8 MB)
[메모리] forecast_lstm 실행 전: 1596.76 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1596.74 MB (변화: -0.02 MB)
[GTN]   [LSTM] 완료  첫값=9.47e+08 (메모리: 1596.7 MB)
[GTN]   [Theta] 시작  (메모리: 1596.7 MB)
[메모리] forecast_theta 실행 전: 1596.74 MB
[메모리] forecast_theta 실행 후: 1596.74 MB (변화: +0.00 MB)
[GTN]   [Theta] 완료  첫값=7.53e+08 (메모리: 1596.7 MB)
[GTN]   [DB] 93행 저장 완료
[PROGRESS] [ 432/500] ( 86.4%)  >>  CECE
[CECE]   45분기 | 2015-03-31 ~ 2026-03-31
[CECE]   [SARIMA] 시작  (메모리: 1596.7 MB)
[메모리] forecast_sarima 실행 전: 1596.74 MB
[메모리] find_best_sarima_params 실행 전: 1596.74 MB
[메모리] find_best_sarima_params 실행 후: 1596.74 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1596.74 MB (변화: +0.00 MB)
[CECE]   [SARIMA] 완료  첫값=2.02e+08 (메모리: 1596.7 MB)
[CECE]   [ETS] 시작  (메모리: 1596.7 MB)
[메모리] forecast_ets 실행 전: 1596.74 MB
[메모리] forecast_ets 실행 후: 1596.75 MB (변화: +0.00 MB)
[CECE]   [ETS] 완료  첫값=2.05e+08 (메모리: 1596.7 MB)
[CECE]   [Prophet] 시작  (메모리: 1596.7 MB)

02:47:45 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1596.75 MB

02:47:45 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1596.75 MB (변화: +0.00 MB)
[CECE]   [Prophet] 완료  첫값=1.92e+08 (메모리: 1596.8 MB)
[CECE]   [LSTM] 시작  (메모리: 1596.8 MB)
[메모리] forecast_lstm 실행 전: 1596.75 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1596.77 MB (변화: +0.02 MB)
[CECE]   [LSTM] 완료  첫값=2.32e+08 (메모리: 1596.8 MB)
[CECE]   [Theta] 시작  (메모리: 1596.8 MB)
[메모리] forecast_theta 실행 전: 1596.77 MB
[메모리] forecast_theta 실행 후: 1596.77 MB (변화: +0.00 MB)
[CECE]   [Theta] 완료  첫값=2.03e+08 (메모리: 1596.8 MB)
[CECE]   [DB] 93행 저장 완료
[PROGRESS] [ 433/500] ( 86.6%)  >>  WILC
[WILC]   45분기 | 2015-03-31 ~ 2026-03-31
[WILC]   [SARIMA] 시작  (메모리: 1596.8 MB)
[메모리] forecast_sarima 실행 전: 1596.77 MB
[메모리] find_best_sarima_params 실행 전: 1596.77 MB
[메모리] find_best_sarima_params 실행 후: 1596.77 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1596.77 MB (변화: +0.00 MB)
[WILC]   [SARIMA] 완료  첫값=1.62e+08 (메모리: 1596.8 MB)
[WILC]   [ETS] 시작  (메모리: 1596.8 MB)
[메모리] forecast_ets 실행 전: 1596.77 MB
[메모리] forecast_ets 실행 후: 1596.78 MB (변화: +0.01 MB)
[WILC]   [ETS] 완료  첫값=1.61e+08 (메모리: 1596.8 MB)
[WILC]   [Prophet] 시작  (메모리: 1596.8 MB)

02:48:06 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1596.78 MB

02:48:06 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1597.59 MB (변화: +0.82 MB)
[WILC]   [Prophet] 완료  첫값=1.57e+08 (메모리: 1597.6 MB)
[WILC]   [LSTM] 시작  (메모리: 1597.6 MB)
[메모리] forecast_lstm 실행 전: 1597.59 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1597.59 MB (변화: -0.00 MB)
[WILC]   [LSTM] 완료  첫값=1.64e+08 (메모리: 1597.6 MB)
[WILC]   [Theta] 시작  (메모리: 1597.6 MB)
[메모리] forecast_theta 실행 전: 1597.59 MB
[메모리] forecast_theta 실행 후: 1597.59 MB (변화: +0.00 MB)
[WILC]   [Theta] 완료  첫값=1.51e+08 (메모리: 1597.6 MB)
[WILC]   [DB] 93행 저장 완료
[PROGRESS] [ 434/500] ( 86.8%)  >>  CO
[CO]   45분기 | 2015-03-31 ~ 2026-03-31
[CO]   [SARIMA] 시작  (메모리: 1597.6 MB)
[메모리] forecast_sarima 실행 전: 1597.59 MB
[메모리] find_best_sarima_params 실행 전: 1597.59 MB
[메모리] find_best_sarima_params 실행 후: 1597.59 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1597.59 MB (변화: +0.00 MB)
[CO]   [SARIMA] 완료  첫값=3.01e+08 (메모리: 1597.6 MB)
[CO]   [ETS] 시작  (메모리: 1597.6 MB)
[메모리] forecast_ets 실행 전: 1597.59 MB
[메모리] forecast_ets 실행 후: 1597.59 MB (변화: +0.00 MB)
[CO]   [ETS] 완료  첫값=3.02e+08 (메모리: 1597.6 MB)
[CO]   [Prophet] 시작  (메모리: 1597.6 MB)

02:48:28 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1597.59 MB

02:48:28 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1597.60 MB (변화: +0.01 MB)
[CO]   [Prophet] 완료  첫값=2.99e+08 (메모리: 1597.6 MB)
[CO]   [LSTM] 시작  (메모리: 1597.6 MB)
[메모리] forecast_lstm 실행 전: 1597.60 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1597.58 MB (변화: -0.02 MB)
[CO]   [LSTM] 완료  첫값=2.99e+08 (메모리: 1597.6 MB)
[CO]   [Theta] 시작  (메모리: 1597.6 MB)
[메모리] forecast_theta 실행 전: 1597.58 MB
[메모리] forecast_theta 실행 후: 1597.58 MB (변화: +0.00 MB)
[CO]   [Theta] 완료  첫값=3.03e+08 (메모리: 1597.6 MB)
[CO]   [DB] 93행 저장 완료
[PROGRESS] [ 435/500] ( 87.0%)  >>  TRX
[TRX]   45분기 | 2015-03-31 ~ 2026-03-31
[TRX]   [SARIMA] 시작  (메모리: 1597.6 MB)
[메모리] forecast_sarima 실행 전: 1597.58 MB
[메모리] find_best_sarima_params 실행 전: 1597.58 MB
[메모리] find_best_sarima_params 실행 후: 1597.58 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1597.58 MB (변화: +0.00 MB)
[TRX]   [SARIMA] 완료  첫값=4.15e+07 (메모리: 1597.6 MB)
[TRX]   [ETS] 시작  (메모리: 1597.6 MB)
[메모리] forecast_ets 실행 전: 1597.58 MB
[메모리] forecast_ets 실행 후: 1597.58 MB (변화: +0.00 MB)
[TRX]   [ETS] 완료  첫값=3.67e+07 (메모리: 1597.6 MB)
[TRX]   [Prophet] 시작  (메모리: 1597.6 MB)

02:48:51 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1597.58 MB

02:48:51 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1597.98 MB (변화: +0.41 MB)
[TRX]   [Prophet] 완료  첫값=1.98e+07 (메모리: 1598.0 MB)
[TRX]   [LSTM] 시작  (메모리: 1598.0 MB)
[메모리] forecast_lstm 실행 전: 1597.98 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.01 MB (변화: +0.03 MB)
[TRX]   [LSTM] 완료  첫값=4.05e+07 (메모리: 1598.0 MB)
[TRX]   [Theta] 시작  (메모리: 1598.0 MB)
[메모리] forecast_theta 실행 전: 1598.01 MB
[메모리] forecast_theta 실행 후: 1598.01 MB (변화: +0.00 MB)
[TRX]   [Theta] 완료  첫값=3.54e+07 (메모리: 1598.0 MB)
[TRX]   [DB] 93행 저장 완료
[PROGRESS] [ 436/500] ( 87.2%)  >>  QUOT
[QUOT]   45분기 | 2015-03-31 ~ 2026-03-31
[QUOT]   [SARIMA] 시작  (메모리: 1598.0 MB)
[메모리] forecast_sarima 실행 전: 1598.01 MB
[메모리] find_best_sarima_params 실행 전: 1598.01 MB
[메모리] find_best_sarima_params 실행 후: 1598.01 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.01 MB (변화: +0.00 MB)
[QUOT]   [SARIMA] 완료  첫값=6.57e+07 (메모리: 1598.0 MB)
[QUOT]   [ETS] 시작  (메모리: 1598.0 MB)
[메모리] forecast_ets 실행 전: 1598.01 MB
[메모리] forecast_ets 실행 후: 1598.02 MB (변화: +0.00 MB)
[QUOT]   [ETS] 완료  첫값=6.59e+07 (메모리: 1598.0 MB)
[QUOT]   [Prophet] 시작  (메모리: 1598.0 MB)

02:49:12 - cmdstanpy - INFO - Chain [1] start processing
02:49:12 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1598.02 MB
[메모리] forecast_prophet 실행 후: 1598.02 MB (변화: +0.00 MB)
[QUOT]   [Prophet] 완료  첫값=8.04e+07 (메모리: 1598.0 MB)
[QUOT]   [LSTM] 시작  (메모리: 1598.0 MB)
[메모리] forecast_lstm 실행 전: 1598.02 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.00 MB (변화: -0.02 MB)
[QUOT]   [LSTM] 완료  첫값=7.18e+07 (메모리: 1598.0 MB)
[QUOT]   [Theta] 시작  (메모리: 1598.0 MB)
[메모리] forecast_theta 실행 전: 1598.00 MB
[메모리] forecast_theta 실행 후: 1598.00 MB (변화: +0.00 MB)
[QUOT]   [Theta] 완료  첫값=6.57e+07 (메모리: 1598.0 MB)
[QUOT]   [DB] 93행 저장 완료
[PROGRESS] [ 437/500] ( 87.4%)  >>  SSP
[SSP]   45분기 | 2015-03-31 ~ 2026-03-31
[SSP]   [SARIMA] 시작  (메모리: 1598.0 MB)
[메모리] forecast_sarima 실행 전: 1598.00 MB
[메모리] find_best_sarima_params 실행 전: 1598.00 MB
[메모리] find_best_sarima_params 실행 후: 1598.00 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.00 MB (변화: +0.00 MB)
[SSP]   [SARIMA] 완료  첫값=5.42e+08 (메모리: 1598.0 MB)
[SSP]   [ETS] 시작  (메모리: 1598.0 MB)
[메모리] forecast_ets 실행 전: 1598.00 MB
[메모리] forecast_ets 실행 후: 1598.00 MB (변화: +0.00 MB)
[SSP]   [ETS] 완료  첫값=5.38e+08 (메모리: 1598.0 MB)
[SSP]   [Prophet] 시작  (메모리: 1598.0 MB)
[메모리] forecast_prophet 실행 전: 1598.00 MB

02:49:37 - cmdstanpy - INFO - Chain [1] start processing
02:49:37 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1598.00 MB (변화: +0.00 MB)
[SSP]   [Prophet] 완료  첫값=6.86e+08 (메모리: 1598.0 MB)
[SSP]   [LSTM] 시작  (메모리: 1598.0 MB)
[메모리] forecast_lstm 실행 전: 1598.00 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.01 MB (변화: +0.01 MB)
[SSP]   [LSTM] 완료  첫값=6.29e+08 (메모리: 1598.0 MB)
[SSP]   [Theta] 시작  (메모리: 1598.0 MB)
[메모리] forecast_theta 실행 전: 1598.01 MB
[메모리] forecast_theta 실행 후: 1598.01 MB (변화: +0.00 MB)
[SSP]   [Theta] 완료  첫값=5.42e+08 (메모리: 1598.0 MB)
[SSP]   [DB] 93행 저장 완료
[PROGRESS] [ 438/500] ( 87.6%)  >>  NBY
[NBY]   45분기 | 2015-03-31 ~ 2026-03-31
[NBY]   [SARIMA] 시작  (메모리: 1598.0 MB)
[메모리] forecast_sarima 실행 전: 1598.01 MB
[메모리] find_best_sarima_params 실행 전: 1598.01 MB
[메모리] find_best_sarima_params 실행 후: 1598.01 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.01 MB (변화: +0.00 MB)
[NBY]   [SARIMA] 완료  첫값=8.21e+05 (메모리: 1598.0 MB)
[NBY]   [ETS] 시작  (메모리: 1598.0 MB)
[메모리] forecast_ets 실행 전: 1598.01 MB
[메모리] forecast_ets 실행 후: 1598.02 MB (변화: +0.01 MB)
[NBY]   [ETS] 완료  첫값=6.77e+05 (메모리: 1598.0 MB)
[NBY]   [Prophet] 시작  (메모리: 1598.0 MB)

02:49:55 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1598.02 MB

02:49:55 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1598.02 MB (변화: +0.00 MB)
[NBY]   [Prophet] 완료  첫값=1.91e+06 (메모리: 1598.0 MB)
[NBY]   [LSTM] 시작  (메모리: 1598.0 MB)
[메모리] forecast_lstm 실행 전: 1598.02 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.04 MB (변화: +0.02 MB)
[NBY]   [LSTM] 완료  첫값=1.68e+06 (메모리: 1598.0 MB)
[NBY]   [Theta] 시작  (메모리: 1598.0 MB)
[메모리] forecast_theta 실행 전: 1598.04 MB
[메모리] forecast_theta 실행 후: 1598.04 MB (변화: +0.00 MB)
[NBY]   [Theta] 완료  첫값=4.96e+05 (메모리: 1598.0 MB)
[NBY]   [DB] 93행 저장 완료
[PROGRESS] [ 439/500] ( 87.8%)  >>  TTGT
[TTGT]   45분기 | 2015-03-31 ~ 2026-03-31
[TTGT]   [SARIMA] 시작  (메모리: 1598.0 MB)
[메모리] forecast_sarima 실행 전: 1598.04 MB
[메모리] find_best_sarima_params 실행 전: 1598.04 MB
[메모리] find_best_sarima_params 실행 후: 1598.04 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.04 MB (변화: +0.00 MB)
[TTGT]   [SARIMA] 완료  첫값=4.93e+07 (메모리: 1598.0 MB)
[TTGT]   [ETS] 시작  (메모리: 1598.0 MB)
[메모리] forecast_ets 실행 전: 1598.04 MB
[메모리] forecast_ets 실행 후: 1598.04 MB (변화: +0.00 MB)
[TTGT]   [ETS] 완료  첫값=3.14e+05 (메모리: 1598.0 MB)
[TTGT]   [Prophet] 시작  (메모리: 1598.0 MB)

02:50:18 - cmdstanpy - INFO - Chain [1] start processing
02:50:18 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1598.04 MB
[메모리] forecast_prophet 실행 후: 1598.04 MB (변화: +0.00 MB)
[TTGT]   [Prophet] 완료  첫값=6.77e+07 (메모리: 1598.0 MB)
[TTGT]   [LSTM] 시작  (메모리: 1598.0 MB)
[메모리] forecast_lstm 실행 전: 1598.04 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.04 MB (변화: -0.00 MB)
[TTGT]   [LSTM] 완료  첫값=5.16e+07 (메모리: 1598.0 MB)
[TTGT]   [Theta] 시작  (메모리: 1598.0 MB)
[메모리] forecast_theta 실행 전: 1598.04 MB
[메모리] forecast_theta 실행 후: 1598.04 MB (변화: +0.00 MB)
[TTGT]   [Theta] 완료  첫값=2.72e+05 (메모리: 1598.0 MB)
[TTGT]   [DB] 93행 저장 완료
[PROGRESS] [ 440/500] ( 88.0%)  >>  RCKT
[RCKT]   45분기 | 2015-03-31 ~ 2026-03-31
[RCKT]   [SARIMA] 시작  (메모리: 1598.0 MB)
[메모리] forecast_sarima 실행 전: 1598.04 MB
[메모리] find_best_sarima_params 실행 전: 1598.04 MB
[메모리] find_best_sarima_params 실행 후: 1598.04 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.04 MB (변화: +0.00 MB)
[RCKT]   [SARIMA] 완료  첫값=0.00e+00 (메모리: 1598.0 MB)
[RCKT]   [ETS] 시작  (메모리: 1598.0 MB)
[메모리] forecast_ets 실행 전: 1598.04 MB
[메모리] forecast_ets 실행 후: 1598.04 MB (변화: +0.00 MB)
[RCKT]   [ETS] 완료  첫값=0.00e+00 (메모리: 1598.0 MB)
[RCKT]   [Prophet] 시작  (메모리: 1598.0 MB)
[메모리] forecast_prophet 실행 전: 1598.04 MB
[메모리] forecast_prophet 실행 후: 1598.04 MB (변화: +0.00 MB)
[RCKT]   [Prophet] 완료  첫값=0.00e+00 (메모리: 1598.0 MB)
[RCKT]   [LSTM] 시작  (메모리: 1598.0 MB)
[메모리] forecast_lstm 실행 전: 1598.04 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.04 MB (변화: +0.01 MB)
[RCKT]   [LSTM] 완료  첫값=0.00e+00 (메모리: 1598.0 MB)
[RCKT]   [Theta] 시작  (메모리: 1598.0 MB)
[메모리] forecast_theta 실행 전: 1598.04 MB
[메모리] forecast_theta 실행 후: 1598.04 MB (변화: +0.00 MB)
[RCKT]   [Theta] 완료  첫값=0.00e+00 (메모리: 1598.0 MB)
[RCKT]   [DB] 93행 저장 완료
[PROGRESS] [ 441/500] ( 88.2%)  >>  MTRX
[MTRX]   45분기 | 2015-03-31 ~ 2026-03-31
[MTRX]   [SARIMA] 시작  (메모리: 1598.0 MB)
[메모리] forecast_sarima 실행 전: 1598.04 MB
[메모리] find_best_sarima_params 실행 전: 1598.04 MB
[메모리] find_best_sarima_params 실행 후: 1598.04 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.04 MB (변화: +0.00 MB)
[MTRX]   [SARIMA] 완료  첫값=2.13e+08 (메모리: 1598.0 MB)
[MTRX]   [ETS] 시작  (메모리: 1598.0 MB)
[메모리] forecast_ets 실행 전: 1598.04 MB
[메모리] forecast_ets 실행 후: 1598.04 MB (변화: +0.00 MB)
[MTRX]   [ETS] 완료  첫값=2.33e+08 (메모리: 1598.0 MB)
[MTRX]   [Prophet] 시작  (메모리: 1598.0 MB)

02:50:57 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1598.04 MB

02:50:57 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1598.05 MB (변화: +0.00 MB)
[MTRX]   [Prophet] 완료  첫값=1.54e+08 (메모리: 1598.0 MB)
[MTRX]   [LSTM] 시작  (메모리: 1598.0 MB)
[메모리] forecast_lstm 실행 전: 1598.05 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.04 MB (변화: -0.00 MB)
[MTRX]   [LSTM] 완료  첫값=1.93e+08 (메모리: 1598.0 MB)
[MTRX]   [Theta] 시작  (메모리: 1598.0 MB)
[메모리] forecast_theta 실행 전: 1598.04 MB
[메모리] forecast_theta 실행 후: 1598.04 MB (변화: +0.00 MB)
[MTRX]   [Theta] 완료  첫값=2.32e+08 (메모리: 1598.0 MB)
[MTRX]   [DB] 93행 저장 완료
[PROGRESS] [ 442/500] ( 88.4%)  >>  DSKE
[DSKE]   43분기 | 2015-09-30 ~ 2026-03-31
[DSKE]   [SARIMA] 시작  (메모리: 1598.0 MB)
[메모리] forecast_sarima 실행 전: 1598.04 MB
[메모리] find_best_sarima_params 실행 전: 1598.04 MB
[메모리] find_best_sarima_params 실행 후: 1598.04 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.04 MB (변화: +0.00 MB)
[DSKE]   [SARIMA] 완료  첫값=3.54e+08 (메모리: 1598.0 MB)
[DSKE]   [ETS] 시작  (메모리: 1598.0 MB)
[메모리] forecast_ets 실행 전: 1598.04 MB
[메모리] forecast_ets 실행 후: 1598.05 MB (변화: +0.00 MB)
[DSKE]   [ETS] 완료  첫값=3.91e+08 (메모리: 1598.0 MB)
[DSKE]   [Prophet] 시작  (메모리: 1598.0 MB)

02:51:16 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1598.05 MB

02:51:16 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1598.07 MB (변화: +0.03 MB)
[DSKE]   [Prophet] 완료  첫값=4.43e+08 (메모리: 1598.1 MB)
[DSKE]   [LSTM] 시작  (메모리: 1598.1 MB)
[메모리] forecast_lstm 실행 전: 1598.07 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.14 MB (변화: +0.07 MB)
[DSKE]   [LSTM] 완료  첫값=3.78e+08 (메모리: 1598.1 MB)
[DSKE]   [Theta] 시작  (메모리: 1598.1 MB)
[메모리] forecast_theta 실행 전: 1598.14 MB
[메모리] forecast_theta 실행 후: 1598.14 MB (변화: +0.00 MB)
[DSKE]   [Theta] 완료  첫값=3.84e+08 (메모리: 1598.1 MB)
[DSKE]   [DB] 91행 저장 완료
[PROGRESS] [ 443/500] ( 88.6%)  >>  LSAK
[LSAK]   45분기 | 2015-03-31 ~ 2026-03-31
[LSAK]   [SARIMA] 시작  (메모리: 1598.1 MB)
[메모리] forecast_sarima 실행 전: 1598.14 MB
[메모리] find_best_sarima_params 실행 전: 1598.14 MB
[메모리] find_best_sarima_params 실행 후: 1598.14 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.14 MB (변화: +0.00 MB)
[LSAK]   [SARIMA] 완료  첫값=1.79e+08 (메모리: 1598.1 MB)
[LSAK]   [ETS] 시작  (메모리: 1598.1 MB)
[메모리] forecast_ets 실행 전: 1598.14 MB
[메모리] forecast_ets 실행 후: 1598.15 MB (변화: +0.00 MB)
[LSAK]   [ETS] 완료  첫값=1.99e+08 (메모리: 1598.1 MB)
[LSAK]   [Prophet] 시작  (메모리: 1598.1 MB)

02:51:36 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1598.15 MB

02:51:36 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1598.15 MB (변화: +0.00 MB)
[LSAK]   [Prophet] 완료  첫값=1.25e+08 (메모리: 1598.1 MB)
[LSAK]   [LSTM] 시작  (메모리: 1598.1 MB)
[메모리] forecast_lstm 실행 전: 1598.15 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.20 MB (변화: +0.05 MB)
[LSAK]   [LSTM] 완료  첫값=1.43e+08 (메모리: 1598.2 MB)
[LSAK]   [Theta] 시작  (메모리: 1598.2 MB)
[메모리] forecast_theta 실행 전: 1598.20 MB
[메모리] forecast_theta 실행 후: 1598.20 MB (변화: +0.00 MB)
[LSAK]   [Theta] 완료  첫값=2.00e+08 (메모리: 1598.2 MB)
[LSAK]   [DB] 93행 저장 완료
[PROGRESS] [ 444/500] ( 88.8%)  >>  KFS
[KFS]   45분기 | 2015-03-31 ~ 2026-03-31
[KFS]   [SARIMA] 시작  (메모리: 1598.2 MB)
[메모리] forecast_sarima 실행 전: 1598.20 MB
[메모리] find_best_sarima_params 실행 전: 1598.20 MB
[메모리] find_best_sarima_params 실행 후: 1598.20 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.20 MB (변화: +0.00 MB)
[KFS]   [SARIMA] 완료  첫값=3.79e+07 (메모리: 1598.2 MB)
[KFS]   [ETS] 시작  (메모리: 1598.2 MB)
[메모리] forecast_ets 실행 전: 1598.20 MB
[메모리] forecast_ets 실행 후: 1598.20 MB (변화: +0.00 MB)
[KFS]   [ETS] 완료  첫값=3.55e+07 (메모리: 1598.2 MB)
[KFS]   [Prophet] 시작  (메모리: 1598.2 MB)

02:51:55 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1598.20 MB

02:51:55 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1598.21 MB (변화: +0.01 MB)
[KFS]   [Prophet] 완료  첫값=2.24e+07 (메모리: 1598.2 MB)
[KFS]   [LSTM] 시작  (메모리: 1598.2 MB)
[메모리] forecast_lstm 실행 전: 1598.21 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.20 MB (변화: -0.01 MB)
[KFS]   [LSTM] 완료  첫값=2.63e+07 (메모리: 1598.2 MB)
[KFS]   [Theta] 시작  (메모리: 1598.2 MB)
[메모리] forecast_theta 실행 전: 1598.20 MB
[메모리] forecast_theta 실행 후: 1598.20 MB (변화: +0.00 MB)
[KFS]   [Theta] 완료  첫값=3.75e+07 (메모리: 1598.2 MB)
[KFS]   [DB] 93행 저장 완료
[PROGRESS] [ 445/500] ( 89.0%)  >>  CTGO
[CTGO]   45분기 | 2015-03-31 ~ 2026-03-31
[CTGO]   [SARIMA] 시작  (메모리: 1598.2 MB)
[메모리] forecast_sarima 실행 전: 1598.20 MB
[메모리] find_best_sarima_params 실행 전: 1598.20 MB
[메모리] find_best_sarima_params 실행 후: 1598.20 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.20 MB (변화: +0.00 MB)
[CTGO]   [SARIMA] 완료  첫값=-9.42e-321 (메모리: 1598.2 MB)
[CTGO]   [ETS] 시작  (메모리: 1598.2 MB)
[메모리] forecast_ets 실행 전: 1598.20 MB
[메모리] forecast_ets 실행 후: 1598.21 MB (변화: +0.01 MB)
[CTGO]   [ETS] 완료  첫값=-1.91e+10 (메모리: 1598.2 MB)
[CTGO]   [Prophet] 시작  (메모리: 1598.2 MB)

02:52:13 - cmdstanpy - INFO - Chain [1] start processing
02:52:13 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1598.21 MB
[메모리] forecast_prophet 실행 후: 1598.21 MB (변화: +0.01 MB)
[CTGO]   [Prophet] 완료  첫값=-2.10e+09 (메모리: 1598.2 MB)
[CTGO]   [LSTM] 시작  (메모리: 1598.2 MB)
[메모리] forecast_lstm 실행 전: 1598.21 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.18 MB (변화: -0.03 MB)
[CTGO]   [LSTM] 완료  첫값=-5.60e+10 (메모리: 1598.2 MB)
[CTGO]   [Theta] 시작  (메모리: 1598.2 MB)
[메모리] forecast_theta 실행 전: 1598.18 MB
[메모리] forecast_theta 실행 후: 1598.18 MB (변화: +0.00 MB)
[CTGO]   [Theta] 완료  첫값=-9.88e+07 (메모리: 1598.2 MB)
[CTGO]   [DB] 93행 저장 완료
[PROGRESS] [ 446/500] ( 89.2%)  >>  TITN
[TITN]   45분기 | 2015-03-31 ~ 2026-03-31
[TITN]   [SARIMA] 시작  (메모리: 1598.2 MB)
[메모리] forecast_sarima 실행 전: 1598.18 MB
[메모리] find_best_sarima_params 실행 전: 1598.18 MB
[메모리] find_best_sarima_params 실행 후: 1598.18 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.18 MB (변화: +0.00 MB)
[TITN]   [SARIMA] 완료  첫값=5.62e+08 (메모리: 1598.2 MB)
[TITN]   [ETS] 시작  (메모리: 1598.2 MB)
[메모리] forecast_ets 실행 전: 1598.18 MB
[메모리] forecast_ets 실행 후: 1598.18 MB (변화: +0.00 MB)
[TITN]   [ETS] 완료  첫값=5.02e+08 (메모리: 1598.2 MB)
[TITN]   [Prophet] 시작  (메모리: 1598.2 MB)

02:52:32 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1598.18 MB

02:52:32 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1598.19 MB (변화: +0.00 MB)
[TITN]   [Prophet] 완료  첫값=6.71e+08 (메모리: 1598.2 MB)
[TITN]   [LSTM] 시작  (메모리: 1598.2 MB)
[메모리] forecast_lstm 실행 전: 1598.19 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.18 MB (변화: -0.01 MB)
[TITN]   [LSTM] 완료  첫값=6.60e+08 (메모리: 1598.2 MB)
[TITN]   [Theta] 시작  (메모리: 1598.2 MB)
[메모리] forecast_theta 실행 전: 1598.18 MB
[메모리] forecast_theta 실행 후: 1598.18 MB (변화: +0.00 MB)
[TITN]   [Theta] 완료  첫값=5.33e+08 (메모리: 1598.2 MB)
[TITN]   [DB] 93행 저장 완료
[PROGRESS] [ 447/500] ( 89.4%)  >>  ESEA
[ESEA]   45분기 | 2015-03-31 ~ 2026-03-31
[ESEA]   [SARIMA] 시작  (메모리: 1598.2 MB)
[메모리] forecast_sarima 실행 전: 1598.18 MB
[메모리] find_best_sarima_params 실행 전: 1598.18 MB
[메모리] find_best_sarima_params 실행 후: 1598.18 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.18 MB (변화: +0.00 MB)
[ESEA]   [SARIMA] 완료  첫값=6.21e+07 (메모리: 1598.2 MB)
[ESEA]   [ETS] 시작  (메모리: 1598.2 MB)
[메모리] forecast_ets 실행 전: 1598.18 MB
[메모리] forecast_ets 실행 후: 1598.18 MB (변화: +0.00 MB)
[ESEA]   [ETS] 완료  첫값=6.32e+07 (메모리: 1598.2 MB)
[ESEA]   [Prophet] 시작  (메모리: 1598.2 MB)

02:52:52 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1598.18 MB

02:52:52 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1598.19 MB (변화: +0.00 MB)
[ESEA]   [Prophet] 완료  첫값=5.90e+07 (메모리: 1598.2 MB)
[ESEA]   [LSTM] 시작  (메모리: 1598.2 MB)
[메모리] forecast_lstm 실행 전: 1598.19 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.19 MB (변화: +0.00 MB)
[ESEA]   [LSTM] 완료  첫값=6.46e+07 (메모리: 1598.2 MB)
[ESEA]   [Theta] 시작  (메모리: 1598.2 MB)
[메모리] forecast_theta 실행 전: 1598.19 MB
[메모리] forecast_theta 실행 후: 1598.19 MB (변화: +0.00 MB)
[ESEA]   [Theta] 완료  첫값=6.20e+07 (메모리: 1598.2 MB)
[ESEA]   [DB] 93행 저장 완료
[PROGRESS] [ 448/500] ( 89.6%)  >>  RVNC
[RVNC]   45분기 | 2015-03-31 ~ 2026-03-31
[RVNC]   [SARIMA] 시작  (메모리: 1598.2 MB)
[메모리] forecast_sarima 실행 전: 1598.19 MB
[메모리] find_best_sarima_params 실행 전: 1598.19 MB
[메모리] find_best_sarima_params 실행 후: 1598.19 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.19 MB (변화: +0.00 MB)
[RVNC]   [SARIMA] 완료  첫값=6.26e+07 (메모리: 1598.2 MB)
[RVNC]   [ETS] 시작  (메모리: 1598.2 MB)
[메모리] forecast_ets 실행 전: 1598.19 MB
[메모리] forecast_ets 실행 후: 1598.19 MB (변화: +0.00 MB)
[RVNC]   [ETS] 완료  첫값=6.18e+07 (메모리: 1598.2 MB)
[RVNC]   [Prophet] 시작  (메모리: 1598.2 MB)

02:53:14 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1598.19 MB

02:53:14 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1598.20 MB (변화: +0.01 MB)
[RVNC]   [Prophet] 완료  첫값=6.37e+07 (메모리: 1598.2 MB)
[RVNC]   [LSTM] 시작  (메모리: 1598.2 MB)
[메모리] forecast_lstm 실행 전: 1598.20 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.18 MB (변화: -0.02 MB)
[RVNC]   [LSTM] 완료  첫값=6.46e+07 (메모리: 1598.2 MB)
[RVNC]   [Theta] 시작  (메모리: 1598.2 MB)
[메모리] forecast_theta 실행 전: 1598.18 MB
[메모리] forecast_theta 실행 후: 1598.18 MB (변화: +0.00 MB)
[RVNC]   [Theta] 완료  첫값=6.22e+07 (메모리: 1598.2 MB)
[RVNC]   [DB] 93행 저장 완료
[PROGRESS] [ 449/500] ( 89.8%)  >>  ACTG
[ACTG]   45분기 | 2015-03-31 ~ 2026-03-31
[ACTG]   [SARIMA] 시작  (메모리: 1598.2 MB)
[메모리] forecast_sarima 실행 전: 1598.18 MB
[메모리] find_best_sarima_params 실행 전: 1598.18 MB
[메모리] find_best_sarima_params 실행 후: 1598.18 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.18 MB (변화: +0.00 MB)
[ACTG]   [SARIMA] 완료  첫값=6.39e+07 (메모리: 1598.2 MB)
[ACTG]   [ETS] 시작  (메모리: 1598.2 MB)
[메모리] forecast_ets 실행 전: 1598.18 MB
[메모리] forecast_ets 실행 후: 1598.18 MB (변화: +0.00 MB)
[ACTG]   [ETS] 완료  첫값=7.21e+07 (메모리: 1598.2 MB)
[ACTG]   [Prophet] 시작  (메모리: 1598.2 MB)

02:53:37 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1598.18 MB

02:53:37 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1598.19 MB (변화: +0.00 MB)
[ACTG]   [Prophet] 완료  첫값=4.08e+07 (메모리: 1598.2 MB)
[ACTG]   [LSTM] 시작  (메모리: 1598.2 MB)
[메모리] forecast_lstm 실행 전: 1598.19 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.19 MB (변화: +0.00 MB)
[ACTG]   [LSTM] 완료  첫값=3.84e+07 (메모리: 1598.2 MB)
[ACTG]   [Theta] 시작  (메모리: 1598.2 MB)
[메모리] forecast_theta 실행 전: 1598.19 MB
[메모리] forecast_theta 실행 후: 1598.19 MB (변화: +0.00 MB)
[ACTG]   [Theta] 완료  첫값=5.70e+07 (메모리: 1598.2 MB)
[ACTG]   [DB] 93행 저장 완료
[PROGRESS] [ 450/500] ( 90.0%)  >>  AKBA
[AKBA]   45분기 | 2015-03-31 ~ 2026-03-31
[AKBA]   [SARIMA] 시작  (메모리: 1598.2 MB)
[메모리] forecast_sarima 실행 전: 1598.19 MB
[메모리] find_best_sarima_params 실행 전: 1598.19 MB
[메모리] find_best_sarima_params 실행 후: 1598.19 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.19 MB (변화: +0.00 MB)
[AKBA]   [SARIMA] 완료  첫값=6.35e+07 (메모리: 1598.2 MB)
[AKBA]   [ETS] 시작  (메모리: 1598.2 MB)
[메모리] forecast_ets 실행 전: 1598.19 MB
[메모리] forecast_ets 실행 후: 1598.20 MB (변화: +0.00 MB)
[AKBA]   [ETS] 완료  첫값=6.47e+07 (메모리: 1598.2 MB)
[AKBA]   [Prophet] 시작  (메모리: 1598.2 MB)

02:53:54 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1598.20 MB

02:53:54 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1598.20 MB (변화: +0.00 MB)
[AKBA]   [Prophet] 완료  첫값=7.22e+07 (메모리: 1598.2 MB)
[AKBA]   [LSTM] 시작  (메모리: 1598.2 MB)
[메모리] forecast_lstm 실행 전: 1598.20 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.32 MB (변화: +0.12 MB)
[AKBA]   [LSTM] 완료  첫값=5.94e+07 (메모리: 1598.3 MB)
[AKBA]   [Theta] 시작  (메모리: 1598.3 MB)
[메모리] forecast_theta 실행 전: 1598.32 MB
[메모리] forecast_theta 실행 후: 1598.32 MB (변화: +0.00 MB)
[AKBA]   [Theta] 완료  첫값=7.09e+07 (메모리: 1598.3 MB)
[AKBA]   [DB] 93행 저장 완료
[PROGRESS] [ 451/500] ( 90.2%)  >>  VSTM
[VSTM]   45분기 | 2015-03-31 ~ 2026-03-31
[VSTM]   [SARIMA] 시작  (메모리: 1598.3 MB)
[메모리] forecast_sarima 실행 전: 1598.32 MB
[메모리] find_best_sarima_params 실행 전: 1598.32 MB
[메모리] find_best_sarima_params 실행 후: 1598.32 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.32 MB (변화: +0.00 MB)
[VSTM]   [SARIMA] 완료  첫값=4.20e+06 (메모리: 1598.3 MB)
[VSTM]   [ETS] 시작  (메모리: 1598.3 MB)
[메모리] forecast_ets 실행 전: 1598.32 MB
[메모리] forecast_ets 실행 후: 1598.32 MB (변화: +0.00 MB)
[VSTM]   [ETS] 완료  첫값=6.01e+06 (메모리: 1598.3 MB)
[VSTM]   [Prophet] 시작  (메모리: 1598.3 MB)

02:54:17 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1598.32 MB

02:54:17 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1598.32 MB (변화: +0.00 MB)
[VSTM]   [Prophet] 완료  첫값=5.92e+06 (메모리: 1598.3 MB)
[VSTM]   [LSTM] 시작  (메모리: 1598.3 MB)
[메모리] forecast_lstm 실행 전: 1598.32 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.32 MB (변화: -0.00 MB)
[VSTM]   [LSTM] 완료  첫값=7.42e+06 (메모리: 1598.3 MB)
[VSTM]   [Theta] 시작  (메모리: 1598.3 MB)
[메모리] forecast_theta 실행 전: 1598.32 MB
[메모리] forecast_theta 실행 후: 1598.32 MB (변화: +0.00 MB)
[VSTM]   [Theta] 완료  첫값=4.78e+06 (메모리: 1598.3 MB)
[VSTM]   [DB] 93행 저장 완료
[PROGRESS] [ 452/500] ( 90.4%)  >>  RC
[RC]   45분기 | 2015-03-31 ~ 2026-03-31
[RC]   [SARIMA] 시작  (메모리: 1598.3 MB)
[메모리] forecast_sarima 실행 전: 1598.32 MB
[메모리] find_best_sarima_params 실행 전: 1598.32 MB
[메모리] find_best_sarima_params 실행 후: 1598.32 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.32 MB (변화: +0.00 MB)
[RC]   [SARIMA] 완료  첫값=1.61e+07 (메모리: 1598.3 MB)
[RC]   [ETS] 시작  (메모리: 1598.3 MB)
[메모리] forecast_ets 실행 전: 1598.32 MB
[메모리] forecast_ets 실행 후: 1598.32 MB (변화: +0.00 MB)
[RC]   [ETS] 완료  첫값=3.83e+07 (메모리: 1598.3 MB)
[RC]   [Prophet] 시작  (메모리: 1598.3 MB)

02:54:39 - cmdstanpy - INFO - Chain [1] start processing
02:54:39 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1598.32 MB
[메모리] forecast_prophet 실행 후: 1598.71 MB (변화: +0.39 MB)
[RC]   [Prophet] 완료  첫값=5.72e+07 (메모리: 1598.7 MB)
[RC]   [LSTM] 시작  (메모리: 1598.7 MB)
[메모리] forecast_lstm 실행 전: 1598.71 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.71 MB (변화: +0.00 MB)
[RC]   [LSTM] 완료  첫값=1.38e+07 (메모리: 1598.7 MB)
[RC]   [Theta] 시작  (메모리: 1598.7 MB)
[메모리] forecast_theta 실행 전: 1598.71 MB
[메모리] forecast_theta 실행 후: 1598.71 MB (변화: +0.00 MB)
[RC]   [Theta] 완료  첫값=2.57e+07 (메모리: 1598.7 MB)
[RC]   [DB] 93행 저장 완료
[PROGRESS] [ 453/500] ( 90.6%)  >>  DBI
[DBI]   45분기 | 2015-03-31 ~ 2026-03-31
[DBI]   [SARIMA] 시작  (메모리: 1598.7 MB)
[메모리] forecast_sarima 실행 전: 1598.71 MB
[메모리] find_best_sarima_params 실행 전: 1598.71 MB
[메모리] find_best_sarima_params 실행 후: 1598.71 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.71 MB (변화: +0.00 MB)
[DBI]   [SARIMA] 완료  첫값=7.72e+08 (메모리: 1598.7 MB)
[DBI]   [ETS] 시작  (메모리: 1598.7 MB)
[메모리] forecast_ets 실행 전: 1598.71 MB
[메모리] forecast_ets 실행 후: 1598.72 MB (변화: +0.00 MB)
[DBI]   [ETS] 완료  첫값=7.28e+08 (메모리: 1598.7 MB)
[DBI]   [Prophet] 시작  (메모리: 1598.7 MB)

02:54:59 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1598.72 MB

02:54:59 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1598.73 MB (변화: +0.01 MB)
[DBI]   [Prophet] 완료  첫값=7.90e+08 (메모리: 1598.7 MB)
[DBI]   [LSTM] 시작  (메모리: 1598.7 MB)
[메모리] forecast_lstm 실행 전: 1598.73 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.70 MB (변화: -0.03 MB)
[DBI]   [LSTM] 완료  첫값=7.35e+08 (메모리: 1598.7 MB)
[DBI]   [Theta] 시작  (메모리: 1598.7 MB)
[메모리] forecast_theta 실행 전: 1598.70 MB
[메모리] forecast_theta 실행 후: 1598.70 MB (변화: +0.00 MB)
[DBI]   [Theta] 완료  첫값=7.54e+08 (메모리: 1598.7 MB)
[DBI]   [DB] 93행 저장 완료
[PROGRESS] [ 454/500] ( 90.8%)  >>  LCTX
[LCTX]   45분기 | 2015-03-31 ~ 2026-03-31
[LCTX]   [SARIMA] 시작  (메모리: 1598.7 MB)
[메모리] forecast_sarima 실행 전: 1598.70 MB
[메모리] find_best_sarima_params 실행 전: 1598.70 MB
[메모리] find_best_sarima_params 실행 후: 1598.70 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.70 MB (변화: +0.00 MB)
[LCTX]   [SARIMA] 완료  첫값=3.70e+06 (메모리: 1598.7 MB)
[LCTX]   [ETS] 시작  (메모리: 1598.7 MB)
[메모리] forecast_ets 실행 전: 1598.70 MB
[메모리] forecast_ets 실행 후: 1598.70 MB (변화: +0.00 MB)
[LCTX]   [ETS] 완료  첫값=3.88e+06 (메모리: 1598.7 MB)
[LCTX]   [Prophet] 시작  (메모리: 1598.7 MB)

02:55:14 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1598.70 MB

02:55:15 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1599.08 MB (변화: +0.38 MB)
[LCTX]   [Prophet] 완료  첫값=3.07e+06 (메모리: 1599.1 MB)
[LCTX]   [LSTM] 시작  (메모리: 1599.1 MB)
[메모리] forecast_lstm 실행 전: 1599.08 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1599.10 MB (변화: +0.02 MB)
[LCTX]   [LSTM] 완료  첫값=2.39e+06 (메모리: 1599.1 MB)
[LCTX]   [Theta] 시작  (메모리: 1599.1 MB)
[메모리] forecast_theta 실행 전: 1599.10 MB
[메모리] forecast_theta 실행 후: 1599.10 MB (변화: +0.00 MB)
[LCTX]   [Theta] 완료  첫값=3.83e+06 (메모리: 1599.1 MB)
[LCTX]   [DB] 93행 저장 완료
[PROGRESS] [ 455/500] ( 91.0%)  >>  ISSC
[ISSC]   45분기 | 2015-03-31 ~ 2026-03-31
[ISSC]   [SARIMA] 시작  (메모리: 1599.1 MB)
[메모리] forecast_sarima 실행 전: 1599.10 MB
[메모리] find_best_sarima_params 실행 전: 1599.10 MB
[메모리] find_best_sarima_params 실행 후: 1599.10 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1599.10 MB (변화: +0.00 MB)
[ISSC]   [SARIMA] 완료  첫값=2.34e+07 (메모리: 1599.1 MB)
[ISSC]   [ETS] 시작  (메모리: 1599.1 MB)
[메모리] forecast_ets 실행 전: 1599.10 MB
[메모리] forecast_ets 실행 후: 1599.10 MB (변화: +0.00 MB)
[ISSC]   [ETS] 완료  첫값=2.34e+07 (메모리: 1599.1 MB)
[ISSC]   [Prophet] 시작  (메모리: 1599.1 MB)

02:55:36 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1599.10 MB

02:55:37 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1599.11 MB (변화: +0.01 MB)
[ISSC]   [Prophet] 완료  첫값=1.60e+07 (메모리: 1599.1 MB)
[ISSC]   [LSTM] 시작  (메모리: 1599.1 MB)
[메모리] forecast_lstm 실행 전: 1599.11 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1599.11 MB (변화: -0.00 MB)
[ISSC]   [LSTM] 완료  첫값=3.10e+07 (메모리: 1599.1 MB)
[ISSC]   [Theta] 시작  (메모리: 1599.1 MB)
[메모리] forecast_theta 실행 전: 1599.11 MB
[메모리] forecast_theta 실행 후: 1599.11 MB (변화: +0.00 MB)
[ISSC]   [Theta] 완료  첫값=2.27e+07 (메모리: 1599.1 MB)
[ISSC]   [DB] 93행 저장 완료
[PROGRESS] [ 456/500] ( 91.2%)  >>  NC
[NC]   45분기 | 2015-03-31 ~ 2026-03-31
[NC]   [SARIMA] 시작  (메모리: 1599.1 MB)
[메모리] forecast_sarima 실행 전: 1599.11 MB
[메모리] find_best_sarima_params 실행 전: 1599.11 MB
[메모리] find_best_sarima_params 실행 후: 1599.11 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1599.11 MB (변화: +0.00 MB)
[NC]   [SARIMA] 완료  첫값=7.24e+07 (메모리: 1599.1 MB)
[NC]   [ETS] 시작  (메모리: 1599.1 MB)
[메모리] forecast_ets 실행 전: 1599.11 MB
[메모리] forecast_ets 실행 후: 1599.11 MB (변화: +0.00 MB)
[NC]   [ETS] 완료  첫값=8.02e+07 (메모리: 1599.1 MB)
[NC]   [Prophet] 시작  (메모리: 1599.1 MB)

02:55:58 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1599.11 MB

02:55:58 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1599.11 MB (변화: +0.00 MB)
[NC]   [Prophet] 완료  첫값=1.32e+07 (메모리: 1599.1 MB)
[NC]   [LSTM] 시작  (메모리: 1599.1 MB)
[메모리] forecast_lstm 실행 전: 1599.11 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1599.14 MB (변화: +0.03 MB)
[NC]   [LSTM] 완료  첫값=6.04e+07 (메모리: 1599.1 MB)
[NC]   [Theta] 시작  (메모리: 1599.1 MB)
[메모리] forecast_theta 실행 전: 1599.14 MB
[메모리] forecast_theta 실행 후: 1599.14 MB (변화: +0.00 MB)
[NC]   [Theta] 완료  첫값=8.23e+07 (메모리: 1599.1 MB)
[NC]   [DB] 93행 저장 완료
[PROGRESS] [ 457/500] ( 91.4%)  >>  JKS
[JKS]   45분기 | 2015-03-31 ~ 2026-03-31
[JKS]   [SARIMA] 시작  (메모리: 1599.1 MB)
[메모리] forecast_sarima 실행 전: 1599.14 MB
[메모리] find_best_sarima_params 실행 전: 1599.14 MB
[메모리] find_best_sarima_params 실행 후: 1599.14 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1599.14 MB (변화: +0.00 MB)
[JKS]   [SARIMA] 완료  첫값=1.64e+10 (메모리: 1599.1 MB)
[JKS]   [ETS] 시작  (메모리: 1599.1 MB)
[메모리] forecast_ets 실행 전: 1599.14 MB
[메모리] forecast_ets 실행 후: 1599.14 MB (변화: +0.00 MB)
[JKS]   [ETS] 완료  첫값=1.86e+10 (메모리: 1599.1 MB)
[JKS]   [Prophet] 시작  (메모리: 1599.1 MB)

02:56:21 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1599.14 MB

02:56:21 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1599.16 MB (변화: +0.02 MB)
[JKS]   [Prophet] 완료  첫값=2.40e+10 (메모리: 1599.2 MB)
[JKS]   [LSTM] 시작  (메모리: 1599.2 MB)
[메모리] forecast_lstm 실행 전: 1599.16 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1599.13 MB (변화: -0.03 MB)
[JKS]   [LSTM] 완료  첫값=1.70e+10 (메모리: 1599.1 MB)
[JKS]   [Theta] 시작  (메모리: 1599.1 MB)
[메모리] forecast_theta 실행 전: 1599.13 MB
[메모리] forecast_theta 실행 후: 1599.13 MB (변화: +0.00 MB)
[JKS]   [Theta] 완료  첫값=1.85e+10 (메모리: 1599.1 MB)
[JKS]   [DB] 93행 저장 완료
[PROGRESS] [ 458/500] ( 91.6%)  >>  NVEC
[NVEC]   45분기 | 2015-03-31 ~ 2026-03-31
[NVEC]   [SARIMA] 시작  (메모리: 1599.1 MB)
[메모리] forecast_sarima 실행 전: 1599.13 MB
[메모리] find_best_sarima_params 실행 전: 1599.13 MB
[메모리] find_best_sarima_params 실행 후: 1599.13 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1599.13 MB (변화: +0.00 MB)
[NVEC]   [SARIMA] 완료  첫값=6.22e+06 (메모리: 1599.1 MB)
[NVEC]   [ETS] 시작  (메모리: 1599.1 MB)
[메모리] forecast_ets 실행 전: 1599.13 MB
[메모리] forecast_ets 실행 후: 1599.13 MB (변화: +0.00 MB)
[NVEC]   [ETS] 완료  첫값=6.21e+06 (메모리: 1599.1 MB)
[NVEC]   [Prophet] 시작  (메모리: 1599.1 MB)

02:56:40 - cmdstanpy - INFO - Chain [1] start processing
02:56:40 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1599.13 MB
[메모리] forecast_prophet 실행 후: 1599.14 MB (변화: +0.00 MB)
[NVEC]   [Prophet] 완료  첫값=6.93e+06 (메모리: 1599.1 MB)
[NVEC]   [LSTM] 시작  (메모리: 1599.1 MB)
[메모리] forecast_lstm 실행 전: 1599.14 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1599.14 MB (변화: +0.00 MB)
[NVEC]   [LSTM] 완료  첫값=6.90e+06 (메모리: 1599.1 MB)
[NVEC]   [Theta] 시작  (메모리: 1599.1 MB)
[메모리] forecast_theta 실행 전: 1599.14 MB
[메모리] forecast_theta 실행 후: 1599.14 MB (변화: +0.00 MB)
[NVEC]   [Theta] 완료  첫값=6.25e+06 (메모리: 1599.1 MB)
[NVEC]   [DB] 93행 저장 완료
[PROGRESS] [ 459/500] ( 91.8%)  >>  LAND
[LAND]   45분기 | 2015-03-31 ~ 2026-03-31
[LAND]   [SARIMA] 시작  (메모리: 1599.1 MB)
[메모리] forecast_sarima 실행 전: 1599.14 MB
[메모리] find_best_sarima_params 실행 전: 1599.14 MB
[메모리] find_best_sarima_params 실행 후: 1599.14 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1599.14 MB (변화: +0.00 MB)
[LAND]   [SARIMA] 완료  첫값=1.86e+07 (메모리: 1599.1 MB)
[LAND]   [ETS] 시작  (메모리: 1599.1 MB)
[메모리] forecast_ets 실행 전: 1599.14 MB
[메모리] forecast_ets 실행 후: 1599.14 MB (변화: +0.00 MB)
[LAND]   [ETS] 완료  첫값=1.80e+07 (메모리: 1599.1 MB)
[LAND]   [Prophet] 시작  (메모리: 1599.1 MB)

02:57:00 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1599.14 MB

02:57:01 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1599.14 MB (변화: +0.00 MB)
[LAND]   [Prophet] 완료  첫값=2.46e+07 (메모리: 1599.1 MB)
[LAND]   [LSTM] 시작  (메모리: 1599.1 MB)
[메모리] forecast_lstm 실행 전: 1599.14 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1599.15 MB (변화: +0.01 MB)
[LAND]   [LSTM] 완료  첫값=2.09e+07 (메모리: 1599.1 MB)
[LAND]   [Theta] 시작  (메모리: 1599.1 MB)
[메모리] forecast_theta 실행 전: 1599.15 MB
[메모리] forecast_theta 실행 후: 1599.15 MB (변화: +0.00 MB)
[LAND]   [Theta] 완료  첫값=1.76e+07 (메모리: 1599.1 MB)
[LAND]   [DB] 93행 저장 완료
[PROGRESS] [ 460/500] ( 92.0%)  >>  HEAR
[HEAR]   45분기 | 2015-03-31 ~ 2026-03-31
[HEAR]   [SARIMA] 시작  (메모리: 1599.1 MB)
[메모리] forecast_sarima 실행 전: 1599.15 MB
[메모리] find_best_sarima_params 실행 전: 1599.15 MB
[메모리] find_best_sarima_params 실행 후: 1599.15 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1599.15 MB (변화: +0.00 MB)
[HEAR]   [SARIMA] 완료  첫값=8.65e+07 (메모리: 1599.1 MB)
[HEAR]   [ETS] 시작  (메모리: 1599.1 MB)
[메모리] forecast_ets 실행 전: 1599.15 MB
[메모리] forecast_ets 실행 후: 1599.15 MB (변화: +0.00 MB)
[HEAR]   [ETS] 완료  첫값=7.18e+07 (메모리: 1599.2 MB)
[HEAR]   [Prophet] 시작  (메모리: 1599.2 MB)

02:57:21 - cmdstanpy - INFO - Chain [1] start processing
02:57:21 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1599.15 MB
[메모리] forecast_prophet 실행 후: 1599.15 MB (변화: +0.00 MB)
[HEAR]   [Prophet] 완료  첫값=9.14e+07 (메모리: 1599.2 MB)
[HEAR]   [LSTM] 시작  (메모리: 1599.2 MB)
[메모리] forecast_lstm 실행 전: 1599.15 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1599.15 MB (변화: -0.00 MB)
[HEAR]   [LSTM] 완료  첫값=7.58e+07 (메모리: 1599.1 MB)
[HEAR]   [Theta] 시작  (메모리: 1599.1 MB)
[메모리] forecast_theta 실행 전: 1599.15 MB
[메모리] forecast_theta 실행 후: 1599.15 MB (변화: +0.00 MB)
[HEAR]   [Theta] 완료  첫값=7.31e+07 (메모리: 1599.1 MB)
[HEAR]   [DB] 93행 저장 완료
[PROGRESS] [ 461/500] ( 92.2%)  >>  ACCO
[ACCO]   45분기 | 2015-03-31 ~ 2026-03-31
[ACCO]   [SARIMA] 시작  (메모리: 1599.1 MB)
[메모리] forecast_sarima 실행 전: 1599.15 MB
[메모리] find_best_sarima_params 실행 전: 1599.15 MB
[메모리] find_best_sarima_params 실행 후: 1599.15 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1599.15 MB (변화: +0.00 MB)
[ACCO]   [SARIMA] 완료  첫값=4.10e+08 (메모리: 1599.1 MB)
[ACCO]   [ETS] 시작  (메모리: 1599.1 MB)
[메모리] forecast_ets 실행 전: 1599.15 MB
[메모리] forecast_ets 실행 후: 1599.15 MB (변화: +0.00 MB)
[ACCO]   [ETS] 완료  첫값=4.54e+08 (메모리: 1599.2 MB)
[ACCO]   [Prophet] 시작  (메모리: 1599.2 MB)

02:57:41 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1599.15 MB

02:57:41 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1599.17 MB (변화: +0.02 MB)
[ACCO]   [Prophet] 완료  첫값=4.45e+08 (메모리: 1599.2 MB)
[ACCO]   [LSTM] 시작  (메모리: 1599.2 MB)
[메모리] forecast_lstm 실행 전: 1599.17 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1599.18 MB (변화: +0.01 MB)
[ACCO]   [LSTM] 완료  첫값=4.06e+08 (메모리: 1599.2 MB)
[ACCO]   [Theta] 시작  (메모리: 1599.2 MB)
[메모리] forecast_theta 실행 전: 1599.18 MB
[메모리] forecast_theta 실행 후: 1599.18 MB (변화: +0.00 MB)
[ACCO]   [Theta] 완료  첫값=4.51e+08 (메모리: 1599.2 MB)
[ACCO]   [DB] 93행 저장 완료
[PROGRESS] [ 462/500] ( 92.4%)  >>  ELA
[ELA]   45분기 | 2015-03-31 ~ 2026-03-31
[ELA]   [SARIMA] 시작  (메모리: 1599.2 MB)
[메모리] forecast_sarima 실행 전: 1599.18 MB
[메모리] find_best_sarima_params 실행 전: 1599.18 MB
[메모리] find_best_sarima_params 실행 후: 1599.18 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1599.18 MB (변화: +0.00 MB)
[ELA]   [SARIMA] 완료  첫값=6.02e+07 (메모리: 1599.2 MB)
[ELA]   [ETS] 시작  (메모리: 1599.2 MB)
[메모리] forecast_ets 실행 전: 1599.18 MB
[메모리] forecast_ets 실행 후: 1599.18 MB (변화: +0.00 MB)
[ELA]   [ETS] 완료  첫값=6.30e+07 (메모리: 1599.2 MB)
[ELA]   [Prophet] 시작  (메모리: 1599.2 MB)

02:58:01 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1599.18 MB

02:58:01 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1599.19 MB (변화: +0.01 MB)
[ELA]   [Prophet] 완료  첫값=5.64e+07 (메모리: 1599.2 MB)
[ELA]   [LSTM] 시작  (메모리: 1599.2 MB)
[메모리] forecast_lstm 실행 전: 1599.19 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1599.28 MB (변화: +0.09 MB)
[ELA]   [LSTM] 완료  첫값=5.42e+07 (메모리: 1599.3 MB)
[ELA]   [Theta] 시작  (메모리: 1599.3 MB)
[메모리] forecast_theta 실행 전: 1599.28 MB
[메모리] forecast_theta 실행 후: 1599.28 MB (변화: +0.00 MB)
[ELA]   [Theta] 완료  첫값=6.18e+07 (메모리: 1599.3 MB)
[ELA]   [DB] 93행 저장 완료
[PROGRESS] [ 463/500] ( 92.6%)  >>  QIWI
[QIWI]   45분기 | 2015-03-31 ~ 2026-03-31
[QIWI]   [SARIMA] 시작  (메모리: 1599.3 MB)
[메모리] forecast_sarima 실행 전: 1599.28 MB
[메모리] find_best_sarima_params 실행 전: 1599.28 MB
[메모리] find_best_sarima_params 실행 후: 1599.28 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1599.28 MB (변화: +0.00 MB)
[QIWI]   [SARIMA] 완료  첫값=-4.60e+10 (메모리: 1599.3 MB)
[QIWI]   [ETS] 시작  (메모리: 1599.3 MB)
[메모리] forecast_ets 실행 전: 1599.28 MB
[메모리] forecast_ets 실행 후: 1599.28 MB (변화: +0.00 MB)
[QIWI]   [ETS] 완료  첫값=-4.58e+10 (메모리: 1599.3 MB)
[QIWI]   [Prophet] 시작  (메모리: 1599.3 MB)

02:58:23 - cmdstanpy - INFO - Chain [1] start processing
02:58:23 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1599.28 MB
[메모리] forecast_prophet 실행 후: 1599.28 MB (변화: +0.00 MB)
[QIWI]   [Prophet] 완료  첫값=-2.82e+10 (메모리: 1599.3 MB)
[QIWI]   [LSTM] 시작  (메모리: 1599.3 MB)
[메모리] forecast_lstm 실행 전: 1599.28 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1599.24 MB (변화: -0.04 MB)
[QIWI]   [LSTM] 완료  첫값=-3.82e+10 (메모리: 1599.2 MB)
[QIWI]   [Theta] 시작  (메모리: 1599.2 MB)
[메모리] forecast_theta 실행 전: 1599.24 MB
[메모리] forecast_theta 실행 후: 1599.24 MB (변화: +0.00 MB)
[QIWI]   [Theta] 완료  첫값=-4.45e+10 (메모리: 1599.2 MB)
[QIWI]   [DB] 93행 저장 완료
[PROGRESS] [ 464/500] ( 92.8%)  >>  KNOP
[KNOP]   45분기 | 2015-03-31 ~ 2026-03-31
[KNOP]   [SARIMA] 시작  (메모리: 1599.2 MB)
[메모리] forecast_sarima 실행 전: 1599.24 MB
[메모리] find_best_sarima_params 실행 전: 1599.24 MB
[메모리] find_best_sarima_params 실행 후: 1599.24 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1599.24 MB (변화: +0.00 MB)
[KNOP]   [SARIMA] 완료  첫값=9.91e+07 (메모리: 1599.2 MB)
[KNOP]   [ETS] 시작  (메모리: 1599.2 MB)
[메모리] forecast_ets 실행 전: 1599.24 MB
[메모리] forecast_ets 실행 후: 1599.24 MB (변화: +0.00 MB)
[KNOP]   [ETS] 완료  첫값=9.97e+07 (메모리: 1599.2 MB)
[KNOP]   [Prophet] 시작  (메모리: 1599.2 MB)

02:58:43 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1599.24 MB

02:58:43 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1599.25 MB (변화: +0.01 MB)
[KNOP]   [Prophet] 완료  첫값=9.05e+07 (메모리: 1599.2 MB)
[KNOP]   [LSTM] 시작  (메모리: 1599.2 MB)
[메모리] forecast_lstm 실행 전: 1599.25 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1599.22 MB (변화: -0.03 MB)
[KNOP]   [LSTM] 완료  첫값=8.33e+07 (메모리: 1599.2 MB)
[KNOP]   [Theta] 시작  (메모리: 1599.2 MB)
[메모리] forecast_theta 실행 전: 1599.22 MB
[메모리] forecast_theta 실행 후: 1599.22 MB (변화: +0.00 MB)
[KNOP]   [Theta] 완료  첫값=9.85e+07 (메모리: 1599.2 MB)
[KNOP]   [DB] 93행 저장 완료
[PROGRESS] [ 465/500] ( 93.0%)  >>  OEC
[OEC]   45분기 | 2015-03-31 ~ 2026-03-31
[OEC]   [SARIMA] 시작  (메모리: 1599.2 MB)
[메모리] forecast_sarima 실행 전: 1599.22 MB
[메모리] find_best_sarima_params 실행 전: 1599.22 MB
[메모리] find_best_sarima_params 실행 후: 1599.22 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1599.22 MB (변화: +0.00 MB)
[OEC]   [SARIMA] 완료  첫값=4.54e+08 (메모리: 1599.2 MB)
[OEC]   [ETS] 시작  (메모리: 1599.2 MB)
[메모리] forecast_ets 실행 전: 1599.22 MB
[메모리] forecast_ets 실행 후: 1599.23 MB (변화: +0.00 MB)
[OEC]   [ETS] 완료  첫값=4.38e+08 (메모리: 1599.2 MB)
[OEC]   [Prophet] 시작  (메모리: 1599.2 MB)
[메모리] forecast_prophet 실행 전: 1599.23 MB

02:59:05 - cmdstanpy - INFO - Chain [1] start processing
02:59:06 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1599.23 MB (변화: +0.01 MB)
[OEC]   [Prophet] 완료  첫값=4.98e+08 (메모리: 1599.2 MB)
[OEC]   [LSTM] 시작  (메모리: 1599.2 MB)
[메모리] forecast_lstm 실행 전: 1599.23 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1599.20 MB (변화: -0.04 MB)
[OEC]   [LSTM] 완료  첫값=4.61e+08 (메모리: 1599.2 MB)
[OEC]   [Theta] 시작  (메모리: 1599.2 MB)
[메모리] forecast_theta 실행 전: 1599.20 MB
[메모리] forecast_theta 실행 후: 1599.20 MB (변화: +0.00 MB)
[OEC]   [Theta] 완료  첫값=4.33e+08 (메모리: 1599.2 MB)
[OEC]   [DB] 93행 저장 완료
[PROGRESS] [ 466/500] ( 93.2%)  >>  GCO
[GCO]   45분기 | 2015-03-31 ~ 2026-03-31
[GCO]   [SARIMA] 시작  (메모리: 1599.2 MB)
[메모리] forecast_sarima 실행 전: 1599.20 MB
[메모리] find_best_sarima_params 실행 전: 1599.20 MB
[메모리] find_best_sarima_params 실행 후: 1599.20 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1599.20 MB (변화: +0.00 MB)
[GCO]   [SARIMA] 완료  첫값=4.21e+08 (메모리: 1599.2 MB)
[GCO]   [ETS] 시작  (메모리: 1599.2 MB)
[메모리] forecast_ets 실행 전: 1599.20 MB
[메모리] forecast_ets 실행 후: 1599.20 MB (변화: +0.00 MB)
[GCO]   [ETS] 완료  첫값=4.39e+08 (메모리: 1599.2 MB)
[GCO]   [Prophet] 시작  (메모리: 1599.2 MB)

02:59:30 - cmdstanpy - INFO - Chain [1] start processing
02:59:30 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1599.20 MB
[메모리] forecast_prophet 실행 후: 1599.20 MB (변화: +0.00 MB)
[GCO]   [Prophet] 완료  첫값=5.20e+08 (메모리: 1599.2 MB)
[GCO]   [LSTM] 시작  (메모리: 1599.2 MB)
[메모리] forecast_lstm 실행 전: 1599.20 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1599.18 MB (변화: -0.02 MB)
[GCO]   [LSTM] 완료  첫값=5.81e+08 (메모리: 1599.2 MB)
[GCO]   [Theta] 시작  (메모리: 1599.2 MB)
[메모리] forecast_theta 실행 전: 1599.18 MB
[메모리] forecast_theta 실행 후: 1599.18 MB (변화: +0.00 MB)
[GCO]   [Theta] 완료  첫값=4.36e+08 (메모리: 1599.2 MB)
[GCO]   [DB] 93행 저장 완료
[PROGRESS] [ 467/500] ( 93.4%)  >>  MCFT
[MCFT]   45분기 | 2015-03-31 ~ 2026-03-31
[MCFT]   [SARIMA] 시작  (메모리: 1599.2 MB)
[메모리] forecast_sarima 실행 전: 1599.18 MB
[메모리] find_best_sarima_params 실행 전: 1599.18 MB
[메모리] find_best_sarima_params 실행 후: 1599.18 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1599.18 MB (변화: +0.00 MB)
[MCFT]   [SARIMA] 완료  첫값=7.18e+07 (메모리: 1599.2 MB)
[MCFT]   [ETS] 시작  (메모리: 1599.2 MB)
[메모리] forecast_ets 실행 전: 1599.18 MB
[메모리] forecast_ets 실행 후: 1599.19 MB (변화: +0.00 MB)
[MCFT]   [ETS] 완료  첫값=7.23e+07 (메모리: 1599.2 MB)
[MCFT]   [Prophet] 시작  (메모리: 1599.2 MB)

02:59:51 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1599.19 MB

02:59:51 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1599.20 MB (변화: +0.01 MB)
[MCFT]   [Prophet] 완료  첫값=1.25e+08 (메모리: 1599.2 MB)
[MCFT]   [LSTM] 시작  (메모리: 1599.2 MB)
[메모리] forecast_lstm 실행 전: 1599.20 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1599.19 MB (변화: -0.01 MB)
[MCFT]   [LSTM] 완료  첫값=9.36e+07 (메모리: 1599.2 MB)
[MCFT]   [Theta] 시작  (메모리: 1599.2 MB)
[메모리] forecast_theta 실행 전: 1599.19 MB
[메모리] forecast_theta 실행 후: 1599.19 MB (변화: +0.00 MB)
[MCFT]   [Theta] 완료  첫값=7.21e+07 (메모리: 1599.2 MB)
[MCFT]   [DB] 93행 저장 완료
[PROGRESS] [ 468/500] ( 93.6%)  >>  MOV
[MOV]   45분기 | 2015-03-31 ~ 2026-03-31
[MOV]   [SARIMA] 시작  (메모리: 1599.2 MB)
[메모리] forecast_sarima 실행 전: 1599.19 MB
[메모리] find_best_sarima_params 실행 전: 1599.19 MB
[메모리] find_best_sarima_params 실행 후: 1599.19 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1599.19 MB (변화: +0.00 MB)
[MOV]   [SARIMA] 완료  첫값=1.41e+08 (메모리: 1599.2 MB)
[MOV]   [ETS] 시작  (메모리: 1599.2 MB)
[메모리] forecast_ets 실행 전: 1599.19 MB
[메모리] forecast_ets 실행 후: 1599.19 MB (변화: +0.00 MB)
[MOV]   [ETS] 완료  첫값=1.34e+08 (메모리: 1599.2 MB)
[MOV]   [Prophet] 시작  (메모리: 1599.2 MB)

03:00:11 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1599.19 MB

03:00:11 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1599.20 MB (변화: +0.00 MB)
[MOV]   [Prophet] 완료  첫값=1.80e+08 (메모리: 1599.2 MB)
[MOV]   [LSTM] 시작  (메모리: 1599.2 MB)
[메모리] forecast_lstm 실행 전: 1599.20 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1599.17 MB (변화: -0.02 MB)
[MOV]   [LSTM] 완료  첫값=1.72e+08 (메모리: 1599.2 MB)
[MOV]   [Theta] 시작  (메모리: 1599.2 MB)
[메모리] forecast_theta 실행 전: 1599.17 MB
[메모리] forecast_theta 실행 후: 1599.17 MB (변화: +0.00 MB)
[MOV]   [Theta] 완료  첫값=1.31e+08 (메모리: 1599.2 MB)
[MOV]   [DB] 93행 저장 완료
[PROGRESS] [ 469/500] ( 93.8%)  >>  CTRN
[CTRN]   45분기 | 2015-03-31 ~ 2026-03-31
[CTRN]   [SARIMA] 시작  (메모리: 1599.2 MB)
[메모리] forecast_sarima 실행 전: 1599.17 MB
[메모리] find_best_sarima_params 실행 전: 1599.17 MB
[메모리] find_best_sarima_params 실행 후: 1599.18 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1599.18 MB (변화: +0.00 MB)
[CTRN]   [SARIMA] 완료  첫값=1.95e+08 (메모리: 1599.2 MB)
[CTRN]   [ETS] 시작  (메모리: 1599.2 MB)
[메모리] forecast_ets 실행 전: 1599.18 MB
[메모리] forecast_ets 실행 후: 1599.18 MB (변화: +0.00 MB)
[CTRN]   [ETS] 완료  첫값=1.98e+08 (메모리: 1599.2 MB)
[CTRN]   [Prophet] 시작  (메모리: 1599.2 MB)

03:00:29 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1599.18 MB

03:00:29 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1599.18 MB (변화: +0.00 MB)
[CTRN]   [Prophet] 완료  첫값=2.07e+08 (메모리: 1599.2 MB)
[CTRN]   [LSTM] 시작  (메모리: 1599.2 MB)
[메모리] forecast_lstm 실행 전: 1599.18 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1599.20 MB (변화: +0.02 MB)
[CTRN]   [LSTM] 완료  첫값=1.88e+08 (메모리: 1599.2 MB)
[CTRN]   [Theta] 시작  (메모리: 1599.2 MB)
[메모리] forecast_theta 실행 전: 1599.20 MB
[메모리] forecast_theta 실행 후: 1599.20 MB (변화: +0.00 MB)
[CTRN]   [Theta] 완료  첫값=1.96e+08 (메모리: 1599.2 MB)
[CTRN]   [DB] 93행 저장 완료
[PROGRESS] [ 470/500] ( 94.0%)  >>  FVR
[FVR] [SKIP] [FVR] 'sale' 관측치 부족: 15개 < 최소 28개
[PROGRESS] [ 471/500] ( 94.2%)  >>  BGS
[BGS]   44분기 | 2015-06-30 ~ 2026-03-31
[BGS]   [SARIMA] 시작  (메모리: 1599.2 MB)
[메모리] forecast_sarima 실행 전: 1599.20 MB
[메모리] find_best_sarima_params 실행 전: 1599.20 MB
[메모리] find_best_sarima_params 실행 후: 1599.20 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1599.20 MB (변화: +0.00 MB)
[BGS]   [SARIMA] 완료  첫값=4.42e+08 (메모리: 1599.2 MB)
[BGS]   [ETS] 시작  (메모리: 1599.2 MB)
[메모리] forecast_ets 실행 전: 1599.20 MB
[메모리] forecast_ets 실행 후: 1599.20 MB (변화: +0.00 MB)
[BGS]   [ETS] 완료  첫값=3.97e+08 (메모리: 1599.2 MB)
[BGS]   [Prophet] 시작  (메모리: 1599.2 MB)

03:00:59 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1599.20 MB

03:00:59 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1599.21 MB (변화: +0.02 MB)
[BGS]   [Prophet] 완료  첫값=5.47e+08 (메모리: 1599.2 MB)
[BGS]   [LSTM] 시작  (메모리: 1599.2 MB)
[메모리] forecast_lstm 실행 전: 1599.21 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1599.23 MB (변화: +0.01 MB)
[BGS]   [LSTM] 완료  첫값=5.22e+08 (메모리: 1599.2 MB)
[BGS]   [Theta] 시작  (메모리: 1599.2 MB)
[메모리] forecast_theta 실행 전: 1599.23 MB
[메모리] forecast_theta 실행 후: 1599.23 MB (변화: +0.00 MB)
[BGS]   [Theta] 완료  첫값=4.15e+08 (메모리: 1599.2 MB)
[BGS]   [DB] 92행 저장 완료
[PROGRESS] [ 472/500] ( 94.4%)  >>  NCMI
[NCMI]   44분기 | 2015-06-30 ~ 2026-03-31
[NCMI]   [SARIMA] 시작  (메모리: 1599.2 MB)
[메모리] forecast_sarima 실행 전: 1599.23 MB
[메모리] find_best_sarima_params 실행 전: 1599.23 MB
[메모리] find_best_sarima_params 실행 후: 1599.23 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1599.23 MB (변화: +0.00 MB)
[NCMI]   [SARIMA] 완료  첫값=4.86e+07 (메모리: 1599.2 MB)
[NCMI]   [ETS] 시작  (메모리: 1599.2 MB)
[메모리] forecast_ets 실행 전: 1599.23 MB
[메모리] forecast_ets 실행 후: 1599.23 MB (변화: +0.00 MB)
[NCMI]   [ETS] 완료  첫값=4.72e+07 (메모리: 1599.2 MB)
[NCMI]   [Prophet] 시작  (메모리: 1599.2 MB)

03:01:14 - cmdstanpy - INFO - Chain [1] start processing
03:01:14 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1599.23 MB
[메모리] forecast_prophet 실행 후: 1599.23 MB (변화: +0.00 MB)
[NCMI]   [Prophet] 완료  첫값=3.36e+07 (메모리: 1599.2 MB)
[NCMI]   [LSTM] 시작  (메모리: 1599.2 MB)
[메모리] forecast_lstm 실행 전: 1599.23 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1599.23 MB (변화: +0.00 MB)
[NCMI]   [LSTM] 완료  첫값=5.17e+07 (메모리: 1599.2 MB)
[NCMI]   [Theta] 시작  (메모리: 1599.2 MB)
[메모리] forecast_theta 실행 전: 1599.23 MB
[메모리] forecast_theta 실행 후: 1599.23 MB (변화: +0.00 MB)
[NCMI]   [Theta] 완료  첫값=6.18e+07 (메모리: 1599.2 MB)
[NCMI]   [DB] 92행 저장 완료
[PROGRESS] [ 473/500] ( 94.6%)  >>  VGZ
[VGZ]   45분기 | 2015-03-31 ~ 2026-03-31
[VGZ]   [SARIMA] 시작  (메모리: 1599.2 MB)
[메모리] forecast_sarima 실행 전: 1599.23 MB
[메모리] find_best_sarima_params 실행 전: 1599.23 MB
[메모리] find_best_sarima_params 실행 후: 1599.23 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1599.23 MB (변화: +0.00 MB)
[VGZ]   [SARIMA] 완료  첫값=-1.88e+04 (메모리: 1599.2 MB)
[VGZ]   [ETS] 시작  (메모리: 1599.2 MB)
[메모리] forecast_ets 실행 전: 1599.23 MB
[메모리] forecast_ets 실행 후: 1599.23 MB (변화: +0.00 MB)
[VGZ]   [ETS] 완료  첫값=-2.25e+04 (메모리: 1599.2 MB)
[VGZ]   [Prophet] 시작  (메모리: 1599.2 MB)

03:01:27 - cmdstanpy - INFO - Chain [1] start processing
03:01:27 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1599.23 MB
[메모리] forecast_prophet 실행 후: 1599.23 MB (변화: +0.00 MB)
[VGZ]   [Prophet] 완료  첫값=-6.10e+04 (메모리: 1599.2 MB)
[VGZ]   [LSTM] 시작  (메모리: 1599.2 MB)
[메모리] forecast_lstm 실행 전: 1599.23 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1599.25 MB (변화: +0.02 MB)
[VGZ]   [LSTM] 완료  첫값=1.31e+04 (메모리: 1599.2 MB)
[VGZ]   [Theta] 시작  (메모리: 1599.2 MB)
[메모리] forecast_theta 실행 전: 1599.25 MB
[메모리] forecast_theta 실행 후: 1599.25 MB (변화: +0.00 MB)
[VGZ]   [Theta] 완료  첫값=-8.51e+04 (메모리: 1599.2 MB)
[VGZ]   [DB] 93행 저장 완료
[PROGRESS] [ 474/500] ( 94.8%)  >>  CCLP
[CCLP]   45분기 | 2015-03-31 ~ 2026-03-31
[CCLP]   [SARIMA] 시작  (메모리: 1599.2 MB)
[메모리] forecast_sarima 실행 전: 1599.25 MB
[메모리] find_best_sarima_params 실행 전: 1599.25 MB
[메모리] find_best_sarima_params 실행 후: 1599.25 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1599.25 MB (변화: +0.00 MB)
[CCLP]   [SARIMA] 완료  첫값=9.82e+07 (메모리: 1599.2 MB)
[CCLP]   [ETS] 시작  (메모리: 1599.2 MB)
[메모리] forecast_ets 실행 전: 1599.25 MB
[메모리] forecast_ets 실행 후: 1599.25 MB (변화: +0.01 MB)
[CCLP]   [ETS] 완료  첫값=1.07e+08 (메모리: 1599.3 MB)
[CCLP]   [Prophet] 시작  (메모리: 1599.3 MB)

03:01:46 - cmdstanpy - INFO - Chain [1] start processing
03:01:46 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1599.25 MB
[메모리] forecast_prophet 실행 후: 1599.26 MB (변화: +0.01 MB)
[CCLP]   [Prophet] 완료  첫값=9.43e+07 (메모리: 1599.3 MB)
[CCLP]   [LSTM] 시작  (메모리: 1599.3 MB)
[메모리] forecast_lstm 실행 전: 1599.26 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1599.28 MB (변화: +0.02 MB)
[CCLP]   [LSTM] 완료  첫값=9.71e+07 (메모리: 1599.3 MB)
[CCLP]   [Theta] 시작  (메모리: 1599.3 MB)
[메모리] forecast_theta 실행 전: 1599.28 MB
[메모리] forecast_theta 실행 후: 1599.28 MB (변화: +0.00 MB)
[CCLP]   [Theta] 완료  첫값=9.83e+07 (메모리: 1599.3 MB)
[CCLP]   [DB] 93행 저장 완료
[PROGRESS] [ 475/500] ( 95.0%)  >>  ATNI
[ATNI]   45분기 | 2015-03-31 ~ 2026-03-31
[ATNI]   [SARIMA] 시작  (메모리: 1599.3 MB)
[메모리] forecast_sarima 실행 전: 1599.28 MB
[메모리] find_best_sarima_params 실행 전: 1599.28 MB
[메모리] find_best_sarima_params 실행 후: 1599.28 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1599.28 MB (변화: +0.00 MB)
[ATNI]   [SARIMA] 완료  첫값=1.83e+08 (메모리: 1599.3 MB)
[ATNI]   [ETS] 시작  (메모리: 1599.3 MB)
[메모리] forecast_ets 실행 전: 1599.28 MB
[메모리] forecast_ets 실행 후: 1599.28 MB (변화: +0.00 MB)
[ATNI]   [ETS] 완료  첫값=1.88e+08 (메모리: 1599.3 MB)
[ATNI]   [Prophet] 시작  (메모리: 1599.3 MB)

03:02:12 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1599.28 MB

03:02:12 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1599.28 MB (변화: +0.00 MB)
[ATNI]   [Prophet] 완료  첫값=2.00e+08 (메모리: 1599.3 MB)
[ATNI]   [LSTM] 시작  (메모리: 1599.3 MB)
[메모리] forecast_lstm 실행 전: 1599.28 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1599.26 MB (변화: -0.02 MB)
[ATNI]   [LSTM] 완료  첫값=1.82e+08 (메모리: 1599.3 MB)
[ATNI]   [Theta] 시작  (메모리: 1599.3 MB)
[메모리] forecast_theta 실행 전: 1599.26 MB
[메모리] forecast_theta 실행 후: 1599.26 MB (변화: +0.00 MB)
[ATNI]   [Theta] 완료  첫값=1.86e+08 (메모리: 1599.3 MB)
[ATNI]   [DB] 93행 저장 완료
[PROGRESS] [ 476/500] ( 95.2%)  >>  SMC
[SMC] [SKIP] [SMC] 'sale' 관측치 부족: 15개 < 최소 28개
[PROGRESS] [ 477/500] ( 95.4%)  >>  CLDT
[CLDT]   45분기 | 2015-03-31 ~ 2026-03-31
[CLDT]   [SARIMA] 시작  (메모리: 1599.3 MB)
[메모리] forecast_sarima 실행 전: 1599.26 MB
[메모리] find_best_sarima_params 실행 전: 1599.26 MB
[메모리] find_best_sarima_params 실행 후: 1599.26 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1599.26 MB (변화: +0.00 MB)
[CLDT]   [SARIMA] 완료  첫값=7.84e+07 (메모리: 1599.3 MB)
[CLDT]   [ETS] 시작  (메모리: 1599.3 MB)
[메모리] forecast_ets 실행 전: 1599.26 MB
[메모리] forecast_ets 실행 후: 1599.27 MB (변화: +0.00 MB)
[CLDT]   [ETS] 완료  첫값=8.59e+07 (메모리: 1599.3 MB)
[CLDT]   [Prophet] 시작  (메모리: 1599.3 MB)

03:02:34 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1599.27 MB

03:02:34 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1599.27 MB (변화: +0.00 MB)
[CLDT]   [Prophet] 완료  첫값=7.23e+07 (메모리: 1599.3 MB)
[CLDT]   [LSTM] 시작  (메모리: 1599.3 MB)
[메모리] forecast_lstm 실행 전: 1599.27 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1599.28 MB (변화: +0.01 MB)
[CLDT]   [LSTM] 완료  첫값=6.72e+07 (메모리: 1599.3 MB)
[CLDT]   [Theta] 시작  (메모리: 1599.3 MB)
[메모리] forecast_theta 실행 전: 1599.28 MB
[메모리] forecast_theta 실행 후: 1599.28 MB (변화: +0.00 MB)
[CLDT]   [Theta] 완료  첫값=7.85e+07 (메모리: 1599.3 MB)
[CLDT]   [DB] 93행 저장 완료
[PROGRESS] [ 478/500] ( 95.6%)  >>  AMCX
[AMCX]   45분기 | 2015-03-31 ~ 2026-03-31
[AMCX]   [SARIMA] 시작  (메모리: 1599.3 MB)
[메모리] forecast_sarima 실행 전: 1599.28 MB
[메모리] find_best_sarima_params 실행 전: 1599.28 MB
[메모리] find_best_sarima_params 실행 후: 1599.28 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1599.28 MB (변화: +0.00 MB)
[AMCX]   [SARIMA] 완료  첫값=5.87e+08 (메모리: 1599.3 MB)
[AMCX]   [ETS] 시작  (메모리: 1599.3 MB)
[메모리] forecast_ets 실행 전: 1599.28 MB
[메모리] forecast_ets 실행 후: 1599.28 MB (변화: +0.00 MB)
[AMCX]   [ETS] 완료  첫값=5.79e+08 (메모리: 1599.3 MB)
[AMCX]   [Prophet] 시작  (메모리: 1599.3 MB)

03:02:58 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1599.28 MB

03:02:58 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1599.28 MB (변화: +0.00 MB)
[AMCX]   [Prophet] 완료  첫값=5.89e+08 (메모리: 1599.3 MB)
[AMCX]   [LSTM] 시작  (메모리: 1599.3 MB)
[메모리] forecast_lstm 실행 전: 1599.28 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1599.29 MB (변화: +0.00 MB)
[AMCX]   [LSTM] 완료  첫값=6.33e+08 (메모리: 1599.3 MB)
[AMCX]   [Theta] 시작  (메모리: 1599.3 MB)
[메모리] forecast_theta 실행 전: 1599.29 MB
[메모리] forecast_theta 실행 후: 1599.29 MB (변화: +0.00 MB)
[AMCX]   [Theta] 완료  첫값=5.85e+08 (메모리: 1599.3 MB)
[AMCX]   [DB] 93행 저장 완료
[PROGRESS] [ 479/500] ( 95.8%)  >>  BYRN
[BYRN]   45분기 | 2015-03-31 ~ 2026-03-31
[BYRN]   [SARIMA] 시작  (메모리: 1599.3 MB)
[메모리] forecast_sarima 실행 전: 1599.29 MB
[메모리] find_best_sarima_params 실행 전: 1599.29 MB
[메모리] find_best_sarima_params 실행 후: 1598.30 MB (변화: -0.98 MB)
[메모리] forecast_sarima 실행 후: 1598.30 MB (변화: -0.98 MB)
[BYRN]   [SARIMA] 완료  첫값=4.46e+07 (메모리: 1598.3 MB)
[BYRN]   [ETS] 시작  (메모리: 1598.3 MB)
[메모리] forecast_ets 실행 전: 1598.30 MB
[메모리] forecast_ets 실행 후: 1598.30 MB (변화: +0.00 MB)
[BYRN]   [ETS] 완료  첫값=7.19e+07 (메모리: 1598.3 MB)
[BYRN]   [Prophet] 시작  (메모리: 1598.3 MB)

03:03:21 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1598.30 MB

03:03:21 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1598.71 MB (변화: +0.41 MB)
[BYRN]   [Prophet] 완료  첫값=2.52e+07 (메모리: 1598.7 MB)
[BYRN]   [LSTM] 시작  (메모리: 1598.7 MB)
[메모리] forecast_lstm 실행 전: 1598.71 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.67 MB (변화: -0.04 MB)
[BYRN]   [LSTM] 완료  첫값=4.28e+07 (메모리: 1598.7 MB)
[BYRN]   [Theta] 시작  (메모리: 1597.6 MB)
[메모리] forecast_theta 실행 전: 1597.63 MB
[메모리] forecast_theta 실행 후: 1597.63 MB (변화: +0.00 MB)
[BYRN]   [Theta] 완료  첫값=9.37e+07 (메모리: 1597.6 MB)
[BYRN]   [DB] 93행 저장 완료
[PROGRESS] [ 480/500] ( 96.0%)  >>  INS
[INS]   45분기 | 2015-03-31 ~ 2026-03-31
[INS]   [SARIMA] 시작  (메모리: 1597.6 MB)
[메모리] forecast_sarima 실행 전: 1597.63 MB
[메모리] find_best_sarima_params 실행 전: 1597.63 MB
[메모리] find_best_sarima_params 실행 후: 1597.63 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1597.63 MB (변화: +0.00 MB)
[INS]   [SARIMA] 완료  첫값=1.98e+07 (메모리: 1597.6 MB)
[INS]   [ETS] 시작  (메모리: 1597.6 MB)
[메모리] forecast_ets 실행 전: 1597.63 MB
[메모리] forecast_ets 실행 후: 1597.64 MB (변화: +0.00 MB)
[INS]   [ETS] 완료  첫값=1.93e+07 (메모리: 1597.6 MB)
[INS]   [Prophet] 시작  (메모리: 1597.6 MB)

03:03:42 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1597.64 MB

03:03:42 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1598.71 MB (변화: +1.07 MB)
[INS]   [Prophet] 완료  첫값=1.86e+07 (메모리: 1598.7 MB)
[INS]   [LSTM] 시작  (메모리: 1598.7 MB)
[메모리] forecast_lstm 실행 전: 1598.71 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.84 MB (변화: +0.13 MB)
[INS]   [LSTM] 완료  첫값=1.50e+07 (메모리: 1598.8 MB)
[INS]   [Theta] 시작  (메모리: 1598.8 MB)
[메모리] forecast_theta 실행 전: 1598.84 MB
[메모리] forecast_theta 실행 후: 1598.84 MB (변화: +0.00 MB)
[INS]   [Theta] 완료  첫값=1.92e+07 (메모리: 1598.8 MB)
[INS]   [DB] 93행 저장 완료
[PROGRESS] [ 481/500] ( 96.2%)  >>  MTLS
[MTLS]   45분기 | 2015-03-31 ~ 2026-03-31
[MTLS]   [SARIMA] 시작  (메모리: 1598.8 MB)
[메모리] forecast_sarima 실행 전: 1598.84 MB
[메모리] find_best_sarima_params 실행 전: 1598.84 MB
[메모리] find_best_sarima_params 실행 후: 1598.84 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.84 MB (변화: +0.00 MB)
[MTLS]   [SARIMA] 완료  첫값=8.00e+07 (메모리: 1598.8 MB)
[MTLS]   [ETS] 시작  (메모리: 1598.8 MB)
[메모리] forecast_ets 실행 전: 1598.84 MB
[메모리] forecast_ets 실행 후: 1598.84 MB (변화: +0.00 MB)
[MTLS]   [ETS] 완료  첫값=7.80e+07 (메모리: 1598.8 MB)
[MTLS]   [Prophet] 시작  (메모리: 1598.8 MB)

03:04:02 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1598.84 MB

03:04:02 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1598.86 MB (변화: +0.02 MB)
[MTLS]   [Prophet] 완료  첫값=7.52e+07 (메모리: 1598.9 MB)
[MTLS]   [LSTM] 시작  (메모리: 1598.9 MB)
[메모리] forecast_lstm 실행 전: 1598.86 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.85 MB (변화: -0.01 MB)
[MTLS]   [LSTM] 완료  첫값=6.97e+07 (메모리: 1598.8 MB)
[MTLS]   [Theta] 시작  (메모리: 1598.8 MB)
[메모리] forecast_theta 실행 전: 1598.85 MB
[메모리] forecast_theta 실행 후: 1598.85 MB (변화: +0.00 MB)
[MTLS]   [Theta] 완료  첫값=7.71e+07 (메모리: 1598.8 MB)
[MTLS]   [DB] 93행 저장 완료
[PROGRESS] [ 482/500] ( 96.4%)  >>  SNMP
[SNMP]   45분기 | 2015-03-31 ~ 2026-03-31
[SNMP]   [SARIMA] 시작  (메모리: 1598.8 MB)
[메모리] forecast_sarima 실행 전: 1598.85 MB
[메모리] find_best_sarima_params 실행 전: 1598.85 MB
[메모리] find_best_sarima_params 실행 후: 1598.85 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.85 MB (변화: +0.00 MB)
[SNMP]   [SARIMA] 완료  첫값=5.92e+06 (메모리: 1598.8 MB)
[SNMP]   [ETS] 시작  (메모리: 1598.8 MB)
[메모리] forecast_ets 실행 전: 1598.85 MB
[메모리] forecast_ets 실행 후: 1598.85 MB (변화: +0.00 MB)
[SNMP]   [ETS] 완료  첫값=4.46e+06 (메모리: 1598.9 MB)
[SNMP]   [Prophet] 시작  (메모리: 1598.9 MB)

03:04:20 - cmdstanpy - INFO - Chain [1] start processing
03:04:21 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1598.85 MB
[메모리] forecast_prophet 실행 후: 1598.87 MB (변화: +0.02 MB)
[SNMP]   [Prophet] 완료  첫값=4.22e+06 (메모리: 1598.9 MB)
[SNMP]   [LSTM] 시작  (메모리: 1598.9 MB)
[메모리] forecast_lstm 실행 전: 1598.87 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.92 MB (변화: +0.05 MB)
[SNMP]   [LSTM] 완료  첫값=4.92e+06 (메모리: 1598.9 MB)
[SNMP]   [Theta] 시작  (메모리: 1598.9 MB)
[메모리] forecast_theta 실행 전: 1598.92 MB
[메모리] forecast_theta 실행 후: 1598.92 MB (변화: +0.00 MB)
[SNMP]   [Theta] 완료  첫값=4.87e+06 (메모리: 1598.9 MB)
[SNMP]   [DB] 93행 저장 완료
[PROGRESS] [ 483/500] ( 96.6%)  >>  OFLX
[OFLX]   45분기 | 2015-03-31 ~ 2026-03-31
[OFLX]   [SARIMA] 시작  (메모리: 1598.9 MB)
[메모리] forecast_sarima 실행 전: 1598.92 MB
[메모리] find_best_sarima_params 실행 전: 1598.92 MB
[메모리] find_best_sarima_params 실행 후: 1598.92 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.92 MB (변화: +0.00 MB)
[OFLX]   [SARIMA] 완료  첫값=2.35e+07 (메모리: 1598.9 MB)
[OFLX]   [ETS] 시작  (메모리: 1598.9 MB)
[메모리] forecast_ets 실행 전: 1598.92 MB
[메모리] forecast_ets 실행 후: 1598.93 MB (변화: +0.00 MB)
[OFLX]   [ETS] 완료  첫값=2.37e+07 (메모리: 1598.9 MB)
[OFLX]   [Prophet] 시작  (메모리: 1598.9 MB)

03:04:45 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1598.93 MB

03:04:45 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1598.93 MB (변화: +0.00 MB)
[OFLX]   [Prophet] 완료  첫값=2.44e+07 (메모리: 1598.9 MB)
[OFLX]   [LSTM] 시작  (메모리: 1598.9 MB)
[메모리] forecast_lstm 실행 전: 1598.93 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.91 MB (변화: -0.02 MB)
[OFLX]   [LSTM] 완료  첫값=2.54e+07 (메모리: 1598.9 MB)
[OFLX]   [Theta] 시작  (메모리: 1598.9 MB)
[메모리] forecast_theta 실행 전: 1598.91 MB
[메모리] forecast_theta 실행 후: 1598.91 MB (변화: +0.00 MB)
[OFLX]   [Theta] 완료  첫값=2.37e+07 (메모리: 1598.9 MB)
[OFLX]   [DB] 93행 저장 완료
[PROGRESS] [ 484/500] ( 96.8%)  >>  RMNI
[RMNI]   45분기 | 2015-03-31 ~ 2026-03-31
[RMNI]   [SARIMA] 시작  (메모리: 1598.9 MB)
[메모리] forecast_sarima 실행 전: 1598.91 MB
[메모리] find_best_sarima_params 실행 전: 1598.91 MB
[메모리] find_best_sarima_params 실행 후: 1598.91 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.91 MB (변화: +0.00 MB)
[RMNI]   [SARIMA] 완료  첫값=1.01e+08 (메모리: 1598.9 MB)
[RMNI]   [ETS] 시작  (메모리: 1598.9 MB)
[메모리] forecast_ets 실행 전: 1598.91 MB
[메모리] forecast_ets 실행 후: 1598.92 MB (변화: +0.00 MB)
[RMNI]   [ETS] 완료  첫값=1.18e+08 (메모리: 1598.9 MB)
[RMNI]   [Prophet] 시작  (메모리: 1598.9 MB)

03:05:03 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1598.92 MB

03:05:03 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1598.93 MB (변화: +0.02 MB)
[RMNI]   [Prophet] 완료  첫값=1.25e+08 (메모리: 1598.9 MB)
[RMNI]   [LSTM] 시작  (메모리: 1598.9 MB)
[메모리] forecast_lstm 실행 전: 1598.93 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.88 MB (변화: -0.05 MB)
[RMNI]   [LSTM] 완료  첫값=1.14e+08 (메모리: 1598.9 MB)
[RMNI]   [Theta] 시작  (메모리: 1598.9 MB)
[메모리] forecast_theta 실행 전: 1598.88 MB
[메모리] forecast_theta 실행 후: 1598.88 MB (변화: +0.00 MB)
[RMNI]   [Theta] 완료  첫값=1.03e+08 (메모리: 1598.9 MB)
[RMNI]   [DB] 93행 저장 완료
[PROGRESS] [ 485/500] ( 97.0%)  >>  LWAY
[LWAY]   45분기 | 2015-03-31 ~ 2026-03-31
[LWAY]   [SARIMA] 시작  (메모리: 1598.9 MB)
[메모리] forecast_sarima 실행 전: 1598.88 MB
[메모리] find_best_sarima_params 실행 전: 1598.88 MB
[메모리] find_best_sarima_params 실행 후: 1598.91 MB (변화: +0.02 MB)
[메모리] forecast_sarima 실행 후: 1598.91 MB (변화: +0.02 MB)
[LWAY]   [SARIMA] 완료  첫값=6.29e+07 (메모리: 1598.9 MB)
[LWAY]   [ETS] 시작  (메모리: 1598.9 MB)
[메모리] forecast_ets 실행 전: 1598.91 MB
[메모리] forecast_ets 실행 후: 1598.91 MB (변화: +0.00 MB)
[LWAY]   [ETS] 완료  첫값=6.50e+07 (메모리: 1598.9 MB)
[LWAY]   [Prophet] 시작  (메모리: 1598.9 MB)

03:05:25 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1598.91 MB

03:05:25 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1598.92 MB (변화: +0.01 MB)
[LWAY]   [Prophet] 완료  첫값=5.75e+07 (메모리: 1598.9 MB)
[LWAY]   [LSTM] 시작  (메모리: 1598.9 MB)
[메모리] forecast_lstm 실행 전: 1598.92 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1599.00 MB (변화: +0.09 MB)
[LWAY]   [LSTM] 완료  첫값=6.26e+07 (메모리: 1599.0 MB)
[LWAY]   [Theta] 시작  (메모리: 1599.0 MB)
[메모리] forecast_theta 실행 전: 1599.00 MB
[메모리] forecast_theta 실행 후: 1599.00 MB (변화: +0.00 MB)
[LWAY]   [Theta] 완료  첫값=5.70e+07 (메모리: 1599.0 MB)
[LWAY]   [DB] 93행 저장 완료
[PROGRESS] [ 486/500] ( 97.2%)  >>  SVC
[SVC]   45분기 | 2015-03-31 ~ 2026-03-31
[SVC]   [SARIMA] 시작  (메모리: 1599.0 MB)
[메모리] forecast_sarima 실행 전: 1599.00 MB
[메모리] find_best_sarima_params 실행 전: 1599.00 MB
[메모리] find_best_sarima_params 실행 후: 1599.00 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1599.00 MB (변화: +0.00 MB)
[SVC]   [SARIMA] 완료  첫값=4.79e+08 (메모리: 1599.0 MB)
[SVC]   [ETS] 시작  (메모리: 1599.0 MB)
[메모리] forecast_ets 실행 전: 1599.00 MB
[메모리] forecast_ets 실행 후: 1599.00 MB (변화: +0.00 MB)
[SVC]   [ETS] 완료  첫값=5.22e+08 (메모리: 1599.0 MB)
[SVC]   [Prophet] 시작  (메모리: 1599.0 MB)

03:05:47 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1599.00 MB

03:05:47 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1599.02 MB (변화: +0.02 MB)
[SVC]   [Prophet] 완료  첫값=4.39e+08 (메모리: 1599.0 MB)
[SVC]   [LSTM] 시작  (메모리: 1599.0 MB)
[메모리] forecast_lstm 실행 전: 1599.02 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.98 MB (변화: -0.04 MB)
[SVC]   [LSTM] 완료  첫값=4.71e+08 (메모리: 1599.0 MB)
[SVC]   [Theta] 시작  (메모리: 1599.0 MB)
[메모리] forecast_theta 실행 전: 1598.98 MB
[메모리] forecast_theta 실행 후: 1598.98 MB (변화: +0.00 MB)
[SVC]   [Theta] 완료  첫값=4.78e+08 (메모리: 1599.0 MB)
[SVC]   [DB] 93행 저장 완료
[PROGRESS] [ 487/500] ( 97.4%)  >>  EVI
[EVI]   45분기 | 2015-03-31 ~ 2026-03-31
[EVI]   [SARIMA] 시작  (메모리: 1599.0 MB)
[메모리] forecast_sarima 실행 전: 1598.98 MB
[메모리] find_best_sarima_params 실행 전: 1598.98 MB
[메모리] find_best_sarima_params 실행 후: 1598.98 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.98 MB (변화: +0.00 MB)
[EVI]   [SARIMA] 완료  첫값=1.20e+08 (메모리: 1599.0 MB)
[EVI]   [ETS] 시작  (메모리: 1599.0 MB)
[메모리] forecast_ets 실행 전: 1598.98 MB
[메모리] forecast_ets 실행 후: 1598.98 MB (변화: +0.00 MB)
[EVI]   [ETS] 완료  첫값=1.30e+08 (메모리: 1599.0 MB)
[EVI]   [Prophet] 시작  (메모리: 1599.0 MB)

03:06:06 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1598.98 MB

03:06:06 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1598.98 MB (변화: +0.00 MB)
[EVI]   [Prophet] 완료  첫값=1.15e+08 (메모리: 1599.0 MB)
[EVI]   [LSTM] 시작  (메모리: 1599.0 MB)
[메모리] forecast_lstm 실행 전: 1598.98 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.97 MB (변화: -0.02 MB)
[EVI]   [LSTM] 완료  첫값=1.10e+08 (메모리: 1599.0 MB)
[EVI]   [Theta] 시작  (메모리: 1599.0 MB)
[메모리] forecast_theta 실행 전: 1598.97 MB
[메모리] forecast_theta 실행 후: 1598.97 MB (변화: +0.00 MB)
[EVI]   [Theta] 완료  첫값=1.13e+08 (메모리: 1599.0 MB)
[EVI]   [DB] 93행 저장 완료
[PROGRESS] [ 488/500] ( 97.6%)  >>  OOMA
[OOMA]   45분기 | 2015-03-31 ~ 2026-03-31
[OOMA]   [SARIMA] 시작  (메모리: 1599.0 MB)
[메모리] forecast_sarima 실행 전: 1598.97 MB
[메모리] find_best_sarima_params 실행 전: 1598.97 MB
[메모리] find_best_sarima_params 실행 후: 1598.97 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.97 MB (변화: +0.00 MB)
[OOMA]   [SARIMA] 완료  첫값=6.86e+07 (메모리: 1599.0 MB)
[OOMA]   [ETS] 시작  (메모리: 1599.0 MB)
[메모리] forecast_ets 실행 전: 1598.97 MB
[메모리] forecast_ets 실행 후: 1598.97 MB (변화: +0.00 MB)
[OOMA]   [ETS] 완료  첫값=6.72e+07 (메모리: 1599.0 MB)
[OOMA]   [Prophet] 시작  (메모리: 1599.0 MB)

03:06:30 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1598.97 MB

03:06:30 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1598.97 MB (변화: +0.00 MB)
[OOMA]   [Prophet] 완료  첫값=6.97e+07 (메모리: 1599.0 MB)
[OOMA]   [LSTM] 시작  (메모리: 1599.0 MB)
[메모리] forecast_lstm 실행 전: 1598.97 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.92 MB (변화: -0.05 MB)
[OOMA]   [LSTM] 완료  첫값=7.13e+07 (메모리: 1598.9 MB)
[OOMA]   [Theta] 시작  (메모리: 1598.9 MB)
[메모리] forecast_theta 실행 전: 1598.92 MB
[메모리] forecast_theta 실행 후: 1598.92 MB (변화: +0.00 MB)
[OOMA]   [Theta] 완료  첫값=6.68e+07 (메모리: 1598.9 MB)
[OOMA]   [DB] 93행 저장 완료
[PROGRESS] [ 489/500] ( 97.8%)  >>  MLP
[MLP]   45분기 | 2015-03-31 ~ 2026-03-31
[MLP]   [SARIMA] 시작  (메모리: 1598.9 MB)
[메모리] forecast_sarima 실행 전: 1598.92 MB
[메모리] find_best_sarima_params 실행 전: 1598.92 MB
[메모리] find_best_sarima_params 실행 후: 1598.92 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.92 MB (변화: +0.00 MB)
[MLP]   [SARIMA] 완료  첫값=6.39e+06 (메모리: 1598.9 MB)
[MLP]   [ETS] 시작  (메모리: 1598.9 MB)
[메모리] forecast_ets 실행 전: 1598.92 MB
[메모리] forecast_ets 실행 후: 1598.92 MB (변화: +0.00 MB)
[MLP]   [ETS] 완료  첫값=6.14e+06 (메모리: 1598.9 MB)
[MLP]   [Prophet] 시작  (메모리: 1598.9 MB)

03:06:54 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1598.92 MB

03:06:54 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1598.87 MB (변화: -0.05 MB)
[MLP]   [Prophet] 완료  첫값=2.27e+06 (메모리: 1598.9 MB)
[MLP]   [LSTM] 시작  (메모리: 1598.9 MB)
[메모리] forecast_lstm 실행 전: 1598.87 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.90 MB (변화: +0.03 MB)
[MLP]   [LSTM] 완료  첫값=3.19e+06 (메모리: 1598.9 MB)
[MLP]   [Theta] 시작  (메모리: 1598.9 MB)
[메모리] forecast_theta 실행 전: 1598.90 MB
[메모리] forecast_theta 실행 후: 1598.90 MB (변화: +0.00 MB)
[MLP]   [Theta] 완료  첫값=4.37e+06 (메모리: 1598.9 MB)
[MLP]   [DB] 93행 저장 완료
[PROGRESS] [ 490/500] ( 98.0%)  >>  STRT
[STRT]   45분기 | 2015-03-31 ~ 2026-03-31
[STRT]   [SARIMA] 시작  (메모리: 1598.9 MB)
[메모리] forecast_sarima 실행 전: 1598.90 MB
[메모리] find_best_sarima_params 실행 전: 1598.90 MB
[메모리] find_best_sarima_params 실행 후: 1598.90 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.90 MB (변화: +0.00 MB)
[STRT]   [SARIMA] 완료  첫값=1.40e+08 (메모리: 1598.9 MB)
[STRT]   [ETS] 시작  (메모리: 1598.9 MB)
[메모리] forecast_ets 실행 전: 1598.90 MB
[메모리] forecast_ets 실행 후: 1598.90 MB (변화: +0.00 MB)
[STRT]   [ETS] 완료  첫값=1.35e+08 (메모리: 1598.9 MB)
[STRT]   [Prophet] 시작  (메모리: 1598.9 MB)

03:07:14 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1598.90 MB

03:07:14 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1598.90 MB (변화: +0.00 MB)
[STRT]   [Prophet] 완료  첫값=1.41e+08 (메모리: 1598.9 MB)
[STRT]   [LSTM] 시작  (메모리: 1598.9 MB)
[메모리] forecast_lstm 실행 전: 1598.90 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1599.14 MB (변화: +0.25 MB)
[STRT]   [LSTM] 완료  첫값=1.27e+08 (메모리: 1599.1 MB)
[STRT]   [Theta] 시작  (메모리: 1599.1 MB)
[메모리] forecast_theta 실행 전: 1599.14 MB
[메모리] forecast_theta 실행 후: 1599.14 MB (변화: +0.00 MB)
[STRT]   [Theta] 완료  첫값=1.42e+08 (메모리: 1599.1 MB)
[STRT]   [DB] 93행 저장 완료
[PROGRESS] [ 491/500] ( 98.2%)  >>  LFCR
[LFCR]   45분기 | 2015-03-31 ~ 2026-03-31
[LFCR]   [SARIMA] 시작  (메모리: 1599.1 MB)
[메모리] forecast_sarima 실행 전: 1599.14 MB
[메모리] find_best_sarima_params 실행 전: 1599.14 MB
[메모리] find_best_sarima_params 실행 후: 1599.14 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1599.14 MB (변화: +0.00 MB)
[LFCR]   [SARIMA] 완료  첫값=3.28e+07 (메모리: 1599.1 MB)
[LFCR]   [ETS] 시작  (메모리: 1599.1 MB)
[메모리] forecast_ets 실행 전: 1599.14 MB
[메모리] forecast_ets 실행 후: 1599.15 MB (변화: +0.01 MB)
[LFCR]   [ETS] 완료  첫값=3.64e+07 (메모리: 1599.2 MB)
[LFCR]   [Prophet] 시작  (메모리: 1599.2 MB)

03:07:31 - cmdstanpy - INFO - Chain [1] start processing
03:07:31 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1599.15 MB
[메모리] forecast_prophet 실행 후: 1598.90 MB (변화: -0.25 MB)
[LFCR]   [Prophet] 완료  첫값=1.29e+07 (메모리: 1598.9 MB)
[LFCR]   [LSTM] 시작  (메모리: 1598.9 MB)
[메모리] forecast_lstm 실행 전: 1598.90 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.75 MB (변화: -0.15 MB)
[LFCR]   [LSTM] 완료  첫값=3.02e+07 (메모리: 1598.7 MB)
[LFCR]   [Theta] 시작  (메모리: 1598.7 MB)
[메모리] forecast_theta 실행 전: 1598.75 MB
[메모리] forecast_theta 실행 후: 1598.75 MB (변화: +0.00 MB)
[LFCR]   [Theta] 완료  첫값=3.55e+07 (메모리: 1598.7 MB)
[LFCR]   [DB] 93행 저장 완료
[PROGRESS] [ 492/500] ( 98.4%)  >>  PKOH
[PKOH]   45분기 | 2015-03-31 ~ 2026-03-31
[PKOH]   [SARIMA] 시작  (메모리: 1598.7 MB)
[메모리] forecast_sarima 실행 전: 1598.75 MB
[메모리] find_best_sarima_params 실행 전: 1598.75 MB
[메모리] find_best_sarima_params 실행 후: 1598.75 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1598.75 MB (변화: +0.00 MB)
[PKOH]   [SARIMA] 완료  첫값=3.97e+08 (메모리: 1598.7 MB)
[PKOH]   [ETS] 시작  (메모리: 1598.7 MB)
[메모리] forecast_ets 실행 전: 1598.75 MB
[메모리] forecast_ets 실행 후: 1598.75 MB (변화: +0.00 MB)
[PKOH]   [ETS] 완료  첫값=3.96e+08 (메모리: 1598.8 MB)
[PKOH]   [Prophet] 시작  (메모리: 1598.8 MB)

03:07:57 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1598.75 MB

03:07:57 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1600.39 MB (변화: +1.64 MB)
[PKOH]   [Prophet] 완료  첫값=3.99e+08 (메모리: 1600.4 MB)
[PKOH]   [LSTM] 시작  (메모리: 1600.4 MB)
[메모리] forecast_lstm 실행 전: 1600.39 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1599.58 MB (변화: -0.80 MB)
[PKOH]   [LSTM] 완료  첫값=5.01e+08 (메모리: 1599.6 MB)
[PKOH]   [Theta] 시작  (메모리: 1599.6 MB)
[메모리] forecast_theta 실행 전: 1599.58 MB
[메모리] forecast_theta 실행 후: 1599.58 MB (변화: +0.00 MB)
[PKOH]   [Theta] 완료  첫값=4.02e+08 (메모리: 1599.6 MB)
[PKOH]   [DB] 93행 저장 완료
[PROGRESS] [ 493/500] ( 98.6%)  >>  PBYI
[PBYI]   45분기 | 2015-03-31 ~ 2026-03-31
[PBYI]   [SARIMA] 시작  (메모리: 1599.6 MB)
[메모리] forecast_sarima 실행 전: 1599.58 MB
[메모리] find_best_sarima_params 실행 전: 1599.58 MB
[메모리] find_best_sarima_params 실행 후: 1599.58 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1599.58 MB (변화: +0.00 MB)
[PBYI]   [SARIMA] 완료  첫값=5.23e+07 (메모리: 1599.6 MB)
[PBYI]   [ETS] 시작  (메모리: 1599.6 MB)
[메모리] forecast_ets 실행 전: 1599.58 MB
[메모리] forecast_ets 실행 후: 1599.59 MB (변화: +0.00 MB)
[PBYI]   [ETS] 완료  첫값=5.62e+07 (메모리: 1599.6 MB)
[PBYI]   [Prophet] 시작  (메모리: 1599.6 MB)

03:08:11 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1599.59 MB

03:08:12 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1600.40 MB (변화: +0.82 MB)
[PBYI]   [Prophet] 완료  첫값=7.54e+07 (메모리: 1600.4 MB)
[PBYI]   [LSTM] 시작  (메모리: 1600.4 MB)
[메모리] forecast_lstm 실행 전: 1600.40 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1599.55 MB (변화: -0.85 MB)
[PBYI]   [LSTM] 완료  첫값=5.63e+07 (메모리: 1599.6 MB)
[PBYI]   [Theta] 시작  (메모리: 1599.6 MB)
[메모리] forecast_theta 실행 전: 1599.55 MB
[메모리] forecast_theta 실행 후: 1599.55 MB (변화: +0.00 MB)
[PBYI]   [Theta] 완료  첫값=4.98e+07 (메모리: 1599.6 MB)
[PBYI]   [DB] 93행 저장 완료
[PROGRESS] [ 494/500] ( 98.8%)  >>  MPX
[MPX]   45분기 | 2015-03-31 ~ 2026-03-31
[MPX]   [SARIMA] 시작  (메모리: 1599.6 MB)
[메모리] forecast_sarima 실행 전: 1599.55 MB
[메모리] find_best_sarima_params 실행 전: 1599.55 MB
[메모리] find_best_sarima_params 실행 후: 1599.56 MB (변화: +0.01 MB)
[메모리] forecast_sarima 실행 후: 1599.56 MB (변화: +0.01 MB)
[MPX]   [SARIMA] 완료  첫값=6.77e+07 (메모리: 1599.6 MB)
[MPX]   [ETS] 시작  (메모리: 1599.6 MB)
[메모리] forecast_ets 실행 전: 1599.56 MB
[메모리] forecast_ets 실행 후: 1599.56 MB (변화: +0.00 MB)
[MPX]   [ETS] 완료  첫값=6.72e+07 (메모리: 1599.6 MB)
[MPX]   [Prophet] 시작  (메모리: 1599.6 MB)

03:08:35 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1599.56 MB

03:08:35 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1598.75 MB (변화: -0.81 MB)
[MPX]   [Prophet] 완료  첫값=7.75e+07 (메모리: 1598.8 MB)
[MPX]   [LSTM] 시작  (메모리: 1598.8 MB)
[메모리] forecast_lstm 실행 전: 1598.75 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1599.73 MB (변화: +0.97 MB)
[MPX]   [LSTM] 완료  첫값=6.68e+07 (메모리: 1599.7 MB)
[MPX]   [Theta] 시작  (메모리: 1599.7 MB)
[메모리] forecast_theta 실행 전: 1599.73 MB
[메모리] forecast_theta 실행 후: 1599.73 MB (변화: +0.00 MB)
[MPX]   [Theta] 완료  첫값=6.40e+07 (메모리: 1599.7 MB)
[MPX]   [DB] 93행 저장 완료
[PROGRESS] [ 495/500] ( 99.0%)  >>  MIXT
[MIXT]   45분기 | 2015-03-31 ~ 2026-03-31
[MIXT]   [SARIMA] 시작  (메모리: 1599.7 MB)
[메모리] forecast_sarima 실행 전: 1599.73 MB
[메모리] find_best_sarima_params 실행 전: 1599.73 MB
[메모리] find_best_sarima_params 실행 후: 1599.73 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1599.73 MB (변화: +0.00 MB)
[MIXT]   [SARIMA] 완료  첫값=3.98e+07 (메모리: 1599.7 MB)
[MIXT]   [ETS] 시작  (메모리: 1599.7 MB)
[메모리] forecast_ets 실행 전: 1599.73 MB
[메모리] forecast_ets 실행 후: 1599.73 MB (변화: +0.00 MB)
[MIXT]   [ETS] 완료  첫값=3.85e+07 (메모리: 1599.7 MB)
[MIXT]   [Prophet] 시작  (메모리: 1599.7 MB)

03:08:54 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1599.73 MB

03:08:54 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1598.75 MB (변화: -0.98 MB)
[MIXT]   [Prophet] 완료  첫값=4.11e+07 (메모리: 1598.8 MB)
[MIXT]   [LSTM] 시작  (메모리: 1598.8 MB)
[메모리] forecast_lstm 실행 전: 1598.75 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1599.71 MB (변화: +0.96 MB)
[MIXT]   [LSTM] 완료  첫값=3.81e+07 (메모리: 1599.7 MB)
[MIXT]   [Theta] 시작  (메모리: 1599.7 MB)
[메모리] forecast_theta 실행 전: 1599.71 MB
[메모리] forecast_theta 실행 후: 1599.71 MB (변화: +0.00 MB)
[MIXT]   [Theta] 완료  첫값=3.73e+07 (메모리: 1599.7 MB)
[MIXT]   [DB] 93행 저장 완료
[PROGRESS] [ 496/500] ( 99.2%)  >>  DENN
[DENN]   44분기 | 2015-06-30 ~ 2026-03-31
[DENN]   [SARIMA] 시작  (메모리: 1599.7 MB)
[메모리] forecast_sarima 실행 전: 1599.71 MB
[메모리] find_best_sarima_params 실행 전: 1599.71 MB
[메모리] find_best_sarima_params 실행 후: 1599.72 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1599.72 MB (변화: +0.00 MB)
[DENN]   [SARIMA] 완료  첫값=1.13e+08 (메모리: 1599.7 MB)
[DENN]   [ETS] 시작  (메모리: 1599.7 MB)
[메모리] forecast_ets 실행 전: 1599.72 MB
[메모리] forecast_ets 실행 후: 1599.72 MB (변화: +0.00 MB)
[DENN]   [ETS] 완료  첫값=1.09e+08 (메모리: 1599.7 MB)
[DENN]   [Prophet] 시작  (메모리: 1599.7 MB)

03:09:15 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1599.72 MB

03:09:15 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1599.74 MB (변화: +0.02 MB)
[DENN]   [Prophet] 완료  첫값=1.05e+08 (메모리: 1599.7 MB)
[DENN]   [LSTM] 시작  (메모리: 1599.7 MB)
[메모리] forecast_lstm 실행 전: 1599.74 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1599.75 MB (변화: +0.02 MB)
[DENN]   [LSTM] 완료  첫값=1.13e+08 (메모리: 1599.8 MB)
[DENN]   [Theta] 시작  (메모리: 1599.8 MB)
[메모리] forecast_theta 실행 전: 1599.75 MB
[메모리] forecast_theta 실행 후: 1599.75 MB (변화: +0.00 MB)
[DENN]   [Theta] 완료  첫값=1.13e+08 (메모리: 1599.8 MB)
[DENN]   [DB] 92행 저장 완료
[PROGRESS] [ 497/500] ( 99.4%)  >>  NEO
[NEO]   45분기 | 2015-03-31 ~ 2026-03-31
[NEO]   [SARIMA] 시작  (메모리: 1599.8 MB)
[메모리] forecast_sarima 실행 전: 1599.75 MB
[메모리] find_best_sarima_params 실행 전: 1599.75 MB
[메모리] find_best_sarima_params 실행 후: 1599.75 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1599.75 MB (변화: +0.00 MB)
[NEO]   [SARIMA] 완료  첫값=1.97e+08 (메모리: 1599.8 MB)
[NEO]   [ETS] 시작  (메모리: 1599.8 MB)
[메모리] forecast_ets 실행 전: 1599.75 MB
[메모리] forecast_ets 실행 후: 1599.75 MB (변화: +0.00 MB)
[NEO]   [ETS] 완료  첫값=1.94e+08 (메모리: 1599.8 MB)
[NEO]   [Prophet] 시작  (메모리: 1599.8 MB)

03:09:36 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1599.75 MB

03:09:36 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1598.90 MB (변화: -0.85 MB)
[NEO]   [Prophet] 완료  첫값=1.92e+08 (메모리: 1598.9 MB)
[NEO]   [LSTM] 시작  (메모리: 1598.9 MB)
[메모리] forecast_lstm 실행 전: 1598.90 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1599.93 MB (변화: +1.02 MB)
[NEO]   [LSTM] 완료  첫값=1.94e+08 (메모리: 1599.9 MB)
[NEO]   [Theta] 시작  (메모리: 1599.9 MB)
[메모리] forecast_theta 실행 전: 1599.93 MB
[메모리] forecast_theta 실행 후: 1599.93 MB (변화: +0.00 MB)
[NEO]   [Theta] 완료  첫값=1.88e+08 (메모리: 1599.9 MB)
[NEO]   [DB] 93행 저장 완료
[PROGRESS] [ 498/500] ( 99.6%)  >>  AMRN
[AMRN]   45분기 | 2015-03-31 ~ 2026-03-31
[AMRN]   [SARIMA] 시작  (메모리: 1599.9 MB)
[메모리] forecast_sarima 실행 전: 1599.93 MB
[메모리] find_best_sarima_params 실행 전: 1599.93 MB
[메모리] find_best_sarima_params 실행 후: 1599.93 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1599.93 MB (변화: +0.00 MB)
[AMRN]   [SARIMA] 완료  첫값=4.65e+07 (메모리: 1599.9 MB)
[AMRN]   [ETS] 시작  (메모리: 1599.9 MB)
[메모리] forecast_ets 실행 전: 1599.93 MB
[메모리] forecast_ets 실행 후: 1599.93 MB (변화: +0.00 MB)
[AMRN]   [ETS] 완료  첫값=5.14e+07 (메모리: 1599.9 MB)
[AMRN]   [Prophet] 시작  (메모리: 1599.9 MB)

03:09:59 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1599.93 MB

03:09:59 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1599.36 MB (변화: -0.57 MB)
[AMRN]   [Prophet] 완료  첫값=9.70e+07 (메모리: 1599.4 MB)
[AMRN]   [LSTM] 시작  (메모리: 1599.4 MB)
[메모리] forecast_lstm 실행 전: 1599.36 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1599.36 MB (변화: -0.00 MB)
[AMRN]   [LSTM] 완료  첫값=7.70e+07 (메모리: 1599.4 MB)
[AMRN]   [Theta] 시작  (메모리: 1599.4 MB)
[메모리] forecast_theta 실행 전: 1599.36 MB
[메모리] forecast_theta 실행 후: 1599.36 MB (변화: +0.00 MB)
[AMRN]   [Theta] 완료  첫값=5.58e+07 (메모리: 1599.4 MB)
[AMRN]   [DB] 93행 저장 완료
[PROGRESS] [ 499/500] ( 99.8%)  >>  LOCO
[LOCO]   44분기 | 2015-06-30 ~ 2026-03-31
[LOCO]   [SARIMA] 시작  (메모리: 1599.4 MB)
[메모리] forecast_sarima 실행 전: 1599.36 MB
[메모리] find_best_sarima_params 실행 전: 1599.36 MB
[메모리] find_best_sarima_params 실행 후: 1599.36 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1599.36 MB (변화: +0.00 MB)
[LOCO]   [SARIMA] 완료  첫값=1.22e+08 (메모리: 1599.4 MB)
[LOCO]   [ETS] 시작  (메모리: 1599.4 MB)
[메모리] forecast_ets 실행 전: 1599.36 MB
[메모리] forecast_ets 실행 후: 1599.36 MB (변화: +0.00 MB)
[LOCO]   [ETS] 완료  첫값=1.29e+08 (메모리: 1599.4 MB)
[LOCO]   [Prophet] 시작  (메모리: 1599.4 MB)

03:10:26 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1599.36 MB

03:10:26 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1599.39 MB (변화: +0.03 MB)
[LOCO]   [Prophet] 완료  첫값=1.24e+08 (메모리: 1599.4 MB)
[LOCO]   [LSTM] 시작  (메모리: 1599.4 MB)
[메모리] forecast_lstm 실행 전: 1599.39 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1600.11 MB (변화: +0.72 MB)
[LOCO]   [LSTM] 완료  첫값=1.20e+08 (메모리: 1600.1 MB)
[LOCO]   [Theta] 시작  (메모리: 1600.1 MB)
[메모리] forecast_theta 실행 전: 1600.11 MB
[메모리] forecast_theta 실행 후: 1600.11 MB (변화: +0.00 MB)
[LOCO]   [Theta] 완료  첫값=1.28e+08 (메모리: 1600.1 MB)
[LOCO]   [DB] 92행 저장 완료
[PROGRESS] [ 500/500] (100.0%)  >>  BNTC
[BNTC]   45분기 | 2015-03-31 ~ 2026-03-31
[BNTC]   [SARIMA] 시작  (메모리: 1600.1 MB)
[메모리] forecast_sarima 실행 전: 1600.11 MB
[메모리] find_best_sarima_params 실행 전: 1600.11 MB
[메모리] find_best_sarima_params 실행 후: 1600.11 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1600.11 MB (변화: +0.00 MB)
[BNTC]   [SARIMA] 완료  첫값=-6.71e+05 (메모리: 1600.1 MB)
[BNTC]   [ETS] 시작  (메모리: 1600.1 MB)
[메모리] forecast_ets 실행 전: 1600.11 MB
[메모리] forecast_ets 실행 후: 1600.11 MB (변화: +0.00 MB)
[BNTC]   [ETS] 완료  첫값=-3.20e+05 (메모리: 1600.1 MB)
[BNTC]   [Prophet] 시작  (메모리: 1600.1 MB)

03:10:41 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1600.11 MB

03:10:41 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1600.11 MB (변화: +0.01 MB)
[BNTC]   [Prophet] 완료  첫값=1.79e+04 (메모리: 1600.1 MB)
[BNTC]   [LSTM] 시작  (메모리: 1600.1 MB)
[메모리] forecast_lstm 실행 전: 1600.11 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1598.36 MB (변화: -1.75 MB)
[BNTC]   [LSTM] 완료  첫값=3.74e+05 (메모리: 1598.4 MB)
[BNTC]   [Theta] 시작  (메모리: 1598.4 MB)
[메모리] forecast_theta 실행 전: 1598.36 MB
[메모리] forecast_theta 실행 후: 1598.36 MB (변화: +0.00 MB)
[BNTC]   [Theta] 완료  첫값=-5.20e+03 (메모리: 1598.4 MB)
[BNTC]   [DB] 93행 저장 완료
[BATCH] ======================================================================
[BATCH] 완료 | 성공: 483  스킵: 17  오류: 0  합계: 500
[BATCH] 스킵 티커  : ['MBX', 'SWIR', 'EZT', 'PVLA', 'WBI', 'LOT', 'HDL', 'TCRZ', 'BTX', 'RZLV', 'BGM', 'AIC', 'TBN', 'ODV', 'KOR', 'FVR', 'SMC']
[BATCH] ======================================================================

## Cell 14 · 저장 결과 조회

배치 완료 후 DB 에 저장된 결과를 확인합니다.

In [14]:
# ── 오늘 예측된 티커 × 모델별 요약 ──────────────────────────
with engine.connect() as conn:
    summary_df = pd.read_sql(
        text(f"""
            SELECT
                ticker,
                item,
                model,
                MIN(date)  AS date_from,
                MAX(date)  AS date_to,
                COUNT(*)   AS row_count,
                forecast_date
            FROM   `{DEST_TABLE}`
            WHERE  forecast_date = :fd
            GROUP  BY ticker, item, model, forecast_date
            ORDER  BY ticker, model
        """),
        conn,
        params={"fd": FORECAST_DATE},
    )

print(f"[오늘({FORECAST_DATE}) 예측 저장 결과: {len(summary_df)}건]")
display(summary_df)

OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query ([WinError 10053] 현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다)')
[SQL:
            SELECT
                ticker,
                item,
                model,
                MIN(date)  AS date_from,
                MAX(date)  AS date_to,
                COUNT(*)   AS row_count,
                forecast_date
            FROM   `us_revenue_forecast_data`
            WHERE  forecast_date = %(fd)s
            GROUP  BY ticker, item, model, forecast_date
            ORDER  BY ticker, model
        ]
[parameters: {'fd': '2026-03-27'}]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [15]:
# ── 전체 DB 저장 통계 ─────────────────────────────────────
with engine.connect() as conn:
    total_stat = pd.read_sql(
        text(f"""
            SELECT
                forecast_date,
                COUNT(DISTINCT ticker) AS ticker_cnt,
                COUNT(DISTINCT model)  AS model_cnt,
                COUNT(*)               AS total_rows
            FROM   `{DEST_TABLE}`
            GROUP  BY forecast_date
            ORDER  BY forecast_date DESC
            LIMIT  10
        """),
        conn,
    )

print("[전체 DB 저장 현황 (최근 10개 예측일)]")
display(total_stat)

[전체 DB 저장 현황 (최근 10개 예측일)]

  forecast_date  ticker_cnt  model_cnt  total_rows
0    2026-03-27         484          7       44964
1    2026-03-26         688          7       63891
2    2026-03-25        1733          7      160980
3    2026-03-24        1170          7      108691