# US Revenue Forecast v2 — 단계별 테스트 노트북

**소스 테이블** : `US_IS_from_FMP`  
**저장 테이블** : `us_revenue_forecast_data`  
**예측 모델**  : SARIMA · ETS · Prophet · LSTM · Theta + Ensemble (SARIMA+ETS+Theta 평균)

---

| 셀 번호 | 단계 |
|---------|------|
| Cell 1  | 환경 설정 & 경로 자동 감지 |
| Cell 2  | 모듈 Import |
| Cell 3  | 파라미터 설정 |
| Cell 4  | DB 연결 테스트 |
| Cell 5  | 재무 데이터 추출 함수 정의 |
| Cell 6  | 단일 티커 데이터 추출 테스트 |
| Cell 7  | 예측 함수 정의 |
| Cell 8  | 단일 티커 예측 테스트 |
| Cell 9  | Long-format 변환 함수 정의 |
| Cell 10 | Long-format 변환 테스트 |
| Cell 11 | DB 테이블 생성 & 저장 함수 정의 |
| Cell 12 | 단일 티커 저장 테스트 |
| Cell 13 | 배치 실행 (전체 / 특정 티커 / 구간 지정) |
| Cell 14 | 저장 결과 조회 |

---
### ⚡ 메모리 전략
> **티커 1개씩 즉시 저장** 방식을 채택합니다.  
> 배치(20개 누적 후 저장)는 리스트가 메모리에 쌓여 오히려 OOM 위험이 높습니다.  
> 1개 예측 → 즉시 저장 → `clear_memory()` 호출 순서로 메모리를 최소 상태로 유지합니다.

### 🔢 구간 예측 (2000개 티커 단계적 처리)
> Cell 13 의 `TICKER_START` / `TICKER_END` 변수로 처리 구간을 지정하세요.  
> 예: 0~499 → 500~999 → ... 순서로 끊어서 실행하면 메모리 부담 없이 전체 예측 가능합니다.

## Cell 1 · 환경 설정 & 경로 자동 감지

노트북(Hoyoung_Park) / 데스크탑(82108) 어느 환경에서 실행해도  
`DATA` 폴더를 자동으로 찾아 `sys.path`에 추가합니다.

In [1]:
import sys, os, warnings
from pathlib import Path
warnings.filterwarnings("ignore")

# ── 후보 프로젝트 루트 (노트북 / 데스크탑) ───────────────────────
_CANDIDATE_ROOTS = [
    r"C:\Users\Hoyoung_Park\PyCharmMiscProject\stock_forecast",          # 노트북
    r"C:\Users\82108\OneDrive\바탕 화면\investment\investment_strategy",   # 데스크탑
]

def _setup_path() -> str:
    """
    프로젝트 루트(DATA/ 폴더의 부모)를 탐색해 sys.path 에 추가합니다.
    탐색 순서:
      1) __file__ 또는 cwd 기준 상위 경로 중 DATA/ 를 포함하는 첫 번째 경로
      2) _CANDIDATE_ROOTS 에서 실존하는 첫 번째 경로
    """
    try:
        start = Path(__file__).resolve().parent
    except NameError:          # 노트북 환경 — __file__ 없음
        start = Path.cwd()

    # 현재 경로부터 상위로 올라가며 DATA/ 탐색
    for p in [start] + list(start.parents):
        if (p / "DATA").is_dir():
            root = str(p)
            if root not in sys.path:
                sys.path.insert(0, root)
            print(f"[PATH] root 자동 감지 : {root}")
            return root

    # cwd 탐색에서 못 찾으면 후보 경로 시도
    for candidate in _CANDIDATE_ROOTS:
        if os.path.isdir(candidate) and os.path.isdir(os.path.join(candidate, "DATA")):
            if candidate not in sys.path:
                sys.path.insert(0, candidate)
            print(f"[PATH] root 후보 경로 : {candidate}")
            return candidate

    raise EnvironmentError(
        "DATA 폴더를 찾을 수 없습니다.\n"
        "_CANDIDATE_ROOTS 목록을 현재 환경에 맞게 수정하거나 "
        "노트북을 프로젝트 루트 아래에서 실행하세요."
    )

_ROOT = _setup_path()
print(f"[확인] 프로젝트 루트  : {_ROOT}")
print(f"[확인] DATA 경로     : {os.path.join(_ROOT, 'DATA')}")
print(f"[확인] sys.path[0]   : {sys.path[0]}")

[PATH] root 자동 감지 : C:\Users\Hoyoung_Park\PyCharmMiscProject\stock_forecast
[확인] 프로젝트 루트  : C:\Users\Hoyoung_Park\PyCharmMiscProject\stock_forecast
[확인] DATA 경로     : C:\Users\Hoyoung_Park\PyCharmMiscProject\stock_forecast\DATA
[확인] sys.path[0]   : C:\Users\Hoyoung_Park\PyCharmMiscProject\stock_forecast

## Cell 2 · 모듈 Import

`DATA` 폴더 내 세 모듈과 외부 라이브러리를 불러옵니다.

In [2]:
# ── 내부 모듈 (DATA 폴더) ─────────────────────────────────────
from DATA.config import get_db_info, get_engine
from DATA.us_target_ticker_list_2000 import ticker_list as DEFAULT_TICKER_LIST
from DATA.universal_ts_forecast_function_v2 import (
    forecast_sarima,
    forecast_ets,
    forecast_prophet,
    forecast_lstm,
    forecast_theta,
    infer_freq_alias,
    seasonal_periods_from_freq,
    clear_memory,
)

# ── 외부 라이브러리 ───────────────────────────────────────────
import gc
import traceback
from typing import Optional, List      # Python 3.9 호환 타입 힌트
import numpy as np
import pandas as pd
from datetime import datetime
from sqlalchemy import text
from IPython.display import display

# ── 로그 유틸 (config 에 log 가 없는 경우 자체 정의) ──────────
try:
    from DATA.config import log
except ImportError:
    def log(tag: str, msg: str):
        ts = datetime.now().strftime("%H:%M:%S")
        print(f"[{ts}][{tag}] {msg}")

print(f"[OK] 모든 모듈 Import 완료")
print(f"[OK] DEFAULT_TICKER_LIST 길이: {len(DEFAULT_TICKER_LIST):,}개")

[OK] 모든 모듈 Import 완료
[OK] DEFAULT_TICKER_LIST 길이: 2,000개

## Cell 3 · 파라미터 설정

항목·기간·모델·배치 등 전역 파라미터를 여기서만 수정합니다.

In [3]:
# ════════════════════════════════════════════════════════════
#  ★ 파라미터 — 필요에 따라 이 셀만 수정하세요 ★
# ════════════════════════════════════════════════════════════

# ── 테이블 ────────────────────────────────────────────────
# ── FMP API ──────────────────────────────────────────────
FMP_API_KEY    = "hT0gAk87j9xZx4PlBApvBqfVL5IahvgV"
FMP_BASE_URL   = "https://financialmodelingprep.com/api/v3"
FMP_MAX_RETRY  = 3
FMP_SLEEP_SEC  = 0.35

# ── 데이터 소스 선택 ──────────────────────────────────────
# "db"  : DB(US_IS_from_FMP) 에서 조회  — 빠름, DB 최신화 필요
# "fmp" : FMP API 에서 직접 조회        — 항상 최신, API 호출 비용
DATA_SOURCE    = "fmp"   # "db" 또는 "fmp"

SRC_TABLE  = "US_IS_from_FMP"           # 원본 재무 테이블
DEST_TABLE = "us_revenue_forecast_data" # 예측 결과 저장 테이블

# ── 재무 항목 ─────────────────────────────────────────────
# 예: "sale" (매출) / "opi" (영업이익) / "ni" (순이익) / "ebitda" 등
ITEM       = "sale"

# ── 예측 설정 ─────────────────────────────────────────────
HORIZON    = 8    # 예측 분기 수 (default 8 = 2년)
MIN_OBS    = 28   # 최소 관측 분기 수 (28 = 7년 × 4분기)

# ── 모델 선택 ─────────────────────────────────────────────
ALL_MODELS      = ["SARIMA", "ETS", "Prophet", "LSTM", "Theta"]
ENSEMBLE_MODELS = ["SARIMA", "ETS", "Theta"]   # 앙상블 구성 모델

# ── 예측 실행일 ───────────────────────────────────────────
FORECAST_DATE = datetime.now().strftime("%Y-%m-%d")

# ════════════════════════════════════════════════════════════
print("[파라미터 확인]")
print(f"  DATA_SOURCE  = {DATA_SOURCE}")
print(f"  SRC_TABLE    = {SRC_TABLE}")
print(f"  DEST_TABLE   = {DEST_TABLE}")
print(f"  ITEM         = {ITEM}")
print(f"  HORIZON      = {HORIZON}분기")
print(f"  MIN_OBS      = {MIN_OBS}개")
print(f"  ALL_MODELS   = {ALL_MODELS}")
print(f"  ENSEMBLE     = {ENSEMBLE_MODELS}")
print(f"  FORECAST_DATE= {FORECAST_DATE}")

[파라미터 확인]
  DATA_SOURCE  = fmp
  SRC_TABLE    = US_IS_from_FMP
  DEST_TABLE   = us_revenue_forecast_data
  ITEM         = sale
  HORIZON      = 8분기
  MIN_OBS      = 28개
  ALL_MODELS   = ['SARIMA', 'ETS', 'Prophet', 'LSTM', 'Theta']
  ENSEMBLE     = ['SARIMA', 'ETS', 'Theta']
  FORECAST_DATE= 2026-04-27

## Cell 4 · DB 연결 테스트

In [4]:
db_info = get_db_info()
engine  = get_engine(db_info)

try:
    with engine.connect() as conn:
        conn.execute(text("SELECT 1"))
    print("[OK] DB 연결 성공")
    print(f"     host={db_info.get('host')}  port={db_info.get('port')}  db={db_info.get('database')}")
except Exception as e:
    print(f"[FAIL] DB 연결 실패: {e}")

[OK] DB 연결 성공
     host=hystox74.synology.me  port=3307  db=investar

## Cell 5 · 재무 데이터 추출 함수 정의

`US_IS_from_FMP` → ticker + item 기준 분기 시계열 추출  

**처리 흐름**
1. ticker / item 기준으로 value, date, period, date_month 추출  
2. 날짜 파싱 및 오름차순 정렬  
3. 월별 중복 제거 (같은 월 → 마지막 행, 단독 행은 보존)  
4. 분기 단위 재집계 (같은 분기 → 마지막 행, 분기말 날짜로 통일)  
5. MIN_OBS 미달 시 ValueError

In [5]:
import time as _time
import requests as _requests


def _fmp_fetch_income(
    ticker: str,
    limit: int = 40,
    period: str = "quarter",
) -> pd.DataFrame:
    """
    FMP API 에서 손익계산서를 직접 조회합니다.
    반환: columns [date, report_date, period, date_month, value]
    """
    url = f"{FMP_BASE_URL}/income-statement/{ticker}"
    params = {"period": period, "limit": limit, "apikey": FMP_API_KEY}

    for k in range(FMP_MAX_RETRY):
        try:
            r = _requests.get(url, params=params, timeout=30)
            if r.status_code == 429:
                _time.sleep(1.5 + k)
                continue
            r.raise_for_status()
            data = r.json()
            if isinstance(data, dict) and "Error Message" in data:
                raise ValueError(data["Error Message"])
            break
        except Exception as e:
            if k == FMP_MAX_RETRY - 1:
                raise RuntimeError(f"FMP 조회 실패 ({ticker}): {e}")
            _time.sleep(FMP_SLEEP_SEC + k * 0.5)

    if not data or not isinstance(data, list):
        return pd.DataFrame()

    df = pd.DataFrame(data)
    if df.empty or "revenue" not in df.columns:
        return pd.DataFrame()

    # FMP 컬럼 → 내부 표준 컬럼으로 변환
    df["date"]        = pd.to_datetime(df["date"],         errors="coerce")
    df["report_date"] = pd.to_datetime(df.get("fillingDate", df.get("acceptedDate", pd.NaT)), errors="coerce")
    df["period"]      = df.get("period", pd.NA)
    # date_month: date 컬럼의 월 첫날 (FMP date = 분기말이므로 그대로 사용)
    df["date_month"]  = df["date"].dt.to_period("M").dt.to_timestamp()
    df["value"]       = pd.to_numeric(df["revenue"], errors="coerce")

    df = (
        df[["date", "report_date", "period", "date_month", "value"]]
        .dropna(subset=["date", "value"])
        .sort_values("date")
        .reset_index(drop=True)
    )
    return df


def _clean_series(df: pd.DataFrame, ticker: str, item: str) -> pd.DataFrame:
    """
    추출된 원시 DataFrame 을 정제합니다.
    - date 기준 중복 제거 (같은 분기말이 여러 번 → 마지막 유지)
    - 분기 연속성 확인 (3개월 간격)
    - 음수 매출 검사
    - 최소 관측치 검사
    """
    df = df.copy()
    df["value"] = pd.to_numeric(df["value"], errors="coerce")
    df = df.dropna(subset=["date", "value"]).sort_values("date").reset_index(drop=True)

    # ── FMP date 는 정확한 분기말이므로 그대로 사용 ──────────
    # 단, 같은 date 가 중복으로 들어온 경우 마지막 행 유지
    df = (
        df.groupby("date", sort=True)
          .last()
          .reset_index()
    )

    return df


def fetch_financial_series(
    engine,
    ticker: str,
    item: str    = "sale",
    min_obs: int = 28,
) -> pd.DataFrame:
    """
    DATA_SOURCE 설정에 따라 DB 또는 FMP API 에서 분기 매출 시계열을 추출합니다.

    DATA_SOURCE = 'fmp' : FMP API 직접 조회 (항상 최신)
    DATA_SOURCE = 'db'  : DB(US_IS_from_FMP) 조회 (빠름)

    반환: columns [date, report_date, period, date_month, value]
    """
    if DATA_SOURCE == "fmp":
        df = _fmp_fetch_income(ticker, limit=max(min_obs + 10, 40))
        if df.empty:
            raise ValueError(f"[{ticker}] FMP에서 '{item}' 데이터 없음")
        _time.sleep(FMP_SLEEP_SEC)  # API 호출 간격
    else:
        # ── DB 조회 (기존 로직) ────────────────────────────
        query = text("""
            SELECT date, report_date, period, date_month, value
            FROM   US_IS_from_FMP
            WHERE  ticker = :ticker
              AND  item   = :item
              AND  value  IS NOT NULL
            ORDER  BY date
        """)
        with engine.connect() as conn:
            df = pd.read_sql(query, conn, params={"ticker": ticker, "item": item})

        if df.empty:
            raise ValueError(f"[{ticker}] DB에서 '{item}' 데이터 없음")

        df["date"]        = pd.to_datetime(df["date"],        errors="coerce")
        df["report_date"] = pd.to_datetime(df["report_date"], errors="coerce")
        df["date_month"]  = pd.to_datetime(df["date_month"],  errors="coerce")
        df["value"]       = pd.to_numeric(df["value"],        errors="coerce")
        df = df.dropna(subset=["date", "value"]).sort_values("date").reset_index(drop=True)

        # DB 중복 제거 (date_month 기준)
        df_no_dm  = df[df["date_month"].isna()].copy()
        df_has_dm = df[df["date_month"].notna()].copy()
        if not df_has_dm.empty:
            df_has_dm["_dm_ym"] = df_has_dm["date_month"].dt.to_period("M")
            df_has_dm = (
                df_has_dm.sort_values("date")
                .groupby("_dm_ym", sort=True).first()
                .reset_index().drop(columns=["_dm_ym"])
            )
        df = (
            pd.concat([df_no_dm, df_has_dm], ignore_index=True)
            .sort_values("date").reset_index(drop=True)
        )

        # DB: report_date 기준 회계분기 재계산
        def _fiscal_qend(row):
            if pd.notna(row["report_date"]):
                return (row["report_date"] - pd.Timedelta(days=45)).to_period("Q").to_timestamp("Q")
            if pd.notna(row["date_month"]):
                return row["date_month"].to_period("Q").to_timestamp("Q")
            return row["date"].to_period("Q").to_timestamp("Q")
        df["date"] = df.apply(_fiscal_qend, axis=1)
        df = df.groupby("date", sort=True).last().reset_index()

    # ── 공통 정제 ─────────────────────────────────────────────
    df = _clean_series(df, ticker, item)

    # ── 음수 매출 검사 ────────────────────────────────────────
    if (df["value"] < 0).any():
        neg_dates = df.loc[df["value"] < 0, "date"].dt.date.tolist()
        raise ValueError(
            f"[{ticker}] '{item}' 음수 매출 존재 → 예측 제외 "
            f"(음수 분기: {neg_dates})"
        )

    # ── 최소 관측치 검사 ──────────────────────────────────────
    if len(df) < min_obs:
        raise ValueError(
            f"[{ticker}] '{item}' 관측치 부족: {len(df)}개 < 최소 {min_obs}개"
        )

    return df


print("[OK] fetch_financial_series 재정의 완료")
print(f"     DATA_SOURCE = '{DATA_SOURCE}'")
if DATA_SOURCE == 'fmp':
    print("     → FMP API 직접 조회 (항상 최신 분기 수신)")
else:
    print("     → DB 조회 (report_date 기준 회계분기 보정 적용)")

[OK] fetch_financial_series 재정의 완료
     DATA_SOURCE = 'fmp'
     → FMP API 직접 조회 (항상 최신 분기 수신)

In [7]:
# ── Cell 6-진단 : DB 원본 데이터 vs 추출 결과 비교 ──────────
# 최신 분기 누락 여부를 확인하는 진단 셀
from sqlalchemy import text as _text

DIAG_TICKER = "NFLX"   # ← 확인할 티커

print(f"[진단] {DIAG_TICKER} — DB 원본 vs fetch 결과 비교")
print("=" * 60)

# DB 원본 (최근 5행)
with engine.connect() as conn:
    raw = pd.read_sql(
        _text("""
            SELECT date, report_date, period, date_month, value
            FROM   US_IS_from_FMP
            WHERE  ticker = :ticker AND item = :item
              AND  value IS NOT NULL
            ORDER  BY date DESC
            LIMIT  6
        """),
        conn,
        params={"ticker": DIAG_TICKER, "item": ITEM}
    )

print("[DB 원본] 최근 6행 (date 내림차순):")
display(raw)

# fetch_financial_series 결과 (최근 5행)
try:
    diag_df = fetch_financial_series(engine, DIAG_TICKER, item=ITEM, min_obs=MIN_OBS)
    print(f"\n[fetch 결과] 최근 5행 (총 {len(diag_df)}분기):")
    display(diag_df.tail(5))
    print(f"\n  → 마지막 분기 date : {diag_df['date'].iloc[-1].date()}")
    print(f"  → 기대값           : 2025-12-31 (NVDA 2025Q4)")
    ok = diag_df['date'].iloc[-1].date().isoformat() == '2026-03-31'
    print(f"  → {'✅ 정상' if ok else '❌ 여전히 누락 — 추가 확인 필요'}")
except Exception as e:
    print(f"[오류] {e}")

[진단] NFLX — DB 원본 vs fetch 결과 비교
============================================================
[DB 원본] 최근 6행 (date 내림차순):

        date report_date period date_month         value
0 2026-01-31  2025-12-31     Q4    2025-12  1.205076e+10
1 2026-01-31  2025-12-31     Q4    2025-12  1.205076e+10
2 2025-12-31  2025-12-31     Q4    2025-12  1.205076e+10
3 2025-12-31  2025-12-31     Q4    2025-12  1.205076e+10
4 2025-11-30  2025-09-30     Q3    2025-09  1.151031e+10
5 2025-11-30  2025-09-30     Q3    2025-09  1.151031e+10

[fetch 결과] 최근 5행 (총 40분기):

         date report_date period date_month        value
35 2025-03-31  2025-04-18     Q1 2025-03-01  10542801000
36 2025-06-30  2025-07-18     Q2 2025-06-01  11079166000
37 2025-09-30  2025-10-22     Q3 2025-09-01  11510307000
38 2025-12-31  2026-01-23     Q4 2025-12-01  12050762000
39 2026-03-31  2026-04-17     Q1 2026-03-01  12249757000

  → 마지막 분기 date : 2026-03-31
  → 기대값           : 2025-12-31 (NVDA 2025Q4)
  → ✅ 정상

## Cell 6 · 단일 티커 데이터 추출 테스트

`TEST_TICKER` 를 원하는 티커로 변경해서 테스트하세요.

In [8]:
TEST_TICKER = DIAG_TICKER   # ← 테스트할 티커

try:
    src_df = fetch_financial_series(
        engine, TEST_TICKER, item=ITEM, min_obs=MIN_OBS
    )
    print(f"[OK] {TEST_TICKER} '{ITEM}' 추출 성공: {len(src_df)}분기")
    print(f"     기간: {src_df['date'].iloc[0].date()} ~ {src_df['date'].iloc[-1].date()}")
    display(src_df.tail(8))
except Exception as e:
    print(f"[FAIL] {e}")

[OK] NFLX 'sale' 추출 성공: 40분기
     기간: 2016-06-30 ~ 2026-03-31

         date report_date period date_month        value
32 2024-06-30  2024-07-19     Q2 2024-06-01   9559310000
33 2024-09-30  2024-10-18     Q3 2024-09-01   9824703000
34 2024-12-31  2025-01-27     Q4 2024-12-01  10246513000
35 2025-03-31  2025-04-18     Q1 2025-03-01  10542801000
36 2025-06-30  2025-07-18     Q2 2025-06-01  11079166000
37 2025-09-30  2025-10-22     Q3 2025-09-01  11510307000
38 2025-12-31  2026-01-23     Q4 2025-12-01  12050762000
39 2026-03-31  2026-04-17     Q1 2026-03-01  12249757000

## Cell 7 · 예측 함수 정의

- `make_forecast_index` : 마지막 실제값 다음 분기부터 HORIZON 개 날짜 생성  
- `forecast_one_ticker` : 5개 모델 순차 실행, 메모리 추적 포함

In [9]:
def make_forecast_index(
    last_date: pd.Timestamp,
    horizon: int,
    freq: str = "QE",
) -> pd.DatetimeIndex:
    """
    last_date 다음 분기부터 horizon 개의 날짜 인덱스를 생성합니다.
    freq : infer_freq_alias() 가 반환하는 값 (Q, QE, QS 등)
    """
    _freq = freq if freq else "QE"
    try:
        idx = pd.date_range(
            start   = last_date + pd.tseries.frequencies.to_offset(_freq),
            periods = horizon,
            freq    = _freq,
        )
    except Exception:
        # fallback: 3개월 간격으로 직접 생성
        idx = pd.date_range(
            start   = last_date + pd.DateOffset(months=3),
            periods = horizon,
            freq    = "QE",
        )
    return idx


def forecast_one_ticker(
    y: pd.Series,
    ticker: str,
    horizon: int,
    models: list,
) -> dict:
    """
    단일 티커의 시계열 y 에 대해 지정 모델들로 예측을 수행합니다.

    실제 함수 시그니처 (universal_ts_forecast_function_v2.py 기준):
      forecast_sarima  : (y, forecast_horizon, seasonal_period=int)
      forecast_ets     : (y, forecast_horizon, m=int)
      forecast_prophet : (y, forecast_horizon, m=int)
      forecast_lstm    : (y, forecast_horizon)           ← m 파라미터 없음
      forecast_theta   : (y, forecast_horizon, m=int)

    Parameters
    ----------
    y       : DatetimeIndex 를 가진 분기 시계열 (Series)
    ticker  : 종목 코드 (로그 출력용)
    horizon : 예측 분기 수
    models  : 사용할 모델 목록  ["SARIMA", "ETS", "Prophet", "LSTM", "Theta"]

    Returns
    -------
    dict  {model_name: {"forecast": array, "spec": dict} or {"error": str}}
    """
    import psutil, os
    proc = psutil.Process(os.getpid())

    def _mem_mb():
        return proc.memory_info().rss / 1024 / 1024

    freq    = infer_freq_alias(y.index)
    sp      = seasonal_periods_from_freq(freq)   # 분기=4, 월=12
    results = {}

    # ── 각 함수의 실제 파라미터명에 맞춰 호출 ─────────────────────
    def _call(model_name):
        if model_name == "SARIMA":
            # forecast_sarima(y, forecast_horizon, seasonal_period=)
            return forecast_sarima(y, horizon, seasonal_period=sp)
        elif model_name == "ETS":
            # forecast_ets(y, forecast_horizon, m=)
            return forecast_ets(y, horizon, m=sp)
        elif model_name == "Prophet":
            # forecast_prophet(y, forecast_horizon, m=)
            return forecast_prophet(y, horizon, m=sp)
        elif model_name == "LSTM":
            # forecast_lstm(y, forecast_horizon)  ← m 파라미터 없음
            return forecast_lstm(y, horizon)
        elif model_name == "Theta":
            # forecast_theta(y, forecast_horizon, m=)
            return forecast_theta(y, horizon, m=sp)
        else:
            raise ValueError(f"알 수 없는 모델: {model_name}")

    for model_name in models:
        log(ticker, f"  [{model_name}] 시작  (메모리: {_mem_mb():.1f} MB)")
        try:
            res = _call(model_name)
            results[model_name] = res
            fc_arr = np.asarray(res.get("forecast", []))
            if len(fc_arr) > 0:
                log(ticker, f"  [{model_name}] 완료  첫값={fc_arr[0]:.2e} (메모리: {_mem_mb():.1f} MB)")
            else:
                log(ticker, f"  [{model_name}] 오류응답: {res}")
        except Exception as e:
            log(ticker, f"  [{model_name}] 오류: {e}")
            results[model_name] = {"error": str(e)}
        finally:
            gc.collect()

    return results

print("[OK] make_forecast_index / forecast_one_ticker 함수 정의 완료")
print("  SARIMA  : forecast_sarima(y, forecast_horizon, seasonal_period=sp)")
print("  ETS     : forecast_ets(y, forecast_horizon, m=sp)")
print("  Prophet : forecast_prophet(y, forecast_horizon, m=sp)")
print("  LSTM    : forecast_lstm(y, forecast_horizon)")
print("  Theta   : forecast_theta(y, forecast_horizon, m=sp)")

[OK] make_forecast_index / forecast_one_ticker 함수 정의 완료
  SARIMA  : forecast_sarima(y, forecast_horizon, seasonal_period=sp)
  ETS     : forecast_ets(y, forecast_horizon, m=sp)
  Prophet : forecast_prophet(y, forecast_horizon, m=sp)
  LSTM    : forecast_lstm(y, forecast_horizon)
  Theta   : forecast_theta(y, forecast_horizon, m=sp)

## Cell 8 · 단일 티커 예측 테스트

Cell 6 에서 추출한 `src_df` 를 사용합니다.  
모델별 예측값과 SARIMA 파라미터를 확인하세요.

In [10]:
# Cell 6 에서 src_df 가 정상 추출된 경우에만 실행
y = src_df.set_index("date")["value"].copy()
y.index = pd.DatetimeIndex(y.index)
y.name  = ITEM

print(f"예측 입력 시계열: {len(y)}분기  ({y.index[0].date()} ~ {y.index[-1].date()})")

# 테스트용 모델 — 빠른 확인이 필요하면 ['SARIMA', 'ETS', 'Theta'] 로 축소 가능
TEST_MODELS = ALL_MODELS

forecast_results = forecast_one_ticker(y, TEST_TICKER, HORIZON, TEST_MODELS)
freq             = infer_freq_alias(y.index)
forecast_index   = make_forecast_index(y.index[-1], HORIZON, freq)

print("\n[예측 결과 요약]")
for model_name, res in forecast_results.items():
    if "error" in res:
        print(f"  {model_name:<10}: 오류 → {res['error']}")
    else:
        fc  = np.asarray(res["forecast"])
        msg = f"  {model_name:<10}: {fc.round(0).tolist()}"
        if model_name == "SARIMA" and "spec" in res:
            spec = res["spec"]
            aic  = spec.get("ic_value", "")
            aic_str = f"  AIC={aic:.2f}" if isinstance(aic, float) else ""
            msg += f"  | order={spec.get('order')} seasonal={spec.get('seasonal_order')}{aic_str}"
        print(msg)

예측 입력 시계열: 40분기  (2016-06-30 ~ 2026-03-31)
[NFLX]   [SARIMA] 시작  (메모리: 421.0 MB)
[메모리] forecast_sarima 실행 전: 421.05 MB
[메모리] find_best_sarima_params 실행 전: 421.06 MB
WARNING:tensorflow:From C:\Users\Hoyoung_Park\PyCharmMiscProject\.venv1\lib\site-packages\keras\src\backend\common\global_state.py:82: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

[메모리] find_best_sarima_params 실행 후: 427.14 MB (변화: +6.08 MB)
[메모리] forecast_sarima 실행 후: 427.26 MB (변화: +6.21 MB)
[NFLX]   [SARIMA] 완료  첫값=1.26e+10 (메모리: 427.3 MB)
[NFLX]   [ETS] 시작  (메모리: 427.3 MB)
[메모리] forecast_ets 실행 전: 427.26 MB
[메모리] forecast_ets 실행 후: 427.46 MB (변화: +0.20 MB)
[NFLX]   [ETS] 완료  첫값=1.26e+10 (메모리: 427.5 MB)
[NFLX]   [Prophet] 시작  (메모리: 427.5 MB)
[메모리] forecast_prophet 실행 전: 427.46 MB

12:43:48 - cmdstanpy - INFO - Chain [1] start processing
12:43:49 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 430.66 MB (변화: +3.20 MB)
[NFLX]   [Prophet] 완료  첫값=1.26e+10 (메모리: 430.7 MB)
[NFLX]   [LSTM] 시작  (메모리: 430.7 MB)
[메모리] forecast_lstm 실행 전: 430.66 MB
[메모리] forecast_lstm 실행 후: 501.95 MB (변화: +71.29 MB)
[NFLX]   [LSTM] 완료  첫값=1.11e+10 (메모리: 501.9 MB)
[NFLX]   [Theta] 시작  (메모리: 501.9 MB)
[메모리] forecast_theta 실행 전: 501.95 MB
[메모리] forecast_theta 실행 후: 502.11 MB (변화: +0.16 MB)
[NFLX]   [Theta] 완료  첫값=1.25e+10 (메모리: 502.1 MB)

[예측 결과 요약]
  SARIMA    : [12590796131.0, 13024643461.0, 13523788925.0, 14072734891.0, 14662867942.0, 15289614833.0, 15950814954.0, 16645771135.0]  | order=(2, 0, 0) seasonal=(0, 0, 0, 4)  AIC=-174.69
  ETS       : [12570148554.0, 12868825573.0, 13228380834.0, 13770135204.0, 14130292137.0, 14466039445.0, 14870220895.0, 15479215091.0]
  Prophet   : [12593805475.0, 12973263027.0, 13352720579.0, 13723929054.0, 14099262068.0, 14478719620.0, 14858177173.0, 15233510186.0]
  LSTM      : [11144074240.0, 11491664896.0, 11813905408.0, 12119980032.0, 12392841216.0, 12667342848.0, 12938358784.0, 13193099264.0]
  Theta     : [12463316593.0, 12627841043.0, 12856605017.0, 13316114697.0, 13548063061.0, 13726525389.0, 13975047579.0, 14475270874.0]

## Cell 9 · Long-format 변환 함수 정의

actual + forecast(각 모델) + Ensemble → 하나의 long-format DataFrame

**저장 컬럼**

| 컬럼 | 설명 |
|------|------|
| ticker | 종목 코드 |
| item | 재무 항목 |
| date | 기준일(분기말) |
| period | 회계 분기(Q1~Q4/FY) — actual 행만 |
| date_month | 해당 분기 기간 — actual 행만 |
| data_type | `actual` / `forecast` |
| model | actual / SARIMA / ETS / Prophet / LSTM / Theta / Ensemble |
| value | 수치값 |
| forecast_date | 예측 실행일 |
| sarima_order | SARIMA (p,d,q) — SARIMA 행만 |
| sarima_seasonal_order | SARIMA (P,D,Q,m) — SARIMA 행만 |
| sarima_ic_value | SARIMA 최적 AIC — SARIMA 행만 |
| created_at | 레코드 생성 시각 |

In [11]:
def build_long_df(
    ticker: str,
    item: str,
    src_df: pd.DataFrame,
    forecast_results: dict,
    forecast_index: pd.DatetimeIndex,
    forecast_date: str,
    ensemble_models: list = None,
) -> pd.DataFrame:
    """
    실제값(actual) + 예측값(각 모델) + 앙상블 → long-format DataFrame.

    Parameters
    ----------
    ticker           : 종목 코드
    item             : 재무 항목
    src_df           : fetch_financial_series() 반환 DataFrame
    forecast_results : forecast_one_ticker() 반환 dict
    forecast_index   : 예측 날짜 DatetimeIndex
    forecast_date    : 예측 실행일 (str)
    ensemble_models  : 앙상블 구성 모델 목록 (None → ENSEMBLE_MODELS 전역 변수 사용)
    """
    if ensemble_models is None:
        ensemble_models = ENSEMBLE_MODELS

    now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    rows    = []

    # ── actual 행 ────────────────────────────────────────────
    for _, row in src_df.iterrows():
        rows.append({
            "ticker"                : ticker,
            "item"                  : item,
            "date"                  : row["date"].strftime("%Y-%m-%d"),
            "period"                : row.get("period"),
            "date_month"            : (
                row["date_month"].strftime("%Y-%m-%d")
                if pd.notna(row.get("date_month")) else None
            ),
            "data_type"             : "actual",
            "model"                 : "actual",
            "value"                 : round(float(row["value"]), 6),
            "forecast_date"         : forecast_date,
            "sarima_order"          : None,
            "sarima_seasonal_order" : None,
            "sarima_ic_value"       : None,
            "created_at"            : now_str,
        })

    # ── forecast 행 ──────────────────────────────────────────
    ensemble_bucket = {}   # { date_str : [val, ...] }

    for model_name, res in forecast_results.items():
        if "error" in res or "forecast" not in res:
            continue

        fc_arr = np.asarray(res["forecast"])
        spec   = res.get("spec", {})

        sarima_order    = None
        sarima_seasonal = None
        sarima_ic       = None
        if model_name == "SARIMA":
            sarima_order    = str(spec.get("order",          ""))
            sarima_seasonal = str(spec.get("seasonal_order", ""))
            raw_ic = spec.get("ic_value")
            if raw_ic is not None:
                try:
                    v = float(raw_ic)
                    sarima_ic = round(v, 4) if np.isfinite(v) else None
                except (TypeError, ValueError):
                    pass

        for i, dt in enumerate(forecast_index):
            if i >= len(fc_arr):
                break
            val    = float(fc_arr[i])
            dt_str = dt.strftime("%Y-%m-%d")

            rows.append({
                "ticker"                : ticker,
                "item"                  : item,
                "date"                  : dt_str,
                "period"                : None,
                "date_month"            : None,
                "data_type"             : "forecast",
                "model"                 : model_name,
                "value"                 : round(val, 6),
                "forecast_date"         : forecast_date,
                "sarima_order"          : sarima_order,
                "sarima_seasonal_order" : sarima_seasonal,
                "sarima_ic_value"       : sarima_ic,
                "created_at"            : now_str,
            })

            if model_name in ensemble_models:
                ensemble_bucket.setdefault(dt_str, []).append(val)

    # ── Ensemble 행 (SARIMA + ETS + Theta 평균) ─────────────
    for dt_str, vals in ensemble_bucket.items():
        rows.append({
            "ticker"                : ticker,
            "item"                  : item,
            "date"                  : dt_str,
            "period"                : None,
            "date_month"            : None,
            "data_type"             : "forecast",
            "model"                 : "Ensemble",
            "value"                 : round(float(np.mean(vals)), 6),
            "forecast_date"         : forecast_date,
            "sarima_order"          : None,
            "sarima_seasonal_order" : None,
            "sarima_ic_value"       : None,
            "created_at"            : now_str,
        })

    return pd.DataFrame(rows)

print("[OK] build_long_df 함수 정의 완료")

[OK] build_long_df 함수 정의 완료

## Cell 10 · Long-format 변환 테스트

In [12]:
long_df = build_long_df(
    ticker           = TEST_TICKER,
    item             = ITEM,
    src_df           = src_df,
    forecast_results = forecast_results,
    forecast_index   = forecast_index,
    forecast_date    = FORECAST_DATE,
)

print(f"[OK] long_df 생성: {len(long_df)}행")
print("\n모델별 행 수:")
display(long_df.groupby(["data_type", "model"]).size().reset_index(name="rows"))
print("\n샘플 (forecast 상위 5행):")
display(long_df[long_df["data_type"] == "forecast"].head())

[OK] long_df 생성: 88행

모델별 행 수:

  data_type     model  rows
0    actual    actual    40
1  forecast       ETS     8
2  forecast  Ensemble     8
3  forecast      LSTM     8
4  forecast   Prophet     8
5  forecast    SARIMA     8
6  forecast     Theta     8

샘플 (forecast 상위 5행):

,ticker,item,date,period,date_month,data_type,model,value,forecast_date,sarima_order,sarima_seasonal_order,sarima_ic_value,created_at
40,NFLX,sale,2026-06-30,None,None,forecast,SARIMA,1.259080e+10,2026-04-27,"(2, 0, 0)","(0, 0, 0, 4)",-174.6898,2026-04-27 12:44:08
41,NFLX,sale,2026-09-30,None,None,forecast,SARIMA,1.302464e+10,2026-04-27,"(2, 0, 0)","(0, 0, 0, 4)",-174.6898,2026-04-27 12:44:08
42,NFLX,sale,2026-12-31,None,None,forecast,SARIMA,1.352379e+10,2026-04-27,"(2, 0, 0)","(0, 0, 0, 4)",-174.6898,2026-04-27 12:44:08
43,NFLX,sale,2027-03-31,None,None,forecast,SARIMA,1.407273e+10,2026-04-27,"(2, 0, 0)","(0, 0, 0, 4)",-174.6898,2026-04-27 12:44:08
44,NFLX,sale,2027-06-30,None,None,forecast,SARIMA,1.466287e+10,2026-04-27,"(2, 0, 0)","(0, 0, 0, 4)",-174.6898,2026-04-27 12:44:08

In [14]:
# long_df.to_csv(r"C:\reports\revenue_forecast_data.csv")

## Cell 11 · DB 테이블 생성 & 저장 함수 정의

**중복 판정 기준** : `(ticker, item, date, model, forecast_date)`  
→ 이미 존재하는 행은 건드리지 않고, 신규 행만 INSERT

In [13]:
# ── 테이블 CREATE (최초 1회) ──────────────────────────────────
CREATE_TABLE_SQL = f"""
CREATE TABLE IF NOT EXISTS `{DEST_TABLE}` (
    id                    BIGINT       NOT NULL AUTO_INCREMENT,
    ticker                VARCHAR(20)  NOT NULL,
    item                  VARCHAR(30)  NOT NULL,
    date                  DATE         NOT NULL,
    period                VARCHAR(10)  DEFAULT NULL,
    date_month            DATE         DEFAULT NULL,
    data_type             VARCHAR(10)  NOT NULL COMMENT 'actual / forecast',
    model                 VARCHAR(20)  NOT NULL,
    value                 DOUBLE       DEFAULT NULL,
    forecast_date         DATE         NOT NULL,
    sarima_order          VARCHAR(30)  DEFAULT NULL,
    sarima_seasonal_order VARCHAR(30)  DEFAULT NULL,
    sarima_ic_value       DOUBLE       DEFAULT NULL,
    created_at            DATETIME     DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_main (ticker, item, date, model, forecast_date),
    INDEX idx_ticker      (ticker),
    INDEX idx_forecast_dt (forecast_date),
    INDEX idx_model       (model)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
"""

def ensure_table(engine):
    """저장 테이블이 없으면 생성합니다."""
    with engine.begin() as conn:
        conn.execute(text(CREATE_TABLE_SQL))
    print(f"[OK] 테이블 '{DEST_TABLE}' 준비 완료")


def save_to_db(engine, long_df: pd.DataFrame, dest_table: str = DEST_TABLE) -> int:
    """
    long_df 를 DB 에 저장합니다.
    - 중복 기준: (ticker, item, date, model, forecast_date)
    - 기존 행 유지 + 신규 행만 INSERT

    Returns
    -------
    int  : 실제 삽입된 신규 행 수
    """
    if long_df is None or long_df.empty:
        return 0

    # ── 1. 기존 키 조회 ────────────────────────────────────
    ticker      = long_df["ticker"].iloc[0]
    item        = long_df["item"].iloc[0]
    fc_date_val = long_df["forecast_date"].iloc[0]

    check_sql = text(f"""
        SELECT CONCAT(ticker,'|',item,'|',date,'|',model,'|',forecast_date) AS uq_key
        FROM   `{dest_table}`
        WHERE  ticker        = :ticker
          AND  item          = :item
          AND  forecast_date = :fc_date
    """)

    with engine.connect() as conn:
        existing = pd.read_sql(
            check_sql, conn,
            params={"ticker": ticker, "item": item, "fc_date": fc_date_val}
        )
    existing_keys = set(existing["uq_key"].tolist()) if not existing.empty else set()

    # ── 2. 신규 행 필터링 ──────────────────────────────────
    new_df = long_df[
        ~long_df.apply(
            lambda r: f"{r['ticker']}|{r['item']}|{r['date']}|{r['model']}|{r['forecast_date']}"
            in existing_keys,
            axis=1,
        )
    ].copy()

    if new_df.empty:
        log(ticker, f"  [DB] 신규 행 없음 — 스킵")
        return 0

    # ── 3. INSERT ─────────────────────────────────────────
    new_df.to_sql(
        name       = dest_table,
        con        = engine,
        if_exists  = "append",
        index      = False,
        chunksize  = 500,
        method     = "multi",
    )
    log(ticker, f"  [DB] {len(new_df)}행 저장 완료")
    return len(new_df)

print("[OK] ensure_table / save_to_db 함수 정의 완료")

[OK] ensure_table / save_to_db 함수 정의 완료

## Cell 12 · 단일 티커 저장 테스트

In [14]:
# 테이블 생성 (최초 1회)
ensure_table(engine)

# Cell 10 의 long_df 저장
inserted = save_to_db(engine, long_df)
print(f"[OK] {TEST_TICKER} 저장 완료 — 삽입: {inserted}행")

# 저장 확인
with engine.connect() as conn:
    chk = pd.read_sql(
        text(f"""
            SELECT model, data_type, COUNT(*) AS cnt
            FROM   `{DEST_TABLE}`
            WHERE  ticker = :tk AND forecast_date = :fd
            GROUP  BY model, data_type
            ORDER  BY model
        """),
        conn,
        params={"tk": TEST_TICKER, "fd": FORECAST_DATE},
    )
display(chk)

[OK] 테이블 'us_revenue_forecast_data' 준비 완료
[NFLX]   [DB] 88행 저장 완료
[OK] NFLX 저장 완료 — 삽입: 88행

      model data_type  cnt
0    actual    actual   40
1  Ensemble  forecast    8
2       ETS  forecast    8
3      LSTM  forecast    8
4   Prophet  forecast    8
5    SARIMA  forecast    8
6     Theta  forecast    8

## Cell 13 · 배치 실행 (전체 / 특정 티커 / 구간 지정)

### 실행 모드 선택

| 변수 | 설명 |
|------|------|
| `RUN_TICKERS` | `None` → DEFAULT_TICKER_LIST 전체 / `["AAPL", ...]` → 특정 티커만 |
| `TICKER_START` | 리스트 슬라이싱 시작 인덱스 (0부터, `None` = 처음) |
| `TICKER_END`   | 리스트 슬라이싱 끝 인덱스 (None = 끝까지) |
| `RUN_MODELS`   | 사용할 모델 목록 |

### 구간 예시
```python
TICKER_START, TICKER_END = 0,   500   # 1~500번째 티커
TICKER_START, TICKER_END = 500, 1000  # 501~1000번째 티커
TICKER_START, TICKER_END = None, None # 전체
```

### 메모리 전략
> 티커 1개 예측 → 즉시 DB 저장 → `clear_memory()` 호출  
> 이 방식이 배치(20개 누적) 방식보다 피크 메모리가 낮고 중단 시 손실도 최소화됩니다.

In [14]:
# ════════════════════════════════════════════════════════════
#  배치 설정 — 여기를 수정하세요
# ════════════════════════════════════════════════════════════

# ── 특정 티커 지정 (None 이면 아래 구간/전체 사용) ────────────
# Optional[list] = Python 3.9 호환 (3.10+ 의 list | None 대신 사용)
RUN_TICKERS = None          # type: Optional[list]
# RUN_TICKERS = ["AAPL", "MSFT", "NVDA"]   # 특정 티커만

# ── 전체 리스트 구간 지정 (RUN_TICKERS=None 일 때 적용) ──────
TICKER_START = 1500           # type: Optional[int]  # 시작 인덱스 (0부터)
TICKER_END   = 2000          # type: Optional[int]  # 끝 인덱스 (exclusive, None=끝까지)
# 예: 0~499   → START=0,   END=500
# 예: 500~999 → START=500, END=1000
# 예: 전체    → START=None, END=None

# ── 모델 / 항목 / 예측 기간 ───────────────────────────────────
RUN_MODELS  = ALL_MODELS   # 또는 ["SARIMA", "ETS", "Theta"]  (빠른 실행)
RUN_ITEM    = ITEM
RUN_HORIZON = HORIZON
RUN_MIN_OBS = MIN_OBS

# ════════════════════════════════════════════════════════════
#  실행 대상 티커 목록 결정
# ════════════════════════════════════════════════════════════
if RUN_TICKERS is not None:
    tickers = RUN_TICKERS
    print(f"[모드] 특정 티커 지정: {tickers}")
else:
    tickers = DEFAULT_TICKER_LIST[TICKER_START:TICKER_END]
    _s = TICKER_START if TICKER_START is not None else 0
    _e = TICKER_END   if TICKER_END   is not None else len(DEFAULT_TICKER_LIST)
    print(f"[모드] 구간 실행: index {_s} ~ {_e-1}  ({len(tickers)}개)")

total = len(tickers)

# ════════════════════════════════════════════════════════════
#  배치 실행
# ════════════════════════════════════════════════════════════
ensure_table(engine)

success, skipped, errored, neg_skipped = 0, 0, 0, 0
skip_list, error_list, neg_skip_list   = [], [], []

log("BATCH", "=" * 70)
log("BATCH", f"시작  | 티커 {total}개 | 항목: {RUN_ITEM} | 예측기간: {RUN_HORIZON}분기")
log("BATCH", f"모델  : {RUN_MODELS}")
log("BATCH", f"예측일: {FORECAST_DATE} | min_obs: {RUN_MIN_OBS}")
log("BATCH", "=" * 70)

for i, ticker in enumerate(tickers, 1):
    pct = i / total * 100
    log("PROGRESS", f"[{i:>4}/{total}] ({pct:5.1f}%)  >>  {ticker}")

    # ── STEP 1 : 데이터 추출 ──────────────────────────────
    try:
        _src_df = fetch_financial_series(
            engine, ticker, RUN_ITEM, RUN_MIN_OBS
        )
    except ValueError as e:
        err_msg = str(e)
        if "음수 매출" in err_msg:
            # 음수 매출 → 예측 제외 (별도 카운트)
            log(ticker, f"[NEG-SKIP] {err_msg}")
            neg_skipped += 1
            neg_skip_list.append(ticker)
        else:
            log(ticker, f"[SKIP] {err_msg}")
            skipped += 1
            skip_list.append(ticker)
        continue
    except Exception as e:
        log(ticker, f"[SKIP] {e}")
        skipped += 1
        skip_list.append(ticker)
        continue

    _y = _src_df.set_index("date")["value"].copy()
    _y.index = pd.DatetimeIndex(_y.index)
    _y.name  = RUN_ITEM
    log(ticker, f"  {len(_y)}분기 | {_y.index[0].date()} ~ {_y.index[-1].date()}")

    # ── STEP 2 : 예측 ─────────────────────────────────────
    try:
        _fc_results = forecast_one_ticker(_y, ticker, RUN_HORIZON, RUN_MODELS)
    except Exception as e:
        log(ticker, f"[ERROR] 예측: {e}")
        traceback.print_exc()
        errored += 1
        error_list.append(ticker)
        del _src_df, _y
        clear_memory()
        continue

    # ── STEP 3 : 예측 인덱스 생성 ────────────────────────
    _freq     = infer_freq_alias(_y.index)
    _fc_index = make_forecast_index(_y.index[-1], RUN_HORIZON, _freq)

    # ── STEP 4 : Long-format 변환 ─────────────────────────
    try:
        _ldf = build_long_df(
            ticker           = ticker,
            item             = RUN_ITEM,
            src_df           = _src_df,
            forecast_results = _fc_results,
            forecast_index   = _fc_index,
            forecast_date    = FORECAST_DATE,
        )
    except Exception as e:
        log(ticker, f"[ERROR] Long-format 변환: {e}")
        errored += 1
        error_list.append(ticker)
        del _src_df, _y, _fc_results
        clear_memory()
        continue

    # ── STEP 5 : DB 저장 (1개씩 즉시 저장 — 메모리 최소화) ─
    try:
        save_to_db(engine, _ldf)
        success += 1
    except Exception as e:
        log(ticker, f"[ERROR] DB 저장: {e}")
        errored += 1
        error_list.append(ticker)

    # ── STEP 6 : 메모리 해제 ─────────────────────────────
    del _src_df, _y, _fc_results, _ldf
    clear_memory()

# ── 요약 ──────────────────────────────────────────────────
log("BATCH", "=" * 70)
log("BATCH", f"완료 | 성공: {success}  데이터스킵: {skipped}  음수제외: {neg_skipped}  오류: {errored}  합계: {total}")
if skip_list:     log("BATCH", f"데이터스킵  : {skip_list}")
if neg_skip_list: log("BATCH", f"음수매출제외 : {neg_skip_list}")
if error_list:    log("BATCH", f"오류 티커   : {error_list}")
log("BATCH", "=" * 70)

[모드] 구간 실행: index 1500 ~ 1999  (500개)
[OK] 테이블 'us_revenue_forecast_data' 준비 완료
[BATCH] ======================================================================
[BATCH] 시작  | 티커 500개 | 항목: sale | 예측기간: 8분기
[BATCH] 모델  : ['SARIMA', 'ETS', 'Prophet', 'LSTM', 'Theta']
[BATCH] 예측일: 2026-04-04 | min_obs: 28
[BATCH] ======================================================================
[PROGRESS] [   1/500] (  0.2%)  >>  CCEC
[CCEC] [SKIP] [CCEC] 'sale' 관측치 부족: 25개 < 최소 28개
[PROGRESS] [   2/500] (  0.4%)  >>  PRLB
[PRLB]   40분기 | 2016-03-31 ~ 2025-12-31
[PRLB]   [SARIMA] 시작  (메모리: 1448.2 MB)
[메모리] forecast_sarima 실행 전: 1448.20 MB
[메모리] find_best_sarima_params 실행 전: 1448.20 MB
[메모리] find_best_sarima_params 실행 후: 1449.27 MB (변화: +1.07 MB)
[메모리] forecast_sarima 실행 후: 1449.29 MB (변화: +1.08 MB)
[PRLB]   [SARIMA] 완료  첫값=1.39e+08 (메모리: 1449.3 MB)
[PRLB]   [ETS] 시작  (메모리: 1449.3 MB)
[메모리] forecast_ets 실행 전: 1449.29 MB
[메모리] forecast_ets 실행 후: 1449.44 MB (변화: +0.16 MB)
[PRLB]   [ETS] 완료  첫값=1.45e+08 (메모리: 1449.4 MB)
[PRLB]   [Prophet] 시작  (메모리: 1449.4 MB)

10:29:30 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1449.44 MB

10:29:30 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1451.08 MB (변화: +1.64 MB)
[PRLB]   [Prophet] 완료  첫값=1.35e+08 (메모리: 1451.1 MB)
[PRLB]   [LSTM] 시작  (메모리: 1451.1 MB)
[메모리] forecast_lstm 실행 전: 1451.08 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1457.95 MB (변화: +6.88 MB)
[PRLB]   [LSTM] 완료  첫값=1.30e+08 (메모리: 1458.0 MB)
[PRLB]   [Theta] 시작  (메모리: 1458.0 MB)
[메모리] forecast_theta 실행 전: 1457.95 MB
[메모리] forecast_theta 실행 후: 1457.96 MB (변화: +0.00 MB)
[PRLB]   [Theta] 완료  첫값=1.43e+08 (메모리: 1458.0 MB)
[PRLB]   [DB] 88행 저장 완료
[PROGRESS] [   3/500] (  0.6%)  >>  BH
[BH]   40분기 | 2016-03-31 ~ 2025-12-31
[BH]   [SARIMA] 시작  (메모리: 1458.4 MB)
[메모리] forecast_sarima 실행 전: 1458.36 MB
[메모리] find_best_sarima_params 실행 전: 1458.36 MB
[메모리] find_best_sarima_params 실행 후: 1459.70 MB (변화: +1.33 MB)
[메모리] forecast_sarima 실행 후: 1459.70 MB (변화: +1.33 MB)
[BH]   [SARIMA] 완료  첫값=9.80e+07 (메모리: 1459.7 MB)
[BH]   [ETS] 시작  (메모리: 1459.7 MB)
[메모리] forecast_ets 실행 전: 1459.70 MB
[메모리] forecast_ets 실행 후: 1459.92 MB (변화: +0.23 MB)
[BH]   [ETS] 완료  첫값=9.88e+07 (메모리: 1459.9 MB)
[BH]   [Prophet] 시작  (메모리: 1459.9 MB)

10:29:46 - cmdstanpy - INFO - Chain [1] start processing
10:29:46 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1459.92 MB
[메모리] forecast_prophet 실행 후: 1461.27 MB (변화: +1.34 MB)
[BH]   [Prophet] 완료  첫값=5.46e+07 (메모리: 1461.3 MB)
[BH]   [LSTM] 시작  (메모리: 1461.3 MB)
[메모리] forecast_lstm 실행 전: 1461.27 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1459.69 MB (변화: -1.58 MB)
[BH]   [LSTM] 완료  첫값=9.39e+07 (메모리: 1459.7 MB)
[BH]   [Theta] 시작  (메모리: 1459.7 MB)
[메모리] forecast_theta 실행 전: 1459.69 MB
[메모리] forecast_theta 실행 후: 1459.69 MB (변화: +0.00 MB)
[BH]   [Theta] 완료  첫값=9.48e+07 (메모리: 1459.7 MB)
[BH]   [DB] 88행 저장 완료
[PROGRESS] [   4/500] (  0.8%)  >>  FOR
[FOR]   40분기 | 2016-03-31 ~ 2025-12-31
[FOR]   [SARIMA] 시작  (메모리: 1460.0 MB)
[메모리] forecast_sarima 실행 전: 1460.00 MB
[메모리] find_best_sarima_params 실행 전: 1460.00 MB
[메모리] find_best_sarima_params 실행 후: 1461.54 MB (변화: +1.54 MB)
[메모리] forecast_sarima 실행 후: 1461.54 MB (변화: +1.54 MB)
[FOR]   [SARIMA] 완료  첫값=3.47e+08 (메모리: 1461.5 MB)
[FOR]   [ETS] 시작  (메모리: 1461.5 MB)
[메모리] forecast_ets 실행 전: 1461.54 MB
[메모리] forecast_ets 실행 후: 1461.62 MB (변화: +0.08 MB)
[FOR]   [ETS] 완료  첫값=4.16e+08 (메모리: 1461.6 MB)
[FOR]   [Prophet] 시작  (메모리: 1461.6 MB)

10:30:04 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1461.62 MB

10:30:04 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1463.35 MB (변화: +1.73 MB)
[FOR]   [Prophet] 완료  첫값=4.88e+08 (메모리: 1463.4 MB)
[FOR]   [LSTM] 시작  (메모리: 1463.4 MB)
[메모리] forecast_lstm 실행 전: 1463.35 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1460.49 MB (변화: -2.86 MB)
[FOR]   [LSTM] 완료  첫값=3.99e+08 (메모리: 1460.5 MB)
[FOR]   [Theta] 시작  (메모리: 1460.2 MB)
[메모리] forecast_theta 실행 전: 1460.21 MB
[메모리] forecast_theta 실행 후: 1460.22 MB (변화: +0.00 MB)
[FOR]   [Theta] 완료  첫값=2.68e+08 (메모리: 1460.2 MB)
[FOR]   [DB] 88행 저장 완료
[PROGRESS] [   5/500] (  1.0%)  >>  VRNT
[VRNT]   40분기 | 2015-10-31 ~ 2025-07-31
[VRNT]   [SARIMA] 시작  (메모리: 1460.6 MB)
[메모리] forecast_sarima 실행 전: 1460.62 MB
[메모리] find_best_sarima_params 실행 전: 1460.62 MB
[메모리] find_best_sarima_params 실행 후: 1462.65 MB (변화: +2.04 MB)
[메모리] forecast_sarima 실행 후: 1462.65 MB (변화: +2.04 MB)
[VRNT]   [SARIMA] 완료  첫값=2.13e+08 (메모리: 1462.7 MB)
[VRNT]   [ETS] 시작  (메모리: 1462.7 MB)
[메모리] forecast_ets 실행 전: 1462.65 MB
[메모리] forecast_ets 실행 후: 1462.89 MB (변화: +0.24 MB)
[VRNT]   [ETS] 완료  첫값=2.15e+08 (메모리: 1462.9 MB)
[VRNT]   [Prophet] 시작  (메모리: 1462.9 MB)

10:30:21 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1462.89 MB

10:30:21 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1464.50 MB (변화: +1.61 MB)
[VRNT]   [Prophet] 완료  첫값=2.19e+08 (메모리: 1464.5 MB)
[VRNT]   [LSTM] 시작  (메모리: 1464.5 MB)
[메모리] forecast_lstm 실행 전: 1464.50 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1464.00 MB (변화: -0.51 MB)
[VRNT]   [LSTM] 완료  첫값=2.32e+08 (메모리: 1464.0 MB)
[VRNT]   [Theta] 시작  (메모리: 1464.0 MB)
[메모리] forecast_theta 실행 전: 1464.00 MB
[메모리] forecast_theta 실행 후: 1464.00 MB (변화: +0.00 MB)
[VRNT]   [Theta] 완료  첫값=2.14e+08 (메모리: 1464.0 MB)
[VRNT]   [DB] 88행 저장 완료
[PROGRESS] [   6/500] (  1.2%)  >>  THS
[THS]   40분기 | 2015-12-31 ~ 2025-09-30
[THS]   [SARIMA] 시작  (메모리: 1464.4 MB)
[메모리] forecast_sarima 실행 전: 1464.44 MB
[메모리] find_best_sarima_params 실행 전: 1464.44 MB
[메모리] find_best_sarima_params 실행 후: 1465.98 MB (변화: +1.54 MB)
[메모리] forecast_sarima 실행 후: 1465.98 MB (변화: +1.54 MB)
[THS]   [SARIMA] 완료  첫값=8.55e+08 (메모리: 1466.0 MB)
[THS]   [ETS] 시작  (메모리: 1466.0 MB)
[메모리] forecast_ets 실행 전: 1465.98 MB
[메모리] forecast_ets 실행 후: 1466.22 MB (변화: +0.23 MB)
[THS]   [ETS] 완료  첫값=9.52e+08 (메모리: 1466.2 MB)
[THS]   [Prophet] 시작  (메모리: 1466.2 MB)

10:30:42 - cmdstanpy - INFO - Chain [1] start processing
10:30:42 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1466.22 MB
[메모리] forecast_prophet 실행 후: 1468.21 MB (변화: +2.00 MB)
[THS]   [Prophet] 완료  첫값=6.85e+08 (메모리: 1468.2 MB)
[THS]   [LSTM] 시작  (메모리: 1468.2 MB)
[메모리] forecast_lstm 실행 전: 1468.21 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1465.48 MB (변화: -2.74 MB)
[THS]   [LSTM] 완료  첫값=8.21e+08 (메모리: 1465.5 MB)
[THS]   [Theta] 시작  (메모리: 1465.5 MB)
[메모리] forecast_theta 실행 전: 1465.48 MB
[메모리] forecast_theta 실행 후: 1465.48 MB (변화: +0.01 MB)
[THS]   [Theta] 완료  첫값=9.78e+08 (메모리: 1465.5 MB)
[THS]   [DB] 88행 저장 완료
[PROGRESS] [   7/500] (  1.4%)  >>  ORC
[ORC] [NEG-SKIP] [ORC] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2016, 3, 31), datetime.date(2020, 3, 31), datetime.date(2021, 3, 31), datetime.date(2021, 6, 30), datetime.date(2021, 12, 31), datetime.date(2022, 3, 31), datetime.date(2022, 6, 30), datetime.date(2022, 9, 30), datetime.date(2023, 9, 30), datetime.date(2024, 6, 30), datetime.date(2025, 6, 30)])
[PROGRESS] [   8/500] (  1.6%)  >>  WLFC
[WLFC]   40분기 | 2016-03-31 ~ 2025-12-31
[WLFC]   [SARIMA] 시작  (메모리: 1465.6 MB)
[메모리] forecast_sarima 실행 전: 1465.65 MB
[메모리] find_best_sarima_params 실행 전: 1465.65 MB
[메모리] find_best_sarima_params 실행 후: 1467.04 MB (변화: +1.39 MB)
[메모리] forecast_sarima 실행 후: 1467.04 MB (변화: +1.39 MB)
[WLFC]   [SARIMA] 완료  첫값=1.94e+08 (메모리: 1467.0 MB)
[WLFC]   [ETS] 시작  (메모리: 1467.0 MB)
[메모리] forecast_ets 실행 전: 1467.04 MB
[메모리] forecast_ets 실행 후: 1467.25 MB (변화: +0.21 MB)
[WLFC]   [ETS] 완료  첫값=1.91e+08 (메모리: 1467.3 MB)
[WLFC]   [Prophet] 시작  (메모리: 1467.3 MB)

10:31:02 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1467.25 MB

10:31:02 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1468.97 MB (변화: +1.71 MB)
[WLFC]   [Prophet] 완료  첫값=1.48e+08 (메모리: 1469.0 MB)
[WLFC]   [LSTM] 시작  (메모리: 1469.0 MB)
[메모리] forecast_lstm 실행 전: 1468.97 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1483.45 MB (변화: +14.48 MB)
[WLFC]   [LSTM] 완료  첫값=2.25e+08 (메모리: 1483.4 MB)
[WLFC]   [Theta] 시작  (메모리: 1483.4 MB)
[메모리] forecast_theta 실행 전: 1483.45 MB
[메모리] forecast_theta 실행 후: 1483.45 MB (변화: +0.00 MB)
[WLFC]   [Theta] 완료  첫값=1.85e+08 (메모리: 1483.4 MB)
[WLFC]   [DB] 88행 저장 완료
[PROGRESS] [   9/500] (  1.8%)  >>  EVRI
[EVRI]   40분기 | 2015-06-30 ~ 2025-03-31
[EVRI]   [SARIMA] 시작  (메모리: 1483.8 MB)
[메모리] forecast_sarima 실행 전: 1483.82 MB
[메모리] find_best_sarima_params 실행 전: 1483.82 MB
[메모리] find_best_sarima_params 실행 후: 1485.16 MB (변화: +1.34 MB)
[메모리] find_best_sarima_params 실행 전: 1485.16 MB
[메모리] find_best_sarima_params 실행 후: 1485.64 MB (변화: +0.48 MB)
[메모리] forecast_sarima 실행 후: 1485.67 MB (변화: +1.85 MB)
[EVRI]   [SARIMA] 완료  첫값=1.79e+08 (메모리: 1485.7 MB)
[EVRI]   [ETS] 시작  (메모리: 1485.7 MB)
[메모리] forecast_ets 실행 전: 1485.67 MB
[메모리] forecast_ets 실행 후: 1485.72 MB (변화: +0.05 MB)
[EVRI]   [ETS] 완료  첫값=1.70e+08 (메모리: 1485.7 MB)
[EVRI]   [Prophet] 시작  (메모리: 1485.7 MB)

10:31:26 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1485.72 MB

10:31:26 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1486.73 MB (변화: +1.01 MB)
[EVRI]   [Prophet] 완료  첫값=1.68e+08 (메모리: 1486.7 MB)
[EVRI]   [LSTM] 시작  (메모리: 1486.7 MB)
[메모리] forecast_lstm 실행 전: 1486.73 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1484.27 MB (변화: -2.46 MB)
[EVRI]   [LSTM] 완료  첫값=1.65e+08 (메모리: 1484.3 MB)
[EVRI]   [Theta] 시작  (메모리: 1484.3 MB)
[메모리] forecast_theta 실행 전: 1484.27 MB
[메모리] forecast_theta 실행 후: 1484.27 MB (변화: +0.00 MB)
[EVRI]   [Theta] 완료  첫값=1.84e+08 (메모리: 1484.3 MB)
[EVRI]   [DB] 88행 저장 완료
[PROGRESS] [  10/500] (  2.0%)  >>  NVGS
[NVGS]   40분기 | 2016-03-31 ~ 2025-12-31
[NVGS]   [SARIMA] 시작  (메모리: 1484.6 MB)
[메모리] forecast_sarima 실행 전: 1484.60 MB
[메모리] find_best_sarima_params 실행 전: 1484.60 MB
[메모리] find_best_sarima_params 실행 후: 1468.74 MB (변화: -15.86 MB)
[메모리] forecast_sarima 실행 후: 1468.74 MB (변화: -15.86 MB)
[NVGS]   [SARIMA] 완료  첫값=1.56e+08 (메모리: 1468.7 MB)
[NVGS]   [ETS] 시작  (메모리: 1468.7 MB)
[메모리] forecast_ets 실행 전: 1468.74 MB
[메모리] forecast_ets 실행 후: 1468.98 MB (변화: +0.24 MB)
[NVGS]   [ETS] 완료  첫값=1.56e+08 (메모리: 1469.0 MB)
[NVGS]   [Prophet] 시작  (메모리: 1469.0 MB)

10:31:43 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1468.98 MB

10:31:43 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1471.05 MB (변화: +2.06 MB)
[NVGS]   [Prophet] 완료  첫값=1.58e+08 (메모리: 1471.0 MB)
[NVGS]   [LSTM] 시작  (메모리: 1471.0 MB)
[메모리] forecast_lstm 실행 전: 1471.05 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1484.14 MB (변화: +13.10 MB)
[NVGS]   [LSTM] 완료  첫값=1.55e+08 (메모리: 1484.1 MB)
[NVGS]   [Theta] 시작  (메모리: 1484.1 MB)
[메모리] forecast_theta 실행 전: 1484.14 MB
[메모리] forecast_theta 실행 후: 1484.15 MB (변화: +0.00 MB)
[NVGS]   [Theta] 완료  첫값=1.54e+08 (메모리: 1484.1 MB)
[NVGS]   [DB] 88행 저장 완료
[PROGRESS] [  11/500] (  2.2%)  >>  MBX
[MBX] [SKIP] [MBX] 'sale' 관측치 부족: 11개 < 최소 28개
[PROGRESS] [  12/500] (  2.4%)  >>  HSII
[HSII]   40분기 | 2015-12-31 ~ 2025-09-30
[HSII]   [SARIMA] 시작  (메모리: 1484.5 MB)
[메모리] forecast_sarima 실행 전: 1484.54 MB
[메모리] find_best_sarima_params 실행 전: 1484.54 MB
[메모리] find_best_sarima_params 실행 후: 1486.04 MB (변화: +1.50 MB)
[메모리] forecast_sarima 실행 후: 1486.04 MB (변화: +1.50 MB)
[HSII]   [SARIMA] 완료  첫값=3.30e+08 (메모리: 1486.0 MB)
[HSII]   [ETS] 시작  (메모리: 1486.0 MB)
[메모리] forecast_ets 실행 전: 1486.04 MB
[메모리] forecast_ets 실행 후: 1486.26 MB (변화: +0.21 MB)
[HSII]   [ETS] 완료  첫값=3.31e+08 (메모리: 1486.3 MB)
[HSII]   [Prophet] 시작  (메모리: 1486.3 MB)

10:32:00 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1486.26 MB

10:32:01 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1487.25 MB (변화: +0.99 MB)
[HSII]   [Prophet] 완료  첫값=3.09e+08 (메모리: 1487.2 MB)
[HSII]   [LSTM] 시작  (메모리: 1487.2 MB)
[메모리] forecast_lstm 실행 전: 1487.25 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1466.79 MB (변화: -20.46 MB)
[HSII]   [LSTM] 완료  첫값=2.85e+08 (메모리: 1466.8 MB)
[HSII]   [Theta] 시작  (메모리: 1466.8 MB)
[메모리] forecast_theta 실행 전: 1466.79 MB
[메모리] forecast_theta 실행 후: 1466.80 MB (변화: +0.00 MB)
[HSII]   [Theta] 완료  첫값=3.27e+08 (메모리: 1466.8 MB)
[HSII]   [DB] 88행 저장 완료
[PROGRESS] [  13/500] (  2.6%)  >>  ALX
[ALX]   40분기 | 2016-03-31 ~ 2025-12-31
[ALX]   [SARIMA] 시작  (메모리: 1467.2 MB)
[메모리] forecast_sarima 실행 전: 1467.20 MB
[메모리] find_best_sarima_params 실행 전: 1467.20 MB
[메모리] find_best_sarima_params 실행 후: 1468.91 MB (변화: +1.71 MB)
[메모리] forecast_sarima 실행 후: 1468.91 MB (변화: +1.71 MB)
[ALX]   [SARIMA] 완료  첫값=5.23e+07 (메모리: 1468.9 MB)
[ALX]   [ETS] 시작  (메모리: 1468.9 MB)
[메모리] forecast_ets 실행 전: 1468.91 MB
[메모리] forecast_ets 실행 후: 1469.21 MB (변화: +0.29 MB)
[ALX]   [ETS] 완료  첫값=5.27e+07 (메모리: 1469.2 MB)
[ALX]   [Prophet] 시작  (메모리: 1469.2 MB)

10:32:20 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1469.21 MB

10:32:20 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1471.26 MB (변화: +2.05 MB)
[ALX]   [Prophet] 완료  첫값=5.30e+07 (메모리: 1471.3 MB)
[ALX]   [LSTM] 시작  (메모리: 1471.3 MB)
[메모리] forecast_lstm 실행 전: 1471.26 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1486.07 MB (변화: +14.82 MB)
[ALX]   [LSTM] 완료  첫값=5.64e+07 (메모리: 1486.1 MB)
[ALX]   [Theta] 시작  (메모리: 1486.1 MB)
[메모리] forecast_theta 실행 전: 1486.07 MB
[메모리] forecast_theta 실행 후: 1486.08 MB (변화: +0.00 MB)
[ALX]   [Theta] 완료  첫값=5.32e+07 (메모리: 1486.1 MB)
[ALX]   [DB] 88행 저장 완료
[PROGRESS] [  14/500] (  2.8%)  >>  AMPH
[AMPH]   40분기 | 2016-03-31 ~ 2025-12-31
[AMPH]   [SARIMA] 시작  (메모리: 1486.3 MB)
[메모리] forecast_sarima 실행 전: 1486.28 MB
[메모리] find_best_sarima_params 실행 전: 1486.28 MB
[메모리] find_best_sarima_params 실행 후: 1487.32 MB (변화: +1.04 MB)
[메모리] forecast_sarima 실행 후: 1487.32 MB (변화: +1.04 MB)
[AMPH]   [SARIMA] 완료  첫값=1.86e+08 (메모리: 1487.3 MB)
[AMPH]   [ETS] 시작  (메모리: 1487.3 MB)
[메모리] forecast_ets 실행 전: 1487.32 MB
[메모리] forecast_ets 실행 후: 1487.41 MB (변화: +0.09 MB)
[AMPH]   [ETS] 완료  첫값=1.80e+08 (메모리: 1487.4 MB)
[AMPH]   [Prophet] 시작  (메모리: 1487.4 MB)

10:32:37 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1487.41 MB

10:32:37 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1488.82 MB (변화: +1.41 MB)
[AMPH]   [Prophet] 완료  첫값=2.00e+08 (메모리: 1488.8 MB)
[AMPH]   [LSTM] 시작  (메모리: 1488.8 MB)
[메모리] forecast_lstm 실행 전: 1488.82 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1486.13 MB (변화: -2.69 MB)
[AMPH]   [LSTM] 완료  첫값=2.23e+08 (메모리: 1486.1 MB)
[AMPH]   [Theta] 시작  (메모리: 1486.1 MB)
[메모리] forecast_theta 실행 전: 1486.13 MB
[메모리] forecast_theta 실행 후: 1486.14 MB (변화: +0.01 MB)
[AMPH]   [Theta] 완료  첫값=1.76e+08 (메모리: 1486.1 MB)
[AMPH]   [DB] 88행 저장 완료
[PROGRESS] [  15/500] (  3.0%)  >>  MOMO
[MOMO]   40분기 | 2016-03-31 ~ 2025-12-31
[MOMO]   [SARIMA] 시작  (메모리: 1486.5 MB)
[메모리] forecast_sarima 실행 전: 1486.47 MB
[메모리] find_best_sarima_params 실행 전: 1486.47 MB
[메모리] find_best_sarima_params 실행 후: 1487.62 MB (변화: +1.15 MB)
[메모리] forecast_sarima 실행 후: 1487.62 MB (변화: +1.15 MB)
[MOMO]   [SARIMA] 완료  첫값=2.26e+09 (메모리: 1487.6 MB)
[MOMO]   [ETS] 시작  (메모리: 1487.6 MB)
[메모리] forecast_ets 실행 전: 1487.62 MB
[메모리] forecast_ets 실행 후: 1487.78 MB (변화: +0.16 MB)
[MOMO]   [ETS] 완료  첫값=2.22e+09 (메모리: 1487.8 MB)
[MOMO]   [Prophet] 시작  (메모리: 1487.8 MB)

10:32:53 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1487.78 MB

10:32:53 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1488.77 MB (변화: +0.99 MB)
[MOMO]   [Prophet] 완료  첫값=3.37e+09 (메모리: 1488.8 MB)
[MOMO]   [LSTM] 시작  (메모리: 1488.8 MB)
[메모리] forecast_lstm 실행 전: 1488.77 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1511.25 MB (변화: +22.48 MB)
[MOMO]   [LSTM] 완료  첫값=2.60e+09 (메모리: 1511.2 MB)
[MOMO]   [Theta] 시작  (메모리: 1511.2 MB)
[메모리] forecast_theta 실행 전: 1511.25 MB
[메모리] forecast_theta 실행 후: 1511.25 MB (변화: +0.00 MB)
[MOMO]   [Theta] 완료  첫값=2.56e+09 (메모리: 1511.2 MB)
[MOMO]   [DB] 88행 저장 완료
[PROGRESS] [  16/500] (  3.2%)  >>  CCF
[CCF]   40분기 | 2013-11-30 ~ 2023-08-31
[CCF]   [SARIMA] 시작  (메모리: 1511.3 MB)
[메모리] forecast_sarima 실행 전: 1511.26 MB
[메모리] find_best_sarima_params 실행 전: 1511.26 MB
[메모리] find_best_sarima_params 실행 후: 1511.36 MB (변화: +0.11 MB)
[메모리] forecast_sarima 실행 후: 1511.36 MB (변화: +0.11 MB)
[CCF]   [SARIMA] 완료  첫값=1.02e+08 (메모리: 1511.4 MB)
[CCF]   [ETS] 시작  (메모리: 1511.4 MB)
[메모리] forecast_ets 실행 전: 1511.36 MB
[메모리] forecast_ets 실행 후: 1511.38 MB (변화: +0.01 MB)
[CCF]   [ETS] 완료  첫값=9.73e+07 (메모리: 1511.4 MB)
[CCF]   [Prophet] 시작  (메모리: 1511.4 MB)

10:33:09 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1511.38 MB

10:33:10 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1511.46 MB (변화: +0.09 MB)
[CCF]   [Prophet] 완료  첫값=9.58e+07 (메모리: 1511.5 MB)
[CCF]   [LSTM] 시작  (메모리: 1511.5 MB)
[메모리] forecast_lstm 실행 전: 1511.46 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1482.73 MB (변화: -28.73 MB)
[CCF]   [LSTM] 완료  첫값=8.82e+07 (메모리: 1482.7 MB)
[CCF]   [Theta] 시작  (메모리: 1482.7 MB)
[메모리] forecast_theta 실행 전: 1482.73 MB
[메모리] forecast_theta 실행 후: 1482.73 MB (변화: +0.00 MB)
[CCF]   [Theta] 완료  첫값=9.63e+07 (메모리: 1482.7 MB)
[CCF]   [DB] 88행 저장 완료
[PROGRESS] [  17/500] (  3.4%)  >>  SLCA
[SLCA]   40분기 | 2014-09-30 ~ 2024-06-30
[SLCA]   [SARIMA] 시작  (메모리: 1482.9 MB)
[메모리] forecast_sarima 실행 전: 1482.94 MB
[메모리] find_best_sarima_params 실행 전: 1482.94 MB
[메모리] find_best_sarima_params 실행 후: 1484.48 MB (변화: +1.54 MB)
[메모리] forecast_sarima 실행 후: 1484.48 MB (변화: +1.54 MB)
[SLCA]   [SARIMA] 완료  첫값=3.26e+08 (메모리: 1484.5 MB)
[SLCA]   [ETS] 시작  (메모리: 1484.5 MB)
[메모리] forecast_ets 실행 전: 1484.48 MB
[메모리] forecast_ets 실행 후: 1484.60 MB (변화: +0.12 MB)
[SLCA]   [ETS] 완료  첫값=3.22e+08 (메모리: 1484.6 MB)
[SLCA]   [Prophet] 시작  (메모리: 1484.6 MB)

10:33:25 - cmdstanpy - INFO - Chain [1] start processing
10:33:25 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1484.60 MB
[메모리] forecast_prophet 실행 후: 1486.35 MB (변화: +1.75 MB)
[SLCA]   [Prophet] 완료  첫값=3.89e+08 (메모리: 1486.4 MB)
[SLCA]   [LSTM] 시작  (메모리: 1486.4 MB)
[메모리] forecast_lstm 실행 전: 1486.35 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1513.32 MB (변화: +26.96 MB)
[SLCA]   [LSTM] 완료  첫값=2.85e+08 (메모리: 1513.3 MB)
[SLCA]   [Theta] 시작  (메모리: 1512.3 MB)
[메모리] forecast_theta 실행 전: 1512.34 MB
[메모리] forecast_theta 실행 후: 1512.34 MB (변화: +0.00 MB)
[SLCA]   [Theta] 완료  첫값=3.21e+08 (메모리: 1512.3 MB)
[SLCA]   [DB] 88행 저장 완료
[PROGRESS] [  18/500] (  3.6%)  >>  SWIR
[SWIR] [SKIP] [SWIR] FMP에서 'sale' 데이터 없음
[PROGRESS] [  19/500] (  3.8%)  >>  GIII
[GIII]   40분기 | 2016-04-30 ~ 2026-01-31
[GIII]   [SARIMA] 시작  (메모리: 1512.4 MB)
[메모리] forecast_sarima 실행 전: 1512.38 MB
[메모리] find_best_sarima_params 실행 전: 1512.38 MB
[메모리] find_best_sarima_params 실행 후: 1512.42 MB (변화: +0.04 MB)
[메모리] forecast_sarima 실행 후: 1512.42 MB (변화: +0.04 MB)
[GIII]   [SARIMA] 완료  첫값=6.03e+08 (메모리: 1512.4 MB)
[GIII]   [ETS] 시작  (메모리: 1512.4 MB)
[메모리] forecast_ets 실행 전: 1512.42 MB
[메모리] forecast_ets 실행 후: 1512.43 MB (변화: +0.01 MB)
[GIII]   [ETS] 완료  첫값=5.98e+08 (메모리: 1512.4 MB)
[GIII]   [Prophet] 시작  (메모리: 1512.4 MB)

10:33:45 - cmdstanpy - INFO - Chain [1] start processing
10:33:45 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1512.43 MB
[메모리] forecast_prophet 실행 후: 1512.46 MB (변화: +0.04 MB)
[GIII]   [Prophet] 완료  첫값=7.79e+08 (메모리: 1512.5 MB)
[GIII]   [LSTM] 시작  (메모리: 1512.5 MB)
[메모리] forecast_lstm 실행 전: 1512.46 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1515.20 MB (변화: +2.73 MB)
[GIII]   [LSTM] 완료  첫값=8.07e+08 (메모리: 1515.2 MB)
[GIII]   [Theta] 시작  (메모리: 1515.2 MB)
[메모리] forecast_theta 실행 전: 1515.20 MB
[메모리] forecast_theta 실행 후: 1515.20 MB (변화: +0.00 MB)
[GIII]   [Theta] 완료  첫값=5.97e+08 (메모리: 1515.2 MB)
[GIII]   [DB] 88행 저장 완료
[PROGRESS] [  20/500] (  4.0%)  >>  IDT
[IDT]   40분기 | 2016-04-30 ~ 2026-01-31
[IDT]   [SARIMA] 시작  (메모리: 1515.2 MB)
[메모리] forecast_sarima 실행 전: 1515.20 MB
[메모리] find_best_sarima_params 실행 전: 1515.20 MB
[메모리] find_best_sarima_params 실행 후: 1515.21 MB (변화: +0.01 MB)
[메모리] forecast_sarima 실행 후: 1515.21 MB (변화: +0.01 MB)
[IDT]   [SARIMA] 완료  첫값=3.20e+08 (메모리: 1515.2 MB)
[IDT]   [ETS] 시작  (메모리: 1515.2 MB)
[메모리] forecast_ets 실행 전: 1515.21 MB
[메모리] forecast_ets 실행 후: 1515.23 MB (변화: +0.02 MB)
[IDT]   [ETS] 완료  첫값=3.18e+08 (메모리: 1515.2 MB)
[IDT]   [Prophet] 시작  (메모리: 1515.2 MB)

10:34:02 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1515.23 MB

10:34:02 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1515.27 MB (변화: +0.04 MB)
[IDT]   [Prophet] 완료  첫값=2.99e+08 (메모리: 1515.3 MB)
[IDT]   [LSTM] 시작  (메모리: 1515.3 MB)
[메모리] forecast_lstm 실행 전: 1515.27 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1488.05 MB (변화: -27.21 MB)
[IDT]   [LSTM] 완료  첫값=3.11e+08 (메모리: 1488.1 MB)
[IDT]   [Theta] 시작  (메모리: 1488.1 MB)
[메모리] forecast_theta 실행 전: 1488.05 MB
[메모리] forecast_theta 실행 후: 1488.05 MB (변화: +0.00 MB)
[IDT]   [Theta] 완료  첫값=3.18e+08 (메모리: 1488.1 MB)
[IDT]   [DB] 88행 저장 완료
[PROGRESS] [  21/500] (  4.2%)  >>  BLFS
[BLFS] [NEG-SKIP] [BLFS] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2024, 12, 31)])
[PROGRESS] [  22/500] (  4.4%)  >>  CTIC
[CTIC]   40분기 | 2013-06-30 ~ 2023-03-31
[CTIC]   [SARIMA] 시작  (메모리: 1488.4 MB)
[메모리] forecast_sarima 실행 전: 1488.44 MB
[메모리] find_best_sarima_params 실행 전: 1488.44 MB
[메모리] find_best_sarima_params 실행 후: 1489.76 MB (변화: +1.32 MB)
[메모리] forecast_sarima 실행 후: 1489.77 MB (변화: +1.33 MB)
[CTIC]   [SARIMA] 완료  첫값=2.00e+07 (메모리: 1489.8 MB)
[CTIC]   [ETS] 시작  (메모리: 1489.8 MB)
[메모리] forecast_ets 실행 전: 1489.77 MB
[메모리] forecast_ets 실행 후: 1490.04 MB (변화: +0.27 MB)
[CTIC]   [ETS] 완료  첫값=8.59e+05 (메모리: 1490.0 MB)
[CTIC]   [Prophet] 시작  (메모리: 1490.0 MB)

10:34:20 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1490.04 MB

10:34:20 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1491.50 MB (변화: +1.46 MB)
[CTIC]   [Prophet] 완료  첫값=5.03e+06 (메모리: 1491.5 MB)
[CTIC]   [LSTM] 시작  (메모리: 1491.5 MB)
[메모리] forecast_lstm 실행 전: 1491.50 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1514.64 MB (변화: +23.14 MB)
[CTIC]   [LSTM] 완료  첫값=1.19e+07 (메모리: 1514.6 MB)
[CTIC]   [Theta] 시작  (메모리: 1514.6 MB)
[메모리] forecast_theta 실행 전: 1514.64 MB
[메모리] forecast_theta 실행 후: 1514.64 MB (변화: +0.00 MB)
[CTIC]   [Theta] 완료  첫값=1.37e+07 (메모리: 1514.6 MB)
[CTIC]   [DB] 88행 저장 완료
[PROGRESS] [  23/500] (  4.6%)  >>  PZZA
[PZZA]   40분기 | 2016-03-27 ~ 2025-12-28
[PZZA]   [SARIMA] 시작  (메모리: 1514.6 MB)
[메모리] forecast_sarima 실행 전: 1514.65 MB
[메모리] find_best_sarima_params 실행 전: 1514.65 MB
[메모리] find_best_sarima_params 실행 후: 1514.68 MB (변화: +0.04 MB)
[메모리] forecast_sarima 실행 후: 1514.68 MB (변화: +0.04 MB)
[PZZA]   [SARIMA] 완료  첫값=5.00e+08 (메모리: 1514.7 MB)
[PZZA]   [ETS] 시작  (메모리: 1514.7 MB)
[메모리] forecast_ets 실행 전: 1514.68 MB
[메모리] forecast_ets 실행 후: 1514.69 MB (변화: +0.01 MB)
[PZZA]   [ETS] 완료  첫값=4.96e+08 (메모리: 1514.7 MB)
[PZZA]   [Prophet] 시작  (메모리: 1514.7 MB)

10:34:41 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1514.69 MB

10:34:41 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1514.73 MB (변화: +0.04 MB)
[PZZA]   [Prophet] 완료  첫값=5.43e+08 (메모리: 1514.7 MB)
[PZZA]   [LSTM] 시작  (메모리: 1514.7 MB)
[메모리] forecast_lstm 실행 전: 1514.73 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1517.71 MB (변화: +2.98 MB)
[PZZA]   [LSTM] 완료  첫값=5.13e+08 (메모리: 1517.7 MB)
[PZZA]   [Theta] 시작  (메모리: 1517.7 MB)
[메모리] forecast_theta 실행 전: 1517.71 MB
[메모리] forecast_theta 실행 후: 1517.71 MB (변화: +0.00 MB)
[PZZA]   [Theta] 완료  첫값=4.95e+08 (메모리: 1517.7 MB)
[PZZA]   [DB] 88행 저장 완료
[PROGRESS] [  24/500] (  4.8%)  >>  AVID
[AVID]   40분기 | 2013-12-31 ~ 2023-09-30
[AVID]   [SARIMA] 시작  (메모리: 1517.7 MB)
[메모리] forecast_sarima 실행 전: 1517.71 MB
[메모리] find_best_sarima_params 실행 전: 1517.71 MB
[메모리] find_best_sarima_params 실행 후: 1517.71 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1517.71 MB (변화: +0.00 MB)
[AVID]   [SARIMA] 완료  첫값=1.05e+08 (메모리: 1517.7 MB)
[AVID]   [ETS] 시작  (메모리: 1517.7 MB)
[메모리] forecast_ets 실행 전: 1517.71 MB
[메모리] forecast_ets 실행 후: 1517.71 MB (변화: +0.00 MB)
[AVID]   [ETS] 완료  첫값=1.08e+08 (메모리: 1517.7 MB)
[AVID]   [Prophet] 시작  (메모리: 1517.7 MB)

10:34:57 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1517.71 MB

10:34:57 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1517.75 MB (변화: +0.04 MB)
[AVID]   [Prophet] 완료  첫값=8.99e+07 (메모리: 1517.8 MB)
[AVID]   [LSTM] 시작  (메모리: 1517.8 MB)
[메모리] forecast_lstm 실행 전: 1517.75 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1518.39 MB (변화: +0.64 MB)
[AVID]   [LSTM] 완료  첫값=9.72e+07 (메모리: 1518.4 MB)
[AVID]   [Theta] 시작  (메모리: 1518.4 MB)
[메모리] forecast_theta 실행 전: 1518.39 MB
[메모리] forecast_theta 실행 후: 1518.39 MB (변화: +0.00 MB)
[AVID]   [Theta] 완료  첫값=1.05e+08 (메모리: 1518.4 MB)
[AVID]   [DB] 88행 저장 완료
[PROGRESS] [  25/500] (  5.0%)  >>  PLPC
[PLPC]   40분기 | 2016-03-31 ~ 2025-12-31
[PLPC]   [SARIMA] 시작  (메모리: 1518.4 MB)
[메모리] forecast_sarima 실행 전: 1518.40 MB
[메모리] find_best_sarima_params 실행 전: 1518.40 MB
[메모리] find_best_sarima_params 실행 후: 1518.38 MB (변화: -0.02 MB)
[메모리] forecast_sarima 실행 후: 1518.38 MB (변화: -0.02 MB)
[PLPC]   [SARIMA] 완료  첫값=1.77e+08 (메모리: 1518.4 MB)
[PLPC]   [ETS] 시작  (메모리: 1518.4 MB)
[메모리] forecast_ets 실행 전: 1518.38 MB
[메모리] forecast_ets 실행 후: 1518.39 MB (변화: +0.01 MB)
[PLPC]   [ETS] 완료  첫값=1.69e+08 (메모리: 1518.4 MB)
[PLPC]   [Prophet] 시작  (메모리: 1518.4 MB)

10:35:14 - cmdstanpy - INFO - Chain [1] start processing
10:35:14 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1518.39 MB
[메모리] forecast_prophet 실행 후: 1518.41 MB (변화: +0.02 MB)
[PLPC]   [Prophet] 완료  첫값=1.78e+08 (메모리: 1518.4 MB)
[PLPC]   [LSTM] 시작  (메모리: 1518.4 MB)
[메모리] forecast_lstm 실행 전: 1518.41 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1521.62 MB (변화: +3.21 MB)
[PLPC]   [LSTM] 완료  첫값=1.62e+08 (메모리: 1521.6 MB)
[PLPC]   [Theta] 시작  (메모리: 1521.6 MB)
[메모리] forecast_theta 실행 전: 1521.62 MB
[메모리] forecast_theta 실행 후: 1521.62 MB (변화: +0.00 MB)
[PLPC]   [Theta] 완료  첫값=1.67e+08 (메모리: 1521.6 MB)
[PLPC]   [DB] 88행 저장 완료
[PROGRESS] [  26/500] (  5.2%)  >>  VVI
[VVI] [NEG-SKIP] [VVI] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2024, 12, 31)])
[PROGRESS] [  27/500] (  5.4%)  >>  DMLP
[DMLP]   40분기 | 2016-03-31 ~ 2025-12-31
[DMLP]   [SARIMA] 시작  (메모리: 1521.6 MB)
[메모리] forecast_sarima 실행 전: 1521.62 MB
[메모리] find_best_sarima_params 실행 전: 1521.62 MB
[메모리] find_best_sarima_params 실행 후: 1521.62 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1521.62 MB (변화: +0.00 MB)
[DMLP]   [SARIMA] 완료  첫값=3.99e+07 (메모리: 1521.6 MB)
[DMLP]   [ETS] 시작  (메모리: 1521.6 MB)
[메모리] forecast_ets 실행 전: 1521.62 MB
[메모리] forecast_ets 실행 후: 1521.63 MB (변화: +0.01 MB)
[DMLP]   [ETS] 완료  첫값=4.01e+07 (메모리: 1521.6 MB)
[DMLP]   [Prophet] 시작  (메모리: 1521.6 MB)

10:35:29 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1521.63 MB

10:35:29 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1521.69 MB (변화: +0.05 MB)
[DMLP]   [Prophet] 완료  첫값=4.58e+07 (메모리: 1521.7 MB)
[DMLP]   [LSTM] 시작  (메모리: 1521.7 MB)
[메모리] forecast_lstm 실행 전: 1521.69 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1522.57 MB (변화: +0.89 MB)
[DMLP]   [LSTM] 완료  첫값=3.87e+07 (메모리: 1522.6 MB)
[DMLP]   [Theta] 시작  (메모리: 1522.6 MB)
[메모리] forecast_theta 실행 전: 1522.57 MB
[메모리] forecast_theta 실행 후: 1522.57 MB (변화: +0.00 MB)
[DMLP]   [Theta] 완료  첫값=4.00e+07 (메모리: 1522.6 MB)
[DMLP]   [DB] 88행 저장 완료
[PROGRESS] [  28/500] (  5.6%)  >>  MODN
[MODN]   40분기 | 2014-06-30 ~ 2024-03-31
[MODN]   [SARIMA] 시작  (메모리: 1522.6 MB)
[메모리] forecast_sarima 실행 전: 1522.57 MB
[메모리] find_best_sarima_params 실행 전: 1522.57 MB
[메모리] find_best_sarima_params 실행 후: 1522.57 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1522.57 MB (변화: +0.00 MB)
[MODN]   [SARIMA] 완료  첫값=6.72e+07 (메모리: 1522.6 MB)
[MODN]   [ETS] 시작  (메모리: 1522.6 MB)
[메모리] forecast_ets 실행 전: 1522.57 MB
[메모리] forecast_ets 실행 후: 1522.59 MB (변화: +0.02 MB)
[MODN]   [ETS] 완료  첫값=6.74e+07 (메모리: 1522.6 MB)
[MODN]   [Prophet] 시작  (메모리: 1522.6 MB)

10:35:46 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1522.59 MB

10:35:47 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1522.67 MB (변화: +0.08 MB)
[MODN]   [Prophet] 완료  첫값=6.76e+07 (메모리: 1522.7 MB)
[MODN]   [LSTM] 시작  (메모리: 1522.7 MB)
[메모리] forecast_lstm 실행 전: 1522.67 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1523.02 MB (변화: +0.35 MB)
[MODN]   [LSTM] 완료  첫값=6.76e+07 (메모리: 1523.0 MB)
[MODN]   [Theta] 시작  (메모리: 1523.0 MB)
[메모리] forecast_theta 실행 전: 1523.02 MB
[메모리] forecast_theta 실행 후: 1523.02 MB (변화: +0.00 MB)
[MODN]   [Theta] 완료  첫값=6.63e+07 (메모리: 1523.0 MB)
[MODN]   [DB] 88행 저장 완료
[PROGRESS] [  29/500] (  5.8%)  >>  CCOI
[CCOI]   40분기 | 2016-03-31 ~ 2025-12-31
[CCOI]   [SARIMA] 시작  (메모리: 1523.0 MB)
[메모리] forecast_sarima 실행 전: 1523.02 MB
[메모리] find_best_sarima_params 실행 전: 1523.02 MB
[메모리] find_best_sarima_params 실행 후: 1523.03 MB (변화: +0.01 MB)
[메모리] forecast_sarima 실행 후: 1523.03 MB (변화: +0.01 MB)
[CCOI]   [SARIMA] 완료  첫값=2.46e+08 (메모리: 1523.0 MB)
[CCOI]   [ETS] 시작  (메모리: 1523.0 MB)
[메모리] forecast_ets 실행 전: 1523.03 MB
[메모리] forecast_ets 실행 후: 1523.03 MB (변화: +0.00 MB)
[CCOI]   [ETS] 완료  첫값=2.42e+08 (메모리: 1523.0 MB)
[CCOI]   [Prophet] 시작  (메모리: 1523.0 MB)

10:36:02 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1523.03 MB

10:36:02 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1523.07 MB (변화: +0.04 MB)
[CCOI]   [Prophet] 완료  첫값=2.50e+08 (메모리: 1523.1 MB)
[CCOI]   [LSTM] 시작  (메모리: 1523.1 MB)
[메모리] forecast_lstm 실행 전: 1523.07 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1493.32 MB (변화: -29.74 MB)
[CCOI]   [LSTM] 완료  첫값=2.81e+08 (메모리: 1493.3 MB)
[CCOI]   [Theta] 시작  (메모리: 1493.3 MB)
[메모리] forecast_theta 실행 전: 1493.32 MB
[메모리] forecast_theta 실행 후: 1493.32 MB (변화: +0.00 MB)
[CCOI]   [Theta] 완료  첫값=2.40e+08 (메모리: 1493.3 MB)
[CCOI]   [DB] 88행 저장 완료
[PROGRESS] [  30/500] (  6.0%)  >>  EZT
[EZT] [SKIP] [EZT] FMP에서 'sale' 데이터 없음
[PROGRESS] [  31/500] (  6.2%)  >>  MRC
[MRC]   40분기 | 2015-12-31 ~ 2025-09-30
[MRC]   [SARIMA] 시작  (메모리: 1493.8 MB)
[메모리] forecast_sarima 실행 전: 1493.79 MB
[메모리] find_best_sarima_params 실행 전: 1493.79 MB
[메모리] find_best_sarima_params 실행 후: 1494.97 MB (변화: +1.19 MB)
[메모리] forecast_sarima 실행 후: 1494.97 MB (변화: +1.19 MB)
[MRC]   [SARIMA] 완료  첫값=6.78e+08 (메모리: 1495.0 MB)
[MRC]   [ETS] 시작  (메모리: 1495.0 MB)
[메모리] forecast_ets 실행 전: 1494.97 MB
[메모리] forecast_ets 실행 후: 1495.25 MB (변화: +0.28 MB)
[MRC]   [ETS] 완료  첫값=6.11e+08 (메모리: 1495.2 MB)
[MRC]   [Prophet] 시작  (메모리: 1495.2 MB)

10:36:22 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1495.25 MB

10:36:23 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1497.01 MB (변화: +1.76 MB)
[MRC]   [Prophet] 완료  첫값=7.31e+08 (메모리: 1497.0 MB)
[MRC]   [LSTM] 시작  (메모리: 1497.0 MB)
[메모리] forecast_lstm 실행 전: 1497.01 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1519.19 MB (변화: +22.18 MB)
[MRC]   [LSTM] 완료  첫값=7.47e+08 (메모리: 1519.2 MB)
[MRC]   [Theta] 시작  (메모리: 1519.2 MB)
[메모리] forecast_theta 실행 전: 1519.19 MB
[메모리] forecast_theta 실행 후: 1519.19 MB (변화: +0.00 MB)
[MRC]   [Theta] 완료  첫값=6.86e+08 (메모리: 1519.2 MB)
[MRC]   [DB] 88행 저장 완료
[PROGRESS] [  32/500] (  6.4%)  >>  PMT
[PMT] [NEG-SKIP] [PMT] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2021, 3, 31), datetime.date(2022, 3, 31), datetime.date(2022, 6, 30)])
[PROGRESS] [  33/500] (  6.6%)  >>  LPG
[LPG]   40분기 | 2016-03-31 ~ 2025-12-31
[LPG]   [SARIMA] 시작  (메모리: 1519.3 MB)
[메모리] forecast_sarima 실행 전: 1519.29 MB
[메모리] find_best_sarima_params 실행 전: 1519.29 MB
[메모리] find_best_sarima_params 실행 후: 1519.39 MB (변화: +0.11 MB)
[메모리] forecast_sarima 실행 후: 1519.39 MB (변화: +0.11 MB)
[LPG]   [SARIMA] 완료  첫값=1.20e+08 (메모리: 1519.4 MB)
[LPG]   [ETS] 시작  (메모리: 1519.4 MB)
[메모리] forecast_ets 실행 전: 1519.39 MB
[메모리] forecast_ets 실행 후: 1519.40 MB (변화: +0.01 MB)
[LPG]   [ETS] 완료  첫값=1.22e+08 (메모리: 1519.4 MB)
[LPG]   [Prophet] 시작  (메모리: 1519.4 MB)

10:36:42 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1519.40 MB

10:36:42 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1519.49 MB (변화: +0.09 MB)
[LPG]   [Prophet] 완료  첫값=1.22e+08 (메모리: 1519.5 MB)
[LPG]   [LSTM] 시작  (메모리: 1519.5 MB)
[메모리] forecast_lstm 실행 전: 1519.49 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1522.75 MB (변화: +3.26 MB)
[LPG]   [LSTM] 완료  첫값=1.39e+08 (메모리: 1522.8 MB)
[LPG]   [Theta] 시작  (메모리: 1522.8 MB)
[메모리] forecast_theta 실행 전: 1522.75 MB
[메모리] forecast_theta 실행 후: 1522.75 MB (변화: +0.00 MB)
[LPG]   [Theta] 완료  첫값=1.21e+08 (메모리: 1522.8 MB)
[LPG]   [DB] 88행 저장 완료
[PROGRESS] [  34/500] (  6.8%)  >>  HLIT
[HLIT]   40분기 | 2016-04-01 ~ 2025-12-31
[HLIT]   [SARIMA] 시작  (메모리: 1522.8 MB)
[메모리] forecast_sarima 실행 전: 1522.75 MB
[메모리] find_best_sarima_params 실행 전: 1522.75 MB
[메모리] find_best_sarima_params 실행 후: 1522.77 MB (변화: +0.02 MB)
[메모리] forecast_sarima 실행 후: 1522.77 MB (변화: +0.02 MB)
[HLIT]   [SARIMA] 완료  첫값=8.04e+07 (메모리: 1522.8 MB)
[HLIT]   [ETS] 시작  (메모리: 1522.8 MB)
[메모리] forecast_ets 실행 전: 1522.77 MB
[메모리] forecast_ets 실행 후: 1522.77 MB (변화: +0.00 MB)
[HLIT]   [ETS] 완료  첫값=7.60e+07 (메모리: 1522.8 MB)
[HLIT]   [Prophet] 시작  (메모리: 1522.8 MB)

10:36:56 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1522.77 MB

10:36:56 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1522.85 MB (변화: +0.08 MB)
[HLIT]   [Prophet] 완료  첫값=1.61e+08 (메모리: 1522.8 MB)
[HLIT]   [LSTM] 시작  (메모리: 1522.8 MB)
[메모리] forecast_lstm 실행 전: 1522.85 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1525.75 MB (변화: +2.90 MB)
[HLIT]   [LSTM] 완료  첫값=1.45e+08 (메모리: 1525.7 MB)
[HLIT]   [Theta] 시작  (메모리: 1525.7 MB)
[메모리] forecast_theta 실행 전: 1525.75 MB
[메모리] forecast_theta 실행 후: 1525.75 MB (변화: +0.00 MB)
[HLIT]   [Theta] 완료  첫값=7.64e+07 (메모리: 1525.7 MB)
[HLIT]   [DB] 88행 저장 완료
[PROGRESS] [  35/500] (  7.0%)  >>  GIC
[GIC]   40분기 | 2016-03-31 ~ 2025-12-31
[GIC]   [SARIMA] 시작  (메모리: 1525.8 MB)
[메모리] forecast_sarima 실행 전: 1525.76 MB
[메모리] find_best_sarima_params 실행 전: 1525.76 MB
[메모리] find_best_sarima_params 실행 후: 1525.77 MB (변화: +0.01 MB)
[메모리] forecast_sarima 실행 후: 1525.77 MB (변화: +0.01 MB)
[GIC]   [SARIMA] 완료  첫값=3.44e+08 (메모리: 1525.8 MB)
[GIC]   [ETS] 시작  (메모리: 1525.8 MB)
[메모리] forecast_ets 실행 전: 1525.77 MB
[메모리] forecast_ets 실행 후: 1525.78 MB (변화: +0.01 MB)
[GIC]   [ETS] 완료  첫값=3.45e+08 (메모리: 1525.8 MB)
[GIC]   [Prophet] 시작  (메모리: 1525.8 MB)

10:37:12 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1525.78 MB

10:37:12 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1525.83 MB (변화: +0.05 MB)
[GIC]   [Prophet] 완료  첫값=2.98e+08 (메모리: 1525.8 MB)
[GIC]   [LSTM] 시작  (메모리: 1525.8 MB)
[메모리] forecast_lstm 실행 전: 1525.83 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1526.71 MB (변화: +0.88 MB)
[GIC]   [LSTM] 완료  첫값=3.28e+08 (메모리: 1526.7 MB)
[GIC]   [Theta] 시작  (메모리: 1526.7 MB)
[메모리] forecast_theta 실행 전: 1526.71 MB
[메모리] forecast_theta 실행 후: 1526.71 MB (변화: +0.00 MB)
[GIC]   [Theta] 완료  첫값=3.46e+08 (메모리: 1526.7 MB)
[GIC]   [DB] 88행 저장 완료
[PROGRESS] [  36/500] (  7.2%)  >>  LGIH
[LGIH]   40분기 | 2016-03-31 ~ 2025-12-31
[LGIH]   [SARIMA] 시작  (메모리: 1526.7 MB)
[메모리] forecast_sarima 실행 전: 1526.71 MB
[메모리] find_best_sarima_params 실행 전: 1526.71 MB
[메모리] find_best_sarima_params 실행 후: 1526.71 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1526.71 MB (변화: +0.00 MB)
[LGIH]   [SARIMA] 완료  첫값=3.97e+08 (메모리: 1526.7 MB)
[LGIH]   [ETS] 시작  (메모리: 1526.7 MB)
[메모리] forecast_ets 실행 전: 1526.71 MB
[메모리] forecast_ets 실행 후: 1526.72 MB (변화: +0.01 MB)
[LGIH]   [ETS] 완료  첫값=3.41e+08 (메모리: 1526.7 MB)
[LGIH]   [Prophet] 시작  (메모리: 1526.7 MB)

10:37:31 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1526.72 MB

10:37:31 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1526.75 MB (변화: +0.03 MB)
[LGIH]   [Prophet] 완료  첫값=6.55e+08 (메모리: 1526.8 MB)
[LGIH]   [LSTM] 시작  (메모리: 1526.8 MB)
[메모리] forecast_lstm 실행 전: 1526.75 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1527.17 MB (변화: +0.41 MB)
[LGIH]   [LSTM] 완료  첫값=5.20e+08 (메모리: 1527.2 MB)
[LGIH]   [Theta] 시작  (메모리: 1527.2 MB)
[메모리] forecast_theta 실행 전: 1527.17 MB
[메모리] forecast_theta 실행 후: 1527.17 MB (변화: +0.00 MB)
[LGIH]   [Theta] 완료  첫값=3.39e+08 (메모리: 1527.2 MB)
[LGIH]   [DB] 88행 저장 완료
[PROGRESS] [  37/500] (  7.4%)  >>  NPKI
[NPKI]   40분기 | 2016-03-31 ~ 2025-12-31
[NPKI]   [SARIMA] 시작  (메모리: 1527.2 MB)
[메모리] forecast_sarima 실행 전: 1527.17 MB
[메모리] find_best_sarima_params 실행 전: 1527.17 MB
[메모리] find_best_sarima_params 실행 후: 1527.17 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1527.17 MB (변화: +0.00 MB)
[NPKI]   [SARIMA] 완료  첫값=7.52e+07 (메모리: 1527.2 MB)
[NPKI]   [ETS] 시작  (메모리: 1527.2 MB)
[메모리] forecast_ets 실행 전: 1527.17 MB
[메모리] forecast_ets 실행 후: 1527.18 MB (변화: +0.01 MB)
[NPKI]   [ETS] 완료  첫값=7.58e+07 (메모리: 1527.2 MB)
[NPKI]   [Prophet] 시작  (메모리: 1527.2 MB)

10:37:45 - cmdstanpy - INFO - Chain [1] start processing
10:37:45 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1527.18 MB
[메모리] forecast_prophet 실행 후: 1527.21 MB (변화: +0.03 MB)
[NPKI]   [Prophet] 완료  첫값=8.79e+07 (메모리: 1527.2 MB)
[NPKI]   [LSTM] 시작  (메모리: 1527.2 MB)
[메모리] forecast_lstm 실행 전: 1527.21 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1526.86 MB (변화: -0.35 MB)
[NPKI]   [LSTM] 완료  첫값=8.30e+07 (메모리: 1526.9 MB)
[NPKI]   [Theta] 시작  (메모리: 1526.9 MB)
[메모리] forecast_theta 실행 전: 1526.86 MB
[메모리] forecast_theta 실행 후: 1526.86 MB (변화: +0.00 MB)
[NPKI]   [Theta] 완료  첫값=7.42e+07 (메모리: 1526.9 MB)
[NPKI]   [DB] 88행 저장 완료
[PROGRESS] [  38/500] (  7.6%)  >>  RLJ
[RLJ]   40분기 | 2016-03-31 ~ 2025-12-31
[RLJ]   [SARIMA] 시작  (메모리: 1526.9 MB)
[메모리] forecast_sarima 실행 전: 1526.86 MB
[메모리] find_best_sarima_params 실행 전: 1526.86 MB
[메모리] find_best_sarima_params 실행 후: 1526.86 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1526.86 MB (변화: +0.00 MB)
[RLJ]   [SARIMA] 완료  첫값=3.28e+08 (메모리: 1526.9 MB)
[RLJ]   [ETS] 시작  (메모리: 1526.9 MB)
[메모리] forecast_ets 실행 전: 1526.86 MB
[메모리] forecast_ets 실행 후: 1526.86 MB (변화: +0.00 MB)
[RLJ]   [ETS] 완료  첫값=3.28e+08 (메모리: 1526.9 MB)
[RLJ]   [Prophet] 시작  (메모리: 1526.9 MB)

10:38:03 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1526.86 MB

10:38:03 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1526.95 MB (변화: +0.09 MB)
[RLJ]   [Prophet] 완료  첫값=3.01e+08 (메모리: 1526.9 MB)
[RLJ]   [LSTM] 시작  (메모리: 1526.9 MB)
[메모리] forecast_lstm 실행 전: 1526.95 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1528.90 MB (변화: +1.95 MB)
[RLJ]   [LSTM] 완료  첫값=2.87e+08 (메모리: 1528.9 MB)
[RLJ]   [Theta] 시작  (메모리: 1528.9 MB)
[메모리] forecast_theta 실행 전: 1528.90 MB
[메모리] forecast_theta 실행 후: 1528.90 MB (변화: +0.00 MB)
[RLJ]   [Theta] 완료  첫값=3.30e+08 (메모리: 1528.9 MB)
[RLJ]   [DB] 88행 저장 완료
[PROGRESS] [  39/500] (  7.8%)  >>  CIR
[CIR]   40분기 | 2013-09-29 ~ 2023-07-02
[CIR]   [SARIMA] 시작  (메모리: 1528.9 MB)
[메모리] forecast_sarima 실행 전: 1528.91 MB
[메모리] find_best_sarima_params 실행 전: 1528.91 MB
[메모리] find_best_sarima_params 실행 후: 1528.92 MB (변화: +0.01 MB)
[메모리] forecast_sarima 실행 후: 1528.92 MB (변화: +0.01 MB)
[CIR]   [SARIMA] 완료  첫값=1.97e+08 (메모리: 1528.9 MB)
[CIR]   [ETS] 시작  (메모리: 1528.9 MB)
[메모리] forecast_ets 실행 전: 1528.92 MB
[메모리] forecast_ets 실행 후: 1528.93 MB (변화: +0.01 MB)
[CIR]   [ETS] 완료  첫값=2.07e+08 (메모리: 1528.9 MB)
[CIR]   [Prophet] 시작  (메모리: 1528.9 MB)

10:38:22 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1528.93 MB

10:38:22 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1528.96 MB (변화: +0.04 MB)
[CIR]   [Prophet] 완료  첫값=2.15e+08 (메모리: 1529.0 MB)
[CIR]   [LSTM] 시작  (메모리: 1529.0 MB)
[메모리] forecast_lstm 실행 전: 1528.96 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1531.36 MB (변화: +2.39 MB)
[CIR]   [LSTM] 완료  첫값=1.90e+08 (메모리: 1531.4 MB)
[CIR]   [Theta] 시작  (메모리: 1531.4 MB)
[메모리] forecast_theta 실행 전: 1531.36 MB
[메모리] forecast_theta 실행 후: 1531.36 MB (변화: +0.00 MB)
[CIR]   [Theta] 완료  첫값=2.09e+08 (메모리: 1531.4 MB)
[CIR]   [DB] 88행 저장 완료
[PROGRESS] [  40/500] (  8.0%)  >>  ESRT
[ESRT]   40분기 | 2016-03-31 ~ 2025-12-31
[ESRT]   [SARIMA] 시작  (메모리: 1531.4 MB)
[메모리] forecast_sarima 실행 전: 1531.36 MB
[메모리] find_best_sarima_params 실행 전: 1531.36 MB
[메모리] find_best_sarima_params 실행 후: 1531.36 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1531.36 MB (변화: +0.00 MB)
[ESRT]   [SARIMA] 완료  첫값=2.00e+08 (메모리: 1531.4 MB)
[ESRT]   [ETS] 시작  (메모리: 1531.4 MB)
[메모리] forecast_ets 실행 전: 1531.36 MB
[메모리] forecast_ets 실행 후: 1531.37 MB (변화: +0.01 MB)
[ESRT]   [ETS] 완료  첫값=1.83e+08 (메모리: 1531.4 MB)
[ESRT]   [Prophet] 시작  (메모리: 1531.4 MB)
[메모리] forecast_prophet 실행 전: 1531.37 MB

10:38:43 - cmdstanpy - INFO - Chain [1] start processing
10:38:43 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1531.41 MB (변화: +0.04 MB)
[ESRT]   [Prophet] 완료  첫값=1.88e+08 (메모리: 1531.4 MB)
[ESRT]   [LSTM] 시작  (메모리: 1531.4 MB)
[메모리] forecast_lstm 실행 전: 1531.41 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1532.20 MB (변화: +0.79 MB)
[ESRT]   [LSTM] 완료  첫값=1.85e+08 (메모리: 1532.2 MB)
[ESRT]   [Theta] 시작  (메모리: 1532.2 MB)
[메모리] forecast_theta 실행 전: 1532.20 MB
[메모리] forecast_theta 실행 후: 1532.20 MB (변화: +0.00 MB)
[ESRT]   [Theta] 완료  첫값=1.83e+08 (메모리: 1532.2 MB)
[ESRT]   [DB] 88행 저장 완료
[PROGRESS] [  41/500] (  8.2%)  >>  PRO
[PRO]   40분기 | 2015-12-31 ~ 2025-09-30
[PRO]   [SARIMA] 시작  (메모리: 1532.2 MB)
[메모리] forecast_sarima 실행 전: 1532.20 MB
[메모리] find_best_sarima_params 실행 전: 1532.20 MB
[메모리] find_best_sarima_params 실행 후: 1532.20 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1532.20 MB (변화: +0.00 MB)
[PRO]   [SARIMA] 완료  첫값=9.43e+07 (메모리: 1532.2 MB)
[PRO]   [ETS] 시작  (메모리: 1532.2 MB)
[메모리] forecast_ets 실행 전: 1532.20 MB
[메모리] forecast_ets 실행 후: 1532.20 MB (변화: +0.00 MB)
[PRO]   [ETS] 완료  첫값=9.48e+07 (메모리: 1532.2 MB)
[PRO]   [Prophet] 시작  (메모리: 1532.2 MB)

10:39:01 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1532.20 MB

10:39:01 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1532.22 MB (변화: +0.02 MB)
[PRO]   [Prophet] 완료  첫값=8.95e+07 (메모리: 1532.2 MB)
[PRO]   [LSTM] 시작  (메모리: 1532.2 MB)
[메모리] forecast_lstm 실행 전: 1532.22 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1532.28 MB (변화: +0.05 MB)
[PRO]   [LSTM] 완료  첫값=8.82e+07 (메모리: 1532.3 MB)
[PRO]   [Theta] 시작  (메모리: 1532.3 MB)
[메모리] forecast_theta 실행 전: 1532.28 MB
[메모리] forecast_theta 실행 후: 1532.28 MB (변화: +0.00 MB)
[PRO]   [Theta] 완료  첫값=9.37e+07 (메모리: 1532.3 MB)
[PRO]   [DB] 88행 저장 완료
[PROGRESS] [  42/500] (  8.4%)  >>  THRM
[THRM]   40분기 | 2016-03-31 ~ 2025-12-31
[THRM]   [SARIMA] 시작  (메모리: 1532.3 MB)
[메모리] forecast_sarima 실행 전: 1532.28 MB
[메모리] find_best_sarima_params 실행 전: 1532.28 MB
[메모리] find_best_sarima_params 실행 후: 1532.28 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1532.28 MB (변화: +0.00 MB)
[THRM]   [SARIMA] 완료  첫값=3.89e+08 (메모리: 1532.3 MB)
[THRM]   [ETS] 시작  (메모리: 1532.3 MB)
[메모리] forecast_ets 실행 전: 1532.28 MB
[메모리] forecast_ets 실행 후: 1532.29 MB (변화: +0.01 MB)
[THRM]   [ETS] 완료  첫값=3.94e+08 (메모리: 1532.3 MB)
[THRM]   [Prophet] 시작  (메모리: 1532.3 MB)

10:39:15 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1532.29 MB

10:39:16 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1532.30 MB (변화: +0.02 MB)
[THRM]   [Prophet] 완료  첫값=3.77e+08 (메모리: 1532.3 MB)
[THRM]   [LSTM] 시작  (메모리: 1532.3 MB)
[메모리] forecast_lstm 실행 전: 1532.30 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1532.04 MB (변화: -0.27 MB)
[THRM]   [LSTM] 완료  첫값=3.90e+08 (메모리: 1532.0 MB)
[THRM]   [Theta] 시작  (메모리: 1532.0 MB)
[메모리] forecast_theta 실행 전: 1532.04 MB
[메모리] forecast_theta 실행 후: 1532.04 MB (변화: +0.00 MB)
[THRM]   [Theta] 완료  첫값=3.91e+08 (메모리: 1532.0 MB)
[THRM]   [DB] 88행 저장 완료
[PROGRESS] [  43/500] (  8.6%)  >>  BW
[BW]   40분기 | 2016-03-31 ~ 2025-12-31
[BW]   [SARIMA] 시작  (메모리: 1532.0 MB)
[메모리] forecast_sarima 실행 전: 1532.04 MB
[메모리] find_best_sarima_params 실행 전: 1532.04 MB
[메모리] find_best_sarima_params 실행 후: 1532.04 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1532.04 MB (변화: +0.00 MB)
[BW]   [SARIMA] 완료  첫값=1.52e+08 (메모리: 1532.0 MB)
[BW]   [ETS] 시작  (메모리: 1532.0 MB)
[메모리] forecast_ets 실행 전: 1532.04 MB
[메모리] forecast_ets 실행 후: 1532.04 MB (변화: +0.00 MB)
[BW]   [ETS] 완료  첫값=1.49e+08 (메모리: 1532.0 MB)
[BW]   [Prophet] 시작  (메모리: 1532.0 MB)

10:39:29 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1532.04 MB

10:39:29 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1532.07 MB (변화: +0.04 MB)
[BW]   [Prophet] 완료  첫값=1.22e+08 (메모리: 1532.1 MB)
[BW]   [LSTM] 시작  (메모리: 1532.1 MB)
[메모리] forecast_lstm 실행 전: 1532.07 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1533.03 MB (변화: +0.95 MB)
[BW]   [LSTM] 완료  첫값=1.67e+08 (메모리: 1533.0 MB)
[BW]   [Theta] 시작  (메모리: 1533.0 MB)
[메모리] forecast_theta 실행 전: 1533.03 MB
[메모리] forecast_theta 실행 후: 1533.03 MB (변화: +0.00 MB)
[BW]   [Theta] 완료  첫값=1.56e+08 (메모리: 1533.0 MB)
[BW]   [DB] 88행 저장 완료
[PROGRESS] [  44/500] (  8.8%)  >>  UPBD
[UPBD]   40분기 | 2016-03-31 ~ 2025-12-31
[UPBD]   [SARIMA] 시작  (메모리: 1533.0 MB)
[메모리] forecast_sarima 실행 전: 1533.03 MB
[메모리] find_best_sarima_params 실행 전: 1533.03 MB
[메모리] find_best_sarima_params 실행 후: 1533.03 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1533.03 MB (변화: +0.00 MB)
[UPBD]   [SARIMA] 완료  첫값=1.33e+09 (메모리: 1533.0 MB)
[UPBD]   [ETS] 시작  (메모리: 1533.0 MB)
[메모리] forecast_ets 실행 전: 1533.03 MB
[메모리] forecast_ets 실행 후: 1533.04 MB (변화: +0.01 MB)
[UPBD]   [ETS] 완료  첫값=1.31e+09 (메모리: 1533.0 MB)
[UPBD]   [Prophet] 시작  (메모리: 1533.0 MB)

10:39:45 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1533.04 MB

10:39:46 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1533.05 MB (변화: +0.02 MB)
[UPBD]   [Prophet] 완료  첫값=1.20e+09 (메모리: 1533.1 MB)
[UPBD]   [LSTM] 시작  (메모리: 1533.1 MB)
[메모리] forecast_lstm 실행 전: 1533.05 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1533.50 MB (변화: +0.44 MB)
[UPBD]   [LSTM] 완료  첫값=1.14e+09 (메모리: 1533.5 MB)
[UPBD]   [Theta] 시작  (메모리: 1533.5 MB)
[메모리] forecast_theta 실행 전: 1533.50 MB
[메모리] forecast_theta 실행 후: 1533.50 MB (변화: +0.00 MB)
[UPBD]   [Theta] 완료  첫값=1.31e+09 (메모리: 1533.5 MB)
[UPBD]   [DB] 88행 저장 완료
[PROGRESS] [  45/500] (  9.0%)  >>  TDOC
[TDOC]   40분기 | 2016-03-31 ~ 2025-12-31
[TDOC]   [SARIMA] 시작  (메모리: 1533.5 MB)
[메모리] forecast_sarima 실행 전: 1533.50 MB
[메모리] find_best_sarima_params 실행 전: 1533.50 MB
[메모리] find_best_sarima_params 실행 후: 1533.50 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1533.50 MB (변화: +0.00 MB)
[TDOC]   [SARIMA] 완료  첫값=6.62e+08 (메모리: 1533.5 MB)
[TDOC]   [ETS] 시작  (메모리: 1533.5 MB)
[메모리] forecast_ets 실행 전: 1533.50 MB
[메모리] forecast_ets 실행 후: 1533.50 MB (변화: +0.01 MB)
[TDOC]   [ETS] 완료  첫값=6.32e+08 (메모리: 1533.5 MB)
[TDOC]   [Prophet] 시작  (메모리: 1533.5 MB)

10:40:06 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1533.50 MB

10:40:06 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1533.53 MB (변화: +0.02 MB)
[TDOC]   [Prophet] 완료  첫값=7.93e+08 (메모리: 1533.5 MB)
[TDOC]   [LSTM] 시작  (메모리: 1533.5 MB)
[메모리] forecast_lstm 실행 전: 1533.53 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1533.36 MB (변화: -0.17 MB)
[TDOC]   [LSTM] 완료  첫값=6.86e+08 (메모리: 1533.4 MB)
[TDOC]   [Theta] 시작  (메모리: 1533.4 MB)
[메모리] forecast_theta 실행 전: 1533.36 MB
[메모리] forecast_theta 실행 후: 1533.36 MB (변화: +0.00 MB)
[TDOC]   [Theta] 완료  첫값=6.59e+08 (메모리: 1533.4 MB)
[TDOC]   [DB] 88행 저장 완료
[PROGRESS] [  46/500] (  9.2%)  >>  TMQ
[TMQ]   40분기 | 2016-05-31 ~ 2026-02-28
[TMQ]   [SARIMA] 시작  (메모리: 1533.4 MB)
[메모리] forecast_sarima 실행 전: 1533.36 MB
[메모리] find_best_sarima_params 실행 전: 1533.36 MB
[메모리] find_best_sarima_params 실행 후: 1533.36 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1533.36 MB (변화: +0.00 MB)
[TMQ]   [SARIMA] 완료  첫값=3.99e-02 (메모리: 1533.4 MB)
[TMQ]   [ETS] 시작  (메모리: 1533.4 MB)
[메모리] forecast_ets 실행 전: 1533.36 MB
[메모리] forecast_ets 실행 후: 1533.37 MB (변화: +0.01 MB)
[TMQ]   [ETS] 완료  첫값=-4.48e+05 (메모리: 1533.4 MB)
[TMQ]   [Prophet] 시작  (메모리: 1533.4 MB)

10:40:22 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1533.37 MB

10:40:22 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1533.40 MB (변화: +0.03 MB)
[TMQ]   [Prophet] 완료  첫값=-6.06e+05 (메모리: 1533.4 MB)
[TMQ]   [LSTM] 시작  (메모리: 1533.4 MB)
[메모리] forecast_lstm 실행 전: 1533.40 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1534.34 MB (변화: +0.95 MB)
[TMQ]   [LSTM] 완료  첫값=-1.73e+03 (메모리: 1534.3 MB)
[TMQ]   [Theta] 시작  (메모리: 1534.3 MB)
[메모리] forecast_theta 실행 전: 1534.34 MB
[메모리] forecast_theta 실행 후: 1534.34 MB (변화: +0.00 MB)
[TMQ]   [Theta] 완료  첫값=-1.12e+06 (메모리: 1534.3 MB)
[TMQ]   [DB] 88행 저장 완료
[PROGRESS] [  47/500] (  9.4%)  >>  HCCI
[HCCI]   40분기 | 2013-09-07 ~ 2023-06-30
[HCCI]   [SARIMA] 시작  (메모리: 1534.3 MB)
[메모리] forecast_sarima 실행 전: 1534.34 MB
[메모리] find_best_sarima_params 실행 전: 1534.34 MB
[메모리] find_best_sarima_params 실행 후: 1534.50 MB (변화: +0.16 MB)
[메모리] forecast_sarima 실행 후: 1534.50 MB (변화: +0.16 MB)
[HCCI]   [SARIMA] 완료  첫값=1.85e+08 (메모리: 1534.5 MB)
[HCCI]   [ETS] 시작  (메모리: 1534.5 MB)
[메모리] forecast_ets 실행 전: 1534.50 MB
[메모리] forecast_ets 실행 후: 1534.52 MB (변화: +0.01 MB)
[HCCI]   [ETS] 완료  첫값=2.18e+08 (메모리: 1534.5 MB)
[HCCI]   [Prophet] 시작  (메모리: 1534.5 MB)

10:40:38 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1534.52 MB

10:40:38 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1534.54 MB (변화: +0.02 MB)
[HCCI]   [Prophet] 완료  첫값=1.62e+08 (메모리: 1534.5 MB)
[HCCI]   [LSTM] 시작  (메모리: 1534.5 MB)
[메모리] forecast_lstm 실행 전: 1534.54 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1534.98 MB (변화: +0.44 MB)
[HCCI]   [LSTM] 완료  첫값=1.74e+08 (메모리: 1535.0 MB)
[HCCI]   [Theta] 시작  (메모리: 1535.0 MB)
[메모리] forecast_theta 실행 전: 1534.98 MB
[메모리] forecast_theta 실행 후: 1534.98 MB (변화: +0.00 MB)
[HCCI]   [Theta] 완료  첫값=1.96e+08 (메모리: 1535.0 MB)
[HCCI]   [DB] 88행 저장 완료
[PROGRESS] [  48/500] (  9.6%)  >>  ASTE
[ASTE]   40분기 | 2016-03-31 ~ 2025-12-31
[ASTE]   [SARIMA] 시작  (메모리: 1535.0 MB)
[메모리] forecast_sarima 실행 전: 1534.98 MB
[메모리] find_best_sarima_params 실행 전: 1534.98 MB
[메모리] find_best_sarima_params 실행 후: 1534.96 MB (변화: -0.02 MB)
[메모리] forecast_sarima 실행 후: 1534.96 MB (변화: -0.02 MB)
[ASTE]   [SARIMA] 완료  첫값=3.79e+08 (메모리: 1535.0 MB)
[ASTE]   [ETS] 시작  (메모리: 1535.0 MB)
[메모리] forecast_ets 실행 전: 1534.96 MB
[메모리] forecast_ets 실행 후: 1534.98 MB (변화: +0.01 MB)
[ASTE]   [ETS] 완료  첫값=3.56e+08 (메모리: 1535.0 MB)
[ASTE]   [Prophet] 시작  (메모리: 1535.0 MB)

10:40:54 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1534.98 MB

10:40:54 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1535.01 MB (변화: +0.03 MB)
[ASTE]   [Prophet] 완료  첫값=3.40e+08 (메모리: 1535.0 MB)
[ASTE]   [LSTM] 시작  (메모리: 1535.0 MB)
[메모리] forecast_lstm 실행 전: 1535.01 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1535.05 MB (변화: +0.04 MB)
[ASTE]   [LSTM] 완료  첫값=3.26e+08 (메모리: 1535.0 MB)
[ASTE]   [Theta] 시작  (메모리: 1535.0 MB)
[메모리] forecast_theta 실행 전: 1535.05 MB
[메모리] forecast_theta 실행 후: 1535.05 MB (변화: +0.00 MB)
[ASTE]   [Theta] 완료  첫값=3.99e+08 (메모리: 1535.0 MB)
[ASTE]   [DB] 88행 저장 완료
[PROGRESS] [  49/500] (  9.8%)  >>  HLX
[HLX]   40분기 | 2016-03-31 ~ 2025-12-31
[HLX]   [SARIMA] 시작  (메모리: 1535.1 MB)
[메모리] forecast_sarima 실행 전: 1535.05 MB
[메모리] find_best_sarima_params 실행 전: 1535.05 MB
[메모리] find_best_sarima_params 실행 후: 1535.05 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1535.05 MB (변화: +0.00 MB)
[HLX]   [SARIMA] 완료  첫값=2.79e+08 (메모리: 1535.1 MB)
[HLX]   [ETS] 시작  (메모리: 1535.1 MB)
[메모리] forecast_ets 실행 전: 1535.05 MB
[메모리] forecast_ets 실행 후: 1535.06 MB (변화: +0.01 MB)
[HLX]   [ETS] 완료  첫값=3.08e+08 (메모리: 1535.1 MB)
[HLX]   [Prophet] 시작  (메모리: 1535.1 MB)

10:41:09 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1535.06 MB

10:41:09 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1535.08 MB (변화: +0.02 MB)
[HLX]   [Prophet] 완료  첫값=3.43e+08 (메모리: 1535.1 MB)
[HLX]   [LSTM] 시작  (메모리: 1535.1 MB)
[메모리] forecast_lstm 실행 전: 1535.08 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1536.36 MB (변화: +1.28 MB)
[HLX]   [LSTM] 완료  첫값=3.98e+08 (메모리: 1536.4 MB)
[HLX]   [Theta] 시작  (메모리: 1536.4 MB)
[메모리] forecast_theta 실행 전: 1536.36 MB
[메모리] forecast_theta 실행 후: 1536.36 MB (변화: +0.00 MB)
[HLX]   [Theta] 완료  첫값=3.04e+08 (메모리: 1536.4 MB)
[HLX]   [DB] 88행 저장 완료
[PROGRESS] [  50/500] ( 10.0%)  >>  UAMY
[UAMY]   40분기 | 2016-03-31 ~ 2025-12-31
[UAMY]   [SARIMA] 시작  (메모리: 1536.4 MB)
[메모리] forecast_sarima 실행 전: 1536.36 MB
[메모리] find_best_sarima_params 실행 전: 1536.36 MB
[메모리] find_best_sarima_params 실행 후: 1536.36 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1536.36 MB (변화: +0.00 MB)
[UAMY]   [SARIMA] 완료  첫값=1.31e+07 (메모리: 1536.4 MB)
[UAMY]   [ETS] 시작  (메모리: 1536.4 MB)
[메모리] forecast_ets 실행 전: 1536.36 MB
[메모리] forecast_ets 실행 후: 1536.36 MB (변화: +0.00 MB)
[UAMY]   [ETS] 완료  첫값=1.74e+07 (메모리: 1536.4 MB)
[UAMY]   [Prophet] 시작  (메모리: 1536.4 MB)

10:41:22 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1536.36 MB

10:41:22 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1536.39 MB (변화: +0.03 MB)
[UAMY]   [Prophet] 완료  첫값=5.46e+06 (메모리: 1536.4 MB)
[UAMY]   [LSTM] 시작  (메모리: 1536.4 MB)
[메모리] forecast_lstm 실행 전: 1536.39 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1537.94 MB (변화: +1.55 MB)
[UAMY]   [LSTM] 완료  첫값=1.76e+07 (메모리: 1537.9 MB)
[UAMY]   [Theta] 시작  (메모리: 1537.9 MB)
[메모리] forecast_theta 실행 전: 1537.94 MB
[메모리] forecast_theta 실행 후: 1537.94 MB (변화: +0.00 MB)
[UAMY]   [Theta] 완료  첫값=1.26e+07 (메모리: 1537.9 MB)
[UAMY]   [DB] 88행 저장 완료
[PROGRESS] [  51/500] ( 10.2%)  >>  REX
[REX]   40분기 | 2016-04-30 ~ 2026-01-31
[REX]   [SARIMA] 시작  (메모리: 1537.9 MB)
[메모리] forecast_sarima 실행 전: 1537.94 MB
[메모리] find_best_sarima_params 실행 전: 1537.94 MB
[메모리] find_best_sarima_params 실행 후: 1537.94 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1537.94 MB (변화: +0.00 MB)
[REX]   [SARIMA] 완료  첫값=1.62e+08 (메모리: 1537.9 MB)
[REX]   [ETS] 시작  (메모리: 1537.9 MB)
[메모리] forecast_ets 실행 전: 1537.94 MB
[메모리] forecast_ets 실행 후: 1537.95 MB (변화: +0.00 MB)
[REX]   [ETS] 완료  첫값=1.57e+08 (메모리: 1537.9 MB)
[REX]   [Prophet] 시작  (메모리: 1537.9 MB)

10:41:40 - cmdstanpy - INFO - Chain [1] start processing
10:41:40 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1537.95 MB
[메모리] forecast_prophet 실행 후: 1537.99 MB (변화: +0.04 MB)
[REX]   [Prophet] 완료  첫값=2.00e+08 (메모리: 1538.0 MB)
[REX]   [LSTM] 시작  (메모리: 1538.0 MB)
[메모리] forecast_lstm 실행 전: 1537.99 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1538.93 MB (변화: +0.94 MB)
[REX]   [LSTM] 완료  첫값=1.63e+08 (메모리: 1538.9 MB)
[REX]   [Theta] 시작  (메모리: 1538.9 MB)
[메모리] forecast_theta 실행 전: 1538.93 MB
[메모리] forecast_theta 실행 후: 1538.93 MB (변화: +0.00 MB)
[REX]   [Theta] 완료  첫값=1.57e+08 (메모리: 1538.9 MB)
[REX]   [DB] 88행 저장 완료
[PROGRESS] [  52/500] ( 10.4%)  >>  SFL
[SFL]   40분기 | 2016-03-31 ~ 2025-12-31
[SFL]   [SARIMA] 시작  (메모리: 1538.9 MB)
[메모리] forecast_sarima 실행 전: 1538.93 MB
[메모리] find_best_sarima_params 실행 전: 1538.93 MB
[메모리] find_best_sarima_params 실행 후: 1538.93 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1538.93 MB (변화: +0.00 MB)
[SFL]   [SARIMA] 완료  첫값=1.78e+08 (메모리: 1538.9 MB)
[SFL]   [ETS] 시작  (메모리: 1538.9 MB)
[메모리] forecast_ets 실행 전: 1538.93 MB
[메모리] forecast_ets 실행 후: 1538.93 MB (변화: +0.00 MB)
[SFL]   [ETS] 완료  첫값=1.74e+08 (메모리: 1538.9 MB)
[SFL]   [Prophet] 시작  (메모리: 1538.9 MB)

10:41:56 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1538.93 MB

10:41:56 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1538.95 MB (변화: +0.02 MB)
[SFL]   [Prophet] 완료  첫값=2.11e+08 (메모리: 1539.0 MB)
[SFL]   [LSTM] 시작  (메모리: 1539.0 MB)
[메모리] forecast_lstm 실행 전: 1538.95 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1539.65 MB (변화: +0.70 MB)
[SFL]   [LSTM] 완료  첫값=2.16e+08 (메모리: 1539.7 MB)
[SFL]   [Theta] 시작  (메모리: 1539.7 MB)
[메모리] forecast_theta 실행 전: 1539.65 MB
[메모리] forecast_theta 실행 후: 1539.65 MB (변화: +0.00 MB)
[SFL]   [Theta] 완료  첫값=1.72e+08 (메모리: 1539.7 MB)
[SFL]   [DB] 88행 저장 완료
[PROGRESS] [  53/500] ( 10.6%)  >>  DLX
[DLX]   40분기 | 2016-03-31 ~ 2025-12-31
[DLX]   [SARIMA] 시작  (메모리: 1539.7 MB)
[메모리] forecast_sarima 실행 전: 1539.65 MB
[메모리] find_best_sarima_params 실행 전: 1539.65 MB
[메모리] find_best_sarima_params 실행 후: 1539.65 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1539.65 MB (변화: +0.00 MB)
[DLX]   [SARIMA] 완료  첫값=5.37e+08 (메모리: 1539.7 MB)
[DLX]   [ETS] 시작  (메모리: 1539.7 MB)
[메모리] forecast_ets 실행 전: 1539.65 MB
[메모리] forecast_ets 실행 후: 1539.66 MB (변화: +0.00 MB)
[DLX]   [ETS] 완료  첫값=5.25e+08 (메모리: 1539.7 MB)
[DLX]   [Prophet] 시작  (메모리: 1539.7 MB)

10:42:16 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1539.66 MB

10:42:16 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1539.69 MB (변화: +0.04 MB)
[DLX]   [Prophet] 완료  첫값=5.52e+08 (메모리: 1539.7 MB)
[DLX]   [LSTM] 시작  (메모리: 1539.7 MB)
[메모리] forecast_lstm 실행 전: 1539.69 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1540.16 MB (변화: +0.47 MB)
[DLX]   [LSTM] 완료  첫값=5.14e+08 (메모리: 1540.2 MB)
[DLX]   [Theta] 시작  (메모리: 1540.2 MB)
[메모리] forecast_theta 실행 전: 1540.16 MB
[메모리] forecast_theta 실행 후: 1540.16 MB (변화: +0.00 MB)
[DLX]   [Theta] 완료  첫값=5.36e+08 (메모리: 1540.2 MB)
[DLX]   [DB] 88행 저장 완료
[PROGRESS] [  54/500] ( 10.8%)  >>  RDWR
[RDWR]   40분기 | 2016-03-31 ~ 2025-12-31
[RDWR]   [SARIMA] 시작  (메모리: 1540.2 MB)
[메모리] forecast_sarima 실행 전: 1540.16 MB
[메모리] find_best_sarima_params 실행 전: 1540.16 MB
[메모리] find_best_sarima_params 실행 후: 1540.16 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1540.16 MB (변화: +0.00 MB)
[RDWR]   [SARIMA] 완료  첫값=7.86e+07 (메모리: 1540.2 MB)
[RDWR]   [ETS] 시작  (메모리: 1540.2 MB)
[메모리] forecast_ets 실행 전: 1540.16 MB
[메모리] forecast_ets 실행 후: 1540.17 MB (변화: +0.00 MB)
[RDWR]   [ETS] 완료  첫값=7.65e+07 (메모리: 1540.2 MB)
[RDWR]   [Prophet] 시작  (메모리: 1540.2 MB)

10:42:38 - cmdstanpy - INFO - Chain [1] start processing
10:42:38 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1540.17 MB
[메모리] forecast_prophet 실행 후: 1540.19 MB (변화: +0.02 MB)
[RDWR]   [Prophet] 완료  첫값=7.49e+07 (메모리: 1540.2 MB)
[RDWR]   [LSTM] 시작  (메모리: 1540.2 MB)
[메모리] forecast_lstm 실행 전: 1540.19 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1538.62 MB (변화: -1.56 MB)
[RDWR]   [LSTM] 완료  첫값=7.57e+07 (메모리: 1538.6 MB)
[RDWR]   [Theta] 시작  (메모리: 1538.6 MB)
[메모리] forecast_theta 실행 전: 1538.62 MB
[메모리] forecast_theta 실행 후: 1538.62 MB (변화: +0.00 MB)
[RDWR]   [Theta] 완료  첫값=7.59e+07 (메모리: 1538.6 MB)
[RDWR]   [DB] 88행 저장 완료
[PROGRESS] [  55/500] ( 11.0%)  >>  AAT
[AAT]   40분기 | 2016-03-31 ~ 2025-12-31
[AAT]   [SARIMA] 시작  (메모리: 1538.6 MB)
[메모리] forecast_sarima 실행 전: 1538.62 MB
[메모리] find_best_sarima_params 실행 전: 1538.62 MB
[메모리] find_best_sarima_params 실행 후: 1538.62 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1538.62 MB (변화: +0.00 MB)
[AAT]   [SARIMA] 완료  첫값=1.11e+08 (메모리: 1538.6 MB)
[AAT]   [ETS] 시작  (메모리: 1538.6 MB)
[메모리] forecast_ets 실행 전: 1538.62 MB
[메모리] forecast_ets 실행 후: 1538.63 MB (변화: +0.01 MB)
[AAT]   [ETS] 완료  첫값=1.09e+08 (메모리: 1538.6 MB)
[AAT]   [Prophet] 시작  (메모리: 1538.6 MB)

10:42:53 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1538.63 MB

10:42:54 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1538.67 MB (변화: +0.04 MB)
[AAT]   [Prophet] 완료  첫값=1.18e+08 (메모리: 1538.7 MB)
[AAT]   [LSTM] 시작  (메모리: 1538.7 MB)
[메모리] forecast_lstm 실행 전: 1538.67 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1539.64 MB (변화: +0.97 MB)
[AAT]   [LSTM] 완료  첫값=1.15e+08 (메모리: 1539.6 MB)
[AAT]   [Theta] 시작  (메모리: 1539.6 MB)
[메모리] forecast_theta 실행 전: 1539.64 MB
[메모리] forecast_theta 실행 후: 1539.64 MB (변화: +0.00 MB)
[AAT]   [Theta] 완료  첫값=1.09e+08 (메모리: 1539.6 MB)
[AAT]   [DB] 88행 저장 완료
[PROGRESS] [  56/500] ( 11.2%)  >>  CRTO
[CRTO]   40분기 | 2016-03-31 ~ 2025-12-31
[CRTO]   [SARIMA] 시작  (메모리: 1539.6 MB)
[메모리] forecast_sarima 실행 전: 1539.64 MB
[메모리] find_best_sarima_params 실행 전: 1539.64 MB
[메모리] find_best_sarima_params 실행 후: 1539.64 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1539.64 MB (변화: +0.00 MB)
[CRTO]   [SARIMA] 완료  첫값=4.36e+08 (메모리: 1539.6 MB)
[CRTO]   [ETS] 시작  (메모리: 1539.6 MB)
[메모리] forecast_ets 실행 전: 1539.64 MB
[메모리] forecast_ets 실행 후: 1539.65 MB (변화: +0.01 MB)
[CRTO]   [ETS] 완료  첫값=4.42e+08 (메모리: 1539.7 MB)
[CRTO]   [Prophet] 시작  (메모리: 1539.7 MB)

10:43:10 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1539.65 MB

10:43:10 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1539.68 MB (변화: +0.02 MB)
[CRTO]   [Prophet] 완료  첫값=5.00e+08 (메모리: 1539.7 MB)
[CRTO]   [LSTM] 시작  (메모리: 1539.7 MB)
[메모리] forecast_lstm 실행 전: 1539.68 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1539.70 MB (변화: +0.02 MB)
[CRTO]   [LSTM] 완료  첫값=5.01e+08 (메모리: 1539.7 MB)
[CRTO]   [Theta] 시작  (메모리: 1539.7 MB)
[메모리] forecast_theta 실행 전: 1539.70 MB
[메모리] forecast_theta 실행 후: 1539.70 MB (변화: +0.00 MB)
[CRTO]   [Theta] 완료  첫값=4.40e+08 (메모리: 1539.7 MB)
[CRTO]   [DB] 88행 저장 완료
[PROGRESS] [  57/500] ( 11.4%)  >>  VLRS
[VLRS]   40분기 | 2016-03-31 ~ 2025-12-31
[VLRS]   [SARIMA] 시작  (메모리: 1539.7 MB)
[메모리] forecast_sarima 실행 전: 1539.70 MB
[메모리] find_best_sarima_params 실행 전: 1539.70 MB
[메모리] find_best_sarima_params 실행 후: 1539.70 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1539.70 MB (변화: +0.00 MB)
[VLRS]   [SARIMA] 완료  첫값=9.34e+08 (메모리: 1539.7 MB)
[VLRS]   [ETS] 시작  (메모리: 1539.7 MB)
[메모리] forecast_ets 실행 전: 1539.70 MB
[메모리] forecast_ets 실행 후: 1539.70 MB (변화: +0.00 MB)
[VLRS]   [ETS] 완료  첫값=7.64e+08 (메모리: 1539.7 MB)
[VLRS]   [Prophet] 시작  (메모리: 1539.7 MB)

10:43:23 - cmdstanpy - INFO - Chain [1] start processing
10:43:23 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1539.70 MB
[메모리] forecast_prophet 실행 후: 1539.74 MB (변화: +0.04 MB)
[VLRS]   [Prophet] 완료  첫값=8.69e+08 (메모리: 1539.7 MB)
[VLRS]   [LSTM] 시작  (메모리: 1539.7 MB)
[메모리] forecast_lstm 실행 전: 1539.74 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1539.74 MB (변화: +0.00 MB)
[VLRS]   [LSTM] 완료  첫값=7.80e+08 (메모리: 1539.7 MB)
[VLRS]   [Theta] 시작  (메모리: 1539.7 MB)
[메모리] forecast_theta 실행 전: 1539.74 MB
[메모리] forecast_theta 실행 후: 1539.74 MB (변화: +0.00 MB)
[VLRS]   [Theta] 완료  첫값=7.50e+08 (메모리: 1539.7 MB)
[VLRS]   [DB] 88행 저장 완료
[PROGRESS] [  58/500] ( 11.6%)  >>  SIFY
[SIFY]   40분기 | 2016-03-31 ~ 2025-12-31
[SIFY]   [SARIMA] 시작  (메모리: 1539.7 MB)
[메모리] forecast_sarima 실행 전: 1539.74 MB
[메모리] find_best_sarima_params 실행 전: 1539.74 MB
[메모리] find_best_sarima_params 실행 후: 1539.74 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1539.74 MB (변화: +0.00 MB)
[SIFY]   [SARIMA] 완료  첫값=1.14e+10 (메모리: 1539.7 MB)
[SIFY]   [ETS] 시작  (메모리: 1539.7 MB)
[메모리] forecast_ets 실행 전: 1539.74 MB
[메모리] forecast_ets 실행 후: 1539.74 MB (변화: +0.00 MB)
[SIFY]   [ETS] 완료  첫값=1.15e+10 (메모리: 1539.7 MB)
[SIFY]   [Prophet] 시작  (메모리: 1539.7 MB)

10:43:39 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1539.74 MB

10:43:39 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1539.78 MB (변화: +0.04 MB)
[SIFY]   [Prophet] 완료  첫값=1.10e+10 (메모리: 1539.8 MB)
[SIFY]   [LSTM] 시작  (메모리: 1539.8 MB)
[메모리] forecast_lstm 실행 전: 1539.78 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1540.05 MB (변화: +0.27 MB)
[SIFY]   [LSTM] 완료  첫값=1.02e+10 (메모리: 1540.0 MB)
[SIFY]   [Theta] 시작  (메모리: 1540.0 MB)
[메모리] forecast_theta 실행 전: 1540.05 MB
[메모리] forecast_theta 실행 후: 1540.05 MB (변화: +0.00 MB)
[SIFY]   [Theta] 완료  첫값=1.18e+10 (메모리: 1540.0 MB)
[SIFY]   [DB] 88행 저장 완료
[PROGRESS] [  59/500] ( 11.8%)  >>  CAPR
[CAPR]   40분기 | 2016-03-31 ~ 2025-12-31
[CAPR]   [SARIMA] 시작  (메모리: 1540.0 MB)
[메모리] forecast_sarima 실행 전: 1540.05 MB
[메모리] find_best_sarima_params 실행 전: 1540.05 MB
[메모리] find_best_sarima_params 실행 후: 1540.05 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1540.05 MB (변화: +0.00 MB)
[CAPR]   [SARIMA] 완료  첫값=-8.80e+05 (메모리: 1540.0 MB)
[CAPR]   [ETS] 시작  (메모리: 1540.0 MB)
[메모리] forecast_ets 실행 전: 1540.05 MB
[메모리] forecast_ets 실행 후: 1540.05 MB (변화: +0.00 MB)
[CAPR]   [ETS] 완료  첫값=-4.19e+06 (메모리: 1540.0 MB)
[CAPR]   [Prophet] 시작  (메모리: 1540.0 MB)

10:43:53 - cmdstanpy - INFO - Chain [1] start processing
10:43:53 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1540.05 MB
[메모리] forecast_prophet 실행 후: 1540.07 MB (변화: +0.03 MB)
[CAPR]   [Prophet] 완료  첫값=3.35e+06 (메모리: 1540.1 MB)
[CAPR]   [LSTM] 시작  (메모리: 1540.1 MB)
[메모리] forecast_lstm 실행 전: 1540.07 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1540.95 MB (변화: +0.87 MB)
[CAPR]   [LSTM] 완료  첫값=1.71e+06 (메모리: 1540.9 MB)
[CAPR]   [Theta] 시작  (메모리: 1540.9 MB)
[메모리] forecast_theta 실행 전: 1540.95 MB
[메모리] forecast_theta 실행 후: 1540.95 MB (변화: +0.00 MB)
[CAPR]   [Theta] 완료  첫값=-5.45e+05 (메모리: 1540.9 MB)
[CAPR]   [DB] 88행 저장 완료
[PROGRESS] [  60/500] ( 12.0%)  >>  UAN
[UAN]   40분기 | 2016-03-31 ~ 2025-12-31
[UAN]   [SARIMA] 시작  (메모리: 1540.9 MB)
[메모리] forecast_sarima 실행 전: 1540.95 MB
[메모리] find_best_sarima_params 실행 전: 1540.95 MB
[메모리] find_best_sarima_params 실행 후: 1540.95 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1540.95 MB (변화: +0.00 MB)
[UAN]   [SARIMA] 완료  첫값=1.29e+08 (메모리: 1540.9 MB)
[UAN]   [ETS] 시작  (메모리: 1540.9 MB)
[메모리] forecast_ets 실행 전: 1540.95 MB
[메모리] forecast_ets 실행 후: 1540.95 MB (변화: +0.00 MB)
[UAN]   [ETS] 완료  첫값=1.30e+08 (메모리: 1540.9 MB)
[UAN]   [Prophet] 시작  (메모리: 1540.9 MB)

10:44:11 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1540.95 MB

10:44:11 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1540.97 MB (변화: +0.02 MB)
[UAN]   [Prophet] 완료  첫값=1.76e+08 (메모리: 1541.0 MB)
[UAN]   [LSTM] 시작  (메모리: 1541.0 MB)
[메모리] forecast_lstm 실행 전: 1540.97 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1540.57 MB (변화: -0.39 MB)
[UAN]   [LSTM] 완료  첫값=1.43e+08 (메모리: 1540.6 MB)
[UAN]   [Theta] 시작  (메모리: 1540.6 MB)
[메모리] forecast_theta 실행 전: 1540.57 MB
[메모리] forecast_theta 실행 후: 1540.57 MB (변화: +0.00 MB)
[UAN]   [Theta] 완료  첫값=1.30e+08 (메모리: 1540.6 MB)
[UAN]   [DB] 88행 저장 완료
[PROGRESS] [  61/500] ( 12.2%)  >>  ALNT
[ALNT]   40분기 | 2016-03-31 ~ 2025-12-31
[ALNT]   [SARIMA] 시작  (메모리: 1540.6 MB)
[메모리] forecast_sarima 실행 전: 1540.57 MB
[메모리] find_best_sarima_params 실행 전: 1540.57 MB
[메모리] find_best_sarima_params 실행 후: 1540.57 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1540.57 MB (변화: +0.00 MB)
[ALNT]   [SARIMA] 완료  첫값=1.52e+08 (메모리: 1540.6 MB)
[ALNT]   [ETS] 시작  (메모리: 1540.6 MB)
[메모리] forecast_ets 실행 전: 1540.57 MB
[메모리] forecast_ets 실행 후: 1540.58 MB (변화: +0.01 MB)
[ALNT]   [ETS] 완료  첫값=1.61e+08 (메모리: 1540.6 MB)
[ALNT]   [Prophet] 시작  (메모리: 1540.6 MB)

10:44:28 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1540.58 MB

10:44:28 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1540.59 MB (변화: +0.01 MB)
[ALNT]   [Prophet] 완료  첫값=1.53e+08 (메모리: 1540.6 MB)
[ALNT]   [LSTM] 시작  (메모리: 1540.6 MB)
[메모리] forecast_lstm 실행 전: 1540.59 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1541.56 MB (변화: +0.97 MB)
[ALNT]   [LSTM] 완료  첫값=1.45e+08 (메모리: 1541.6 MB)
[ALNT]   [Theta] 시작  (메모리: 1541.6 MB)
[메모리] forecast_theta 실행 전: 1541.56 MB
[메모리] forecast_theta 실행 후: 1541.56 MB (변화: +0.00 MB)
[ALNT]   [Theta] 완료  첫값=1.60e+08 (메모리: 1541.6 MB)
[ALNT]   [DB] 88행 저장 완료
[PROGRESS] [  62/500] ( 12.4%)  >>  CDNA
[CDNA]   40분기 | 2016-03-31 ~ 2025-12-31
[CDNA]   [SARIMA] 시작  (메모리: 1541.6 MB)
[메모리] forecast_sarima 실행 전: 1541.56 MB
[메모리] find_best_sarima_params 실행 전: 1541.56 MB
[메모리] find_best_sarima_params 실행 후: 1541.56 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1541.56 MB (변화: +0.00 MB)
[CDNA]   [SARIMA] 완료  첫값=1.16e+08 (메모리: 1541.6 MB)
[CDNA]   [ETS] 시작  (메모리: 1541.6 MB)
[메모리] forecast_ets 실행 전: 1541.56 MB
[메모리] forecast_ets 실행 후: 1541.57 MB (변화: +0.00 MB)
[CDNA]   [ETS] 완료  첫값=1.12e+08 (메모리: 1541.6 MB)
[CDNA]   [Prophet] 시작  (메모리: 1541.6 MB)

10:44:44 - cmdstanpy - INFO - Chain [1] start processing
10:44:44 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1541.57 MB
[메모리] forecast_prophet 실행 후: 1541.59 MB (변화: +0.03 MB)
[CDNA]   [Prophet] 완료  첫값=1.05e+08 (메모리: 1541.6 MB)
[CDNA]   [LSTM] 시작  (메모리: 1541.6 MB)
[메모리] forecast_lstm 실행 전: 1541.59 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1542.83 MB (변화: +1.23 MB)
[CDNA]   [LSTM] 완료  첫값=9.19e+07 (메모리: 1542.8 MB)
[CDNA]   [Theta] 시작  (메모리: 1542.8 MB)
[메모리] forecast_theta 실행 전: 1542.83 MB
[메모리] forecast_theta 실행 후: 1542.83 MB (변화: +0.00 MB)
[CDNA]   [Theta] 완료  첫값=1.12e+08 (메모리: 1542.8 MB)
[CDNA]   [DB] 88행 저장 완료
[PROGRESS] [  63/500] ( 12.6%)  >>  SP
[SP]   40분기 | 2014-06-30 ~ 2024-03-31
[SP]   [SARIMA] 시작  (메모리: 1542.8 MB)
[메모리] forecast_sarima 실행 전: 1542.83 MB
[메모리] find_best_sarima_params 실행 전: 1542.83 MB
[메모리] find_best_sarima_params 실행 후: 1542.83 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1542.83 MB (변화: +0.00 MB)
[SP]   [SARIMA] 완료  첫값=4.53e+08 (메모리: 1542.8 MB)
[SP]   [ETS] 시작  (메모리: 1542.8 MB)
[메모리] forecast_ets 실행 전: 1542.83 MB
[메모리] forecast_ets 실행 후: 1542.83 MB (변화: +0.00 MB)
[SP]   [ETS] 완료  첫값=4.30e+08 (메모리: 1542.8 MB)
[SP]   [Prophet] 시작  (메모리: 1542.8 MB)

10:45:03 - cmdstanpy - INFO - Chain [1] start processing
10:45:03 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1542.83 MB
[메모리] forecast_prophet 실행 후: 1542.86 MB (변화: +0.03 MB)
[SP]   [Prophet] 완료  첫값=3.73e+08 (메모리: 1542.9 MB)
[SP]   [LSTM] 시작  (메모리: 1542.9 MB)
[메모리] forecast_lstm 실행 전: 1542.86 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1542.71 MB (변화: -0.16 MB)
[SP]   [LSTM] 완료  첫값=3.64e+08 (메모리: 1542.7 MB)
[SP]   [Theta] 시작  (메모리: 1542.7 MB)
[메모리] forecast_theta 실행 전: 1542.71 MB
[메모리] forecast_theta 실행 후: 1542.71 MB (변화: +0.00 MB)
[SP]   [Theta] 완료  첫값=4.51e+08 (메모리: 1542.7 MB)
[SP]   [DB] 88행 저장 완료
[PROGRESS] [  64/500] ( 12.8%)  >>  DEA
[DEA]   40분기 | 2016-03-31 ~ 2025-12-31
[DEA]   [SARIMA] 시작  (메모리: 1542.7 MB)
[메모리] forecast_sarima 실행 전: 1542.71 MB
[메모리] find_best_sarima_params 실행 전: 1542.71 MB
[메모리] find_best_sarima_params 실행 후: 1542.71 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1542.71 MB (변화: +0.00 MB)
[DEA]   [SARIMA] 완료  첫값=9.00e+07 (메모리: 1542.7 MB)
[DEA]   [ETS] 시작  (메모리: 1542.7 MB)
[메모리] forecast_ets 실행 전: 1542.71 MB
[메모리] forecast_ets 실행 후: 1542.71 MB (변화: +0.00 MB)
[DEA]   [ETS] 완료  첫값=8.56e+07 (메모리: 1542.7 MB)
[DEA]   [Prophet] 시작  (메모리: 1542.7 MB)

10:45:20 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1542.71 MB

10:45:20 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1542.73 MB (변화: +0.02 MB)
[DEA]   [Prophet] 완료  첫값=8.46e+07 (메모리: 1542.7 MB)
[DEA]   [LSTM] 시작  (메모리: 1542.7 MB)
[메모리] forecast_lstm 실행 전: 1542.73 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1543.05 MB (변화: +0.32 MB)
[DEA]   [LSTM] 완료  첫값=8.05e+07 (메모리: 1543.1 MB)
[DEA]   [Theta] 시작  (메모리: 1543.1 MB)
[메모리] forecast_theta 실행 전: 1543.05 MB
[메모리] forecast_theta 실행 후: 1543.05 MB (변화: +0.00 MB)
[DEA]   [Theta] 완료  첫값=8.54e+07 (메모리: 1543.1 MB)
[DEA]   [DB] 88행 저장 완료
[PROGRESS] [  65/500] ( 13.0%)  >>  CSR
[CSR]   40분기 | 2016-04-30 ~ 2025-12-31
[CSR]   [SARIMA] 시작  (메모리: 1543.1 MB)
[메모리] forecast_sarima 실행 전: 1543.05 MB
[메모리] find_best_sarima_params 실행 전: 1543.05 MB
[메모리] find_best_sarima_params 실행 후: 1543.05 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1543.05 MB (변화: +0.00 MB)
[CSR]   [SARIMA] 완료  첫값=1.51e+08 (메모리: 1543.1 MB)
[CSR]   [ETS] 시작  (메모리: 1543.1 MB)
[메모리] forecast_ets 실행 전: 1543.05 MB
[메모리] forecast_ets 실행 후: 1543.06 MB (변화: +0.00 MB)
[CSR]   [ETS] 완료  첫값=1.89e+08 (메모리: 1543.1 MB)
[CSR]   [Prophet] 시작  (메모리: 1543.1 MB)

10:45:35 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1543.06 MB

10:45:35 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1542.72 MB (변화: -0.34 MB)
[CSR]   [Prophet] 완료  첫값=7.58e+07 (메모리: 1542.7 MB)
[CSR]   [LSTM] 시작  (메모리: 1542.7 MB)
[메모리] forecast_lstm 실행 전: 1542.72 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1546.13 MB (변화: +3.41 MB)
[CSR]   [LSTM] 완료  첫값=8.70e+07 (메모리: 1546.1 MB)
[CSR]   [Theta] 시작  (메모리: 1546.1 MB)
[메모리] forecast_theta 실행 전: 1546.13 MB
[메모리] forecast_theta 실행 후: 1546.13 MB (변화: +0.00 MB)
[CSR]   [Theta] 완료  첫값=1.48e+08 (메모리: 1546.1 MB)
[CSR]   [DB] 88행 저장 완료
[PROGRESS] [  66/500] ( 13.2%)  >>  CIM
[CIM] [NEG-SKIP] [CIM] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2018, 12, 31), datetime.date(2020, 3, 31), datetime.date(2020, 6, 30), datetime.date(2022, 3, 31), datetime.date(2022, 6, 30), datetime.date(2022, 9, 30), datetime.date(2024, 12, 31)])
[PROGRESS] [  67/500] ( 13.4%)  >>  SBGI
[SBGI]   40분기 | 2016-03-31 ~ 2025-12-31
[SBGI]   [SARIMA] 시작  (메모리: 1546.1 MB)
[메모리] forecast_sarima 실행 전: 1546.13 MB
[메모리] find_best_sarima_params 실행 전: 1546.13 MB
[메모리] find_best_sarima_params 실행 후: 1546.13 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1546.13 MB (변화: +0.00 MB)
[SBGI]   [SARIMA] 완료  첫값=8.36e+08 (메모리: 1546.1 MB)
[SBGI]   [ETS] 시작  (메모리: 1546.1 MB)
[메모리] forecast_ets 실행 전: 1546.13 MB
[메모리] forecast_ets 실행 후: 1546.14 MB (변화: +0.01 MB)
[SBGI]   [ETS] 완료  첫값=7.34e+08 (메모리: 1546.1 MB)
[SBGI]   [Prophet] 시작  (메모리: 1546.1 MB)

10:45:53 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1546.14 MB

10:45:53 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1546.17 MB (변화: +0.03 MB)
[SBGI]   [Prophet] 완료  첫값=1.05e+09 (메모리: 1546.2 MB)
[SBGI]   [LSTM] 시작  (메모리: 1546.2 MB)
[메모리] forecast_lstm 실행 전: 1546.17 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1545.90 MB (변화: -0.27 MB)
[SBGI]   [LSTM] 완료  첫값=1.07e+09 (메모리: 1545.9 MB)
[SBGI]   [Theta] 시작  (메모리: 1545.9 MB)
[메모리] forecast_theta 실행 전: 1545.90 MB
[메모리] forecast_theta 실행 후: 1545.90 MB (변화: +0.00 MB)
[SBGI]   [Theta] 완료  첫값=7.34e+08 (메모리: 1545.9 MB)
[SBGI]   [DB] 88행 저장 완료
[PROGRESS] [  68/500] ( 13.6%)  >>  GILT
[GILT]   40분기 | 2016-03-31 ~ 2025-12-31
[GILT]   [SARIMA] 시작  (메모리: 1545.9 MB)
[메모리] forecast_sarima 실행 전: 1545.90 MB
[메모리] find_best_sarima_params 실행 전: 1545.90 MB
[메모리] find_best_sarima_params 실행 후: 1545.90 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1545.90 MB (변화: +0.00 MB)
[GILT]   [SARIMA] 완료  첫값=1.30e+08 (메모리: 1545.9 MB)
[GILT]   [ETS] 시작  (메모리: 1545.9 MB)
[메모리] forecast_ets 실행 전: 1545.90 MB
[메모리] forecast_ets 실행 후: 1545.91 MB (변화: +0.00 MB)
[GILT]   [ETS] 완료  첫값=1.19e+08 (메모리: 1545.9 MB)
[GILT]   [Prophet] 시작  (메모리: 1545.9 MB)

10:46:11 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1545.91 MB

10:46:11 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1545.94 MB (변화: +0.03 MB)
[GILT]   [Prophet] 완료  첫값=8.23e+07 (메모리: 1545.9 MB)
[GILT]   [LSTM] 시작  (메모리: 1545.9 MB)
[메모리] forecast_lstm 실행 전: 1545.94 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1546.91 MB (변화: +0.98 MB)
[GILT]   [LSTM] 완료  첫값=1.19e+08 (메모리: 1546.9 MB)
[GILT]   [Theta] 시작  (메모리: 1546.9 MB)
[메모리] forecast_theta 실행 전: 1546.91 MB
[메모리] forecast_theta 실행 후: 1546.91 MB (변화: +0.00 MB)
[GILT]   [Theta] 완료  첫값=1.36e+08 (메모리: 1546.9 MB)
[GILT]   [DB] 88행 저장 완료
[PROGRESS] [  69/500] ( 13.8%)  >>  DAKT
[DAKT]   40분기 | 2016-04-30 ~ 2026-01-31
[DAKT]   [SARIMA] 시작  (메모리: 1546.9 MB)
[메모리] forecast_sarima 실행 전: 1546.91 MB
[메모리] find_best_sarima_params 실행 전: 1546.91 MB
[메모리] find_best_sarima_params 실행 후: 1546.91 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1546.91 MB (변화: +0.00 MB)
[DAKT]   [SARIMA] 완료  첫값=2.01e+08 (메모리: 1546.9 MB)
[DAKT]   [ETS] 시작  (메모리: 1546.9 MB)
[메모리] forecast_ets 실행 전: 1546.91 MB
[메모리] forecast_ets 실행 후: 1546.92 MB (변화: +0.00 MB)
[DAKT]   [ETS] 완료  첫값=2.09e+08 (메모리: 1546.9 MB)
[DAKT]   [Prophet] 시작  (메모리: 1546.9 MB)

10:46:30 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1546.92 MB

10:46:31 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1546.95 MB (변화: +0.03 MB)
[DAKT]   [Prophet] 완료  첫값=1.99e+08 (메모리: 1546.9 MB)
[DAKT]   [LSTM] 시작  (메모리: 1546.9 MB)
[메모리] forecast_lstm 실행 전: 1546.95 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1546.88 MB (변화: -0.07 MB)
[DAKT]   [LSTM] 완료  첫값=1.99e+08 (메모리: 1546.9 MB)
[DAKT]   [Theta] 시작  (메모리: 1546.9 MB)
[메모리] forecast_theta 실행 전: 1546.88 MB
[메모리] forecast_theta 실행 후: 1546.88 MB (변화: +0.00 MB)
[DAKT]   [Theta] 완료  첫값=2.08e+08 (메모리: 1546.9 MB)
[DAKT]   [DB] 88행 저장 완료
[PROGRESS] [  70/500] ( 14.0%)  >>  CMP
[CMP] [NEG-SKIP] [CMP] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2021, 9, 30)])
[PROGRESS] [  71/500] ( 14.2%)  >>  HIBB
[HIBB]   40분기 | 2014-07-31 ~ 2024-05-04
[HIBB]   [SARIMA] 시작  (메모리: 1546.9 MB)
[메모리] forecast_sarima 실행 전: 1546.88 MB
[메모리] find_best_sarima_params 실행 전: 1546.88 MB
[메모리] find_best_sarima_params 실행 후: 1546.88 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1546.88 MB (변화: +0.00 MB)
[HIBB]   [SARIMA] 완료  첫값=4.71e+08 (메모리: 1546.9 MB)
[HIBB]   [ETS] 시작  (메모리: 1546.9 MB)
[메모리] forecast_ets 실행 전: 1546.88 MB
[메모리] forecast_ets 실행 후: 1546.89 MB (변화: +0.01 MB)
[HIBB]   [ETS] 완료  첫값=4.15e+08 (메모리: 1546.9 MB)
[HIBB]   [Prophet] 시작  (메모리: 1546.9 MB)

10:46:47 - cmdstanpy - INFO - Chain [1] start processing
10:46:47 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1546.89 MB
[메모리] forecast_prophet 실행 후: 1546.91 MB (변화: +0.02 MB)
[HIBB]   [Prophet] 완료  첫값=4.56e+08 (메모리: 1546.9 MB)
[HIBB]   [LSTM] 시작  (메모리: 1546.9 MB)
[메모리] forecast_lstm 실행 전: 1546.91 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1546.90 MB (변화: -0.01 MB)
[HIBB]   [LSTM] 완료  첫값=5.15e+08 (메모리: 1546.9 MB)
[HIBB]   [Theta] 시작  (메모리: 1546.9 MB)
[메모리] forecast_theta 실행 전: 1546.90 MB
[메모리] forecast_theta 실행 후: 1546.90 MB (변화: +0.00 MB)
[HIBB]   [Theta] 완료  첫값=3.97e+08 (메모리: 1546.9 MB)
[HIBB]   [DB] 88행 저장 완료
[PROGRESS] [  72/500] ( 14.4%)  >>  MMI
[MMI]   40분기 | 2016-03-31 ~ 2025-12-31
[MMI]   [SARIMA] 시작  (메모리: 1546.9 MB)
[메모리] forecast_sarima 실행 전: 1546.90 MB
[메모리] find_best_sarima_params 실행 전: 1546.90 MB
[메모리] find_best_sarima_params 실행 후: 1546.90 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1546.90 MB (변화: +0.00 MB)
[MMI]   [SARIMA] 완료  첫값=1.75e+08 (메모리: 1546.9 MB)
[MMI]   [ETS] 시작  (메모리: 1546.9 MB)
[메모리] forecast_ets 실행 전: 1546.90 MB
[메모리] forecast_ets 실행 후: 1546.91 MB (변화: +0.00 MB)
[MMI]   [ETS] 완료  첫값=1.75e+08 (메모리: 1546.9 MB)
[MMI]   [Prophet] 시작  (메모리: 1546.9 MB)

10:47:02 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1546.91 MB

10:47:02 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1546.93 MB (변화: +0.03 MB)
[MMI]   [Prophet] 완료  첫값=2.27e+08 (메모리: 1546.9 MB)
[MMI]   [LSTM] 시작  (메모리: 1546.9 MB)
[메모리] forecast_lstm 실행 전: 1546.93 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1547.16 MB (변화: +0.22 MB)
[MMI]   [LSTM] 완료  첫값=2.02e+08 (메모리: 1547.2 MB)
[MMI]   [Theta] 시작  (메모리: 1547.2 MB)
[메모리] forecast_theta 실행 전: 1547.16 MB
[메모리] forecast_theta 실행 후: 1547.16 MB (변화: +0.00 MB)
[MMI]   [Theta] 완료  첫값=2.26e+08 (메모리: 1547.2 MB)
[MMI]   [DB] 88행 저장 완료
[PROGRESS] [  73/500] ( 14.6%)  >>  NEGG
[NEGG]   40분기 | 2011-09-30 ~ 2025-06-30
[NEGG]   [SARIMA] 시작  (메모리: 1547.2 MB)
[메모리] forecast_sarima 실행 전: 1547.16 MB
[메모리] find_best_sarima_params 실행 전: 1547.16 MB
[메모리] find_best_sarima_params 실행 후: 1547.16 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1547.16 MB (변화: +0.00 MB)
[NEGG]   [SARIMA] 완료  첫값=3.24e+08 (메모리: 1547.2 MB)
[NEGG]   [ETS] 시작  (메모리: 1547.2 MB)
[메모리] forecast_ets 실행 전: 1547.16 MB
[메모리] forecast_ets 실행 후: 1547.16 MB (변화: +0.00 MB)
[NEGG]   [ETS] 완료  첫값=2.44e+08 (메모리: 1547.2 MB)
[NEGG]   [Prophet] 시작  (메모리: 1547.2 MB)

10:47:14 - cmdstanpy - INFO - Chain [1] start processing
10:47:14 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1547.16 MB
[메모리] forecast_prophet 실행 후: 1547.19 MB (변화: +0.03 MB)
[NEGG]   [Prophet] 완료  첫값=-9.66e+07 (메모리: 1547.2 MB)
[NEGG]   [LSTM] 시작  (메모리: 1547.2 MB)
[메모리] forecast_lstm 실행 전: 1547.19 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1548.29 MB (변화: +1.11 MB)
[NEGG]   [LSTM] 완료  첫값=4.53e+08 (메모리: 1548.3 MB)
[NEGG]   [Theta] 시작  (메모리: 1548.3 MB)
[메모리] forecast_theta 실행 전: 1548.29 MB
[메모리] forecast_theta 실행 후: 1548.29 MB (변화: +0.00 MB)
[NEGG]   [Theta] 완료  첫값=3.67e+08 (메모리: 1548.3 MB)
[NEGG]   [DB] 88행 저장 완료
[PROGRESS] [  74/500] ( 14.8%)  >>  TROX
[TROX]   40분기 | 2016-03-31 ~ 2025-12-31
[TROX]   [SARIMA] 시작  (메모리: 1548.3 MB)
[메모리] forecast_sarima 실행 전: 1548.29 MB
[메모리] find_best_sarima_params 실행 전: 1548.29 MB
[메모리] find_best_sarima_params 실행 후: 1548.29 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1548.29 MB (변화: +0.00 MB)
[TROX]   [SARIMA] 완료  첫값=7.30e+08 (메모리: 1548.3 MB)
[TROX]   [ETS] 시작  (메모리: 1548.3 MB)
[메모리] forecast_ets 실행 전: 1548.29 MB
[메모리] forecast_ets 실행 후: 1548.30 MB (변화: +0.00 MB)
[TROX]   [ETS] 완료  첫값=7.51e+08 (메모리: 1548.3 MB)
[TROX]   [Prophet] 시작  (메모리: 1548.3 MB)

10:47:32 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1548.30 MB

10:47:32 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1548.32 MB (변화: +0.02 MB)
[TROX]   [Prophet] 완료  첫값=8.53e+08 (메모리: 1548.3 MB)
[TROX]   [LSTM] 시작  (메모리: 1548.3 MB)
[메모리] forecast_lstm 실행 전: 1548.32 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1549.82 MB (변화: +1.50 MB)
[TROX]   [LSTM] 완료  첫값=7.42e+08 (메모리: 1549.8 MB)
[TROX]   [Theta] 시작  (메모리: 1549.8 MB)
[메모리] forecast_theta 실행 전: 1549.82 MB
[메모리] forecast_theta 실행 후: 1549.82 MB (변화: +0.00 MB)
[TROX]   [Theta] 완료  첫값=7.51e+08 (메모리: 1549.8 MB)
[TROX]   [DB] 88행 저장 완료
[PROGRESS] [  75/500] ( 15.0%)  >>  PDM
[PDM]   40분기 | 2016-03-31 ~ 2025-12-31
[PDM]   [SARIMA] 시작  (메모리: 1549.8 MB)
[메모리] forecast_sarima 실행 전: 1549.82 MB
[메모리] find_best_sarima_params 실행 전: 1549.82 MB
[메모리] find_best_sarima_params 실행 후: 1549.82 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1549.82 MB (변화: +0.00 MB)
[PDM]   [SARIMA] 완료  첫값=1.43e+08 (메모리: 1549.8 MB)
[PDM]   [ETS] 시작  (메모리: 1549.8 MB)
[메모리] forecast_ets 실행 전: 1549.82 MB
[메모리] forecast_ets 실행 후: 1549.82 MB (변화: +0.00 MB)
[PDM]   [ETS] 완료  첫값=1.41e+08 (메모리: 1549.8 MB)
[PDM]   [Prophet] 시작  (메모리: 1549.8 MB)
[메모리] forecast_prophet 실행 전: 1549.82 MB

10:47:54 - cmdstanpy - INFO - Chain [1] start processing
10:47:54 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1549.85 MB (변화: +0.02 MB)
[PDM]   [Prophet] 완료  첫값=1.45e+08 (메모리: 1549.8 MB)
[PDM]   [LSTM] 시작  (메모리: 1549.8 MB)
[메모리] forecast_lstm 실행 전: 1549.85 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1549.44 MB (변화: -0.41 MB)
[PDM]   [LSTM] 완료  첫값=1.40e+08 (메모리: 1549.4 MB)
[PDM]   [Theta] 시작  (메모리: 1549.4 MB)
[메모리] forecast_theta 실행 전: 1549.44 MB
[메모리] forecast_theta 실행 후: 1549.44 MB (변화: +0.00 MB)
[PDM]   [Theta] 완료  첫값=1.43e+08 (메모리: 1549.4 MB)
[PDM]   [DB] 88행 저장 완료
[PROGRESS] [  76/500] ( 15.2%)  >>  PVLA
[PVLA] [SKIP] [PVLA] 'sale' 관측치 부족: 12개 < 최소 28개
[PROGRESS] [  77/500] ( 15.4%)  >>  PDS
[PDS]   40분기 | 2016-03-31 ~ 2025-12-31
[PDS]   [SARIMA] 시작  (메모리: 1549.4 MB)
[메모리] forecast_sarima 실행 전: 1549.44 MB
[메모리] find_best_sarima_params 실행 전: 1549.44 MB
[메모리] find_best_sarima_params 실행 후: 1549.44 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1549.44 MB (변화: +0.00 MB)
[PDS]   [SARIMA] 완료  첫값=4.90e+08 (메모리: 1549.4 MB)
[PDS]   [ETS] 시작  (메모리: 1549.4 MB)
[메모리] forecast_ets 실행 전: 1549.44 MB
[메모리] forecast_ets 실행 후: 1549.44 MB (변화: +0.00 MB)
[PDS]   [ETS] 완료  첫값=5.24e+08 (메모리: 1549.4 MB)
[PDS]   [Prophet] 시작  (메모리: 1549.4 MB)

10:48:14 - cmdstanpy - INFO - Chain [1] start processing
10:48:14 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1549.44 MB
[메모리] forecast_prophet 실행 후: 1549.46 MB (변화: +0.02 MB)
[PDS]   [Prophet] 완료  첫값=4.48e+08 (메모리: 1549.5 MB)
[PDS]   [LSTM] 시작  (메모리: 1549.5 MB)
[메모리] forecast_lstm 실행 전: 1549.46 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1549.32 MB (변화: -0.14 MB)
[PDS]   [LSTM] 완료  첫값=3.54e+08 (메모리: 1549.3 MB)
[PDS]   [Theta] 시작  (메모리: 1549.3 MB)
[메모리] forecast_theta 실행 전: 1549.32 MB
[메모리] forecast_theta 실행 후: 1549.32 MB (변화: +0.00 MB)
[PDS]   [Theta] 완료  첫값=5.16e+08 (메모리: 1549.3 MB)
[PDS]   [DB] 88행 저장 완료
[PROGRESS] [  78/500] ( 15.6%)  >>  MRTN
[MRTN]   40분기 | 2016-03-31 ~ 2025-12-31
[MRTN]   [SARIMA] 시작  (메모리: 1549.3 MB)
[메모리] forecast_sarima 실행 전: 1549.32 MB
[메모리] find_best_sarima_params 실행 전: 1549.32 MB
[메모리] find_best_sarima_params 실행 후: 1549.32 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1549.32 MB (변화: +0.00 MB)
[MRTN]   [SARIMA] 완료  첫값=2.06e+08 (메모리: 1549.3 MB)
[MRTN]   [ETS] 시작  (메모리: 1549.3 MB)
[메모리] forecast_ets 실행 전: 1549.32 MB
[메모리] forecast_ets 실행 후: 1549.33 MB (변화: +0.00 MB)
[MRTN]   [ETS] 완료  첫값=1.97e+08 (메모리: 1549.3 MB)
[MRTN]   [Prophet] 시작  (메모리: 1549.3 MB)

10:48:34 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1549.33 MB

10:48:35 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1549.36 MB (변화: +0.03 MB)
[MRTN]   [Prophet] 완료  첫값=2.25e+08 (메모리: 1549.4 MB)
[MRTN]   [LSTM] 시작  (메모리: 1549.4 MB)
[메모리] forecast_lstm 실행 전: 1549.36 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1550.28 MB (변화: +0.93 MB)
[MRTN]   [LSTM] 완료  첫값=2.45e+08 (메모리: 1550.3 MB)
[MRTN]   [Theta] 시작  (메모리: 1550.3 MB)
[메모리] forecast_theta 실행 전: 1550.28 MB
[메모리] forecast_theta 실행 후: 1550.28 MB (변화: +0.00 MB)
[MRTN]   [Theta] 완료  첫값=2.07e+08 (메모리: 1550.3 MB)
[MRTN]   [DB] 88행 저장 완료
[PROGRESS] [  79/500] ( 15.8%)  >>  VEC
[VEC]   40분기 | 2013-09-30 ~ 2025-12-31
[VEC]   [SARIMA] 시작  (메모리: 1550.3 MB)
[메모리] forecast_sarima 실행 전: 1550.29 MB
[메모리] find_best_sarima_params 실행 전: 1550.29 MB
[메모리] find_best_sarima_params 실행 후: 1550.29 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1550.29 MB (변화: +0.00 MB)
[VEC]   [SARIMA] 완료  첫값=1.26e+09 (메모리: 1550.3 MB)
[VEC]   [ETS] 시작  (메모리: 1550.3 MB)
[메모리] forecast_ets 실행 전: 1550.29 MB
[메모리] forecast_ets 실행 후: 1550.29 MB (변화: +0.00 MB)
[VEC]   [ETS] 완료  첫값=1.45e+09 (메모리: 1550.3 MB)
[VEC]   [Prophet] 시작  (메모리: 1550.3 MB)
[메모리] forecast_prophet 실행 전: 1550.29 MB

10:48:53 - cmdstanpy - INFO - Chain [1] start processing
10:48:53 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1550.30 MB (변화: +0.02 MB)
[VEC]   [Prophet] 완료  첫값=1.10e+09 (메모리: 1550.3 MB)
[VEC]   [LSTM] 시작  (메모리: 1550.3 MB)
[메모리] forecast_lstm 실행 전: 1550.30 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1550.31 MB (변화: +0.01 MB)
[VEC]   [LSTM] 완료  첫값=1.78e+09 (메모리: 1550.3 MB)
[VEC]   [Theta] 시작  (메모리: 1550.3 MB)
[메모리] forecast_theta 실행 전: 1550.31 MB
[메모리] forecast_theta 실행 후: 1550.31 MB (변화: +0.00 MB)
[VEC]   [Theta] 완료  첫값=1.12e+09 (메모리: 1550.3 MB)
[VEC]   [DB] 88행 저장 완료
[PROGRESS] [  80/500] ( 16.0%)  >>  GLYC
[GLYC] [NEG-SKIP] [GLYC] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2016, 12, 31)])
[PROGRESS] [  81/500] ( 16.2%)  >>  GLDD
[GLDD]   40분기 | 2016-03-31 ~ 2025-12-31
[GLDD]   [SARIMA] 시작  (메모리: 1550.3 MB)
[메모리] forecast_sarima 실행 전: 1550.31 MB
[메모리] find_best_sarima_params 실행 전: 1550.31 MB
[메모리] find_best_sarima_params 실행 후: 1550.31 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1550.31 MB (변화: +0.00 MB)
[GLDD]   [SARIMA] 완료  첫값=2.24e+08 (메모리: 1550.3 MB)
[GLDD]   [ETS] 시작  (메모리: 1550.3 MB)
[메모리] forecast_ets 실행 전: 1550.31 MB
[메모리] forecast_ets 실행 후: 1550.32 MB (변화: +0.01 MB)
[GLDD]   [ETS] 완료  첫값=2.50e+08 (메모리: 1550.3 MB)
[GLDD]   [Prophet] 시작  (메모리: 1550.3 MB)

10:49:12 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1550.32 MB

10:49:12 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1550.34 MB (변화: +0.02 MB)
[GLDD]   [Prophet] 완료  첫값=1.88e+08 (메모리: 1550.3 MB)
[GLDD]   [LSTM] 시작  (메모리: 1550.3 MB)
[메모리] forecast_lstm 실행 전: 1550.34 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1550.44 MB (변화: +0.10 MB)
[GLDD]   [LSTM] 완료  첫값=1.82e+08 (메모리: 1550.4 MB)
[GLDD]   [Theta] 시작  (메모리: 1550.4 MB)
[메모리] forecast_theta 실행 전: 1550.44 MB
[메모리] forecast_theta 실행 후: 1550.44 MB (변화: +0.00 MB)
[GLDD]   [Theta] 완료  첫값=2.24e+08 (메모리: 1550.4 MB)
[GLDD]   [DB] 88행 저장 완료
[PROGRESS] [  82/500] ( 16.4%)  >>  MFA
[MFA] [NEG-SKIP] [MFA] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2020, 3, 31), datetime.date(2022, 3, 31), datetime.date(2022, 6, 30), datetime.date(2022, 9, 30), datetime.date(2023, 9, 30)])
[PROGRESS] [  83/500] ( 16.6%)  >>  SAFE
[SAFE]   40분기 | 2016-03-31 ~ 2025-12-31
[SAFE]   [SARIMA] 시작  (메모리: 1550.4 MB)
[메모리] forecast_sarima 실행 전: 1550.44 MB
[메모리] find_best_sarima_params 실행 전: 1550.44 MB
[메모리] find_best_sarima_params 실행 후: 1550.44 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1550.44 MB (변화: +0.00 MB)
[SAFE]   [SARIMA] 완료  첫값=1.01e+08 (메모리: 1550.4 MB)
[SAFE]   [ETS] 시작  (메모리: 1550.4 MB)
[메모리] forecast_ets 실행 전: 1550.44 MB
[메모리] forecast_ets 실행 후: 1550.44 MB (변화: +0.00 MB)
[SAFE]   [ETS] 완료  첫값=1.15e+08 (메모리: 1550.4 MB)
[SAFE]   [Prophet] 시작  (메모리: 1550.4 MB)

10:49:30 - cmdstanpy - INFO - Chain [1] start processing
10:49:30 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1550.44 MB
[메모리] forecast_prophet 실행 후: 1550.46 MB (변화: +0.02 MB)
[SAFE]   [Prophet] 완료  첫값=1.08e+08 (메모리: 1550.5 MB)
[SAFE]   [LSTM] 시작  (메모리: 1550.5 MB)
[메모리] forecast_lstm 실행 전: 1550.46 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1548.79 MB (변화: -1.67 MB)
[SAFE]   [LSTM] 완료  첫값=9.62e+07 (메모리: 1548.8 MB)
[SAFE]   [Theta] 시작  (메모리: 1548.8 MB)
[메모리] forecast_theta 실행 전: 1548.79 MB
[메모리] forecast_theta 실행 후: 1548.79 MB (변화: +0.00 MB)
[SAFE]   [Theta] 완료  첫값=1.09e+08 (메모리: 1548.8 MB)
[SAFE]   [DB] 88행 저장 완료
[PROGRESS] [  84/500] ( 16.8%)  >>  BVH
[BVH]   40분기 | 2013-12-31 ~ 2023-09-30
[BVH]   [SARIMA] 시작  (메모리: 1548.8 MB)
[메모리] forecast_sarima 실행 전: 1548.79 MB
[메모리] find_best_sarima_params 실행 전: 1548.79 MB
[메모리] find_best_sarima_params 실행 후: 1548.79 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1548.79 MB (변화: +0.00 MB)
[BVH]   [SARIMA] 완료  첫값=2.12e+08 (메모리: 1548.8 MB)
[BVH]   [ETS] 시작  (메모리: 1548.8 MB)
[메모리] forecast_ets 실행 전: 1548.79 MB
[메모리] forecast_ets 실행 후: 1548.80 MB (변화: +0.00 MB)
[BVH]   [ETS] 완료  첫값=2.20e+08 (메모리: 1548.8 MB)
[BVH]   [Prophet] 시작  (메모리: 1548.8 MB)

10:49:44 - cmdstanpy - INFO - Chain [1] start processing
10:49:44 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1548.80 MB
[메모리] forecast_prophet 실행 후: 1548.82 MB (변화: +0.03 MB)
[BVH]   [Prophet] 완료  첫값=2.07e+08 (메모리: 1548.8 MB)
[BVH]   [LSTM] 시작  (메모리: 1548.8 MB)
[메모리] forecast_lstm 실행 전: 1548.82 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1549.77 MB (변화: +0.95 MB)
[BVH]   [LSTM] 완료  첫값=1.85e+08 (메모리: 1549.8 MB)
[BVH]   [Theta] 시작  (메모리: 1549.8 MB)
[메모리] forecast_theta 실행 전: 1549.77 MB
[메모리] forecast_theta 실행 후: 1549.77 MB (변화: +0.00 MB)
[BVH]   [Theta] 완료  첫값=2.30e+08 (메모리: 1549.8 MB)
[BVH]   [DB] 88행 저장 완료
[PROGRESS] [  85/500] ( 17.0%)  >>  TBPH
[TBPH]   40분기 | 2016-03-31 ~ 2025-12-31
[TBPH]   [SARIMA] 시작  (메모리: 1549.8 MB)
[메모리] forecast_sarima 실행 전: 1549.77 MB
[메모리] find_best_sarima_params 실행 전: 1549.77 MB
[메모리] find_best_sarima_params 실행 후: 1549.77 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1549.77 MB (변화: +0.00 MB)
[TBPH]   [SARIMA] 완료  첫값=2.18e+07 (메모리: 1549.8 MB)
[TBPH]   [ETS] 시작  (메모리: 1549.8 MB)
[메모리] forecast_ets 실행 전: 1549.77 MB
[메모리] forecast_ets 실행 후: 1549.78 MB (변화: +0.01 MB)
[TBPH]   [ETS] 완료  첫값=2.49e+07 (메모리: 1549.8 MB)
[TBPH]   [Prophet] 시작  (메모리: 1549.8 MB)

10:49:57 - cmdstanpy - INFO - Chain [1] start processing
10:49:58 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1549.78 MB
[메모리] forecast_prophet 실행 후: 1549.80 MB (변화: +0.02 MB)
[TBPH]   [Prophet] 완료  첫값=2.15e+07 (메모리: 1549.8 MB)
[TBPH]   [LSTM] 시작  (메모리: 1549.8 MB)
[메모리] forecast_lstm 실행 전: 1549.80 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1549.51 MB (변화: -0.29 MB)
[TBPH]   [LSTM] 완료  첫값=1.79e+07 (메모리: 1549.5 MB)
[TBPH]   [Theta] 시작  (메모리: 1549.5 MB)
[메모리] forecast_theta 실행 전: 1549.51 MB
[메모리] forecast_theta 실행 후: 1549.51 MB (변화: +0.00 MB)
[TBPH]   [Theta] 완료  첫값=3.19e+07 (메모리: 1549.5 MB)
[TBPH]   [DB] 88행 저장 완료
[PROGRESS] [  86/500] ( 17.2%)  >>  OPK
[OPK]   40분기 | 2016-03-31 ~ 2025-12-31
[OPK]   [SARIMA] 시작  (메모리: 1549.5 MB)
[메모리] forecast_sarima 실행 전: 1549.51 MB
[메모리] find_best_sarima_params 실행 전: 1549.51 MB
[메모리] find_best_sarima_params 실행 후: 1549.51 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1549.51 MB (변화: +0.00 MB)
[OPK]   [SARIMA] 완료  첫값=1.48e+08 (메모리: 1549.5 MB)
[OPK]   [ETS] 시작  (메모리: 1549.5 MB)
[메모리] forecast_ets 실행 전: 1549.51 MB
[메모리] forecast_ets 실행 후: 1549.51 MB (변화: +0.00 MB)
[OPK]   [ETS] 완료  첫값=1.52e+08 (메모리: 1549.5 MB)
[OPK]   [Prophet] 시작  (메모리: 1549.5 MB)

10:50:12 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1549.51 MB

10:50:12 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1549.90 MB (변화: +0.39 MB)
[OPK]   [Prophet] 완료  첫값=2.01e+08 (메모리: 1549.9 MB)
[OPK]   [LSTM] 시작  (메모리: 1549.9 MB)
[메모리] forecast_lstm 실행 전: 1549.90 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1551.17 MB (변화: +1.27 MB)
[OPK]   [LSTM] 완료  첫값=2.36e+08 (메모리: 1551.2 MB)
[OPK]   [Theta] 시작  (메모리: 1551.2 MB)
[메모리] forecast_theta 실행 전: 1551.17 MB
[메모리] forecast_theta 실행 후: 1551.17 MB (변화: +0.00 MB)
[OPK]   [Theta] 완료  첫값=1.47e+08 (메모리: 1551.2 MB)
[OPK]   [DB] 88행 저장 완료
[PROGRESS] [  87/500] ( 17.4%)  >>  SOL
[SOL]   40분기 | 2015-12-31 ~ 2025-09-30
[SOL]   [SARIMA] 시작  (메모리: 1551.2 MB)
[메모리] forecast_sarima 실행 전: 1551.17 MB
[메모리] find_best_sarima_params 실행 전: 1551.17 MB
[메모리] find_best_sarima_params 실행 후: 1551.17 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1551.17 MB (변화: +0.00 MB)
[SOL]   [SARIMA] 완료  첫값=2.16e+07 (메모리: 1551.2 MB)
[SOL]   [ETS] 시작  (메모리: 1551.2 MB)
[메모리] forecast_ets 실행 전: 1551.17 MB
[메모리] forecast_ets 실행 후: 1551.18 MB (변화: +0.00 MB)
[SOL]   [ETS] 완료  첫값=1.52e+07 (메모리: 1551.2 MB)
[SOL]   [Prophet] 시작  (메모리: 1551.2 MB)

10:50:30 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1551.18 MB

10:50:30 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1551.19 MB (변화: +0.02 MB)
[SOL]   [Prophet] 완료  첫값=-3.79e+07 (메모리: 1551.2 MB)
[SOL]   [LSTM] 시작  (메모리: 1551.2 MB)
[메모리] forecast_lstm 실행 전: 1551.19 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1552.14 MB (변화: +0.95 MB)
[SOL]   [LSTM] 완료  첫값=2.08e+07 (메모리: 1552.1 MB)
[SOL]   [Theta] 시작  (메모리: 1552.1 MB)
[메모리] forecast_theta 실행 전: 1552.14 MB
[메모리] forecast_theta 실행 후: 1552.14 MB (변화: +0.00 MB)
[SOL]   [Theta] 완료  첫값=1.70e+07 (메모리: 1552.1 MB)
[SOL]   [DB] 88행 저장 완료
[PROGRESS] [  88/500] ( 17.6%)  >>  PRSU
[PRSU] [NEG-SKIP] [PRSU] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2024, 12, 31)])
[PROGRESS] [  89/500] ( 17.8%)  >>  CCO
[CCO]   40분기 | 2016-03-31 ~ 2025-12-31
[CCO]   [SARIMA] 시작  (메모리: 1552.1 MB)
[메모리] forecast_sarima 실행 전: 1552.14 MB
[메모리] find_best_sarima_params 실행 전: 1552.14 MB
[메모리] find_best_sarima_params 실행 후: 1552.14 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1552.14 MB (변화: +0.00 MB)
[CCO]   [SARIMA] 완료  첫값=3.51e+08 (메모리: 1552.1 MB)
[CCO]   [ETS] 시작  (메모리: 1552.1 MB)
[메모리] forecast_ets 실행 전: 1552.14 MB
[메모리] forecast_ets 실행 후: 1552.15 MB (변화: +0.00 MB)
[CCO]   [ETS] 완료  첫값=3.41e+08 (메모리: 1552.1 MB)
[CCO]   [Prophet] 시작  (메모리: 1552.1 MB)

10:50:50 - cmdstanpy - INFO - Chain [1] start processing
10:50:50 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1552.15 MB
[메모리] forecast_prophet 실행 후: 1552.18 MB (변화: +0.03 MB)
[CCO]   [Prophet] 완료  첫값=4.20e+08 (메모리: 1552.2 MB)
[CCO]   [LSTM] 시작  (메모리: 1552.2 MB)
[메모리] forecast_lstm 실행 전: 1552.18 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1552.17 MB (변화: -0.01 MB)
[CCO]   [LSTM] 완료  첫값=4.58e+08 (메모리: 1552.2 MB)
[CCO]   [Theta] 시작  (메모리: 1552.2 MB)
[메모리] forecast_theta 실행 전: 1552.17 MB
[메모리] forecast_theta 실행 후: 1552.17 MB (변화: +0.00 MB)
[CCO]   [Theta] 완료  첫값=3.48e+08 (메모리: 1552.2 MB)
[CCO]   [DB] 88행 저장 완료
[PROGRESS] [  90/500] ( 18.0%)  >>  CPLP
[CPLP]   40분기 | 2014-09-30 ~ 2024-06-30
[CPLP]   [SARIMA] 시작  (메모리: 1552.2 MB)
[메모리] forecast_sarima 실행 전: 1552.17 MB
[메모리] find_best_sarima_params 실행 전: 1552.17 MB
[메모리] find_best_sarima_params 실행 후: 1552.17 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1552.17 MB (변화: +0.00 MB)
[CPLP]   [SARIMA] 완료  첫값=9.65e+07 (메모리: 1552.2 MB)
[CPLP]   [ETS] 시작  (메모리: 1552.2 MB)
[메모리] forecast_ets 실행 전: 1552.17 MB
[메모리] forecast_ets 실행 후: 1552.17 MB (변화: +0.00 MB)
[CPLP]   [ETS] 완료  첫값=1.09e+08 (메모리: 1552.2 MB)
[CPLP]   [Prophet] 시작  (메모리: 1552.2 MB)

10:51:04 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1552.17 MB

10:51:04 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1552.19 MB (변화: +0.02 MB)
[CPLP]   [Prophet] 완료  첫값=7.45e+07 (메모리: 1552.2 MB)
[CPLP]   [LSTM] 시작  (메모리: 1552.2 MB)
[메모리] forecast_lstm 실행 전: 1552.19 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1552.18 MB (변화: -0.01 MB)
[CPLP]   [LSTM] 완료  첫값=8.14e+07 (메모리: 1552.2 MB)
[CPLP]   [Theta] 시작  (메모리: 1552.2 MB)
[메모리] forecast_theta 실행 전: 1552.18 MB
[메모리] forecast_theta 실행 후: 1552.18 MB (변화: +0.00 MB)
[CPLP]   [Theta] 완료  첫값=1.07e+08 (메모리: 1552.2 MB)
[CPLP]   [DB] 88행 저장 완료
[PROGRESS] [  91/500] ( 18.2%)  >>  LQDT
[LQDT]   40분기 | 2016-03-31 ~ 2025-12-31
[LQDT]   [SARIMA] 시작  (메모리: 1552.2 MB)
[메모리] forecast_sarima 실행 전: 1552.18 MB
[메모리] find_best_sarima_params 실행 전: 1552.18 MB
[메모리] find_best_sarima_params 실행 후: 1552.18 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1552.18 MB (변화: +0.00 MB)
[LQDT]   [SARIMA] 완료  첫값=1.22e+08 (메모리: 1552.2 MB)
[LQDT]   [ETS] 시작  (메모리: 1552.2 MB)
[메모리] forecast_ets 실행 전: 1552.18 MB
[메모리] forecast_ets 실행 후: 1552.18 MB (변화: +0.00 MB)
[LQDT]   [ETS] 완료  첫값=1.32e+08 (메모리: 1552.2 MB)
[LQDT]   [Prophet] 시작  (메모리: 1552.2 MB)

10:51:24 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1552.18 MB

10:51:24 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1552.22 MB (변화: +0.04 MB)
[LQDT]   [Prophet] 완료  첫값=9.93e+07 (메모리: 1552.2 MB)
[LQDT]   [LSTM] 시작  (메모리: 1552.2 MB)
[메모리] forecast_lstm 실행 전: 1552.22 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1552.17 MB (변화: -0.05 MB)
[LQDT]   [LSTM] 완료  첫값=1.53e+08 (메모리: 1552.2 MB)
[LQDT]   [Theta] 시작  (메모리: 1552.2 MB)
[메모리] forecast_theta 실행 전: 1552.17 MB
[메모리] forecast_theta 실행 후: 1552.17 MB (변화: +0.00 MB)
[LQDT]   [Theta] 완료  첫값=1.29e+08 (메모리: 1552.2 MB)
[LQDT]   [DB] 88행 저장 완료
[PROGRESS] [  92/500] ( 18.4%)  >>  BBSI
[BBSI]   40분기 | 2016-03-31 ~ 2025-12-31
[BBSI]   [SARIMA] 시작  (메모리: 1552.2 MB)
[메모리] forecast_sarima 실행 전: 1552.17 MB
[메모리] find_best_sarima_params 실행 전: 1552.17 MB
[메모리] find_best_sarima_params 실행 후: 1552.17 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1552.17 MB (변화: +0.00 MB)
[BBSI]   [SARIMA] 완료  첫값=3.12e+08 (메모리: 1552.2 MB)
[BBSI]   [ETS] 시작  (메모리: 1552.2 MB)
[메모리] forecast_ets 실행 전: 1552.17 MB
[메모리] forecast_ets 실행 후: 1552.18 MB (변화: +0.00 MB)
[BBSI]   [ETS] 완료  첫값=3.01e+08 (메모리: 1552.2 MB)
[BBSI]   [Prophet] 시작  (메모리: 1552.2 MB)

10:51:44 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1552.18 MB

10:51:45 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1552.20 MB (변화: +0.02 MB)
[BBSI]   [Prophet] 완료  첫값=3.12e+08 (메모리: 1552.2 MB)
[BBSI]   [LSTM] 시작  (메모리: 1552.2 MB)
[메모리] forecast_lstm 실행 전: 1552.20 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1551.93 MB (변화: -0.27 MB)
[BBSI]   [LSTM] 완료  첫값=2.98e+08 (메모리: 1551.9 MB)
[BBSI]   [Theta] 시작  (메모리: 1551.9 MB)
[메모리] forecast_theta 실행 전: 1551.93 MB
[메모리] forecast_theta 실행 후: 1551.93 MB (변화: +0.00 MB)
[BBSI]   [Theta] 완료  첫값=2.99e+08 (메모리: 1551.9 MB)
[BBSI]   [DB] 88행 저장 완료
[PROGRESS] [  93/500] ( 18.6%)  >>  NBR
[NBR]   40분기 | 2016-03-31 ~ 2025-12-31
[NBR]   [SARIMA] 시작  (메모리: 1551.9 MB)
[메모리] forecast_sarima 실행 전: 1551.93 MB
[메모리] find_best_sarima_params 실행 전: 1551.93 MB
[메모리] find_best_sarima_params 실행 후: 1551.93 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1551.93 MB (변화: +0.00 MB)
[NBR]   [SARIMA] 완료  첫값=7.88e+08 (메모리: 1551.9 MB)
[NBR]   [ETS] 시작  (메모리: 1551.9 MB)
[메모리] forecast_ets 실행 전: 1551.93 MB
[메모리] forecast_ets 실행 후: 1551.93 MB (변화: +0.00 MB)
[NBR]   [ETS] 완료  첫값=8.01e+08 (메모리: 1551.9 MB)
[NBR]   [Prophet] 시작  (메모리: 1551.9 MB)

10:52:01 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1551.93 MB

10:52:01 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1551.96 MB (변화: +0.03 MB)
[NBR]   [Prophet] 완료  첫값=7.45e+08 (메모리: 1552.0 MB)
[NBR]   [LSTM] 시작  (메모리: 1552.0 MB)
[메모리] forecast_lstm 실행 전: 1551.96 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1551.81 MB (변화: -0.15 MB)
[NBR]   [LSTM] 완료  첫값=6.45e+08 (메모리: 1551.8 MB)
[NBR]   [Theta] 시작  (메모리: 1551.8 MB)
[메모리] forecast_theta 실행 전: 1551.81 MB
[메모리] forecast_theta 실행 후: 1551.81 MB (변화: +0.00 MB)
[NBR]   [Theta] 완료  첫값=8.00e+08 (메모리: 1551.8 MB)
[NBR]   [DB] 88행 저장 완료
[PROGRESS] [  94/500] ( 18.8%)  >>  IOVA
[IOVA]   40분기 | 2016-03-31 ~ 2025-12-31
[IOVA]   [SARIMA] 시작  (메모리: 1551.8 MB)
[메모리] forecast_sarima 실행 전: 1551.81 MB
[메모리] find_best_sarima_params 실행 전: 1551.81 MB
[메모리] find_best_sarima_params 실행 후: 1551.81 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1551.81 MB (변화: +0.00 MB)
[IOVA]   [SARIMA] 완료  첫값=0.00e+00 (메모리: 1551.8 MB)
[IOVA]   [ETS] 시작  (메모리: 1551.8 MB)
[메모리] forecast_ets 실행 전: 1551.81 MB
[메모리] forecast_ets 실행 후: 1551.82 MB (변화: +0.00 MB)
[IOVA]   [ETS] 완료  첫값=9.29e+07 (메모리: 1551.8 MB)
[IOVA]   [Prophet] 시작  (메모리: 1551.8 MB)

10:52:21 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1551.82 MB

10:52:22 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1551.84 MB (변화: +0.03 MB)
[IOVA]   [Prophet] 완료  첫값=3.85e+07 (메모리: 1551.8 MB)
[IOVA]   [LSTM] 시작  (메모리: 1551.8 MB)
[메모리] forecast_lstm 실행 전: 1551.84 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1552.78 MB (변화: +0.94 MB)
[IOVA]   [LSTM] 완료  첫값=1.35e+08 (메모리: 1552.8 MB)
[IOVA]   [Theta] 시작  (메모리: 1552.8 MB)
[메모리] forecast_theta 실행 전: 1552.78 MB
[메모리] forecast_theta 실행 후: 1552.78 MB (변화: +0.00 MB)
[IOVA]   [Theta] 완료  첫값=8.30e+07 (메모리: 1552.8 MB)
[IOVA]   [DB] 88행 저장 완료
[PROGRESS] [  95/500] ( 19.0%)  >>  WBI
[WBI] [SKIP] [WBI] 'sale' 관측치 부족: 4개 < 최소 28개
[PROGRESS] [  96/500] ( 19.2%)  >>  LMB
[LMB]   40분기 | 2016-03-31 ~ 2025-12-31
[LMB]   [SARIMA] 시작  (메모리: 1552.8 MB)
[메모리] forecast_sarima 실행 전: 1552.78 MB
[메모리] find_best_sarima_params 실행 전: 1552.78 MB
[메모리] find_best_sarima_params 실행 후: 1552.78 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1552.78 MB (변화: +0.00 MB)
[LMB]   [SARIMA] 완료  첫값=1.76e+08 (메모리: 1552.8 MB)
[LMB]   [ETS] 시작  (메모리: 1552.8 MB)
[메모리] forecast_ets 실행 전: 1552.78 MB
[메모리] forecast_ets 실행 후: 1552.79 MB (변화: +0.00 MB)
[LMB]   [ETS] 완료  첫값=1.65e+08 (메모리: 1552.8 MB)
[LMB]   [Prophet] 시작  (메모리: 1552.8 MB)

10:52:42 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1552.79 MB

10:52:42 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1552.80 MB (변화: +0.02 MB)
[LMB]   [Prophet] 완료  첫값=1.46e+08 (메모리: 1552.8 MB)
[LMB]   [LSTM] 시작  (메모리: 1552.8 MB)
[메모리] forecast_lstm 실행 전: 1552.80 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1552.78 MB (변화: -0.02 MB)
[LMB]   [LSTM] 완료  첫값=1.35e+08 (메모리: 1552.8 MB)
[LMB]   [Theta] 시작  (메모리: 1552.8 MB)
[메모리] forecast_theta 실행 전: 1552.78 MB
[메모리] forecast_theta 실행 후: 1552.78 MB (변화: +0.00 MB)
[LMB]   [Theta] 완료  첫값=1.63e+08 (메모리: 1552.8 MB)
[LMB]   [DB] 88행 저장 완료
[PROGRESS] [  97/500] ( 19.4%)  >>  AXL
[AXL]   40분기 | 2016-03-31 ~ 2025-12-31
[AXL]   [SARIMA] 시작  (메모리: 1552.8 MB)
[메모리] forecast_sarima 실행 전: 1552.78 MB
[메모리] find_best_sarima_params 실행 전: 1552.78 MB
[메모리] find_best_sarima_params 실행 후: 1552.78 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1552.78 MB (변화: +0.00 MB)
[AXL]   [SARIMA] 완료  첫값=1.45e+09 (메모리: 1552.8 MB)
[AXL]   [ETS] 시작  (메모리: 1552.8 MB)
[메모리] forecast_ets 실행 전: 1552.78 MB
[메모리] forecast_ets 실행 후: 1552.78 MB (변화: +0.00 MB)
[AXL]   [ETS] 완료  첫값=1.49e+09 (메모리: 1552.8 MB)
[AXL]   [Prophet] 시작  (메모리: 1552.8 MB)

10:52:57 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1552.78 MB

10:52:57 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1552.81 MB (변화: +0.03 MB)
[AXL]   [Prophet] 완료  첫값=1.51e+09 (메모리: 1552.8 MB)
[AXL]   [LSTM] 시작  (메모리: 1552.8 MB)
[메모리] forecast_lstm 실행 전: 1552.81 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1552.81 MB (변화: -0.00 MB)
[AXL]   [LSTM] 완료  첫값=1.40e+09 (메모리: 1552.8 MB)
[AXL]   [Theta] 시작  (메모리: 1552.8 MB)
[메모리] forecast_theta 실행 전: 1552.81 MB
[메모리] forecast_theta 실행 후: 1552.81 MB (변화: +0.00 MB)
[AXL]   [Theta] 완료  첫값=1.44e+09 (메모리: 1552.8 MB)
[AXL]   [DB] 88행 저장 완료
[PROGRESS] [  98/500] ( 19.6%)  >>  CPAC
[CPAC]   40분기 | 2016-03-31 ~ 2025-12-31
[CPAC]   [SARIMA] 시작  (메모리: 1552.8 MB)
[메모리] forecast_sarima 실행 전: 1552.81 MB
[메모리] find_best_sarima_params 실행 전: 1552.81 MB
[메모리] find_best_sarima_params 실행 후: 1552.81 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1552.81 MB (변화: +0.00 MB)
[CPAC]   [SARIMA] 완료  첫값=5.82e+08 (메모리: 1552.8 MB)
[CPAC]   [ETS] 시작  (메모리: 1552.8 MB)
[메모리] forecast_ets 실행 전: 1552.81 MB
[메모리] forecast_ets 실행 후: 1552.82 MB (변화: +0.00 MB)
[CPAC]   [ETS] 완료  첫값=5.39e+08 (메모리: 1552.8 MB)
[CPAC]   [Prophet] 시작  (메모리: 1552.8 MB)

10:53:12 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1552.82 MB

10:53:12 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1552.84 MB (변화: +0.03 MB)
[CPAC]   [Prophet] 완료  첫값=5.67e+08 (메모리: 1552.8 MB)
[CPAC]   [LSTM] 시작  (메모리: 1552.8 MB)
[메모리] forecast_lstm 실행 전: 1552.84 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1552.74 MB (변화: -0.11 MB)
[CPAC]   [LSTM] 완료  첫값=5.07e+08 (메모리: 1552.7 MB)
[CPAC]   [Theta] 시작  (메모리: 1552.7 MB)
[메모리] forecast_theta 실행 전: 1552.74 MB
[메모리] forecast_theta 실행 후: 1552.74 MB (변화: +0.00 MB)
[CPAC]   [Theta] 완료  첫값=5.27e+08 (메모리: 1552.7 MB)
[CPAC]   [DB] 88행 저장 완료
[PROGRESS] [  99/500] ( 19.8%)  >>  STAA
[STAA]   40분기 | 2016-04-01 ~ 2026-01-02
[STAA]   [SARIMA] 시작  (메모리: 1552.7 MB)
[메모리] forecast_sarima 실행 전: 1552.74 MB
[메모리] find_best_sarima_params 실행 전: 1552.74 MB
[메모리] find_best_sarima_params 실행 후: 1552.74 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1552.74 MB (변화: +0.00 MB)
[STAA]   [SARIMA] 완료  첫값=3.24e+07 (메모리: 1552.7 MB)
[STAA]   [ETS] 시작  (메모리: 1552.7 MB)
[메모리] forecast_ets 실행 전: 1552.74 MB
[메모리] forecast_ets 실행 후: 1552.75 MB (변화: +0.01 MB)
[STAA]   [ETS] 완료  첫값=6.26e+07 (메모리: 1552.7 MB)
[STAA]   [Prophet] 시작  (메모리: 1552.7 MB)

10:53:26 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1552.75 MB

10:53:26 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1552.78 MB (변화: +0.03 MB)
[STAA]   [Prophet] 완료  첫값=8.33e+07 (메모리: 1552.8 MB)
[STAA]   [LSTM] 시작  (메모리: 1552.8 MB)
[메모리] forecast_lstm 실행 전: 1552.78 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1551.58 MB (변화: -1.20 MB)
[STAA]   [LSTM] 완료  첫값=7.30e+07 (메모리: 1551.6 MB)
[STAA]   [Theta] 시작  (메모리: 1551.6 MB)
[메모리] forecast_theta 실행 전: 1551.58 MB
[메모리] forecast_theta 실행 후: 1551.58 MB (변화: +0.00 MB)
[STAA]   [Theta] 완료  첫값=6.12e+07 (메모리: 1551.6 MB)
[STAA]   [DB] 88행 저장 완료
[PROGRESS] [ 100/500] ( 20.0%)  >>  LOT
[LOT] [SKIP] [LOT] 'sale' 관측치 부족: 17개 < 최소 28개
[PROGRESS] [ 101/500] ( 20.2%)  >>  CHS
[CHS]   40분기 | 2014-02-01 ~ 2023-10-28
[CHS]   [SARIMA] 시작  (메모리: 1551.6 MB)
[메모리] forecast_sarima 실행 전: 1551.59 MB
[메모리] find_best_sarima_params 실행 전: 1551.59 MB
[메모리] find_best_sarima_params 실행 후: 1551.59 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1551.59 MB (변화: +0.00 MB)
[CHS]   [SARIMA] 완료  첫값=5.05e+08 (메모리: 1551.6 MB)
[CHS]   [ETS] 시작  (메모리: 1551.6 MB)
[메모리] forecast_ets 실행 전: 1551.59 MB
[메모리] forecast_ets 실행 후: 1551.59 MB (변화: +0.00 MB)
[CHS]   [ETS] 완료  첫값=5.30e+08 (메모리: 1551.6 MB)
[CHS]   [Prophet] 시작  (메모리: 1551.6 MB)

10:53:46 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1551.59 MB

10:53:46 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1551.62 MB (변화: +0.03 MB)
[CHS]   [Prophet] 완료  첫값=4.30e+08 (메모리: 1551.6 MB)
[CHS]   [LSTM] 시작  (메모리: 1551.6 MB)
[메모리] forecast_lstm 실행 전: 1551.62 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1552.61 MB (변화: +1.00 MB)
[CHS]   [LSTM] 완료  첫값=4.68e+08 (메모리: 1552.6 MB)
[CHS]   [Theta] 시작  (메모리: 1552.6 MB)
[메모리] forecast_theta 실행 전: 1552.61 MB
[메모리] forecast_theta 실행 후: 1552.61 MB (변화: +0.00 MB)
[CHS]   [Theta] 완료  첫값=5.31e+08 (메모리: 1552.6 MB)
[CHS]   [DB] 88행 저장 완료
[PROGRESS] [ 102/500] ( 20.4%)  >>  HA
[HA]   40분기 | 2014-09-30 ~ 2024-06-30
[HA]   [SARIMA] 시작  (메모리: 1552.6 MB)
[메모리] forecast_sarima 실행 전: 1552.61 MB
[메모리] find_best_sarima_params 실행 전: 1552.61 MB
[메모리] find_best_sarima_params 실행 후: 1552.61 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1552.61 MB (변화: +0.00 MB)
[HA]   [SARIMA] 완료  첫값=7.08e+08 (메모리: 1552.6 MB)
[HA]   [ETS] 시작  (메모리: 1552.6 MB)
[메모리] forecast_ets 실행 전: 1552.61 MB
[메모리] forecast_ets 실행 후: 1552.62 MB (변화: +0.01 MB)
[HA]   [ETS] 완료  첫값=8.14e+08 (메모리: 1552.6 MB)
[HA]   [Prophet] 시작  (메모리: 1552.6 MB)

10:53:59 - cmdstanpy - INFO - Chain [1] start processing
10:54:00 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1552.62 MB
[메모리] forecast_prophet 실행 후: 1552.65 MB (변화: +0.03 MB)
[HA]   [Prophet] 완료  첫값=5.73e+08 (메모리: 1552.7 MB)
[HA]   [LSTM] 시작  (메모리: 1552.7 MB)
[메모리] forecast_lstm 실행 전: 1552.65 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1552.60 MB (변화: -0.05 MB)
[HA]   [LSTM] 완료  첫값=5.99e+08 (메모리: 1552.6 MB)
[HA]   [Theta] 시작  (메모리: 1552.6 MB)
[메모리] forecast_theta 실행 전: 1552.60 MB
[메모리] forecast_theta 실행 후: 1552.60 MB (변화: +0.00 MB)
[HA]   [Theta] 완료  첫값=7.30e+08 (메모리: 1552.6 MB)
[HA]   [DB] 88행 저장 완료
[PROGRESS] [ 103/500] ( 20.6%)  >>  SSYS
[SSYS]   40분기 | 2016-03-31 ~ 2025-12-31
[SSYS]   [SARIMA] 시작  (메모리: 1552.6 MB)
[메모리] forecast_sarima 실행 전: 1552.60 MB
[메모리] find_best_sarima_params 실행 전: 1552.60 MB
[메모리] find_best_sarima_params 실행 후: 1552.60 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1552.60 MB (변화: +0.00 MB)
[SSYS]   [SARIMA] 완료  첫값=1.38e+08 (메모리: 1552.6 MB)
[SSYS]   [ETS] 시작  (메모리: 1552.6 MB)
[메모리] forecast_ets 실행 전: 1552.60 MB
[메모리] forecast_ets 실행 후: 1552.61 MB (변화: +0.00 MB)
[SSYS]   [ETS] 완료  첫값=1.28e+08 (메모리: 1552.6 MB)
[SSYS]   [Prophet] 시작  (메모리: 1552.6 MB)

10:54:20 - cmdstanpy - INFO - Chain [1] start processing
10:54:20 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1552.61 MB
[메모리] forecast_prophet 실행 후: 1552.64 MB (변화: +0.03 MB)
[SSYS]   [Prophet] 완료  첫값=1.41e+08 (메모리: 1552.6 MB)
[SSYS]   [LSTM] 시작  (메모리: 1552.6 MB)
[메모리] forecast_lstm 실행 전: 1552.64 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1551.88 MB (변화: -0.76 MB)
[SSYS]   [LSTM] 완료  첫값=1.46e+08 (메모리: 1551.9 MB)
[SSYS]   [Theta] 시작  (메모리: 1551.9 MB)
[메모리] forecast_theta 실행 전: 1551.88 MB
[메모리] forecast_theta 실행 후: 1551.88 MB (변화: +0.00 MB)
[SSYS]   [Theta] 완료  첫값=1.39e+08 (메모리: 1551.9 MB)
[SSYS]   [DB] 88행 저장 완료
[PROGRESS] [ 104/500] ( 20.8%)  >>  HDL
[HDL] [SKIP] [HDL] 'sale' 관측치 부족: 19개 < 최소 28개
[PROGRESS] [ 105/500] ( 21.0%)  >>  BJRI
[BJRI]   40분기 | 2016-03-29 ~ 2025-12-30
[BJRI]   [SARIMA] 시작  (메모리: 1551.9 MB)
[메모리] forecast_sarima 실행 전: 1551.88 MB
[메모리] find_best_sarima_params 실행 전: 1551.88 MB
[메모리] find_best_sarima_params 실행 후: 1551.88 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1551.88 MB (변화: +0.00 MB)
[BJRI]   [SARIMA] 완료  첫값=3.48e+08 (메모리: 1551.9 MB)
[BJRI]   [ETS] 시작  (메모리: 1551.9 MB)
[메모리] forecast_ets 실행 전: 1551.88 MB
[메모리] forecast_ets 실행 후: 1551.88 MB (변화: +0.00 MB)
[BJRI]   [ETS] 완료  첫값=3.60e+08 (메모리: 1551.9 MB)
[BJRI]   [Prophet] 시작  (메모리: 1551.9 MB)

10:54:39 - cmdstanpy - INFO - Chain [1] start processing
10:54:39 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1551.88 MB
[메모리] forecast_prophet 실행 후: 1551.92 MB (변화: +0.04 MB)
[BJRI]   [Prophet] 완료  첫값=3.45e+08 (메모리: 1551.9 MB)
[BJRI]   [LSTM] 시작  (메모리: 1551.9 MB)
[메모리] forecast_lstm 실행 전: 1551.92 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1552.85 MB (변화: +0.93 MB)
[BJRI]   [LSTM] 완료  첫값=3.40e+08 (메모리: 1552.9 MB)
[BJRI]   [Theta] 시작  (메모리: 1552.9 MB)
[메모리] forecast_theta 실행 전: 1552.85 MB
[메모리] forecast_theta 실행 후: 1552.85 MB (변화: +0.00 MB)
[BJRI]   [Theta] 완료  첫값=3.53e+08 (메모리: 1552.9 MB)
[BJRI]   [DB] 88행 저장 완료
[PROGRESS] [ 106/500] ( 21.2%)  >>  XNCR
[XNCR]   40분기 | 2016-03-31 ~ 2025-12-31
[XNCR]   [SARIMA] 시작  (메모리: 1552.9 MB)
[메모리] forecast_sarima 실행 전: 1552.85 MB
[메모리] find_best_sarima_params 실행 전: 1552.85 MB
[메모리] find_best_sarima_params 실행 후: 1552.85 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1552.85 MB (변화: +0.00 MB)
[XNCR]   [SARIMA] 완료  첫값=4.28e+07 (메모리: 1552.9 MB)
[XNCR]   [ETS] 시작  (메모리: 1552.9 MB)
[메모리] forecast_ets 실행 전: 1552.85 MB
[메모리] forecast_ets 실행 후: 1552.86 MB (변화: +0.00 MB)
[XNCR]   [ETS] 완료  첫값=6.79e+07 (메모리: 1552.9 MB)
[XNCR]   [Prophet] 시작  (메모리: 1552.9 MB)

10:54:52 - cmdstanpy - INFO - Chain [1] start processing
10:54:53 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1552.86 MB
[메모리] forecast_prophet 실행 후: 1552.89 MB (변화: +0.03 MB)
[XNCR]   [Prophet] 완료  첫값=4.66e+07 (메모리: 1552.9 MB)
[XNCR]   [LSTM] 시작  (메모리: 1552.9 MB)
[메모리] forecast_lstm 실행 전: 1552.89 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1552.77 MB (변화: -0.11 MB)
[XNCR]   [LSTM] 완료  첫값=4.52e+07 (메모리: 1552.8 MB)
[XNCR]   [Theta] 시작  (메모리: 1552.8 MB)
[메모리] forecast_theta 실행 전: 1552.77 MB
[메모리] forecast_theta 실행 후: 1552.77 MB (변화: +0.00 MB)
[XNCR]   [Theta] 완료  첫값=3.77e+07 (메모리: 1552.8 MB)
[XNCR]   [DB] 88행 저장 완료
[PROGRESS] [ 107/500] ( 21.4%)  >>  GSM
[GSM]   40분기 | 2016-03-31 ~ 2025-12-31
[GSM]   [SARIMA] 시작  (메모리: 1552.8 MB)
[메모리] forecast_sarima 실행 전: 1552.77 MB
[메모리] find_best_sarima_params 실행 전: 1552.77 MB
[메모리] find_best_sarima_params 실행 후: 1552.77 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1552.77 MB (변화: +0.00 MB)
[GSM]   [SARIMA] 완료  첫값=3.29e+08 (메모리: 1552.8 MB)
[GSM]   [ETS] 시작  (메모리: 1552.8 MB)
[메모리] forecast_ets 실행 전: 1552.77 MB
[메모리] forecast_ets 실행 후: 1552.78 MB (변화: +0.00 MB)
[GSM]   [ETS] 완료  첫값=3.22e+08 (메모리: 1552.8 MB)
[GSM]   [Prophet] 시작  (메모리: 1552.8 MB)

10:55:06 - cmdstanpy - INFO - Chain [1] start processing
10:55:06 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1552.78 MB
[메모리] forecast_prophet 실행 후: 1552.81 MB (변화: +0.03 MB)
[GSM]   [Prophet] 완료  첫값=4.03e+08 (메모리: 1552.8 MB)
[GSM]   [LSTM] 시작  (메모리: 1552.8 MB)
[메모리] forecast_lstm 실행 전: 1552.81 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1553.65 MB (변화: +0.84 MB)
[GSM]   [LSTM] 완료  첫값=5.02e+08 (메모리: 1553.6 MB)
[GSM]   [Theta] 시작  (메모리: 1553.6 MB)
[메모리] forecast_theta 실행 전: 1553.65 MB
[메모리] forecast_theta 실행 후: 1553.65 MB (변화: +0.00 MB)
[GSM]   [Theta] 완료  첫값=3.29e+08 (메모리: 1553.6 MB)
[GSM]   [DB] 88행 저장 완료
[PROGRESS] [ 108/500] ( 21.6%)  >>  ALBO
[ALBO] [NEG-SKIP] [ALBO] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2017, 12, 31)])
[PROGRESS] [ 109/500] ( 21.8%)  >>  SPTN
[SPTN]   40분기 | 2015-10-10 ~ 2025-07-12
[SPTN]   [SARIMA] 시작  (메모리: 1553.6 MB)
[메모리] forecast_sarima 실행 전: 1553.65 MB
[메모리] find_best_sarima_params 실행 전: 1553.65 MB
[메모리] find_best_sarima_params 실행 후: 1553.65 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1553.65 MB (변화: +0.00 MB)
[SPTN]   [SARIMA] 완료  첫값=2.30e+09 (메모리: 1553.6 MB)
[SPTN]   [ETS] 시작  (메모리: 1553.6 MB)
[메모리] forecast_ets 실행 전: 1553.65 MB
[메모리] forecast_ets 실행 후: 1553.66 MB (변화: +0.01 MB)
[SPTN]   [ETS] 완료  첫값=2.27e+09 (메모리: 1553.7 MB)
[SPTN]   [Prophet] 시작  (메모리: 1553.7 MB)

10:55:28 - cmdstanpy - INFO - Chain [1] start processing
10:55:28 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1553.66 MB
[메모리] forecast_prophet 실행 후: 1553.82 MB (변화: +0.16 MB)
[SPTN]   [Prophet] 완료  첫값=2.53e+09 (메모리: 1553.8 MB)
[SPTN]   [LSTM] 시작  (메모리: 1553.8 MB)
[메모리] forecast_lstm 실행 전: 1553.82 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1554.97 MB (변화: +1.15 MB)
[SPTN]   [LSTM] 완료  첫값=2.45e+09 (메모리: 1555.0 MB)
[SPTN]   [Theta] 시작  (메모리: 1555.0 MB)
[메모리] forecast_theta 실행 전: 1554.97 MB
[메모리] forecast_theta 실행 후: 1554.97 MB (변화: +0.00 MB)
[SPTN]   [Theta] 완료  첫값=2.25e+09 (메모리: 1555.0 MB)
[SPTN]   [DB] 88행 저장 완료
[PROGRESS] [ 110/500] ( 22.0%)  >>  SCHN
[SCHN]   40분기 | 2015-08-31 ~ 2025-05-31
[SCHN]   [SARIMA] 시작  (메모리: 1555.0 MB)
[메모리] forecast_sarima 실행 전: 1554.97 MB
[메모리] find_best_sarima_params 실행 전: 1554.97 MB
[메모리] find_best_sarima_params 실행 후: 1554.97 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1554.97 MB (변화: +0.00 MB)
[SCHN]   [SARIMA] 완료  첫값=7.11e+08 (메모리: 1555.0 MB)
[SCHN]   [ETS] 시작  (메모리: 1555.0 MB)
[메모리] forecast_ets 실행 전: 1554.97 MB
[메모리] forecast_ets 실행 후: 1554.98 MB (변화: +0.00 MB)
[SCHN]   [ETS] 완료  첫값=7.46e+08 (메모리: 1555.0 MB)
[SCHN]   [Prophet] 시작  (메모리: 1555.0 MB)

10:55:44 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1554.98 MB

10:55:44 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1555.02 MB (변화: +0.04 MB)
[SCHN]   [Prophet] 완료  첫값=8.12e+08 (메모리: 1555.0 MB)
[SCHN]   [LSTM] 시작  (메모리: 1555.0 MB)
[메모리] forecast_lstm 실행 전: 1555.02 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1554.61 MB (변화: -0.40 MB)
[SCHN]   [LSTM] 완료  첫값=8.05e+08 (메모리: 1554.6 MB)
[SCHN]   [Theta] 시작  (메모리: 1554.6 MB)
[메모리] forecast_theta 실행 전: 1554.61 MB
[메모리] forecast_theta 실행 후: 1554.61 MB (변화: +0.00 MB)
[SCHN]   [Theta] 완료  첫값=7.38e+08 (메모리: 1554.6 MB)
[SCHN]   [DB] 88행 저장 완료
[PROGRESS] [ 111/500] ( 22.2%)  >>  CTMX
[CTMX]   40분기 | 2016-03-31 ~ 2025-12-31
[CTMX]   [SARIMA] 시작  (메모리: 1554.6 MB)
[메모리] forecast_sarima 실행 전: 1554.61 MB
[메모리] find_best_sarima_params 실행 전: 1554.61 MB
[메모리] find_best_sarima_params 실행 후: 1554.61 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1554.61 MB (변화: +0.00 MB)
[CTMX]   [SARIMA] 완료  첫값=2.17e+06 (메모리: 1554.6 MB)
[CTMX]   [ETS] 시작  (메모리: 1554.6 MB)
[메모리] forecast_ets 실행 전: 1554.61 MB
[메모리] forecast_ets 실행 후: 1554.62 MB (변화: +0.01 MB)
[CTMX]   [ETS] 완료  첫값=4.31e+05 (메모리: 1554.6 MB)
[CTMX]   [Prophet] 시작  (메모리: 1554.6 MB)

10:55:57 - cmdstanpy - INFO - Chain [1] start processing
10:55:58 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1554.62 MB
[메모리] forecast_prophet 실행 후: 1554.64 MB (변화: +0.02 MB)
[CTMX]   [Prophet] 완료  첫값=2.73e+07 (메모리: 1554.6 MB)
[CTMX]   [LSTM] 시작  (메모리: 1554.6 MB)
[메모리] forecast_lstm 실행 전: 1554.64 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1555.66 MB (변화: +1.02 MB)
[CTMX]   [LSTM] 완료  첫값=2.51e+07 (메모리: 1555.7 MB)
[CTMX]   [Theta] 시작  (메모리: 1555.7 MB)
[메모리] forecast_theta 실행 전: 1555.66 MB
[메모리] forecast_theta 실행 후: 1555.66 MB (변화: +0.00 MB)
[CTMX]   [Theta] 완료  첫값=8.16e+05 (메모리: 1555.7 MB)
[CTMX]   [DB] 88행 저장 완료
[PROGRESS] [ 112/500] ( 22.4%)  >>  RYI
[RYI]   40분기 | 2016-03-31 ~ 2025-12-31
[RYI]   [SARIMA] 시작  (메모리: 1555.7 MB)
[메모리] forecast_sarima 실행 전: 1555.66 MB
[메모리] find_best_sarima_params 실행 전: 1555.66 MB
[메모리] find_best_sarima_params 실행 후: 1555.66 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1555.66 MB (변화: +0.00 MB)
[RYI]   [SARIMA] 완료  첫값=1.32e+09 (메모리: 1555.7 MB)
[RYI]   [ETS] 시작  (메모리: 1555.7 MB)
[메모리] forecast_ets 실행 전: 1555.66 MB
[메모리] forecast_ets 실행 후: 1555.67 MB (변화: +0.01 MB)
[RYI]   [ETS] 완료  첫값=1.29e+09 (메모리: 1555.7 MB)
[RYI]   [Prophet] 시작  (메모리: 1555.7 MB)

10:56:14 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1555.67 MB

10:56:14 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1555.71 MB (변화: +0.04 MB)
[RYI]   [Prophet] 완료  첫값=1.39e+09 (메모리: 1555.7 MB)
[RYI]   [LSTM] 시작  (메모리: 1555.7 MB)
[메모리] forecast_lstm 실행 전: 1555.71 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1555.73 MB (변화: +0.03 MB)
[RYI]   [LSTM] 완료  첫값=1.24e+09 (메모리: 1555.7 MB)
[RYI]   [Theta] 시작  (메모리: 1555.7 MB)
[메모리] forecast_theta 실행 전: 1555.73 MB
[메모리] forecast_theta 실행 후: 1555.73 MB (변화: +0.00 MB)
[RYI]   [Theta] 완료  첫값=1.11e+09 (메모리: 1555.7 MB)
[RYI]   [DB] 88행 저장 완료
[PROGRESS] [ 113/500] ( 22.6%)  >>  SCSC
[SCSC]   40분기 | 2016-03-31 ~ 2025-12-31
[SCSC]   [SARIMA] 시작  (메모리: 1555.7 MB)
[메모리] forecast_sarima 실행 전: 1555.74 MB
[메모리] find_best_sarima_params 실행 전: 1555.74 MB
[메모리] find_best_sarima_params 실행 후: 1555.74 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1555.74 MB (변화: +0.00 MB)
[SCSC]   [SARIMA] 완료  첫값=7.58e+08 (메모리: 1555.7 MB)
[SCSC]   [ETS] 시작  (메모리: 1555.7 MB)
[메모리] forecast_ets 실행 전: 1555.74 MB
[메모리] forecast_ets 실행 후: 1555.74 MB (변화: +0.00 MB)
[SCSC]   [ETS] 완료  첫값=6.85e+08 (메모리: 1555.7 MB)
[SCSC]   [Prophet] 시작  (메모리: 1555.7 MB)

10:56:29 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1555.74 MB

10:56:29 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1555.77 MB (변화: +0.02 MB)
[SCSC]   [Prophet] 완료  첫값=7.89e+08 (메모리: 1555.8 MB)
[SCSC]   [LSTM] 시작  (메모리: 1555.8 MB)
[메모리] forecast_lstm 실행 전: 1555.77 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1555.73 MB (변화: -0.03 MB)
[SCSC]   [LSTM] 완료  첫값=8.13e+08 (메모리: 1555.7 MB)
[SCSC]   [Theta] 시작  (메모리: 1555.7 MB)
[메모리] forecast_theta 실행 전: 1555.73 MB
[메모리] forecast_theta 실행 후: 1555.73 MB (변화: +0.00 MB)
[SCSC]   [Theta] 완료  첫값=7.60e+08 (메모리: 1555.7 MB)
[SCSC]   [DB] 88행 저장 완료
[PROGRESS] [ 114/500] ( 22.8%)  >>  CLB
[CLB]   40분기 | 2016-03-31 ~ 2025-12-31
[CLB]   [SARIMA] 시작  (메모리: 1555.7 MB)
[메모리] forecast_sarima 실행 전: 1555.74 MB
[메모리] find_best_sarima_params 실행 전: 1555.74 MB
[메모리] find_best_sarima_params 실행 후: 1555.74 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1555.74 MB (변화: +0.00 MB)
[CLB]   [SARIMA] 완료  첫값=1.38e+08 (메모리: 1555.7 MB)
[CLB]   [ETS] 시작  (메모리: 1555.7 MB)
[메모리] forecast_ets 실행 전: 1555.74 MB
[메모리] forecast_ets 실행 후: 1555.75 MB (변화: +0.01 MB)
[CLB]   [ETS] 완료  첫값=1.36e+08 (메모리: 1555.8 MB)
[CLB]   [Prophet] 시작  (메모리: 1555.8 MB)

10:56:48 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1555.75 MB

10:56:48 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1555.78 MB (변화: +0.03 MB)
[CLB]   [Prophet] 완료  첫값=1.17e+08 (메모리: 1555.8 MB)
[CLB]   [LSTM] 시작  (메모리: 1555.8 MB)
[메모리] forecast_lstm 실행 전: 1555.78 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1556.68 MB (변화: +0.90 MB)
[CLB]   [LSTM] 완료  첫값=1.29e+08 (메모리: 1556.7 MB)
[CLB]   [Theta] 시작  (메모리: 1556.7 MB)
[메모리] forecast_theta 실행 전: 1556.68 MB
[메모리] forecast_theta 실행 후: 1556.68 MB (변화: +0.00 MB)
[CLB]   [Theta] 완료  첫값=1.36e+08 (메모리: 1556.7 MB)
[CLB]   [DB] 88행 저장 완료
[PROGRESS] [ 115/500] ( 23.0%)  >>  EPC
[EPC]   40분기 | 2016-03-31 ~ 2025-12-31
[EPC]   [SARIMA] 시작  (메모리: 1556.7 MB)
[메모리] forecast_sarima 실행 전: 1556.68 MB
[메모리] find_best_sarima_params 실행 전: 1556.68 MB
[메모리] find_best_sarima_params 실행 후: 1556.68 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1556.68 MB (변화: +0.00 MB)
[EPC]   [SARIMA] 완료  첫값=4.96e+08 (메모리: 1556.7 MB)
[EPC]   [ETS] 시작  (메모리: 1556.7 MB)
[메모리] forecast_ets 실행 전: 1556.68 MB
[메모리] forecast_ets 실행 후: 1556.68 MB (변화: +0.00 MB)
[EPC]   [ETS] 완료  첫값=5.44e+08 (메모리: 1556.7 MB)
[EPC]   [Prophet] 시작  (메모리: 1556.7 MB)

10:57:08 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1556.68 MB

10:57:09 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1556.71 MB (변화: +0.03 MB)
[EPC]   [Prophet] 완료  첫값=5.29e+08 (메모리: 1556.7 MB)
[EPC]   [LSTM] 시작  (메모리: 1556.7 MB)
[메모리] forecast_lstm 실행 전: 1556.71 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1556.56 MB (변화: -0.15 MB)
[EPC]   [LSTM] 완료  첫값=5.41e+08 (메모리: 1556.6 MB)
[EPC]   [Theta] 시작  (메모리: 1556.6 MB)
[메모리] forecast_theta 실행 전: 1556.56 MB
[메모리] forecast_theta 실행 후: 1556.56 MB (변화: +0.00 MB)
[EPC]   [Theta] 완료  첫값=5.44e+08 (메모리: 1556.6 MB)
[EPC]   [DB] 88행 저장 완료
[PROGRESS] [ 116/500] ( 23.2%)  >>  IART
[IART]   40분기 | 2016-03-31 ~ 2025-12-31
[IART]   [SARIMA] 시작  (메모리: 1556.6 MB)
[메모리] forecast_sarima 실행 전: 1556.56 MB
[메모리] find_best_sarima_params 실행 전: 1556.56 MB
[메모리] find_best_sarima_params 실행 후: 1556.56 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1556.56 MB (변화: +0.00 MB)
[IART]   [SARIMA] 완료  첫값=4.31e+08 (메모리: 1556.6 MB)
[IART]   [ETS] 시작  (메모리: 1556.6 MB)
[메모리] forecast_ets 실행 전: 1556.56 MB
[메모리] forecast_ets 실행 후: 1556.57 MB (변화: +0.01 MB)
[IART]   [ETS] 완료  첫값=4.09e+08 (메모리: 1556.6 MB)
[IART]   [Prophet] 시작  (메모리: 1556.6 MB)

10:57:24 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1556.57 MB

10:57:24 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1556.59 MB (변화: +0.03 MB)
[IART]   [Prophet] 완료  첫값=4.35e+08 (메모리: 1556.6 MB)
[IART]   [LSTM] 시작  (메모리: 1556.6 MB)
[메모리] forecast_lstm 실행 전: 1556.59 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1557.54 MB (변화: +0.95 MB)
[IART]   [LSTM] 완료  첫값=3.92e+08 (메모리: 1557.5 MB)
[IART]   [Theta] 시작  (메모리: 1557.5 MB)
[메모리] forecast_theta 실행 전: 1557.54 MB
[메모리] forecast_theta 실행 후: 1557.54 MB (변화: +0.00 MB)
[IART]   [Theta] 완료  첫값=4.03e+08 (메모리: 1557.5 MB)
[IART]   [DB] 88행 저장 완료
[PROGRESS] [ 117/500] ( 23.4%)  >>  TMST
[TMST]   40분기 | 2016-03-31 ~ 2025-12-31
[TMST]   [SARIMA] 시작  (메모리: 1557.5 MB)
[메모리] forecast_sarima 실행 전: 1557.54 MB
[메모리] find_best_sarima_params 실행 전: 1557.54 MB
[메모리] find_best_sarima_params 실행 후: 1557.54 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1557.54 MB (변화: +0.00 MB)
[TMST]   [SARIMA] 완료  첫값=2.67e+08 (메모리: 1557.5 MB)
[TMST]   [ETS] 시작  (메모리: 1557.5 MB)
[메모리] forecast_ets 실행 전: 1557.54 MB
[메모리] forecast_ets 실행 후: 1557.54 MB (변화: +0.00 MB)
[TMST]   [ETS] 완료  첫값=3.05e+08 (메모리: 1557.5 MB)
[TMST]   [Prophet] 시작  (메모리: 1557.5 MB)

10:57:38 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1557.54 MB

10:57:38 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1557.57 MB (변화: +0.03 MB)
[TMST]   [Prophet] 완료  첫값=3.04e+08 (메모리: 1557.6 MB)
[TMST]   [LSTM] 시작  (메모리: 1557.6 MB)
[메모리] forecast_lstm 실행 전: 1557.57 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1557.56 MB (변화: -0.01 MB)
[TMST]   [LSTM] 완료  첫값=2.77e+08 (메모리: 1557.6 MB)
[TMST]   [Theta] 시작  (메모리: 1557.6 MB)
[메모리] forecast_theta 실행 전: 1557.56 MB
[메모리] forecast_theta 실행 후: 1557.56 MB (변화: +0.00 MB)
[TMST]   [Theta] 완료  첫값=2.69e+08 (메모리: 1557.6 MB)
[TMST]   [DB] 88행 저장 완료
[PROGRESS] [ 118/500] ( 23.6%)  >>  TELL
[TELL]   40분기 | 2014-09-30 ~ 2024-06-30
[TELL]   [SARIMA] 시작  (메모리: 1557.6 MB)
[메모리] forecast_sarima 실행 전: 1557.56 MB
[메모리] find_best_sarima_params 실행 전: 1557.56 MB
[메모리] find_best_sarima_params 실행 후: 1557.56 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1557.56 MB (변화: +0.00 MB)
[TELL]   [SARIMA] 완료  첫값=2.64e+07 (메모리: 1557.6 MB)
[TELL]   [ETS] 시작  (메모리: 1557.6 MB)
[메모리] forecast_ets 실행 전: 1557.56 MB
[메모리] forecast_ets 실행 후: 1557.57 MB (변화: +0.01 MB)
[TELL]   [ETS] 완료  첫값=1.46e+07 (메모리: 1557.6 MB)
[TELL]   [Prophet] 시작  (메모리: 1557.6 MB)

10:57:51 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1557.57 MB

10:57:51 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1557.57 MB (변화: +0.00 MB)
[TELL]   [Prophet] 완료  첫값=5.11e+07 (메모리: 1557.6 MB)
[TELL]   [LSTM] 시작  (메모리: 1557.6 MB)
[메모리] forecast_lstm 실행 전: 1557.57 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1557.55 MB (변화: -0.03 MB)
[TELL]   [LSTM] 완료  첫값=4.44e+07 (메모리: 1557.5 MB)
[TELL]   [Theta] 시작  (메모리: 1557.5 MB)
[메모리] forecast_theta 실행 전: 1557.55 MB
[메모리] forecast_theta 실행 후: 1557.55 MB (변화: +0.00 MB)
[TELL]   [Theta] 완료  첫값=1.79e+07 (메모리: 1557.5 MB)
[TELL]   [DB] 88행 저장 완료
[PROGRESS] [ 119/500] ( 23.8%)  >>  LIND
[LIND] [NEG-SKIP] [LIND] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2020, 6, 30)])
[PROGRESS] [ 120/500] ( 24.0%)  >>  DJCO
[DJCO]   40분기 | 2016-03-31 ~ 2025-12-31
[DJCO]   [SARIMA] 시작  (메모리: 1557.5 MB)
[메모리] forecast_sarima 실행 전: 1557.55 MB
[메모리] find_best_sarima_params 실행 전: 1557.55 MB
[메모리] find_best_sarima_params 실행 후: 1557.55 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1557.55 MB (변화: +0.00 MB)
[DJCO]   [SARIMA] 완료  첫값=2.02e+07 (메모리: 1557.5 MB)
[DJCO]   [ETS] 시작  (메모리: 1557.5 MB)
[메모리] forecast_ets 실행 전: 1557.55 MB
[메모리] forecast_ets 실행 후: 1557.55 MB (변화: +0.00 MB)
[DJCO]   [ETS] 완료  첫값=2.22e+07 (메모리: 1557.6 MB)
[DJCO]   [Prophet] 시작  (메모리: 1557.6 MB)

10:58:11 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1557.55 MB

10:58:11 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1557.59 MB (변화: +0.04 MB)
[DJCO]   [Prophet] 완료  첫값=2.03e+07 (메모리: 1557.6 MB)
[DJCO]   [LSTM] 시작  (메모리: 1557.6 MB)
[메모리] forecast_lstm 실행 전: 1557.59 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1557.55 MB (변화: -0.03 MB)
[DJCO]   [LSTM] 완료  첫값=2.16e+07 (메모리: 1557.6 MB)
[DJCO]   [Theta] 시작  (메모리: 1557.6 MB)
[메모리] forecast_theta 실행 전: 1557.55 MB
[메모리] forecast_theta 실행 후: 1557.55 MB (변화: +0.00 MB)
[DJCO]   [Theta] 완료  첫값=2.18e+07 (메모리: 1557.6 MB)
[DJCO]   [DB] 88행 저장 완료
[PROGRESS] [ 121/500] ( 24.2%)  >>  PCRX
[PCRX]   40분기 | 2016-03-31 ~ 2025-12-31
[PCRX]   [SARIMA] 시작  (메모리: 1557.6 MB)
[메모리] forecast_sarima 실행 전: 1557.55 MB
[메모리] find_best_sarima_params 실행 전: 1557.55 MB
[메모리] find_best_sarima_params 실행 후: 1557.55 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1557.55 MB (변화: +0.00 MB)
[PCRX]   [SARIMA] 완료  첫값=1.99e+08 (메모리: 1557.6 MB)
[PCRX]   [ETS] 시작  (메모리: 1557.6 MB)
[메모리] forecast_ets 실행 전: 1557.55 MB
[메모리] forecast_ets 실행 후: 1557.56 MB (변화: +0.00 MB)
[PCRX]   [ETS] 완료  첫값=1.88e+08 (메모리: 1557.6 MB)
[PCRX]   [Prophet] 시작  (메모리: 1557.6 MB)

10:58:26 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1557.56 MB

10:58:26 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1557.57 MB (변화: +0.01 MB)
[PCRX]   [Prophet] 완료  첫값=2.01e+08 (메모리: 1557.6 MB)
[PCRX]   [LSTM] 시작  (메모리: 1557.6 MB)
[메모리] forecast_lstm 실행 전: 1557.57 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1557.55 MB (변화: -0.02 MB)
[PCRX]   [LSTM] 완료  첫값=1.83e+08 (메모리: 1557.6 MB)
[PCRX]   [Theta] 시작  (메모리: 1557.6 MB)
[메모리] forecast_theta 실행 전: 1557.55 MB
[메모리] forecast_theta 실행 후: 1557.55 MB (변화: +0.00 MB)
[PCRX]   [Theta] 완료  첫값=1.82e+08 (메모리: 1557.6 MB)
[PCRX]   [DB] 88행 저장 완료
[PROGRESS] [ 122/500] ( 24.4%)  >>  GCI
[GCI]   40분기 | 2016-03-27 ~ 2025-12-31
[GCI]   [SARIMA] 시작  (메모리: 1557.6 MB)
[메모리] forecast_sarima 실행 전: 1557.55 MB
[메모리] find_best_sarima_params 실행 전: 1557.55 MB
[메모리] find_best_sarima_params 실행 후: 1557.55 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1557.55 MB (변화: +0.00 MB)
[GCI]   [SARIMA] 완료  첫값=5.95e+08 (메모리: 1557.6 MB)
[GCI]   [ETS] 시작  (메모리: 1557.6 MB)
[메모리] forecast_ets 실행 전: 1557.55 MB
[메모리] forecast_ets 실행 후: 1557.56 MB (변화: +0.00 MB)
[GCI]   [ETS] 완료  첫값=5.57e+08 (메모리: 1557.6 MB)
[GCI]   [Prophet] 시작  (메모리: 1557.6 MB)

10:58:42 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1557.56 MB

10:58:42 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1557.59 MB (변화: +0.03 MB)
[GCI]   [Prophet] 완료  첫값=7.74e+08 (메모리: 1557.6 MB)
[GCI]   [LSTM] 시작  (메모리: 1557.6 MB)
[메모리] forecast_lstm 실행 전: 1557.59 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1557.62 MB (변화: +0.04 MB)
[GCI]   [LSTM] 완료  첫값=6.48e+08 (메모리: 1557.6 MB)
[GCI]   [Theta] 시작  (메모리: 1557.6 MB)
[메모리] forecast_theta 실행 전: 1557.62 MB
[메모리] forecast_theta 실행 후: 1557.62 MB (변화: +0.00 MB)
[GCI]   [Theta] 완료  첫값=5.53e+08 (메모리: 1557.6 MB)
[GCI]   [DB] 88행 저장 완료
[PROGRESS] [ 123/500] ( 24.6%)  >>  ITRN
[ITRN]   40분기 | 2016-03-31 ~ 2025-12-31
[ITRN]   [SARIMA] 시작  (메모리: 1557.6 MB)
[메모리] forecast_sarima 실행 전: 1557.62 MB
[메모리] find_best_sarima_params 실행 전: 1557.62 MB
[메모리] find_best_sarima_params 실행 후: 1557.62 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1557.62 MB (변화: +0.00 MB)
[ITRN]   [SARIMA] 완료  첫값=9.46e+07 (메모리: 1557.6 MB)
[ITRN]   [ETS] 시작  (메모리: 1557.6 MB)
[메모리] forecast_ets 실행 전: 1557.62 MB
[메모리] forecast_ets 실행 후: 1557.63 MB (변화: +0.00 MB)
[ITRN]   [ETS] 완료  첫값=9.73e+07 (메모리: 1557.6 MB)
[ITRN]   [Prophet] 시작  (메모리: 1557.6 MB)

10:59:02 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1557.63 MB

10:59:02 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1556.64 MB (변화: -0.98 MB)
[ITRN]   [Prophet] 완료  첫값=8.94e+07 (메모리: 1556.6 MB)
[ITRN]   [LSTM] 시작  (메모리: 1556.6 MB)
[메모리] forecast_lstm 실행 전: 1556.64 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1557.83 MB (변화: +1.18 MB)
[ITRN]   [LSTM] 완료  첫값=9.85e+07 (메모리: 1557.8 MB)
[ITRN]   [Theta] 시작  (메모리: 1557.8 MB)
[메모리] forecast_theta 실행 전: 1557.83 MB
[메모리] forecast_theta 실행 후: 1557.83 MB (변화: +0.00 MB)
[ITRN]   [Theta] 완료  첫값=9.69e+07 (메모리: 1557.8 MB)
[ITRN]   [DB] 88행 저장 완료
[PROGRESS] [ 124/500] ( 24.8%)  >>  VERB
[VERB] [NEG-SKIP] [VERB] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2016, 12, 31)])
[PROGRESS] [ 125/500] ( 25.0%)  >>  GES
[GES]   40분기 | 2016-01-30 ~ 2025-11-01
[GES]   [SARIMA] 시작  (메모리: 1557.8 MB)
[메모리] forecast_sarima 실행 전: 1557.83 MB
[메모리] find_best_sarima_params 실행 전: 1557.83 MB
[메모리] find_best_sarima_params 실행 후: 1557.83 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1557.83 MB (변화: +0.00 MB)
[GES]   [SARIMA] 완료  첫값=9.80e+08 (메모리: 1557.8 MB)
[GES]   [ETS] 시작  (메모리: 1557.8 MB)
[메모리] forecast_ets 실행 전: 1557.83 MB
[메모리] forecast_ets 실행 후: 1557.84 MB (변화: +0.00 MB)
[GES]   [ETS] 완료  첫값=1.02e+09 (메모리: 1557.8 MB)
[GES]   [Prophet] 시작  (메모리: 1557.8 MB)

10:59:18 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1557.84 MB

10:59:18 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1557.86 MB (변화: +0.02 MB)
[GES]   [Prophet] 완료  첫값=7.43e+08 (메모리: 1557.9 MB)
[GES]   [LSTM] 시작  (메모리: 1557.9 MB)
[메모리] forecast_lstm 실행 전: 1557.86 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1558.05 MB (변화: +0.19 MB)
[GES]   [LSTM] 완료  첫값=7.04e+08 (메모리: 1558.1 MB)
[GES]   [Theta] 시작  (메모리: 1558.1 MB)
[메모리] forecast_theta 실행 전: 1558.05 MB
[메모리] forecast_theta 실행 후: 1558.05 MB (변화: +0.00 MB)
[GES]   [Theta] 완료  첫값=1.02e+09 (메모리: 1558.1 MB)
[GES]   [DB] 88행 저장 완료
[PROGRESS] [ 126/500] ( 25.2%)  >>  GNK
[GNK]   40분기 | 2016-03-31 ~ 2025-12-31
[GNK]   [SARIMA] 시작  (메모리: 1558.1 MB)
[메모리] forecast_sarima 실행 전: 1558.05 MB
[메모리] find_best_sarima_params 실행 전: 1558.05 MB
[메모리] find_best_sarima_params 실행 후: 1558.05 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1558.05 MB (변화: +0.00 MB)
[GNK]   [SARIMA] 완료  첫값=9.26e+07 (메모리: 1558.1 MB)
[GNK]   [ETS] 시작  (메모리: 1558.1 MB)
[메모리] forecast_ets 실행 전: 1558.05 MB
[메모리] forecast_ets 실행 후: 1558.05 MB (변화: +0.00 MB)
[GNK]   [ETS] 완료  첫값=9.12e+07 (메모리: 1558.1 MB)
[GNK]   [Prophet] 시작  (메모리: 1558.1 MB)

10:59:33 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1558.05 MB

10:59:33 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1558.08 MB (변화: +0.02 MB)
[GNK]   [Prophet] 완료  첫값=1.25e+08 (메모리: 1558.1 MB)
[GNK]   [LSTM] 시작  (메모리: 1558.1 MB)
[메모리] forecast_lstm 실행 전: 1558.08 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1557.93 MB (변화: -0.15 MB)
[GNK]   [LSTM] 완료  첫값=1.11e+08 (메모리: 1557.9 MB)
[GNK]   [Theta] 시작  (메모리: 1557.9 MB)
[메모리] forecast_theta 실행 전: 1557.93 MB
[메모리] forecast_theta 실행 후: 1557.93 MB (변화: +0.00 MB)
[GNK]   [Theta] 완료  첫값=9.31e+07 (메모리: 1557.9 MB)
[GNK]   [DB] 88행 저장 완료
[PROGRESS] [ 127/500] ( 25.4%)  >>  GERN
[GERN]   40분기 | 2016-03-31 ~ 2025-12-31
[GERN]   [SARIMA] 시작  (메모리: 1557.9 MB)
[메모리] forecast_sarima 실행 전: 1557.93 MB
[메모리] find_best_sarima_params 실행 전: 1557.93 MB
[메모리] find_best_sarima_params 실행 후: 1557.93 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1557.93 MB (변화: +0.00 MB)
[GERN]   [SARIMA] 완료  첫값=2.31e+07 (메모리: 1557.9 MB)
[GERN]   [ETS] 시작  (메모리: 1557.9 MB)
[메모리] forecast_ets 실행 전: 1557.93 MB
[메모리] forecast_ets 실행 후: 1557.93 MB (변화: +0.00 MB)
[GERN]   [ETS] 완료  첫값=4.18e+07 (메모리: 1557.9 MB)
[GERN]   [Prophet] 시작  (메모리: 1557.9 MB)

10:59:46 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1557.93 MB

10:59:46 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1557.97 MB (변화: +0.04 MB)
[GERN]   [Prophet] 완료  첫값=2.36e+07 (메모리: 1558.0 MB)
[GERN]   [LSTM] 시작  (메모리: 1558.0 MB)
[메모리] forecast_lstm 실행 전: 1557.97 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1558.60 MB (변화: +0.63 MB)
[GERN]   [LSTM] 완료  첫값=7.92e+07 (메모리: 1558.6 MB)
[GERN]   [Theta] 시작  (메모리: 1558.6 MB)
[메모리] forecast_theta 실행 전: 1558.60 MB
[메모리] forecast_theta 실행 후: 1558.60 MB (변화: +0.00 MB)
[GERN]   [Theta] 완료  첫값=5.04e+07 (메모리: 1558.6 MB)
[GERN]   [DB] 88행 저장 완료
[PROGRESS] [ 128/500] ( 25.6%)  >>  HNRG
[HNRG]   40분기 | 2016-03-31 ~ 2025-12-31
[HNRG]   [SARIMA] 시작  (메모리: 1558.6 MB)
[메모리] forecast_sarima 실행 전: 1558.61 MB
[메모리] find_best_sarima_params 실행 전: 1558.61 MB
[메모리] find_best_sarima_params 실행 후: 1558.61 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1558.61 MB (변화: +0.00 MB)
[HNRG]   [SARIMA] 완료  첫값=1.02e+08 (메모리: 1558.6 MB)
[HNRG]   [ETS] 시작  (메모리: 1558.6 MB)
[메모리] forecast_ets 실행 전: 1558.61 MB
[메모리] forecast_ets 실행 후: 1558.62 MB (변화: +0.01 MB)
[HNRG]   [ETS] 완료  첫값=9.60e+07 (메모리: 1558.6 MB)
[HNRG]   [Prophet] 시작  (메모리: 1558.6 MB)

11:00:04 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1558.62 MB

11:00:04 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1558.65 MB (변화: +0.04 MB)
[HNRG]   [Prophet] 완료  첫값=1.23e+08 (메모리: 1558.7 MB)
[HNRG]   [LSTM] 시작  (메모리: 1558.7 MB)
[메모리] forecast_lstm 실행 전: 1558.65 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1558.29 MB (변화: -0.36 MB)
[HNRG]   [LSTM] 완료  첫값=1.11e+08 (메모리: 1558.3 MB)
[HNRG]   [Theta] 시작  (메모리: 1558.3 MB)
[메모리] forecast_theta 실행 전: 1558.29 MB
[메모리] forecast_theta 실행 후: 1558.29 MB (변화: +0.00 MB)
[HNRG]   [Theta] 완료  첫값=1.05e+08 (메모리: 1558.3 MB)
[HNRG]   [DB] 88행 저장 완료
[PROGRESS] [ 129/500] ( 25.8%)  >>  PLOW
[PLOW]   40분기 | 2016-03-31 ~ 2025-12-31
[PLOW]   [SARIMA] 시작  (메모리: 1558.3 MB)
[메모리] forecast_sarima 실행 전: 1558.29 MB
[메모리] find_best_sarima_params 실행 전: 1558.29 MB
[메모리] find_best_sarima_params 실행 후: 1558.29 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1558.29 MB (변화: +0.00 MB)
[PLOW]   [SARIMA] 완료  첫값=1.05e+08 (메모리: 1558.3 MB)
[PLOW]   [ETS] 시작  (메모리: 1558.3 MB)
[메모리] forecast_ets 실행 전: 1558.29 MB
[메모리] forecast_ets 실행 후: 1558.30 MB (변화: +0.00 MB)
[PLOW]   [ETS] 완료  첫값=1.05e+08 (메모리: 1558.3 MB)
[PLOW]   [Prophet] 시작  (메모리: 1558.3 MB)

11:00:24 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1558.30 MB

11:00:25 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1558.30 MB (변화: +0.01 MB)
[PLOW]   [Prophet] 완료  첫값=1.63e+08 (메모리: 1558.3 MB)
[PLOW]   [LSTM] 시작  (메모리: 1558.3 MB)
[메모리] forecast_lstm 실행 전: 1558.30 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1558.15 MB (변화: -0.16 MB)
[PLOW]   [LSTM] 완료  첫값=1.41e+08 (메모리: 1558.1 MB)
[PLOW]   [Theta] 시작  (메모리: 1558.1 MB)
[메모리] forecast_theta 실행 전: 1558.15 MB
[메모리] forecast_theta 실행 후: 1558.15 MB (변화: +0.00 MB)
[PLOW]   [Theta] 완료  첫값=1.09e+08 (메모리: 1558.1 MB)
[PLOW]   [DB] 88행 저장 완료
[PROGRESS] [ 130/500] ( 26.0%)  >>  NPK
[NPK]   40분기 | 2016-04-03 ~ 2025-12-31
[NPK]   [SARIMA] 시작  (메모리: 1558.1 MB)
[메모리] forecast_sarima 실행 전: 1558.15 MB
[메모리] find_best_sarima_params 실행 전: 1558.15 MB
[메모리] find_best_sarima_params 실행 후: 1558.15 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1558.15 MB (변화: +0.00 MB)
[NPK]   [SARIMA] 완료  첫값=1.13e+08 (메모리: 1558.1 MB)
[NPK]   [ETS] 시작  (메모리: 1558.1 MB)
[메모리] forecast_ets 실행 전: 1558.15 MB
[메모리] forecast_ets 실행 후: 1558.16 MB (변화: +0.01 MB)
[NPK]   [ETS] 완료  첫값=1.15e+08 (메모리: 1558.2 MB)
[NPK]   [Prophet] 시작  (메모리: 1558.2 MB)

11:00:40 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1558.16 MB

11:00:40 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1558.42 MB (변화: +0.26 MB)
[NPK]   [Prophet] 완료  첫값=1.06e+08 (메모리: 1558.4 MB)
[NPK]   [LSTM] 시작  (메모리: 1558.4 MB)
[메모리] forecast_lstm 실행 전: 1558.42 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1558.02 MB (변화: -0.39 MB)
[NPK]   [LSTM] 완료  첫값=1.02e+08 (메모리: 1558.0 MB)
[NPK]   [Theta] 시작  (메모리: 1558.0 MB)
[메모리] forecast_theta 실행 전: 1558.02 MB
[메모리] forecast_theta 실행 후: 1558.02 MB (변화: +0.00 MB)
[NPK]   [Theta] 완료  첫값=1.14e+08 (메모리: 1558.0 MB)
[NPK]   [DB] 88행 저장 완료
[PROGRESS] [ 131/500] ( 26.2%)  >>  JBSS
[JBSS]   40분기 | 2016-03-24 ~ 2025-12-25
[JBSS]   [SARIMA] 시작  (메모리: 1558.0 MB)
[메모리] forecast_sarima 실행 전: 1558.02 MB
[메모리] find_best_sarima_params 실행 전: 1558.02 MB
[메모리] find_best_sarima_params 실행 후: 1558.50 MB (변화: +0.47 MB)
[메모리] find_best_sarima_params 실행 전: 1558.50 MB
[메모리] find_best_sarima_params 실행 후: 1558.53 MB (변화: +0.03 MB)
[메모리] forecast_sarima 실행 후: 1558.53 MB (변화: +0.50 MB)
[JBSS]   [SARIMA] 오류응답: {'error': 'SARIMA 적합 실패 (발산 포함)'}
[JBSS]   [ETS] 시작  (메모리: 1558.5 MB)
[메모리] forecast_ets 실행 전: 1558.53 MB
[메모리] forecast_ets 실행 후: 1558.53 MB (변화: +0.00 MB)
[JBSS]   [ETS] 완료  첫값=6.35e+08 (메모리: 1558.5 MB)
[JBSS]   [Prophet] 시작  (메모리: 1558.5 MB)

11:01:13 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1558.53 MB

11:01:13 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1558.59 MB (변화: +0.06 MB)
[JBSS]   [Prophet] 완료  첫값=-4.65e+07 (메모리: 1558.6 MB)
[JBSS]   [LSTM] 시작  (메모리: 1558.6 MB)
[메모리] forecast_lstm 실행 전: 1558.59 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1559.38 MB (변화: +0.79 MB)
[JBSS]   [LSTM] 완료  첫값=2.74e+08 (메모리: 1559.4 MB)
[JBSS]   [Theta] 시작  (메모리: 1559.4 MB)
[메모리] forecast_theta 실행 전: 1559.38 MB
[메모리] forecast_theta 실행 후: 1559.38 MB (변화: +0.00 MB)
[JBSS]   [Theta] 완료  첫값=2.92e+08 (메모리: 1559.4 MB)
[JBSS]   [DB] 80행 저장 완료
[PROGRESS] [ 132/500] ( 26.4%)  >>  CAPL
[CAPL]   40분기 | 2016-03-31 ~ 2025-12-31
[CAPL]   [SARIMA] 시작  (메모리: 1559.4 MB)
[메모리] forecast_sarima 실행 전: 1559.39 MB
[메모리] find_best_sarima_params 실행 전: 1559.39 MB
[메모리] find_best_sarima_params 실행 후: 1559.39 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1559.39 MB (변화: +0.00 MB)
[CAPL]   [SARIMA] 완료  첫값=2.69e+09 (메모리: 1559.4 MB)
[CAPL]   [ETS] 시작  (메모리: 1559.4 MB)
[메모리] forecast_ets 실행 전: 1559.39 MB
[메모리] forecast_ets 실행 후: 1559.39 MB (변화: +0.00 MB)
[CAPL]   [ETS] 완료  첫값=2.53e+09 (메모리: 1559.4 MB)
[CAPL]   [Prophet] 시작  (메모리: 1559.4 MB)

11:01:29 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1559.39 MB

11:01:29 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1559.42 MB (변화: +0.03 MB)
[CAPL]   [Prophet] 완료  첫값=1.35e+09 (메모리: 1559.4 MB)
[CAPL]   [LSTM] 시작  (메모리: 1559.4 MB)
[메모리] forecast_lstm 실행 전: 1559.42 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1559.39 MB (변화: -0.03 MB)
[CAPL]   [LSTM] 완료  첫값=1.12e+09 (메모리: 1559.4 MB)
[CAPL]   [Theta] 시작  (메모리: 1559.4 MB)
[메모리] forecast_theta 실행 전: 1559.39 MB
[메모리] forecast_theta 실행 후: 1559.39 MB (변화: +0.00 MB)
[CAPL]   [Theta] 완료  첫값=2.50e+09 (메모리: 1559.4 MB)
[CAPL]   [DB] 88행 저장 완료
[PROGRESS] [ 133/500] ( 26.6%)  >>  SMP
[SMP]   40분기 | 2016-03-31 ~ 2025-12-31
[SMP]   [SARIMA] 시작  (메모리: 1559.4 MB)
[메모리] forecast_sarima 실행 전: 1559.39 MB
[메모리] find_best_sarima_params 실행 전: 1559.39 MB
[메모리] find_best_sarima_params 실행 후: 1559.39 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1559.39 MB (변화: +0.00 MB)
[SMP]   [SARIMA] 완료  첫값=4.12e+08 (메모리: 1559.4 MB)
[SMP]   [ETS] 시작  (메모리: 1559.4 MB)
[메모리] forecast_ets 실행 전: 1559.39 MB
[메모리] forecast_ets 실행 후: 1559.40 MB (변화: +0.01 MB)
[SMP]   [ETS] 완료  첫값=4.33e+08 (메모리: 1559.4 MB)
[SMP]   [Prophet] 시작  (메모리: 1559.4 MB)

11:01:45 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1559.40 MB

11:01:45 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1559.43 MB (변화: +0.03 MB)
[SMP]   [Prophet] 완료  첫값=4.07e+08 (메모리: 1559.4 MB)
[SMP]   [LSTM] 시작  (메모리: 1559.4 MB)
[메모리] forecast_lstm 실행 전: 1559.43 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1559.47 MB (변화: +0.04 MB)
[SMP]   [LSTM] 완료  첫값=4.62e+08 (메모리: 1559.5 MB)
[SMP]   [Theta] 시작  (메모리: 1559.5 MB)
[메모리] forecast_theta 실행 전: 1559.47 MB
[메모리] forecast_theta 실행 후: 1559.47 MB (변화: +0.00 MB)
[SMP]   [Theta] 완료  첫값=4.27e+08 (메모리: 1559.5 MB)
[SMP]   [DB] 88행 저장 완료
[PROGRESS] [ 134/500] ( 26.8%)  >>  AMWD
[AMWD]   40분기 | 2016-04-30 ~ 2026-01-31
[AMWD]   [SARIMA] 시작  (메모리: 1559.5 MB)
[메모리] forecast_sarima 실행 전: 1559.47 MB
[메모리] find_best_sarima_params 실행 전: 1559.47 MB
[메모리] find_best_sarima_params 실행 후: 1559.47 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1559.47 MB (변화: +0.00 MB)
[AMWD]   [SARIMA] 완료  첫값=3.43e+08 (메모리: 1559.5 MB)
[AMWD]   [ETS] 시작  (메모리: 1559.5 MB)
[메모리] forecast_ets 실행 전: 1559.47 MB
[메모리] forecast_ets 실행 후: 1559.47 MB (변화: +0.00 MB)
[AMWD]   [ETS] 완료  첫값=3.37e+08 (메모리: 1559.5 MB)
[AMWD]   [Prophet] 시작  (메모리: 1559.5 MB)

11:02:06 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1559.47 MB

11:02:06 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1559.48 MB (변화: +0.02 MB)
[AMWD]   [Prophet] 완료  첫값=4.93e+08 (메모리: 1559.5 MB)
[AMWD]   [LSTM] 시작  (메모리: 1559.5 MB)
[메모리] forecast_lstm 실행 전: 1559.48 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1558.26 MB (변화: -1.22 MB)
[AMWD]   [LSTM] 완료  첫값=4.76e+08 (메모리: 1558.3 MB)
[AMWD]   [Theta] 시작  (메모리: 1558.3 MB)
[메모리] forecast_theta 실행 전: 1558.26 MB
[메모리] forecast_theta 실행 후: 1558.26 MB (변화: +0.00 MB)
[AMWD]   [Theta] 완료  첫값=3.48e+08 (메모리: 1558.3 MB)
[AMWD]   [DB] 88행 저장 완료
[PROGRESS] [ 135/500] ( 27.0%)  >>  NAT
[NAT]   40분기 | 2016-03-31 ~ 2025-12-31
[NAT]   [SARIMA] 시작  (메모리: 1558.3 MB)
[메모리] forecast_sarima 실행 전: 1558.26 MB
[메모리] find_best_sarima_params 실행 전: 1558.26 MB
[메모리] find_best_sarima_params 실행 후: 1558.26 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1558.26 MB (변화: +0.00 MB)
[NAT]   [SARIMA] 완료  첫값=7.01e+07 (메모리: 1558.3 MB)
[NAT]   [ETS] 시작  (메모리: 1558.3 MB)
[메모리] forecast_ets 실행 전: 1558.26 MB
[메모리] forecast_ets 실행 후: 1558.27 MB (변화: +0.00 MB)
[NAT]   [ETS] 완료  첫값=9.35e+07 (메모리: 1558.3 MB)
[NAT]   [Prophet] 시작  (메모리: 1558.3 MB)

11:02:19 - cmdstanpy - INFO - Chain [1] start processing
11:02:19 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1558.27 MB
[메모리] forecast_prophet 실행 후: 1558.29 MB (변화: +0.02 MB)
[NAT]   [Prophet] 완료  첫값=8.17e+07 (메모리: 1558.3 MB)
[NAT]   [LSTM] 시작  (메모리: 1558.3 MB)
[메모리] forecast_lstm 실행 전: 1558.29 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1558.21 MB (변화: -0.07 MB)
[NAT]   [LSTM] 완료  첫값=8.28e+07 (메모리: 1558.2 MB)
[NAT]   [Theta] 시작  (메모리: 1558.2 MB)
[메모리] forecast_theta 실행 전: 1558.21 MB
[메모리] forecast_theta 실행 후: 1558.21 MB (변화: +0.00 MB)
[NAT]   [Theta] 완료  첫값=8.41e+07 (메모리: 1558.2 MB)
[NAT]   [DB] 88행 저장 완료
[PROGRESS] [ 136/500] ( 27.2%)  >>  NX
[NX]   40분기 | 2016-04-30 ~ 2026-01-31
[NX]   [SARIMA] 시작  (메모리: 1558.2 MB)
[메모리] forecast_sarima 실행 전: 1558.22 MB
[메모리] find_best_sarima_params 실행 전: 1558.22 MB
[메모리] find_best_sarima_params 실행 후: 1558.22 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1558.22 MB (변화: +0.00 MB)
[NX]   [SARIMA] 완료  첫값=4.43e+08 (메모리: 1558.2 MB)
[NX]   [ETS] 시작  (메모리: 1558.2 MB)
[메모리] forecast_ets 실행 전: 1558.22 MB
[메모리] forecast_ets 실행 후: 1558.23 MB (변화: +0.01 MB)
[NX]   [ETS] 완료  첫값=4.50e+08 (메모리: 1558.2 MB)
[NX]   [Prophet] 시작  (메모리: 1558.2 MB)

11:02:34 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1558.23 MB

11:02:34 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1558.27 MB (변화: +0.04 MB)
[NX]   [Prophet] 완료  첫값=3.92e+08 (메모리: 1558.3 MB)
[NX]   [LSTM] 시작  (메모리: 1558.3 MB)
[메모리] forecast_lstm 실행 전: 1558.27 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1559.27 MB (변화: +1.01 MB)
[NX]   [LSTM] 완료  첫값=5.50e+08 (메모리: 1559.3 MB)
[NX]   [Theta] 시작  (메모리: 1559.3 MB)
[메모리] forecast_theta 실행 전: 1559.27 MB
[메모리] forecast_theta 실행 후: 1559.27 MB (변화: +0.00 MB)
[NX]   [Theta] 완료  첫값=4.47e+08 (메모리: 1559.3 MB)
[NX]   [DB] 88행 저장 완료
[PROGRESS] [ 137/500] ( 27.4%)  >>  POET
[POET]   40분기 | 2015-12-31 ~ 2025-09-30
[POET]   [SARIMA] 시작  (메모리: 1559.3 MB)
[메모리] forecast_sarima 실행 전: 1559.30 MB
[메모리] find_best_sarima_params 실행 전: 1559.30 MB
[메모리] find_best_sarima_params 실행 후: 1559.30 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1559.30 MB (변화: +0.00 MB)
[POET]   [SARIMA] 완료  첫값=1.27e+05 (메모리: 1559.3 MB)
[POET]   [ETS] 시작  (메모리: 1559.3 MB)
[메모리] forecast_ets 실행 전: 1559.30 MB
[메모리] forecast_ets 실행 후: 1559.30 MB (변화: +0.01 MB)
[POET]   [ETS] 완료  첫값=3.10e+05 (메모리: 1559.3 MB)
[POET]   [Prophet] 시작  (메모리: 1559.3 MB)

11:02:51 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1559.30 MB

11:02:51 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1559.33 MB (변화: +0.03 MB)
[POET]   [Prophet] 완료  첫값=-3.02e+04 (메모리: 1559.3 MB)
[POET]   [LSTM] 시작  (메모리: 1559.3 MB)
[메모리] forecast_lstm 실행 전: 1559.33 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1559.32 MB (변화: -0.02 MB)
[POET]   [LSTM] 완료  첫값=1.27e+05 (메모리: 1559.3 MB)
[POET]   [Theta] 시작  (메모리: 1559.3 MB)
[메모리] forecast_theta 실행 전: 1559.32 MB
[메모리] forecast_theta 실행 후: 1559.32 MB (변화: +0.00 MB)
[POET]   [Theta] 완료  첫값=2.51e+05 (메모리: 1559.3 MB)
[POET]   [DB] 88행 저장 완료
[PROGRESS] [ 138/500] ( 27.6%)  >>  SCHL
[SCHL]   40분기 | 2016-05-31 ~ 2026-02-28
[SCHL]   [SARIMA] 시작  (메모리: 1559.3 MB)
[메모리] forecast_sarima 실행 전: 1559.32 MB
[메모리] find_best_sarima_params 실행 전: 1559.32 MB
[메모리] find_best_sarima_params 실행 후: 1559.32 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1559.32 MB (변화: +0.00 MB)
[SCHL]   [SARIMA] 완료  첫값=4.99e+08 (메모리: 1559.3 MB)
[SCHL]   [ETS] 시작  (메모리: 1559.3 MB)
[메모리] forecast_ets 실행 전: 1559.32 MB
[메모리] forecast_ets 실행 후: 1559.32 MB (변화: +0.00 MB)
[SCHL]   [ETS] 완료  첫값=4.54e+08 (메모리: 1559.3 MB)
[SCHL]   [Prophet] 시작  (메모리: 1559.3 MB)

11:03:11 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1559.32 MB

11:03:11 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1559.34 MB (변화: +0.02 MB)
[SCHL]   [Prophet] 완료  첫값=3.90e+08 (메모리: 1559.3 MB)
[SCHL]   [LSTM] 시작  (메모리: 1559.3 MB)
[메모리] forecast_lstm 실행 전: 1559.34 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1559.30 MB (변화: -0.04 MB)
[SCHL]   [LSTM] 완료  첫값=3.83e+08 (메모리: 1559.3 MB)
[SCHL]   [Theta] 시작  (메모리: 1559.3 MB)
[메모리] forecast_theta 실행 전: 1559.30 MB
[메모리] forecast_theta 실행 후: 1559.30 MB (변화: +0.00 MB)
[SCHL]   [Theta] 완료  첫값=4.60e+08 (메모리: 1559.3 MB)
[SCHL]   [DB] 88행 저장 완료
[PROGRESS] [ 139/500] ( 27.8%)  >>  FARO
[FARO]   40분기 | 2015-06-27 ~ 2025-03-31
[FARO]   [SARIMA] 시작  (메모리: 1559.3 MB)
[메모리] forecast_sarima 실행 전: 1559.30 MB
[메모리] find_best_sarima_params 실행 전: 1559.30 MB
[메모리] find_best_sarima_params 실행 후: 1559.30 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1559.30 MB (변화: +0.00 MB)
[FARO]   [SARIMA] 완료  첫값=8.17e+07 (메모리: 1559.3 MB)
[FARO]   [ETS] 시작  (메모리: 1559.3 MB)
[메모리] forecast_ets 실행 전: 1559.30 MB
[메모리] forecast_ets 실행 후: 1559.30 MB (변화: +0.00 MB)
[FARO]   [ETS] 완료  첫값=8.19e+07 (메모리: 1559.3 MB)
[FARO]   [Prophet] 시작  (메모리: 1559.3 MB)

11:03:27 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1559.30 MB

11:03:27 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1559.33 MB (변화: +0.02 MB)
[FARO]   [Prophet] 완료  첫값=8.74e+07 (메모리: 1559.3 MB)
[FARO]   [LSTM] 시작  (메모리: 1559.3 MB)
[메모리] forecast_lstm 실행 전: 1559.33 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1559.30 MB (변화: -0.03 MB)
[FARO]   [LSTM] 완료  첫값=8.64e+07 (메모리: 1559.3 MB)
[FARO]   [Theta] 시작  (메모리: 1559.3 MB)
[메모리] forecast_theta 실행 전: 1559.30 MB
[메모리] forecast_theta 실행 후: 1559.30 MB (변화: +0.00 MB)
[FARO]   [Theta] 완료  첫값=8.16e+07 (메모리: 1559.3 MB)
[FARO]   [DB] 88행 저장 완료
[PROGRESS] [ 140/500] ( 28.0%)  >>  RPD
[RPD]   40분기 | 2016-03-31 ~ 2025-12-31
[RPD]   [SARIMA] 시작  (메모리: 1559.3 MB)
[메모리] forecast_sarima 실행 전: 1559.30 MB
[메모리] find_best_sarima_params 실행 전: 1559.30 MB
[메모리] find_best_sarima_params 실행 후: 1559.30 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1559.30 MB (변화: +0.00 MB)
[RPD]   [SARIMA] 완료  첫값=2.15e+08 (메모리: 1559.3 MB)
[RPD]   [ETS] 시작  (메모리: 1559.3 MB)
[메모리] forecast_ets 실행 전: 1559.30 MB
[메모리] forecast_ets 실행 후: 1559.30 MB (변화: +0.00 MB)
[RPD]   [ETS] 완료  첫값=2.10e+08 (메모리: 1559.3 MB)
[RPD]   [Prophet] 시작  (메모리: 1559.3 MB)

11:03:46 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1559.30 MB

11:03:46 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1559.32 MB (변화: +0.02 MB)
[RPD]   [Prophet] 완료  첫값=2.43e+08 (메모리: 1559.3 MB)
[RPD]   [LSTM] 시작  (메모리: 1559.3 MB)
[메모리] forecast_lstm 실행 전: 1559.32 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1559.29 MB (변화: -0.02 MB)
[RPD]   [LSTM] 완료  첫값=2.32e+08 (메모리: 1559.3 MB)
[RPD]   [Theta] 시작  (메모리: 1559.3 MB)
[메모리] forecast_theta 실행 전: 1559.29 MB
[메모리] forecast_theta 실행 후: 1559.29 MB (변화: +0.00 MB)
[RPD]   [Theta] 완료  첫값=2.14e+08 (메모리: 1559.3 MB)
[RPD]   [DB] 88행 저장 완료
[PROGRESS] [ 141/500] ( 28.2%)  >>  FWRD
[FWRD]   40분기 | 2016-03-31 ~ 2025-12-31
[FWRD]   [SARIMA] 시작  (메모리: 1559.3 MB)
[메모리] forecast_sarima 실행 전: 1559.29 MB
[메모리] find_best_sarima_params 실행 전: 1559.29 MB
[메모리] find_best_sarima_params 실행 후: 1559.29 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1559.29 MB (변화: +0.00 MB)
[FWRD]   [SARIMA] 완료  첫값=6.02e+08 (메모리: 1559.3 MB)
[FWRD]   [ETS] 시작  (메모리: 1559.3 MB)
[메모리] forecast_ets 실행 전: 1559.29 MB
[메모리] forecast_ets 실행 후: 1559.30 MB (변화: +0.00 MB)
[FWRD]   [ETS] 완료  첫값=6.70e+08 (메모리: 1559.3 MB)
[FWRD]   [Prophet] 시작  (메모리: 1559.3 MB)
[메모리] forecast_prophet 실행 전: 1559.30 MB

11:04:01 - cmdstanpy - INFO - Chain [1] start processing
11:04:01 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1559.32 MB (변화: +0.02 MB)
[FWRD]   [Prophet] 완료  첫값=5.87e+08 (메모리: 1559.3 MB)
[FWRD]   [LSTM] 시작  (메모리: 1559.3 MB)
[메모리] forecast_lstm 실행 전: 1559.32 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1558.11 MB (변화: -1.21 MB)
[FWRD]   [LSTM] 완료  첫값=5.67e+08 (메모리: 1558.1 MB)
[FWRD]   [Theta] 시작  (메모리: 1558.1 MB)
[메모리] forecast_theta 실행 전: 1558.11 MB
[메모리] forecast_theta 실행 후: 1558.11 MB (변화: +0.00 MB)
[FWRD]   [Theta] 완료  첫값=6.40e+08 (메모리: 1558.1 MB)
[FWRD]   [DB] 88행 저장 완료
[PROGRESS] [ 142/500] ( 28.4%)  >>  CSII
[CSII]   40분기 | 2013-03-31 ~ 2022-12-31
[CSII]   [SARIMA] 시작  (메모리: 1558.1 MB)
[메모리] forecast_sarima 실행 전: 1558.11 MB
[메모리] find_best_sarima_params 실행 전: 1558.11 MB
[메모리] find_best_sarima_params 실행 후: 1558.11 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1558.11 MB (변화: +0.00 MB)
[CSII]   [SARIMA] 완료  첫값=6.28e+07 (메모리: 1558.1 MB)
[CSII]   [ETS] 시작  (메모리: 1558.1 MB)
[메모리] forecast_ets 실행 전: 1558.11 MB
[메모리] forecast_ets 실행 후: 1558.11 MB (변화: +0.01 MB)
[CSII]   [ETS] 완료  첫값=6.28e+07 (메모리: 1558.1 MB)
[CSII]   [Prophet] 시작  (메모리: 1558.1 MB)

11:04:17 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1558.11 MB

11:04:17 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1558.15 MB (변화: +0.04 MB)
[CSII]   [Prophet] 완료  첫값=6.90e+07 (메모리: 1558.1 MB)
[CSII]   [LSTM] 시작  (메모리: 1558.1 MB)
[메모리] forecast_lstm 실행 전: 1558.15 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1558.16 MB (변화: +0.01 MB)
[CSII]   [LSTM] 완료  첫값=5.99e+07 (메모리: 1558.2 MB)
[CSII]   [Theta] 시작  (메모리: 1558.2 MB)
[메모리] forecast_theta 실행 전: 1558.16 MB
[메모리] forecast_theta 실행 후: 1558.16 MB (변화: +0.00 MB)
[CSII]   [Theta] 완료  첫값=6.19e+07 (메모리: 1558.2 MB)
[CSII]   [DB] 88행 저장 완료
[PROGRESS] [ 143/500] ( 28.6%)  >>  ODP
[ODP]   40분기 | 2015-12-31 ~ 2025-09-27
[ODP]   [SARIMA] 시작  (메모리: 1558.2 MB)
[메모리] forecast_sarima 실행 전: 1558.16 MB
[메모리] find_best_sarima_params 실행 전: 1558.16 MB
[메모리] find_best_sarima_params 실행 후: 1558.16 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1558.16 MB (변화: +0.00 MB)
[ODP]   [SARIMA] 완료  첫값=1.53e+09 (메모리: 1558.2 MB)
[ODP]   [ETS] 시작  (메모리: 1558.2 MB)
[메모리] forecast_ets 실행 전: 1558.16 MB
[메모리] forecast_ets 실행 후: 1558.16 MB (변화: +0.01 MB)
[ODP]   [ETS] 완료  첫값=1.55e+09 (메모리: 1558.2 MB)
[ODP]   [Prophet] 시작  (메모리: 1558.2 MB)

11:04:34 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1558.16 MB

11:04:34 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1558.20 MB (변화: +0.04 MB)
[ODP]   [Prophet] 완료  첫값=1.63e+09 (메모리: 1558.2 MB)
[ODP]   [LSTM] 시작  (메모리: 1558.2 MB)
[메모리] forecast_lstm 실행 전: 1558.20 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1557.80 MB (변화: -0.41 MB)
[ODP]   [LSTM] 완료  첫값=1.58e+09 (메모리: 1557.8 MB)
[ODP]   [Theta] 시작  (메모리: 1557.8 MB)
[메모리] forecast_theta 실행 전: 1557.80 MB
[메모리] forecast_theta 실행 후: 1557.80 MB (변화: +0.00 MB)
[ODP]   [Theta] 완료  첫값=1.54e+09 (메모리: 1557.8 MB)
[ODP]   [DB] 88행 저장 완료
[PROGRESS] [ 144/500] ( 28.8%)  >>  IRWD
[IRWD]   40분기 | 2016-03-31 ~ 2025-12-31
[IRWD]   [SARIMA] 시작  (메모리: 1557.8 MB)
[메모리] forecast_sarima 실행 전: 1557.80 MB
[메모리] find_best_sarima_params 실행 전: 1557.80 MB
[메모리] find_best_sarima_params 실행 후: 1557.80 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1557.80 MB (변화: +0.00 MB)
[IRWD]   [SARIMA] 완료  첫값=4.96e+07 (메모리: 1557.8 MB)
[IRWD]   [ETS] 시작  (메모리: 1557.8 MB)
[메모리] forecast_ets 실행 전: 1557.80 MB
[메모리] forecast_ets 실행 후: 1557.80 MB (변화: +0.01 MB)
[IRWD]   [ETS] 완료  첫값=5.27e+07 (메모리: 1557.8 MB)
[IRWD]   [Prophet] 시작  (메모리: 1557.8 MB)

11:04:52 - cmdstanpy - INFO - Chain [1] start processing
11:04:52 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1557.80 MB
[메모리] forecast_prophet 실행 후: 1557.82 MB (변화: +0.02 MB)
[IRWD]   [Prophet] 완료  첫값=1.01e+08 (메모리: 1557.8 MB)
[IRWD]   [LSTM] 시작  (메모리: 1557.8 MB)
[메모리] forecast_lstm 실행 전: 1557.82 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1557.67 MB (변화: -0.15 MB)
[IRWD]   [LSTM] 완료  첫값=9.22e+07 (메모리: 1557.7 MB)
[IRWD]   [Theta] 시작  (메모리: 1557.7 MB)
[메모리] forecast_theta 실행 전: 1557.67 MB
[메모리] forecast_theta 실행 후: 1557.67 MB (변화: +0.00 MB)
[IRWD]   [Theta] 완료  첫값=5.48e+07 (메모리: 1557.7 MB)
[IRWD]   [DB] 88행 저장 완료
[PROGRESS] [ 145/500] ( 29.0%)  >>  RDUS
[RDUS]   40분기 | 2015-09-30 ~ 2025-05-31
[RDUS]   [SARIMA] 시작  (메모리: 1557.7 MB)
[메모리] forecast_sarima 실행 전: 1557.67 MB
[메모리] find_best_sarima_params 실행 전: 1557.67 MB
[메모리] find_best_sarima_params 실행 후: 1557.67 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1557.67 MB (변화: +0.00 MB)
[RDUS]   [SARIMA] 완료  첫값=7.43e+08 (메모리: 1557.7 MB)
[RDUS]   [ETS] 시작  (메모리: 1557.7 MB)
[메모리] forecast_ets 실행 전: 1557.67 MB
[메모리] forecast_ets 실행 후: 1557.67 MB (변화: +0.00 MB)
[RDUS]   [ETS] 완료  첫값=7.52e+08 (메모리: 1557.7 MB)
[RDUS]   [Prophet] 시작  (메모리: 1557.7 MB)

11:05:05 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1557.67 MB

11:05:05 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1557.70 MB (변화: +0.03 MB)
[RDUS]   [Prophet] 완료  첫값=6.72e+08 (메모리: 1557.7 MB)
[RDUS]   [LSTM] 시작  (메모리: 1557.7 MB)
[메모리] forecast_lstm 실행 전: 1557.70 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1557.53 MB (변화: -0.17 MB)
[RDUS]   [LSTM] 완료  첫값=6.88e+08 (메모리: 1557.5 MB)
[RDUS]   [Theta] 시작  (메모리: 1557.5 MB)
[메모리] forecast_theta 실행 전: 1557.53 MB
[메모리] forecast_theta 실행 후: 1557.53 MB (변화: +0.00 MB)
[RDUS]   [Theta] 완료  첫값=8.02e+08 (메모리: 1557.5 MB)
[RDUS]   [DB] 88행 저장 완료
[PROGRESS] [ 146/500] ( 29.2%)  >>  AIV
[AIV]   40분기 | 2015-03-31 ~ 2025-12-31
[AIV]   [SARIMA] 시작  (메모리: 1557.5 MB)
[메모리] forecast_sarima 실행 전: 1557.53 MB
[메모리] find_best_sarima_params 실행 전: 1557.53 MB
[메모리] find_best_sarima_params 실행 후: 1557.65 MB (변화: +0.12 MB)
[메모리] forecast_sarima 실행 후: 1557.65 MB (변화: +0.12 MB)
[AIV]   [SARIMA] 완료  첫값=3.28e+07 (메모리: 1557.6 MB)
[AIV]   [ETS] 시작  (메모리: 1557.6 MB)
[메모리] forecast_ets 실행 전: 1557.65 MB
[메모리] forecast_ets 실행 후: 1557.66 MB (변화: +0.01 MB)
[AIV]   [ETS] 완료  첫값=3.29e+07 (메모리: 1557.7 MB)
[AIV]   [Prophet] 시작  (메모리: 1557.7 MB)

11:05:24 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1557.66 MB

11:05:24 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1557.68 MB (변화: +0.03 MB)
[AIV]   [Prophet] 완료  첫값=-1.61e+07 (메모리: 1557.7 MB)
[AIV]   [LSTM] 시작  (메모리: 1557.7 MB)
[메모리] forecast_lstm 실행 전: 1557.68 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1557.46 MB (변화: -0.22 MB)
[AIV]   [LSTM] 완료  첫값=4.90e+07 (메모리: 1557.5 MB)
[AIV]   [Theta] 시작  (메모리: 1557.5 MB)
[메모리] forecast_theta 실행 전: 1557.46 MB
[메모리] forecast_theta 실행 후: 1557.46 MB (변화: +0.00 MB)
[AIV]   [Theta] 완료  첫값=3.36e+07 (메모리: 1557.5 MB)
[AIV]   [DB] 88행 저장 완료
[PROGRESS] [ 147/500] ( 29.4%)  >>  APOG
[APOG]   40분기 | 2016-02-28 ~ 2025-11-29
[APOG]   [SARIMA] 시작  (메모리: 1557.5 MB)
[메모리] forecast_sarima 실행 전: 1557.47 MB
[메모리] find_best_sarima_params 실행 전: 1557.47 MB
[메모리] find_best_sarima_params 실행 후: 1557.47 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1557.47 MB (변화: +0.00 MB)
[APOG]   [SARIMA] 완료  첫값=3.47e+08 (메모리: 1557.5 MB)
[APOG]   [ETS] 시작  (메모리: 1557.5 MB)
[메모리] forecast_ets 실행 전: 1557.47 MB
[메모리] forecast_ets 실행 후: 1557.48 MB (변화: +0.01 MB)
[APOG]   [ETS] 완료  첫값=3.54e+08 (메모리: 1557.5 MB)
[APOG]   [Prophet] 시작  (메모리: 1557.5 MB)

11:05:44 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1557.48 MB

11:05:44 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1557.50 MB (변화: +0.03 MB)
[APOG]   [Prophet] 완료  첫값=3.61e+08 (메모리: 1557.5 MB)
[APOG]   [LSTM] 시작  (메모리: 1557.5 MB)
[메모리] forecast_lstm 실행 전: 1557.50 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1557.20 MB (변화: -0.30 MB)
[APOG]   [LSTM] 완료  첫값=3.39e+08 (메모리: 1557.2 MB)
[APOG]   [Theta] 시작  (메모리: 1557.2 MB)
[메모리] forecast_theta 실행 전: 1557.20 MB
[메모리] forecast_theta 실행 후: 1557.20 MB (변화: +0.00 MB)
[APOG]   [Theta] 완료  첫값=3.52e+08 (메모리: 1557.2 MB)
[APOG]   [DB] 88행 저장 완료
[PROGRESS] [ 148/500] ( 29.6%)  >>  GHM
[GHM]   40분기 | 2016-03-31 ~ 2025-12-31
[GHM]   [SARIMA] 시작  (메모리: 1557.2 MB)
[메모리] forecast_sarima 실행 전: 1557.20 MB
[메모리] find_best_sarima_params 실행 전: 1557.20 MB
[메모리] find_best_sarima_params 실행 후: 1557.20 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1557.20 MB (변화: +0.00 MB)
[GHM]   [SARIMA] 완료  첫값=6.09e+07 (메모리: 1557.2 MB)
[GHM]   [ETS] 시작  (메모리: 1557.2 MB)
[메모리] forecast_ets 실행 전: 1557.20 MB
[메모리] forecast_ets 실행 후: 1557.20 MB (변화: +0.00 MB)
[GHM]   [ETS] 완료  첫값=6.84e+07 (메모리: 1557.2 MB)
[GHM]   [Prophet] 시작  (메모리: 1557.2 MB)

11:06:00 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1557.20 MB

11:06:00 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1557.58 MB (변화: +0.38 MB)
[GHM]   [Prophet] 완료  첫값=6.07e+07 (메모리: 1557.6 MB)
[GHM]   [LSTM] 시작  (메모리: 1557.6 MB)
[메모리] forecast_lstm 실행 전: 1557.58 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1557.81 MB (변화: +0.23 MB)
[GHM]   [LSTM] 완료  첫값=6.75e+07 (메모리: 1557.8 MB)
[GHM]   [Theta] 시작  (메모리: 1557.8 MB)
[메모리] forecast_theta 실행 전: 1557.81 MB
[메모리] forecast_theta 실행 후: 1557.81 MB (변화: +0.00 MB)
[GHM]   [Theta] 완료  첫값=6.62e+07 (메모리: 1557.8 MB)
[GHM]   [DB] 88행 저장 완료
[PROGRESS] [ 149/500] ( 29.8%)  >>  MOBL
[MOBL]   31분기 | 2013-03-31 ~ 2020-09-30
[MOBL]   [SARIMA] 시작  (메모리: 1557.8 MB)
[메모리] forecast_sarima 실행 전: 1557.81 MB
[메모리] find_best_sarima_params 실행 전: 1557.81 MB
[메모리] find_best_sarima_params 실행 후: 1557.83 MB (변화: +0.02 MB)
[메모리] forecast_sarima 실행 후: 1557.83 MB (변화: +0.02 MB)
[MOBL]   [SARIMA] 완료  첫값=5.73e+07 (메모리: 1557.8 MB)
[MOBL]   [ETS] 시작  (메모리: 1557.8 MB)
[메모리] forecast_ets 실행 전: 1557.83 MB
[메모리] forecast_ets 실행 후: 1557.83 MB (변화: +0.00 MB)
[MOBL]   [ETS] 완료  첫값=5.89e+07 (메모리: 1557.8 MB)
[MOBL]   [Prophet] 시작  (메모리: 1557.8 MB)

11:06:21 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1557.83 MB

11:06:21 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1557.85 MB (변화: +0.02 MB)
[MOBL]   [Prophet] 완료  첫값=5.70e+07 (메모리: 1557.9 MB)
[MOBL]   [LSTM] 시작  (메모리: 1557.9 MB)
[메모리] forecast_lstm 실행 전: 1557.85 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1558.77 MB (변화: +0.92 MB)
[MOBL]   [LSTM] 완료  첫값=5.39e+07 (메모리: 1558.8 MB)
[MOBL]   [Theta] 시작  (메모리: 1558.8 MB)
[메모리] forecast_theta 실행 전: 1558.77 MB
[메모리] forecast_theta 실행 후: 1558.77 MB (변화: +0.00 MB)
[MOBL]   [Theta] 완료  첫값=5.41e+07 (메모리: 1558.8 MB)
[MOBL]   [DB] 79행 저장 완료
[PROGRESS] [ 150/500] ( 30.0%)  >>  MLCO
[MLCO]   40분기 | 2016-03-31 ~ 2025-12-31
[MLCO]   [SARIMA] 시작  (메모리: 1558.8 MB)
[메모리] forecast_sarima 실행 전: 1558.77 MB
[메모리] find_best_sarima_params 실행 전: 1558.77 MB
[메모리] find_best_sarima_params 실행 후: 1558.77 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1558.77 MB (변화: +0.00 MB)
[MLCO]   [SARIMA] 완료  첫값=1.30e+09 (메모리: 1558.8 MB)
[MLCO]   [ETS] 시작  (메모리: 1558.8 MB)
[메모리] forecast_ets 실행 전: 1558.77 MB
[메모리] forecast_ets 실행 후: 1558.77 MB (변화: +0.00 MB)
[MLCO]   [ETS] 완료  첫값=1.33e+09 (메모리: 1558.8 MB)
[MLCO]   [Prophet] 시작  (메모리: 1558.8 MB)

11:06:36 - cmdstanpy - INFO - Chain [1] start processing
11:06:36 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1558.77 MB
[메모리] forecast_prophet 실행 후: 1559.87 MB (변화: +1.10 MB)
[MLCO]   [Prophet] 완료  첫값=8.44e+08 (메모리: 1559.9 MB)
[MLCO]   [LSTM] 시작  (메모리: 1559.9 MB)
[메모리] forecast_lstm 실행 전: 1559.87 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1559.98 MB (변화: +0.11 MB)
[MLCO]   [LSTM] 완료  첫값=1.04e+09 (메모리: 1560.0 MB)
[MLCO]   [Theta] 시작  (메모리: 1560.0 MB)
[메모리] forecast_theta 실행 전: 1559.98 MB
[메모리] forecast_theta 실행 후: 1559.98 MB (변화: +0.00 MB)
[MLCO]   [Theta] 완료  첫값=1.29e+09 (메모리: 1560.0 MB)
[MLCO]   [DB] 88행 저장 완료
[PROGRESS] [ 151/500] ( 30.2%)  >>  UBP
[UBP]   40분기 | 2013-07-31 ~ 2023-04-30
[UBP]   [SARIMA] 시작  (메모리: 1560.0 MB)
[메모리] forecast_sarima 실행 전: 1559.98 MB
[메모리] find_best_sarima_params 실행 전: 1559.98 MB
[메모리] find_best_sarima_params 실행 후: 1559.98 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1559.98 MB (변화: +0.00 MB)
[UBP]   [SARIMA] 완료  첫값=3.54e+07 (메모리: 1560.0 MB)
[UBP]   [ETS] 시작  (메모리: 1560.0 MB)
[메모리] forecast_ets 실행 전: 1559.98 MB
[메모리] forecast_ets 실행 후: 1559.98 MB (변화: +0.01 MB)
[UBP]   [ETS] 완료  첫값=3.56e+07 (메모리: 1560.0 MB)
[UBP]   [Prophet] 시작  (메모리: 1560.0 MB)

11:06:56 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1559.98 MB

11:06:56 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1560.39 MB (변화: +0.41 MB)
[UBP]   [Prophet] 완료  첫값=3.64e+07 (메모리: 1560.4 MB)
[UBP]   [LSTM] 시작  (메모리: 1560.4 MB)
[메모리] forecast_lstm 실행 전: 1560.39 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1560.25 MB (변화: -0.14 MB)
[UBP]   [LSTM] 완료  첫값=3.47e+07 (메모리: 1560.3 MB)
[UBP]   [Theta] 시작  (메모리: 1560.3 MB)
[메모리] forecast_theta 실행 전: 1560.25 MB
[메모리] forecast_theta 실행 후: 1560.25 MB (변화: +0.00 MB)
[UBP]   [Theta] 완료  첫값=3.48e+07 (메모리: 1560.3 MB)
[UBP]   [DB] 88행 저장 완료
[PROGRESS] [ 152/500] ( 30.4%)  >>  UBA
[UBA]   40분기 | 2013-07-31 ~ 2023-04-30
[UBA]   [SARIMA] 시작  (메모리: 1560.3 MB)
[메모리] forecast_sarima 실행 전: 1560.25 MB
[메모리] find_best_sarima_params 실행 전: 1560.25 MB
[메모리] find_best_sarima_params 실행 후: 1560.25 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1560.25 MB (변화: +0.00 MB)
[UBA]   [SARIMA] 완료  첫값=3.54e+07 (메모리: 1560.3 MB)
[UBA]   [ETS] 시작  (메모리: 1560.3 MB)
[메모리] forecast_ets 실행 전: 1560.25 MB
[메모리] forecast_ets 실행 후: 1560.26 MB (변화: +0.00 MB)
[UBA]   [ETS] 완료  첫값=3.56e+07 (메모리: 1560.3 MB)
[UBA]   [Prophet] 시작  (메모리: 1560.3 MB)

11:07:13 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1560.26 MB

11:07:13 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1560.29 MB (변화: +0.03 MB)
[UBA]   [Prophet] 완료  첫값=3.64e+07 (메모리: 1560.3 MB)
[UBA]   [LSTM] 시작  (메모리: 1560.3 MB)
[메모리] forecast_lstm 실행 전: 1560.29 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1560.25 MB (변화: -0.04 MB)
[UBA]   [LSTM] 완료  첫값=3.47e+07 (메모리: 1560.2 MB)
[UBA]   [Theta] 시작  (메모리: 1560.2 MB)
[메모리] forecast_theta 실행 전: 1560.25 MB
[메모리] forecast_theta 실행 후: 1560.25 MB (변화: +0.00 MB)
[UBA]   [Theta] 완료  첫값=3.48e+07 (메모리: 1560.2 MB)
[UBA]   [DB] 88행 저장 완료
[PROGRESS] [ 153/500] ( 30.6%)  >>  LINC
[LINC]   40분기 | 2016-03-31 ~ 2025-12-31
[LINC]   [SARIMA] 시작  (메모리: 1560.3 MB)
[메모리] forecast_sarima 실행 전: 1560.25 MB
[메모리] find_best_sarima_params 실행 전: 1560.25 MB
[메모리] find_best_sarima_params 실행 후: 1560.25 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1560.25 MB (변화: +0.00 MB)
[LINC]   [SARIMA] 완료  첫값=1.39e+08 (메모리: 1560.3 MB)
[LINC]   [ETS] 시작  (메모리: 1560.3 MB)
[메모리] forecast_ets 실행 전: 1560.25 MB
[메모리] forecast_ets 실행 후: 1560.25 MB (변화: +0.00 MB)
[LINC]   [ETS] 완료  첫값=1.40e+08 (메모리: 1560.3 MB)
[LINC]   [Prophet] 시작  (메모리: 1560.3 MB)

11:07:30 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1560.25 MB

11:07:30 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1560.28 MB (변화: +0.03 MB)
[LINC]   [Prophet] 완료  첫값=1.32e+08 (메모리: 1560.3 MB)
[LINC]   [LSTM] 시작  (메모리: 1560.3 MB)
[메모리] forecast_lstm 실행 전: 1560.28 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1560.25 MB (변화: -0.03 MB)
[LINC]   [LSTM] 완료  첫값=1.15e+08 (메모리: 1560.3 MB)
[LINC]   [Theta] 시작  (메모리: 1560.3 MB)
[메모리] forecast_theta 실행 전: 1560.25 MB
[메모리] forecast_theta 실행 후: 1560.25 MB (변화: +0.00 MB)
[LINC]   [Theta] 완료  첫값=1.38e+08 (메모리: 1560.3 MB)
[LINC]   [DB] 88행 저장 완료
[PROGRESS] [ 154/500] ( 30.8%)  >>  MATW
[MATW]   40분기 | 2016-03-31 ~ 2025-12-31
[MATW]   [SARIMA] 시작  (메모리: 1560.3 MB)
[메모리] forecast_sarima 실행 전: 1560.25 MB
[메모리] find_best_sarima_params 실행 전: 1560.25 MB
[메모리] find_best_sarima_params 실행 후: 1560.25 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1560.25 MB (변화: +0.00 MB)
[MATW]   [SARIMA] 완료  첫값=2.98e+08 (메모리: 1560.3 MB)
[MATW]   [ETS] 시작  (메모리: 1560.3 MB)
[메모리] forecast_ets 실행 전: 1560.25 MB
[메모리] forecast_ets 실행 후: 1560.26 MB (변화: +0.01 MB)
[MATW]   [ETS] 완료  첫값=2.83e+08 (메모리: 1560.3 MB)
[MATW]   [Prophet] 시작  (메모리: 1560.3 MB)

11:07:47 - cmdstanpy - INFO - Chain [1] start processing
11:07:47 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1560.26 MB
[메모리] forecast_prophet 실행 후: 1560.29 MB (변화: +0.03 MB)
[MATW]   [Prophet] 완료  첫값=4.25e+08 (메모리: 1560.3 MB)
[MATW]   [LSTM] 시작  (메모리: 1560.3 MB)
[메모리] forecast_lstm 실행 전: 1560.29 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1560.86 MB (변화: +0.57 MB)
[MATW]   [LSTM] 완료  첫값=4.27e+08 (메모리: 1560.9 MB)
[MATW]   [Theta] 시작  (메모리: 1560.9 MB)
[메모리] forecast_theta 실행 전: 1560.86 MB
[메모리] forecast_theta 실행 후: 1560.86 MB (변화: +0.00 MB)
[MATW]   [Theta] 완료  첫값=2.91e+08 (메모리: 1560.9 MB)
[MATW]   [DB] 88행 저장 완료
[PROGRESS] [ 155/500] ( 31.0%)  >>  TK
[TK]   40분기 | 2015-12-31 ~ 2025-12-31
[TK]   [SARIMA] 시작  (메모리: 1560.9 MB)
[메모리] forecast_sarima 실행 전: 1560.86 MB
[메모리] find_best_sarima_params 실행 전: 1560.86 MB
[메모리] find_best_sarima_params 실행 후: 1560.86 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1560.86 MB (변화: +0.00 MB)
[TK]   [SARIMA] 완료  첫값=2.51e+08 (메모리: 1560.9 MB)
[TK]   [ETS] 시작  (메모리: 1560.9 MB)
[메모리] forecast_ets 실행 전: 1560.86 MB
[메모리] forecast_ets 실행 후: 1560.86 MB (변화: +0.00 MB)
[TK]   [ETS] 완료  첫값=2.73e+08 (메모리: 1560.9 MB)
[TK]   [Prophet] 시작  (메모리: 1560.9 MB)

11:08:01 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1560.86 MB

11:08:01 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1560.89 MB (변화: +0.04 MB)
[TK]   [Prophet] 완료  첫값=2.08e+08 (메모리: 1560.9 MB)
[TK]   [LSTM] 시작  (메모리: 1560.9 MB)
[메모리] forecast_lstm 실행 전: 1560.89 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1560.46 MB (변화: -0.43 MB)
[TK]   [LSTM] 완료  첫값=3.45e+08 (메모리: 1560.5 MB)
[TK]   [Theta] 시작  (메모리: 1560.5 MB)
[메모리] forecast_theta 실행 전: 1560.46 MB
[메모리] forecast_theta 실행 후: 1560.46 MB (변화: +0.00 MB)
[TK]   [Theta] 완료  첫값=2.55e+08 (메모리: 1560.5 MB)
[TK]   [DB] 88행 저장 완료
[PROGRESS] [ 156/500] ( 31.2%)  >>  AEHR
[AEHR]   40분기 | 2016-02-29 ~ 2025-11-28
[AEHR]   [SARIMA] 시작  (메모리: 1560.5 MB)
[메모리] forecast_sarima 실행 전: 1560.46 MB
[메모리] find_best_sarima_params 실행 전: 1560.46 MB
[메모리] find_best_sarima_params 실행 후: 1560.46 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1560.46 MB (변화: +0.00 MB)
[AEHR]   [SARIMA] 완료  첫값=1.05e+07 (메모리: 1560.5 MB)
[AEHR]   [ETS] 시작  (메모리: 1560.5 MB)
[메모리] forecast_ets 실행 전: 1560.46 MB
[메모리] forecast_ets 실행 후: 1560.46 MB (변화: +0.00 MB)
[AEHR]   [ETS] 완료  첫값=1.04e+07 (메모리: 1560.5 MB)
[AEHR]   [Prophet] 시작  (메모리: 1560.5 MB)

11:08:14 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1560.46 MB

11:08:14 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1560.49 MB (변화: +0.03 MB)
[AEHR]   [Prophet] 완료  첫값=1.67e+07 (메모리: 1560.5 MB)
[AEHR]   [LSTM] 시작  (메모리: 1560.5 MB)
[메모리] forecast_lstm 실행 전: 1560.49 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1561.43 MB (변화: +0.94 MB)
[AEHR]   [LSTM] 완료  첫값=1.40e+07 (메모리: 1561.4 MB)
[AEHR]   [Theta] 시작  (메모리: 1561.4 MB)
[메모리] forecast_theta 실행 전: 1561.43 MB
[메모리] forecast_theta 실행 후: 1561.43 MB (변화: +0.00 MB)
[AEHR]   [Theta] 완료  첫값=9.97e+06 (메모리: 1561.4 MB)
[AEHR]   [DB] 88행 저장 완료
[PROGRESS] [ 157/500] ( 31.4%)  >>  OMER
[OMER] [NEG-SKIP] [OMER] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2021, 12, 31)])
[PROGRESS] [ 158/500] ( 31.6%)  >>  MTUS
[MTUS]   40분기 | 2016-03-31 ~ 2025-12-31
[MTUS]   [SARIMA] 시작  (메모리: 1561.4 MB)
[메모리] forecast_sarima 실행 전: 1561.43 MB
[메모리] find_best_sarima_params 실행 전: 1561.43 MB
[메모리] find_best_sarima_params 실행 후: 1561.43 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1561.43 MB (변화: +0.00 MB)
[MTUS]   [SARIMA] 완료  첫값=2.67e+08 (메모리: 1561.4 MB)
[MTUS]   [ETS] 시작  (메모리: 1561.4 MB)
[메모리] forecast_ets 실행 전: 1561.43 MB
[메모리] forecast_ets 실행 후: 1561.44 MB (변화: +0.00 MB)
[MTUS]   [ETS] 완료  첫값=3.06e+08 (메모리: 1561.4 MB)
[MTUS]   [Prophet] 시작  (메모리: 1561.4 MB)

11:08:30 - cmdstanpy - INFO - Chain [1] start processing
11:08:30 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1561.44 MB
[메모리] forecast_prophet 실행 후: 1561.45 MB (변화: +0.01 MB)
[MTUS]   [Prophet] 완료  첫값=3.03e+08 (메모리: 1561.4 MB)
[MTUS]   [LSTM] 시작  (메모리: 1561.4 MB)
[메모리] forecast_lstm 실행 전: 1561.45 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1561.42 MB (변화: -0.03 MB)
[MTUS]   [LSTM] 완료  첫값=2.71e+08 (메모리: 1561.4 MB)
[MTUS]   [Theta] 시작  (메모리: 1561.4 MB)
[메모리] forecast_theta 실행 전: 1561.42 MB
[메모리] forecast_theta 실행 후: 1561.42 MB (변화: +0.00 MB)
[MTUS]   [Theta] 완료  첫값=2.69e+08 (메모리: 1561.4 MB)
[MTUS]   [DB] 88행 저장 완료
[PROGRESS] [ 159/500] ( 31.8%)  >>  ATRI
[ATRI]   40분기 | 2014-10-27 ~ 2024-06-30
[ATRI]   [SARIMA] 시작  (메모리: 1561.4 MB)
[메모리] forecast_sarima 실행 전: 1561.42 MB
[메모리] find_best_sarima_params 실행 전: 1561.42 MB
[메모리] find_best_sarima_params 실행 후: 1561.50 MB (변화: +0.08 MB)
[메모리] forecast_sarima 실행 후: 1561.50 MB (변화: +0.08 MB)
[ATRI]   [SARIMA] 완료  첫값=4.50e+07 (메모리: 1561.5 MB)
[ATRI]   [ETS] 시작  (메모리: 1561.5 MB)
[메모리] forecast_ets 실행 전: 1561.50 MB
[메모리] forecast_ets 실행 후: 1561.51 MB (변화: +0.00 MB)
[ATRI]   [ETS] 완료  첫값=4.41e+07 (메모리: 1561.5 MB)
[ATRI]   [Prophet] 시작  (메모리: 1561.5 MB)

11:08:47 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1561.51 MB

11:08:47 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1561.54 MB (변화: +0.03 MB)
[ATRI]   [Prophet] 완료  첫값=4.47e+07 (메모리: 1561.5 MB)
[ATRI]   [LSTM] 시작  (메모리: 1561.5 MB)
[메모리] forecast_lstm 실행 전: 1561.54 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1560.75 MB (변화: -0.79 MB)
[ATRI]   [LSTM] 완료  첫값=4.44e+07 (메모리: 1560.7 MB)
[ATRI]   [Theta] 시작  (메모리: 1560.7 MB)
[메모리] forecast_theta 실행 전: 1560.75 MB
[메모리] forecast_theta 실행 후: 1560.75 MB (변화: +0.00 MB)
[ATRI]   [Theta] 완료  첫값=4.61e+07 (메모리: 1560.7 MB)
[ATRI]   [DB] 88행 저장 완료
[PROGRESS] [ 160/500] ( 32.0%)  >>  ODC
[ODC]   40분기 | 2016-04-30 ~ 2026-01-31
[ODC]   [SARIMA] 시작  (메모리: 1560.7 MB)
[메모리] forecast_sarima 실행 전: 1560.75 MB
[메모리] find_best_sarima_params 실행 전: 1560.75 MB
[메모리] find_best_sarima_params 실행 후: 1560.75 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1560.75 MB (변화: +0.00 MB)
[ODC]   [SARIMA] 완료  첫값=1.23e+08 (메모리: 1560.7 MB)
[ODC]   [ETS] 시작  (메모리: 1560.7 MB)
[메모리] forecast_ets 실행 전: 1560.75 MB
[메모리] forecast_ets 실행 후: 1560.75 MB (변화: +0.01 MB)
[ODC]   [ETS] 완료  첫값=1.20e+08 (메모리: 1560.8 MB)
[ODC]   [Prophet] 시작  (메모리: 1560.8 MB)

11:09:04 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1560.75 MB

11:09:04 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1560.77 MB (변화: +0.02 MB)
[ODC]   [Prophet] 완료  첫값=1.29e+08 (메모리: 1560.8 MB)
[ODC]   [LSTM] 시작  (메모리: 1560.8 MB)
[메모리] forecast_lstm 실행 전: 1560.77 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1561.83 MB (변화: +1.06 MB)
[ODC]   [LSTM] 완료  첫값=1.33e+08 (메모리: 1561.8 MB)
[ODC]   [Theta] 시작  (메모리: 1561.8 MB)
[메모리] forecast_theta 실행 전: 1561.83 MB
[메모리] forecast_theta 실행 후: 1561.83 MB (변화: +0.00 MB)
[ODC]   [Theta] 완료  첫값=1.18e+08 (메모리: 1561.8 MB)
[ODC]   [DB] 88행 저장 완료
[PROGRESS] [ 161/500] ( 32.2%)  >>  TCRZ
[TCRZ] [SKIP] [TCRZ] FMP에서 'sale' 데이터 없음
[PROGRESS] [ 162/500] ( 32.4%)  >>  QNST
[QNST]   40분기 | 2016-03-31 ~ 2025-12-31
[QNST]   [SARIMA] 시작  (메모리: 1561.8 MB)
[메모리] forecast_sarima 실행 전: 1561.83 MB
[메모리] find_best_sarima_params 실행 전: 1561.83 MB
[메모리] find_best_sarima_params 실행 후: 1561.83 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1561.83 MB (변화: +0.00 MB)
[QNST]   [SARIMA] 완료  첫값=3.22e+08 (메모리: 1561.8 MB)
[QNST]   [ETS] 시작  (메모리: 1561.8 MB)
[메모리] forecast_ets 실행 전: 1561.83 MB
[메모리] forecast_ets 실행 후: 1561.84 MB (변화: +0.00 MB)
[QNST]   [ETS] 완료  첫값=3.41e+08 (메모리: 1561.8 MB)
[QNST]   [Prophet] 시작  (메모리: 1561.8 MB)

11:09:25 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1561.84 MB

11:09:25 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1561.85 MB (변화: +0.02 MB)
[QNST]   [Prophet] 완료  첫값=2.41e+08 (메모리: 1561.9 MB)
[QNST]   [LSTM] 시작  (메모리: 1561.9 MB)
[메모리] forecast_lstm 실행 전: 1561.85 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1561.80 MB (변화: -0.05 MB)
[QNST]   [LSTM] 완료  첫값=2.49e+08 (메모리: 1561.8 MB)
[QNST]   [Theta] 시작  (메모리: 1561.8 MB)
[메모리] forecast_theta 실행 전: 1561.80 MB
[메모리] forecast_theta 실행 후: 1561.80 MB (변화: +0.00 MB)
[QNST]   [Theta] 완료  첫값=3.36e+08 (메모리: 1561.8 MB)
[QNST]   [DB] 88행 저장 완료
[PROGRESS] [ 163/500] ( 32.6%)  >>  GAU
[GAU] [NEG-SKIP] [GAU] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2019, 3, 31), datetime.date(2019, 9, 30), datetime.date(2021, 12, 31)])
[PROGRESS] [ 164/500] ( 32.8%)  >>  GPRE
[GPRE]   40분기 | 2016-03-31 ~ 2025-12-31
[GPRE]   [SARIMA] 시작  (메모리: 1561.8 MB)
[메모리] forecast_sarima 실행 전: 1561.80 MB
[메모리] find_best_sarima_params 실행 전: 1561.80 MB
[메모리] find_best_sarima_params 실행 후: 1561.80 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1561.80 MB (변화: +0.00 MB)
[GPRE]   [SARIMA] 완료  첫값=4.29e+08 (메모리: 1561.8 MB)
[GPRE]   [ETS] 시작  (메모리: 1561.8 MB)
[메모리] forecast_ets 실행 전: 1561.80 MB
[메모리] forecast_ets 실행 후: 1561.80 MB (변화: +0.00 MB)
[GPRE]   [ETS] 완료  첫값=4.10e+08 (메모리: 1561.8 MB)
[GPRE]   [Prophet] 시작  (메모리: 1561.8 MB)

11:09:42 - cmdstanpy - INFO - Chain [1] start processing
11:09:42 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1561.80 MB
[메모리] forecast_prophet 실행 후: 1561.82 MB (변화: +0.02 MB)
[GPRE]   [Prophet] 완료  첫값=6.00e+08 (메모리: 1561.8 MB)
[GPRE]   [LSTM] 시작  (메모리: 1561.8 MB)
[메모리] forecast_lstm 실행 전: 1561.82 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1561.79 MB (변화: -0.03 MB)
[GPRE]   [LSTM] 완료  첫값=6.49e+08 (메모리: 1561.8 MB)
[GPRE]   [Theta] 시작  (메모리: 1561.8 MB)
[메모리] forecast_theta 실행 전: 1561.79 MB
[메모리] forecast_theta 실행 후: 1561.79 MB (변화: +0.00 MB)
[GPRE]   [Theta] 완료  첫값=4.32e+08 (메모리: 1561.8 MB)
[GPRE]   [DB] 88행 저장 완료
[PROGRESS] [ 165/500] ( 33.0%)  >>  HTLD
[HTLD]   40분기 | 2016-03-31 ~ 2025-12-31
[HTLD]   [SARIMA] 시작  (메모리: 1561.8 MB)
[메모리] forecast_sarima 실행 전: 1561.79 MB
[메모리] find_best_sarima_params 실행 전: 1561.79 MB
[메모리] find_best_sarima_params 실행 후: 1561.79 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1561.79 MB (변화: +0.00 MB)
[HTLD]   [SARIMA] 완료  첫값=1.70e+08 (메모리: 1561.8 MB)
[HTLD]   [ETS] 시작  (메모리: 1561.8 MB)
[메모리] forecast_ets 실행 전: 1561.79 MB
[메모리] forecast_ets 실행 후: 1561.80 MB (변화: +0.01 MB)
[HTLD]   [ETS] 완료  첫값=1.72e+08 (메모리: 1561.8 MB)
[HTLD]   [Prophet] 시작  (메모리: 1561.8 MB)

11:10:03 - cmdstanpy - INFO - Chain [1] start processing
11:10:03 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1561.80 MB
[메모리] forecast_prophet 실행 후: 1561.84 MB (변화: +0.04 MB)
[HTLD]   [Prophet] 완료  첫값=2.62e+08 (메모리: 1561.8 MB)
[HTLD]   [LSTM] 시작  (메모리: 1561.8 MB)
[메모리] forecast_lstm 실행 전: 1561.84 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1561.81 MB (변화: -0.03 MB)
[HTLD]   [LSTM] 완료  첫값=2.27e+08 (메모리: 1561.8 MB)
[HTLD]   [Theta] 시작  (메모리: 1561.8 MB)
[메모리] forecast_theta 실행 전: 1561.81 MB
[메모리] forecast_theta 실행 후: 1561.81 MB (변화: +0.00 MB)
[HTLD]   [Theta] 완료  첫값=1.72e+08 (메모리: 1561.8 MB)
[HTLD]   [DB] 88행 저장 완료
[PROGRESS] [ 166/500] ( 33.2%)  >>  CMRX
[CMRX]   40분기 | 2015-03-31 ~ 2024-12-31
[CMRX]   [SARIMA] 시작  (메모리: 1561.8 MB)
[메모리] forecast_sarima 실행 전: 1561.81 MB
[메모리] find_best_sarima_params 실행 전: 1561.81 MB
[메모리] find_best_sarima_params 실행 후: 1561.81 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1561.81 MB (변화: +0.00 MB)
[CMRX]   [SARIMA] 완료  첫값=3.99e+06 (메모리: 1561.8 MB)
[CMRX]   [ETS] 시작  (메모리: 1561.8 MB)
[메모리] forecast_ets 실행 전: 1561.81 MB
[메모리] forecast_ets 실행 후: 1561.81 MB (변화: +0.00 MB)
[CMRX]   [ETS] 완료  첫값=1.01e+06 (메모리: 1561.8 MB)
[CMRX]   [Prophet] 시작  (메모리: 1561.8 MB)

11:10:18 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1561.81 MB

11:10:18 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1561.84 MB (변화: +0.02 MB)
[CMRX]   [Prophet] 완료  첫값=2.07e+06 (메모리: 1561.8 MB)
[CMRX]   [LSTM] 시작  (메모리: 1561.8 MB)
[메모리] forecast_lstm 실행 전: 1561.84 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1562.21 MB (변화: +0.37 MB)
[CMRX]   [LSTM] 완료  첫값=-1.24e+05 (메모리: 1562.2 MB)
[CMRX]   [Theta] 시작  (메모리: 1562.2 MB)
[메모리] forecast_theta 실행 전: 1562.21 MB
[메모리] forecast_theta 실행 후: 1562.21 MB (변화: +0.00 MB)
[CMRX]   [Theta] 완료  첫값=1.32e+06 (메모리: 1562.2 MB)
[CMRX]   [DB] 88행 저장 완료
[PROGRESS] [ 167/500] ( 33.4%)  >>  FOXF
[FOXF]   40분기 | 2016-04-01 ~ 2026-01-02
[FOXF]   [SARIMA] 시작  (메모리: 1562.2 MB)
[메모리] forecast_sarima 실행 전: 1562.21 MB
[메모리] find_best_sarima_params 실행 전: 1562.21 MB
[메모리] find_best_sarima_params 실행 후: 1562.21 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1562.21 MB (변화: +0.00 MB)
[FOXF]   [SARIMA] 완료  첫값=3.72e+08 (메모리: 1562.2 MB)
[FOXF]   [ETS] 시작  (메모리: 1562.2 MB)
[메모리] forecast_ets 실행 전: 1562.21 MB
[메모리] forecast_ets 실행 후: 1562.21 MB (변화: +0.01 MB)
[FOXF]   [ETS] 완료  첫값=3.69e+08 (메모리: 1562.2 MB)
[FOXF]   [Prophet] 시작  (메모리: 1562.2 MB)

11:10:36 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1562.21 MB

11:10:36 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1561.87 MB (변화: -0.35 MB)
[FOXF]   [Prophet] 완료  첫값=4.33e+08 (메모리: 1561.9 MB)
[FOXF]   [LSTM] 시작  (메모리: 1561.9 MB)
[메모리] forecast_lstm 실행 전: 1561.87 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1562.80 MB (변화: +0.93 MB)
[FOXF]   [LSTM] 완료  첫값=3.69e+08 (메모리: 1562.8 MB)
[FOXF]   [Theta] 시작  (메모리: 1562.8 MB)
[메모리] forecast_theta 실행 전: 1562.80 MB
[메모리] forecast_theta 실행 후: 1562.80 MB (변화: +0.00 MB)
[FOXF]   [Theta] 완료  첫값=3.63e+08 (메모리: 1562.8 MB)
[FOXF]   [DB] 88행 저장 완료
[PROGRESS] [ 168/500] ( 33.6%)  >>  CDMO
[CDMO]   40분기 | 2015-01-31 ~ 2024-10-31
[CDMO]   [SARIMA] 시작  (메모리: 1562.8 MB)
[메모리] forecast_sarima 실행 전: 1562.80 MB
[메모리] find_best_sarima_params 실행 전: 1562.80 MB
[메모리] find_best_sarima_params 실행 후: 1562.80 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1562.80 MB (변화: +0.00 MB)
[CDMO]   [SARIMA] 완료  첫값=4.23e+07 (메모리: 1562.8 MB)
[CDMO]   [ETS] 시작  (메모리: 1562.8 MB)
[메모리] forecast_ets 실행 전: 1562.80 MB
[메모리] forecast_ets 실행 후: 1562.81 MB (변화: +0.01 MB)
[CDMO]   [ETS] 완료  첫값=3.77e+07 (메모리: 1562.8 MB)
[CDMO]   [Prophet] 시작  (메모리: 1562.8 MB)

11:10:51 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1562.81 MB

11:10:51 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1562.82 MB (변화: +0.02 MB)
[CDMO]   [Prophet] 완료  첫값=3.87e+07 (메모리: 1562.8 MB)
[CDMO]   [LSTM] 시작  (메모리: 1562.8 MB)
[메모리] forecast_lstm 실행 전: 1562.82 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1561.68 MB (변화: -1.15 MB)
[CDMO]   [LSTM] 완료  첫값=3.73e+07 (메모리: 1561.7 MB)
[CDMO]   [Theta] 시작  (메모리: 1561.7 MB)
[메모리] forecast_theta 실행 전: 1561.68 MB
[메모리] forecast_theta 실행 후: 1561.68 MB (변화: +0.00 MB)
[CDMO]   [Theta] 완료  첫값=3.15e+07 (메모리: 1561.7 MB)
[CDMO]   [DB] 88행 저장 완료
[PROGRESS] [ 169/500] ( 33.8%)  >>  BBW
[BBW]   40분기 | 2016-04-02 ~ 2026-01-31
[BBW]   [SARIMA] 시작  (메모리: 1561.7 MB)
[메모리] forecast_sarima 실행 전: 1561.68 MB
[메모리] find_best_sarima_params 실행 전: 1561.68 MB
[메모리] find_best_sarima_params 실행 후: 1561.68 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1561.68 MB (변화: +0.00 MB)
[BBW]   [SARIMA] 완료  첫값=1.24e+08 (메모리: 1561.7 MB)
[BBW]   [ETS] 시작  (메모리: 1561.7 MB)
[메모리] forecast_ets 실행 전: 1561.68 MB
[메모리] forecast_ets 실행 후: 1561.69 MB (변화: +0.01 MB)
[BBW]   [ETS] 완료  첫값=1.25e+08 (메모리: 1561.7 MB)
[BBW]   [Prophet] 시작  (메모리: 1561.7 MB)

11:11:05 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1561.69 MB

11:11:05 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1561.70 MB (변화: +0.01 MB)
[BBW]   [Prophet] 완료  첫값=1.30e+08 (메모리: 1561.7 MB)
[BBW]   [LSTM] 시작  (메모리: 1561.7 MB)
[메모리] forecast_lstm 실행 전: 1561.70 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1562.69 MB (변화: +0.99 MB)
[BBW]   [LSTM] 완료  첫값=1.19e+08 (메모리: 1562.7 MB)
[BBW]   [Theta] 시작  (메모리: 1562.7 MB)
[메모리] forecast_theta 실행 전: 1562.69 MB
[메모리] forecast_theta 실행 후: 1562.69 MB (변화: +0.00 MB)
[BBW]   [Theta] 완료  첫값=1.23e+08 (메모리: 1562.7 MB)
[BBW]   [DB] 88행 저장 완료
[PROGRESS] [ 170/500] ( 34.0%)  >>  AXTI
[AXTI]   40분기 | 2016-03-31 ~ 2025-12-31
[AXTI]   [SARIMA] 시작  (메모리: 1562.7 MB)
[메모리] forecast_sarima 실행 전: 1562.69 MB
[메모리] find_best_sarima_params 실행 전: 1562.69 MB
[메모리] find_best_sarima_params 실행 후: 1562.69 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1562.69 MB (변화: +0.00 MB)
[AXTI]   [SARIMA] 완료  첫값=2.30e+07 (메모리: 1562.7 MB)
[AXTI]   [ETS] 시작  (메모리: 1562.7 MB)
[메모리] forecast_ets 실행 전: 1562.69 MB
[메모리] forecast_ets 실행 후: 1562.70 MB (변화: +0.00 MB)
[AXTI]   [ETS] 완료  첫값=2.22e+07 (메모리: 1562.7 MB)
[AXTI]   [Prophet] 시작  (메모리: 1562.7 MB)
[메모리] forecast_prophet 실행 전: 1562.70 MB

11:11:21 - cmdstanpy - INFO - Chain [1] start processing
11:11:21 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1562.72 MB (변화: +0.03 MB)
[AXTI]   [Prophet] 완료  첫값=2.63e+07 (메모리: 1562.7 MB)
[AXTI]   [LSTM] 시작  (메모리: 1562.7 MB)
[메모리] forecast_lstm 실행 전: 1562.72 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1562.70 MB (변화: -0.02 MB)
[AXTI]   [LSTM] 완료  첫값=2.84e+07 (메모리: 1562.7 MB)
[AXTI]   [Theta] 시작  (메모리: 1562.7 MB)
[메모리] forecast_theta 실행 전: 1562.70 MB
[메모리] forecast_theta 실행 후: 1562.70 MB (변화: +0.00 MB)
[AXTI]   [Theta] 완료  첫값=2.31e+07 (메모리: 1562.7 MB)
[AXTI]   [DB] 88행 저장 완료
[PROGRESS] [ 171/500] ( 34.2%)  >>  ICPT
[ICPT]   40분기 | 2013-12-31 ~ 2023-09-30
[ICPT]   [SARIMA] 시작  (메모리: 1562.7 MB)
[메모리] forecast_sarima 실행 전: 1562.70 MB
[메모리] find_best_sarima_params 실행 전: 1562.70 MB
[메모리] find_best_sarima_params 실행 후: 1562.70 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1562.70 MB (변화: +0.00 MB)
[ICPT]   [SARIMA] 완료  첫값=9.78e+07 (메모리: 1562.7 MB)
[ICPT]   [ETS] 시작  (메모리: 1562.7 MB)
[메모리] forecast_ets 실행 전: 1562.70 MB
[메모리] forecast_ets 실행 후: 1562.71 MB (변화: +0.01 MB)
[ICPT]   [ETS] 완료  첫값=1.01e+08 (메모리: 1562.7 MB)
[ICPT]   [Prophet] 시작  (메모리: 1562.7 MB)

11:11:40 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1562.71 MB

11:11:40 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1562.73 MB (변화: +0.02 MB)
[ICPT]   [Prophet] 완료  첫값=1.04e+08 (메모리: 1562.7 MB)
[ICPT]   [LSTM] 시작  (메모리: 1562.7 MB)
[메모리] forecast_lstm 실행 전: 1562.73 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1562.72 MB (변화: -0.02 MB)
[ICPT]   [LSTM] 완료  첫값=9.11e+07 (메모리: 1562.7 MB)
[ICPT]   [Theta] 시작  (메모리: 1562.7 MB)
[메모리] forecast_theta 실행 전: 1562.72 MB
[메모리] forecast_theta 실행 후: 1562.72 MB (변화: +0.00 MB)
[ICPT]   [Theta] 완료  첫값=9.37e+07 (메모리: 1562.7 MB)
[ICPT]   [DB] 88행 저장 완료
[PROGRESS] [ 172/500] ( 34.4%)  >>  TEN
[TEN]   40분기 | 2016-03-31 ~ 2025-12-31
[TEN]   [SARIMA] 시작  (메모리: 1562.7 MB)
[메모리] forecast_sarima 실행 전: 1562.72 MB
[메모리] find_best_sarima_params 실행 전: 1562.72 MB
[메모리] find_best_sarima_params 실행 후: 1562.72 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1562.72 MB (변화: +0.00 MB)
[TEN]   [SARIMA] 완료  첫값=2.25e+08 (메모리: 1562.7 MB)
[TEN]   [ETS] 시작  (메모리: 1562.7 MB)
[메모리] forecast_ets 실행 전: 1562.72 MB
[메모리] forecast_ets 실행 후: 1562.72 MB (변화: +0.00 MB)
[TEN]   [ETS] 완료  첫값=2.25e+08 (메모리: 1562.7 MB)
[TEN]   [Prophet] 시작  (메모리: 1562.7 MB)

11:11:53 - cmdstanpy - INFO - Chain [1] start processing
11:11:53 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1562.72 MB
[메모리] forecast_prophet 실행 후: 1562.73 MB (변화: +0.01 MB)
[TEN]   [Prophet] 완료  첫값=2.97e+07 (메모리: 1562.7 MB)
[TEN]   [LSTM] 시작  (메모리: 1562.7 MB)
[메모리] forecast_lstm 실행 전: 1562.73 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1561.48 MB (변화: -1.25 MB)
[TEN]   [LSTM] 완료  첫값=7.87e+08 (메모리: 1561.5 MB)
[TEN]   [Theta] 시작  (메모리: 1561.5 MB)
[메모리] forecast_theta 실행 전: 1561.48 MB
[메모리] forecast_theta 실행 후: 1561.48 MB (변화: +0.00 MB)
[TEN]   [Theta] 완료  첫값=2.29e+08 (메모리: 1561.5 MB)
[TEN]   [DB] 88행 저장 완료
[PROGRESS] [ 173/500] ( 34.6%)  >>  POLY
[POLY]   40분기 | 2012-09-29 ~ 2022-07-02
[POLY]   [SARIMA] 시작  (메모리: 1561.5 MB)
[메모리] forecast_sarima 실행 전: 1561.48 MB
[메모리] find_best_sarima_params 실행 전: 1561.48 MB
[메모리] find_best_sarima_params 실행 후: 1561.48 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1561.48 MB (변화: +0.00 MB)
[POLY]   [SARIMA] 완료  첫값=4.25e+08 (메모리: 1561.5 MB)
[POLY]   [ETS] 시작  (메모리: 1561.5 MB)
[메모리] forecast_ets 실행 전: 1561.48 MB
[메모리] forecast_ets 실행 후: 1561.48 MB (변화: +0.00 MB)
[POLY]   [ETS] 완료  첫값=4.60e+08 (메모리: 1561.5 MB)
[POLY]   [Prophet] 시작  (메모리: 1561.5 MB)

11:12:11 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1561.48 MB

11:12:11 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1561.87 MB (변화: +0.39 MB)
[POLY]   [Prophet] 완료  첫값=4.61e+08 (메모리: 1561.9 MB)
[POLY]   [LSTM] 시작  (메모리: 1561.9 MB)
[메모리] forecast_lstm 실행 전: 1561.87 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1561.96 MB (변화: +0.09 MB)
[POLY]   [LSTM] 완료  첫값=4.28e+08 (메모리: 1562.0 MB)
[POLY]   [Theta] 시작  (메모리: 1562.0 MB)
[메모리] forecast_theta 실행 전: 1561.96 MB
[메모리] forecast_theta 실행 후: 1561.96 MB (변화: +0.00 MB)
[POLY]   [Theta] 완료  첫값=4.58e+08 (메모리: 1562.0 MB)
[POLY]   [DB] 88행 저장 완료
[PROGRESS] [ 174/500] ( 34.8%)  >>  NEWP
[NEWP] [NEG-SKIP] [NEWP] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2016, 12, 31), datetime.date(2017, 6, 30), datetime.date(2017, 9, 30), datetime.date(2018, 3, 31), datetime.date(2018, 6, 30), datetime.date(2019, 6, 30)])
[PROGRESS] [ 175/500] ( 35.0%)  >>  CTLP
[CTLP]   40분기 | 2016-03-31 ~ 2025-12-31
[CTLP]   [SARIMA] 시작  (메모리: 1562.0 MB)
[메모리] forecast_sarima 실행 전: 1561.96 MB
[메모리] find_best_sarima_params 실행 전: 1561.96 MB
[메모리] find_best_sarima_params 실행 후: 1561.96 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1561.96 MB (변화: +0.00 MB)
[CTLP]   [SARIMA] 완료  첫값=8.56e+07 (메모리: 1562.0 MB)
[CTLP]   [ETS] 시작  (메모리: 1562.0 MB)
[메모리] forecast_ets 실행 전: 1561.96 MB
[메모리] forecast_ets 실행 후: 1561.96 MB (변화: +0.00 MB)
[CTLP]   [ETS] 완료  첫값=8.64e+07 (메모리: 1562.0 MB)
[CTLP]   [Prophet] 시작  (메모리: 1562.0 MB)

11:12:28 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1561.96 MB

11:12:28 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1561.50 MB (변화: -0.46 MB)
[CTLP]   [Prophet] 완료  첫값=8.25e+07 (메모리: 1561.5 MB)
[CTLP]   [LSTM] 시작  (메모리: 1561.5 MB)
[메모리] forecast_lstm 실행 전: 1561.50 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1562.46 MB (변화: +0.96 MB)
[CTLP]   [LSTM] 완료  첫값=7.55e+07 (메모리: 1562.5 MB)
[CTLP]   [Theta] 시작  (메모리: 1562.5 MB)
[메모리] forecast_theta 실행 전: 1562.46 MB
[메모리] forecast_theta 실행 후: 1562.46 MB (변화: +0.00 MB)
[CTLP]   [Theta] 완료  첫값=8.25e+07 (메모리: 1562.5 MB)
[CTLP]   [DB] 88행 저장 완료
[PROGRESS] [ 176/500] ( 35.2%)  >>  ABUS
[ABUS] [NEG-SKIP] [ABUS] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2016, 12, 31)])
[PROGRESS] [ 177/500] ( 35.4%)  >>  AMN
[AMN]   40분기 | 2016-03-31 ~ 2025-12-31
[AMN]   [SARIMA] 시작  (메모리: 1562.5 MB)
[메모리] forecast_sarima 실행 전: 1562.46 MB
[메모리] find_best_sarima_params 실행 전: 1562.46 MB
[메모리] find_best_sarima_params 실행 후: 1562.46 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1562.46 MB (변화: +0.00 MB)
[AMN]   [SARIMA] 완료  첫값=8.36e+08 (메모리: 1562.5 MB)
[AMN]   [ETS] 시작  (메모리: 1562.5 MB)
[메모리] forecast_ets 실행 전: 1562.46 MB
[메모리] forecast_ets 실행 후: 1562.46 MB (변화: +0.00 MB)
[AMN]   [ETS] 완료  첫값=7.89e+08 (메모리: 1562.5 MB)
[AMN]   [Prophet] 시작  (메모리: 1562.5 MB)

11:12:46 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1562.46 MB

11:12:46 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1562.49 MB (변화: +0.03 MB)
[AMN]   [Prophet] 완료  첫값=9.87e+08 (메모리: 1562.5 MB)
[AMN]   [LSTM] 시작  (메모리: 1562.5 MB)
[메모리] forecast_lstm 실행 전: 1562.49 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1562.45 MB (변화: -0.04 MB)
[AMN]   [LSTM] 완료  첫값=8.00e+08 (메모리: 1562.4 MB)
[AMN]   [Theta] 시작  (메모리: 1562.4 MB)
[메모리] forecast_theta 실행 전: 1562.45 MB
[메모리] forecast_theta 실행 후: 1562.45 MB (변화: +0.00 MB)
[AMN]   [Theta] 완료  첫값=7.90e+08 (메모리: 1562.4 MB)
[AMN]   [DB] 88행 저장 완료
[PROGRESS] [ 178/500] ( 35.6%)  >>  BTX
[BTX] [SKIP] [BTX] FMP에서 'sale' 데이터 없음
[PROGRESS] [ 179/500] ( 35.8%)  >>  WRN
[WRN]   40분기 | 2016-03-31 ~ 2025-12-31
[WRN]   [SARIMA] 시작  (메모리: 1562.4 MB)
[메모리] forecast_sarima 실행 전: 1562.45 MB
[메모리] find_best_sarima_params 실행 전: 1562.45 MB
[메모리] find_best_sarima_params 실행 후: 1562.46 MB (변화: +0.01 MB)
[메모리] forecast_sarima 실행 후: 1562.46 MB (변화: +0.01 MB)
[WRN]   [SARIMA] 완료  첫값=0.00e+00 (메모리: 1562.5 MB)
[WRN]   [ETS] 시작  (메모리: 1562.5 MB)
[메모리] forecast_ets 실행 전: 1562.46 MB
[메모리] forecast_ets 실행 후: 1562.46 MB (변화: +0.00 MB)
[WRN]   [ETS] 완료  첫값=0.00e+00 (메모리: 1562.5 MB)
[WRN]   [Prophet] 시작  (메모리: 1562.5 MB)
[메모리] forecast_prophet 실행 전: 1562.46 MB
[메모리] forecast_prophet 실행 후: 1561.49 MB (변화: -0.98 MB)
[WRN]   [Prophet] 완료  첫값=0.00e+00 (메모리: 1561.5 MB)
[WRN]   [LSTM] 시작  (메모리: 1561.5 MB)
[메모리] forecast_lstm 실행 전: 1561.49 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1562.70 MB (변화: +1.21 MB)
[WRN]   [LSTM] 완료  첫값=0.00e+00 (메모리: 1562.7 MB)
[WRN]   [Theta] 시작  (메모리: 1562.7 MB)
[메모리] forecast_theta 실행 전: 1562.70 MB
[메모리] forecast_theta 실행 후: 1562.70 MB (변화: +0.00 MB)
[WRN]   [Theta] 완료  첫값=0.00e+00 (메모리: 1562.7 MB)
[WRN]   [DB] 88행 저장 완료
[PROGRESS] [ 180/500] ( 36.0%)  >>  HAYN
[HAYN]   40분기 | 2014-09-30 ~ 2024-06-30
[HAYN]   [SARIMA] 시작  (메모리: 1562.7 MB)
[메모리] forecast_sarima 실행 전: 1562.70 MB
[메모리] find_best_sarima_params 실행 전: 1562.70 MB
[메모리] find_best_sarima_params 실행 후: 1562.70 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1562.70 MB (변화: +0.00 MB)
[HAYN]   [SARIMA] 완료  첫값=1.67e+08 (메모리: 1562.7 MB)
[HAYN]   [ETS] 시작  (메모리: 1562.7 MB)
[메모리] forecast_ets 실행 전: 1562.70 MB
[메모리] forecast_ets 실행 후: 1562.70 MB (변화: +0.00 MB)
[HAYN]   [ETS] 완료  첫값=1.63e+08 (메모리: 1562.7 MB)
[HAYN]   [Prophet] 시작  (메모리: 1562.7 MB)

11:13:24 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1562.70 MB

11:13:24 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1562.73 MB (변화: +0.03 MB)
[HAYN]   [Prophet] 완료  첫값=1.31e+08 (메모리: 1562.7 MB)
[HAYN]   [LSTM] 시작  (메모리: 1562.7 MB)
[메모리] forecast_lstm 실행 전: 1562.73 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1563.01 MB (변화: +0.28 MB)
[HAYN]   [LSTM] 완료  첫값=1.31e+08 (메모리: 1563.0 MB)
[HAYN]   [Theta] 시작  (메모리: 1563.0 MB)
[메모리] forecast_theta 실행 전: 1563.01 MB
[메모리] forecast_theta 실행 후: 1563.01 MB (변화: +0.00 MB)
[HAYN]   [Theta] 완료  첫값=1.54e+08 (메모리: 1563.0 MB)
[HAYN]   [DB] 88행 저장 완료
[PROGRESS] [ 181/500] ( 36.2%)  >>  ADTN
[ADTN]   40분기 | 2016-03-31 ~ 2025-12-31
[ADTN]   [SARIMA] 시작  (메모리: 1563.0 MB)
[메모리] forecast_sarima 실행 전: 1563.01 MB
[메모리] find_best_sarima_params 실행 전: 1563.01 MB
[메모리] find_best_sarima_params 실행 후: 1563.01 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1563.01 MB (변화: +0.00 MB)
[ADTN]   [SARIMA] 완료  첫값=2.92e+08 (메모리: 1563.0 MB)
[ADTN]   [ETS] 시작  (메모리: 1563.0 MB)
[메모리] forecast_ets 실행 전: 1563.01 MB
[메모리] forecast_ets 실행 후: 1563.02 MB (변화: +0.00 MB)
[ADTN]   [ETS] 완료  첫값=2.89e+08 (메모리: 1563.0 MB)
[ADTN]   [Prophet] 시작  (메모리: 1563.0 MB)

11:13:39 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1563.02 MB

11:13:39 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1563.05 MB (변화: +0.03 MB)
[ADTN]   [Prophet] 완료  첫값=2.72e+08 (메모리: 1563.0 MB)
[ADTN]   [LSTM] 시작  (메모리: 1563.0 MB)
[메모리] forecast_lstm 실행 전: 1563.05 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1562.55 MB (변화: -0.50 MB)
[ADTN]   [LSTM] 완료  첫값=2.52e+08 (메모리: 1562.5 MB)
[ADTN]   [Theta] 시작  (메모리: 1562.5 MB)
[메모리] forecast_theta 실행 전: 1562.55 MB
[메모리] forecast_theta 실행 후: 1562.55 MB (변화: +0.00 MB)
[ADTN]   [Theta] 완료  첫값=2.88e+08 (메모리: 1562.5 MB)
[ADTN]   [DB] 88행 저장 완료
[PROGRESS] [ 182/500] ( 36.4%)  >>  MDXG
[MDXG]   40분기 | 2016-03-31 ~ 2025-12-31
[MDXG]   [SARIMA] 시작  (메모리: 1562.5 MB)
[메모리] forecast_sarima 실행 전: 1562.55 MB
[메모리] find_best_sarima_params 실행 전: 1562.55 MB
[메모리] find_best_sarima_params 실행 후: 1562.55 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1562.55 MB (변화: +0.00 MB)
[MDXG]   [SARIMA] 완료  첫값=1.21e+08 (메모리: 1562.5 MB)
[MDXG]   [ETS] 시작  (메모리: 1562.5 MB)
[메모리] forecast_ets 실행 전: 1562.55 MB
[메모리] forecast_ets 실행 후: 1562.55 MB (변화: +0.01 MB)
[MDXG]   [ETS] 완료  첫값=1.06e+08 (메모리: 1562.6 MB)
[MDXG]   [Prophet] 시작  (메모리: 1562.6 MB)
[메모리] forecast_prophet 실행 전: 1562.55 MB

11:13:54 - cmdstanpy - INFO - Chain [1] start processing
11:13:54 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1562.57 MB (변화: +0.01 MB)
[MDXG]   [Prophet] 완료  첫값=8.95e+07 (메모리: 1562.6 MB)
[MDXG]   [LSTM] 시작  (메모리: 1562.6 MB)
[메모리] forecast_lstm 실행 전: 1562.57 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1563.48 MB (변화: +0.92 MB)
[MDXG]   [LSTM] 완료  첫값=8.65e+07 (메모리: 1563.5 MB)
[MDXG]   [Theta] 시작  (메모리: 1563.5 MB)
[메모리] forecast_theta 실행 전: 1563.48 MB
[메모리] forecast_theta 실행 후: 1563.48 MB (변화: +0.00 MB)
[MDXG]   [Theta] 완료  첫값=1.17e+08 (메모리: 1563.5 MB)
[MDXG]   [DB] 88행 저장 완료
[PROGRESS] [ 183/500] ( 36.6%)  >>  MTA
[MTA] [NEG-SKIP] [MTA] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2020, 5, 31)])
[PROGRESS] [ 184/500] ( 36.8%)  >>  BLDP
[BLDP]   40분기 | 2016-03-31 ~ 2025-12-31
[BLDP]   [SARIMA] 시작  (메모리: 1563.5 MB)
[메모리] forecast_sarima 실행 전: 1563.48 MB
[메모리] find_best_sarima_params 실행 전: 1563.48 MB
[메모리] find_best_sarima_params 실행 후: 1563.48 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1563.48 MB (변화: +0.00 MB)
[BLDP]   [SARIMA] 완료  첫값=1.43e+07 (메모리: 1563.5 MB)
[BLDP]   [ETS] 시작  (메모리: 1563.5 MB)
[메모리] forecast_ets 실행 전: 1563.48 MB
[메모리] forecast_ets 실행 후: 1563.49 MB (변화: +0.01 MB)
[BLDP]   [ETS] 완료  첫값=1.96e+07 (메모리: 1563.5 MB)
[BLDP]   [Prophet] 시작  (메모리: 1563.5 MB)

11:14:09 - cmdstanpy - INFO - Chain [1] start processing
11:14:09 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1563.49 MB
[메모리] forecast_prophet 실행 후: 1563.53 MB (변화: +0.04 MB)
[BLDP]   [Prophet] 완료  첫값=2.31e+07 (메모리: 1563.5 MB)
[BLDP]   [LSTM] 시작  (메모리: 1563.5 MB)
[메모리] forecast_lstm 실행 전: 1563.53 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1562.47 MB (변화: -1.05 MB)
[BLDP]   [LSTM] 완료  첫값=2.38e+07 (메모리: 1562.5 MB)
[BLDP]   [Theta] 시작  (메모리: 1561.4 MB)
[메모리] forecast_theta 실행 전: 1561.36 MB
[메모리] forecast_theta 실행 후: 1561.36 MB (변화: +0.00 MB)
[BLDP]   [Theta] 완료  첫값=1.94e+07 (메모리: 1561.4 MB)
[BLDP]   [DB] 88행 저장 완료
[PROGRESS] [ 185/500] ( 37.0%)  >>  OSTK
[OSTK]   40분기 | 2016-03-31 ~ 2025-12-31
[OSTK]   [SARIMA] 시작  (메모리: 1561.4 MB)
[메모리] forecast_sarima 실행 전: 1561.36 MB
[메모리] find_best_sarima_params 실행 전: 1561.36 MB
[메모리] find_best_sarima_params 실행 후: 1561.36 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1561.36 MB (변화: +0.00 MB)
[OSTK]   [SARIMA] 완료  첫값=2.52e+08 (메모리: 1561.4 MB)
[OSTK]   [ETS] 시작  (메모리: 1561.4 MB)
[메모리] forecast_ets 실행 전: 1561.36 MB
[메모리] forecast_ets 실행 후: 1561.36 MB (변화: +0.00 MB)
[OSTK]   [ETS] 완료  첫값=2.45e+08 (메모리: 1561.4 MB)
[OSTK]   [Prophet] 시작  (메모리: 1561.4 MB)

11:14:24 - cmdstanpy - INFO - Chain [1] start processing
11:14:24 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1561.36 MB
[메모리] forecast_prophet 실행 후: 1561.38 MB (변화: +0.02 MB)
[OSTK]   [Prophet] 완료  첫값=3.85e+08 (메모리: 1561.4 MB)
[OSTK]   [LSTM] 시작  (메모리: 1561.4 MB)
[메모리] forecast_lstm 실행 전: 1561.38 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1562.44 MB (변화: +1.05 MB)
[OSTK]   [LSTM] 완료  첫값=3.80e+08 (메모리: 1562.4 MB)
[OSTK]   [Theta] 시작  (메모리: 1562.4 MB)
[메모리] forecast_theta 실행 전: 1562.44 MB
[메모리] forecast_theta 실행 후: 1562.44 MB (변화: +0.00 MB)
[OSTK]   [Theta] 완료  첫값=2.70e+08 (메모리: 1562.4 MB)
[OSTK]   [DB] 88행 저장 완료
[PROGRESS] [ 186/500] ( 37.2%)  >>  NXRT
[NXRT]   40분기 | 2016-03-31 ~ 2025-12-31
[NXRT]   [SARIMA] 시작  (메모리: 1562.4 MB)
[메모리] forecast_sarima 실행 전: 1562.44 MB
[메모리] find_best_sarima_params 실행 전: 1562.44 MB
[메모리] find_best_sarima_params 실행 후: 1562.44 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1562.44 MB (변화: +0.00 MB)
[NXRT]   [SARIMA] 완료  첫값=6.51e+07 (메모리: 1562.4 MB)
[NXRT]   [ETS] 시작  (메모리: 1562.4 MB)
[메모리] forecast_ets 실행 전: 1562.44 MB
[메모리] forecast_ets 실행 후: 1562.45 MB (변화: +0.01 MB)
[NXRT]   [ETS] 완료  첫값=6.60e+07 (메모리: 1562.4 MB)
[NXRT]   [Prophet] 시작  (메모리: 1562.4 MB)

11:14:46 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1562.45 MB

11:14:46 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1562.46 MB (변화: +0.01 MB)
[NXRT]   [Prophet] 완료  첫값=6.56e+07 (메모리: 1562.5 MB)
[NXRT]   [LSTM] 시작  (메모리: 1562.5 MB)
[메모리] forecast_lstm 실행 전: 1562.46 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1562.45 MB (변화: -0.01 MB)
[NXRT]   [LSTM] 완료  첫값=6.56e+07 (메모리: 1562.4 MB)
[NXRT]   [Theta] 시작  (메모리: 1562.4 MB)
[메모리] forecast_theta 실행 전: 1562.45 MB
[메모리] forecast_theta 실행 후: 1562.45 MB (변화: +0.00 MB)
[NXRT]   [Theta] 완료  첫값=6.56e+07 (메모리: 1562.4 MB)
[NXRT]   [DB] 88행 저장 완료
[PROGRESS] [ 187/500] ( 37.4%)  >>  MYE
[MYE]   40분기 | 2016-03-31 ~ 2025-12-31
[MYE]   [SARIMA] 시작  (메모리: 1562.4 MB)
[메모리] forecast_sarima 실행 전: 1562.45 MB
[메모리] find_best_sarima_params 실행 전: 1562.45 MB
[메모리] find_best_sarima_params 실행 후: 1562.45 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1562.45 MB (변화: +0.00 MB)
[MYE]   [SARIMA] 완료  첫값=2.06e+08 (메모리: 1562.4 MB)
[MYE]   [ETS] 시작  (메모리: 1562.4 MB)
[메모리] forecast_ets 실행 전: 1562.45 MB
[메모리] forecast_ets 실행 후: 1562.45 MB (변화: +0.00 MB)
[MYE]   [ETS] 완료  첫값=2.21e+08 (메모리: 1562.5 MB)
[MYE]   [Prophet] 시작  (메모리: 1562.5 MB)

11:15:07 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1562.45 MB

11:15:07 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1562.46 MB (변화: +0.01 MB)
[MYE]   [Prophet] 완료  첫값=2.24e+08 (메모리: 1562.5 MB)
[MYE]   [LSTM] 시작  (메모리: 1562.5 MB)
[메모리] forecast_lstm 실행 전: 1562.46 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1562.43 MB (변화: -0.03 MB)
[MYE]   [LSTM] 완료  첫값=2.08e+08 (메모리: 1562.4 MB)
[MYE]   [Theta] 시작  (메모리: 1562.4 MB)
[메모리] forecast_theta 실행 전: 1562.43 MB
[메모리] forecast_theta 실행 후: 1562.43 MB (변화: +0.00 MB)
[MYE]   [Theta] 완료  첫값=2.20e+08 (메모리: 1562.4 MB)
[MYE]   [DB] 88행 저장 완료
[PROGRESS] [ 188/500] ( 37.6%)  >>  AMC
[AMC]   40분기 | 2016-03-31 ~ 2025-12-31
[AMC]   [SARIMA] 시작  (메모리: 1562.4 MB)
[메모리] forecast_sarima 실행 전: 1562.43 MB
[메모리] find_best_sarima_params 실행 전: 1562.43 MB
[메모리] find_best_sarima_params 실행 후: 1562.43 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1562.43 MB (변화: +0.00 MB)
[AMC]   [SARIMA] 완료  첫값=9.92e+08 (메모리: 1562.4 MB)
[AMC]   [ETS] 시작  (메모리: 1562.4 MB)
[메모리] forecast_ets 실행 전: 1562.43 MB
[메모리] forecast_ets 실행 후: 1562.44 MB (변화: +0.01 MB)
[AMC]   [ETS] 완료  첫값=1.15e+09 (메모리: 1562.4 MB)
[AMC]   [Prophet] 시작  (메모리: 1562.4 MB)

11:15:24 - cmdstanpy - INFO - Chain [1] start processing
11:15:24 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1562.44 MB
[메모리] forecast_prophet 실행 후: 1562.48 MB (변화: +0.04 MB)
[AMC]   [Prophet] 완료  첫값=1.08e+09 (메모리: 1562.5 MB)
[AMC]   [LSTM] 시작  (메모리: 1562.5 MB)
[메모리] forecast_lstm 실행 전: 1562.48 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1562.41 MB (변화: -0.07 MB)
[AMC]   [LSTM] 완료  첫값=1.12e+09 (메모리: 1562.4 MB)
[AMC]   [Theta] 시작  (메모리: 1562.4 MB)
[메모리] forecast_theta 실행 전: 1562.41 MB
[메모리] forecast_theta 실행 후: 1562.41 MB (변화: +0.00 MB)
[AMC]   [Theta] 완료  첫값=1.29e+09 (메모리: 1562.4 MB)
[AMC]   [DB] 88행 저장 완료
[PROGRESS] [ 189/500] ( 37.8%)  >>  APEI
[APEI]   40분기 | 2016-03-31 ~ 2025-12-31
[APEI]   [SARIMA] 시작  (메모리: 1562.4 MB)
[메모리] forecast_sarima 실행 전: 1562.41 MB
[메모리] find_best_sarima_params 실행 전: 1562.41 MB
[메모리] find_best_sarima_params 실행 후: 1562.41 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1562.41 MB (변화: +0.00 MB)
[APEI]   [SARIMA] 완료  첫값=1.61e+08 (메모리: 1562.4 MB)
[APEI]   [ETS] 시작  (메모리: 1562.4 MB)
[메모리] forecast_ets 실행 전: 1562.41 MB
[메모리] forecast_ets 실행 후: 1562.42 MB (변화: +0.01 MB)
[APEI]   [ETS] 완료  첫값=1.57e+08 (메모리: 1562.4 MB)
[APEI]   [Prophet] 시작  (메모리: 1562.4 MB)

11:15:38 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1562.42 MB

11:15:39 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1562.44 MB (변화: +0.02 MB)
[APEI]   [Prophet] 완료  첫값=1.71e+08 (메모리: 1562.4 MB)
[APEI]   [LSTM] 시작  (메모리: 1562.4 MB)
[메모리] forecast_lstm 실행 전: 1562.44 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1562.87 MB (변화: +0.43 MB)
[APEI]   [LSTM] 완료  첫값=1.62e+08 (메모리: 1562.9 MB)
[APEI]   [Theta] 시작  (메모리: 1562.9 MB)
[메모리] forecast_theta 실행 전: 1562.87 MB
[메모리] forecast_theta 실행 후: 1562.87 MB (변화: +0.00 MB)
[APEI]   [Theta] 완료  첫값=1.55e+08 (메모리: 1562.9 MB)
[APEI]   [DB] 88행 저장 완료
[PROGRESS] [ 190/500] ( 38.0%)  >>  BFS
[BFS]   40분기 | 2016-03-31 ~ 2025-12-31
[BFS]   [SARIMA] 시작  (메모리: 1562.9 MB)
[메모리] forecast_sarima 실행 전: 1562.87 MB
[메모리] find_best_sarima_params 실행 전: 1562.87 MB
[메모리] find_best_sarima_params 실행 후: 1562.87 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1562.87 MB (변화: +0.00 MB)
[BFS]   [SARIMA] 완료  첫값=7.62e+07 (메모리: 1562.9 MB)
[BFS]   [ETS] 시작  (메모리: 1562.9 MB)
[메모리] forecast_ets 실행 전: 1562.87 MB
[메모리] forecast_ets 실행 후: 1562.87 MB (변화: +0.00 MB)
[BFS]   [ETS] 완료  첫값=7.77e+07 (메모리: 1562.9 MB)
[BFS]   [Prophet] 시작  (메모리: 1562.9 MB)

11:15:57 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1562.87 MB

11:15:57 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1563.15 MB (변화: +0.28 MB)
[BFS]   [Prophet] 완료  첫값=7.41e+07 (메모리: 1563.1 MB)
[BFS]   [LSTM] 시작  (메모리: 1563.1 MB)
[메모리] forecast_lstm 실행 전: 1563.15 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1562.75 MB (변화: -0.40 MB)
[BFS]   [LSTM] 완료  첫값=7.93e+07 (메모리: 1562.8 MB)
[BFS]   [Theta] 시작  (메모리: 1562.8 MB)
[메모리] forecast_theta 실행 전: 1562.75 MB
[메모리] forecast_theta 실행 후: 1562.75 MB (변화: +0.00 MB)
[BFS]   [Theta] 완료  첫값=7.80e+07 (메모리: 1562.8 MB)
[BFS]   [DB] 88행 저장 완료
[PROGRESS] [ 191/500] ( 38.2%)  >>  PACB
[PACB]   40분기 | 2016-03-31 ~ 2025-12-31
[PACB]   [SARIMA] 시작  (메모리: 1562.8 MB)
[메모리] forecast_sarima 실행 전: 1562.75 MB
[메모리] find_best_sarima_params 실행 전: 1562.75 MB
[메모리] find_best_sarima_params 실행 후: 1562.75 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1562.75 MB (변화: +0.00 MB)
[PACB]   [SARIMA] 완료  첫값=4.46e+07 (메모리: 1562.8 MB)
[PACB]   [ETS] 시작  (메모리: 1562.8 MB)
[메모리] forecast_ets 실행 전: 1562.75 MB
[메모리] forecast_ets 실행 후: 1562.75 MB (변화: +0.00 MB)
[PACB]   [ETS] 완료  첫값=3.88e+07 (메모리: 1562.8 MB)
[PACB]   [Prophet] 시작  (메모리: 1562.8 MB)
[메모리] forecast_prophet 실행 전: 1562.75 MB

11:16:16 - cmdstanpy - INFO - Chain [1] start processing
11:16:16 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1562.78 MB (변화: +0.02 MB)
[PACB]   [Prophet] 완료  첫값=4.45e+07 (메모리: 1562.8 MB)
[PACB]   [LSTM] 시작  (메모리: 1562.8 MB)
[메모리] forecast_lstm 실행 전: 1562.78 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1563.14 MB (변화: +0.36 MB)
[PACB]   [LSTM] 완료  첫값=4.24e+07 (메모리: 1563.1 MB)
[PACB]   [Theta] 시작  (메모리: 1563.1 MB)
[메모리] forecast_theta 실행 전: 1563.14 MB
[메모리] forecast_theta 실행 후: 1563.14 MB (변화: +0.00 MB)
[PACB]   [Theta] 완료  첫값=3.85e+07 (메모리: 1563.1 MB)
[PACB]   [DB] 88행 저장 완료
[PROGRESS] [ 192/500] ( 38.4%)  >>  ERII
[ERII]   40분기 | 2016-03-31 ~ 2025-12-31
[ERII]   [SARIMA] 시작  (메모리: 1563.1 MB)
[메모리] forecast_sarima 실행 전: 1563.14 MB
[메모리] find_best_sarima_params 실행 전: 1563.14 MB
[메모리] find_best_sarima_params 실행 후: 1563.14 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1563.14 MB (변화: +0.00 MB)
[ERII]   [SARIMA] 완료  첫값=8.64e+06 (메모리: 1563.1 MB)
[ERII]   [ETS] 시작  (메모리: 1563.1 MB)
[메모리] forecast_ets 실행 전: 1563.14 MB
[메모리] forecast_ets 실행 후: 1563.14 MB (변화: +0.00 MB)
[ERII]   [ETS] 완료  첫값=8.69e+06 (메모리: 1563.1 MB)
[ERII]   [Prophet] 시작  (메모리: 1563.1 MB)

11:16:31 - cmdstanpy - INFO - Chain [1] start processing
11:16:31 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1563.14 MB
[메모리] forecast_prophet 실행 후: 1563.17 MB (변화: +0.03 MB)
[ERII]   [Prophet] 완료  첫값=3.94e+07 (메모리: 1563.2 MB)
[ERII]   [LSTM] 시작  (메모리: 1563.2 MB)
[메모리] forecast_lstm 실행 전: 1563.17 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1563.51 MB (변화: +0.34 MB)
[ERII]   [LSTM] 완료  첫값=3.42e+07 (메모리: 1563.5 MB)
[ERII]   [Theta] 시작  (메모리: 1563.5 MB)
[메모리] forecast_theta 실행 전: 1563.51 MB
[메모리] forecast_theta 실행 후: 1563.51 MB (변화: +0.00 MB)
[ERII]   [Theta] 완료  첫값=2.32e+07 (메모리: 1563.5 MB)
[ERII]   [DB] 88행 저장 완료
[PROGRESS] [ 193/500] ( 38.6%)  >>  NKTR
[NKTR]   40분기 | 2016-03-31 ~ 2025-12-31
[NKTR]   [SARIMA] 시작  (메모리: 1563.5 MB)
[메모리] forecast_sarima 실행 전: 1563.51 MB
[메모리] find_best_sarima_params 실행 전: 1563.51 MB
[메모리] find_best_sarima_params 실행 후: 1563.51 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1563.51 MB (변화: +0.00 MB)
[NKTR]   [SARIMA] 완료  첫값=1.64e+07 (메모리: 1563.5 MB)
[NKTR]   [ETS] 시작  (메모리: 1563.5 MB)
[메모리] forecast_ets 실행 전: 1563.51 MB
[메모리] forecast_ets 실행 후: 1563.51 MB (변화: +0.00 MB)
[NKTR]   [ETS] 완료  첫값=1.24e+07 (메모리: 1563.5 MB)
[NKTR]   [Prophet] 시작  (메모리: 1563.5 MB)

11:16:45 - cmdstanpy - INFO - Chain [1] start processing
11:16:45 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1563.51 MB
[메모리] forecast_prophet 실행 후: 1563.17 MB (변화: -0.34 MB)
[NKTR]   [Prophet] 완료  첫값=-6.36e+06 (메모리: 1563.2 MB)
[NKTR]   [LSTM] 시작  (메모리: 1563.2 MB)
[메모리] forecast_lstm 실행 전: 1563.17 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1564.18 MB (변화: +1.01 MB)
[NKTR]   [LSTM] 완료  첫값=1.83e+07 (메모리: 1564.2 MB)
[NKTR]   [Theta] 시작  (메모리: 1564.2 MB)
[메모리] forecast_theta 실행 전: 1564.18 MB
[메모리] forecast_theta 실행 후: 1564.18 MB (변화: +0.00 MB)
[NKTR]   [Theta] 완료  첫값=1.62e+07 (메모리: 1564.2 MB)
[NKTR]   [DB] 88행 저장 완료
[PROGRESS] [ 194/500] ( 38.8%)  >>  KALV
[KALV]   40분기 | 2016-03-31 ~ 2025-12-31
[KALV]   [SARIMA] 시작  (메모리: 1564.2 MB)
[메모리] forecast_sarima 실행 전: 1564.18 MB
[메모리] find_best_sarima_params 실행 전: 1564.18 MB
[메모리] find_best_sarima_params 실행 후: 1564.18 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1564.18 MB (변화: +0.00 MB)
[KALV]   [SARIMA] 오류응답: {'error': 'SARIMA 적합 실패 (발산 포함)'}
[KALV]   [ETS] 시작  (메모리: 1564.2 MB)
[메모리] forecast_ets 실행 전: 1564.18 MB
[메모리] forecast_ets 실행 후: 1564.18 MB (변화: +0.00 MB)
[KALV]   [ETS] 완료  첫값=1.03e+08 (메모리: 1564.2 MB)
[KALV]   [Prophet] 시작  (메모리: 1564.2 MB)

11:16:56 - cmdstanpy - INFO - Chain [1] start processing
11:16:56 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1564.18 MB
[메모리] forecast_prophet 실행 후: 1564.48 MB (변화: +0.30 MB)
[KALV]   [Prophet] 완료  첫값=6.89e+06 (메모리: 1564.5 MB)
[KALV]   [LSTM] 시작  (메모리: 1564.5 MB)
[메모리] forecast_lstm 실행 전: 1564.48 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1564.29 MB (변화: -0.18 MB)
[KALV]   [LSTM] 완료  첫값=4.44e+06 (메모리: 1564.3 MB)
[KALV]   [Theta] 시작  (메모리: 1564.3 MB)
[메모리] forecast_theta 실행 전: 1564.29 MB
[메모리] forecast_theta 실행 후: 1564.29 MB (변화: +0.00 MB)
[KALV]   [Theta] 완료  첫값=6.00e+07 (메모리: 1564.3 MB)
[KALV]   [DB] 80행 저장 완료
[PROGRESS] [ 195/500] ( 39.0%)  >>  RWT
[RWT] [NEG-SKIP] [RWT] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2020, 3, 31), datetime.date(2022, 6, 30), datetime.date(2022, 9, 30), datetime.date(2022, 12, 31)])
[PROGRESS] [ 196/500] ( 39.2%)  >>  KURA
[KURA]   40분기 | 2016-03-31 ~ 2025-12-31
[KURA]   [SARIMA] 시작  (메모리: 1564.3 MB)
[메모리] forecast_sarima 실행 전: 1564.29 MB
[메모리] find_best_sarima_params 실행 전: 1564.29 MB
[메모리] find_best_sarima_params 실행 후: 1564.29 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1564.29 MB (변화: +0.00 MB)
[KURA]   [SARIMA] 완료  첫값=9.12e+06 (메모리: 1564.3 MB)
[KURA]   [ETS] 시작  (메모리: 1564.3 MB)
[메모리] forecast_ets 실행 전: 1564.29 MB
[메모리] forecast_ets 실행 후: 1564.30 MB (변화: +0.00 MB)
[KURA]   [ETS] 완료  첫값=1.69e+07 (메모리: 1564.3 MB)
[KURA]   [Prophet] 시작  (메모리: 1564.3 MB)

11:17:09 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1564.30 MB

11:17:09 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1564.32 MB (변화: +0.03 MB)
[KURA]   [Prophet] 완료  첫값=1.09e+07 (메모리: 1564.3 MB)
[KURA]   [LSTM] 시작  (메모리: 1564.3 MB)
[메모리] forecast_lstm 실행 전: 1564.32 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1565.27 MB (변화: +0.95 MB)
[KURA]   [LSTM] 완료  첫값=2.65e+07 (메모리: 1565.3 MB)
[KURA]   [Theta] 시작  (메모리: 1565.3 MB)
[메모리] forecast_theta 실행 전: 1565.27 MB
[메모리] forecast_theta 실행 후: 1565.27 MB (변화: +0.00 MB)
[KURA]   [Theta] 완료  첫값=1.78e+07 (메모리: 1565.3 MB)
[KURA]   [DB] 88행 저장 완료
[PROGRESS] [ 197/500] ( 39.4%)  >>  WLKP
[WLKP]   40분기 | 2016-03-31 ~ 2025-12-31
[WLKP]   [SARIMA] 시작  (메모리: 1565.3 MB)
[메모리] forecast_sarima 실행 전: 1565.27 MB
[메모리] find_best_sarima_params 실행 전: 1565.27 MB
[메모리] find_best_sarima_params 실행 후: 1565.27 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1565.27 MB (변화: +0.00 MB)
[WLKP]   [SARIMA] 완료  첫값=3.23e+08 (메모리: 1565.3 MB)
[WLKP]   [ETS] 시작  (메모리: 1565.3 MB)
[메모리] forecast_ets 실행 전: 1565.27 MB
[메모리] forecast_ets 실행 후: 1565.27 MB (변화: +0.00 MB)
[WLKP]   [ETS] 완료  첫값=3.03e+08 (메모리: 1565.3 MB)
[WLKP]   [Prophet] 시작  (메모리: 1565.3 MB)

11:17:28 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1565.27 MB

11:17:28 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1565.30 MB (변화: +0.02 MB)
[WLKP]   [Prophet] 완료  첫값=3.17e+08 (메모리: 1565.3 MB)
[WLKP]   [LSTM] 시작  (메모리: 1565.3 MB)
[메모리] forecast_lstm 실행 전: 1565.30 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1565.21 MB (변화: -0.09 MB)
[WLKP]   [LSTM] 완료  첫값=3.02e+08 (메모리: 1565.2 MB)
[WLKP]   [Theta] 시작  (메모리: 1565.2 MB)
[메모리] forecast_theta 실행 전: 1565.21 MB
[메모리] forecast_theta 실행 후: 1565.21 MB (변화: +0.00 MB)
[WLKP]   [Theta] 완료  첫값=3.23e+08 (메모리: 1565.2 MB)
[WLKP]   [DB] 88행 저장 완료
[PROGRESS] [ 198/500] ( 39.6%)  >>  MMX
[MMX]   40분기 | 2012-09-30 ~ 2022-09-30
[MMX]   [SARIMA] 시작  (메모리: 1565.2 MB)
[메모리] forecast_sarima 실행 전: 1565.21 MB
[메모리] find_best_sarima_params 실행 전: 1565.21 MB
[메모리] find_best_sarima_params 실행 후: 1565.21 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1565.21 MB (변화: +0.00 MB)
[MMX]   [SARIMA] 완료  첫값=1.80e+07 (메모리: 1565.2 MB)
[MMX]   [ETS] 시작  (메모리: 1565.2 MB)
[메모리] forecast_ets 실행 전: 1565.21 MB
[메모리] forecast_ets 실행 후: 1565.22 MB (변화: +0.00 MB)
[MMX]   [ETS] 완료  첫값=1.70e+07 (메모리: 1565.2 MB)
[MMX]   [Prophet] 시작  (메모리: 1565.2 MB)

11:17:44 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1565.22 MB

11:17:44 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1565.24 MB (변화: +0.02 MB)
[MMX]   [Prophet] 완료  첫값=1.53e+07 (메모리: 1565.2 MB)
[MMX]   [LSTM] 시작  (메모리: 1565.2 MB)
[메모리] forecast_lstm 실행 전: 1565.24 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1564.75 MB (변화: -0.49 MB)
[MMX]   [LSTM] 완료  첫값=1.80e+07 (메모리: 1564.8 MB)
[MMX]   [Theta] 시작  (메모리: 1564.8 MB)
[메모리] forecast_theta 실행 전: 1564.75 MB
[메모리] forecast_theta 실행 후: 1564.75 MB (변화: +0.00 MB)
[MMX]   [Theta] 완료  첫값=1.68e+07 (메모리: 1564.8 MB)
[MMX]   [DB] 88행 저장 완료
[PROGRESS] [ 199/500] ( 39.8%)  >>  RZLV
[RZLV] [SKIP] [RZLV] 'sale' 관측치 부족: 7개 < 최소 28개
[PROGRESS] [ 200/500] ( 40.0%)  >>  HSC
[HSC]   40분기 | 2015-12-31 ~ 2025-12-31
[HSC]   [SARIMA] 시작  (메모리: 1564.8 MB)
[메모리] forecast_sarima 실행 전: 1564.75 MB
[메모리] find_best_sarima_params 실행 전: 1564.75 MB
[메모리] find_best_sarima_params 실행 후: 1564.75 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1564.75 MB (변화: +0.00 MB)
[HSC]   [SARIMA] 완료  첫값=5.64e+08 (메모리: 1564.8 MB)
[HSC]   [ETS] 시작  (메모리: 1564.8 MB)
[메모리] forecast_ets 실행 전: 1564.75 MB
[메모리] forecast_ets 실행 후: 1564.76 MB (변화: +0.01 MB)
[HSC]   [ETS] 완료  첫값=5.56e+08 (메모리: 1564.8 MB)
[HSC]   [Prophet] 시작  (메모리: 1564.8 MB)

11:18:00 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1564.76 MB

11:18:00 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1564.79 MB (변화: +0.03 MB)
[HSC]   [Prophet] 완료  첫값=5.97e+08 (메모리: 1564.8 MB)
[HSC]   [LSTM] 시작  (메모리: 1564.8 MB)
[메모리] forecast_lstm 실행 전: 1564.79 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1565.79 MB (변화: +1.00 MB)
[HSC]   [LSTM] 완료  첫값=5.81e+08 (메모리: 1565.8 MB)
[HSC]   [Theta] 시작  (메모리: 1565.8 MB)
[메모리] forecast_theta 실행 전: 1565.79 MB
[메모리] forecast_theta 실행 후: 1565.79 MB (변화: +0.00 MB)
[HSC]   [Theta] 완료  첫값=5.44e+08 (메모리: 1565.8 MB)
[HSC]   [DB] 88행 저장 완료
[PROGRESS] [ 201/500] ( 40.2%)  >>  KE
[KE]   40분기 | 2016-03-31 ~ 2025-12-31
[KE]   [SARIMA] 시작  (메모리: 1565.8 MB)
[메모리] forecast_sarima 실행 전: 1565.79 MB
[메모리] find_best_sarima_params 실행 전: 1565.79 MB
[메모리] find_best_sarima_params 실행 후: 1565.79 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1565.79 MB (변화: +0.00 MB)
[KE]   [SARIMA] 완료  첫값=3.45e+08 (메모리: 1565.8 MB)
[KE]   [ETS] 시작  (메모리: 1565.8 MB)
[메모리] forecast_ets 실행 전: 1565.79 MB
[메모리] forecast_ets 실행 후: 1565.79 MB (변화: +0.00 MB)
[KE]   [ETS] 완료  첫값=3.59e+08 (메모리: 1565.8 MB)
[KE]   [Prophet] 시작  (메모리: 1565.8 MB)

11:18:16 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1565.79 MB

11:18:16 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1565.79 MB (변화: +0.00 MB)
[KE]   [Prophet] 완료  첫값=4.37e+08 (메모리: 1565.8 MB)
[KE]   [LSTM] 시작  (메모리: 1565.8 MB)
[메모리] forecast_lstm 실행 전: 1565.79 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1564.49 MB (변화: -1.30 MB)
[KE]   [LSTM] 완료  첫값=3.99e+08 (메모리: 1564.5 MB)
[KE]   [Theta] 시작  (메모리: 1564.5 MB)
[메모리] forecast_theta 실행 전: 1564.49 MB
[메모리] forecast_theta 실행 후: 1564.49 MB (변화: +0.00 MB)
[KE]   [Theta] 완료  첫값=3.56e+08 (메모리: 1564.5 MB)
[KE]   [DB] 88행 저장 완료
[PROGRESS] [ 202/500] ( 40.4%)  >>  BGM
[BGM] [SKIP] [BGM] 'sale' 관측치 부족: 2개 < 최소 28개
[PROGRESS] [ 203/500] ( 40.6%)  >>  CRY
[CRY]   40분기 | 2013-06-30 ~ 2025-12-31
[CRY]   [SARIMA] 시작  (메모리: 1564.5 MB)
[메모리] forecast_sarima 실행 전: 1564.49 MB
[메모리] find_best_sarima_params 실행 전: 1564.49 MB
[메모리] find_best_sarima_params 실행 후: 1564.49 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1564.49 MB (변화: +0.00 MB)
[CRY]   [SARIMA] 완료  첫값=1.21e+08 (메모리: 1564.5 MB)
[CRY]   [ETS] 시작  (메모리: 1564.5 MB)
[메모리] forecast_ets 실행 전: 1564.49 MB
[메모리] forecast_ets 실행 후: 1564.50 MB (변화: +0.01 MB)
[CRY]   [ETS] 완료  첫값=1.17e+08 (메모리: 1564.5 MB)
[CRY]   [Prophet] 시작  (메모리: 1564.5 MB)

11:18:32 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1564.50 MB

11:18:32 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1564.53 MB (변화: +0.03 MB)
[CRY]   [Prophet] 완료  첫값=1.15e+08 (메모리: 1564.5 MB)
[CRY]   [LSTM] 시작  (메모리: 1564.5 MB)
[메모리] forecast_lstm 실행 전: 1564.53 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1565.56 MB (변화: +1.03 MB)
[CRY]   [LSTM] 완료  첫값=1.29e+08 (메모리: 1565.6 MB)
[CRY]   [Theta] 시작  (메모리: 1565.6 MB)
[메모리] forecast_theta 실행 전: 1565.56 MB
[메모리] forecast_theta 실행 후: 1565.56 MB (변화: +0.00 MB)
[CRY]   [Theta] 완료  첫값=1.13e+08 (메모리: 1565.6 MB)
[CRY]   [DB] 88행 저장 완료
[PROGRESS] [ 204/500] ( 40.8%)  >>  WSR
[WSR]   40분기 | 2016-03-31 ~ 2025-12-31
[WSR]   [SARIMA] 시작  (메모리: 1565.6 MB)
[메모리] forecast_sarima 실행 전: 1565.56 MB
[메모리] find_best_sarima_params 실행 전: 1565.56 MB
[메모리] find_best_sarima_params 실행 후: 1565.56 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1565.56 MB (변화: +0.00 MB)
[WSR]   [SARIMA] 완료  첫값=4.45e+07 (메모리: 1565.6 MB)
[WSR]   [ETS] 시작  (메모리: 1565.6 MB)
[메모리] forecast_ets 실행 전: 1565.56 MB
[메모리] forecast_ets 실행 후: 1565.56 MB (변화: +0.00 MB)
[WSR]   [ETS] 완료  첫값=4.35e+07 (메모리: 1565.6 MB)
[WSR]   [Prophet] 시작  (메모리: 1565.6 MB)

11:18:52 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1565.56 MB

11:18:52 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1565.72 MB (변화: +0.16 MB)
[WSR]   [Prophet] 완료  첫값=4.09e+07 (메모리: 1565.7 MB)
[WSR]   [LSTM] 시작  (메모리: 1565.7 MB)
[메모리] forecast_lstm 실행 전: 1565.72 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1565.00 MB (변화: -0.73 MB)
[WSR]   [LSTM] 완료  첫값=3.98e+07 (메모리: 1565.0 MB)
[WSR]   [Theta] 시작  (메모리: 1565.0 MB)
[메모리] forecast_theta 실행 전: 1565.00 MB
[메모리] forecast_theta 실행 후: 1565.00 MB (변화: +0.00 MB)
[WSR]   [Theta] 완료  첫값=4.33e+07 (메모리: 1565.0 MB)
[WSR]   [DB] 88행 저장 완료
[PROGRESS] [ 205/500] ( 41.0%)  >>  GDEN
[GDEN]   40분기 | 2016-03-31 ~ 2025-12-31
[GDEN]   [SARIMA] 시작  (메모리: 1565.0 MB)
[메모리] forecast_sarima 실행 전: 1565.00 MB
[메모리] find_best_sarima_params 실행 전: 1565.00 MB
[메모리] find_best_sarima_params 실행 후: 1565.00 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1565.00 MB (변화: +0.00 MB)
[GDEN]   [SARIMA] 완료  첫값=1.55e+08 (메모리: 1565.0 MB)
[GDEN]   [ETS] 시작  (메모리: 1565.0 MB)
[메모리] forecast_ets 실행 전: 1565.00 MB
[메모리] forecast_ets 실행 후: 1565.00 MB (변화: +0.01 MB)
[GDEN]   [ETS] 완료  첫값=1.58e+08 (메모리: 1565.0 MB)
[GDEN]   [Prophet] 시작  (메모리: 1565.0 MB)

11:19:06 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1565.00 MB

11:19:06 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1565.02 MB (변화: +0.02 MB)
[GDEN]   [Prophet] 완료  첫값=2.39e+08 (메모리: 1565.0 MB)
[GDEN]   [LSTM] 시작  (메모리: 1565.0 MB)
[메모리] forecast_lstm 실행 전: 1565.02 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1565.96 MB (변화: +0.93 MB)
[GDEN]   [LSTM] 완료  첫값=2.01e+08 (메모리: 1566.0 MB)
[GDEN]   [Theta] 시작  (메모리: 1566.0 MB)
[메모리] forecast_theta 실행 전: 1565.96 MB
[메모리] forecast_theta 실행 후: 1565.96 MB (변화: +0.00 MB)
[GDEN]   [Theta] 완료  첫값=1.57e+08 (메모리: 1566.0 MB)
[GDEN]   [DB] 88행 저장 완료
[PROGRESS] [ 206/500] ( 41.2%)  >>  AIOT
[AIOT]   40분기 | 2016-03-31 ~ 2025-12-31
[AIOT]   [SARIMA] 시작  (메모리: 1566.0 MB)
[메모리] forecast_sarima 실행 전: 1565.96 MB
[메모리] find_best_sarima_params 실행 전: 1565.96 MB
[메모리] find_best_sarima_params 실행 후: 1565.96 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1565.96 MB (변화: +0.00 MB)
[AIOT]   [SARIMA] 완료  첫값=1.13e+08 (메모리: 1566.0 MB)
[AIOT]   [ETS] 시작  (메모리: 1566.0 MB)
[메모리] forecast_ets 실행 전: 1565.96 MB
[메모리] forecast_ets 실행 후: 1565.96 MB (변화: +0.00 MB)
[AIOT]   [ETS] 완료  첫값=1.01e+08 (메모리: 1566.0 MB)
[AIOT]   [Prophet] 시작  (메모리: 1566.0 MB)

11:19:26 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1565.96 MB

11:19:26 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1565.98 MB (변화: +0.02 MB)
[AIOT]   [Prophet] 완료  첫값=8.54e+07 (메모리: 1566.0 MB)
[AIOT]   [LSTM] 시작  (메모리: 1566.0 MB)
[메모리] forecast_lstm 실행 전: 1565.98 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1566.09 MB (변화: +0.11 MB)
[AIOT]   [LSTM] 완료  첫값=1.59e+08 (메모리: 1566.1 MB)
[AIOT]   [Theta] 시작  (메모리: 1566.1 MB)
[메모리] forecast_theta 실행 전: 1566.09 MB
[메모리] forecast_theta 실행 후: 1566.09 MB (변화: +0.00 MB)
[AIOT]   [Theta] 완료  첫값=1.12e+08 (메모리: 1566.1 MB)
[AIOT]   [DB] 88행 저장 완료
[PROGRESS] [ 207/500] ( 41.4%)  >>  ATXS
[ATXS]   40분기 | 2015-12-31 ~ 2025-09-30
[ATXS]   [SARIMA] 시작  (메모리: 1566.1 MB)
[메모리] forecast_sarima 실행 전: 1566.09 MB
[메모리] find_best_sarima_params 실행 전: 1566.09 MB
[메모리] find_best_sarima_params 실행 후: 1566.09 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1566.09 MB (변화: +0.00 MB)
[ATXS]   [SARIMA] 완료  첫값=7.06e+05 (메모리: 1566.1 MB)
[ATXS]   [ETS] 시작  (메모리: 1566.1 MB)
[메모리] forecast_ets 실행 전: 1566.09 MB
[메모리] forecast_ets 실행 후: 1566.10 MB (변화: +0.01 MB)
[ATXS]   [ETS] 완료  첫값=6.64e+05 (메모리: 1566.1 MB)
[ATXS]   [Prophet] 시작  (메모리: 1566.1 MB)

11:19:41 - cmdstanpy - INFO - Chain [1] start processing
11:19:41 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1566.10 MB
[메모리] forecast_prophet 실행 후: 1566.12 MB (변화: +0.03 MB)
[ATXS]   [Prophet] 완료  첫값=5.99e+04 (메모리: 1566.1 MB)
[ATXS]   [LSTM] 시작  (메모리: 1566.1 MB)
[메모리] forecast_lstm 실행 전: 1566.12 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1566.36 MB (변화: +0.23 MB)
[ATXS]   [LSTM] 완료  첫값=2.10e+04 (메모리: 1566.4 MB)
[ATXS]   [Theta] 시작  (메모리: 1566.4 MB)
[메모리] forecast_theta 실행 전: 1566.36 MB
[메모리] forecast_theta 실행 후: 1566.36 MB (변화: +0.00 MB)
[ATXS]   [Theta] 완료  첫값=4.40e+04 (메모리: 1566.4 MB)
[ATXS]   [DB] 88행 저장 완료
[PROGRESS] [ 208/500] ( 41.6%)  >>  GYRE
[GYRE] [NEG-SKIP] [GYRE] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2018, 12, 31)])
[PROGRESS] [ 209/500] ( 41.8%)  >>  BZH
[BZH]   40분기 | 2016-03-31 ~ 2025-12-31
[BZH]   [SARIMA] 시작  (메모리: 1566.4 MB)
[메모리] forecast_sarima 실행 전: 1566.36 MB
[메모리] find_best_sarima_params 실행 전: 1566.36 MB
[메모리] find_best_sarima_params 실행 후: 1566.36 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1566.36 MB (변화: +0.00 MB)
[BZH]   [SARIMA] 완료  첫값=5.60e+08 (메모리: 1566.4 MB)
[BZH]   [ETS] 시작  (메모리: 1566.4 MB)
[메모리] forecast_ets 실행 전: 1566.36 MB
[메모리] forecast_ets 실행 후: 1566.36 MB (변화: +0.00 MB)
[BZH]   [ETS] 완료  첫값=5.51e+08 (메모리: 1566.4 MB)
[BZH]   [Prophet] 시작  (메모리: 1566.4 MB)

11:20:02 - cmdstanpy - INFO - Chain [1] start processing
11:20:02 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1566.36 MB
[메모리] forecast_prophet 실행 후: 1566.39 MB (변화: +0.03 MB)
[BZH]   [Prophet] 완료  첫값=5.95e+08 (메모리: 1566.4 MB)
[BZH]   [LSTM] 시작  (메모리: 1566.4 MB)
[메모리] forecast_lstm 실행 전: 1566.39 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1567.04 MB (변화: +0.65 MB)
[BZH]   [LSTM] 완료  첫값=5.59e+08 (메모리: 1567.0 MB)
[BZH]   [Theta] 시작  (메모리: 1567.0 MB)
[메모리] forecast_theta 실행 전: 1567.04 MB
[메모리] forecast_theta 실행 후: 1567.04 MB (변화: +0.00 MB)
[BZH]   [Theta] 완료  첫값=5.08e+08 (메모리: 1567.0 MB)
[BZH]   [DB] 88행 저장 완료
[PROGRESS] [ 210/500] ( 42.0%)  >>  RGNX
[RGNX]   40분기 | 2016-03-31 ~ 2025-12-31
[RGNX]   [SARIMA] 시작  (메모리: 1567.0 MB)
[메모리] forecast_sarima 실행 전: 1567.04 MB
[메모리] find_best_sarima_params 실행 전: 1567.04 MB
[메모리] find_best_sarima_params 실행 후: 1567.04 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1567.04 MB (변화: +0.00 MB)
[RGNX]   [SARIMA] 완료  첫값=4.53e+07 (메모리: 1567.0 MB)
[RGNX]   [ETS] 시작  (메모리: 1567.0 MB)
[메모리] forecast_ets 실행 전: 1567.04 MB
[메모리] forecast_ets 실행 후: 1567.04 MB (변화: +0.00 MB)
[RGNX]   [ETS] 완료  첫값=1.99e+07 (메모리: 1567.0 MB)
[RGNX]   [Prophet] 시작  (메모리: 1567.0 MB)

11:20:15 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1567.04 MB

11:20:15 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1567.07 MB (변화: +0.02 MB)
[RGNX]   [Prophet] 완료  첫값=5.05e+07 (메모리: 1567.1 MB)
[RGNX]   [LSTM] 시작  (메모리: 1567.1 MB)
[메모리] forecast_lstm 실행 전: 1567.07 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1566.51 MB (변화: -0.56 MB)
[RGNX]   [LSTM] 완료  첫값=3.88e+07 (메모리: 1566.5 MB)
[RGNX]   [Theta] 시작  (메모리: 1566.5 MB)
[메모리] forecast_theta 실행 전: 1566.51 MB
[메모리] forecast_theta 실행 후: 1566.51 MB (변화: +0.00 MB)
[RGNX]   [Theta] 완료  첫값=3.39e+07 (메모리: 1566.5 MB)
[RGNX]   [DB] 88행 저장 완료
[PROGRESS] [ 211/500] ( 42.2%)  >>  FFHL
[FFHL]   40분기 | 2012-06-30 ~ 2022-06-30
[FFHL]   [SARIMA] 시작  (메모리: 1566.5 MB)
[메모리] forecast_sarima 실행 전: 1566.51 MB
[메모리] find_best_sarima_params 실행 전: 1566.51 MB
[메모리] find_best_sarima_params 실행 후: 1566.51 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1566.51 MB (변화: +0.00 MB)
[FFHL]   [SARIMA] 완료  첫값=9.48e+07 (메모리: 1566.5 MB)
[FFHL]   [ETS] 시작  (메모리: 1566.5 MB)
[메모리] forecast_ets 실행 전: 1566.51 MB
[메모리] forecast_ets 실행 후: 1566.52 MB (변화: +0.01 MB)
[FFHL]   [ETS] 완료  첫값=9.90e+07 (메모리: 1566.5 MB)
[FFHL]   [Prophet] 시작  (메모리: 1566.5 MB)

11:20:29 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1566.52 MB

11:20:30 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1566.53 MB (변화: +0.01 MB)
[FFHL]   [Prophet] 완료  첫값=9.87e+07 (메모리: 1566.5 MB)
[FFHL]   [LSTM] 시작  (메모리: 1566.5 MB)
[메모리] forecast_lstm 실행 전: 1566.53 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1567.49 MB (변화: +0.96 MB)
[FFHL]   [LSTM] 완료  첫값=9.03e+07 (메모리: 1567.5 MB)
[FFHL]   [Theta] 시작  (메모리: 1567.5 MB)
[메모리] forecast_theta 실행 전: 1567.49 MB
[메모리] forecast_theta 실행 후: 1567.49 MB (변화: +0.00 MB)
[FFHL]   [Theta] 완료  첫값=9.46e+07 (메모리: 1567.5 MB)
[FFHL]   [DB] 88행 저장 완료
[PROGRESS] [ 212/500] ( 42.4%)  >>  CXP
[CXP]   40분기 | 2011-12-31 ~ 2021-09-30
[CXP]   [SARIMA] 시작  (메모리: 1566.4 MB)
[메모리] forecast_sarima 실행 전: 1566.38 MB
[메모리] find_best_sarima_params 실행 전: 1566.38 MB
[메모리] find_best_sarima_params 실행 후: 1566.38 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1566.38 MB (변화: +0.00 MB)
[CXP]   [SARIMA] 완료  첫값=6.33e+07 (메모리: 1566.4 MB)
[CXP]   [ETS] 시작  (메모리: 1566.4 MB)
[메모리] forecast_ets 실행 전: 1566.38 MB
[메모리] forecast_ets 실행 후: 1566.39 MB (변화: +0.01 MB)
[CXP]   [ETS] 완료  첫값=5.58e+07 (메모리: 1566.4 MB)
[CXP]   [Prophet] 시작  (메모리: 1566.4 MB)

11:20:45 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1566.39 MB

11:20:45 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1566.41 MB (변화: +0.03 MB)
[CXP]   [Prophet] 완료  첫값=5.15e+07 (메모리: 1566.4 MB)
[CXP]   [LSTM] 시작  (메모리: 1566.4 MB)
[메모리] forecast_lstm 실행 전: 1566.41 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1566.38 MB (변화: -0.03 MB)
[CXP]   [LSTM] 완료  첫값=6.59e+07 (메모리: 1566.4 MB)
[CXP]   [Theta] 시작  (메모리: 1566.4 MB)
[메모리] forecast_theta 실행 전: 1566.38 MB
[메모리] forecast_theta 실행 후: 1566.38 MB (변화: +0.00 MB)
[CXP]   [Theta] 완료  첫값=5.67e+07 (메모리: 1566.4 MB)
[CXP]   [DB] 88행 저장 완료
[PROGRESS] [ 213/500] ( 42.6%)  >>  LXU
[LXU]   40분기 | 2016-03-31 ~ 2025-12-31
[LXU]   [SARIMA] 시작  (메모리: 1566.4 MB)
[메모리] forecast_sarima 실행 전: 1566.38 MB
[메모리] find_best_sarima_params 실행 전: 1566.38 MB
[메모리] find_best_sarima_params 실행 후: 1566.38 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1566.38 MB (변화: +0.00 MB)
[LXU]   [SARIMA] 완료  첫값=1.54e+08 (메모리: 1566.4 MB)
[LXU]   [ETS] 시작  (메모리: 1566.4 MB)
[메모리] forecast_ets 실행 전: 1566.38 MB
[메모리] forecast_ets 실행 후: 1566.39 MB (변화: +0.01 MB)
[LXU]   [ETS] 완료  첫값=1.76e+08 (메모리: 1566.4 MB)
[LXU]   [Prophet] 시작  (메모리: 1566.4 MB)

11:21:04 - cmdstanpy - INFO - Chain [1] start processing
11:21:04 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1566.39 MB
[메모리] forecast_prophet 실행 후: 1566.41 MB (변화: +0.02 MB)
[LXU]   [Prophet] 완료  첫값=1.67e+08 (메모리: 1566.4 MB)
[LXU]   [LSTM] 시작  (메모리: 1566.4 MB)
[메모리] forecast_lstm 실행 전: 1566.41 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1567.40 MB (변화: +0.99 MB)
[LXU]   [LSTM] 완료  첫값=1.43e+08 (메모리: 1567.4 MB)
[LXU]   [Theta] 시작  (메모리: 1567.4 MB)
[메모리] forecast_theta 실행 전: 1567.40 MB
[메모리] forecast_theta 실행 후: 1567.40 MB (변화: +0.00 MB)
[LXU]   [Theta] 완료  첫값=1.76e+08 (메모리: 1567.4 MB)
[LXU]   [DB] 88행 저장 완료
[PROGRESS] [ 214/500] ( 42.8%)  >>  VOLT
[VOLT] [SKIP] [VOLT] FMP에서 'sale' 데이터 없음
[PROGRESS] [ 215/500] ( 43.0%)  >>  MATV
[MATV]   40분기 | 2016-03-31 ~ 2025-12-31
[MATV]   [SARIMA] 시작  (메모리: 1567.4 MB)
[메모리] forecast_sarima 실행 전: 1567.40 MB
[메모리] find_best_sarima_params 실행 전: 1567.40 MB
[메모리] find_best_sarima_params 실행 후: 1567.40 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1567.40 MB (변화: +0.00 MB)
[MATV]   [SARIMA] 완료  첫값=4.72e+08 (메모리: 1567.4 MB)
[MATV]   [ETS] 시작  (메모리: 1567.4 MB)
[메모리] forecast_ets 실행 전: 1567.40 MB
[메모리] forecast_ets 실행 후: 1567.41 MB (변화: +0.01 MB)
[MATV]   [ETS] 완료  첫값=4.86e+08 (메모리: 1567.4 MB)
[MATV]   [Prophet] 시작  (메모리: 1567.4 MB)

11:21:25 - cmdstanpy - INFO - Chain [1] start processing
11:21:25 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1567.41 MB
[메모리] forecast_prophet 실행 후: 1567.43 MB (변화: +0.02 MB)
[MATV]   [Prophet] 완료  첫값=5.59e+08 (메모리: 1567.4 MB)
[MATV]   [LSTM] 시작  (메모리: 1567.4 MB)
[메모리] forecast_lstm 실행 전: 1567.43 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1567.39 MB (변화: -0.03 MB)
[MATV]   [LSTM] 완료  첫값=5.08e+08 (메모리: 1567.4 MB)
[MATV]   [Theta] 시작  (메모리: 1567.4 MB)
[메모리] forecast_theta 실행 전: 1567.39 MB
[메모리] forecast_theta 실행 후: 1567.39 MB (변화: +0.00 MB)
[MATV]   [Theta] 완료  첫값=4.82e+08 (메모리: 1567.4 MB)
[MATV]   [DB] 88행 저장 완료
[PROGRESS] [ 216/500] ( 43.2%)  >>  VTLE
[VTLE]   40분기 | 2015-12-31 ~ 2025-09-30
[VTLE]   [SARIMA] 시작  (메모리: 1567.4 MB)
[메모리] forecast_sarima 실행 전: 1567.39 MB
[메모리] find_best_sarima_params 실행 전: 1567.39 MB
[메모리] find_best_sarima_params 실행 후: 1567.39 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1567.39 MB (변화: +0.00 MB)
[VTLE]   [SARIMA] 완료  첫값=4.21e+08 (메모리: 1567.4 MB)
[VTLE]   [ETS] 시작  (메모리: 1567.4 MB)
[메모리] forecast_ets 실행 전: 1567.39 MB
[메모리] forecast_ets 실행 후: 1567.40 MB (변화: +0.00 MB)
[VTLE]   [ETS] 완료  첫값=4.39e+08 (메모리: 1567.4 MB)
[VTLE]   [Prophet] 시작  (메모리: 1567.4 MB)

11:21:40 - cmdstanpy - INFO - Chain [1] start processing
11:21:40 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1567.40 MB
[메모리] forecast_prophet 실행 후: 1567.42 MB (변화: +0.02 MB)
[VTLE]   [Prophet] 완료  첫값=5.06e+08 (메모리: 1567.4 MB)
[VTLE]   [LSTM] 시작  (메모리: 1567.4 MB)
[메모리] forecast_lstm 실행 전: 1567.42 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1567.38 MB (변화: -0.04 MB)
[VTLE]   [LSTM] 완료  첫값=4.28e+08 (메모리: 1567.4 MB)
[VTLE]   [Theta] 시작  (메모리: 1567.4 MB)
[메모리] forecast_theta 실행 전: 1567.38 MB
[메모리] forecast_theta 실행 후: 1567.38 MB (변화: +0.00 MB)
[VTLE]   [Theta] 완료  첫값=4.30e+08 (메모리: 1567.4 MB)
[VTLE]   [DB] 88행 저장 완료
[PROGRESS] [ 217/500] ( 43.4%)  >>  RUTH
[RUTH]   40분기 | 2013-06-30 ~ 2023-03-26
[RUTH]   [SARIMA] 시작  (메모리: 1567.4 MB)
[메모리] forecast_sarima 실행 전: 1567.38 MB
[메모리] find_best_sarima_params 실행 전: 1567.38 MB
[메모리] find_best_sarima_params 실행 후: 1567.38 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1567.38 MB (변화: +0.00 MB)
[RUTH]   [SARIMA] 완료  첫값=1.14e+08 (메모리: 1567.4 MB)
[RUTH]   [ETS] 시작  (메모리: 1567.4 MB)
[메모리] forecast_ets 실행 전: 1567.38 MB
[메모리] forecast_ets 실행 후: 1567.38 MB (변화: +0.00 MB)
[RUTH]   [ETS] 완료  첫값=1.16e+08 (메모리: 1567.4 MB)
[RUTH]   [Prophet] 시작  (메모리: 1567.4 MB)

11:21:55 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1567.38 MB

11:21:55 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1567.40 MB (변화: +0.02 MB)
[RUTH]   [Prophet] 완료  첫값=1.13e+08 (메모리: 1567.4 MB)
[RUTH]   [LSTM] 시작  (메모리: 1567.4 MB)
[메모리] forecast_lstm 실행 전: 1567.40 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1567.32 MB (변화: -0.08 MB)
[RUTH]   [LSTM] 완료  첫값=1.06e+08 (메모리: 1567.3 MB)
[RUTH]   [Theta] 시작  (메모리: 1567.3 MB)
[메모리] forecast_theta 실행 전: 1567.32 MB
[메모리] forecast_theta 실행 후: 1567.32 MB (변화: +0.00 MB)
[RUTH]   [Theta] 완료  첫값=1.08e+08 (메모리: 1567.3 MB)
[RUTH]   [DB] 88행 저장 완료
[PROGRESS] [ 218/500] ( 43.6%)  >>  LYTS
[LYTS]   40분기 | 2016-03-31 ~ 2025-12-31
[LYTS]   [SARIMA] 시작  (메모리: 1567.3 MB)
[메모리] forecast_sarima 실행 전: 1567.32 MB
[메모리] find_best_sarima_params 실행 전: 1567.32 MB
[메모리] find_best_sarima_params 실행 후: 1567.32 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1567.32 MB (변화: +0.00 MB)
[LYTS]   [SARIMA] 완료  첫값=1.34e+08 (메모리: 1567.3 MB)
[LYTS]   [ETS] 시작  (메모리: 1567.3 MB)
[메모리] forecast_ets 실행 전: 1567.32 MB
[메모리] forecast_ets 실행 후: 1567.33 MB (변화: +0.01 MB)
[LYTS]   [ETS] 완료  첫값=1.33e+08 (메모리: 1567.3 MB)
[LYTS]   [Prophet] 시작  (메모리: 1567.3 MB)

11:22:15 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1567.33 MB

11:22:15 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1567.37 MB (변화: +0.04 MB)
[LYTS]   [Prophet] 완료  첫값=1.41e+08 (메모리: 1567.4 MB)
[LYTS]   [LSTM] 시작  (메모리: 1567.4 MB)
[메모리] forecast_lstm 실행 전: 1567.37 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1565.47 MB (변화: -1.90 MB)
[LYTS]   [LSTM] 완료  첫값=1.35e+08 (메모리: 1565.5 MB)
[LYTS]   [Theta] 시작  (메모리: 1565.5 MB)
[메모리] forecast_theta 실행 전: 1565.47 MB
[메모리] forecast_theta 실행 후: 1565.47 MB (변화: +0.00 MB)
[LYTS]   [Theta] 완료  첫값=1.32e+08 (메모리: 1565.5 MB)
[LYTS]   [DB] 88행 저장 완료
[PROGRESS] [ 219/500] ( 43.8%)  >>  SSTK
[SSTK]   40분기 | 2016-03-31 ~ 2025-12-31
[SSTK]   [SARIMA] 시작  (메모리: 1565.5 MB)
[메모리] forecast_sarima 실행 전: 1565.47 MB
[메모리] find_best_sarima_params 실행 전: 1565.47 MB
[메모리] find_best_sarima_params 실행 후: 1565.47 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1565.47 MB (변화: +0.00 MB)
[SSTK]   [SARIMA] 완료  첫값=2.24e+08 (메모리: 1565.5 MB)
[SSTK]   [ETS] 시작  (메모리: 1565.5 MB)
[메모리] forecast_ets 실행 전: 1565.47 MB
[메모리] forecast_ets 실행 후: 1565.47 MB (변화: +0.00 MB)
[SSTK]   [ETS] 완료  첫값=2.30e+08 (메모리: 1565.5 MB)
[SSTK]   [Prophet] 시작  (메모리: 1565.5 MB)
[메모리] forecast_prophet 실행 전: 1565.47 MB

11:22:32 - cmdstanpy - INFO - Chain [1] start processing
11:22:32 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1565.51 MB (변화: +0.04 MB)
[SSTK]   [Prophet] 완료  첫값=2.55e+08 (메모리: 1565.5 MB)
[SSTK]   [LSTM] 시작  (메모리: 1565.5 MB)
[메모리] forecast_lstm 실행 전: 1565.51 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1565.47 MB (변화: -0.04 MB)
[SSTK]   [LSTM] 완료  첫값=2.56e+08 (메모리: 1565.5 MB)
[SSTK]   [Theta] 시작  (메모리: 1565.5 MB)
[메모리] forecast_theta 실행 전: 1565.47 MB
[메모리] forecast_theta 실행 후: 1565.47 MB (변화: +0.00 MB)
[SSTK]   [Theta] 완료  첫값=2.16e+08 (메모리: 1565.5 MB)
[SSTK]   [DB] 88행 저장 완료
[PROGRESS] [ 220/500] ( 44.0%)  >>  ATHM
[ATHM] [NEG-SKIP] [ATHM] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2025, 9, 30)])
[PROGRESS] [ 221/500] ( 44.2%)  >>  TATT
[TATT]   40분기 | 2016-03-31 ~ 2025-12-31
[TATT]   [SARIMA] 시작  (메모리: 1565.5 MB)
[메모리] forecast_sarima 실행 전: 1565.47 MB
[메모리] find_best_sarima_params 실행 전: 1565.47 MB
[메모리] find_best_sarima_params 실행 후: 1565.47 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1565.47 MB (변화: +0.00 MB)
[TATT]   [SARIMA] 완료  첫값=4.74e+07 (메모리: 1565.5 MB)
[TATT]   [ETS] 시작  (메모리: 1565.5 MB)
[메모리] forecast_ets 실행 전: 1565.47 MB
[메모리] forecast_ets 실행 후: 1565.47 MB (변화: +0.00 MB)
[TATT]   [ETS] 완료  첫값=4.82e+07 (메모리: 1565.5 MB)
[TATT]   [Prophet] 시작  (메모리: 1565.5 MB)
[메모리] forecast_prophet 실행 전: 1565.47 MB

11:22:49 - cmdstanpy - INFO - Chain [1] start processing
11:22:49 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1565.72 MB (변화: +0.25 MB)
[TATT]   [Prophet] 완료  첫값=3.56e+07 (메모리: 1565.7 MB)
[TATT]   [LSTM] 시작  (메모리: 1565.7 MB)
[메모리] forecast_lstm 실행 전: 1565.72 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1565.69 MB (변화: -0.03 MB)
[TATT]   [LSTM] 완료  첫값=5.22e+07 (메모리: 1565.7 MB)
[TATT]   [Theta] 시작  (메모리: 1565.7 MB)
[메모리] forecast_theta 실행 전: 1565.69 MB
[메모리] forecast_theta 실행 후: 1565.69 MB (변화: +0.00 MB)
[TATT]   [Theta] 완료  첫값=4.77e+07 (메모리: 1565.7 MB)
[TATT]   [DB] 88행 저장 완료
[PROGRESS] [ 222/500] ( 44.4%)  >>  CSV
[CSV]   40분기 | 2016-03-31 ~ 2025-12-31
[CSV]   [SARIMA] 시작  (메모리: 1565.7 MB)
[메모리] forecast_sarima 실행 전: 1565.69 MB
[메모리] find_best_sarima_params 실행 전: 1565.69 MB
[메모리] find_best_sarima_params 실행 후: 1565.69 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1565.69 MB (변화: +0.00 MB)
[CSV]   [SARIMA] 완료  첫값=1.08e+08 (메모리: 1565.7 MB)
[CSV]   [ETS] 시작  (메모리: 1565.7 MB)
[메모리] forecast_ets 실행 전: 1565.69 MB
[메모리] forecast_ets 실행 후: 1565.70 MB (변화: +0.00 MB)
[CSV]   [ETS] 완료  첫값=1.13e+08 (메모리: 1565.7 MB)
[CSV]   [Prophet] 시작  (메모리: 1565.7 MB)

11:23:10 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1565.70 MB

11:23:10 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1565.36 MB (변화: -0.34 MB)
[CSV]   [Prophet] 완료  첫값=1.10e+08 (메모리: 1565.4 MB)
[CSV]   [LSTM] 시작  (메모리: 1565.4 MB)
[메모리] forecast_lstm 실행 전: 1565.36 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1566.33 MB (변화: +0.97 MB)
[CSV]   [LSTM] 완료  첫값=1.08e+08 (메모리: 1566.3 MB)
[CSV]   [Theta] 시작  (메모리: 1566.3 MB)
[메모리] forecast_theta 실행 전: 1566.33 MB
[메모리] forecast_theta 실행 후: 1566.33 MB (변화: +0.00 MB)
[CSV]   [Theta] 완료  첫값=1.12e+08 (메모리: 1566.3 MB)
[CSV]   [DB] 88행 저장 완료
[PROGRESS] [ 223/500] ( 44.6%)  >>  URG
[URG]   40분기 | 2016-03-31 ~ 2025-12-31
[URG]   [SARIMA] 시작  (메모리: 1566.3 MB)
[메모리] forecast_sarima 실행 전: 1566.33 MB
[메모리] find_best_sarima_params 실행 전: 1566.33 MB
[메모리] find_best_sarima_params 실행 후: 1566.33 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1566.33 MB (변화: +0.00 MB)
[URG]   [SARIMA] 완료  첫값=9.96e+06 (메모리: 1566.3 MB)
[URG]   [ETS] 시작  (메모리: 1566.3 MB)
[메모리] forecast_ets 실행 전: 1566.33 MB
[메모리] forecast_ets 실행 후: 1566.33 MB (변화: +0.00 MB)
[URG]   [ETS] 완료  첫값=7.51e+06 (메모리: 1566.3 MB)
[URG]   [Prophet] 시작  (메모리: 1566.3 MB)

11:23:24 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1566.33 MB

11:23:24 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1566.82 MB (변화: +0.49 MB)
[URG]   [Prophet] 완료  첫값=3.94e+06 (메모리: 1566.8 MB)
[URG]   [LSTM] 시작  (메모리: 1566.8 MB)
[메모리] forecast_lstm 실행 전: 1566.82 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1567.05 MB (변화: +0.23 MB)
[URG]   [LSTM] 완료  첫값=4.97e+06 (메모리: 1567.1 MB)
[URG]   [Theta] 시작  (메모리: 1567.1 MB)
[메모리] forecast_theta 실행 전: 1567.05 MB
[메모리] forecast_theta 실행 후: 1567.05 MB (변화: +0.00 MB)
[URG]   [Theta] 완료  첫값=8.19e+06 (메모리: 1567.1 MB)
[URG]   [DB] 88행 저장 완료
[PROGRESS] [ 224/500] ( 44.8%)  >>  RIGL
[RIGL]   40분기 | 2016-03-31 ~ 2025-12-31
[RIGL]   [SARIMA] 시작  (메모리: 1567.1 MB)
[메모리] forecast_sarima 실행 전: 1567.05 MB
[메모리] find_best_sarima_params 실행 전: 1567.05 MB
[메모리] find_best_sarima_params 실행 후: 1567.05 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1567.05 MB (변화: +0.00 MB)
[RIGL]   [SARIMA] 완료  첫값=7.91e+07 (메모리: 1567.1 MB)
[RIGL]   [ETS] 시작  (메모리: 1567.1 MB)
[메모리] forecast_ets 실행 전: 1567.05 MB
[메모리] forecast_ets 실행 후: 1567.05 MB (변화: +0.00 MB)
[RIGL]   [ETS] 완료  첫값=7.42e+07 (메모리: 1567.1 MB)
[RIGL]   [Prophet] 시작  (메모리: 1567.1 MB)

11:23:38 - cmdstanpy - INFO - Chain [1] start processing
11:23:39 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1567.05 MB
[메모리] forecast_prophet 실행 후: 1567.05 MB (변화: +0.00 MB)
[RIGL]   [Prophet] 완료  첫값=6.04e+07 (메모리: 1567.1 MB)
[RIGL]   [LSTM] 시작  (메모리: 1567.1 MB)
[메모리] forecast_lstm 실행 전: 1567.05 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1567.07 MB (변화: +0.02 MB)
[RIGL]   [LSTM] 완료  첫값=5.23e+07 (메모리: 1567.1 MB)
[RIGL]   [Theta] 시작  (메모리: 1567.1 MB)
[메모리] forecast_theta 실행 전: 1567.07 MB
[메모리] forecast_theta 실행 후: 1567.07 MB (변화: +0.00 MB)
[RIGL]   [Theta] 완료  첫값=7.55e+07 (메모리: 1567.1 MB)
[RIGL]   [DB] 88행 저장 완료
[PROGRESS] [ 225/500] ( 45.0%)  >>  SXC
[SXC]   40분기 | 2016-03-31 ~ 2025-12-31
[SXC]   [SARIMA] 시작  (메모리: 1567.1 MB)
[메모리] forecast_sarima 실행 전: 1567.07 MB
[메모리] find_best_sarima_params 실행 전: 1567.07 MB
[메모리] find_best_sarima_params 실행 후: 1567.07 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1567.07 MB (변화: +0.00 MB)
[SXC]   [SARIMA] 완료  첫값=4.86e+08 (메모리: 1567.1 MB)
[SXC]   [ETS] 시작  (메모리: 1567.1 MB)
[메모리] forecast_ets 실행 전: 1567.07 MB
[메모리] forecast_ets 실행 후: 1567.08 MB (변화: +0.01 MB)
[SXC]   [ETS] 완료  첫값=4.83e+08 (메모리: 1567.1 MB)
[SXC]   [Prophet] 시작  (메모리: 1567.1 MB)

11:23:55 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1567.08 MB

11:23:55 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1567.10 MB (변화: +0.02 MB)
[SXC]   [Prophet] 완료  첫값=5.14e+08 (메모리: 1567.1 MB)
[SXC]   [LSTM] 시작  (메모리: 1567.1 MB)
[메모리] forecast_lstm 실행 전: 1567.10 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1567.37 MB (변화: +0.27 MB)
[SXC]   [LSTM] 완료  첫값=4.74e+08 (메모리: 1567.4 MB)
[SXC]   [Theta] 시작  (메모리: 1567.4 MB)
[메모리] forecast_theta 실행 전: 1567.37 MB
[메모리] forecast_theta 실행 후: 1567.37 MB (변화: +0.00 MB)
[SXC]   [Theta] 완료  첫값=4.80e+08 (메모리: 1567.4 MB)
[SXC]   [DB] 88행 저장 완료
[PROGRESS] [ 226/500] ( 45.2%)  >>  STAR
[STAR] [NEG-SKIP] [STAR] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2021, 12, 31)])
[PROGRESS] [ 227/500] ( 45.4%)  >>  ESPR
[ESPR]   40분기 | 2016-03-31 ~ 2025-12-31
[ESPR]   [SARIMA] 시작  (메모리: 1567.4 MB)
[메모리] forecast_sarima 실행 전: 1567.37 MB
[메모리] find_best_sarima_params 실행 전: 1567.37 MB
[메모리] find_best_sarima_params 실행 후: 1567.37 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1567.37 MB (변화: +0.00 MB)
[ESPR]   [SARIMA] 완료  첫값=9.80e+07 (메모리: 1567.4 MB)
[ESPR]   [ETS] 시작  (메모리: 1567.4 MB)
[메모리] forecast_ets 실행 전: 1567.37 MB
[메모리] forecast_ets 실행 후: 1567.38 MB (변화: +0.01 MB)
[ESPR]   [ETS] 완료  첫값=1.06e+08 (메모리: 1567.4 MB)
[ESPR]   [Prophet] 시작  (메모리: 1567.4 MB)

11:24:14 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1567.38 MB

11:24:14 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1567.39 MB (변화: +0.02 MB)
[ESPR]   [Prophet] 완료  첫값=7.99e+07 (메모리: 1567.4 MB)
[ESPR]   [LSTM] 시작  (메모리: 1567.4 MB)
[메모리] forecast_lstm 실행 전: 1567.39 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1567.52 MB (변화: +0.12 MB)
[ESPR]   [LSTM] 완료  첫값=6.92e+07 (메모리: 1567.5 MB)
[ESPR]   [Theta] 시작  (메모리: 1567.5 MB)
[메모리] forecast_theta 실행 전: 1567.52 MB
[메모리] forecast_theta 실행 후: 1567.52 MB (변화: +0.00 MB)
[ESPR]   [Theta] 완료  첫값=9.15e+07 (메모리: 1567.5 MB)
[ESPR]   [DB] 88행 저장 완료
[PROGRESS] [ 228/500] ( 45.6%)  >>  AOSL
[AOSL]   40분기 | 2016-03-31 ~ 2025-12-31
[AOSL]   [SARIMA] 시작  (메모리: 1567.5 MB)
[메모리] forecast_sarima 실행 전: 1567.52 MB
[메모리] find_best_sarima_params 실행 전: 1567.52 MB
[메모리] find_best_sarima_params 실행 후: 1567.52 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1567.52 MB (변화: +0.00 MB)
[AOSL]   [SARIMA] 완료  첫값=1.59e+08 (메모리: 1567.5 MB)
[AOSL]   [ETS] 시작  (메모리: 1567.5 MB)
[메모리] forecast_ets 실행 전: 1567.52 MB
[메모리] forecast_ets 실행 후: 1567.52 MB (변화: +0.01 MB)
[AOSL]   [ETS] 완료  첫값=1.52e+08 (메모리: 1567.5 MB)
[AOSL]   [Prophet] 시작  (메모리: 1567.5 MB)

11:24:29 - cmdstanpy - INFO - Chain [1] start processing
11:24:29 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1567.52 MB
[메모리] forecast_prophet 실행 후: 1567.55 MB (변화: +0.02 MB)
[AOSL]   [Prophet] 완료  첫값=1.97e+08 (메모리: 1567.5 MB)
[AOSL]   [LSTM] 시작  (메모리: 1567.5 MB)
[메모리] forecast_lstm 실행 전: 1567.55 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1568.56 MB (변화: +1.01 MB)
[AOSL]   [LSTM] 완료  첫값=1.72e+08 (메모리: 1568.6 MB)
[AOSL]   [Theta] 시작  (메모리: 1568.6 MB)
[메모리] forecast_theta 실행 전: 1568.56 MB
[메모리] forecast_theta 실행 후: 1568.56 MB (변화: +0.00 MB)
[AOSL]   [Theta] 완료  첫값=1.51e+08 (메모리: 1568.6 MB)
[AOSL]   [DB] 88행 저장 완료
[PROGRESS] [ 229/500] ( 45.8%)  >>  PLAY
[PLAY]   40분기 | 2016-05-01 ~ 2026-02-03
[PLAY]   [SARIMA] 시작  (메모리: 1568.6 MB)
[메모리] forecast_sarima 실행 전: 1568.56 MB
[메모리] find_best_sarima_params 실행 전: 1568.56 MB
[메모리] find_best_sarima_params 실행 후: 1568.56 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1568.56 MB (변화: +0.00 MB)
[PLAY]   [SARIMA] 완료  첫값=5.30e+08 (메모리: 1568.6 MB)
[PLAY]   [ETS] 시작  (메모리: 1568.6 MB)
[메모리] forecast_ets 실행 전: 1568.56 MB
[메모리] forecast_ets 실행 후: 1568.56 MB (변화: +0.00 MB)
[PLAY]   [ETS] 완료  첫값=5.73e+08 (메모리: 1568.6 MB)
[PLAY]   [Prophet] 시작  (메모리: 1568.6 MB)

11:24:46 - cmdstanpy - INFO - Chain [1] start processing
11:24:47 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1568.56 MB
[메모리] forecast_prophet 실행 후: 1568.57 MB (변화: +0.01 MB)
[PLAY]   [Prophet] 완료  첫값=5.51e+08 (메모리: 1568.6 MB)
[PLAY]   [LSTM] 시작  (메모리: 1568.6 MB)
[메모리] forecast_lstm 실행 전: 1568.57 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1568.54 MB (변화: -0.03 MB)
[PLAY]   [LSTM] 완료  첫값=5.41e+08 (메모리: 1568.5 MB)
[PLAY]   [Theta] 시작  (메모리: 1568.5 MB)
[메모리] forecast_theta 실행 전: 1568.54 MB
[메모리] forecast_theta 실행 후: 1568.54 MB (변화: +0.00 MB)
[PLAY]   [Theta] 완료  첫값=5.36e+08 (메모리: 1568.5 MB)
[PLAY]   [DB] 88행 저장 완료
[PROGRESS] [ 230/500] ( 46.0%)  >>  GRPN
[GRPN]   40분기 | 2016-03-31 ~ 2025-12-31
[GRPN]   [SARIMA] 시작  (메모리: 1568.5 MB)
[메모리] forecast_sarima 실행 전: 1568.54 MB
[메모리] find_best_sarima_params 실행 전: 1568.54 MB
[메모리] find_best_sarima_params 실행 후: 1568.54 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1568.54 MB (변화: +0.00 MB)
[GRPN]   [SARIMA] 완료  첫값=1.21e+08 (메모리: 1568.5 MB)
[GRPN]   [ETS] 시작  (메모리: 1568.5 MB)
[메모리] forecast_ets 실행 전: 1568.54 MB
[메모리] forecast_ets 실행 후: 1568.55 MB (변화: +0.01 MB)
[GRPN]   [ETS] 완료  첫값=1.21e+08 (메모리: 1568.5 MB)
[GRPN]   [Prophet] 시작  (메모리: 1568.5 MB)

11:25:02 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1568.55 MB

11:25:02 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1568.58 MB (변화: +0.03 MB)
[GRPN]   [Prophet] 완료  첫값=-4.61e+07 (메모리: 1568.6 MB)
[GRPN]   [LSTM] 시작  (메모리: 1568.6 MB)
[메모리] forecast_lstm 실행 전: 1568.58 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1568.93 MB (변화: +0.36 MB)
[GRPN]   [LSTM] 완료  첫값=1.27e+08 (메모리: 1568.9 MB)
[GRPN]   [Theta] 시작  (메모리: 1568.9 MB)
[메모리] forecast_theta 실행 전: 1568.93 MB
[메모리] forecast_theta 실행 후: 1568.93 MB (변화: +0.00 MB)
[GRPN]   [Theta] 완료  첫값=1.03e+08 (메모리: 1568.9 MB)
[GRPN]   [DB] 88행 저장 완료
[PROGRESS] [ 231/500] ( 46.2%)  >>  CVLG
[CVLG]   40분기 | 2016-03-31 ~ 2025-12-31
[CVLG]   [SARIMA] 시작  (메모리: 1568.9 MB)
[메모리] forecast_sarima 실행 전: 1568.93 MB
[메모리] find_best_sarima_params 실행 전: 1568.93 MB
[메모리] find_best_sarima_params 실행 후: 1568.93 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1568.93 MB (변화: +0.00 MB)
[CVLG]   [SARIMA] 완료  첫값=2.93e+08 (메모리: 1568.9 MB)
[CVLG]   [ETS] 시작  (메모리: 1568.9 MB)
[메모리] forecast_ets 실행 전: 1568.93 MB
[메모리] forecast_ets 실행 후: 1568.94 MB (변화: +0.00 MB)
[CVLG]   [ETS] 완료  첫값=2.95e+08 (메모리: 1568.9 MB)
[CVLG]   [Prophet] 시작  (메모리: 1568.9 MB)

11:25:22 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1568.94 MB

11:25:22 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1568.98 MB (변화: +0.04 MB)
[CVLG]   [Prophet] 완료  첫값=3.18e+08 (메모리: 1569.0 MB)
[CVLG]   [LSTM] 시작  (메모리: 1569.0 MB)
[메모리] forecast_lstm 실행 전: 1568.98 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1568.67 MB (변화: -0.31 MB)
[CVLG]   [LSTM] 완료  첫값=2.82e+08 (메모리: 1568.7 MB)
[CVLG]   [Theta] 시작  (메모리: 1568.7 MB)
[메모리] forecast_theta 실행 전: 1568.67 MB
[메모리] forecast_theta 실행 후: 1568.67 MB (변화: +0.00 MB)
[CVLG]   [Theta] 완료  첫값=2.67e+08 (메모리: 1568.7 MB)
[CVLG]   [DB] 88행 저장 완료
[PROGRESS] [ 232/500] ( 46.4%)  >>  CBRL
[CBRL]   40분기 | 2016-04-29 ~ 2026-01-30
[CBRL]   [SARIMA] 시작  (메모리: 1568.7 MB)
[메모리] forecast_sarima 실행 전: 1568.67 MB
[메모리] find_best_sarima_params 실행 전: 1568.67 MB
[메모리] find_best_sarima_params 실행 후: 1568.67 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1568.67 MB (변화: +0.00 MB)
[CBRL]   [SARIMA] 완료  첫값=7.71e+08 (메모리: 1568.7 MB)
[CBRL]   [ETS] 시작  (메모리: 1568.7 MB)
[메모리] forecast_ets 실행 전: 1568.67 MB
[메모리] forecast_ets 실행 후: 1568.67 MB (변화: +0.00 MB)
[CBRL]   [ETS] 완료  첫값=7.54e+08 (메모리: 1568.7 MB)
[CBRL]   [Prophet] 시작  (메모리: 1568.7 MB)

11:25:38 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1568.67 MB

11:25:38 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1568.69 MB (변화: +0.02 MB)
[CBRL]   [Prophet] 완료  첫값=8.68e+08 (메모리: 1568.7 MB)
[CBRL]   [LSTM] 시작  (메모리: 1568.7 MB)
[메모리] forecast_lstm 실행 전: 1568.69 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1569.70 MB (변화: +1.02 MB)
[CBRL]   [LSTM] 완료  첫값=8.51e+08 (메모리: 1569.7 MB)
[CBRL]   [Theta] 시작  (메모리: 1569.7 MB)
[메모리] forecast_theta 실행 전: 1569.70 MB
[메모리] forecast_theta 실행 후: 1569.70 MB (변화: +0.00 MB)
[CBRL]   [Theta] 완료  첫값=8.57e+08 (메모리: 1569.7 MB)
[CBRL]   [DB] 88행 저장 완료
[PROGRESS] [ 233/500] ( 46.6%)  >>  HSTM
[HSTM]   40분기 | 2016-03-31 ~ 2025-12-31
[HSTM]   [SARIMA] 시작  (메모리: 1569.7 MB)
[메모리] forecast_sarima 실행 전: 1569.71 MB
[메모리] find_best_sarima_params 실행 전: 1569.71 MB
[메모리] find_best_sarima_params 실행 후: 1569.71 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1569.71 MB (변화: +0.00 MB)
[HSTM]   [SARIMA] 완료  첫값=8.05e+07 (메모리: 1569.7 MB)
[HSTM]   [ETS] 시작  (메모리: 1569.7 MB)
[메모리] forecast_ets 실행 전: 1569.71 MB
[메모리] forecast_ets 실행 후: 1569.71 MB (변화: +0.00 MB)
[HSTM]   [ETS] 완료  첫값=7.97e+07 (메모리: 1569.7 MB)
[HSTM]   [Prophet] 시작  (메모리: 1569.7 MB)

11:25:56 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1569.71 MB

11:25:56 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1569.73 MB (변화: +0.02 MB)
[HSTM]   [Prophet] 완료  첫값=7.73e+07 (메모리: 1569.7 MB)
[HSTM]   [LSTM] 시작  (메모리: 1569.7 MB)
[메모리] forecast_lstm 실행 전: 1569.73 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1569.75 MB (변화: +0.02 MB)
[HSTM]   [LSTM] 완료  첫값=7.42e+07 (메모리: 1569.8 MB)
[HSTM]   [Theta] 시작  (메모리: 1569.8 MB)
[메모리] forecast_theta 실행 전: 1569.75 MB
[메모리] forecast_theta 실행 후: 1569.75 MB (변화: +0.00 MB)
[HSTM]   [Theta] 완료  첫값=7.95e+07 (메모리: 1569.8 MB)
[HSTM]   [DB] 88행 저장 완료
[PROGRESS] [ 234/500] ( 46.8%)  >>  CHUY
[CHUY]   40분기 | 2014-09-28 ~ 2024-06-30
[CHUY]   [SARIMA] 시작  (메모리: 1569.8 MB)
[메모리] forecast_sarima 실행 전: 1569.75 MB
[메모리] find_best_sarima_params 실행 전: 1569.75 MB
[메모리] find_best_sarima_params 실행 후: 1569.75 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1569.75 MB (변화: +0.00 MB)
[CHUY]   [SARIMA] 완료  첫값=1.22e+08 (메모리: 1569.8 MB)
[CHUY]   [ETS] 시작  (메모리: 1569.8 MB)
[메모리] forecast_ets 실행 전: 1569.75 MB
[메모리] forecast_ets 실행 후: 1569.75 MB (변화: +0.00 MB)
[CHUY]   [ETS] 완료  첫값=1.19e+08 (메모리: 1569.8 MB)
[CHUY]   [Prophet] 시작  (메모리: 1569.8 MB)

11:26:12 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1569.75 MB

11:26:12 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1569.76 MB (변화: +0.00 MB)
[CHUY]   [Prophet] 완료  첫값=1.16e+08 (메모리: 1569.8 MB)
[CHUY]   [LSTM] 시작  (메모리: 1569.8 MB)
[메모리] forecast_lstm 실행 전: 1569.76 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1568.48 MB (변화: -1.28 MB)
[CHUY]   [LSTM] 완료  첫값=1.09e+08 (메모리: 1568.5 MB)
[CHUY]   [Theta] 시작  (메모리: 1568.5 MB)
[메모리] forecast_theta 실행 전: 1568.48 MB
[메모리] forecast_theta 실행 후: 1568.48 MB (변화: +0.00 MB)
[CHUY]   [Theta] 완료  첫값=1.19e+08 (메모리: 1568.5 MB)
[CHUY]   [DB] 88행 저장 완료
[PROGRESS] [ 235/500] ( 47.0%)  >>  NWPX
[NWPX]   40분기 | 2016-03-31 ~ 2025-12-31
[NWPX]   [SARIMA] 시작  (메모리: 1568.5 MB)
[메모리] forecast_sarima 실행 전: 1568.48 MB
[메모리] find_best_sarima_params 실행 전: 1568.48 MB
[메모리] find_best_sarima_params 실행 후: 1568.48 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1568.48 MB (변화: +0.00 MB)
[NWPX]   [SARIMA] 완료  첫값=1.23e+08 (메모리: 1568.5 MB)
[NWPX]   [ETS] 시작  (메모리: 1568.5 MB)
[메모리] forecast_ets 실행 전: 1568.48 MB
[메모리] forecast_ets 실행 후: 1568.48 MB (변화: +0.00 MB)
[NWPX]   [ETS] 완료  첫값=1.22e+08 (메모리: 1568.5 MB)
[NWPX]   [Prophet] 시작  (메모리: 1568.5 MB)

11:26:28 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1568.48 MB

11:26:28 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1568.50 MB (변화: +0.02 MB)
[NWPX]   [Prophet] 완료  첫값=1.43e+08 (메모리: 1568.5 MB)
[NWPX]   [LSTM] 시작  (메모리: 1568.5 MB)
[메모리] forecast_lstm 실행 전: 1568.50 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1568.47 MB (변화: -0.03 MB)
[NWPX]   [LSTM] 완료  첫값=1.29e+08 (메모리: 1568.5 MB)
[NWPX]   [Theta] 시작  (메모리: 1568.5 MB)
[메모리] forecast_theta 실행 전: 1568.47 MB
[메모리] forecast_theta 실행 후: 1568.47 MB (변화: +0.00 MB)
[NWPX]   [Theta] 완료  첫값=1.20e+08 (메모리: 1568.5 MB)
[NWPX]   [DB] 88행 저장 완료
[PROGRESS] [ 236/500] ( 47.2%)  >>  IDR
[IDR]   40분기 | 2016-03-31 ~ 2025-12-31
[IDR]   [SARIMA] 시작  (메모리: 1568.5 MB)
[메모리] forecast_sarima 실행 전: 1568.47 MB
[메모리] find_best_sarima_params 실행 전: 1568.47 MB
[메모리] find_best_sarima_params 실행 후: 1568.47 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1568.47 MB (변화: +0.00 MB)
[IDR]   [SARIMA] 완료  첫값=1.40e+07 (메모리: 1568.5 MB)
[IDR]   [ETS] 시작  (메모리: 1568.5 MB)
[메모리] forecast_ets 실행 전: 1568.47 MB
[메모리] forecast_ets 실행 후: 1568.48 MB (변화: +0.00 MB)
[IDR]   [ETS] 완료  첫값=1.67e+07 (메모리: 1568.5 MB)
[IDR]   [Prophet] 시작  (메모리: 1568.5 MB)

11:26:42 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1568.48 MB

11:26:43 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1568.51 MB (변화: +0.03 MB)
[IDR]   [Prophet] 완료  첫값=7.59e+06 (메모리: 1568.5 MB)
[IDR]   [LSTM] 시작  (메모리: 1568.5 MB)
[메모리] forecast_lstm 실행 전: 1568.51 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1568.50 MB (변화: -0.01 MB)
[IDR]   [LSTM] 완료  첫값=2.05e+07 (메모리: 1568.5 MB)
[IDR]   [Theta] 시작  (메모리: 1568.5 MB)
[메모리] forecast_theta 실행 전: 1568.50 MB
[메모리] forecast_theta 실행 후: 1568.50 MB (변화: +0.00 MB)
[IDR]   [Theta] 완료  첫값=1.53e+07 (메모리: 1568.5 MB)
[IDR]   [DB] 88행 저장 완료
[PROGRESS] [ 237/500] ( 47.4%)  >>  NYMT
[NYMT] [NEG-SKIP] [NYMT] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2020, 3, 31)])
[PROGRESS] [ 238/500] ( 47.6%)  >>  IIIN
[IIIN]   40분기 | 2016-04-02 ~ 2025-12-27
[IIIN]   [SARIMA] 시작  (메모리: 1568.5 MB)
[메모리] forecast_sarima 실행 전: 1568.50 MB
[메모리] find_best_sarima_params 실행 전: 1568.50 MB
[메모리] find_best_sarima_params 실행 후: 1568.50 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1568.50 MB (변화: +0.00 MB)
[IIIN]   [SARIMA] 완료  첫값=1.79e+08 (메모리: 1568.5 MB)
[IIIN]   [ETS] 시작  (메모리: 1568.5 MB)
[메모리] forecast_ets 실행 전: 1568.50 MB
[메모리] forecast_ets 실행 후: 1568.50 MB (변화: +0.00 MB)
[IIIN]   [ETS] 완료  첫값=1.78e+08 (메모리: 1568.5 MB)
[IIIN]   [Prophet] 시작  (메모리: 1568.5 MB)

11:27:01 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1568.50 MB

11:27:02 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1568.52 MB (변화: +0.02 MB)
[IIIN]   [Prophet] 완료  첫값=1.76e+08 (메모리: 1568.5 MB)
[IIIN]   [LSTM] 시작  (메모리: 1568.5 MB)
[메모리] forecast_lstm 실행 전: 1568.52 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1568.56 MB (변화: +0.04 MB)
[IIIN]   [LSTM] 완료  첫값=1.54e+08 (메모리: 1568.6 MB)
[IIIN]   [Theta] 시작  (메모리: 1568.6 MB)
[메모리] forecast_theta 실행 전: 1568.56 MB
[메모리] forecast_theta 실행 후: 1568.56 MB (변화: +0.00 MB)
[IIIN]   [Theta] 완료  첫값=1.77e+08 (메모리: 1568.6 MB)
[IIIN]   [DB] 88행 저장 완료
[PROGRESS] [ 239/500] ( 47.8%)  >>  EBS
[EBS]   40분기 | 2016-03-31 ~ 2025-12-31
[EBS]   [SARIMA] 시작  (메모리: 1568.6 MB)
[메모리] forecast_sarima 실행 전: 1568.56 MB
[메모리] find_best_sarima_params 실행 전: 1568.56 MB
[메모리] find_best_sarima_params 실행 후: 1568.56 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1568.56 MB (변화: +0.00 MB)
[EBS]   [SARIMA] 완료  첫값=1.65e+08 (메모리: 1568.6 MB)
[EBS]   [ETS] 시작  (메모리: 1568.6 MB)
[메모리] forecast_ets 실행 전: 1568.56 MB
[메모리] forecast_ets 실행 후: 1568.56 MB (변화: +0.00 MB)
[EBS]   [ETS] 완료  첫값=1.25e+08 (메모리: 1568.6 MB)
[EBS]   [Prophet] 시작  (메모리: 1568.6 MB)

11:27:20 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1568.56 MB

11:27:20 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1569.65 MB (변화: +1.09 MB)
[EBS]   [Prophet] 완료  첫값=3.19e+08 (메모리: 1569.7 MB)
[EBS]   [LSTM] 시작  (메모리: 1569.7 MB)
[메모리] forecast_lstm 실행 전: 1569.65 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1569.20 MB (변화: -0.45 MB)
[EBS]   [LSTM] 완료  첫값=2.61e+08 (메모리: 1569.2 MB)
[EBS]   [Theta] 시작  (메모리: 1569.2 MB)
[메모리] forecast_theta 실행 전: 1569.20 MB
[메모리] forecast_theta 실행 후: 1569.20 MB (변화: +0.00 MB)
[EBS]   [Theta] 완료  첫값=1.34e+08 (메모리: 1569.2 MB)
[EBS]   [DB] 88행 저장 완료
[PROGRESS] [ 240/500] ( 48.0%)  >>  KODK
[KODK]   40분기 | 2016-03-31 ~ 2025-12-31
[KODK]   [SARIMA] 시작  (메모리: 1569.2 MB)
[메모리] forecast_sarima 실행 전: 1569.20 MB
[메모리] find_best_sarima_params 실행 전: 1569.20 MB
[메모리] find_best_sarima_params 실행 후: 1569.20 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1569.20 MB (변화: +0.00 MB)
[KODK]   [SARIMA] 완료  첫값=2.69e+08 (메모리: 1569.2 MB)
[KODK]   [ETS] 시작  (메모리: 1569.2 MB)
[메모리] forecast_ets 실행 전: 1569.20 MB
[메모리] forecast_ets 실행 후: 1569.20 MB (변화: +0.00 MB)
[KODK]   [ETS] 완료  첫값=2.52e+08 (메모리: 1569.2 MB)
[KODK]   [Prophet] 시작  (메모리: 1569.2 MB)

11:27:35 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1569.20 MB

11:27:35 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1569.23 MB (변화: +0.02 MB)
[KODK]   [Prophet] 완료  첫값=2.39e+08 (메모리: 1569.2 MB)
[KODK]   [LSTM] 시작  (메모리: 1569.2 MB)
[메모리] forecast_lstm 실행 전: 1569.23 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1569.15 MB (변화: -0.08 MB)
[KODK]   [LSTM] 완료  첫값=2.65e+08 (메모리: 1569.1 MB)
[KODK]   [Theta] 시작  (메모리: 1569.1 MB)
[메모리] forecast_theta 실행 전: 1569.15 MB
[메모리] forecast_theta 실행 후: 1569.15 MB (변화: +0.00 MB)
[KODK]   [Theta] 완료  첫값=2.75e+08 (메모리: 1569.1 MB)
[KODK]   [DB] 88행 저장 완료
[PROGRESS] [ 241/500] ( 48.2%)  >>  KRO
[KRO]   40분기 | 2016-03-31 ~ 2025-12-31
[KRO]   [SARIMA] 시작  (메모리: 1569.1 MB)
[메모리] forecast_sarima 실행 전: 1569.15 MB
[메모리] find_best_sarima_params 실행 전: 1569.15 MB
[메모리] find_best_sarima_params 실행 후: 1569.15 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1569.15 MB (변화: +0.00 MB)
[KRO]   [SARIMA] 완료  첫값=4.78e+08 (메모리: 1569.1 MB)
[KRO]   [ETS] 시작  (메모리: 1569.1 MB)
[메모리] forecast_ets 실행 전: 1569.15 MB
[메모리] forecast_ets 실행 후: 1569.16 MB (변화: +0.01 MB)
[KRO]   [ETS] 완료  첫값=4.77e+08 (메모리: 1569.2 MB)
[KRO]   [Prophet] 시작  (메모리: 1569.2 MB)

11:27:51 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1569.16 MB

11:27:51 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1569.19 MB (변화: +0.03 MB)
[KRO]   [Prophet] 완료  첫값=4.82e+08 (메모리: 1569.2 MB)
[KRO]   [LSTM] 시작  (메모리: 1569.2 MB)
[메모리] forecast_lstm 실행 전: 1569.19 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1568.79 MB (변화: -0.40 MB)
[KRO]   [LSTM] 완료  첫값=4.42e+08 (메모리: 1568.8 MB)
[KRO]   [Theta] 시작  (메모리: 1568.8 MB)
[메모리] forecast_theta 실행 전: 1568.79 MB
[메모리] forecast_theta 실행 후: 1568.79 MB (변화: +0.00 MB)
[KRO]   [Theta] 완료  첫값=4.30e+08 (메모리: 1568.8 MB)
[KRO]   [DB] 88행 저장 완료
[PROGRESS] [ 242/500] ( 48.4%)  >>  MBUU
[MBUU]   40분기 | 2016-03-31 ~ 2025-12-31
[MBUU]   [SARIMA] 시작  (메모리: 1568.8 MB)
[메모리] forecast_sarima 실행 전: 1568.79 MB
[메모리] find_best_sarima_params 실행 전: 1568.79 MB
[메모리] find_best_sarima_params 실행 후: 1568.79 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1568.79 MB (변화: +0.00 MB)
[MBUU]   [SARIMA] 완료  첫값=1.93e+08 (메모리: 1568.8 MB)
[MBUU]   [ETS] 시작  (메모리: 1568.8 MB)
[메모리] forecast_ets 실행 전: 1568.79 MB
[메모리] forecast_ets 실행 후: 1568.79 MB (변화: +0.00 MB)
[MBUU]   [ETS] 완료  첫값=2.19e+08 (메모리: 1568.8 MB)
[MBUU]   [Prophet] 시작  (메모리: 1568.8 MB)
[메모리] forecast_prophet 실행 전: 1568.79 MB

11:28:07 - cmdstanpy - INFO - Chain [1] start processing
11:28:07 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1568.81 MB (변화: +0.02 MB)
[MBUU]   [Prophet] 완료  첫값=2.93e+08 (메모리: 1568.8 MB)
[MBUU]   [LSTM] 시작  (메모리: 1568.8 MB)
[메모리] forecast_lstm 실행 전: 1568.81 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1569.78 MB (변화: +0.96 MB)
[MBUU]   [LSTM] 완료  첫값=2.28e+08 (메모리: 1569.8 MB)
[MBUU]   [Theta] 시작  (메모리: 1569.8 MB)
[메모리] forecast_theta 실행 전: 1569.78 MB
[메모리] forecast_theta 실행 후: 1569.78 MB (변화: +0.00 MB)
[MBUU]   [Theta] 완료  첫값=2.15e+08 (메모리: 1569.8 MB)
[MBUU]   [DB] 88행 저장 완료
[PROGRESS] [ 243/500] ( 48.6%)  >>  AIC
[AIC] [SKIP] [AIC] 'sale' 관측치 부족: 20개 < 최소 28개
[PROGRESS] [ 244/500] ( 48.8%)  >>  SGOC
[SGOC] [SKIP] [SGOC] 'sale' 관측치 부족: 24개 < 최소 28개
[PROGRESS] [ 245/500] ( 49.0%)  >>  ETD
[ETD]   40분기 | 2016-03-31 ~ 2025-12-31
[ETD]   [SARIMA] 시작  (메모리: 1569.8 MB)
[메모리] forecast_sarima 실행 전: 1569.78 MB
[메모리] find_best_sarima_params 실행 전: 1569.78 MB
[메모리] find_best_sarima_params 실행 후: 1569.78 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1569.78 MB (변화: +0.00 MB)
[ETD]   [SARIMA] 완료  첫값=1.49e+08 (메모리: 1569.8 MB)
[ETD]   [ETS] 시작  (메모리: 1569.8 MB)
[메모리] forecast_ets 실행 전: 1569.78 MB
[메모리] forecast_ets 실행 후: 1569.78 MB (변화: +0.00 MB)
[ETD]   [ETS] 완료  첫값=1.39e+08 (메모리: 1569.8 MB)
[ETD]   [Prophet] 시작  (메모리: 1569.8 MB)

11:28:29 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1569.78 MB

11:28:30 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1569.79 MB (변화: +0.01 MB)
[ETD]   [Prophet] 완료  첫값=1.60e+08 (메모리: 1569.8 MB)
[ETD]   [LSTM] 시작  (메모리: 1569.8 MB)
[메모리] forecast_lstm 실행 전: 1569.79 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1569.80 MB (변화: +0.01 MB)
[ETD]   [LSTM] 완료  첫값=1.57e+08 (메모리: 1569.8 MB)
[ETD]   [Theta] 시작  (메모리: 1569.8 MB)
[메모리] forecast_theta 실행 전: 1569.80 MB
[메모리] forecast_theta 실행 후: 1569.80 MB (변화: +0.00 MB)
[ETD]   [Theta] 완료  첫값=1.49e+08 (메모리: 1569.8 MB)
[ETD]   [DB] 88행 저장 완료
[PROGRESS] [ 246/500] ( 49.2%)  >>  NR
[NR] [NEG-SKIP] [NR] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2024, 12, 31)])
[PROGRESS] [ 247/500] ( 49.4%)  >>  NTGR
[NTGR]   40분기 | 2016-04-03 ~ 2025-12-31
[NTGR]   [SARIMA] 시작  (메모리: 1569.8 MB)
[메모리] forecast_sarima 실행 전: 1569.80 MB
[메모리] find_best_sarima_params 실행 전: 1569.80 MB
[메모리] find_best_sarima_params 실행 후: 1569.80 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1569.80 MB (변화: +0.00 MB)
[NTGR]   [SARIMA] 완료  첫값=1.55e+08 (메모리: 1569.8 MB)
[NTGR]   [ETS] 시작  (메모리: 1569.8 MB)
[메모리] forecast_ets 실행 전: 1569.80 MB
[메모리] forecast_ets 실행 후: 1569.80 MB (변화: +0.00 MB)
[NTGR]   [ETS] 완료  첫값=1.51e+08 (메모리: 1569.8 MB)
[NTGR]   [Prophet] 시작  (메모리: 1569.8 MB)

11:28:46 - cmdstanpy - INFO - Chain [1] start processing
11:28:46 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1569.80 MB
[메모리] forecast_prophet 실행 후: 1569.82 MB (변화: +0.02 MB)
[NTGR]   [Prophet] 완료  첫값=1.59e+08 (메모리: 1569.8 MB)
[NTGR]   [LSTM] 시작  (메모리: 1569.8 MB)
[메모리] forecast_lstm 실행 전: 1569.82 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1569.79 MB (변화: -0.03 MB)
[NTGR]   [LSTM] 완료  첫값=1.93e+08 (메모리: 1569.8 MB)
[NTGR]   [Theta] 시작  (메모리: 1569.8 MB)
[메모리] forecast_theta 실행 전: 1569.79 MB
[메모리] forecast_theta 실행 후: 1569.79 MB (변화: +0.00 MB)
[NTGR]   [Theta] 완료  첫값=1.52e+08 (메모리: 1569.8 MB)
[NTGR]   [DB] 88행 저장 완료
[PROGRESS] [ 248/500] ( 49.6%)  >>  IVR
[IVR] [NEG-SKIP] [IVR] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2016, 3, 31), datetime.date(2018, 9, 30), datetime.date(2018, 12, 31), datetime.date(2020, 3, 31), datetime.date(2020, 6, 30), datetime.date(2021, 3, 31), datetime.date(2021, 6, 30), datetime.date(2021, 12, 31), datetime.date(2022, 3, 31), datetime.date(2022, 6, 30), datetime.date(2022, 9, 30), datetime.date(2023, 9, 30), datetime.date(2024, 6, 30)])
[PROGRESS] [ 249/500] ( 49.8%)  >>  KFRC
[KFRC]   40분기 | 2016-03-31 ~ 2025-12-31
[KFRC]   [SARIMA] 시작  (메모리: 1569.8 MB)
[메모리] forecast_sarima 실행 전: 1569.79 MB
[메모리] find_best_sarima_params 실행 전: 1569.79 MB
[메모리] find_best_sarima_params 실행 후: 1569.79 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1569.79 MB (변화: +0.00 MB)
[KFRC]   [SARIMA] 완료  첫값=3.32e+08 (메모리: 1569.8 MB)
[KFRC]   [ETS] 시작  (메모리: 1569.8 MB)
[메모리] forecast_ets 실행 전: 1569.79 MB
[메모리] forecast_ets 실행 후: 1569.79 MB (변화: +0.00 MB)
[KFRC]   [ETS] 완료  첫값=3.24e+08 (메모리: 1569.8 MB)
[KFRC]   [Prophet] 시작  (메모리: 1569.8 MB)

11:29:04 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1569.79 MB

11:29:04 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1569.80 MB (변화: +0.01 MB)
[KFRC]   [Prophet] 완료  첫값=3.28e+08 (메모리: 1569.8 MB)
[KFRC]   [LSTM] 시작  (메모리: 1569.8 MB)
[메모리] forecast_lstm 실행 전: 1569.80 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1569.77 MB (변화: -0.03 MB)
[KFRC]   [LSTM] 완료  첫값=3.50e+08 (메모리: 1569.8 MB)
[KFRC]   [Theta] 시작  (메모리: 1569.8 MB)
[메모리] forecast_theta 실행 전: 1569.77 MB
[메모리] forecast_theta 실행 후: 1569.77 MB (변화: +0.00 MB)
[KFRC]   [Theta] 완료  첫값=3.28e+08 (메모리: 1569.8 MB)
[KFRC]   [DB] 88행 저장 완료
[PROGRESS] [ 250/500] ( 50.0%)  >>  SRDX
[SRDX]   40분기 | 2015-09-30 ~ 2025-06-30
[SRDX]   [SARIMA] 시작  (메모리: 1569.8 MB)
[메모리] forecast_sarima 실행 전: 1569.77 MB
[메모리] find_best_sarima_params 실행 전: 1569.77 MB
[메모리] find_best_sarima_params 실행 후: 1569.77 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1569.77 MB (변화: +0.00 MB)
[SRDX]   [SARIMA] 완료  첫값=3.39e+07 (메모리: 1569.8 MB)
[SRDX]   [ETS] 시작  (메모리: 1569.8 MB)
[메모리] forecast_ets 실행 전: 1569.77 MB
[메모리] forecast_ets 실행 후: 1569.78 MB (변화: +0.00 MB)
[SRDX]   [ETS] 완료  첫값=3.44e+07 (메모리: 1569.8 MB)
[SRDX]   [Prophet] 시작  (메모리: 1569.8 MB)

11:29:23 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1569.78 MB

11:29:23 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1569.79 MB (변화: +0.02 MB)
[SRDX]   [Prophet] 완료  첫값=3.32e+07 (메모리: 1569.8 MB)
[SRDX]   [LSTM] 시작  (메모리: 1569.8 MB)
[메모리] forecast_lstm 실행 전: 1569.79 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1570.38 MB (변화: +0.59 MB)
[SRDX]   [LSTM] 완료  첫값=3.42e+07 (메모리: 1570.4 MB)
[SRDX]   [Theta] 시작  (메모리: 1570.4 MB)
[메모리] forecast_theta 실행 전: 1570.38 MB
[메모리] forecast_theta 실행 후: 1570.38 MB (변화: +0.00 MB)
[SRDX]   [Theta] 완료  첫값=3.04e+07 (메모리: 1570.4 MB)
[SRDX]   [DB] 88행 저장 완료
[PROGRESS] [ 251/500] ( 50.2%)  >>  SHEN
[SHEN]   40분기 | 2016-03-31 ~ 2025-12-31
[SHEN]   [SARIMA] 시작  (메모리: 1570.4 MB)
[메모리] forecast_sarima 실행 전: 1570.38 MB
[메모리] find_best_sarima_params 실행 전: 1570.38 MB
[메모리] find_best_sarima_params 실행 후: 1570.38 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1570.38 MB (변화: +0.00 MB)
[SHEN]   [SARIMA] 완료  첫값=-7.47e+06 (메모리: 1570.4 MB)
[SHEN]   [ETS] 시작  (메모리: 1570.4 MB)
[메모리] forecast_ets 실행 전: 1570.38 MB
[메모리] forecast_ets 실행 후: 1570.39 MB (변화: +0.01 MB)
[SHEN]   [ETS] 완료  첫값=5.90e+06 (메모리: 1570.4 MB)
[SHEN]   [Prophet] 시작  (메모리: 1570.4 MB)

11:29:35 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1570.39 MB

11:29:35 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1570.78 MB (변화: +0.39 MB)
[SHEN]   [Prophet] 완료  첫값=4.44e+07 (메모리: 1570.8 MB)
[SHEN]   [LSTM] 시작  (메모리: 1570.8 MB)
[메모리] forecast_lstm 실행 전: 1570.78 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1570.03 MB (변화: -0.75 MB)
[SHEN]   [LSTM] 완료  첫값=6.95e+07 (메모리: 1570.0 MB)
[SHEN]   [Theta] 시작  (메모리: 1570.0 MB)
[메모리] forecast_theta 실행 전: 1570.03 MB
[메모리] forecast_theta 실행 후: 1570.03 MB (변화: +0.00 MB)
[SHEN]   [Theta] 완료  첫값=6.82e+05 (메모리: 1570.0 MB)
[SHEN]   [DB] 88행 저장 완료
[PROGRESS] [ 252/500] ( 50.4%)  >>  CGC
[CGC]   40분기 | 2016-03-31 ~ 2025-12-31
[CGC]   [SARIMA] 시작  (메모리: 1570.0 MB)
[메모리] forecast_sarima 실행 전: 1570.03 MB
[메모리] find_best_sarima_params 실행 전: 1570.03 MB
[메모리] find_best_sarima_params 실행 후: 1570.03 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1570.03 MB (변화: +0.00 MB)
[CGC]   [SARIMA] 완료  첫값=6.55e+07 (메모리: 1570.0 MB)
[CGC]   [ETS] 시작  (메모리: 1570.0 MB)
[메모리] forecast_ets 실행 전: 1570.03 MB
[메모리] forecast_ets 실행 후: 1570.04 MB (변화: +0.01 MB)
[CGC]   [ETS] 완료  첫값=6.87e+07 (메모리: 1570.0 MB)
[CGC]   [Prophet] 시작  (메모리: 1570.0 MB)

11:29:50 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1570.04 MB

11:29:50 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1570.77 MB (변화: +0.73 MB)
[CGC]   [Prophet] 완료  첫값=1.09e+08 (메모리: 1570.8 MB)
[CGC]   [LSTM] 시작  (메모리: 1570.8 MB)
[메모리] forecast_lstm 실행 전: 1570.77 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1571.29 MB (변화: +0.51 MB)
[CGC]   [LSTM] 완료  첫값=9.07e+07 (메모리: 1571.3 MB)
[CGC]   [Theta] 시작  (메모리: 1571.3 MB)
[메모리] forecast_theta 실행 전: 1571.29 MB
[메모리] forecast_theta 실행 후: 1571.29 MB (변화: +0.00 MB)
[CGC]   [Theta] 완료  첫값=7.08e+07 (메모리: 1571.3 MB)
[CGC]   [DB] 88행 저장 완료
[PROGRESS] [ 253/500] ( 50.6%)  >>  CDXC
[CDXC]   40분기 | 2016-04-02 ~ 2025-12-31
[CDXC]   [SARIMA] 시작  (메모리: 1571.3 MB)
[메모리] forecast_sarima 실행 전: 1571.29 MB
[메모리] find_best_sarima_params 실행 전: 1571.29 MB
[메모리] find_best_sarima_params 실행 후: 1571.29 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1571.29 MB (변화: +0.00 MB)
[CDXC]   [SARIMA] 완료  첫값=5.54e+06 (메모리: 1571.3 MB)
[CDXC]   [ETS] 시작  (메모리: 1571.3 MB)
[메모리] forecast_ets 실행 전: 1571.29 MB
[메모리] forecast_ets 실행 후: 1571.29 MB (변화: +0.00 MB)
[CDXC]   [ETS] 완료  첫값=3.08e+05 (메모리: 1571.3 MB)
[CDXC]   [Prophet] 시작  (메모리: 1571.3 MB)

11:30:10 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1571.29 MB

11:30:10 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1571.31 MB (변화: +0.02 MB)
[CDXC]   [Prophet] 완료  첫값=2.03e+07 (메모리: 1571.3 MB)
[CDXC]   [LSTM] 시작  (메모리: 1571.3 MB)
[메모리] forecast_lstm 실행 전: 1571.31 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1571.52 MB (변화: +0.21 MB)
[CDXC]   [LSTM] 완료  첫값=1.69e+07 (메모리: 1571.5 MB)
[CDXC]   [Theta] 시작  (메모리: 1571.5 MB)
[메모리] forecast_theta 실행 전: 1571.52 MB
[메모리] forecast_theta 실행 후: 1571.52 MB (변화: +0.00 MB)
[CDXC]   [Theta] 완료  첫값=1.81e+05 (메모리: 1571.5 MB)
[CDXC]   [DB] 88행 저장 완료
[PROGRESS] [ 254/500] ( 50.8%)  >>  HZO
[HZO]   40분기 | 2016-03-31 ~ 2025-12-31
[HZO]   [SARIMA] 시작  (메모리: 1571.5 MB)
[메모리] forecast_sarima 실행 전: 1571.52 MB
[메모리] find_best_sarima_params 실행 전: 1571.52 MB
[메모리] find_best_sarima_params 실행 후: 1571.52 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1571.52 MB (변화: +0.00 MB)
[HZO]   [SARIMA] 완료  첫값=5.91e+08 (메모리: 1571.5 MB)
[HZO]   [ETS] 시작  (메모리: 1571.5 MB)
[메모리] forecast_ets 실행 전: 1571.52 MB
[메모리] forecast_ets 실행 후: 1571.52 MB (변화: +0.00 MB)
[HZO]   [ETS] 완료  첫값=5.57e+08 (메모리: 1571.5 MB)
[HZO]   [Prophet] 시작  (메모리: 1571.5 MB)

11:30:26 - cmdstanpy - INFO - Chain [1] start processing
11:30:26 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1571.52 MB
[메모리] forecast_prophet 실행 후: 1571.18 MB (변화: -0.35 MB)
[HZO]   [Prophet] 완료  첫값=6.79e+08 (메모리: 1571.2 MB)
[HZO]   [LSTM] 시작  (메모리: 1571.2 MB)
[메모리] forecast_lstm 실행 전: 1571.18 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1572.15 MB (변화: +0.97 MB)
[HZO]   [LSTM] 완료  첫값=6.03e+08 (메모리: 1572.1 MB)
[HZO]   [Theta] 시작  (메모리: 1572.1 MB)
[메모리] forecast_theta 실행 전: 1572.15 MB
[메모리] forecast_theta 실행 후: 1572.15 MB (변화: +0.00 MB)
[HZO]   [Theta] 완료  첫값=5.91e+08 (메모리: 1572.1 MB)
[HZO]   [DB] 88행 저장 완료
[PROGRESS] [ 255/500] ( 51.0%)  >>  CRMD
[CRMD]   40분기 | 2016-03-31 ~ 2025-12-31
[CRMD]   [SARIMA] 시작  (메모리: 1572.1 MB)
[메모리] forecast_sarima 실행 전: 1572.15 MB
[메모리] find_best_sarima_params 실행 전: 1572.15 MB
[메모리] find_best_sarima_params 실행 후: 1572.15 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1572.15 MB (변화: +0.00 MB)
[CRMD]   [SARIMA] 완료  첫값=1.54e+08 (메모리: 1572.1 MB)
[CRMD]   [ETS] 시작  (메모리: 1572.1 MB)
[메모리] forecast_ets 실행 전: 1572.15 MB
[메모리] forecast_ets 실행 후: 1572.15 MB (변화: +0.00 MB)
[CRMD]   [ETS] 완료  첫값=1.48e+08 (메모리: 1572.2 MB)
[CRMD]   [Prophet] 시작  (메모리: 1572.2 MB)

11:30:43 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1572.15 MB

11:30:43 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1572.18 MB (변화: +0.02 MB)
[CRMD]   [Prophet] 완료  첫값=3.36e+07 (메모리: 1572.2 MB)
[CRMD]   [LSTM] 시작  (메모리: 1572.2 MB)
[메모리] forecast_lstm 실행 전: 1572.18 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1571.74 MB (변화: -0.44 MB)
[CRMD]   [LSTM] 완료  첫값=1.67e+08 (메모리: 1571.7 MB)
[CRMD]   [Theta] 시작  (메모리: 1571.7 MB)
[메모리] forecast_theta 실행 전: 1571.74 MB
[메모리] forecast_theta 실행 후: 1571.74 MB (변화: +0.00 MB)
[CRMD]   [Theta] 완료  첫값=1.29e+08 (메모리: 1571.7 MB)
[CRMD]   [DB] 88행 저장 완료
[PROGRESS] [ 256/500] ( 51.2%)  >>  AVNS
[AVNS]   40분기 | 2016-03-31 ~ 2025-12-31
[AVNS]   [SARIMA] 시작  (메모리: 1571.7 MB)
[메모리] forecast_sarima 실행 전: 1571.74 MB
[메모리] find_best_sarima_params 실행 전: 1571.74 MB
[메모리] find_best_sarima_params 실행 후: 1571.74 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1571.74 MB (변화: +0.00 MB)
[AVNS]   [SARIMA] 완료  첫값=1.78e+08 (메모리: 1571.7 MB)
[AVNS]   [ETS] 시작  (메모리: 1571.7 MB)
[메모리] forecast_ets 실행 전: 1571.74 MB
[메모리] forecast_ets 실행 후: 1571.75 MB (변화: +0.01 MB)
[AVNS]   [ETS] 완료  첫값=1.72e+08 (메모리: 1571.7 MB)
[AVNS]   [Prophet] 시작  (메모리: 1571.7 MB)

11:31:04 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1571.75 MB

11:31:04 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1571.40 MB (변화: -0.34 MB)
[AVNS]   [Prophet] 완료  첫값=1.31e+08 (메모리: 1571.4 MB)
[AVNS]   [LSTM] 시작  (메모리: 1571.4 MB)
[메모리] forecast_lstm 실행 전: 1571.40 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1572.35 MB (변화: +0.95 MB)
[AVNS]   [LSTM] 완료  첫값=1.77e+08 (메모리: 1572.4 MB)
[AVNS]   [Theta] 시작  (메모리: 1572.4 MB)
[메모리] forecast_theta 실행 전: 1572.35 MB
[메모리] forecast_theta 실행 후: 1572.35 MB (변화: +0.00 MB)
[AVNS]   [Theta] 완료  첫값=1.80e+08 (메모리: 1572.4 MB)
[AVNS]   [DB] 88행 저장 완료
[PROGRESS] [ 257/500] ( 51.4%)  >>  ABST
[ABST]   40분기 | 2013-06-30 ~ 2023-03-31
[ABST]   [SARIMA] 시작  (메모리: 1572.4 MB)
[메모리] forecast_sarima 실행 전: 1572.35 MB
[메모리] find_best_sarima_params 실행 전: 1572.35 MB
[메모리] find_best_sarima_params 실행 후: 1572.35 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1572.35 MB (변화: +0.00 MB)
[ABST]   [SARIMA] 완료  첫값=6.04e+07 (메모리: 1572.4 MB)
[ABST]   [ETS] 시작  (메모리: 1572.4 MB)
[메모리] forecast_ets 실행 전: 1572.35 MB
[메모리] forecast_ets 실행 후: 1572.36 MB (변화: +0.00 MB)
[ABST]   [ETS] 완료  첫값=6.11e+07 (메모리: 1572.4 MB)
[ABST]   [Prophet] 시작  (메모리: 1572.4 MB)

11:31:20 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1572.36 MB

11:31:20 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1571.78 MB (변화: -0.58 MB)
[ABST]   [Prophet] 완료  첫값=4.45e+07 (메모리: 1571.8 MB)
[ABST]   [LSTM] 시작  (메모리: 1571.8 MB)
[메모리] forecast_lstm 실행 전: 1571.78 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1572.89 MB (변화: +1.11 MB)
[ABST]   [LSTM] 완료  첫값=7.35e+07 (메모리: 1572.9 MB)
[ABST]   [Theta] 시작  (메모리: 1572.9 MB)
[메모리] forecast_theta 실행 전: 1572.89 MB
[메모리] forecast_theta 실행 후: 1572.89 MB (변화: +0.00 MB)
[ABST]   [Theta] 완료  첫값=5.84e+07 (메모리: 1572.9 MB)
[ABST]   [DB] 88행 저장 완료
[PROGRESS] [ 258/500] ( 51.6%)  >>  GOGO
[GOGO]   40분기 | 2016-03-31 ~ 2025-12-31
[GOGO]   [SARIMA] 시작  (메모리: 1572.9 MB)
[메모리] forecast_sarima 실행 전: 1572.89 MB
[메모리] find_best_sarima_params 실행 전: 1572.89 MB
[메모리] find_best_sarima_params 실행 후: 1572.89 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1572.89 MB (변화: +0.00 MB)
[GOGO]   [SARIMA] 완료  첫값=2.31e+08 (메모리: 1572.9 MB)
[GOGO]   [ETS] 시작  (메모리: 1572.9 MB)
[메모리] forecast_ets 실행 전: 1572.89 MB
[메모리] forecast_ets 실행 후: 1572.89 MB (변화: +0.00 MB)
[GOGO]   [ETS] 완료  첫값=2.17e+08 (메모리: 1572.9 MB)
[GOGO]   [Prophet] 시작  (메모리: 1572.9 MB)

11:31:39 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1572.89 MB

11:31:39 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1572.92 MB (변화: +0.03 MB)
[GOGO]   [Prophet] 완료  첫값=1.25e+08 (메모리: 1572.9 MB)
[GOGO]   [LSTM] 시작  (메모리: 1572.9 MB)
[메모리] forecast_lstm 실행 전: 1572.92 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1572.88 MB (변화: -0.04 MB)
[GOGO]   [LSTM] 완료  첫값=1.80e+08 (메모리: 1572.9 MB)
[GOGO]   [Theta] 시작  (메모리: 1572.9 MB)
[메모리] forecast_theta 실행 전: 1572.88 MB
[메모리] forecast_theta 실행 후: 1572.88 MB (변화: +0.00 MB)
[GOGO]   [Theta] 완료  첫값=2.30e+08 (메모리: 1572.9 MB)
[GOGO]   [DB] 88행 저장 완료
[PROGRESS] [ 259/500] ( 51.8%)  >>  CMCL
[CMCL]   40분기 | 2016-03-31 ~ 2025-12-31
[CMCL]   [SARIMA] 시작  (메모리: 1572.9 MB)
[메모리] forecast_sarima 실행 전: 1572.88 MB
[메모리] find_best_sarima_params 실행 전: 1572.88 MB
[메모리] find_best_sarima_params 실행 후: 1572.88 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1572.88 MB (변화: +0.00 MB)
[CMCL]   [SARIMA] 완료  첫값=7.43e+07 (메모리: 1572.9 MB)
[CMCL]   [ETS] 시작  (메모리: 1572.9 MB)
[메모리] forecast_ets 실행 전: 1572.88 MB
[메모리] forecast_ets 실행 후: 1572.89 MB (변화: +0.00 MB)
[CMCL]   [ETS] 완료  첫값=6.96e+07 (메모리: 1572.9 MB)
[CMCL]   [Prophet] 시작  (메모리: 1572.9 MB)

11:31:59 - cmdstanpy - INFO - Chain [1] start processing
11:31:59 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1572.89 MB
[메모리] forecast_prophet 실행 후: 1572.91 MB (변화: +0.03 MB)
[CMCL]   [Prophet] 완료  첫값=5.79e+07 (메모리: 1572.9 MB)
[CMCL]   [LSTM] 시작  (메모리: 1572.9 MB)
[메모리] forecast_lstm 실행 전: 1572.91 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1572.55 MB (변화: -0.36 MB)
[CMCL]   [LSTM] 완료  첫값=8.19e+07 (메모리: 1572.6 MB)
[CMCL]   [Theta] 시작  (메모리: 1572.6 MB)
[메모리] forecast_theta 실행 전: 1572.55 MB
[메모리] forecast_theta 실행 후: 1572.55 MB (변화: +0.00 MB)
[CMCL]   [Theta] 완료  첫값=6.79e+07 (메모리: 1572.6 MB)
[CMCL]   [DB] 88행 저장 완료
[PROGRESS] [ 260/500] ( 52.0%)  >>  KOS
[KOS]   40분기 | 2016-03-31 ~ 2025-12-31
[KOS]   [SARIMA] 시작  (메모리: 1572.6 MB)
[메모리] forecast_sarima 실행 전: 1572.55 MB
[메모리] find_best_sarima_params 실행 전: 1572.55 MB
[메모리] find_best_sarima_params 실행 후: 1572.55 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1572.55 MB (변화: +0.00 MB)
[KOS]   [SARIMA] 완료  첫값=3.56e+08 (메모리: 1572.6 MB)
[KOS]   [ETS] 시작  (메모리: 1572.6 MB)
[메모리] forecast_ets 실행 전: 1572.55 MB
[메모리] forecast_ets 실행 후: 1572.56 MB (변화: +0.00 MB)
[KOS]   [ETS] 완료  첫값=2.54e+08 (메모리: 1572.6 MB)
[KOS]   [Prophet] 시작  (메모리: 1572.6 MB)

11:32:16 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1572.56 MB

11:32:16 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1572.58 MB (변화: +0.02 MB)
[KOS]   [Prophet] 완료  첫값=4.93e+08 (메모리: 1572.6 MB)
[KOS]   [LSTM] 시작  (메모리: 1572.6 MB)
[메모리] forecast_lstm 실행 전: 1572.58 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1573.52 MB (변화: +0.95 MB)
[KOS]   [LSTM] 완료  첫값=3.77e+08 (메모리: 1573.5 MB)
[KOS]   [Theta] 시작  (메모리: 1573.5 MB)
[메모리] forecast_theta 실행 전: 1573.52 MB
[메모리] forecast_theta 실행 후: 1573.52 MB (변화: +0.00 MB)
[KOS]   [Theta] 완료  첫값=2.34e+08 (메모리: 1573.5 MB)
[KOS]   [DB] 88행 저장 완료
[PROGRESS] [ 261/500] ( 52.2%)  >>  MNRO
[MNRO]   40분기 | 2016-03-31 ~ 2025-12-27
[MNRO]   [SARIMA] 시작  (메모리: 1573.5 MB)
[메모리] forecast_sarima 실행 전: 1573.52 MB
[메모리] find_best_sarima_params 실행 전: 1573.52 MB
[메모리] find_best_sarima_params 실행 후: 1573.52 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1573.52 MB (변화: +0.00 MB)
[MNRO]   [SARIMA] 완료  첫값=2.95e+08 (메모리: 1573.5 MB)
[MNRO]   [ETS] 시작  (메모리: 1573.5 MB)
[메모리] forecast_ets 실행 전: 1573.52 MB
[메모리] forecast_ets 실행 후: 1573.53 MB (변화: +0.00 MB)
[MNRO]   [ETS] 완료  첫값=2.80e+08 (메모리: 1573.5 MB)
[MNRO]   [Prophet] 시작  (메모리: 1573.5 MB)

11:32:36 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1573.53 MB

11:32:36 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1573.56 MB (변화: +0.03 MB)
[MNRO]   [Prophet] 완료  첫값=3.06e+08 (메모리: 1573.6 MB)
[MNRO]   [LSTM] 시작  (메모리: 1573.6 MB)
[메모리] forecast_lstm 실행 전: 1573.56 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1573.52 MB (변화: -0.04 MB)
[MNRO]   [LSTM] 완료  첫값=3.03e+08 (메모리: 1573.5 MB)
[MNRO]   [Theta] 시작  (메모리: 1573.5 MB)
[메모리] forecast_theta 실행 전: 1573.52 MB
[메모리] forecast_theta 실행 후: 1573.52 MB (변화: +0.00 MB)
[MNRO]   [Theta] 완료  첫값=2.94e+08 (메모리: 1573.5 MB)
[MNRO]   [DB] 88행 저장 완료
[PROGRESS] [ 262/500] ( 52.4%)  >>  APPS
[APPS]   40분기 | 2016-03-31 ~ 2025-12-31
[APPS]   [SARIMA] 시작  (메모리: 1573.5 MB)
[메모리] forecast_sarima 실행 전: 1573.52 MB
[메모리] find_best_sarima_params 실행 전: 1573.52 MB
[메모리] find_best_sarima_params 실행 후: 1573.52 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1573.52 MB (변화: +0.00 MB)
[APPS]   [SARIMA] 완료  첫값=1.45e+08 (메모리: 1573.5 MB)
[APPS]   [ETS] 시작  (메모리: 1573.5 MB)
[메모리] forecast_ets 실행 전: 1573.52 MB
[메모리] forecast_ets 실행 후: 1573.53 MB (변화: +0.00 MB)
[APPS]   [ETS] 완료  첫값=1.34e+08 (메모리: 1573.5 MB)
[APPS]   [Prophet] 시작  (메모리: 1573.5 MB)

11:32:52 - cmdstanpy - INFO - Chain [1] start processing
11:32:52 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1573.53 MB
[메모리] forecast_prophet 실행 후: 1573.53 MB (변화: +0.00 MB)
[APPS]   [Prophet] 완료  첫값=1.76e+08 (메모리: 1573.5 MB)
[APPS]   [LSTM] 시작  (메모리: 1573.5 MB)
[메모리] forecast_lstm 실행 전: 1573.53 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1573.53 MB (변화: +0.00 MB)
[APPS]   [LSTM] 완료  첫값=1.38e+08 (메모리: 1573.5 MB)
[APPS]   [Theta] 시작  (메모리: 1573.5 MB)
[메모리] forecast_theta 실행 전: 1573.53 MB
[메모리] forecast_theta 실행 후: 1573.53 MB (변화: +0.00 MB)
[APPS]   [Theta] 완료  첫값=1.34e+08 (메모리: 1573.5 MB)
[APPS]   [DB] 88행 저장 완료
[PROGRESS] [ 263/500] ( 52.6%)  >>  RGR
[RGR]   40분기 | 2016-04-02 ~ 2025-12-31
[RGR]   [SARIMA] 시작  (메모리: 1573.5 MB)
[메모리] forecast_sarima 실행 전: 1573.53 MB
[메모리] find_best_sarima_params 실행 전: 1573.53 MB
[메모리] find_best_sarima_params 실행 후: 1573.53 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1573.53 MB (변화: +0.00 MB)
[RGR]   [SARIMA] 완료  첫값=1.50e+08 (메모리: 1573.5 MB)
[RGR]   [ETS] 시작  (메모리: 1573.5 MB)
[메모리] forecast_ets 실행 전: 1573.53 MB
[메모리] forecast_ets 실행 후: 1573.53 MB (변화: +0.00 MB)
[RGR]   [ETS] 완료  첫값=1.56e+08 (메모리: 1573.5 MB)
[RGR]   [Prophet] 시작  (메모리: 1573.5 MB)

11:33:11 - cmdstanpy - INFO - Chain [1] start processing
11:33:12 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1573.53 MB
[메모리] forecast_prophet 실행 후: 1573.55 MB (변화: +0.02 MB)
[RGR]   [Prophet] 완료  첫값=1.40e+08 (메모리: 1573.6 MB)
[RGR]   [LSTM] 시작  (메모리: 1573.6 MB)
[메모리] forecast_lstm 실행 전: 1573.55 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1572.14 MB (변화: -1.41 MB)
[RGR]   [LSTM] 완료  첫값=1.35e+08 (메모리: 1572.1 MB)
[RGR]   [Theta] 시작  (메모리: 1572.1 MB)
[메모리] forecast_theta 실행 전: 1572.14 MB
[메모리] forecast_theta 실행 후: 1572.14 MB (변화: +0.00 MB)
[RGR]   [Theta] 완료  첫값=1.51e+08 (메모리: 1572.1 MB)
[RGR]   [DB] 88행 저장 완료
[PROGRESS] [ 264/500] ( 52.8%)  >>  NGVC
[NGVC]   40분기 | 2016-03-31 ~ 2025-12-31
[NGVC]   [SARIMA] 시작  (메모리: 1572.1 MB)
[메모리] forecast_sarima 실행 전: 1572.14 MB
[메모리] find_best_sarima_params 실행 전: 1572.14 MB
[메모리] find_best_sarima_params 실행 후: 1572.14 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1572.14 MB (변화: +0.00 MB)
[NGVC]   [SARIMA] 완료  첫값=3.41e+08 (메모리: 1572.1 MB)
[NGVC]   [ETS] 시작  (메모리: 1572.1 MB)
[메모리] forecast_ets 실행 전: 1572.14 MB
[메모리] forecast_ets 실행 후: 1572.14 MB (변화: +0.00 MB)
[NGVC]   [ETS] 완료  첫값=3.49e+08 (메모리: 1572.1 MB)
[NGVC]   [Prophet] 시작  (메모리: 1572.1 MB)

11:33:32 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1572.14 MB

11:33:32 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1572.17 MB (변화: +0.02 MB)
[NGVC]   [Prophet] 완료  첫값=3.41e+08 (메모리: 1572.2 MB)
[NGVC]   [LSTM] 시작  (메모리: 1572.2 MB)
[메모리] forecast_lstm 실행 전: 1572.17 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1573.17 MB (변화: +1.00 MB)
[NGVC]   [LSTM] 완료  첫값=3.32e+08 (메모리: 1573.2 MB)
[NGVC]   [Theta] 시작  (메모리: 1573.2 MB)
[메모리] forecast_theta 실행 전: 1573.17 MB
[메모리] forecast_theta 실행 후: 1573.17 MB (변화: +0.00 MB)
[NGVC]   [Theta] 완료  첫값=3.46e+08 (메모리: 1573.2 MB)
[NGVC]   [DB] 88행 저장 완료
[PROGRESS] [ 265/500] ( 53.0%)  >>  REPX
[REPX]   40분기 | 2016-03-31 ~ 2025-12-31
[REPX]   [SARIMA] 시작  (메모리: 1573.2 MB)
[메모리] forecast_sarima 실행 전: 1573.17 MB
[메모리] find_best_sarima_params 실행 전: 1573.17 MB
[메모리] find_best_sarima_params 실행 후: 1573.17 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1573.17 MB (변화: +0.00 MB)
[REPX]   [SARIMA] 완료  첫값=1.78e+08 (메모리: 1573.2 MB)
[REPX]   [ETS] 시작  (메모리: 1573.2 MB)
[메모리] forecast_ets 실행 전: 1573.17 MB
[메모리] forecast_ets 실행 후: 1573.17 MB (변화: +0.00 MB)
[REPX]   [ETS] 완료  첫값=1.28e+08 (메모리: 1573.2 MB)
[REPX]   [Prophet] 시작  (메모리: 1573.2 MB)

11:33:46 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1573.17 MB

11:33:46 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1573.20 MB (변화: +0.03 MB)
[REPX]   [Prophet] 완료  첫값=1.15e+08 (메모리: 1573.2 MB)
[REPX]   [LSTM] 시작  (메모리: 1573.2 MB)
[메모리] forecast_lstm 실행 전: 1573.20 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1572.05 MB (변화: -1.15 MB)
[REPX]   [LSTM] 완료  첫값=1.10e+08 (메모리: 1572.1 MB)
[REPX]   [Theta] 시작  (메모리: 1572.1 MB)
[메모리] forecast_theta 실행 전: 1572.05 MB
[메모리] forecast_theta 실행 후: 1572.05 MB (변화: +0.00 MB)
[REPX]   [Theta] 완료  첫값=1.90e+08 (메모리: 1572.1 MB)
[REPX]   [DB] 88행 저장 완료
[PROGRESS] [ 266/500] ( 53.2%)  >>  KRNT
[KRNT]   40분기 | 2016-03-31 ~ 2025-12-31
[KRNT]   [SARIMA] 시작  (메모리: 1572.1 MB)
[메모리] forecast_sarima 실행 전: 1572.05 MB
[메모리] find_best_sarima_params 실행 전: 1572.05 MB
[메모리] find_best_sarima_params 실행 후: 1572.05 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1572.05 MB (변화: +0.00 MB)
[KRNT]   [SARIMA] 완료  첫값=4.92e+07 (메모리: 1572.1 MB)
[KRNT]   [ETS] 시작  (메모리: 1572.1 MB)
[메모리] forecast_ets 실행 전: 1572.05 MB
[메모리] forecast_ets 실행 후: 1572.05 MB (변화: +0.00 MB)
[KRNT]   [ETS] 완료  첫값=4.87e+07 (메모리: 1572.1 MB)
[KRNT]   [Prophet] 시작  (메모리: 1572.1 MB)

11:34:01 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1572.05 MB

11:34:01 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1572.14 MB (변화: +0.09 MB)
[KRNT]   [Prophet] 완료  첫값=6.77e+07 (메모리: 1572.1 MB)
[KRNT]   [LSTM] 시작  (메모리: 1572.1 MB)
[메모리] forecast_lstm 실행 전: 1572.14 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1573.18 MB (변화: +1.03 MB)
[KRNT]   [LSTM] 완료  첫값=5.58e+07 (메모리: 1573.2 MB)
[KRNT]   [Theta] 시작  (메모리: 1573.2 MB)
[메모리] forecast_theta 실행 전: 1573.18 MB
[메모리] forecast_theta 실행 후: 1573.18 MB (변화: +0.00 MB)
[KRNT]   [Theta] 완료  첫값=4.83e+07 (메모리: 1573.2 MB)
[KRNT]   [DB] 88행 저장 완료
[PROGRESS] [ 267/500] ( 53.4%)  >>  EU
[EU]   40분기 | 2016-03-31 ~ 2025-12-31
[EU]   [SARIMA] 시작  (메모리: 1573.2 MB)
[메모리] forecast_sarima 실행 전: 1573.18 MB
[메모리] find_best_sarima_params 실행 전: 1573.18 MB
[메모리] find_best_sarima_params 실행 후: 1573.18 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1573.18 MB (변화: +0.00 MB)
[EU]   [SARIMA] 완료  첫값=1.56e+07 (메모리: 1573.2 MB)
[EU]   [ETS] 시작  (메모리: 1573.2 MB)
[메모리] forecast_ets 실행 전: 1573.18 MB
[메모리] forecast_ets 실행 후: 1573.18 MB (변화: +0.00 MB)
[EU]   [ETS] 완료  첫값=1.88e+07 (메모리: 1573.2 MB)
[EU]   [Prophet] 시작  (메모리: 1573.2 MB)

11:34:17 - cmdstanpy - INFO - Chain [1] start processing
11:34:17 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1573.18 MB
[메모리] forecast_prophet 실행 후: 1573.20 MB (변화: +0.02 MB)
[EU]   [Prophet] 완료  첫값=8.91e+06 (메모리: 1573.2 MB)
[EU]   [LSTM] 시작  (메모리: 1573.2 MB)
[메모리] forecast_lstm 실행 전: 1573.20 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1572.05 MB (변화: -1.14 MB)
[EU]   [LSTM] 완료  첫값=1.34e+07 (메모리: 1572.1 MB)
[EU]   [Theta] 시작  (메모리: 1572.1 MB)
[메모리] forecast_theta 실행 전: 1572.05 MB
[메모리] forecast_theta 실행 후: 1572.05 MB (변화: +0.00 MB)
[EU]   [Theta] 완료  첫값=1.43e+07 (메모리: 1572.1 MB)
[EU]   [DB] 88행 저장 완료
[PROGRESS] [ 268/500] ( 53.6%)  >>  SNDA
[SNDA]   40분기 | 2016-03-31 ~ 2025-12-31
[SNDA]   [SARIMA] 시작  (메모리: 1572.1 MB)
[메모리] forecast_sarima 실행 전: 1572.05 MB
[메모리] find_best_sarima_params 실행 전: 1572.05 MB
[메모리] find_best_sarima_params 실행 후: 1572.05 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1572.05 MB (변화: +0.00 MB)
[SNDA]   [SARIMA] 완료  첫값=9.75e+07 (메모리: 1572.1 MB)
[SNDA]   [ETS] 시작  (메모리: 1572.1 MB)
[메모리] forecast_ets 실행 전: 1572.05 MB
[메모리] forecast_ets 실행 후: 1572.05 MB (변화: +0.00 MB)
[SNDA]   [ETS] 완료  첫값=9.81e+07 (메모리: 1572.1 MB)
[SNDA]   [Prophet] 시작  (메모리: 1572.1 MB)

11:34:36 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1572.05 MB

11:34:37 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1572.07 MB (변화: +0.02 MB)
[SNDA]   [Prophet] 완료  첫값=5.99e+07 (메모리: 1572.1 MB)
[SNDA]   [LSTM] 시작  (메모리: 1572.1 MB)
[메모리] forecast_lstm 실행 전: 1572.07 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1571.42 MB (변화: -0.65 MB)
[SNDA]   [LSTM] 완료  첫값=8.96e+07 (메모리: 1571.4 MB)
[SNDA]   [Theta] 시작  (메모리: 1571.4 MB)
[메모리] forecast_theta 실행 전: 1571.42 MB
[메모리] forecast_theta 실행 후: 1571.42 MB (변화: +0.00 MB)
[SNDA]   [Theta] 완료  첫값=9.39e+07 (메모리: 1571.4 MB)
[SNDA]   [DB] 88행 저장 완료
[PROGRESS] [ 269/500] ( 53.8%)  >>  CEVA
[CEVA]   40분기 | 2016-03-31 ~ 2025-12-31
[CEVA]   [SARIMA] 시작  (메모리: 1571.4 MB)
[메모리] forecast_sarima 실행 전: 1571.42 MB
[메모리] find_best_sarima_params 실행 전: 1571.42 MB
[메모리] find_best_sarima_params 실행 후: 1571.42 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1571.42 MB (변화: +0.00 MB)
[CEVA]   [SARIMA] 완료  첫값=2.73e+07 (메모리: 1571.4 MB)
[CEVA]   [ETS] 시작  (메모리: 1571.4 MB)
[메모리] forecast_ets 실행 전: 1571.42 MB
[메모리] forecast_ets 실행 후: 1571.42 MB (변화: +0.00 MB)
[CEVA]   [ETS] 완료  첫값=2.73e+07 (메모리: 1571.4 MB)
[CEVA]   [Prophet] 시작  (메모리: 1571.4 MB)

11:34:56 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1571.42 MB

11:34:56 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1571.44 MB (변화: +0.02 MB)
[CEVA]   [Prophet] 완료  첫값=3.06e+07 (메모리: 1571.4 MB)
[CEVA]   [LSTM] 시작  (메모리: 1571.4 MB)
[메모리] forecast_lstm 실행 전: 1571.44 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1571.61 MB (변화: +0.17 MB)
[CEVA]   [LSTM] 완료  첫값=2.72e+07 (메모리: 1571.6 MB)
[CEVA]   [Theta] 시작  (메모리: 1571.6 MB)
[메모리] forecast_theta 실행 전: 1571.61 MB
[메모리] forecast_theta 실행 후: 1571.61 MB (변화: +0.00 MB)
[CEVA]   [Theta] 완료  첫값=2.71e+07 (메모리: 1571.6 MB)
[CEVA]   [DB] 88행 저장 완료
[PROGRESS] [ 270/500] ( 54.0%)  >>  HOV
[HOV]   40분기 | 2016-04-30 ~ 2026-01-31
[HOV]   [SARIMA] 시작  (메모리: 1571.6 MB)
[메모리] forecast_sarima 실행 전: 1571.61 MB
[메모리] find_best_sarima_params 실행 전: 1571.61 MB
[메모리] find_best_sarima_params 실행 후: 1571.61 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1571.61 MB (변화: +0.00 MB)
[HOV]   [SARIMA] 완료  첫값=7.22e+08 (메모리: 1571.6 MB)
[HOV]   [ETS] 시작  (메모리: 1571.6 MB)
[메모리] forecast_ets 실행 전: 1571.61 MB
[메모리] forecast_ets 실행 후: 1571.61 MB (변화: +0.00 MB)
[HOV]   [ETS] 완료  첫값=7.08e+08 (메모리: 1571.6 MB)
[HOV]   [Prophet] 시작  (메모리: 1571.6 MB)

11:35:16 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1571.61 MB

11:35:16 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1571.27 MB (변화: -0.34 MB)
[HOV]   [Prophet] 완료  첫값=7.61e+08 (메모리: 1571.3 MB)
[HOV]   [LSTM] 시작  (메모리: 1571.3 MB)
[메모리] forecast_lstm 실행 전: 1571.27 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1572.24 MB (변화: +0.98 MB)
[HOV]   [LSTM] 완료  첫값=7.27e+08 (메모리: 1572.2 MB)
[HOV]   [Theta] 시작  (메모리: 1572.2 MB)
[메모리] forecast_theta 실행 전: 1572.24 MB
[메모리] forecast_theta 실행 후: 1572.24 MB (변화: +0.00 MB)
[HOV]   [Theta] 완료  첫값=7.20e+08 (메모리: 1572.2 MB)
[HOV]   [DB] 88행 저장 완료
[PROGRESS] [ 271/500] ( 54.2%)  >>  CMCO
[CMCO]   40분기 | 2016-03-31 ~ 2025-12-31
[CMCO]   [SARIMA] 시작  (메모리: 1572.2 MB)
[메모리] forecast_sarima 실행 전: 1572.24 MB
[메모리] find_best_sarima_params 실행 전: 1572.24 MB
[메모리] find_best_sarima_params 실행 후: 1572.24 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1572.24 MB (변화: +0.00 MB)
[CMCO]   [SARIMA] 완료  첫값=2.62e+08 (메모리: 1572.2 MB)
[CMCO]   [ETS] 시작  (메모리: 1572.2 MB)
[메모리] forecast_ets 실행 전: 1572.24 MB
[메모리] forecast_ets 실행 후: 1572.25 MB (변화: +0.00 MB)
[CMCO]   [ETS] 완료  첫값=2.77e+08 (메모리: 1572.2 MB)
[CMCO]   [Prophet] 시작  (메모리: 1572.2 MB)

11:35:32 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1572.25 MB

11:35:32 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1572.27 MB (변화: +0.02 MB)
[CMCO]   [Prophet] 완료  첫값=2.59e+08 (메모리: 1572.3 MB)
[CMCO]   [LSTM] 시작  (메모리: 1572.3 MB)
[메모리] forecast_lstm 실행 전: 1572.27 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1572.38 MB (변화: +0.11 MB)
[CMCO]   [LSTM] 완료  첫값=2.72e+08 (메모리: 1572.4 MB)
[CMCO]   [Theta] 시작  (메모리: 1572.4 MB)
[메모리] forecast_theta 실행 전: 1572.38 MB
[메모리] forecast_theta 실행 후: 1572.38 MB (변화: +0.00 MB)
[CMCO]   [Theta] 완료  첫값=2.60e+08 (메모리: 1572.4 MB)
[CMCO]   [DB] 88행 저장 완료
[PROGRESS] [ 272/500] ( 54.4%)  >>  LAB
[LAB]   40분기 | 2016-03-31 ~ 2025-12-31
[LAB]   [SARIMA] 시작  (메모리: 1572.4 MB)
[메모리] forecast_sarima 실행 전: 1572.38 MB
[메모리] find_best_sarima_params 실행 전: 1572.38 MB
[메모리] find_best_sarima_params 실행 후: 1572.38 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1572.38 MB (변화: +0.00 MB)
[LAB]   [SARIMA] 완료  첫값=7.67e+06 (메모리: 1572.4 MB)
[LAB]   [ETS] 시작  (메모리: 1572.4 MB)
[메모리] forecast_ets 실행 전: 1572.38 MB
[메모리] forecast_ets 실행 후: 1572.38 MB (변화: +0.00 MB)
[LAB]   [ETS] 완료  첫값=1.75e+06 (메모리: 1572.4 MB)
[LAB]   [Prophet] 시작  (메모리: 1572.4 MB)

11:35:46 - cmdstanpy - INFO - Chain [1] start processing
11:35:46 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1572.38 MB
[메모리] forecast_prophet 실행 후: 1571.91 MB (변화: -0.48 MB)
[LAB]   [Prophet] 완료  첫값=3.00e+07 (메모리: 1571.9 MB)
[LAB]   [LSTM] 시작  (메모리: 1571.9 MB)
[메모리] forecast_lstm 실행 전: 1571.91 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1572.89 MB (변화: +0.98 MB)
[LAB]   [LSTM] 완료  첫값=2.96e+07 (메모리: 1572.9 MB)
[LAB]   [Theta] 시작  (메모리: 1572.9 MB)
[메모리] forecast_theta 실행 전: 1572.89 MB
[메모리] forecast_theta 실행 후: 1572.89 MB (변화: +0.00 MB)
[LAB]   [Theta] 완료  첫값=2.65e+07 (메모리: 1572.9 MB)
[LAB]   [DB] 88행 저장 완료
[PROGRESS] [ 273/500] ( 54.6%)  >>  TBN
[TBN] [NEG-SKIP] [TBN] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2023, 3, 31)])
[PROGRESS] [ 274/500] ( 54.8%)  >>  APEN
[APEN]   40분기 | 2013-03-31 ~ 2022-12-31
[APEN]   [SARIMA] 시작  (메모리: 1572.9 MB)
[메모리] forecast_sarima 실행 전: 1572.89 MB
[메모리] find_best_sarima_params 실행 전: 1572.89 MB
[메모리] find_best_sarima_params 실행 후: 1572.89 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1572.89 MB (변화: +0.00 MB)
[APEN]   [SARIMA] 완료  첫값=1.73e+07 (메모리: 1572.9 MB)
[APEN]   [ETS] 시작  (메모리: 1572.9 MB)
[메모리] forecast_ets 실행 전: 1572.89 MB
[메모리] forecast_ets 실행 후: 1572.89 MB (변화: +0.00 MB)
[APEN]   [ETS] 완료  첫값=1.75e+07 (메모리: 1572.9 MB)
[APEN]   [Prophet] 시작  (메모리: 1572.9 MB)

11:35:59 - cmdstanpy - INFO - Chain [1] start processing
11:36:00 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1572.89 MB
[메모리] forecast_prophet 실행 후: 1572.91 MB (변화: +0.02 MB)
[APEN]   [Prophet] 완료  첫값=2.04e+07 (메모리: 1572.9 MB)
[APEN]   [LSTM] 시작  (메모리: 1572.9 MB)
[메모리] forecast_lstm 실행 전: 1572.91 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1572.88 MB (변화: -0.03 MB)
[APEN]   [LSTM] 완료  첫값=1.52e+07 (메모리: 1572.9 MB)
[APEN]   [Theta] 시작  (메모리: 1572.9 MB)
[메모리] forecast_theta 실행 전: 1572.88 MB
[메모리] forecast_theta 실행 후: 1572.88 MB (변화: +0.00 MB)
[APEN]   [Theta] 완료  첫값=2.26e+07 (메모리: 1572.9 MB)
[APEN]   [DB] 88행 저장 완료
[PROGRESS] [ 275/500] ( 55.0%)  >>  CASS
[CASS]   40분기 | 2016-03-31 ~ 2025-12-31
[CASS]   [SARIMA] 시작  (메모리: 1572.9 MB)
[메모리] forecast_sarima 실행 전: 1572.88 MB
[메모리] find_best_sarima_params 실행 전: 1572.88 MB
[메모리] find_best_sarima_params 실행 후: 1572.88 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1572.88 MB (변화: +0.00 MB)
[CASS]   [SARIMA] 완료  첫값=5.01e+07 (메모리: 1572.9 MB)
[CASS]   [ETS] 시작  (메모리: 1572.9 MB)
[메모리] forecast_ets 실행 전: 1572.88 MB
[메모리] forecast_ets 실행 후: 1572.88 MB (변화: +0.00 MB)
[CASS]   [ETS] 완료  첫값=4.90e+07 (메모리: 1572.9 MB)
[CASS]   [Prophet] 시작  (메모리: 1572.9 MB)

11:36:20 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1572.88 MB

11:36:20 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1572.91 MB (변화: +0.03 MB)
[CASS]   [Prophet] 완료  첫값=5.45e+07 (메모리: 1572.9 MB)
[CASS]   [LSTM] 시작  (메모리: 1572.9 MB)
[메모리] forecast_lstm 실행 전: 1572.91 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1572.20 MB (변화: -0.71 MB)
[CASS]   [LSTM] 완료  첫값=5.29e+07 (메모리: 1572.2 MB)
[CASS]   [Theta] 시작  (메모리: 1572.2 MB)
[메모리] forecast_theta 실행 전: 1572.20 MB
[메모리] forecast_theta 실행 후: 1572.20 MB (변화: +0.00 MB)
[CASS]   [Theta] 완료  첫값=4.87e+07 (메모리: 1572.2 MB)
[CASS]   [DB] 88행 저장 완료
[PROGRESS] [ 276/500] ( 55.2%)  >>  BDSI
[BDSI]   40분기 | 2012-03-31 ~ 2021-12-31
[BDSI]   [SARIMA] 시작  (메모리: 1572.2 MB)
[메모리] forecast_sarima 실행 전: 1572.20 MB
[메모리] find_best_sarima_params 실행 전: 1572.20 MB
[메모리] find_best_sarima_params 실행 후: 1572.20 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1572.20 MB (변화: +0.00 MB)
[BDSI]   [SARIMA] 완료  첫값=4.91e+07 (메모리: 1572.2 MB)
[BDSI]   [ETS] 시작  (메모리: 1572.2 MB)
[메모리] forecast_ets 실행 전: 1572.20 MB
[메모리] forecast_ets 실행 후: 1572.20 MB (변화: +0.00 MB)
[BDSI]   [ETS] 완료  첫값=4.62e+07 (메모리: 1572.2 MB)
[BDSI]   [Prophet] 시작  (메모리: 1572.2 MB)

11:36:33 - cmdstanpy - INFO - Chain [1] start processing
11:36:33 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1572.20 MB
[메모리] forecast_prophet 실행 후: 1572.21 MB (변화: +0.01 MB)
[BDSI]   [Prophet] 완료  첫값=3.72e+07 (메모리: 1572.2 MB)
[BDSI]   [LSTM] 시작  (메모리: 1572.2 MB)
[메모리] forecast_lstm 실행 전: 1572.21 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1573.22 MB (변화: +1.01 MB)
[BDSI]   [LSTM] 완료  첫값=5.62e+07 (메모리: 1573.2 MB)
[BDSI]   [Theta] 시작  (메모리: 1573.2 MB)
[메모리] forecast_theta 실행 전: 1573.22 MB
[메모리] forecast_theta 실행 후: 1573.22 MB (변화: +0.00 MB)
[BDSI]   [Theta] 완료  첫값=4.68e+07 (메모리: 1573.2 MB)
[BDSI]   [DB] 88행 저장 완료
[PROGRESS] [ 277/500] ( 55.4%)  >>  CTO
[CTO]   40분기 | 2016-03-31 ~ 2025-12-31
[CTO]   [SARIMA] 시작  (메모리: 1573.2 MB)
[메모리] forecast_sarima 실행 전: 1573.22 MB
[메모리] find_best_sarima_params 실행 전: 1573.22 MB
[메모리] find_best_sarima_params 실행 후: 1573.22 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1573.22 MB (변화: +0.00 MB)
[CTO]   [SARIMA] 완료  첫값=3.79e+07 (메모리: 1573.2 MB)
[CTO]   [ETS] 시작  (메모리: 1573.2 MB)
[메모리] forecast_ets 실행 전: 1573.22 MB
[메모리] forecast_ets 실행 후: 1573.22 MB (변화: +0.00 MB)
[CTO]   [ETS] 완료  첫값=4.04e+07 (메모리: 1573.2 MB)
[CTO]   [Prophet] 시작  (메모리: 1573.2 MB)

11:36:51 - cmdstanpy - INFO - Chain [1] start processing
11:36:51 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1573.22 MB
[메모리] forecast_prophet 실행 후: 1573.25 MB (변화: +0.02 MB)
[CTO]   [Prophet] 완료  첫값=3.13e+07 (메모리: 1573.2 MB)
[CTO]   [LSTM] 시작  (메모리: 1573.2 MB)
[메모리] forecast_lstm 실행 전: 1573.25 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1573.51 MB (변화: +0.27 MB)
[CTO]   [LSTM] 완료  첫값=4.16e+07 (메모리: 1573.5 MB)
[CTO]   [Theta] 시작  (메모리: 1573.5 MB)
[메모리] forecast_theta 실행 전: 1573.51 MB
[메모리] forecast_theta 실행 후: 1573.51 MB (변화: +0.00 MB)
[CTO]   [Theta] 완료  첫값=3.87e+07 (메모리: 1573.5 MB)
[CTO]   [DB] 88행 저장 완료
[PROGRESS] [ 278/500] ( 55.6%)  >>  LE
[LE]   40분기 | 2016-04-29 ~ 2026-01-30
[LE]   [SARIMA] 시작  (메모리: 1573.5 MB)
[메모리] forecast_sarima 실행 전: 1573.51 MB
[메모리] find_best_sarima_params 실행 전: 1573.51 MB
[메모리] find_best_sarima_params 실행 후: 1573.51 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1573.51 MB (변화: +0.00 MB)
[LE]   [SARIMA] 완료  첫값=2.65e+08 (메모리: 1573.5 MB)
[LE]   [ETS] 시작  (메모리: 1573.5 MB)
[메모리] forecast_ets 실행 전: 1573.51 MB
[메모리] forecast_ets 실행 후: 1573.52 MB (변화: +0.01 MB)
[LE]   [ETS] 완료  첫값=2.57e+08 (메모리: 1573.5 MB)
[LE]   [Prophet] 시작  (메모리: 1573.5 MB)

11:37:11 - cmdstanpy - INFO - Chain [1] start processing
11:37:11 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1573.52 MB
[메모리] forecast_prophet 실행 후: 1573.55 MB (변화: +0.03 MB)
[LE]   [Prophet] 완료  첫값=3.76e+08 (메모리: 1573.6 MB)
[LE]   [LSTM] 시작  (메모리: 1573.6 MB)
[메모리] forecast_lstm 실행 전: 1573.55 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1574.30 MB (변화: +0.75 MB)
[LE]   [LSTM] 완료  첫값=3.76e+08 (메모리: 1574.3 MB)
[LE]   [Theta] 시작  (메모리: 1574.3 MB)
[메모리] forecast_theta 실행 전: 1574.30 MB
[메모리] forecast_theta 실행 후: 1574.30 MB (변화: +0.00 MB)
[LE]   [Theta] 완료  첫값=2.57e+08 (메모리: 1574.3 MB)
[LE]   [DB] 88행 저장 완료
[PROGRESS] [ 279/500] ( 55.8%)  >>  KOP
[KOP]   40분기 | 2016-03-31 ~ 2025-12-31
[KOP]   [SARIMA] 시작  (메모리: 1574.3 MB)
[메모리] forecast_sarima 실행 전: 1574.30 MB
[메모리] find_best_sarima_params 실행 전: 1574.30 MB
[메모리] find_best_sarima_params 실행 후: 1574.30 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1574.30 MB (변화: +0.00 MB)
[KOP]   [SARIMA] 완료  첫값=4.40e+08 (메모리: 1574.3 MB)
[KOP]   [ETS] 시작  (메모리: 1574.3 MB)
[메모리] forecast_ets 실행 전: 1574.30 MB
[메모리] forecast_ets 실행 후: 1574.30 MB (변화: +0.00 MB)
[KOP]   [ETS] 완료  첫값=4.54e+08 (메모리: 1574.3 MB)
[KOP]   [Prophet] 시작  (메모리: 1574.3 MB)

11:37:28 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1574.30 MB

11:37:28 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1574.32 MB (변화: +0.02 MB)
[KOP]   [Prophet] 완료  첫값=5.32e+08 (메모리: 1574.3 MB)
[KOP]   [LSTM] 시작  (메모리: 1574.3 MB)
[메모리] forecast_lstm 실행 전: 1574.32 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1573.95 MB (변화: -0.38 MB)
[KOP]   [LSTM] 완료  첫값=4.98e+08 (메모리: 1573.9 MB)
[KOP]   [Theta] 시작  (메모리: 1573.9 MB)
[메모리] forecast_theta 실행 전: 1573.95 MB
[메모리] forecast_theta 실행 후: 1573.95 MB (변화: +0.00 MB)
[KOP]   [Theta] 완료  첫값=4.53e+08 (메모리: 1573.9 MB)
[KOP]   [DB] 88행 저장 완료
[PROGRESS] [ 280/500] ( 56.0%)  >>  TRNS
[TRNS]   39분기 | 2016-06-25 ~ 2025-12-27
[TRNS]   [SARIMA] 시작  (메모리: 1573.9 MB)
[메모리] forecast_sarima 실행 전: 1573.95 MB
[메모리] find_best_sarima_params 실행 전: 1573.95 MB
[메모리] find_best_sarima_params 실행 후: 1573.97 MB (변화: +0.03 MB)
[메모리] forecast_sarima 실행 후: 1573.97 MB (변화: +0.03 MB)
[TRNS]   [SARIMA] 완료  첫값=9.12e+07 (메모리: 1574.0 MB)
[TRNS]   [ETS] 시작  (메모리: 1574.0 MB)
[메모리] forecast_ets 실행 전: 1573.97 MB
[메모리] forecast_ets 실행 후: 1573.97 MB (변화: +0.00 MB)
[TRNS]   [ETS] 완료  첫값=9.33e+07 (메모리: 1574.0 MB)
[TRNS]   [Prophet] 시작  (메모리: 1574.0 MB)

11:37:46 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1573.97 MB

11:37:46 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1573.99 MB (변화: +0.02 MB)
[TRNS]   [Prophet] 완료  첫값=8.00e+07 (메모리: 1574.0 MB)
[TRNS]   [LSTM] 시작  (메모리: 1574.0 MB)
[메모리] forecast_lstm 실행 전: 1573.99 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1574.97 MB (변화: +0.98 MB)
[TRNS]   [LSTM] 완료  첫값=7.89e+07 (메모리: 1575.0 MB)
[TRNS]   [Theta] 시작  (메모리: 1575.0 MB)
[메모리] forecast_theta 실행 전: 1574.97 MB
[메모리] forecast_theta 실행 후: 1574.97 MB (변화: +0.00 MB)
[TRNS]   [Theta] 완료  첫값=8.96e+07 (메모리: 1575.0 MB)
[TRNS]   [DB] 87행 저장 완료
[PROGRESS] [ 281/500] ( 56.2%)  >>  ANGI
[ANGI]   40분기 | 2016-03-31 ~ 2025-12-31
[ANGI]   [SARIMA] 시작  (메모리: 1575.0 MB)
[메모리] forecast_sarima 실행 전: 1574.97 MB
[메모리] find_best_sarima_params 실행 전: 1574.97 MB
[메모리] find_best_sarima_params 실행 후: 1574.97 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1574.97 MB (변화: +0.00 MB)
[ANGI]   [SARIMA] 완료  첫값=2.45e+08 (메모리: 1575.0 MB)
[ANGI]   [ETS] 시작  (메모리: 1575.0 MB)
[메모리] forecast_ets 실행 전: 1574.97 MB
[메모리] forecast_ets 실행 후: 1574.98 MB (변화: +0.00 MB)
[ANGI]   [ETS] 완료  첫값=2.51e+08 (메모리: 1575.0 MB)
[ANGI]   [Prophet] 시작  (메모리: 1575.0 MB)

11:38:01 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1574.98 MB

11:38:01 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1575.00 MB (변화: +0.02 MB)
[ANGI]   [Prophet] 완료  첫값=4.01e+08 (메모리: 1575.0 MB)
[ANGI]   [LSTM] 시작  (메모리: 1575.0 MB)
[메모리] forecast_lstm 실행 전: 1575.00 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1574.23 MB (변화: -0.76 MB)
[ANGI]   [LSTM] 완료  첫값=2.85e+08 (메모리: 1574.2 MB)
[ANGI]   [Theta] 시작  (메모리: 1574.2 MB)
[메모리] forecast_theta 실행 전: 1574.23 MB
[메모리] forecast_theta 실행 후: 1574.23 MB (변화: +0.00 MB)
[ANGI]   [Theta] 완료  첫값=2.46e+08 (메모리: 1574.2 MB)
[ANGI]   [DB] 88행 저장 완료
[PROGRESS] [ 282/500] ( 56.4%)  >>  LXRX
[LXRX]   40분기 | 2016-03-31 ~ 2025-12-31
[LXRX]   [SARIMA] 시작  (메모리: 1574.2 MB)
[메모리] forecast_sarima 실행 전: 1574.23 MB
[메모리] find_best_sarima_params 실행 전: 1574.23 MB
[메모리] find_best_sarima_params 실행 후: 1574.23 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1574.23 MB (변화: +0.00 MB)
[LXRX]   [SARIMA] 완료  첫값=5.79e+06 (메모리: 1574.2 MB)
[LXRX]   [ETS] 시작  (메모리: 1574.2 MB)
[메모리] forecast_ets 실행 전: 1574.23 MB
[메모리] forecast_ets 실행 후: 1574.24 MB (변화: +0.00 MB)
[LXRX]   [ETS] 완료  첫값=3.94e+06 (메모리: 1574.2 MB)
[LXRX]   [Prophet] 시작  (메모리: 1574.2 MB)

11:38:14 - cmdstanpy - INFO - Chain [1] start processing
11:38:14 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1574.24 MB
[메모리] forecast_prophet 실행 후: 1574.26 MB (변화: +0.02 MB)
[LXRX]   [Prophet] 완료  첫값=1.76e+06 (메모리: 1574.3 MB)
[LXRX]   [LSTM] 시작  (메모리: 1574.3 MB)
[메모리] forecast_lstm 실행 전: 1574.26 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1575.23 MB (변화: +0.96 MB)
[LXRX]   [LSTM] 완료  첫값=1.18e+07 (메모리: 1575.2 MB)
[LXRX]   [Theta] 시작  (메모리: 1575.2 MB)
[메모리] forecast_theta 실행 전: 1575.23 MB
[메모리] forecast_theta 실행 후: 1575.23 MB (변화: +0.00 MB)
[LXRX]   [Theta] 완료  첫값=3.58e+06 (메모리: 1575.2 MB)
[LXRX]   [DB] 88행 저장 완료
[PROGRESS] [ 283/500] ( 56.6%)  >>  VPG
[VPG]   40분기 | 2016-04-02 ~ 2025-12-31
[VPG]   [SARIMA] 시작  (메모리: 1575.2 MB)
[메모리] forecast_sarima 실행 전: 1575.23 MB
[메모리] find_best_sarima_params 실행 전: 1575.23 MB
[메모리] find_best_sarima_params 실행 후: 1575.23 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1575.23 MB (변화: +0.00 MB)
[VPG]   [SARIMA] 완료  첫값=8.13e+07 (메모리: 1575.2 MB)
[VPG]   [ETS] 시작  (메모리: 1575.2 MB)
[메모리] forecast_ets 실행 전: 1575.23 MB
[메모리] forecast_ets 실행 후: 1575.23 MB (변화: +0.00 MB)
[VPG]   [ETS] 완료  첫값=7.88e+07 (메모리: 1575.2 MB)
[VPG]   [Prophet] 시작  (메모리: 1575.2 MB)

11:38:34 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1575.23 MB

11:38:34 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1575.26 MB (변화: +0.03 MB)
[VPG]   [Prophet] 완료  첫값=8.72e+07 (메모리: 1575.3 MB)
[VPG]   [LSTM] 시작  (메모리: 1575.3 MB)
[메모리] forecast_lstm 실행 전: 1575.26 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1575.23 MB (변화: -0.03 MB)
[VPG]   [LSTM] 완료  첫값=7.97e+07 (메모리: 1575.2 MB)
[VPG]   [Theta] 시작  (메모리: 1575.2 MB)
[메모리] forecast_theta 실행 전: 1575.23 MB
[메모리] forecast_theta 실행 후: 1575.23 MB (변화: +0.00 MB)
[VPG]   [Theta] 완료  첫값=7.85e+07 (메모리: 1575.2 MB)
[VPG]   [DB] 88행 저장 완료
[PROGRESS] [ 284/500] ( 56.8%)  >>  BYON
[BYON]   40분기 | 2016-03-31 ~ 2025-12-31
[BYON]   [SARIMA] 시작  (메모리: 1575.2 MB)
[메모리] forecast_sarima 실행 전: 1575.23 MB
[메모리] find_best_sarima_params 실행 전: 1575.23 MB
[메모리] find_best_sarima_params 실행 후: 1575.23 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1575.23 MB (변화: +0.00 MB)
[BYON]   [SARIMA] 완료  첫값=2.51e+08 (메모리: 1575.2 MB)
[BYON]   [ETS] 시작  (메모리: 1575.2 MB)
[메모리] forecast_ets 실행 전: 1575.23 MB
[메모리] forecast_ets 실행 후: 1575.24 MB (변화: +0.00 MB)
[BYON]   [ETS] 완료  첫값=2.44e+08 (메모리: 1575.2 MB)
[BYON]   [Prophet] 시작  (메모리: 1575.2 MB)

11:38:54 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1575.24 MB

11:38:54 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1575.26 MB (변화: +0.02 MB)
[BYON]   [Prophet] 완료  첫값=3.83e+08 (메모리: 1575.3 MB)
[BYON]   [LSTM] 시작  (메모리: 1575.3 MB)
[메모리] forecast_lstm 실행 전: 1575.26 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1575.23 MB (변화: -0.03 MB)
[BYON]   [LSTM] 완료  첫값=3.75e+08 (메모리: 1575.2 MB)
[BYON]   [Theta] 시작  (메모리: 1575.2 MB)
[메모리] forecast_theta 실행 전: 1575.23 MB
[메모리] forecast_theta 실행 후: 1575.23 MB (변화: +0.00 MB)
[BYON]   [Theta] 완료  첫값=2.70e+08 (메모리: 1575.2 MB)
[BYON]   [DB] 88행 저장 완료
[PROGRESS] [ 285/500] ( 57.0%)  >>  RYAM
[RYAM]   40분기 | 2016-03-26 ~ 2025-12-31
[RYAM]   [SARIMA] 시작  (메모리: 1575.2 MB)
[메모리] forecast_sarima 실행 전: 1575.23 MB
[메모리] find_best_sarima_params 실행 전: 1575.23 MB
[메모리] find_best_sarima_params 실행 후: 1575.23 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1575.23 MB (변화: +0.00 MB)
[RYAM]   [SARIMA] 완료  첫값=3.91e+08 (메모리: 1575.2 MB)
[RYAM]   [ETS] 시작  (메모리: 1575.2 MB)
[메모리] forecast_ets 실행 전: 1575.23 MB
[메모리] forecast_ets 실행 후: 1575.23 MB (변화: +0.00 MB)
[RYAM]   [ETS] 완료  첫값=3.81e+08 (메모리: 1575.2 MB)
[RYAM]   [Prophet] 시작  (메모리: 1575.2 MB)

11:39:09 - cmdstanpy - INFO - Chain [1] start processing
11:39:09 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1575.23 MB
[메모리] forecast_prophet 실행 후: 1575.26 MB (변화: +0.03 MB)
[RYAM]   [Prophet] 완료  첫값=4.37e+08 (메모리: 1575.3 MB)
[RYAM]   [LSTM] 시작  (메모리: 1575.3 MB)
[메모리] forecast_lstm 실행 전: 1575.26 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1575.23 MB (변화: -0.03 MB)
[RYAM]   [LSTM] 완료  첫값=3.70e+08 (메모리: 1575.2 MB)
[RYAM]   [Theta] 시작  (메모리: 1575.2 MB)
[메모리] forecast_theta 실행 전: 1575.23 MB
[메모리] forecast_theta 실행 후: 1575.23 MB (변화: +0.00 MB)
[RYAM]   [Theta] 완료  첫값=4.19e+08 (메모리: 1575.2 MB)
[RYAM]   [DB] 88행 저장 완료
[PROGRESS] [ 286/500] ( 57.2%)  >>  HY
[HY]   40분기 | 2016-03-31 ~ 2025-12-31
[HY]   [SARIMA] 시작  (메모리: 1575.2 MB)
[메모리] forecast_sarima 실행 전: 1575.23 MB
[메모리] find_best_sarima_params 실행 전: 1575.23 MB
[메모리] find_best_sarima_params 실행 후: 1575.23 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1575.23 MB (변화: +0.00 MB)
[HY]   [SARIMA] 완료  첫값=9.33e+08 (메모리: 1575.2 MB)
[HY]   [ETS] 시작  (메모리: 1575.2 MB)
[메모리] forecast_ets 실행 전: 1575.23 MB
[메모리] forecast_ets 실행 후: 1575.24 MB (변화: +0.00 MB)
[HY]   [ETS] 완료  첫값=9.09e+08 (메모리: 1575.2 MB)
[HY]   [Prophet] 시작  (메모리: 1575.2 MB)

11:39:25 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1575.24 MB

11:39:25 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1575.25 MB (변화: +0.02 MB)
[HY]   [Prophet] 완료  첫값=1.04e+09 (메모리: 1575.3 MB)
[HY]   [LSTM] 시작  (메모리: 1575.3 MB)
[메모리] forecast_lstm 실행 전: 1575.25 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1575.21 MB (변화: -0.04 MB)
[HY]   [LSTM] 완료  첫값=1.01e+09 (메모리: 1575.2 MB)
[HY]   [Theta] 시작  (메모리: 1575.2 MB)
[메모리] forecast_theta 실행 전: 1575.21 MB
[메모리] forecast_theta 실행 후: 1575.21 MB (변화: +0.00 MB)
[HY]   [Theta] 완료  첫값=9.09e+08 (메모리: 1575.2 MB)
[HY]   [DB] 88행 저장 완료
[PROGRESS] [ 287/500] ( 57.4%)  >>  RGLS
[RGLS]   40분기 | 2015-06-30 ~ 2025-03-31
[RGLS]   [SARIMA] 시작  (메모리: 1575.2 MB)
[메모리] forecast_sarima 실행 전: 1575.21 MB
[메모리] find_best_sarima_params 실행 전: 1575.21 MB
[메모리] find_best_sarima_params 실행 후: 1575.21 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1575.21 MB (변화: +0.00 MB)
[RGLS]   [SARIMA] 완료  첫값=-2.93e+05 (메모리: 1575.2 MB)
[RGLS]   [ETS] 시작  (메모리: 1575.2 MB)
[메모리] forecast_ets 실행 전: 1575.21 MB
[메모리] forecast_ets 실행 후: 1575.21 MB (변화: +0.00 MB)
[RGLS]   [ETS] 완료  첫값=-1.19e+06 (메모리: 1575.2 MB)
[RGLS]   [Prophet] 시작  (메모리: 1575.2 MB)

11:39:38 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1575.21 MB

11:39:38 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1575.24 MB (변화: +0.02 MB)
[RGLS]   [Prophet] 완료  첫값=-3.44e+05 (메모리: 1575.2 MB)
[RGLS]   [LSTM] 시작  (메모리: 1575.2 MB)
[메모리] forecast_lstm 실행 전: 1575.24 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1574.84 MB (변화: -0.39 MB)
[RGLS]   [LSTM] 완료  첫값=6.31e+05 (메모리: 1574.8 MB)
[RGLS]   [Theta] 시작  (메모리: 1574.8 MB)
[메모리] forecast_theta 실행 전: 1574.84 MB
[메모리] forecast_theta 실행 후: 1574.84 MB (변화: +0.00 MB)
[RGLS]   [Theta] 완료  첫값=-2.52e+04 (메모리: 1574.8 MB)
[RGLS]   [DB] 88행 저장 완료
[PROGRESS] [ 288/500] ( 57.6%)  >>  ODV
[ODV] [SKIP] [ODV] 'sale' 관측치 부족: 26개 < 최소 28개
[PROGRESS] [ 289/500] ( 57.8%)  >>  BLMN
[BLMN]   40분기 | 2016-03-27 ~ 2025-12-28
[BLMN]   [SARIMA] 시작  (메모리: 1574.8 MB)
[메모리] forecast_sarima 실행 전: 1574.84 MB
[메모리] find_best_sarima_params 실행 전: 1574.84 MB
[메모리] find_best_sarima_params 실행 후: 1574.84 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1574.84 MB (변화: +0.00 MB)
[BLMN]   [SARIMA] 완료  첫값=9.96e+08 (메모리: 1574.8 MB)
[BLMN]   [ETS] 시작  (메모리: 1574.8 MB)
[메모리] forecast_ets 실행 전: 1574.84 MB
[메모리] forecast_ets 실행 후: 1574.85 MB (변화: +0.00 MB)
[BLMN]   [ETS] 완료  첫값=1.06e+09 (메모리: 1574.8 MB)
[BLMN]   [Prophet] 시작  (메모리: 1574.8 MB)

11:39:53 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1574.85 MB

11:39:53 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1574.88 MB (변화: +0.03 MB)
[BLMN]   [Prophet] 완료  첫값=1.01e+09 (메모리: 1574.9 MB)
[BLMN]   [LSTM] 시작  (메모리: 1574.9 MB)
[메모리] forecast_lstm 실행 전: 1574.88 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1575.15 MB (변화: +0.28 MB)
[BLMN]   [LSTM] 완료  첫값=1.02e+09 (메모리: 1575.2 MB)
[BLMN]   [Theta] 시작  (메모리: 1575.2 MB)
[메모리] forecast_theta 실행 전: 1575.15 MB
[메모리] forecast_theta 실행 후: 1575.15 MB (변화: +0.00 MB)
[BLMN]   [Theta] 완료  첫값=9.56e+08 (메모리: 1575.2 MB)
[BLMN]   [DB] 88행 저장 완료
[PROGRESS] [ 290/500] ( 58.0%)  >>  OXM
[OXM]   40분기 | 2016-04-30 ~ 2026-01-31
[OXM]   [SARIMA] 시작  (메모리: 1575.2 MB)
[메모리] forecast_sarima 실행 전: 1575.15 MB
[메모리] find_best_sarima_params 실행 전: 1575.15 MB
[메모리] find_best_sarima_params 실행 후: 1575.15 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1575.15 MB (변화: +0.00 MB)
[OXM]   [SARIMA] 완료  첫값=3.71e+08 (메모리: 1575.2 MB)
[OXM]   [ETS] 시작  (메모리: 1575.2 MB)
[메모리] forecast_ets 실행 전: 1575.15 MB
[메모리] forecast_ets 실행 후: 1575.16 MB (변화: +0.00 MB)
[OXM]   [ETS] 완료  첫값=3.63e+08 (메모리: 1575.2 MB)
[OXM]   [Prophet] 시작  (메모리: 1575.2 MB)

11:40:12 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1575.16 MB

11:40:12 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1575.20 MB (변화: +0.05 MB)
[OXM]   [Prophet] 완료  첫값=3.84e+08 (메모리: 1575.2 MB)
[OXM]   [LSTM] 시작  (메모리: 1575.2 MB)
[메모리] forecast_lstm 실행 전: 1575.20 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1576.20 MB (변화: +1.00 MB)
[OXM]   [LSTM] 완료  첫값=3.73e+08 (메모리: 1576.2 MB)
[OXM]   [Theta] 시작  (메모리: 1576.2 MB)
[메모리] forecast_theta 실행 전: 1576.20 MB
[메모리] forecast_theta 실행 후: 1576.20 MB (변화: +0.00 MB)
[OXM]   [Theta] 완료  첫값=3.62e+08 (메모리: 1576.2 MB)
[OXM]   [DB] 88행 저장 완료
[PROGRESS] [ 291/500] ( 58.2%)  >>  TWI
[TWI]   40분기 | 2016-03-31 ~ 2025-12-31
[TWI]   [SARIMA] 시작  (메모리: 1576.2 MB)
[메모리] forecast_sarima 실행 전: 1576.20 MB
[메모리] find_best_sarima_params 실행 전: 1576.20 MB
[메모리] find_best_sarima_params 실행 후: 1576.20 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1576.20 MB (변화: +0.00 MB)
[TWI]   [SARIMA] 완료  첫값=4.82e+08 (메모리: 1576.2 MB)
[TWI]   [ETS] 시작  (메모리: 1576.2 MB)
[메모리] forecast_ets 실행 전: 1576.20 MB
[메모리] forecast_ets 실행 후: 1576.20 MB (변화: +0.00 MB)
[TWI]   [ETS] 완료  첫값=4.79e+08 (메모리: 1576.2 MB)
[TWI]   [Prophet] 시작  (메모리: 1576.2 MB)

11:40:29 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1576.20 MB

11:40:29 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1576.23 MB (변화: +0.02 MB)
[TWI]   [Prophet] 완료  첫값=4.97e+08 (메모리: 1576.2 MB)
[TWI]   [LSTM] 시작  (메모리: 1576.2 MB)
[메모리] forecast_lstm 실행 전: 1576.23 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1576.18 MB (변화: -0.05 MB)
[TWI]   [LSTM] 완료  첫값=4.37e+08 (메모리: 1576.2 MB)
[TWI]   [Theta] 시작  (메모리: 1576.2 MB)
[메모리] forecast_theta 실행 전: 1576.18 MB
[메모리] forecast_theta 실행 후: 1576.18 MB (변화: +0.00 MB)
[TWI]   [Theta] 완료  첫값=4.77e+08 (메모리: 1576.2 MB)
[TWI]   [DB] 88행 저장 완료
[PROGRESS] [ 292/500] ( 58.4%)  >>  BXC
[BXC]   40분기 | 2016-04-02 ~ 2026-01-03
[BXC]   [SARIMA] 시작  (메모리: 1576.2 MB)
[메모리] forecast_sarima 실행 전: 1576.18 MB
[메모리] find_best_sarima_params 실행 전: 1576.18 MB
[메모리] find_best_sarima_params 실행 후: 1576.18 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1576.18 MB (변화: +0.00 MB)
[BXC]   [SARIMA] 완료  첫값=7.54e+08 (메모리: 1576.2 MB)
[BXC]   [ETS] 시작  (메모리: 1576.2 MB)
[메모리] forecast_ets 실행 전: 1576.18 MB
[메모리] forecast_ets 실행 후: 1576.18 MB (변화: +0.00 MB)
[BXC]   [ETS] 완료  첫값=7.54e+08 (메모리: 1576.2 MB)
[BXC]   [Prophet] 시작  (메모리: 1576.2 MB)

11:40:48 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1576.18 MB

11:40:48 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1576.20 MB (변화: +0.02 MB)
[BXC]   [Prophet] 완료  첫값=9.40e+08 (메모리: 1576.2 MB)
[BXC]   [LSTM] 시작  (메모리: 1576.2 MB)
[메모리] forecast_lstm 실행 전: 1576.20 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1575.69 MB (변화: -0.52 MB)
[BXC]   [LSTM] 완료  첫값=8.21e+08 (메모리: 1575.7 MB)
[BXC]   [Theta] 시작  (메모리: 1575.7 MB)
[메모리] forecast_theta 실행 전: 1575.69 MB
[메모리] forecast_theta 실행 후: 1575.69 MB (변화: +0.00 MB)
[BXC]   [Theta] 완료  첫값=7.50e+08 (메모리: 1575.7 MB)
[BXC]   [DB] 88행 저장 완료
[PROGRESS] [ 293/500] ( 58.6%)  >>  STKL
[STKL] [NEG-SKIP] [STKL] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2020, 12, 31)])
[PROGRESS] [ 294/500] ( 58.8%)  >>  CPS
[CPS]   40분기 | 2016-03-31 ~ 2025-12-31
[CPS]   [SARIMA] 시작  (메모리: 1575.7 MB)
[메모리] forecast_sarima 실행 전: 1575.69 MB
[메모리] find_best_sarima_params 실행 전: 1575.69 MB
[메모리] find_best_sarima_params 실행 후: 1575.69 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1575.69 MB (변화: +0.00 MB)
[CPS]   [SARIMA] 완료  첫값=6.71e+08 (메모리: 1575.7 MB)
[CPS]   [ETS] 시작  (메모리: 1575.7 MB)
[메모리] forecast_ets 실행 전: 1575.69 MB
[메모리] forecast_ets 실행 후: 1575.69 MB (변화: +0.00 MB)
[CPS]   [ETS] 완료  첫값=6.86e+08 (메모리: 1575.7 MB)
[CPS]   [Prophet] 시작  (메모리: 1575.7 MB)

11:41:08 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1575.69 MB

11:41:08 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1575.71 MB (변화: +0.02 MB)
[CPS]   [Prophet] 완료  첫값=5.90e+08 (메모리: 1575.7 MB)
[CPS]   [LSTM] 시작  (메모리: 1575.7 MB)
[메모리] forecast_lstm 실행 전: 1575.71 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1575.56 MB (변화: -0.16 MB)
[CPS]   [LSTM] 완료  첫값=6.13e+08 (메모리: 1575.6 MB)
[CPS]   [Theta] 시작  (메모리: 1575.6 MB)
[메모리] forecast_theta 실행 전: 1575.56 MB
[메모리] forecast_theta 실행 후: 1575.56 MB (변화: +0.00 MB)
[CPS]   [Theta] 완료  첫값=6.92e+08 (메모리: 1575.6 MB)
[CPS]   [DB] 88행 저장 완료
[PROGRESS] [ 295/500] ( 59.0%)  >>  AMOT
[AMOT]   40분기 | 2015-09-30 ~ 2025-12-31
[AMOT]   [SARIMA] 시작  (메모리: 1575.6 MB)
[메모리] forecast_sarima 실행 전: 1575.56 MB
[메모리] find_best_sarima_params 실행 전: 1575.56 MB
[메모리] find_best_sarima_params 실행 후: 1575.56 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1575.56 MB (변화: +0.00 MB)
[AMOT]   [SARIMA] 완료  첫값=1.47e+08 (메모리: 1575.6 MB)
[AMOT]   [ETS] 시작  (메모리: 1575.6 MB)
[메모리] forecast_ets 실행 전: 1575.56 MB
[메모리] forecast_ets 실행 후: 1575.57 MB (변화: +0.01 MB)
[AMOT]   [ETS] 완료  첫값=1.63e+08 (메모리: 1575.6 MB)
[AMOT]   [Prophet] 시작  (메모리: 1575.6 MB)

11:41:24 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1575.57 MB

11:41:25 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1575.59 MB (변화: +0.02 MB)
[AMOT]   [Prophet] 완료  첫값=1.46e+08 (메모리: 1575.6 MB)
[AMOT]   [LSTM] 시작  (메모리: 1575.6 MB)
[메모리] forecast_lstm 실행 전: 1575.59 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1575.40 MB (변화: -0.18 MB)
[AMOT]   [LSTM] 완료  첫값=1.40e+08 (메모리: 1575.4 MB)
[AMOT]   [Theta] 시작  (메모리: 1575.4 MB)
[메모리] forecast_theta 실행 전: 1575.40 MB
[메모리] forecast_theta 실행 후: 1575.40 MB (변화: +0.00 MB)
[AMOT]   [Theta] 완료  첫값=1.51e+08 (메모리: 1575.4 MB)
[AMOT]   [DB] 88행 저장 완료
[PROGRESS] [ 296/500] ( 59.2%)  >>  AHH
[AHH]   40분기 | 2016-03-31 ~ 2025-12-31
[AHH]   [SARIMA] 시작  (메모리: 1575.4 MB)
[메모리] forecast_sarima 실행 전: 1575.40 MB
[메모리] find_best_sarima_params 실행 전: 1575.40 MB
[메모리] find_best_sarima_params 실행 후: 1575.40 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1575.40 MB (변화: +0.00 MB)
[AHH]   [SARIMA] 완료  첫값=6.52e+07 (메모리: 1575.4 MB)
[AHH]   [ETS] 시작  (메모리: 1575.4 MB)
[메모리] forecast_ets 실행 전: 1575.40 MB
[메모리] forecast_ets 실행 후: 1575.40 MB (변화: +0.00 MB)
[AHH]   [ETS] 완료  첫값=5.97e+07 (메모리: 1575.4 MB)
[AHH]   [Prophet] 시작  (메모리: 1575.4 MB)

11:41:40 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1575.40 MB

11:41:40 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1575.79 MB (변화: +0.38 MB)
[AHH]   [Prophet] 완료  첫값=1.51e+08 (메모리: 1575.8 MB)
[AHH]   [LSTM] 시작  (메모리: 1575.8 MB)
[메모리] forecast_lstm 실행 전: 1575.79 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1575.40 MB (변화: -0.38 MB)
[AHH]   [LSTM] 완료  첫값=1.19e+08 (메모리: 1575.4 MB)
[AHH]   [Theta] 시작  (메모리: 1575.4 MB)
[메모리] forecast_theta 실행 전: 1575.40 MB
[메모리] forecast_theta 실행 후: 1575.40 MB (변화: +0.00 MB)
[AHH]   [Theta] 완료  첫값=7.50e+07 (메모리: 1575.4 MB)
[AHH]   [DB] 88행 저장 완료
[PROGRESS] [ 297/500] ( 59.4%)  >>  CNSL
[CNSL]   40분기 | 2014-12-31 ~ 2024-09-30
[CNSL]   [SARIMA] 시작  (메모리: 1575.4 MB)
[메모리] forecast_sarima 실행 전: 1575.40 MB
[메모리] find_best_sarima_params 실행 전: 1575.40 MB
[메모리] find_best_sarima_params 실행 후: 1575.40 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1575.40 MB (변화: +0.00 MB)
[CNSL]   [SARIMA] 완료  첫값=2.66e+08 (메모리: 1575.4 MB)
[CNSL]   [ETS] 시작  (메모리: 1575.4 MB)
[메모리] forecast_ets 실행 전: 1575.40 MB
[메모리] forecast_ets 실행 후: 1575.41 MB (변화: +0.00 MB)
[CNSL]   [ETS] 완료  첫값=2.66e+08 (메모리: 1575.4 MB)
[CNSL]   [Prophet] 시작  (메모리: 1575.4 MB)

11:42:00 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1575.41 MB

11:42:00 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1576.15 MB (변화: +0.74 MB)
[CNSL]   [Prophet] 완료  첫값=3.33e+08 (메모리: 1576.1 MB)
[CNSL]   [LSTM] 시작  (메모리: 1576.1 MB)
[메모리] forecast_lstm 실행 전: 1576.15 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1576.74 MB (변화: +0.59 MB)
[CNSL]   [LSTM] 완료  첫값=2.88e+08 (메모리: 1576.7 MB)
[CNSL]   [Theta] 시작  (메모리: 1576.7 MB)
[메모리] forecast_theta 실행 전: 1576.74 MB
[메모리] forecast_theta 실행 후: 1576.74 MB (변화: +0.00 MB)
[CNSL]   [Theta] 완료  첫값=2.65e+08 (메모리: 1576.7 MB)
[CNSL]   [DB] 88행 저장 완료
[PROGRESS] [ 298/500] ( 59.6%)  >>  GOOD
[GOOD]   40분기 | 2016-03-31 ~ 2025-12-31
[GOOD]   [SARIMA] 시작  (메모리: 1576.7 MB)
[메모리] forecast_sarima 실행 전: 1576.74 MB
[메모리] find_best_sarima_params 실행 전: 1576.74 MB
[메모리] find_best_sarima_params 실행 후: 1576.74 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1576.74 MB (변화: +0.00 MB)
[GOOD]   [SARIMA] 완료  첫값=4.43e+07 (메모리: 1576.7 MB)
[GOOD]   [ETS] 시작  (메모리: 1576.7 MB)
[메모리] forecast_ets 실행 전: 1576.74 MB
[메모리] forecast_ets 실행 후: 1576.75 MB (변화: +0.01 MB)
[GOOD]   [ETS] 완료  첫값=4.47e+07 (메모리: 1576.7 MB)
[GOOD]   [Prophet] 시작  (메모리: 1576.7 MB)

11:42:21 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1576.75 MB

11:42:21 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1577.12 MB (변화: +0.38 MB)
[GOOD]   [Prophet] 완료  첫값=4.10e+07 (메모리: 1577.1 MB)
[GOOD]   [LSTM] 시작  (메모리: 1577.1 MB)
[메모리] forecast_lstm 실행 전: 1577.12 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1576.74 MB (변화: -0.38 MB)
[GOOD]   [LSTM] 완료  첫값=3.85e+07 (메모리: 1576.7 MB)
[GOOD]   [Theta] 시작  (메모리: 1576.7 MB)
[메모리] forecast_theta 실행 전: 1576.74 MB
[메모리] forecast_theta 실행 후: 1576.74 MB (변화: +0.00 MB)
[GOOD]   [Theta] 완료  첫값=4.44e+07 (메모리: 1576.7 MB)
[GOOD]   [DB] 88행 저장 완료
[PROGRESS] [ 299/500] ( 59.8%)  >>  DBVT
[DBVT] [NEG-SKIP] [DBVT] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2020, 12, 31), datetime.date(2022, 12, 31)])
[PROGRESS] [ 300/500] ( 60.0%)  >>  LLNW
[LLNW]   40분기 | 2012-09-30 ~ 2022-06-30
[LLNW]   [SARIMA] 시작  (메모리: 1576.7 MB)
[메모리] forecast_sarima 실행 전: 1576.74 MB
[메모리] find_best_sarima_params 실행 전: 1576.74 MB
[메모리] find_best_sarima_params 실행 후: 1576.74 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1576.74 MB (변화: +0.00 MB)
[LLNW]   [SARIMA] 완료  첫값=7.53e+07 (메모리: 1576.7 MB)
[LLNW]   [ETS] 시작  (메모리: 1576.7 MB)
[메모리] forecast_ets 실행 전: 1576.74 MB
[메모리] forecast_ets 실행 후: 1576.75 MB (변화: +0.01 MB)
[LLNW]   [ETS] 완료  첫값=7.47e+07 (메모리: 1576.7 MB)
[LLNW]   [Prophet] 시작  (메모리: 1576.7 MB)
[메모리] forecast_prophet 실행 전: 1576.75 MB

11:42:39 - cmdstanpy - INFO - Chain [1] start processing
11:42:39 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1576.40 MB (변화: -0.34 MB)
[LLNW]   [Prophet] 완료  첫값=6.02e+07 (메모리: 1576.4 MB)
[LLNW]   [LSTM] 시작  (메모리: 1576.4 MB)
[메모리] forecast_lstm 실행 전: 1576.40 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1577.39 MB (변화: +0.98 MB)
[LLNW]   [LSTM] 완료  첫값=7.06e+07 (메모리: 1577.4 MB)
[LLNW]   [Theta] 시작  (메모리: 1577.4 MB)
[메모리] forecast_theta 실행 전: 1577.39 MB
[메모리] forecast_theta 실행 후: 1577.39 MB (변화: +0.00 MB)
[LLNW]   [Theta] 완료  첫값=7.40e+07 (메모리: 1577.4 MB)
[LLNW]   [DB] 88행 저장 완료
[PROGRESS] [ 301/500] ( 60.2%)  >>  SAGE
[SAGE]   40분기 | 2015-09-30 ~ 2025-06-30
[SAGE]   [SARIMA] 시작  (메모리: 1577.4 MB)
[메모리] forecast_sarima 실행 전: 1577.39 MB
[메모리] find_best_sarima_params 실행 전: 1577.39 MB
[메모리] find_best_sarima_params 실행 후: 1577.39 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1577.39 MB (변화: +0.00 MB)
[SAGE]   [SARIMA] 완료  첫값=1.23e+07 (메모리: 1577.4 MB)
[SAGE]   [ETS] 시작  (메모리: 1577.4 MB)
[메모리] forecast_ets 실행 전: 1577.39 MB
[메모리] forecast_ets 실행 후: 1577.39 MB (변화: +0.00 MB)
[SAGE]   [ETS] 완료  첫값=8.82e+07 (메모리: 1577.4 MB)
[SAGE]   [Prophet] 시작  (메모리: 1577.4 MB)

11:42:56 - cmdstanpy - INFO - Chain [1] start processing
11:42:56 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1577.39 MB
[메모리] forecast_prophet 실행 후: 1577.43 MB (변화: +0.04 MB)
[SAGE]   [Prophet] 완료  첫값=4.88e+07 (메모리: 1577.4 MB)
[SAGE]   [LSTM] 시작  (메모리: 1577.4 MB)
[메모리] forecast_lstm 실행 전: 1577.43 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1577.37 MB (변화: -0.06 MB)
[SAGE]   [LSTM] 완료  첫값=7.31e+07 (메모리: 1577.4 MB)
[SAGE]   [Theta] 시작  (메모리: 1577.4 MB)
[메모리] forecast_theta 실행 전: 1577.37 MB
[메모리] forecast_theta 실행 후: 1577.37 MB (변화: +0.00 MB)
[SAGE]   [Theta] 완료  첫값=2.54e+07 (메모리: 1577.4 MB)
[SAGE]   [DB] 88행 저장 완료
[PROGRESS] [ 302/500] ( 60.4%)  >>  SB
[SB]   40분기 | 2016-03-31 ~ 2025-12-31
[SB]   [SARIMA] 시작  (메모리: 1577.4 MB)
[메모리] forecast_sarima 실행 전: 1577.37 MB
[메모리] find_best_sarima_params 실행 전: 1577.37 MB
[메모리] find_best_sarima_params 실행 후: 1577.37 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1577.37 MB (변화: +0.00 MB)
[SB]   [SARIMA] 완료  첫값=7.46e+07 (메모리: 1577.4 MB)
[SB]   [ETS] 시작  (메모리: 1577.4 MB)
[메모리] forecast_ets 실행 전: 1577.37 MB
[메모리] forecast_ets 실행 후: 1577.38 MB (변화: +0.00 MB)
[SB]   [ETS] 완료  첫값=6.84e+07 (메모리: 1577.4 MB)
[SB]   [Prophet] 시작  (메모리: 1577.4 MB)

11:43:14 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1577.38 MB

11:43:14 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1577.51 MB (변화: +0.14 MB)
[SB]   [Prophet] 완료  첫값=8.85e+07 (메모리: 1577.5 MB)
[SB]   [LSTM] 시작  (메모리: 1577.5 MB)
[메모리] forecast_lstm 실행 전: 1577.51 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1578.96 MB (변화: +1.45 MB)
[SB]   [LSTM] 완료  첫값=7.21e+07 (메모리: 1579.0 MB)
[SB]   [Theta] 시작  (메모리: 1579.0 MB)
[메모리] forecast_theta 실행 전: 1578.96 MB
[메모리] forecast_theta 실행 후: 1578.96 MB (변화: +0.00 MB)
[SB]   [Theta] 완료  첫값=6.75e+07 (메모리: 1579.0 MB)
[SB]   [DB] 88행 저장 완료
[PROGRESS] [ 303/500] ( 60.6%)  >>  CLMB
[CLMB]   40분기 | 2016-03-31 ~ 2025-12-31
[CLMB]   [SARIMA] 시작  (메모리: 1579.0 MB)
[메모리] forecast_sarima 실행 전: 1578.96 MB
[메모리] find_best_sarima_params 실행 전: 1578.96 MB
[메모리] find_best_sarima_params 실행 후: 1578.96 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1578.96 MB (변화: +0.00 MB)
[CLMB]   [SARIMA] 완료  첫값=1.58e+08 (메모리: 1579.0 MB)
[CLMB]   [ETS] 시작  (메모리: 1579.0 MB)
[메모리] forecast_ets 실행 전: 1578.96 MB
[메모리] forecast_ets 실행 후: 1578.97 MB (변화: +0.00 MB)
[CLMB]   [ETS] 완료  첫값=1.58e+08 (메모리: 1579.0 MB)
[CLMB]   [Prophet] 시작  (메모리: 1579.0 MB)

11:43:29 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1578.97 MB

11:43:29 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1579.00 MB (변화: +0.03 MB)
[CLMB]   [Prophet] 완료  첫값=1.17e+08 (메모리: 1579.0 MB)
[CLMB]   [LSTM] 시작  (메모리: 1579.0 MB)
[메모리] forecast_lstm 실행 전: 1579.00 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1578.51 MB (변화: -0.49 MB)
[CLMB]   [LSTM] 완료  첫값=2.38e+08 (메모리: 1578.5 MB)
[CLMB]   [Theta] 시작  (메모리: 1578.5 MB)
[메모리] forecast_theta 실행 전: 1578.51 MB
[메모리] forecast_theta 실행 후: 1578.51 MB (변화: +0.00 MB)
[CLMB]   [Theta] 완료  첫값=1.56e+08 (메모리: 1578.5 MB)
[CLMB]   [DB] 88행 저장 완료
[PROGRESS] [ 304/500] ( 60.8%)  >>  MYGN
[MYGN]   40분기 | 2016-03-31 ~ 2025-12-31
[MYGN]   [SARIMA] 시작  (메모리: 1578.5 MB)
[메모리] forecast_sarima 실행 전: 1578.51 MB
[메모리] find_best_sarima_params 실행 전: 1578.51 MB
[메모리] find_best_sarima_params 실행 후: 1578.51 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1578.51 MB (변화: +0.00 MB)
[MYGN]   [SARIMA] 완료  첫값=2.18e+08 (메모리: 1578.5 MB)
[MYGN]   [ETS] 시작  (메모리: 1578.5 MB)
[메모리] forecast_ets 실행 전: 1578.51 MB
[메모리] forecast_ets 실행 후: 1578.52 MB (변화: +0.01 MB)
[MYGN]   [ETS] 완료  첫값=2.18e+08 (메모리: 1578.5 MB)
[MYGN]   [Prophet] 시작  (메모리: 1578.5 MB)

11:43:44 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1578.52 MB

11:43:45 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1578.52 MB (변화: +0.01 MB)
[MYGN]   [Prophet] 완료  첫값=1.88e+08 (메모리: 1578.5 MB)
[MYGN]   [LSTM] 시작  (메모리: 1578.5 MB)
[메모리] forecast_lstm 실행 전: 1578.52 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1578.38 MB (변화: -0.14 MB)
[MYGN]   [LSTM] 완료  첫값=1.78e+08 (메모리: 1578.4 MB)
[MYGN]   [Theta] 시작  (메모리: 1578.4 MB)
[메모리] forecast_theta 실행 전: 1578.38 MB
[메모리] forecast_theta 실행 후: 1578.38 MB (변화: +0.00 MB)
[MYGN]   [Theta] 완료  첫값=2.08e+08 (메모리: 1578.4 MB)
[MYGN]   [DB] 88행 저장 완료
[PROGRESS] [ 305/500] ( 61.0%)  >>  TNP
[TNP]   40분기 | 2015-09-30 ~ 2025-06-30
[TNP]   [SARIMA] 시작  (메모리: 1578.4 MB)
[메모리] forecast_sarima 실행 전: 1578.38 MB
[메모리] find_best_sarima_params 실행 전: 1578.38 MB
[메모리] find_best_sarima_params 실행 후: 1578.38 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1578.38 MB (변화: +0.00 MB)
[TNP]   [SARIMA] 완료  첫값=1.95e+08 (메모리: 1578.4 MB)
[TNP]   [ETS] 시작  (메모리: 1578.4 MB)
[메모리] forecast_ets 실행 전: 1578.38 MB
[메모리] forecast_ets 실행 후: 1578.38 MB (변화: +0.00 MB)
[TNP]   [ETS] 완료  첫값=1.78e+08 (메모리: 1578.4 MB)
[TNP]   [Prophet] 시작  (메모리: 1578.4 MB)

11:44:00 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1578.38 MB

11:44:00 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1578.42 MB (변화: +0.04 MB)
[TNP]   [Prophet] 완료  첫값=2.17e+08 (메모리: 1578.4 MB)
[TNP]   [LSTM] 시작  (메모리: 1578.4 MB)
[메모리] forecast_lstm 실행 전: 1578.42 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1578.37 MB (변화: -0.05 MB)
[TNP]   [LSTM] 완료  첫값=2.10e+08 (메모리: 1578.4 MB)
[TNP]   [Theta] 시작  (메모리: 1578.4 MB)
[메모리] forecast_theta 실행 전: 1578.37 MB
[메모리] forecast_theta 실행 후: 1578.37 MB (변화: +0.00 MB)
[TNP]   [Theta] 완료  첫값=1.77e+08 (메모리: 1578.4 MB)
[TNP]   [DB] 88행 저장 완료
[PROGRESS] [ 306/500] ( 61.2%)  >>  UHT
[UHT]   40분기 | 2016-03-31 ~ 2025-12-31
[UHT]   [SARIMA] 시작  (메모리: 1578.4 MB)
[메모리] forecast_sarima 실행 전: 1578.37 MB
[메모리] find_best_sarima_params 실행 전: 1578.37 MB
[메모리] find_best_sarima_params 실행 후: 1578.37 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1578.37 MB (변화: +0.00 MB)
[UHT]   [SARIMA] 완료  첫값=7.71e+07 (메모리: 1578.4 MB)
[UHT]   [ETS] 시작  (메모리: 1578.4 MB)
[메모리] forecast_ets 실행 전: 1578.37 MB
[메모리] forecast_ets 실행 후: 1578.37 MB (변화: +0.00 MB)
[UHT]   [ETS] 완료  첫값=2.85e+07 (메모리: 1578.4 MB)
[UHT]   [Prophet] 시작  (메모리: 1578.4 MB)

11:44:17 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1578.37 MB

11:44:17 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1578.38 MB (변화: +0.01 MB)
[UHT]   [Prophet] 완료  첫값=3.08e+07 (메모리: 1578.4 MB)
[UHT]   [LSTM] 시작  (메모리: 1578.4 MB)
[메모리] forecast_lstm 실행 전: 1578.38 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1578.93 MB (변화: +0.55 MB)
[UHT]   [LSTM] 완료  첫값=4.00e+07 (메모리: 1578.9 MB)
[UHT]   [Theta] 시작  (메모리: 1578.9 MB)
[메모리] forecast_theta 실행 전: 1578.93 MB
[메모리] forecast_theta 실행 후: 1578.93 MB (변화: +0.00 MB)
[UHT]   [Theta] 완료  첫값=7.45e+07 (메모리: 1578.9 MB)
[UHT]   [DB] 88행 저장 완료
[PROGRESS] [ 307/500] ( 61.4%)  >>  NUS
[NUS]   40분기 | 2016-03-31 ~ 2025-12-31
[NUS]   [SARIMA] 시작  (메모리: 1578.9 MB)
[메모리] forecast_sarima 실행 전: 1578.93 MB
[메모리] find_best_sarima_params 실행 전: 1578.93 MB
[메모리] find_best_sarima_params 실행 후: 1578.93 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1578.93 MB (변화: +0.00 MB)
[NUS]   [SARIMA] 완료  첫값=3.51e+08 (메모리: 1578.9 MB)
[NUS]   [ETS] 시작  (메모리: 1578.9 MB)
[메모리] forecast_ets 실행 전: 1578.93 MB
[메모리] forecast_ets 실행 후: 1578.93 MB (변화: +0.00 MB)
[NUS]   [ETS] 완료  첫값=3.26e+08 (메모리: 1578.9 MB)
[NUS]   [Prophet] 시작  (메모리: 1578.9 MB)

11:44:37 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1578.93 MB

11:44:37 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1579.26 MB (변화: +0.32 MB)
[NUS]   [Prophet] 완료  첫값=4.49e+08 (메모리: 1579.3 MB)
[NUS]   [LSTM] 시작  (메모리: 1579.3 MB)
[메모리] forecast_lstm 실행 전: 1579.26 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1580.47 MB (변화: +1.21 MB)
[NUS]   [LSTM] 완료  첫값=4.34e+08 (메모리: 1580.5 MB)
[NUS]   [Theta] 시작  (메모리: 1580.5 MB)
[메모리] forecast_theta 실행 전: 1580.47 MB
[메모리] forecast_theta 실행 후: 1580.47 MB (변화: +0.00 MB)
[NUS]   [Theta] 완료  첫값=3.35e+08 (메모리: 1580.5 MB)
[NUS]   [DB] 88행 저장 완료
[PROGRESS] [ 308/500] ( 61.6%)  >>  ZEUS
[ZEUS]   40분기 | 2015-12-31 ~ 2025-09-30
[ZEUS]   [SARIMA] 시작  (메모리: 1580.5 MB)
[메모리] forecast_sarima 실행 전: 1580.47 MB
[메모리] find_best_sarima_params 실행 전: 1580.47 MB
[메모리] find_best_sarima_params 실행 후: 1580.47 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1580.47 MB (변화: +0.00 MB)
[ZEUS]   [SARIMA] 완료  첫값=5.10e+08 (메모리: 1580.5 MB)
[ZEUS]   [ETS] 시작  (메모리: 1580.5 MB)
[메모리] forecast_ets 실행 전: 1580.47 MB
[메모리] forecast_ets 실행 후: 1580.47 MB (변화: +0.00 MB)
[ZEUS]   [ETS] 완료  첫값=4.53e+08 (메모리: 1580.5 MB)
[ZEUS]   [Prophet] 시작  (메모리: 1580.5 MB)

11:44:53 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1580.47 MB

11:44:53 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1580.85 MB (변화: +0.38 MB)
[ZEUS]   [Prophet] 완료  첫값=5.94e+08 (메모리: 1580.8 MB)
[ZEUS]   [LSTM] 시작  (메모리: 1580.8 MB)
[메모리] forecast_lstm 실행 전: 1580.85 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1580.46 MB (변화: -0.38 MB)
[ZEUS]   [LSTM] 완료  첫값=4.84e+08 (메모리: 1580.5 MB)
[ZEUS]   [Theta] 시작  (메모리: 1580.5 MB)
[메모리] forecast_theta 실행 전: 1580.46 MB
[메모리] forecast_theta 실행 후: 1580.46 MB (변화: +0.00 MB)
[ZEUS]   [Theta] 완료  첫값=4.49e+08 (메모리: 1580.5 MB)
[ZEUS]   [DB] 88행 저장 완료
[PROGRESS] [ 309/500] ( 61.8%)  >>  PRTA
[PRTA]   40분기 | 2016-03-31 ~ 2025-12-31
[PRTA]   [SARIMA] 시작  (메모리: 1580.5 MB)
[메모리] forecast_sarima 실행 전: 1580.46 MB
[메모리] find_best_sarima_params 실행 전: 1580.46 MB
[메모리] find_best_sarima_params 실행 후: 1580.46 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1580.46 MB (변화: +0.00 MB)
[PRTA]   [SARIMA] 완료  첫값=1.19e+05 (메모리: 1580.5 MB)
[PRTA]   [ETS] 시작  (메모리: 1580.5 MB)
[메모리] forecast_ets 실행 전: 1580.46 MB
[메모리] forecast_ets 실행 후: 1580.47 MB (변화: +0.00 MB)
[PRTA]   [ETS] 완료  첫값=1.47e+06 (메모리: 1580.5 MB)
[PRTA]   [Prophet] 시작  (메모리: 1580.5 MB)

11:45:10 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1580.47 MB

11:45:10 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1580.13 MB (변화: -0.34 MB)
[PRTA]   [Prophet] 완료  첫값=2.60e+07 (메모리: 1580.1 MB)
[PRTA]   [LSTM] 시작  (메모리: 1580.1 MB)
[메모리] forecast_lstm 실행 전: 1580.13 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1580.01 MB (변화: -0.12 MB)
[PRTA]   [LSTM] 완료  첫값=1.80e+07 (메모리: 1580.0 MB)
[PRTA]   [Theta] 시작  (메모리: 1580.0 MB)
[메모리] forecast_theta 실행 전: 1580.01 MB
[메모리] forecast_theta 실행 후: 1580.01 MB (변화: +0.00 MB)
[PRTA]   [Theta] 완료  첫값=1.51e+06 (메모리: 1580.0 MB)
[PRTA]   [DB] 88행 저장 완료
[PROGRESS] [ 310/500] ( 62.0%)  >>  MGPI
[MGPI]   40분기 | 2016-03-31 ~ 2025-12-31
[MGPI]   [SARIMA] 시작  (메모리: 1580.0 MB)
[메모리] forecast_sarima 실행 전: 1580.01 MB
[메모리] find_best_sarima_params 실행 전: 1580.01 MB
[메모리] find_best_sarima_params 실행 후: 1580.01 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1580.01 MB (변화: +0.00 MB)
[MGPI]   [SARIMA] 완료  첫값=1.36e+08 (메모리: 1580.0 MB)
[MGPI]   [ETS] 시작  (메모리: 1580.0 MB)
[메모리] forecast_ets 실행 전: 1580.01 MB
[메모리] forecast_ets 실행 후: 1580.01 MB (변화: +0.00 MB)
[MGPI]   [ETS] 완료  첫값=1.32e+08 (메모리: 1580.0 MB)
[MGPI]   [Prophet] 시작  (메모리: 1580.0 MB)
[메모리] forecast_prophet 실행 전: 1580.01 MB

11:45:26 - cmdstanpy - INFO - Chain [1] start processing
11:45:26 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1580.03 MB (변화: +0.02 MB)
[MGPI]   [Prophet] 완료  첫값=1.96e+08 (메모리: 1580.0 MB)
[MGPI]   [LSTM] 시작  (메모리: 1580.0 MB)
[메모리] forecast_lstm 실행 전: 1580.03 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1580.99 MB (변화: +0.96 MB)
[MGPI]   [LSTM] 완료  첫값=1.59e+08 (메모리: 1581.0 MB)
[MGPI]   [Theta] 시작  (메모리: 1581.0 MB)
[메모리] forecast_theta 실행 전: 1580.99 MB
[메모리] forecast_theta 실행 후: 1580.99 MB (변화: +0.00 MB)
[MGPI]   [Theta] 완료  첫값=1.32e+08 (메모리: 1581.0 MB)
[MGPI]   [DB] 88행 저장 완료
[PROGRESS] [ 311/500] ( 62.2%)  >>  DRQ
[DRQ]   40분기 | 2016-03-31 ~ 2025-12-31
[DRQ]   [SARIMA] 시작  (메모리: 1581.0 MB)
[메모리] forecast_sarima 실행 전: 1580.99 MB
[메모리] find_best_sarima_params 실행 전: 1580.99 MB
[메모리] find_best_sarima_params 실행 후: 1580.99 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1580.99 MB (변화: +0.00 MB)
[DRQ]   [SARIMA] 완료  첫값=2.74e+08 (메모리: 1581.0 MB)
[DRQ]   [ETS] 시작  (메모리: 1581.0 MB)
[메모리] forecast_ets 실행 전: 1580.99 MB
[메모리] forecast_ets 실행 후: 1580.99 MB (변화: +0.00 MB)
[DRQ]   [ETS] 완료  첫값=2.68e+08 (메모리: 1581.0 MB)
[DRQ]   [Prophet] 시작  (메모리: 1581.0 MB)

11:45:41 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1580.99 MB

11:45:41 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1581.02 MB (변화: +0.03 MB)
[DRQ]   [Prophet] 완료  첫값=1.67e+08 (메모리: 1581.0 MB)
[DRQ]   [LSTM] 시작  (메모리: 1581.0 MB)
[메모리] forecast_lstm 실행 전: 1581.02 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1579.95 MB (변화: -1.07 MB)
[DRQ]   [LSTM] 완료  첫값=3.45e+08 (메모리: 1580.0 MB)
[DRQ]   [Theta] 시작  (메모리: 1580.0 MB)
[메모리] forecast_theta 실행 전: 1579.95 MB
[메모리] forecast_theta 실행 후: 1579.95 MB (변화: +0.00 MB)
[DRQ]   [Theta] 완료  첫값=2.54e+08 (메모리: 1580.0 MB)
[DRQ]   [DB] 88행 저장 완료
[PROGRESS] [ 312/500] ( 62.4%)  >>  HCKT
[HCKT]   40분기 | 2016-04-01 ~ 2025-12-26
[HCKT]   [SARIMA] 시작  (메모리: 1580.0 MB)
[메모리] forecast_sarima 실행 전: 1579.95 MB
[메모리] find_best_sarima_params 실행 전: 1579.95 MB
[메모리] find_best_sarima_params 실행 후: 1579.95 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1579.95 MB (변화: +0.00 MB)
[HCKT]   [SARIMA] 완료  첫값=7.67e+07 (메모리: 1580.0 MB)
[HCKT]   [ETS] 시작  (메모리: 1580.0 MB)
[메모리] forecast_ets 실행 전: 1579.95 MB
[메모리] forecast_ets 실행 후: 1579.96 MB (변화: +0.00 MB)
[HCKT]   [ETS] 완료  첫값=7.80e+07 (메모리: 1580.0 MB)
[HCKT]   [Prophet] 시작  (메모리: 1580.0 MB)

11:46:01 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1579.96 MB

11:46:01 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1580.21 MB (변화: +0.26 MB)
[HCKT]   [Prophet] 완료  첫값=7.74e+07 (메모리: 1580.2 MB)
[HCKT]   [LSTM] 시작  (메모리: 1580.2 MB)
[메모리] forecast_lstm 실행 전: 1580.21 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1580.33 MB (변화: +0.12 MB)
[HCKT]   [LSTM] 완료  첫값=7.56e+07 (메모리: 1580.3 MB)
[HCKT]   [Theta] 시작  (메모리: 1580.3 MB)
[메모리] forecast_theta 실행 전: 1580.33 MB
[메모리] forecast_theta 실행 후: 1580.33 MB (변화: +0.00 MB)
[HCKT]   [Theta] 완료  첫값=7.61e+07 (메모리: 1580.3 MB)
[HCKT]   [DB] 88행 저장 완료
[PROGRESS] [ 313/500] ( 62.6%)  >>  SCVL
[SCVL]   40분기 | 2016-04-30 ~ 2026-01-31
[SCVL]   [SARIMA] 시작  (메모리: 1580.3 MB)
[메모리] forecast_sarima 실행 전: 1580.33 MB
[메모리] find_best_sarima_params 실행 전: 1580.33 MB
[메모리] find_best_sarima_params 실행 후: 1580.33 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1580.33 MB (변화: +0.00 MB)
[SCVL]   [SARIMA] 완료  첫값=2.83e+08 (메모리: 1580.3 MB)
[SCVL]   [ETS] 시작  (메모리: 1580.3 MB)
[메모리] forecast_ets 실행 전: 1580.33 MB
[메모리] forecast_ets 실행 후: 1580.34 MB (변화: +0.00 MB)
[SCVL]   [ETS] 완료  첫값=2.99e+08 (메모리: 1580.3 MB)
[SCVL]   [Prophet] 시작  (메모리: 1580.3 MB)

11:46:16 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1580.34 MB

11:46:16 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1581.08 MB (변화: +0.75 MB)
[SCVL]   [Prophet] 완료  첫값=3.11e+08 (메모리: 1581.1 MB)
[SCVL]   [LSTM] 시작  (메모리: 1581.1 MB)
[메모리] forecast_lstm 실행 전: 1581.08 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1581.19 MB (변화: +0.11 MB)
[SCVL]   [LSTM] 완료  첫값=2.85e+08 (메모리: 1581.2 MB)
[SCVL]   [Theta] 시작  (메모리: 1581.2 MB)
[메모리] forecast_theta 실행 전: 1581.19 MB
[메모리] forecast_theta 실행 후: 1581.19 MB (변화: +0.00 MB)
[SCVL]   [Theta] 완료  첫값=2.66e+08 (메모리: 1581.2 MB)
[SCVL]   [DB] 88행 저장 완료
[PROGRESS] [ 314/500] ( 62.8%)  >>  SABR
[SABR]   40분기 | 2016-03-31 ~ 2025-12-31
[SABR]   [SARIMA] 시작  (메모리: 1581.2 MB)
[메모리] forecast_sarima 실행 전: 1581.19 MB
[메모리] find_best_sarima_params 실행 전: 1581.19 MB
[메모리] find_best_sarima_params 실행 후: 1581.19 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1581.19 MB (변화: +0.00 MB)
[SABR]   [SARIMA] 완료  첫값=6.82e+08 (메모리: 1581.2 MB)
[SABR]   [ETS] 시작  (메모리: 1581.2 MB)
[메모리] forecast_ets 실행 전: 1581.19 MB
[메모리] forecast_ets 실행 후: 1581.20 MB (변화: +0.00 MB)
[SABR]   [ETS] 완료  첫값=7.23e+08 (메모리: 1581.2 MB)
[SABR]   [Prophet] 시작  (메모리: 1581.2 MB)

11:46:30 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1581.20 MB

11:46:30 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1580.85 MB (변화: -0.34 MB)
[SABR]   [Prophet] 완료  첫값=5.86e+08 (메모리: 1580.9 MB)
[SABR]   [LSTM] 시작  (메모리: 1580.9 MB)
[메모리] forecast_lstm 실행 전: 1580.85 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1581.92 MB (변화: +1.07 MB)
[SABR]   [LSTM] 완료  첫값=6.58e+08 (메모리: 1581.9 MB)
[SABR]   [Theta] 시작  (메모리: 1580.7 MB)
[메모리] forecast_theta 실행 전: 1580.68 MB
[메모리] forecast_theta 실행 후: 1580.68 MB (변화: +0.00 MB)
[SABR]   [Theta] 완료  첫값=6.78e+08 (메모리: 1580.7 MB)
[SABR]   [DB] 88행 저장 완료
[PROGRESS] [ 315/500] ( 63.0%)  >>  OFIX
[OFIX]   40분기 | 2016-03-31 ~ 2025-12-31
[OFIX]   [SARIMA] 시작  (메모리: 1580.7 MB)
[메모리] forecast_sarima 실행 전: 1580.68 MB
[메모리] find_best_sarima_params 실행 전: 1580.68 MB
[메모리] find_best_sarima_params 실행 후: 1580.68 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1580.68 MB (변화: +0.00 MB)
[OFIX]   [SARIMA] 완료  첫값=2.21e+08 (메모리: 1580.7 MB)
[OFIX]   [ETS] 시작  (메모리: 1580.7 MB)
[메모리] forecast_ets 실행 전: 1580.68 MB
[메모리] forecast_ets 실행 후: 1580.68 MB (변화: +0.00 MB)
[OFIX]   [ETS] 완료  첫값=2.10e+08 (메모리: 1580.7 MB)
[OFIX]   [Prophet] 시작  (메모리: 1580.7 MB)

11:46:49 - cmdstanpy - INFO - Chain [1] start processing
11:46:49 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1580.68 MB
[메모리] forecast_prophet 실행 후: 1581.07 MB (변화: +0.38 MB)
[OFIX]   [Prophet] 완료  첫값=1.98e+08 (메모리: 1581.1 MB)
[OFIX]   [LSTM] 시작  (메모리: 1581.1 MB)
[메모리] forecast_lstm 실행 전: 1581.07 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1581.27 MB (변화: +0.21 MB)
[OFIX]   [LSTM] 완료  첫값=2.18e+08 (메모리: 1581.3 MB)
[OFIX]   [Theta] 시작  (메모리: 1581.3 MB)
[메모리] forecast_theta 실행 전: 1581.27 MB
[메모리] forecast_theta 실행 후: 1581.27 MB (변화: +0.00 MB)
[OFIX]   [Theta] 완료  첫값=2.07e+08 (메모리: 1581.3 MB)
[OFIX]   [DB] 88행 저장 완료
[PROGRESS] [ 316/500] ( 63.2%)  >>  OCGN
[OCGN] [NEG-SKIP] [OCGN] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2025, 12, 31)])
[PROGRESS] [ 317/500] ( 63.4%)  >>  FTK
[FTK]   40분기 | 2016-03-31 ~ 2025-12-31
[FTK]   [SARIMA] 시작  (메모리: 1581.3 MB)
[메모리] forecast_sarima 실행 전: 1581.27 MB
[메모리] find_best_sarima_params 실행 전: 1581.27 MB
[메모리] find_best_sarima_params 실행 후: 1581.27 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1581.27 MB (변화: +0.00 MB)
[FTK]   [SARIMA] 완료  첫값=6.75e+07 (메모리: 1581.3 MB)
[FTK]   [ETS] 시작  (메모리: 1581.3 MB)
[메모리] forecast_ets 실행 전: 1581.27 MB
[메모리] forecast_ets 실행 후: 1581.28 MB (변화: +0.00 MB)
[FTK]   [ETS] 완료  첫값=7.15e+07 (메모리: 1581.3 MB)
[FTK]   [Prophet] 시작  (메모리: 1581.3 MB)
[메모리] forecast_prophet 실행 전: 1581.28 MB

11:47:06 - cmdstanpy - INFO - Chain [1] start processing
11:47:06 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1581.31 MB (변화: +0.03 MB)
[FTK]   [Prophet] 완료  첫값=3.31e+07 (메모리: 1581.3 MB)
[FTK]   [LSTM] 시작  (메모리: 1581.3 MB)
[메모리] forecast_lstm 실행 전: 1581.31 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1582.33 MB (변화: +1.02 MB)
[FTK]   [LSTM] 완료  첫값=5.16e+07 (메모리: 1582.3 MB)
[FTK]   [Theta] 시작  (메모리: 1582.3 MB)
[메모리] forecast_theta 실행 전: 1582.33 MB
[메모리] forecast_theta 실행 후: 1582.33 MB (변화: +0.00 MB)
[FTK]   [Theta] 완료  첫값=6.77e+07 (메모리: 1582.3 MB)
[FTK]   [DB] 88행 저장 완료
[PROGRESS] [ 318/500] ( 63.6%)  >>  PBPB
[PBPB]   40분기 | 2015-09-27 ~ 2025-06-29
[PBPB]   [SARIMA] 시작  (메모리: 1582.3 MB)
[메모리] forecast_sarima 실행 전: 1582.33 MB
[메모리] find_best_sarima_params 실행 전: 1582.33 MB
[메모리] find_best_sarima_params 실행 후: 1582.33 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1582.33 MB (변화: +0.00 MB)
[PBPB]   [SARIMA] 완료  첫값=1.24e+08 (메모리: 1582.3 MB)
[PBPB]   [ETS] 시작  (메모리: 1582.3 MB)
[메모리] forecast_ets 실행 전: 1582.33 MB
[메모리] forecast_ets 실행 후: 1582.33 MB (변화: +0.00 MB)
[PBPB]   [ETS] 완료  첫값=1.25e+08 (메모리: 1582.3 MB)
[PBPB]   [Prophet] 시작  (메모리: 1582.3 MB)

11:47:25 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1582.33 MB

11:47:25 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1582.71 MB (변화: +0.38 MB)
[PBPB]   [Prophet] 완료  첫값=1.14e+08 (메모리: 1582.7 MB)
[PBPB]   [LSTM] 시작  (메모리: 1582.7 MB)
[메모리] forecast_lstm 실행 전: 1582.71 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1582.43 MB (변화: -0.28 MB)
[PBPB]   [LSTM] 완료  첫값=1.13e+08 (메모리: 1582.4 MB)
[PBPB]   [Theta] 시작  (메모리: 1582.4 MB)
[메모리] forecast_theta 실행 전: 1582.43 MB
[메모리] forecast_theta 실행 후: 1582.43 MB (변화: +0.00 MB)
[PBPB]   [Theta] 완료  첫값=1.23e+08 (메모리: 1582.4 MB)
[PBPB]   [DB] 88행 저장 완료
[PROGRESS] [ 319/500] ( 63.8%)  >>  FET
[FET]   40분기 | 2016-03-31 ~ 2025-12-31
[FET]   [SARIMA] 시작  (메모리: 1582.4 MB)
[메모리] forecast_sarima 실행 전: 1582.43 MB
[메모리] find_best_sarima_params 실행 전: 1582.43 MB
[메모리] find_best_sarima_params 실행 후: 1582.43 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1582.43 MB (변화: +0.00 MB)
[FET]   [SARIMA] 완료  첫값=2.04e+08 (메모리: 1582.4 MB)
[FET]   [ETS] 시작  (메모리: 1582.4 MB)
[메모리] forecast_ets 실행 전: 1582.43 MB
[메모리] forecast_ets 실행 후: 1582.43 MB (변화: +0.00 MB)
[FET]   [ETS] 완료  첫값=2.06e+08 (메모리: 1582.4 MB)
[FET]   [Prophet] 시작  (메모리: 1582.4 MB)

11:47:40 - cmdstanpy - INFO - Chain [1] start processing
11:47:40 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1582.43 MB
[메모리] forecast_prophet 실행 후: 1582.46 MB (변화: +0.03 MB)
[FET]   [Prophet] 완료  첫값=1.84e+08 (메모리: 1582.5 MB)
[FET]   [LSTM] 시작  (메모리: 1582.5 MB)
[메모리] forecast_lstm 실행 전: 1582.46 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1582.09 MB (변화: -0.37 MB)
[FET]   [LSTM] 완료  첫값=1.92e+08 (메모리: 1582.1 MB)
[FET]   [Theta] 시작  (메모리: 1582.1 MB)
[메모리] forecast_theta 실행 전: 1582.09 MB
[메모리] forecast_theta 실행 후: 1582.09 MB (변화: +0.00 MB)
[FET]   [Theta] 완료  첫값=2.02e+08 (메모리: 1582.1 MB)
[FET]   [DB] 88행 저장 완료
[PROGRESS] [ 320/500] ( 64.0%)  >>  THM
[THM]   40분기 | 2016-03-31 ~ 2025-12-31
[THM]   [SARIMA] 시작  (메모리: 1582.1 MB)
[메모리] forecast_sarima 실행 전: 1582.09 MB
[메모리] find_best_sarima_params 실행 전: 1582.09 MB
[메모리] find_best_sarima_params 실행 후: 1582.09 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1582.09 MB (변화: +0.00 MB)
[THM]   [SARIMA] 완료  첫값=-1.16e+02 (메모리: 1582.1 MB)
[THM]   [ETS] 시작  (메모리: 1582.1 MB)
[메모리] forecast_ets 실행 전: 1582.09 MB
[메모리] forecast_ets 실행 후: 1582.10 MB (변화: +0.01 MB)
[THM]   [ETS] 완료  첫값=-2.65e+02 (메모리: 1582.1 MB)
[THM]   [Prophet] 시작  (메모리: 1582.1 MB)

11:47:58 - cmdstanpy - INFO - Chain [1] start processing
11:47:58 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1582.10 MB
[메모리] forecast_prophet 실행 후: 1582.12 MB (변화: +0.03 MB)
[THM]   [Prophet] 완료  첫값=-1.19e+02 (메모리: 1582.1 MB)
[THM]   [LSTM] 시작  (메모리: 1582.1 MB)
[메모리] forecast_lstm 실행 전: 1582.12 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1583.08 MB (변화: +0.96 MB)
[THM]   [LSTM] 완료  첫값=7.42e+02 (메모리: 1583.1 MB)
[THM]   [Theta] 시작  (메모리: 1583.1 MB)
[메모리] forecast_theta 실행 전: 1583.08 MB
[메모리] forecast_theta 실행 후: 1583.08 MB (변화: +0.00 MB)
[THM]   [Theta] 완료  첫값=-7.04e+02 (메모리: 1583.1 MB)
[THM]   [DB] 88행 저장 완료
[PROGRESS] [ 321/500] ( 64.2%)  >>  PANL
[PANL]   40분기 | 2016-03-31 ~ 2025-12-31
[PANL]   [SARIMA] 시작  (메모리: 1583.1 MB)
[메모리] forecast_sarima 실행 전: 1583.08 MB
[메모리] find_best_sarima_params 실행 전: 1583.08 MB
[메모리] find_best_sarima_params 실행 후: 1583.08 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1583.08 MB (변화: +0.00 MB)
[PANL]   [SARIMA] 완료  첫값=1.57e+08 (메모리: 1583.1 MB)
[PANL]   [ETS] 시작  (메모리: 1583.1 MB)
[메모리] forecast_ets 실행 전: 1583.08 MB
[메모리] forecast_ets 실행 후: 1583.09 MB (변화: +0.00 MB)
[PANL]   [ETS] 완료  첫값=1.61e+08 (메모리: 1583.1 MB)
[PANL]   [Prophet] 시작  (메모리: 1583.1 MB)

11:48:17 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1583.09 MB

11:48:17 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1583.11 MB (변화: +0.03 MB)
[PANL]   [Prophet] 완료  첫값=1.73e+08 (메모리: 1583.1 MB)
[PANL]   [LSTM] 시작  (메모리: 1583.1 MB)
[메모리] forecast_lstm 실행 전: 1583.11 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1581.79 MB (변화: -1.32 MB)
[PANL]   [LSTM] 완료  첫값=1.33e+08 (메모리: 1581.8 MB)
[PANL]   [Theta] 시작  (메모리: 1581.8 MB)
[메모리] forecast_theta 실행 전: 1581.79 MB
[메모리] forecast_theta 실행 후: 1581.79 MB (변화: +0.00 MB)
[PANL]   [Theta] 완료  첫값=1.86e+08 (메모리: 1581.8 MB)
[PANL]   [DB] 88행 저장 완료
[PROGRESS] [ 322/500] ( 64.4%)  >>  INN
[INN]   40분기 | 2016-03-31 ~ 2025-12-31
[INN]   [SARIMA] 시작  (메모리: 1581.8 MB)
[메모리] forecast_sarima 실행 전: 1581.79 MB
[메모리] find_best_sarima_params 실행 전: 1581.79 MB
[메모리] find_best_sarima_params 실행 후: 1581.79 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1581.79 MB (변화: +0.00 MB)
[INN]   [SARIMA] 완료  첫값=1.75e+08 (메모리: 1581.8 MB)
[INN]   [ETS] 시작  (메모리: 1581.8 MB)
[메모리] forecast_ets 실행 전: 1581.79 MB
[메모리] forecast_ets 실행 후: 1581.80 MB (변화: +0.00 MB)
[INN]   [ETS] 완료  첫값=1.87e+08 (메모리: 1581.8 MB)
[INN]   [Prophet] 시작  (메모리: 1581.8 MB)

11:48:32 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1581.80 MB

11:48:32 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1581.82 MB (변화: +0.02 MB)
[INN]   [Prophet] 완료  첫값=1.79e+08 (메모리: 1581.8 MB)
[INN]   [LSTM] 시작  (메모리: 1581.8 MB)
[메모리] forecast_lstm 실행 전: 1581.82 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1581.43 MB (변화: -0.39 MB)
[INN]   [LSTM] 완료  첫값=1.72e+08 (메모리: 1581.4 MB)
[INN]   [Theta] 시작  (메모리: 1581.4 MB)
[메모리] forecast_theta 실행 전: 1581.43 MB
[메모리] forecast_theta 실행 후: 1581.43 MB (변화: +0.00 MB)
[INN]   [Theta] 완료  첫값=1.77e+08 (메모리: 1581.4 MB)
[INN]   [DB] 88행 저장 완료
[PROGRESS] [ 323/500] ( 64.6%)  >>  FEIM
[FEIM]   40분기 | 2016-04-30 ~ 2026-01-31
[FEIM]   [SARIMA] 시작  (메모리: 1581.4 MB)
[메모리] forecast_sarima 실행 전: 1581.43 MB
[메모리] find_best_sarima_params 실행 전: 1581.43 MB
[메모리] find_best_sarima_params 실행 후: 1581.43 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1581.43 MB (변화: +0.00 MB)
[FEIM]   [SARIMA] 완료  첫값=1.69e+07 (메모리: 1581.4 MB)
[FEIM]   [ETS] 시작  (메모리: 1581.4 MB)
[메모리] forecast_ets 실행 전: 1581.43 MB
[메모리] forecast_ets 실행 후: 1581.43 MB (변화: +0.00 MB)
[FEIM]   [ETS] 완료  첫값=1.73e+07 (메모리: 1581.4 MB)
[FEIM]   [Prophet] 시작  (메모리: 1581.4 MB)

11:48:47 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1581.43 MB

11:48:47 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1581.44 MB (변화: +0.01 MB)
[FEIM]   [Prophet] 완료  첫값=1.52e+07 (메모리: 1581.4 MB)
[FEIM]   [LSTM] 시작  (메모리: 1581.4 MB)
[메모리] forecast_lstm 실행 전: 1581.44 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1582.38 MB (변화: +0.95 MB)
[FEIM]   [LSTM] 완료  첫값=1.55e+07 (메모리: 1582.4 MB)
[FEIM]   [Theta] 시작  (메모리: 1582.4 MB)
[메모리] forecast_theta 실행 전: 1582.38 MB
[메모리] forecast_theta 실행 후: 1582.38 MB (변화: +0.00 MB)
[FEIM]   [Theta] 완료  첫값=1.69e+07 (메모리: 1582.4 MB)
[FEIM]   [DB] 88행 저장 완료
[PROGRESS] [ 324/500] ( 64.8%)  >>  ZVRA
[ZVRA]   40분기 | 2016-03-31 ~ 2025-12-31
[ZVRA]   [SARIMA] 시작  (메모리: 1582.4 MB)
[메모리] forecast_sarima 실행 전: 1582.38 MB
[메모리] find_best_sarima_params 실행 전: 1582.38 MB
[메모리] find_best_sarima_params 실행 후: 1582.38 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1582.38 MB (변화: +0.00 MB)
[ZVRA]   [SARIMA] 완료  첫값=3.66e+07 (메모리: 1582.4 MB)
[ZVRA]   [ETS] 시작  (메모리: 1582.4 MB)
[메모리] forecast_ets 실행 전: 1582.38 MB
[메모리] forecast_ets 실행 후: 1582.39 MB (변화: +0.00 MB)
[ZVRA]   [ETS] 완료  첫값=3.38e+07 (메모리: 1582.4 MB)
[ZVRA]   [Prophet] 시작  (메모리: 1582.4 MB)

11:49:01 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1582.39 MB

11:49:01 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1582.55 MB (변화: +0.16 MB)
[ZVRA]   [Prophet] 완료  첫값=1.55e+07 (메모리: 1582.6 MB)
[ZVRA]   [LSTM] 시작  (메모리: 1582.6 MB)
[메모리] forecast_lstm 실행 전: 1582.55 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1581.81 MB (변화: -0.74 MB)
[ZVRA]   [LSTM] 완료  첫값=4.63e+07 (메모리: 1581.8 MB)
[ZVRA]   [Theta] 시작  (메모리: 1581.8 MB)
[메모리] forecast_theta 실행 전: 1581.81 MB
[메모리] forecast_theta 실행 후: 1581.81 MB (변화: +0.00 MB)
[ZVRA]   [Theta] 완료  첫값=3.23e+07 (메모리: 1581.8 MB)
[ZVRA]   [DB] 88행 저장 완료
[PROGRESS] [ 325/500] ( 65.0%)  >>  CYRX
[CYRX]   40분기 | 2016-03-31 ~ 2025-12-31
[CYRX]   [SARIMA] 시작  (메모리: 1581.8 MB)
[메모리] forecast_sarima 실행 전: 1581.81 MB
[메모리] find_best_sarima_params 실행 전: 1581.81 MB
[메모리] find_best_sarima_params 실행 후: 1581.81 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1581.81 MB (변화: +0.00 MB)
[CYRX]   [SARIMA] 완료  첫값=4.95e+07 (메모리: 1581.8 MB)
[CYRX]   [ETS] 시작  (메모리: 1581.8 MB)
[메모리] forecast_ets 실행 전: 1581.81 MB
[메모리] forecast_ets 실행 후: 1581.81 MB (변화: +0.00 MB)
[CYRX]   [ETS] 완료  첫값=4.47e+07 (메모리: 1581.8 MB)
[CYRX]   [Prophet] 시작  (메모리: 1581.8 MB)

11:49:20 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1581.81 MB

11:49:20 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1581.85 MB (변화: +0.04 MB)
[CYRX]   [Prophet] 완료  첫값=6.62e+07 (메모리: 1581.8 MB)
[CYRX]   [LSTM] 시작  (메모리: 1581.8 MB)
[메모리] forecast_lstm 실행 전: 1581.85 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1580.49 MB (변화: -1.36 MB)
[CYRX]   [LSTM] 완료  첫값=4.99e+07 (메모리: 1580.5 MB)
[CYRX]   [Theta] 시작  (메모리: 1580.5 MB)
[메모리] forecast_theta 실행 전: 1580.49 MB
[메모리] forecast_theta 실행 후: 1580.50 MB (변화: +0.00 MB)
[CYRX]   [Theta] 완료  첫값=4.33e+07 (메모리: 1580.5 MB)
[CYRX]   [DB] 88행 저장 완료
[PROGRESS] [ 326/500] ( 65.2%)  >>  SOHU
[SOHU]   40분기 | 2016-03-31 ~ 2025-12-31
[SOHU]   [SARIMA] 시작  (메모리: 1580.5 MB)
[메모리] forecast_sarima 실행 전: 1580.50 MB
[메모리] find_best_sarima_params 실행 전: 1580.50 MB
[메모리] find_best_sarima_params 실행 후: 1580.50 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1580.50 MB (변화: +0.00 MB)
[SOHU]   [SARIMA] 완료  첫값=1.43e+08 (메모리: 1580.5 MB)
[SOHU]   [ETS] 시작  (메모리: 1580.5 MB)
[메모리] forecast_ets 실행 전: 1580.50 MB
[메모리] forecast_ets 실행 후: 1580.50 MB (변화: +0.00 MB)
[SOHU]   [ETS] 완료  첫값=1.22e+08 (메모리: 1580.5 MB)
[SOHU]   [Prophet] 시작  (메모리: 1580.5 MB)
[메모리] forecast_prophet 실행 전: 1580.50 MB

11:49:39 - cmdstanpy - INFO - Chain [1] start processing
11:49:39 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1580.54 MB (변화: +0.04 MB)
[SOHU]   [Prophet] 완료  첫값=6.97e+07 (메모리: 1580.5 MB)
[SOHU]   [LSTM] 시작  (메모리: 1580.5 MB)
[메모리] forecast_lstm 실행 전: 1580.54 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1581.47 MB (변화: +0.93 MB)
[SOHU]   [LSTM] 완료  첫값=1.48e+08 (메모리: 1581.5 MB)
[SOHU]   [Theta] 시작  (메모리: 1581.5 MB)
[메모리] forecast_theta 실행 전: 1581.47 MB
[메모리] forecast_theta 실행 후: 1581.47 MB (변화: +0.00 MB)
[SOHU]   [Theta] 완료  첫값=1.24e+08 (메모리: 1581.5 MB)
[SOHU]   [DB] 88행 저장 완료
[PROGRESS] [ 327/500] ( 65.4%)  >>  LGTY
[LGTY]   40분기 | 2015-01-31 ~ 2024-10-31
[LGTY]   [SARIMA] 시작  (메모리: 1581.5 MB)
[메모리] forecast_sarima 실행 전: 1581.47 MB
[메모리] find_best_sarima_params 실행 전: 1581.47 MB
[메모리] find_best_sarima_params 실행 후: 1581.47 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1581.47 MB (변화: +0.00 MB)
[LGTY]   [SARIMA] 완료  첫값=2.53e+07 (메모리: 1581.5 MB)
[LGTY]   [ETS] 시작  (메모리: 1581.5 MB)
[메모리] forecast_ets 실행 전: 1581.47 MB
[메모리] forecast_ets 실행 후: 1581.48 MB (변화: +0.01 MB)
[LGTY]   [ETS] 완료  첫값=2.58e+07 (메모리: 1581.5 MB)
[LGTY]   [Prophet] 시작  (메모리: 1581.5 MB)

11:49:59 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1581.48 MB

11:49:59 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1581.49 MB (변화: +0.01 MB)
[LGTY]   [Prophet] 완료  첫값=2.78e+07 (메모리: 1581.5 MB)
[LGTY]   [LSTM] 시작  (메모리: 1581.5 MB)
[메모리] forecast_lstm 실행 전: 1581.49 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1581.57 MB (변화: +0.08 MB)
[LGTY]   [LSTM] 완료  첫값=2.74e+07 (메모리: 1581.6 MB)
[LGTY]   [Theta] 시작  (메모리: 1581.6 MB)
[메모리] forecast_theta 실행 전: 1581.57 MB
[메모리] forecast_theta 실행 후: 1581.57 MB (변화: +0.00 MB)
[LGTY]   [Theta] 완료  첫값=2.55e+07 (메모리: 1581.6 MB)
[LGTY]   [DB] 88행 저장 완료
[PROGRESS] [ 328/500] ( 65.6%)  >>  BDN
[BDN]   40분기 | 2016-03-31 ~ 2025-12-31
[BDN]   [SARIMA] 시작  (메모리: 1581.6 MB)
[메모리] forecast_sarima 실행 전: 1581.57 MB
[메모리] find_best_sarima_params 실행 전: 1581.57 MB
[메모리] find_best_sarima_params 실행 후: 1581.57 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1581.57 MB (변화: +0.00 MB)
[BDN]   [SARIMA] 완료  첫값=1.21e+08 (메모리: 1581.6 MB)
[BDN]   [ETS] 시작  (메모리: 1581.6 MB)
[메모리] forecast_ets 실행 전: 1581.57 MB
[메모리] forecast_ets 실행 후: 1581.57 MB (변화: +0.00 MB)
[BDN]   [ETS] 완료  첫값=1.21e+08 (메모리: 1581.6 MB)
[BDN]   [Prophet] 시작  (메모리: 1581.6 MB)

11:50:20 - cmdstanpy - INFO - Chain [1] start processing
11:50:20 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1581.57 MB
[메모리] forecast_prophet 실행 후: 1581.58 MB (변화: +0.01 MB)
[BDN]   [Prophet] 완료  첫값=1.22e+08 (메모리: 1581.6 MB)
[BDN]   [LSTM] 시작  (메모리: 1581.6 MB)
[메모리] forecast_lstm 실행 전: 1581.58 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1581.52 MB (변화: -0.07 MB)
[BDN]   [LSTM] 완료  첫값=1.27e+08 (메모리: 1581.5 MB)
[BDN]   [Theta] 시작  (메모리: 1581.5 MB)
[메모리] forecast_theta 실행 전: 1581.52 MB
[메모리] forecast_theta 실행 후: 1581.52 MB (변화: +0.00 MB)
[BDN]   [Theta] 완료  첫값=1.21e+08 (메모리: 1581.5 MB)
[BDN]   [DB] 88행 저장 완료
[PROGRESS] [ 329/500] ( 65.8%)  >>  OIS
[OIS]   40분기 | 2016-03-31 ~ 2025-12-31
[OIS]   [SARIMA] 시작  (메모리: 1581.5 MB)
[메모리] forecast_sarima 실행 전: 1581.52 MB
[메모리] find_best_sarima_params 실행 전: 1581.52 MB
[메모리] find_best_sarima_params 실행 후: 1581.52 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1581.52 MB (변화: +0.00 MB)
[OIS]   [SARIMA] 완료  첫값=1.78e+08 (메모리: 1581.5 MB)
[OIS]   [ETS] 시작  (메모리: 1581.5 MB)
[메모리] forecast_ets 실행 전: 1581.52 MB
[메모리] forecast_ets 실행 후: 1581.52 MB (변화: +0.01 MB)
[OIS]   [ETS] 완료  첫값=1.72e+08 (메모리: 1581.5 MB)
[OIS]   [Prophet] 시작  (메모리: 1581.5 MB)

11:50:39 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1581.52 MB

11:50:39 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1582.26 MB (변화: +0.74 MB)
[OIS]   [Prophet] 완료  첫값=1.71e+08 (메모리: 1582.3 MB)
[OIS]   [LSTM] 시작  (메모리: 1582.3 MB)
[메모리] forecast_lstm 실행 전: 1582.26 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1582.33 MB (변화: +0.07 MB)
[OIS]   [LSTM] 완료  첫값=1.79e+08 (메모리: 1582.3 MB)
[OIS]   [Theta] 시작  (메모리: 1582.3 MB)
[메모리] forecast_theta 실행 전: 1582.33 MB
[메모리] forecast_theta 실행 후: 1582.33 MB (변화: +0.00 MB)
[OIS]   [Theta] 완료  첫값=1.78e+08 (메모리: 1582.3 MB)
[OIS]   [DB] 88행 저장 완료
[PROGRESS] [ 330/500] ( 66.0%)  >>  TAST
[TAST]   40분기 | 2014-06-29 ~ 2024-03-31
[TAST]   [SARIMA] 시작  (메모리: 1582.3 MB)
[메모리] forecast_sarima 실행 전: 1582.33 MB
[메모리] find_best_sarima_params 실행 전: 1582.33 MB
[메모리] find_best_sarima_params 실행 후: 1582.33 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1582.33 MB (변화: +0.00 MB)
[TAST]   [SARIMA] 완료  첫값=5.11e+08 (메모리: 1582.3 MB)
[TAST]   [ETS] 시작  (메모리: 1582.3 MB)
[메모리] forecast_ets 실행 전: 1582.33 MB
[메모리] forecast_ets 실행 후: 1582.33 MB (변화: +0.00 MB)
[TAST]   [ETS] 완료  첫값=5.07e+08 (메모리: 1582.3 MB)
[TAST]   [Prophet] 시작  (메모리: 1582.3 MB)

11:51:00 - cmdstanpy - INFO - Chain [1] start processing
11:51:00 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1582.33 MB
[메모리] forecast_prophet 실행 후: 1581.86 MB (변화: -0.48 MB)
[TAST]   [Prophet] 완료  첫값=4.92e+08 (메모리: 1581.9 MB)
[TAST]   [LSTM] 시작  (메모리: 1581.9 MB)
[메모리] forecast_lstm 실행 전: 1581.86 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1582.81 MB (변화: +0.96 MB)
[TAST]   [LSTM] 완료  첫값=4.80e+08 (메모리: 1582.8 MB)
[TAST]   [Theta] 시작  (메모리: 1582.8 MB)
[메모리] forecast_theta 실행 전: 1582.81 MB
[메모리] forecast_theta 실행 후: 1582.81 MB (변화: +0.00 MB)
[TAST]   [Theta] 완료  첫값=5.01e+08 (메모리: 1582.8 MB)
[TAST]   [DB] 88행 저장 완료
[PROGRESS] [ 331/500] ( 66.2%)  >>  DVS
[DVS]   40분기 | 2016-03-31 ~ 2025-12-31
[DVS]   [SARIMA] 시작  (메모리: 1582.8 MB)
[메모리] forecast_sarima 실행 전: 1582.81 MB
[메모리] find_best_sarima_params 실행 전: 1582.81 MB
[메모리] find_best_sarima_params 실행 후: 1582.81 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1582.81 MB (변화: +0.00 MB)
[DVS]   [SARIMA] 완료  첫값=0.00e+00 (메모리: 1582.8 MB)
[DVS]   [ETS] 시작  (메모리: 1582.8 MB)
[메모리] forecast_ets 실행 전: 1582.81 MB
[메모리] forecast_ets 실행 후: 1582.82 MB (변화: +0.00 MB)
[DVS]   [ETS] 완료  첫값=0.00e+00 (메모리: 1582.8 MB)
[DVS]   [Prophet] 시작  (메모리: 1582.8 MB)
[메모리] forecast_prophet 실행 전: 1582.82 MB
[메모리] forecast_prophet 실행 후: 1582.84 MB (변화: +0.02 MB)
[DVS]   [Prophet] 완료  첫값=0.00e+00 (메모리: 1582.8 MB)
[DVS]   [LSTM] 시작  (메모리: 1582.8 MB)
[메모리] forecast_lstm 실행 전: 1582.84 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1582.70 MB (변화: -0.14 MB)
[DVS]   [LSTM] 완료  첫값=0.00e+00 (메모리: 1582.7 MB)
[DVS]   [Theta] 시작  (메모리: 1582.7 MB)
[메모리] forecast_theta 실행 전: 1582.70 MB
[메모리] forecast_theta 실행 후: 1582.70 MB (변화: +0.00 MB)
[DVS]   [Theta] 완료  첫값=0.00e+00 (메모리: 1582.7 MB)
[DVS]   [DB] 88행 저장 완료
[PROGRESS] [ 332/500] ( 66.4%)  >>  RBBN
[RBBN]   40분기 | 2016-03-31 ~ 2025-12-31
[RBBN]   [SARIMA] 시작  (메모리: 1582.7 MB)
[메모리] forecast_sarima 실행 전: 1582.70 MB
[메모리] find_best_sarima_params 실행 전: 1582.70 MB
[메모리] find_best_sarima_params 실행 후: 1582.70 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1582.70 MB (변화: +0.00 MB)
[RBBN]   [SARIMA] 완료  첫값=1.85e+08 (메모리: 1582.7 MB)
[RBBN]   [ETS] 시작  (메모리: 1582.7 MB)
[메모리] forecast_ets 실행 전: 1582.70 MB
[메모리] forecast_ets 실행 후: 1582.71 MB (변화: +0.00 MB)
[RBBN]   [ETS] 완료  첫값=1.80e+08 (메모리: 1582.7 MB)
[RBBN]   [Prophet] 시작  (메모리: 1582.7 MB)

11:51:34 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1582.71 MB

11:51:34 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1582.73 MB (변화: +0.02 MB)
[RBBN]   [Prophet] 완료  첫값=2.55e+08 (메모리: 1582.7 MB)
[RBBN]   [LSTM] 시작  (메모리: 1582.7 MB)
[메모리] forecast_lstm 실행 전: 1582.73 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1582.25 MB (변화: -0.48 MB)
[RBBN]   [LSTM] 완료  첫값=2.06e+08 (메모리: 1582.2 MB)
[RBBN]   [Theta] 시작  (메모리: 1582.2 MB)
[메모리] forecast_theta 실행 전: 1582.25 MB
[메모리] forecast_theta 실행 후: 1582.25 MB (변화: +0.00 MB)
[RBBN]   [Theta] 완료  첫값=1.76e+08 (메모리: 1582.2 MB)
[RBBN]   [DB] 88행 저장 완료
[PROGRESS] [ 333/500] ( 66.6%)  >>  SWBI
[SWBI]   40분기 | 2016-04-30 ~ 2026-01-31
[SWBI]   [SARIMA] 시작  (메모리: 1582.2 MB)
[메모리] forecast_sarima 실행 전: 1582.25 MB
[메모리] find_best_sarima_params 실행 전: 1582.25 MB
[메모리] find_best_sarima_params 실행 후: 1582.25 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1582.25 MB (변화: +0.00 MB)
[SWBI]   [SARIMA] 완료  첫값=1.64e+08 (메모리: 1582.2 MB)
[SWBI]   [ETS] 시작  (메모리: 1582.2 MB)
[메모리] forecast_ets 실행 전: 1582.25 MB
[메모리] forecast_ets 실행 후: 1582.26 MB (변화: +0.01 MB)
[SWBI]   [ETS] 완료  첫값=1.55e+08 (메모리: 1582.3 MB)
[SWBI]   [Prophet] 시작  (메모리: 1582.3 MB)

11:51:49 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1582.26 MB

11:51:49 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1582.27 MB (변화: +0.02 MB)
[SWBI]   [Prophet] 완료  첫값=1.26e+08 (메모리: 1582.3 MB)
[SWBI]   [LSTM] 시작  (메모리: 1582.3 MB)
[메모리] forecast_lstm 실행 전: 1582.27 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1583.22 MB (변화: +0.95 MB)
[SWBI]   [LSTM] 완료  첫값=1.48e+08 (메모리: 1583.2 MB)
[SWBI]   [Theta] 시작  (메모리: 1583.2 MB)
[메모리] forecast_theta 실행 전: 1583.22 MB
[메모리] forecast_theta 실행 후: 1583.22 MB (변화: +0.00 MB)
[SWBI]   [Theta] 완료  첫값=1.26e+08 (메모리: 1583.2 MB)
[SWBI]   [DB] 88행 저장 완료
[PROGRESS] [ 334/500] ( 66.8%)  >>  LWLG
[LWLG]   40분기 | 2016-03-31 ~ 2025-12-31
[LWLG]   [SARIMA] 시작  (메모리: 1583.2 MB)
[메모리] forecast_sarima 실행 전: 1583.22 MB
[메모리] find_best_sarima_params 실행 전: 1583.22 MB
[메모리] find_best_sarima_params 실행 후: 1583.22 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1583.22 MB (변화: +0.00 MB)
[LWLG]   [SARIMA] 완료  첫값=1.35e+05 (메모리: 1583.2 MB)
[LWLG]   [ETS] 시작  (메모리: 1583.2 MB)
[메모리] forecast_ets 실행 전: 1583.22 MB
[메모리] forecast_ets 실행 후: 1583.23 MB (변화: +0.00 MB)
[LWLG]   [ETS] 완료  첫값=6.68e+04 (메모리: 1583.2 MB)
[LWLG]   [Prophet] 시작  (메모리: 1583.2 MB)

11:52:07 - cmdstanpy - INFO - Chain [1] start processing
11:52:07 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1583.23 MB
[메모리] forecast_prophet 실행 후: 1583.26 MB (변화: +0.03 MB)
[LWLG]   [Prophet] 완료  첫값=2.61e+04 (메모리: 1583.3 MB)
[LWLG]   [LSTM] 시작  (메모리: 1583.3 MB)
[메모리] forecast_lstm 실행 전: 1583.26 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1582.87 MB (변화: -0.39 MB)
[LWLG]   [LSTM] 완료  첫값=1.24e+05 (메모리: 1582.9 MB)
[LWLG]   [Theta] 시작  (메모리: 1582.9 MB)
[메모리] forecast_theta 실행 전: 1582.87 MB
[메모리] forecast_theta 실행 후: 1582.87 MB (변화: +0.00 MB)
[LWLG]   [Theta] 완료  첫값=1.58e+05 (메모리: 1582.9 MB)
[LWLG]   [DB] 88행 저장 완료
[PROGRESS] [ 335/500] ( 67.0%)  >>  NAGE
[NAGE]   40분기 | 2016-03-31 ~ 2025-12-31
[NAGE]   [SARIMA] 시작  (메모리: 1582.9 MB)
[메모리] forecast_sarima 실행 전: 1582.87 MB
[메모리] find_best_sarima_params 실행 전: 1582.87 MB
[메모리] find_best_sarima_params 실행 후: 1582.87 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1582.87 MB (변화: +0.00 MB)
[NAGE]   [SARIMA] 완료  첫값=3.53e+07 (메모리: 1582.9 MB)
[NAGE]   [ETS] 시작  (메모리: 1582.9 MB)
[메모리] forecast_ets 실행 전: 1582.87 MB
[메모리] forecast_ets 실행 후: 1582.87 MB (변화: +0.00 MB)
[NAGE]   [ETS] 완료  첫값=3.36e+07 (메모리: 1582.9 MB)
[NAGE]   [Prophet] 시작  (메모리: 1582.9 MB)

11:52:26 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1582.87 MB

11:52:26 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1582.91 MB (변화: +0.04 MB)
[NAGE]   [Prophet] 완료  첫값=3.12e+07 (메모리: 1582.9 MB)
[NAGE]   [LSTM] 시작  (메모리: 1582.9 MB)
[메모리] forecast_lstm 실행 전: 1582.91 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1582.55 MB (변화: -0.36 MB)
[NAGE]   [LSTM] 완료  첫값=2.94e+07 (메모리: 1582.5 MB)
[NAGE]   [Theta] 시작  (메모리: 1582.5 MB)
[메모리] forecast_theta 실행 전: 1582.55 MB
[메모리] forecast_theta 실행 후: 1582.55 MB (변화: +0.00 MB)
[NAGE]   [Theta] 완료  첫값=3.22e+07 (메모리: 1582.5 MB)
[NAGE]   [DB] 88행 저장 완료
[PROGRESS] [ 336/500] ( 67.2%)  >>  DIN
[DIN]   40분기 | 2016-03-31 ~ 2025-12-28
[DIN]   [SARIMA] 시작  (메모리: 1582.5 MB)
[메모리] forecast_sarima 실행 전: 1582.55 MB
[메모리] find_best_sarima_params 실행 전: 1582.55 MB
[메모리] find_best_sarima_params 실행 후: 1582.55 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1582.55 MB (변화: +0.00 MB)
[DIN]   [SARIMA] 완료  첫값=2.25e+08 (메모리: 1582.5 MB)
[DIN]   [ETS] 시작  (메모리: 1582.5 MB)
[메모리] forecast_ets 실행 전: 1582.55 MB
[메모리] forecast_ets 실행 후: 1582.55 MB (변화: +0.00 MB)
[DIN]   [ETS] 완료  첫값=2.33e+08 (메모리: 1582.6 MB)
[DIN]   [Prophet] 시작  (메모리: 1582.6 MB)
[메모리] forecast_prophet 실행 전: 1582.55 MB

11:52:42 - cmdstanpy - INFO - Chain [1] start processing
11:52:42 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1582.57 MB (변화: +0.02 MB)
[DIN]   [Prophet] 완료  첫값=2.26e+08 (메모리: 1582.6 MB)
[DIN]   [LSTM] 시작  (메모리: 1582.6 MB)
[메모리] forecast_lstm 실행 전: 1582.57 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1582.39 MB (변화: -0.18 MB)
[DIN]   [LSTM] 완료  첫값=2.07e+08 (메모리: 1582.4 MB)
[DIN]   [Theta] 시작  (메모리: 1582.4 MB)
[메모리] forecast_theta 실행 전: 1582.39 MB
[메모리] forecast_theta 실행 후: 1582.39 MB (변화: +0.00 MB)
[DIN]   [Theta] 완료  첫값=2.19e+08 (메모리: 1582.4 MB)
[DIN]   [DB] 88행 저장 완료
[PROGRESS] [ 337/500] ( 67.4%)  >>  KMDA
[KMDA]   40분기 | 2016-03-31 ~ 2025-12-31
[KMDA]   [SARIMA] 시작  (메모리: 1582.4 MB)
[메모리] forecast_sarima 실행 전: 1582.39 MB
[메모리] find_best_sarima_params 실행 전: 1582.39 MB
[메모리] find_best_sarima_params 실행 후: 1582.39 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1582.39 MB (변화: +0.00 MB)
[KMDA]   [SARIMA] 완료  첫값=4.47e+07 (메모리: 1582.4 MB)
[KMDA]   [ETS] 시작  (메모리: 1582.4 MB)
[메모리] forecast_ets 실행 전: 1582.39 MB
[메모리] forecast_ets 실행 후: 1582.39 MB (변화: +0.00 MB)
[KMDA]   [ETS] 완료  첫값=3.84e+07 (메모리: 1582.4 MB)
[KMDA]   [Prophet] 시작  (메모리: 1582.4 MB)

11:52:56 - cmdstanpy - INFO - Chain [1] start processing
11:52:56 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1582.39 MB
[메모리] forecast_prophet 실행 후: 1582.41 MB (변화: +0.01 MB)
[KMDA]   [Prophet] 완료  첫값=4.35e+07 (메모리: 1582.4 MB)
[KMDA]   [LSTM] 시작  (메모리: 1582.4 MB)
[메모리] forecast_lstm 실행 전: 1582.41 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1582.30 MB (변화: -0.10 MB)
[KMDA]   [LSTM] 완료  첫값=3.99e+07 (메모리: 1582.3 MB)
[KMDA]   [Theta] 시작  (메모리: 1582.3 MB)
[메모리] forecast_theta 실행 전: 1582.30 MB
[메모리] forecast_theta 실행 후: 1582.30 MB (변화: +0.00 MB)
[KMDA]   [Theta] 완료  첫값=3.74e+07 (메모리: 1582.3 MB)
[KMDA]   [DB] 88행 저장 완료
[PROGRESS] [ 338/500] ( 67.6%)  >>  EGY
[EGY]   40분기 | 2016-03-31 ~ 2025-12-31
[EGY]   [SARIMA] 시작  (메모리: 1582.3 MB)
[메모리] forecast_sarima 실행 전: 1582.30 MB
[메모리] find_best_sarima_params 실행 전: 1582.30 MB
[메모리] find_best_sarima_params 실행 후: 1582.30 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1582.30 MB (변화: +0.00 MB)
[EGY]   [SARIMA] 완료  첫값=5.99e+07 (메모리: 1582.3 MB)
[EGY]   [ETS] 시작  (메모리: 1582.3 MB)
[메모리] forecast_ets 실행 전: 1582.30 MB
[메모리] forecast_ets 실행 후: 1582.31 MB (변화: +0.00 MB)
[EGY]   [ETS] 완료  첫값=6.95e+07 (메모리: 1582.3 MB)
[EGY]   [Prophet] 시작  (메모리: 1582.3 MB)

11:53:11 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1582.31 MB

11:53:11 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1582.34 MB (변화: +0.03 MB)
[EGY]   [Prophet] 완료  첫값=1.26e+08 (메모리: 1582.3 MB)
[EGY]   [LSTM] 시작  (메모리: 1582.3 MB)
[메모리] forecast_lstm 실행 전: 1582.34 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1581.96 MB (변화: -0.38 MB)
[EGY]   [LSTM] 완료  첫값=1.09e+08 (메모리: 1582.0 MB)
[EGY]   [Theta] 시작  (메모리: 1582.0 MB)
[메모리] forecast_theta 실행 전: 1581.96 MB
[메모리] forecast_theta 실행 후: 1581.96 MB (변화: +0.00 MB)
[EGY]   [Theta] 완료  첫값=6.77e+07 (메모리: 1582.0 MB)
[EGY]   [DB] 88행 저장 완료
[PROGRESS] [ 339/500] ( 67.8%)  >>  EBF
[EBF]   40분기 | 2016-02-28 ~ 2025-11-30
[EBF]   [SARIMA] 시작  (메모리: 1582.0 MB)
[메모리] forecast_sarima 실행 전: 1581.96 MB
[메모리] find_best_sarima_params 실행 전: 1581.96 MB
[메모리] find_best_sarima_params 실행 후: 1581.96 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1581.96 MB (변화: +0.00 MB)
[EBF]   [SARIMA] 완료  첫값=1.00e+08 (메모리: 1582.0 MB)
[EBF]   [ETS] 시작  (메모리: 1582.0 MB)
[메모리] forecast_ets 실행 전: 1581.96 MB
[메모리] forecast_ets 실행 후: 1581.97 MB (변화: +0.00 MB)
[EBF]   [ETS] 완료  첫값=9.46e+07 (메모리: 1582.0 MB)
[EBF]   [Prophet] 시작  (메모리: 1582.0 MB)

11:53:27 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1581.97 MB

11:53:27 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1582.34 MB (변화: +0.38 MB)
[EBF]   [Prophet] 완료  첫값=1.02e+08 (메모리: 1582.3 MB)
[EBF]   [LSTM] 시작  (메모리: 1582.3 MB)
[메모리] forecast_lstm 실행 전: 1582.34 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1581.94 MB (변화: -0.40 MB)
[EBF]   [LSTM] 완료  첫값=9.87e+07 (메모리: 1581.9 MB)
[EBF]   [Theta] 시작  (메모리: 1581.9 MB)
[메모리] forecast_theta 실행 전: 1581.94 MB
[메모리] forecast_theta 실행 후: 1581.94 MB (변화: +0.00 MB)
[EBF]   [Theta] 완료  첫값=1.00e+08 (메모리: 1581.9 MB)
[EBF]   [DB] 88행 저장 완료
[PROGRESS] [ 340/500] ( 68.0%)  >>  FPI
[FPI]   40분기 | 2016-03-31 ~ 2025-12-31
[FPI]   [SARIMA] 시작  (메모리: 1581.9 MB)
[메모리] forecast_sarima 실행 전: 1581.94 MB
[메모리] find_best_sarima_params 실행 전: 1581.94 MB
[메모리] find_best_sarima_params 실행 후: 1581.94 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1581.94 MB (변화: +0.00 MB)
[FPI]   [SARIMA] 완료  첫값=1.17e+07 (메모리: 1581.9 MB)
[FPI]   [ETS] 시작  (메모리: 1581.9 MB)
[메모리] forecast_ets 실행 전: 1581.94 MB
[메모리] forecast_ets 실행 후: 1581.95 MB (변화: +0.00 MB)
[FPI]   [ETS] 완료  첫값=1.24e+07 (메모리: 1581.9 MB)
[FPI]   [Prophet] 시작  (메모리: 1581.9 MB)

11:53:47 - cmdstanpy - INFO - Chain [1] start processing
11:53:47 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1581.95 MB
[메모리] forecast_prophet 실행 후: 1581.96 MB (변화: +0.02 MB)
[FPI]   [Prophet] 완료  첫값=1.60e+07 (메모리: 1582.0 MB)
[FPI]   [LSTM] 시작  (메모리: 1582.0 MB)
[메모리] forecast_lstm 실행 전: 1581.96 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1582.93 MB (변화: +0.96 MB)
[FPI]   [LSTM] 완료  첫값=1.62e+07 (메모리: 1582.9 MB)
[FPI]   [Theta] 시작  (메모리: 1582.9 MB)
[메모리] forecast_theta 실행 전: 1582.93 MB
[메모리] forecast_theta 실행 후: 1582.93 MB (변화: +0.00 MB)
[FPI]   [Theta] 완료  첫값=1.25e+07 (메모리: 1582.9 MB)
[FPI]   [DB] 88행 저장 완료
[PROGRESS] [ 341/500] ( 68.2%)  >>  PWFL
[PWFL]   40분기 | 2016-03-31 ~ 2025-12-31
[PWFL]   [SARIMA] 시작  (메모리: 1582.9 MB)
[메모리] forecast_sarima 실행 전: 1582.93 MB
[메모리] find_best_sarima_params 실행 전: 1582.93 MB
[메모리] find_best_sarima_params 실행 후: 1582.93 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1582.93 MB (변화: +0.00 MB)
[PWFL]   [SARIMA] 완료  첫값=1.21e+08 (메모리: 1582.9 MB)
[PWFL]   [ETS] 시작  (메모리: 1582.9 MB)
[메모리] forecast_ets 실행 전: 1582.93 MB
[메모리] forecast_ets 실행 후: 1582.93 MB (변화: +0.01 MB)
[PWFL]   [ETS] 완료  첫값=1.14e+08 (메모리: 1582.9 MB)
[PWFL]   [Prophet] 시작  (메모리: 1582.9 MB)

11:54:02 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1582.93 MB

11:54:02 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1582.95 MB (변화: +0.02 MB)
[PWFL]   [Prophet] 완료  첫값=8.22e+07 (메모리: 1583.0 MB)
[PWFL]   [LSTM] 시작  (메모리: 1583.0 MB)
[메모리] forecast_lstm 실행 전: 1582.95 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1582.96 MB (변화: +0.01 MB)
[PWFL]   [LSTM] 완료  첫값=1.62e+08 (메모리: 1583.0 MB)
[PWFL]   [Theta] 시작  (메모리: 1583.0 MB)
[메모리] forecast_theta 실행 전: 1582.96 MB
[메모리] forecast_theta 실행 후: 1582.96 MB (변화: +0.00 MB)
[PWFL]   [Theta] 완료  첫값=1.08e+08 (메모리: 1583.0 MB)
[PWFL]   [DB] 88행 저장 완료
[PROGRESS] [ 342/500] ( 68.4%)  >>  MAGN
[MAGN]   40분기 | 2016-03-31 ~ 2025-12-27
[MAGN]   [SARIMA] 시작  (메모리: 1583.0 MB)
[메모리] forecast_sarima 실행 전: 1582.96 MB
[메모리] find_best_sarima_params 실행 전: 1582.96 MB
[메모리] find_best_sarima_params 실행 후: 1582.96 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1582.96 MB (변화: +0.00 MB)
[MAGN]   [SARIMA] 완료  첫값=8.45e+08 (메모리: 1583.0 MB)
[MAGN]   [ETS] 시작  (메모리: 1583.0 MB)
[메모리] forecast_ets 실행 전: 1582.96 MB
[메모리] forecast_ets 실행 후: 1582.96 MB (변화: +0.00 MB)
[MAGN]   [ETS] 완료  첫값=8.39e+08 (메모리: 1583.0 MB)
[MAGN]   [Prophet] 시작  (메모리: 1583.0 MB)

11:54:19 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1582.96 MB

11:54:19 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1582.99 MB (변화: +0.02 MB)
[MAGN]   [Prophet] 완료  첫값=5.27e+08 (메모리: 1583.0 MB)
[MAGN]   [LSTM] 시작  (메모리: 1583.0 MB)
[메모리] forecast_lstm 실행 전: 1582.99 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1582.13 MB (변화: -0.86 MB)
[MAGN]   [LSTM] 완료  첫값=1.21e+09 (메모리: 1582.1 MB)
[MAGN]   [Theta] 시작  (메모리: 1582.1 MB)
[메모리] forecast_theta 실행 전: 1582.13 MB
[메모리] forecast_theta 실행 후: 1582.13 MB (변화: +0.00 MB)
[MAGN]   [Theta] 완료  첫값=8.12e+08 (메모리: 1582.1 MB)
[MAGN]   [DB] 88행 저장 완료
[PROGRESS] [ 343/500] ( 68.6%)  >>  RMR
[RMR]   40분기 | 2016-03-31 ~ 2025-12-31
[RMR]   [SARIMA] 시작  (메모리: 1582.1 MB)
[메모리] forecast_sarima 실행 전: 1582.13 MB
[메모리] find_best_sarima_params 실행 전: 1582.13 MB
[메모리] find_best_sarima_params 실행 후: 1582.13 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1582.13 MB (변화: +0.00 MB)
[RMR]   [SARIMA] 완료  첫값=1.66e+08 (메모리: 1582.1 MB)
[RMR]   [ETS] 시작  (메모리: 1582.1 MB)
[메모리] forecast_ets 실행 전: 1582.13 MB
[메모리] forecast_ets 실행 후: 1582.13 MB (변화: +0.00 MB)
[RMR]   [ETS] 완료  첫값=1.68e+08 (메모리: 1582.1 MB)
[RMR]   [Prophet] 시작  (메모리: 1582.1 MB)

11:54:36 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1582.13 MB

11:54:36 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1582.15 MB (변화: +0.02 MB)
[RMR]   [Prophet] 완료  첫값=1.81e+08 (메모리: 1582.1 MB)
[RMR]   [LSTM] 시작  (메모리: 1582.1 MB)
[메모리] forecast_lstm 실행 전: 1582.15 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1583.12 MB (변화: +0.97 MB)
[RMR]   [LSTM] 완료  첫값=1.79e+08 (메모리: 1583.1 MB)
[RMR]   [Theta] 시작  (메모리: 1583.1 MB)
[메모리] forecast_theta 실행 전: 1583.12 MB
[메모리] forecast_theta 실행 후: 1583.12 MB (변화: +0.00 MB)
[RMR]   [Theta] 완료  첫값=1.80e+08 (메모리: 1583.1 MB)
[RMR]   [DB] 88행 저장 완료
[PROGRESS] [ 344/500] ( 68.8%)  >>  HPP
[HPP]   40분기 | 2016-03-31 ~ 2025-12-31
[HPP]   [SARIMA] 시작  (메모리: 1583.1 MB)
[메모리] forecast_sarima 실행 전: 1583.12 MB
[메모리] find_best_sarima_params 실행 전: 1583.12 MB
[메모리] find_best_sarima_params 실행 후: 1583.12 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1583.12 MB (변화: +0.00 MB)
[HPP]   [SARIMA] 완료  첫값=2.59e+08 (메모리: 1583.1 MB)
[HPP]   [ETS] 시작  (메모리: 1583.1 MB)
[메모리] forecast_ets 실행 전: 1583.12 MB
[메모리] forecast_ets 실행 후: 1583.12 MB (변화: +0.00 MB)
[HPP]   [ETS] 완료  첫값=2.50e+08 (메모리: 1583.1 MB)
[HPP]   [Prophet] 시작  (메모리: 1583.1 MB)
[메모리] forecast_prophet 실행 전: 1583.12 MB

11:54:51 - cmdstanpy - INFO - Chain [1] start processing
11:54:51 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1583.13 MB (변화: +0.01 MB)
[HPP]   [Prophet] 완료  첫값=2.15e+08 (메모리: 1583.1 MB)
[HPP]   [LSTM] 시작  (메모리: 1583.1 MB)
[메모리] forecast_lstm 실행 전: 1583.13 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1583.11 MB (변화: -0.02 MB)
[HPP]   [LSTM] 완료  첫값=2.18e+08 (메모리: 1583.1 MB)
[HPP]   [Theta] 시작  (메모리: 1583.1 MB)
[메모리] forecast_theta 실행 전: 1583.11 MB
[메모리] forecast_theta 실행 후: 1583.11 MB (변화: +0.00 MB)
[HPP]   [Theta] 완료  첫값=2.49e+08 (메모리: 1583.1 MB)
[HPP]   [DB] 88행 저장 완료
[PROGRESS] [ 345/500] ( 69.0%)  >>  GEVO
[GEVO]   40분기 | 2016-03-31 ~ 2025-12-31
[GEVO]   [SARIMA] 시작  (메모리: 1583.1 MB)
[메모리] forecast_sarima 실행 전: 1583.11 MB
[메모리] find_best_sarima_params 실행 전: 1583.11 MB
[메모리] find_best_sarima_params 실행 후: 1583.11 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1583.11 MB (변화: +0.00 MB)
[GEVO]   [SARIMA] 완료  첫값=6.41e+07 (메모리: 1583.1 MB)
[GEVO]   [ETS] 시작  (메모리: 1583.1 MB)
[메모리] forecast_ets 실행 전: 1583.11 MB
[메모리] forecast_ets 실행 후: 1583.11 MB (변화: +0.00 MB)
[GEVO]   [ETS] 완료  첫값=6.38e+07 (메모리: 1583.1 MB)
[GEVO]   [Prophet] 시작  (메모리: 1583.1 MB)

11:55:07 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1583.11 MB

11:55:08 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1583.14 MB (변화: +0.03 MB)
[GEVO]   [Prophet] 완료  첫값=1.54e+07 (메모리: 1583.1 MB)
[GEVO]   [LSTM] 시작  (메모리: 1583.1 MB)
[메모리] forecast_lstm 실행 전: 1583.14 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1581.78 MB (변화: -1.37 MB)
[GEVO]   [LSTM] 완료  첫값=5.73e+07 (메모리: 1581.8 MB)
[GEVO]   [Theta] 시작  (메모리: 1581.8 MB)
[메모리] forecast_theta 실행 전: 1581.78 MB
[메모리] forecast_theta 실행 후: 1581.78 MB (변화: +0.00 MB)
[GEVO]   [Theta] 완료  첫값=6.51e+07 (메모리: 1581.8 MB)
[GEVO]   [DB] 88행 저장 완료
[PROGRESS] [ 346/500] ( 69.2%)  >>  SIGA
[SIGA]   40분기 | 2016-03-31 ~ 2025-12-31
[SIGA]   [SARIMA] 시작  (메모리: 1581.8 MB)
[메모리] forecast_sarima 실행 전: 1581.78 MB
[메모리] find_best_sarima_params 실행 전: 1581.78 MB
[메모리] find_best_sarima_params 실행 후: 1581.78 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1581.78 MB (변화: +0.00 MB)
[SIGA]   [SARIMA] 완료  첫값=1.19e+07 (메모리: 1581.8 MB)
[SIGA]   [ETS] 시작  (메모리: 1581.8 MB)
[메모리] forecast_ets 실행 전: 1581.78 MB
[메모리] forecast_ets 실행 후: 1581.78 MB (변화: +0.00 MB)
[SIGA]   [ETS] 완료  첫값=1.60e+07 (메모리: 1581.8 MB)
[SIGA]   [Prophet] 시작  (메모리: 1581.8 MB)

11:55:25 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1581.78 MB

11:55:26 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1581.79 MB (변화: +0.01 MB)
[SIGA]   [Prophet] 완료  첫값=3.66e+07 (메모리: 1581.8 MB)
[SIGA]   [LSTM] 시작  (메모리: 1581.8 MB)
[메모리] forecast_lstm 실행 전: 1581.79 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1582.72 MB (변화: +0.93 MB)
[SIGA]   [LSTM] 완료  첫값=3.08e+07 (메모리: 1582.7 MB)
[SIGA]   [Theta] 시작  (메모리: 1582.7 MB)
[메모리] forecast_theta 실행 전: 1582.72 MB
[메모리] forecast_theta 실행 후: 1582.72 MB (변화: +0.00 MB)
[SIGA]   [Theta] 완료  첫값=1.41e+07 (메모리: 1582.7 MB)
[SIGA]   [DB] 88행 저장 완료
[PROGRESS] [ 347/500] ( 69.4%)  >>  CHCT
[CHCT]   40분기 | 2016-03-31 ~ 2025-12-31
[CHCT]   [SARIMA] 시작  (메모리: 1582.7 MB)
[메모리] forecast_sarima 실행 전: 1582.72 MB
[메모리] find_best_sarima_params 실행 전: 1582.72 MB
[메모리] find_best_sarima_params 실행 후: 1582.72 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1582.72 MB (변화: +0.00 MB)
[CHCT]   [SARIMA] 완료  첫값=3.12e+07 (메모리: 1582.7 MB)
[CHCT]   [ETS] 시작  (메모리: 1582.7 MB)
[메모리] forecast_ets 실행 전: 1582.72 MB
[메모리] forecast_ets 실행 후: 1582.73 MB (변화: +0.01 MB)
[CHCT]   [ETS] 완료  첫값=3.15e+07 (메모리: 1582.7 MB)
[CHCT]   [Prophet] 시작  (메모리: 1582.7 MB)

11:55:42 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1582.73 MB

11:55:42 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1582.75 MB (변화: +0.02 MB)
[CHCT]   [Prophet] 완료  첫값=3.13e+07 (메모리: 1582.8 MB)
[CHCT]   [LSTM] 시작  (메모리: 1582.8 MB)
[메모리] forecast_lstm 실행 전: 1582.75 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1582.48 MB (변화: -0.28 MB)
[CHCT]   [LSTM] 완료  첫값=3.15e+07 (메모리: 1582.5 MB)
[CHCT]   [Theta] 시작  (메모리: 1582.5 MB)
[메모리] forecast_theta 실행 전: 1582.48 MB
[메모리] forecast_theta 실행 후: 1582.48 MB (변화: +0.00 MB)
[CHCT]   [Theta] 완료  첫값=3.19e+07 (메모리: 1582.5 MB)
[CHCT]   [DB] 88행 저장 완료
[PROGRESS] [ 348/500] ( 69.6%)  >>  HT
[HT]   40분기 | 2013-12-31 ~ 2023-09-30
[HT]   [SARIMA] 시작  (메모리: 1582.5 MB)
[메모리] forecast_sarima 실행 전: 1582.48 MB
[메모리] find_best_sarima_params 실행 전: 1582.48 MB
[메모리] find_best_sarima_params 실행 후: 1582.48 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1582.48 MB (변화: +0.00 MB)
[HT]   [SARIMA] 완료  첫값=9.20e+07 (메모리: 1582.5 MB)
[HT]   [ETS] 시작  (메모리: 1582.5 MB)
[메모리] forecast_ets 실행 전: 1582.48 MB
[메모리] forecast_ets 실행 후: 1582.48 MB (변화: +0.00 MB)
[HT]   [ETS] 완료  첫값=9.24e+07 (메모리: 1582.5 MB)
[HT]   [Prophet] 시작  (메모리: 1582.5 MB)

11:55:57 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1582.48 MB

11:55:57 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1582.86 MB (변화: +0.38 MB)
[HT]   [Prophet] 완료  첫값=8.40e+07 (메모리: 1582.9 MB)
[HT]   [LSTM] 시작  (메모리: 1582.9 MB)
[메모리] forecast_lstm 실행 전: 1582.86 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1582.59 MB (변화: -0.27 MB)
[HT]   [LSTM] 완료  첫값=7.96e+07 (메모리: 1582.6 MB)
[HT]   [Theta] 시작  (메모리: 1582.6 MB)
[메모리] forecast_theta 실행 전: 1582.59 MB
[메모리] forecast_theta 실행 후: 1582.59 MB (변화: +0.00 MB)
[HT]   [Theta] 완료  첫값=9.17e+07 (메모리: 1582.6 MB)
[HT]   [DB] 88행 저장 완료
[PROGRESS] [ 349/500] ( 69.8%)  >>  CLNE
[CLNE]   40분기 | 2016-03-31 ~ 2025-12-31
[CLNE]   [SARIMA] 시작  (메모리: 1582.6 MB)
[메모리] forecast_sarima 실행 전: 1582.59 MB
[메모리] find_best_sarima_params 실행 전: 1582.59 MB
[메모리] find_best_sarima_params 실행 후: 1582.59 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1582.59 MB (변화: +0.00 MB)
[CLNE]   [SARIMA] 완료  첫값=9.45e+07 (메모리: 1582.6 MB)
[CLNE]   [ETS] 시작  (메모리: 1582.6 MB)
[메모리] forecast_ets 실행 전: 1582.59 MB
[메모리] forecast_ets 실행 후: 1582.60 MB (변화: +0.00 MB)
[CLNE]   [ETS] 완료  첫값=1.02e+08 (메모리: 1582.6 MB)
[CLNE]   [Prophet] 시작  (메모리: 1582.6 MB)

11:56:10 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1582.60 MB

11:56:10 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1582.62 MB (변화: +0.02 MB)
[CLNE]   [Prophet] 완료  첫값=1.02e+08 (메모리: 1582.6 MB)
[CLNE]   [LSTM] 시작  (메모리: 1582.6 MB)
[메모리] forecast_lstm 실행 전: 1582.62 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1582.59 MB (변화: -0.02 MB)
[CLNE]   [LSTM] 완료  첫값=1.01e+08 (메모리: 1582.6 MB)
[CLNE]   [Theta] 시작  (메모리: 1582.6 MB)
[메모리] forecast_theta 실행 전: 1582.59 MB
[메모리] forecast_theta 실행 후: 1582.59 MB (변화: +0.00 MB)
[CLNE]   [Theta] 완료  첫값=9.75e+07 (메모리: 1582.6 MB)
[CLNE]   [DB] 88행 저장 완료
[PROGRESS] [ 350/500] ( 70.0%)  >>  MITK
[MITK]   40분기 | 2016-03-31 ~ 2025-12-31
[MITK]   [SARIMA] 시작  (메모리: 1582.6 MB)
[메모리] forecast_sarima 실행 전: 1582.59 MB
[메모리] find_best_sarima_params 실행 전: 1582.59 MB
[메모리] find_best_sarima_params 실행 후: 1582.59 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1582.59 MB (변화: +0.00 MB)
[MITK]   [SARIMA] 완료  첫값=5.55e+07 (메모리: 1582.6 MB)
[MITK]   [ETS] 시작  (메모리: 1582.6 MB)
[메모리] forecast_ets 실행 전: 1582.59 MB
[메모리] forecast_ets 실행 후: 1582.60 MB (변화: +0.00 MB)
[MITK]   [ETS] 완료  첫값=4.80e+07 (메모리: 1582.6 MB)
[MITK]   [Prophet] 시작  (메모리: 1582.6 MB)

11:56:26 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1582.60 MB

11:56:26 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1582.62 MB (변화: +0.02 MB)
[MITK]   [Prophet] 완료  첫값=5.12e+07 (메모리: 1582.6 MB)
[MITK]   [LSTM] 시작  (메모리: 1582.6 MB)
[메모리] forecast_lstm 실행 전: 1582.62 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1582.84 MB (변화: +0.23 MB)
[MITK]   [LSTM] 완료  첫값=4.56e+07 (메모리: 1582.8 MB)
[MITK]   [Theta] 시작  (메모리: 1582.8 MB)
[메모리] forecast_theta 실행 전: 1582.84 MB
[메모리] forecast_theta 실행 후: 1582.84 MB (변화: +0.00 MB)
[MITK]   [Theta] 완료  첫값=4.98e+07 (메모리: 1582.8 MB)
[MITK]   [DB] 88행 저장 완료
[PROGRESS] [ 351/500] ( 70.2%)  >>  ORN
[ORN]   40분기 | 2016-03-31 ~ 2025-12-31
[ORN]   [SARIMA] 시작  (메모리: 1582.8 MB)
[메모리] forecast_sarima 실행 전: 1582.84 MB
[메모리] find_best_sarima_params 실행 전: 1582.84 MB
[메모리] find_best_sarima_params 실행 후: 1582.84 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1582.84 MB (변화: +0.00 MB)
[ORN]   [SARIMA] 완료  첫값=2.16e+08 (메모리: 1582.8 MB)
[ORN]   [ETS] 시작  (메모리: 1582.8 MB)
[메모리] forecast_ets 실행 전: 1582.84 MB
[메모리] forecast_ets 실행 후: 1582.85 MB (변화: +0.00 MB)
[ORN]   [ETS] 완료  첫값=2.14e+08 (메모리: 1582.8 MB)
[ORN]   [Prophet] 시작  (메모리: 1582.8 MB)

11:56:42 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1582.85 MB

11:56:42 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1582.13 MB (변화: -0.71 MB)
[ORN]   [Prophet] 완료  첫값=2.10e+08 (메모리: 1582.1 MB)
[ORN]   [LSTM] 시작  (메모리: 1582.1 MB)
[메모리] forecast_lstm 실행 전: 1582.13 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1584.34 MB (변화: +2.21 MB)
[ORN]   [LSTM] 완료  첫값=2.03e+08 (메모리: 1584.3 MB)
[ORN]   [Theta] 시작  (메모리: 1584.3 MB)
[메모리] forecast_theta 실행 전: 1584.34 MB
[메모리] forecast_theta 실행 후: 1584.34 MB (변화: +0.00 MB)
[ORN]   [Theta] 완료  첫값=2.30e+08 (메모리: 1584.3 MB)
[ORN]   [DB] 88행 저장 완료
[PROGRESS] [ 352/500] ( 70.4%)  >>  ASC
[ASC]   40분기 | 2016-03-31 ~ 2025-12-31
[ASC]   [SARIMA] 시작  (메모리: 1584.3 MB)
[메모리] forecast_sarima 실행 전: 1584.34 MB
[메모리] find_best_sarima_params 실행 전: 1584.34 MB
[메모리] find_best_sarima_params 실행 후: 1584.34 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1584.34 MB (변화: +0.00 MB)
[ASC]   [SARIMA] 완료  첫값=8.31e+07 (메모리: 1584.3 MB)
[ASC]   [ETS] 시작  (메모리: 1584.3 MB)
[메모리] forecast_ets 실행 전: 1584.34 MB
[메모리] forecast_ets 실행 후: 1584.35 MB (변화: +0.00 MB)
[ASC]   [ETS] 완료  첫값=8.73e+07 (메모리: 1584.3 MB)
[ASC]   [Prophet] 시작  (메모리: 1584.3 MB)

11:56:57 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1584.35 MB

11:56:58 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1584.00 MB (변화: -0.34 MB)
[ASC]   [Prophet] 완료  첫값=1.03e+08 (메모리: 1584.0 MB)
[ASC]   [LSTM] 시작  (메모리: 1584.0 MB)
[메모리] forecast_lstm 실행 전: 1584.00 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1584.98 MB (변화: +0.98 MB)
[ASC]   [LSTM] 완료  첫값=8.02e+07 (메모리: 1585.0 MB)
[ASC]   [Theta] 시작  (메모리: 1585.0 MB)
[메모리] forecast_theta 실행 전: 1584.98 MB
[메모리] forecast_theta 실행 후: 1584.98 MB (변화: +0.00 MB)
[ASC]   [Theta] 완료  첫값=8.68e+07 (메모리: 1585.0 MB)
[ASC]   [DB] 88행 저장 완료
[PROGRESS] [ 353/500] ( 70.6%)  >>  PKE
[PKE]   40분기 | 2016-02-28 ~ 2025-11-30
[PKE]   [SARIMA] 시작  (메모리: 1585.0 MB)
[메모리] forecast_sarima 실행 전: 1584.98 MB
[메모리] find_best_sarima_params 실행 전: 1584.98 MB
[메모리] find_best_sarima_params 실행 후: 1584.98 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1584.98 MB (변화: +0.00 MB)
[PKE]   [SARIMA] 완료  첫값=1.85e+07 (메모리: 1585.0 MB)
[PKE]   [ETS] 시작  (메모리: 1585.0 MB)
[메모리] forecast_ets 실행 전: 1584.98 MB
[메모리] forecast_ets 실행 후: 1584.99 MB (변화: +0.00 MB)
[PKE]   [ETS] 완료  첫값=1.86e+07 (메모리: 1585.0 MB)
[PKE]   [Prophet] 시작  (메모리: 1585.0 MB)

11:57:16 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1584.99 MB

11:57:16 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1585.03 MB (변화: +0.04 MB)
[PKE]   [Prophet] 완료  첫값=1.00e+07 (메모리: 1585.0 MB)
[PKE]   [LSTM] 시작  (메모리: 1585.0 MB)
[메모리] forecast_lstm 실행 전: 1585.03 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1584.45 MB (변화: -0.57 MB)
[PKE]   [LSTM] 완료  첫값=1.43e+07 (메모리: 1584.5 MB)
[PKE]   [Theta] 시작  (메모리: 1584.5 MB)
[메모리] forecast_theta 실행 전: 1584.45 MB
[메모리] forecast_theta 실행 후: 1584.45 MB (변화: +0.00 MB)
[PKE]   [Theta] 완료  첫값=1.90e+07 (메모리: 1584.5 MB)
[PKE]   [DB] 88행 저장 완료
[PROGRESS] [ 354/500] ( 70.8%)  >>  JOUT
[JOUT]   40분기 | 2016-04-01 ~ 2026-01-02
[JOUT]   [SARIMA] 시작  (메모리: 1584.5 MB)
[메모리] forecast_sarima 실행 전: 1584.45 MB
[메모리] find_best_sarima_params 실행 전: 1584.45 MB
[메모리] find_best_sarima_params 실행 후: 1584.45 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1584.45 MB (변화: +0.00 MB)
[JOUT]   [SARIMA] 완료  첫값=1.71e+08 (메모리: 1584.5 MB)
[JOUT]   [ETS] 시작  (메모리: 1584.5 MB)
[메모리] forecast_ets 실행 전: 1584.45 MB
[메모리] forecast_ets 실행 후: 1584.46 MB (변화: +0.00 MB)
[JOUT]   [ETS] 완료  첫값=1.91e+08 (메모리: 1584.5 MB)
[JOUT]   [Prophet] 시작  (메모리: 1584.5 MB)

11:57:35 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1584.46 MB

11:57:35 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1584.47 MB (변화: +0.01 MB)
[JOUT]   [Prophet] 완료  첫값=1.71e+08 (메모리: 1584.5 MB)
[JOUT]   [LSTM] 시작  (메모리: 1584.5 MB)
[메모리] forecast_lstm 실행 전: 1584.47 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1585.41 MB (변화: +0.94 MB)
[JOUT]   [LSTM] 완료  첫값=1.47e+08 (메모리: 1585.4 MB)
[JOUT]   [Theta] 시작  (메모리: 1585.4 MB)
[메모리] forecast_theta 실행 전: 1585.41 MB
[메모리] forecast_theta 실행 후: 1585.41 MB (변화: +0.00 MB)
[JOUT]   [Theta] 완료  첫값=1.91e+08 (메모리: 1585.4 MB)
[JOUT]   [DB] 88행 저장 완료
[PROGRESS] [ 355/500] ( 71.0%)  >>  MCS
[MCS]   40분기 | 2016-03-31 ~ 2025-12-31
[MCS]   [SARIMA] 시작  (메모리: 1585.4 MB)
[메모리] forecast_sarima 실행 전: 1585.41 MB
[메모리] find_best_sarima_params 실행 전: 1585.41 MB
[메모리] find_best_sarima_params 실행 후: 1585.41 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1585.41 MB (변화: +0.00 MB)
[MCS]   [SARIMA] 완료  첫값=2.13e+08 (메모리: 1585.4 MB)
[MCS]   [ETS] 시작  (메모리: 1585.4 MB)
[메모리] forecast_ets 실행 전: 1585.41 MB
[메모리] forecast_ets 실행 후: 1585.41 MB (변화: +0.00 MB)
[MCS]   [ETS] 완료  첫값=1.86e+08 (메모리: 1585.4 MB)
[MCS]   [Prophet] 시작  (메모리: 1585.4 MB)

11:57:49 - cmdstanpy - INFO - Chain [1] start processing
11:57:49 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1585.41 MB
[메모리] forecast_prophet 실행 후: 1585.43 MB (변화: +0.01 MB)
[MCS]   [Prophet] 완료  첫값=1.79e+08 (메모리: 1585.4 MB)
[MCS]   [LSTM] 시작  (메모리: 1585.4 MB)
[메모리] forecast_lstm 실행 전: 1585.43 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1585.80 MB (변화: +0.38 MB)
[MCS]   [LSTM] 완료  첫값=2.20e+08 (메모리: 1585.8 MB)
[MCS]   [Theta] 시작  (메모리: 1585.8 MB)
[메모리] forecast_theta 실행 전: 1585.80 MB
[메모리] forecast_theta 실행 후: 1585.80 MB (변화: +0.00 MB)
[MCS]   [Theta] 완료  첫값=1.98e+08 (메모리: 1585.8 MB)
[MCS]   [DB] 88행 저장 완료
[PROGRESS] [ 356/500] ( 71.2%)  >>  CODI
[CODI]   40분기 | 2016-03-31 ~ 2025-12-31
[CODI]   [SARIMA] 시작  (메모리: 1585.8 MB)
[메모리] forecast_sarima 실행 전: 1585.80 MB
[메모리] find_best_sarima_params 실행 전: 1585.80 MB
[메모리] find_best_sarima_params 실행 후: 1585.80 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1585.80 MB (변화: +0.00 MB)
[CODI]   [SARIMA] 완료  첫값=4.32e+08 (메모리: 1585.8 MB)
[CODI]   [ETS] 시작  (메모리: 1585.8 MB)
[메모리] forecast_ets 실행 전: 1585.80 MB
[메모리] forecast_ets 실행 후: 1585.81 MB (변화: +0.00 MB)
[CODI]   [ETS] 완료  첫값=4.22e+08 (메모리: 1585.8 MB)
[CODI]   [Prophet] 시작  (메모리: 1585.8 MB)

11:58:04 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1585.81 MB

11:58:04 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1585.83 MB (변화: +0.02 MB)
[CODI]   [Prophet] 완료  첫값=5.52e+08 (메모리: 1585.8 MB)
[CODI]   [LSTM] 시작  (메모리: 1585.8 MB)
[메모리] forecast_lstm 실행 전: 1585.83 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1585.80 MB (변화: -0.03 MB)
[CODI]   [LSTM] 완료  첫값=4.87e+08 (메모리: 1585.8 MB)
[CODI]   [Theta] 시작  (메모리: 1585.8 MB)
[메모리] forecast_theta 실행 전: 1585.80 MB
[메모리] forecast_theta 실행 후: 1585.80 MB (변화: +0.00 MB)
[CODI]   [Theta] 완료  첫값=4.15e+08 (메모리: 1585.8 MB)
[CODI]   [DB] 88행 저장 완료
[PROGRESS] [ 357/500] ( 71.4%)  >>  CERS
[CERS]   40분기 | 2016-03-31 ~ 2025-12-31
[CERS]   [SARIMA] 시작  (메모리: 1585.8 MB)
[메모리] forecast_sarima 실행 전: 1585.80 MB
[메모리] find_best_sarima_params 실행 전: 1585.80 MB
[메모리] find_best_sarima_params 실행 후: 1585.80 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1585.80 MB (변화: +0.00 MB)
[CERS]   [SARIMA] 완료  첫값=4.72e+07 (메모리: 1585.8 MB)
[CERS]   [ETS] 시작  (메모리: 1585.8 MB)
[메모리] forecast_ets 실행 전: 1585.80 MB
[메모리] forecast_ets 실행 후: 1585.81 MB (변화: +0.01 MB)
[CERS]   [ETS] 완료  첫값=4.86e+07 (메모리: 1585.8 MB)
[CERS]   [Prophet] 시작  (메모리: 1585.8 MB)

11:58:20 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1585.81 MB

11:58:20 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1585.47 MB (변화: -0.34 MB)
[CERS]   [Prophet] 완료  첫값=5.42e+07 (메모리: 1585.5 MB)
[CERS]   [LSTM] 시작  (메모리: 1585.5 MB)
[메모리] forecast_lstm 실행 전: 1585.47 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1585.36 MB (변화: -0.11 MB)
[CERS]   [LSTM] 완료  첫값=5.02e+07 (메모리: 1585.4 MB)
[CERS]   [Theta] 시작  (메모리: 1585.4 MB)
[메모리] forecast_theta 실행 전: 1585.36 MB
[메모리] forecast_theta 실행 후: 1585.36 MB (변화: +0.00 MB)
[CERS]   [Theta] 완료  첫값=4.69e+07 (메모리: 1585.4 MB)
[CERS]   [DB] 88행 저장 완료
[PROGRESS] [ 358/500] ( 71.6%)  >>  NRC
[NRC]   40분기 | 2016-03-31 ~ 2025-12-31
[NRC]   [SARIMA] 시작  (메모리: 1585.4 MB)
[메모리] forecast_sarima 실행 전: 1585.36 MB
[메모리] find_best_sarima_params 실행 전: 1585.36 MB
[메모리] find_best_sarima_params 실행 후: 1585.36 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1585.36 MB (변화: +0.00 MB)
[NRC]   [SARIMA] 완료  첫값=3.33e+07 (메모리: 1585.4 MB)
[NRC]   [ETS] 시작  (메모리: 1585.4 MB)
[메모리] forecast_ets 실행 전: 1585.36 MB
[메모리] forecast_ets 실행 후: 1585.37 MB (변화: +0.00 MB)
[NRC]   [ETS] 완료  첫값=3.24e+07 (메모리: 1585.4 MB)
[NRC]   [Prophet] 시작  (메모리: 1585.4 MB)

11:58:38 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1585.37 MB

11:58:38 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1585.38 MB (변화: +0.01 MB)
[NRC]   [Prophet] 완료  첫값=3.48e+07 (메모리: 1585.4 MB)
[NRC]   [LSTM] 시작  (메모리: 1585.4 MB)
[메모리] forecast_lstm 실행 전: 1585.38 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.35 MB (변화: +0.97 MB)
[NRC]   [LSTM] 완료  첫값=3.55e+07 (메모리: 1586.3 MB)
[NRC]   [Theta] 시작  (메모리: 1586.3 MB)
[메모리] forecast_theta 실행 전: 1586.35 MB
[메모리] forecast_theta 실행 후: 1586.35 MB (변화: +0.00 MB)
[NRC]   [Theta] 완료  첫값=3.50e+07 (메모리: 1586.3 MB)
[NRC]   [DB] 88행 저장 완료
[PROGRESS] [ 359/500] ( 71.8%)  >>  BBBY
[BBBY]   40분기 | 2015-08-29 ~ 2025-12-31
[BBBY]   [SARIMA] 시작  (메모리: 1586.3 MB)
[메모리] forecast_sarima 실행 전: 1586.35 MB
[메모리] find_best_sarima_params 실행 전: 1586.35 MB
[메모리] find_best_sarima_params 실행 후: 1586.35 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.35 MB (변화: +0.00 MB)
[BBBY]   [SARIMA] 완료  첫값=2.77e+08 (메모리: 1586.3 MB)
[BBBY]   [ETS] 시작  (메모리: 1586.3 MB)
[메모리] forecast_ets 실행 전: 1586.35 MB
[메모리] forecast_ets 실행 후: 1586.35 MB (변화: +0.00 MB)
[BBBY]   [ETS] 완료  첫값=3.04e+08 (메모리: 1586.4 MB)
[BBBY]   [Prophet] 시작  (메모리: 1586.4 MB)

11:58:52 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1586.35 MB

11:58:52 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1586.38 MB (변화: +0.03 MB)
[BBBY]   [Prophet] 완료  첫값=-3.60e+08 (메모리: 1586.4 MB)
[BBBY]   [LSTM] 시작  (메모리: 1586.4 MB)
[메모리] forecast_lstm 실행 전: 1586.38 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1585.30 MB (변화: -1.08 MB)
[BBBY]   [LSTM] 완료  첫값=4.62e+08 (메모리: 1585.3 MB)
[BBBY]   [Theta] 시작  (메모리: 1585.3 MB)
[메모리] forecast_theta 실행 전: 1585.30 MB
[메모리] forecast_theta 실행 후: 1585.30 MB (변화: +0.00 MB)
[BBBY]   [Theta] 완료  첫값=3.13e+08 (메모리: 1585.3 MB)
[BBBY]   [DB] 88행 저장 완료
[PROGRESS] [ 360/500] ( 72.0%)  >>  IMMP
[IMMP] [NEG-SKIP] [IMMP] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2016, 6, 30)])
[PROGRESS] [ 361/500] ( 72.2%)  >>  MTW
[MTW]   40분기 | 2016-03-31 ~ 2025-12-31
[MTW]   [SARIMA] 시작  (메모리: 1585.3 MB)
[메모리] forecast_sarima 실행 전: 1585.30 MB
[메모리] find_best_sarima_params 실행 전: 1585.30 MB
[메모리] find_best_sarima_params 실행 후: 1585.30 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1585.30 MB (변화: +0.00 MB)
[MTW]   [SARIMA] 완료  첫값=5.46e+08 (메모리: 1585.3 MB)
[MTW]   [ETS] 시작  (메모리: 1585.3 MB)
[메모리] forecast_ets 실행 전: 1585.30 MB
[메모리] forecast_ets 실행 후: 1585.30 MB (변화: +0.00 MB)
[MTW]   [ETS] 완료  첫값=5.49e+08 (메모리: 1585.3 MB)
[MTW]   [Prophet] 시작  (메모리: 1585.3 MB)

11:59:14 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1585.30 MB

11:59:14 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1585.32 MB (변화: +0.02 MB)
[MTW]   [Prophet] 완료  첫값=5.70e+08 (메모리: 1585.3 MB)
[MTW]   [LSTM] 시작  (메모리: 1585.3 MB)
[메모리] forecast_lstm 실행 전: 1585.32 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.29 MB (변화: +0.96 MB)
[MTW]   [LSTM] 완료  첫값=5.48e+08 (메모리: 1586.3 MB)
[MTW]   [Theta] 시작  (메모리: 1586.3 MB)
[메모리] forecast_theta 실행 전: 1586.29 MB
[메모리] forecast_theta 실행 후: 1586.29 MB (변화: +0.00 MB)
[MTW]   [Theta] 완료  첫값=5.46e+08 (메모리: 1586.3 MB)
[MTW]   [DB] 88행 저장 완료
[PROGRESS] [ 362/500] ( 72.4%)  >>  KOPN
[KOPN]   40분기 | 2015-12-31 ~ 2025-09-27
[KOPN]   [SARIMA] 시작  (메모리: 1586.3 MB)
[메모리] forecast_sarima 실행 전: 1586.29 MB
[메모리] find_best_sarima_params 실행 전: 1586.29 MB
[메모리] find_best_sarima_params 실행 후: 1586.29 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.29 MB (변화: +0.00 MB)
[KOPN]   [SARIMA] 완료  첫값=1.27e+07 (메모리: 1586.3 MB)
[KOPN]   [ETS] 시작  (메모리: 1586.3 MB)
[메모리] forecast_ets 실행 전: 1586.29 MB
[메모리] forecast_ets 실행 후: 1586.29 MB (변화: +0.00 MB)
[KOPN]   [ETS] 완료  첫값=1.40e+07 (메모리: 1586.3 MB)
[KOPN]   [Prophet] 시작  (메모리: 1586.3 MB)

11:59:29 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1586.29 MB

11:59:29 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1586.32 MB (변화: +0.02 MB)
[KOPN]   [Prophet] 완료  첫값=1.29e+07 (메모리: 1586.3 MB)
[KOPN]   [LSTM] 시작  (메모리: 1586.3 MB)
[메모리] forecast_lstm 실행 전: 1586.32 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.28 MB (변화: -0.04 MB)
[KOPN]   [LSTM] 완료  첫값=1.10e+07 (메모리: 1586.3 MB)
[KOPN]   [Theta] 시작  (메모리: 1586.3 MB)
[메모리] forecast_theta 실행 전: 1586.28 MB
[메모리] forecast_theta 실행 후: 1586.28 MB (변화: +0.00 MB)
[KOPN]   [Theta] 완료  첫값=1.36e+07 (메모리: 1586.3 MB)
[KOPN]   [DB] 88행 저장 완료
[PROGRESS] [ 363/500] ( 72.6%)  >>  SVA
[SVA]   40분기 | 2012-03-31 ~ 2023-12-31
[SVA]   [SARIMA] 시작  (메모리: 1586.3 MB)
[메모리] forecast_sarima 실행 전: 1586.28 MB
[메모리] find_best_sarima_params 실행 전: 1586.28 MB
[메모리] find_best_sarima_params 실행 후: 1586.28 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.28 MB (변화: +0.00 MB)
[SVA]   [SARIMA] 완료  첫값=5.25e+08 (메모리: 1586.3 MB)
[SVA]   [ETS] 시작  (메모리: 1586.3 MB)
[메모리] forecast_ets 실행 전: 1586.28 MB
[메모리] forecast_ets 실행 후: 1586.29 MB (변화: +0.00 MB)
[SVA]   [ETS] 완료  첫값=2.08e+08 (메모리: 1586.3 MB)
[SVA]   [Prophet] 시작  (메모리: 1586.3 MB)

11:59:42 - cmdstanpy - INFO - Chain [1] start processing
11:59:42 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1586.29 MB
[메모리] forecast_prophet 실행 후: 1586.32 MB (변화: +0.03 MB)
[SVA]   [Prophet] 완료  첫값=2.00e+09 (메모리: 1586.3 MB)
[SVA]   [LSTM] 시작  (메모리: 1586.3 MB)
[메모리] forecast_lstm 실행 전: 1586.32 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.28 MB (변화: -0.04 MB)
[SVA]   [LSTM] 완료  첫값=-5.67e+08 (메모리: 1586.3 MB)
[SVA]   [Theta] 시작  (메모리: 1586.3 MB)
[메모리] forecast_theta 실행 전: 1586.28 MB
[메모리] forecast_theta 실행 후: 1586.28 MB (변화: +0.00 MB)
[SVA]   [Theta] 완료  첫값=3.23e+08 (메모리: 1586.3 MB)
[SVA]   [DB] 88행 저장 완료
[PROGRESS] [ 364/500] ( 72.8%)  >>  MLR
[MLR]   40분기 | 2016-03-31 ~ 2025-12-31
[MLR]   [SARIMA] 시작  (메모리: 1586.3 MB)
[메모리] forecast_sarima 실행 전: 1586.28 MB
[메모리] find_best_sarima_params 실행 전: 1586.28 MB
[메모리] find_best_sarima_params 실행 후: 1586.28 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.28 MB (변화: +0.00 MB)
[MLR]   [SARIMA] 완료  첫값=1.64e+08 (메모리: 1586.3 MB)
[MLR]   [ETS] 시작  (메모리: 1586.3 MB)
[메모리] forecast_ets 실행 전: 1586.28 MB
[메모리] forecast_ets 실행 후: 1586.28 MB (변화: +0.00 MB)
[MLR]   [ETS] 완료  첫값=1.78e+08 (메모리: 1586.3 MB)
[MLR]   [Prophet] 시작  (메모리: 1586.3 MB)

12:00:02 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1586.28 MB

12:00:02 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1585.30 MB (변화: -0.98 MB)
[MLR]   [Prophet] 완료  첫값=2.69e+08 (메모리: 1585.3 MB)
[MLR]   [LSTM] 시작  (메모리: 1585.3 MB)
[메모리] forecast_lstm 실행 전: 1585.30 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.55 MB (변화: +1.25 MB)
[MLR]   [LSTM] 완료  첫값=2.48e+08 (메모리: 1586.6 MB)
[MLR]   [Theta] 시작  (메모리: 1586.6 MB)
[메모리] forecast_theta 실행 전: 1586.55 MB
[메모리] forecast_theta 실행 후: 1586.55 MB (변화: +0.00 MB)
[MLR]   [Theta] 완료  첫값=1.78e+08 (메모리: 1586.6 MB)
[MLR]   [DB] 88행 저장 완료
[PROGRESS] [ 365/500] ( 73.0%)  >>  OSPN
[OSPN]   40분기 | 2016-03-31 ~ 2025-12-31
[OSPN]   [SARIMA] 시작  (메모리: 1586.6 MB)
[메모리] forecast_sarima 실행 전: 1586.55 MB
[메모리] find_best_sarima_params 실행 전: 1586.55 MB
[메모리] find_best_sarima_params 실행 후: 1586.55 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.55 MB (변화: +0.00 MB)
[OSPN]   [SARIMA] 완료  첫값=6.20e+07 (메모리: 1586.6 MB)
[OSPN]   [ETS] 시작  (메모리: 1586.6 MB)
[메모리] forecast_ets 실행 전: 1586.55 MB
[메모리] forecast_ets 실행 후: 1586.56 MB (변화: +0.00 MB)
[OSPN]   [ETS] 완료  첫값=5.71e+07 (메모리: 1586.6 MB)
[OSPN]   [Prophet] 시작  (메모리: 1586.6 MB)

12:00:18 - cmdstanpy - INFO - Chain [1] start processing
12:00:18 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1586.56 MB
[메모리] forecast_prophet 실행 후: 1586.59 MB (변화: +0.04 MB)
[OSPN]   [Prophet] 완료  첫값=6.22e+07 (메모리: 1586.6 MB)
[OSPN]   [LSTM] 시작  (메모리: 1586.6 MB)
[메모리] forecast_lstm 실행 전: 1586.59 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.57 MB (변화: -0.02 MB)
[OSPN]   [LSTM] 완료  첫값=5.93e+07 (메모리: 1586.6 MB)
[OSPN]   [Theta] 시작  (메모리: 1586.6 MB)
[메모리] forecast_theta 실행 전: 1586.57 MB
[메모리] forecast_theta 실행 후: 1586.57 MB (변화: +0.00 MB)
[OSPN]   [Theta] 완료  첫값=5.68e+07 (메모리: 1586.6 MB)
[OSPN]   [DB] 88행 저장 완료
[PROGRESS] [ 366/500] ( 73.2%)  >>  VNDA
[VNDA]   40분기 | 2016-03-31 ~ 2025-12-31
[VNDA]   [SARIMA] 시작  (메모리: 1586.6 MB)
[메모리] forecast_sarima 실행 전: 1586.57 MB
[메모리] find_best_sarima_params 실행 전: 1586.57 MB
[메모리] find_best_sarima_params 실행 후: 1586.57 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.57 MB (변화: +0.00 MB)
[VNDA]   [SARIMA] 완료  첫값=5.80e+07 (메모리: 1586.6 MB)
[VNDA]   [ETS] 시작  (메모리: 1586.6 MB)
[메모리] forecast_ets 실행 전: 1586.57 MB
[메모리] forecast_ets 실행 후: 1586.58 MB (변화: +0.00 MB)
[VNDA]   [ETS] 완료  첫값=5.45e+07 (메모리: 1586.6 MB)
[VNDA]   [Prophet] 시작  (메모리: 1586.6 MB)

12:00:34 - cmdstanpy - INFO - Chain [1] start processing
12:00:34 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1586.58 MB
[메모리] forecast_prophet 실행 후: 1586.61 MB (변화: +0.03 MB)
[VNDA]   [Prophet] 완료  첫값=6.04e+07 (메모리: 1586.6 MB)
[VNDA]   [LSTM] 시작  (메모리: 1586.6 MB)
[메모리] forecast_lstm 실행 전: 1586.61 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.20 MB (변화: -0.41 MB)
[VNDA]   [LSTM] 완료  첫값=5.01e+07 (메모리: 1586.2 MB)
[VNDA]   [Theta] 시작  (메모리: 1586.2 MB)
[메모리] forecast_theta 실행 전: 1586.20 MB
[메모리] forecast_theta 실행 후: 1586.20 MB (변화: +0.00 MB)
[VNDA]   [Theta] 완료  첫값=5.42e+07 (메모리: 1586.2 MB)
[VNDA]   [DB] 88행 저장 완료
[PROGRESS] [ 367/500] ( 73.4%)  >>  CD
[CD] [NEG-SKIP] [CD] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2018, 12, 31)])
[PROGRESS] [ 368/500] ( 73.6%)  >>  TCI
[TCI]   40분기 | 2016-03-31 ~ 2025-12-31
[TCI]   [SARIMA] 시작  (메모리: 1586.2 MB)
[메모리] forecast_sarima 실행 전: 1586.21 MB
[메모리] find_best_sarima_params 실행 전: 1586.21 MB
[메모리] find_best_sarima_params 실행 후: 1586.21 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.21 MB (변화: +0.00 MB)
[TCI]   [SARIMA] 완료  첫값=1.36e+07 (메모리: 1586.2 MB)
[TCI]   [ETS] 시작  (메모리: 1586.2 MB)
[메모리] forecast_ets 실행 전: 1586.21 MB
[메모리] forecast_ets 실행 후: 1586.21 MB (변화: +0.00 MB)
[TCI]   [ETS] 완료  첫값=1.16e+07 (메모리: 1586.2 MB)
[TCI]   [Prophet] 시작  (메모리: 1586.2 MB)

12:00:49 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1586.21 MB

12:00:50 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1586.22 MB (변화: +0.01 MB)
[TCI]   [Prophet] 완료  첫값=4.66e+06 (메모리: 1586.2 MB)
[TCI]   [LSTM] 시작  (메모리: 1586.2 MB)
[메모리] forecast_lstm 실행 전: 1586.22 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.06 MB (변화: -0.16 MB)
[TCI]   [LSTM] 완료  첫값=1.08e+07 (메모리: 1586.1 MB)
[TCI]   [Theta] 시작  (메모리: 1586.1 MB)
[메모리] forecast_theta 실행 전: 1586.06 MB
[메모리] forecast_theta 실행 후: 1586.06 MB (변화: +0.00 MB)
[TCI]   [Theta] 완료  첫값=1.18e+07 (메모리: 1586.1 MB)
[TCI]   [DB] 88행 저장 완료
[PROGRESS] [ 369/500] ( 73.8%)  >>  EMX
[EMX]   40분기 | 2015-09-30 ~ 2025-06-30
[EMX]   [SARIMA] 시작  (메모리: 1586.1 MB)
[메모리] forecast_sarima 실행 전: 1586.06 MB
[메모리] find_best_sarima_params 실행 전: 1586.06 MB
[메모리] find_best_sarima_params 실행 후: 1586.06 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.06 MB (변화: +0.00 MB)
[EMX]   [SARIMA] 완료  첫값=1.08e+07 (메모리: 1586.1 MB)
[EMX]   [ETS] 시작  (메모리: 1586.1 MB)
[메모리] forecast_ets 실행 전: 1586.06 MB
[메모리] forecast_ets 실행 후: 1586.07 MB (변화: +0.00 MB)
[EMX]   [ETS] 완료  첫값=1.06e+07 (메모리: 1586.1 MB)
[EMX]   [Prophet] 시작  (메모리: 1586.1 MB)

12:01:07 - cmdstanpy - INFO - Chain [1] start processing
12:01:07 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1586.07 MB
[메모리] forecast_prophet 실행 후: 1586.09 MB (변화: +0.02 MB)
[EMX]   [Prophet] 완료  첫값=6.63e+06 (메모리: 1586.1 MB)
[EMX]   [LSTM] 시작  (메모리: 1586.1 MB)
[메모리] forecast_lstm 실행 전: 1586.09 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.05 MB (변화: -0.03 MB)
[EMX]   [LSTM] 완료  첫값=7.58e+06 (메모리: 1586.1 MB)
[EMX]   [Theta] 시작  (메모리: 1586.1 MB)
[메모리] forecast_theta 실행 전: 1586.05 MB
[메모리] forecast_theta 실행 후: 1586.05 MB (변화: +0.00 MB)
[EMX]   [Theta] 완료  첫값=1.02e+07 (메모리: 1586.1 MB)
[EMX]   [DB] 88행 저장 완료
[PROGRESS] [ 370/500] ( 74.0%)  >>  OLP
[OLP]   40분기 | 2016-03-31 ~ 2025-12-31
[OLP]   [SARIMA] 시작  (메모리: 1586.1 MB)
[메모리] forecast_sarima 실행 전: 1586.05 MB
[메모리] find_best_sarima_params 실행 전: 1586.05 MB
[메모리] find_best_sarima_params 실행 후: 1586.05 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.05 MB (변화: +0.00 MB)
[OLP]   [SARIMA] 완료  첫값=2.44e+07 (메모리: 1586.1 MB)
[OLP]   [ETS] 시작  (메모리: 1586.1 MB)
[메모리] forecast_ets 실행 전: 1586.05 MB
[메모리] forecast_ets 실행 후: 1586.06 MB (변화: +0.00 MB)
[OLP]   [ETS] 완료  첫값=2.46e+07 (메모리: 1586.1 MB)
[OLP]   [Prophet] 시작  (메모리: 1586.1 MB)

12:01:28 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1586.06 MB

12:01:28 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1586.07 MB (변화: +0.01 MB)
[OLP]   [Prophet] 완료  첫값=2.44e+07 (메모리: 1586.1 MB)
[OLP]   [LSTM] 시작  (메모리: 1586.1 MB)
[메모리] forecast_lstm 실행 전: 1586.07 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.05 MB (변화: -0.02 MB)
[OLP]   [LSTM] 완료  첫값=2.30e+07 (메모리: 1586.1 MB)
[OLP]   [Theta] 시작  (메모리: 1586.1 MB)
[메모리] forecast_theta 실행 전: 1586.05 MB
[메모리] forecast_theta 실행 후: 1586.05 MB (변화: +0.00 MB)
[OLP]   [Theta] 완료  첫값=2.42e+07 (메모리: 1586.1 MB)
[OLP]   [DB] 88행 저장 완료
[PROGRESS] [ 371/500] ( 74.2%)  >>  OBE
[OBE]   40분기 | 2016-03-31 ~ 2025-12-31
[OBE]   [SARIMA] 시작  (메모리: 1586.1 MB)
[메모리] forecast_sarima 실행 전: 1586.05 MB
[메모리] find_best_sarima_params 실행 전: 1586.05 MB
[메모리] find_best_sarima_params 실행 후: 1586.05 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.05 MB (변화: +0.00 MB)
[OBE]   [SARIMA] 완료  첫값=1.10e+08 (메모리: 1586.1 MB)
[OBE]   [ETS] 시작  (메모리: 1586.1 MB)
[메모리] forecast_ets 실행 전: 1586.05 MB
[메모리] forecast_ets 실행 후: 1586.06 MB (변화: +0.00 MB)
[OBE]   [ETS] 완료  첫값=1.21e+08 (메모리: 1586.1 MB)
[OBE]   [Prophet] 시작  (메모리: 1586.1 MB)

12:01:44 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1586.06 MB

12:01:44 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1586.08 MB (변화: +0.02 MB)
[OBE]   [Prophet] 완료  첫값=1.83e+08 (메모리: 1586.1 MB)
[OBE]   [LSTM] 시작  (메모리: 1586.1 MB)
[메모리] forecast_lstm 실행 전: 1586.08 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1584.98 MB (변화: -1.09 MB)
[OBE]   [LSTM] 완료  첫값=1.53e+08 (메모리: 1585.0 MB)
[OBE]   [Theta] 시작  (메모리: 1585.0 MB)
[메모리] forecast_theta 실행 전: 1584.98 MB
[메모리] forecast_theta 실행 후: 1584.98 MB (변화: +0.00 MB)
[OBE]   [Theta] 완료  첫값=1.17e+08 (메모리: 1585.0 MB)
[OBE]   [DB] 88행 저장 완료
[PROGRESS] [ 372/500] ( 74.4%)  >>  SLS
[SLS]   40분기 | 2016-03-31 ~ 2025-12-31
[SLS]   [SARIMA] 시작  (메모리: 1585.0 MB)
[메모리] forecast_sarima 실행 전: 1584.98 MB
[메모리] find_best_sarima_params 실행 전: 1584.98 MB
[메모리] find_best_sarima_params 실행 후: 1584.98 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1584.98 MB (변화: +0.00 MB)
[SLS]   [SARIMA] 완료  첫값=2.60e+05 (메모리: 1585.0 MB)
[SLS]   [ETS] 시작  (메모리: 1585.0 MB)
[메모리] forecast_ets 실행 전: 1584.98 MB
[메모리] forecast_ets 실행 후: 1584.99 MB (변화: +0.00 MB)
[SLS]   [ETS] 완료  첫값=9.74e+04 (메모리: 1585.0 MB)
[SLS]   [Prophet] 시작  (메모리: 1585.0 MB)

12:02:00 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1584.99 MB

12:02:00 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1585.01 MB (변화: +0.02 MB)
[SLS]   [Prophet] 완료  첫값=2.95e+05 (메모리: 1585.0 MB)
[SLS]   [LSTM] 시작  (메모리: 1585.0 MB)
[메모리] forecast_lstm 실행 전: 1585.01 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1585.97 MB (변화: +0.96 MB)
[SLS]   [LSTM] 완료  첫값=5.85e+05 (메모리: 1586.0 MB)
[SLS]   [Theta] 시작  (메모리: 1586.0 MB)
[메모리] forecast_theta 실행 전: 1585.97 MB
[메모리] forecast_theta 실행 후: 1585.97 MB (변화: +0.00 MB)
[SLS]   [Theta] 완료  첫값=1.48e+03 (메모리: 1586.0 MB)
[SLS]   [DB] 88행 저장 완료
[PROGRESS] [ 373/500] ( 74.6%)  >>  GSS
[GSS]   40분기 | 2011-12-31 ~ 2021-09-30
[GSS]   [SARIMA] 시작  (메모리: 1586.0 MB)
[메모리] forecast_sarima 실행 전: 1585.97 MB
[메모리] find_best_sarima_params 실행 전: 1585.97 MB
[메모리] find_best_sarima_params 실행 후: 1585.97 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1585.97 MB (변화: +0.00 MB)
[GSS]   [SARIMA] 완료  첫값=6.33e+07 (메모리: 1586.0 MB)
[GSS]   [ETS] 시작  (메모리: 1586.0 MB)
[메모리] forecast_ets 실행 전: 1585.97 MB
[메모리] forecast_ets 실행 후: 1585.98 MB (변화: +0.01 MB)
[GSS]   [ETS] 완료  첫값=6.16e+07 (메모리: 1586.0 MB)
[GSS]   [Prophet] 시작  (메모리: 1586.0 MB)

12:02:19 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1585.98 MB

12:02:19 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1585.99 MB (변화: +0.02 MB)
[GSS]   [Prophet] 완료  첫값=4.96e+07 (메모리: 1586.0 MB)
[GSS]   [LSTM] 시작  (메모리: 1586.0 MB)
[메모리] forecast_lstm 실행 전: 1585.99 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.00 MB (변화: +0.00 MB)
[GSS]   [LSTM] 완료  첫값=6.86e+07 (메모리: 1586.0 MB)
[GSS]   [Theta] 시작  (메모리: 1586.0 MB)
[메모리] forecast_theta 실행 전: 1586.00 MB
[메모리] forecast_theta 실행 후: 1586.00 MB (변화: +0.00 MB)
[GSS]   [Theta] 완료  첫값=6.23e+07 (메모리: 1586.0 MB)
[GSS]   [DB] 88행 저장 완료
[PROGRESS] [ 374/500] ( 74.8%)  >>  MLAB
[MLAB]   40분기 | 2016-03-31 ~ 2025-12-31
[MLAB]   [SARIMA] 시작  (메모리: 1586.0 MB)
[메모리] forecast_sarima 실행 전: 1586.00 MB
[메모리] find_best_sarima_params 실행 전: 1586.00 MB
[메모리] find_best_sarima_params 실행 후: 1586.00 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.00 MB (변화: +0.00 MB)
[MLAB]   [SARIMA] 완료  첫값=6.64e+07 (메모리: 1586.0 MB)
[MLAB]   [ETS] 시작  (메모리: 1586.0 MB)
[메모리] forecast_ets 실행 전: 1586.00 MB
[메모리] forecast_ets 실행 후: 1586.00 MB (변화: +0.00 MB)
[MLAB]   [ETS] 완료  첫값=6.94e+07 (메모리: 1586.0 MB)
[MLAB]   [Prophet] 시작  (메모리: 1586.0 MB)

12:02:39 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1586.00 MB

12:02:39 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1586.00 MB (변화: +0.00 MB)
[MLAB]   [Prophet] 완료  첫값=6.60e+07 (메모리: 1586.0 MB)
[MLAB]   [LSTM] 시작  (메모리: 1586.0 MB)
[메모리] forecast_lstm 실행 전: 1586.00 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1585.96 MB (변화: -0.04 MB)
[MLAB]   [LSTM] 완료  첫값=6.10e+07 (메모리: 1586.0 MB)
[MLAB]   [Theta] 시작  (메모리: 1586.0 MB)
[메모리] forecast_theta 실행 전: 1585.96 MB
[메모리] forecast_theta 실행 후: 1585.96 MB (변화: +0.00 MB)
[MLAB]   [Theta] 완료  첫값=6.83e+07 (메모리: 1586.0 MB)
[MLAB]   [DB] 88행 저장 완료
[PROGRESS] [ 375/500] ( 75.0%)  >>  WOLF
[WOLF]   39분기 | 2016-06-26 ~ 2025-12-28
[WOLF]   [SARIMA] 시작  (메모리: 1586.0 MB)
[메모리] forecast_sarima 실행 전: 1585.96 MB
[메모리] find_best_sarima_params 실행 전: 1585.96 MB
[메모리] find_best_sarima_params 실행 후: 1585.96 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1585.96 MB (변화: +0.00 MB)
[WOLF]   [SARIMA] 완료  첫값=2.46e+08 (메모리: 1586.0 MB)
[WOLF]   [ETS] 시작  (메모리: 1586.0 MB)
[메모리] forecast_ets 실행 전: 1585.96 MB
[메모리] forecast_ets 실행 후: 1585.97 MB (변화: +0.01 MB)
[WOLF]   [ETS] 완료  첫값=1.79e+08 (메모리: 1586.0 MB)
[WOLF]   [Prophet] 시작  (메모리: 1586.0 MB)

12:02:52 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1585.97 MB

12:02:52 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1586.00 MB (변화: +0.03 MB)
[WOLF]   [Prophet] 완료  첫값=1.23e+08 (메모리: 1586.0 MB)
[WOLF]   [LSTM] 시작  (메모리: 1586.0 MB)
[메모리] forecast_lstm 실행 전: 1586.00 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.52 MB (변화: +0.52 MB)
[WOLF]   [LSTM] 완료  첫값=1.64e+08 (메모리: 1586.5 MB)
[WOLF]   [Theta] 시작  (메모리: 1586.5 MB)
[메모리] forecast_theta 실행 전: 1586.52 MB
[메모리] forecast_theta 실행 후: 1586.52 MB (변화: +0.00 MB)
[WOLF]   [Theta] 완료  첫값=1.74e+08 (메모리: 1586.5 MB)
[WOLF]   [DB] 87행 저장 완료
[PROGRESS] [ 376/500] ( 75.2%)  >>  MG
[MG]   40분기 | 2016-02-29 ~ 2025-12-31
[MG]   [SARIMA] 시작  (메모리: 1586.5 MB)
[메모리] forecast_sarima 실행 전: 1586.52 MB
[메모리] find_best_sarima_params 실행 전: 1586.52 MB
[메모리] find_best_sarima_params 실행 후: 1586.52 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.52 MB (변화: +0.00 MB)
[MG]   [SARIMA] 완료  첫값=1.81e+08 (메모리: 1586.5 MB)
[MG]   [ETS] 시작  (메모리: 1586.5 MB)
[메모리] forecast_ets 실행 전: 1586.52 MB
[메모리] forecast_ets 실행 후: 1586.53 MB (변화: +0.00 MB)
[MG]   [ETS] 완료  첫값=1.75e+08 (메모리: 1586.5 MB)
[MG]   [Prophet] 시작  (메모리: 1586.5 MB)

12:03:11 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1586.53 MB

12:03:12 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1586.78 MB (변화: +0.25 MB)
[MG]   [Prophet] 완료  첫값=1.77e+08 (메모리: 1586.8 MB)
[MG]   [LSTM] 시작  (메모리: 1586.8 MB)
[메모리] forecast_lstm 실행 전: 1586.78 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.50 MB (변화: -0.28 MB)
[MG]   [LSTM] 완료  첫값=1.92e+08 (메모리: 1586.5 MB)
[MG]   [Theta] 시작  (메모리: 1586.5 MB)
[메모리] forecast_theta 실행 전: 1586.50 MB
[메모리] forecast_theta 실행 후: 1586.50 MB (변화: +0.00 MB)
[MG]   [Theta] 완료  첫값=1.84e+08 (메모리: 1586.5 MB)
[MG]   [DB] 88행 저장 완료
[PROGRESS] [ 377/500] ( 75.4%)  >>  GLDG
[GLDG]   40분기 | 2016-02-29 ~ 2025-11-30
[GLDG]   [SARIMA] 시작  (메모리: 1586.5 MB)
[메모리] forecast_sarima 실행 전: 1586.50 MB
[메모리] find_best_sarima_params 실행 전: 1586.50 MB
[메모리] find_best_sarima_params 실행 후: 1586.50 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.50 MB (변화: +0.00 MB)
[GLDG]   [SARIMA] 완료  첫값=0.00e+00 (메모리: 1586.5 MB)
[GLDG]   [ETS] 시작  (메모리: 1586.5 MB)
[메모리] forecast_ets 실행 전: 1586.50 MB
[메모리] forecast_ets 실행 후: 1586.50 MB (변화: +0.00 MB)
[GLDG]   [ETS] 완료  첫값=0.00e+00 (메모리: 1586.5 MB)
[GLDG]   [Prophet] 시작  (메모리: 1586.5 MB)
[메모리] forecast_prophet 실행 전: 1586.50 MB
[메모리] forecast_prophet 실행 후: 1586.17 MB (변화: -0.34 MB)
[GLDG]   [Prophet] 완료  첫값=0.00e+00 (메모리: 1586.2 MB)
[GLDG]   [LSTM] 시작  (메모리: 1586.2 MB)
[메모리] forecast_lstm 실행 전: 1586.17 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1587.14 MB (변화: +0.97 MB)
[GLDG]   [LSTM] 완료  첫값=0.00e+00 (메모리: 1587.1 MB)
[GLDG]   [Theta] 시작  (메모리: 1587.1 MB)
[메모리] forecast_theta 실행 전: 1587.14 MB
[메모리] forecast_theta 실행 후: 1587.14 MB (변화: +0.00 MB)
[GLDG]   [Theta] 완료  첫값=0.00e+00 (메모리: 1587.1 MB)
[GLDG]   [DB] 88행 저장 완료
[PROGRESS] [ 378/500] ( 75.6%)  >>  AVXL
[AVXL]   40분기 | 2016-03-31 ~ 2025-12-31
[AVXL]   [SARIMA] 시작  (메모리: 1587.1 MB)
[메모리] forecast_sarima 실행 전: 1587.14 MB
[메모리] find_best_sarima_params 실행 전: 1587.14 MB
[메모리] find_best_sarima_params 실행 후: 1587.14 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1587.14 MB (변화: +0.00 MB)
[AVXL]   [SARIMA] 완료  첫값=0.00e+00 (메모리: 1587.1 MB)
[AVXL]   [ETS] 시작  (메모리: 1587.1 MB)
[메모리] forecast_ets 실행 전: 1587.14 MB
[메모리] forecast_ets 실행 후: 1587.14 MB (변화: +0.00 MB)
[AVXL]   [ETS] 완료  첫값=0.00e+00 (메모리: 1587.1 MB)
[AVXL]   [Prophet] 시작  (메모리: 1587.1 MB)
[메모리] forecast_prophet 실행 전: 1587.14 MB
[메모리] forecast_prophet 실행 후: 1587.16 MB (변화: +0.02 MB)
[AVXL]   [Prophet] 완료  첫값=0.00e+00 (메모리: 1587.2 MB)
[AVXL]   [LSTM] 시작  (메모리: 1587.2 MB)
[메모리] forecast_lstm 실행 전: 1587.16 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1587.13 MB (변화: -0.03 MB)
[AVXL]   [LSTM] 완료  첫값=0.00e+00 (메모리: 1587.1 MB)
[AVXL]   [Theta] 시작  (메모리: 1587.1 MB)
[메모리] forecast_theta 실행 전: 1587.13 MB
[메모리] forecast_theta 실행 후: 1587.13 MB (변화: +0.00 MB)
[AVXL]   [Theta] 완료  첫값=0.00e+00 (메모리: 1587.1 MB)
[AVXL]   [DB] 88행 저장 완료
[PROGRESS] [ 379/500] ( 75.8%)  >>  CVGW
[CVGW]   40분기 | 2016-04-30 ~ 2026-01-31
[CVGW]   [SARIMA] 시작  (메모리: 1587.1 MB)
[메모리] forecast_sarima 실행 전: 1587.13 MB
[메모리] find_best_sarima_params 실행 전: 1587.13 MB
[메모리] find_best_sarima_params 실행 후: 1587.13 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1587.13 MB (변화: +0.00 MB)
[CVGW]   [SARIMA] 완료  첫값=1.50e+08 (메모리: 1587.1 MB)
[CVGW]   [ETS] 시작  (메모리: 1587.1 MB)
[메모리] forecast_ets 실행 전: 1587.13 MB
[메모리] forecast_ets 실행 후: 1587.13 MB (변화: +0.00 MB)
[CVGW]   [ETS] 완료  첫값=1.41e+08 (메모리: 1587.1 MB)
[CVGW]   [Prophet] 시작  (메모리: 1587.1 MB)

12:04:00 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1587.13 MB

12:04:00 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1587.16 MB (변화: +0.03 MB)
[CVGW]   [Prophet] 완료  첫값=1.70e+08 (메모리: 1587.2 MB)
[CVGW]   [LSTM] 시작  (메모리: 1587.2 MB)
[메모리] forecast_lstm 실행 전: 1587.16 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1587.15 MB (변화: -0.01 MB)
[CVGW]   [LSTM] 완료  첫값=1.76e+08 (메모리: 1587.2 MB)
[CVGW]   [Theta] 시작  (메모리: 1587.2 MB)
[메모리] forecast_theta 실행 전: 1587.15 MB
[메모리] forecast_theta 실행 후: 1587.15 MB (변화: +0.00 MB)
[CVGW]   [Theta] 완료  첫값=1.42e+08 (메모리: 1587.2 MB)
[CVGW]   [DB] 88행 저장 완료
[PROGRESS] [ 380/500] ( 76.0%)  >>  GRVY
[GRVY]   40분기 | 2016-03-31 ~ 2025-12-31
[GRVY]   [SARIMA] 시작  (메모리: 1587.2 MB)
[메모리] forecast_sarima 실행 전: 1587.15 MB
[메모리] find_best_sarima_params 실행 전: 1587.15 MB
[메모리] find_best_sarima_params 실행 후: 1587.15 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1587.15 MB (변화: +0.00 MB)
[GRVY]   [SARIMA] 완료  첫값=5.26e+10 (메모리: 1587.2 MB)
[GRVY]   [ETS] 시작  (메모리: 1587.2 MB)
[메모리] forecast_ets 실행 전: 1587.15 MB
[메모리] forecast_ets 실행 후: 1587.16 MB (변화: +0.00 MB)
[GRVY]   [ETS] 완료  첫값=3.22e+10 (메모리: 1587.2 MB)
[GRVY]   [Prophet] 시작  (메모리: 1587.2 MB)

12:04:13 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1587.16 MB

12:04:14 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1587.18 MB (변화: +0.03 MB)
[GRVY]   [Prophet] 완료  첫값=1.32e+11 (메모리: 1587.2 MB)
[GRVY]   [LSTM] 시작  (메모리: 1587.2 MB)
[메모리] forecast_lstm 실행 전: 1587.18 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1587.15 MB (변화: -0.03 MB)
[GRVY]   [LSTM] 완료  첫값=1.14e+11 (메모리: 1587.2 MB)
[GRVY]   [Theta] 시작  (메모리: 1587.2 MB)
[메모리] forecast_theta 실행 전: 1587.15 MB
[메모리] forecast_theta 실행 후: 1587.15 MB (변화: +0.00 MB)
[GRVY]   [Theta] 완료  첫값=8.22e+10 (메모리: 1587.2 MB)
[GRVY]   [DB] 88행 저장 완료
[PROGRESS] [ 381/500] ( 76.2%)  >>  FRPH
[FRPH]   40분기 | 2015-12-31 ~ 2025-09-30
[FRPH]   [SARIMA] 시작  (메모리: 1587.2 MB)
[메모리] forecast_sarima 실행 전: 1587.15 MB
[메모리] find_best_sarima_params 실행 전: 1587.15 MB
[메모리] find_best_sarima_params 실행 후: 1587.15 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1587.15 MB (변화: +0.00 MB)
[FRPH]   [SARIMA] 완료  첫값=1.11e+07 (메모리: 1587.2 MB)
[FRPH]   [ETS] 시작  (메모리: 1587.2 MB)
[메모리] forecast_ets 실행 전: 1587.15 MB
[메모리] forecast_ets 실행 후: 1587.16 MB (변화: +0.00 MB)
[FRPH]   [ETS] 완료  첫값=1.07e+07 (메모리: 1587.2 MB)
[FRPH]   [Prophet] 시작  (메모리: 1587.2 MB)

12:04:29 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1587.16 MB

12:04:29 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1587.19 MB (변화: +0.03 MB)
[FRPH]   [Prophet] 완료  첫값=9.71e+06 (메모리: 1587.2 MB)
[FRPH]   [LSTM] 시작  (메모리: 1587.2 MB)
[메모리] forecast_lstm 실행 전: 1587.19 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1587.18 MB (변화: -0.01 MB)
[FRPH]   [LSTM] 완료  첫값=9.88e+06 (메모리: 1587.2 MB)
[FRPH]   [Theta] 시작  (메모리: 1587.2 MB)
[메모리] forecast_theta 실행 전: 1587.18 MB
[메모리] forecast_theta 실행 후: 1587.18 MB (변화: +0.00 MB)
[FRPH]   [Theta] 완료  첫값=1.07e+07 (메모리: 1587.2 MB)
[FRPH]   [DB] 88행 저장 완료
[PROGRESS] [ 382/500] ( 76.4%)  >>  IPI
[IPI]   40분기 | 2016-03-31 ~ 2025-12-31
[IPI]   [SARIMA] 시작  (메모리: 1587.2 MB)
[메모리] forecast_sarima 실행 전: 1587.18 MB
[메모리] find_best_sarima_params 실행 전: 1587.18 MB
[메모리] find_best_sarima_params 실행 후: 1587.18 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1587.18 MB (변화: +0.00 MB)
[IPI]   [SARIMA] 완료  첫값=1.05e+08 (메모리: 1587.2 MB)
[IPI]   [ETS] 시작  (메모리: 1587.2 MB)
[메모리] forecast_ets 실행 전: 1587.18 MB
[메모리] forecast_ets 실행 후: 1587.18 MB (변화: +0.00 MB)
[IPI]   [ETS] 완료  첫값=9.81e+07 (메모리: 1587.2 MB)
[IPI]   [Prophet] 시작  (메모리: 1587.2 MB)

12:04:48 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1587.18 MB

12:04:48 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1587.19 MB (변화: +0.01 MB)
[IPI]   [Prophet] 완료  첫값=7.71e+07 (메모리: 1587.2 MB)
[IPI]   [LSTM] 시작  (메모리: 1587.2 MB)
[메모리] forecast_lstm 실행 전: 1587.19 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.04 MB (변화: -1.15 MB)
[IPI]   [LSTM] 완료  첫값=6.89e+07 (메모리: 1586.0 MB)
[IPI]   [Theta] 시작  (메모리: 1586.0 MB)
[메모리] forecast_theta 실행 전: 1586.04 MB
[메모리] forecast_theta 실행 후: 1586.04 MB (변화: +0.00 MB)
[IPI]   [Theta] 완료  첫값=9.84e+07 (메모리: 1586.0 MB)
[IPI]   [DB] 88행 저장 완료
[PROGRESS] [ 383/500] ( 76.6%)  >>  CABO
[CABO]   40분기 | 2016-03-31 ~ 2025-12-31
[CABO]   [SARIMA] 시작  (메모리: 1586.0 MB)
[메모리] forecast_sarima 실행 전: 1586.04 MB
[메모리] find_best_sarima_params 실행 전: 1586.04 MB
[메모리] find_best_sarima_params 실행 후: 1586.04 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.04 MB (변화: +0.00 MB)
[CABO]   [SARIMA] 완료  첫값=3.69e+08 (메모리: 1586.0 MB)
[CABO]   [ETS] 시작  (메모리: 1586.0 MB)
[메모리] forecast_ets 실행 전: 1586.04 MB
[메모리] forecast_ets 실행 후: 1586.05 MB (변화: +0.00 MB)
[CABO]   [ETS] 완료  첫값=3.55e+08 (메모리: 1586.0 MB)
[CABO]   [Prophet] 시작  (메모리: 1586.0 MB)

12:05:05 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1586.05 MB

12:05:05 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1586.06 MB (변화: +0.02 MB)
[CABO]   [Prophet] 완료  첫값=3.82e+08 (메모리: 1586.1 MB)
[CABO]   [LSTM] 시작  (메모리: 1586.1 MB)
[메모리] forecast_lstm 실행 전: 1586.06 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1585.71 MB (변화: -0.35 MB)
[CABO]   [LSTM] 완료  첫값=3.97e+08 (메모리: 1585.7 MB)
[CABO]   [Theta] 시작  (메모리: 1585.7 MB)
[메모리] forecast_theta 실행 전: 1585.71 MB
[메모리] forecast_theta 실행 후: 1585.71 MB (변화: +0.00 MB)
[CABO]   [Theta] 완료  첫값=3.62e+08 (메모리: 1585.7 MB)
[CABO]   [DB] 88행 저장 완료
[PROGRESS] [ 384/500] ( 76.8%)  >>  DMAC
[DMAC] [NEG-SKIP] [DMAC] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2018, 12, 31)])
[PROGRESS] [ 385/500] ( 77.0%)  >>  LAAC
[LAAC] [NEG-SKIP] [LAAC] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2019, 12, 31)])
[PROGRESS] [ 386/500] ( 77.2%)  >>  CYH
[CYH]   40분기 | 2016-03-31 ~ 2025-12-31
[CYH]   [SARIMA] 시작  (메모리: 1585.7 MB)
[메모리] forecast_sarima 실행 전: 1585.72 MB
[메모리] find_best_sarima_params 실행 전: 1585.72 MB
[메모리] find_best_sarima_params 실행 후: 1585.72 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1585.72 MB (변화: +0.00 MB)
[CYH]   [SARIMA] 완료  첫값=3.07e+09 (메모리: 1585.7 MB)
[CYH]   [ETS] 시작  (메모리: 1585.7 MB)
[메모리] forecast_ets 실행 전: 1585.72 MB
[메모리] forecast_ets 실행 후: 1585.72 MB (변화: +0.00 MB)
[CYH]   [ETS] 완료  첫값=3.19e+09 (메모리: 1585.7 MB)
[CYH]   [Prophet] 시작  (메모리: 1585.7 MB)

12:05:28 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1585.72 MB

12:05:28 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1585.75 MB (변화: +0.03 MB)
[CYH]   [Prophet] 완료  첫값=3.12e+09 (메모리: 1585.8 MB)
[CYH]   [LSTM] 시작  (메모리: 1585.8 MB)
[메모리] forecast_lstm 실행 전: 1585.75 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1585.60 MB (변화: -0.15 MB)
[CYH]   [LSTM] 완료  첫값=3.02e+09 (메모리: 1585.6 MB)
[CYH]   [Theta] 시작  (메모리: 1585.6 MB)
[메모리] forecast_theta 실행 전: 1585.60 MB
[메모리] forecast_theta 실행 후: 1585.60 MB (변화: +0.00 MB)
[CYH]   [Theta] 완료  첫값=3.11e+09 (메모리: 1585.6 MB)
[CYH]   [DB] 88행 저장 완료
[PROGRESS] [ 387/500] ( 77.4%)  >>  ATEX
[ATEX]   40분기 | 2016-03-31 ~ 2025-12-31
[ATEX]   [SARIMA] 시작  (메모리: 1585.6 MB)
[메모리] forecast_sarima 실행 전: 1585.60 MB
[메모리] find_best_sarima_params 실행 전: 1585.60 MB
[메모리] find_best_sarima_params 실행 후: 1585.60 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1585.60 MB (변화: +0.00 MB)
[ATEX]   [SARIMA] 완료  첫값=1.57e+06 (메모리: 1585.6 MB)
[ATEX]   [ETS] 시작  (메모리: 1585.6 MB)
[메모리] forecast_ets 실행 전: 1585.60 MB
[메모리] forecast_ets 실행 후: 1585.60 MB (변화: +0.00 MB)
[ATEX]   [ETS] 완료  첫값=1.46e+06 (메모리: 1585.6 MB)
[ATEX]   [Prophet] 시작  (메모리: 1585.6 MB)

12:05:41 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1585.60 MB

12:05:42 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1585.63 MB (변화: +0.03 MB)
[ATEX]   [Prophet] 완료  첫값=9.28e+05 (메모리: 1585.6 MB)
[ATEX]   [LSTM] 시작  (메모리: 1585.6 MB)
[메모리] forecast_lstm 실행 전: 1585.63 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.59 MB (변화: +0.96 MB)
[ATEX]   [LSTM] 완료  첫값=1.11e+06 (메모리: 1586.6 MB)
[ATEX]   [Theta] 시작  (메모리: 1585.6 MB)
[메모리] forecast_theta 실행 전: 1585.55 MB
[메모리] forecast_theta 실행 후: 1585.55 MB (변화: +0.00 MB)
[ATEX]   [Theta] 완료  첫값=1.43e+06 (메모리: 1585.6 MB)
[ATEX]   [DB] 88행 저장 완료
[PROGRESS] [ 388/500] ( 77.6%)  >>  SHYF
[SHYF]   40분기 | 2015-06-30 ~ 2025-03-31
[SHYF]   [SARIMA] 시작  (메모리: 1585.6 MB)
[메모리] forecast_sarima 실행 전: 1585.55 MB
[메모리] find_best_sarima_params 실행 전: 1585.55 MB
[메모리] find_best_sarima_params 실행 후: 1585.55 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1585.55 MB (변화: +0.00 MB)
[SHYF]   [SARIMA] 완료  첫값=2.04e+08 (메모리: 1585.6 MB)
[SHYF]   [ETS] 시작  (메모리: 1585.6 MB)
[메모리] forecast_ets 실행 전: 1585.55 MB
[메모리] forecast_ets 실행 후: 1585.55 MB (변화: +0.00 MB)
[SHYF]   [ETS] 완료  첫값=2.06e+08 (메모리: 1585.6 MB)
[SHYF]   [Prophet] 시작  (메모리: 1585.6 MB)
[메모리] forecast_prophet 실행 전: 1585.55 MB

12:06:01 - cmdstanpy - INFO - Chain [1] start processing
12:06:01 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1585.93 MB (변화: +0.38 MB)
[SHYF]   [Prophet] 완료  첫값=2.43e+08 (메모리: 1585.9 MB)
[SHYF]   [LSTM] 시작  (메모리: 1585.9 MB)
[메모리] forecast_lstm 실행 전: 1585.93 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.24 MB (변화: +0.31 MB)
[SHYF]   [LSTM] 완료  첫값=2.22e+08 (메모리: 1586.2 MB)
[SHYF]   [Theta] 시작  (메모리: 1586.2 MB)
[메모리] forecast_theta 실행 전: 1586.24 MB
[메모리] forecast_theta 실행 후: 1586.24 MB (변화: +0.00 MB)
[SHYF]   [Theta] 완료  첫값=2.05e+08 (메모리: 1586.2 MB)
[SHYF]   [DB] 88행 저장 완료
[PROGRESS] [ 389/500] ( 77.8%)  >>  NETI
[NETI]   40분기 | 2013-12-31 ~ 2023-09-30
[NETI]   [SARIMA] 시작  (메모리: 1586.2 MB)
[메모리] forecast_sarima 실행 전: 1586.24 MB
[메모리] find_best_sarima_params 실행 전: 1586.24 MB
[메모리] find_best_sarima_params 실행 후: 1586.24 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.24 MB (변화: +0.00 MB)
[NETI]   [SARIMA] 완료  첫값=7.29e+07 (메모리: 1586.2 MB)
[NETI]   [ETS] 시작  (메모리: 1586.2 MB)
[메모리] forecast_ets 실행 전: 1586.24 MB
[메모리] forecast_ets 실행 후: 1586.25 MB (변화: +0.00 MB)
[NETI]   [ETS] 완료  첫값=5.37e+07 (메모리: 1586.2 MB)
[NETI]   [Prophet] 시작  (메모리: 1586.2 MB)

12:06:17 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1586.25 MB

12:06:17 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1586.27 MB (변화: +0.02 MB)
[NETI]   [Prophet] 완료  첫값=5.59e+07 (메모리: 1586.3 MB)
[NETI]   [LSTM] 시작  (메모리: 1586.3 MB)
[메모리] forecast_lstm 실행 전: 1586.27 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1585.82 MB (변화: -0.44 MB)
[NETI]   [LSTM] 완료  첫값=4.64e+07 (메모리: 1585.8 MB)
[NETI]   [Theta] 시작  (메모리: 1585.8 MB)
[메모리] forecast_theta 실행 전: 1585.82 MB
[메모리] forecast_theta 실행 후: 1585.82 MB (변화: +0.00 MB)
[NETI]   [Theta] 완료  첫값=5.23e+07 (메모리: 1585.8 MB)
[NETI]   [DB] 88행 저장 완료
[PROGRESS] [ 390/500] ( 78.0%)  >>  NOA
[NOA]   40분기 | 2016-03-31 ~ 2025-12-31
[NOA]   [SARIMA] 시작  (메모리: 1585.8 MB)
[메모리] forecast_sarima 실행 전: 1585.82 MB
[메모리] find_best_sarima_params 실행 전: 1585.82 MB
[메모리] find_best_sarima_params 실행 후: 1585.82 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1585.82 MB (변화: +0.00 MB)
[NOA]   [SARIMA] 완료  첫값=3.18e+08 (메모리: 1585.8 MB)
[NOA]   [ETS] 시작  (메모리: 1585.8 MB)
[메모리] forecast_ets 실행 전: 1585.82 MB
[메모리] forecast_ets 실행 후: 1585.83 MB (변화: +0.00 MB)
[NOA]   [ETS] 완료  첫값=3.63e+08 (메모리: 1585.8 MB)
[NOA]   [Prophet] 시작  (메모리: 1585.8 MB)

12:06:36 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1585.83 MB

12:06:36 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1586.21 MB (변화: +0.39 MB)
[NOA]   [Prophet] 완료  첫값=3.20e+08 (메모리: 1586.2 MB)
[NOA]   [LSTM] 시작  (메모리: 1586.2 MB)
[메모리] forecast_lstm 실행 전: 1586.21 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1585.84 MB (변화: -0.38 MB)
[NOA]   [LSTM] 완료  첫값=3.19e+08 (메모리: 1585.8 MB)
[NOA]   [Theta] 시작  (메모리: 1585.8 MB)
[메모리] forecast_theta 실행 전: 1585.84 MB
[메모리] forecast_theta 실행 후: 1585.84 MB (변화: +0.00 MB)
[NOA]   [Theta] 완료  첫값=3.73e+08 (메모리: 1585.8 MB)
[NOA]   [DB] 88행 저장 완료
[PROGRESS] [ 391/500] ( 78.2%)  >>  NGS
[NGS]   40분기 | 2016-03-31 ~ 2025-12-31
[NGS]   [SARIMA] 시작  (메모리: 1585.8 MB)
[메모리] forecast_sarima 실행 전: 1585.84 MB
[메모리] find_best_sarima_params 실행 전: 1585.84 MB
[메모리] find_best_sarima_params 실행 후: 1585.84 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1585.84 MB (변화: +0.00 MB)
[NGS]   [SARIMA] 완료  첫값=4.72e+07 (메모리: 1585.8 MB)
[NGS]   [ETS] 시작  (메모리: 1585.8 MB)
[메모리] forecast_ets 실행 전: 1585.84 MB
[메모리] forecast_ets 실행 후: 1585.84 MB (변화: +0.00 MB)
[NGS]   [ETS] 완료  첫값=4.94e+07 (메모리: 1585.8 MB)
[NGS]   [Prophet] 시작  (메모리: 1585.8 MB)

12:06:53 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1585.84 MB

12:06:53 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1585.85 MB (변화: +0.01 MB)
[NGS]   [Prophet] 완료  첫값=4.79e+07 (메모리: 1585.9 MB)
[NGS]   [LSTM] 시작  (메모리: 1585.9 MB)
[메모리] forecast_lstm 실행 전: 1585.85 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.82 MB (변화: +0.97 MB)
[NGS]   [LSTM] 완료  첫값=5.31e+07 (메모리: 1586.8 MB)
[NGS]   [Theta] 시작  (메모리: 1586.8 MB)
[메모리] forecast_theta 실행 전: 1586.82 MB
[메모리] forecast_theta 실행 후: 1586.82 MB (변화: +0.00 MB)
[NGS]   [Theta] 완료  첫값=4.77e+07 (메모리: 1586.8 MB)
[NGS]   [DB] 88행 저장 완료
[PROGRESS] [ 392/500] ( 78.4%)  >>  TRC
[TRC]   40분기 | 2016-03-31 ~ 2025-12-31
[TRC]   [SARIMA] 시작  (메모리: 1586.8 MB)
[메모리] forecast_sarima 실행 전: 1586.82 MB
[메모리] find_best_sarima_params 실행 전: 1586.82 MB
[메모리] find_best_sarima_params 실행 후: 1586.82 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.82 MB (변화: +0.00 MB)
[TRC]   [SARIMA] 완료  첫값=1.04e+07 (메모리: 1586.8 MB)
[TRC]   [ETS] 시작  (메모리: 1586.8 MB)
[메모리] forecast_ets 실행 전: 1586.82 MB
[메모리] forecast_ets 실행 후: 1586.83 MB (변화: +0.00 MB)
[TRC]   [ETS] 완료  첫값=1.18e+07 (메모리: 1586.8 MB)
[TRC]   [Prophet] 시작  (메모리: 1586.8 MB)

12:07:12 - cmdstanpy - INFO - Chain [1] start processing
12:07:12 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1586.83 MB
[메모리] forecast_prophet 실행 후: 1586.85 MB (변화: +0.02 MB)
[TRC]   [Prophet] 완료  첫값=1.39e+07 (메모리: 1586.9 MB)
[TRC]   [LSTM] 시작  (메모리: 1586.9 MB)
[메모리] forecast_lstm 실행 전: 1586.85 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.80 MB (변화: -0.05 MB)
[TRC]   [LSTM] 완료  첫값=1.19e+07 (메모리: 1586.8 MB)
[TRC]   [Theta] 시작  (메모리: 1586.8 MB)
[메모리] forecast_theta 실행 전: 1586.80 MB
[메모리] forecast_theta 실행 후: 1586.80 MB (변화: +0.00 MB)
[TRC]   [Theta] 완료  첫값=1.11e+07 (메모리: 1586.8 MB)
[TRC]   [DB] 88행 저장 완료
[PROGRESS] [ 393/500] ( 78.6%)  >>  FCEL
[FCEL]   40분기 | 2016-04-30 ~ 2026-01-31
[FCEL]   [SARIMA] 시작  (메모리: 1586.8 MB)
[메모리] forecast_sarima 실행 전: 1586.80 MB
[메모리] find_best_sarima_params 실행 전: 1586.80 MB
[메모리] find_best_sarima_params 실행 후: 1586.80 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.80 MB (변화: +0.00 MB)
[FCEL]   [SARIMA] 완료  첫값=3.81e+07 (메모리: 1586.8 MB)
[FCEL]   [ETS] 시작  (메모리: 1586.8 MB)
[메모리] forecast_ets 실행 전: 1586.80 MB
[메모리] forecast_ets 실행 후: 1586.80 MB (변화: +0.00 MB)
[FCEL]   [ETS] 완료  첫값=3.32e+07 (메모리: 1586.8 MB)
[FCEL]   [Prophet] 시작  (메모리: 1586.8 MB)

12:07:25 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1586.80 MB

12:07:25 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1586.81 MB (변화: +0.01 MB)
[FCEL]   [Prophet] 완료  첫값=3.41e+07 (메모리: 1586.8 MB)
[FCEL]   [LSTM] 시작  (메모리: 1586.8 MB)
[메모리] forecast_lstm 실행 전: 1586.81 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.77 MB (변화: -0.04 MB)
[FCEL]   [LSTM] 완료  첫값=3.32e+07 (메모리: 1586.8 MB)
[FCEL]   [Theta] 시작  (메모리: 1586.8 MB)
[메모리] forecast_theta 실행 전: 1586.77 MB
[메모리] forecast_theta 실행 후: 1586.77 MB (변화: +0.00 MB)
[FCEL]   [Theta] 완료  첫값=3.66e+07 (메모리: 1586.8 MB)
[FCEL]   [DB] 88행 저장 완료
[PROGRESS] [ 394/500] ( 78.8%)  >>  ALLT
[ALLT]   40분기 | 2016-03-31 ~ 2025-12-31
[ALLT]   [SARIMA] 시작  (메모리: 1586.8 MB)
[메모리] forecast_sarima 실행 전: 1586.77 MB
[메모리] find_best_sarima_params 실행 전: 1586.77 MB
[메모리] find_best_sarima_params 실행 후: 1586.77 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.77 MB (변화: +0.00 MB)
[ALLT]   [SARIMA] 완료  첫값=2.58e+07 (메모리: 1586.8 MB)
[ALLT]   [ETS] 시작  (메모리: 1586.8 MB)
[메모리] forecast_ets 실행 전: 1586.77 MB
[메모리] forecast_ets 실행 후: 1586.77 MB (변화: +0.00 MB)
[ALLT]   [ETS] 완료  첫값=2.52e+07 (메모리: 1586.8 MB)
[ALLT]   [Prophet] 시작  (메모리: 1586.8 MB)

12:07:40 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1586.77 MB

12:07:40 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1586.79 MB (변화: +0.02 MB)
[ALLT]   [Prophet] 완료  첫값=2.87e+07 (메모리: 1586.8 MB)
[ALLT]   [LSTM] 시작  (메모리: 1586.8 MB)
[메모리] forecast_lstm 실행 전: 1586.79 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.50 MB (변화: -0.29 MB)
[ALLT]   [LSTM] 완료  첫값=3.04e+07 (메모리: 1586.5 MB)
[ALLT]   [Theta] 시작  (메모리: 1586.5 MB)
[메모리] forecast_theta 실행 전: 1586.50 MB
[메모리] forecast_theta 실행 후: 1586.50 MB (변화: +0.00 MB)
[ALLT]   [Theta] 완료  첫값=2.41e+07 (메모리: 1586.5 MB)
[ALLT]   [DB] 88행 저장 완료
[PROGRESS] [ 395/500] ( 79.0%)  >>  CLFD
[CLFD]   40분기 | 2016-03-31 ~ 2025-12-31
[CLFD]   [SARIMA] 시작  (메모리: 1586.5 MB)
[메모리] forecast_sarima 실행 전: 1586.50 MB
[메모리] find_best_sarima_params 실행 전: 1586.50 MB
[메모리] find_best_sarima_params 실행 후: 1586.50 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.50 MB (변화: +0.00 MB)
[CLFD]   [SARIMA] 완료  첫값=6.23e+07 (메모리: 1586.5 MB)
[CLFD]   [ETS] 시작  (메모리: 1586.5 MB)
[메모리] forecast_ets 실행 전: 1586.50 MB
[메모리] forecast_ets 실행 후: 1586.50 MB (변화: +0.00 MB)
[CLFD]   [ETS] 완료  첫값=3.11e+07 (메모리: 1586.5 MB)
[CLFD]   [Prophet] 시작  (메모리: 1586.5 MB)

12:07:59 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1586.50 MB

12:07:59 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1587.49 MB (변화: +0.99 MB)
[CLFD]   [Prophet] 완료  첫값=5.59e+07 (메모리: 1587.5 MB)
[CLFD]   [LSTM] 시작  (메모리: 1587.5 MB)
[메모리] forecast_lstm 실행 전: 1587.49 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.82 MB (변화: -0.67 MB)
[CLFD]   [LSTM] 완료  첫값=3.99e+07 (메모리: 1586.8 MB)
[CLFD]   [Theta] 시작  (메모리: 1586.8 MB)
[메모리] forecast_theta 실행 전: 1586.82 MB
[메모리] forecast_theta 실행 후: 1586.82 MB (변화: +0.00 MB)
[CLFD]   [Theta] 완료  첫값=3.11e+07 (메모리: 1586.8 MB)
[CLFD]   [DB] 88행 저장 완료
[PROGRESS] [ 396/500] ( 79.2%)  >>  EVH
[EVH]   40분기 | 2016-03-31 ~ 2025-12-31
[EVH]   [SARIMA] 시작  (메모리: 1586.8 MB)
[메모리] forecast_sarima 실행 전: 1586.82 MB
[메모리] find_best_sarima_params 실행 전: 1586.82 MB
[메모리] find_best_sarima_params 실행 후: 1586.82 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.82 MB (변화: +0.00 MB)
[EVH]   [SARIMA] 완료  첫값=4.97e+08 (메모리: 1586.8 MB)
[EVH]   [ETS] 시작  (메모리: 1586.8 MB)
[메모리] forecast_ets 실행 전: 1586.82 MB
[메모리] forecast_ets 실행 후: 1586.82 MB (변화: +0.00 MB)
[EVH]   [ETS] 완료  첫값=4.48e+08 (메모리: 1586.8 MB)
[EVH]   [Prophet] 시작  (메모리: 1586.8 MB)

12:08:19 - cmdstanpy - INFO - Chain [1] start processing
12:08:19 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1586.82 MB
[메모리] forecast_prophet 실행 후: 1586.10 MB (변화: -0.72 MB)
[EVH]   [Prophet] 완료  첫값=5.86e+08 (메모리: 1586.1 MB)
[EVH]   [LSTM] 시작  (메모리: 1586.1 MB)
[메모리] forecast_lstm 실행 전: 1586.10 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1587.55 MB (변화: +1.45 MB)
[EVH]   [LSTM] 완료  첫값=6.64e+08 (메모리: 1587.5 MB)
[EVH]   [Theta] 시작  (메모리: 1587.5 MB)
[메모리] forecast_theta 실행 전: 1587.55 MB
[메모리] forecast_theta 실행 후: 1587.55 MB (변화: +0.00 MB)
[EVH]   [Theta] 완료  첫값=4.69e+08 (메모리: 1587.5 MB)
[EVH]   [DB] 88행 저장 완료
[PROGRESS] [ 397/500] ( 79.4%)  >>  CAL
[CAL]   40분기 | 2016-04-30 ~ 2026-01-31
[CAL]   [SARIMA] 시작  (메모리: 1587.5 MB)
[메모리] forecast_sarima 실행 전: 1587.55 MB
[메모리] find_best_sarima_params 실행 전: 1587.55 MB
[메모리] find_best_sarima_params 실행 후: 1587.55 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1587.55 MB (변화: +0.00 MB)
[CAL]   [SARIMA] 완료  첫값=6.55e+08 (메모리: 1587.5 MB)
[CAL]   [ETS] 시작  (메모리: 1587.5 MB)
[메모리] forecast_ets 실행 전: 1587.55 MB
[메모리] forecast_ets 실행 후: 1587.55 MB (변화: +0.00 MB)
[CAL]   [ETS] 완료  첫값=6.43e+08 (메모리: 1587.6 MB)
[CAL]   [Prophet] 시작  (메모리: 1587.6 MB)

12:08:34 - cmdstanpy - INFO - Chain [1] start processing
12:08:34 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1587.55 MB
[메모리] forecast_prophet 실행 후: 1587.21 MB (변화: -0.34 MB)
[CAL]   [Prophet] 완료  첫값=7.02e+08 (메모리: 1587.2 MB)
[CAL]   [LSTM] 시작  (메모리: 1587.2 MB)
[메모리] forecast_lstm 실행 전: 1587.21 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1588.20 MB (변화: +1.00 MB)
[CAL]   [LSTM] 완료  첫값=6.69e+08 (메모리: 1588.2 MB)
[CAL]   [Theta] 시작  (메모리: 1588.2 MB)
[메모리] forecast_theta 실행 전: 1588.20 MB
[메모리] forecast_theta 실행 후: 1588.20 MB (변화: +0.00 MB)
[CAL]   [Theta] 완료  첫값=7.04e+08 (메모리: 1588.2 MB)
[CAL]   [DB] 88행 저장 완료
[PROGRESS] [ 398/500] ( 79.6%)  >>  PTSI
[PTSI] [NEG-SKIP] [PTSI] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2024, 12, 31)])
[PROGRESS] [ 399/500] ( 79.8%)  >>  NATR
[NATR]   40분기 | 2016-03-31 ~ 2025-12-31
[NATR]   [SARIMA] 시작  (메모리: 1588.2 MB)
[메모리] forecast_sarima 실행 전: 1588.20 MB
[메모리] find_best_sarima_params 실행 전: 1588.20 MB
[메모리] find_best_sarima_params 실행 후: 1588.20 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1588.20 MB (변화: +0.00 MB)
[NATR]   [SARIMA] 완료  첫값=1.25e+08 (메모리: 1588.2 MB)
[NATR]   [ETS] 시작  (메모리: 1588.2 MB)
[메모리] forecast_ets 실행 전: 1588.20 MB
[메모리] forecast_ets 실행 후: 1588.21 MB (변화: +0.00 MB)
[NATR]   [ETS] 완료  첫값=1.23e+08 (메모리: 1588.2 MB)
[NATR]   [Prophet] 시작  (메모리: 1588.2 MB)
[메모리] forecast_prophet 실행 전: 1588.21 MB

12:08:52 - cmdstanpy - INFO - Chain [1] start processing
12:08:52 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1588.23 MB (변화: +0.02 MB)
[NATR]   [Prophet] 완료  첫값=1.22e+08 (메모리: 1588.2 MB)
[NATR]   [LSTM] 시작  (메모리: 1588.2 MB)
[메모리] forecast_lstm 실행 전: 1588.23 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1588.21 MB (변화: -0.02 MB)
[NATR]   [LSTM] 완료  첫값=1.17e+08 (메모리: 1588.2 MB)
[NATR]   [Theta] 시작  (메모리: 1588.2 MB)
[메모리] forecast_theta 실행 전: 1588.21 MB
[메모리] forecast_theta 실행 후: 1588.21 MB (변화: +0.00 MB)
[NATR]   [Theta] 완료  첫값=1.23e+08 (메모리: 1588.2 MB)
[NATR]   [DB] 88행 저장 완료
[PROGRESS] [ 400/500] ( 80.0%)  >>  LPTH
[LPTH]   40분기 | 2016-03-31 ~ 2025-12-31
[LPTH]   [SARIMA] 시작  (메모리: 1588.2 MB)
[메모리] forecast_sarima 실행 전: 1588.21 MB
[메모리] find_best_sarima_params 실행 전: 1588.21 MB
[메모리] find_best_sarima_params 실행 후: 1588.21 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1588.21 MB (변화: +0.00 MB)
[LPTH]   [SARIMA] 완료  첫값=1.70e+07 (메모리: 1588.2 MB)
[LPTH]   [ETS] 시작  (메모리: 1588.2 MB)
[메모리] forecast_ets 실행 전: 1588.21 MB
[메모리] forecast_ets 실행 후: 1588.21 MB (변화: +0.00 MB)
[LPTH]   [ETS] 완료  첫값=1.68e+07 (메모리: 1588.2 MB)
[LPTH]   [Prophet] 시작  (메모리: 1588.2 MB)

12:09:07 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1588.21 MB

12:09:08 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1588.22 MB (변화: +0.01 MB)
[LPTH]   [Prophet] 완료  첫값=1.09e+07 (메모리: 1588.2 MB)
[LPTH]   [LSTM] 시작  (메모리: 1588.2 MB)
[메모리] forecast_lstm 실행 전: 1588.22 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1588.20 MB (변화: -0.03 MB)
[LPTH]   [LSTM] 완료  첫값=1.06e+07 (메모리: 1588.2 MB)
[LPTH]   [Theta] 시작  (메모리: 1588.2 MB)
[메모리] forecast_theta 실행 전: 1588.20 MB
[메모리] forecast_theta 실행 후: 1588.20 MB (변화: +0.00 MB)
[LPTH]   [Theta] 완료  첫값=1.64e+07 (메모리: 1588.2 MB)
[LPTH]   [DB] 88행 저장 완료
[PROGRESS] [ 401/500] ( 80.2%)  >>  ULH
[ULH]   40분기 | 2016-04-02 ~ 2025-12-31
[ULH]   [SARIMA] 시작  (메모리: 1588.2 MB)
[메모리] forecast_sarima 실행 전: 1588.20 MB
[메모리] find_best_sarima_params 실행 전: 1588.20 MB
[메모리] find_best_sarima_params 실행 후: 1588.20 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1588.20 MB (변화: +0.00 MB)
[ULH]   [SARIMA] 완료  첫값=3.89e+08 (메모리: 1588.2 MB)
[ULH]   [ETS] 시작  (메모리: 1588.2 MB)
[메모리] forecast_ets 실행 전: 1588.20 MB
[메모리] forecast_ets 실행 후: 1588.20 MB (변화: +0.00 MB)
[ULH]   [ETS] 완료  첫값=4.03e+08 (메모리: 1588.2 MB)
[ULH]   [Prophet] 시작  (메모리: 1588.2 MB)

12:09:22 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1588.20 MB

12:09:22 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1588.22 MB (변화: +0.02 MB)
[ULH]   [Prophet] 완료  첫값=4.74e+08 (메모리: 1588.2 MB)
[ULH]   [LSTM] 시작  (메모리: 1588.2 MB)
[메모리] forecast_lstm 실행 전: 1588.22 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1587.18 MB (변화: -1.04 MB)
[ULH]   [LSTM] 완료  첫값=4.24e+08 (메모리: 1587.2 MB)
[ULH]   [Theta] 시작  (메모리: 1587.2 MB)
[메모리] forecast_theta 실행 전: 1587.18 MB
[메모리] forecast_theta 실행 후: 1587.18 MB (변화: +0.00 MB)
[ULH]   [Theta] 완료  첫값=4.01e+08 (메모리: 1587.2 MB)
[ULH]   [DB] 88행 저장 완료
[PROGRESS] [ 402/500] ( 80.4%)  >>  HVT
[HVT]   40분기 | 2016-03-31 ~ 2025-12-31
[HVT]   [SARIMA] 시작  (메모리: 1587.2 MB)
[메모리] forecast_sarima 실행 전: 1587.18 MB
[메모리] find_best_sarima_params 실행 전: 1587.18 MB
[메모리] find_best_sarima_params 실행 후: 1587.18 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1587.18 MB (변화: +0.00 MB)
[HVT]   [SARIMA] 완료  첫값=2.05e+08 (메모리: 1587.2 MB)
[HVT]   [ETS] 시작  (메모리: 1587.2 MB)
[메모리] forecast_ets 실행 전: 1587.18 MB
[메모리] forecast_ets 실행 후: 1587.18 MB (변화: +0.00 MB)
[HVT]   [ETS] 완료  첫값=1.81e+08 (메모리: 1587.2 MB)
[HVT]   [Prophet] 시작  (메모리: 1587.2 MB)

12:09:42 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1587.18 MB

12:09:42 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1587.19 MB (변화: +0.00 MB)
[HVT]   [Prophet] 완료  첫값=2.12e+08 (메모리: 1587.2 MB)
[HVT]   [LSTM] 시작  (메모리: 1587.2 MB)
[메모리] forecast_lstm 실행 전: 1587.19 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1587.02 MB (변화: -0.17 MB)
[HVT]   [LSTM] 완료  첫값=2.15e+08 (메모리: 1587.0 MB)
[HVT]   [Theta] 시작  (메모리: 1587.0 MB)
[메모리] forecast_theta 실행 전: 1587.02 MB
[메모리] forecast_theta 실행 후: 1587.02 MB (변화: +0.00 MB)
[HVT]   [Theta] 완료  첫값=1.96e+08 (메모리: 1587.0 MB)
[HVT]   [DB] 88행 저장 완료
[PROGRESS] [ 403/500] ( 80.6%)  >>  ANGO
[ANGO]   40분기 | 2016-05-31 ~ 2026-02-28
[ANGO]   [SARIMA] 시작  (메모리: 1587.0 MB)
[메모리] forecast_sarima 실행 전: 1587.02 MB
[메모리] find_best_sarima_params 실행 전: 1587.02 MB
[메모리] find_best_sarima_params 실행 후: 1587.02 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1587.02 MB (변화: +0.00 MB)
[ANGO]   [SARIMA] 완료  첫값=7.89e+07 (메모리: 1587.0 MB)
[ANGO]   [ETS] 시작  (메모리: 1587.0 MB)
[메모리] forecast_ets 실행 전: 1587.02 MB
[메모리] forecast_ets 실행 후: 1587.02 MB (변화: +0.00 MB)
[ANGO]   [ETS] 완료  첫값=8.13e+07 (메모리: 1587.0 MB)
[ANGO]   [Prophet] 시작  (메모리: 1587.0 MB)

12:09:57 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1587.02 MB

12:09:57 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1587.77 MB (변화: +0.74 MB)
[ANGO]   [Prophet] 완료  첫값=7.33e+07 (메모리: 1587.8 MB)
[ANGO]   [LSTM] 시작  (메모리: 1587.8 MB)
[메모리] forecast_lstm 실행 전: 1587.77 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1587.24 MB (변화: -0.53 MB)
[ANGO]   [LSTM] 완료  첫값=7.79e+07 (메모리: 1587.2 MB)
[ANGO]   [Theta] 시작  (메모리: 1587.2 MB)
[메모리] forecast_theta 실행 전: 1587.24 MB
[메모리] forecast_theta 실행 후: 1587.24 MB (변화: +0.00 MB)
[ANGO]   [Theta] 완료  첫값=7.81e+07 (메모리: 1587.2 MB)
[ANGO]   [DB] 88행 저장 완료
[PROGRESS] [ 404/500] ( 80.8%)  >>  ZUMZ
[ZUMZ]   40분기 | 2016-04-30 ~ 2026-01-31
[ZUMZ]   [SARIMA] 시작  (메모리: 1587.2 MB)
[메모리] forecast_sarima 실행 전: 1587.24 MB
[메모리] find_best_sarima_params 실행 전: 1587.24 MB
[메모리] find_best_sarima_params 실행 후: 1587.24 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1587.24 MB (변화: +0.00 MB)
[ZUMZ]   [SARIMA] 완료  첫값=1.85e+08 (메모리: 1587.2 MB)
[ZUMZ]   [ETS] 시작  (메모리: 1587.2 MB)
[메모리] forecast_ets 실행 전: 1587.24 MB
[메모리] forecast_ets 실행 후: 1587.25 MB (변화: +0.01 MB)
[ZUMZ]   [ETS] 완료  첫값=1.89e+08 (메모리: 1587.2 MB)
[ZUMZ]   [Prophet] 시작  (메모리: 1587.2 MB)

12:10:17 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1587.25 MB

12:10:17 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1586.90 MB (변화: -0.35 MB)
[ZUMZ]   [Prophet] 완료  첫값=2.47e+08 (메모리: 1586.9 MB)
[ZUMZ]   [LSTM] 시작  (메모리: 1586.9 MB)
[메모리] forecast_lstm 실행 전: 1586.90 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1587.84 MB (변화: +0.95 MB)
[ZUMZ]   [LSTM] 완료  첫값=2.22e+08 (메모리: 1587.8 MB)
[ZUMZ]   [Theta] 시작  (메모리: 1587.8 MB)
[메모리] forecast_theta 실행 전: 1587.84 MB
[메모리] forecast_theta 실행 후: 1587.84 MB (변화: +0.00 MB)
[ZUMZ]   [Theta] 완료  첫값=1.87e+08 (메모리: 1587.8 MB)
[ZUMZ]   [DB] 88행 저장 완료
[PROGRESS] [ 405/500] ( 81.0%)  >>  PTN
[PTN] [NEG-SKIP] [PTN] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2020, 9, 30), datetime.date(2020, 12, 31)])
[PROGRESS] [ 406/500] ( 81.2%)  >>  USAP
[USAP]   40분기 | 2014-12-31 ~ 2024-09-30
[USAP]   [SARIMA] 시작  (메모리: 1587.8 MB)
[메모리] forecast_sarima 실행 전: 1587.84 MB
[메모리] find_best_sarima_params 실행 전: 1587.84 MB
[메모리] find_best_sarima_params 실행 후: 1587.84 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1587.84 MB (변화: +0.00 MB)
[USAP]   [SARIMA] 완료  첫값=9.35e+07 (메모리: 1587.8 MB)
[USAP]   [ETS] 시작  (메모리: 1587.8 MB)
[메모리] forecast_ets 실행 전: 1587.84 MB
[메모리] forecast_ets 실행 후: 1587.85 MB (변화: +0.00 MB)
[USAP]   [ETS] 완료  첫값=8.43e+07 (메모리: 1587.8 MB)
[USAP]   [Prophet] 시작  (메모리: 1587.8 MB)

12:10:33 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1587.85 MB

12:10:33 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1587.87 MB (변화: +0.02 MB)
[USAP]   [Prophet] 완료  첫값=6.63e+07 (메모리: 1587.9 MB)
[USAP]   [LSTM] 시작  (메모리: 1587.9 MB)
[메모리] forecast_lstm 실행 전: 1587.87 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1587.41 MB (변화: -0.46 MB)
[USAP]   [LSTM] 완료  첫값=6.06e+07 (메모리: 1587.4 MB)
[USAP]   [Theta] 시작  (메모리: 1587.4 MB)
[메모리] forecast_theta 실행 전: 1587.41 MB
[메모리] forecast_theta 실행 후: 1587.41 MB (변화: +0.00 MB)
[USAP]   [Theta] 완료  첫값=8.77e+07 (메모리: 1587.4 MB)
[USAP]   [DB] 88행 저장 완료
[PROGRESS] [ 407/500] ( 81.4%)  >>  CLPT
[CLPT]   40분기 | 2016-03-31 ~ 2025-12-31
[CLPT]   [SARIMA] 시작  (메모리: 1587.4 MB)
[메모리] forecast_sarima 실행 전: 1587.41 MB
[메모리] find_best_sarima_params 실행 전: 1587.41 MB
[메모리] find_best_sarima_params 실행 후: 1587.41 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1587.41 MB (변화: +0.00 MB)
[CLPT]   [SARIMA] 완료  첫값=1.10e+07 (메모리: 1587.4 MB)
[CLPT]   [ETS] 시작  (메모리: 1587.4 MB)
[메모리] forecast_ets 실행 전: 1587.41 MB
[메모리] forecast_ets 실행 후: 1587.41 MB (변화: +0.00 MB)
[CLPT]   [ETS] 완료  첫값=1.11e+07 (메모리: 1587.4 MB)
[CLPT]   [Prophet] 시작  (메모리: 1587.4 MB)

12:10:53 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1587.41 MB

12:10:53 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1587.43 MB (변화: +0.02 MB)
[CLPT]   [Prophet] 완료  첫값=9.79e+06 (메모리: 1587.4 MB)
[CLPT]   [LSTM] 시작  (메모리: 1587.4 MB)
[메모리] forecast_lstm 실행 전: 1587.43 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1587.16 MB (변화: -0.27 MB)
[CLPT]   [LSTM] 완료  첫값=1.15e+07 (메모리: 1587.2 MB)
[CLPT]   [Theta] 시작  (메모리: 1587.2 MB)
[메모리] forecast_theta 실행 전: 1587.16 MB
[메모리] forecast_theta 실행 후: 1587.16 MB (변화: +0.00 MB)
[CLPT]   [Theta] 완료  첫값=1.09e+07 (메모리: 1587.2 MB)
[CLPT]   [DB] 88행 저장 완료
[PROGRESS] [ 408/500] ( 81.6%)  >>  TSAT
[TSAT]   40분기 | 2016-03-31 ~ 2025-12-31
[TSAT]   [SARIMA] 시작  (메모리: 1587.2 MB)
[메모리] forecast_sarima 실행 전: 1587.16 MB
[메모리] find_best_sarima_params 실행 전: 1587.16 MB
[메모리] find_best_sarima_params 실행 후: 1587.16 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1587.16 MB (변화: +0.00 MB)
[TSAT]   [SARIMA] 완료  첫값=9.19e+07 (메모리: 1587.2 MB)
[TSAT]   [ETS] 시작  (메모리: 1587.2 MB)
[메모리] forecast_ets 실행 전: 1587.16 MB
[메모리] forecast_ets 실행 후: 1587.16 MB (변화: +0.00 MB)
[TSAT]   [ETS] 완료  첫값=8.38e+07 (메모리: 1587.2 MB)
[TSAT]   [Prophet] 시작  (메모리: 1587.2 MB)

12:11:14 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1587.16 MB

12:11:14 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1587.18 MB (변화: +0.02 MB)
[TSAT]   [Prophet] 완료  첫값=1.02e+08 (메모리: 1587.2 MB)
[TSAT]   [LSTM] 시작  (메모리: 1587.2 MB)
[메모리] forecast_lstm 실행 전: 1587.18 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.91 MB (변화: -0.27 MB)
[TSAT]   [LSTM] 완료  첫값=1.45e+08 (메모리: 1586.9 MB)
[TSAT]   [Theta] 시작  (메모리: 1586.9 MB)
[메모리] forecast_theta 실행 전: 1586.91 MB
[메모리] forecast_theta 실행 후: 1586.91 MB (변화: +0.00 MB)
[TSAT]   [Theta] 완료  첫값=8.95e+07 (메모리: 1586.9 MB)
[TSAT]   [DB] 88행 저장 완료
[PROGRESS] [ 409/500] ( 81.8%)  >>  SGU
[SGU]   40분기 | 2016-03-31 ~ 2025-12-31
[SGU]   [SARIMA] 시작  (메모리: 1586.9 MB)
[메모리] forecast_sarima 실행 전: 1586.91 MB
[메모리] find_best_sarima_params 실행 전: 1586.91 MB
[메모리] find_best_sarima_params 실행 후: 1586.91 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.91 MB (변화: +0.00 MB)
[SGU]   [SARIMA] 완료  첫값=7.43e+08 (메모리: 1586.9 MB)
[SGU]   [ETS] 시작  (메모리: 1586.9 MB)
[메모리] forecast_ets 실행 전: 1586.91 MB
[메모리] forecast_ets 실행 후: 1586.91 MB (변화: +0.00 MB)
[SGU]   [ETS] 완료  첫값=7.39e+08 (메모리: 1586.9 MB)
[SGU]   [Prophet] 시작  (메모리: 1586.9 MB)

12:11:28 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1586.91 MB

12:11:28 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1586.94 MB (변화: +0.03 MB)
[SGU]   [Prophet] 완료  첫값=4.80e+08 (메모리: 1586.9 MB)
[SGU]   [LSTM] 시작  (메모리: 1586.9 MB)
[메모리] forecast_lstm 실행 전: 1586.94 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.79 MB (변화: -0.15 MB)
[SGU]   [LSTM] 완료  첫값=5.05e+08 (메모리: 1586.8 MB)
[SGU]   [Theta] 시작  (메모리: 1586.8 MB)
[메모리] forecast_theta 실행 전: 1586.79 MB
[메모리] forecast_theta 실행 후: 1586.79 MB (변화: +0.00 MB)
[SGU]   [Theta] 완료  첫값=7.36e+08 (메모리: 1586.8 MB)
[SGU]   [DB] 88행 저장 완료
[PROGRESS] [ 410/500] ( 82.0%)  >>  VHI
[VHI]   40분기 | 2016-03-31 ~ 2025-12-31
[VHI]   [SARIMA] 시작  (메모리: 1586.8 MB)
[메모리] forecast_sarima 실행 전: 1586.79 MB
[메모리] find_best_sarima_params 실행 전: 1586.79 MB
[메모리] find_best_sarima_params 실행 후: 1586.79 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.79 MB (변화: +0.00 MB)
[VHI]   [SARIMA] 완료  첫값=5.18e+08 (메모리: 1586.8 MB)
[VHI]   [ETS] 시작  (메모리: 1586.8 MB)
[메모리] forecast_ets 실행 전: 1586.79 MB
[메모리] forecast_ets 실행 후: 1586.80 MB (변화: +0.00 MB)
[VHI]   [ETS] 완료  첫값=5.30e+08 (메모리: 1586.8 MB)
[VHI]   [Prophet] 시작  (메모리: 1586.8 MB)

12:11:43 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1586.80 MB

12:11:43 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1586.81 MB (변화: +0.02 MB)
[VHI]   [Prophet] 완료  첫값=5.50e+08 (메모리: 1586.8 MB)
[VHI]   [LSTM] 시작  (메모리: 1586.8 MB)
[메모리] forecast_lstm 실행 전: 1586.81 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1587.77 MB (변화: +0.96 MB)
[VHI]   [LSTM] 완료  첫값=5.09e+08 (메모리: 1587.8 MB)
[VHI]   [Theta] 시작  (메모리: 1587.8 MB)
[메모리] forecast_theta 실행 전: 1587.77 MB
[메모리] forecast_theta 실행 후: 1587.77 MB (변화: +0.00 MB)
[VHI]   [Theta] 완료  첫값=4.99e+08 (메모리: 1587.8 MB)
[VHI]   [DB] 88행 저장 완료
[PROGRESS] [ 411/500] ( 82.2%)  >>  PLG
[PLG]   40분기 | 2016-02-29 ~ 2025-11-30
[PLG]   [SARIMA] 시작  (메모리: 1587.8 MB)
[메모리] forecast_sarima 실행 전: 1587.77 MB
[메모리] find_best_sarima_params 실행 전: 1587.77 MB
[메모리] find_best_sarima_params 실행 후: 1587.77 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1587.77 MB (변화: +0.00 MB)
[PLG]   [SARIMA] 완료  첫값=0.00e+00 (메모리: 1587.8 MB)
[PLG]   [ETS] 시작  (메모리: 1587.8 MB)
[메모리] forecast_ets 실행 전: 1587.77 MB
[메모리] forecast_ets 실행 후: 1587.78 MB (변화: +0.01 MB)
[PLG]   [ETS] 완료  첫값=0.00e+00 (메모리: 1587.8 MB)
[PLG]   [Prophet] 시작  (메모리: 1587.8 MB)
[메모리] forecast_prophet 실행 전: 1587.78 MB
[메모리] forecast_prophet 실행 후: 1587.79 MB (변화: +0.02 MB)
[PLG]   [Prophet] 완료  첫값=0.00e+00 (메모리: 1587.8 MB)
[PLG]   [LSTM] 시작  (메모리: 1587.8 MB)
[메모리] forecast_lstm 실행 전: 1587.79 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1587.77 MB (변화: -0.03 MB)
[PLG]   [LSTM] 완료  첫값=0.00e+00 (메모리: 1587.8 MB)
[PLG]   [Theta] 시작  (메모리: 1587.8 MB)
[메모리] forecast_theta 실행 전: 1587.77 MB
[메모리] forecast_theta 실행 후: 1587.77 MB (변화: +0.00 MB)
[PLG]   [Theta] 완료  첫값=0.00e+00 (메모리: 1587.8 MB)
[PLG]   [DB] 88행 저장 완료
[PROGRESS] [ 412/500] ( 82.4%)  >>  KOR
[KOR] [SKIP] [KOR] FMP에서 'sale' 데이터 없음
[PROGRESS] [ 413/500] ( 82.6%)  >>  GPRK
[GPRK]   40분기 | 2016-03-31 ~ 2025-12-31
[GPRK]   [SARIMA] 시작  (메모리: 1587.8 MB)
[메모리] forecast_sarima 실행 전: 1587.77 MB
[메모리] find_best_sarima_params 실행 전: 1587.77 MB
[메모리] find_best_sarima_params 실행 후: 1587.77 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1587.77 MB (변화: +0.00 MB)
[GPRK]   [SARIMA] 완료  첫값=7.04e+07 (메모리: 1587.8 MB)
[GPRK]   [ETS] 시작  (메모리: 1587.8 MB)
[메모리] forecast_ets 실행 전: 1587.77 MB
[메모리] forecast_ets 실행 후: 1587.77 MB (변화: +0.00 MB)
[GPRK]   [ETS] 완료  첫값=9.69e+07 (메모리: 1587.8 MB)
[GPRK]   [Prophet] 시작  (메모리: 1587.8 MB)

12:12:16 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1587.77 MB

12:12:16 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1587.79 MB (변화: +0.02 MB)
[GPRK]   [Prophet] 완료  첫값=1.90e+08 (메모리: 1587.8 MB)
[GPRK]   [LSTM] 시작  (메모리: 1587.8 MB)
[메모리] forecast_lstm 실행 전: 1587.79 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1587.83 MB (변화: +0.04 MB)
[GPRK]   [LSTM] 완료  첫값=1.43e+08 (메모리: 1587.8 MB)
[GPRK]   [Theta] 시작  (메모리: 1587.8 MB)
[메모리] forecast_theta 실행 전: 1587.83 MB
[메모리] forecast_theta 실행 후: 1587.83 MB (변화: +0.00 MB)
[GPRK]   [Theta] 완료  첫값=1.14e+08 (메모리: 1587.8 MB)
[GPRK]   [DB] 88행 저장 완료
[PROGRESS] [ 414/500] ( 82.8%)  >>  NATH
[NATH]   40분기 | 2016-03-31 ~ 2025-12-28
[NATH]   [SARIMA] 시작  (메모리: 1587.8 MB)
[메모리] forecast_sarima 실행 전: 1587.83 MB
[메모리] find_best_sarima_params 실행 전: 1587.83 MB
[메모리] find_best_sarima_params 실행 후: 1587.83 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1587.83 MB (변화: +0.00 MB)
[NATH]   [SARIMA] 완료  첫값=3.70e+07 (메모리: 1587.8 MB)
[NATH]   [ETS] 시작  (메모리: 1587.8 MB)
[메모리] forecast_ets 실행 전: 1587.83 MB
[메모리] forecast_ets 실행 후: 1587.83 MB (변화: +0.00 MB)
[NATH]   [ETS] 완료  첫값=3.39e+07 (메모리: 1587.8 MB)
[NATH]   [Prophet] 시작  (메모리: 1587.8 MB)

12:12:31 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1587.83 MB

12:12:31 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1587.87 MB (변화: +0.04 MB)
[NATH]   [Prophet] 완료  첫값=3.74e+07 (메모리: 1587.9 MB)
[NATH]   [LSTM] 시작  (메모리: 1587.9 MB)
[메모리] forecast_lstm 실행 전: 1587.87 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1587.84 MB (변화: -0.03 MB)
[NATH]   [LSTM] 완료  첫값=4.39e+07 (메모리: 1587.8 MB)
[NATH]   [Theta] 시작  (메모리: 1587.8 MB)
[메모리] forecast_theta 실행 전: 1587.84 MB
[메모리] forecast_theta 실행 후: 1587.84 MB (변화: +0.00 MB)
[NATH]   [Theta] 완료  첫값=3.36e+07 (메모리: 1587.8 MB)
[NATH]   [DB] 88행 저장 완료
[PROGRESS] [ 415/500] ( 83.0%)  >>  PERI
[PERI]   40분기 | 2016-03-31 ~ 2025-12-31
[PERI]   [SARIMA] 시작  (메모리: 1587.8 MB)
[메모리] forecast_sarima 실행 전: 1587.84 MB
[메모리] find_best_sarima_params 실행 전: 1587.84 MB
[메모리] find_best_sarima_params 실행 후: 1587.84 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1587.84 MB (변화: +0.00 MB)
[PERI]   [SARIMA] 완료  첫값=1.08e+08 (메모리: 1587.8 MB)
[PERI]   [ETS] 시작  (메모리: 1587.8 MB)
[메모리] forecast_ets 실행 전: 1587.84 MB
[메모리] forecast_ets 실행 후: 1587.84 MB (변화: +0.00 MB)
[PERI]   [ETS] 완료  첫값=1.02e+08 (메모리: 1587.8 MB)
[PERI]   [Prophet] 시작  (메모리: 1587.8 MB)

12:12:46 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1587.84 MB

12:12:46 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1587.86 MB (변화: +0.02 MB)
[PERI]   [Prophet] 완료  첫값=1.57e+08 (메모리: 1587.9 MB)
[PERI]   [LSTM] 시작  (메모리: 1587.9 MB)
[메모리] forecast_lstm 실행 전: 1587.86 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.77 MB (변화: -1.09 MB)
[PERI]   [LSTM] 완료  첫값=1.47e+08 (메모리: 1586.8 MB)
[PERI]   [Theta] 시작  (메모리: 1586.8 MB)
[메모리] forecast_theta 실행 전: 1586.77 MB
[메모리] forecast_theta 실행 후: 1586.77 MB (변화: +0.00 MB)
[PERI]   [Theta] 완료  첫값=1.02e+08 (메모리: 1586.8 MB)
[PERI]   [DB] 88행 저장 완료
[PROGRESS] [ 416/500] ( 83.2%)  >>  LTBR
[LTBR]   40분기 | 2016-03-31 ~ 2025-12-31
[LTBR]   [SARIMA] 시작  (메모리: 1586.8 MB)
[메모리] forecast_sarima 실행 전: 1586.77 MB
[메모리] find_best_sarima_params 실행 전: 1586.77 MB
[메모리] find_best_sarima_params 실행 후: 1586.77 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.77 MB (변화: +0.00 MB)
[LTBR]   [SARIMA] 완료  첫값=5.99e-11 (메모리: 1586.8 MB)
[LTBR]   [ETS] 시작  (메모리: 1586.8 MB)
[메모리] forecast_ets 실행 전: 1586.77 MB
[메모리] forecast_ets 실행 후: 1586.78 MB (변화: +0.00 MB)
[LTBR]   [ETS] 완료  첫값=9.52e+02 (메모리: 1586.8 MB)
[LTBR]   [Prophet] 시작  (메모리: 1586.8 MB)

12:13:02 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1586.78 MB

12:13:02 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1586.80 MB (변화: +0.02 MB)
[LTBR]   [Prophet] 완료  첫값=-3.81e+04 (메모리: 1586.8 MB)
[LTBR]   [LSTM] 시작  (메모리: 1586.8 MB)
[메모리] forecast_lstm 실행 전: 1586.80 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.80 MB (변화: +0.00 MB)
[LTBR]   [LSTM] 완료  첫값=-2.89e+02 (메모리: 1586.8 MB)
[LTBR]   [Theta] 시작  (메모리: 1586.8 MB)
[메모리] forecast_theta 실행 전: 1586.80 MB
[메모리] forecast_theta 실행 후: 1586.80 MB (변화: +0.00 MB)
[LTBR]   [Theta] 완료  첫값=-3.67e+03 (메모리: 1586.8 MB)
[LTBR]   [DB] 88행 저장 완료
[PROGRESS] [ 417/500] ( 83.4%)  >>  ACRS
[ACRS]   40분기 | 2016-03-31 ~ 2025-12-31
[ACRS]   [SARIMA] 시작  (메모리: 1586.8 MB)
[메모리] forecast_sarima 실행 전: 1586.80 MB
[메모리] find_best_sarima_params 실행 전: 1586.80 MB
[메모리] find_best_sarima_params 실행 후: 1586.80 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.80 MB (변화: +0.00 MB)
[ACRS]   [SARIMA] 완료  첫값=1.85e+06 (메모리: 1586.8 MB)
[ACRS]   [ETS] 시작  (메모리: 1586.8 MB)
[메모리] forecast_ets 실행 전: 1586.80 MB
[메모리] forecast_ets 실행 후: 1586.80 MB (변화: +0.00 MB)
[ACRS]   [ETS] 완료  첫값=1.66e+06 (메모리: 1586.8 MB)
[ACRS]   [Prophet] 시작  (메모리: 1586.8 MB)

12:13:13 - cmdstanpy - INFO - Chain [1] start processing
12:13:13 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1586.80 MB
[메모리] forecast_prophet 실행 후: 1586.81 MB (변화: +0.01 MB)
[ACRS]   [Prophet] 완료  첫값=6.03e+06 (메모리: 1586.8 MB)
[ACRS]   [LSTM] 시작  (메모리: 1586.8 MB)
[메모리] forecast_lstm 실행 전: 1586.81 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.77 MB (변화: -0.04 MB)
[ACRS]   [LSTM] 완료  첫값=3.77e+06 (메모리: 1586.8 MB)
[ACRS]   [Theta] 시작  (메모리: 1586.8 MB)
[메모리] forecast_theta 실행 전: 1586.77 MB
[메모리] forecast_theta 실행 후: 1586.77 MB (변화: +0.00 MB)
[ACRS]   [Theta] 완료  첫값=2.42e+06 (메모리: 1586.8 MB)
[ACRS]   [DB] 88행 저장 완료
[PROGRESS] [ 418/500] ( 83.6%)  >>  LND
[LND]   40분기 | 2016-03-31 ~ 2025-12-31
[LND]   [SARIMA] 시작  (메모리: 1586.8 MB)
[메모리] forecast_sarima 실행 전: 1586.77 MB
[메모리] find_best_sarima_params 실행 전: 1586.77 MB
[메모리] find_best_sarima_params 실행 후: 1586.77 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.77 MB (변화: +0.00 MB)
[LND]   [SARIMA] 완료  첫값=1.63e+08 (메모리: 1586.8 MB)
[LND]   [ETS] 시작  (메모리: 1586.8 MB)
[메모리] forecast_ets 실행 전: 1586.77 MB
[메모리] forecast_ets 실행 후: 1586.77 MB (변화: +0.00 MB)
[LND]   [ETS] 완료  첫값=9.07e+07 (메모리: 1586.8 MB)
[LND]   [Prophet] 시작  (메모리: 1586.8 MB)
[메모리] forecast_prophet 실행 전: 1586.77 MB

12:13:31 - cmdstanpy - INFO - Chain [1] start processing
12:13:32 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1586.79 MB (변화: +0.02 MB)
[LND]   [Prophet] 완료  첫값=3.77e+08 (메모리: 1586.8 MB)
[LND]   [LSTM] 시작  (메모리: 1586.8 MB)
[메모리] forecast_lstm 실행 전: 1586.79 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.78 MB (변화: -0.02 MB)
[LND]   [LSTM] 완료  첫값=3.49e+08 (메모리: 1586.8 MB)
[LND]   [Theta] 시작  (메모리: 1586.8 MB)
[메모리] forecast_theta 실행 전: 1586.78 MB
[메모리] forecast_theta 실행 후: 1586.78 MB (변화: +0.00 MB)
[LND]   [Theta] 완료  첫값=8.83e+07 (메모리: 1586.8 MB)
[LND]   [DB] 88행 저장 완료
[PROGRESS] [ 419/500] ( 83.8%)  >>  HELE
[HELE]   40분기 | 2016-02-28 ~ 2025-11-30
[HELE]   [SARIMA] 시작  (메모리: 1586.8 MB)
[메모리] forecast_sarima 실행 전: 1586.78 MB
[메모리] find_best_sarima_params 실행 전: 1586.78 MB
[메모리] find_best_sarima_params 실행 후: 1586.78 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.78 MB (변화: +0.00 MB)
[HELE]   [SARIMA] 완료  첫값=4.55e+08 (메모리: 1586.8 MB)
[HELE]   [ETS] 시작  (메모리: 1586.8 MB)
[메모리] forecast_ets 실행 전: 1586.78 MB
[메모리] forecast_ets 실행 후: 1586.78 MB (변화: +0.00 MB)
[HELE]   [ETS] 완료  첫값=4.33e+08 (메모리: 1586.8 MB)
[HELE]   [Prophet] 시작  (메모리: 1586.8 MB)

12:13:46 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1586.78 MB

12:13:47 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1586.82 MB (변화: +0.04 MB)
[HELE]   [Prophet] 완료  첫값=5.35e+08 (메모리: 1586.8 MB)
[HELE]   [LSTM] 시작  (메모리: 1586.8 MB)
[메모리] forecast_lstm 실행 전: 1586.82 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.77 MB (변화: -0.05 MB)
[HELE]   [LSTM] 완료  첫값=4.72e+08 (메모리: 1586.8 MB)
[HELE]   [Theta] 시작  (메모리: 1586.8 MB)
[메모리] forecast_theta 실행 전: 1586.77 MB
[메모리] forecast_theta 실행 후: 1586.77 MB (변화: +0.00 MB)
[HELE]   [Theta] 완료  첫값=4.31e+08 (메모리: 1586.8 MB)
[HELE]   [DB] 88행 저장 완료
[PROGRESS] [ 420/500] ( 84.0%)  >>  CLLS
[CLLS]   40분기 | 2016-03-31 ~ 2025-12-31
[CLLS]   [SARIMA] 시작  (메모리: 1586.8 MB)
[메모리] forecast_sarima 실행 전: 1586.77 MB
[메모리] find_best_sarima_params 실행 전: 1586.77 MB
[메모리] find_best_sarima_params 실행 후: 1586.77 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.77 MB (변화: +0.00 MB)
[CLLS]   [SARIMA] 완료  첫값=6.84e+06 (메모리: 1586.8 MB)
[CLLS]   [ETS] 시작  (메모리: 1586.8 MB)
[메모리] forecast_ets 실행 전: 1586.77 MB
[메모리] forecast_ets 실행 후: 1586.77 MB (변화: +0.00 MB)
[CLLS]   [ETS] 완료  첫값=1.52e+07 (메모리: 1586.8 MB)
[CLLS]   [Prophet] 시작  (메모리: 1586.8 MB)

12:14:00 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1586.77 MB

12:14:00 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1586.79 MB (변화: +0.01 MB)
[CLLS]   [Prophet] 완료  첫값=1.12e+07 (메모리: 1586.8 MB)
[CLLS]   [LSTM] 시작  (메모리: 1586.8 MB)
[메모리] forecast_lstm 실행 전: 1586.79 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.79 MB (변화: +0.01 MB)
[CLLS]   [LSTM] 완료  첫값=1.18e+07 (메모리: 1586.8 MB)
[CLLS]   [Theta] 시작  (메모리: 1586.8 MB)
[메모리] forecast_theta 실행 전: 1586.79 MB
[메모리] forecast_theta 실행 후: 1586.79 MB (변화: +0.00 MB)
[CLLS]   [Theta] 완료  첫값=1.46e+07 (메모리: 1586.8 MB)
[CLLS]   [DB] 88행 저장 완료
[PROGRESS] [ 421/500] ( 84.2%)  >>  PLM
[PLM]   40분기 | 2013-07-31 ~ 2023-06-30
[PLM]   [SARIMA] 시작  (메모리: 1586.8 MB)
[메모리] forecast_sarima 실행 전: 1586.79 MB
[메모리] find_best_sarima_params 실행 전: 1586.79 MB
[메모리] find_best_sarima_params 실행 후: 1586.79 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.79 MB (변화: +0.00 MB)
[PLM]   [SARIMA] 완료  첫값=1.04e-164 (메모리: 1586.8 MB)
[PLM]   [ETS] 시작  (메모리: 1586.8 MB)
[메모리] forecast_ets 실행 전: 1586.79 MB
[메모리] forecast_ets 실행 후: 1586.80 MB (변화: +0.00 MB)
[PLM]   [ETS] 완료  첫값=-2.85e+03 (메모리: 1586.8 MB)
[PLM]   [Prophet] 시작  (메모리: 1586.8 MB)

12:14:19 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1586.80 MB

12:14:19 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1586.82 MB (변화: +0.02 MB)
[PLM]   [Prophet] 완료  첫값=-6.74e+03 (메모리: 1586.8 MB)
[PLM]   [LSTM] 시작  (메모리: 1586.8 MB)
[메모리] forecast_lstm 실행 전: 1586.82 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1585.68 MB (변화: -1.13 MB)
[PLM]   [LSTM] 완료  첫값=-3.91e+00 (메모리: 1585.7 MB)
[PLM]   [Theta] 시작  (메모리: 1585.7 MB)
[메모리] forecast_theta 실행 전: 1585.68 MB
[메모리] forecast_theta 실행 후: 1585.68 MB (변화: +0.00 MB)
[PLM]   [Theta] 완료  첫값=-1.11e+04 (메모리: 1585.7 MB)
[PLM]   [DB] 88행 저장 완료
[PROGRESS] [ 422/500] ( 84.4%)  >>  WNC
[WNC]   40분기 | 2016-03-31 ~ 2025-12-31
[WNC]   [SARIMA] 시작  (메모리: 1585.7 MB)
[메모리] forecast_sarima 실행 전: 1585.68 MB
[메모리] find_best_sarima_params 실행 전: 1585.68 MB
[메모리] find_best_sarima_params 실행 후: 1585.68 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1585.68 MB (변화: +0.00 MB)
[WNC]   [SARIMA] 완료  첫값=2.81e+08 (메모리: 1585.7 MB)
[WNC]   [ETS] 시작  (메모리: 1585.7 MB)
[메모리] forecast_ets 실행 전: 1585.68 MB
[메모리] forecast_ets 실행 후: 1585.69 MB (변화: +0.00 MB)
[WNC]   [ETS] 완료  첫값=2.85e+08 (메모리: 1585.7 MB)
[WNC]   [Prophet] 시작  (메모리: 1585.7 MB)

12:14:38 - cmdstanpy - INFO - Chain [1] start processing
12:14:38 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1585.69 MB
[메모리] forecast_prophet 실행 후: 1585.71 MB (변화: +0.02 MB)
[WNC]   [Prophet] 완료  첫값=5.08e+08 (메모리: 1585.7 MB)
[WNC]   [LSTM] 시작  (메모리: 1585.7 MB)
[메모리] forecast_lstm 실행 전: 1585.71 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.66 MB (변화: +0.95 MB)
[WNC]   [LSTM] 완료  첫값=4.08e+08 (메모리: 1586.7 MB)
[WNC]   [Theta] 시작  (메모리: 1586.7 MB)
[메모리] forecast_theta 실행 전: 1586.66 MB
[메모리] forecast_theta 실행 후: 1586.66 MB (변화: +0.00 MB)
[WNC]   [Theta] 완료  첫값=3.28e+08 (메모리: 1586.7 MB)
[WNC]   [DB] 88행 저장 완료
[PROGRESS] [ 423/500] ( 84.6%)  >>  USNA
[USNA]   40분기 | 2016-04-02 ~ 2026-01-03
[USNA]   [SARIMA] 시작  (메모리: 1586.7 MB)
[메모리] forecast_sarima 실행 전: 1586.66 MB
[메모리] find_best_sarima_params 실행 전: 1586.66 MB
[메모리] find_best_sarima_params 실행 후: 1586.66 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.66 MB (변화: +0.00 MB)
[USNA]   [SARIMA] 완료  첫값=2.26e+08 (메모리: 1586.7 MB)
[USNA]   [ETS] 시작  (메모리: 1586.7 MB)
[메모리] forecast_ets 실행 전: 1586.66 MB
[메모리] forecast_ets 실행 후: 1586.66 MB (변화: +0.00 MB)
[USNA]   [ETS] 완료  첫값=2.38e+08 (메모리: 1586.7 MB)
[USNA]   [Prophet] 시작  (메모리: 1586.7 MB)
[메모리] forecast_prophet 실행 전: 1586.66 MB

12:14:58 - cmdstanpy - INFO - Chain [1] start processing
12:14:58 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1586.68 MB (변화: +0.02 MB)
[USNA]   [Prophet] 완료  첫값=2.16e+08 (메모리: 1586.7 MB)
[USNA]   [LSTM] 시작  (메모리: 1586.7 MB)
[메모리] forecast_lstm 실행 전: 1586.68 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.39 MB (변화: -0.29 MB)
[USNA]   [LSTM] 완료  첫값=2.34e+08 (메모리: 1586.4 MB)
[USNA]   [Theta] 시작  (메모리: 1586.4 MB)
[메모리] forecast_theta 실행 전: 1586.39 MB
[메모리] forecast_theta 실행 후: 1586.39 MB (변화: +0.00 MB)
[USNA]   [Theta] 완료  첫값=2.33e+08 (메모리: 1586.4 MB)
[USNA]   [DB] 88행 저장 완료
[PROGRESS] [ 424/500] ( 84.8%)  >>  JACK
[JACK]   40분기 | 2016-04-10 ~ 2026-01-18
[JACK]   [SARIMA] 시작  (메모리: 1586.4 MB)
[메모리] forecast_sarima 실행 전: 1586.39 MB
[메모리] find_best_sarima_params 실행 전: 1586.39 MB
[메모리] find_best_sarima_params 실행 후: 1586.39 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.39 MB (변화: +0.00 MB)
[JACK]   [SARIMA] 완료  첫값=2.36e+08 (메모리: 1586.4 MB)
[JACK]   [ETS] 시작  (메모리: 1586.4 MB)
[메모리] forecast_ets 실행 전: 1586.39 MB
[메모리] forecast_ets 실행 후: 1586.40 MB (변화: +0.00 MB)
[JACK]   [ETS] 완료  첫값=2.97e+08 (메모리: 1586.4 MB)
[JACK]   [Prophet] 시작  (메모리: 1586.4 MB)

12:15:11 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1586.40 MB

12:15:11 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1587.08 MB (변화: +0.68 MB)
[JACK]   [Prophet] 완료  첫값=4.15e+08 (메모리: 1587.1 MB)
[JACK]   [LSTM] 시작  (메모리: 1587.1 MB)
[메모리] forecast_lstm 실행 전: 1587.08 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.94 MB (변화: -0.14 MB)
[JACK]   [LSTM] 완료  첫값=3.76e+08 (메모리: 1586.9 MB)
[JACK]   [Theta] 시작  (메모리: 1586.9 MB)
[메모리] forecast_theta 실행 전: 1586.94 MB
[메모리] forecast_theta 실행 후: 1586.94 MB (변화: +0.00 MB)
[JACK]   [Theta] 완료  첫값=2.85e+08 (메모리: 1586.9 MB)
[JACK]   [DB] 88행 저장 완료
[PROGRESS] [ 425/500] ( 85.0%)  >>  ELVA
[ELVA]   40분기 | 2016-03-31 ~ 2025-12-31
[ELVA]   [SARIMA] 시작  (메모리: 1586.9 MB)
[메모리] forecast_sarima 실행 전: 1586.94 MB
[메모리] find_best_sarima_params 실행 전: 1586.94 MB
[메모리] find_best_sarima_params 실행 후: 1586.94 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.94 MB (변화: +0.00 MB)
[ELVA]   [SARIMA] 완료  첫값=2.37e+07 (메모리: 1586.9 MB)
[ELVA]   [ETS] 시작  (메모리: 1586.9 MB)
[메모리] forecast_ets 실행 전: 1586.94 MB
[메모리] forecast_ets 실행 후: 1586.94 MB (변화: +0.00 MB)
[ELVA]   [ETS] 완료  첫값=2.06e+07 (메모리: 1586.9 MB)
[ELVA]   [Prophet] 시작  (메모리: 1586.9 MB)

12:15:25 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1586.94 MB

12:15:25 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1586.97 MB (변화: +0.03 MB)
[ELVA]   [Prophet] 완료  첫값=1.40e+07 (메모리: 1587.0 MB)
[ELVA]   [LSTM] 시작  (메모리: 1587.0 MB)
[메모리] forecast_lstm 실행 전: 1586.97 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1586.95 MB (변화: -0.02 MB)
[ELVA]   [LSTM] 완료  첫값=2.07e+07 (메모리: 1587.0 MB)
[ELVA]   [Theta] 시작  (메모리: 1587.0 MB)
[메모리] forecast_theta 실행 전: 1586.95 MB
[메모리] forecast_theta 실행 후: 1586.95 MB (변화: +0.00 MB)
[ELVA]   [Theta] 완료  첫값=2.04e+07 (메모리: 1587.0 MB)
[ELVA]   [DB] 88행 저장 완료
[PROGRESS] [ 426/500] ( 85.2%)  >>  SMLP
[SMLP]   40분기 | 2014-06-30 ~ 2024-03-31
[SMLP]   [SARIMA] 시작  (메모리: 1587.0 MB)
[메모리] forecast_sarima 실행 전: 1586.96 MB
[메모리] find_best_sarima_params 실행 전: 1586.96 MB
[메모리] find_best_sarima_params 실행 후: 1586.96 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1586.96 MB (변화: +0.00 MB)
[SMLP]   [SARIMA] 완료  첫값=1.19e+08 (메모리: 1587.0 MB)
[SMLP]   [ETS] 시작  (메모리: 1587.0 MB)
[메모리] forecast_ets 실행 전: 1586.96 MB
[메모리] forecast_ets 실행 후: 1586.96 MB (변화: +0.00 MB)
[SMLP]   [ETS] 완료  첫값=1.11e+08 (메모리: 1587.0 MB)
[SMLP]   [Prophet] 시작  (메모리: 1587.0 MB)
[메모리] forecast_prophet 실행 전: 1586.96 MB

12:15:45 - cmdstanpy - INFO - Chain [1] start processing
12:15:45 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1586.61 MB (변화: -0.35 MB)
[SMLP]   [Prophet] 완료  첫값=1.11e+08 (메모리: 1586.6 MB)
[SMLP]   [LSTM] 시작  (메모리: 1586.6 MB)
[메모리] forecast_lstm 실행 전: 1586.61 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1588.38 MB (변화: +1.77 MB)
[SMLP]   [LSTM] 완료  첫값=1.11e+08 (메모리: 1588.4 MB)
[SMLP]   [Theta] 시작  (메모리: 1588.4 MB)
[메모리] forecast_theta 실행 전: 1588.38 MB
[메모리] forecast_theta 실행 후: 1588.38 MB (변화: +0.00 MB)
[SMLP]   [Theta] 완료  첫값=1.20e+08 (메모리: 1588.4 MB)
[SMLP]   [DB] 88행 저장 완료
[PROGRESS] [ 427/500] ( 85.4%)  >>  SLP
[SLP]   40분기 | 2016-02-29 ~ 2025-11-30
[SLP]   [SARIMA] 시작  (메모리: 1588.4 MB)
[메모리] forecast_sarima 실행 전: 1588.38 MB
[메모리] find_best_sarima_params 실행 전: 1588.38 MB
[메모리] find_best_sarima_params 실행 후: 1588.38 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1588.38 MB (변화: +0.00 MB)
[SLP]   [SARIMA] 완료  첫값=2.30e+07 (메모리: 1588.4 MB)
[SLP]   [ETS] 시작  (메모리: 1588.4 MB)
[메모리] forecast_ets 실행 전: 1588.38 MB
[메모리] forecast_ets 실행 후: 1588.38 MB (변화: +0.00 MB)
[SLP]   [ETS] 완료  첫값=2.32e+07 (메모리: 1588.4 MB)
[SLP]   [Prophet] 시작  (메모리: 1588.4 MB)

12:16:06 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1588.38 MB

12:16:06 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1588.05 MB (변화: -0.33 MB)
[SLP]   [Prophet] 완료  첫값=2.01e+07 (메모리: 1588.1 MB)
[SLP]   [LSTM] 시작  (메모리: 1588.1 MB)
[메모리] forecast_lstm 실행 전: 1588.05 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1587.94 MB (변화: -0.11 MB)
[SLP]   [LSTM] 완료  첫값=1.90e+07 (메모리: 1587.9 MB)
[SLP]   [Theta] 시작  (메모리: 1587.9 MB)
[메모리] forecast_theta 실행 전: 1587.94 MB
[메모리] forecast_theta 실행 후: 1587.94 MB (변화: +0.00 MB)
[SLP]   [Theta] 완료  첫값=2.13e+07 (메모리: 1587.9 MB)
[SLP]   [DB] 88행 저장 완료
[PROGRESS] [ 428/500] ( 85.6%)  >>  LXFR
[LXFR]   40분기 | 2016-03-31 ~ 2025-12-31
[LXFR]   [SARIMA] 시작  (메모리: 1587.9 MB)
[메모리] forecast_sarima 실행 전: 1587.94 MB
[메모리] find_best_sarima_params 실행 전: 1587.94 MB
[메모리] find_best_sarima_params 실행 후: 1587.94 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1587.94 MB (변화: +0.00 MB)
[LXFR]   [SARIMA] 완료  첫값=9.15e+07 (메모리: 1587.9 MB)
[LXFR]   [ETS] 시작  (메모리: 1587.9 MB)
[메모리] forecast_ets 실행 전: 1587.94 MB
[메모리] forecast_ets 실행 후: 1587.95 MB (변화: +0.00 MB)
[LXFR]   [ETS] 완료  첫값=9.54e+07 (메모리: 1587.9 MB)
[LXFR]   [Prophet] 시작  (메모리: 1587.9 MB)

12:16:20 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1587.95 MB

12:16:21 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1588.32 MB (변화: +0.38 MB)
[LXFR]   [Prophet] 완료  첫값=9.36e+07 (메모리: 1588.3 MB)
[LXFR]   [LSTM] 시작  (메모리: 1588.3 MB)
[메모리] forecast_lstm 실행 전: 1588.32 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1588.18 MB (변화: -0.14 MB)
[LXFR]   [LSTM] 완료  첫값=9.09e+07 (메모리: 1588.2 MB)
[LXFR]   [Theta] 시작  (메모리: 1588.2 MB)
[메모리] forecast_theta 실행 전: 1588.18 MB
[메모리] forecast_theta 실행 후: 1588.18 MB (변화: +0.00 MB)
[LXFR]   [Theta] 완료  첫값=9.27e+07 (메모리: 1588.2 MB)
[LXFR]   [DB] 88행 저장 완료
[PROGRESS] [ 429/500] ( 85.8%)  >>  TROO
[TROO]   33분기 | 2009-06-30 ~ 2025-06-30
[TROO]   [SARIMA] 시작  (메모리: 1588.2 MB)
[메모리] forecast_sarima 실행 전: 1588.18 MB
[메모리] find_best_sarima_params 실행 전: 1588.18 MB
[메모리] find_best_sarima_params 실행 후: 1588.35 MB (변화: +0.17 MB)
[메모리] forecast_sarima 실행 후: 1588.35 MB (변화: +0.17 MB)
[TROO]   [SARIMA] 완료  첫값=3.31e+06 (메모리: 1588.4 MB)
[TROO]   [ETS] 시작  (메모리: 1588.4 MB)
[메모리] forecast_ets 실행 전: 1588.35 MB
[메모리] forecast_ets 실행 후: 1588.36 MB (변화: +0.00 MB)
[TROO]   [ETS] 완료  첫값=-6.99e+06 (메모리: 1588.4 MB)
[TROO]   [Prophet] 시작  (메모리: 1588.4 MB)

12:16:34 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1588.36 MB

12:16:34 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1588.43 MB (변화: +0.07 MB)
[TROO]   [Prophet] 완료  첫값=-1.85e+07 (메모리: 1588.4 MB)
[TROO]   [LSTM] 시작  (메모리: 1588.4 MB)
[메모리] forecast_lstm 실행 전: 1588.43 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1588.14 MB (변화: -0.29 MB)
[TROO]   [LSTM] 완료  첫값=2.74e+06 (메모리: 1588.1 MB)
[TROO]   [Theta] 시작  (메모리: 1588.1 MB)
[메모리] forecast_theta 실행 전: 1588.14 MB
[메모리] forecast_theta 실행 후: 1588.14 MB (변화: +0.00 MB)
[TROO]   [Theta] 완료  첫값=6.34e+06 (메모리: 1588.1 MB)
[TROO]   [DB] 81행 저장 완료
[PROGRESS] [ 430/500] ( 86.0%)  >>  CINR
[CINR]   40분기 | 2012-03-31 ~ 2021-12-31
[CINR]   [SARIMA] 시작  (메모리: 1588.1 MB)
[메모리] forecast_sarima 실행 전: 1588.14 MB
[메모리] find_best_sarima_params 실행 전: 1588.14 MB
[메모리] find_best_sarima_params 실행 후: 1588.14 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1588.14 MB (변화: +0.00 MB)
[CINR]   [SARIMA] 완료  첫값=1.57e+08 (메모리: 1588.1 MB)
[CINR]   [ETS] 시작  (메모리: 1588.1 MB)
[메모리] forecast_ets 실행 전: 1588.14 MB
[메모리] forecast_ets 실행 후: 1588.14 MB (변화: +0.00 MB)
[CINR]   [ETS] 완료  첫값=1.54e+08 (메모리: 1588.1 MB)
[CINR]   [Prophet] 시작  (메모리: 1588.1 MB)

12:16:49 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1588.14 MB

12:16:49 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1588.17 MB (변화: +0.02 MB)
[CINR]   [Prophet] 완료  첫값=1.25e+08 (메모리: 1588.2 MB)
[CINR]   [LSTM] 시작  (메모리: 1588.2 MB)
[메모리] forecast_lstm 실행 전: 1588.17 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1589.16 MB (변화: +1.00 MB)
[CINR]   [LSTM] 완료  첫값=1.19e+08 (메모리: 1589.2 MB)
[CINR]   [Theta] 시작  (메모리: 1589.2 MB)
[메모리] forecast_theta 실행 전: 1589.16 MB
[메모리] forecast_theta 실행 후: 1589.16 MB (변화: +0.00 MB)
[CINR]   [Theta] 완료  첫값=1.22e+08 (메모리: 1589.2 MB)
[CINR]   [DB] 88행 저장 완료
[PROGRESS] [ 431/500] ( 86.2%)  >>  GTN
[GTN]   40분기 | 2016-03-31 ~ 2025-12-31
[GTN]   [SARIMA] 시작  (메모리: 1589.2 MB)
[메모리] forecast_sarima 실행 전: 1589.16 MB
[메모리] find_best_sarima_params 실행 전: 1589.16 MB
[메모리] find_best_sarima_params 실행 후: 1589.16 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1589.16 MB (변화: +0.00 MB)
[GTN]   [SARIMA] 완료  첫값=8.23e+08 (메모리: 1589.2 MB)
[GTN]   [ETS] 시작  (메모리: 1589.2 MB)
[메모리] forecast_ets 실행 전: 1589.16 MB
[메모리] forecast_ets 실행 후: 1589.17 MB (변화: +0.00 MB)
[GTN]   [ETS] 완료  첫값=7.34e+08 (메모리: 1589.2 MB)
[GTN]   [Prophet] 시작  (메모리: 1589.2 MB)

12:17:04 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1589.17 MB

12:17:04 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1589.18 MB (변화: +0.01 MB)
[GTN]   [Prophet] 완료  첫값=1.02e+09 (메모리: 1589.2 MB)
[GTN]   [LSTM] 시작  (메모리: 1589.2 MB)
[메모리] forecast_lstm 실행 전: 1589.18 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1589.14 MB (변화: -0.04 MB)
[GTN]   [LSTM] 완료  첫값=8.68e+08 (메모리: 1589.1 MB)
[GTN]   [Theta] 시작  (메모리: 1589.1 MB)
[메모리] forecast_theta 실행 전: 1589.14 MB
[메모리] forecast_theta 실행 후: 1589.14 MB (변화: +0.00 MB)
[GTN]   [Theta] 완료  첫값=7.23e+08 (메모리: 1589.1 MB)
[GTN]   [DB] 88행 저장 완료
[PROGRESS] [ 432/500] ( 86.4%)  >>  CECE
[CECE]   40분기 | 2015-12-31 ~ 2025-12-31
[CECE]   [SARIMA] 시작  (메모리: 1589.1 MB)
[메모리] forecast_sarima 실행 전: 1589.14 MB
[메모리] find_best_sarima_params 실행 전: 1589.14 MB
[메모리] find_best_sarima_params 실행 후: 1589.14 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1589.14 MB (변화: +0.00 MB)
[CECE]   [SARIMA] 완료  첫값=2.19e+08 (메모리: 1589.1 MB)
[CECE]   [ETS] 시작  (메모리: 1589.1 MB)
[메모리] forecast_ets 실행 전: 1589.14 MB
[메모리] forecast_ets 실행 후: 1589.14 MB (변화: +0.00 MB)
[CECE]   [ETS] 완료  첫값=2.37e+08 (메모리: 1589.1 MB)
[CECE]   [Prophet] 시작  (메모리: 1589.1 MB)
[메모리] forecast_prophet 실행 전: 1589.14 MB

12:17:20 - cmdstanpy - INFO - Chain [1] start processing
12:17:20 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1589.17 MB (변화: +0.02 MB)
[CECE]   [Prophet] 완료  첫값=1.52e+08 (메모리: 1589.2 MB)
[CECE]   [LSTM] 시작  (메모리: 1589.2 MB)
[메모리] forecast_lstm 실행 전: 1589.17 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1589.14 MB (변화: -0.03 MB)
[CECE]   [LSTM] 완료  첫값=2.43e+08 (메모리: 1589.1 MB)
[CECE]   [Theta] 시작  (메모리: 1589.1 MB)
[메모리] forecast_theta 실행 전: 1589.14 MB
[메모리] forecast_theta 실행 후: 1589.14 MB (변화: +0.00 MB)
[CECE]   [Theta] 완료  첫값=2.29e+08 (메모리: 1589.1 MB)
[CECE]   [DB] 88행 저장 완료
[PROGRESS] [ 433/500] ( 86.6%)  >>  WILC
[WILC]   40분기 | 2016-03-31 ~ 2025-12-31
[WILC]   [SARIMA] 시작  (메모리: 1589.1 MB)
[메모리] forecast_sarima 실행 전: 1589.14 MB
[메모리] find_best_sarima_params 실행 전: 1589.14 MB
[메모리] find_best_sarima_params 실행 후: 1589.14 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1589.14 MB (변화: +0.00 MB)
[WILC]   [SARIMA] 완료  첫값=1.60e+08 (메모리: 1589.1 MB)
[WILC]   [ETS] 시작  (메모리: 1589.1 MB)
[메모리] forecast_ets 실행 전: 1589.14 MB
[메모리] forecast_ets 실행 후: 1589.14 MB (변화: +0.00 MB)
[WILC]   [ETS] 완료  첫값=1.79e+08 (메모리: 1589.1 MB)
[WILC]   [Prophet] 시작  (메모리: 1589.1 MB)

12:17:37 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1589.14 MB

12:17:38 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1589.15 MB (변화: +0.01 MB)
[WILC]   [Prophet] 완료  첫값=1.58e+08 (메모리: 1589.2 MB)
[WILC]   [LSTM] 시작  (메모리: 1589.2 MB)
[메모리] forecast_lstm 실행 전: 1589.15 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1589.14 MB (변화: -0.01 MB)
[WILC]   [LSTM] 완료  첫값=1.52e+08 (메모리: 1589.1 MB)
[WILC]   [Theta] 시작  (메모리: 1589.1 MB)
[메모리] forecast_theta 실행 전: 1589.14 MB
[메모리] forecast_theta 실행 후: 1589.14 MB (변화: +0.00 MB)
[WILC]   [Theta] 완료  첫값=1.68e+08 (메모리: 1589.1 MB)
[WILC]   [DB] 88행 저장 완료
[PROGRESS] [ 434/500] ( 86.8%)  >>  CO
[CO]   40분기 | 2012-09-30 ~ 2022-07-05
[CO]   [SARIMA] 시작  (메모리: 1589.1 MB)
[메모리] forecast_sarima 실행 전: 1589.14 MB
[메모리] find_best_sarima_params 실행 전: 1589.14 MB
[메모리] find_best_sarima_params 실행 후: 1589.14 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1589.14 MB (변화: +0.00 MB)
[CO]   [SARIMA] 완료  첫값=3.03e+08 (메모리: 1589.1 MB)
[CO]   [ETS] 시작  (메모리: 1589.1 MB)
[메모리] forecast_ets 실행 전: 1589.14 MB
[메모리] forecast_ets 실행 후: 1589.14 MB (변화: +0.00 MB)
[CO]   [ETS] 완료  첫값=3.12e+08 (메모리: 1589.1 MB)
[CO]   [Prophet] 시작  (메모리: 1589.1 MB)

12:17:55 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1589.14 MB

12:17:55 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1589.15 MB (변화: +0.01 MB)
[CO]   [Prophet] 완료  첫값=3.30e+08 (메모리: 1589.1 MB)
[CO]   [LSTM] 시작  (메모리: 1589.1 MB)
[메모리] forecast_lstm 실행 전: 1589.15 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1587.39 MB (변화: -1.75 MB)
[CO]   [LSTM] 완료  첫값=3.16e+08 (메모리: 1587.4 MB)
[CO]   [Theta] 시작  (메모리: 1587.4 MB)
[메모리] forecast_theta 실행 전: 1587.39 MB
[메모리] forecast_theta 실행 후: 1587.39 MB (변화: +0.00 MB)
[CO]   [Theta] 완료  첫값=3.09e+08 (메모리: 1587.4 MB)
[CO]   [DB] 88행 저장 완료
[PROGRESS] [ 435/500] ( 87.0%)  >>  TRX
[TRX]   40분기 | 2016-02-29 ~ 2025-11-30
[TRX]   [SARIMA] 시작  (메모리: 1587.4 MB)
[메모리] forecast_sarima 실행 전: 1587.39 MB
[메모리] find_best_sarima_params 실행 전: 1587.39 MB
[메모리] find_best_sarima_params 실행 후: 1587.39 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1587.39 MB (변화: +0.00 MB)
[TRX]   [SARIMA] 완료  첫값=2.84e+07 (메모리: 1587.4 MB)
[TRX]   [ETS] 시작  (메모리: 1587.4 MB)
[메모리] forecast_ets 실행 전: 1587.39 MB
[메모리] forecast_ets 실행 후: 1587.40 MB (변화: +0.00 MB)
[TRX]   [ETS] 완료  첫값=3.61e+07 (메모리: 1587.4 MB)
[TRX]   [Prophet] 시작  (메모리: 1587.4 MB)

12:18:08 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1587.40 MB

12:18:08 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1587.43 MB (변화: +0.03 MB)
[TRX]   [Prophet] 완료  첫값=1.86e+07 (메모리: 1587.4 MB)
[TRX]   [LSTM] 시작  (메모리: 1587.4 MB)
[메모리] forecast_lstm 실행 전: 1587.43 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1588.39 MB (변화: +0.96 MB)
[TRX]   [LSTM] 완료  첫값=3.52e+07 (메모리: 1588.4 MB)
[TRX]   [Theta] 시작  (메모리: 1588.4 MB)
[메모리] forecast_theta 실행 전: 1588.39 MB
[메모리] forecast_theta 실행 후: 1588.39 MB (변화: +0.00 MB)
[TRX]   [Theta] 완료  첫값=3.44e+07 (메모리: 1588.4 MB)
[TRX]   [DB] 88행 저장 완료
[PROGRESS] [ 436/500] ( 87.2%)  >>  QUOT
[QUOT]   40분기 | 2013-09-30 ~ 2023-06-30
[QUOT]   [SARIMA] 시작  (메모리: 1588.4 MB)
[메모리] forecast_sarima 실행 전: 1588.39 MB
[메모리] find_best_sarima_params 실행 전: 1588.39 MB
[메모리] find_best_sarima_params 실행 후: 1588.39 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1588.39 MB (변화: +0.00 MB)
[QUOT]   [SARIMA] 완료  첫값=8.43e+07 (메모리: 1588.4 MB)
[QUOT]   [ETS] 시작  (메모리: 1588.4 MB)
[메모리] forecast_ets 실행 전: 1588.39 MB
[메모리] forecast_ets 실행 후: 1588.39 MB (변화: +0.00 MB)
[QUOT]   [ETS] 완료  첫값=7.29e+07 (메모리: 1588.4 MB)
[QUOT]   [Prophet] 시작  (메모리: 1588.4 MB)

12:18:24 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1588.39 MB

12:18:25 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1588.41 MB (변화: +0.02 MB)
[QUOT]   [Prophet] 완료  첫값=1.11e+08 (메모리: 1588.4 MB)
[QUOT]   [LSTM] 시작  (메모리: 1588.4 MB)
[메모리] forecast_lstm 실행 전: 1588.41 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1588.31 MB (변화: -0.10 MB)
[QUOT]   [LSTM] 완료  첫값=9.22e+07 (메모리: 1588.3 MB)
[QUOT]   [Theta] 시작  (메모리: 1588.3 MB)
[메모리] forecast_theta 실행 전: 1588.31 MB
[메모리] forecast_theta 실행 후: 1588.31 MB (변화: +0.00 MB)
[QUOT]   [Theta] 완료  첫값=7.30e+07 (메모리: 1588.3 MB)
[QUOT]   [DB] 88행 저장 완료
[PROGRESS] [ 437/500] ( 87.4%)  >>  SSP
[SSP]   40분기 | 2016-03-31 ~ 2025-12-31
[SSP]   [SARIMA] 시작  (메모리: 1588.3 MB)
[메모리] forecast_sarima 실행 전: 1588.31 MB
[메모리] find_best_sarima_params 실행 전: 1588.31 MB
[메모리] find_best_sarima_params 실행 후: 1588.31 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1588.31 MB (변화: +0.00 MB)
[SSP]   [SARIMA] 완료  첫값=4.82e+08 (메모리: 1588.3 MB)
[SSP]   [ETS] 시작  (메모리: 1588.3 MB)
[메모리] forecast_ets 실행 전: 1588.31 MB
[메모리] forecast_ets 실행 후: 1588.32 MB (변화: +0.00 MB)
[SSP]   [ETS] 완료  첫값=4.66e+08 (메모리: 1588.3 MB)
[SSP]   [Prophet] 시작  (메모리: 1588.3 MB)

12:18:44 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1588.32 MB

12:18:45 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1587.97 MB (변화: -0.34 MB)
[SSP]   [Prophet] 완료  첫값=6.95e+08 (메모리: 1588.0 MB)
[SSP]   [LSTM] 시작  (메모리: 1588.0 MB)
[메모리] forecast_lstm 실행 전: 1587.97 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1587.81 MB (변화: -0.16 MB)
[SSP]   [LSTM] 완료  첫값=5.95e+08 (메모리: 1587.8 MB)
[SSP]   [Theta] 시작  (메모리: 1587.8 MB)
[메모리] forecast_theta 실행 전: 1587.81 MB
[메모리] forecast_theta 실행 후: 1587.81 MB (변화: +0.00 MB)
[SSP]   [Theta] 완료  첫값=4.77e+08 (메모리: 1587.8 MB)
[SSP]   [DB] 88행 저장 완료
[PROGRESS] [ 438/500] ( 87.6%)  >>  NBY
[NBY] [NEG-SKIP] [NBY] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2025, 12, 31)])
[PROGRESS] [ 439/500] ( 87.8%)  >>  TTGT
[TTGT]   40분기 | 2016-03-31 ~ 2025-12-31
[TTGT]   [SARIMA] 시작  (메모리: 1587.8 MB)
[메모리] forecast_sarima 실행 전: 1587.81 MB
[메모리] find_best_sarima_params 실행 전: 1587.81 MB
[메모리] find_best_sarima_params 실행 후: 1587.81 MB (변화: +0.00 MB)
[메모리] find_best_sarima_params 실행 전: 1587.81 MB
[메모리] find_best_sarima_params 실행 후: 1587.81 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1587.81 MB (변화: +0.00 MB)
[TTGT]   [SARIMA] 완료  첫값=2.74e+03 (메모리: 1587.8 MB)
[TTGT]   [ETS] 시작  (메모리: 1587.8 MB)
[메모리] forecast_ets 실행 전: 1587.81 MB
[메모리] forecast_ets 실행 후: 1587.81 MB (변화: +0.00 MB)
[TTGT]   [ETS] 완료  첫값=1.04e+08 (메모리: 1587.8 MB)
[TTGT]   [Prophet] 시작  (메모리: 1587.8 MB)

12:19:09 - cmdstanpy - INFO - Chain [1] start processing
12:19:09 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1587.81 MB
[메모리] forecast_prophet 실행 후: 1588.56 MB (변화: +0.75 MB)
[TTGT]   [Prophet] 완료  첫값=8.84e+07 (메모리: 1588.6 MB)
[TTGT]   [LSTM] 시작  (메모리: 1588.6 MB)
[메모리] forecast_lstm 실행 전: 1588.56 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1588.16 MB (변화: -0.40 MB)
[TTGT]   [LSTM] 완료  첫값=8.46e+07 (메모리: 1588.2 MB)
[TTGT]   [Theta] 시작  (메모리: 1588.2 MB)
[메모리] forecast_theta 실행 전: 1588.16 MB
[메모리] forecast_theta 실행 후: 1588.16 MB (변화: +0.00 MB)
[TTGT]   [Theta] 완료  첫값=4.79e+07 (메모리: 1588.2 MB)
[TTGT]   [DB] 88행 저장 완료
[PROGRESS] [ 440/500] ( 88.0%)  >>  RCKT
[RCKT]   40분기 | 2016-03-31 ~ 2025-12-31
[RCKT]   [SARIMA] 시작  (메모리: 1588.2 MB)
[메모리] forecast_sarima 실행 전: 1588.16 MB
[메모리] find_best_sarima_params 실행 전: 1588.16 MB
[메모리] find_best_sarima_params 실행 후: 1588.16 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1588.16 MB (변화: +0.00 MB)
[RCKT]   [SARIMA] 완료  첫값=0.00e+00 (메모리: 1588.2 MB)
[RCKT]   [ETS] 시작  (메모리: 1588.2 MB)
[메모리] forecast_ets 실행 전: 1588.16 MB
[메모리] forecast_ets 실행 후: 1588.16 MB (변화: +0.00 MB)
[RCKT]   [ETS] 완료  첫값=0.00e+00 (메모리: 1588.2 MB)
[RCKT]   [Prophet] 시작  (메모리: 1588.2 MB)
[메모리] forecast_prophet 실행 전: 1588.16 MB
[메모리] forecast_prophet 실행 후: 1587.81 MB (변화: -0.35 MB)
[RCKT]   [Prophet] 완료  첫값=0.00e+00 (메모리: 1587.8 MB)
[RCKT]   [LSTM] 시작  (메모리: 1587.8 MB)
[메모리] forecast_lstm 실행 전: 1587.81 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1588.77 MB (변화: +0.96 MB)
[RCKT]   [LSTM] 완료  첫값=0.00e+00 (메모리: 1588.8 MB)
[RCKT]   [Theta] 시작  (메모리: 1588.8 MB)
[메모리] forecast_theta 실행 전: 1588.77 MB
[메모리] forecast_theta 실행 후: 1588.77 MB (변화: +0.00 MB)
[RCKT]   [Theta] 완료  첫값=0.00e+00 (메모리: 1588.8 MB)
[RCKT]   [DB] 88행 저장 완료
[PROGRESS] [ 441/500] ( 88.2%)  >>  MTRX
[MTRX]   40분기 | 2016-03-31 ~ 2025-12-31
[MTRX]   [SARIMA] 시작  (메모리: 1588.8 MB)
[메모리] forecast_sarima 실행 전: 1588.77 MB
[메모리] find_best_sarima_params 실행 전: 1588.77 MB
[메모리] find_best_sarima_params 실행 후: 1588.77 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1588.77 MB (변화: +0.00 MB)
[MTRX]   [SARIMA] 완료  첫값=2.11e+08 (메모리: 1588.8 MB)
[MTRX]   [ETS] 시작  (메모리: 1588.8 MB)
[메모리] forecast_ets 실행 전: 1588.77 MB
[메모리] forecast_ets 실행 후: 1588.77 MB (변화: +0.00 MB)
[MTRX]   [ETS] 완료  첫값=1.97e+08 (메모리: 1588.8 MB)
[MTRX]   [Prophet] 시작  (메모리: 1588.8 MB)

12:19:42 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1588.77 MB

12:19:42 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1588.32 MB (변화: -0.45 MB)
[MTRX]   [Prophet] 완료  첫값=1.53e+08 (메모리: 1588.3 MB)
[MTRX]   [LSTM] 시작  (메모리: 1588.3 MB)
[메모리] forecast_lstm 실행 전: 1588.32 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1589.29 MB (변화: +0.97 MB)
[MTRX]   [LSTM] 완료  첫값=1.92e+08 (메모리: 1589.3 MB)
[MTRX]   [Theta] 시작  (메모리: 1589.3 MB)
[메모리] forecast_theta 실행 전: 1589.29 MB
[메모리] forecast_theta 실행 후: 1589.29 MB (변화: +0.00 MB)
[MTRX]   [Theta] 완료  첫값=1.98e+08 (메모리: 1589.3 MB)
[MTRX]   [DB] 88행 저장 완료
[PROGRESS] [ 442/500] ( 88.4%)  >>  DSKE
[DSKE]   34분기 | 2015-09-30 ~ 2023-12-31
[DSKE]   [SARIMA] 시작  (메모리: 1589.3 MB)
[메모리] forecast_sarima 실행 전: 1589.29 MB
[메모리] find_best_sarima_params 실행 전: 1589.29 MB
[메모리] find_best_sarima_params 실행 후: 1589.30 MB (변화: +0.01 MB)
[메모리] forecast_sarima 실행 후: 1589.30 MB (변화: +0.01 MB)
[DSKE]   [SARIMA] 완료  첫값=3.69e+08 (메모리: 1589.3 MB)
[DSKE]   [ETS] 시작  (메모리: 1589.3 MB)
[메모리] forecast_ets 실행 전: 1589.30 MB
[메모리] forecast_ets 실행 후: 1589.30 MB (변화: +0.00 MB)
[DSKE]   [ETS] 완료  첫값=3.47e+08 (메모리: 1589.3 MB)
[DSKE]   [Prophet] 시작  (메모리: 1589.3 MB)

12:19:58 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1589.30 MB

12:19:58 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1589.33 MB (변화: +0.02 MB)
[DSKE]   [Prophet] 완료  첫값=4.83e+08 (메모리: 1589.3 MB)
[DSKE]   [LSTM] 시작  (메모리: 1589.3 MB)
[메모리] forecast_lstm 실행 전: 1589.33 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1589.35 MB (변화: +0.02 MB)
[DSKE]   [LSTM] 완료  첫값=3.92e+08 (메모리: 1589.3 MB)
[DSKE]   [Theta] 시작  (메모리: 1589.3 MB)
[메모리] forecast_theta 실행 전: 1589.35 MB
[메모리] forecast_theta 실행 후: 1589.35 MB (변화: +0.00 MB)
[DSKE]   [Theta] 완료  첫값=3.67e+08 (메모리: 1589.3 MB)
[DSKE]   [DB] 82행 저장 완료
[PROGRESS] [ 443/500] ( 88.6%)  >>  LSAK
[LSAK]   40분기 | 2016-03-31 ~ 2025-12-31
[LSAK]   [SARIMA] 시작  (메모리: 1589.3 MB)
[메모리] forecast_sarima 실행 전: 1589.35 MB
[메모리] find_best_sarima_params 실행 전: 1589.35 MB
[메모리] find_best_sarima_params 실행 후: 1589.35 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1589.35 MB (변화: +0.00 MB)
[LSAK]   [SARIMA] 완료  첫값=1.79e+08 (메모리: 1589.3 MB)
[LSAK]   [ETS] 시작  (메모리: 1589.3 MB)
[메모리] forecast_ets 실행 전: 1589.35 MB
[메모리] forecast_ets 실행 후: 1589.35 MB (변화: +0.00 MB)
[LSAK]   [ETS] 완료  첫값=1.73e+08 (메모리: 1589.4 MB)
[LSAK]   [Prophet] 시작  (메모리: 1589.4 MB)

12:20:16 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1589.35 MB

12:20:16 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1589.36 MB (변화: +0.00 MB)
[LSAK]   [Prophet] 완료  첫값=1.29e+08 (메모리: 1589.4 MB)
[LSAK]   [LSTM] 시작  (메모리: 1589.4 MB)
[메모리] forecast_lstm 실행 전: 1589.36 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1589.88 MB (변화: +0.52 MB)
[LSAK]   [LSTM] 완료  첫값=1.64e+08 (메모리: 1589.9 MB)
[LSAK]   [Theta] 시작  (메모리: 1589.9 MB)
[메모리] forecast_theta 실행 전: 1589.88 MB
[메모리] forecast_theta 실행 후: 1589.88 MB (변화: +0.00 MB)
[LSAK]   [Theta] 완료  첫값=1.72e+08 (메모리: 1589.9 MB)
[LSAK]   [DB] 88행 저장 완료
[PROGRESS] [ 444/500] ( 88.8%)  >>  KFS
[KFS]   40분기 | 2016-03-31 ~ 2025-12-31
[KFS]   [SARIMA] 시작  (메모리: 1589.9 MB)
[메모리] forecast_sarima 실행 전: 1589.88 MB
[메모리] find_best_sarima_params 실행 전: 1589.88 MB
[메모리] find_best_sarima_params 실행 후: 1589.88 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1589.88 MB (변화: +0.00 MB)
[KFS]   [SARIMA] 완료  첫값=4.27e+07 (메모리: 1589.9 MB)
[KFS]   [ETS] 시작  (메모리: 1589.9 MB)
[메모리] forecast_ets 실행 전: 1589.88 MB
[메모리] forecast_ets 실행 후: 1589.88 MB (변화: +0.00 MB)
[KFS]   [ETS] 완료  첫값=4.51e+07 (메모리: 1589.9 MB)
[KFS]   [Prophet] 시작  (메모리: 1589.9 MB)

12:20:35 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1589.88 MB

12:20:35 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1590.14 MB (변화: +0.26 MB)
[KFS]   [Prophet] 완료  첫값=2.24e+07 (메모리: 1590.1 MB)
[KFS]   [LSTM] 시작  (메모리: 1590.1 MB)
[메모리] forecast_lstm 실행 전: 1590.14 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1589.48 MB (변화: -0.66 MB)
[KFS]   [LSTM] 완료  첫값=2.67e+07 (메모리: 1589.5 MB)
[KFS]   [Theta] 시작  (메모리: 1589.5 MB)
[메모리] forecast_theta 실행 전: 1589.48 MB
[메모리] forecast_theta 실행 후: 1589.48 MB (변화: +0.00 MB)
[KFS]   [Theta] 완료  첫값=3.83e+07 (메모리: 1589.5 MB)
[KFS]   [DB] 88행 저장 완료
[PROGRESS] [ 445/500] ( 89.0%)  >>  CTGO
[CTGO]   40분기 | 2016-03-31 ~ 2025-12-31
[CTGO]   [SARIMA] 시작  (메모리: 1589.5 MB)
[메모리] forecast_sarima 실행 전: 1589.48 MB
[메모리] find_best_sarima_params 실행 전: 1589.48 MB
[메모리] find_best_sarima_params 실행 후: 1589.48 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1589.48 MB (변화: +0.00 MB)
[CTGO]   [SARIMA] 완료  첫값=0.00e+00 (메모리: 1589.5 MB)
[CTGO]   [ETS] 시작  (메모리: 1589.5 MB)
[메모리] forecast_ets 실행 전: 1589.48 MB
[메모리] forecast_ets 실행 후: 1589.48 MB (변화: +0.00 MB)
[CTGO]   [ETS] 완료  첫값=0.00e+00 (메모리: 1589.5 MB)
[CTGO]   [Prophet] 시작  (메모리: 1589.5 MB)
[메모리] forecast_prophet 실행 전: 1589.48 MB
[메모리] forecast_prophet 실행 후: 1589.50 MB (변화: +0.02 MB)
[CTGO]   [Prophet] 완료  첫값=0.00e+00 (메모리: 1589.5 MB)
[CTGO]   [LSTM] 시작  (메모리: 1589.5 MB)
[메모리] forecast_lstm 실행 전: 1589.50 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1590.46 MB (변화: +0.96 MB)
[CTGO]   [LSTM] 완료  첫값=0.00e+00 (메모리: 1590.5 MB)
[CTGO]   [Theta] 시작  (메모리: 1590.5 MB)
[메모리] forecast_theta 실행 전: 1590.46 MB
[메모리] forecast_theta 실행 후: 1590.46 MB (변화: +0.00 MB)
[CTGO]   [Theta] 완료  첫값=0.00e+00 (메모리: 1590.5 MB)
[CTGO]   [DB] 88행 저장 완료
[PROGRESS] [ 446/500] ( 89.2%)  >>  TITN
[TITN]   40분기 | 2016-04-30 ~ 2026-01-31
[TITN]   [SARIMA] 시작  (메모리: 1590.5 MB)
[메모리] forecast_sarima 실행 전: 1590.46 MB
[메모리] find_best_sarima_params 실행 전: 1590.46 MB
[메모리] find_best_sarima_params 실행 후: 1589.34 MB (변화: -1.11 MB)
[메모리] forecast_sarima 실행 후: 1589.34 MB (변화: -1.11 MB)
[TITN]   [SARIMA] 완료  첫값=5.52e+08 (메모리: 1589.3 MB)
[TITN]   [ETS] 시작  (메모리: 1589.3 MB)
[메모리] forecast_ets 실행 전: 1589.34 MB
[메모리] forecast_ets 실행 후: 1589.35 MB (변화: +0.00 MB)
[TITN]   [ETS] 완료  첫값=5.00e+08 (메모리: 1589.3 MB)
[TITN]   [Prophet] 시작  (메모리: 1589.3 MB)

12:21:11 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1589.35 MB

12:21:11 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1589.36 MB (변화: +0.01 MB)
[TITN]   [Prophet] 완료  첫값=7.08e+08 (메모리: 1589.4 MB)
[TITN]   [LSTM] 시작  (메모리: 1589.4 MB)
[메모리] forecast_lstm 실행 전: 1589.36 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1590.29 MB (변화: +0.93 MB)
[TITN]   [LSTM] 완료  첫값=7.08e+08 (메모리: 1590.3 MB)
[TITN]   [Theta] 시작  (메모리: 1590.3 MB)
[메모리] forecast_theta 실행 전: 1590.29 MB
[메모리] forecast_theta 실행 후: 1590.29 MB (변화: +0.00 MB)
[TITN]   [Theta] 완료  첫값=5.32e+08 (메모리: 1590.3 MB)
[TITN]   [DB] 88행 저장 완료
[PROGRESS] [ 447/500] ( 89.4%)  >>  ESEA
[ESEA]   40분기 | 2016-03-31 ~ 2025-12-31
[ESEA]   [SARIMA] 시작  (메모리: 1590.3 MB)
[메모리] forecast_sarima 실행 전: 1590.29 MB
[메모리] find_best_sarima_params 실행 전: 1590.29 MB
[메모리] find_best_sarima_params 실행 후: 1590.29 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1590.29 MB (변화: +0.00 MB)
[ESEA]   [SARIMA] 완료  첫값=5.66e+07 (메모리: 1590.3 MB)
[ESEA]   [ETS] 시작  (메모리: 1590.3 MB)
[메모리] forecast_ets 실행 전: 1590.29 MB
[메모리] forecast_ets 실행 후: 1590.30 MB (변화: +0.00 MB)
[ESEA]   [ETS] 완료  첫값=6.08e+07 (메모리: 1590.3 MB)
[ESEA]   [Prophet] 시작  (메모리: 1590.3 MB)

12:21:30 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1590.30 MB

12:21:30 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1590.31 MB (변화: +0.02 MB)
[ESEA]   [Prophet] 완료  첫값=6.06e+07 (메모리: 1590.3 MB)
[ESEA]   [LSTM] 시작  (메모리: 1590.3 MB)
[메모리] forecast_lstm 실행 전: 1590.31 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1590.30 MB (변화: -0.01 MB)
[ESEA]   [LSTM] 완료  첫값=5.76e+07 (메모리: 1590.3 MB)
[ESEA]   [Theta] 시작  (메모리: 1590.3 MB)
[메모리] forecast_theta 실행 전: 1590.30 MB
[메모리] forecast_theta 실행 후: 1590.30 MB (변화: +0.00 MB)
[ESEA]   [Theta] 완료  첫값=5.81e+07 (메모리: 1590.3 MB)
[ESEA]   [DB] 88행 저장 완료
[PROGRESS] [ 448/500] ( 89.6%)  >>  RVNC
[RVNC]   40분기 | 2014-12-31 ~ 2024-09-30
[RVNC]   [SARIMA] 시작  (메모리: 1590.3 MB)
[메모리] forecast_sarima 실행 전: 1590.30 MB
[메모리] find_best_sarima_params 실행 전: 1590.30 MB
[메모리] find_best_sarima_params 실행 후: 1590.30 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1590.30 MB (변화: +0.00 MB)
[RVNC]   [SARIMA] 완료  첫값=8.88e+07 (메모리: 1590.3 MB)
[RVNC]   [ETS] 시작  (메모리: 1590.3 MB)
[메모리] forecast_ets 실행 전: 1590.30 MB
[메모리] forecast_ets 실행 후: 1590.30 MB (변화: +0.00 MB)
[RVNC]   [ETS] 완료  첫값=7.26e+07 (메모리: 1590.3 MB)
[RVNC]   [Prophet] 시작  (메모리: 1590.3 MB)

12:21:45 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1590.30 MB

12:21:45 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1590.34 MB (변화: +0.03 MB)
[RVNC]   [Prophet] 완료  첫값=5.04e+07 (메모리: 1590.3 MB)
[RVNC]   [LSTM] 시작  (메모리: 1590.3 MB)
[메모리] forecast_lstm 실행 전: 1590.34 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1590.30 MB (변화: -0.04 MB)
[RVNC]   [LSTM] 완료  첫값=8.60e+07 (메모리: 1590.3 MB)
[RVNC]   [Theta] 시작  (메모리: 1590.3 MB)
[메모리] forecast_theta 실행 전: 1590.30 MB
[메모리] forecast_theta 실행 후: 1590.30 MB (변화: +0.00 MB)
[RVNC]   [Theta] 완료  첫값=6.47e+07 (메모리: 1590.3 MB)
[RVNC]   [DB] 88행 저장 완료
[PROGRESS] [ 449/500] ( 89.8%)  >>  ACTG
[ACTG]   40분기 | 2016-03-31 ~ 2025-12-31
[ACTG]   [SARIMA] 시작  (메모리: 1590.3 MB)
[메모리] forecast_sarima 실행 전: 1590.30 MB
[메모리] find_best_sarima_params 실행 전: 1590.30 MB
[메모리] find_best_sarima_params 실행 후: 1590.30 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1590.30 MB (변화: +0.00 MB)
[ACTG]   [SARIMA] 완료  첫값=3.67e+07 (메모리: 1590.3 MB)
[ACTG]   [ETS] 시작  (메모리: 1590.3 MB)
[메모리] forecast_ets 실행 전: 1590.30 MB
[메모리] forecast_ets 실행 후: 1590.30 MB (변화: +0.00 MB)
[ACTG]   [ETS] 완료  첫값=8.33e+07 (메모리: 1590.3 MB)
[ACTG]   [Prophet] 시작  (메모리: 1590.3 MB)

12:22:01 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1590.30 MB

12:22:02 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1590.34 MB (변화: +0.04 MB)
[ACTG]   [Prophet] 완료  첫값=4.08e+07 (메모리: 1590.3 MB)
[ACTG]   [LSTM] 시작  (메모리: 1590.3 MB)
[메모리] forecast_lstm 실행 전: 1590.34 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1590.68 MB (변화: +0.34 MB)
[ACTG]   [LSTM] 완료  첫값=5.57e+07 (메모리: 1590.7 MB)
[ACTG]   [Theta] 시작  (메모리: 1590.7 MB)
[메모리] forecast_theta 실행 전: 1590.68 MB
[메모리] forecast_theta 실행 후: 1590.68 MB (변화: +0.00 MB)
[ACTG]   [Theta] 완료  첫값=5.31e+07 (메모리: 1590.7 MB)
[ACTG]   [DB] 88행 저장 완료
[PROGRESS] [ 450/500] ( 90.0%)  >>  AKBA
[AKBA]   40분기 | 2016-03-31 ~ 2025-12-31
[AKBA]   [SARIMA] 시작  (메모리: 1590.7 MB)
[메모리] forecast_sarima 실행 전: 1590.68 MB
[메모리] find_best_sarima_params 실행 전: 1590.68 MB
[메모리] find_best_sarima_params 실행 후: 1590.68 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1590.68 MB (변화: +0.00 MB)
[AKBA]   [SARIMA] 완료  첫값=5.66e+07 (메모리: 1590.7 MB)
[AKBA]   [ETS] 시작  (메모리: 1590.7 MB)
[메모리] forecast_ets 실행 전: 1590.68 MB
[메모리] forecast_ets 실행 후: 1590.68 MB (변화: +0.00 MB)
[AKBA]   [ETS] 완료  첫값=5.71e+07 (메모리: 1590.7 MB)
[AKBA]   [Prophet] 시작  (메모리: 1590.7 MB)

12:22:19 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1590.68 MB

12:22:19 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1590.70 MB (변화: +0.02 MB)
[AKBA]   [Prophet] 완료  첫값=6.62e+07 (메모리: 1590.7 MB)
[AKBA]   [LSTM] 시작  (메모리: 1590.7 MB)
[메모리] forecast_lstm 실행 전: 1590.70 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1591.64 MB (변화: +0.95 MB)
[AKBA]   [LSTM] 완료  첫값=6.19e+07 (메모리: 1591.6 MB)
[AKBA]   [Theta] 시작  (메모리: 1591.6 MB)
[메모리] forecast_theta 실행 전: 1591.64 MB
[메모리] forecast_theta 실행 후: 1591.64 MB (변화: +0.00 MB)
[AKBA]   [Theta] 완료  첫값=5.85e+07 (메모리: 1591.6 MB)
[AKBA]   [DB] 88행 저장 완료
[PROGRESS] [ 451/500] ( 90.2%)  >>  VSTM
[VSTM]   40분기 | 2016-03-31 ~ 2025-12-31
[VSTM]   [SARIMA] 시작  (메모리: 1591.6 MB)
[메모리] forecast_sarima 실행 전: 1591.64 MB
[메모리] find_best_sarima_params 실행 전: 1591.64 MB
[메모리] find_best_sarima_params 실행 후: 1591.64 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1591.64 MB (변화: +0.00 MB)
[VSTM]   [SARIMA] 완료  첫값=3.56e+06 (메모리: 1591.6 MB)
[VSTM]   [ETS] 시작  (메모리: 1591.6 MB)
[메모리] forecast_ets 실행 전: 1591.64 MB
[메모리] forecast_ets 실행 후: 1591.64 MB (변화: +0.00 MB)
[VSTM]   [ETS] 완료  첫값=4.13e+06 (메모리: 1591.6 MB)
[VSTM]   [Prophet] 시작  (메모리: 1591.6 MB)

12:22:36 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1591.64 MB

12:22:36 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1591.66 MB (변화: +0.02 MB)
[VSTM]   [Prophet] 완료  첫값=5.19e+06 (메모리: 1591.7 MB)
[VSTM]   [LSTM] 시작  (메모리: 1591.7 MB)
[메모리] forecast_lstm 실행 전: 1591.66 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1591.64 MB (변화: -0.02 MB)
[VSTM]   [LSTM] 완료  첫값=8.43e+06 (메모리: 1591.6 MB)
[VSTM]   [Theta] 시작  (메모리: 1591.6 MB)
[메모리] forecast_theta 실행 전: 1591.64 MB
[메모리] forecast_theta 실행 후: 1591.64 MB (변화: +0.00 MB)
[VSTM]   [Theta] 완료  첫값=4.33e+06 (메모리: 1591.6 MB)
[VSTM]   [DB] 88행 저장 완료
[PROGRESS] [ 452/500] ( 90.4%)  >>  RC
[RC] [NEG-SKIP] [RC] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2024, 3, 31), datetime.date(2024, 6, 30), datetime.date(2025, 3, 31), datetime.date(2025, 6, 30)])
[PROGRESS] [ 453/500] ( 90.6%)  >>  DBI
[DBI]   40분기 | 2016-04-30 ~ 2026-01-31
[DBI]   [SARIMA] 시작  (메모리: 1591.6 MB)
[메모리] forecast_sarima 실행 전: 1591.64 MB
[메모리] find_best_sarima_params 실행 전: 1591.64 MB
[메모리] find_best_sarima_params 실행 후: 1591.64 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1591.64 MB (변화: +0.00 MB)
[DBI]   [SARIMA] 완료  첫값=7.15e+08 (메모리: 1591.6 MB)
[DBI]   [ETS] 시작  (메모리: 1591.6 MB)
[메모리] forecast_ets 실행 전: 1591.64 MB
[메모리] forecast_ets 실행 후: 1591.65 MB (변화: +0.00 MB)
[DBI]   [ETS] 완료  첫값=6.82e+08 (메모리: 1591.6 MB)
[DBI]   [Prophet] 시작  (메모리: 1591.6 MB)

12:22:57 - cmdstanpy - INFO - Chain [1] start processing
12:22:57 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1591.65 MB
[메모리] forecast_prophet 실행 후: 1591.68 MB (변화: +0.03 MB)
[DBI]   [Prophet] 완료  첫값=7.72e+08 (메모리: 1591.7 MB)
[DBI]   [LSTM] 시작  (메모리: 1591.7 MB)
[메모리] forecast_lstm 실행 전: 1591.68 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1590.55 MB (변화: -1.12 MB)
[DBI]   [LSTM] 완료  첫값=7.24e+08 (메모리: 1590.6 MB)
[DBI]   [Theta] 시작  (메모리: 1590.6 MB)
[메모리] forecast_theta 실행 전: 1590.55 MB
[메모리] forecast_theta 실행 후: 1590.55 MB (변화: +0.00 MB)
[DBI]   [Theta] 완료  첫값=7.14e+08 (메모리: 1590.6 MB)
[DBI]   [DB] 88행 저장 완료
[PROGRESS] [ 454/500] ( 90.8%)  >>  LCTX
[LCTX]   40분기 | 2016-03-31 ~ 2025-12-31
[LCTX]   [SARIMA] 시작  (메모리: 1590.6 MB)
[메모리] forecast_sarima 실행 전: 1590.55 MB
[메모리] find_best_sarima_params 실행 전: 1590.55 MB
[메모리] find_best_sarima_params 실행 후: 1590.55 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1590.55 MB (변화: +0.00 MB)
[LCTX]   [SARIMA] 완료  첫값=4.42e+06 (메모리: 1590.6 MB)
[LCTX]   [ETS] 시작  (메모리: 1590.6 MB)
[메모리] forecast_ets 실행 전: 1590.55 MB
[메모리] forecast_ets 실행 후: 1590.55 MB (변화: +0.00 MB)
[LCTX]   [ETS] 완료  첫값=4.46e+06 (메모리: 1590.6 MB)
[LCTX]   [Prophet] 시작  (메모리: 1590.6 MB)

12:23:11 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1590.55 MB

12:23:11 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1590.57 MB (변화: +0.02 MB)
[LCTX]   [Prophet] 완료  첫값=3.40e+06 (메모리: 1590.6 MB)
[LCTX]   [LSTM] 시작  (메모리: 1590.6 MB)
[메모리] forecast_lstm 실행 전: 1590.57 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1591.55 MB (변화: +0.98 MB)
[LCTX]   [LSTM] 완료  첫값=2.71e+06 (메모리: 1591.6 MB)
[LCTX]   [Theta] 시작  (메모리: 1591.6 MB)
[메모리] forecast_theta 실행 전: 1591.55 MB
[메모리] forecast_theta 실행 후: 1591.55 MB (변화: +0.00 MB)
[LCTX]   [Theta] 완료  첫값=4.19e+06 (메모리: 1591.6 MB)
[LCTX]   [DB] 88행 저장 완료
[PROGRESS] [ 455/500] ( 91.0%)  >>  ISSC
[ISSC]   40분기 | 2016-03-31 ~ 2025-12-31
[ISSC]   [SARIMA] 시작  (메모리: 1591.6 MB)
[메모리] forecast_sarima 실행 전: 1591.55 MB
[메모리] find_best_sarima_params 실행 전: 1591.55 MB
[메모리] find_best_sarima_params 실행 후: 1591.55 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1591.55 MB (변화: +0.00 MB)
[ISSC]   [SARIMA] 완료  첫값=2.49e+07 (메모리: 1591.6 MB)
[ISSC]   [ETS] 시작  (메모리: 1591.6 MB)
[메모리] forecast_ets 실행 전: 1591.55 MB
[메모리] forecast_ets 실행 후: 1591.55 MB (변화: +0.00 MB)
[ISSC]   [ETS] 완료  첫값=2.68e+07 (메모리: 1591.6 MB)
[ISSC]   [Prophet] 시작  (메모리: 1591.6 MB)

12:23:26 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1591.55 MB

12:23:26 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1591.58 MB (변화: +0.03 MB)
[ISSC]   [Prophet] 완료  첫값=1.59e+07 (메모리: 1591.6 MB)
[ISSC]   [LSTM] 시작  (메모리: 1591.6 MB)
[메모리] forecast_lstm 실행 전: 1591.58 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1591.61 MB (변화: +0.02 MB)
[ISSC]   [LSTM] 완료  첫값=3.15e+07 (메모리: 1591.6 MB)
[ISSC]   [Theta] 시작  (메모리: 1591.6 MB)
[메모리] forecast_theta 실행 전: 1591.61 MB
[메모리] forecast_theta 실행 후: 1591.61 MB (변화: +0.00 MB)
[ISSC]   [Theta] 완료  첫값=2.50e+07 (메모리: 1591.6 MB)
[ISSC]   [DB] 88행 저장 완료
[PROGRESS] [ 456/500] ( 91.2%)  >>  NC
[NC]   40분기 | 2016-03-31 ~ 2025-12-31
[NC]   [SARIMA] 시작  (메모리: 1591.6 MB)
[메모리] forecast_sarima 실행 전: 1591.61 MB
[메모리] find_best_sarima_params 실행 전: 1591.61 MB
[메모리] find_best_sarima_params 실행 후: 1591.61 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1591.61 MB (변화: +0.00 MB)
[NC]   [SARIMA] 완료  첫값=7.07e+07 (메모리: 1591.6 MB)
[NC]   [ETS] 시작  (메모리: 1591.6 MB)
[메모리] forecast_ets 실행 전: 1591.61 MB
[메모리] forecast_ets 실행 후: 1591.61 MB (변화: +0.01 MB)
[NC]   [ETS] 완료  첫값=7.12e+07 (메모리: 1591.6 MB)
[NC]   [Prophet] 시작  (메모리: 1591.6 MB)

12:23:45 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1591.61 MB

12:23:45 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1591.62 MB (변화: +0.01 MB)
[NC]   [Prophet] 완료  첫값=2.75e+07 (메모리: 1591.6 MB)
[NC]   [LSTM] 시작  (메모리: 1591.6 MB)
[메모리] forecast_lstm 실행 전: 1591.62 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1591.60 MB (변화: -0.02 MB)
[NC]   [LSTM] 완료  첫값=6.61e+07 (메모리: 1591.6 MB)
[NC]   [Theta] 시작  (메모리: 1591.6 MB)
[메모리] forecast_theta 실행 전: 1591.60 MB
[메모리] forecast_theta 실행 후: 1591.60 MB (변화: +0.00 MB)
[NC]   [Theta] 완료  첫값=6.76e+07 (메모리: 1591.6 MB)
[NC]   [DB] 88행 저장 완료
[PROGRESS] [ 457/500] ( 91.4%)  >>  JKS
[JKS]   40분기 | 2015-12-31 ~ 2025-09-30
[JKS]   [SARIMA] 시작  (메모리: 1591.6 MB)
[메모리] forecast_sarima 실행 전: 1591.60 MB
[메모리] find_best_sarima_params 실행 전: 1591.60 MB
[메모리] find_best_sarima_params 실행 후: 1591.60 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1591.60 MB (변화: +0.00 MB)
[JKS]   [SARIMA] 완료  첫값=1.61e+10 (메모리: 1591.6 MB)
[JKS]   [ETS] 시작  (메모리: 1591.6 MB)
[메모리] forecast_ets 실행 전: 1591.60 MB
[메모리] forecast_ets 실행 후: 1591.60 MB (변화: +0.00 MB)
[JKS]   [ETS] 완료  첫값=1.88e+10 (메모리: 1591.6 MB)
[JKS]   [Prophet] 시작  (메모리: 1591.6 MB)

12:24:04 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1591.60 MB

12:24:04 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1591.62 MB (변화: +0.02 MB)
[JKS]   [Prophet] 완료  첫값=2.48e+10 (메모리: 1591.6 MB)
[JKS]   [LSTM] 시작  (메모리: 1591.6 MB)
[메모리] forecast_lstm 실행 전: 1591.62 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1591.63 MB (변화: +0.00 MB)
[JKS]   [LSTM] 완료  첫값=2.26e+10 (메모리: 1591.6 MB)
[JKS]   [Theta] 시작  (메모리: 1591.6 MB)
[메모리] forecast_theta 실행 전: 1591.63 MB
[메모리] forecast_theta 실행 후: 1591.63 MB (변화: +0.00 MB)
[JKS]   [Theta] 완료  첫값=1.87e+10 (메모리: 1591.6 MB)
[JKS]   [DB] 88행 저장 완료
[PROGRESS] [ 458/500] ( 91.6%)  >>  NVEC
[NVEC]   40분기 | 2016-03-31 ~ 2025-12-31
[NVEC]   [SARIMA] 시작  (메모리: 1591.6 MB)
[메모리] forecast_sarima 실행 전: 1591.63 MB
[메모리] find_best_sarima_params 실행 전: 1591.63 MB
[메모리] find_best_sarima_params 실행 후: 1591.63 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1591.63 MB (변화: +0.00 MB)
[NVEC]   [SARIMA] 완료  첫값=6.28e+06 (메모리: 1591.6 MB)
[NVEC]   [ETS] 시작  (메모리: 1591.6 MB)
[메모리] forecast_ets 실행 전: 1591.63 MB
[메모리] forecast_ets 실행 후: 1591.64 MB (변화: +0.01 MB)
[NVEC]   [ETS] 완료  첫값=6.59e+06 (메모리: 1591.6 MB)
[NVEC]   [Prophet] 시작  (메모리: 1591.6 MB)

12:24:23 - cmdstanpy - INFO - Chain [1] start processing
12:24:23 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1591.64 MB
[메모리] forecast_prophet 실행 후: 1591.65 MB (변화: +0.01 MB)
[NVEC]   [Prophet] 완료  첫값=7.08e+06 (메모리: 1591.6 MB)
[NVEC]   [LSTM] 시작  (메모리: 1591.6 MB)
[메모리] forecast_lstm 실행 전: 1591.65 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1591.61 MB (변화: -0.04 MB)
[NVEC]   [LSTM] 완료  첫값=6.61e+06 (메모리: 1591.6 MB)
[NVEC]   [Theta] 시작  (메모리: 1591.6 MB)
[메모리] forecast_theta 실행 전: 1591.61 MB
[메모리] forecast_theta 실행 후: 1591.61 MB (변화: +0.00 MB)
[NVEC]   [Theta] 완료  첫값=6.28e+06 (메모리: 1591.6 MB)
[NVEC]   [DB] 88행 저장 완료
[PROGRESS] [ 459/500] ( 91.8%)  >>  LAND
[LAND]   40분기 | 2016-03-31 ~ 2025-12-31
[LAND]   [SARIMA] 시작  (메모리: 1591.6 MB)
[메모리] forecast_sarima 실행 전: 1591.61 MB
[메모리] find_best_sarima_params 실행 전: 1591.61 MB
[메모리] find_best_sarima_params 실행 후: 1591.61 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1591.61 MB (변화: +0.00 MB)
[LAND]   [SARIMA] 완료  첫값=5.29e+07 (메모리: 1591.6 MB)
[LAND]   [ETS] 시작  (메모리: 1591.6 MB)
[메모리] forecast_ets 실행 전: 1591.61 MB
[메모리] forecast_ets 실행 후: 1591.62 MB (변화: +0.00 MB)
[LAND]   [ETS] 완료  첫값=4.11e+07 (메모리: 1591.6 MB)
[LAND]   [Prophet] 시작  (메모리: 1591.6 MB)

12:24:43 - cmdstanpy - INFO - Chain [1] start processing
12:24:43 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1591.62 MB
[메모리] forecast_prophet 실행 후: 1591.63 MB (변화: +0.02 MB)
[LAND]   [Prophet] 완료  첫값=2.69e+07 (메모리: 1591.6 MB)
[LAND]   [LSTM] 시작  (메모리: 1591.6 MB)
[메모리] forecast_lstm 실행 전: 1591.63 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1590.07 MB (변화: -1.56 MB)
[LAND]   [LSTM] 완료  첫값=2.58e+07 (메모리: 1590.1 MB)
[LAND]   [Theta] 시작  (메모리: 1590.1 MB)
[메모리] forecast_theta 실행 전: 1590.07 MB
[메모리] forecast_theta 실행 후: 1590.07 MB (변화: +0.00 MB)
[LAND]   [Theta] 완료  첫값=4.06e+07 (메모리: 1590.1 MB)
[LAND]   [DB] 88행 저장 완료
[PROGRESS] [ 460/500] ( 92.0%)  >>  HEAR
[HEAR]   40분기 | 2016-03-31 ~ 2025-12-31
[HEAR]   [SARIMA] 시작  (메모리: 1590.1 MB)
[메모리] forecast_sarima 실행 전: 1590.07 MB
[메모리] find_best_sarima_params 실행 전: 1590.07 MB
[메모리] find_best_sarima_params 실행 후: 1590.07 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1590.07 MB (변화: +0.00 MB)
[HEAR]   [SARIMA] 완료  첫값=5.40e+07 (메모리: 1590.1 MB)
[HEAR]   [ETS] 시작  (메모리: 1590.1 MB)
[메모리] forecast_ets 실행 전: 1590.07 MB
[메모리] forecast_ets 실행 후: 1590.07 MB (변화: +0.00 MB)
[HEAR]   [ETS] 완료  첫값=5.06e+07 (메모리: 1590.1 MB)
[HEAR]   [Prophet] 시작  (메모리: 1590.1 MB)

12:24:57 - cmdstanpy - INFO - Chain [1] start processing
12:24:57 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1590.07 MB
[메모리] forecast_prophet 실행 후: 1590.08 MB (변화: +0.01 MB)
[HEAR]   [Prophet] 완료  첫값=9.40e+07 (메모리: 1590.1 MB)
[HEAR]   [LSTM] 시작  (메모리: 1590.1 MB)
[메모리] forecast_lstm 실행 전: 1590.08 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1591.05 MB (변화: +0.96 MB)
[HEAR]   [LSTM] 완료  첫값=7.51e+07 (메모리: 1591.0 MB)
[HEAR]   [Theta] 시작  (메모리: 1591.0 MB)
[메모리] forecast_theta 실행 전: 1591.05 MB
[메모리] forecast_theta 실행 후: 1591.05 MB (변화: +0.00 MB)
[HEAR]   [Theta] 완료  첫값=5.08e+07 (메모리: 1591.0 MB)
[HEAR]   [DB] 88행 저장 완료
[PROGRESS] [ 461/500] ( 92.2%)  >>  ACCO
[ACCO]   40분기 | 2016-03-31 ~ 2025-12-31
[ACCO]   [SARIMA] 시작  (메모리: 1591.0 MB)
[메모리] forecast_sarima 실행 전: 1591.05 MB
[메모리] find_best_sarima_params 실행 전: 1591.05 MB
[메모리] find_best_sarima_params 실행 후: 1591.05 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1591.05 MB (변화: +0.00 MB)
[ACCO]   [SARIMA] 완료  첫값=3.32e+08 (메모리: 1591.0 MB)
[ACCO]   [ETS] 시작  (메모리: 1591.0 MB)
[메모리] forecast_ets 실행 전: 1591.05 MB
[메모리] forecast_ets 실행 후: 1591.05 MB (변화: +0.00 MB)
[ACCO]   [ETS] 완료  첫값=3.26e+08 (메모리: 1591.1 MB)
[ACCO]   [Prophet] 시작  (메모리: 1591.1 MB)

12:25:14 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1591.05 MB

12:25:14 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1591.68 MB (변화: +0.62 MB)
[ACCO]   [Prophet] 완료  첫값=4.40e+08 (메모리: 1591.7 MB)
[ACCO]   [LSTM] 시작  (메모리: 1591.7 MB)
[메모리] forecast_lstm 실행 전: 1591.68 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1591.57 MB (변화: -0.10 MB)
[ACCO]   [LSTM] 완료  첫값=4.19e+08 (메모리: 1591.6 MB)
[ACCO]   [Theta] 시작  (메모리: 1591.6 MB)
[메모리] forecast_theta 실행 전: 1591.57 MB
[메모리] forecast_theta 실행 후: 1591.57 MB (변화: +0.00 MB)
[ACCO]   [Theta] 완료  첫값=3.28e+08 (메모리: 1591.6 MB)
[ACCO]   [DB] 88행 저장 완료
[PROGRESS] [ 462/500] ( 92.4%)  >>  ELA
[ELA]   40분기 | 2016-03-31 ~ 2025-12-31
[ELA]   [SARIMA] 시작  (메모리: 1591.6 MB)
[메모리] forecast_sarima 실행 전: 1591.57 MB
[메모리] find_best_sarima_params 실행 전: 1591.57 MB
[메모리] find_best_sarima_params 실행 후: 1591.57 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1591.57 MB (변화: +0.00 MB)
[ELA]   [SARIMA] 완료  첫값=7.68e+07 (메모리: 1591.6 MB)
[ELA]   [ETS] 시작  (메모리: 1591.6 MB)
[메모리] forecast_ets 실행 전: 1591.57 MB
[메모리] forecast_ets 실행 후: 1591.58 MB (변화: +0.00 MB)
[ELA]   [ETS] 완료  첫값=7.36e+07 (메모리: 1591.6 MB)
[ELA]   [Prophet] 시작  (메모리: 1591.6 MB)

12:25:30 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1591.58 MB

12:25:30 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1592.11 MB (변화: +0.53 MB)
[ELA]   [Prophet] 완료  첫값=5.93e+07 (메모리: 1592.1 MB)
[ELA]   [LSTM] 시작  (메모리: 1592.1 MB)
[메모리] forecast_lstm 실행 전: 1592.11 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1592.30 MB (변화: +0.20 MB)
[ELA]   [LSTM] 완료  첫값=4.93e+07 (메모리: 1592.3 MB)
[ELA]   [Theta] 시작  (메모리: 1592.3 MB)
[메모리] forecast_theta 실행 전: 1592.30 MB
[메모리] forecast_theta 실행 후: 1592.30 MB (변화: +0.00 MB)
[ELA]   [Theta] 완료  첫값=7.83e+07 (메모리: 1592.3 MB)
[ELA]   [DB] 88행 저장 완료
[PROGRESS] [ 463/500] ( 92.6%)  >>  QIWI
[QIWI] [NEG-SKIP] [QIWI] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2023, 12, 31)])
[PROGRESS] [ 464/500] ( 92.8%)  >>  KNOP
[KNOP]   40분기 | 2016-03-31 ~ 2025-12-31
[KNOP]   [SARIMA] 시작  (메모리: 1592.3 MB)
[메모리] forecast_sarima 실행 전: 1592.30 MB
[메모리] find_best_sarima_params 실행 전: 1592.30 MB
[메모리] find_best_sarima_params 실행 후: 1592.30 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1592.30 MB (변화: +0.00 MB)
[KNOP]   [SARIMA] 완료  첫값=9.86e+07 (메모리: 1592.3 MB)
[KNOP]   [ETS] 시작  (메모리: 1592.3 MB)
[메모리] forecast_ets 실행 전: 1592.30 MB
[메모리] forecast_ets 실행 후: 1592.31 MB (변화: +0.00 MB)
[KNOP]   [ETS] 완료  첫값=9.59e+07 (메모리: 1592.3 MB)
[KNOP]   [Prophet] 시작  (메모리: 1592.3 MB)

12:25:48 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1592.31 MB

12:25:48 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1592.33 MB (변화: +0.02 MB)
[KNOP]   [Prophet] 완료  첫값=8.80e+07 (메모리: 1592.3 MB)
[KNOP]   [LSTM] 시작  (메모리: 1592.3 MB)
[메모리] forecast_lstm 실행 전: 1592.33 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1591.83 MB (변화: -0.50 MB)
[KNOP]   [LSTM] 완료  첫값=8.22e+07 (메모리: 1591.8 MB)
[KNOP]   [Theta] 시작  (메모리: 1591.8 MB)
[메모리] forecast_theta 실행 전: 1591.83 MB
[메모리] forecast_theta 실행 후: 1591.83 MB (변화: +0.00 MB)
[KNOP]   [Theta] 완료  첫값=9.72e+07 (메모리: 1591.8 MB)
[KNOP]   [DB] 88행 저장 완료
[PROGRESS] [ 465/500] ( 93.0%)  >>  OEC
[OEC]   40분기 | 2016-03-31 ~ 2025-12-31
[OEC]   [SARIMA] 시작  (메모리: 1591.8 MB)
[메모리] forecast_sarima 실행 전: 1591.83 MB
[메모리] find_best_sarima_params 실행 전: 1591.83 MB
[메모리] find_best_sarima_params 실행 후: 1591.83 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1591.83 MB (변화: +0.00 MB)
[OEC]   [SARIMA] 완료  첫값=4.16e+08 (메모리: 1591.8 MB)
[OEC]   [ETS] 시작  (메모리: 1591.8 MB)
[메모리] forecast_ets 실행 전: 1591.83 MB
[메모리] forecast_ets 실행 후: 1591.83 MB (변화: +0.00 MB)
[OEC]   [ETS] 완료  첫값=4.58e+08 (메모리: 1591.8 MB)
[OEC]   [Prophet] 시작  (메모리: 1591.8 MB)
[메모리] forecast_prophet 실행 전: 1591.83 MB

12:26:03 - cmdstanpy - INFO - Chain [1] start processing
12:26:04 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1591.86 MB (변화: +0.02 MB)
[OEC]   [Prophet] 완료  첫값=4.97e+08 (메모리: 1591.9 MB)
[OEC]   [LSTM] 시작  (메모리: 1591.9 MB)
[메모리] forecast_lstm 실행 전: 1591.86 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1591.83 MB (변화: -0.02 MB)
[OEC]   [LSTM] 완료  첫값=5.44e+08 (메모리: 1591.8 MB)
[OEC]   [Theta] 시작  (메모리: 1591.8 MB)
[메모리] forecast_theta 실행 전: 1591.83 MB
[메모리] forecast_theta 실행 후: 1591.83 MB (변화: +0.00 MB)
[OEC]   [Theta] 완료  첫값=4.22e+08 (메모리: 1591.8 MB)
[OEC]   [DB] 88행 저장 완료
[PROGRESS] [ 466/500] ( 93.2%)  >>  GCO
[GCO]   40분기 | 2016-04-30 ~ 2026-01-31
[GCO]   [SARIMA] 시작  (메모리: 1591.8 MB)
[메모리] forecast_sarima 실행 전: 1591.83 MB
[메모리] find_best_sarima_params 실행 전: 1591.83 MB
[메모리] find_best_sarima_params 실행 후: 1591.83 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1591.83 MB (변화: +0.00 MB)
[GCO]   [SARIMA] 완료  첫값=5.13e+08 (메모리: 1591.8 MB)
[GCO]   [ETS] 시작  (메모리: 1591.8 MB)
[메모리] forecast_ets 실행 전: 1591.83 MB
[메모리] forecast_ets 실행 후: 1591.84 MB (변화: +0.00 MB)
[GCO]   [ETS] 완료  첫값=5.21e+08 (메모리: 1591.8 MB)
[GCO]   [Prophet] 시작  (메모리: 1591.8 MB)

12:26:18 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1591.84 MB

12:26:18 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1591.86 MB (변화: +0.03 MB)
[GCO]   [Prophet] 완료  첫값=5.59e+08 (메모리: 1591.9 MB)
[GCO]   [LSTM] 시작  (메모리: 1591.9 MB)
[메모리] forecast_lstm 실행 전: 1591.86 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1591.39 MB (변화: -0.47 MB)
[GCO]   [LSTM] 완료  첫값=5.32e+08 (메모리: 1591.4 MB)
[GCO]   [Theta] 시작  (메모리: 1591.4 MB)
[메모리] forecast_theta 실행 전: 1591.39 MB
[메모리] forecast_theta 실행 후: 1591.39 MB (변화: +0.00 MB)
[GCO]   [Theta] 완료  첫값=5.20e+08 (메모리: 1591.4 MB)
[GCO]   [DB] 88행 저장 완료
[PROGRESS] [ 467/500] ( 93.4%)  >>  MCFT
[MCFT]   40분기 | 2016-03-27 ~ 2025-12-28
[MCFT]   [SARIMA] 시작  (메모리: 1591.4 MB)
[메모리] forecast_sarima 실행 전: 1591.39 MB
[메모리] find_best_sarima_params 실행 전: 1591.39 MB
[메모리] find_best_sarima_params 실행 후: 1591.39 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1591.39 MB (변화: +0.00 MB)
[MCFT]   [SARIMA] 완료  첫값=7.18e+07 (메모리: 1591.4 MB)
[MCFT]   [ETS] 시작  (메모리: 1591.4 MB)
[메모리] forecast_ets 실행 전: 1591.39 MB
[메모리] forecast_ets 실행 후: 1591.39 MB (변화: +0.00 MB)
[MCFT]   [ETS] 완료  첫값=7.97e+07 (메모리: 1591.4 MB)
[MCFT]   [Prophet] 시작  (메모리: 1591.4 MB)

12:26:32 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1591.39 MB

12:26:32 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1591.41 MB (변화: +0.01 MB)
[MCFT]   [Prophet] 완료  첫값=1.19e+08 (메모리: 1591.4 MB)
[MCFT]   [LSTM] 시작  (메모리: 1591.4 MB)
[메모리] forecast_lstm 실행 전: 1591.41 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1592.42 MB (변화: +1.02 MB)
[MCFT]   [LSTM] 완료  첫값=1.05e+08 (메모리: 1592.4 MB)
[MCFT]   [Theta] 시작  (메모리: 1592.4 MB)
[메모리] forecast_theta 실행 전: 1592.42 MB
[메모리] forecast_theta 실행 후: 1592.42 MB (변화: +0.00 MB)
[MCFT]   [Theta] 완료  첫값=7.19e+07 (메모리: 1592.4 MB)
[MCFT]   [DB] 88행 저장 완료
[PROGRESS] [ 468/500] ( 93.6%)  >>  MOV
[MOV]   40분기 | 2016-04-30 ~ 2026-01-31
[MOV]   [SARIMA] 시작  (메모리: 1592.4 MB)
[메모리] forecast_sarima 실행 전: 1592.42 MB
[메모리] find_best_sarima_params 실행 전: 1592.42 MB
[메모리] find_best_sarima_params 실행 후: 1592.42 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1592.42 MB (변화: +0.00 MB)
[MOV]   [SARIMA] 완료  첫값=1.56e+08 (메모리: 1592.4 MB)
[MOV]   [ETS] 시작  (메모리: 1592.4 MB)
[메모리] forecast_ets 실행 전: 1592.42 MB
[메모리] forecast_ets 실행 후: 1592.43 MB (변화: +0.00 MB)
[MOV]   [ETS] 완료  첫값=1.36e+08 (메모리: 1592.4 MB)
[MOV]   [Prophet] 시작  (메모리: 1592.4 MB)

12:26:51 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1592.43 MB

12:26:51 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1592.43 MB (변화: +0.01 MB)
[MOV]   [Prophet] 완료  첫값=1.82e+08 (메모리: 1592.4 MB)
[MOV]   [LSTM] 시작  (메모리: 1592.4 MB)
[메모리] forecast_lstm 실행 전: 1592.43 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1592.42 MB (변화: -0.02 MB)
[MOV]   [LSTM] 완료  첫값=1.63e+08 (메모리: 1592.4 MB)
[MOV]   [Theta] 시작  (메모리: 1592.4 MB)
[메모리] forecast_theta 실행 전: 1592.42 MB
[메모리] forecast_theta 실행 후: 1592.42 MB (변화: +0.00 MB)
[MOV]   [Theta] 완료  첫값=1.33e+08 (메모리: 1592.4 MB)
[MOV]   [DB] 88행 저장 완료
[PROGRESS] [ 469/500] ( 93.8%)  >>  CTRN
[CTRN]   40분기 | 2016-04-30 ~ 2026-01-31
[CTRN]   [SARIMA] 시작  (메모리: 1592.4 MB)
[메모리] forecast_sarima 실행 전: 1592.42 MB
[메모리] find_best_sarima_params 실행 전: 1592.42 MB
[메모리] find_best_sarima_params 실행 후: 1592.42 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1592.42 MB (변화: +0.00 MB)
[CTRN]   [SARIMA] 완료  첫값=2.06e+08 (메모리: 1592.4 MB)
[CTRN]   [ETS] 시작  (메모리: 1592.4 MB)
[메모리] forecast_ets 실행 전: 1592.42 MB
[메모리] forecast_ets 실행 후: 1592.42 MB (변화: +0.00 MB)
[CTRN]   [ETS] 완료  첫값=2.06e+08 (메모리: 1592.4 MB)
[CTRN]   [Prophet] 시작  (메모리: 1592.4 MB)

12:27:07 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1592.42 MB

12:27:07 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1592.44 MB (변화: +0.02 MB)
[CTRN]   [Prophet] 완료  첫값=2.08e+08 (메모리: 1592.4 MB)
[CTRN]   [LSTM] 시작  (메모리: 1592.4 MB)
[메모리] forecast_lstm 실행 전: 1592.44 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1592.40 MB (변화: -0.04 MB)
[CTRN]   [LSTM] 완료  첫값=1.91e+08 (메모리: 1592.4 MB)
[CTRN]   [Theta] 시작  (메모리: 1592.4 MB)
[메모리] forecast_theta 실행 전: 1592.40 MB
[메모리] forecast_theta 실행 후: 1592.40 MB (변화: +0.00 MB)
[CTRN]   [Theta] 완료  첫값=2.05e+08 (메모리: 1592.4 MB)
[CTRN]   [DB] 88행 저장 완료
[PROGRESS] [ 470/500] ( 94.0%)  >>  FVR
[FVR] [SKIP] [FVR] 'sale' 관측치 부족: 13개 < 최소 28개
[PROGRESS] [ 471/500] ( 94.2%)  >>  BGS
[BGS]   40분기 | 2016-04-02 ~ 2026-01-03
[BGS]   [SARIMA] 시작  (메모리: 1592.4 MB)
[메모리] forecast_sarima 실행 전: 1592.40 MB
[메모리] find_best_sarima_params 실행 전: 1592.40 MB
[메모리] find_best_sarima_params 실행 후: 1592.40 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1592.40 MB (변화: +0.00 MB)
[BGS]   [SARIMA] 완료  첫값=4.19e+08 (메모리: 1592.4 MB)
[BGS]   [ETS] 시작  (메모리: 1592.4 MB)
[메모리] forecast_ets 실행 전: 1592.40 MB
[메모리] forecast_ets 실행 후: 1592.40 MB (변화: +0.00 MB)
[BGS]   [ETS] 완료  첫값=4.76e+08 (메모리: 1592.4 MB)
[BGS]   [Prophet] 시작  (메모리: 1592.4 MB)
[메모리] forecast_prophet 실행 전: 1592.40 MB

12:27:24 - cmdstanpy - INFO - Chain [1] start processing
12:27:24 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1592.41 MB (변화: +0.01 MB)
[BGS]   [Prophet] 완료  첫값=5.32e+08 (메모리: 1592.4 MB)
[BGS]   [LSTM] 시작  (메모리: 1592.4 MB)
[메모리] forecast_lstm 실행 전: 1592.41 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1592.42 MB (변화: +0.00 MB)
[BGS]   [LSTM] 완료  첫값=4.72e+08 (메모리: 1592.4 MB)
[BGS]   [Theta] 시작  (메모리: 1592.4 MB)
[메모리] forecast_theta 실행 전: 1592.42 MB
[메모리] forecast_theta 실행 후: 1592.42 MB (변화: +0.00 MB)
[BGS]   [Theta] 완료  첫값=4.74e+08 (메모리: 1592.4 MB)
[BGS]   [DB] 88행 저장 완료
[PROGRESS] [ 472/500] ( 94.4%)  >>  NCMI
[NCMI]   40분기 | 2016-03-31 ~ 2026-01-01
[NCMI]   [SARIMA] 시작  (메모리: 1592.4 MB)
[메모리] forecast_sarima 실행 전: 1592.42 MB
[메모리] find_best_sarima_params 실행 전: 1592.42 MB
[메모리] find_best_sarima_params 실행 후: 1592.42 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1592.42 MB (변화: +0.00 MB)
[NCMI]   [SARIMA] 완료  첫값=4.12e+07 (메모리: 1592.4 MB)
[NCMI]   [ETS] 시작  (메모리: 1592.4 MB)
[메모리] forecast_ets 실행 전: 1592.42 MB
[메모리] forecast_ets 실행 후: 1592.42 MB (변화: +0.00 MB)
[NCMI]   [ETS] 완료  첫값=4.27e+07 (메모리: 1592.4 MB)
[NCMI]   [Prophet] 시작  (메모리: 1592.4 MB)

12:27:37 - cmdstanpy - INFO - Chain [1] start processing
12:27:37 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1592.42 MB
[메모리] forecast_prophet 실행 후: 1592.44 MB (변화: +0.02 MB)
[NCMI]   [Prophet] 완료  첫값=3.65e+07 (메모리: 1592.4 MB)
[NCMI]   [LSTM] 시작  (메모리: 1592.4 MB)
[메모리] forecast_lstm 실행 전: 1592.44 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1592.40 MB (변화: -0.04 MB)
[NCMI]   [LSTM] 완료  첫값=4.99e+07 (메모리: 1592.4 MB)
[NCMI]   [Theta] 시작  (메모리: 1592.4 MB)
[메모리] forecast_theta 실행 전: 1592.40 MB
[메모리] forecast_theta 실행 후: 1592.40 MB (변화: +0.00 MB)
[NCMI]   [Theta] 완료  첫값=8.31e+07 (메모리: 1592.4 MB)
[NCMI]   [DB] 88행 저장 완료
[PROGRESS] [ 473/500] ( 94.6%)  >>  VGZ
[VGZ]   40분기 | 2016-03-31 ~ 2025-12-31
[VGZ]   [SARIMA] 시작  (메모리: 1592.4 MB)
[메모리] forecast_sarima 실행 전: 1592.40 MB
[메모리] find_best_sarima_params 실행 전: 1592.40 MB
[메모리] find_best_sarima_params 실행 후: 1592.40 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1592.40 MB (변화: +0.00 MB)
[VGZ]   [SARIMA] 완료  첫값=-2.08e+04 (메모리: 1592.4 MB)
[VGZ]   [ETS] 시작  (메모리: 1592.4 MB)
[메모리] forecast_ets 실행 전: 1592.40 MB
[메모리] forecast_ets 실행 후: 1592.40 MB (변화: +0.00 MB)
[VGZ]   [ETS] 완료  첫값=-3.60e+04 (메모리: 1592.4 MB)
[VGZ]   [Prophet] 시작  (메모리: 1592.4 MB)

12:27:49 - cmdstanpy - INFO - Chain [1] start processing
12:27:49 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1592.40 MB
[메모리] forecast_prophet 실행 후: 1592.41 MB (변화: +0.01 MB)
[VGZ]   [Prophet] 완료  첫값=-4.57e+04 (메모리: 1592.4 MB)
[VGZ]   [LSTM] 시작  (메모리: 1592.4 MB)
[메모리] forecast_lstm 실행 전: 1592.41 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1592.39 MB (변화: -0.02 MB)
[VGZ]   [LSTM] 완료  첫값=1.37e+02 (메모리: 1592.4 MB)
[VGZ]   [Theta] 시작  (메모리: 1592.4 MB)
[메모리] forecast_theta 실행 전: 1592.39 MB
[메모리] forecast_theta 실행 후: 1592.39 MB (변화: +0.00 MB)
[VGZ]   [Theta] 완료  첫값=-7.48e+04 (메모리: 1592.4 MB)
[VGZ]   [DB] 88행 저장 완료
[PROGRESS] [ 474/500] ( 94.8%)  >>  CCLP
[CCLP]   40분기 | 2014-03-31 ~ 2023-12-31
[CCLP]   [SARIMA] 시작  (메모리: 1592.4 MB)
[메모리] forecast_sarima 실행 전: 1592.39 MB
[메모리] find_best_sarima_params 실행 전: 1592.39 MB
[메모리] find_best_sarima_params 실행 후: 1592.39 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1592.39 MB (변화: +0.00 MB)
[CCLP]   [SARIMA] 완료  첫값=8.27e+07 (메모리: 1592.4 MB)
[CCLP]   [ETS] 시작  (메모리: 1592.4 MB)
[메모리] forecast_ets 실행 전: 1592.39 MB
[메모리] forecast_ets 실행 후: 1592.40 MB (변화: +0.00 MB)
[CCLP]   [ETS] 완료  첫값=8.32e+07 (메모리: 1592.4 MB)
[CCLP]   [Prophet] 시작  (메모리: 1592.4 MB)

12:28:03 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1592.40 MB

12:28:03 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1592.43 MB (변화: +0.03 MB)
[CCLP]   [Prophet] 완료  첫값=9.48e+07 (메모리: 1592.4 MB)
[CCLP]   [LSTM] 시작  (메모리: 1592.4 MB)
[메모리] forecast_lstm 실행 전: 1592.43 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1592.41 MB (변화: -0.02 MB)
[CCLP]   [LSTM] 완료  첫값=9.17e+07 (메모리: 1592.4 MB)
[CCLP]   [Theta] 시작  (메모리: 1592.4 MB)
[메모리] forecast_theta 실행 전: 1592.41 MB
[메모리] forecast_theta 실행 후: 1592.41 MB (변화: +0.00 MB)
[CCLP]   [Theta] 완료  첫값=9.85e+07 (메모리: 1592.4 MB)
[CCLP]   [DB] 88행 저장 완료
[PROGRESS] [ 475/500] ( 95.0%)  >>  ATNI
[ATNI]   40분기 | 2016-03-31 ~ 2025-12-31
[ATNI]   [SARIMA] 시작  (메모리: 1592.4 MB)
[메모리] forecast_sarima 실행 전: 1592.41 MB
[메모리] find_best_sarima_params 실행 전: 1592.41 MB
[메모리] find_best_sarima_params 실행 후: 1592.41 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1592.41 MB (변화: +0.00 MB)
[ATNI]   [SARIMA] 완료  첫값=1.88e+08 (메모리: 1592.4 MB)
[ATNI]   [ETS] 시작  (메모리: 1592.4 MB)
[메모리] forecast_ets 실행 전: 1592.41 MB
[메모리] forecast_ets 실행 후: 1592.41 MB (변화: +0.00 MB)
[ATNI]   [ETS] 완료  첫값=1.79e+08 (메모리: 1592.4 MB)
[ATNI]   [Prophet] 시작  (메모리: 1592.4 MB)

12:28:23 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1592.41 MB

12:28:23 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1592.44 MB (변화: +0.03 MB)
[ATNI]   [Prophet] 완료  첫값=1.98e+08 (메모리: 1592.4 MB)
[ATNI]   [LSTM] 시작  (메모리: 1592.4 MB)
[메모리] forecast_lstm 실행 전: 1592.44 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1592.37 MB (변화: -0.07 MB)
[ATNI]   [LSTM] 완료  첫값=1.83e+08 (메모리: 1592.4 MB)
[ATNI]   [Theta] 시작  (메모리: 1591.2 MB)
[메모리] forecast_theta 실행 전: 1591.25 MB
[메모리] forecast_theta 실행 후: 1591.25 MB (변화: +0.00 MB)
[ATNI]   [Theta] 완료  첫값=1.78e+08 (메모리: 1591.2 MB)
[ATNI]   [DB] 88행 저장 완료
[PROGRESS] [ 476/500] ( 95.2%)  >>  SMC
[SMC] [SKIP] [SMC] 'sale' 관측치 부족: 14개 < 최소 28개
[PROGRESS] [ 477/500] ( 95.4%)  >>  CLDT
[CLDT]   40분기 | 2016-03-31 ~ 2025-12-31
[CLDT]   [SARIMA] 시작  (메모리: 1591.2 MB)
[메모리] forecast_sarima 실행 전: 1591.25 MB
[메모리] find_best_sarima_params 실행 전: 1591.25 MB
[메모리] find_best_sarima_params 실행 후: 1591.25 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1591.25 MB (변화: +0.00 MB)
[CLDT]   [SARIMA] 완료  첫값=6.77e+07 (메모리: 1591.2 MB)
[CLDT]   [ETS] 시작  (메모리: 1591.2 MB)
[메모리] forecast_ets 실행 전: 1591.25 MB
[메모리] forecast_ets 실행 후: 1591.26 MB (변화: +0.01 MB)
[CLDT]   [ETS] 완료  첫값=6.48e+07 (메모리: 1591.3 MB)
[CLDT]   [Prophet] 시작  (메모리: 1591.3 MB)

12:28:39 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1591.26 MB

12:28:39 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1591.28 MB (변화: +0.02 MB)
[CLDT]   [Prophet] 완료  첫값=7.05e+07 (메모리: 1591.3 MB)
[CLDT]   [LSTM] 시작  (메모리: 1591.3 MB)
[메모리] forecast_lstm 실행 전: 1591.28 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1591.03 MB (변화: -0.25 MB)
[CLDT]   [LSTM] 완료  첫값=6.92e+07 (메모리: 1591.0 MB)
[CLDT]   [Theta] 시작  (메모리: 1591.0 MB)
[메모리] forecast_theta 실행 전: 1591.03 MB
[메모리] forecast_theta 실행 후: 1591.03 MB (변화: +0.00 MB)
[CLDT]   [Theta] 완료  첫값=6.93e+07 (메모리: 1591.0 MB)
[CLDT]   [DB] 88행 저장 완료
[PROGRESS] [ 478/500] ( 95.6%)  >>  AMCX
[AMCX]   40분기 | 2016-03-31 ~ 2025-12-31
[AMCX]   [SARIMA] 시작  (메모리: 1591.0 MB)
[메모리] forecast_sarima 실행 전: 1591.03 MB
[메모리] find_best_sarima_params 실행 전: 1591.03 MB
[메모리] find_best_sarima_params 실행 후: 1591.03 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1591.03 MB (변화: +0.00 MB)
[AMCX]   [SARIMA] 완료  첫값=5.80e+08 (메모리: 1591.0 MB)
[AMCX]   [ETS] 시작  (메모리: 1591.0 MB)
[메모리] forecast_ets 실행 전: 1591.03 MB
[메모리] forecast_ets 실행 후: 1591.03 MB (변화: +0.00 MB)
[AMCX]   [ETS] 완료  첫값=5.59e+08 (메모리: 1591.0 MB)
[AMCX]   [Prophet] 시작  (메모리: 1591.0 MB)

12:28:59 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1591.03 MB

12:28:59 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1591.05 MB (변화: +0.02 MB)
[AMCX]   [Prophet] 완료  첫값=6.07e+08 (메모리: 1591.0 MB)
[AMCX]   [LSTM] 시작  (메모리: 1591.0 MB)
[메모리] forecast_lstm 실행 전: 1591.05 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1590.88 MB (변화: -0.17 MB)
[AMCX]   [LSTM] 완료  첫값=6.38e+08 (메모리: 1590.9 MB)
[AMCX]   [Theta] 시작  (메모리: 1590.9 MB)
[메모리] forecast_theta 실행 전: 1590.88 MB
[메모리] forecast_theta 실행 후: 1590.88 MB (변화: +0.00 MB)
[AMCX]   [Theta] 완료  첫값=5.59e+08 (메모리: 1590.9 MB)
[AMCX]   [DB] 88행 저장 완료
[PROGRESS] [ 479/500] ( 95.8%)  >>  BYRN
[BYRN]   40분기 | 2016-02-29 ~ 2025-11-30
[BYRN]   [SARIMA] 시작  (메모리: 1590.9 MB)
[메모리] forecast_sarima 실행 전: 1590.88 MB
[메모리] find_best_sarima_params 실행 전: 1590.88 MB
[메모리] find_best_sarima_params 실행 후: 1590.88 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1590.88 MB (변화: +0.00 MB)
[BYRN]   [SARIMA] 완료  첫값=2.83e+07 (메모리: 1590.9 MB)
[BYRN]   [ETS] 시작  (메모리: 1590.9 MB)
[메모리] forecast_ets 실행 전: 1590.88 MB
[메모리] forecast_ets 실행 후: 1590.88 MB (변화: +0.00 MB)
[BYRN]   [ETS] 완료  첫값=2.02e+07 (메모리: 1590.9 MB)
[BYRN]   [Prophet] 시작  (메모리: 1590.9 MB)

12:29:13 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1590.88 MB

12:29:13 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1591.63 MB (변화: +0.75 MB)
[BYRN]   [Prophet] 완료  첫값=2.48e+07 (메모리: 1591.6 MB)
[BYRN]   [LSTM] 시작  (메모리: 1591.6 MB)
[메모리] forecast_lstm 실행 전: 1591.63 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1591.62 MB (변화: -0.01 MB)
[BYRN]   [LSTM] 완료  첫값=3.92e+07 (메모리: 1591.6 MB)
[BYRN]   [Theta] 시작  (메모리: 1591.6 MB)
[메모리] forecast_theta 실행 전: 1591.62 MB
[메모리] forecast_theta 실행 후: 1591.62 MB (변화: +0.00 MB)
[BYRN]   [Theta] 완료  첫값=1.41e+07 (메모리: 1591.6 MB)
[BYRN]   [DB] 88행 저장 완료
[PROGRESS] [ 480/500] ( 96.0%)  >>  INS
[INS]   40분기 | 2012-12-31 ~ 2025-06-30
[INS]   [SARIMA] 시작  (메모리: 1591.6 MB)
[메모리] forecast_sarima 실행 전: 1591.62 MB
[메모리] find_best_sarima_params 실행 전: 1591.62 MB
[메모리] find_best_sarima_params 실행 후: 1591.62 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1591.62 MB (변화: +0.00 MB)
[INS]   [SARIMA] 완료  첫값=1.93e+07 (메모리: 1591.6 MB)
[INS]   [ETS] 시작  (메모리: 1591.6 MB)
[메모리] forecast_ets 실행 전: 1591.62 MB
[메모리] forecast_ets 실행 후: 1591.62 MB (변화: +0.00 MB)
[INS]   [ETS] 완료  첫값=1.77e+07 (메모리: 1591.6 MB)
[INS]   [Prophet] 시작  (메모리: 1591.6 MB)

12:29:30 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1591.62 MB

12:29:30 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1591.28 MB (변화: -0.34 MB)
[INS]   [Prophet] 완료  첫값=1.55e+07 (메모리: 1591.3 MB)
[INS]   [LSTM] 시작  (메모리: 1591.3 MB)
[메모리] forecast_lstm 실행 전: 1591.28 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1592.25 MB (변화: +0.97 MB)
[INS]   [LSTM] 완료  첫값=2.09e+07 (메모리: 1592.2 MB)
[INS]   [Theta] 시작  (메모리: 1592.2 MB)
[메모리] forecast_theta 실행 전: 1592.25 MB
[메모리] forecast_theta 실행 후: 1592.25 MB (변화: +0.00 MB)
[INS]   [Theta] 완료  첫값=1.74e+07 (메모리: 1592.2 MB)
[INS]   [DB] 88행 저장 완료
[PROGRESS] [ 481/500] ( 96.2%)  >>  MTLS
[MTLS]   40분기 | 2016-03-31 ~ 2025-12-31
[MTLS]   [SARIMA] 시작  (메모리: 1592.2 MB)
[메모리] forecast_sarima 실행 전: 1592.25 MB
[메모리] find_best_sarima_params 실행 전: 1592.25 MB
[메모리] find_best_sarima_params 실행 후: 1592.25 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1592.25 MB (변화: +0.00 MB)
[MTLS]   [SARIMA] 완료  첫값=7.50e+07 (메모리: 1592.2 MB)
[MTLS]   [ETS] 시작  (메모리: 1592.2 MB)
[메모리] forecast_ets 실행 전: 1592.25 MB
[메모리] forecast_ets 실행 후: 1592.25 MB (변화: +0.00 MB)
[MTLS]   [ETS] 완료  첫값=7.15e+07 (메모리: 1592.2 MB)
[MTLS]   [Prophet] 시작  (메모리: 1592.2 MB)

12:29:50 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1592.25 MB

12:29:50 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1591.41 MB (변화: -0.84 MB)
[MTLS]   [Prophet] 완료  첫값=7.31e+07 (메모리: 1591.4 MB)
[MTLS]   [LSTM] 시작  (메모리: 1591.4 MB)
[메모리] forecast_lstm 실행 전: 1591.41 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.77 MB (변화: +2.36 MB)
[MTLS]   [LSTM] 완료  첫값=6.99e+07 (메모리: 1593.8 MB)
[MTLS]   [Theta] 시작  (메모리: 1593.8 MB)
[메모리] forecast_theta 실행 전: 1593.77 MB
[메모리] forecast_theta 실행 후: 1593.77 MB (변화: +0.00 MB)
[MTLS]   [Theta] 완료  첫값=6.91e+07 (메모리: 1593.8 MB)
[MTLS]   [DB] 88행 저장 완료
[PROGRESS] [ 482/500] ( 96.4%)  >>  SNMP
[SNMP]   40분기 | 2013-12-31 ~ 2023-09-30
[SNMP]   [SARIMA] 시작  (메모리: 1593.8 MB)
[메모리] forecast_sarima 실행 전: 1593.77 MB
[메모리] find_best_sarima_params 실행 전: 1593.77 MB
[메모리] find_best_sarima_params 실행 후: 1593.77 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.77 MB (변화: +0.00 MB)
[SNMP]   [SARIMA] 완료  첫값=6.12e+06 (메모리: 1593.8 MB)
[SNMP]   [ETS] 시작  (메모리: 1593.8 MB)
[메모리] forecast_ets 실행 전: 1593.77 MB
[메모리] forecast_ets 실행 후: 1593.77 MB (변화: +0.00 MB)
[SNMP]   [ETS] 완료  첫값=6.48e+06 (메모리: 1593.8 MB)
[SNMP]   [Prophet] 시작  (메모리: 1593.8 MB)

12:30:04 - cmdstanpy - INFO - Chain [1] start processing
12:30:04 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1593.77 MB
[메모리] forecast_prophet 실행 후: 1593.80 MB (변화: +0.03 MB)
[SNMP]   [Prophet] 완료  첫값=1.05e+07 (메모리: 1593.8 MB)
[SNMP]   [LSTM] 시작  (메모리: 1593.8 MB)
[메모리] forecast_lstm 실행 전: 1593.80 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.35 MB (변화: -0.45 MB)
[SNMP]   [LSTM] 완료  첫값=5.85e+06 (메모리: 1593.4 MB)
[SNMP]   [Theta] 시작  (메모리: 1593.4 MB)
[메모리] forecast_theta 실행 전: 1593.35 MB
[메모리] forecast_theta 실행 후: 1593.35 MB (변화: +0.00 MB)
[SNMP]   [Theta] 완료  첫값=7.41e+06 (메모리: 1593.4 MB)
[SNMP]   [DB] 88행 저장 완료
[PROGRESS] [ 483/500] ( 96.6%)  >>  OFLX
[OFLX]   40분기 | 2016-03-31 ~ 2025-12-31
[OFLX]   [SARIMA] 시작  (메모리: 1593.4 MB)
[메모리] forecast_sarima 실행 전: 1593.35 MB
[메모리] find_best_sarima_params 실행 전: 1593.35 MB
[메모리] find_best_sarima_params 실행 후: 1593.35 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.35 MB (변화: +0.00 MB)
[OFLX]   [SARIMA] 완료  첫값=2.52e+07 (메모리: 1593.4 MB)
[OFLX]   [ETS] 시작  (메모리: 1593.4 MB)
[메모리] forecast_ets 실행 전: 1593.35 MB
[메모리] forecast_ets 실행 후: 1593.36 MB (변화: +0.00 MB)
[OFLX]   [ETS] 완료  첫값=2.33e+07 (메모리: 1593.4 MB)
[OFLX]   [Prophet] 시작  (메모리: 1593.4 MB)
[메모리] forecast_prophet 실행 전: 1593.36 MB

12:30:24 - cmdstanpy - INFO - Chain [1] start processing
12:30:24 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.38 MB (변화: +0.02 MB)
[OFLX]   [Prophet] 완료  첫값=2.57e+07 (메모리: 1593.4 MB)
[OFLX]   [LSTM] 시작  (메모리: 1593.4 MB)
[메모리] forecast_lstm 실행 전: 1593.38 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1594.32 MB (변화: +0.95 MB)
[OFLX]   [LSTM] 완료  첫값=2.59e+07 (메모리: 1594.3 MB)
[OFLX]   [Theta] 시작  (메모리: 1594.3 MB)
[메모리] forecast_theta 실행 전: 1594.32 MB
[메모리] forecast_theta 실행 후: 1594.32 MB (변화: +0.00 MB)
[OFLX]   [Theta] 완료  첫값=2.34e+07 (메모리: 1594.3 MB)
[OFLX]   [DB] 88행 저장 완료
[PROGRESS] [ 484/500] ( 96.8%)  >>  RMNI
[RMNI]   40분기 | 2016-03-31 ~ 2025-12-31
[RMNI]   [SARIMA] 시작  (메모리: 1594.3 MB)
[메모리] forecast_sarima 실행 전: 1594.32 MB
[메모리] find_best_sarima_params 실행 전: 1594.32 MB
[메모리] find_best_sarima_params 실행 후: 1594.32 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1594.32 MB (변화: +0.00 MB)
[RMNI]   [SARIMA] 완료  첫값=1.04e+08 (메모리: 1594.3 MB)
[RMNI]   [ETS] 시작  (메모리: 1594.3 MB)
[메모리] forecast_ets 실행 전: 1594.32 MB
[메모리] forecast_ets 실행 후: 1594.33 MB (변화: +0.00 MB)
[RMNI]   [ETS] 완료  첫값=1.05e+08 (메모리: 1594.3 MB)
[RMNI]   [Prophet] 시작  (메모리: 1594.3 MB)

12:30:43 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1594.33 MB

12:30:43 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1594.36 MB (변화: +0.03 MB)
[RMNI]   [Prophet] 완료  첫값=1.08e+08 (메모리: 1594.4 MB)
[RMNI]   [LSTM] 시작  (메모리: 1594.4 MB)
[메모리] forecast_lstm 실행 전: 1594.36 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1594.37 MB (변화: +0.01 MB)
[RMNI]   [LSTM] 완료  첫값=1.07e+08 (메모리: 1594.4 MB)
[RMNI]   [Theta] 시작  (메모리: 1594.4 MB)
[메모리] forecast_theta 실행 전: 1594.37 MB
[메모리] forecast_theta 실행 후: 1594.37 MB (변화: +0.00 MB)
[RMNI]   [Theta] 완료  첫값=1.07e+08 (메모리: 1594.4 MB)
[RMNI]   [DB] 88행 저장 완료
[PROGRESS] [ 485/500] ( 97.0%)  >>  LWAY
[LWAY]   40분기 | 2016-03-31 ~ 2025-12-31
[LWAY]   [SARIMA] 시작  (메모리: 1594.4 MB)
[메모리] forecast_sarima 실행 전: 1594.37 MB
[메모리] find_best_sarima_params 실행 전: 1594.37 MB
[메모리] find_best_sarima_params 실행 후: 1594.37 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1594.37 MB (변화: +0.00 MB)
[LWAY]   [SARIMA] 완료  첫값=5.61e+07 (메모리: 1594.4 MB)
[LWAY]   [ETS] 시작  (메모리: 1594.4 MB)
[메모리] forecast_ets 실행 전: 1594.37 MB
[메모리] forecast_ets 실행 후: 1594.37 MB (변화: +0.00 MB)
[LWAY]   [ETS] 완료  첫값=5.93e+07 (메모리: 1594.4 MB)
[LWAY]   [Prophet] 시작  (메모리: 1594.4 MB)

12:30:59 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1594.37 MB

12:30:59 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1594.38 MB (변화: +0.01 MB)
[LWAY]   [Prophet] 완료  첫값=5.56e+07 (메모리: 1594.4 MB)
[LWAY]   [LSTM] 시작  (메모리: 1594.4 MB)
[메모리] forecast_lstm 실행 전: 1594.38 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.00 MB (변화: -1.38 MB)
[LWAY]   [LSTM] 완료  첫값=6.20e+07 (메모리: 1593.0 MB)
[LWAY]   [Theta] 시작  (메모리: 1593.0 MB)
[메모리] forecast_theta 실행 전: 1593.00 MB
[메모리] forecast_theta 실행 후: 1593.00 MB (변화: +0.00 MB)
[LWAY]   [Theta] 완료  첫값=5.91e+07 (메모리: 1593.0 MB)
[LWAY]   [DB] 88행 저장 완료
[PROGRESS] [ 486/500] ( 97.2%)  >>  SVC
[SVC]   40분기 | 2016-03-31 ~ 2025-12-31
[SVC]   [SARIMA] 시작  (메모리: 1593.0 MB)
[메모리] forecast_sarima 실행 전: 1593.00 MB
[메모리] find_best_sarima_params 실행 전: 1593.00 MB
[메모리] find_best_sarima_params 실행 후: 1593.00 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.00 MB (변화: +0.00 MB)
[SVC]   [SARIMA] 완료  첫값=3.97e+08 (메모리: 1593.0 MB)
[SVC]   [ETS] 시작  (메모리: 1593.0 MB)
[메모리] forecast_ets 실행 전: 1593.00 MB
[메모리] forecast_ets 실행 후: 1593.00 MB (변화: +0.00 MB)
[SVC]   [ETS] 완료  첫값=3.84e+08 (메모리: 1593.0 MB)
[SVC]   [Prophet] 시작  (메모리: 1593.0 MB)
[메모리] forecast_prophet 실행 전: 1593.00 MB

12:31:19 - cmdstanpy - INFO - Chain [1] start processing
12:31:19 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.03 MB (변화: +0.02 MB)
[SVC]   [Prophet] 완료  첫값=4.20e+08 (메모리: 1593.0 MB)
[SVC]   [LSTM] 시작  (메모리: 1593.0 MB)
[메모리] forecast_lstm 실행 전: 1593.03 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1594.00 MB (변화: +0.98 MB)
[SVC]   [LSTM] 완료  첫값=4.37e+08 (메모리: 1594.0 MB)
[SVC]   [Theta] 시작  (메모리: 1594.0 MB)
[메모리] forecast_theta 실행 전: 1594.00 MB
[메모리] forecast_theta 실행 후: 1594.00 MB (변화: +0.00 MB)
[SVC]   [Theta] 완료  첫값=4.09e+08 (메모리: 1594.0 MB)
[SVC]   [DB] 88행 저장 완료
[PROGRESS] [ 487/500] ( 97.4%)  >>  EVI
[EVI]   40분기 | 2016-03-31 ~ 2025-12-31
[EVI]   [SARIMA] 시작  (메모리: 1594.0 MB)
[메모리] forecast_sarima 실행 전: 1594.00 MB
[메모리] find_best_sarima_params 실행 전: 1594.00 MB
[메모리] find_best_sarima_params 실행 후: 1594.00 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1594.00 MB (변화: +0.00 MB)
[EVI]   [SARIMA] 완료  첫값=1.18e+08 (메모리: 1594.0 MB)
[EVI]   [ETS] 시작  (메모리: 1594.0 MB)
[메모리] forecast_ets 실행 전: 1594.00 MB
[메모리] forecast_ets 실행 후: 1594.01 MB (변화: +0.00 MB)
[EVI]   [ETS] 완료  첫값=1.13e+08 (메모리: 1594.0 MB)
[EVI]   [Prophet] 시작  (메모리: 1594.0 MB)

12:31:39 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1594.01 MB

12:31:39 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1594.01 MB (변화: +0.00 MB)
[EVI]   [Prophet] 완료  첫값=1.11e+08 (메모리: 1594.0 MB)
[EVI]   [LSTM] 시작  (메모리: 1594.0 MB)
[메모리] forecast_lstm 실행 전: 1594.01 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.98 MB (변화: -0.03 MB)
[EVI]   [LSTM] 완료  첫값=1.01e+08 (메모리: 1594.0 MB)
[EVI]   [Theta] 시작  (메모리: 1594.0 MB)
[메모리] forecast_theta 실행 전: 1593.98 MB
[메모리] forecast_theta 실행 후: 1593.98 MB (변화: +0.00 MB)
[EVI]   [Theta] 완료  첫값=1.10e+08 (메모리: 1594.0 MB)
[EVI]   [DB] 88행 저장 완료
[PROGRESS] [ 488/500] ( 97.6%)  >>  OOMA
[OOMA]   40분기 | 2016-04-30 ~ 2026-01-31
[OOMA]   [SARIMA] 시작  (메모리: 1594.0 MB)
[메모리] forecast_sarima 실행 전: 1593.98 MB
[메모리] find_best_sarima_params 실행 전: 1593.98 MB
[메모리] find_best_sarima_params 실행 후: 1593.98 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.98 MB (변화: +0.00 MB)
[OOMA]   [SARIMA] 완료  첫값=7.68e+07 (메모리: 1594.0 MB)
[OOMA]   [ETS] 시작  (메모리: 1594.0 MB)
[메모리] forecast_ets 실행 전: 1593.98 MB
[메모리] forecast_ets 실행 후: 1593.98 MB (변화: +0.00 MB)
[OOMA]   [ETS] 완료  첫값=7.37e+07 (메모리: 1594.0 MB)
[OOMA]   [Prophet] 시작  (메모리: 1594.0 MB)

12:31:57 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1593.98 MB

12:31:57 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1594.00 MB (변화: +0.02 MB)
[OOMA]   [Prophet] 완료  첫값=7.25e+07 (메모리: 1594.0 MB)
[OOMA]   [LSTM] 시작  (메모리: 1594.0 MB)
[메모리] forecast_lstm 실행 전: 1594.00 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.98 MB (변화: -0.02 MB)
[OOMA]   [LSTM] 완료  첫값=6.80e+07 (메모리: 1594.0 MB)
[OOMA]   [Theta] 시작  (메모리: 1594.0 MB)
[메모리] forecast_theta 실행 전: 1593.98 MB
[메모리] forecast_theta 실행 후: 1593.98 MB (변화: +0.00 MB)
[OOMA]   [Theta] 완료  첫값=7.38e+07 (메모리: 1594.0 MB)
[OOMA]   [DB] 88행 저장 완료
[PROGRESS] [ 489/500] ( 97.8%)  >>  MLP
[MLP]   40분기 | 2016-03-31 ~ 2025-12-31
[MLP]   [SARIMA] 시작  (메모리: 1594.0 MB)
[메모리] forecast_sarima 실행 전: 1593.98 MB
[메모리] find_best_sarima_params 실행 전: 1593.98 MB
[메모리] find_best_sarima_params 실행 후: 1593.98 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.98 MB (변화: +0.00 MB)
[MLP]   [SARIMA] 완료  첫값=4.69e+06 (메모리: 1594.0 MB)
[MLP]   [ETS] 시작  (메모리: 1594.0 MB)
[메모리] forecast_ets 실행 전: 1593.98 MB
[메모리] forecast_ets 실행 후: 1593.98 MB (변화: +0.00 MB)
[MLP]   [ETS] 완료  첫값=3.93e+06 (메모리: 1594.0 MB)
[MLP]   [Prophet] 시작  (메모리: 1594.0 MB)

12:32:13 - cmdstanpy - INFO - Chain [1] start processing
12:32:14 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1593.98 MB
[메모리] forecast_prophet 실행 후: 1594.00 MB (변화: +0.02 MB)
[MLP]   [Prophet] 완료  첫값=1.95e+06 (메모리: 1594.0 MB)
[MLP]   [LSTM] 시작  (메모리: 1594.0 MB)
[메모리] forecast_lstm 실행 전: 1594.00 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1594.00 MB (변화: +0.00 MB)
[MLP]   [LSTM] 완료  첫값=3.45e+06 (메모리: 1594.0 MB)
[MLP]   [Theta] 시작  (메모리: 1594.0 MB)
[메모리] forecast_theta 실행 전: 1594.00 MB
[메모리] forecast_theta 실행 후: 1594.00 MB (변화: +0.00 MB)
[MLP]   [Theta] 완료  첫값=4.44e+06 (메모리: 1594.0 MB)
[MLP]   [DB] 88행 저장 완료
[PROGRESS] [ 490/500] ( 98.0%)  >>  STRT
[STRT]   40분기 | 2016-03-27 ~ 2025-12-28
[STRT]   [SARIMA] 시작  (메모리: 1594.0 MB)
[메모리] forecast_sarima 실행 전: 1594.00 MB
[메모리] find_best_sarima_params 실행 전: 1594.00 MB
[메모리] find_best_sarima_params 실행 후: 1594.00 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1594.00 MB (변화: +0.00 MB)
[STRT]   [SARIMA] 완료  첫값=1.39e+08 (메모리: 1594.0 MB)
[STRT]   [ETS] 시작  (메모리: 1594.0 MB)
[메모리] forecast_ets 실행 전: 1594.00 MB
[메모리] forecast_ets 실행 후: 1594.00 MB (변화: +0.00 MB)
[STRT]   [ETS] 완료  첫값=1.47e+08 (메모리: 1594.0 MB)
[STRT]   [Prophet] 시작  (메모리: 1594.0 MB)

12:32:27 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1594.00 MB

12:32:27 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1594.02 MB (변화: +0.02 MB)
[STRT]   [Prophet] 완료  첫값=1.39e+08 (메모리: 1594.0 MB)
[STRT]   [LSTM] 시작  (메모리: 1594.0 MB)
[메모리] forecast_lstm 실행 전: 1594.02 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1594.00 MB (변화: -0.02 MB)
[STRT]   [LSTM] 완료  첫값=1.34e+08 (메모리: 1594.0 MB)
[STRT]   [Theta] 시작  (메모리: 1594.0 MB)
[메모리] forecast_theta 실행 전: 1594.00 MB
[메모리] forecast_theta 실행 후: 1594.00 MB (변화: +0.00 MB)
[STRT]   [Theta] 완료  첫값=1.43e+08 (메모리: 1594.0 MB)
[STRT]   [DB] 88행 저장 완료
[PROGRESS] [ 491/500] ( 98.2%)  >>  LFCR
[LFCR]   40분기 | 2016-02-29 ~ 2025-12-31
[LFCR]   [SARIMA] 시작  (메모리: 1594.0 MB)
[메모리] forecast_sarima 실행 전: 1594.00 MB
[메모리] find_best_sarima_params 실행 전: 1594.00 MB
[메모리] find_best_sarima_params 실행 후: 1594.00 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1594.00 MB (변화: +0.00 MB)
[LFCR]   [SARIMA] 완료  첫값=4.10e+07 (메모리: 1594.0 MB)
[LFCR]   [ETS] 시작  (메모리: 1594.0 MB)
[메모리] forecast_ets 실행 전: 1594.00 MB
[메모리] forecast_ets 실행 후: 1594.00 MB (변화: +0.00 MB)
[LFCR]   [ETS] 완료  첫값=4.07e+07 (메모리: 1594.0 MB)
[LFCR]   [Prophet] 시작  (메모리: 1594.0 MB)

12:32:41 - cmdstanpy - INFO - Chain [1] start processing
12:32:41 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 전: 1594.00 MB
[메모리] forecast_prophet 실행 후: 1594.01 MB (변화: +0.01 MB)
[LFCR]   [Prophet] 완료  첫값=1.19e+07 (메모리: 1594.0 MB)
[LFCR]   [LSTM] 시작  (메모리: 1594.0 MB)
[메모리] forecast_lstm 실행 전: 1594.01 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1594.00 MB (변화: -0.00 MB)
[LFCR]   [LSTM] 완료  첫값=2.59e+07 (메모리: 1594.0 MB)
[LFCR]   [Theta] 시작  (메모리: 1594.0 MB)
[메모리] forecast_theta 실행 전: 1594.00 MB
[메모리] forecast_theta 실행 후: 1594.00 MB (변화: +0.00 MB)
[LFCR]   [Theta] 완료  첫값=3.78e+07 (메모리: 1594.0 MB)
[LFCR]   [DB] 88행 저장 완료
[PROGRESS] [ 492/500] ( 98.4%)  >>  PKOH
[PKOH]   40분기 | 2016-03-31 ~ 2025-12-31
[PKOH]   [SARIMA] 시작  (메모리: 1594.0 MB)
[메모리] forecast_sarima 실행 전: 1594.00 MB
[메모리] find_best_sarima_params 실행 전: 1594.00 MB
[메모리] find_best_sarima_params 실행 후: 1594.00 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1594.00 MB (변화: +0.00 MB)
[PKOH]   [SARIMA] 완료  첫값=3.99e+08 (메모리: 1594.0 MB)
[PKOH]   [ETS] 시작  (메모리: 1594.0 MB)
[메모리] forecast_ets 실행 전: 1594.00 MB
[메모리] forecast_ets 실행 후: 1594.01 MB (변화: +0.00 MB)
[PKOH]   [ETS] 완료  첫값=4.29e+08 (메모리: 1594.0 MB)
[PKOH]   [Prophet] 시작  (메모리: 1594.0 MB)

12:33:01 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1594.01 MB

12:33:01 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1594.02 MB (변화: +0.01 MB)
[PKOH]   [Prophet] 완료  첫값=4.02e+08 (메모리: 1594.0 MB)
[PKOH]   [LSTM] 시작  (메모리: 1594.0 MB)
[메모리] forecast_lstm 실행 전: 1594.02 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1594.01 MB (변화: -0.01 MB)
[PKOH]   [LSTM] 완료  첫값=3.85e+08 (메모리: 1594.0 MB)
[PKOH]   [Theta] 시작  (메모리: 1594.0 MB)
[메모리] forecast_theta 실행 전: 1594.01 MB
[메모리] forecast_theta 실행 후: 1594.01 MB (변화: +0.00 MB)
[PKOH]   [Theta] 완료  첫값=4.02e+08 (메모리: 1594.0 MB)
[PKOH]   [DB] 88행 저장 완료
[PROGRESS] [ 493/500] ( 98.6%)  >>  PBYI
[PBYI]   40분기 | 2016-03-31 ~ 2025-12-31
[PBYI]   [SARIMA] 시작  (메모리: 1594.0 MB)
[메모리] forecast_sarima 실행 전: 1594.01 MB
[메모리] find_best_sarima_params 실행 전: 1594.01 MB
[메모리] find_best_sarima_params 실행 후: 1594.01 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1594.01 MB (변화: +0.00 MB)
[PBYI]   [SARIMA] 완료  첫값=4.40e+07 (메모리: 1594.0 MB)
[PBYI]   [ETS] 시작  (메모리: 1594.0 MB)
[메모리] forecast_ets 실행 전: 1594.01 MB
[메모리] forecast_ets 실행 후: 1594.01 MB (변화: +0.00 MB)
[PBYI]   [ETS] 완료  첫값=7.78e+07 (메모리: 1594.0 MB)
[PBYI]   [Prophet] 시작  (메모리: 1594.0 MB)

12:33:13 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1594.01 MB

12:33:13 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1594.04 MB (변화: +0.02 MB)
[PBYI]   [Prophet] 완료  첫값=7.44e+07 (메모리: 1594.0 MB)
[PBYI]   [LSTM] 시작  (메모리: 1594.0 MB)
[메모리] forecast_lstm 실행 전: 1594.04 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1594.08 MB (변화: +0.05 MB)
[PBYI]   [LSTM] 완료  첫값=5.55e+07 (메모리: 1594.1 MB)
[PBYI]   [Theta] 시작  (메모리: 1594.1 MB)
[메모리] forecast_theta 실행 전: 1594.08 MB
[메모리] forecast_theta 실행 후: 1594.08 MB (변화: +0.00 MB)
[PBYI]   [Theta] 완료  첫값=6.68e+07 (메모리: 1594.1 MB)
[PBYI]   [DB] 88행 저장 완료
[PROGRESS] [ 494/500] ( 98.8%)  >>  MPX
[MPX]   40분기 | 2016-03-31 ~ 2025-12-31
[MPX]   [SARIMA] 시작  (메모리: 1594.1 MB)
[메모리] forecast_sarima 실행 전: 1594.08 MB
[메모리] find_best_sarima_params 실행 전: 1594.08 MB
[메모리] find_best_sarima_params 실행 후: 1594.08 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1594.08 MB (변화: +0.00 MB)
[MPX]   [SARIMA] 완료  첫값=6.46e+07 (메모리: 1594.1 MB)
[MPX]   [ETS] 시작  (메모리: 1594.1 MB)
[메모리] forecast_ets 실행 전: 1594.08 MB
[메모리] forecast_ets 실행 후: 1594.09 MB (변화: +0.00 MB)
[MPX]   [ETS] 완료  첫값=7.11e+07 (메모리: 1594.1 MB)
[MPX]   [Prophet] 시작  (메모리: 1594.1 MB)

12:33:28 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1594.09 MB

12:33:29 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1594.11 MB (변화: +0.02 MB)
[MPX]   [Prophet] 완료  첫값=7.58e+07 (메모리: 1594.1 MB)
[MPX]   [LSTM] 시작  (메모리: 1594.1 MB)
[메모리] forecast_lstm 실행 전: 1594.11 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1594.05 MB (변화: -0.05 MB)
[MPX]   [LSTM] 완료  첫값=7.32e+07 (메모리: 1594.1 MB)
[MPX]   [Theta] 시작  (메모리: 1594.1 MB)
[메모리] forecast_theta 실행 전: 1594.05 MB
[메모리] forecast_theta 실행 후: 1594.05 MB (변화: +0.00 MB)
[MPX]   [Theta] 완료  첫값=6.22e+07 (메모리: 1594.1 MB)
[MPX]   [DB] 88행 저장 완료
[PROGRESS] [ 495/500] ( 99.0%)  >>  MIXT
[MIXT]   40분기 | 2014-03-31 ~ 2023-12-31
[MIXT]   [SARIMA] 시작  (메모리: 1594.1 MB)
[메모리] forecast_sarima 실행 전: 1594.05 MB
[메모리] find_best_sarima_params 실행 전: 1594.05 MB
[메모리] find_best_sarima_params 실행 후: 1594.05 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1594.05 MB (변화: +0.00 MB)
[MIXT]   [SARIMA] 완료  첫값=3.87e+07 (메모리: 1594.1 MB)
[MIXT]   [ETS] 시작  (메모리: 1594.1 MB)
[메모리] forecast_ets 실행 전: 1594.05 MB
[메모리] forecast_ets 실행 후: 1594.05 MB (변화: +0.00 MB)
[MIXT]   [ETS] 완료  첫값=3.92e+07 (메모리: 1594.1 MB)
[MIXT]   [Prophet] 시작  (메모리: 1594.1 MB)

12:33:48 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1594.05 MB

12:33:48 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1594.07 MB (변화: +0.02 MB)
[MIXT]   [Prophet] 완료  첫값=3.86e+07 (메모리: 1594.1 MB)
[MIXT]   [LSTM] 시작  (메모리: 1594.1 MB)
[메모리] forecast_lstm 실행 전: 1594.07 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1594.02 MB (변화: -0.05 MB)
[MIXT]   [LSTM] 완료  첫값=3.61e+07 (메모리: 1594.0 MB)
[MIXT]   [Theta] 시작  (메모리: 1594.0 MB)
[메모리] forecast_theta 실행 전: 1594.02 MB
[메모리] forecast_theta 실행 후: 1594.02 MB (변화: +0.00 MB)
[MIXT]   [Theta] 완료  첫값=3.92e+07 (메모리: 1594.0 MB)
[MIXT]   [DB] 88행 저장 완료
[PROGRESS] [ 496/500] ( 99.2%)  >>  DENN
[DENN]   40분기 | 2015-12-31 ~ 2025-09-24
[DENN]   [SARIMA] 시작  (메모리: 1594.0 MB)
[메모리] forecast_sarima 실행 전: 1594.02 MB
[메모리] find_best_sarima_params 실행 전: 1594.02 MB
[메모리] find_best_sarima_params 실행 후: 1594.02 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1594.02 MB (변화: +0.00 MB)
[DENN]   [SARIMA] 완료  첫값=1.13e+08 (메모리: 1594.0 MB)
[DENN]   [ETS] 시작  (메모리: 1594.0 MB)
[메모리] forecast_ets 실행 전: 1594.02 MB
[메모리] forecast_ets 실행 후: 1594.02 MB (변화: +0.00 MB)
[DENN]   [ETS] 완료  첫값=1.17e+08 (메모리: 1594.0 MB)
[DENN]   [Prophet] 시작  (메모리: 1594.0 MB)

12:34:03 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1594.02 MB

12:34:03 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1594.32 MB (변화: +0.29 MB)
[DENN]   [Prophet] 완료  첫값=1.04e+08 (메모리: 1594.3 MB)
[DENN]   [LSTM] 시작  (메모리: 1594.3 MB)
[메모리] forecast_lstm 실행 전: 1594.32 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.59 MB (변화: -0.73 MB)
[DENN]   [LSTM] 완료  첫값=1.09e+08 (메모리: 1593.6 MB)
[DENN]   [Theta] 시작  (메모리: 1593.6 MB)
[메모리] forecast_theta 실행 전: 1593.59 MB
[메모리] forecast_theta 실행 후: 1593.59 MB (변화: +0.00 MB)
[DENN]   [Theta] 완료  첫값=1.14e+08 (메모리: 1593.6 MB)
[DENN]   [DB] 88행 저장 완료
[PROGRESS] [ 497/500] ( 99.4%)  >>  NEO
[NEO]   40분기 | 2016-03-31 ~ 2025-12-31
[NEO]   [SARIMA] 시작  (메모리: 1593.6 MB)
[메모리] forecast_sarima 실행 전: 1593.59 MB
[메모리] find_best_sarima_params 실행 전: 1593.59 MB
[메모리] find_best_sarima_params 실행 후: 1593.59 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.59 MB (변화: +0.00 MB)
[NEO]   [SARIMA] 완료  첫값=1.96e+08 (메모리: 1593.6 MB)
[NEO]   [ETS] 시작  (메모리: 1593.6 MB)
[메모리] forecast_ets 실행 전: 1593.59 MB
[메모리] forecast_ets 실행 후: 1593.59 MB (변화: +0.00 MB)
[NEO]   [ETS] 완료  첫값=1.92e+08 (메모리: 1593.6 MB)
[NEO]   [Prophet] 시작  (메모리: 1593.6 MB)

12:34:24 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1593.59 MB

12:34:24 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.61 MB (변화: +0.02 MB)
[NEO]   [Prophet] 완료  첫값=1.86e+08 (메모리: 1593.6 MB)
[NEO]   [LSTM] 시작  (메모리: 1593.6 MB)
[메모리] forecast_lstm 실행 전: 1593.61 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1593.46 MB (변화: -0.15 MB)
[NEO]   [LSTM] 완료  첫값=1.78e+08 (메모리: 1593.5 MB)
[NEO]   [Theta] 시작  (메모리: 1593.5 MB)
[메모리] forecast_theta 실행 전: 1593.46 MB
[메모리] forecast_theta 실행 후: 1593.46 MB (변화: +0.00 MB)
[NEO]   [Theta] 완료  첫값=1.87e+08 (메모리: 1593.5 MB)
[NEO]   [DB] 88행 저장 완료
[PROGRESS] [ 498/500] ( 99.6%)  >>  AMRN
[AMRN]   40분기 | 2016-03-31 ~ 2025-12-31
[AMRN]   [SARIMA] 시작  (메모리: 1593.5 MB)
[메모리] forecast_sarima 실행 전: 1593.46 MB
[메모리] find_best_sarima_params 실행 전: 1593.46 MB
[메모리] find_best_sarima_params 실행 후: 1593.46 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1593.46 MB (변화: +0.00 MB)
[AMRN]   [SARIMA] 완료  첫값=2.67e+07 (메모리: 1593.5 MB)
[AMRN]   [ETS] 시작  (메모리: 1593.5 MB)
[메모리] forecast_ets 실행 전: 1593.46 MB
[메모리] forecast_ets 실행 후: 1593.46 MB (변화: +0.00 MB)
[AMRN]   [ETS] 완료  첫값=1.89e+07 (메모리: 1593.5 MB)
[AMRN]   [Prophet] 시작  (메모리: 1593.5 MB)

12:34:39 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1593.46 MB

12:34:39 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1593.49 MB (변화: +0.03 MB)
[AMRN]   [Prophet] 완료  첫값=8.95e+07 (메모리: 1593.5 MB)
[AMRN]   [LSTM] 시작  (메모리: 1593.5 MB)
[메모리] forecast_lstm 실행 전: 1593.49 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1594.46 MB (변화: +0.97 MB)
[AMRN]   [LSTM] 완료  첫값=8.57e+07 (메모리: 1594.5 MB)
[AMRN]   [Theta] 시작  (메모리: 1594.5 MB)
[메모리] forecast_theta 실행 전: 1594.46 MB
[메모리] forecast_theta 실행 후: 1594.46 MB (변화: +0.00 MB)
[AMRN]   [Theta] 완료  첫값=1.65e+07 (메모리: 1594.5 MB)
[AMRN]   [DB] 88행 저장 완료
[PROGRESS] [ 499/500] ( 99.8%)  >>  LOCO
[LOCO]   40분기 | 2016-03-30 ~ 2025-12-31
[LOCO]   [SARIMA] 시작  (메모리: 1594.5 MB)
[메모리] forecast_sarima 실행 전: 1594.46 MB
[메모리] find_best_sarima_params 실행 전: 1594.46 MB
[메모리] find_best_sarima_params 실행 후: 1594.46 MB (변화: +0.00 MB)
[메모리] forecast_sarima 실행 후: 1594.46 MB (변화: +0.00 MB)
[LOCO]   [SARIMA] 완료  첫값=1.26e+08 (메모리: 1594.5 MB)
[LOCO]   [ETS] 시작  (메모리: 1594.5 MB)
[메모리] forecast_ets 실행 전: 1594.46 MB
[메모리] forecast_ets 실행 후: 1594.46 MB (변화: +0.00 MB)
[LOCO]   [ETS] 완료  첫값=1.23e+08 (메모리: 1594.5 MB)
[LOCO]   [Prophet] 시작  (메모리: 1594.5 MB)

12:34:59 - cmdstanpy - INFO - Chain [1] start processing

[메모리] forecast_prophet 실행 전: 1594.46 MB

12:34:59 - cmdstanpy - INFO - Chain [1] done processing

[메모리] forecast_prophet 실행 후: 1594.47 MB (변화: +0.00 MB)
[LOCO]   [Prophet] 완료  첫값=1.24e+08 (메모리: 1594.5 MB)
[LOCO]   [LSTM] 시작  (메모리: 1594.5 MB)
[메모리] forecast_lstm 실행 전: 1594.47 MB
WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
[메모리] forecast_lstm 실행 후: 1594.46 MB (변화: -0.01 MB)
[LOCO]   [LSTM] 완료  첫값=1.19e+08 (메모리: 1594.5 MB)
[LOCO]   [Theta] 시작  (메모리: 1594.5 MB)
[메모리] forecast_theta 실행 전: 1594.46 MB
[메모리] forecast_theta 실행 후: 1594.46 MB (변화: +0.00 MB)
[LOCO]   [Theta] 완료  첫값=1.24e+08 (메모리: 1594.5 MB)
[LOCO]   [DB] 88행 저장 완료
[PROGRESS] [ 500/500] (100.0%)  >>  BNTC
[BNTC] [NEG-SKIP] [BNTC] 'sale' 음수 매출 존재 → 예측 제외 (음수 분기: [datetime.date(2020, 6, 30)])
[BATCH] ======================================================================
[BATCH] 완료 | 성공: 443  데이터스킵: 19  음수제외: 38  오류: 0  합계: 500
[BATCH] 데이터스킵  : ['CCEC', 'MBX', 'SWIR', 'EZT', 'PVLA', 'WBI', 'LOT', 'HDL', 'TCRZ', 'BTX', 'RZLV', 'BGM', 'VOLT', 'AIC', 'SGOC', 'ODV', 'KOR', 'FVR', 'SMC']
[BATCH] 음수매출제외 : ['ORC', 'BLFS', 'VVI', 'PMT', 'CIM', 'CMP', 'GLYC', 'MFA', 'PRSU', 'ALBO', 'LIND', 'VERB', 'OMER', 'GAU', 'NEWP', 'ABUS', 'MTA', 'RWT', 'GYRE', 'ATHM', 'STAR', 'NYMT', 'NR', 'IVR', 'TBN', 'STKL', 'DBVT', 'OCGN', 'IMMP', 'CD', 'DMAC', 'LAAC', 'PTSI', 'PTN', 'NBY', 'RC', 'QIWI', 'BNTC']
[BATCH] ======================================================================

## Cell 14 · 저장 결과 조회

배치 완료 후 DB 에 저장된 결과를 확인합니다.

In [15]:
# ── 오늘 예측된 티커 × 모델별 요약 ──────────────────────────
with engine.connect() as conn:
    summary_df = pd.read_sql(
        text(f"""
            SELECT
                ticker,
                item,
                model,
                MIN(date)  AS date_from,
                MAX(date)  AS date_to,
                COUNT(*)   AS row_count,
                forecast_date
            FROM   `{DEST_TABLE}`
            WHERE  forecast_date = :fd
            GROUP  BY ticker, item, model, forecast_date
            ORDER  BY ticker, model
        """),
        conn,
        params={"fd": FORECAST_DATE},
    )

print(f"[오늘({FORECAST_DATE}) 예측 저장 결과: {len(summary_df)}건]")
display(summary_df)

[오늘(2026-04-03) 예측 저장 결과: 6732건]

     ticker  item     model   date_from     date_to  row_count forecast_date
0         A  sale    actual  2016-04-30  2026-01-31         40    2026-04-03
1         A  sale  Ensemble  2026-03-31  2027-12-31          8    2026-04-03
2         A  sale       ETS  2026-03-31  2027-12-31          8    2026-04-03
3         A  sale      LSTM  2026-03-31  2027-12-31          8    2026-04-03
4         A  sale   Prophet  2026-03-31  2027-12-31          8    2026-04-03
...     ...   ...       ...         ...         ...        ...           ...
6727    ZWS  sale       ETS  2026-03-31  2027-12-31          8    2026-04-03
6728    ZWS  sale      LSTM  2026-03-31  2027-12-31          8    2026-04-03
6729    ZWS  sale   Prophet  2026-03-31  2027-12-31          8    2026-04-03
6730    ZWS  sale    SARIMA  2026-03-31  2027-12-31          8    2026-04-03
6731    ZWS  sale     Theta  2026-03-31  2027-12-31          8    2026-04-03

[6732 rows x 7 columns]

In [16]:
# ── 전체 DB 저장 통계 ─────────────────────────────────────
with engine.connect() as conn:
    total_stat = pd.read_sql(
        text(f"""
            SELECT
                forecast_date,
                COUNT(DISTINCT ticker) AS ticker_cnt,
                COUNT(DISTINCT model)  AS model_cnt,
                COUNT(*)               AS total_rows
            FROM   `{DEST_TABLE}`
            GROUP  BY forecast_date
            ORDER  BY forecast_date DESC
            LIMIT  10
        """),
        conn,
    )

print("[전체 DB 저장 현황 (최근 10개 예측일)]")
display(total_stat)

[전체 DB 저장 현황 (최근 10개 예측일)]

  forecast_date  ticker_cnt  model_cnt  total_rows
0    2026-04-03         962          7       84616
1    2026-03-31         731          7       65721
2    2026-03-30         964          7       87241

## Cell 15 · 오염 데이터 삭제 & 재예측

### 왜 필요한가?
기존 예측은 **FMP 중복 데이터(같은 실적이 다른 분기 날짜에 저장된 행)**를  
그대로 포함한 시계열로 예측했습니다.  
예) `date_month=2025-12`인 실적이 `2025-12-31`과 `2026-03-31` 두 날짜에 저장  
→ 시계열 마지막에 **가짜 분기가 추가**되어 예측 기준점이 한 분기 뒤로 밀림

### 처리 순서
1. **Cell 15-A** : 삭제 대상 확인 (실제 삭제 전 확인용)
2. **Cell 15-B** : `us_revenue_forecast_data` 에서 기존 예측 데이터 삭제
3. **Cell 13** : 수정된 `fetch_financial_series` 로 재예측 실행

> ⚠️ 특정 ticker 만 재예측하려면 `RUN_TICKERS = ["AAPL", ...]` 로 지정하세요.

In [23]:
# # ══════════════════════════════════════════════════════
# #  Cell 15-A : 삭제 대상 확인 (읽기 전용 — 실제 삭제 안 함)
# # ══════════════════════════════════════════════════════
#
# # 삭제할 forecast_date 지정
# # None → DEST_TABLE 전체 삭제 / 문자열 → 특정 날짜만
# DELETE_FORECAST_DATE = None    # 예: "2026-03-25"  또는 None (전체)
# DELETE_TICKERS       = None    # 예: ["AAPL", "MSFT"]  또는 None (전체)
#
# # ── 삭제 대상 row 수 확인 ─────────────────────────────
# with engine.connect() as conn:
#     cond_parts = []
#     cond_params = {}
#     if DELETE_FORECAST_DATE:
#         cond_parts.append("forecast_date = :fd")
#         cond_params["fd"] = DELETE_FORECAST_DATE
#     if DELETE_TICKERS:
#         in_clause = ", ".join([f":t{i}" for i in range(len(DELETE_TICKERS))])
#         cond_parts.append(f"ticker IN ({in_clause})")
#         for i, t in enumerate(DELETE_TICKERS):
#             cond_params[f"t{i}"] = t
#
#     where_sql = ("WHERE " + " AND ".join(cond_parts)) if cond_parts else ""
#     check_sql = text(f"SELECT COUNT(*) AS cnt FROM `{DEST_TABLE}` {where_sql}")
#     row = conn.execute(check_sql, cond_params).fetchone()
#     cnt = row[0] if row else 0
#
# print(f"[확인] 삭제 대상 조건:")
# print(f"       forecast_date = {DELETE_FORECAST_DATE or '전체'}")
# print(f"       tickers       = {DELETE_TICKERS or '전체'}")
# print(f"       삭제 예정 행 수: {cnt:,}행")
# print()
# print("실제 삭제하려면 Cell 15-B 를 실행하세요.")

In [17]:
# # ══════════════════════════════════════════════════════
# #  Cell 15-B : 실제 삭제 실행
# #  ⚠️  되돌릴 수 없습니다. Cell 15-A 확인 후 실행하세요.
# # ══════════════════════════════════════════════════════
#
# # Cell 15-A 와 동일한 조건 사용
# with engine.begin() as conn:
#     del_parts = []
#     del_params = {}
#     if DELETE_FORECAST_DATE:
#         del_parts.append("forecast_date = :fd")
#         del_params["fd"] = DELETE_FORECAST_DATE
#     if DELETE_TICKERS:
#         in_clause = ", ".join([f":t{i}" for i in range(len(DELETE_TICKERS))])
#         del_parts.append(f"ticker IN ({in_clause})")
#         for i, t in enumerate(DELETE_TICKERS):
#             del_params[f"t{i}"] = t
#
#     where_sql = ("WHERE " + " AND ".join(del_parts)) if del_parts else ""
#     delete_sql = text(f"DELETE FROM `{DEST_TABLE}` {where_sql}")
#     result = conn.execute(delete_sql, del_params)
#
# print(f"[완료] 삭제된 행 수: {result.rowcount:,}행")
# print()
# print("다음 단계: Cell 13 을 실행해 재예측을 진행하세요.")
# print("  → fetch_financial_series 가 수정됐으므로 정확한 시계열로 재예측됩니다.")